<a id='top'></a>

# Webscraping of TransferMarkt Data
##### Notebook to scrape raw data from [TransferMarkt](https://www.transfermarkt.co.uk/) using [Beautifulsoup](https://pypi.org/project/beautifulsoup4/).

### By [Edd Webster](https://www.twitter.com/eddwebster)
Notebook first written: 13/09/2020<br>
Notebook last updated: 04/12/2020

![title](../../img/transfermarkt-logo-banner.png)

Click [here](#section5) to jump straight to the Exploratory Data Analysis section and skip the [Task Brief](#section2), [Data Sources](#section3), and [Data Engineering](#section4) sections. Or click [here](#section6) to jump straight to the Conclusion.

___

<a id='sectionintro'></a>

## <a id='import_libraries'>Introduction</a>
This notebook scrapes data from [TransferMarkt](https://www.transfermarkt.co.uk/) using [Beautifulsoup](https://pypi.org/project/beautifulsoup4/) and the [Tyrone Mings web scraper](https://github.com/FCrSTATS/tyrone_mings) by [FCrSTATS](https://twitter.com/FC_rstats). This landed data is then manipulated as DataFrames using [pandas](http://pandas.pydata.org/).

For more information about this notebook and the author, I'm available through all the following channels:
*    [eddwebster.com](https://www.eddwebster.com/);
*    edd.j.webster@gmail.com;
*    [@eddwebster](https://www.twitter.com/eddwebster);
*    [linkedin.com/in/eddwebster](https://www.linkedin.com/in/eddwebster/);
*    [github/eddwebster](https://github.com/eddwebster/);
*    [public.tableau.com/profile/edd.webster](https://public.tableau.com/profile/edd.webster);
*    [kaggle.com/eddwebster](https://www.kaggle.com/eddwebster); and
*    [hackerrank.com/eddwebster](https://www.hackerrank.com/eddwebster).

![title](../../img/fifa21eddwebsterbanner.png)

The accompanying GitHub repository for this notebook can be found [here](https://github.com/eddwebster/football_analytics) and a static version of this notebook can be found [here](https://nbviewer.jupyter.org/github/eddwebster/football_analytics/blob/master/notebooks/A%29%20Web%20Scraping/TransferMarkt%20Web%20Scraping%20and%20Parsing.ipynb).

___

<a id='sectioncontents'></a>

## <a id='notebook_contents'>Notebook Contents</a>
1.    [Notebook Dependencies](#section1)<br>
2.    [Project Brief](#section2)<br>
3.    [Data Sources](#section3)<br>
      1.    [Introduction](#section3.1)<br>
      2.    [Data Dictionary](#section3.2)<br>
      3.    [Creating the DataFrame](#section3.3)<br>
      4.    [Initial Data Handling](#section3.4)<br>
      5.    [Export the Raw DataFrame](#section3.5)<br>         
4.    [Data Engineering](#section4)<br>
      1.    [Introduction](#section4.1)<br>
      2.    [Columns of Interest](#section4.2)<br>
      3.    [String Cleaning](#section4.3)<br>
      4.    [Converting Data Types](#section4.4)<br>
      5.    [Export the Engineered DataFrame](#section4.5)<br>
5.    [Exploratory Data Analysis (EDA)](#section5)<br>
      1.    [...](#section5.1)<br>
      2.    [...](#section5.2)<br>
      3.    [...](#section5.3)<br>
6.    [Summary](#section6)<br>
7.    [Next Steps](#section7)<br>
8.    [Bibliography](#section8)<br>

___

<a id='section1'></a>

## <a id='#section1'>1. Notebook Dependencies</a>

This notebook was written using [Python 3](https://docs.python.org/3.7/) and requires the following libraries:
*    [`Jupyter notebooks`](https://jupyter.org/) for this notebook environment with which this project is presented;
*    [`NumPy`](http://www.numpy.org/) for multidimensional array computing;
*    [`pandas`](http://pandas.pydata.org/) for data analysis and manipulation;
*    [`Beautifulsoup`](https://pypi.org/project/beautifulsoup4/) for web scraping; and
*    [`matplotlib`](https://matplotlib.org/contents.html?v=20200411155018) for data visualisations;

All packages used for this notebook except for BeautifulSoup can be obtained by downloading and installing the [Conda](https://anaconda.org/anaconda/conda) distribution, available on all platforms (Windows, Linux and Mac OSX). Step-by-step guides on how to install Anaconda can be found for Windows [here](https://medium.com/@GalarnykMichael/install-python-on-windows-anaconda-c63c7c3d1444) and Mac [here](https://medium.com/@GalarnykMichael/install-python-on-mac-anaconda-ccd9f2014072), as well as in the Anaconda documentation itself [here](https://docs.anaconda.com/anaconda/install/).

### Import Libraries and Modules

In [1]:
# Python ≥3.5 (ideally)
import platform
import sys, getopt
assert sys.version_info >= (3, 5)
import csv

# Import Dependencies
%matplotlib inline

# Math Operations
import numpy as np
from math import pi

# Datetime
import datetime
from datetime import date
import time

# Data Preprocessing
import pandas as pd
import os
import re
import random
from io import BytesIO
from pathlib import Path

# Reading directories
import glob
import os
from os.path import basename

# Flatten lists
from functools import reduce

# Working with JSON
import json
from pandas.io.json import json_normalize

# Web Scraping
import requests
from bs4 import BeautifulSoup
import re

# APIs
from tyrone_mings import * 

# Fuzzy Matching - Record Linkage
import recordlinkage
import jellyfish
import numexpr as ne

# Data Visualisation
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('seaborn-whitegrid')
import missingno as msno

# Progress Bar
from tqdm import tqdm

# Display in Jupyter
from IPython.display import Image, YouTubeVideo
from IPython.core.display import HTML

# Ignore Warnings
import warnings
warnings.filterwarnings(action="ignore", message="^internal gelsd")

print('Setup Complete')

Setup Complete

In [2]:
# Python / module versions used here for reference
print('Python: {}'.format(platform.python_version()))
print('NumPy: {}'.format(np.__version__))
print('pandas: {}'.format(pd.__version__))
print('matplotlib: {}'.format(mpl.__version__))
print('Seaborn: {}'.format(sns.__version__))

Python: 3.7.6
NumPy: 1.18.1
pandas: 1.0.1
matplotlib: 3.1.3
Seaborn: 0.10.0

### Defined Variables

In [3]:
# Define today's date
today = datetime.datetime.now().strftime('%d/%m/%Y').replace('/', '')

### Defined Filepaths

In [4]:
# Set up initial paths to subfolders
base_dir = os.path.join('..', '..', )
data_dir = os.path.join(base_dir, 'data')
data_dir_tm = os.path.join(base_dir, 'data', 'tm')
img_dir = os.path.join(base_dir, 'img')
fig_dir = os.path.join(base_dir, 'img', 'fig')
video_dir = os.path.join(base_dir, 'video')

### Notebook Settings

In [5]:
pd.set_option('display.max_columns', None)

---

<a id='section2'></a>

## <a id='#section2'>2. Project Brief</a>
This notebook scrapes data from [TransferMarkt](https://www.transfermarkt.co.uk/) using [Beautifulsoup](https://pypi.org/project/beautifulsoup4/) and the [Tyrone Mings web scraper](https://github.com/FCrSTATS/tyrone_mings) by [FCrSTATS](https://twitter.com/FC_rstats). This landed data is then manipulated as DataFrames using [pandas](http://pandas.pydata.org/).

The data of player values produced in this notebook is exported to CSV. This data can be further analysed in Python, joined to other datasets, or explored using dashboarding tools such as Tableau or PowerBI, or explores in a spreadsheet such as Microsoft Excel or Google Sheets.

---

<a id='section3'></a>

## <a id='#section3'>3. Data Sources</a>

### <a id='#section3.1'>3.1. Introduction</a>
[TransferMarkt](https://www.transfermarkt.co.uk/) is a German-based website owned by [Axel Springer](https://www.axelspringer.com/en/) and is the leading website for the football transfer market. The website posts football related data, including: scores and results, football news, transfer rumours, and most usefully for us - calculated estimates ofthe market values for teams and individual players.

To read more about how these estimations are made, [Beyond crowd judgments: Data-driven estimation of market value in association football](https://www.sciencedirect.com/science/article/pii/S0377221717304332) by Oliver Müllera, Alexander Simons, and Markus Weinmann does an excellent job of explaining how the estimations are made and their level of accuracy.

Before conducting our EDA, the data needs to be imported as a DataFrame in the Data Sources section [Section 3](#section3) and cleaned in the Data Engineering section [Section 4](#section4).

We'll be using the [pandas](http://pandas.pydata.org/) library to import our data to this workbook as a DataFrame.

### <a id='#section3.2'>3.2. Data Dictionaries</a>
The [TransferMarkt](https://www.transfermarkt.co.uk/) dataset has six features (columns) with the following definitions and data types:

| Feature     | Data type    |
|------|-----|
| `position_number`    | object     |
| `position_description`    | object     |
| `name`    | object     |
| `dob`    | object     |
| `nationality`    | object     |
| `value`    | object     |

### <a id='#section3.3'>3.3. Creating the DataFrame - scraping the data</a>

#### <a id='#section3.3.1.'>3.3.1. League Codes</a>
Before scraping data from [TransferMarkt](https://www.transfermarkt.co.uk/), we need to look at the leagues in England that we wish to scrape.

The [Tyrone Mings web scraper](https://github.com/FCrSTATS/tyrone_mings) by [FCrSTATS](https://github.com/FCrSTATS) for [TransferMarkt](https://www.transfermarkt.co.uk/) is made up of two parts:
1.    In the first part, the scraper takes the webpages for each of the individual leagues  e.g. the Championship, and extract the hyperlinks to the pages of all the individual teams in the league table.
2.    In the second part the script, the webscraper uses the list of invidual teams hyperlinks collected in part 1 to then collect the hyperlinks for each of the players for those teams. From this, the scraper can then extract the information we need for each of these players. This information is downloaded in two parts - bio and status. This is then joined together using the player_id.

This information collected for all the players is converted to a [pandas](http://pandas.pydata.org/) DataFrame from which we can view and manipulate the data.

An example webpage for a football league is the following: https://www.transfermarkt.co.uk/jumplist/startseite/wettbewerb/GB1/plus/?saison_id=2019. As we can see, between the subdirectory path of `'/wettbewerb/'` and the `'/plus/'`, there is a 3 or 4 digit code. For The Premier League, the code is GB1.

In order to scrape the webpages from [TransferMarkt](https://www.transfermarkt.co.uk/), the codes the leagues we require, need to be recorded from [TransferMarkt](https://www.transfermarkt.co.uk/). The following leagues are all the leagues that feature on the latest FBref 'Big 5' European leagues dataset, the EFL dataset, and the the [FIFA 21 player dataset](https://www.kaggle.com/stefanoleone992/fifa-21-complete-player-dataset), all of which are datasets for which this [TransferMarkt](https://www.transfermarkt.co.uk/) data will be subsequently matched to.

| League Name on FIFA    | Country    | Corresponding [TransferMarkt](https://www.transfermarkt.co.uk/) League Code    |
|------|-----|-----|
| Österreichische Fußball-Bundesliga    | Austria    | A1    |
| SAF    | Argentina    | AR1N    |
| Hyundai A-League    | Australia    | AUS1    |
| Belgium Pro League    | Belgium    | BE1    |
| Raiffeisen Super League    | Switzerland    | C1    |
| Campeonato Scotiabank    | Chile    | CLPD    |
| Liga Dimayor    | Colombia    | COL1    |
| CSL    | China    | CSL    |
| Superliga    | Denmark    | DK1    |
| LaLiga Santander    | Spain    | ES1    |
| LaLiga 1 I 2 I 3    | Spain    | ES2    |
| Finnliiga    | Finland    | FI1    |
| Ligue 1 Conforama    | France    | FR1    |
| Domino’s Ligue 2    | France    | FR2    |
| Premier League    | England    | GB1    |
| EFL Championship    | England    | GB2    |
| EFL League One    | England    | GB3    |
| EFL League Two    | England    | GB4    |
| Hellas Liga    | Greece    | GR1    |
| SSE Airtricity League    | Ireland    | IR1    |
| Serie A TIM    | Italy    | IT1    |
| Calcio B    | Italy    | IT2    |
| Meiji Yasuda J1 League    | Japan    | JAP1    |
| Croatia Liga    | Croatia    | KR1    |
| Bundesliga    | Germany    | L1    |
| Bundesliga 2    | Germany    | L2    |
| 3. Liga    | Germany    | L3    |
| LIGA Bancomer MX    | Mexico    | MEX1    |
| Major League Soccer    | United States    | MLS1    |
| Eredivisie    | Netherlands    | NL1    |
| Eliteserien    | Norway    | NO1    |
| Ekstraklasa    | Poland    | PL1    |
| Liga NOS    | Portugal    | PO1    |
| Romania Liga I    | Romania    | RO1    |
| K LEAGUE Classic    | South Korea    | RSK1    |
| League of Russia    | Russia    | RU1    |
| Saudi Professional    | League	Saudi Arabia    | SA1    |
| Scottish Premiership    | Scotland    | SC1    |
| Allsvenskan    | Sweden    | SE1    |
| South African FL    | South Africa    | SFA1    |
| Süper Lig    | Turkey    | TR1    |
| Česká Liga    | Czech Republic    | TS1    |
| UAE Gulf League    | United Arab Emirates    | UAE1    |
| Ukraine Liga    | Ukraine    | UKR1    |


Unfortunately, on writing this notebook, the following leagues are that is present on FIFA but cannot scraped from [TransferMarkt](https://www.transfermarkt.co.uk/) with the script and will and therefore not be included in the dataset.

| League Name on FIFA    | Country    | Corresponding [TransferMarkt](https://www.transfermarkt.co.uk/) League Code    |
|------|-----|-----|
| League of Russia    | Russia    | RU1    |

#### <a id='#section3.3.2.'>3.3.2. Define Season and Leagues to Scrape</a>

In [6]:
# Define variables and lists

## Define season
season = '2020'    # '2020' for the 20/21 season

## Define list of leagues for players to scrape
lst_leagues = ['A1',
               'AR1N',
               'AUS1',
               'BE1',
               'C1',
               'CLPD',
               'COL1',
               'CSL',
               'DK1',
               'ES1',
               'ES2',
               'FI1',
               'FR1',
               'FR2',
               'GB1',
               'GB2',
               'GB3',
               'GB4',
               'GR1',
               'IR1',
               'IT1',
               'IT2',
               'JAP1',
               'KR1',
               'L1',
               'L2',
               'L3',
               'MEX1',
               'MLS1',
               'NL1',
               'NO1',
               'PL1',
               'PO1',
               'RO1',
               'RSK1',
               'RU1',
               'SA1',
               'SC1',
               'SE1',
               'SFA1',
               'TR1',
               'TS1',
               'UAE1',
               'UKR1'
              ]

In [7]:
# Create 'Full Season' and 'Short Season' strings

## Full season
full_season_string = str(int(season)) + '/' + str(int(season) + 1)

## Short season
short_season_string = str((str(int(season))[-2:]) + (str(int(season) + 1)[-2:]))

In [8]:
full_season_string

'2020/2021'

In [9]:
short_season_string

'2021'

#### <a id='#section3.3.3.'>3.3.3. Player URLs</a>

In [10]:
# Run this script to download all the URLs for the players of interest from TransferMarkt

## Start timer
tic = datetime.datetime.now()

## Create empty list
lst_player_urls = []

## Print time scraping started
print(f'Scraping started at: {tic}')

## Scrape information for each player
for league in lst_leagues:
    try:
        lst_output = get_player_urls_from_league_page(f'https://www.transfermarkt.co.uk/championship/startseite/wettbewerb/{league}/plus/?saison_id={season}', verbose=True)
        lst_player_urls.append(lst_output)
        print(f'All player URLs for the {league} league appended.')
    except:
        pass

## End timer
toc = datetime.datetime.now()

## Print time scraping ended
print(f'Scraping ended at: {toc}')

## Flatten nested list into a single list
lst_player_urls = reduce(lambda x,y: x+y, lst_player_urls)

## No. URLs i.e. players
len_player_urls = len(lst_player_urls)

## Calculate time take
total_time = (toc-tic).total_seconds()
print(f'Time taken to scrape the {len_player_urls:,} player urls for the {full_season_string} season is: {total_time/60:0.2f} minutes.')

Scraping started at: 2020-12-07 14:50:35.925099
fk austria wien players added
fc admira wacker modling players added
red bull salzburg players added
wolfsberger ac players added
skn st polten players added
sk rapid wien players added
sk sturm graz players added
sc rheindorf altach players added
wsg wattens players added
lask linz players added
tsv hartberg players added
sv ried players added
All player URLs for the A1 league appended.
club atletico san lorenzo de almagro players added
club atletico banfield players added
club atletico central cordoba sde  players added
club deportivo godoy cruz players added
ca independiente de avellaneda players added
club atletico aldosivi mdp  players added
club atletico colon santa fe  players added
club atletico lanus players added
club atletico huracan players added
estudiantes de la plata players added
club atletico boca juniors players added
club atletico tucuman players added
club atletico river plate players added
club atletico newells old boys players added
racing club de avellaneda players added
defensa y justicia players added
club atletico velez sarsfield players added
arsenal de sarandi fc players added
ca union santa fe players added
club atletico rosario central players added
talleres de cordoba ca players added
club atletico patronato players added
argentinos juniors players added
club de gimnasia y esgrima la plata players added
All player URLs for the AR1N league appended.
macarthur south west sydney players added
adelaide united players added
sydney fc players added
brisbane roar players added
western sydney wanderers players added
central coast mariners players added
melbourne victory players added
wellington phoenix players added
perth glory players added
melbourne heart fc players added
western melbourne group players added
newcastle united jets players added
All player URLs for the AUS1 league appended.
standard luttich players added
kv mechelen players added
royal fc antwerpen players added
oud heverlee leuven players added
rsc anderlecht players added
kas eupen players added
waasland beveren players added
kaa gent players added
cercle brugge players added
sv zulte waregem players added
kv kortrijk players added
fc brugge players added
k fc o beerschot wilrijk players added
vv st truiden players added
mouscron peruwelz players added
rsc charleroi players added
kv oostende players added
krc genk players added
All player URLs for the BE1 league appended.
fc luzern players added
fc lugano players added
fc zurich players added
fc sion players added
bsc young boys players added
servette fc players added
fc basel 1893 players added
fc vaduz players added
fc st gallen players added
fc lausanne sport players added
All player URLs for the C1 league appended.
cd palestino players added
union la calera players added
santiago wanderers players added
club deportes iquique players added
csd colo colo players added
cd universidad catolica players added
cd ohiggins players added
cd huachipato players added
cd cobresal players added
universidad concepcion players added
cdp curico unido players added
deportes la serena players added
union espanola players added
coquimbo unido players added
club de deportes antofagasta players added
cd everton players added
audax italiano players added
club universidad de chile players added
All player URLs for the CLPD league appended.
atletico nacional players added
independiente santa fe players added
cd atletico junior players added
ad union magdalena players added
alianza petrolera players added
cd america de cali players added
atletico bucaramanga players added
boyaca patriotas fc players added
once caldas players added
cd atletico huila players added
millonarios fc players added
deportes tolima players added
cucuta deportivo players added
jaguares de cordoba players added
envigado fc players added
independiente medellin players added
cd la equidad players added
deportivo cali players added
itagui ditaires players added
deportivo pasto players added
All player URLs for the COL1 league appended.
qingdao hainiu players added
wuhan zall professional f c players added
dalian aerbin players added
guangzhou r amp f f c  players added
shenzhen ruby players added
shandong luneng taishan f c  players added
tianjin teda players added
shijiazhuang yongchang players added
hebei zhongji players added
guangzhou evergrande f c  players added
shanghai east asia players added
henan jianye players added
chongqing lifan players added
jiangsu guoxin sainty players added
beijing guoan players added
shanghai greenland players added
All player URLs for the CSL league appended.
fc nordsjaelland players added
fc kopenhagen players added
aarhus gf players added
aalborg bk players added
odense boldklub players added
randers fc players added
brondby if players added
fc midtjylland players added
lyngby bk players added
vejle boldklub players added
sonderjyske players added
ac horsens players added
All player URLs for the DK1 league appended.
fc granada players added
real valladolid players added
fc villarreal players added
fc elche players added
atletico madrid players added
real madrid players added
fc sevilla players added
real sociedad san sebastian players added
cadiz cf players added
ca osasuna players added
real betis sevilla players added
deportivo alaves players added
fc valencia players added
ud levante players added
sd eibar players added
sd huesca players added
celta vigo players added
fc barcelona players added
fc getafe players added
athletic bilbao players added
All player URLs for the ES1 league appended.
fc malaga players added
fc cartagena players added
cd leganes players added
real oviedo players added
cd mirandes players added
ud las palmas players added
ud almeria players added
sd ponferradina players added
ce sabadell players added
ud logrones players added
fc fuenlabrada players added
rayo vallecano players added
ad alcorcon players added
rcd mallorca players added
cd teneriffa players added
fc girona players added
albacete balompie players added
espanyol barcelona players added
cd lugo players added
sporting gijon players added
cd castellon players added
real saragossa players added
All player URLs for the ES2 league appended.
fc honka players added
fc haka players added
fc kooteepee players added
seinajoen jk players added
ilves tampere players added
ifk mariehamn players added
fc lahti players added
hjk helsinki players added
helsinki ifk players added
kuopion palloseura players added
fc inter turku players added
ac oulu players added
All player URLs for the FI1 league appended.
ogc nizza players added
olympique lyon players added
fc stade rennes players added
as saint etienne players added
rc lens players added
stade reims players added
stade brest 29 players added
osc lille players added
fc girondins bordeaux players added
hsc montpellier players added
fc lorient players added
olympique marseille players added
olympique nimes players added
fc paris saint germain players added
as monaco players added
fc metz players added
racing strassburg players added
sco angers players added
fc nantes players added
fco dijon players added
All player URLs for the FR1 league appended.
fc valenciennes players added
ea guingamp players added
sm caen players added
paris fc players added
rodez aveyron football players added
fc sochaux montbeliard players added
ac ajaccio players added
aj auxerre players added
fc chambly players added
es troyes ac players added
fc pau players added
lb chateauroux players added
fc chamois niort players added
as nancy lorraine players added
grenoble foot 38 players added
union littoral de dunkerque players added
fc toulouse players added
ac le havre players added
clermont foot auvergne 63 players added
sc amiens players added
All player URLs for the FR2 league appended.
newcastle united players added
fc chelsea players added
fc everton players added
west ham united players added
brighton amp hove albion players added
fc southampton players added
leicester city players added
crystal palace players added
leeds united players added
fc liverpool players added
sheffield united players added
fc burnley players added
fc fulham players added
manchester city players added

wolverhampton wanderers players added
aston villa players added
manchester united players added
west bromwich albion players added
fc arsenal players added
tottenham hotspur players added
All player URLs for the GB1 league appended.
fc middlesbrough players added
swansea city players added
afc bournemouth players added
stoke city players added
sheffield wednesday players added
fc barnsley players added
derby county players added
wycombe wanderers players added
fc reading players added
cardiff city players added
queens park rangers players added
birmingham city players added
luton town players added
huddersfield town players added
blackburn rovers players added
fc millwall players added
nottingham forest players added
fc watford players added
fc brentford players added
coventry city players added
rotherham united players added
bristol city players added
norwich city players added
preston north end players added
All player URLs for the GB2 league appended.
charlton athletic players added
milton keynes dons players added
fleetwood town players added
oxford united players added
plymouth argyle players added
shrewsbury town players added
ipswich town players added
fc blackpool players added
fc portsmouth players added
wigan athletic players added
bristol rovers players added
afc wimbledon players added
fc gillingham players added
afc sunderland players added
lincoln city players added
afc rochdale players added
doncaster rovers players added
northampton town players added
hull city players added
crewe alexandra players added
burton albion players added
swindon town players added
peterborough united players added
accrington stanley players added
All player URLs for the GB3 league appended.
harrogate town players added
oldham athletic players added
grimsby town players added
port vale fc players added
salford city players added
afc barrow players added
tranmere rovers players added
cheltenham town players added
bolton wanderers players added
colchester united players added
cambridge united players added
fc stevenage players added
scunthorpe united players added
southend united players added
carlisle united players added
crawley town players added
fc walsall players added
forest green rovers players added
mansfield town players added
leyton orient players added
exeter city players added
newport county players added
fc morecambe players added
bradford city players added
All player URLs for the GB4 league appended.
panetolikos agrinio players added
ofi kreta players added
ae larisa players added
pas lamia 1964 players added
volos nfc players added
atromitos athen players added
apollon smyrnis players added
asteras tripolis players added
pas giannina players added
paok thessaloniki players added
panathinaikos athen players added
olympiakos piraus players added
aek athen players added
aris thessaloniki players added
All player URLs for the GR1 league appended.
derry city players added
dundalk fc players added
shelbourne fc players added
bohemian football club dublin players added
waterford united fc players added
st patricks athletic fc dublin players added
finn harps players added
sligo rovers players added
cork city fc players added
shamrock rovers players added
All player URLs for the IR1 league appended.
us sassuolo players added
juventus turin players added
cagliari calcio players added
fc genua 1893 players added
benevento calcio players added
udinese calcio players added
fc bologna players added
ac mailand players added
hellas verona players added
fc turin players added
fc crotone players added
as rom players added
inter mailand players added
atalanta bergamo players added
lazio rom players added
uc sampdoria players added
fc parma players added
spezia calcio players added
ssc neapel players added
ac florenz players added
All player URLs for the IT1 league appended.
pordenone calcio players added
us lecce players added
chievo verona players added
spal 2013 players added
ascoli calcio players added
delfino pescara 1936 players added
virtus entella players added
fc empoli players added
brescia calcio players added
ac reggiana 1919 players added
us cremonese players added
us salernitana 1919 players added
ac pisa 1909 players added
ac monza brianza players added
nuova cosenza calcio players added
as cittadella players added
fbc unione venezia players added
reggina calcio players added
frosinone calcio players added
vicenza calcio players added
All player URLs for the IT2 league appended.
sagan tosu players added
consadole sapporo players added
nagoya grampus players added
fc tokyo players added
kawasaki frontale players added
yokohama fc players added
vegalta sendai players added
shonan bellmare players added
vissel kobe players added
shimizu s pulse players added
kashiwa reysol players added
oita trinita players added
cerezo osaka players added
yokohama f marinos players added
urawa red diamonds players added
sanfrecce hiroshima players added
gamba osaka players added
kashima antlers players added
All player URLs for the JAP1 league appended.
nk osijek players added
nk varazdin players added
slaven belupo koprivnica players added
nk istra 1961 players added
hnk hajduk split players added
gnk dinamo zagreb players added
hnk gorica players added
hnk sibenik players added
nk lokomotiva zagreb players added
hnk rijeka players added
All player URLs for the KR1 league appended.
borussia dortmund players added
fc bayern munchen players added
1 fsv mainz 05 players added
tsg 1899 hoffenheim players added
1 fc union berlin players added
vfl wolfsburg players added
sv werder bremen players added
arminia bielefeld players added
sc freiburg players added
borussia monchengladbach players added
rasenballsport leipzig players added
eintracht frankfurt players added
fc schalke 04 players added
vfb stuttgart players added
fc augsburg players added
1 fc koln players added
bayer 04 leverkusen players added
hertha bsc players added
All player URLs for the L1 league appended.
vfl bochum players added
hamburger sv players added
hannover 96 players added
fortuna dusseldorf players added
fc st pauli players added
1 fc heidenheim players added
sc paderborn 07 players added
fc erzgebirge aue players added
sv darmstadt 98 players added
eintracht braunschweig players added
wurzburger kickers players added
holstein kiel players added
1 fc nurnberg players added
vfl osnabruck players added
karlsruher sc players added
spvgg greuther furth players added
sv sandhausen players added
ssv jahn regensburg players added
All player URLs for the L2 league appended.
1 fc saarbrucken players added
sc verl players added
tsv 1860 munchen players added
kfc uerdingen 05 players added
1 fc kaiserslautern players added
dynamo dresden players added
fc hansa rostock players added
sv wehen wiesbaden players added
hallescher fc players added
sv meppen players added
fc viktoria koln players added
fsv zwickau players added
fc ingolstadt 04 players added
spvgg unterhaching players added
sv waldhof mannheim 07 players added
fc bayern munchen ii players added
1 fc magdeburg players added
ata spor munchen players added
msv duisburg players added
vfb lubeck players added
All player URLs for the L3 league appended.
santos laguna players added
queretaro fc players added
atlas guadalajara players added
cf pachuca players added
tigres uanl players added
club necaxa players added
cf america players added
deportivo toluca players added
puebla fc players added
fc juarez players added
deportivo guadalajara players added
atletico san luis players added
club tijuana players added
club leon fc players added
sporting kansas city players added
new york red bulls players added
orlando city sc players added
fc dallas players added
philadelphia union players added
columbus crew players added
san jose earthquakes players added
portland timbers players added
toronto fc players added
seattle sounders fc players added
chicago fire players added
new york city fc players added
nashville mls team players added
los angeles football club players added
montreal impact players added
real salt lake city players added
vancouver whitecaps players added
houston dynamo players added
colorado rapids players added
los angeles galaxy players added

new england revolution players added
inter miami cf players added
d c united players added
minnesota united fc players added
atlanta united fc players added
fc cincinnati players added
All player URLs for the MLS1 league appended.
vvv venlo players added
fc twente enschede players added
az alkmaar players added
fc emmen players added
psv eindhoven players added
fortuna sittard players added
ajax amsterdam players added
vitesse arnheim players added
ado den haag players added
fc groningen players added
heracles almelo players added
rkc waalwijk players added
willem ii tilburg players added
sparta rotterdam players added
feyenoord rotterdam players added
fc utrecht players added
pec zwolle players added
sc heerenveen players added
All player URLs for the NL1 league appended.
stabaek if players added
kristiansund bk players added
sandefjord fotball players added
ik start kristiansand players added
molde fk players added
mjondalen if players added
brann bergen players added
valerenga oslo players added
viking stavanger players added
aalesunds fk players added
odds bk players added
sarpsborg 08 ff players added
rosenborg trondheim players added
stromsgodset if players added
fk haugesund players added
fk bodo glimt players added
All player URLs for the NO1 league appended.
cracovia krakau players added
pogon stettin players added
jagiellonia bialystok players added
lechia gdansk players added
stal mielec players added
warta posen players added
rakow czestochowa players added
wisla plock players added
zaglebie lubin players added
gornik zabrze players added
piast gliwice players added
podbeskidzie bielsko biala players added
wisla krakau players added
legia warschau players added
slask wroclaw players added
lech pozna%C5%84 players added
All player URLs for the PL1 league appended.
portimonense sc players added
sc braga players added
boavista porto fc players added
fc pacos de ferreira players added
fc porto players added
gil vicente fc players added
rio ave fc players added
moreirense fc players added
cd nacional players added
fc famalicao players added
cf belenenses lissabon players added
sc farense players added
cd tondela players added
benfica lissabon players added
cs maritimo players added
cd santa clara players added
vitoria guimaraes sc players added
sporting lissabon players added
All player URLs for the PO1 league appended.
scm argesul pitesti players added
cs u craiova players added
dinamo bukarest players added
steaua bukarest players added
fc botosani players added
sepsi osk sfantu gheorghe players added
fc voluntari players added
fc viitorul constanta players added
fc hermannstadt players added
uta arad players added
fc clinceni players added
csms iasi players added
cf chindia targoviste players added
gaz metan medias players added
cfr cluj players added
astra giurgiu players added
All player URLs for the RO1 league appended.
seongnam fc players added
pohang steelers players added
gangwon fc players added
suwon bluewings players added
gwangju fc players added
daegu fc players added
incheon united fc players added
busan ipark players added
fc seoul players added
sangju sangmu phoenix players added
ulsan hyundai players added
jeonbuk hyundai motors players added
All player URLs for the RSK1 league appended.
zenit st petersburg players added
fk krasnodar players added
arsenal tula players added
fk ufa players added
lokomotiv moskau players added
ural sverdlovskaya oblast players added
fk khimki players added
fk tambov players added
rubin kazan players added
fk sochi players added
spartak moskau players added
zska moskau players added
fk rostov players added
terek grozny players added
dinamo moskau players added
rotor volgograd players added
All player URLs for the RU1 league appended.
al hilal riad players added
abha club players added
al ettifaq players added
al nasr riad players added
al ain players added
al faisaly harmah players added
al ahli dschidda players added
al taawon players added
al qadisiyah fc players added
damak fc players added
al raed players added
al wahda mekka players added
al batin players added
al shabab riad players added
al ittihad dschidda players added
al fateh players added
All player URLs for the SA1 league appended.
st johnstone fc players added
ross county fc players added
motherwell fc players added
hamilton academical fc players added
kilmarnock fc players added
glasgow rangers players added
aberdeen fc players added
hibernian fc players added
livingston fc players added
st mirren fc players added
dundee united fc players added
celtic glasgow players added
All player URLs for the SC1 league appended.
mjallby aif players added
malmo ff players added
helsingborgs if players added
bk hacken players added
ostersunds fk players added
ik sirius players added
aik stockholm players added
falkenbergs ff players added
hammarby if players added
ifk norrkoping players added
kalmar ff players added
varbergs bois players added
ifk goteborg players added
djurgardens if players added
if elfsborg boras players added
orebro sk players added
All player URLs for the SE1 league appended.
orlando pirates players added
chippa united players added
supersport united players added
ts galaxy fc players added
baroka fc players added
mpumalanga black aces fc players added
cr vasco da gama players added
tshakhuma tsha madzivhandila fc players added
kaizer chiefs players added
mamelodi sundowns fc players added
maritzburg united fc players added
lamontville golden arrows players added
moroka swallows players added
amazulu fc players added
bloemfontein celtic players added
black leopards fc players added
All player URLs for the SFA1 league appended.
torku konyaspor players added
kayserispor players added
erzurum buyuksehir belediyespor players added
besiktas istanbul players added
goztepe izmir players added
genclerbirligi ankara players added
hatayspor players added
galatasaray istanbul players added
trabzonspor players added
medical park antalyaspor players added
fenerbahce istanbul players added
tekden denizlispor players added
yeni malatyaspor players added
istanbul buyuksehir belediyespor players added
alanyaspor players added
caykur rizespor players added
localtime fatih karagumruk players added
sivasspor players added
kasimpasa players added
gaziantep buyuksehir belediyespor players added
mke ankaragucu players added
All player URLs for the TR1 league appended.
fc banik ostrava players added
fc bohemians prag 1905 players added
fc viktoria pilsen players added
fk mlada boleslav players added
fk teplice players added
fc zbrojovka brunn players added
sk slavia prag players added
1 fk pribram players added
1 fc slovacko players added
fk pardubice players added
slezsky fc opava players added
fc slovan liberec players added
sk dynamo ceske budejovice players added
sk sigma olmutz players added
fc tescoma zlin players added
ac sparta prag players added
mfk karvina players added
fk jablonec players added
All player URLs for the TS1 league appended.
sharjah cultural sports club players added
hatta club players added
al nasr dubai  players added
al wasl sports club players added
al ittihad kalba players added
al dhafra players added
al khaleej players added
al ain fc players added
fc shabab al ahli dubai players added
fujairah sc players added
al jazira abu dhabi  players added
ajman club players added
baniyas sc players added
al wahda fc abu dhabi players added
All player URLs for the UAE1 league appended.
fk minaj players added
pfk oleksandria players added
ingulets pyatykhatky players added
ilyichivets mariupol players added
olimpik donetsk players added
fk lviv players added
shakhtar donetsk players added
rukh vinnyky players added
dynamo kiew players added
kolos kovalivka players added
desna chernigiv players added
sk dnipro 1 players added
zorya lugansk players added
vorskla poltava players added
All player URLs for the UKR1 league appended.
Scraping ended at: 2020-12-07 15:54:46.649223
Time taken to scrape the 21,940 player urls for the 2020/2021 season is: 64.18 minutes.

In [11]:
# List length i.e. total players
len(lst_player_urls)

21940

In [ ]:
# Write some code here that saves these URLs to a one column DataFrame

#### <a id='#section3.3.3.'>3.3.3. Bio Information</a>

In [48]:
# Run this script to scrape latest version of bio data from TransferMarkt

## Start timer
tic = datetime.datetime.now()

## Create empty list
lst_df_bio = []

## Print time scraping started
print(f'Scraping started at: {tic}')

## Scrape bio information for each player
for player_page in lst_player_urls:
    try:
        dict_output = tm_pull(player_page, player_bio=True, output='pandas')
        df = dict_output['player_bio']
        lst_df_bio.append(df)
        print(f'Bio data appended for: {player_page}.')
    except:
        pass

## Concatenate DataFrames
df_bio = pd.concat(lst_df_bio)

## Print time scraping ended
print(f'Scraping ended at: {toc}')

## Create attribute for the season    
df_bio['season'] = full_season_string

## End timer
toc = datetime.datetime.now()

## Calculate time take
total_time = (toc-tic).total_seconds()
print(f'Time taken to scrape the bio data of the {len_player_urls:,} players for the {full_season_string} season is: {total_time/60:0.2f} minutes.')

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Time taken to scrape the bio data of the 21965 players for the 20/21 season is: 295.74 minutes.

In [64]:
# Display DataFrame
df_bio.head()

,player_id,player_name,day_of_birth,month_of_birth,year_of_birth,pob,cob,dob,position,height,foot,second_citizenship,season
0,206906,dominik baumgartner,20,7,1996,Horn,Austria,1996-07-20,None,187,right,None,2020-2021
0,336382,dejan joveljic,7,8,1999,Bijeljina,Bosnia-Herzegovina,1999-08-07,None,182,right,Bosnia-Herzegovina,2020-2021
0,52821,mario leitgeb,30,6,1988,Graz,Austria,1988-06-30,None,183,right,None,2020-2021
0,444018,eliel peretz,18,11,1996,Bat Yam,Israel,1996-11-18,None,189,right,None,2020-2021
0,145010,marc andre schmerböck,1,4,1994,Feldbach,Austria,1994-04-01,None,180,left,None,2020-2021

In [63]:
df_bio.shape

(21965, 13)

##### Export DataFrame

In [67]:
# Export DataFrame as a CSV file

## Export a copy to the 'archive' subfolder of the TM folder, including the date
df_bio.to_csv(data_dir_tm + f'/raw/{short_season_string}/bio/archive/' + f'tm_player_bio_all_{short_season_string}_last_updated_{today}.csv', index=None, header=True)

## Export another copy to the TM folder called 'latest' (can be overwritten)
df_bio.to_csv(data_dir_tm + f'/raw/{short_season_string}/bio/' + f'tm_player_bio_all_{short_season_string}_latest.csv', index=None, header=True)

#### <a id='#section3.3.4.'>3.3.4. Status Information</a>

In [53]:
# Run this script to scrape latest version of status data from TransferMarkt

## Start timer
tic = datetime.datetime.now()

## Create empty list
lst_df_status = []

## Print time scraping started
print(f'Scraping started at: {tic}')

## Scrape status information for each player
for player_page in lst_player_urls:
    try:
        dict_output = tm_pull(player_page, player_status=True, output='pandas')
        df = dict_output['player_status']
        lst_df_status.append(df)
        print(f'Status data appended for: {player_page}.')
    except:
        pass

## Concatenate DataFrames
df_status = pd.concat(lst_df_status)

## Print time scraping ended
print(f'Scraping ended at: {toc}')

## Create attribute for the season    
df_status['season'] = full_season_string

## End timer
toc = datetime.datetime.now()

## Calculate time take
total_time = (toc-tic).total_seconds()
print(f'Time taken to scrape the status data of the {len_player_urls:,} players for the {full_season_string} season is: {total_time/60:0.2f} minutes.')

Scraping started at: 2020-12-05 04:44:09.834141

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Scraping ended at: 2020-12-05 04:33:32.993690
Time taken to scrape the status data of the 21965 players for the 20/21 season is: 311.60 minutes.

In [65]:
# Display DataFrame
df_status.head()

,player_id,current_club,current_club_country,market_value,joined,contract_expires,contract_option,on_loan_from,on_loan_from_country,loan_contract_expiry,player_agent,season
0,531217,wolfsberger ac,austria,200000,2020-06-01,None,None,None,None,None,Selection Fussballconsulting,2020-2021
0,451317,sv ried,austria,400000,2019-07-01,None,None,None,None,None,More than Sport GmbH,2020-2021
0,445038,sv ried,austria,75000,2020-09-21,None,None,None,None,None,ONE ON ONE Sports Management,2020-2021
0,159581,sv ried,austria,200000,2019-07-01,None,None,None,None,None,Relatives,2020-2021
0,394070,sv ried,austria,75000,2019-07-01,None,None,None,None,None,None,2020-2021

In [66]:
df_status.shape

(3581, 12)

##### Export DataFrame

In [54]:
# Export DataFrame as a CSV file

## Export a copy to the 'archive' subfolder of the TM folder, including the date
df_status.to_csv(data_dir_tm + f'/raw/{short_season_string}/status/archive/' + f'tm_player_status_all_{short_season_string}_last_updated_{today}.csv', index=None, header=True)

## Export another copy to the TM folder called 'latest' (can be overwritten)
df_status.to_csv(data_dir_tm + f'/raw/{short_season_string}/status/' + f'tm_player_status_all_{short_season_string}_latest.csv', index=None, header=True)

#### <a id='#section3.3.5.'>3.3.5. Transfer History</a>

In [29]:
# Run this script to scrape latest version of transfer history data from TransferMarkt

## Start timer
tic = datetime.datetime.now()

## Create empty list
lst_df_th = []

## Print time scraping started
print(f'Scraping started at: {tic}')

## Scrape bio information for each player
for player_page in lst_player_urls:
    try:
        dict_output = tm_pull(player_page, transfer_history=True, output='pandas')
        df = dict_output['transfer_history']
        lst_df_th.append(df)
        print(f'Transfer history data appended for: {player_page}.')
    except:
        pass

## Concatenate DataFrames
df_th = pd.concat(lst_df_th)

## Print time scraping ended
print(f'Scraping ended at: {toc}')

## Create attribute for the season    
df_th['season'] = full_season_string

## End timer
toc = datetime.datetime.now()

## Calculate time take
total_time = (toc-tic).total_seconds()
print(f'Time taken to scrape the transfer history data of the {len_player_urls:,} players for the {full_season_string} season is: {total_time/60:0.2f} minutes.')

Scraping started at: 2020-12-05 16:19:57.492112
Transfer history data appended for: https://www.transfermarkt.com/samuel-oum-gouet/profil/spieler/452238.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-schreiner/profil/spieler/59132.
Transfer history data appended for: https://www.transfermarkt.com/nosa-iyobosa-edokpolor/profil/spieler/276841.
Transfer history data appended for: https://www.transfermarkt.com/jakob-odehnal/profil/spieler/526353.
Transfer history data appended for: https://www.transfermarkt.com/tino-casali/profil/spieler/169271.
Transfer history data appended for: https://www.transfermarkt.com/lars-nussbaumer/profil/spieler/407503.
Transfer history data appended for: https://www.transfermarkt.com/alain-wiss/profil/spieler/58165.
Transfer history data appended for: https://www.transfermarkt.com/nana-kofi-babil/profil/spieler/734819.
Transfer history data appended for: https://www.transfermarkt.com/manfred-fischer/profil/spieler/269093.
Transfer history data appended for: https://www.transfermarkt.com/marco-meilinger/profil/spieler/79607.
Transfer history data appended for: https://www.transfermarkt.com/mario-stefel/profil/spieler/356558.
Transfer history data appended for: https://www.transfermarkt.com/emir-karic/profil/spieler/286596.
Transfer history data appended for: https://www.transfermarkt.com/daniel-nussbaumer/profil/spieler/307824.
Transfer history data appended for: https://www.transfermarkt.com/anderson/profil/spieler/494830.
Transfer history data appended for: https://www.transfermarkt.com/ogulcan-bekar/profil/spieler/375358.
Transfer history data appended for: https://www.transfermarkt.com/frantz-pangop/profil/spieler/266954.
Transfer history data appended for: https://www.transfermarkt.com/berkay-dabanli/profil/spieler/121528.
Transfer history data appended for: https://www.transfermarkt.com/jan-zwischenbrugger/profil/spieler/83617.
Transfer history data appended for: https://www.transfermarkt.com/philipp-netzer/profil/spieler/17084.
Transfer history data appended for: https://www.transfermarkt.com/manuel-thurnwald/profil/spieler/307485.
Transfer history data appended for: https://www.transfermarkt.com/martin-kobras/profil/spieler/51719.
Transfer history data appended for: https://www.transfermarkt.com/johannes-tartarotti/profil/spieler/307871.
Transfer history data appended for: https://www.transfermarkt.com/david-bumberger/profil/spieler/321850.
Transfer history data appended for: https://www.transfermarkt.com/daniel-maderner/profil/spieler/195741.
Transfer history data appended for: https://www.transfermarkt.com/aljaz-casar/profil/spieler/682519.
Transfer history data appended for: https://www.transfermarkt.com/daniel-schutz/profil/spieler/52245.
Transfer history data appended for: https://www.transfermarkt.com/robert-ljubicic/profil/spieler/353634.
Transfer history data appended for: https://www.transfermarkt.com/armin-gremsl/profil/spieler/159758.
Transfer history data appended for: https://www.transfermarkt.com/kofi-schulz/profil/spieler/192539.
Transfer history data appended for: https://www.transfermarkt.com/alexander-schmidt/profil/spieler/307939.
Transfer history data appended for: https://www.transfermarkt.com/marcel-tanzmayr/profil/spieler/524541.
Transfer history data appended for: https://www.transfermarkt.com/daniel-drescher/profil/spieler/49510.
Transfer history data appended for: https://www.transfermarkt.com/lukas-grozurek/profil/spieler/75829.
Transfer history data appended for: https://www.transfermarkt.com/dor-hugi/profil/spieler/293602.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-meister/profil/spieler/321057.
Transfer history data appended for: https://www.transfermarkt.com/george-davies/profil/spieler/273065.
Transfer history data appended for: https://www.transfermarkt.com/ahmet-muhamedbegovic/profil/spieler/271323.
Transfer history data appended for: https://www.transfermarkt.com/reza-asadi/profil/spieler/408805.
Transfer history data appended for: https://www.transfermarkt.com/luan/profil/spieler/349820.
Transfer history data appended for: https://www.transfermarkt.com/christoph-messerer/profil/spieler/646845.
Transfer history data appended for: https://www.transfermarkt.com/daniel-luxbacher/profil/spieler/81710.
Transfer history data appended for: https://www.transfermarkt.com/michael-steinwender/profil/spieler/375434.
Transfer history data appended for: https://www.transfermarkt.com/michael-blauensteiner/profil/spieler/195854.
Transfer history data appended for: https://www.transfermarkt.com/manuel-maranda/profil/spieler/287995.
Transfer history data appended for: https://www.transfermarkt.com/emilian-metu/profil/spieler/580622.
Transfer history data appended for: https://www.transfermarkt.com/christoph-riegler/profil/spieler/122899.
Transfer history data appended for: https://www.transfermarkt.com/peter-pokorny/profil/spieler/490595.
Transfer history data appended for: https://www.transfermarkt.com/martin-majnovics/profil/spieler/394609.
Transfer history data appended for: https://www.transfermarkt.com/christoph-halper/profil/spieler/308086.
Transfer history data appended for: https://www.transfermarkt.com/phoenix-missi/profil/spieler/806199.
Transfer history data appended for: https://www.transfermarkt.com/andreas-leitner/profil/spieler/106851.
Transfer history data appended for: https://www.transfermarkt.com/lukas-rath/profil/spieler/67442.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-lukacevic/profil/spieler/321870.
Transfer history data appended for: https://www.transfermarkt.com/stephan-auer/profil/spieler/82527.
Transfer history data appended for: https://www.transfermarkt.com/morten-hjulmand/profil/spieler/461496.
Transfer history data appended for: https://www.transfermarkt.com/wilhelm-vorsager/profil/spieler/293015.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-breunig/profil/spieler/584254.
Transfer history data appended for: https://www.transfermarkt.com/nikola-pejovic/profil/spieler/343954.
Transfer history data appended for: https://www.transfermarkt.com/filip-ristanic/profil/spieler/601113.
Transfer history data appended for: https://www.transfermarkt.com/luca-kronberger/profil/spieler/519011.
Transfer history data appended for: https://www.transfermarkt.com/stefan-maierhofer/profil/spieler/32660.
Transfer history data appended for: https://www.transfermarkt.com/osman-hadzikic/profil/spieler/188881.
Transfer history data appended for: https://www.transfermarkt.com/marcus-maier/profil/spieler/195577.
Transfer history data appended for: https://www.transfermarkt.com/marco-kadlec/profil/spieler/394150.
Transfer history data appended for: https://www.transfermarkt.com/onurhan-babuscu/profil/spieler/538481.
Transfer history data appended for: https://www.transfermarkt.com/josef-ganda/profil/spieler/456929.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-bauer/profil/spieler/151739.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-cirkovic/profil/spieler/452218.
Transfer history data appended for: https://www.transfermarkt.com/christoph-haas/profil/spieler/157390.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-aiwu/profil/spieler/394152.
Transfer history data appended for: https://www.transfermarkt.com/roman-kerschbaum/profil/spieler/120202.
Transfer history data appended for: https://www.transfermarkt.com/marco-hausjell/profil/spieler/354054.
Transfer history data appended for: https://www.transfermarkt.com/lukas-malicsek/profil/spieler/354061.
Transfer history data appended for: https://www.transfermarkt.com/felix-kekoh/profil/spieler/806200.
Transfer history data appended for: https://www.transfermarkt.com/dominik-starkl/profil/spieler/158214.
Transfer history data appended for: https://www.transfermarkt.com/paul-koller/profil/spieler/523895.
Transfer history data appended for: https://www.transfermarkt.com/julian-buchta/profil/spieler/346844.
Transfer history data appended for: https://www.transfermarkt.com/tomislav-tomic/profil/spieler/190272.
Transfer history data appended for: https://www.transfermarkt.com/pascal-petlach/profil/spieler/354063.

Transfer history data appended for: https://www.transfermarkt.com/srdjan-grahovac/profil/spieler/123158.
Transfer history data appended for: https://www.transfermarkt.com/marcel-ritzmaier/profil/spieler/84162.
Transfer history data appended for: https://www.transfermarkt.com/adrian-hajdari/profil/spieler/388304.
Transfer history data appended for: https://www.transfermarkt.com/filip-stojkovic/profil/spieler/139751.
Transfer history data appended for: https://www.transfermarkt.com/thorsten-schick/profil/spieler/55574.
Transfer history data appended for: https://www.transfermarkt.com/christopher-dibon/profil/spieler/54607.
Transfer history data appended for: https://www.transfermarkt.com/dalibor-velimirovic/profil/spieler/437891.
Transfer history data appended for: https://www.transfermarkt.com/mateo-barac/profil/spieler/329629.
Transfer history data appended for: https://www.transfermarkt.com/taxiarchis-fountas/profil/spieler/192409.
Transfer history data appended for: https://www.transfermarkt.com/tamas-szanto/profil/spieler/235529.
Transfer history data appended for: https://www.transfermarkt.com/paul-gartler/profil/spieler/223957.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-ullmann/profil/spieler/239934.
Transfer history data appended for: https://www.transfermarkt.com/kelvin-arase/profil/spieler/321048.
Transfer history data appended for: https://www.transfermarkt.com/dejan-ljubicic/profil/spieler/287188.
Transfer history data appended for: https://www.transfermarkt.com/lion-schuster/profil/spieler/391560.
Transfer history data appended for: https://www.transfermarkt.com/bernhard-unger/profil/spieler/341761.
Transfer history data appended for: https://www.transfermarkt.com/philipp-schobesberger/profil/spieler/190848.
Transfer history data appended for: https://www.transfermarkt.com/yusuf-demir/profil/spieler/548031.
Transfer history data appended for: https://www.transfermarkt.com/dejan-petrovic/profil/spieler/320859.
Transfer history data appended for: https://www.transfermarkt.com/ercan-kara/profil/spieler/320701.
Transfer history data appended for: https://www.transfermarkt.com/leo-greiml/profil/spieler/434110.
Transfer history data appended for: https://www.transfermarkt.com/mario-sonnleitner/profil/spieler/18297.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-hofmann/profil/spieler/131231.
Transfer history data appended for: https://www.transfermarkt.com/christoph-knasmullner/profil/spieler/59068.
Transfer history data appended for: https://www.transfermarkt.com/melih-ibrahimoglu/profil/spieler/391555.
Transfer history data appended for: https://www.transfermarkt.com/dragoljub-savic/profil/spieler/574656.
Transfer history data appended for: https://www.transfermarkt.com/lukas-sulzbacher/profil/spieler/375355.
Transfer history data appended for: https://www.transfermarkt.com/koya-kitagawa/profil/spieler/290705.
Transfer history data appended for: https://www.transfermarkt.com/richard-strebinger/profil/spieler/93768.
Transfer history data appended for: https://www.transfermarkt.com/paul-gobara/profil/spieler/353915.
Transfer history data appended for: https://www.transfermarkt.com/georg-teigl/profil/spieler/81698.
Transfer history data appended for: https://www.transfermarkt.com/christoph-schosswendter/profil/spieler/68379.
Transfer history data appended for: https://www.transfermarkt.com/matthias-braunoder/profil/spieler/488052.
Transfer history data appended for: https://www.transfermarkt.com/thomas-ebner/profil/spieler/122781.
Transfer history data appended for: https://www.transfermarkt.com/christoph-monschein/profil/spieler/300095.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-jukic/profil/spieler/393699.
Transfer history data appended for: https://www.transfermarkt.com/alexander-grunwald/profil/spieler/34763.
Transfer history data appended for: https://www.transfermarkt.com/christian-schoissengeyr/profil/spieler/157242.
Transfer history data appended for: https://www.transfermarkt.com/alon-turgeman/profil/spieler/177249.
Transfer history data appended for: https://www.transfermarkt.com/benedikt-pichler/profil/spieler/331362.
Transfer history data appended for: https://www.transfermarkt.com/csaba-mester/profil/spieler/497340.
Transfer history data appended for: https://www.transfermarkt.com/manprit-sarkaria/profil/spieler/288690.
Transfer history data appended for: https://www.transfermarkt.com/stefan-radulovic/profil/spieler/527529.
Transfer history data appended for: https://www.transfermarkt.com/mirko-kos/profil/spieler/307511.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-sax/profil/spieler/115072.
Transfer history data appended for: https://www.transfermarkt.com/vesel-demaku/profil/spieler/346846.
Transfer history data appended for: https://www.transfermarkt.com/ammar-helac/profil/spieler/307598.
Transfer history data appended for: https://www.transfermarkt.com/stephan-zwierschitz/profil/spieler/81701.
Transfer history data appended for: https://www.transfermarkt.com/bright-edomwonyi/profil/spieler/229857.
Transfer history data appended for: https://www.transfermarkt.com/niels-hahn/profil/spieler/404936.
Transfer history data appended for: https://www.transfermarkt.com/maudo-jarjue/profil/spieler/450462.
Transfer history data appended for: https://www.transfermarkt.com/dominik-fitz/profil/spieler/354022.
Transfer history data appended for: https://www.transfermarkt.com/anouar-el-moukhantir/profil/spieler/261495.
Transfer history data appended for: https://www.transfermarkt.com/markus-suttner/profil/spieler/31514.
Transfer history data appended for: https://www.transfermarkt.com/patrick-pentz/profil/spieler/223972.
Transfer history data appended for: https://www.transfermarkt.com/patrick-wimmer/profil/spieler/533295.
Transfer history data appended for: https://www.transfermarkt.com/erik-palmer-brown/profil/spieler/282199.
Transfer history data appended for: https://www.transfermarkt.com/christoph-martschinko/profil/spieler/120191.
Transfer history data appended for: https://www.transfermarkt.com/johannes-handl/profil/spieler/293084.
Transfer history data appended for: https://www.transfermarkt.com/hamidou-maiga/profil/spieler/364851.
Transfer history data appended for: https://www.transfermarkt.com/tobias-kainz/profil/spieler/69741.
Transfer history data appended for: https://www.transfermarkt.com/michael-huber/profil/spieler/72146.
Transfer history data appended for: https://www.transfermarkt.com/rajko-rep/profil/spieler/80525.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-pusswald/profil/spieler/782179.
Transfer history data appended for: https://www.transfermarkt.com/samson-tijani/profil/spieler/666613.
Transfer history data appended for: https://www.transfermarkt.com/florian-faist/profil/spieler/255287.
Transfer history data appended for: https://www.transfermarkt.com/lukas-ried/profil/spieler/194770.
Transfer history data appended for: https://www.transfermarkt.com/manfred-gollner/profil/spieler/89055.
Transfer history data appended for: https://www.transfermarkt.com/stefan-golles/profil/spieler/307381.
Transfer history data appended for: https://www.transfermarkt.com/felix-luckeneder/profil/spieler/156691.
Transfer history data appended for: https://www.transfermarkt.com/michael-john-lema/profil/spieler/317450.
Transfer history data appended for: https://www.transfermarkt.com/bakary-nimaga/profil/spieler/257730.
Transfer history data appended for: https://www.transfermarkt.com/christian-klem/profil/spieler/58948.
Transfer history data appended for: https://www.transfermarkt.com/lukas-gabbichler/profil/spieler/341762.
Transfer history data appended for: https://www.transfermarkt.com/julius-ertlthaler/profil/spieler/286622.
Transfer history data appended for: https://www.transfermarkt.com/rene-swete/profil/spieler/181454.
Transfer history data appended for: https://www.transfermarkt.com/stefan-rakowitz/profil/spieler/76422.
Transfer history data appended for: https://www.transfermarkt.com/alexander-burgstaller/profil/spieler/307554.
Transfer history data appended for: https://www.transfermarkt.com/andreas-lienhart/profil/spieler/32394.

Transfer history data appended for: https://www.transfermarkt.com/philipp-sturm/profil/spieler/307696.
Transfer history data appended for: https://www.transfermarkt.com/sascha-horvath/profil/spieler/186365.
Transfer history data appended for: https://www.transfermarkt.com/dario-tadic/profil/spieler/50860.
Transfer history data appended for: https://www.transfermarkt.com/lukas-fadinger/profil/spieler/394018.
Transfer history data appended for: https://www.transfermarkt.com/jurgen-heil/profil/spieler/271223.
Transfer history data appended for: https://www.transfermarkt.com/abdoul-yoda/profil/spieler/811856.
Transfer history data appended for: https://www.transfermarkt.com/raphael-sallinger/profil/spieler/225360.
Transfer history data appended for: https://www.transfermarkt.com/thomas-rotter/profil/spieler/119231.
Transfer history data appended for: https://www.transfermarkt.com/seifedin-chabbi/profil/spieler/106862.
Transfer history data appended for: https://www.transfermarkt.com/filip-borsos/profil/spieler/445038.
Transfer history data appended for: https://www.transfermarkt.com/luca-meisl/profil/spieler/307641.
Transfer history data appended for: https://www.transfermarkt.com/marcel-canadi/profil/spieler/223953.
Transfer history data appended for: https://www.transfermarkt.com/valentin-grubeck/profil/spieler/159581.
Transfer history data appended for: https://www.transfermarkt.com/sadam-sulley/profil/spieler/437600.
Transfer history data appended for: https://www.transfermarkt.com/marco-grull/profil/spieler/391766.
Transfer history data appended for: https://www.transfermarkt.com/stefan-nutz/profil/spieler/106171.
Transfer history data appended for: https://www.transfermarkt.com/marcel-ziegl/profil/spieler/59152.
Transfer history data appended for: https://www.transfermarkt.com/seth-paintsil/profil/spieler/372813.
Transfer history data appended for: https://www.transfermarkt.com/bernd-gschweidl/profil/spieler/167350.
Transfer history data appended for: https://www.transfermarkt.com/murat-satin/profil/spieler/225687.
Transfer history data appended for: https://www.transfermarkt.com/balakiyem-takougnadi/profil/spieler/122132.
Transfer history data appended for: https://www.transfermarkt.com/arne-ammerer/profil/spieler/240653.
Transfer history data appended for: https://www.transfermarkt.com/felix-seiwald/profil/spieler/394070.
Transfer history data appended for: https://www.transfermarkt.com/kennedy-boateng/profil/spieler/451317.
Transfer history data appended for: https://www.transfermarkt.com/ante-bajic/profil/spieler/282918.
Transfer history data appended for: https://www.transfermarkt.com/daniel-offenbacher/profil/spieler/83505.
Transfer history data appended for: https://www.transfermarkt.com/samuel-sahin-radlinger/profil/spieler/77563.
Transfer history data appended for: https://www.transfermarkt.com/constantin-reiner/profil/spieler/286643.
Transfer history data appended for: https://www.transfermarkt.com/julian-wiessmeier/profil/spieler/93559.
Transfer history data appended for: https://www.transfermarkt.com/thomas-reifeltshammer/profil/spieler/77612.
Transfer history data appended for: https://www.transfermarkt.com/lukas-gutlbauer/profil/spieler/371430.
Transfer history data appended for: https://www.transfermarkt.com/markus-lackner/profil/spieler/82536.
Transfer history data appended for: https://www.transfermarkt.com/canillas/profil/spieler/383246.
Transfer history data appended for: https://www.transfermarkt.com/manuel-kerhe/profil/spieler/52369.
Transfer history data appended for: https://www.transfermarkt.com/manuel-haas/profil/spieler/186363.
Transfer history data appended for: https://www.transfermarkt.com/michael-lercher/profil/spieler/186369.
Transfer history data appended for: https://www.transfermarkt.com/daniel-edward-daniliuc/profil/spieler/354052.
Transfer history data appended for: https://www.transfermarkt.com/raffael-behounek/profil/spieler/321095.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-celic/profil/spieler/353899.
Transfer history data appended for: https://www.transfermarkt.com/felix-kerber/profil/spieler/524490.
Transfer history data appended for: https://www.transfermarkt.com/bruno-soares/profil/spieler/104545.
Transfer history data appended for: https://www.transfermarkt.com/nikolai-baden-frederiksen/profil/spieler/400550.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-pranter/profil/spieler/58963.
Transfer history data appended for: https://www.transfermarkt.com/florian-toplitsch/profil/spieler/83584.
Transfer history data appended for: https://www.transfermarkt.com/stefan-hager/profil/spieler/158179.
Transfer history data appended for: https://www.transfermarkt.com/simon-beccari/profil/spieler/364558.
Transfer history data appended for: https://www.transfermarkt.com/kelvin-yeboah/profil/spieler/589737.
Transfer history data appended for: https://www.transfermarkt.com/zan-rogelj/profil/spieler/371861.
Transfer history data appended for: https://www.transfermarkt.com/florian-buchacher/profil/spieler/52773.
Transfer history data appended for: https://www.transfermarkt.com/ferdinand-oswald/profil/spieler/58360.
Transfer history data appended for: https://www.transfermarkt.com/fabian-koch/profil/spieler/59069.
Transfer history data appended for: https://www.transfermarkt.com/kilian-bauernfeind/profil/spieler/524475.
Transfer history data appended for: https://www.transfermarkt.com/renny-smith/profil/spieler/291895.
Transfer history data appended for: https://www.transfermarkt.com/david-schnegg/profil/spieler/378260.
Transfer history data appended for: https://www.transfermarkt.com/johannes-naschberger/profil/spieler/321874.
Transfer history data appended for: https://www.transfermarkt.com/florian-rieder/profil/spieler/317847.
Transfer history data appended for: https://www.transfermarkt.com/david-gugganig/profil/spieler/223960.
Transfer history data appended for: https://www.transfermarkt.com/julian-golles/profil/spieler/339826.
Transfer history data appended for: https://www.transfermarkt.com/stefan-lauf/profil/spieler/604548.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-jauregui/profil/spieler/282469.
Transfer history data appended for: https://www.transfermarkt.com/thanos-petsos/profil/spieler/82110.
Transfer history data appended for: https://www.transfermarkt.com/tobias-anselm/profil/spieler/321847.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-ozegovic/profil/spieler/319825.
Transfer history data appended for: https://www.transfermarkt.com/philipp-huspek/profil/spieler/59057.
Transfer history data appended for: https://www.transfermarkt.com/paul-komposch/profil/spieler/452461.
Transfer history data appended for: https://www.transfermarkt.com/dardan-shabanhaxhaj/profil/spieler/452464.
Transfer history data appended for: https://www.transfermarkt.com/stefan-hierlander/profil/spieler/59053.
Transfer history data appended for: https://www.transfermarkt.com/amadou-dante/profil/spieler/649087.
Transfer history data appended for: https://www.transfermarkt.com/luka-maric/profil/spieler/432859.
Transfer history data appended for: https://www.transfermarkt.com/niklas-geyrhofer/profil/spieler/394008.
Transfer history data appended for: https://www.transfermarkt.com/jorg-siebenhandl/profil/spieler/59009.
Transfer history data appended for: https://www.transfermarkt.com/kevin-friesenbichler/profil/spieler/106848.
Transfer history data appended for: https://www.transfermarkt.com/vincent-trummer/profil/spieler/365589.
Transfer history data appended for: https://www.transfermarkt.com/jusuf-gazibegovic/profil/spieler/393745.
Transfer history data appended for: https://www.transfermarkt.com/emeka-eze/profil/spieler/498517.
Transfer history data appended for: https://www.transfermarkt.com/francisco-mwepu/profil/spieler/632872.
Transfer history data appended for: https://www.transfermarkt.com/gregory-wuthrich/profil/spieler/203125.
Transfer history data appended for: https://www.transfermarkt.com/lukas-jager/profil/spieler/120206.
Transfer history data appended for: https://www.transfermarkt.com/david-nemeth/profil/spieler/451906.

Transfer history data appended for: https://www.transfermarkt.com/ivan-ljubic/profil/spieler/250028.
Transfer history data appended for: https://www.transfermarkt.com/tobias-koch/profil/spieler/434103.
Transfer history data appended for: https://www.transfermarkt.com/sandro-schendl/profil/spieler/527596.
Transfer history data appended for: https://www.transfermarkt.com/sandro-ingolitsch/profil/spieler/286627.
Transfer history data appended for: https://www.transfermarkt.com/tobias-schutzenauer/profil/spieler/243237.
Transfer history data appended for: https://www.transfermarkt.com/jakob-jantscher/profil/spieler/52269.
Transfer history data appended for: https://www.transfermarkt.com/andreas-kuen/profil/spieler/186798.
Transfer history data appended for: https://www.transfermarkt.com/jon-gorenc-stankovic/profil/spieler/245034.
Transfer history data appended for: https://www.transfermarkt.com/otar-kiteishvili/profil/spieler/352596.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-zettl/profil/spieler/434106.
Transfer history data appended for: https://www.transfermarkt.com/fabian-tauchhammer/profil/spieler/428462.
Transfer history data appended for: https://www.transfermarkt.com/luka-lochoshvili/profil/spieler/345189.
Transfer history data appended for: https://www.transfermarkt.com/christopher-wernitznig/profil/spieler/77117.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-rnic/profil/spieler/27236.
Transfer history data appended for: https://www.transfermarkt.com/marc-andre-schmerbock/profil/spieler/145010.
Transfer history data appended for: https://www.transfermarkt.com/lukas-schofl/profil/spieler/514440.
Transfer history data appended for: https://www.transfermarkt.com/alexander-kofler/profil/spieler/55569.
Transfer history data appended for: https://www.transfermarkt.com/cheikhou-dieng/profil/spieler/225536.
Transfer history data appended for: https://www.transfermarkt.com/guram-giorbelidze/profil/spieler/330277.
Transfer history data appended for: https://www.transfermarkt.com/eliel-peretz/profil/spieler/444018.
Transfer history data appended for: https://www.transfermarkt.com/stefan-peric/profil/spieler/223973.
Transfer history data appended for: https://www.transfermarkt.com/matthaus-taferner/profil/spieler/434104.
Transfer history data appended for: https://www.transfermarkt.com/mario-leitgeb/profil/spieler/52821.
Transfer history data appended for: https://www.transfermarkt.com/sven-sprangler/profil/spieler/181714.
Transfer history data appended for: https://www.transfermarkt.com/manuel-kuttin/profil/spieler/91410.
Transfer history data appended for: https://www.transfermarkt.com/dominik-baumgartner/profil/spieler/206906.
Transfer history data appended for: https://www.transfermarkt.com/marko-soldo/profil/spieler/270598.
Transfer history data appended for: https://www.transfermarkt.com/michael-liendl/profil/spieler/17057.
Transfer history data appended for: https://www.transfermarkt.com/kai-stratznig/profil/spieler/531217.
Transfer history data appended for: https://www.transfermarkt.com/dario-vizinger/profil/spieler/391340.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-scherzer/profil/spieler/196782.
Transfer history data appended for: https://www.transfermarkt.com/mario-pavelic/profil/spieler/106866.
Transfer history data appended for: https://www.transfermarkt.com/dejan-joveljic/profil/spieler/336382.
Transfer history data appended for: https://www.transfermarkt.com/michael-novak/profil/spieler/77487.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-wober/profil/spieler/263361.
Transfer history data appended for: https://www.transfermarkt.com/carlos-miguel-coronel/profil/spieler/378871.
Transfer history data appended for: https://www.transfermarkt.com/majeed-ashimeru/profil/spieler/360140.
Transfer history data appended for: https://www.transfermarkt.com/dominik-szoboszlai/profil/spieler/451276.
Transfer history data appended for: https://www.transfermarkt.com/antoine-bernede/profil/spieler/395512.
Transfer history data appended for: https://www.transfermarkt.com/albert-vallci/profil/spieler/261935.
Transfer history data appended for: https://www.transfermarkt.com/alexander-walke/profil/spieler/1271.
Transfer history data appended for: https://www.transfermarkt.com/luka-sucic/profil/spieler/502722.
Transfer history data appended for: https://www.transfermarkt.com/amar-dedic/profil/spieler/519184.
Transfer history data appended for: https://www.transfermarkt.com/cican-stankovic/profil/spieler/127679.
Transfer history data appended for: https://www.transfermarkt.com/ousmane-diakite/profil/spieler/402007.
Transfer history data appended for: https://www.transfermarkt.com/andreas-ulmer/profil/spieler/31196.
Transfer history data appended for: https://www.transfermarkt.com/noah-okafor/profil/spieler/346890.
Transfer history data appended for: https://www.transfermarkt.com/jerome-onguene/profil/spieler/272638.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-seiwald/profil/spieler/404950.
Transfer history data appended for: https://www.transfermarkt.com/patrick-farkas/profil/spieler/81675.
Transfer history data appended for: https://www.transfermarkt.com/chukwubuike-adamu/profil/spieler/452477.
Transfer history data appended for: https://www.transfermarkt.com/mergim-berisha/profil/spieler/307924.
Transfer history data appended for: https://www.transfermarkt.com/patson-daka/profil/spieler/365172.
Transfer history data appended for: https://www.transfermarkt.com/karim-adeyemi/profil/spieler/496094.
Transfer history data appended for: https://www.transfermarkt.com/enock-mwepu/profil/spieler/490307.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-camara/profil/spieler/543382.
Transfer history data appended for: https://www.transfermarkt.com/youba-diarra/profil/spieler/564451.
Transfer history data appended for: https://www.transfermarkt.com/sekou-koita/profil/spieler/402010.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-kristensen/profil/spieler/369684.
Transfer history data appended for: https://www.transfermarkt.com/thomas-gebauer/profil/spieler/12137.
Transfer history data appended for: https://www.transfermarkt.com/stefan-haudum/profil/spieler/156681.
Transfer history data appended for: https://www.transfermarkt.com/lukas-grgic/profil/spieler/224871.
Transfer history data appended for: https://www.transfermarkt.com/james-holland/profil/spieler/43158.
Transfer history data appended for: https://www.transfermarkt.com/peter-michorl/profil/spieler/158106.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-drame/profil/spieler/649028.
Transfer history data appended for: https://www.transfermarkt.com/tobias-lawal/profil/spieler/393686.
Transfer history data appended for: https://www.transfermarkt.com/johannes-eggestein/profil/spieler/251303.
Transfer history data appended for: https://www.transfermarkt.com/thomas-goiginger/profil/spieler/189912.
Transfer history data appended for: https://www.transfermarkt.com/reinhold-ranftl/profil/spieler/83119.
Transfer history data appended for: https://www.transfermarkt.com/thomas-sabitzer/profil/spieler/394032.
Transfer history data appended for: https://www.transfermarkt.com/christian-ramsebner/profil/spieler/37820.
Transfer history data appended for: https://www.transfermarkt.com/marko-raguz/profil/spieler/307664.
Transfer history data appended for: https://www.transfermarkt.com/andreas-gruber/profil/spieler/194477.
Transfer history data appended for: https://www.transfermarkt.com/andres-andrade/profil/spieler/403808.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-cheberko/profil/spieler/343153.
Transfer history data appended for: https://www.transfermarkt.com/alexander-schlager/profil/spieler/186374.
Transfer history data appended for: https://www.transfermarkt.com/gernot-trauner/profil/spieler/59145.
Transfer history data appended for: https://www.transfermarkt.com/husein-balic/profil/spieler/241803.
Transfer history data appended for: https://www.transfermarkt.com/patrick-plojer/profil/spieler/434111.

Transfer history data appended for: https://www.transfermarkt.com/thomas-turner/profil/spieler/316729.
Transfer history data appended for: https://www.transfermarkt.com/petar-filipovic/profil/spieler/85922.
Transfer history data appended for: https://www.transfermarkt.com/mads-emil-madsen/profil/spieler/422950.
Transfer history data appended for: https://www.transfermarkt.com/dominik-reiter/profil/spieler/307667.
Transfer history data appended for: https://www.transfermarkt.com/valentino-muller/profil/spieler/307817.
Transfer history data appended for: https://www.transfermarkt.com/marvin-potzmann/profil/spieler/106869.
Transfer history data appended for: https://www.transfermarkt.com/mamoudou-karamoko/profil/spieler/646782.
Transfer history data appended for: https://www.transfermarkt.com/philipp-wiesinger/profil/spieler/159139.
Transfer history data appended for: https://www.transfermarkt.com/rene-renner/profil/spieler/212333.
Transfer history data appended for: https://www.transfermarkt.com/pablo-palacio/profil/spieler/655659.
Transfer history data appended for: https://www.transfermarkt.com/walter-bou/profil/spieler/334233.
Transfer history data appended for: https://www.transfermarkt.com/daniel-juarez/profil/spieler/742539.
Transfer history data appended for: https://www.transfermarkt.com/nery-leyes/profil/spieler/280204.
Transfer history data appended for: https://www.transfermarkt.com/nelson-acevedo/profil/spieler/125184.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-carabajal/profil/spieler/280157.
Transfer history data appended for: https://www.transfermarkt.com/franco-troyansky/profil/spieler/424673.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-andereggen/profil/spieler/409093.
Transfer history data appended for: https://www.transfermarkt.com/damian-martinez/profil/spieler/107282.
Transfer history data appended for: https://www.transfermarkt.com/brian-blasi/profil/spieler/409090.
Transfer history data appended for: https://www.transfermarkt.com/claudio-corvalan/profil/spieler/125108.
Transfer history data appended for: https://www.transfermarkt.com/jalil-elias/profil/spieler/376859.
Transfer history data appended for: https://www.transfermarkt.com/javier-mendez/profil/spieler/285772.
Transfer history data appended for: https://www.transfermarkt.com/federico-milo/profil/spieler/283395.
Transfer history data appended for: https://www.transfermarkt.com/mauro-luna-diale/profil/spieler/653266.
Transfer history data appended for: https://www.transfermarkt.com/franco-calderon/profil/spieler/667616.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-bottinelli/profil/spieler/19947.
Transfer history data appended for: https://www.transfermarkt.com/gaston-comas/profil/spieler/689210.
Transfer history data appended for: https://www.transfermarkt.com/lucas-rios/profil/spieler/647894.
Transfer history data appended for: https://www.transfermarkt.com/fernando-marquez/profil/spieler/75597.
Transfer history data appended for: https://www.transfermarkt.com/alan-sosa/profil/spieler/545408.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-mazzola/profil/spieler/90797.
Transfer history data appended for: https://www.transfermarkt.com/juan-manuel-garcia/profil/spieler/457244.
Transfer history data appended for: https://www.transfermarkt.com/juan-ignacio-nardoni/profil/spieler/689211.
Transfer history data appended for: https://www.transfermarkt.com/martin-canete/profil/spieler/746185.
Transfer history data appended for: https://www.transfermarkt.com/fernando-elizari/profil/spieler/223024.
Transfer history data appended for: https://www.transfermarkt.com/federico-vera/profil/spieler/829967.
Transfer history data appended for: https://www.transfermarkt.com/gaston-gonzalez/profil/spieler/689052.
Transfer history data appended for: https://www.transfermarkt.com/braian-alvarez/profil/spieler/545618.
Transfer history data appended for: https://www.transfermarkt.com/franco-godoy/profil/spieler/579974.
Transfer history data appended for: https://www.transfermarkt.com/francisco-gerometta/profil/spieler/745789.
Transfer history data appended for: https://www.transfermarkt.com/marcos-peano/profil/spieler/360338.
Transfer history data appended for: https://www.transfermarkt.com/yeimar-gomez-andrade/profil/spieler/343359.
Transfer history data appended for: https://www.transfermarkt.com/matias-nani/profil/spieler/486597.
Transfer history data appended for: https://www.transfermarkt.com/federico-bonansea/profil/spieler/360203.
Transfer history data appended for: https://www.transfermarkt.com/jorge-zules/profil/spieler/610261.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-moyano/profil/spieler/148789.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-assis/profil/spieler/209708.
Transfer history data appended for: https://www.transfermarkt.com/javier-cabrera/profil/spieler/147131.
Transfer history data appended for: https://www.transfermarkt.com/alfredo-pussetto/profil/spieler/323834.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-galvan/profil/spieler/216730.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-bonifacio/profil/spieler/334224.
Transfer history data appended for: https://www.transfermarkt.com/francesco-lo-celso/profil/spieler/642757.
Transfer history data appended for: https://www.transfermarkt.com/diego-novaretti/profil/spieler/87493.
Transfer history data appended for: https://www.transfermarkt.com/josue-ayala/profil/spieler/55955.
Transfer history data appended for: https://www.transfermarkt.com/matias-caruzzo/profil/spieler/56573.
Transfer history data appended for: https://www.transfermarkt.com/luciano-ferreyra/profil/spieler/661139.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-gonzalez/profil/spieler/659589.
Transfer history data appended for: https://www.transfermarkt.com/agustin-allione/profil/spieler/189411.
Transfer history data appended for: https://www.transfermarkt.com/ciro-rius/profil/spieler/101875.
Transfer history data appended for: https://www.transfermarkt.com/luca-martinez-dupuy/profil/spieler/831110.
Transfer history data appended for: https://www.transfermarkt.com/gino-infantino/profil/spieler/831162.
Transfer history data appended for: https://www.transfermarkt.com/joan-mazzaco/profil/spieler/491692.
Transfer history data appended for: https://www.transfermarkt.com/damian-martinez/profil/spieler/107282.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-britez/profil/spieler/262851.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-mino/profil/spieler/508135.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-molina/profil/spieler/424042.
Transfer history data appended for: https://www.transfermarkt.com/fernando-torrent/profil/spieler/433772.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-vecchio/profil/spieler/75728.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-bottinelli/profil/spieler/19947.
Transfer history data appended for: https://www.transfermarkt.com/lucas-gamba/profil/spieler/125906.
Transfer history data appended for: https://www.transfermarkt.com/claudio-riano/profil/spieler/238011.
Transfer history data appended for: https://www.transfermarkt.com/diego-zabala/profil/spieler/177562.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-colazo/profil/spieler/116277.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-blanco/profil/spieler/831161.
Transfer history data appended for: https://www.transfermarkt.com/facundo-almada/profil/spieler/639390.
Transfer history data appended for: https://www.transfermarkt.com/alan-bonansea/profil/spieler/538609.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-laso/profil/spieler/360797.
Transfer history data appended for: https://www.transfermarkt.com/alfonso-parot/profil/spieler/84238.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-gil/profil/spieler/125907.

Transfer history data appended for: https://www.transfermarkt.com/cristian-gonzalez/profil/spieler/358738.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-russo/profil/spieler/833130.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-villagra/profil/spieler/657220.
Transfer history data appended for: https://www.transfermarkt.com/jonas-aguirre/profil/spieler/149436.
Transfer history data appended for: https://www.transfermarkt.com/leonel-rivas/profil/spieler/471655.
Transfer history data appended for: https://www.transfermarkt.com/miguel-barbieri/profil/spieler/431703.
Transfer history data appended for: https://www.transfermarkt.com/alan-marinelli/profil/spieler/669677.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-lovera/profil/spieler/441422.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-ojeda/profil/spieler/471657.
Transfer history data appended for: https://www.transfermarkt.com/kevin-gutierrez/profil/spieler/554799.
Transfer history data appended for: https://www.transfermarkt.com/fabio-pereyra/profil/spieler/610248.
Transfer history data appended for: https://www.transfermarkt.com/lucas-necul/profil/spieler/578761.
Transfer history data appended for: https://www.transfermarkt.com/gaston-alvarez-suarez/profil/spieler/213191.
Transfer history data appended for: https://www.transfermarkt.com/bruno-baez/profil/spieler/838389.
Transfer history data appended for: https://www.transfermarkt.com/julian-navas/profil/spieler/274970.
Transfer history data appended for: https://www.transfermarkt.com/facundo-pons/profil/spieler/615257.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-parisi/profil/spieler/610569.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-castro/profil/spieler/441160.
Transfer history data appended for: https://www.transfermarkt.com/juan-cruz-kaprof/profil/spieler/282365.
Transfer history data appended for: https://www.transfermarkt.com/pablo-alvarez/profil/spieler/55993.
Transfer history data appended for: https://www.transfermarkt.com/daniel-sappa/profil/spieler/423438.
Transfer history data appended for: https://www.transfermarkt.com/ramiro-luna/profil/spieler/818912.
Transfer history data appended for: https://www.transfermarkt.com/mateo-carabajal/profil/spieler/578757.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-rescaldani/profil/spieler/164477.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-mendez/profil/spieler/149478.
Transfer history data appended for: https://www.transfermarkt.com/diego-nunez/profil/spieler/498133.
Transfer history data appended for: https://www.transfermarkt.com/ruben-zamponi/profil/spieler/11924.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-gariglio/profil/spieler/830848.
Transfer history data appended for: https://www.transfermarkt.com/fernando-torrent/profil/spieler/433772.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-gimenez/profil/spieler/364946.
Transfer history data appended for: https://www.transfermarkt.com/jesus-soraire/profil/spieler/610251.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-rivero/profil/spieler/597258.
Transfer history data appended for: https://www.transfermarkt.com/juan-manuel-garcia/profil/spieler/457244.
Transfer history data appended for: https://www.transfermarkt.com/leonel-picco/profil/spieler/663077.
Transfer history data appended for: https://www.transfermarkt.com/jhonatan-candia/profil/spieler/259917.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-ramirez/profil/spieler/838388.
Transfer history data appended for: https://www.transfermarkt.com/marcos-abreliano/profil/spieler/578760.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-miracco/profil/spieler/252591.
Transfer history data appended for: https://www.transfermarkt.com/gaston-suso/profil/spieler/469776.
Transfer history data appended for: https://www.transfermarkt.com/franco-sbuttoni/profil/spieler/135872.
Transfer history data appended for: https://www.transfermarkt.com/facundo-kruspzky/profil/spieler/830847.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-piovi/profil/spieler/487346.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-papa/profil/spieler/30820.
Transfer history data appended for: https://www.transfermarkt.com/alejo-antilef/profil/spieler/563817.
Transfer history data appended for: https://www.transfermarkt.com/ramiro-balbuena/profil/spieler/833435.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-cerica/profil/spieler/440181.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-marchi/profil/spieler/642521.
Transfer history data appended for: https://www.transfermarkt.com/joel-sonora/profil/spieler/346644.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-gagliardo/profil/spieler/133912.
Transfer history data appended for: https://www.transfermarkt.com/matias-belloso/profil/spieler/818913.
Transfer history data appended for: https://www.transfermarkt.com/leonel-ferroni/profil/spieler/548903.
Transfer history data appended for: https://www.transfermarkt.com/jose-valencia/profil/spieler/119183.
Transfer history data appended for: https://www.transfermarkt.com/abel-arganaraz/profil/spieler/757905.
Transfer history data appended for: https://www.transfermarkt.com/mateo-montenegro/profil/spieler/728287.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-banegas/profil/spieler/697041.
Transfer history data appended for: https://www.transfermarkt.com/lucas-brochero/profil/spieler/830783.
Transfer history data appended for: https://www.transfermarkt.com/leonel-caffaratti/profil/spieler/497155.
Transfer history data appended for: https://www.transfermarkt.com/mauro-barraza/profil/spieler/612632.
Transfer history data appended for: https://www.transfermarkt.com/agustin-allione/profil/spieler/189411.
Transfer history data appended for: https://www.transfermarkt.com/leandro-vella/profil/spieler/441268.
Transfer history data appended for: https://www.transfermarkt.com/francisco-cerro/profil/spieler/125107.
Transfer history data appended for: https://www.transfermarkt.com/francisco-manenti/profil/spieler/653690.
Transfer history data appended for: https://www.transfermarkt.com/cristian-vega/profil/spieler/443689.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-correa/profil/spieler/74361.
Transfer history data appended for: https://www.transfermarkt.com/diego-rodriguez/profil/spieler/90800.
Transfer history data appended for: https://www.transfermarkt.com/marcos-sanchez/profil/spieler/143954.
Transfer history data appended for: https://www.transfermarkt.com/ariel-rojas/profil/spieler/57753.
Transfer history data appended for: https://www.transfermarkt.com/santiago-gallucci/profil/spieler/113129.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-romero/profil/spieler/612633.
Transfer history data appended for: https://www.transfermarkt.com/claudio-riano/profil/spieler/238011.
Transfer history data appended for: https://www.transfermarkt.com/oscar-salomon/profil/spieler/698323.
Transfer history data appended for: https://www.transfermarkt.com/ismael-quilez/profil/spieler/91360.
Transfer history data appended for: https://www.transfermarkt.com/cesar-taborda/profil/spieler/72900.
Transfer history data appended for: https://www.transfermarkt.com/cristian-diaz/profil/spieler/113021.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-barrios/profil/spieler/503377.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-maciel/profil/spieler/535033.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-herrera/profil/spieler/485880.
Transfer history data appended for: https://www.transfermarkt.com/hugo-vera-oviedo/profil/spieler/267794.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-femia/profil/spieler/691601.

Transfer history data appended for: https://www.transfermarkt.com/facundo-melivilo/profil/spieler/134564.
Transfer history data appended for: https://www.transfermarkt.com/lisandro-alzugaray/profil/spieler/396920.
Transfer history data appended for: https://www.transfermarkt.com/joao-rodriguez/profil/spieler/253125.
Transfer history data appended for: https://www.transfermarkt.com/juan-vieyra/profil/spieler/259074.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-miracco/profil/spieler/252591.
Transfer history data appended for: https://www.transfermarkt.com/leandro-requena/profil/spieler/89296.
Transfer history data appended for: https://www.transfermarkt.com/dany-cure/profil/spieler/258740.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-sanchez/profil/spieler/89246.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-villalba/profil/spieler/269817.
Transfer history data appended for: https://www.transfermarkt.com/franco-sbuttoni/profil/spieler/135872.
Transfer history data appended for: https://www.transfermarkt.com/matias-nani/profil/spieler/486597.
Transfer history data appended for: https://www.transfermarkt.com/juan-galeano/profil/spieler/196159.
Transfer history data appended for: https://www.transfermarkt.com/franco-cristaldo/profil/spieler/332259.
Transfer history data appended for: https://www.transfermarkt.com/federico-andueza/profil/spieler/365942.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-bay/profil/spieler/360425.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-cavallotti/profil/spieler/55862.
Transfer history data appended for: https://www.transfermarkt.com/matias-pato/profil/spieler/384760.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-galvan/profil/spieler/216730.
Transfer history data appended for: https://www.transfermarkt.com/ivan-ramirez/profil/spieler/531093.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-pasquini/profil/spieler/270987.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-thaller/profil/spieler/563923.
Transfer history data appended for: https://www.transfermarkt.com/pablo-martinez/profil/spieler/606268.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-morales/profil/spieler/576023.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-carrasco/profil/spieler/503005.
Transfer history data appended for: https://www.transfermarkt.com/matias-perez/profil/spieler/744416.
Transfer history data appended for: https://www.transfermarkt.com/lucas-acosta/profil/spieler/296799.
Transfer history data appended for: https://www.transfermarkt.com/agustin-rossi/profil/spieler/352324.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-acosta/profil/spieler/45307.
Transfer history data appended for: https://www.transfermarkt.com/alexis-perez/profil/spieler/313359.
Transfer history data appended for: https://www.transfermarkt.com/lucas-vera/profil/spieler/689628.
Transfer history data appended for: https://www.transfermarkt.com/kevin-lomonaco/profil/spieler/661136.
Transfer history data appended for: https://www.transfermarkt.com/luciano-abecasis/profil/spieler/149435.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-gomez/profil/spieler/282357.
Transfer history data appended for: https://www.transfermarkt.com/marcelino-moreno/profil/spieler/456617.
Transfer history data appended for: https://www.transfermarkt.com/facundo-quignon/profil/spieler/131218.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-sinisterra/profil/spieler/463055.
Transfer history data appended for: https://www.transfermarkt.com/dario-caceres/profil/spieler/567663.
Transfer history data appended for: https://www.transfermarkt.com/alejo-tabares/profil/spieler/756988.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-morgantini/profil/spieler/615253.
Transfer history data appended for: https://www.transfermarkt.com/julian-aude/profil/spieler/661128.
Transfer history data appended for: https://www.transfermarkt.com/tomas-belmonte/profil/spieler/483446.
Transfer history data appended for: https://www.transfermarkt.com/matias-esquivel/profil/spieler/739996.
Transfer history data appended for: https://www.transfermarkt.com/fernando-belluschi/profil/spieler/26460.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-valenti/profil/spieler/625202.
Transfer history data appended for: https://www.transfermarkt.com/pedro-de-la-vega/profil/spieler/618984.
Transfer history data appended for: https://www.transfermarkt.com/facundo-perez/profil/spieler/700182.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-torres/profil/spieler/838406.
Transfer history data appended for: https://www.transfermarkt.com/alexandro-bernabei/profil/spieler/719635.
Transfer history data appended for: https://www.transfermarkt.com/pablo-aranda/profil/spieler/829382.
Transfer history data appended for: https://www.transfermarkt.com/leonel-di-placido/profil/spieler/322843.
Transfer history data appended for: https://www.transfermarkt.com/matias-vera/profil/spieler/745786.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-krilanovich/profil/spieler/661155.
Transfer history data appended for: https://www.transfermarkt.com/brian-aguirre/profil/spieler/829378.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-orsini/profil/spieler/289149.
Transfer history data appended for: https://www.transfermarkt.com/franco-orozco/profil/spieler/661140.
Transfer history data appended for: https://www.transfermarkt.com/ousmane-ndong/profil/spieler/829380.
Transfer history data appended for: https://www.transfermarkt.com/favio-cabral/profil/spieler/748210.
Transfer history data appended for: https://www.transfermarkt.com/franco-fragueda/profil/spieler/656111.
Transfer history data appended for: https://www.transfermarkt.com/guido-herrera/profil/spieler/230014.
Transfer history data appended for: https://www.transfermarkt.com/franco-fragapane/profil/spieler/226005.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-alvez/profil/spieler/668510.
Transfer history data appended for: https://www.transfermarkt.com/diego-valoyes/profil/spieler/413983.
Transfer history data appended for: https://www.transfermarkt.com/pablo-solari/profil/spieler/756991.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-blazquez/profil/spieler/668996.
Transfer history data appended for: https://www.transfermarkt.com/piero-hincapie/profil/spieler/659813.
Transfer history data appended for: https://www.transfermarkt.com/juan-komar/profil/spieler/319691.
Transfer history data appended for: https://www.transfermarkt.com/exequiel-beltramone/profil/spieler/715800.
Transfer history data appended for: https://www.transfermarkt.com/marcos-diaz/profil/spieler/56006.
Transfer history data appended for: https://www.transfermarkt.com/mateo-retegui/profil/spieler/554903.
Transfer history data appended for: https://www.transfermarkt.com/mateo-mamani/profil/spieler/830110.
Transfer history data appended for: https://www.transfermarkt.com/renzo-paparelli/profil/spieler/652967.
Transfer history data appended for: https://www.transfermarkt.com/carlos-villalba/profil/spieler/652968.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-guzman/profil/spieler/626916.
Transfer history data appended for: https://www.transfermarkt.com/francis-mac-allister/profil/spieler/440380.
Transfer history data appended for: https://www.transfermarkt.com/juan-ignacio-mendez/profil/spieler/508134.
Transfer history data appended for: https://www.transfermarkt.com/jose-mauri/profil/spieler/240958.
Transfer history data appended for: https://www.transfermarkt.com/mauro-valiente/profil/spieler/621403.
Transfer history data appended for: https://www.transfermarkt.com/martin-payero/profil/spieler/555820.
Transfer history data appended for: https://www.transfermarkt.com/rafael-perez/profil/spieler/117874.

Transfer history data appended for: https://www.transfermarkt.com/mauricio-caranta/profil/spieler/12556.
Transfer history data appended for: https://www.transfermarkt.com/federico-navarro/profil/spieler/632131.
Transfer history data appended for: https://www.transfermarkt.com/facundo-medina/profil/spieler/474800.
Transfer history data appended for: https://www.transfermarkt.com/fernando-bersano/profil/spieler/533569.
Transfer history data appended for: https://www.transfermarkt.com/mauro-ortiz/profil/spieler/528398.
Transfer history data appended for: https://www.transfermarkt.com/junior-arias/profil/spieler/268652.
Transfer history data appended for: https://www.transfermarkt.com/javier-gandolfi/profil/spieler/26242.
Transfer history data appended for: https://www.transfermarkt.com/dayro-moreno/profil/spieler/42457.
Transfer history data appended for: https://www.transfermarkt.com/enzo-diaz/profil/spieler/540458.
Transfer history data appended for: https://www.transfermarkt.com/tomas-pochettino/profil/spieler/348354.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-tenaglia/profil/spieler/533568.
Transfer history data appended for: https://www.transfermarkt.com/julian-malatini/profil/spieler/830108.
Transfer history data appended for: https://www.transfermarkt.com/gaston-torres/profil/spieler/830109.
Transfer history data appended for: https://www.transfermarkt.com/leonel-rivas/profil/spieler/471655.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-lago/profil/spieler/813459.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-bustos/profil/spieler/439629.
Transfer history data appended for: https://www.transfermarkt.com/joel-sonora/profil/spieler/346644.
Transfer history data appended for: https://www.transfermarkt.com/augusto-schott/profil/spieler/670566.
Transfer history data appended for: https://www.transfermarkt.com/nelson-insfran/profil/spieler/660280.
Transfer history data appended for: https://www.transfermarkt.com/jesus-vargas/profil/spieler/457784.
Transfer history data appended for: https://www.transfermarkt.com/lucas-licht/profil/spieler/30815.
Transfer history data appended for: https://www.transfermarkt.com/matias-perez-garcia/profil/spieler/67439.
Transfer history data appended for: https://www.transfermarkt.com/lucas-barrios/profil/spieler/58516.
Transfer history data appended for: https://www.transfermarkt.com/khalil-caraballo/profil/spieler/702885.
Transfer history data appended for: https://www.transfermarkt.com/patricio-monti/profil/spieler/593943.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-coronel/profil/spieler/125082.
Transfer history data appended for: https://www.transfermarkt.com/eric-ramirez/profil/spieler/364945.
Transfer history data appended for: https://www.transfermarkt.com/agustin-bolivar/profil/spieler/534623.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-chavez/profil/spieler/566712.
Transfer history data appended for: https://www.transfermarkt.com/alexis-martin-arias/profil/spieler/360521.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-caire/profil/spieler/79974.
Transfer history data appended for: https://www.transfermarkt.com/jose-paradela/profil/spieler/639152.
Transfer history data appended for: https://www.transfermarkt.com/tomas-durso/profil/spieler/534625.
Transfer history data appended for: https://www.transfermarkt.com/brian-mansilla/profil/spieler/373374.
Transfer history data appended for: https://www.transfermarkt.com/paolo-goltz/profil/spieler/55183.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-cocimano/profil/spieler/745326.
Transfer history data appended for: https://www.transfermarkt.com/ivo-mammini/profil/spieler/748065.
Transfer history data appended for: https://www.transfermarkt.com/manuel-guanini/profil/spieler/376083.
Transfer history data appended for: https://www.transfermarkt.com/antonio-napolitano/profil/spieler/748064.
Transfer history data appended for: https://www.transfermarkt.com/lucas-miguez/profil/spieler/748063.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-morales/profil/spieler/457061.
Transfer history data appended for: https://www.transfermarkt.com/matias-melluso/profil/spieler/564216.
Transfer history data appended for: https://www.transfermarkt.com/victor-ayala/profil/spieler/122519.
Transfer history data appended for: https://www.transfermarkt.com/german-guiffrey/profil/spieler/610616.
Transfer history data appended for: https://www.transfermarkt.com/matias-gomez/profil/spieler/577923.
Transfer history data appended for: https://www.transfermarkt.com/jhonatan-agudelo/profil/spieler/313426.
Transfer history data appended for: https://www.transfermarkt.com/harrinson-mancilla/profil/spieler/460349.
Transfer history data appended for: https://www.transfermarkt.com/horacio-tijanovich/profil/spieler/380974.
Transfer history data appended for: https://www.transfermarkt.com/johan-carbonero/profil/spieler/572042.
Transfer history data appended for: https://www.transfermarkt.com/janeiler-rivas/profil/spieler/208729.
Transfer history data appended for: https://www.transfermarkt.com/tomas-fernandez/profil/spieler/639153.
Transfer history data appended for: https://www.transfermarkt.com/jorge-broun/profil/spieler/55150.
Transfer history data appended for: https://www.transfermarkt.com/matias-miranda/profil/spieler/714744.
Transfer history data appended for: https://www.transfermarkt.com/matias-garcia/profil/spieler/267393.
Transfer history data appended for: https://www.transfermarkt.com/franco-mussis/profil/spieler/74821.
Transfer history data appended for: https://www.transfermarkt.com/pablo-velazquez/profil/spieler/84282.
Transfer history data appended for: https://www.transfermarkt.com/claudio-spinelli/profil/spieler/504882.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-comba/profil/spieler/615182.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-weigandt/profil/spieler/491690.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-contin/profil/spieler/340164.
Transfer history data appended for: https://www.transfermarkt.com/mateo-coronel/profil/spieler/685179.
Transfer history data appended for: https://www.transfermarkt.com/enzo-ybanez/profil/spieler/534034.
Transfer history data appended for: https://www.transfermarkt.com/elias-gomez/profil/spieler/302139.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-centurion/profil/spieler/665933.
Transfer history data appended for: https://www.transfermarkt.com/matias-caruzzo/profil/spieler/56573.
Transfer history data appended for: https://www.transfermarkt.com/leandro-finochietto/profil/spieler/534036.
Transfer history data appended for: https://www.transfermarkt.com/diego-sosa/profil/spieler/345545.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-hauche/profil/spieler/54845.
Transfer history data appended for: https://www.transfermarkt.com/gaston-veron/profil/spieler/564001.
Transfer history data appended for: https://www.transfermarkt.com/franco-ibarra/profil/spieler/741685.
Transfer history data appended for: https://www.transfermarkt.com/damian-batallini/profil/spieler/421998.
Transfer history data appended for: https://www.transfermarkt.com/franco-moyano/profil/spieler/480764.
Transfer history data appended for: https://www.transfermarkt.com/francis-mac-allister/profil/spieler/440380.
Transfer history data appended for: https://www.transfermarkt.com/victorio-ramis/profil/spieler/381065.
Transfer history data appended for: https://www.transfermarkt.com/fausto-montero/profil/spieler/144237.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-forastiero/profil/spieler/709550.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-sandoval/profil/spieler/74268.
Transfer history data appended for: https://www.transfermarkt.com/daniel-saggiomo/profil/spieler/356503.
Transfer history data appended for: https://www.transfermarkt.com/agustin-aleo/profil/spieler/572088.

Transfer history data appended for: https://www.transfermarkt.com/matko-miljevic/profil/spieler/632797.
Transfer history data appended for: https://www.transfermarkt.com/santiago-silva/profil/spieler/7274.
Transfer history data appended for: https://www.transfermarkt.com/lucas-ambrogio/profil/spieler/697584.
Transfer history data appended for: https://www.transfermarkt.com/lucas-chaves/profil/spieler/360791.
Transfer history data appended for: https://www.transfermarkt.com/fausto-vera/profil/spieler/491701.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-florentin/profil/spieler/675341.
Transfer history data appended for: https://www.transfermarkt.com/marcos-angeleri/profil/spieler/27448.
Transfer history data appended for: https://www.transfermarkt.com/francisco-ilarregui/profil/spieler/339463.
Transfer history data appended for: https://www.transfermarkt.com/matias-romero/profil/spieler/605721.
Transfer history data appended for: https://www.transfermarkt.com/marco-di-cesare/profil/spieler/839029.
Transfer history data appended for: https://www.transfermarkt.com/edwar-lopez/profil/spieler/572077.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-silva/profil/spieler/422914.
Transfer history data appended for: https://www.transfermarkt.com/miguel-torren/profil/spieler/19992.
Transfer history data appended for: https://www.transfermarkt.com/juan-roman-pucheta/profil/spieler/830478.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-avalos/profil/spieler/358418.
Transfer history data appended for: https://www.transfermarkt.com/ivan-colman/profil/spieler/380603.
Transfer history data appended for: https://www.transfermarkt.com/luis-miguel-rodriguez/profil/spieler/87497.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-celis/profil/spieler/255944.
Transfer history data appended for: https://www.transfermarkt.com/facundo-garces/profil/spieler/533354.
Transfer history data appended for: https://www.transfermarkt.com/eric-meza/profil/spieler/830857.
Transfer history data appended for: https://www.transfermarkt.com/rafael-delgado/profil/spieler/167314.
Transfer history data appended for: https://www.transfermarkt.com/santiago-pierotti/profil/spieler/674806.
Transfer history data appended for: https://www.transfermarkt.com/juan-cruz-zurbriggen/profil/spieler/728222.
Transfer history data appended for: https://www.transfermarkt.com/gian-nardelli/profil/spieler/830853.
Transfer history data appended for: https://www.transfermarkt.com/federico-lertora/profil/spieler/125104.
Transfer history data appended for: https://www.transfermarkt.com/braian-galvan/profil/spieler/533566.
Transfer history data appended for: https://www.transfermarkt.com/jorge-ortega/profil/spieler/234626.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-ortiz/profil/spieler/213543.
Transfer history data appended for: https://www.transfermarkt.com/gaston-diaz/profil/spieler/68748.
Transfer history data appended for: https://www.transfermarkt.com/tomas-chancalay/profil/spieler/533565.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-burian/profil/spieler/72649.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-hass/profil/spieler/649786.
Transfer history data appended for: https://www.transfermarkt.com/alex-vigo/profil/spieler/648520.
Transfer history data appended for: https://www.transfermarkt.com/wilson-morelo/profil/spieler/74065.
Transfer history data appended for: https://www.transfermarkt.com/mauro-da-luz/profil/spieler/458603.
Transfer history data appended for: https://www.transfermarkt.com/mateo-hernandez/profil/spieler/637859.
Transfer history data appended for: https://www.transfermarkt.com/bruno-bianchi/profil/spieler/55998.
Transfer history data appended for: https://www.transfermarkt.com/fernando-zuqui/profil/spieler/248763.
Transfer history data appended for: https://www.transfermarkt.com/tomas-sandoval/profil/spieler/437964.
Transfer history data appended for: https://www.transfermarkt.com/facundo-farias/profil/spieler/728221.
Transfer history data appended for: https://www.transfermarkt.com/brian-fernandez/profil/spieler/267676.
Transfer history data appended for: https://www.transfermarkt.com/agustin-doffo/profil/spieler/374858.
Transfer history data appended for: https://www.transfermarkt.com/tomas-moschion/profil/spieler/631887.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-chicco/profil/spieler/503329.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-olivera/profil/spieler/105845.
Transfer history data appended for: https://www.transfermarkt.com/franco-quiroz/profil/spieler/534032.
Transfer history data appended for: https://www.transfermarkt.com/brian-farioli/profil/spieler/710281.
Transfer history data appended for: https://www.transfermarkt.com/cristian-bernardi/profil/spieler/267572.
Transfer history data appended for: https://www.transfermarkt.com/yeiler-goez/profil/spieler/585358.
Transfer history data appended for: https://www.transfermarkt.com/damian-schmidt/profil/spieler/267639.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-piovi/profil/spieler/284120.
Transfer history data appended for: https://www.transfermarkt.com/rafael-garcia/profil/spieler/159904.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-escobar/profil/spieler/440377.
Transfer history data appended for: https://www.transfermarkt.com/lucas-acevedo/profil/spieler/284306.
Transfer history data appended for: https://www.transfermarkt.com/lucas-gonzalez/profil/spieler/688778.
Transfer history data appended for: https://www.transfermarkt.com/renzo-bacchia/profil/spieler/612873.
Transfer history data appended for: https://www.transfermarkt.com/domingo-blanco/profil/spieler/285127.
Transfer history data appended for: https://www.transfermarkt.com/juan-ignacio-pacchini/profil/spieler/830784.
Transfer history data appended for: https://www.transfermarkt.com/alexander-barboza/profil/spieler/379752.
Transfer history data appended for: https://www.transfermarkt.com/alan-velasco/profil/spieler/661154.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-messiniti/profil/spieler/546692.
Transfer history data appended for: https://www.transfermarkt.com/alan-franco/profil/spieler/503343.
Transfer history data appended for: https://www.transfermarkt.com/pablo-hernandez/profil/spieler/91763.
Transfer history data appended for: https://www.transfermarkt.com/milton-alvarez/profil/spieler/526527.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-domingo/profil/spieler/39150.
Transfer history data appended for: https://www.transfermarkt.com/lucas-rodriguez/profil/spieler/171593.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-del-castillo/profil/spieler/830785.
Transfer history data appended for: https://www.transfermarkt.com/gaston-togni/profil/spieler/503342.
Transfer history data appended for: https://www.transfermarkt.com/francisco-pizzini/profil/spieler/213122.
Transfer history data appended for: https://www.transfermarkt.com/marcos-landaburu/profil/spieler/830786.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-asis/profil/spieler/549958.
Transfer history data appended for: https://www.transfermarkt.com/thomas-ortega/profil/spieler/742593.
Transfer history data appended for: https://www.transfermarkt.com/jorge-figal/profil/spieler/334055.
Transfer history data appended for: https://www.transfermarkt.com/alan-sonora/profil/spieler/688779.
Transfer history data appended for: https://www.transfermarkt.com/lucas-romero/profil/spieler/242201.
Transfer history data appended for: https://www.transfermarkt.com/sergio-barreto/profil/spieler/556047.
Transfer history data appended for: https://www.transfermarkt.com/diego-mercado/profil/spieler/556049.
Transfer history data appended for: https://www.transfermarkt.com/braian-martinez/profil/spieler/739995.
Transfer history data appended for: https://www.transfermarkt.com/martin-benitez/profil/spieler/189418.

Transfer history data appended for: https://www.transfermarkt.com/fabricio-bustos/profil/spieler/275381.
Transfer history data appended for: https://www.transfermarkt.com/juan-di-lorenzo/profil/spieler/401574.
Transfer history data appended for: https://www.transfermarkt.com/juan-sanchez-mino/profil/spieler/169249.
Transfer history data appended for: https://www.transfermarkt.com/gaston-silva/profil/spieler/189452.
Transfer history data appended for: https://www.transfermarkt.com/francisco-silva/profil/spieler/84870.
Transfer history data appended for: https://www.transfermarkt.com/cecilio-dominguez/profil/spieler/273012.
Transfer history data appended for: https://www.transfermarkt.com/carlos-benavidez/profil/spieler/431190.
Transfer history data appended for: https://www.transfermarkt.com/pablo-becker/profil/spieler/171610.
Transfer history data appended for: https://www.transfermarkt.com/matias-villarreal/profil/spieler/441076.
Transfer history data appended for: https://www.transfermarkt.com/malcom-braida/profil/spieler/552185.
Transfer history data appended for: https://www.transfermarkt.com/facundo-tobares/profil/spieler/633046.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-yeri/profil/spieler/140603.
Transfer history data appended for: https://www.transfermarkt.com/lucas-villalba/profil/spieler/240913.
Transfer history data appended for: https://www.transfermarkt.com/cain-fara/profil/spieler/619072.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-indacoechea/profil/spieler/688162.
Transfer history data appended for: https://www.transfermarkt.com/franco-perinciolo/profil/spieler/830347.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-rinaldi/profil/spieler/283602.
Transfer history data appended for: https://www.transfermarkt.com/federico-gino/profil/spieler/273130.
Transfer history data appended for: https://www.transfermarkt.com/franco-perez/profil/spieler/639358.
Transfer history data appended for: https://www.transfermarkt.com/hernan-burbano/profil/spieler/176255.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-bazzana/profil/spieler/497157.
Transfer history data appended for: https://www.transfermarkt.com/facundo-bertoglio/profil/spieler/107525.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-iniguez/profil/spieler/542138.
Transfer history data appended for: https://www.transfermarkt.com/federico-milo/profil/spieler/283395.
Transfer history data appended for: https://www.transfermarkt.com/leandro-maciel/profil/spieler/438923.
Transfer history data appended for: https://www.transfermarkt.com/roman-martinez/profil/spieler/53134.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-contreras/profil/spieler/266906.
Transfer history data appended for: https://www.transfermarkt.com/lucas-di-yorio/profil/spieler/439108.
Transfer history data appended for: https://www.transfermarkt.com/francisco-grahl/profil/spieler/494220.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-rincon/profil/spieler/223917.
Transfer history data appended for: https://www.transfermarkt.com/javier-iritier/profil/spieler/471654.
Transfer history data appended for: https://www.transfermarkt.com/fabian-assmann/profil/spieler/55904.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-artola/profil/spieler/748244.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-schunke/profil/spieler/78232.
Transfer history data appended for: https://www.transfermarkt.com/federico-andrada/profil/spieler/234249.
Transfer history data appended for: https://www.transfermarkt.com/luciano-pocrnjic/profil/spieler/26469.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-zarate/profil/spieler/748246.
Transfer history data appended for: https://www.transfermarkt.com/fernando-roman/profil/spieler/836251.
Transfer history data appended for: https://www.transfermarkt.com/marcos-miers/profil/spieler/140784.
Transfer history data appended for: https://www.transfermarkt.com/manuel-panaro/profil/spieler/836252.
Transfer history data appended for: https://www.transfermarkt.com/uriel-ramirez/profil/spieler/830344.
Transfer history data appended for: https://www.transfermarkt.com/felipe-rodriguez/profil/spieler/202906.
Transfer history data appended for: https://www.transfermarkt.com/yoel-juarez/profil/spieler/660286.
Transfer history data appended for: https://www.transfermarkt.com/nazareno-solis/profil/spieler/419660.
Transfer history data appended for: https://www.transfermarkt.com/mario-lopez/profil/spieler/364373.
Transfer history data appended for: https://www.transfermarkt.com/luis-ingolotti/profil/spieler/552636.
Transfer history data appended for: https://www.transfermarkt.com/leonel-galeano/profil/spieler/124244.
Transfer history data appended for: https://www.transfermarkt.com/joel-carli/profil/spieler/87323.
Transfer history data appended for: https://www.transfermarkt.com/gaston-gil-romero/profil/spieler/222052.
Transfer history data appended for: https://www.transfermarkt.com/fernando-evangelista/profil/spieler/240058.
Transfer history data appended for: https://www.transfermarkt.com/franco-quinteros/profil/spieler/567241.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-bertolo/profil/spieler/52903.
Transfer history data appended for: https://www.transfermarkt.com/alexis-maldonado/profil/spieler/444100.
Transfer history data appended for: https://www.transfermarkt.com/giuliano-galoppo/profil/spieler/567249.
Transfer history data appended for: https://www.transfermarkt.com/reinaldo-lenis/profil/spieler/268093.
Transfer history data appended for: https://www.transfermarkt.com/ivan-arboleda/profil/spieler/260740.
Transfer history data appended for: https://www.transfermarkt.com/nery-leyes/profil/spieler/280204.
Transfer history data appended for: https://www.transfermarkt.com/fabian-bordagaray/profil/spieler/110320.
Transfer history data appended for: https://www.transfermarkt.com/agustin-fontana/profil/spieler/345229.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-arciero/profil/spieler/322649.
Transfer history data appended for: https://www.transfermarkt.com/israel-damonte/profil/spieler/20129.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-cuero/profil/spieler/211395.
Transfer history data appended for: https://www.transfermarkt.com/facundo-cambeses/profil/spieler/435001.
Transfer history data appended for: https://www.transfermarkt.com/luciano-pons/profil/spieler/538770.
Transfer history data appended for: https://www.transfermarkt.com/jorge-rodriguez/profil/spieler/333760.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-benega/profil/spieler/606271.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-alvarez/profil/spieler/534615.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-dubarbier/profil/spieler/55866.
Transfer history data appended for: https://www.transfermarkt.com/martin-payero/profil/spieler/555820.
Transfer history data appended for: https://www.transfermarkt.com/matias-gonzalez/profil/spieler/831160.
Transfer history data appended for: https://www.transfermarkt.com/julian-carranza/profil/spieler/491707.
Transfer history data appended for: https://www.transfermarkt.com/matias-moya/profil/spieler/476616.
Transfer history data appended for: https://www.transfermarkt.com/agustin-urzi/profil/spieler/636441.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-coronel/profil/spieler/565194.
Transfer history data appended for: https://www.transfermarkt.com/facundo-altamirano/profil/spieler/362358.
Transfer history data appended for: https://www.transfermarkt.com/jonas-gutierrez/profil/spieler/26443.
Transfer history data appended for: https://www.transfermarkt.com/alexis-sosa/profil/spieler/462768.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-asenjo/profil/spieler/333762.
Transfer history data appended for: https://www.transfermarkt.com/claudio-bravo/profil/spieler/441408.

Transfer history data appended for: https://www.transfermarkt.com/claudio-villagra/profil/spieler/334511.
Transfer history data appended for: https://www.transfermarkt.com/esteban-conde/profil/spieler/59256.
Transfer history data appended for: https://www.transfermarkt.com/junior-arias/profil/spieler/268652.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-linares/profil/spieler/534616.
Transfer history data appended for: https://www.transfermarkt.com/pablo-velazquez/profil/spieler/84282.
Transfer history data appended for: https://www.transfermarkt.com/juan-manuel-cruz/profil/spieler/748316.
Transfer history data appended for: https://www.transfermarkt.com/luciano-gomez/profil/spieler/423705.
Transfer history data appended for: https://www.transfermarkt.com/federico-torres/profil/spieler/728264.
Transfer history data appended for: https://www.transfermarkt.com/luis-sequeira/profil/spieler/668550.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-piatti/profil/spieler/37433.
Transfer history data appended for: https://www.transfermarkt.com/hector-fertoli/profil/spieler/424024.
Transfer history data appended for: https://www.transfermarkt.com/matias-palacios/profil/spieler/621370.
Transfer history data appended for: https://www.transfermarkt.com/adolfo-gaich/profil/spieler/608469.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-rodriguez/profil/spieler/19998.
Transfer history data appended for: https://www.transfermarkt.com/mauro-pitton/profil/spieler/376710.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-donatti/profil/spieler/119646.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-fernandez-mercau/profil/spieler/739315.
Transfer history data appended for: https://www.transfermarkt.com/victor-salazar/profil/spieler/347749.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-rojas/profil/spieler/471639.
Transfer history data appended for: https://www.transfermarkt.com/oscar-romero/profil/spieler/217886.
Transfer history data appended for: https://www.transfermarkt.com/franco-di-santo/profil/spieler/59783.
Transfer history data appended for: https://www.transfermarkt.com/gino-peruzzi/profil/spieler/138110.
Transfer history data appended for: https://www.transfermarkt.com/adam-bareiro/profil/spieler/514120.
Transfer history data appended for: https://www.transfermarkt.com/ruben-botta/profil/spieler/88542.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-blandi/profil/spieler/153022.
Transfer history data appended for: https://www.transfermarkt.com/ramon-arias/profil/spieler/131095.
Transfer history data appended for: https://www.transfermarkt.com/marcos-senesi/profil/spieler/469781.
Transfer history data appended for: https://www.transfermarkt.com/santiago-vergini/profil/spieler/94783.
Transfer history data appended for: https://www.transfermarkt.com/jose-devecchi/profil/spieler/282684.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-barrios/profil/spieler/503377.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-herrera/profil/spieler/485880.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-ferrari/profil/spieler/340507.
Transfer history data appended for: https://www.transfermarkt.com/fernando-belluschi/profil/spieler/26460.
Transfer history data appended for: https://www.transfermarkt.com/lucas-menossi/profil/spieler/225481.
Transfer history data appended for: https://www.transfermarkt.com/diego-rodriguez/profil/spieler/127828.
Transfer history data appended for: https://www.transfermarkt.com/federico-gattoni/profil/spieler/660735.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-navarro/profil/spieler/26727.
Transfer history data appended for: https://www.transfermarkt.com/angel-romero/profil/spieler/262262.
Transfer history data appended for: https://www.transfermarkt.com/elias-pereyra/profil/spieler/576027.
Transfer history data appended for: https://www.transfermarkt.com/juan-ramirez/profil/spieler/190756.
Transfer history data appended for: https://www.transfermarkt.com/francisco-flores/profil/spieler/661129.
Transfer history data appended for: https://www.transfermarkt.com/agustin-hausch/profil/spieler/668514.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-herrera/profil/spieler/621369.
Transfer history data appended for: https://www.transfermarkt.com/manuel-insaurralde/profil/spieler/627237.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-lopez-kaleniuk/profil/spieler/688589.
Transfer history data appended for: https://www.transfermarkt.com/alexis-sabella/profil/spieler/756812.
Transfer history data appended for: https://www.transfermarkt.com/alexander-diaz/profil/spieler/618986.
Transfer history data appended for: https://www.transfermarkt.com/mariano-peralta-bauer/profil/spieler/748602.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-reniero/profil/spieler/496415.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-fernandez/profil/spieler/333921.
Transfer history data appended for: https://www.transfermarkt.com/bruno-pitton/profil/spieler/395216.
Transfer history data appended for: https://www.transfermarkt.com/julian-palacios/profil/spieler/728262.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-maciel/profil/spieler/666330.
Transfer history data appended for: https://www.transfermarkt.com/cristian-medina/profil/spieler/661133.
Transfer history data appended for: https://www.transfermarkt.com/walter-bou/profil/spieler/334233.
Transfer history data appended for: https://www.transfermarkt.com/gaston-gerzel/profil/spieler/830479.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-maroni/profil/spieler/441385.
Transfer history data appended for: https://www.transfermarkt.com/javier-garcia/profil/spieler/7966.
Transfer history data appended for: https://www.transfermarkt.com/ivan-marcone/profil/spieler/90451.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-perez/profil/spieler/182108.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-jara/profil/spieler/116163.
Transfer history data appended for: https://www.transfermarkt.com/esteban-andrada/profil/spieler/105888.
Transfer history data appended for: https://www.transfermarkt.com/edwin-cardona/profil/spieler/119342.
Transfer history data appended for: https://www.transfermarkt.com/marcos-diaz/profil/spieler/56006.
Transfer history data appended for: https://www.transfermarkt.com/exequiel-zeballos/profil/spieler/661132.
Transfer history data appended for: https://www.transfermarkt.com/alan-varela/profil/spieler/756990.
Transfer history data appended for: https://www.transfermarkt.com/agustin-rossi/profil/spieler/352324.
Transfer history data appended for: https://www.transfermarkt.com/carlos-izquierdoz/profil/spieler/116968.
Transfer history data appended for: https://www.transfermarkt.com/jorman-campuzano/profil/spieler/459467.
Transfer history data appended for: https://www.transfermarkt.com/paolo-goltz/profil/spieler/55183.
Transfer history data appended for: https://www.transfermarkt.com/eduardo-salvio/profil/spieler/84535.
Transfer history data appended for: https://www.transfermarkt.com/daniele-de-rossi/profil/spieler/5947.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-capaldo/profil/spieler/649672.
Transfer history data appended for: https://www.transfermarkt.com/manuel-roffo/profil/spieler/491687.
Transfer history data appended for: https://www.transfermarkt.com/diego-gonzalez/profil/spieler/54578.
Transfer history data appended for: https://www.transfermarkt.com/aaron-molinas/profil/spieler/575999.
Transfer history data appended for: https://www.transfermarkt.com/agustin-almendra/profil/spieler/491698.
Transfer history data appended for: https://www.transfermarkt.com/alexis-mac-allister/profil/spieler/534033.
Transfer history data appended for: https://www.transfermarkt.com/ramon-abila/profil/spieler/88049.

Transfer history data appended for: https://www.transfermarkt.com/agustin-obando/profil/spieler/491706.
Transfer history data appended for: https://www.transfermarkt.com/junior-alonso/profil/spieler/273000.
Transfer history data appended for: https://www.transfermarkt.com/julio-buffarini/profil/spieler/89281.
Transfer history data appended for: https://www.transfermarkt.com/enzo-roldan/profil/spieler/814970.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-mas/profil/spieler/77153.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-villa/profil/spieler/493000.
Transfer history data appended for: https://www.transfermarkt.com/frank-fabra/profil/spieler/156561.
Transfer history data appended for: https://www.transfermarkt.com/renzo-giampaoli/profil/spieler/838405.
Transfer history data appended for: https://www.transfermarkt.com/carlos-tevez/profil/spieler/4276.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-reynoso/profil/spieler/439626.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-fernandez/profil/spieler/220647.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-weigandt/profil/spieler/491690.
Transfer history data appended for: https://www.transfermarkt.com/gaston-avila/profil/spieler/748601.
Transfer history data appended for: https://www.transfermarkt.com/leonel-ferroni/profil/spieler/548903.
Transfer history data appended for: https://www.transfermarkt.com/denis-rodriguez/profil/spieler/381347.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-castro/profil/spieler/565899.
Transfer history data appended for: https://www.transfermarkt.com/maxi-rodriguez/profil/spieler/7895.
Transfer history data appended for: https://www.transfermarkt.com/manuel-llano/profil/spieler/756811.
Transfer history data appended for: https://www.transfermarkt.com/mauro-formica/profil/spieler/55870.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-scocco/profil/spieler/51088.
Transfer history data appended for: https://www.transfermarkt.com/jeronimo-cacciabue/profil/spieler/563819.
Transfer history data appended for: https://www.transfermarkt.com/anibal-moreno/profil/spieler/642758.
Transfer history data appended for: https://www.transfermarkt.com/alan-aguerre/profil/spieler/269784.
Transfer history data appended for: https://www.transfermarkt.com/juan-sforza/profil/spieler/659264.
Transfer history data appended for: https://www.transfermarkt.com/francisco-fydriszewski/profil/spieler/337921.
Transfer history data appended for: https://www.transfermarkt.com/stefano-callegari/profil/spieler/556300.
Transfer history data appended for: https://www.transfermarkt.com/mateo-maccari/profil/spieler/723699.
Transfer history data appended for: https://www.transfermarkt.com/mariano-bittolo/profil/spieler/105842.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-salinas/profil/spieler/125750.
Transfer history data appended for: https://www.transfermarkt.com/alexis-rodriguez/profil/spieler/553423.
Transfer history data appended for: https://www.transfermarkt.com/matias-orihuela/profil/spieler/338170.
Transfer history data appended for: https://www.transfermarkt.com/manuel-guanini/profil/spieler/376083.
Transfer history data appended for: https://www.transfermarkt.com/facundo-nadalin/profil/spieler/554798.
Transfer history data appended for: https://www.transfermarkt.com/santiago-gentiletti/profil/spieler/30782.
Transfer history data appended for: https://www.transfermarkt.com/williams-barlasina/profil/spieler/836282.
Transfer history data appended for: https://www.transfermarkt.com/lucas-villarruel/profil/spieler/268499.
Transfer history data appended for: https://www.transfermarkt.com/cristian-lema/profil/spieler/147128.
Transfer history data appended for: https://www.transfermarkt.com/enzo-cabrera/profil/spieler/538527.
Transfer history data appended for: https://www.transfermarkt.com/francisco-gonzalez/profil/spieler/703564.
Transfer history data appended for: https://www.transfermarkt.com/brian-calderara/profil/spieler/830111.
Transfer history data appended for: https://www.transfermarkt.com/angelo-gabrielli/profil/spieler/285655.
Transfer history data appended for: https://www.transfermarkt.com/facundo-mansilla/profil/spieler/833783.
Transfer history data appended for: https://www.transfermarkt.com/julian-fernandez/profil/spieler/275319.
Transfer history data appended for: https://www.transfermarkt.com/ramiro-macagno/profil/spieler/401913.
Transfer history data appended for: https://www.transfermarkt.com/juan-manuel-requena/profil/spieler/637902.
Transfer history data appended for: https://www.transfermarkt.com/cristian-insaurralde/profil/spieler/238140.
Transfer history data appended for: https://www.transfermarkt.com/ramiro-sordo/profil/spieler/830112.
Transfer history data appended for: https://www.transfermarkt.com/nelson-ibanez/profil/spieler/75534.
Transfer history data appended for: https://www.transfermarkt.com/raul-lozano/profil/spieler/613093.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-cordero/profil/spieler/371840.
Transfer history data appended for: https://www.transfermarkt.com/martin-ojeda/profil/spieler/440988.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-mendive/profil/spieler/520847.
Transfer history data appended for: https://www.transfermarkt.com/lucas-barrios/profil/spieler/58516.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-romat/profil/spieler/67827.
Transfer history data appended for: https://www.transfermarkt.com/agustin-curruhinca/profil/spieler/728257.
Transfer history data appended for: https://www.transfermarkt.com/facundo-cambeses/profil/spieler/435001.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-faravelli/profil/spieler/181706.
Transfer history data appended for: https://www.transfermarkt.com/javier-mendoza/profil/spieler/300309.
Transfer history data appended for: https://www.transfermarkt.com/lucas-merolla/profil/spieler/424984.
Transfer history data appended for: https://www.transfermarkt.com/cesar-ibanez/profil/spieler/674391.
Transfer history data appended for: https://www.transfermarkt.com/walter-perez/profil/spieler/606272.
Transfer history data appended for: https://www.transfermarkt.com/fernando-cosciuc/profil/spieler/503368.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-cabral/profil/spieler/709552.
Transfer history data appended for: https://www.transfermarkt.com/cristian-nunez/profil/spieler/830476.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-bettini/profil/spieler/211087.
Transfer history data appended for: https://www.transfermarkt.com/carlos-araujo/profil/spieler/30674.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-cordero/profil/spieler/652948.
Transfer history data appended for: https://www.transfermarkt.com/mauro-bogado/profil/spieler/54822.
Transfer history data appended for: https://www.transfermarkt.com/juan-garro/profil/spieler/174042.
Transfer history data appended for: https://www.transfermarkt.com/antony-silva/profil/spieler/153235.
Transfer history data appended for: https://www.transfermarkt.com/juan-vieyra/profil/spieler/259074.
Transfer history data appended for: https://www.transfermarkt.com/fernando-pellegrino/profil/spieler/125843.
Transfer history data appended for: https://www.transfermarkt.com/saul-salcedo/profil/spieler/353035.
Transfer history data appended for: https://www.transfermarkt.com/agustin-casco/profil/spieler/627236.
Transfer history data appended for: https://www.transfermarkt.com/norberto-briasco/profil/spieler/457218.
Transfer history data appended for: https://www.transfermarkt.com/diego-mercado/profil/spieler/556049.
Transfer history data appended for: https://www.transfermarkt.com/santiago-hezze/profil/spieler/742803.
Transfer history data appended for: https://www.transfermarkt.com/pablo-oro/profil/spieler/745881.
Transfer history data appended for: https://www.transfermarkt.com/mariano-bareiro/profil/spieler/352326.

Transfer history data appended for: https://www.transfermarkt.com/joaquin-arzura/profil/spieler/288005.
Transfer history data appended for: https://www.transfermarkt.com/franco-cristaldo/profil/spieler/332259.
Transfer history data appended for: https://www.transfermarkt.com/leandro-grimi/profil/spieler/45317.
Transfer history data appended for: https://www.transfermarkt.com/braian-maidana/profil/spieler/740024.
Transfer history data appended for: https://www.transfermarkt.com/rafael-ferrario/profil/spieler/742802.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-gomez/profil/spieler/247672.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-navarro/profil/spieler/745877.
Transfer history data appended for: https://www.transfermarkt.com/patricio-toranzo/profil/spieler/26256.
Transfer history data appended for: https://www.transfermarkt.com/adrian-calello/profil/spieler/55911.
Transfer history data appended for: https://www.transfermarkt.com/federico-marin/profil/spieler/612728.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-bonifacio/profil/spieler/334224.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-ramirez/profil/spieler/728245.
Transfer history data appended for: https://www.transfermarkt.com/martin-aruga/profil/spieler/634811.
Transfer history data appended for: https://www.transfermarkt.com/leandro-marin/profil/spieler/113132.
Transfer history data appended for: https://www.transfermarkt.com/federico-mancinelli/profil/spieler/54356.
Transfer history data appended for: https://www.transfermarkt.com/mauro-gonzalez/profil/spieler/383636.
Transfer history data appended for: https://www.transfermarkt.com/pablo-cortizo/profil/spieler/66317.
Transfer history data appended for: https://www.transfermarkt.com/dardo-miloc/profil/spieler/118375.
Transfer history data appended for: https://www.transfermarkt.com/agustin-guiffrey/profil/spieler/566713.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-delgadillo/profil/spieler/372163.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-compagnucci/profil/spieler/538608.
Transfer history data appended for: https://www.transfermarkt.com/daniel-sappa/profil/spieler/423438.
Transfer history data appended for: https://www.transfermarkt.com/federico-vietto/profil/spieler/401579.
Transfer history data appended for: https://www.transfermarkt.com/cristian-tarragona/profil/spieler/422698.
Transfer history data appended for: https://www.transfermarkt.com/agustin-sufi/profil/spieler/441263.
Transfer history data appended for: https://www.transfermarkt.com/matias-ibanez/profil/spieler/73586.
Transfer history data appended for: https://www.transfermarkt.com/brian-negro/profil/spieler/741682.
Transfer history data appended for: https://www.transfermarkt.com/jorge-ortiz/profil/spieler/55212.
Transfer history data appended for: https://www.transfermarkt.com/cristian-chimino/profil/spieler/143951.
Transfer history data appended for: https://www.transfermarkt.com/faustino-dettler/profil/spieler/663492.
Transfer history data appended for: https://www.transfermarkt.com/brian-nievas/profil/spieler/661074.
Transfer history data appended for: https://www.transfermarkt.com/juan-cruz-franzoni/profil/spieler/576806.
Transfer history data appended for: https://www.transfermarkt.com/fernando-luna/profil/spieler/386611.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-comas/profil/spieler/267734.
Transfer history data appended for: https://www.transfermarkt.com/julian-chicco/profil/spieler/401583.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-canto/profil/spieler/359970.
Transfer history data appended for: https://www.transfermarkt.com/franco-rivasseau/profil/spieler/724566.
Transfer history data appended for: https://www.transfermarkt.com/german-rivero/profil/spieler/396869.
Transfer history data appended for: https://www.transfermarkt.com/oliver-benitez/profil/spieler/107529.
Transfer history data appended for: https://www.transfermarkt.com/santiago-brinone/profil/spieler/621376.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-geminiani/profil/spieler/267747.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-diaz/profil/spieler/345004.
Transfer history data appended for: https://www.transfermarkt.com/juan-galetto/profil/spieler/749231.
Transfer history data appended for: https://www.transfermarkt.com/matias-escudero/profil/spieler/267893.
Transfer history data appended for: https://www.transfermarkt.com/dylan-gissi/profil/spieler/81056.
Transfer history data appended for: https://www.transfermarkt.com/junior-arias/profil/spieler/268652.
Transfer history data appended for: https://www.transfermarkt.com/lucas-mancinelli/profil/spieler/202761.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-torres/profil/spieler/486237.
Transfer history data appended for: https://www.transfermarkt.com/lucas-kruspzky/profil/spieler/113131.
Transfer history data appended for: https://www.transfermarkt.com/mathias-abero/profil/spieler/142370.
Transfer history data appended for: https://www.transfermarkt.com/jose-barreto/profil/spieler/655031.
Transfer history data appended for: https://www.transfermarkt.com/federico-costa/profil/spieler/425136.
Transfer history data appended for: https://www.transfermarkt.com/damian-lemos/profil/spieler/68557.
Transfer history data appended for: https://www.transfermarkt.com/bruno-urribarri/profil/spieler/40896.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-avalos/profil/spieler/358418.
Transfer history data appended for: https://www.transfermarkt.com/walter-andrade/profil/spieler/28563.
Transfer history data appended for: https://www.transfermarkt.com/hugo-silveira/profil/spieler/263052.
Transfer history data appended for: https://www.transfermarkt.com/ian-escobar/profil/spieler/440164.
Transfer history data appended for: https://www.transfermarkt.com/hugo-silva/profil/spieler/422701.
Transfer history data appended for: https://www.transfermarkt.com/enzo-ybanez/profil/spieler/534034.
Transfer history data appended for: https://www.transfermarkt.com/martin-ojeda/profil/spieler/440988.
Transfer history data appended for: https://www.transfermarkt.com/damian-perez/profil/spieler/71106.
Transfer history data appended for: https://www.transfermarkt.com/nestor-breitenbruch/profil/spieler/334056.
Transfer history data appended for: https://www.transfermarkt.com/leandro-vella/profil/spieler/441268.
Transfer history data appended for: https://www.transfermarkt.com/wilder-cartagena/profil/spieler/224669.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-carrasco/profil/spieler/503005.
Transfer history data appended for: https://www.transfermarkt.com/agustin-manzur/profil/spieler/563717.
Transfer history data appended for: https://www.transfermarkt.com/richard-prieto/profil/spieler/415841.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-alanis/profil/spieler/342149.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-bullaude/profil/spieler/627068.
Transfer history data appended for: https://www.transfermarkt.com/santiago-garcia/profil/spieler/102432.
Transfer history data appended for: https://www.transfermarkt.com/jaime-ayovi/profil/spieler/139494.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-herrera/profil/spieler/270977.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-rey/profil/spieler/166591.
Transfer history data appended for: https://www.transfermarkt.com/luciano-pizarro/profil/spieler/503330.
Transfer history data appended for: https://www.transfermarkt.com/jalil-elias/profil/spieler/376859.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-mateo/profil/spieler/544164.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-varela/profil/spieler/553421.
Transfer history data appended for: https://www.transfermarkt.com/valentin-burgoa/profil/spieler/563719.

Transfer history data appended for: https://www.transfermarkt.com/victorio-ramis/profil/spieler/381065.
Transfer history data appended for: https://www.transfermarkt.com/andres-mehring/profil/spieler/240903.
Transfer history data appended for: https://www.transfermarkt.com/matias-gonzalez/profil/spieler/831160.
Transfer history data appended for: https://www.transfermarkt.com/facundo-barboza/profil/spieler/422395.
Transfer history data appended for: https://www.transfermarkt.com/christian-almeida/profil/spieler/195936.
Transfer history data appended for: https://www.transfermarkt.com/danilo-ortiz/profil/spieler/265590.
Transfer history data appended for: https://www.transfermarkt.com/juan-brunetta/profil/spieler/466268.
Transfer history data appended for: https://www.transfermarkt.com/agustin-aleo/profil/spieler/572088.
Transfer history data appended for: https://www.transfermarkt.com/tomas-badaloni/profil/spieler/568546.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-freites/profil/spieler/702886.
Transfer history data appended for: https://www.transfermarkt.com/marcos-rouzies/profil/spieler/649997.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-ferrari/profil/spieler/340507.
Transfer history data appended for: https://www.transfermarkt.com/roberto-ramirez/profil/spieler/332248.
Transfer history data appended for: https://www.transfermarkt.com/franco-gonzalez/profil/spieler/689209.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/renzo-tesuri/profil/spieler/457666.
Transfer history data appended for: https://www.transfermarkt.com/juan-bolado/profil/spieler/457215.
Transfer history data appended for: https://www.transfermarkt.com/juan-andrada/profil/spieler/457212.
Transfer history data appended for: https://www.transfermarkt.com/fabian-henriquez/profil/spieler/400611.
Transfer history data appended for: https://www.transfermarkt.com/zaid-romero/profil/spieler/741142.
Transfer history data appended for: https://www.transfermarkt.com/miguel-jacquet/profil/spieler/391348.
Transfer history data appended for: https://www.transfermarkt.com/agustin-alvarez/profil/spieler/688380.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-goni/profil/spieler/594104.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-lomonaco/profil/spieler/556046.
Transfer history data appended for: https://www.transfermarkt.com/leonel-gonzalez/profil/spieler/302416.
Transfer history data appended for: https://www.transfermarkt.com/kevin-gutierrez/profil/spieler/554799.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-arena/profil/spieler/552629.
Transfer history data appended for: https://www.transfermarkt.com/nelson-ibanez/profil/spieler/75534.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-toledo/profil/spieler/147655.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-lamendola/profil/spieler/756809.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-rosales/profil/spieler/756810.
Transfer history data appended for: https://www.transfermarkt.com/ramiro-ruiz-rodriguez/profil/spieler/633048.
Transfer history data appended for: https://www.transfermarkt.com/mauro-osores/profil/spieler/532351.
Transfer history data appended for: https://www.transfermarkt.com/leandro-diaz/profil/spieler/140214.
Transfer history data appended for: https://www.transfermarkt.com/javier-toledo/profil/spieler/72620.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-risso-patron/profil/spieler/532350.
Transfer history data appended for: https://www.transfermarkt.com/harold-reina/profil/spieler/89893.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-castellani/profil/spieler/87840.
Transfer history data appended for: https://www.transfermarkt.com/ariel-rojas/profil/spieler/57753.
Transfer history data appended for: https://www.transfermarkt.com/federico-bravo/profil/spieler/266775.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-ortiz/profil/spieler/213543.
Transfer history data appended for: https://www.transfermarkt.com/matias-solohaga/profil/spieler/837975.
Transfer history data appended for: https://www.transfermarkt.com/cristian-erbes/profil/spieler/118283.
Transfer history data appended for: https://www.transfermarkt.com/lucas-melano/profil/spieler/220753.
Transfer history data appended for: https://www.transfermarkt.com/matias-alustiza/profil/spieler/64843.
Transfer history data appended for: https://www.transfermarkt.com/tomas-marchiori/profil/spieler/596909.
Transfer history data appended for: https://www.transfermarkt.com/yonathan-cabral/profil/spieler/318819.
Transfer history data appended for: https://www.transfermarkt.com/camilo-albornoz/profil/spieler/745945.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-heredia/profil/spieler/538367.
Transfer history data appended for: https://www.transfermarkt.com/bruno-bianchi/profil/spieler/55998.
Transfer history data appended for: https://www.transfermarkt.com/jonas-romero/profil/spieler/532352.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-aguirre/profil/spieler/88166.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-acosta/profil/spieler/422917.
Transfer history data appended for: https://www.transfermarkt.com/kevin-isa-luna/profil/spieler/663710.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-sanchez/profil/spieler/89246.
Transfer history data appended for: https://www.transfermarkt.com/dylan-gissi/profil/spieler/81056.
Transfer history data appended for: https://www.transfermarkt.com/franco-mussis/profil/spieler/74821.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-ortiz/profil/spieler/267772.
Transfer history data appended for: https://www.transfermarkt.com/agustin-lagos/profil/spieler/698551.
Transfer history data appended for: https://www.transfermarkt.com/franco-pizzicanella/profil/spieler/424046.
Transfer history data appended for: https://www.transfermarkt.com/tomas-cuello/profil/spieler/503052.
Transfer history data appended for: https://www.transfermarkt.com/augusto-lotti/profil/spieler/406296.
Transfer history data appended for: https://www.transfermarkt.com/raul-castro/profil/spieler/320654.
Transfer history data appended for: https://www.transfermarkt.com/santiago-sosa/profil/spieler/576026.
Transfer history data appended for: https://www.transfermarkt.com/enzo-fernandez/profil/spieler/648195.
Transfer history data appended for: https://www.transfermarkt.com/jorge-moreira/profil/spieler/139439.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-rollheiser/profil/spieler/491704.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-scocco/profil/spieler/51088.
Transfer history data appended for: https://www.transfermarkt.com/bruno-zuculini/profil/spieler/115507.
Transfer history data appended for: https://www.transfermarkt.com/lucas-martinez-quarta/profil/spieler/373373.
Transfer history data appended for: https://www.transfermarkt.com/santiago-simon/profil/spieler/661131.
Transfer history data appended for: https://www.transfermarkt.com/elias-lopez/profil/spieler/491691.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-montiel/profil/spieler/402733.
Transfer history data appended for: https://www.transfermarkt.com/santos-borre/profil/spieler/323831.
Transfer history data appended for: https://www.transfermarkt.com/franco-paredes/profil/spieler/749016.
Transfer history data appended for: https://www.transfermarkt.com/exequiel-palacios/profil/spieler/401578.
Transfer history data appended for: https://www.transfermarkt.com/tomas-castro/profil/spieler/836491.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-fernandez/profil/spieler/50669.
Transfer history data appended for: https://www.transfermarkt.com/german-lux/profil/spieler/19979.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-ponzio/profil/spieler/7987.
Transfer history data appended for: https://www.transfermarkt.com/paulo-diaz/profil/spieler/271478.
Transfer history data appended for: https://www.transfermarkt.com/milton-casco/profil/spieler/115183.
Transfer history data appended for: https://www.transfermarkt.com/julian-alvarez/profil/spieler/576024.
Transfer history data appended for: https://www.transfermarkt.com/augusto-aguirre/profil/spieler/548467.
Transfer history data appended for: https://www.transfermarkt.com/franco-armani/profil/spieler/119634.
Transfer history data appended for: https://www.transfermarkt.com/federico-girotti/profil/spieler/639149.
Transfer history data appended for: https://www.transfermarkt.com/lucas-beltran/profil/spieler/628366.
Transfer history data appended for: https://www.transfermarkt.com/enzo-perez/profil/spieler/56066.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-de-la-cruz/profil/spieler/397458.
Transfer history data appended for: https://www.transfermarkt.com/enrique-bologna/profil/spieler/30753.
Transfer history data appended for: https://www.transfermarkt.com/fabrizio-angileri/profil/spieler/268506.
Transfer history data appended for: https://www.transfermarkt.com/ivan-rossi/profil/spieler/267433.
Transfer history data appended for: https://www.transfermarkt.com/matias-suarez/profil/spieler/66660.
Transfer history data appended for: https://www.transfermarkt.com/cristian-ferreira/profil/spieler/548468.

Transfer history data appended for: https://www.transfermarkt.com/robert-rojas/profil/spieler/527494.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-gallardo/profil/spieler/548466.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-aliseda/profil/spieler/604616.
Transfer history data appended for: https://www.transfermarkt.com/aldo-maiz/profil/spieler/738247.
Transfer history data appended for: https://www.transfermarkt.com/enzo-fernandez/profil/spieler/648195.
Transfer history data appended for: https://www.transfermarkt.com/hector-martinez/profil/spieler/401576.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-tripichio/profil/spieler/275614.
Transfer history data appended for: https://www.transfermarkt.com/nelson-acevedo/profil/spieler/125184.
Transfer history data appended for: https://www.transfermarkt.com/eugenio-isnaldo/profil/spieler/260801.
Transfer history data appended for: https://www.transfermarkt.com/nestor-breitenbruch/profil/spieler/334056.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-farias/profil/spieler/514928.
Transfer history data appended for: https://www.transfermarkt.com/ciro-rius/profil/spieler/101875.
Transfer history data appended for: https://www.transfermarkt.com/francisco-cerro/profil/spieler/125107.
Transfer history data appended for: https://www.transfermarkt.com/rafael-delgado/profil/spieler/167314.
Transfer history data appended for: https://www.transfermarkt.com/juan-martin-lucero/profil/spieler/162807.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-unsain/profil/spieler/337600.
Transfer history data appended for: https://www.transfermarkt.com/bautista-merlini/profil/spieler/431737.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-herrera/profil/spieler/270977.
Transfer history data appended for: https://www.transfermarkt.com/diego-rodriguez/profil/spieler/90800.
Transfer history data appended for: https://www.transfermarkt.com/juan-villagra/profil/spieler/826113.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-britez/profil/spieler/262851.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-avellaneda/profil/spieler/270968.
Transfer history data appended for: https://www.transfermarkt.com/franco-paredes/profil/spieler/749016.
Transfer history data appended for: https://www.transfermarkt.com/ruben-botta/profil/spieler/88542.
Transfer history data appended for: https://www.transfermarkt.com/fernando-marquez/profil/spieler/75597.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-duarte/profil/spieler/213469.
Transfer history data appended for: https://www.transfermarkt.com/julio-gonzalez/profil/spieler/417196.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-barrios/profil/spieler/503377.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-hachen/profil/spieler/213541.
Transfer history data appended for: https://www.transfermarkt.com/francisco-pizzini/profil/spieler/213122.
Transfer history data appended for: https://www.transfermarkt.com/lucas-villarruel/profil/spieler/268499.
Transfer history data appended for: https://www.transfermarkt.com/braian-ojeda/profil/spieler/491596.
Transfer history data appended for: https://www.transfermarkt.com/juan-rodriguez/profil/spieler/189448.
Transfer history data appended for: https://www.transfermarkt.com/enzo-coacci/profil/spieler/642529.
Transfer history data appended for: https://www.transfermarkt.com/lucio-chiappero/profil/spieler/361719.
Transfer history data appended for: https://www.transfermarkt.com/matias-laba/profil/spieler/147496.
Transfer history data appended for: https://www.transfermarkt.com/tomas-ortiz/profil/spieler/639384.
Transfer history data appended for: https://www.transfermarkt.com/diego-rodriguez/profil/spieler/127828.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-benitez/profil/spieler/96432.
Transfer history data appended for: https://www.transfermarkt.com/guido-mainero/profil/spieler/441270.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-escalante/profil/spieler/740671.
Transfer history data appended for: https://www.transfermarkt.com/alexis-castro/profil/spieler/364602.
Transfer history data appended for: https://www.transfermarkt.com/juan-miritello/profil/spieler/728200.
Transfer history data appended for: https://www.transfermarkt.com/marcos-ledesma/profil/spieler/344421.
Transfer history data appended for: https://www.transfermarkt.com/adonis-frias/profil/spieler/598838.
Transfer history data appended for: https://www.transfermarkt.com/neri-cardozo/profil/spieler/19955.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-piovi/profil/spieler/284120.
Transfer history data appended for: https://www.transfermarkt.com/matias-barrios/profil/spieler/748212.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-fernandez/profil/spieler/333921.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-mana/profil/spieler/282631.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-gallardo/profil/spieler/548466.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/nicolas-pasquini/profil/spieler/270987.
Transfer history data appended for: https://www.transfermarkt.com/leandro-diaz/profil/spieler/140214.
Transfer history data appended for: https://www.transfermarkt.com/mateo-retegui/profil/spieler/554903.
Transfer history data appended for: https://www.transfermarkt.com/nazareno-colombo/profil/spieler/688207.
Transfer history data appended for: https://www.transfermarkt.com/martin-cauteruccio/profil/spieler/76599.
Transfer history data appended for: https://www.transfermarkt.com/juan-fuentes/profil/spieler/319468.
Transfer history data appended for: https://www.transfermarkt.com/jeronimo-pourtau/profil/spieler/504885.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-bazzana/profil/spieler/497157.
Transfer history data appended for: https://www.transfermarkt.com/facundo-mura/profil/spieler/642759.
Transfer history data appended for: https://www.transfermarkt.com/angel-gonzalez/profil/spieler/347920.
Transfer history data appended for: https://www.transfermarkt.com/lucas-rodriguez/profil/spieler/380996.
Transfer history data appended for: https://www.transfermarkt.com/federico-gonzalez/profil/spieler/77380.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-rosales/profil/spieler/251619.
Transfer history data appended for: https://www.transfermarkt.com/franco-romero/profil/spieler/833115.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-guzman/profil/spieler/756813.
Transfer history data appended for: https://www.transfermarkt.com/carlo-lattanzio/profil/spieler/383818.
Transfer history data appended for: https://www.transfermarkt.com/marcos-rojo/profil/spieler/93176.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-schunke/profil/spieler/78232.
Transfer history data appended for: https://www.transfermarkt.com/luciano-squadrone/profil/spieler/830310.
Transfer history data appended for: https://www.transfermarkt.com/david-ayala/profil/spieler/661094.
Transfer history data appended for: https://www.transfermarkt.com/bautista-kociubinski/profil/spieler/830318.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-gonzalez/profil/spieler/688181.
Transfer history data appended for: https://www.transfermarkt.com/mauro-diaz/profil/spieler/87845.
Transfer history data appended for: https://www.transfermarkt.com/facundo-sanchez/profil/spieler/107523.
Transfer history data appended for: https://www.transfermarkt.com/javier-mascherano/profil/spieler/19981.
Transfer history data appended for: https://www.transfermarkt.com/matias-pellegrini/profil/spieler/606267.
Transfer history data appended for: https://www.transfermarkt.com/ivan-gomez/profil/spieler/459318.
Transfer history data appended for: https://www.transfermarkt.com/edwar-lopez/profil/spieler/572077.
Transfer history data appended for: https://www.transfermarkt.com/dario-sarmiento/profil/spieler/668552.
Transfer history data appended for: https://www.transfermarkt.com/ivan-erquiaga/profil/spieler/579977.
Transfer history data appended for: https://www.transfermarkt.com/diego-garcia/profil/spieler/409088.
Transfer history data appended for: https://www.transfermarkt.com/manuel-castro/profil/spieler/335984.
Transfer history data appended for: https://www.transfermarkt.com/gaspar-di-pizio/profil/spieler/839028.
Transfer history data appended for: https://www.transfermarkt.com/enzo-kalinski/profil/spieler/67818.
Transfer history data appended for: https://www.transfermarkt.com/franco-sivetti/profil/spieler/625204.
Transfer history data appended for: https://www.transfermarkt.com/esteban-obregon/profil/spieler/830315.
Transfer history data appended for: https://www.transfermarkt.com/andres-ayala/profil/spieler/576029.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-jara/profil/spieler/40429.
Transfer history data appended for: https://www.transfermarkt.com/fabian-cubero/profil/spieler/26438.
Transfer history data appended for: https://www.transfermarkt.com/florian-monzon/profil/spieler/756993.
Transfer history data appended for: https://www.transfermarkt.com/federico-versaci/profil/spieler/840967.
Transfer history data appended for: https://www.transfermarkt.com/facundo-caseres/profil/spieler/829434.
Transfer history data appended for: https://www.transfermarkt.com/pablo-galdames/profil/spieler/313830.
Transfer history data appended for: https://www.transfermarkt.com/agustin-bouzat/profil/spieler/422699.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-amor/profil/spieler/348273.
Transfer history data appended for: https://www.transfermarkt.com/marcos-enrique/profil/spieler/742512.
Transfer history data appended for: https://www.transfermarkt.com/alexander-dominguez/profil/spieler/84310.
Transfer history data appended for: https://www.transfermarkt.com/mauro-pitton/profil/spieler/376710.
Transfer history data appended for: https://www.transfermarkt.com/lucas-hoyos/profil/spieler/75462.
Transfer history data appended for: https://www.transfermarkt.com/damian-fernandez/profil/spieler/706562.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-alvarez/profil/spieler/76077.
Transfer history data appended for: https://www.transfermarkt.com/tomas-cavanagh/profil/spieler/832090.
Transfer history data appended for: https://www.transfermarkt.com/juan-martin-lucero/profil/spieler/162807.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-barreal/profil/spieler/613873.
Transfer history data appended for: https://www.transfermarkt.com/cristian-tarragona/profil/spieler/422698.
Transfer history data appended for: https://www.transfermarkt.com/thiago-almada/profil/spieler/576028.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-giannetti/profil/spieler/225963.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-romero/profil/spieler/365758.
Transfer history data appended for: https://www.transfermarkt.com/luis-abram/profil/spieler/330684.
Transfer history data appended for: https://www.transfermarkt.com/lucas-robertone/profil/spieler/457221.
Transfer history data appended for: https://www.transfermarkt.com/hernan-de-la-fuente/profil/spieler/552628.
Transfer history data appended for: https://www.transfermarkt.com/braian-cufre/profil/spieler/401521.
Transfer history data appended for: https://www.transfermarkt.com/tomas-guidara/profil/spieler/355900.
Transfer history data appended for: https://www.transfermarkt.com/miguel-brizuela/profil/spieler/689465.
Transfer history data appended for: https://www.transfermarkt.com/matias-borgogno/profil/spieler/592427.
Transfer history data appended for: https://www.transfermarkt.com/luca-orellano/profil/spieler/636784.
Transfer history data appended for: https://www.transfermarkt.com/guido-mainero/profil/spieler/441270.
Transfer history data appended for: https://www.transfermarkt.com/cristian-nunez/profil/spieler/563815.
Transfer history data appended for: https://www.transfermarkt.com/lucas-janson/profil/spieler/238448.
Transfer history data appended for: https://www.transfermarkt.com/federico-mancuello/profil/spieler/96313.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-garcia/profil/spieler/829433.
Transfer history data appended for: https://www.transfermarkt.com/francisco-ortega/profil/spieler/553663.
Transfer history data appended for: https://www.transfermarkt.com/gaston-gimenez/profil/spieler/216758.
Transfer history data appended for: https://www.transfermarkt.com/facundo-perrone/profil/spieler/840968.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-dominguez/profil/spieler/497291.
Transfer history data appended for: https://www.transfermarkt.com/tobias-zarate/profil/spieler/742603.
Transfer history data appended for: https://www.transfermarkt.com/alexis-soto/profil/spieler/409272.
Transfer history data appended for: https://www.transfermarkt.com/eugenio-mena/profil/spieler/113999.
Transfer history data appended for: https://www.transfermarkt.com/david-barbona/profil/spieler/356089.

Transfer history data appended for: https://www.transfermarkt.com/hector-fertoli/profil/spieler/424024.
Transfer history data appended for: https://www.transfermarkt.com/javier-garcia/profil/spieler/7966.
Transfer history data appended for: https://www.transfermarkt.com/gaston-gomez/profil/spieler/337627.
Transfer history data appended for: https://www.transfermarkt.com/lucas-orban/profil/spieler/110309.
Transfer history data appended for: https://www.transfermarkt.com/fernando-prado/profil/spieler/836421.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-arias/profil/spieler/54330.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-donatti/profil/spieler/119646.
Transfer history data appended for: https://www.transfermarkt.com/lisandro-lopez/profil/spieler/27661.
Transfer history data appended for: https://www.transfermarkt.com/evelio-cardozo/profil/spieler/652551.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-schlegel/profil/spieler/504258.
Transfer history data appended for: https://www.transfermarkt.com/matias-ibanez/profil/spieler/73586.
Transfer history data appended for: https://www.transfermarkt.com/luca-andrada/profil/spieler/728256.
Transfer history data appended for: https://www.transfermarkt.com/ivan-maggi/profil/spieler/708874.
Transfer history data appended for: https://www.transfermarkt.com/elias-machuca/profil/spieler/668544.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-garre/profil/spieler/462977.
Transfer history data appended for: https://www.transfermarkt.com/diego-gonzalez/profil/spieler/54578.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-sigali/profil/spieler/54570.
Transfer history data appended for: https://www.transfermarkt.com/julian-lopez/profil/spieler/625203.
Transfer history data appended for: https://www.transfermarkt.com/augusto-solari/profil/spieler/282694.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-martinez/profil/spieler/309388.
Transfer history data appended for: https://www.transfermarkt.com/mateo-cassierra/profil/spieler/362667.
Transfer history data appended for: https://www.transfermarkt.com/carlos-alcaraz/profil/spieler/748319.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-reniero/profil/spieler/496415.
Transfer history data appended for: https://www.transfermarkt.com/fabricio-dominguez/profil/spieler/621793.
Transfer history data appended for: https://www.transfermarkt.com/juan-jose-caceres/profil/spieler/756494.
Transfer history data appended for: https://www.transfermarkt.com/tiago-banega/profil/spieler/744806.
Transfer history data appended for: https://www.transfermarkt.com/ivan-pillud/profil/spieler/77720.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-diaz/profil/spieler/83895.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-melgarejo/profil/spieler/127822.
Transfer history data appended for: https://www.transfermarkt.com/matias-rojas/profil/spieler/417327.
Transfer history data appended for: https://www.transfermarkt.com/sergio-sanchez/profil/spieler/830782.
Transfer history data appended for: https://www.transfermarkt.com/neri-cardozo/profil/spieler/19955.
Transfer history data appended for: https://www.transfermarkt.com/leonel-miranda/profil/spieler/259246.
Transfer history data appended for: https://www.transfermarkt.com/matias-zaracho/profil/spieler/480774.
Transfer history data appended for: https://www.transfermarkt.com/christopher-oikonomidis/profil/spieler/248483.
Transfer history data appended for: https://www.transfermarkt.com/tando-velaphi/profil/spieler/49529.
Transfer history data appended for: https://www.transfermarkt.com/alex-grant/profil/spieler/225068.
Transfer history data appended for: https://www.transfermarkt.com/james-meredith/profil/spieler/48111.
Transfer history data appended for: https://www.transfermarkt.com/vince-lia/profil/spieler/43165.
Transfer history data appended for: https://www.transfermarkt.com/neil-kilkenny/profil/spieler/2997.
Transfer history data appended for: https://www.transfermarkt.com/carlo-armiento/profil/spieler/623962.
Transfer history data appended for: https://www.transfermarkt.com/brandon-wilson/profil/spieler/385923.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-aspropotamitis/profil/spieler/363689.
Transfer history data appended for: https://www.transfermarkt.com/osama-malik/profil/spieler/114975.
Transfer history data appended for: https://www.transfermarkt.com/nick-dagostino/profil/spieler/399165.
Transfer history data appended for: https://www.transfermarkt.com/nick-sullivan/profil/spieler/670226.
Transfer history data appended for: https://www.transfermarkt.com/tarek-elrich/profil/spieler/43151.
Transfer history data appended for: https://www.transfermarkt.com/andy-keogh/profil/spieler/29419.
Transfer history data appended for: https://www.transfermarkt.com/dane-ingham/profil/spieler/485449.
Transfer history data appended for: https://www.transfermarkt.com/darryl-lachman/profil/spieler/93393.
Transfer history data appended for: https://www.transfermarkt.com/dino-djulbic/profil/spieler/48295.
Transfer history data appended for: https://www.transfermarkt.com/liam-reddy/profil/spieler/43182.
Transfer history data appended for: https://www.transfermarkt.com/daniel-stynes/profil/spieler/525779.
Transfer history data appended for: https://www.transfermarkt.com/riley-warland/profil/spieler/552746.
Transfer history data appended for: https://www.transfermarkt.com/diego-castro/profil/spieler/57791.
Transfer history data appended for: https://www.transfermarkt.com/anthony-caceres/profil/spieler/226739.
Transfer history data appended for: https://www.transfermarkt.com/alex-wilkinson/profil/spieler/43128.
Transfer history data appended for: https://www.transfermarkt.com/michael-zullo/profil/spieler/55444.
Transfer history data appended for: https://www.transfermarkt.com/luke-brattan/profil/spieler/114365.
Transfer history data appended for: https://www.transfermarkt.com/paulo-retre/profil/spieler/257685.
Transfer history data appended for: https://www.transfermarkt.com/calem-nieuwenhof/profil/spieler/734487.
Transfer history data appended for: https://www.transfermarkt.com/kosta-barbarouses/profil/spieler/50200.
Transfer history data appended for: https://www.transfermarkt.com/rhyan-grant/profil/spieler/108108.
Transfer history data appended for: https://www.transfermarkt.com/joel-king/profil/spieler/616430.
Transfer history data appended for: https://www.transfermarkt.com/tom-heward-belle/profil/spieler/349422.
Transfer history data appended for: https://www.transfermarkt.com/chris-zuvela/profil/spieler/525625.
Transfer history data appended for: https://www.transfermarkt.com/harry-van-der-saag/profil/spieler/702655.
Transfer history data appended for: https://www.transfermarkt.com/alexander-baumjohann/profil/spieler/16474.
Transfer history data appended for: https://www.transfermarkt.com/luke-ivanovic/profil/spieler/637747.
Transfer history data appended for: https://www.transfermarkt.com/trent-buhagiar/profil/spieler/415273.
Transfer history data appended for: https://www.transfermarkt.com/ben-warland/profil/spieler/285225.
Transfer history data appended for: https://www.transfermarkt.com/patrick-flottmann/profil/spieler/399161.
Transfer history data appended for: https://www.transfermarkt.com/andrew-redmayne/profil/spieler/51975.
Transfer history data appended for: https://www.transfermarkt.com/ryan-mcgowan/profil/spieler/54265.
Transfer history data appended for: https://www.transfermarkt.com/milos-ninkovic/profil/spieler/48740.
Transfer history data appended for: https://www.transfermarkt.com/mark-natta/profil/spieler/813296.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-taay/profil/spieler/732828.
Transfer history data appended for: https://www.transfermarkt.com/tate-russell/profil/spieler/589458.
Transfer history data appended for: https://www.transfermarkt.com/patrick-ziegler/profil/spieler/54964.
Transfer history data appended for: https://www.transfermarkt.com/keanu-baccus/profil/spieler/479037.

Transfer history data appended for: https://www.transfermarkt.com/simon-cox/profil/spieler/37150.
Transfer history data appended for: https://www.transfermarkt.com/dylan-mcgowan/profil/spieler/72504.
Transfer history data appended for: https://www.transfermarkt.com/daniel-georgievski/profil/spieler/47615.
Transfer history data appended for: https://www.transfermarkt.com/daniel-margush/profil/spieler/414085.
Transfer history data appended for: https://www.transfermarkt.com/phillip-cancar/profil/spieler/716810.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-adam/profil/spieler/692322.
Transfer history data appended for: https://www.transfermarkt.com/tass-mourdoukoutas/profil/spieler/561049.
Transfer history data appended for: https://www.transfermarkt.com/daniel-wilmering/profil/spieler/660145.
Transfer history data appended for: https://www.transfermarkt.com/kwame-yeboah/profil/spieler/187383.
Transfer history data appended for: https://www.transfermarkt.com/jordan-odoherty/profil/spieler/453838.
Transfer history data appended for: https://www.transfermarkt.com/graham-dorrans/profil/spieler/36608.
Transfer history data appended for: https://www.transfermarkt.com/daniel-lopar/profil/spieler/4769.
Transfer history data appended for: https://www.transfermarkt.com/fabian-monge/profil/spieler/650865.
Transfer history data appended for: https://www.transfermarkt.com/vedran-janjetovic/profil/spieler/47194.
Transfer history data appended for: https://www.transfermarkt.com/bruce-kamau/profil/spieler/334157.
Transfer history data appended for: https://www.transfermarkt.com/kosta-grozos/profil/spieler/500924.
Transfer history data appended for: https://www.transfermarkt.com/jarrod-carluccio/profil/spieler/749273.
Transfer history data appended for: https://www.transfermarkt.com/anthony-lesiotis/profil/spieler/565890.
Transfer history data appended for: https://www.transfermarkt.com/josh-brindell-south/profil/spieler/290697.
Transfer history data appended for: https://www.transfermarkt.com/kai-trewin/profil/spieler/691326.
Transfer history data appended for: https://www.transfermarkt.com/jamie-young/profil/spieler/13435.
Transfer history data appended for: https://www.transfermarkt.com/danny-kim/profil/spieler/607430.
Transfer history data appended for: https://www.transfermarkt.com/corey-brown/profil/spieler/187345.
Transfer history data appended for: https://www.transfermarkt.com/macklin-freke/profil/spieler/631103.
Transfer history data appended for: https://www.transfermarkt.com/joe-champness/profil/spieler/539321.
Transfer history data appended for: https://www.transfermarkt.com/jai-ingham/profil/spieler/307784.
Transfer history data appended for: https://www.transfermarkt.com/scott-mcdonald/profil/spieler/13799.
Transfer history data appended for: https://www.transfermarkt.com/jack-hingert/profil/spieler/121903.
Transfer history data appended for: https://www.transfermarkt.com/tom-aldred/profil/spieler/95076.
Transfer history data appended for: https://www.transfermarkt.com/izaack-powell/profil/spieler/650572.
Transfer history data appended for: https://www.transfermarkt.com/rahmat-akbari/profil/spieler/543320.
Transfer history data appended for: https://www.transfermarkt.com/dylan-wenzel-halls/profil/spieler/582754.
Transfer history data appended for: https://www.transfermarkt.com/macauley-gillesphey/profil/spieler/267113.
Transfer history data appended for: https://www.transfermarkt.com/george-mells/profil/spieler/337278.
Transfer history data appended for: https://www.transfermarkt.com/jordan-courtney-perkins/profil/spieler/691325.
Transfer history data appended for: https://www.transfermarkt.com/jay-oshea/profil/spieler/68327.
Transfer history data appended for: https://www.transfermarkt.com/jesse-daley/profil/spieler/544489.
Transfer history data appended for: https://www.transfermarkt.com/riku-danzaki/profil/spieler/657124.
Transfer history data appended for: https://www.transfermarkt.com/ivan-vujica/profil/spieler/240436.
Transfer history data appended for: https://www.transfermarkt.com/max-burgess/profil/spieler/343049.
Transfer history data appended for: https://www.transfermarkt.com/steven-lustica/profil/spieler/127910.
Transfer history data appended for: https://www.transfermarkt.com/valentino-yuel/profil/spieler/662257.
Transfer history data appended for: https://www.transfermarkt.com/tomoki-imai/profil/spieler/255095.
Transfer history data appended for: https://www.transfermarkt.com/ryan-scott/profil/spieler/604264.
Transfer history data appended for: https://www.transfermarkt.com/victor-sanchez/profil/spieler/63290.
Transfer history data appended for: https://www.transfermarkt.com/joshua-risdon/profil/spieler/160614.
Transfer history data appended for: https://www.transfermarkt.com/filip-kurto/profil/spieler/104376.
Transfer history data appended for: https://www.transfermarkt.com/joshua-cavallo/profil/spieler/613515.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-diamanti/profil/spieler/23197.
Transfer history data appended for: https://www.transfermarkt.com/jerry-skotadis/profil/spieler/613653.
Transfer history data appended for: https://www.transfermarkt.com/connor-pain/profil/spieler/257682.
Transfer history data appended for: https://www.transfermarkt.com/luke-duzel/profil/spieler/703660.
Transfer history data appended for: https://www.transfermarkt.com/besart-berisha/profil/spieler/17257.
Transfer history data appended for: https://www.transfermarkt.com/aaron-calver/profil/spieler/255162.
Transfer history data appended for: https://www.transfermarkt.com/brendan-hamill/profil/spieler/147600.
Transfer history data appended for: https://www.transfermarkt.com/dylan-pierias/profil/spieler/486972.
Transfer history data appended for: https://www.transfermarkt.com/kwabena-appiah-kubi/profil/spieler/230478.
Transfer history data appended for: https://www.transfermarkt.com/thiel-iradukunda/profil/spieler/603861.
Transfer history data appended for: https://www.transfermarkt.com/apostolos-stamatelopoulos/profil/spieler/547924.
Transfer history data appended for: https://www.transfermarkt.com/oskar-dillon/profil/spieler/606651.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-pasquali/profil/spieler/448680.
Transfer history data appended for: https://www.transfermarkt.com/andrew-durante/profil/spieler/43148.
Transfer history data appended for: https://www.transfermarkt.com/lachlan-wales/profil/spieler/499735.
Transfer history data appended for: https://www.transfermarkt.com/tomislav-uskok/profil/spieler/409114.
Transfer history data appended for: https://www.transfermarkt.com/conor-metcalfe/profil/spieler/522223.
Transfer history data appended for: https://www.transfermarkt.com/adrian-luna/profil/spieler/131113.
Transfer history data appended for: https://www.transfermarkt.com/scott-jamieson/profil/spieler/52498.
Transfer history data appended for: https://www.transfermarkt.com/harrison-delbridge/profil/spieler/318541.
Transfer history data appended for: https://www.transfermarkt.com/matthew-sutton/profil/spieler/561484.
Transfer history data appended for: https://www.transfermarkt.com/marco-tilio/profil/spieler/565531.
Transfer history data appended for: https://www.transfermarkt.com/taras-gomulka/profil/spieler/794888.
Transfer history data appended for: https://www.transfermarkt.com/florin-berenguer/profil/spieler/111040.
Transfer history data appended for: https://www.transfermarkt.com/nathaniel-atkinson/profil/spieler/556038.
Transfer history data appended for: https://www.transfermarkt.com/kerrin-stokes/profil/spieler/704397.
Transfer history data appended for: https://www.transfermarkt.com/lucas-portelli/profil/spieler/613514.
Transfer history data appended for: https://www.transfermarkt.com/raphael-borges-rodrigues/profil/spieler/704398.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-garuccio/profil/spieler/187359.
Transfer history data appended for: https://www.transfermarkt.com/richard-windbichler/profil/spieler/74770.
Transfer history data appended for: https://www.transfermarkt.com/rostyn-griffiths/profil/spieler/67715.

Transfer history data appended for: https://www.transfermarkt.com/aiden-oneill/profil/spieler/385918.
Transfer history data appended for: https://www.transfermarkt.com/scott-galloway/profil/spieler/257415.
Transfer history data appended for: https://www.transfermarkt.com/andrew-nabbout/profil/spieler/247289.
Transfer history data appended for: https://www.transfermarkt.com/naoki-tsubaki/profil/spieler/491198.
Transfer history data appended for: https://www.transfermarkt.com/mitchell-graham/profil/spieler/613513.
Transfer history data appended for: https://www.transfermarkt.com/idrus-abdulahi/profil/spieler/626709.
Transfer history data appended for: https://www.transfermarkt.com/tom-glover/profil/spieler/335615.
Transfer history data appended for: https://www.transfermarkt.com/jamie-maclaren/profil/spieler/173591.
Transfer history data appended for: https://www.transfermarkt.com/curtis-good/profil/spieler/179471.
Transfer history data appended for: https://www.transfermarkt.com/craig-noone/profil/spieler/81202.
Transfer history data appended for: https://www.transfermarkt.com/pacifique-niyongabire/profil/spieler/561646.
Transfer history data appended for: https://www.transfermarkt.com/alhassan-toure/profil/spieler/692440.
Transfer history data appended for: https://www.transfermarkt.com/george-timotheou/profil/spieler/344677.
Transfer history data appended for: https://www.transfermarkt.com/joe-caletti/profil/spieler/351919.
Transfer history data appended for: https://www.transfermarkt.com/michael-jakobsen/profil/spieler/8421.
Transfer history data appended for: https://www.transfermarkt.com/stefan-mauk/profil/spieler/189231.
Transfer history data appended for: https://www.transfermarkt.com/ben-halloran/profil/spieler/160740.
Transfer history data appended for: https://www.transfermarkt.com/james-troisi/profil/spieler/52585.
Transfer history data appended for: https://www.transfermarkt.com/michael-marrone/profil/spieler/111896.
Transfer history data appended for: https://www.transfermarkt.com/yaya-dukuly/profil/spieler/652487.
Transfer history data appended for: https://www.transfermarkt.com/louis-darrigo/profil/spieler/561650.
Transfer history data appended for: https://www.transfermarkt.com/tomi-juric/profil/spieler/171820.
Transfer history data appended for: https://www.transfermarkt.com/kusini-yengi/profil/spieler/708099.
Transfer history data appended for: https://www.transfermarkt.com/ryan-kitto/profil/spieler/296454.
Transfer history data appended for: https://www.transfermarkt.com/james-delianov/profil/spieler/399981.
Transfer history data appended for: https://www.transfermarkt.com/jordan-elsey/profil/spieler/187355.
Transfer history data appended for: https://www.transfermarkt.com/javi-lopez/profil/spieler/72310.
Transfer history data appended for: https://www.transfermarkt.com/joe-gauci/profil/spieler/591844.
Transfer history data appended for: https://www.transfermarkt.com/nathan-konstandopoulos/profil/spieler/306518.
Transfer history data appended for: https://www.transfermarkt.com/adama-traore/profil/spieler/70209.
Transfer history data appended for: https://www.transfermarkt.com/so-nishikawa/profil/spieler/742829.
Transfer history data appended for: https://www.transfermarkt.com/luis-lawrie-lattanzio/profil/spieler/703627.
Transfer history data appended for: https://www.transfermarkt.com/leigh-broxham/profil/spieler/30788.
Transfer history data appended for: https://www.transfermarkt.com/storm-roux/profil/spieler/175699.
Transfer history data appended for: https://www.transfermarkt.com/nick-ansell/profil/spieler/157132.
Transfer history data appended for: https://www.transfermarkt.com/jay-barnett/profil/spieler/647456.
Transfer history data appended for: https://www.transfermarkt.com/jacob-butterfield/profil/spieler/39827.
Transfer history data appended for: https://www.transfermarkt.com/max-crocombe/profil/spieler/207843.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-iannucci/profil/spieler/613516.
Transfer history data appended for: https://www.transfermarkt.com/jake-brimmer/profil/spieler/337282.
Transfer history data appended for: https://www.transfermarkt.com/elvis-kamsoba/profil/spieler/607269.
Transfer history data appended for: https://www.transfermarkt.com/aaron-anderson/profil/spieler/668844.
Transfer history data appended for: https://www.transfermarkt.com/birkan-kirdar/profil/spieler/565527.
Transfer history data appended for: https://www.transfermarkt.com/callum-mcmanaman/profil/spieler/61711.
Transfer history data appended for: https://www.transfermarkt.com/rudy-gestede/profil/spieler/39908.
Transfer history data appended for: https://www.transfermarkt.com/ben-folami/profil/spieler/532107.
Transfer history data appended for: https://www.transfermarkt.com/marco-rojas/profil/spieler/114940.
Transfer history data appended for: https://www.transfermarkt.com/lleyton-brooks/profil/spieler/742831.
Transfer history data appended for: https://www.transfermarkt.com/matt-acton/profil/spieler/124780.
Transfer history data appended for: https://www.transfermarkt.com/dylan-ryan/profil/spieler/480022.
Transfer history data appended for: https://www.transfermarkt.com/brandon-lauton/profil/spieler/692324.
Transfer history data appended for: https://www.transfermarkt.com/denis-genreau/profil/spieler/470618.
Transfer history data appended for: https://www.transfermarkt.com/adam-federici/profil/spieler/4233.
Transfer history data appended for: https://www.transfermarkt.com/nick-suman/profil/spieler/477136.
Transfer history data appended for: https://www.transfermarkt.com/yianni-nicolaou/profil/spieler/607274.
Transfer history data appended for: https://www.transfermarkt.com/liam-rose/profil/spieler/329834.
Transfer history data appended for: https://www.transfermarkt.com/benat-etxebarria/profil/spieler/40888.
Transfer history data appended for: https://www.transfermarkt.com/antonis-martis/profil/spieler/527957.
Transfer history data appended for: https://www.transfermarkt.com/ivan-franjic/profil/spieler/48424.
Transfer history data appended for: https://www.transfermarkt.com/markel-susaeta/profil/spieler/54245.
Transfer history data appended for: https://www.transfermarkt.com/mark-milligan/profil/spieler/37372.
Transfer history data appended for: https://www.transfermarkt.com/jake-hollman/profil/spieler/811400.
Transfer history data appended for: https://www.transfermarkt.com/charles-mbombwa/profil/spieler/603866.
Transfer history data appended for: https://www.transfermarkt.com/jake-mcging/profil/spieler/355721.
Transfer history data appended for: https://www.transfermarkt.com/milislav-popovic/profil/spieler/388303.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-jovanovic/profil/spieler/50377.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-susnjar/profil/spieler/206836.
Transfer history data appended for: https://www.transfermarkt.com/tommy-oar/profil/spieler/80708.
Transfer history data appended for: https://www.transfermarkt.com/loic-puyo/profil/spieler/170916.
Transfer history data appended for: https://www.transfermarkt.com/anthony-golec/profil/spieler/104096.
Transfer history data appended for: https://www.transfermarkt.com/moudi-najjar/profil/spieler/566941.
Transfer history data appended for: https://www.transfermarkt.com/michael-ruhs/profil/spieler/703624.
Transfer history data appended for: https://www.transfermarkt.com/walter-scott/profil/spieler/560827.
Transfer history data appended for: https://www.transfermarkt.com/tim-payne/profil/spieler/149901.
Transfer history data appended for: https://www.transfermarkt.com/matthew-ridenton/profil/spieler/264457.
Transfer history data appended for: https://www.transfermarkt.com/liam-mcging/profil/spieler/675114.
Transfer history data appended for: https://www.transfermarkt.com/joshua-laws/profil/spieler/293742.
Transfer history data appended for: https://www.transfermarkt.com/alex-rufer/profil/spieler/256019.
Transfer history data appended for: https://www.transfermarkt.com/zac-jones/profil/spieler/485667.
Transfer history data appended for: https://www.transfermarkt.com/clayton-lewis/profil/spieler/292982.

Transfer history data appended for: https://www.transfermarkt.com/oskar-van-hattum/profil/spieler/617025.
Transfer history data appended for: https://www.transfermarkt.com/ben-waine/profil/spieler/539502.
Transfer history data appended for: https://www.transfermarkt.com/stefan-marinovic/profil/spieler/120619.
Transfer history data appended for: https://www.transfermarkt.com/luke-devere/profil/spieler/80716.
Transfer history data appended for: https://www.transfermarkt.com/reno-piscopo/profil/spieler/265093.
Transfer history data appended for: https://www.transfermarkt.com/james-mcgarry/profil/spieler/345343.
Transfer history data appended for: https://www.transfermarkt.com/sam-sutton/profil/spieler/470986.
Transfer history data appended for: https://www.transfermarkt.com/louis-fenton/profil/spieler/203552.
Transfer history data appended for: https://www.transfermarkt.com/oliver-sail/profil/spieler/290838.
Transfer history data appended for: https://www.transfermarkt.com/jaushua-sotirio/profil/spieler/302818.
Transfer history data appended for: https://www.transfermarkt.com/cameron-devlin/profil/spieler/399162.
Transfer history data appended for: https://www.transfermarkt.com/mirza-muratovic/profil/spieler/613651.
Transfer history data appended for: https://www.transfermarkt.com/david-ball/profil/spieler/121401.
Transfer history data appended for: https://www.transfermarkt.com/te-atawhai-hudson-wihongi/profil/spieler/204766.
Transfer history data appended for: https://www.transfermarkt.com/ulises-davila/profil/spieler/108820.
Transfer history data appended for: https://www.transfermarkt.com/matt-simon/profil/spieler/43372.
Transfer history data appended for: https://www.transfermarkt.com/matthew-hatch/profil/spieler/831057.
Transfer history data appended for: https://www.transfermarkt.com/mark-moric/profil/spieler/496653.
Transfer history data appended for: https://www.transfermarkt.com/mark-birighitti/profil/spieler/80702.
Transfer history data appended for: https://www.transfermarkt.com/adam-pearce/profil/spieler/345701.
Transfer history data appended for: https://www.transfermarkt.com/jacob-melling/profil/spieler/181924.
Transfer history data appended for: https://www.transfermarkt.com/dylan-ruiz-diaz/profil/spieler/668120.
Transfer history data appended for: https://www.transfermarkt.com/ruon-tongyik/profil/spieler/410067.
Transfer history data appended for: https://www.transfermarkt.com/jack-clisby/profil/spieler/256915.
Transfer history data appended for: https://www.transfermarkt.com/joshua-nisbet/profil/spieler/603863.
Transfer history data appended for: https://www.transfermarkt.com/kye-rowles/profil/spieler/399990.
Transfer history data appended for: https://www.transfermarkt.com/alou-kuol/profil/spieler/748070.
Transfer history data appended for: https://www.transfermarkt.com/ziggy-gordon/profil/spieler/175841.
Transfer history data appended for: https://www.transfermarkt.com/daniel-de-silva/profil/spieler/259721.
Transfer history data appended for: https://www.transfermarkt.com/jair/profil/spieler/148664.
Transfer history data appended for: https://www.transfermarkt.com/gianni-stensness/profil/spieler/627472.
Transfer history data appended for: https://www.transfermarkt.com/oliver-bozanic/profil/spieler/43117.
Transfer history data appended for: https://www.transfermarkt.com/daniel-bouman/profil/spieler/411483.
Transfer history data appended for: https://www.transfermarkt.com/louis-khoury/profil/spieler/506211.
Transfer history data appended for: https://www.transfermarkt.com/daniel-hall/profil/spieler/833592.
Transfer history data appended for: https://www.transfermarkt.com/lewis-miller/profil/spieler/603864.
Transfer history data appended for: https://www.transfermarkt.com/bernie-ibini-isei/profil/spieler/140205.
Transfer history data appended for: https://www.transfermarkt.com/john-koutroumbis/profil/spieler/456583.
Transfer history data appended for: https://www.transfermarkt.com/jack-simmons/profil/spieler/596086.
Transfer history data appended for: https://www.transfermarkt.com/angus-thurgate/profil/spieler/559464.
Transfer history data appended for: https://www.transfermarkt.com/steven-ugarkovic/profil/spieler/262971.
Transfer history data appended for: https://www.transfermarkt.com/lachlan-jackson/profil/spieler/298883.
Transfer history data appended for: https://www.transfermarkt.com/joe-ledley/profil/spieler/34409.
Transfer history data appended for: https://www.transfermarkt.com/ben-kantarovski/profil/spieler/66394.
Transfer history data appended for: https://www.transfermarkt.com/connor-otoole/profil/spieler/434225.
Transfer history data appended for: https://www.transfermarkt.com/kaine-sheppard/profil/spieler/237533.
Transfer history data appended for: https://www.transfermarkt.com/jason-hoffman/profil/spieler/62839.
Transfer history data appended for: https://www.transfermarkt.com/nigel-boogaard/profil/spieler/43116.
Transfer history data appended for: https://www.transfermarkt.com/makis-petratos/profil/spieler/614402.
Transfer history data appended for: https://www.transfermarkt.com/nikolai-topor-stanley/profil/spieler/37870.
Transfer history data appended for: https://www.transfermarkt.com/lewis-italiano/profil/spieler/204381.
Transfer history data appended for: https://www.transfermarkt.com/michael-neill/profil/spieler/265715.
Transfer history data appended for: https://www.transfermarkt.com/roy-odonovan/profil/spieler/34629.
Transfer history data appended for: https://www.transfermarkt.com/kosta-petratos/profil/spieler/418026.
Transfer history data appended for: https://www.transfermarkt.com/noah-james/profil/spieler/471494.
Transfer history data appended for: https://www.transfermarkt.com/ramy-najjarine/profil/spieler/448337.
Transfer history data appended for: https://www.transfermarkt.com/patrick-langlois/profil/spieler/601976.
Transfer history data appended for: https://www.transfermarkt.com/ignace-van-der-brempt/profil/spieler/490423.
Transfer history data appended for: https://www.transfermarkt.com/ethan-horvath/profil/spieler/242284.
Transfer history data appended for: https://www.transfermarkt.com/eder-balanta/profil/spieler/265127.
Transfer history data appended for: https://www.transfermarkt.com/krepin-diatta/profil/spieler/490426.
Transfer history data appended for: https://www.transfermarkt.com/youssouph-badji/profil/spieler/649035.
Transfer history data appended for: https://www.transfermarkt.com/david-okereke/profil/spieler/413605.
Transfer history data appended for: https://www.transfermarkt.com/senne-lammens/profil/spieler/503883.
Transfer history data appended for: https://www.transfermarkt.com/simon-mignolet/profil/spieler/50219.
Transfer history data appended for: https://www.transfermarkt.com/odilon-kossounou/profil/spieler/644771.
Transfer history data appended for: https://www.transfermarkt.com/michael-krmencik/profil/spieler/178469.
Transfer history data appended for: https://www.transfermarkt.com/amadou-sagna/profil/spieler/649025.
Transfer history data appended for: https://www.transfermarkt.com/ruud-vormer/profil/spieler/45864.
Transfer history data appended for: https://www.transfermarkt.com/thomas-van-den-keybus/profil/spieler/502298.
Transfer history data appended for: https://www.transfermarkt.com/siebe-schrijvers/profil/spieler/208552.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-dennis/profil/spieler/448854.
Transfer history data appended for: https://www.transfermarkt.com/maxim-de-cuyper/profil/spieler/429915.
Transfer history data appended for: https://www.transfermarkt.com/charles-de-ketelaere/profil/spieler/435772.
Transfer history data appended for: https://www.transfermarkt.com/noa-lang/profil/spieler/339332.
Transfer history data appended for: https://www.transfermarkt.com/brandon-mechele/profil/spieler/236168.
Transfer history data appended for: https://www.transfermarkt.com/mats-rits/profil/spieler/92164.
Transfer history data appended for: https://www.transfermarkt.com/eduard-sobol/profil/spieler/206717.
Transfer history data appended for: https://www.transfermarkt.com/simon-deli/profil/spieler/234124.
Transfer history data appended for: https://www.transfermarkt.com/nick-shinton/profil/spieler/409533.

Transfer history data appended for: https://www.transfermarkt.com/federico-ricca/profil/spieler/285322.
Transfer history data appended for: https://www.transfermarkt.com/hans-vanaken/profil/spieler/137576.
Transfer history data appended for: https://www.transfermarkt.com/dylan-ouedraogo/profil/spieler/460648.
Transfer history data appended for: https://www.transfermarkt.com/casper-de-norre/profil/spieler/292806.
Transfer history data appended for: https://www.transfermarkt.com/yohan-croizet/profil/spieler/195910.
Transfer history data appended for: https://www.transfermarkt.com/oregan-ravet/profil/spieler/547889.
Transfer history data appended for: https://www.transfermarkt.com/kamal-sowah/profil/spieler/564489.
Transfer history data appended for: https://www.transfermarkt.com/thomas-henry/profil/spieler/412513.
Transfer history data appended for: https://www.transfermarkt.com/aboubakar-keita/profil/spieler/294807.
Transfer history data appended for: https://www.transfermarkt.com/milan-tucic/profil/spieler/513646.
Transfer history data appended for: https://www.transfermarkt.com/stallone-limbombe/profil/spieler/292615.
Transfer history data appended for: https://www.transfermarkt.com/david-hubert/profil/spieler/52811.
Transfer history data appended for: https://www.transfermarkt.com/pierre-yves-ngawa/profil/spieler/140786.
Transfer history data appended for: https://www.transfermarkt.com/thibault-vlietinck/profil/spieler/249568.
Transfer history data appended for: https://www.transfermarkt.com/yannick-aguemon/profil/spieler/170485.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-maertens/profil/spieler/310131.
Transfer history data appended for: https://www.transfermarkt.com/kristiyan-malinov/profil/spieler/282897.
Transfer history data appended for: https://www.transfermarkt.com/josh-eppiah/profil/spieler/455917.
Transfer history data appended for: https://www.transfermarkt.com/derrick-tshimanga/profil/spieler/78507.
Transfer history data appended for: https://www.transfermarkt.com/frederic-duplus/profil/spieler/77829.
Transfer history data appended for: https://www.transfermarkt.com/arthur-allemeersch/profil/spieler/565019.
Transfer history data appended for: https://www.transfermarkt.com/sascha-kotysch/profil/spieler/41125.
Transfer history data appended for: https://www.transfermarkt.com/rafael-romo/profil/spieler/101031.
Transfer history data appended for: https://www.transfermarkt.com/jordy-gillekens/profil/spieler/465307.
Transfer history data appended for: https://www.transfermarkt.com/olivier-myny/profil/spieler/316406.
Transfer history data appended for: https://www.transfermarkt.com/daniel-iversen/profil/spieler/260841.
Transfer history data appended for: https://www.transfermarkt.com/xavier-mercier/profil/spieler/190146.
Transfer history data appended for: https://www.transfermarkt.com/kenneth-schuermans/profil/spieler/217776.
Transfer history data appended for: https://www.transfermarkt.com/isaac-asante/profil/spieler/719654.
Transfer history data appended for: https://www.transfermarkt.com/musa-al-tamari/profil/spieler/551505.
Transfer history data appended for: https://www.transfermarkt.com/tristan-borges/profil/spieler/402531.
Transfer history data appended for: https://www.transfermarkt.com/barnabas-bese/profil/spieler/148809.
Transfer history data appended for: https://www.transfermarkt.com/jonah-osabutey/profil/spieler/269766.
Transfer history data appended for: https://www.transfermarkt.com/daan-vekemans/profil/spieler/481640.
Transfer history data appended for: https://www.transfermarkt.com/toon-raemaekers/profil/spieler/712086.
Transfer history data appended for: https://www.transfermarkt.com/tom-van-hyfte/profil/spieler/22372.
Transfer history data appended for: https://www.transfermarkt.com/samy-kehli/profil/spieler/176026.
Transfer history data appended for: https://www.transfermarkt.com/boris-lambert/profil/spieler/585711.
Transfer history data appended for: https://www.transfermarkt.com/ortwin-de-wolf/profil/spieler/450218.
Transfer history data appended for: https://www.transfermarkt.com/jens-cools/profil/spieler/142929.
Transfer history data appended for: https://www.transfermarkt.com/menno-koch/profil/spieler/182578.
Transfer history data appended for: https://www.transfermarkt.com/pierre-ramses-akono/profil/spieler/625861.
Transfer history data appended for: https://www.transfermarkt.com/smail-prevljak/profil/spieler/328264.
Transfer history data appended for: https://www.transfermarkt.com/theo-defourny/profil/spieler/104543.
Transfer history data appended for: https://www.transfermarkt.com/benoit-poulain/profil/spieler/80188.
Transfer history data appended for: https://www.transfermarkt.com/edo-kayembe/profil/spieler/486477.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-kone/profil/spieler/171165.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-agbadou/profil/spieler/683895.
Transfer history data appended for: https://www.transfermarkt.com/abdul-nurudeen/profil/spieler/511168.
Transfer history data appended for: https://www.transfermarkt.com/silas-gnaka/profil/spieler/481091.
Transfer history data appended for: https://www.transfermarkt.com/stef-peeters/profil/spieler/208542.
Transfer history data appended for: https://www.transfermarkt.com/sibiry-keita/profil/spieler/565778.
Transfer history data appended for: https://www.transfermarkt.com/adriano/profil/spieler/34495.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-heris/profil/spieler/101531.
Transfer history data appended for: https://www.transfermarkt.com/jordi-amat/profil/spieler/85289.
Transfer history data appended for: https://www.transfermarkt.com/isaac-nuhu/profil/spieler/740615.
Transfer history data appended for: https://www.transfermarkt.com/nils-schouterden/profil/spieler/62700.
Transfer history data appended for: https://www.transfermarkt.com/senna-miangue/profil/spieler/249552.
Transfer history data appended for: https://www.transfermarkt.com/konan-n-rsquo-dri/profil/spieler/649490.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-sowah-adjei/profil/spieler/408839.
Transfer history data appended for: https://www.transfermarkt.com/julien-ngoy/profil/spieler/286005.
Transfer history data appended for: https://www.transfermarkt.com/gary-magnee/profil/spieler/679050.
Transfer history data appended for: https://www.transfermarkt.com/laurent-henkinet/profil/spieler/157125.
Transfer history data appended for: https://www.transfermarkt.com/john-nekadio/profil/spieler/740039.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-carcela-gonzalez/profil/spieler/42714.
Transfer history data appended for: https://www.transfermarkt.com/maxime-lestienne/profil/spieler/96454.
Transfer history data appended for: https://www.transfermarkt.com/joachim-carcela-gonzalez/profil/spieler/381965.
Transfer history data appended for: https://www.transfermarkt.com/eddy-sylvestre/profil/spieler/629566.
Transfer history data appended for: https://www.transfermarkt.com/gojko-cimirot/profil/spieler/150482.
Transfer history data appended for: https://www.transfermarkt.com/moussa-sissako/profil/spieler/536475.
Transfer history data appended for: https://www.transfermarkt.com/felipe-avenatti/profil/spieler/216375.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-boljevic/profil/spieler/227532.
Transfer history data appended for: https://www.transfermarkt.com/zinho-vanheusden/profil/spieler/338672.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-gavory/profil/spieler/182816.
Transfer history data appended for: https://www.transfermarkt.com/jean-francois-gillet/profil/spieler/22149.
Transfer history data appended for: https://www.transfermarkt.com/merveille-bokadi/profil/spieler/368612.
Transfer history data appended for: https://www.transfermarkt.com/mitchy-ntelo/profil/spieler/706860.
Transfer history data appended for: https://www.transfermarkt.com/samuel-bastien/profil/spieler/289510.
Transfer history data appended for: https://www.transfermarkt.com/obbi-oulare/profil/spieler/314959.

Transfer history data appended for: https://www.transfermarkt.com/arnaud-bodart/profil/spieler/417278.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-raskin/profil/spieler/422763.
Transfer history data appended for: https://www.transfermarkt.com/collins-fai/profil/spieler/250638.
Transfer history data appended for: https://www.transfermarkt.com/abdoul-tapsoba/profil/spieler/640735.
Transfer history data appended for: https://www.transfermarkt.com/jackson-muleka/profil/spieler/549966.
Transfer history data appended for: https://www.transfermarkt.com/william-balikwisha/profil/spieler/381968.
Transfer history data appended for: https://www.transfermarkt.com/michel-ange-balikwisha/profil/spieler/502239.
Transfer history data appended for: https://www.transfermarkt.com/eden-shamir/profil/spieler/204111.
Transfer history data appended for: https://www.transfermarkt.com/damjan-pavlovic/profil/spieler/409511.
Transfer history data appended for: https://www.transfermarkt.com/noe-dussenne/profil/spieler/160736.
Transfer history data appended for: https://www.transfermarkt.com/laurent-jans/profil/spieler/163724.
Transfer history data appended for: https://www.transfermarkt.com/selim-amallah/profil/spieler/377219.
Transfer history data appended for: https://www.transfermarkt.com/michel-vlap/profil/spieler/342702.
Transfer history data appended for: https://www.transfermarkt.com/ognjen-vranjes/profil/spieler/94807.
Transfer history data appended for: https://www.transfermarkt.com/yari-verschaeren/profil/spieler/502302.
Transfer history data appended for: https://www.transfermarkt.com/elias-cobbaut/profil/spieler/419723.
Transfer history data appended for: https://www.transfermarkt.com/mustapha-bundu/profil/spieler/457728.
Transfer history data appended for: https://www.transfermarkt.com/adrien-trebel/profil/spieler/159622.
Transfer history data appended for: https://www.transfermarkt.com/zakaria-bakkali/profil/spieler/203378.
Transfer history data appended for: https://www.transfermarkt.com/rik-vercauteren/profil/spieler/463737.
Transfer history data appended for: https://www.transfermarkt.com/hendrik-van-crombrugge/profil/spieler/137326.
Transfer history data appended for: https://www.transfermarkt.com/marco-kana/profil/spieler/486051.
Transfer history data appended for: https://www.transfermarkt.com/michael-murillo/profil/spieler/354482.
Transfer history data appended for: https://www.transfermarkt.com/timon-wellenreuther/profil/spieler/196829.
Transfer history data appended for: https://www.transfermarkt.com/hannes-delcroix/profil/spieler/338635.
Transfer history data appended for: https://www.transfermarkt.com/antonio-milic/profil/spieler/179896.
Transfer history data appended for: https://www.transfermarkt.com/ilias-takidine/profil/spieler/488768.
Transfer history data appended for: https://www.transfermarkt.com/josh-cullen/profil/spieler/242606.
Transfer history data appended for: https://www.transfermarkt.com/albert-sambi-lokonga/profil/spieler/381967.
Transfer history data appended for: https://www.transfermarkt.com/peter-zulj/profil/spieler/128105.
Transfer history data appended for: https://www.transfermarkt.com/kristian-arnstad/profil/spieler/581106.
Transfer history data appended for: https://www.transfermarkt.com/anouar-ait-el-hadj/profil/spieler/486039.
Transfer history data appended for: https://www.transfermarkt.com/francis-amuzu/profil/spieler/423604.
Transfer history data appended for: https://www.transfermarkt.com/lukas-nmecha/profil/spieler/314288.
Transfer history data appended for: https://www.transfermarkt.com/bart-verbruggen/profil/spieler/565093.
Transfer history data appended for: https://www.transfermarkt.com/killian-sardella/profil/spieler/454336.
Transfer history data appended for: https://www.transfermarkt.com/percy-tau/profil/spieler/312239.
Transfer history data appended for: https://www.transfermarkt.com/kemar-lawrence/profil/spieler/288710.
Transfer history data appended for: https://www.transfermarkt.com/bubacarr-sanneh/profil/spieler/292366.
Transfer history data appended for: https://www.transfermarkt.com/antoine-colassin/profil/spieler/440953.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-mykhaylichenko/profil/spieler/294730.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-dauda/profil/spieler/360711.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-albanese/profil/spieler/407347.
Transfer history data appended for: https://www.transfermarkt.com/georges-mandjeck/profil/spieler/52112.
Transfer history data appended for: https://www.transfermarkt.com/nikola-pej%C4%8Di%C4%87/profil/spieler/840907.
Transfer history data appended for: https://www.transfermarkt.com/melvin-sitti/profil/spieler/689089.
Transfer history data appended for: https://www.transfermarkt.com/matthias-verreth/profil/spieler/292817.
Transfer history data appended for: https://www.transfermarkt.com/andreas-wiegel/profil/spieler/45698.
Transfer history data appended for: https://www.transfermarkt.com/denzel-jubitana/profil/spieler/502893.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-vukotic/profil/spieler/398851.
Transfer history data appended for: https://www.transfermarkt.com/danel-sinani/profil/spieler/346499.
Transfer history data appended for: https://www.transfermarkt.com/milan-de-mey/profil/spieler/558553.
Transfer history data appended for: https://www.transfermarkt.com/serge-leuko/profil/spieler/184917.
Transfer history data appended for: https://www.transfermarkt.com/brendan-schoonbaert/profil/spieler/369159.
Transfer history data appended for: https://www.transfermarkt.com/nordin-jackers/profil/spieler/250543.
Transfer history data appended for: https://www.transfermarkt.com/brent-gabriel/profil/spieler/338665.
Transfer history data appended for: https://www.transfermarkt.com/alexis-gamboa/profil/spieler/452714.
Transfer history data appended for: https://www.transfermarkt.com/dries-wuytens/profil/spieler/83951.
Transfer history data appended for: https://www.transfermarkt.com/djihad-bizimana/profil/spieler/418173.
Transfer history data appended for: https://www.transfermarkt.com/lucas-pirard/profil/spieler/168166.
Transfer history data appended for: https://www.transfermarkt.com/andrija-vukcevic/profil/spieler/294987.
Transfer history data appended for: https://www.transfermarkt.com/paul-keita/profil/spieler/164735.
Transfer history data appended for: https://www.transfermarkt.com/daan-heymans/profil/spieler/446491.
Transfer history data appended for: https://www.transfermarkt.com/din-sula/profil/spieler/358907.
Transfer history data appended for: https://www.transfermarkt.com/jur-schryvers/profil/spieler/250574.
Transfer history data appended for: https://www.transfermarkt.com/jenthe-mertens/profil/spieler/526469.
Transfer history data appended for: https://www.transfermarkt.com/tom-reyners/profil/spieler/358042.
Transfer history data appended for: https://www.transfermarkt.com/joseph-efford/profil/spieler/537467.
Transfer history data appended for: https://www.transfermarkt.com/jordan-faucher/profil/spieler/169757.
Transfer history data appended for: https://www.transfermarkt.com/amine-khammas/profil/spieler/401938.
Transfer history data appended for: https://www.transfermarkt.com/aboubakary-koita/profil/spieler/422377.
Transfer history data appended for: https://www.transfermarkt.com/miguel-vieira/profil/spieler/214300.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-bertone/profil/spieler/194975.
Transfer history data appended for: https://www.transfermarkt.com/seung-woo-lee/profil/spieler/280239.
Transfer history data appended for: https://www.transfermarkt.com/duckens-nazon/profil/spieler/345763.
Transfer history data appended for: https://www.transfermarkt.com/yuma-suzuki/profil/spieler/345323.
Transfer history data appended for: https://www.transfermarkt.com/liberato-cacace/profil/spieler/469211.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-buatu/profil/spieler/137313.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-sory-sankhon/profil/spieler/426648.

Transfer history data appended for: https://www.transfermarkt.com/keito-nakamura/profil/spieler/405397.
Transfer history data appended for: https://www.transfermarkt.com/mory-konate/profil/spieler/364370.
Transfer history data appended for: https://www.transfermarkt.com/kenny-steppe/profil/spieler/42531.
Transfer history data appended for: https://www.transfermarkt.com/steve-de-ridder/profil/spieler/41818.
Transfer history data appended for: https://www.transfermarkt.com/siebren-lathouwers/profil/spieler/452580.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-filippov/profil/spieler/237623.
Transfer history data appended for: https://www.transfermarkt.com/georgios-vagiannidis/profil/spieler/546186.
Transfer history data appended for: https://www.transfermarkt.com/tatsuya-ito/profil/spieler/381248.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-caufriez/profil/spieler/369267.
Transfer history data appended for: https://www.transfermarkt.com/nelson-balongo/profil/spieler/583756.
Transfer history data appended for: https://www.transfermarkt.com/samy-mmaee/profil/spieler/331840.
Transfer history data appended for: https://www.transfermarkt.com/hamza-masoudi/profil/spieler/597095.
Transfer history data appended for: https://www.transfermarkt.com/jorge-teixeira/profil/spieler/59791.
Transfer history data appended for: https://www.transfermarkt.com/pol-garcia/profil/spieler/178217.
Transfer history data appended for: https://www.transfermarkt.com/wolke-janssens/profil/spieler/235247.
Transfer history data appended for: https://www.transfermarkt.com/samuel-asamoah/profil/spieler/232848.
Transfer history data appended for: https://www.transfermarkt.com/ko-matsubara/profil/spieler/307300.
Transfer history data appended for: https://www.transfermarkt.com/daniel-schmidt/profil/spieler/158799.
Transfer history data appended for: https://www.transfermarkt.com/facundo-colidio/profil/spieler/491705.
Transfer history data appended for: https://www.transfermarkt.com/wim-vanmarsenille/profil/spieler/706037.
Transfer history data appended for: https://www.transfermarkt.com/stan-van-dessel/profil/spieler/480265.
Transfer history data appended for: https://www.transfermarkt.com/ike-ugbo/profil/spieler/339943.
Transfer history data appended for: https://www.transfermarkt.com/jean-marcelin/profil/spieler/475412.
Transfer history data appended for: https://www.transfermarkt.com/kylian-hazard/profil/spieler/275457.
Transfer history data appended for: https://www.transfermarkt.com/miguel-van-damme/profil/spieler/321571.
Transfer history data appended for: https://www.transfermarkt.com/merveille-goblet/profil/spieler/193470.
Transfer history data appended for: https://www.transfermarkt.com/charles-vanhoutte/profil/spieler/569845.
Transfer history data appended for: https://www.transfermarkt.com/calvin-dekuyper/profil/spieler/719455.
Transfer history data appended for: https://www.transfermarkt.com/vitinho/profil/spieler/468249.
Transfer history data appended for: https://www.transfermarkt.com/anthony-musaba/profil/spieler/511401.
Transfer history data appended for: https://www.transfermarkt.com/andi-koshi/profil/spieler/502268.
Transfer history data appended for: https://www.transfermarkt.com/warleson/profil/spieler/477460.
Transfer history data appended for: https://www.transfermarkt.com/thibo-somers/profil/spieler/719456.
Transfer history data appended for: https://www.transfermarkt.com/david-bates/profil/spieler/272539.
Transfer history data appended for: https://www.transfermarkt.com/johanna-omolo/profil/spieler/85834.
Transfer history data appended for: https://www.transfermarkt.com/aldom-deuro/profil/spieler/648971.
Transfer history data appended for: https://www.transfermarkt.com/dimitar-velkovski/profil/spieler/323403.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-taravel/profil/spieler/56821.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-da-silva-lopes/profil/spieler/348756.
Transfer history data appended for: https://www.transfermarkt.com/arne-cassaert/profil/spieler/725003.
Transfer history data appended for: https://www.transfermarkt.com/naomichi-ueda/profil/spieler/188915.
Transfer history data appended for: https://www.transfermarkt.com/alexander-corryn/profil/spieler/129580.
Transfer history data appended for: https://www.transfermarkt.com/giulian-biancone/profil/spieler/536507.
Transfer history data appended for: https://www.transfermarkt.com/franck-kanoute/profil/spieler/478198.
Transfer history data appended for: https://www.transfermarkt.com/robbe-decostere/profil/spieler/601407.
Transfer history data appended for: https://www.transfermarkt.com/serge-philippe-raux-yao/profil/spieler/683891.
Transfer history data appended for: https://www.transfermarkt.com/dino-hotic/profil/spieler/183836.
Transfer history data appended for: https://www.transfermarkt.com/kevin-hoggas/profil/spieler/379737.
Transfer history data appended for: https://www.transfermarkt.com/olivier-deman/profil/spieler/621802.
Transfer history data appended for: https://www.transfermarkt.com/bram-castro/profil/spieler/13283.
Transfer history data appended for: https://www.transfermarkt.com/ari-freyr-skulason/profil/spieler/42948.
Transfer history data appended for: https://www.transfermarkt.com/evangelos-patoulidis/profil/spieler/375718.
Transfer history data appended for: https://www.transfermarkt.com/maxime-darpino/profil/spieler/346290.
Transfer history data appended for: https://www.transfermarkt.com/robbie-dhaese/profil/spieler/460379.
Transfer history data appended for: https://www.transfermarkt.com/jordy-schelfhout/profil/spieler/688245.
Transfer history data appended for: https://www.transfermarkt.com/cameron-mcgeehan/profil/spieler/167265.
Transfer history data appended for: https://www.transfermarkt.com/marko-kvasina/profil/spieler/240778.
Transfer history data appended for: https://www.transfermarkt.com/jack-hendry/profil/spieler/363223.
Transfer history data appended for: https://www.transfermarkt.com/arthur-theate/profil/spieler/368891.
Transfer history data appended for: https://www.transfermarkt.com/francois-marquet/profil/spieler/194438.
Transfer history data appended for: https://www.transfermarkt.com/jorben-vanhulle/profil/spieler/433615.
Transfer history data appended for: https://www.transfermarkt.com/brecht-capon/profil/spieler/42703.
Transfer history data appended for: https://www.transfermarkt.com/makhtar-gueye/profil/spieler/606849.
Transfer history data appended for: https://www.transfermarkt.com/indy-boonen/profil/spieler/338817.
Transfer history data appended for: https://www.transfermarkt.com/frederik-jakel/profil/spieler/405679.
Transfer history data appended for: https://www.transfermarkt.com/guillaume-hubert/profil/spieler/129585.
Transfer history data appended for: https://www.transfermarkt.com/kevin-vandendriessche/profil/spieler/174285.
Transfer history data appended for: https://www.transfermarkt.com/nick-batzner/profil/spieler/443855.
Transfer history data appended for: https://www.transfermarkt.com/jelle-bataille/profil/spieler/460378.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-thiam/profil/spieler/368624.
Transfer history data appended for: https://www.transfermarkt.com/anton-tanghe/profil/spieler/460848.
Transfer history data appended for: https://www.transfermarkt.com/theo-ndicka-matam/profil/spieler/461595.
Transfer history data appended for: https://www.transfermarkt.com/fabrice-ondoa/profil/spieler/220999.
Transfer history data appended for: https://www.transfermarkt.com/andrew-hjulsager/profil/spieler/167798.
Transfer history data appended for: https://www.transfermarkt.com/sindrit-guri/profil/spieler/189604.
Transfer history data appended for: https://www.transfermarkt.com/toby-sibbick/profil/spieler/484215.
Transfer history data appended for: https://www.transfermarkt.com/fashion-sakala/profil/spieler/485729.
Transfer history data appended for: https://www.transfermarkt.com/pape-habib-gueye/profil/spieler/585339.
Transfer history data appended for: https://www.transfermarkt.com/sambou-sissoko/profil/spieler/649019.

Transfer history data appended for: https://www.transfermarkt.com/marko-ilic/profil/spieler/343953.
Transfer history data appended for: https://www.transfermarkt.com/petar-golubovic/profil/spieler/239783.
Transfer history data appended for: https://www.transfermarkt.com/lucas-rougeaux/profil/spieler/226288.
Transfer history data appended for: https://www.transfermarkt.com/adam-jakubech/profil/spieler/258267.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-badamosi/profil/spieler/369384.
Transfer history data appended for: https://www.transfermarkt.com/michiel-jonckheere/profil/spieler/150711.
Transfer history data appended for: https://www.transfermarkt.com/hannes-van-der-bruggen/profil/spieler/110822.
Transfer history data appended for: https://www.transfermarkt.com/julien-de-sart/profil/spieler/129592.
Transfer history data appended for: https://www.transfermarkt.com/jovan-stojanovic/profil/spieler/175440.
Transfer history data appended for: https://www.transfermarkt.com/kristof-dhaene/profil/spieler/156496.
Transfer history data appended for: https://www.transfermarkt.com/maxim-deman/profil/spieler/688246.
Transfer history data appended for: https://www.transfermarkt.com/brendan-hines-ike/profil/spieler/411302.
Transfer history data appended for: https://www.transfermarkt.com/eric-ocansey/profil/spieler/380416.
Transfer history data appended for: https://www.transfermarkt.com/faiz-selemani/profil/spieler/352017.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-makarenko/profil/spieler/96455.
Transfer history data appended for: https://www.transfermarkt.com/timothy-derijck/profil/spieler/31131.
Transfer history data appended for: https://www.transfermarkt.com/christophe-lepoint/profil/spieler/4742.
Transfer history data appended for: https://www.transfermarkt.com/trent-sainsbury/profil/spieler/145840.
Transfer history data appended for: https://www.transfermarkt.com/ilombe-mboyo/profil/spieler/96227.
Transfer history data appended for: https://www.transfermarkt.com/luqman-hakim/profil/spieler/541749.
Transfer history data appended for: https://www.transfermarkt.com/gilles-dewaele/profil/spieler/250138.
Transfer history data appended for: https://www.transfermarkt.com/pieter-gerkens/profil/spieler/183383.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-gelin/profil/spieler/288237.
Transfer history data appended for: https://www.transfermarkt.com/alireza-beiranvand/profil/spieler/229081.
Transfer history data appended for: https://www.transfermarkt.com/moustafa-ava-dongo/profil/spieler/708876.
Transfer history data appended for: https://www.transfermarkt.com/jordan-lukaku/profil/spieler/140804.
Transfer history data appended for: https://www.transfermarkt.com/simen-juklerod/profil/spieler/230985.
Transfer history data appended for: https://www.transfermarkt.com/alexis-de-sart/profil/spieler/323713.
Transfer history data appended for: https://www.transfermarkt.com/bruny-nsimba/profil/spieler/452584.
Transfer history data appended for: https://www.transfermarkt.com/davor-matijas/profil/spieler/357780.
Transfer history data appended for: https://www.transfermarkt.com/lior-refaelov/profil/spieler/24484.
Transfer history data appended for: https://www.transfermarkt.com/dylan-batubinsika/profil/spieler/289432.
Transfer history data appended for: https://www.transfermarkt.com/koji-miyoshi/profil/spieler/295060.
Transfer history data appended for: https://www.transfermarkt.com/jean-butez/profil/spieler/290537.
Transfer history data appended for: https://www.transfermarkt.com/guy-mbenza/profil/spieler/506948.
Transfer history data appended for: https://www.transfermarkt.com/dieumerci-mbokani/profil/spieler/44624.
Transfer history data appended for: https://www.transfermarkt.com/benson-manuel/profil/spieler/322702.
Transfer history data appended for: https://www.transfermarkt.com/ritchie-de-laet/profil/spieler/55687.
Transfer history data appended for: https://www.transfermarkt.com/ivo-rodrigues/profil/spieler/215122.
Transfer history data appended for: https://www.transfermarkt.com/jae-ik-lee/profil/spieler/297709.
Transfer history data appended for: https://www.transfermarkt.com/ruben-geeraerts/profil/spieler/687628.
Transfer history data appended for: https://www.transfermarkt.com/nill-de-pauw/profil/spieler/52746.
Transfer history data appended for: https://www.transfermarkt.com/junior-pius/profil/spieler/314969.
Transfer history data appended for: https://www.transfermarkt.com/aurelio-buta/profil/spieler/258039.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-seck/profil/spieler/265383.
Transfer history data appended for: https://www.transfermarkt.com/martin-hongla/profil/spieler/398808.
Transfer history data appended for: https://www.transfermarkt.com/didier-lamkel-ze/profil/spieler/442320.
Transfer history data appended for: https://www.transfermarkt.com/dragan-lausberg/profil/spieler/435775.
Transfer history data appended for: https://www.transfermarkt.com/sander-coopman/profil/spieler/279254.
Transfer history data appended for: https://www.transfermarkt.com/matheus/profil/spieler/412688.
Transfer history data appended for: https://www.transfermarkt.com/nana-ampomah/profil/spieler/429086.
Transfer history data appended for: https://www.transfermarkt.com/frank-boya/profil/spieler/473201.
Transfer history data appended for: https://www.transfermarkt.com/louis-verstraete/profil/spieler/396841.
Transfer history data appended for: https://www.transfermarkt.com/faris-haroun/profil/spieler/16617.
Transfer history data appended for: https://www.transfermarkt.com/modou-diagne/profil/spieler/256902.
Transfer history data appended for: https://www.transfermarkt.com/ivan-goranov/profil/spieler/183538.
Transfer history data appended for: https://www.transfermarkt.com/amine-benchaib/profil/spieler/503855.
Transfer history data appended for: https://www.transfermarkt.com/ali-gholizadeh/profil/spieler/294772.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-teodorczyk/profil/spieler/157849.
Transfer history data appended for: https://www.transfermarkt.com/remy-descamps/profil/spieler/282028.
Transfer history data appended for: https://www.transfermarkt.com/saido-berahino/profil/spieler/128897.
Transfer history data appended for: https://www.transfermarkt.com/guillaume-gillet/profil/spieler/31952.
Transfer history data appended for: https://www.transfermarkt.com/kaveh-rezaei/profil/spieler/132553.
Transfer history data appended for: https://www.transfermarkt.com/ryota-morioka/profil/spieler/140310.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-fall/profil/spieler/289713.
Transfer history data appended for: https://www.transfermarkt.com/marco-ilaimaharitra/profil/spieler/205550.
Transfer history data appended for: https://www.transfermarkt.com/lucas-ribeiro-costa/profil/spieler/612880.
Transfer history data appended for: https://www.transfermarkt.com/jules-van-cleemput/profil/spieler/384280.
Transfer history data appended for: https://www.transfermarkt.com/dorian-dessoleil/profil/spieler/182424.
Transfer history data appended for: https://www.transfermarkt.com/joachim-imbrechts/profil/spieler/502261.
Transfer history data appended for: https://www.transfermarkt.com/parfait-mandanda/profil/spieler/86055.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-hendrickx/profil/spieler/161658.
Transfer history data appended for: https://www.transfermarkt.com/steeven-willems/profil/spieler/203539.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-penneteau/profil/spieler/5578.
Transfer history data appended for: https://www.transfermarkt.com/massimo-bruno/profil/spieler/111376.
Transfer history data appended for: https://www.transfermarkt.com/christophe-diandy/profil/spieler/105352.
Transfer history data appended for: https://www.transfermarkt.com/joris-kayembe/profil/spieler/129586.
Transfer history data appended for: https://www.transfermarkt.com/ken-nkuba/profil/spieler/627939.
Transfer history data appended for: https://www.transfermarkt.com/gjoko-zajkov/profil/spieler/205849.

Transfer history data appended for: https://www.transfermarkt.com/jon-flanagan/profil/spieler/145922.
Transfer history data appended for: https://www.transfermarkt.com/shamar-nicholson/profil/spieler/354666.
Transfer history data appended for: https://www.transfermarkt.com/luka-zarandia/profil/spieler/250073.
Transfer history data appended for: https://www.transfermarkt.com/eike-bansen/profil/spieler/287025.
Transfer history data appended for: https://www.transfermarkt.com/ewoud-pletinckx/profil/spieler/491298.
Transfer history data appended for: https://www.transfermarkt.com/tomas-chory/profil/spieler/198614.
Transfer history data appended for: https://www.transfermarkt.com/olivier-deschacht/profil/spieler/9593.
Transfer history data appended for: https://www.transfermarkt.com/jannes-van-hecke/profil/spieler/620566.
Transfer history data appended for: https://www.transfermarkt.com/erdin-demir/profil/spieler/151567.
Transfer history data appended for: https://www.transfermarkt.com/maxime-thiel/profil/spieler/464068.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-seck/profil/spieler/209933.
Transfer history data appended for: https://www.transfermarkt.com/bassem-srarfi/profil/spieler/401836.
Transfer history data appended for: https://www.transfermarkt.com/daniel-opare/profil/spieler/65781.
Transfer history data appended for: https://www.transfermarkt.com/damien-marcq/profil/spieler/57534.
Transfer history data appended for: https://www.transfermarkt.com/gianni-bruno/profil/spieler/95604.
Transfer history data appended for: https://www.transfermarkt.com/louis-bostyn/profil/spieler/159382.
Transfer history data appended for: https://www.transfermarkt.com/william-bianda/profil/spieler/427197.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-kainourgios/profil/spieler/493332.
Transfer history data appended for: https://www.transfermarkt.com/laurens-de-bock/profil/spieler/110668.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-de-smet/profil/spieler/499956.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-armenakas/profil/spieler/336679.
Transfer history data appended for: https://www.transfermarkt.com/sammy-bossut/profil/spieler/48064.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-sissako/profil/spieler/418661.
Transfer history data appended for: https://www.transfermarkt.com/jelle-vossen/profil/spieler/42748.
Transfer history data appended for: https://www.transfermarkt.com/cameron-humphreys/profil/spieler/277723.
Transfer history data appended for: https://www.transfermarkt.com/mikael-soisalo/profil/spieler/323010.
Transfer history data appended for: https://www.transfermarkt.com/abdallah-ali-mohamed/profil/spieler/517372.
Transfer history data appended for: https://www.transfermarkt.com/jean-luc-dompe/profil/spieler/291222.
Transfer history data appended for: https://www.transfermarkt.com/carlos-cuesta/profil/spieler/474589.
Transfer history data appended for: https://www.transfermarkt.com/daniel-munoz/profil/spieler/493003.
Transfer history data appended for: https://www.transfermarkt.com/joakim-maehle/profil/spieler/369674.
Transfer history data appended for: https://www.transfermarkt.com/cyriel-dessers/profil/spieler/317806.
Transfer history data appended for: https://www.transfermarkt.com/maarten-vandevoordt/profil/spieler/486046.
Transfer history data appended for: https://www.transfermarkt.com/rubin-seigers/profil/spieler/314980.
Transfer history data appended for: https://www.transfermarkt.com/kristian-thorstvedt/profil/spieler/564785.
Transfer history data appended for: https://www.transfermarkt.com/dries-wouters/profil/spieler/249570.
Transfer history data appended for: https://www.transfermarkt.com/gerardo-arteaga/profil/spieler/469718.
Transfer history data appended for: https://www.transfermarkt.com/elias-sierra/profil/spieler/409514.
Transfer history data appended for: https://www.transfermarkt.com/junya-ito/profil/spieler/348791.
Transfer history data appended for: https://www.transfermarkt.com/jhon-lucumi/profil/spieler/413565.
Transfer history data appended for: https://www.transfermarkt.com/paul-onuachu/profil/spieler/272855.
Transfer history data appended for: https://www.transfermarkt.com/jere-uronen/profil/spieler/131827.
Transfer history data appended for: https://www.transfermarkt.com/zinho-gano/profil/spieler/182446.
Transfer history data appended for: https://www.transfermarkt.com/bastien-toma/profil/spieler/390179.
Transfer history data appended for: https://www.transfermarkt.com/shawn-adewoye/profil/spieler/358021.
Transfer history data appended for: https://www.transfermarkt.com/luca-oyen/profil/spieler/551085.
Transfer history data appended for: https://www.transfermarkt.com/eboue-kouassi/profil/spieler/314137.
Transfer history data appended for: https://www.transfermarkt.com/sebastien-dewaest/profil/spieler/125754.
Transfer history data appended for: https://www.transfermarkt.com/patrik-hrosovsky/profil/spieler/217879.
Transfer history data appended for: https://www.transfermarkt.com/mats-moller-daehli/profil/spieler/190831.
Transfer history data appended for: https://www.transfermarkt.com/tobe-leysen/profil/spieler/580434.
Transfer history data appended for: https://www.transfermarkt.com/danny-vukovic/profil/spieler/43113.
Transfer history data appended for: https://www.transfermarkt.com/bryan-heynen/profil/spieler/356081.
Transfer history data appended for: https://www.transfermarkt.com/pierre-dwomoh/profil/spieler/652803.
Transfer history data appended for: https://www.transfermarkt.com/yannick-thoelen/profil/spieler/64246.
Transfer history data appended for: https://www.transfermarkt.com/maxime-wenssens/profil/spieler/570819.
Transfer history data appended for: https://www.transfermarkt.com/issa-kabore/profil/spieler/649452.
Transfer history data appended for: https://www.transfermarkt.com/thibault-peyre/profil/spieler/170914.
Transfer history data appended for: https://www.transfermarkt.com/maryan-shved/profil/spieler/359247.
Transfer history data appended for: https://www.transfermarkt.com/kerim-mrabti/profil/spieler/225569.
Transfer history data appended for: https://www.transfermarkt.com/victor-wernersson/profil/spieler/271816.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-coucke/profil/spieler/338651.
Transfer history data appended for: https://www.transfermarkt.com/lucas-bijker/profil/spieler/187283.
Transfer history data appended for: https://www.transfermarkt.com/sofiane-bouzian/profil/spieler/593378.
Transfer history data appended for: https://www.transfermarkt.com/william-togui/profil/spieler/362291.
Transfer history data appended for: https://www.transfermarkt.com/trova-boni/profil/spieler/557012.
Transfer history data appended for: https://www.transfermarkt.com/sheldon-bateau/profil/spieler/113378.
Transfer history data appended for: https://www.transfermarkt.com/gustav-engvall/profil/spieler/248024.
Transfer history data appended for: https://www.transfermarkt.com/joachim-van-damme/profil/spieler/74544.
Transfer history data appended for: https://www.transfermarkt.com/niklo-dailly/profil/spieler/695769.
Transfer history data appended for: https://www.transfermarkt.com/rob-schoofs/profil/spieler/157396.
Transfer history data appended for: https://www.transfermarkt.com/lars-coveliers/profil/spieler/429911.
Transfer history data appended for: https://www.transfermarkt.com/aster-vranckx/profil/spieler/503881.
Transfer history data appended for: https://www.transfermarkt.com/onur-kaya/profil/spieler/33709.
Transfer history data appended for: https://www.transfermarkt.com/sandy-walsh/profil/spieler/187329.
Transfer history data appended for: https://www.transfermarkt.com/jordi-vanlerberghe/profil/spieler/235275.
Transfer history data appended for: https://www.transfermarkt.com/siemen-voet/profil/spieler/460845.
Transfer history data appended for: https://www.transfermarkt.com/steven-defour/profil/spieler/33866.
Transfer history data appended for: https://www.transfermarkt.com/geoffry-hairemans/profil/spieler/110292.
Transfer history data appended for: https://www.transfermarkt.com/nikola-storm/profil/spieler/183120.

Transfer history data appended for: https://www.transfermarkt.com/rocky-bushiri/profil/spieler/511802.
Transfer history data appended for: https://www.transfermarkt.com/jordan-botaka/profil/spieler/196860.
Transfer history data appended for: https://www.transfermarkt.com/laurent-depoitre/profil/spieler/90583.
Transfer history data appended for: https://www.transfermarkt.com/anderson-niangbo/profil/spieler/294814.
Transfer history data appended for: https://www.transfermarkt.com/elisha-owusu/profil/spieler/395695.
Transfer history data appended for: https://www.transfermarkt.com/niklas-dorsch/profil/spieler/251302.
Transfer history data appended for: https://www.transfermarkt.com/osman-bukari/profil/spieler/548650.
Transfer history data appended for: https://www.transfermarkt.com/sven-kums/profil/spieler/42735.
Transfer history data appended for: https://www.transfermarkt.com/nurio-fortuna/profil/spieler/290261.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-de-bruyn/profil/spieler/224691.
Transfer history data appended for: https://www.transfermarkt.com/vadis-odjidja-ofoe/profil/spieler/38388.
Transfer history data appended for: https://www.transfermarkt.com/michael-ngadeu-ngadjui/profil/spieler/227239.
Transfer history data appended for: https://www.transfermarkt.com/dylan-mbayo/profil/spieler/502289.
Transfer history data appended for: https://www.transfermarkt.com/andreas-hanche-olsen/profil/spieler/370683.
Transfer history data appended for: https://www.transfermarkt.com/giorgi-chakvetadze/profil/spieler/412616.
Transfer history data appended for: https://www.transfermarkt.com/colin-coosemans/profil/spieler/154351.
Transfer history data appended for: https://www.transfermarkt.com/milad-mohammadi/profil/spieler/333355.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-cisse/profil/spieler/684340.
Transfer history data appended for: https://www.transfermarkt.com/sinan-bolat/profil/spieler/33862.
Transfer history data appended for: https://www.transfermarkt.com/roman-yaremchuk/profil/spieler/221958.
Transfer history data appended for: https://www.transfermarkt.com/igor-plastun/profil/spieler/97335.
Transfer history data appended for: https://www.transfermarkt.com/alessio-castro-montes/profil/spieler/340166.
Transfer history data appended for: https://www.transfermarkt.com/davy-roef/profil/spieler/140808.
Transfer history data appended for: https://www.transfermarkt.com/roman-bezus/profil/spieler/97567.
Transfer history data appended for: https://www.transfermarkt.com/bruno-godeau/profil/spieler/142924.
Transfer history data appended for: https://www.transfermarkt.com/matheo-parmentier/profil/spieler/737533.
Transfer history data appended for: https://www.transfermarkt.com/sulayman-marreh/profil/spieler/264046.
Transfer history data appended for: https://www.transfermarkt.com/dino-arslanagic/profil/spieler/110660.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-ippolito/profil/spieler/664128.
Transfer history data appended for: https://www.transfermarkt.com/matheo-vroman/profil/spieler/593939.
Transfer history data appended for: https://www.transfermarkt.com/beni-badibanga/profil/spieler/347625.
Transfer history data appended for: https://www.transfermarkt.com/imad-faraj/profil/spieler/371145.
Transfer history data appended for: https://www.transfermarkt.com/nick-gillekens/profil/spieler/283580.
Transfer history data appended for: https://www.transfermarkt.com/charles-andreas-brym/profil/spieler/595028.
Transfer history data appended for: https://www.transfermarkt.com/herve-koffi/profil/spieler/415383.
Transfer history data appended for: https://www.transfermarkt.com/vaso-vasic/profil/spieler/68030.
Transfer history data appended for: https://www.transfermarkt.com/babacar-dione/profil/spieler/509116.
Transfer history data appended for: https://www.transfermarkt.com/matias-silvestre/profil/spieler/20003.
Transfer history data appended for: https://www.transfermarkt.com/robbe-quirynen/profil/spieler/660319.
Transfer history data appended for: https://www.transfermarkt.com/marko-bakic/profil/spieler/188335.
Transfer history data appended for: https://www.transfermarkt.com/nuno-da-costa/profil/spieler/306166.
Transfer history data appended for: https://www.transfermarkt.com/el-hadji-gueye/profil/spieler/795055.
Transfer history data appended for: https://www.transfermarkt.com/enes-saglik/profil/spieler/120306.
Transfer history data appended for: https://www.transfermarkt.com/xadas/profil/spieler/345345.
Transfer history data appended for: https://www.transfermarkt.com/saad-agouzoul/profil/spieler/556865.
Transfer history data appended for: https://www.transfermarkt.com/darly-nlandu/profil/spieler/434226.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-mohamed/profil/spieler/190917.
Transfer history data appended for: https://www.transfermarkt.com/kouadio-yves-dabila/profil/spieler/503740.
Transfer history data appended for: https://www.transfermarkt.com/serge-tabekou/profil/spieler/370522.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-ciranni/profil/spieler/338680.
Transfer history data appended for: https://www.transfermarkt.com/virgiliu-postolachi/profil/spieler/536519.
Transfer history data appended for: https://www.transfermarkt.com/fabrice-olinga/profil/spieler/238291.
Transfer history data appended for: https://www.transfermarkt.com/capita/profil/spieler/666545.
Transfer history data appended for: https://www.transfermarkt.com/jean-onana/profil/spieler/656441.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-van-durmen/profil/spieler/434514.
Transfer history data appended for: https://www.transfermarkt.com/eric-junior-bocat/profil/spieler/740529.
Transfer history data appended for: https://www.transfermarkt.com/agim-zeka/profil/spieler/342824.
Transfer history data appended for: https://www.transfermarkt.com/harlem-gnohere/profil/spieler/70778.
Transfer history data appended for: https://www.transfermarkt.com/deni-ho%C4%8Dko/profil/spieler/227534.
Transfer history data appended for: https://www.transfermarkt.com/lillo-guarneri/profil/spieler/490387.
Transfer history data appended for: https://www.transfermarkt.com/antoine-lejoly/profil/spieler/289583.
Transfer history data appended for: https://www.transfermarkt.com/tarik-tissoudali/profil/spieler/245228.
Transfer history data appended for: https://www.transfermarkt.com/frederic-frans/profil/spieler/46715.
Transfer history data appended for: https://www.transfermarkt.com/gregory-grisez/profil/spieler/89628.
Transfer history data appended for: https://www.transfermarkt.com/blessing-eleke/profil/spieler/348229.
Transfer history data appended for: https://www.transfermarkt.com/musashi-suzuki/profil/spieler/188914.
Transfer history data appended for: https://www.transfermarkt.com/denis-prychynenko/profil/spieler/93862.
Transfer history data appended for: https://www.transfermarkt.com/loris-brogno/profil/spieler/182420.
Transfer history data appended for: https://www.transfermarkt.com/mike-vanhamel/profil/spieler/42178.
Transfer history data appended for: https://www.transfermarkt.com/keres-masangu/profil/spieler/393018.
Transfer history data appended for: https://www.transfermarkt.com/felipe-micael/profil/spieler/741100.
Transfer history data appended for: https://www.transfermarkt.com/dario-van-den-buijs/profil/spieler/235274.
Transfer history data appended for: https://www.transfermarkt.com/ismaila-coulibaly/profil/spieler/490224.
Transfer history data appended for: https://www.transfermarkt.com/tom-pietermaat/profil/spieler/110797.
Transfer history data appended for: https://www.transfermarkt.com/joren-dom/profil/spieler/80442.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-reda-halaimia/profil/spieler/387944.
Transfer history data appended for: https://www.transfermarkt.com/jan-van-den-bergh/profil/spieler/334495.
Transfer history data appended for: https://www.transfermarkt.com/ryan-sanusi/profil/spieler/202380.
Transfer history data appended for: https://www.transfermarkt.com/yan-vorogovskiy/profil/spieler/357608.

Transfer history data appended for: https://www.transfermarkt.com/wouter-biebauw/profil/spieler/19896.
Transfer history data appended for: https://www.transfermarkt.com/marius-noubissi/profil/spieler/357701.
Transfer history data appended for: https://www.transfermarkt.com/ayrton-mboko/profil/spieler/285998.
Transfer history data appended for: https://www.transfermarkt.com/pierre-bourdin/profil/spieler/164902.
Transfer history data appended for: https://www.transfermarkt.com/abdoulie-sanyang/profil/spieler/693906.
Transfer history data appended for: https://www.transfermarkt.com/matteo-di-giusto/profil/spieler/421823.
Transfer history data appended for: https://www.transfermarkt.com/cedric-gasser/profil/spieler/384104.
Transfer history data appended for: https://www.transfermarkt.com/gion-chande/profil/spieler/290013.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-buchel/profil/spieler/66708.
Transfer history data appended for: https://www.transfermarkt.com/boris-prokopic/profil/spieler/48076.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-goppel/profil/spieler/294704.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-luchinger/profil/spieler/159714.
Transfer history data appended for: https://www.transfermarkt.com/nico-hug/profil/spieler/274681.
Transfer history data appended for: https://www.transfermarkt.com/joel-schmied/profil/spieler/322517.
Transfer history data appended for: https://www.transfermarkt.com/yannick-schmid/profil/spieler/291896.
Transfer history data appended for: https://www.transfermarkt.com/pius-dorn/profil/spieler/192166.
Transfer history data appended for: https://www.transfermarkt.com/milan-gajic/profil/spieler/46928.
Transfer history data appended for: https://www.transfermarkt.com/dejan-djokic/profil/spieler/524710.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-coulibaly/profil/spieler/74607.
Transfer history data appended for: https://www.transfermarkt.com/tunahan-cicek/profil/spieler/154573.
Transfer history data appended for: https://www.transfermarkt.com/justin-ospelt/profil/spieler/405831.
Transfer history data appended for: https://www.transfermarkt.com/ferhat-saglam/profil/spieler/508069.
Transfer history data appended for: https://www.transfermarkt.com/yago-gomes-do-nascimento/profil/spieler/603773.
Transfer history data appended for: https://www.transfermarkt.com/sandro-wieser/profil/spieler/130227.
Transfer history data appended for: https://www.transfermarkt.com/gianni-antoniazzi/profil/spieler/322504.
Transfer history data appended for: https://www.transfermarkt.com/manuel-sutter/profil/spieler/59140.
Transfer history data appended for: https://www.transfermarkt.com/denis-simani/profil/spieler/135344.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-santin/profil/spieler/192082.
Transfer history data appended for: https://www.transfermarkt.com/fuad-rahimi/profil/spieler/410601.
Transfer history data appended for: https://www.transfermarkt.com/nicolae-milinceanu/profil/spieler/256669.
Transfer history data appended for: https://www.transfermarkt.com/linus-obexer/profil/spieler/254972.
Transfer history data appended for: https://www.transfermarkt.com/olivier-custodio/profil/spieler/183312.
Transfer history data appended for: https://www.transfermarkt.com/cendrim-kameraj/profil/spieler/390173.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-pietrogiovanna/profil/spieler/608004.
Transfer history data appended for: https://www.transfermarkt.com/numa-lavanchy/profil/spieler/147501.
Transfer history data appended for: https://www.transfermarkt.com/noam-baumann/profil/spieler/192605.
Transfer history data appended for: https://www.transfermarkt.com/miroslav-covilo/profil/spieler/60452.
Transfer history data appended for: https://www.transfermarkt.com/christopher-lungoyi/profil/spieler/346903.
Transfer history data appended for: https://www.transfermarkt.com/roman-macek/profil/spieler/256085.
Transfer history data appended for: https://www.transfermarkt.com/alexander-gerndt/profil/spieler/45881.
Transfer history data appended for: https://www.transfermarkt.com/mickael-facchinetti/profil/spieler/79392.
Transfer history data appended for: https://www.transfermarkt.com/ransford-selasi/profil/spieler/292333.
Transfer history data appended for: https://www.transfermarkt.com/mijat-maric/profil/spieler/6666.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-ardaiz/profil/spieler/415550.
Transfer history data appended for: https://www.transfermarkt.com/stefano-guidotti/profil/spieler/396405.
Transfer history data appended for: https://www.transfermarkt.com/noah-de-queiroz/profil/spieler/357860.
Transfer history data appended for: https://www.transfermarkt.com/adria-guerrero/profil/spieler/282724.
Transfer history data appended for: https://www.transfermarkt.com/fabio-daprela/profil/spieler/66109.
Transfer history data appended for: https://www.transfermarkt.com/david-jovanovic/profil/spieler/510893.
Transfer history data appended for: https://www.transfermarkt.com/kevin-monzialo/profil/spieler/591199.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-sabbatini/profil/spieler/102409.
Transfer history data appended for: https://www.transfermarkt.com/mattia-bottani/profil/spieler/86484.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-osigwe/profil/spieler/199453.
Transfer history data appended for: https://www.transfermarkt.com/akos-kecskes/profil/spieler/204155.
Transfer history data appended for: https://www.transfermarkt.com/florjan-seferaj/profil/spieler/529316.
Transfer history data appended for: https://www.transfermarkt.com/lucio-soldini/profil/spieler/507450.
Transfer history data appended for: https://www.transfermarkt.com/josias-lukembila/profil/spieler/449590.
Transfer history data appended for: https://www.transfermarkt.com/moritz-jenz/profil/spieler/460245.
Transfer history data appended for: https://www.transfermarkt.com/christian-schneuwly/profil/spieler/52556.
Transfer history data appended for: https://www.transfermarkt.com/cameron-puertas/profil/spieler/449592.
Transfer history data appended for: https://www.transfermarkt.com/mory-diaw/profil/spieler/164904.
Transfer history data appended for: https://www.transfermarkt.com/aldin-turkes/profil/spieler/192655.
Transfer history data appended for: https://www.transfermarkt.com/pedro-brazao/profil/spieler/577590.
Transfer history data appended for: https://www.transfermarkt.com/theo-rochat/profil/spieler/525923.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-getaz/profil/spieler/129642.
Transfer history data appended for: https://www.transfermarkt.com/stjepan-kukuruzovic/profil/spieler/68655.
Transfer history data appended for: https://www.transfermarkt.com/mickael-nanizayamo/profil/spieler/463744.
Transfer history data appended for: https://www.transfermarkt.com/marc-tsoungui/profil/spieler/357858.
Transfer history data appended for: https://www.transfermarkt.com/armel-zohouri/profil/spieler/819419.
Transfer history data appended for: https://www.transfermarkt.com/noah-loosli/profil/spieler/265209.
Transfer history data appended for: https://www.transfermarkt.com/thomas-castella/profil/spieler/165435.
Transfer history data appended for: https://www.transfermarkt.com/simone-rapp/profil/spieler/154635.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-bares/profil/spieler/484743.
Transfer history data appended for: https://www.transfermarkt.com/evann-guessand/profil/spieler/500689.
Transfer history data appended for: https://www.transfermarkt.com/trazie-thomas/profil/spieler/819420.
Transfer history data appended for: https://www.transfermarkt.com/isaac-schmidt/profil/spieler/449597.
Transfer history data appended for: https://www.transfermarkt.com/anthony-koura/profil/spieler/127098.
Transfer history data appended for: https://www.transfermarkt.com/alvyn-sanches/profil/spieler/583058.
Transfer history data appended for: https://www.transfermarkt.com/elton-monteiro/profil/spieler/122722.

Transfer history data appended for: https://www.transfermarkt.com/noah-falk/profil/spieler/365096.
Transfer history data appended for: https://www.transfermarkt.com/nikola-boranijasevic/profil/spieler/180090.
Transfer history data appended for: https://www.transfermarkt.com/per-egil-flo/profil/spieler/41869.
Transfer history data appended for: https://www.transfermarkt.com/joel-geissmann/profil/spieler/167188.
Transfer history data appended for: https://www.transfermarkt.com/lucas-da-cunha/profil/spieler/495667.
Transfer history data appended for: https://www.transfermarkt.com/tsiy-william-ndenge/profil/spieler/253574.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-ndiaye/profil/spieler/457031.
Transfer history data appended for: https://www.transfermarkt.com/nenad-zivkovic/profil/spieler/507419.
Transfer history data appended for: https://www.transfermarkt.com/lucas/profil/spieler/190314.
Transfer history data appended for: https://www.transfermarkt.com/ashvin-balaruban/profil/spieler/507454.
Transfer history data appended for: https://www.transfermarkt.com/silvan-sidler/profil/spieler/342063.
Transfer history data appended for: https://www.transfermarkt.com/marvin-schulz/profil/spieler/168678.
Transfer history data appended for: https://www.transfermarkt.com/samuel-alabi/profil/spieler/582019.
Transfer history data appended for: https://www.transfermarkt.com/varol-tasar/profil/spieler/310361.
Transfer history data appended for: https://www.transfermarkt.com/marco-burch/profil/spieler/479268.
Transfer history data appended for: https://www.transfermarkt.com/alex-carbonell/profil/spieler/262389.
Transfer history data appended for: https://www.transfermarkt.com/christian-schwegler/profil/spieler/4931.
Transfer history data appended for: https://www.transfermarkt.com/david-zibung/profil/spieler/4914.
Transfer history data appended for: https://www.transfermarkt.com/marco-burki/profil/spieler/172192.
Transfer history data appended for: https://www.transfermarkt.com/tyron-owusu/profil/spieler/583055.
Transfer history data appended for: https://www.transfermarkt.com/stefan-knezevic/profil/spieler/293247.
Transfer history data appended for: https://www.transfermarkt.com/martin-frydek/profil/spieler/146710.
Transfer history data appended for: https://www.transfermarkt.com/yvan-alounga/profil/spieler/534493.
Transfer history data appended for: https://www.transfermarkt.com/lorik-emini/profil/spieler/410871.
Transfer history data appended for: https://www.transfermarkt.com/mark-marleku/profil/spieler/310066.
Transfer history data appended for: https://www.transfermarkt.com/simon-grether/profil/spieler/159299.
Transfer history data appended for: https://www.transfermarkt.com/dejan-sorgic/profil/spieler/65442.
Transfer history data appended for: https://www.transfermarkt.com/marius-muller/profil/spieler/118161.
Transfer history data appended for: https://www.transfermarkt.com/lino-lang/profil/spieler/445326.
Transfer history data appended for: https://www.transfermarkt.com/filip-ugrinic/profil/spieler/394236.
Transfer history data appended for: https://www.transfermarkt.com/louis-schaub/profil/spieler/147485.
Transfer history data appended for: https://www.transfermarkt.com/salah-aziz-binous/profil/spieler/511143.
Transfer history data appended for: https://www.transfermarkt.com/julian-hermann/profil/spieler/310113.
Transfer history data appended for: https://www.transfermarkt.com/ricky-van-wolfswinkel/profil/spieler/41355.
Transfer history data appended for: https://www.transfermarkt.com/timm-klose/profil/spieler/65255.
Transfer history data appended for: https://www.transfermarkt.com/albian-hajdari/profil/spieler/579459.
Transfer history data appended for: https://www.transfermarkt.com/pajtim-kasami/profil/spieler/130108.
Transfer history data appended for: https://www.transfermarkt.com/edon-zhegrova/profil/spieler/496857.
Transfer history data appended for: https://www.transfermarkt.com/felix-gebhardt/profil/spieler/499317.
Transfer history data appended for: https://www.transfermarkt.com/raoul-petretta/profil/spieler/243878.
Transfer history data appended for: https://www.transfermarkt.com/eray-comert/profil/spieler/298583.
Transfer history data appended for: https://www.transfermarkt.com/luca-zuffi/profil/spieler/59246.
Transfer history data appended for: https://www.transfermarkt.com/orges-bunjaku/profil/spieler/499214.
Transfer history data appended for: https://www.transfermarkt.com/jozef-pukaj/profil/spieler/421809.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-dimitriou/profil/spieler/348522.
Transfer history data appended for: https://www.transfermarkt.com/arthur-cabral/profil/spieler/390638.
Transfer history data appended for: https://www.transfermarkt.com/valentin-stocker/profil/spieler/45178.
Transfer history data appended for: https://www.transfermarkt.com/aldo-kalulu/profil/spieler/292822.
Transfer history data appended for: https://www.transfermarkt.com/silvan-widmer/profil/spieler/168989.
Transfer history data appended for: https://www.transfermarkt.com/jasper-van-der-werff/profil/spieler/322519.
Transfer history data appended for: https://www.transfermarkt.com/afimico-pululu/profil/spieler/410649.
Transfer history data appended for: https://www.transfermarkt.com/lirik-vishi/profil/spieler/499213.
Transfer history data appended for: https://www.transfermarkt.com/taulant-xhaka/profil/spieler/113125.
Transfer history data appended for: https://www.transfermarkt.com/samuele-campo/profil/spieler/183446.
Transfer history data appended for: https://www.transfermarkt.com/yannick-marchand/profil/spieler/346882.
Transfer history data appended for: https://www.transfermarkt.com/julian-von-moos/profil/spieler/500762.
Transfer history data appended for: https://www.transfermarkt.com/jorge/profil/spieler/345084.
Transfer history data appended for: https://www.transfermarkt.com/djordje-nikolic/profil/spieler/274344.
Transfer history data appended for: https://www.transfermarkt.com/heinz-lindner/profil/spieler/59082.
Transfer history data appended for: https://www.transfermarkt.com/tician-tushi/profil/spieler/507499.
Transfer history data appended for: https://www.transfermarkt.com/andrea-padula/profil/spieler/334665.
Transfer history data appended for: https://www.transfermarkt.com/mihailo-stevanovic/profil/spieler/499330.
Transfer history data appended for: https://www.transfermarkt.com/elis-isufi/profil/spieler/346889.
Transfer history data appended for: https://www.transfermarkt.com/fabian-frei/profil/spieler/52595.
Transfer history data appended for: https://www.transfermarkt.com/antonio-marchesano/profil/spieler/150963.
Transfer history data appended for: https://www.transfermarkt.com/blaz-kramer/profil/spieler/322288.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-kololli/profil/spieler/191486.
Transfer history data appended for: https://www.transfermarkt.com/salim-khelifi/profil/spieler/147049.
Transfer history data appended for: https://www.transfermarkt.com/kedus-haile-selassie/profil/spieler/357871.
Transfer history data appended for: https://www.transfermarkt.com/nathan/profil/spieler/339711.
Transfer history data appended for: https://www.transfermarkt.com/vasilije-janjicic/profil/spieler/265254.
Transfer history data appended for: https://www.transfermarkt.com/nils-reichmuth/profil/spieler/507412.
Transfer history data appended for: https://www.transfermarkt.com/hekuran-kryeziu/profil/spieler/168979.
Transfer history data appended for: https://www.transfermarkt.com/mirlind-kryeziu/profil/spieler/265208.
Transfer history data appended for: https://www.transfermarkt.com/assan-ceesay/profil/spieler/388382.
Transfer history data appended for: https://www.transfermarkt.com/willie-britto/profil/spieler/364307.
Transfer history data appended for: https://www.transfermarkt.com/zivko-kostadinovic/profil/spieler/178277.
Transfer history data appended for: https://www.transfermarkt.com/fabian-rohner/profil/spieler/451483.
Transfer history data appended for: https://www.transfermarkt.com/novem-baumann/profil/spieler/183308.
Transfer history data appended for: https://www.transfermarkt.com/silvan-wallner/profil/spieler/602443.

Transfer history data appended for: https://www.transfermarkt.com/wilfried-gnonto/profil/spieler/627626.
Transfer history data appended for: https://www.transfermarkt.com/umaru-bangura/profil/spieler/38304.
Transfer history data appended for: https://www.transfermarkt.com/filip-frei/profil/spieler/507468.
Transfer history data appended for: https://www.transfermarkt.com/aiyegun-tosin/profil/spieler/239647.
Transfer history data appended for: https://www.transfermarkt.com/ousmane-doumbia/profil/spieler/286292.
Transfer history data appended for: https://www.transfermarkt.com/tobias-schattin/profil/spieler/237679.
Transfer history data appended for: https://www.transfermarkt.com/becir-omeragic/profil/spieler/507344.
Transfer history data appended for: https://www.transfermarkt.com/henri-koide/profil/spieler/507495.
Transfer history data appended for: https://www.transfermarkt.com/marco-schonbachler/profil/spieler/47528.
Transfer history data appended for: https://www.transfermarkt.com/adrian-winter/profil/spieler/59681.
Transfer history data appended for: https://www.transfermarkt.com/yanick-brecher/profil/spieler/165532.
Transfer history data appended for: https://www.transfermarkt.com/stephan-seiler/profil/spieler/421819.
Transfer history data appended for: https://www.transfermarkt.com/toni-domgjoni/profil/spieler/344649.
Transfer history data appended for: https://www.transfermarkt.com/fabio-solimando/profil/spieler/507463.
Transfer history data appended for: https://www.transfermarkt.com/tim-staubli/profil/spieler/346894.
Transfer history data appended for: https://www.transfermarkt.com/adonis-ajeti/profil/spieler/223380.
Transfer history data appended for: https://www.transfermarkt.com/betim-fazliji/profil/spieler/410636.
Transfer history data appended for: https://www.transfermarkt.com/jordi-quintilla/profil/spieler/166679.
Transfer history data appended for: https://www.transfermarkt.com/victor-ruiz/profil/spieler/336857.
Transfer history data appended for: https://www.transfermarkt.com/angelo-campos/profil/spieler/421821.
Transfer history data appended for: https://www.transfermarkt.com/armin-abaz/profil/spieler/357862.
Transfer history data appended for: https://www.transfermarkt.com/basil-stillhart/profil/spieler/269526.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-luchinger/profil/spieler/183260.
Transfer history data appended for: https://www.transfermarkt.com/nico-strubi/profil/spieler/346896.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-gonzalez/profil/spieler/346901.
Transfer history data appended for: https://www.transfermarkt.com/yannis-letard/profil/spieler/590280.
Transfer history data appended for: https://www.transfermarkt.com/vincent-rufli/profil/spieler/23874.
Transfer history data appended for: https://www.transfermarkt.com/lukas-watkowiak/profil/spieler/196791.
Transfer history data appended for: https://www.transfermarkt.com/lawrence-ati-zigi/profil/spieler/254285.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-krauchi/profil/spieler/289892.
Transfer history data appended for: https://www.transfermarkt.com/fabiano-alves/profil/spieler/347398.
Transfer history data appended for: https://www.transfermarkt.com/florian-kamberi/profil/spieler/284020.
Transfer history data appended for: https://www.transfermarkt.com/leonidas-stergiou/profil/spieler/507345.
Transfer history data appended for: https://www.transfermarkt.com/boris-babic/profil/spieler/237660.
Transfer history data appended for: https://www.transfermarkt.com/lukas-gortler/profil/spieler/179638.
Transfer history data appended for: https://www.transfermarkt.com/miro-muheim/profil/spieler/298603.
Transfer history data appended for: https://www.transfermarkt.com/kwadwo-duah/profil/spieler/254955.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-guillemenot/profil/spieler/290016.
Transfer history data appended for: https://www.transfermarkt.com/salifou-diarrassouba/profil/spieler/649459.
Transfer history data appended for: https://www.transfermarkt.com/thody-elie-youan/profil/spieler/465715.
Transfer history data appended for: https://www.transfermarkt.com/boubacar-traore/profil/spieler/410083.
Transfer history data appended for: https://www.transfermarkt.com/andre-ribeiro/profil/spieler/342482.
Transfer history data appended for: https://www.transfermarkt.com/musah-nuhu/profil/spieler/477681.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-gaudino/profil/spieler/195051.
Transfer history data appended for: https://www.transfermarkt.com/jean-pierre-nsame/profil/spieler/225055.
Transfer history data appended for: https://www.transfermarkt.com/cedric-zesiger/profil/spieler/382478.
Transfer history data appended for: https://www.transfermarkt.com/jordan-lefort/profil/spieler/192492.
Transfer history data appended for: https://www.transfermarkt.com/christopher-martins-pereira/profil/spieler/248054.
Transfer history data appended for: https://www.transfermarkt.com/sandro-lauper/profil/spieler/254965.
Transfer history data appended for: https://www.transfermarkt.com/meschack-elia/profil/spieler/423678.
Transfer history data appended for: https://www.transfermarkt.com/taulant-seferi/profil/spieler/254985.
Transfer history data appended for: https://www.transfermarkt.com/fabian-lustenberger/profil/spieler/42203.
Transfer history data appended for: https://www.transfermarkt.com/felix-mambimbi/profil/spieler/507496.
Transfer history data appended for: https://www.transfermarkt.com/christian-fassnacht/profil/spieler/250490.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-moumi-ngamaleu/profil/spieler/266768.
Transfer history data appended for: https://www.transfermarkt.com/joschua-neuenschwander/profil/spieler/346905.
Transfer history data appended for: https://www.transfermarkt.com/fabian-rieder/profil/spieler/507341.
Transfer history data appended for: https://www.transfermarkt.com/david-von-ballmoos/profil/spieler/203124.
Transfer history data appended for: https://www.transfermarkt.com/nico-maier/profil/spieler/346904.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-camara/profil/spieler/426723.
Transfer history data appended for: https://www.transfermarkt.com/ulisses-garcia/profil/spieler/192616.
Transfer history data appended for: https://www.transfermarkt.com/leo-seydoux/profil/spieler/313097.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-burgy/profil/spieler/203895.
Transfer history data appended for: https://www.transfermarkt.com/jordan-siebatcheu/profil/spieler/355369.
Transfer history data appended for: https://www.transfermarkt.com/silvan-hefti/profil/spieler/237666.
Transfer history data appended for: https://www.transfermarkt.com/quentin-maceiras/profil/spieler/274498.
Transfer history data appended for: https://www.transfermarkt.com/michel-aebischer/profil/spieler/237658.
Transfer history data appended for: https://www.transfermarkt.com/marvin-spielmann/profil/spieler/192653.
Transfer history data appended for: https://www.transfermarkt.com/miralem-sulejmani/profil/spieler/36080.
Transfer history data appended for: https://www.transfermarkt.com/esteban-petignat/profil/spieler/479480.
Transfer history data appended for: https://www.transfermarkt.com/guillaume-faivre/profil/spieler/32750.
Transfer history data appended for: https://www.transfermarkt.com/anto-grgic/profil/spieler/192637.
Transfer history data appended for: https://www.transfermarkt.com/ayoub-abdellaoui/profil/spieler/262208.
Transfer history data appended for: https://www.transfermarkt.com/nathanael-saintini/profil/spieler/585950.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-cavare/profil/spieler/278553.
Transfer history data appended for: https://www.transfermarkt.com/matteo-tosetti/profil/spieler/111453.
Transfer history data appended for: https://www.transfermarkt.com/aimery-pinga/profil/spieler/347097.
Transfer history data appended for: https://www.transfermarkt.com/baltazar/profil/spieler/585346.
Transfer history data appended for: https://www.transfermarkt.com/jan-bamert/profil/spieler/289875.

Transfer history data appended for: https://www.transfermarkt.com/christian-zock/profil/spieler/337017.
Transfer history data appended for: https://www.transfermarkt.com/musa-araz/profil/spieler/147037.
Transfer history data appended for: https://www.transfermarkt.com/mauro-rodrigues/profil/spieler/514623.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-nsakala/profil/spieler/418656.
Transfer history data appended for: https://www.transfermarkt.com/geoffroy-serey-die/profil/spieler/77708.
Transfer history data appended for: https://www.transfermarkt.com/andre-edgar/profil/spieler/525924.
Transfer history data appended for: https://www.transfermarkt.com/luca-clemenza/profil/spieler/291520.
Transfer history data appended for: https://www.transfermarkt.com/jean-ruiz/profil/spieler/345067.
Transfer history data appended for: https://www.transfermarkt.com/patrick-luan/profil/spieler/518676.
Transfer history data appended for: https://www.transfermarkt.com/mattias-andersson/profil/spieler/342407.
Transfer history data appended for: https://www.transfermarkt.com/roberts-uldrikis/profil/spieler/342152.
Transfer history data appended for: https://www.transfermarkt.com/guillaume-hoarau/profil/spieler/23934.
Transfer history data appended for: https://www.transfermarkt.com/timothy-fayulu/profil/spieler/541420.
Transfer history data appended for: https://www.transfermarkt.com/dennis-iapichino/profil/spieler/123711.
Transfer history data appended for: https://www.transfermarkt.com/jared-khasa/profil/spieler/425460.
Transfer history data appended for: https://www.transfermarkt.com/ivan-martic/profil/spieler/73048.
Transfer history data appended for: https://www.transfermarkt.com/nathan-senerine/profil/spieler/488171.
Transfer history data appended for: https://www.transfermarkt.com/yamato-wakatsuki/profil/spieler/657624.
Transfer history data appended for: https://www.transfermarkt.com/nikita-vlasenko/profil/spieler/510898.
Transfer history data appended for: https://www.transfermarkt.com/damien-buchard/profil/spieler/346887.
Transfer history data appended for: https://www.transfermarkt.com/itaitinga/profil/spieler/610123.
Transfer history data appended for: https://www.transfermarkt.com/artan-asani/profil/spieler/355772.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-karlen/profil/spieler/166400.
Transfer history data appended for: https://www.transfermarkt.com/raphael-rossi/profil/spieler/290271.
Transfer history data appended for: https://www.transfermarkt.com/sandro-theler/profil/spieler/421820.
Transfer history data appended for: https://www.transfermarkt.com/siyar-doldur/profil/spieler/346888.
Transfer history data appended for: https://www.transfermarkt.com/arian-kabashi/profil/spieler/335548.
Transfer history data appended for: https://www.transfermarkt.com/birama-ndoye/profil/spieler/237903.
Transfer history data appended for: https://www.transfermarkt.com/nasser-daoudou-msa/profil/spieler/531356.
Transfer history data appended for: https://www.transfermarkt.com/yassin-fortune/profil/spieler/342878.
Transfer history data appended for: https://www.transfermarkt.com/kevin-fickentscher/profil/spieler/33651.
Transfer history data appended for: https://www.transfermarkt.com/steve-rouiller/profil/spieler/88404.
Transfer history data appended for: https://www.transfermarkt.com/gael-ondoua/profil/spieler/322309.
Transfer history data appended for: https://www.transfermarkt.com/mathis-holcbecher/profil/spieler/507469.
Transfer history data appended for: https://www.transfermarkt.com/theo-valls/profil/spieler/341396.
Transfer history data appended for: https://www.transfermarkt.com/noah-henchoz/profil/spieler/507340.
Transfer history data appended for: https://www.transfermarkt.com/alexis-guerin/profil/spieler/695055.
Transfer history data appended for: https://www.transfermarkt.com/matteo-regillo/profil/spieler/509829.
Transfer history data appended for: https://www.transfermarkt.com/alexis-martial/profil/spieler/613767.
Transfer history data appended for: https://www.transfermarkt.com/boubacar-fofana/profil/spieler/563098.
Transfer history data appended for: https://www.transfermarkt.com/kastriot-imeri/profil/spieler/469957.
Transfer history data appended for: https://www.transfermarkt.com/alban-ajdini/profil/spieler/511801.
Transfer history data appended for: https://www.transfermarkt.com/gael-clichy/profil/spieler/7449.
Transfer history data appended for: https://www.transfermarkt.com/koro-kone/profil/spieler/61005.
Transfer history data appended for: https://www.transfermarkt.com/yoan-severin/profil/spieler/340065.
Transfer history data appended for: https://www.transfermarkt.com/alex-schalk/profil/spieler/186228.
Transfer history data appended for: https://www.transfermarkt.com/anthony-sauthier/profil/spieler/69899.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-vouilloz/profil/spieler/507488.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-azevedo/profil/spieler/507466.
Transfer history data appended for: https://www.transfermarkt.com/miroslav-stevanovic/profil/spieler/75816.
Transfer history data appended for: https://www.transfermarkt.com/joel-kiassumbua/profil/spieler/111423.
Transfer history data appended for: https://www.transfermarkt.com/timothe-cognat/profil/spieler/324796.
Transfer history data appended for: https://www.transfermarkt.com/boris-cespedes/profil/spieler/183311.
Transfer history data appended for: https://www.transfermarkt.com/moussa-diallo/profil/spieler/450390.
Transfer history data appended for: https://www.transfermarkt.com/alexis-antunes/profil/spieler/346898.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-frick/profil/spieler/170344.
Transfer history data appended for: https://www.transfermarkt.com/edin-omeragic/profil/spieler/507391.
Transfer history data appended for: https://www.transfermarkt.com/grejohn-kyei/profil/spieler/321647.
Transfer history data appended for: https://www.transfermarkt.com/theophilious-opoku-mensah/profil/spieler/507411.
Transfer history data appended for: https://www.transfermarkt.com/arial-mendy/profil/spieler/422715.
Transfer history data appended for: https://www.transfermarkt.com/diego-stuardo/profil/spieler/559158.
Transfer history data appended for: https://www.transfermarkt.com/juan-abarca/profil/spieler/89777.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-abarzua/profil/spieler/537683.
Transfer history data appended for: https://www.transfermarkt.com/juan-patino/profil/spieler/838259.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-cordoba/profil/spieler/660736.
Transfer history data appended for: https://www.transfermarkt.com/eric-godoy/profil/spieler/136899.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-quinteros/profil/spieler/110163.
Transfer history data appended for: https://www.transfermarkt.com/mario-oporto/profil/spieler/841339.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-correa/profil/spieler/74361.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-alles/profil/spieler/102415.
Transfer history data appended for: https://www.transfermarkt.com/matias-cabrera/profil/spieler/76598.
Transfer history data appended for: https://www.transfermarkt.com/antonio-ramirez/profil/spieler/461606.
Transfer history data appended for: https://www.transfermarkt.com/cecilio-waterman/profil/spieler/177064.
Transfer history data appended for: https://www.transfermarkt.com/claudio-navarrete/profil/spieler/587459.
Transfer history data appended for: https://www.transfermarkt.com/leandro-diaz/profil/spieler/658849.
Transfer history data appended for: https://www.transfermarkt.com/bryan-carvallo/profil/spieler/319463.
Transfer history data appended for: https://www.transfermarkt.com/andres-robles/profil/spieler/168987.
Transfer history data appended for: https://www.transfermarkt.com/jaime-carreno/profil/spieler/393372.
Transfer history data appended for: https://www.transfermarkt.com/fabian-neira/profil/spieler/740259.
Transfer history data appended for: https://www.transfermarkt.com/simon-ramirez/profil/spieler/401712.

Transfer history data appended for: https://www.transfermarkt.com/hardy-cavero/profil/spieler/319464.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-reyes/profil/spieler/76836.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-povea/profil/spieler/239200.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-camargo/profil/spieler/105890.
Transfer history data appended for: https://www.transfermarkt.com/richard-leyton/profil/spieler/53012.
Transfer history data appended for: https://www.transfermarkt.com/martin-lara/profil/spieler/491644.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-ubilla/profil/spieler/136903.
Transfer history data appended for: https://www.transfermarkt.com/willian-gama/profil/spieler/491651.
Transfer history data appended for: https://www.transfermarkt.com/jason-leon/profil/spieler/740263.
Transfer history data appended for: https://www.transfermarkt.com/bernardo-cerezo/profil/spieler/251047.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-viana/profil/spieler/136904.
Transfer history data appended for: https://www.transfermarkt.com/daniel-gonzalez/profil/spieler/662737.
Transfer history data appended for: https://www.transfermarkt.com/alexis-valencia/profil/spieler/491652.
Transfer history data appended for: https://www.transfermarkt.com/diego-plaza/profil/spieler/699318.
Transfer history data appended for: https://www.transfermarkt.com/victor-espinoza/profil/spieler/699313.
Transfer history data appended for: https://www.transfermarkt.com/enzo-gutierrez/profil/spieler/90506.
Transfer history data appended for: https://www.transfermarkt.com/nestor-canelon/profil/spieler/308720.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-rojas/profil/spieler/628971.
Transfer history data appended for: https://www.transfermarkt.com/matias-fernandez/profil/spieler/402519.
Transfer history data appended for: https://www.transfermarkt.com/luis-garcia/profil/spieler/388689.
Transfer history data appended for: https://www.transfermarkt.com/aldrix-jara/profil/spieler/841844.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-lanaro/profil/spieler/329503.
Transfer history data appended for: https://www.transfermarkt.com/esli-garcia/profil/spieler/486175.
Transfer history data appended for: https://www.transfermarkt.com/ronnie-fernandez/profil/spieler/140518.
Transfer history data appended for: https://www.transfermarkt.com/juan-soto/profil/spieler/373928.
Transfer history data appended for: https://www.transfermarkt.com/victor-retamal/profil/spieler/567415.
Transfer history data appended for: https://www.transfermarkt.com/marco-medel/profil/spieler/73423.
Transfer history data appended for: https://www.transfermarkt.com/angelo-quinones/profil/spieler/457850.
Transfer history data appended for: https://www.transfermarkt.com/matias-plaza/profil/spieler/699316.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-mino/profil/spieler/172101.
Transfer history data appended for: https://www.transfermarkt.com/matias-marin/profil/spieler/628976.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-luna/profil/spieler/77371.
Transfer history data appended for: https://www.transfermarkt.com/cristian-vega/profil/spieler/840957.
Transfer history data appended for: https://www.transfermarkt.com/francisco-alarcon/profil/spieler/160899.
Transfer history data appended for: https://www.transfermarkt.com/axel-herrera/profil/spieler/699317.
Transfer history data appended for: https://www.transfermarkt.com/esteban-carvajal/profil/spieler/138815.
Transfer history data appended for: https://www.transfermarkt.com/diego-oyarzun/profil/spieler/668150.
Transfer history data appended for: https://www.transfermarkt.com/jorge-araya/profil/spieler/323775.
Transfer history data appended for: https://www.transfermarkt.com/lucas-acevedo/profil/spieler/284306.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-benitez/profil/spieler/309796.
Transfer history data appended for: https://www.transfermarkt.com/felipe-chamorro/profil/spieler/837082.
Transfer history data appended for: https://www.transfermarkt.com/carlos-villanueva/profil/spieler/53164.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-rojas/profil/spieler/744278.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-cabrera/profil/spieler/534293.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-silva/profil/spieler/377287.
Transfer history data appended for: https://www.transfermarkt.com/cristian-guerra/profil/spieler/365304.
Transfer history data appended for: https://www.transfermarkt.com/federico-anselmo/profil/spieler/343163.
Transfer history data appended for: https://www.transfermarkt.com/cesar-cortes/profil/spieler/51629.
Transfer history data appended for: https://www.transfermarkt.com/henry-sanhueza/profil/spieler/417956.
Transfer history data appended for: https://www.transfermarkt.com/vicente-fernandez/profil/spieler/534263.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-meza/profil/spieler/837133.
Transfer history data appended for: https://www.transfermarkt.com/enzo-guerrero/profil/spieler/172389.
Transfer history data appended for: https://www.transfermarkt.com/matias-campos-lopez/profil/spieler/119515.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-fuentes/profil/spieler/744277.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-solabarrieta/profil/spieler/671953.
Transfer history data appended for: https://www.transfermarkt.com/leandro-benegas/profil/spieler/125899.
Transfer history data appended for: https://www.transfermarkt.com/agustin-farias/profil/spieler/267894.
Transfer history data appended for: https://www.transfermarkt.com/renato-tarifeno/profil/spieler/460877.
Transfer history data appended for: https://www.transfermarkt.com/daniel-vicencio/profil/spieler/200884.
Transfer history data appended for: https://www.transfermarkt.com/fabian-ahumada/profil/spieler/371823.
Transfer history data appended for: https://www.transfermarkt.com/federico-lanzillotta/profil/spieler/267906.
Transfer history data appended for: https://www.transfermarkt.com/bryan-carrasco/profil/spieler/128474.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-soto/profil/spieler/534909.
Transfer history data appended for: https://www.transfermarkt.com/diego-valencia/profil/spieler/491648.
Transfer history data appended for: https://www.transfermarkt.com/marcelino-nunez/profil/spieler/715558.
Transfer history data appended for: https://www.transfermarkt.com/edson-puch/profil/spieler/113217.
Transfer history data appended for: https://www.transfermarkt.com/cristobal-finch/profil/spieler/737925.
Transfer history data appended for: https://www.transfermarkt.com/juan-fuentes/profil/spieler/319468.
Transfer history data appended for: https://www.transfermarkt.com/raimundo-rebolledo/profil/spieler/376781.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-suarez/profil/spieler/573832.
Transfer history data appended for: https://www.transfermarkt.com/luciano-aued/profil/spieler/55856.
Transfer history data appended for: https://www.transfermarkt.com/ian-toro/profil/spieler/819276.
Transfer history data appended for: https://www.transfermarkt.com/diego-buonanotte/profil/spieler/45646.
Transfer history data appended for: https://www.transfermarkt.com/carlos-salomon/profil/spieler/172561.
Transfer history data appended for: https://www.transfermarkt.com/juan-cornejo/profil/spieler/59100.
Transfer history data appended for: https://www.transfermarkt.com/alfonso-parot/profil/spieler/84238.
Transfer history data appended for: https://www.transfermarkt.com/cristopher-toselli/profil/spieler/72903.
Transfer history data appended for: https://www.transfermarkt.com/valber-huerta/profil/spieler/226306.
Transfer history data appended for: https://www.transfermarkt.com/cesar-munder/profil/spieler/578074.

Transfer history data appended for: https://www.transfermarkt.com/gaston-lezcano/profil/spieler/195740.
Transfer history data appended for: https://www.transfermarkt.com/jose-pedro-fuenzalida/profil/spieler/72602.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-saavedra/profil/spieler/401706.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-tapia/profil/spieler/662739.
Transfer history data appended for: https://www.transfermarkt.com/alexander-aravena/profil/spieler/662742.
Transfer history data appended for: https://www.transfermarkt.com/vicente-bernedo/profil/spieler/737926.
Transfer history data appended for: https://www.transfermarkt.com/tomas-asta-buruaga/profil/spieler/404118.
Transfer history data appended for: https://www.transfermarkt.com/francisco-silva/profil/spieler/84870.
Transfer history data appended for: https://www.transfermarkt.com/german-lanaro/profil/spieler/63585.
Transfer history data appended for: https://www.transfermarkt.com/renato-araya/profil/spieler/836081.
Transfer history data appended for: https://www.transfermarkt.com/brian-torrealba/profil/spieler/352340.
Transfer history data appended for: https://www.transfermarkt.com/luis-kovacic/profil/spieler/740257.
Transfer history data appended for: https://www.transfermarkt.com/moises-gonzalez/profil/spieler/695979.
Transfer history data appended for: https://www.transfermarkt.com/cristian-pizarro/profil/spieler/749447.
Transfer history data appended for: https://www.transfermarkt.com/tomas-alarcon/profil/spieler/454238.
Transfer history data appended for: https://www.transfermarkt.com/roberto-cereceda/profil/spieler/63391.
Transfer history data appended for: https://www.transfermarkt.com/matias-sepulveda/profil/spieler/511436.
Transfer history data appended for: https://www.transfermarkt.com/gaston-zuniga/profil/spieler/491635.
Transfer history data appended for: https://www.transfermarkt.com/facundo-castro/profil/spieler/318843.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-gotti/profil/spieler/267595.
Transfer history data appended for: https://www.transfermarkt.com/hugo-herrera/profil/spieler/539468.
Transfer history data appended for: https://www.transfermarkt.com/patricio-romero/profil/spieler/840429.
Transfer history data appended for: https://www.transfermarkt.com/roberto-gutierrez/profil/spieler/64783.
Transfer history data appended for: https://www.transfermarkt.com/francisco-arancibia/profil/spieler/324046.
Transfer history data appended for: https://www.transfermarkt.com/diego-gonzalez/profil/spieler/401707.
Transfer history data appended for: https://www.transfermarkt.com/luis-ureta/profil/spieler/401714.
Transfer history data appended for: https://www.transfermarkt.com/matias-fracchia/profil/spieler/531995.
Transfer history data appended for: https://www.transfermarkt.com/gerardo-navarrete/profil/spieler/133984.
Transfer history data appended for: https://www.transfermarkt.com/diego-gonzalez/profil/spieler/577742.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-munoz/profil/spieler/103252.
Transfer history data appended for: https://www.transfermarkt.com/albert-acevedo/profil/spieler/84232.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-larrondo/profil/spieler/87463.
Transfer history data appended for: https://www.transfermarkt.com/antonio-diaz/profil/spieler/491646.
Transfer history data appended for: https://www.transfermarkt.com/augusto-batalla/profil/spieler/275218.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-marquez/profil/spieler/172591.
Transfer history data appended for: https://www.transfermarkt.com/diego-carreno/profil/spieler/662755.
Transfer history data appended for: https://www.transfermarkt.com/esteban-moreira/profil/spieler/749448.
Transfer history data appended for: https://www.transfermarkt.com/paulo-magalhaes/profil/spieler/89714.
Transfer history data appended for: https://www.transfermarkt.com/ramon-fernandez/profil/spieler/77852.
Transfer history data appended for: https://www.transfermarkt.com/matias-meneses/profil/spieler/547020.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-davis/profil/spieler/738428.
Transfer history data appended for: https://www.transfermarkt.com/abel-moreno/profil/spieler/747714.
Transfer history data appended for: https://www.transfermarkt.com/felipe-seymour/profil/spieler/83891.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-saez/profil/spieler/234238.
Transfer history data appended for: https://www.transfermarkt.com/erick-wiemberg/profil/spieler/531286.
Transfer history data appended for: https://www.transfermarkt.com/thomas-rodriguez/profil/spieler/402581.
Transfer history data appended for: https://www.transfermarkt.com/elvis-hernandez/profil/spieler/745320.
Transfer history data appended for: https://www.transfermarkt.com/alexis-martin-arias/profil/spieler/360521.
Transfer history data appended for: https://www.transfermarkt.com/cristopher-medina/profil/spieler/747832.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-castellani/profil/spieler/87840.
Transfer history data appended for: https://www.transfermarkt.com/christian-vilches/profil/spieler/91055.
Transfer history data appended for: https://www.transfermarkt.com/fernando-cordero/profil/spieler/80733.
Transfer history data appended for: https://www.transfermarkt.com/pedro-sanchez/profil/spieler/525162.
Transfer history data appended for: https://www.transfermarkt.com/jorge-romo/profil/spieler/111066.
Transfer history data appended for: https://www.transfermarkt.com/yonathan-andia/profil/spieler/567414.
Transfer history data appended for: https://www.transfermarkt.com/fabrizio-manzo/profil/spieler/534301.
Transfer history data appended for: https://www.transfermarkt.com/jeisson-vargas/profil/spieler/369564.
Transfer history data appended for: https://www.transfermarkt.com/juan-leiva/profil/spieler/194493.
Transfer history data appended for: https://www.transfermarkt.com/esteban-valencia/profil/spieler/589854.
Transfer history data appended for: https://www.transfermarkt.com/miguel-vargas/profil/spieler/352338.
Transfer history data appended for: https://www.transfermarkt.com/vicente-ramirez/profil/spieler/674846.
Transfer history data appended for: https://www.transfermarkt.com/matias-navarrete/profil/spieler/185654.
Transfer history data appended for: https://www.transfermarkt.com/matias-laba/profil/spieler/147496.
Transfer history data appended for: https://www.transfermarkt.com/cristian-aguirre/profil/spieler/740258.
Transfer history data appended for: https://www.transfermarkt.com/ariel-caceres/profil/spieler/604551.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-rojo/profil/spieler/749054.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-stefanelli/profil/spieler/333923.
Transfer history data appended for: https://www.transfermarkt.com/diego-oyarzun/profil/spieler/297041.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-martinez/profil/spieler/207393.
Transfer history data appended for: https://www.transfermarkt.com/jhon-garcia/profil/spieler/491670.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-rodriguez/profil/spieler/623947.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-verdugo/profil/spieler/512875.
Transfer history data appended for: https://www.transfermarkt.com/cesar-valenzuela/profil/spieler/131237.
Transfer history data appended for: https://www.transfermarkt.com/claudio-sepulveda/profil/spieler/180019.
Transfer history data appended for: https://www.transfermarkt.com/denilson-ovando/profil/spieler/473560.
Transfer history data appended for: https://www.transfermarkt.com/israel-poblete/profil/spieler/336346.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-gutierrez/profil/spieler/662749.
Transfer history data appended for: https://www.transfermarkt.com/dylan-aravena/profil/spieler/749050.
Transfer history data appended for: https://www.transfermarkt.com/cris-martinez/profil/spieler/320331.

Transfer history data appended for: https://www.transfermarkt.com/walter-mazzantti/profil/spieler/477458.
Transfer history data appended for: https://www.transfermarkt.com/javier-altamirano/profil/spieler/567630.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-ramirez/profil/spieler/418464.
Transfer history data appended for: https://www.transfermarkt.com/cristian-cuevas/profil/spieler/186863.
Transfer history data appended for: https://www.transfermarkt.com/joffre-escobar/profil/spieler/264671.
Transfer history data appended for: https://www.transfermarkt.com/juan-sanchez-sotelo/profil/spieler/82550.
Transfer history data appended for: https://www.transfermarkt.com/jose-molina/profil/spieler/740256.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-tapia/profil/spieler/460830.
Transfer history data appended for: https://www.transfermarkt.com/brayan-palmezano/profil/spieler/486832.
Transfer history data appended for: https://www.transfermarkt.com/yerko-urra/profil/spieler/408568.
Transfer history data appended for: https://www.transfermarkt.com/juan-cordova/profil/spieler/512808.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-castellon/profil/spieler/189785.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-gazzolo/profil/spieler/439360.
Transfer history data appended for: https://www.transfermarkt.com/antonio-castillo/profil/spieler/696695.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-garrido/profil/spieler/749051.
Transfer history data appended for: https://www.transfermarkt.com/martin-parra/profil/spieler/749049.
Transfer history data appended for: https://www.transfermarkt.com/salvador-cordero/profil/spieler/418169.
Transfer history data appended for: https://www.transfermarkt.com/ariel-uribe/profil/spieler/628970.
Transfer history data appended for: https://www.transfermarkt.com/carlos-munoz/profil/spieler/138979.
Transfer history data appended for: https://www.transfermarkt.com/chriss-gutierrez/profil/spieler/460880.
Transfer history data appended for: https://www.transfermarkt.com/andres-souper/profil/spieler/512874.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-freitas/profil/spieler/196520.
Transfer history data appended for: https://www.transfermarkt.com/fernando-hurtado/profil/spieler/89712.
Transfer history data appended for: https://www.transfermarkt.com/lukas-soza/profil/spieler/711258.
Transfer history data appended for: https://www.transfermarkt.com/jason-flores/profil/spieler/342244.
Transfer history data appended for: https://www.transfermarkt.com/byron-nieto/profil/spieler/560148.
Transfer history data appended for: https://www.transfermarkt.com/cristian-rojas/profil/spieler/89616.
Transfer history data appended for: https://www.transfermarkt.com/gary-tello/profil/spieler/148735.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-penailillo/profil/spieler/138980.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-sarria/profil/spieler/460917.
Transfer history data appended for: https://www.transfermarkt.com/simon-gonzalez/profil/spieler/740017.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-gonzalez/profil/spieler/53001.
Transfer history data appended for: https://www.transfermarkt.com/tobias-figueroa/profil/spieler/132693.
Transfer history data appended for: https://www.transfermarkt.com/marco-collao/profil/spieler/534290.
Transfer history data appended for: https://www.transfermarkt.com/felipe-flores/profil/spieler/80736.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-mencia/profil/spieler/139438.
Transfer history data appended for: https://www.transfermarkt.com/michael-lepe/profil/spieler/119409.
Transfer history data appended for: https://www.transfermarkt.com/eduard-bello/profil/spieler/309505.
Transfer history data appended for: https://www.transfermarkt.com/branco-ampuero/profil/spieler/185665.
Transfer history data appended for: https://www.transfermarkt.com/luis-guerra/profil/spieler/369965.
Transfer history data appended for: https://www.transfermarkt.com/adrian-cuadra/profil/spieler/413189.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-zuniga/profil/spieler/119423.
Transfer history data appended for: https://www.transfermarkt.com/diego-fernandez/profil/spieler/380188.
Transfer history data appended for: https://www.transfermarkt.com/matias-donoso/profil/spieler/172579.
Transfer history data appended for: https://www.transfermarkt.com/bruno-gutierrez/profil/spieler/718212.
Transfer history data appended for: https://www.transfermarkt.com/hans-salinas/profil/spieler/89765.
Transfer history data appended for: https://www.transfermarkt.com/abel-hidalgo/profil/spieler/567625.
Transfer history data appended for: https://www.transfermarkt.com/jesus-hernandez/profil/spieler/123487.
Transfer history data appended for: https://www.transfermarkt.com/diego-orellana/profil/spieler/156029.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-contreras/profil/spieler/265971.
Transfer history data appended for: https://www.transfermarkt.com/rafael-caroca/profil/spieler/76388.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-blanco/profil/spieler/423635.
Transfer history data appended for: https://www.transfermarkt.com/lucas-aveldano/profil/spieler/81456.
Transfer history data appended for: https://www.transfermarkt.com/cesar-huanca/profil/spieler/460841.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-ramos/profil/spieler/120431.
Transfer history data appended for: https://www.transfermarkt.com/fabian-ramos/profil/spieler/736116.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-perez/profil/spieler/103253.
Transfer history data appended for: https://www.transfermarkt.com/michael-contreras/profil/spieler/179504.
Transfer history data appended for: https://www.transfermarkt.com/guido-mainero/profil/spieler/441270.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-lorenzetti/profil/spieler/30816.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-cuerdo/profil/spieler/73072.
Transfer history data appended for: https://www.transfermarkt.com/julio-borquez/profil/spieler/491632.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-zenteno/profil/spieler/40434.
Transfer history data appended for: https://www.transfermarkt.com/luis-sotomayor/profil/spieler/365674.
Transfer history data appended for: https://www.transfermarkt.com/matias-blazquez/profil/spieler/138965.
Transfer history data appended for: https://www.transfermarkt.com/michael-fuentes/profil/spieler/573836.
Transfer history data appended for: https://www.transfermarkt.com/felipe-saavedra/profil/spieler/408866.
Transfer history data appended for: https://www.transfermarkt.com/misael-cubillos/profil/spieler/266609.
Transfer history data appended for: https://www.transfermarkt.com/franz-schultz/profil/spieler/178887.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-crovetto/profil/spieler/73411.
Transfer history data appended for: https://www.transfermarkt.com/tomas-ahumada/profil/spieler/749055.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-montecinos/profil/spieler/319471.
Transfer history data appended for: https://www.transfermarkt.com/carlos-labrin/profil/spieler/89783.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-medel/profil/spieler/740460.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-orellana/profil/spieler/319473.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-garcia/profil/spieler/567627.
Transfer history data appended for: https://www.transfermarkt.com/manuel-fernandez/profil/spieler/195958.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-aedo/profil/spieler/841065.
Transfer history data appended for: https://www.transfermarkt.com/ariel-martinez/profil/spieler/378873.

Transfer history data appended for: https://www.transfermarkt.com/osvaldo-bosso/profil/spieler/209815.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-delgado/profil/spieler/265540.
Transfer history data appended for: https://www.transfermarkt.com/cristobal-marin/profil/spieler/534971.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-alvarez/profil/spieler/533444.
Transfer history data appended for: https://www.transfermarkt.com/oliver-rojas/profil/spieler/491642.
Transfer history data appended for: https://www.transfermarkt.com/alfred-canales/profil/spieler/740261.
Transfer history data appended for: https://www.transfermarkt.com/fabian-torres/profil/spieler/534285.
Transfer history data appended for: https://www.transfermarkt.com/jesus-ramirez/profil/spieler/419936.
Transfer history data appended for: https://www.transfermarkt.com/jose-devecchi/profil/spieler/282684.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-holgado/profil/spieler/549273.
Transfer history data appended for: https://www.transfermarkt.com/jorge-henriquez/profil/spieler/367230.
Transfer history data appended for: https://www.transfermarkt.com/diego-torres/profil/spieler/227888.
Transfer history data appended for: https://www.transfermarkt.com/ivan-ledezma/profil/spieler/345734.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-munoz/profil/spieler/265839.
Transfer history data appended for: https://www.transfermarkt.com/pablo-lavandeira/profil/spieler/196037.
Transfer history data appended for: https://www.transfermarkt.com/bryan-figueroa/profil/spieler/632227.
Transfer history data appended for: https://www.transfermarkt.com/luis-cabrera/profil/spieler/181483.
Transfer history data appended for: https://www.transfermarkt.com/rene-melendez/profil/spieler/401698.
Transfer history data appended for: https://www.transfermarkt.com/cristobal-munoz/profil/spieler/698322.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-fernandez/profil/spieler/549597.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-vidal/profil/spieler/170021.
Transfer history data appended for: https://www.transfermarkt.com/bayron-saavedra/profil/spieler/345006.
Transfer history data appended for: https://www.transfermarkt.com/jose-aguilera/profil/spieler/602552.
Transfer history data appended for: https://www.transfermarkt.com/john-salas/profil/spieler/442251.
Transfer history data appended for: https://www.transfermarkt.com/fernando-manriquez/profil/spieler/103251.
Transfer history data appended for: https://www.transfermarkt.com/felipe-villagran/profil/spieler/451859.
Transfer history data appended for: https://www.transfermarkt.com/diego-vallejos/profil/spieler/265499.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-orellana/profil/spieler/226315.
Transfer history data appended for: https://www.transfermarkt.com/diego-vergara/profil/spieler/696694.
Transfer history data appended for: https://www.transfermarkt.com/ruben-farfan/profil/spieler/265470.
Transfer history data appended for: https://www.transfermarkt.com/raul-osorio/profil/spieler/319474.
Transfer history data appended for: https://www.transfermarkt.com/rafael-arace/profil/spieler/308698.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-abdala/profil/spieler/732505.
Transfer history data appended for: https://www.transfermarkt.com/matias-cano/profil/spieler/453812.
Transfer history data appended for: https://www.transfermarkt.com/jorge-gatica/profil/spieler/529498.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-palacios/profil/spieler/728527.
Transfer history data appended for: https://www.transfermarkt.com/daniel-retamal/profil/spieler/534283.
Transfer history data appended for: https://www.transfermarkt.com/federico-pereyra/profil/spieler/422746.
Transfer history data appended for: https://www.transfermarkt.com/diego-aravena/profil/spieler/513364.
Transfer history data appended for: https://www.transfermarkt.com/luis-pedro-figueroa/profil/spieler/21754.
Transfer history data appended for: https://www.transfermarkt.com/gaspar-iniguez/profil/spieler/189432.
Transfer history data appended for: https://www.transfermarkt.com/cristian-zavala/profil/spieler/600555.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-berardo/profil/spieler/113594.
Transfer history data appended for: https://www.transfermarkt.com/juan-carlos-espinoza/profil/spieler/124478.
Transfer history data appended for: https://www.transfermarkt.com/joe-abrigo/profil/spieler/491429.
Transfer history data appended for: https://www.transfermarkt.com/cristofer-salas/profil/spieler/729082.
Transfer history data appended for: https://www.transfermarkt.com/victor-gonzalez/profil/spieler/740260.
Transfer history data appended for: https://www.transfermarkt.com/fabian-hormazabal/profil/spieler/371988.
Transfer history data appended for: https://www.transfermarkt.com/martin-tonso/profil/spieler/178987.
Transfer history data appended for: https://www.transfermarkt.com/richard-paredes/profil/spieler/376543.
Transfer history data appended for: https://www.transfermarkt.com/david-vallejos/profil/spieler/739545.
Transfer history data appended for: https://www.transfermarkt.com/enzo-ferrario/profil/spieler/172562.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-brito/profil/spieler/89797.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-fuentealba/profil/spieler/568207.
Transfer history data appended for: https://www.transfermarkt.com/romulo/profil/spieler/687359.
Transfer history data appended for: https://www.transfermarkt.com/raul-olivares/profil/spieler/66281.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-rizzoli/profil/spieler/698490.
Transfer history data appended for: https://www.transfermarkt.com/sergio-arriagada/profil/spieler/747715.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-salinas/profil/spieler/125750.
Transfer history data appended for: https://www.transfermarkt.com/facundo-aguero/profil/spieler/441265.
Transfer history data appended for: https://www.transfermarkt.com/jaime-valdes/profil/spieler/22131.
Transfer history data appended for: https://www.transfermarkt.com/felipe-barrientos/profil/spieler/428471.
Transfer history data appended for: https://www.transfermarkt.com/kevin-medel/profil/spieler/386173.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-baeza/profil/spieler/580093.
Transfer history data appended for: https://www.transfermarkt.com/vicente-duran/profil/spieler/698488.
Transfer history data appended for: https://www.transfermarkt.com/daniel-monardes/profil/spieler/742028.
Transfer history data appended for: https://www.transfermarkt.com/zacarias-lopez/profil/spieler/365813.
Transfer history data appended for: https://www.transfermarkt.com/david-achucarro/profil/spieler/113126.
Transfer history data appended for: https://www.transfermarkt.com/lucas-fasson/profil/spieler/729266.
Transfer history data appended for: https://www.transfermarkt.com/stefano-magnasco/profil/spieler/180907.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-leyton/profil/spieler/184987.
Transfer history data appended for: https://www.transfermarkt.com/danny-perez/profil/spieler/486842.
Transfer history data appended for: https://www.transfermarkt.com/david-montoya/profil/spieler/570526.
Transfer history data appended for: https://www.transfermarkt.com/danilo-catalan/profil/spieler/439363.
Transfer history data appended for: https://www.transfermarkt.com/walter-ponce/profil/spieler/401695.
Transfer history data appended for: https://www.transfermarkt.com/marko-biskupovic/profil/spieler/180906.
Transfer history data appended for: https://www.transfermarkt.com/alex-ibacache/profil/spieler/571083.
Transfer history data appended for: https://www.transfermarkt.com/kennet-lara/profil/spieler/567604.
Transfer history data appended for: https://www.transfermarkt.com/fernando-lazcano/profil/spieler/89784.

Transfer history data appended for: https://www.transfermarkt.com/heber-garcia/profil/spieler/334574.
Transfer history data appended for: https://www.transfermarkt.com/diego-vera/profil/spieler/72657.
Transfer history data appended for: https://www.transfermarkt.com/byron-hernandez/profil/spieler/661373.
Transfer history data appended for: https://www.transfermarkt.com/bayron-oyarzo/profil/spieler/367462.
Transfer history data appended for: https://www.transfermarkt.com/federico-castro/profil/spieler/359042.
Transfer history data appended for: https://www.transfermarkt.com/franco-bechtholdt/profil/spieler/501241.
Transfer history data appended for: https://www.transfermarkt.com/pablo-corral/profil/spieler/179441.
Transfer history data appended for: https://www.transfermarkt.com/matias-cavalleri/profil/spieler/549235.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-mall/profil/spieler/513064.
Transfer history data appended for: https://www.transfermarkt.com/yerson-opazo/profil/spieler/89802.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-ortiz/profil/spieler/740032.
Transfer history data appended for: https://www.transfermarkt.com/martin-cortes/profil/spieler/20223.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-harding/profil/spieler/712111.
Transfer history data appended for: https://www.transfermarkt.com/paulo-garces/profil/spieler/67048.
Transfer history data appended for: https://www.transfermarkt.com/carlos-herrera/profil/spieler/602553.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-jaime/profil/spieler/123013.
Transfer history data appended for: https://www.transfermarkt.com/pablo-parra/profil/spieler/149173.
Transfer history data appended for: https://www.transfermarkt.com/fabian-cerda/profil/spieler/93258.
Transfer history data appended for: https://www.transfermarkt.com/fernando-godoy/profil/spieler/130452.
Transfer history data appended for: https://www.transfermarkt.com/carlos-espinosa/profil/spieler/62150.
Transfer history data appended for: https://www.transfermarkt.com/jens-buss/profil/spieler/665964.
Transfer history data appended for: https://www.transfermarkt.com/leonel-galeano/profil/spieler/124244.
Transfer history data appended for: https://www.transfermarkt.com/jose-rojas/profil/spieler/83890.
Transfer history data appended for: https://www.transfermarkt.com/matias-ormazabal/profil/spieler/567603.
Transfer history data appended for: https://www.transfermarkt.com/diego-urzua/profil/spieler/539066.
Transfer history data appended for: https://www.transfermarkt.com/cesar-diaz/profil/spieler/662741.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-galdames/profil/spieler/660990.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-villagra/profil/spieler/747716.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-nunez/profil/spieler/577011.
Transfer history data appended for: https://www.transfermarkt.com/misael-davila/profil/spieler/119442.
Transfer history data appended for: https://www.transfermarkt.com/mauro-caballero/profil/spieler/213988.
Transfer history data appended for: https://www.transfermarkt.com/mario-larenas/profil/spieler/270782.
Transfer history data appended for: https://www.transfermarkt.com/daniel-castro/profil/spieler/573833.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-gomez/profil/spieler/193137.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-gonzalez/profil/spieler/461601.
Transfer history data appended for: https://www.transfermarkt.com/harold-cummings/profil/spieler/121790.
Transfer history data appended for: https://www.transfermarkt.com/ronald-gonzalez/profil/spieler/146546.
Transfer history data appended for: https://www.transfermarkt.com/thomas-galdames/profil/spieler/539469.
Transfer history data appended for: https://www.transfermarkt.com/felipe-fritz/profil/spieler/386439.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-mancilla/profil/spieler/265588.
Transfer history data appended for: https://www.transfermarkt.com/agustin-volker/profil/spieler/732684.
Transfer history data appended for: https://www.transfermarkt.com/mario-sandoval/profil/spieler/179790.
Transfer history data appended for: https://www.transfermarkt.com/bastian-yanez/profil/spieler/600028.
Transfer history data appended for: https://www.transfermarkt.com/jose-leguizamon/profil/spieler/389552.
Transfer history data appended for: https://www.transfermarkt.com/luis-pavez/profil/spieler/90093.
Transfer history data appended for: https://www.transfermarkt.com/juan-jose-echave/profil/spieler/622351.
Transfer history data appended for: https://www.transfermarkt.com/carlos-palacios/profil/spieler/571219.
Transfer history data appended for: https://www.transfermarkt.com/diego-sanchez/profil/spieler/179532.
Transfer history data appended for: https://www.transfermarkt.com/victor-mendez/profil/spieler/538281.
Transfer history data appended for: https://www.transfermarkt.com/mauro-maureira/profil/spieler/661465.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-salazar/profil/spieler/249261.
Transfer history data appended for: https://www.transfermarkt.com/luis-gonzalez/profil/spieler/749445.
Transfer history data appended for: https://www.transfermarkt.com/luis-pavez/profil/spieler/268150.
Transfer history data appended for: https://www.transfermarkt.com/yulian-mejia/profil/spieler/178114.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-suazo/profil/spieler/385105.
Transfer history data appended for: https://www.transfermarkt.com/bryan-soto/profil/spieler/817052.
Transfer history data appended for: https://www.transfermarkt.com/pablo-solari/profil/spieler/756991.
Transfer history data appended for: https://www.transfermarkt.com/carlo-villanueva/profil/spieler/538282.
Transfer history data appended for: https://www.transfermarkt.com/miguel-pinto/profil/spieler/40431.
Transfer history data appended for: https://www.transfermarkt.com/esteban-paredes/profil/spieler/79022.
Transfer history data appended for: https://www.transfermarkt.com/juan-insaurralde/profil/spieler/65072.
Transfer history data appended for: https://www.transfermarkt.com/branco-provoste/profil/spieler/461622.
Transfer history data appended for: https://www.transfermarkt.com/oscar-opazo/profil/spieler/136901.
Transfer history data appended for: https://www.transfermarkt.com/pablo-mouche/profil/spieler/17872.
Transfer history data appended for: https://www.transfermarkt.com/brayan-cortes/profil/spieler/248352.
Transfer history data appended for: https://www.transfermarkt.com/julio-barroso/profil/spieler/51354.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-blandi/profil/spieler/153022.
Transfer history data appended for: https://www.transfermarkt.com/carlos-carmona/profil/spieler/76387.
Transfer history data appended for: https://www.transfermarkt.com/luciano-arriagada/profil/spieler/737965.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-costa/profil/spieler/203385.
Transfer history data appended for: https://www.transfermarkt.com/williams-alarcon/profil/spieler/599552.
Transfer history data appended for: https://www.transfermarkt.com/ivan-morales/profil/spieler/461608.
Transfer history data appended for: https://www.transfermarkt.com/brayan-vejar/profil/spieler/270424.
Transfer history data appended for: https://www.transfermarkt.com/matias-zaldivia/profil/spieler/168259.
Transfer history data appended for: https://www.transfermarkt.com/felipe-campos/profil/spieler/214645.
Transfer history data appended for: https://www.transfermarkt.com/cesar-fuentes/profil/spieler/189794.
Transfer history data appended for: https://www.transfermarkt.com/javier-parraguez/profil/spieler/181558.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-falcon/profil/spieler/437993.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-jara/profil/spieler/438222.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-valencia/profil/spieler/201318.

Transfer history data appended for: https://www.transfermarkt.com/dario-melo/profil/spieler/189797.
Transfer history data appended for: https://www.transfermarkt.com/ronald-de-la-fuente/profil/spieler/191543.
Transfer history data appended for: https://www.transfermarkt.com/osvaldo-gonzalez/profil/spieler/76391.
Transfer history data appended for: https://www.transfermarkt.com/cristobal-campos/profil/spieler/628969.
Transfer history data appended for: https://www.transfermarkt.com/pablo-aranguiz/profil/spieler/369850.
Transfer history data appended for: https://www.transfermarkt.com/reinaldo-lenis/profil/spieler/268093.
Transfer history data appended for: https://www.transfermarkt.com/augusto-barrios/profil/spieler/187724.
Transfer history data appended for: https://www.transfermarkt.com/luis-del-pino-mago/profil/spieler/390151.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-morales/profil/spieler/491643.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-galani/profil/spieler/534294.
Transfer history data appended for: https://www.transfermarkt.com/walter-montillo/profil/spieler/19984.
Transfer history data appended for: https://www.transfermarkt.com/diego-carrasco/profil/spieler/534284.
Transfer history data appended for: https://www.transfermarkt.com/fernando-cornejo/profil/spieler/367700.
Transfer history data appended for: https://www.transfermarkt.com/brandon-cortes/profil/spieler/663994.
Transfer history data appended for: https://www.transfermarkt.com/matias-rodriguez/profil/spieler/65929.
Transfer history data appended for: https://www.transfermarkt.com/cristian-barros/profil/spieler/692611.
Transfer history data appended for: https://www.transfermarkt.com/angelo-henriquez/profil/spieler/189740.
Transfer history data appended for: https://www.transfermarkt.com/jean-beausejour/profil/spieler/18871.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-guerra/profil/spieler/534037.
Transfer history data appended for: https://www.transfermarkt.com/fernando-de-paul/profil/spieler/157766.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-espinoza/profil/spieler/176905.
Transfer history data appended for: https://www.transfermarkt.com/camilo-moya/profil/spieler/401699.
Transfer history data appended for: https://www.transfermarkt.com/nelson-espinoza/profil/spieler/287696.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-martinez/profil/spieler/366142.
Transfer history data appended for: https://www.transfermarkt.com/simon-contreras/profil/spieler/740255.
Transfer history data appended for: https://www.transfermarkt.com/luis-casanova/profil/spieler/140025.
Transfer history data appended for: https://www.transfermarkt.com/john-riascos/profil/spieler/840956.
Transfer history data appended for: https://www.transfermarkt.com/rodolfo-gonzalez/profil/spieler/89710.
Transfer history data appended for: https://www.transfermarkt.com/john-santander/profil/spieler/245639.
Transfer history data appended for: https://www.transfermarkt.com/eduardo-farias/profil/spieler/89732.
Transfer history data appended for: https://www.transfermarkt.com/oscar-salinas/profil/spieler/156147.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-osses/profil/spieler/662753.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-varas/profil/spieler/82226.
Transfer history data appended for: https://www.transfermarkt.com/juan-gutierrez/profil/spieler/216793.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-jorquera/profil/spieler/222133.
Transfer history data appended for: https://www.transfermarkt.com/facundo-castro/profil/spieler/332252.
Transfer history data appended for: https://www.transfermarkt.com/rodolfo-gamarra/profil/spieler/102277.
Transfer history data appended for: https://www.transfermarkt.com/christopher-mesias/profil/spieler/661479.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-canete/profil/spieler/108810.
Transfer history data appended for: https://www.transfermarkt.com/mario-pardo/profil/spieler/89803.
Transfer history data appended for: https://www.transfermarkt.com/andy-aguilera/profil/spieler/740262.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-silva/profil/spieler/178288.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-santander/profil/spieler/749048.
Transfer history data appended for: https://www.transfermarkt.com/felipe-reynero/profil/spieler/173030.
Transfer history data appended for: https://www.transfermarkt.com/leandro-requena/profil/spieler/89296.
Transfer history data appended for: https://www.transfermarkt.com/jorge-deschamps/profil/spieler/84210.
Transfer history data appended for: https://www.transfermarkt.com/diego-cespedes/profil/spieler/747495.
Transfer history data appended for: https://www.transfermarkt.com/ariel-coronel/profil/spieler/267884.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-cespedes/profil/spieler/189791.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-filla/profil/spieler/576231.
Transfer history data appended for: https://www.transfermarkt.com/francisco-valdes/profil/spieler/832953.
Transfer history data appended for: https://www.transfermarkt.com/franco-ragusa/profil/spieler/138982.
Transfer history data appended for: https://www.transfermarkt.com/pablo-cardenas/profil/spieler/661480.
Transfer history data appended for: https://www.transfermarkt.com/juan-carlos-gaete/profil/spieler/584007.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-olivera/profil/spieler/160221.
Transfer history data appended for: https://www.transfermarkt.com/ivan-contreras/profil/spieler/749446.
Transfer history data appended for: https://www.transfermarkt.com/kevin-figueroa/profil/spieler/837134.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-rivera/profil/spieler/530515.
Transfer history data appended for: https://www.transfermarkt.com/francisco-robles/profil/spieler/747786.
Transfer history data appended for: https://www.transfermarkt.com/cristian-suarez/profil/spieler/64080.
Transfer history data appended for: https://www.transfermarkt.com/johnny-herrera/profil/spieler/10582.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-madrid/profil/spieler/271880.
Transfer history data appended for: https://www.transfermarkt.com/cristian-menendez/profil/spieler/74086.
Transfer history data appended for: https://www.transfermarkt.com/juan-cuevas/profil/spieler/62363.
Transfer history data appended for: https://www.transfermarkt.com/dilan-zuniga/profil/spieler/323842.
Transfer history data appended for: https://www.transfermarkt.com/gary-moya/profil/spieler/840430.
Transfer history data appended for: https://www.transfermarkt.com/luis-santelices/profil/spieler/172111.
Transfer history data appended for: https://www.transfermarkt.com/jorge-diaz/profil/spieler/560312.
Transfer history data appended for: https://www.transfermarkt.com/marco-sebastian-pol/profil/spieler/200609.
Transfer history data appended for: https://www.transfermarkt.com/jorge-pena/profil/spieler/695981.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-pereira/profil/spieler/661482.
Transfer history data appended for: https://www.transfermarkt.com/camilo-rodriguez/profil/spieler/319480.
Transfer history data appended for: https://www.transfermarkt.com/denil-maldonado/profil/spieler/401769.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-cerato/profil/spieler/134495.
Transfer history data appended for: https://www.transfermarkt.com/matias-leiva/profil/spieler/530509.
Transfer history data appended for: https://www.transfermarkt.com/fernando-saavedra/profil/spieler/89764.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-sasso/profil/spieler/747833.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-berrios/profil/spieler/538284.
Transfer history data appended for: https://www.transfermarkt.com/juan-martin-roman/profil/spieler/841245.

Transfer history data appended for: https://www.transfermarkt.com/bastian-san-juan/profil/spieler/272185.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-echeverria/profil/spieler/265726.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-henriquez/profil/spieler/747785.
Transfer history data appended for: https://www.transfermarkt.com/carlos-lobos/profil/spieler/319470.
Transfer history data appended for: https://www.transfermarkt.com/marcos-velazquez/profil/spieler/89773.
Transfer history data appended for: https://www.transfermarkt.com/baldomero-perlaza/profil/spieler/172300.
Transfer history data appended for: https://www.transfermarkt.com/juan-david-valencia/profil/spieler/72566.
Transfer history data appended for: https://www.transfermarkt.com/omar-perez/profil/spieler/74425.
Transfer history data appended for: https://www.transfermarkt.com/miguel-solis/profil/spieler/119182.
Transfer history data appended for: https://www.transfermarkt.com/arley-rodriguez/profil/spieler/208714.
Transfer history data appended for: https://www.transfermarkt.com/brayan-perea/profil/spieler/188498.
Transfer history data appended for: https://www.transfermarkt.com/juan-sebastian-pedroza/profil/spieler/677706.
Transfer history data appended for: https://www.transfermarkt.com/diego-martinez/profil/spieler/74475.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-salazar/profil/spieler/355155.
Transfer history data appended for: https://www.transfermarkt.com/leandro-castellanos/profil/spieler/73346.
Transfer history data appended for: https://www.transfermarkt.com/carmelo-valencia/profil/spieler/73443.
Transfer history data appended for: https://www.transfermarkt.com/antony-otero/profil/spieler/421214.
Transfer history data appended for: https://www.transfermarkt.com/dylan-borrero/profil/spieler/662453.
Transfer history data appended for: https://www.transfermarkt.com/carlos-polo/profil/spieler/650591.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-murillo/profil/spieler/655432.
Transfer history data appended for: https://www.transfermarkt.com/fabio-burbano/profil/spieler/119889.
Transfer history data appended for: https://www.transfermarkt.com/yonatan-murillo/profil/spieler/242546.
Transfer history data appended for: https://www.transfermarkt.com/carlos-arboleda/profil/spieler/179474.
Transfer history data appended for: https://www.transfermarkt.com/camilo-charria/profil/spieler/666225.
Transfer history data appended for: https://www.transfermarkt.com/geovanni-banguera/profil/spieler/413558.
Transfer history data appended for: https://www.transfermarkt.com/andres-perez/profil/spieler/54886.
Transfer history data appended for: https://www.transfermarkt.com/facundo-guichon/profil/spieler/174776.
Transfer history data appended for: https://www.transfermarkt.com/fabian-sambueza/profil/spieler/358015.
Transfer history data appended for: https://www.transfermarkt.com/tomas-maya/profil/spieler/422866.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-hernandez/profil/spieler/643750.
Transfer history data appended for: https://www.transfermarkt.com/kevin-mier/profil/spieler/491542.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-caicedo/profil/spieler/662451.
Transfer history data appended for: https://www.transfermarkt.com/federico-anselmo/profil/spieler/343163.
Transfer history data appended for: https://www.transfermarkt.com/martin-payares/profil/spieler/362093.
Transfer history data appended for: https://www.transfermarkt.com/camilo-rosero/profil/spieler/339762.
Transfer history data appended for: https://www.transfermarkt.com/roger-torres/profil/spieler/126042.
Transfer history data appended for: https://www.transfermarkt.com/jose-moya/profil/spieler/253056.
Transfer history data appended for: https://www.transfermarkt.com/maicol-balanta/profil/spieler/215374.
Transfer history data appended for: https://www.transfermarkt.com/edwin-herrera/profil/spieler/602036.
Transfer history data appended for: https://www.transfermarkt.com/jefferson-duque/profil/spieler/77286.
Transfer history data appended for: https://www.transfermarkt.com/dixon-renteria/profil/spieler/628927.
Transfer history data appended for: https://www.transfermarkt.com/juan-daniel-roa/profil/spieler/161195.
Transfer history data appended for: https://www.transfermarkt.com/jose-palacios/profil/spieler/474620.
Transfer history data appended for: https://www.transfermarkt.com/omar-rodriguez/profil/spieler/606420.
Transfer history data appended for: https://www.transfermarkt.com/daniel-giraldo/profil/spieler/185246.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-chara/profil/spieler/568878.
Transfer history data appended for: https://www.transfermarkt.com/fainer-torijano/profil/spieler/136005.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/carlos-henao/profil/spieler/188393.
Transfer history data appended for: https://www.transfermarkt.com/luis-manuel-seijas/profil/spieler/55231.
Transfer history data appended for: https://www.transfermarkt.com/victor-giraldo/profil/spieler/74517.
Transfer history data appended for: https://www.transfermarkt.com/jhon-jairo-velasquez/profil/spieler/414774.
Transfer history data appended for: https://www.transfermarkt.com/juan-guillermo-pedroza/profil/spieler/263253.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-gil/profil/spieler/567347.
Transfer history data appended for: https://www.transfermarkt.com/federico-arbelaez/profil/spieler/571910.
Transfer history data appended for: https://www.transfermarkt.com/alexis-serna/profil/spieler/648260.
Transfer history data appended for: https://www.transfermarkt.com/luciano-guaycochea/profil/spieler/265082.
Transfer history data appended for: https://www.transfermarkt.com/ronaldo-ariza/profil/spieler/384672.
Transfer history data appended for: https://www.transfermarkt.com/jorge-suarez/profil/spieler/590698.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/harold-rivera/profil/spieler/211391.
Transfer history data appended for: https://www.transfermarkt.com/cesar-arias/profil/spieler/119202.
Transfer history data appended for: https://www.transfermarkt.com/jeisson-palacios/profil/spieler/356497.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-saldana/profil/spieler/362577.
Transfer history data appended for: https://www.transfermarkt.com/wilson-cuero/profil/spieler/118520.
Transfer history data appended for: https://www.transfermarkt.com/david-valencia/profil/spieler/260397.
Transfer history data appended for: https://www.transfermarkt.com/juan-camilo-portilla/profil/spieler/585747.
Transfer history data appended for: https://www.transfermarkt.com/cleider-alzate/profil/spieler/177972.
Transfer history data appended for: https://www.transfermarkt.com/edwin-torres/profil/spieler/593356.
Transfer history data appended for: https://www.transfermarkt.com/jose-correa/profil/spieler/157906.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-jerez/profil/spieler/75712.
Transfer history data appended for: https://www.transfermarkt.com/yeiner-orozco/profil/spieler/189111.
Transfer history data appended for: https://www.transfermarkt.com/pier-graziani/profil/spieler/263038.
Transfer history data appended for: https://www.transfermarkt.com/jhon-vasquez/profil/spieler/389010.
Transfer history data appended for: https://www.transfermarkt.com/carlos-perez/profil/spieler/421014.
Transfer history data appended for: https://www.transfermarkt.com/diego-cuadros/profil/spieler/453577.
Transfer history data appended for: https://www.transfermarkt.com/farid-diaz/profil/spieler/74623.
Transfer history data appended for: https://www.transfermarkt.com/harrison-henao/profil/spieler/165775.
Transfer history data appended for: https://www.transfermarkt.com/juan-david-rios/profil/spieler/417780.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/estefano-arango/profil/spieler/313283.
Transfer history data appended for: https://www.transfermarkt.com/juan-serrano/profil/spieler/593354.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-herrera/profil/spieler/569351.
Transfer history data appended for: https://www.transfermarkt.com/luis-fernando-mosquera/profil/spieler/74102.
Transfer history data appended for: https://www.transfermarkt.com/victor-arboleda/profil/spieler/369190.
Transfer history data appended for: https://www.transfermarkt.com/juan-dominguez/profil/spieler/73685.
Transfer history data appended for: https://www.transfermarkt.com/jackson-montano/profil/spieler/189110.
Transfer history data appended for: https://www.transfermarkt.com/edwin-mosquera/profil/spieler/613201.
Transfer history data appended for: https://www.transfermarkt.com/carlos-sinisterra/profil/spieler/421146.
Transfer history data appended for: https://www.transfermarkt.com/david-gonzalez/profil/spieler/52267.
Transfer history data appended for: https://www.transfermarkt.com/german-cano/profil/spieler/54590.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-tegue/profil/spieler/543464.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-palacios/profil/spieler/210481.
Transfer history data appended for: https://www.transfermarkt.com/bryan-castrillon/profil/spieler/585420.
Transfer history data appended for: https://www.transfermarkt.com/andres-mosquera/profil/spieler/100379.
Transfer history data appended for: https://www.transfermarkt.com/wilson-lopez/profil/spieler/650656.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-castro/profil/spieler/414746.
Transfer history data appended for: https://www.transfermarkt.com/elvis-perlaza/profil/spieler/74668.
Transfer history data appended for: https://www.transfermarkt.com/andres-ricaurte/profil/spieler/253846.
Transfer history data appended for: https://www.transfermarkt.com/diego-herazo/profil/spieler/384580.
Transfer history data appended for: https://www.transfermarkt.com/hernan-pertuz/profil/spieler/92004.
Transfer history data appended for: https://www.transfermarkt.com/jaime-giraldo/profil/spieler/524933.
Transfer history data appended for: https://www.transfermarkt.com/juan-diaz/profil/spieler/632290.
Transfer history data appended for: https://www.transfermarkt.com/esteban-ruiz/profil/spieler/339874.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-macias/profil/spieler/428595.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-marulanda/profil/spieler/591848.
Transfer history data appended for: https://www.transfermarkt.com/yesid-diaz/profil/spieler/653161.
Transfer history data appended for: https://www.transfermarkt.com/deinner-quinones/profil/spieler/352566.
Transfer history data appended for: https://www.transfermarkt.com/didier-moreno/profil/spieler/182122.
Transfer history data appended for: https://www.transfermarkt.com/andres-cadavid/profil/spieler/179487.
Transfer history data appended for: https://www.transfermarkt.com/ever-valencia/profil/spieler/384581.
Transfer history data appended for: https://www.transfermarkt.com/steven-rodriguez/profil/spieler/649330.
Transfer history data appended for: https://www.transfermarkt.com/dairon-mosquera/profil/spieler/255963.
Transfer history data appended for: https://www.transfermarkt.com/diego-arias/profil/spieler/77277.
Transfer history data appended for: https://www.transfermarkt.com/william-palacios/profil/spieler/265982.
Transfer history data appended for: https://www.transfermarkt.com/yhojan-valbuena/profil/spieler/609285.
Transfer history data appended for: https://www.transfermarkt.com/brayan-angulo/profil/spieler/312835.
Transfer history data appended for: https://www.transfermarkt.com/william-arboleda/profil/spieler/74403.
Transfer history data appended for: https://www.transfermarkt.com/william-parra/profil/spieler/331066.
Transfer history data appended for: https://www.transfermarkt.com/juan-manuel-cuesta/profil/spieler/660840.
Transfer history data appended for: https://www.transfermarkt.com/larry-angulo/profil/spieler/571867.
Transfer history data appended for: https://www.transfermarkt.com/cristian-echavarria/profil/spieler/488677.
Transfer history data appended for: https://www.transfermarkt.com/brayan-carabali/profil/spieler/652362.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-cortes/profil/spieler/463397.
Transfer history data appended for: https://www.transfermarkt.com/hector-urrego/profil/spieler/233055.
Transfer history data appended for: https://www.transfermarkt.com/daniel-castro/profil/spieler/745172.
Transfer history data appended for: https://www.transfermarkt.com/luis-tipton/profil/spieler/124752.
Transfer history data appended for: https://www.transfermarkt.com/didier-delgado/profil/spieler/304813.
Transfer history data appended for: https://www.transfermarkt.com/wilder-guisao/profil/spieler/232914.
Transfer history data appended for: https://www.transfermarkt.com/darwin-carrero/profil/spieler/253860.
Transfer history data appended for: https://www.transfermarkt.com/juan-camilo-chaverra/profil/spieler/130482.
Transfer history data appended for: https://www.transfermarkt.com/henry-obando/profil/spieler/261919.
Transfer history data appended for: https://www.transfermarkt.com/andres-sarmiento/profil/spieler/474590.
Transfer history data appended for: https://www.transfermarkt.com/carmelo-valencia/profil/spieler/73443.
Transfer history data appended for: https://www.transfermarkt.com/matias-perez-garcia/profil/spieler/67439.
Transfer history data appended for: https://www.transfermarkt.com/duvan-carillo/profil/spieler/636704.
Transfer history data appended for: https://www.transfermarkt.com/juan-marin/profil/spieler/637526.
Transfer history data appended for: https://www.transfermarkt.com/christian-mina/profil/spieler/460890.
Transfer history data appended for: https://www.transfermarkt.com/harrison-canchimbo/profil/spieler/363060.
Transfer history data appended for: https://www.transfermarkt.com/james-castro/profil/spieler/73348.
Transfer history data appended for: https://www.transfermarkt.com/robert-carvajal/profil/spieler/636666.
Transfer history data appended for: https://www.transfermarkt.com/johan-gomez/profil/spieler/460896.
Transfer history data appended for: https://www.transfermarkt.com/juan-chaverra/profil/spieler/347894.
Transfer history data appended for: https://www.transfermarkt.com/diego-sanchez/profil/spieler/570524.
Transfer history data appended for: https://www.transfermarkt.com/jose-orlando-perez/profil/spieler/648292.
Transfer history data appended for: https://www.transfermarkt.com/erick-montano/profil/spieler/637527.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-duarte/profil/spieler/213469.
Transfer history data appended for: https://www.transfermarkt.com/carlos-mosquera/profil/spieler/122578.
Transfer history data appended for: https://www.transfermarkt.com/john-hernandez/profil/spieler/207551.
Transfer history data appended for: https://www.transfermarkt.com/yeison-carabali/profil/spieler/460892.
Transfer history data appended for: https://www.transfermarkt.com/ever-valencia/profil/spieler/384581.
Transfer history data appended for: https://www.transfermarkt.com/alexis-hinestroza/profil/spieler/73696.
Transfer history data appended for: https://www.transfermarkt.com/jhonatan-agudelo/profil/spieler/313426.
Transfer history data appended for: https://www.transfermarkt.com/daniel-restrepo/profil/spieler/254129.
Transfer history data appended for: https://www.transfermarkt.com/harrinson-mancilla/profil/spieler/460349.
Transfer history data appended for: https://www.transfermarkt.com/david-achucarro/profil/spieler/113126.
Transfer history data appended for: https://www.transfermarkt.com/lisandro-cabrera/profil/spieler/617776.
Transfer history data appended for: https://www.transfermarkt.com/luis-ortiz/profil/spieler/748354.
Transfer history data appended for: https://www.transfermarkt.com/mateo-munoz/profil/spieler/405763.

Transfer history data appended for: https://www.transfermarkt.com/mateo-cardona/profil/spieler/356105.
Transfer history data appended for: https://www.transfermarkt.com/jefferson-solano/profil/spieler/637511.
Transfer history data appended for: https://www.transfermarkt.com/javier-lopez/profil/spieler/182120.
Transfer history data appended for: https://www.transfermarkt.com/jeysen-nunez/profil/spieler/213871.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/diego-chica/profil/spieler/119021.
Transfer history data appended for: https://www.transfermarkt.com/luis-miranda/profil/spieler/637506.
Transfer history data appended for: https://www.transfermarkt.com/michael-lopez/profil/spieler/453922.
Transfer history data appended for: https://www.transfermarkt.com/braynner-garcia/profil/spieler/73352.
Transfer history data appended for: https://www.transfermarkt.com/jhony-da-silva/profil/spieler/127439.
Transfer history data appended for: https://www.transfermarkt.com/omar-montano/profil/spieler/655332.
Transfer history data appended for: https://www.transfermarkt.com/diego-echeverri/profil/spieler/418113.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/harold-rivera/profil/spieler/211391.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-roa/profil/spieler/485879.
Transfer history data appended for: https://www.transfermarkt.com/brayan-moreno/profil/spieler/649680.
Transfer history data appended for: https://www.transfermarkt.com/andres-amaya/profil/spieler/572079.
Transfer history data appended for: https://www.transfermarkt.com/omar-duarte/profil/spieler/384582.
Transfer history data appended for: https://www.transfermarkt.com/jhonathan-caicedo/profil/spieler/334571.
Transfer history data appended for: https://www.transfermarkt.com/bayron-garces/profil/spieler/253282.
Transfer history data appended for: https://www.transfermarkt.com/jhonatan-perez/profil/spieler/572036.
Transfer history data appended for: https://www.transfermarkt.com/jhon-cordoba/profil/spieler/628879.
Transfer history data appended for: https://www.transfermarkt.com/geovanni-banguera/profil/spieler/413558.
Transfer history data appended for: https://www.transfermarkt.com/eddie-ibarguen/profil/spieler/647721.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/elacio-cordoba/profil/spieler/242522.
Transfer history data appended for: https://www.transfermarkt.com/kevin-salazar/profil/spieler/421012.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-gottesman/profil/spieler/498555.
Transfer history data appended for: https://www.transfermarkt.com/victor-moreno/profil/spieler/626675.
Transfer history data appended for: https://www.transfermarkt.com/yilton-diaz/profil/spieler/417778.
Transfer history data appended for: https://www.transfermarkt.com/geovan-montes/profil/spieler/362669.
Transfer history data appended for: https://www.transfermarkt.com/tomas-maya/profil/spieler/422866.
Transfer history data appended for: https://www.transfermarkt.com/luis-cardoza/profil/spieler/90674.
Transfer history data appended for: https://www.transfermarkt.com/diego-barreto/profil/spieler/572038.
Transfer history data appended for: https://www.transfermarkt.com/wilder-mosquera/profil/spieler/356362.
Transfer history data appended for: https://www.transfermarkt.com/diego-sanchez/profil/spieler/570524.
Transfer history data appended for: https://www.transfermarkt.com/jorge-aguirre/profil/spieler/177970.
Transfer history data appended for: https://www.transfermarkt.com/daniel-duarte/profil/spieler/67978.
Transfer history data appended for: https://www.transfermarkt.com/david-ramirez/profil/spieler/588990.
Transfer history data appended for: https://www.transfermarkt.com/francisco-pungo/profil/spieler/497353.
Transfer history data appended for: https://www.transfermarkt.com/jean-becerra/profil/spieler/253043.
Transfer history data appended for: https://www.transfermarkt.com/aldair-quintana/profil/spieler/407168.
Transfer history data appended for: https://www.transfermarkt.com/luis-mosquera/profil/spieler/601321.
Transfer history data appended for: https://www.transfermarkt.com/daniel-moreno/profil/spieler/587425.
Transfer history data appended for: https://www.transfermarkt.com/cristian-canga/profil/spieler/253045.
Transfer history data appended for: https://www.transfermarkt.com/freyn-figueroa/profil/spieler/572075.
Transfer history data appended for: https://www.transfermarkt.com/carlos-riascos/profil/spieler/422864.
Transfer history data appended for: https://www.transfermarkt.com/deyman-cortes/profil/spieler/543468.
Transfer history data appended for: https://www.transfermarkt.com/diego-moreno/profil/spieler/312731.
Transfer history data appended for: https://www.transfermarkt.com/michael-ordonez/profil/spieler/308253.
Transfer history data appended for: https://www.transfermarkt.com/harrison-henao/profil/spieler/165775.
Transfer history data appended for: https://www.transfermarkt.com/yosimarc-torres/profil/spieler/700206.
Transfer history data appended for: https://www.transfermarkt.com/jean-carlos-pestana/profil/spieler/572076.
Transfer history data appended for: https://www.transfermarkt.com/jhon-mena/profil/spieler/589016.
Transfer history data appended for: https://www.transfermarkt.com/hernan-hernandez/profil/spieler/587460.
Transfer history data appended for: https://www.transfermarkt.com/hernan-hechalar/profil/spieler/76151.
Transfer history data appended for: https://www.transfermarkt.com/michael-lopez/profil/spieler/600859.
Transfer history data appended for: https://www.transfermarkt.com/carlos-mosquera/profil/spieler/253868.
Transfer history data appended for: https://www.transfermarkt.com/edward-morillo/profil/spieler/683317.
Transfer history data appended for: https://www.transfermarkt.com/luis-mosquera/profil/spieler/130523.
Transfer history data appended for: https://www.transfermarkt.com/jordan/profil/spieler/191631.
Transfer history data appended for: https://www.transfermarkt.com/arley-rodriguez/profil/spieler/208714.
Transfer history data appended for: https://www.transfermarkt.com/jefersson-martinez/profil/spieler/254122.
Transfer history data appended for: https://www.transfermarkt.com/mateo-giraldo/profil/spieler/580791.
Transfer history data appended for: https://www.transfermarkt.com/alexis-zapata/profil/spieler/263027.
Transfer history data appended for: https://www.transfermarkt.com/ernesto-hernandez/profil/spieler/74255.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-giraldo/profil/spieler/332558.
Transfer history data appended for: https://www.transfermarkt.com/jesus-martinez/profil/spieler/262935.
Transfer history data appended for: https://www.transfermarkt.com/michael-gomez/profil/spieler/413659.
Transfer history data appended for: https://www.transfermarkt.com/carlos-teran/profil/spieler/649184.
Transfer history data appended for: https://www.transfermarkt.com/cristian-arrieta/profil/spieler/365756.
Transfer history data appended for: https://www.transfermarkt.com/santiago-jimenez/profil/spieler/474678.
Transfer history data appended for: https://www.transfermarkt.com/carlos-rojas/profil/spieler/498688.
Transfer history data appended for: https://www.transfermarkt.com/juan-mosquera/profil/spieler/312732.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-betancur/profil/spieler/652352.
Transfer history data appended for: https://www.transfermarkt.com/humberto-mendoza/profil/spieler/63183.
Transfer history data appended for: https://www.transfermarkt.com/yamilson-rivera/profil/spieler/77182.
Transfer history data appended for: https://www.transfermarkt.com/yadir-meneses/profil/spieler/543465.
Transfer history data appended for: https://www.transfermarkt.com/jeronimo-buritica/profil/spieler/652354.
Transfer history data appended for: https://www.transfermarkt.com/jhon-duran/profil/spieler/649317.
Transfer history data appended for: https://www.transfermarkt.com/brayan-lucumi/profil/spieler/262932.
Transfer history data appended for: https://www.transfermarkt.com/wilfrido-de-la-rosa/profil/spieler/325778.
Transfer history data appended for: https://www.transfermarkt.com/ivan-rojas/profil/spieler/474677.
Transfer history data appended for: https://www.transfermarkt.com/santiago-londono/profil/spieler/240142.
Transfer history data appended for: https://www.transfermarkt.com/jairo-palomino/profil/spieler/74666.
Transfer history data appended for: https://www.transfermarkt.com/neyder-moreno/profil/spieler/571908.
Transfer history data appended for: https://www.transfermarkt.com/camilo-velazquez/profil/spieler/498685.
Transfer history data appended for: https://www.transfermarkt.com/bruno/profil/spieler/662578.
Transfer history data appended for: https://www.transfermarkt.com/george-saunders/profil/spieler/312923.
Transfer history data appended for: https://www.transfermarkt.com/francisco-baez/profil/spieler/644772.
Transfer history data appended for: https://www.transfermarkt.com/santiago-norena/profil/spieler/582031.
Transfer history data appended for: https://www.transfermarkt.com/johnatan-estrada/profil/spieler/74059.
Transfer history data appended for: https://www.transfermarkt.com/michael-lopez/profil/spieler/453922.
Transfer history data appended for: https://www.transfermarkt.com/luis-tipton/profil/spieler/124752.
Transfer history data appended for: https://www.transfermarkt.com/juan-jimenez/profil/spieler/313072.
Transfer history data appended for: https://www.transfermarkt.com/dilan-vahos/profil/spieler/659690.
Transfer history data appended for: https://www.transfermarkt.com/jordan/profil/spieler/191631.
Transfer history data appended for: https://www.transfermarkt.com/fabian-viafara/profil/spieler/326011.
Transfer history data appended for: https://www.transfermarkt.com/camilo-ayala/profil/spieler/73678.
Transfer history data appended for: https://www.transfermarkt.com/ederson-moreno/profil/spieler/599707.
Transfer history data appended for: https://www.transfermarkt.com/cristian-florez/profil/spieler/288320.
Transfer history data appended for: https://www.transfermarkt.com/carmelo-valencia/profil/spieler/73443.
Transfer history data appended for: https://www.transfermarkt.com/andrey-estupinan/profil/spieler/583812.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-roa/profil/spieler/485879.
Transfer history data appended for: https://www.transfermarkt.com/felipe-ponce/profil/spieler/70083.

Transfer history data appended for: https://www.transfermarkt.com/mariano-vazquez/profil/spieler/421396.
Transfer history data appended for: https://www.transfermarkt.com/luis-carlos-arias/profil/spieler/100495.
Transfer history data appended for: https://www.transfermarkt.com/franco-bolo/profil/spieler/440005.
Transfer history data appended for: https://www.transfermarkt.com/daniel-rojano/profil/spieler/475779.
Transfer history data appended for: https://www.transfermarkt.com/dager-palacios/profil/spieler/74527.
Transfer history data appended for: https://www.transfermarkt.com/eder-castaneda/profil/spieler/178109.
Transfer history data appended for: https://www.transfermarkt.com/yosimar-quinones/profil/spieler/234799.
Transfer history data appended for: https://www.transfermarkt.com/cristian-tovar/profil/spieler/492999.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-valenzuela/profil/spieler/604861.
Transfer history data appended for: https://www.transfermarkt.com/henry-rojas/profil/spieler/76925.
Transfer history data appended for: https://www.transfermarkt.com/ray-vanegas/profil/spieler/255977.
Transfer history data appended for: https://www.transfermarkt.com/adrian-estacio/profil/spieler/596423.
Transfer history data appended for: https://www.transfermarkt.com/julian-guevara/profil/spieler/498048.
Transfer history data appended for: https://www.transfermarkt.com/jown-cardona/profil/spieler/380700.
Transfer history data appended for: https://www.transfermarkt.com/wilfrido-de-la-rosa/profil/spieler/325778.
Transfer history data appended for: https://www.transfermarkt.com/hasan-vergara/profil/spieler/654031.
Transfer history data appended for: https://www.transfermarkt.com/jose-ortiz/profil/spieler/572044.
Transfer history data appended for: https://www.transfermarkt.com/geisson-perea/profil/spieler/460621.
Transfer history data appended for: https://www.transfermarkt.com/anier-figueroa/profil/spieler/140003.
Transfer history data appended for: https://www.transfermarkt.com/romeesh-ivey/profil/spieler/653672.
Transfer history data appended for: https://www.transfermarkt.com/johan-campana/profil/spieler/654032.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-acosta/profil/spieler/364057.
Transfer history data appended for: https://www.transfermarkt.com/eliser-quinones/profil/spieler/156569.
Transfer history data appended for: https://www.transfermarkt.com/juan-sebastian-villota/profil/spieler/92688.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-britos/profil/spieler/419314.
Transfer history data appended for: https://www.transfermarkt.com/cesar-amaya/profil/spieler/124536.
Transfer history data appended for: https://www.transfermarkt.com/kevin-rendon/profil/spieler/213576.
Transfer history data appended for: https://www.transfermarkt.com/carlos-bejarano/profil/spieler/74479.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/carlos-henao/profil/spieler/188393.
Transfer history data appended for: https://www.transfermarkt.com/john-sanchez/profil/spieler/345657.
Transfer history data appended for: https://www.transfermarkt.com/carlos-mosquera/profil/spieler/253868.
Transfer history data appended for: https://www.transfermarkt.com/brayan-torres/profil/spieler/664927.
Transfer history data appended for: https://www.transfermarkt.com/victor-giraldo/profil/spieler/74517.
Transfer history data appended for: https://www.transfermarkt.com/neto-volpi/profil/spieler/202959.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-carreno/profil/spieler/214234.
Transfer history data appended for: https://www.transfermarkt.com/daniel-giraldo/profil/spieler/185246.
Transfer history data appended for: https://www.transfermarkt.com/leyvin-balanta/profil/spieler/209898.
Transfer history data appended for: https://www.transfermarkt.com/yeison-gordillo/profil/spieler/147670.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-montero/profil/spieler/292985.
Transfer history data appended for: https://www.transfermarkt.com/bernaldo-manzano/profil/spieler/331577.
Transfer history data appended for: https://www.transfermarkt.com/diego-valdes/profil/spieler/119364.
Transfer history data appended for: https://www.transfermarkt.com/carlos-robles/profil/spieler/119914.
Transfer history data appended for: https://www.transfermarkt.com/luis-gonzalez/profil/spieler/86428.
Transfer history data appended for: https://www.transfermarkt.com/marco-perez/profil/spieler/76648.
Transfer history data appended for: https://www.transfermarkt.com/luis-caballero/profil/spieler/127813.
Transfer history data appended for: https://www.transfermarkt.com/larry-vasquez/profil/spieler/260925.
Transfer history data appended for: https://www.transfermarkt.com/pablo-meza/profil/spieler/480418.
Transfer history data appended for: https://www.transfermarkt.com/carlos-renteria/profil/spieler/262951.
Transfer history data appended for: https://www.transfermarkt.com/david-centeno/profil/spieler/352703.
Transfer history data appended for: https://www.transfermarkt.com/nilson-castrillon/profil/spieler/339760.
Transfer history data appended for: https://www.transfermarkt.com/rafael-carrascal/profil/spieler/260385.
Transfer history data appended for: https://www.transfermarkt.com/jorge-ramos/profil/spieler/117876.
Transfer history data appended for: https://www.transfermarkt.com/julian-quinones/profil/spieler/203138.
Transfer history data appended for: https://www.transfermarkt.com/sergio-mosquera/profil/spieler/262514.
Transfer history data appended for: https://www.transfermarkt.com/jose-moya/profil/spieler/253056.
Transfer history data appended for: https://www.transfermarkt.com/johnny-mostacilla/profil/spieler/188492.
Transfer history data appended for: https://www.transfermarkt.com/omar-albornoz/profil/spieler/387605.
Transfer history data appended for: https://www.transfermarkt.com/alex-castro/profil/spieler/304870.
Transfer history data appended for: https://www.transfermarkt.com/maicol-balanta/profil/spieler/215374.
Transfer history data appended for: https://www.transfermarkt.com/juan-guillermo-arboleda/profil/spieler/212696.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-nieto/profil/spieler/260391.
Transfer history data appended for: https://www.transfermarkt.com/jaminton-campaz/profil/spieler/491553.
Transfer history data appended for: https://www.transfermarkt.com/junior-hernandez/profil/spieler/746579.
Transfer history data appended for: https://www.transfermarkt.com/anderson-plata/profil/spieler/211399.
Transfer history data appended for: https://www.transfermarkt.com/kevin-perez/profil/spieler/746582.
Transfer history data appended for: https://www.transfermarkt.com/danovis-banguero/profil/spieler/73345.
Transfer history data appended for: https://www.transfermarkt.com/victor-soto/profil/spieler/74630.
Transfer history data appended for: https://www.transfermarkt.com/william-cuesta/profil/spieler/262915.
Transfer history data appended for: https://www.transfermarkt.com/guido-vadala/profil/spieler/343504.
Transfer history data appended for: https://www.transfermarkt.com/juan-patino/profil/spieler/663186.
Transfer history data appended for: https://www.transfermarkt.com/daniel-catano/profil/spieler/131097.
Transfer history data appended for: https://www.transfermarkt.com/john-garcia/profil/spieler/356360.
Transfer history data appended for: https://www.transfermarkt.com/cristian-bonilla/profil/spieler/102269.
Transfer history data appended for: https://www.transfermarkt.com/walmer-pacheco/profil/spieler/337775.
Transfer history data appended for: https://www.transfermarkt.com/brayner-de-alba/profil/spieler/572074.
Transfer history data appended for: https://www.transfermarkt.com/pablo-sabbag/profil/spieler/426325.
Transfer history data appended for: https://www.transfermarkt.com/andres-murillo/profil/spieler/353928.
Transfer history data appended for: https://www.transfermarkt.com/juan-mahecha/profil/spieler/76636.
Transfer history data appended for: https://www.transfermarkt.com/esteban-ruiz/profil/spieler/339874.
Transfer history data appended for: https://www.transfermarkt.com/matheo-castano/profil/spieler/580636.
Transfer history data appended for: https://www.transfermarkt.com/matias-mier/profil/spieler/76716.
Transfer history data appended for: https://www.transfermarkt.com/oscar-bernal/profil/spieler/304171.
Transfer history data appended for: https://www.transfermarkt.com/jaider-riquett/profil/spieler/462201.
Transfer history data appended for: https://www.transfermarkt.com/jesus-gonzalez/profil/spieler/375302.
Transfer history data appended for: https://www.transfermarkt.com/pablo-lima/profil/spieler/223175.
Transfer history data appended for: https://www.transfermarkt.com/hansel-zapata/profil/spieler/485877.
Transfer history data appended for: https://www.transfermarkt.com/ethan-gonzalez/profil/spieler/460363.
Transfer history data appended for: https://www.transfermarkt.com/daniel-padilla/profil/spieler/572073.
Transfer history data appended for: https://www.transfermarkt.com/neider-barona/profil/spieler/474676.
Transfer history data appended for: https://www.transfermarkt.com/gaston-poncet/profil/spieler/216787.
Transfer history data appended for: https://www.transfermarkt.com/andres-correa/profil/spieler/189393.
Transfer history data appended for: https://www.transfermarkt.com/danilo-arboleda/profil/spieler/364586.
Transfer history data appended for: https://www.transfermarkt.com/carlos-ibarguen/profil/spieler/362582.
Transfer history data appended for: https://www.transfermarkt.com/cristian-palomeque/profil/spieler/260392.
Transfer history data appended for: https://www.transfermarkt.com/armando-vargas/profil/spieler/312834.
Transfer history data appended for: https://www.transfermarkt.com/joan-castro/profil/spieler/480682.
Transfer history data appended for: https://www.transfermarkt.com/stalin-motta/profil/spieler/74524.
Transfer history data appended for: https://www.transfermarkt.com/juan-marin/profil/spieler/657095.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-vacca/profil/spieler/588992.
Transfer history data appended for: https://www.transfermarkt.com/diego-gomez/profil/spieler/312915.
Transfer history data appended for: https://www.transfermarkt.com/kevin-piedrahita/profil/spieler/167038.
Transfer history data appended for: https://www.transfermarkt.com/carlos-peralta/profil/spieler/119912.
Transfer history data appended for: https://www.transfermarkt.com/maicol-medina/profil/spieler/385938.
Transfer history data appended for: https://www.transfermarkt.com/almir-soto/profil/spieler/363731.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/brayan-fernandez/profil/spieler/498267.
Transfer history data appended for: https://www.transfermarkt.com/darwin-carrero/profil/spieler/253860.
Transfer history data appended for: https://www.transfermarkt.com/stiven-lucumi/profil/spieler/773604.
Transfer history data appended for: https://www.transfermarkt.com/julian-millan/profil/spieler/495689.
Transfer history data appended for: https://www.transfermarkt.com/herlbert-soto/profil/spieler/356662.
Transfer history data appended for: https://www.transfermarkt.com/felipe-avila/profil/spieler/460362.
Transfer history data appended for: https://www.transfermarkt.com/norvey-salazar/profil/spieler/139978.
Transfer history data appended for: https://www.transfermarkt.com/cesar-hinestroza/profil/spieler/156555.
Transfer history data appended for: https://www.transfermarkt.com/julian-buitrago/profil/spieler/571911.
Transfer history data appended for: https://www.transfermarkt.com/jesus-marimon/profil/spieler/388617.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/jerson-malagon/profil/spieler/262933.
Transfer history data appended for: https://www.transfermarkt.com/nelson-lemus/profil/spieler/123306.
Transfer history data appended for: https://www.transfermarkt.com/cesar-caicedo/profil/spieler/253044.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/oswal-alvarez/profil/spieler/224947.
Transfer history data appended for: https://www.transfermarkt.com/paul-rubiano/profil/spieler/500074.
Transfer history data appended for: https://www.transfermarkt.com/cristian-barrios/profil/spieler/587296.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/jhon-fredy-salazar/profil/spieler/370678.
Transfer history data appended for: https://www.transfermarkt.com/francisco-carabali/profil/spieler/155817.
Transfer history data appended for: https://www.transfermarkt.com/eder-chaux/profil/spieler/253827.
Transfer history data appended for: https://www.transfermarkt.com/daniel-briceno/profil/spieler/77201.
Transfer history data appended for: https://www.transfermarkt.com/martin-payares/profil/spieler/362093.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/alvaro-villete/profil/spieler/227112.
Transfer history data appended for: https://www.transfermarkt.com/exequiel-benavidez/profil/spieler/68743.
Transfer history data appended for: https://www.transfermarkt.com/miller-mosquera/profil/spieler/298628.
Transfer history data appended for: https://www.transfermarkt.com/kelvin-osorio/profil/spieler/393696.
Transfer history data appended for: https://www.transfermarkt.com/juan-david-castaneda/profil/spieler/345658.
Transfer history data appended for: https://www.transfermarkt.com/jhon-arias/profil/spieler/588989.
Transfer history data appended for: https://www.transfermarkt.com/daniel-mantilla/profil/spieler/571912.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-otero/profil/spieler/77178.
Transfer history data appended for: https://www.transfermarkt.com/carlos-andres-rivas/profil/spieler/332002.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/davinson-monsalve/profil/spieler/73389.
Transfer history data appended for: https://www.transfermarkt.com/israel-alba/profil/spieler/366711.
Transfer history data appended for: https://www.transfermarkt.com/misael-martinez/profil/spieler/657009.
Transfer history data appended for: https://www.transfermarkt.com/diego-gomez/profil/spieler/312915.
Transfer history data appended for: https://www.transfermarkt.com/oscar-balanta/profil/spieler/213580.
Transfer history data appended for: https://www.transfermarkt.com/federico-arbelaez/profil/spieler/571910.
Transfer history data appended for: https://www.transfermarkt.com/juan-david-valencia/profil/spieler/72566.
Transfer history data appended for: https://www.transfermarkt.com/daniel-munoz/profil/spieler/493003.
Transfer history data appended for: https://www.transfermarkt.com/leandro-velazquez/profil/spieler/72442.
Transfer history data appended for: https://www.transfermarkt.com/francisco-rodriguez/profil/spieler/119253.
Transfer history data appended for: https://www.transfermarkt.com/giovanny-martinez/profil/spieler/174366.
Transfer history data appended for: https://www.transfermarkt.com/jader-obrian/profil/spieler/361433.
Transfer history data appended for: https://www.transfermarkt.com/miguel-medina/profil/spieler/362092.
Transfer history data appended for: https://www.transfermarkt.com/daniel-lloreda/profil/spieler/587096.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-rodriguez/profil/spieler/649878.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/jerson-malagon/profil/spieler/262933.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-lopez/profil/spieler/633880.
Transfer history data appended for: https://www.transfermarkt.com/kevin-salazar/profil/spieler/421012.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/jonathan-lopera/profil/spieler/262475.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-angulo/profil/spieler/366324.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/elacio-cordoba/profil/spieler/242522.
Transfer history data appended for: https://www.transfermarkt.com/fernei-ibarguen/profil/spieler/580467.
Transfer history data appended for: https://www.transfermarkt.com/jacobo-escobar/profil/spieler/655729.
Transfer history data appended for: https://www.transfermarkt.com/yilton-diaz/profil/spieler/417778.
Transfer history data appended for: https://www.transfermarkt.com/camilo-diaz/profil/spieler/659624.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/jeison-quinones/profil/spieler/607811.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/mauricio-restrepo/profil/spieler/177974.
Transfer history data appended for: https://www.transfermarkt.com/octavio-patino/profil/spieler/632413.
Transfer history data appended for: https://www.transfermarkt.com/juan-ortiz/profil/spieler/74424.
Transfer history data appended for: https://www.transfermarkt.com/andres-renteria/profil/spieler/233007.
Transfer history data appended for: https://www.transfermarkt.com/anthony-uribe/profil/spieler/155099.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/mauricio-gomez/profil/spieler/272283.
Transfer history data appended for: https://www.transfermarkt.com/alexis-hinestroza/profil/spieler/73696.
Transfer history data appended for: https://www.transfermarkt.com/luis-delgado/profil/spieler/117838.
Transfer history data appended for: https://www.transfermarkt.com/david-contreras/profil/spieler/362581.
Transfer history data appended for: https://www.transfermarkt.com/aldo-leao-ramirez/profil/spieler/63184.
Transfer history data appended for: https://www.transfermarkt.com/johan-jimenez/profil/spieler/493002.
Transfer history data appended for: https://www.transfermarkt.com/hanyer-mosquera/profil/spieler/77175.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/ivan-rivas/profil/spieler/178119.
Transfer history data appended for: https://www.transfermarkt.com/elkin-blanco/profil/spieler/75479.
Transfer history data appended for: https://www.transfermarkt.com/jefferson-mena/profil/spieler/189390.
Transfer history data appended for: https://www.transfermarkt.com/jefferson-cuero/profil/spieler/143721.
Transfer history data appended for: https://www.transfermarkt.com/carlos-ramirez/profil/spieler/77306.
Transfer history data appended for: https://www.transfermarkt.com/gilberto-garcia/profil/spieler/77207.
Transfer history data appended for: https://www.transfermarkt.com/luis-mosquera/profil/spieler/130523.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-freitas/profil/spieler/203367.
Transfer history data appended for: https://www.transfermarkt.com/david-agudelo/profil/spieler/651655.
Transfer history data appended for: https://www.transfermarkt.com/victor-aquino/profil/spieler/90083.
Transfer history data appended for: https://www.transfermarkt.com/anderson-mojica/profil/spieler/649730.
Transfer history data appended for: https://www.transfermarkt.com/feiver-mercado/profil/spieler/77173.
Transfer history data appended for: https://www.transfermarkt.com/didier-delgado/profil/spieler/304813.
Transfer history data appended for: https://www.transfermarkt.com/kevin-moreno/profil/spieler/491533.
Transfer history data appended for: https://www.transfermarkt.com/pablo-mina/profil/spieler/260567.
Transfer history data appended for: https://www.transfermarkt.com/deiber-caicedo/profil/spieler/543467.
Transfer history data appended for: https://www.transfermarkt.com/harrison-canchimbo/profil/spieler/363060.
Transfer history data appended for: https://www.transfermarkt.com/mateo-puerta/profil/spieler/498266.
Transfer history data appended for: https://www.transfermarkt.com/matias-cabrera/profil/spieler/76598.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-giraldo/profil/spieler/664545.
Transfer history data appended for: https://www.transfermarkt.com/jesus-arrieta/profil/spieler/260380.
Transfer history data appended for: https://www.transfermarkt.com/carlos-carbonero/profil/spieler/136605.
Transfer history data appended for: https://www.transfermarkt.com/yeison-tolosa/profil/spieler/529759.
Transfer history data appended for: https://www.transfermarkt.com/camilo-ariza/profil/spieler/654248.
Transfer history data appended for: https://www.transfermarkt.com/camilo-vargas/profil/spieler/74113.
Transfer history data appended for: https://www.transfermarkt.com/juan-carlos-caicedo/profil/spieler/587501.
Transfer history data appended for: https://www.transfermarkt.com/yimmi-congo/profil/spieler/649794.
Transfer history data appended for: https://www.transfermarkt.com/andres-arroyo/profil/spieler/662458.
Transfer history data appended for: https://www.transfermarkt.com/jeison-angulo/profil/spieler/331056.
Transfer history data appended for: https://www.transfermarkt.com/juan-rengifo/profil/spieler/773925.
Transfer history data appended for: https://www.transfermarkt.com/ivan-ibanez/profil/spieler/587555.
Transfer history data appended for: https://www.transfermarkt.com/carlos-mario-rodriguez/profil/spieler/421008.
Transfer history data appended for: https://www.transfermarkt.com/jhon-mosquera/profil/spieler/239126.
Transfer history data appended for: https://www.transfermarkt.com/darwin-andrade/profil/spieler/161282.
Transfer history data appended for: https://www.transfermarkt.com/andres-colorado/profil/spieler/648309.
Transfer history data appended for: https://www.transfermarkt.com/juan-angulo/profil/spieler/84109.
Transfer history data appended for: https://www.transfermarkt.com/johan-wallens/profil/spieler/120013.
Transfer history data appended for: https://www.transfermarkt.com/francisco-delorenzi/profil/spieler/648439.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-benedetti/profil/spieler/382836.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-chara/profil/spieler/568878.
Transfer history data appended for: https://www.transfermarkt.com/andres-balanta/profil/spieler/587547.
Transfer history data appended for: https://www.transfermarkt.com/christian-rivera/profil/spieler/426324.
Transfer history data appended for: https://www.transfermarkt.com/julian-zea/profil/spieler/614845.
Transfer history data appended for: https://www.transfermarkt.com/kevin-velasco/profil/spieler/600857.
Transfer history data appended for: https://www.transfermarkt.com/agustin-palavecino/profil/spieler/610590.
Transfer history data appended for: https://www.transfermarkt.com/cesar-amaya/profil/spieler/124536.
Transfer history data appended for: https://www.transfermarkt.com/luis-ferreira/profil/spieler/773924.
Transfer history data appended for: https://www.transfermarkt.com/kevin-balanta/profil/spieler/339758.
Transfer history data appended for: https://www.transfermarkt.com/richard-renteria/profil/spieler/421210.
Transfer history data appended for: https://www.transfermarkt.com/baldomero-perlaza/profil/spieler/172300.
Transfer history data appended for: https://www.transfermarkt.com/christian-mafla/profil/spieler/131099.
Transfer history data appended for: https://www.transfermarkt.com/felix-charrupi/profil/spieler/651657.
Transfer history data appended for: https://www.transfermarkt.com/andres-reyes/profil/spieler/582995.
Transfer history data appended for: https://www.transfermarkt.com/andres-sarmiento/profil/spieler/474590.
Transfer history data appended for: https://www.transfermarkt.com/carlos-cuesta/profil/spieler/474589.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-guerra/profil/spieler/567016.
Transfer history data appended for: https://www.transfermarkt.com/daniel-munoz/profil/spieler/493003.
Transfer history data appended for: https://www.transfermarkt.com/pablo-ceppelini/profil/spieler/159773.
Transfer history data appended for: https://www.transfermarkt.com/alexis-henriquez/profil/spieler/74153.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-ramirez/profil/spieler/446850.
Transfer history data appended for: https://www.transfermarkt.com/helibelton-palacios/profil/spieler/211389.
Transfer history data appended for: https://www.transfermarkt.com/omar-duarte/profil/spieler/384582.
Transfer history data appended for: https://www.transfermarkt.com/jean-lucas-rivera/profil/spieler/648290.
Transfer history data appended for: https://www.transfermarkt.com/patricio-cucchi/profil/spieler/596911.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-hernandez/profil/spieler/77067.
Transfer history data appended for: https://www.transfermarkt.com/cristian-blanco/profil/spieler/638187.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-gomez/profil/spieler/570522.
Transfer history data appended for: https://www.transfermarkt.com/carlos-rivas/profil/spieler/227390.
Transfer history data appended for: https://www.transfermarkt.com/christian-vargas/profil/spieler/83015.
Transfer history data appended for: https://www.transfermarkt.com/daniel-bocanegra/profil/spieler/129257.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-hernandez/profil/spieler/643750.
Transfer history data appended for: https://www.transfermarkt.com/kevin-mier/profil/spieler/491542.
Transfer history data appended for: https://www.transfermarkt.com/yilmar-velazquez/profil/spieler/638188.
Transfer history data appended for: https://www.transfermarkt.com/brayan-rovira/profil/spieler/345656.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-yabur/profil/spieler/585378.
Transfer history data appended for: https://www.transfermarkt.com/jeison-lucumi/profil/spieler/352567.
Transfer history data appended for: https://www.transfermarkt.com/andres-perea/profil/spieler/491536.
Transfer history data appended for: https://www.transfermarkt.com/aldair-quintana/profil/spieler/407168.
Transfer history data appended for: https://www.transfermarkt.com/yerson-candelo/profil/spieler/158333.

Transfer history data appended for: https://www.transfermarkt.com/jose-cuadrado/profil/spieler/74057.
Transfer history data appended for: https://www.transfermarkt.com/aldo-leao-ramirez/profil/spieler/63184.
Transfer history data appended for: https://www.transfermarkt.com/neyder-moreno/profil/spieler/571908.
Transfer history data appended for: https://www.transfermarkt.com/cristian-moya/profil/spieler/651653.
Transfer history data appended for: https://www.transfermarkt.com/miguel-quintero/profil/spieler/638191.
Transfer history data appended for: https://www.transfermarkt.com/juan-david-ramirez/profil/spieler/552471.
Transfer history data appended for: https://www.transfermarkt.com/deiver-machado/profil/spieler/332560.
Transfer history data appended for: https://www.transfermarkt.com/yeiler-goez/profil/spieler/585358.
Transfer history data appended for: https://www.transfermarkt.com/jarlan-barrera/profil/spieler/338219.
Transfer history data appended for: https://www.transfermarkt.com/gilberto-garcia/profil/spieler/77207.
Transfer history data appended for: https://www.transfermarkt.com/brayan-cordoba/profil/spieler/585356.
Transfer history data appended for: https://www.transfermarkt.com/david-agudelo/profil/spieler/651655.
Transfer history data appended for: https://www.transfermarkt.com/edwuin-cetre/profil/spieler/470390.
Transfer history data appended for: https://www.transfermarkt.com/luis-sandoval/profil/spieler/569222.
Transfer history data appended for: https://www.transfermarkt.com/luis-diaz/profil/spieler/480692.
Transfer history data appended for: https://www.transfermarkt.com/enrique-serje/profil/spieler/456113.
Transfer history data appended for: https://www.transfermarkt.com/homer-martinez/profil/spieler/656344.
Transfer history data appended for: https://www.transfermarkt.com/edder-farias/profil/spieler/140128.
Transfer history data appended for: https://www.transfermarkt.com/german-gutierrez/profil/spieler/332053.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-hernandez/profil/spieler/73693.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-pico/profil/spieler/213528.
Transfer history data appended for: https://www.transfermarkt.com/ivan-luquetta/profil/spieler/524970.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-viera/profil/spieler/33531.
Transfer history data appended for: https://www.transfermarkt.com/michael-rangel/profil/spieler/260393.
Transfer history data appended for: https://www.transfermarkt.com/yohandry-orozco/profil/spieler/72638.
Transfer history data appended for: https://www.transfermarkt.com/luis-gonzalez/profil/spieler/86428.
Transfer history data appended for: https://www.transfermarkt.com/jefferson-gomez/profil/spieler/366655.
Transfer history data appended for: https://www.transfermarkt.com/daniel-moreno/profil/spieler/600842.
Transfer history data appended for: https://www.transfermarkt.com/cesar-haydar/profil/spieler/651477.
Transfer history data appended for: https://www.transfermarkt.com/camilo-diaz/profil/spieler/659624.
Transfer history data appended for: https://www.transfermarkt.com/luis-carlos-ruiz/profil/spieler/77089.
Transfer history data appended for: https://www.transfermarkt.com/fabian-sambueza/profil/spieler/358015.
Transfer history data appended for: https://www.transfermarkt.com/jose-chunga/profil/spieler/224009.
Transfer history data appended for: https://www.transfermarkt.com/rafael-perez/profil/spieler/117874.
Transfer history data appended for: https://www.transfermarkt.com/willer-ditta/profil/spieler/609255.
Transfer history data appended for: https://www.transfermarkt.com/marlon-piedrahita/profil/spieler/73428.
Transfer history data appended for: https://www.transfermarkt.com/roger-torres/profil/spieler/126042.
Transfer history data appended for: https://www.transfermarkt.com/stiwart-acuna/profil/spieler/569219.
Transfer history data appended for: https://www.transfermarkt.com/fabian-angel/profil/spieler/491546.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/david-murillo/profil/spieler/260907.
Transfer history data appended for: https://www.transfermarkt.com/german-mera/profil/spieler/73704.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-fuentes/profil/spieler/480686.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/ivan-rivas/profil/spieler/178119.
Transfer history data appended for: https://www.transfermarkt.com/james-sanchez/profil/spieler/157157.
Transfer history data appended for: https://www.transfermarkt.com/victor-cantillo/profil/spieler/263032.
Transfer history data appended for: https://www.transfermarkt.com/sergio-pabon/profil/spieler/569225.
Transfer history data appended for: https://www.transfermarkt.com/leiner-escalante/profil/spieler/171151.
Transfer history data appended for: https://www.transfermarkt.com/luis-narvaez/profil/spieler/119206.
Transfer history data appended for: https://www.transfermarkt.com/deivy-balanta/profil/spieler/260382.
Transfer history data appended for: https://www.transfermarkt.com/christian-marrugo/profil/spieler/77212.
Transfer history data appended for: https://www.transfermarkt.com/roberto-ovelar/profil/spieler/72984.
Transfer history data appended for: https://www.transfermarkt.com/jefersson-martinez/profil/spieler/254122.
Transfer history data appended for: https://www.transfermarkt.com/santiago-montoya/profil/spieler/237468.
Transfer history data appended for: https://www.transfermarkt.com/juan-camilo-salazar/profil/spieler/572048.
Transfer history data appended for: https://www.transfermarkt.com/andres-llinas/profil/spieler/626693.
Transfer history data appended for: https://www.transfermarkt.com/orles-aragon/profil/spieler/572217.
Transfer history data appended for: https://www.transfermarkt.com/david-silva/profil/spieler/74071.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/christian-huerfano/profil/spieler/570164.
Transfer history data appended for: https://www.transfermarkt.com/juan-moreno/profil/spieler/582924.
Transfer history data appended for: https://www.transfermarkt.com/jhon-duque/profil/spieler/421009.
Transfer history data appended for: https://www.transfermarkt.com/carlos-lopez/profil/spieler/579734.
Transfer history data appended for: https://www.transfermarkt.com/luis-payares/profil/spieler/176256.
Transfer history data appended for: https://www.transfermarkt.com/felipe-banguero/profil/spieler/362406.
Transfer history data appended for: https://www.transfermarkt.com/stiven-vega/profil/spieler/393964.
Transfer history data appended for: https://www.transfermarkt.com/cesar-carrillo/profil/spieler/362886.
Transfer history data appended for: https://www.transfermarkt.com/omar-bertel/profil/spieler/569268.
Transfer history data appended for: https://www.transfermarkt.com/oscar-barreto/profil/spieler/326200.
Transfer history data appended for: https://www.transfermarkt.com/hansel-zapata/profil/spieler/485877.
Transfer history data appended for: https://www.transfermarkt.com/wuilker-farinez/profil/spieler/373714.
Transfer history data appended for: https://www.transfermarkt.com/ramiro-sanchez/profil/spieler/199208.
Transfer history data appended for: https://www.transfermarkt.com/felipe-jaramillo/profil/spieler/570528.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-moreno/profil/spieler/339855.
Transfer history data appended for: https://www.transfermarkt.com/breiner-paz/profil/spieler/483264.
Transfer history data appended for: https://www.transfermarkt.com/jose-guillermo-ortiz/profil/spieler/256343.
Transfer history data appended for: https://www.transfermarkt.com/fabian-gonzalez/profil/spieler/272284.
Transfer history data appended for: https://www.transfermarkt.com/andres-felipe-roman/profil/spieler/552474.
Transfer history data appended for: https://www.transfermarkt.com/juan-dominguez/profil/spieler/73685.
Transfer history data appended for: https://www.transfermarkt.com/eliser-quinones/profil/spieler/156569.
Transfer history data appended for: https://www.transfermarkt.com/jorge-rengifo/profil/spieler/626686.
Transfer history data appended for: https://www.transfermarkt.com/alex-rambal/profil/spieler/647304.
Transfer history data appended for: https://www.transfermarkt.com/juan-perez/profil/spieler/242554.
Transfer history data appended for: https://www.transfermarkt.com/cristian-arango/profil/spieler/262999.
Transfer history data appended for: https://www.transfermarkt.com/juan-camilo-garcia/profil/spieler/626691.
Transfer history data appended for: https://www.transfermarkt.com/deivy-balanta/profil/spieler/260382.
Transfer history data appended for: https://www.transfermarkt.com/jader-valencia/profil/spieler/570165.
Transfer history data appended for: https://www.transfermarkt.com/dairin-gonzalez/profil/spieler/312916.
Transfer history data appended for: https://www.transfermarkt.com/anibal-mosquera/profil/spieler/214737.
Transfer history data appended for: https://www.transfermarkt.com/daiver-vega/profil/spieler/638282.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-marquez/profil/spieler/627396.
Transfer history data appended for: https://www.transfermarkt.com/jahir-scott/profil/spieler/638280.
Transfer history data appended for: https://www.transfermarkt.com/luis-carlos-arias/profil/spieler/100495.
Transfer history data appended for: https://www.transfermarkt.com/andres-canchano/profil/spieler/663968.
Transfer history data appended for: https://www.transfermarkt.com/yulian-gomez/profil/spieler/524932.
Transfer history data appended for: https://www.transfermarkt.com/brayan-correa/profil/spieler/649207.
Transfer history data appended for: https://www.transfermarkt.com/jean-carlos-blanco/profil/spieler/119336.
Transfer history data appended for: https://www.transfermarkt.com/edisson-restrepo/profil/spieler/345653.
Transfer history data appended for: https://www.transfermarkt.com/juan-ortiz/profil/spieler/74424.
Transfer history data appended for: https://www.transfermarkt.com/cesar-giraldo/profil/spieler/460345.
Transfer history data appended for: https://www.transfermarkt.com/henri-pernia/profil/spieler/116593.
Transfer history data appended for: https://www.transfermarkt.com/lucas-sotero/profil/spieler/159533.
Transfer history data appended for: https://www.transfermarkt.com/david-ferreira/profil/spieler/53340.
Transfer history data appended for: https://www.transfermarkt.com/juan-carlos-pereira/profil/spieler/190836.
Transfer history data appended for: https://www.transfermarkt.com/fernando-battiste/profil/spieler/73228.
Transfer history data appended for: https://www.transfermarkt.com/jhojan-valencia/profil/spieler/388289.
Transfer history data appended for: https://www.transfermarkt.com/dixon-renteria/profil/spieler/628927.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-sanchez/profil/spieler/638241.
Transfer history data appended for: https://www.transfermarkt.com/juan-sebastian-villota/profil/spieler/92688.
Transfer history data appended for: https://www.transfermarkt.com/julio-murillo/profil/spieler/167037.
Transfer history data appended for: https://www.transfermarkt.com/giovane/profil/spieler/654237.
Transfer history data appended for: https://www.transfermarkt.com/uvaldo-luna/profil/spieler/273909.
Transfer history data appended for: https://www.transfermarkt.com/cristian-subero/profil/spieler/119013.
Transfer history data appended for: https://www.transfermarkt.com/cristian-mina/profil/spieler/783527.
Transfer history data appended for: https://www.transfermarkt.com/horacio-ramirez/profil/spieler/103117.
Transfer history data appended for: https://www.transfermarkt.com/mario-guerrero/profil/spieler/654176.
Transfer history data appended for: https://www.transfermarkt.com/david-quintero/profil/spieler/614973.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-segovia/profil/spieler/196169.
Transfer history data appended for: https://www.transfermarkt.com/cristian-florez/profil/spieler/288320.
Transfer history data appended for: https://www.transfermarkt.com/juan-nieva/profil/spieler/582545.
Transfer history data appended for: https://www.transfermarkt.com/daniel-quinones/profil/spieler/669669.
Transfer history data appended for: https://www.transfermarkt.com/jhoaho-hinestroza/profil/spieler/255939.
Transfer history data appended for: https://www.transfermarkt.com/yeferson-contreras/profil/spieler/585351.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/andres-alvarez/profil/spieler/601872.
Transfer history data appended for: https://www.transfermarkt.com/jose-lugo/profil/spieler/614869.
Transfer history data appended for: https://www.transfermarkt.com/pedro-franco/profil/spieler/118998.
Transfer history data appended for: https://www.transfermarkt.com/cristian-alvarez/profil/spieler/225998.
Transfer history data appended for: https://www.transfermarkt.com/jhonatan-perez/profil/spieler/572036.
Transfer history data appended for: https://www.transfermarkt.com/hector-quinones/profil/spieler/131094.
Transfer history data appended for: https://www.transfermarkt.com/michael-rangel/profil/spieler/260393.
Transfer history data appended for: https://www.transfermarkt.com/marlon-torres/profil/spieler/485731.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-carvajal/profil/spieler/543466.
Transfer history data appended for: https://www.transfermarkt.com/jhonier-viveros/profil/spieler/213399.
Transfer history data appended for: https://www.transfermarkt.com/arled-cadavid/profil/spieler/253824.
Transfer history data appended for: https://www.transfermarkt.com/juan-zuluaga/profil/spieler/262553.
Transfer history data appended for: https://www.transfermarkt.com/mayer-vidal/profil/spieler/582536.
Transfer history data appended for: https://www.transfermarkt.com/jhon-quinones/profil/spieler/585350.
Transfer history data appended for: https://www.transfermarkt.com/kevin-viveros/profil/spieler/580461.
Transfer history data appended for: https://www.transfermarkt.com/santiago-roa/profil/spieler/498650.
Transfer history data appended for: https://www.transfermarkt.com/luis-alejandro-paz/profil/spieler/70720.
Transfer history data appended for: https://www.transfermarkt.com/marino-hinestroza/profil/spieler/663319.
Transfer history data appended for: https://www.transfermarkt.com/yesus-cabrera/profil/spieler/133522.
Transfer history data appended for: https://www.transfermarkt.com/luis-sanchez/profil/spieler/648483.
Transfer history data appended for: https://www.transfermarkt.com/kevin-andrade/profil/spieler/614898.
Transfer history data appended for: https://www.transfermarkt.com/rafael-carrascal/profil/spieler/260385.
Transfer history data appended for: https://www.transfermarkt.com/julian-guevara/profil/spieler/498048.
Transfer history data appended for: https://www.transfermarkt.com/daniel-buitrago/profil/spieler/216871.
Transfer history data appended for: https://www.transfermarkt.com/matias-pisano/profil/spieler/139923.
Transfer history data appended for: https://www.transfermarkt.com/brayan-angulo/profil/spieler/312835.
Transfer history data appended for: https://www.transfermarkt.com/carlos-sierra/profil/spieler/536653.
Transfer history data appended for: https://www.transfermarkt.com/cristian-hinestroza/profil/spieler/614971.
Transfer history data appended for: https://www.transfermarkt.com/juan-camilo-mesa/profil/spieler/624919.
Transfer history data appended for: https://www.transfermarkt.com/fernando-aristeguieta/profil/spieler/140126.
Transfer history data appended for: https://www.transfermarkt.com/jeison-pinillo/profil/spieler/585349.
Transfer history data appended for: https://www.transfermarkt.com/edwin-velasco/profil/spieler/356098.
Transfer history data appended for: https://www.transfermarkt.com/santiago-moreno/profil/spieler/654766.
Transfer history data appended for: https://www.transfermarkt.com/duvan-vergara/profil/spieler/413658.
Transfer history data appended for: https://www.transfermarkt.com/jean-sinisterra/profil/spieler/648377.
Transfer history data appended for: https://www.transfermarkt.com/carlos-bejarano/profil/spieler/74479.
Transfer history data appended for: https://www.transfermarkt.com/jeison-medina/profil/spieler/570520.
Transfer history data appended for: https://www.transfermarkt.com/jefferson-murillo/profil/spieler/185247.
Transfer history data appended for: https://www.transfermarkt.com/neto-volpi/profil/spieler/202959.
Transfer history data appended for: https://www.transfermarkt.com/luis-jimenez/profil/spieler/654184.
Transfer history data appended for: https://www.transfermarkt.com/misael-riascos/profil/spieler/213596.
Transfer history data appended for: https://www.transfermarkt.com/jhan-valencia/profil/spieler/654799.
Transfer history data appended for: https://www.transfermarkt.com/pablo-bueno/profil/spieler/87508.
Transfer history data appended for: https://www.transfermarkt.com/rafhael-lucas/profil/spieler/225414.
Transfer history data appended for: https://www.transfermarkt.com/vicente-prado/profil/spieler/648103.
Transfer history data appended for: https://www.transfermarkt.com/edwin-ortega/profil/spieler/652395.
Transfer history data appended for: https://www.transfermarkt.com/hugo-daza/profil/spieler/607815.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-ayala/profil/spieler/272259.
Transfer history data appended for: https://www.transfermarkt.com/dario-lopez/profil/spieler/421171.
Transfer history data appended for: https://www.transfermarkt.com/juan-zuluaga/profil/spieler/262553.
Transfer history data appended for: https://www.transfermarkt.com/juan-silgado/profil/spieler/601049.
Transfer history data appended for: https://www.transfermarkt.com/david-cortes/profil/spieler/183882.
Transfer history data appended for: https://www.transfermarkt.com/fabio-castillo/profil/spieler/140015.
Transfer history data appended for: https://www.transfermarkt.com/jorge-obregon/profil/spieler/414773.
Transfer history data appended for: https://www.transfermarkt.com/stiven-renteria/profil/spieler/587552.
Transfer history data appended for: https://www.transfermarkt.com/jorge-lozano/profil/spieler/119179.
Transfer history data appended for: https://www.transfermarkt.com/angel-bonilla/profil/spieler/460366.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-zapata/profil/spieler/648015.
Transfer history data appended for: https://www.transfermarkt.com/delio-ojeda/profil/spieler/202223.
Transfer history data appended for: https://www.transfermarkt.com/edison-toloza/profil/spieler/74111.
Transfer history data appended for: https://www.transfermarkt.com/jhon-mendez/profil/spieler/316991.
Transfer history data appended for: https://www.transfermarkt.com/jhon-renteria/profil/spieler/573347.
Transfer history data appended for: https://www.transfermarkt.com/braison-cardona/profil/spieler/651322.
Transfer history data appended for: https://www.transfermarkt.com/jose-escobar/profil/spieler/77288.
Transfer history data appended for: https://www.transfermarkt.com/alexis-ordonez/profil/spieler/742334.
Transfer history data appended for: https://www.transfermarkt.com/yulian-anchico/profil/spieler/74097.
Transfer history data appended for: https://www.transfermarkt.com/darwin-lopez/profil/spieler/253225.
Transfer history data appended for: https://www.transfermarkt.com/pablo-rojas/profil/spieler/385844.
Transfer history data appended for: https://www.transfermarkt.com/olmes-garcia/profil/spieler/189106.
Transfer history data appended for: https://www.transfermarkt.com/jamil-lucumi-rodriguez/profil/spieler/636559.
Transfer history data appended for: https://www.transfermarkt.com/david-murillo/profil/spieler/260907.
Transfer history data appended for: https://www.transfermarkt.com/stiwar-garcia/profil/spieler/232904.
Transfer history data appended for: https://www.transfermarkt.com/duban-ciro/profil/spieler/742335.
Transfer history data appended for: https://www.transfermarkt.com/roque-cardozo/profil/spieler/210996.
Transfer history data appended for: https://www.transfermarkt.com/edis-ibarguen/profil/spieler/424670.
Transfer history data appended for: https://www.transfermarkt.com/ronaldo-lucena/profil/spieler/377373.
Transfer history data appended for: https://www.transfermarkt.com/andres-arboleda/profil/spieler/89559.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-escorcia/profil/spieler/400087.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-cortes/profil/spieler/463397.
Transfer history data appended for: https://www.transfermarkt.com/jefferson-cuero/profil/spieler/143721.

Transfer history data appended for: https://www.transfermarkt.com/harrison-mojica/profil/spieler/253277.
Transfer history data appended for: https://www.transfermarkt.com/diego-ordonez/profil/spieler/254784.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-lozano/profil/spieler/213137.
Transfer history data appended for: https://www.transfermarkt.com/jesus-murillo/profil/spieler/260908.
Transfer history data appended for: https://www.transfermarkt.com/fabian-mosquera/profil/spieler/460350.
Transfer history data appended for: https://www.transfermarkt.com/yohn-mosquera/profil/spieler/92000.
Transfer history data appended for: https://www.transfermarkt.com/harlin-suarez/profil/spieler/485730.
Transfer history data appended for: https://www.transfermarkt.com/lewis-ochoa/profil/spieler/76922.
Transfer history data appended for: https://www.transfermarkt.com/tomas-clavijo/profil/spieler/585518.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-garcia/profil/spieler/632246.
Transfer history data appended for: https://www.transfermarkt.com/enrique-serje/profil/spieler/456113.
Transfer history data appended for: https://www.transfermarkt.com/carlos-pajaro/profil/spieler/639184.
Transfer history data appended for: https://www.transfermarkt.com/esteban-ocampo/profil/spieler/620113.
Transfer history data appended for: https://www.transfermarkt.com/sergio-roman/profil/spieler/324974.
Transfer history data appended for: https://www.transfermarkt.com/elvis-mosquera/profil/spieler/162656.
Transfer history data appended for: https://www.transfermarkt.com/david-lemos/profil/spieler/424039.
Transfer history data appended for: https://www.transfermarkt.com/marcelino-carreazo/profil/spieler/572043.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-palma/profil/spieler/572041.
Transfer history data appended for: https://www.transfermarkt.com/juan-david-rodriguez/profil/spieler/253847.
Transfer history data appended for: https://www.transfermarkt.com/jean-carlos-blanco/profil/spieler/119336.
Transfer history data appended for: https://www.transfermarkt.com/elkin-soto/profil/spieler/40937.
Transfer history data appended for: https://www.transfermarkt.com/carlos-lizarazo/profil/spieler/119975.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/mauricio-restrepo/profil/spieler/177974.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-steer/profil/spieler/90851.
Transfer history data appended for: https://www.transfermarkt.com/adrian-estacio/profil/spieler/596423.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/diego-peralta/profil/spieler/140008.
Transfer history data appended for: https://www.transfermarkt.com/erick-montano/profil/spieler/637527.
Transfer history data appended for: https://www.transfermarkt.com/juan-salcedo/profil/spieler/460694.
Transfer history data appended for: https://www.transfermarkt.com/david-gomez/profil/spieler/356361.
Transfer history data appended for: https://www.transfermarkt.com/kevin-londono/profil/spieler/421007.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-moreno/profil/spieler/339855.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-nieto/profil/spieler/260391.
Transfer history data appended for: https://www.transfermarkt.com/johan-carbonero/profil/spieler/572042.
Transfer history data appended for: https://www.transfermarkt.com/junior-julio/profil/spieler/610253.
Transfer history data appended for: https://www.transfermarkt.com/gerardo-ortiz/profil/spieler/89260.
Transfer history data appended for: https://www.transfermarkt.com/miguel-nazarit/profil/spieler/572039.
Transfer history data appended for: https://www.transfermarkt.com/edis-ibarguen/profil/spieler/424670.
Transfer history data appended for: https://www.transfermarkt.com/edwin-velasco/profil/spieler/356098.
Transfer history data appended for: https://www.transfermarkt.com/andres-felipe-correa/profil/spieler/177973.
Transfer history data appended for: https://www.transfermarkt.com/dario-andres-rodriguez/profil/spieler/312526.
Transfer history data appended for: https://www.transfermarkt.com/joel-contreras/profil/spieler/663055.
Transfer history data appended for: https://www.transfermarkt.com/efrain-navarro/profil/spieler/580427.
Transfer history data appended for: https://www.transfermarkt.com/jean-paul-pineda/profil/spieler/90096.
Transfer history data appended for: https://www.transfermarkt.com/jeison-quinones/profil/spieler/119344.
Transfer history data appended for: https://www.transfermarkt.com/harold-gomez/profil/spieler/148697.
Transfer history data appended for: https://www.transfermarkt.com/anderson-angulo/profil/spieler/570531.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-gomez/profil/spieler/52028.
Transfer history data appended for: https://www.transfermarkt.com/james-aguirre/profil/spieler/332056.
Transfer history data appended for: https://www.transfermarkt.com/camilo-mancilla/profil/spieler/262981.
Transfer history data appended for: https://www.transfermarkt.com/nelson-ramos/profil/spieler/74477.
Transfer history data appended for: https://www.transfermarkt.com/roque-caballero/profil/spieler/417776.
Transfer history data appended for: https://www.transfermarkt.com/christian-vargas/profil/spieler/83015.
Transfer history data appended for: https://www.transfermarkt.com/fabio-rodriguez/profil/spieler/77184.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/jeison-quinones/profil/spieler/607811.
Transfer history data appended for: https://www.transfermarkt.com/steve-makuka/profil/spieler/403753.
Transfer history data appended for: https://www.transfermarkt.com/henri-pernia/profil/spieler/116593.
Transfer history data appended for: https://www.transfermarkt.com/jorge-aguirre/profil/spieler/177970.
Transfer history data appended for: https://www.transfermarkt.com/sergio-romero/profil/spieler/242558.
Transfer history data appended for: https://www.transfermarkt.com/luis-hurtado/profil/spieler/428935.
Transfer history data appended for: https://www.transfermarkt.com/miguel-felipe-barragan/profil/spieler/632414.
Transfer history data appended for: https://www.transfermarkt.com/andres-ariza/profil/spieler/663163.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-bernal/profil/spieler/74098.
Transfer history data appended for: https://www.transfermarkt.com/javier-orobio/profil/spieler/426656.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-avila/profil/spieler/89576.
Transfer history data appended for: https://www.transfermarkt.com/johan-caballero/profil/spieler/571896.
Transfer history data appended for: https://www.transfermarkt.com/sherman-cardenas/profil/spieler/38823.
Transfer history data appended for: https://www.transfermarkt.com/carlos-ibarguen/profil/spieler/362582.
Transfer history data appended for: https://www.transfermarkt.com/yuber-asprilla/profil/spieler/130516.
Transfer history data appended for: https://www.transfermarkt.com/cesar-quintero/profil/spieler/119362.
Transfer history data appended for: https://www.transfermarkt.com/juan-felipe-torres/profil/spieler/331391.
Transfer history data appended for: https://www.transfermarkt.com/elkin-blanco/profil/spieler/75479.
Transfer history data appended for: https://www.transfermarkt.com/luis-mena/profil/spieler/119027.
Transfer history data appended for: https://www.transfermarkt.com/roger-lemus/profil/spieler/190791.
Transfer history data appended for: https://www.transfermarkt.com/marvin-vallecilla/profil/spieler/356457.
Transfer history data appended for: https://www.transfermarkt.com/jhon-perez/profil/spieler/380699.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-nunez/profil/spieler/83531.
Transfer history data appended for: https://www.transfermarkt.com/mingan-cui/profil/spieler/231433.
Transfer history data appended for: https://www.transfermarkt.com/xuri-zhao/profil/spieler/81816.
Transfer history data appended for: https://www.transfermarkt.com/xiao-zhou/profil/spieler/563420.
Transfer history data appended for: https://www.transfermarkt.com/sam-larsson/profil/spieler/159668.
Transfer history data appended for: https://www.transfermarkt.com/liangming-lin/profil/spieler/359385.
Transfer history data appended for: https://www.transfermarkt.com/lei-tong/profil/spieler/363584.
Transfer history data appended for: https://www.transfermarkt.com/jiaxuan-zhu/profil/spieler/795262.
Transfer history data appended for: https://www.transfermarkt.com/jiamin-xu/profil/spieler/231446.
Transfer history data appended for: https://www.transfermarkt.com/chong-zhang/profil/spieler/156070.
Transfer history data appended for: https://www.transfermarkt.com/guowen-sun/profil/spieler/218235.
Transfer history data appended for: https://www.transfermarkt.com/jailson/profil/spieler/366948.
Transfer history data appended for: https://www.transfermarkt.com/jiahui-huang/profil/spieler/527716.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-boateng/profil/spieler/332612.
Transfer history data appended for: https://www.transfermarkt.com/qinghao-xue/profil/spieler/521129.
Transfer history data appended for: https://www.transfermarkt.com/pengfei-shan/profil/spieler/231440.
Transfer history data appended for: https://www.transfermarkt.com/salomon-rondon/profil/spieler/80197.
Transfer history data appended for: https://www.transfermarkt.com/xianjun-wang/profil/spieler/468293.
Transfer history data appended for: https://www.transfermarkt.com/xuebo-li/profil/spieler/587422.
Transfer history data appended for: https://www.transfermarkt.com/wei-wu/profil/spieler/359404.
Transfer history data appended for: https://www.transfermarkt.com/huanhuan-shan/profil/spieler/424770.
Transfer history data appended for: https://www.transfermarkt.com/yanfeng-dong/profil/spieler/267531.
Transfer history data appended for: https://www.transfermarkt.com/haoyu-yang/profil/spieler/819278.
Transfer history data appended for: https://www.transfermarkt.com/yupeng-he/profil/spieler/527717.
Transfer history data appended for: https://www.transfermarkt.com/jinxian-wang/profil/spieler/267553.
Transfer history data appended for: https://www.transfermarkt.com/shuai-li/profil/spieler/279525.
Transfer history data appended for: https://www.transfermarkt.com/marcus-danielson/profil/spieler/48249.
Transfer history data appended for: https://www.transfermarkt.com/yaopeng-wang/profil/spieler/267554.
Transfer history data appended for: https://www.transfermarkt.com/hui-cheng/profil/spieler/469302.
Transfer history data appended for: https://www.transfermarkt.com/marek-hamsik/profil/spieler/38593.
Transfer history data appended for: https://www.transfermarkt.com/zhenao-wang/profil/spieler/527720.
Transfer history data appended for: https://www.transfermarkt.com/jianbin-li/profil/spieler/173251.
Transfer history data appended for: https://www.transfermarkt.com/hao-guo/profil/spieler/236635.
Transfer history data appended for: https://www.transfermarkt.com/yue-song/profil/spieler/266874.
Transfer history data appended for: https://www.transfermarkt.com/kaimu-zheng/profil/spieler/218291.
Transfer history data appended for: https://www.transfermarkt.com/haoyu-mao/profil/spieler/492146.
Transfer history data appended for: https://www.transfermarkt.com/shiwei-che/profil/spieler/316122.
Transfer history data appended for: https://www.transfermarkt.com/felix-bastians/profil/spieler/39083.
Transfer history data appended for: https://www.transfermarkt.com/taoyu-piao/profil/spieler/260808.
Transfer history data appended for: https://www.transfermarkt.com/frank-acheampong/profil/spieler/157160.
Transfer history data appended for: https://www.transfermarkt.com/yingjie-zhao/profil/spieler/218026.
Transfer history data appended for: https://www.transfermarkt.com/yuefeng-bai/profil/spieler/185082.
Transfer history data appended for: https://www.transfermarkt.com/zhi-xiao/profil/spieler/148184.
Transfer history data appended for: https://www.transfermarkt.com/sandro-lima/profil/spieler/284739.
Transfer history data appended for: https://www.transfermarkt.com/jiakang-hui/profil/spieler/211058.
Transfer history data appended for: https://www.transfermarkt.com/tianyi-qiu/profil/spieler/148875.
Transfer history data appended for: https://www.transfermarkt.com/jingxuan-lan/profil/spieler/657136.
Transfer history data appended for: https://www.transfermarkt.com/tiquinho-soares/profil/spieler/103381.
Transfer history data appended for: https://www.transfermarkt.com/weijun-xie/profil/spieler/525911.
Transfer history data appended for: https://www.transfermarkt.com/zhenghao-wang/profil/spieler/657129.
Transfer history data appended for: https://www.transfermarkt.com/zixuan-han/profil/spieler/492097.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/yuanjie-su/profil/spieler/292786.
Transfer history data appended for: https://www.transfermarkt.com/honglue-zhao/profil/spieler/156072.
Transfer history data appended for: https://www.transfermarkt.com/yumiao-qian/profil/spieler/520997.
Transfer history data appended for: https://www.transfermarkt.com/shangkun-teng/profil/spieler/156520.
Transfer history data appended for: https://www.transfermarkt.com/yang-liu/profil/spieler/211899.
Transfer history data appended for: https://www.transfermarkt.com/shenglong-jiang/profil/spieler/527715.
Transfer history data appended for: https://www.transfermarkt.com/wangsong-tan/profil/spieler/81807.
Transfer history data appended for: https://www.transfermarkt.com/hao-rong/profil/spieler/133813.
Transfer history data appended for: https://www.transfermarkt.com/peng-wang/profil/spieler/439769.
Transfer history data appended for: https://www.transfermarkt.com/wenhao-long/profil/spieler/458472.
Transfer history data appended for: https://www.transfermarkt.com/zhechao-chen/profil/spieler/267529.
Transfer history data appended for: https://www.transfermarkt.com/richairo-zivkovic/profil/spieler/252755.
Transfer history data appended for: https://www.transfermarkt.com/miao-tang/profil/spieler/150081.
Transfer history data appended for: https://www.transfermarkt.com/songyi-li/profil/spieler/229719.
Transfer history data appended for: https://www.transfermarkt.com/chengru-wu/profil/spieler/468290.
Transfer history data appended for: https://www.transfermarkt.com/zhizhao-chen/profil/spieler/211056.
Transfer history data appended for: https://www.transfermarkt.com/jiaqi-han/profil/spieler/563419.
Transfer history data appended for: https://www.transfermarkt.com/huapeng-wang/profil/spieler/527719.
Transfer history data appended for: https://www.transfermarkt.com/mousa-dembele/profil/spieler/19368.
Transfer history data appended for: https://www.transfermarkt.com/adrian-mierzejewski/profil/spieler/16955.
Transfer history data appended for: https://www.transfermarkt.com/renatinho/profil/spieler/68804.
Transfer history data appended for: https://www.transfermarkt.com/lin-lu/profil/spieler/218210.
Transfer history data appended for: https://www.transfermarkt.com/gong-zhang/profil/spieler/245721.
Transfer history data appended for: https://www.transfermarkt.com/chao-zeng/profil/spieler/254211.
Transfer history data appended for: https://www.transfermarkt.com/chugui-ye/profil/spieler/269271.
Transfer history data appended for: https://www.transfermarkt.com/yuncheng-fu/profil/spieler/425163.
Transfer history data appended for: https://www.transfermarkt.com/teng-yi/profil/spieler/153214.
Transfer history data appended for: https://www.transfermarkt.com/chun-lok-tan/profil/spieler/278983.
Transfer history data appended for: https://www.transfermarkt.com/ming-li/profil/spieler/655578.
Transfer history data appended for: https://www.transfermarkt.com/jihong-jiang/profil/spieler/156052.
Transfer history data appended for: https://www.transfermarkt.com/feiya-chang/profil/spieler/251948.
Transfer history data appended for: https://www.transfermarkt.com/tixiang-li/profil/spieler/150150.
Transfer history data appended for: https://www.transfermarkt.com/yuelei-cheng/profil/spieler/183048.
Transfer history data appended for: https://www.transfermarkt.com/zhengyu-huang/profil/spieler/424780.
Transfer history data appended for: https://www.transfermarkt.com/wenjie-song/profil/spieler/211354.
Transfer history data appended for: https://www.transfermarkt.com/cheng-piao/profil/spieler/211254.
Transfer history data appended for: https://www.transfermarkt.com/dehai-zou/profil/spieler/218248.
Transfer history data appended for: https://www.transfermarkt.com/yang-yu/profil/spieler/150166.
Transfer history data appended for: https://www.transfermarkt.com/renato-augusto/profil/spieler/53058.
Transfer history data appended for: https://www.transfermarkt.com/gang-wang/profil/spieler/61353.
Transfer history data appended for: https://www.transfermarkt.com/min-jae-kim/profil/spieler/503482.
Transfer history data appended for: https://www.transfermarkt.com/alan/profil/spieler/73460.
Transfer history data appended for: https://www.transfermarkt.com/zhongguo-chi/profil/spieler/252282.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-viera/profil/spieler/153238.
Transfer history data appended for: https://www.transfermarkt.com/tao-jiang/profil/spieler/157220.
Transfer history data appended for: https://www.transfermarkt.com/ziming-wang/profil/spieler/317148.
Transfer history data appended for: https://www.transfermarkt.com/lei-li/profil/spieler/211060.
Transfer history data appended for: https://www.transfermarkt.com/taiyan-jin/profil/spieler/211012.
Transfer history data appended for: https://www.transfermarkt.com/quanbo-guo/profil/spieler/424960.
Transfer history data appended for: https://www.transfermarkt.com/da-wen/profil/spieler/570093.
Transfer history data appended for: https://www.transfermarkt.com/nico-yennaris/profil/spieler/122721.
Transfer history data appended for: https://www.transfermarkt.com/john-hou-saeter/profil/spieler/323446.
Transfer history data appended for: https://www.transfermarkt.com/sen-hou/profil/spieler/147782.
Transfer history data appended for: https://www.transfermarkt.com/dun-ba/profil/spieler/268766.
Transfer history data appended for: https://www.transfermarkt.com/kunyue-ma/profil/spieler/655922.
Transfer history data appended for: https://www.transfermarkt.com/xizhe-zhang/profil/spieler/150163.
Transfer history data appended for: https://www.transfermarkt.com/guobo-liu/profil/spieler/527714.
Transfer history data appended for: https://www.transfermarkt.com/fernando/profil/spieler/105456.
Transfer history data appended for: https://www.transfermarkt.com/cedric-bakambu/profil/spieler/127048.
Transfer history data appended for: https://www.transfermarkt.com/peng-lu/profil/spieler/156057.
Transfer history data appended for: https://www.transfermarkt.com/dabao-yu/profil/spieler/58386.
Transfer history data appended for: https://www.transfermarkt.com/fan-yang/profil/spieler/425206.
Transfer history data appended for: https://www.transfermarkt.com/junling-yan/profil/spieler/224161.
Transfer history data appended for: https://www.transfermarkt.com/hai-yu/profil/spieler/46827.
Transfer history data appended for: https://www.transfermarkt.com/shenyuan-li/profil/spieler/448145.
Transfer history data appended for: https://www.transfermarkt.com/huachen-zhang/profil/spieler/424938.
Transfer history data appended for: https://www.transfermarkt.com/tong-guo/profil/spieler/661972.
Transfer history data appended for: https://www.transfermarkt.com/aaron-mooy/profil/spieler/123951.
Transfer history data appended for: https://www.transfermarkt.com/oscar/profil/spieler/85314.
Transfer history data appended for: https://www.transfermarkt.com/shenchao-wang/profil/spieler/236672.
Transfer history data appended for: https://www.transfermarkt.com/wenzhuo-huang/profil/spieler/571371.
Transfer history data appended for: https://www.transfermarkt.com/jian-shi/profil/spieler/571369.
Transfer history data appended for: https://www.transfermarkt.com/lai-wei/profil/spieler/448143.
Transfer history data appended for: https://www.transfermarkt.com/yi-zhang/profil/spieler/254626.
Transfer history data appended for: https://www.transfermarkt.com/boyan-jia/profil/spieler/776224.
Transfer history data appended for: https://www.transfermarkt.com/haowen-li/profil/spieler/251980.
Transfer history data appended for: https://www.transfermarkt.com/huikang-cai/profil/spieler/236609.
Transfer history data appended for: https://www.transfermarkt.com/shiyuan-yang/profil/spieler/254621.
Transfer history data appended for: https://www.transfermarkt.com/chunxin-chen/profil/spieler/491968.
Transfer history data appended for: https://www.transfermarkt.com/binbin-chen/profil/spieler/363791.
Transfer history data appended for: https://www.transfermarkt.com/rui-yu/profil/spieler/224162.
Transfer history data appended for: https://www.transfermarkt.com/ke-shi/profil/spieler/218244.

Transfer history data appended for: https://www.transfermarkt.com/zhen-wei/profil/spieler/424939.
Transfer history data appended for: https://www.transfermarkt.com/marko-arnautovic/profil/spieler/41384.
Transfer history data appended for: https://www.transfermarkt.com/shenglong-li/profil/spieler/254611.
Transfer history data appended for: https://www.transfermarkt.com/wei-chen/profil/spieler/363795.
Transfer history data appended for: https://www.transfermarkt.com/huan-fu/profil/spieler/250199.
Transfer history data appended for: https://www.transfermarkt.com/murahmetjan-muzepper/profil/spieler/148170.
Transfer history data appended for: https://www.transfermarkt.com/hulk/profil/spieler/80562.
Transfer history data appended for: https://www.transfermarkt.com/chuangyi-lin/profil/spieler/236647.
Transfer history data appended for: https://www.transfermarkt.com/wenjie-lei/profil/spieler/448142.
Transfer history data appended for: https://www.transfermarkt.com/wenjun-lu/profil/spieler/236649.
Transfer history data appended for: https://www.transfermarkt.com/guan-he/profil/spieler/236638.
Transfer history data appended for: https://www.transfermarkt.com/wei-zhang/profil/spieler/254642.
Transfer history data appended for: https://www.transfermarkt.com/dalun-gao/profil/spieler/544701.
Transfer history data appended for: https://www.transfermarkt.com/xi-wu/profil/spieler/148891.
Transfer history data appended for: https://www.transfermarkt.com/mubarak-wakaso/profil/spieler/45639.
Transfer history data appended for: https://www.transfermarkt.com/cheng-zhang/profil/spieler/252325.
Transfer history data appended for: https://www.transfermarkt.com/jiahao-zhu/profil/spieler/661920.
Transfer history data appended for: https://www.transfermarkt.com/tianyi-gao/profil/spieler/425245.
Transfer history data appended for: https://www.transfermarkt.com/boyuan-feng/profil/spieler/363752.
Transfer history data appended for: https://www.transfermarkt.com/abduhamit-abdugheni/profil/spieler/449191.
Transfer history data appended for: https://www.transfermarkt.com/zihao-huang/profil/spieler/589614.
Transfer history data appended for: https://www.transfermarkt.com/yinong-tian/profil/spieler/224160.
Transfer history data appended for: https://www.transfermarkt.com/xiang-ji/profil/spieler/211307.
Transfer history data appended for: https://www.transfermarkt.com/yan-zhang/profil/spieler/355783.
Transfer history data appended for: https://www.transfermarkt.com/jing-luo/profil/spieler/236650.
Transfer history data appended for: https://www.transfermarkt.com/xiaobin-zhang/profil/spieler/302080.
Transfer history data appended for: https://www.transfermarkt.com/xiaofan-xie/profil/spieler/447881.
Transfer history data appended for: https://www.transfermarkt.com/miranda/profil/spieler/33357.
Transfer history data appended for: https://www.transfermarkt.com/jiawei-li/profil/spieler/657163.
Transfer history data appended for: https://www.transfermarkt.com/chao-gu/profil/spieler/211655.
Transfer history data appended for: https://www.transfermarkt.com/boyu-yang/profil/spieler/156069.
Transfer history data appended for: https://www.transfermarkt.com/shuming-hu/profil/spieler/795268.
Transfer history data appended for: https://www.transfermarkt.com/pengfei-xie/profil/spieler/218247.
Transfer history data appended for: https://www.transfermarkt.com/zichang-huang/profil/spieler/437944.
Transfer history data appended for: https://www.transfermarkt.com/yun-zhou/profil/spieler/156877.
Transfer history data appended for: https://www.transfermarkt.com/yuxi-qi/profil/spieler/468278.
Transfer history data appended for: https://www.transfermarkt.com/chongqiu-ye/profil/spieler/211309.
Transfer history data appended for: https://www.transfermarkt.com/alex-teixeira/profil/spieler/66515.
Transfer history data appended for: https://www.transfermarkt.com/zhiwei-xie/profil/spieler/661961.
Transfer history data appended for: https://www.transfermarkt.com/li-zou/profil/spieler/795265.
Transfer history data appended for: https://www.transfermarkt.com/lingfeng-zhang/profil/spieler/439780.
Transfer history data appended for: https://www.transfermarkt.com/wei-wang/profil/spieler/252106.
Transfer history data appended for: https://www.transfermarkt.com/aidi-fulangxisi/profil/spieler/218195.
Transfer history data appended for: https://www.transfermarkt.com/jinhao-bi/profil/spieler/211841.
Transfer history data appended for: https://www.transfermarkt.com/junchen-zhou/profil/spieler/509011.
Transfer history data appended for: https://www.transfermarkt.com/lu-zhang/profil/spieler/148164.
Transfer history data appended for: https://www.transfermarkt.com/xiaoting-feng/profil/spieler/81815.
Transfer history data appended for: https://www.transfermarkt.com/stephan-el-shaarawy/profil/spieler/94529.
Transfer history data appended for: https://www.transfermarkt.com/chenjie-zhu/profil/spieler/509001.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-moreno/profil/spieler/74661.
Transfer history data appended for: https://www.transfermarkt.com/hanchao-yu/profil/spieler/45308.
Transfer history data appended for: https://www.transfermarkt.com/jiajun-bai/profil/spieler/224158.
Transfer history data appended for: https://www.transfermarkt.com/mingjian-zhao/profil/spieler/156073.
Transfer history data appended for: https://www.transfermarkt.com/jianrong-zhu/profil/spieler/211164.
Transfer history data appended for: https://www.transfermarkt.com/shin-wook-kim/profil/spieler/152689.
Transfer history data appended for: https://www.transfermarkt.com/kai-sun/profil/spieler/250226.
Transfer history data appended for: https://www.transfermarkt.com/fidel-martinez/profil/spieler/75612.
Transfer history data appended for: https://www.transfermarkt.com/xu-yang/profil/spieler/140382.
Transfer history data appended for: https://www.transfermarkt.com/sheng-qin/profil/spieler/156846.
Transfer history data appended for: https://www.transfermarkt.com/yunding-cao/profil/spieler/185084.
Transfer history data appended for: https://www.transfermarkt.com/shuai-li/profil/spieler/35225.
Transfer history data appended for: https://www.transfermarkt.com/stephane-mbia/profil/spieler/27470.
Transfer history data appended for: https://www.transfermarkt.com/zhen-ma/profil/spieler/571339.
Transfer history data appended for: https://www.transfermarkt.com/pin-lu/profil/spieler/279527.
Transfer history data appended for: https://www.transfermarkt.com/xinli-peng/profil/spieler/211062.
Transfer history data appended for: https://www.transfermarkt.com/shenglong-jiang/profil/spieler/527715.
Transfer history data appended for: https://www.transfermarkt.com/yue-zhu/profil/spieler/594462.
Transfer history data appended for: https://www.transfermarkt.com/alexander-ndoumbou/profil/spieler/127144.
Transfer history data appended for: https://www.transfermarkt.com/jiabao-wen/profil/spieler/419477.
Transfer history data appended for: https://www.transfermarkt.com/haijian-wang/profil/spieler/655476.
Transfer history data appended for: https://www.transfermarkt.com/shilin-sun/profil/spieler/251163.
Transfer history data appended for: https://www.transfermarkt.com/baojie-zhu/profil/spieler/211068.
Transfer history data appended for: https://www.transfermarkt.com/zheng-zheng/profil/spieler/148011.
Transfer history data appended for: https://www.transfermarkt.com/marouane-fellaini/profil/spieler/39679.
Transfer history data appended for: https://www.transfermarkt.com/jingdao-jin/profil/spieler/198438.
Transfer history data appended for: https://www.transfermarkt.com/yang-liu/profil/spieler/316041.
Transfer history data appended for: https://www.transfermarkt.com/tamas-kadar/profil/spieler/64313.
Transfer history data appended for: https://www.transfermarkt.com/xinghan-wu/profil/spieler/221670.
Transfer history data appended for: https://www.transfermarkt.com/abdurasul-abudulam/profil/spieler/509012.
Transfer history data appended for: https://www.transfermarkt.com/moises/profil/spieler/128822.
Transfer history data appended for: https://www.transfermarkt.com/dalei-wang/profil/spieler/143068.
Transfer history data appended for: https://www.transfermarkt.com/tianyu-qi/profil/spieler/236526.

Transfer history data appended for: https://www.transfermarkt.com/kerui-chen/profil/spieler/254169.
Transfer history data appended for: https://www.transfermarkt.com/junshuai-liu/profil/spieler/337995.
Transfer history data appended for: https://www.transfermarkt.com/binbin-liu/profil/spieler/218268.
Transfer history data appended for: https://www.transfermarkt.com/hailong-li/profil/spieler/337524.
Transfer history data appended for: https://www.transfermarkt.com/lin-dai/profil/spieler/148842.
Transfer history data appended for: https://www.transfermarkt.com/qihang-sun/profil/spieler/572110.
Transfer history data appended for: https://www.transfermarkt.com/xin-tian/profil/spieler/492324.
Transfer history data appended for: https://www.transfermarkt.com/long-song/profil/spieler/211680.
Transfer history data appended for: https://www.transfermarkt.com/liuyu-duan/profil/spieler/571342.
Transfer history data appended for: https://www.transfermarkt.com/leonardo/profil/spieler/27065.
Transfer history data appended for: https://www.transfermarkt.com/cong-huang/profil/spieler/419841.
Transfer history data appended for: https://www.transfermarkt.com/graziano-pelle/profil/spieler/29594.
Transfer history data appended for: https://www.transfermarkt.com/junmin-hao/profil/spieler/63549.
Transfer history data appended for: https://www.transfermarkt.com/lei-wu/profil/spieler/531282.
Transfer history data appended for: https://www.transfermarkt.com/rongze-han/profil/spieler/236521.
Transfer history data appended for: https://www.transfermarkt.com/guanxi-li/profil/spieler/424768.
Transfer history data appended for: https://www.transfermarkt.com/tianyu-guo/profil/spieler/424769.
Transfer history data appended for: https://www.transfermarkt.com/yuhao-zhao/profil/spieler/261342.
Transfer history data appended for: https://www.transfermarkt.com/huaze-gao/profil/spieler/363583.
Transfer history data appended for: https://www.transfermarkt.com/hongbo-yin/profil/spieler/230443.
Transfer history data appended for: https://www.transfermarkt.com/wenyi-chi/profil/spieler/252281.
Transfer history data appended for: https://www.transfermarkt.com/paulinho/profil/spieler/212923.
Transfer history data appended for: https://www.transfermarkt.com/qiuming-wang/profil/spieler/261247.
Transfer history data appended for: https://www.transfermarkt.com/cheng-yang/profil/spieler/50486.
Transfer history data appended for: https://www.transfermarkt.com/ximing-pan/profil/spieler/269730.
Transfer history data appended for: https://www.transfermarkt.com/wei-zhang/profil/spieler/657156.
Transfer history data appended for: https://www.transfermarkt.com/samir-memisevic/profil/spieler/238595.
Transfer history data appended for: https://www.transfermarkt.com/shipeng-luo/profil/spieler/572711.
Transfer history data appended for: https://www.transfermarkt.com/hang-ren/profil/spieler/155203.
Transfer history data appended for: https://www.transfermarkt.com/tianyuan-xu/profil/spieler/439776.
Transfer history data appended for: https://www.transfermarkt.com/hao-li/profil/spieler/251979.
Transfer history data appended for: https://www.transfermarkt.com/yu-zhang/profil/spieler/594467.
Transfer history data appended for: https://www.transfermarkt.com/jing-liu/profil/spieler/359390.
Transfer history data appended for: https://www.transfermarkt.com/yaxiong-bao/profil/spieler/570188.
Transfer history data appended for: https://www.transfermarkt.com/marcao/profil/spieler/476102.
Transfer history data appended for: https://www.transfermarkt.com/wei-liao/profil/spieler/661924.
Transfer history data appended for: https://www.transfermarkt.com/chengdong-zhang/profil/spieler/138655.
Transfer history data appended for: https://www.transfermarkt.com/wenjun-jiang/profil/spieler/212145.
Transfer history data appended for: https://www.transfermarkt.com/lin-cui/profil/spieler/450984.
Transfer history data appended for: https://www.transfermarkt.com/haifeng-ding/profil/spieler/150014.
Transfer history data appended for: https://www.transfermarkt.com/junzhe-zhang/profil/spieler/217836.
Transfer history data appended for: https://www.transfermarkt.com/senwen-luo/profil/spieler/236523.
Transfer history data appended for: https://www.transfermarkt.com/wei-ren/profil/spieler/448147.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-buya-turay/profil/spieler/340745.
Transfer history data appended for: https://www.transfermarkt.com/xiao-chen/profil/spieler/254171.
Transfer history data appended for: https://www.transfermarkt.com/shihao-piao/profil/spieler/252307.
Transfer history data appended for: https://www.transfermarkt.com/chengjian-liao/profil/spieler/254633.
Transfer history data appended for: https://www.transfermarkt.com/puliang-shao/profil/spieler/148002.
Transfer history data appended for: https://www.transfermarkt.com/jiyu-zhong/profil/spieler/287570.
Transfer history data appended for: https://www.transfermarkt.com/xuan-cao/profil/spieler/156495.
Transfer history data appended for: https://www.transfermarkt.com/muriqui/profil/spieler/74249.
Transfer history data appended for: https://www.transfermarkt.com/zitong-chen/profil/spieler/492151.
Transfer history data appended for: https://www.transfermarkt.com/xinyu-liu/profil/spieler/251188.
Transfer history data appended for: https://www.transfermarkt.com/romulo/profil/spieler/140682.
Transfer history data appended for: https://www.transfermarkt.com/matheus/profil/spieler/35245.
Transfer history data appended for: https://www.transfermarkt.com/yun-yang/profil/spieler/107486.
Transfer history data appended for: https://www.transfermarkt.com/yubiao-deng/profil/spieler/439774.
Transfer history data appended for: https://www.transfermarkt.com/chaoyang-liu/profil/spieler/509003.
Transfer history data appended for: https://www.transfermarkt.com/peng-wang/profil/spieler/287567.
Transfer history data appended for: https://www.transfermarkt.com/feng-han/profil/spieler/154338.
Transfer history data appended for: https://www.transfermarkt.com/ziming-liu/profil/spieler/356238.
Transfer history data appended for: https://www.transfermarkt.com/hantao-lu/profil/spieler/655243.
Transfer history data appended for: https://www.transfermarkt.com/zeng-chen/profil/spieler/360370.
Transfer history data appended for: https://www.transfermarkt.com/pu-chen/profil/spieler/376597.
Transfer history data appended for: https://www.transfermarkt.com/peng-wang/profil/spieler/367451.
Transfer history data appended for: https://www.transfermarkt.com/jianfei-zhao/profil/spieler/437943.
Transfer history data appended for: https://www.transfermarkt.com/xuelong-sun/profil/spieler/492404.
Transfer history data appended for: https://www.transfermarkt.com/aokai-zhang/profil/spieler/447002.
Transfer history data appended for: https://www.transfermarkt.com/oscar-taty-maritu/profil/spieler/596689.
Transfer history data appended for: https://www.transfermarkt.com/stoppila-sunzu/profil/spieler/82324.
Transfer history data appended for: https://www.transfermarkt.com/zhenqiang-zhang/profil/spieler/236685.
Transfer history data appended for: https://www.transfermarkt.com/zhiyun-zheng/profil/spieler/315614.
Transfer history data appended for: https://www.transfermarkt.com/jianxiang-sun/profil/spieler/794785.
Transfer history data appended for: https://www.transfermarkt.com/jinze-wang/profil/spieler/482839.
Transfer history data appended for: https://www.transfermarkt.com/tim-chow/profil/spieler/196693.
Transfer history data appended for: https://www.transfermarkt.com/yan-wu/profil/spieler/236677.
Transfer history data appended for: https://www.transfermarkt.com/hao-chen/profil/spieler/236518.
Transfer history data appended for: https://www.transfermarkt.com/jing-guo/profil/spieler/439773.
Transfer history data appended for: https://www.transfermarkt.com/zhao-ke/profil/spieler/250207.
Transfer history data appended for: https://www.transfermarkt.com/wentao-zhang/profil/spieler/254643.
Transfer history data appended for: https://www.transfermarkt.com/christian-bassogog/profil/spieler/374281.
Transfer history data appended for: https://www.transfermarkt.com/xin-luo/profil/spieler/252137.

Transfer history data appended for: https://www.transfermarkt.com/chuang-huang/profil/spieler/439772.
Transfer history data appended for: https://www.transfermarkt.com/guoming-wang/profil/spieler/251168.
Transfer history data appended for: https://www.transfermarkt.com/xu-zhang/profil/spieler/563415.
Transfer history data appended for: https://www.transfermarkt.com/chenglong-shi/profil/spieler/448271.
Transfer history data appended for: https://www.transfermarkt.com/changjie-du/profil/spieler/361752.
Transfer history data appended for: https://www.transfermarkt.com/sung-hwan-kim/profil/spieler/134668.
Transfer history data appended for: https://www.transfermarkt.com/keqiang-chen/profil/spieler/662481.
Transfer history data appended for: https://www.transfermarkt.com/longxiang-sun/profil/spieler/468294.
Transfer history data appended for: https://www.transfermarkt.com/ivotm/profil/spieler/55499.
Transfer history data appended for: https://www.transfermarkt.com/xuan-han/profil/spieler/252100.
Transfer history data appended for: https://www.transfermarkt.com/fernando-karanga/profil/spieler/118654.
Transfer history data appended for: https://www.transfermarkt.com/yifan-wang/profil/spieler/656336.
Transfer history data appended for: https://www.transfermarkt.com/abduwal-ablet/profil/spieler/211372.
Transfer history data appended for: https://www.transfermarkt.com/boxuan-feng/profil/spieler/412962.
Transfer history data appended for: https://www.transfermarkt.com/ziyi-niu/profil/spieler/662480.
Transfer history data appended for: https://www.transfermarkt.com/haiwang-song/profil/spieler/316233.
Transfer history data appended for: https://www.transfermarkt.com/jinbao-zhong/profil/spieler/259686.
Transfer history data appended for: https://www.transfermarkt.com/yusong-ni/profil/spieler/156058.
Transfer history data appended for: https://www.transfermarkt.com/xingyu-ma/profil/spieler/140459.
Transfer history data appended for: https://www.transfermarkt.com/kuo-yang/profil/spieler/252011.
Transfer history data appended for: https://www.transfermarkt.com/shangyuan-wang/profil/spieler/228326.
Transfer history data appended for: https://www.transfermarkt.com/abraham-halik/profil/spieler/784606.
Transfer history data appended for: https://www.transfermarkt.com/kun-hu/profil/spieler/797128.
Transfer history data appended for: https://www.transfermarkt.com/boxuan-song/profil/spieler/148879.
Transfer history data appended for: https://www.transfermarkt.com/huan-liu/profil/spieler/245706.
Transfer history data appended for: https://www.transfermarkt.com/dong-cao/profil/spieler/424987.
Transfer history data appended for: https://www.transfermarkt.com/congyao-yin/profil/spieler/325737.
Transfer history data appended for: https://www.transfermarkt.com/tianpeng-wen/profil/spieler/367339.
Transfer history data appended for: https://www.transfermarkt.com/qing-wu/profil/spieler/155677.
Transfer history data appended for: https://www.transfermarkt.com/xiaofei-deng/profil/spieler/50533.
Transfer history data appended for: https://www.transfermarkt.com/jie-chen/profil/spieler/201784.
Transfer history data appended for: https://www.transfermarkt.com/defu-ma/profil/spieler/570218.
Transfer history data appended for: https://www.transfermarkt.com/alan-kardec/profil/spieler/53922.
Transfer history data appended for: https://www.transfermarkt.com/yerjet-yerzat/profil/spieler/268995.
Transfer history data appended for: https://www.transfermarkt.com/hao-luo/profil/spieler/316511.
Transfer history data appended for: https://www.transfermarkt.com/wu-xu/profil/spieler/424996.
Transfer history data appended for: https://www.transfermarkt.com/weijie-sui/profil/spieler/236668.
Transfer history data appended for: https://www.transfermarkt.com/xiyang-huang/profil/spieler/155660.
Transfer history data appended for: https://www.transfermarkt.com/shuai-yang/profil/spieler/316458.
Transfer history data appended for: https://www.transfermarkt.com/kejiang-chen/profil/spieler/363798.
Transfer history data appended for: https://www.transfermarkt.com/lei-chen/profil/spieler/148838.
Transfer history data appended for: https://www.transfermarkt.com/jiaxing-deng/profil/spieler/795248.
Transfer history data appended for: https://www.transfermarkt.com/zhe-jiang/profil/spieler/211811.
Transfer history data appended for: https://www.transfermarkt.com/le-liu/profil/spieler/245707.
Transfer history data appended for: https://www.transfermarkt.com/honglin-dong/profil/spieler/316136.
Transfer history data appended for: https://www.transfermarkt.com/mincheng-yuan/profil/spieler/365550.
Transfer history data appended for: https://www.transfermarkt.com/dilmurat-mawlanniyaz/profil/spieler/449187.
Transfer history data appended for: https://www.transfermarkt.com/marcinho/profil/spieler/520081.
Transfer history data appended for: https://www.transfermarkt.com/denis-popovic/profil/spieler/85574.
Transfer history data appended for: https://www.transfermarkt.com/haochen-zhang/profil/spieler/794191.
Transfer history data appended for: https://www.transfermarkt.com/zhenli-liu/profil/spieler/81823.
Transfer history data appended for: https://www.transfermarkt.com/xinfeng-fang/profil/spieler/483902.
Transfer history data appended for: https://www.transfermarkt.com/jagos-vukovic/profil/spieler/46894.
Transfer history data appended for: https://www.transfermarkt.com/zihao-yan/profil/spieler/267559.
Transfer history data appended for: https://www.transfermarkt.com/zhe-shi/profil/spieler/252314.
Transfer history data appended for: https://www.transfermarkt.com/zhizhao-li/profil/spieler/654860.
Transfer history data appended for: https://www.transfermarkt.com/xiang-gao/profil/spieler/104806.
Transfer history data appended for: https://www.transfermarkt.com/bari-mamatil/profil/spieler/185642.
Transfer history data appended for: https://www.transfermarkt.com/joseph-marie-minala/profil/spieler/289087.
Transfer history data appended for: https://www.transfermarkt.com/hao-wang/profil/spieler/220484.
Transfer history data appended for: https://www.transfermarkt.com/yu-xing/profil/spieler/363236.
Transfer history data appended for: https://www.transfermarkt.com/yaki-yen/profil/spieler/93629.
Transfer history data appended for: https://www.transfermarkt.com/memet-abdulla-ezmat/profil/spieler/657461.
Transfer history data appended for: https://www.transfermarkt.com/yu-yang/profil/spieler/211022.
Transfer history data appended for: https://www.transfermarkt.com/fei-wang/profil/spieler/155216.
Transfer history data appended for: https://www.transfermarkt.com/jianwen-wang/profil/spieler/279732.
Transfer history data appended for: https://www.transfermarkt.com/jiangshan-yao/profil/spieler/211308.
Transfer history data appended for: https://www.transfermarkt.com/weipeng-jiang/profil/spieler/259682.
Transfer history data appended for: https://www.transfermarkt.com/zheng-zou/profil/spieler/211165.
Transfer history data appended for: https://www.transfermarkt.com/zhexiang-ruan/profil/spieler/316447.
Transfer history data appended for: https://www.transfermarkt.com/jiashen-liu/profil/spieler/211849.
Transfer history data appended for: https://www.transfermarkt.com/romain-alessandrini/profil/spieler/98334.
Transfer history data appended for: https://www.transfermarkt.com/shi-zhao/profil/spieler/268793.
Transfer history data appended for: https://www.transfermarkt.com/jean-evrard-kouassi/profil/spieler/178322.
Transfer history data appended for: https://www.transfermarkt.com/yi-luo/profil/spieler/155668.
Transfer history data appended for: https://www.transfermarkt.com/zhifeng-wang/profil/spieler/491272.
Transfer history data appended for: https://www.transfermarkt.com/chunyu-dong/profil/spieler/217901.
Transfer history data appended for: https://www.transfermarkt.com/shoubo-sun/profil/spieler/156062.
Transfer history data appended for: https://www.transfermarkt.com/ao-xia/profil/spieler/572714.
Transfer history data appended for: https://www.transfermarkt.com/jinghang-hu/profil/spieler/316465.
Transfer history data appended for: https://www.transfermarkt.com/hang-li/profil/spieler/251155.
Transfer history data appended for: https://www.transfermarkt.com/leo-baptistao/profil/spieler/221899.

Transfer history data appended for: https://www.transfermarkt.com/chao-li/profil/spieler/251154.
Transfer history data appended for: https://www.transfermarkt.com/tong-zhou/profil/spieler/212157.
Transfer history data appended for: https://www.transfermarkt.com/rafael-silva/profil/spieler/213619.
Transfer history data appended for: https://www.transfermarkt.com/defu-song/profil/spieler/662509.
Transfer history data appended for: https://www.transfermarkt.com/yi-liu/profil/spieler/252258.
Transfer history data appended for: https://www.transfermarkt.com/yun-liu/profil/spieler/317136.
Transfer history data appended for: https://www.transfermarkt.com/pengfei-han/profil/spieler/276523.
Transfer history data appended for: https://www.transfermarkt.com/zhiwei-song/profil/spieler/252145.
Transfer history data appended for: https://www.transfermarkt.com/tian-ming/profil/spieler/312368.
Transfer history data appended for: https://www.transfermarkt.com/shangkun-liu/profil/spieler/251927.
Transfer history data appended for: https://www.transfermarkt.com/bozhao-zhou/profil/spieler/656020.
Transfer history data appended for: https://www.transfermarkt.com/ao-chen/profil/spieler/468289.
Transfer history data appended for: https://www.transfermarkt.com/junjian-liao/profil/spieler/236646.
Transfer history data appended for: https://www.transfermarkt.com/kai-wang/profil/spieler/156524.
Transfer history data appended for: https://www.transfermarkt.com/zhen-cong/profil/spieler/314537.
Transfer history data appended for: https://www.transfermarkt.com/zhibo-ai/profil/spieler/147758.
Transfer history data appended for: https://www.transfermarkt.com/zilei-jiang/profil/spieler/424942.
Transfer history data appended for: https://www.transfermarkt.com/yuanyi-li/profil/spieler/265712.
Transfer history data appended for: https://www.transfermarkt.com/zhen-ge/profil/spieler/230372.
Transfer history data appended for: https://www.transfermarkt.com/ke-sun/profil/spieler/156851.
Transfer history data appended for: https://www.transfermarkt.com/qiang-jin/profil/spieler/264407.
Transfer history data appended for: https://www.transfermarkt.com/zhipeng-jiang/profil/spieler/211125.
Transfer history data appended for: https://www.transfermarkt.com/ole-selnaes/profil/spieler/175961.
Transfer history data appended for: https://www.transfermarkt.com/wai-tsun-dai/profil/spieler/522543.
Transfer history data appended for: https://www.transfermarkt.com/yue-liu/profil/spieler/252259.
Transfer history data appended for: https://www.transfermarkt.com/lin-gao/profil/spieler/74160.
Transfer history data appended for: https://www.transfermarkt.com/wei-guo/profil/spieler/236636.
Transfer history data appended for: https://www.transfermarkt.com/haidong-lu/profil/spieler/252136.
Transfer history data appended for: https://www.transfermarkt.com/yongpo-wang/profil/spieler/50536.
Transfer history data appended for: https://www.transfermarkt.com/wei-qiao/profil/spieler/148183.
Transfer history data appended for: https://www.transfermarkt.com/yang-xu/profil/spieler/148185.
Transfer history data appended for: https://www.transfermarkt.com/yuan-zhang/profil/spieler/439768.
Transfer history data appended for: https://www.transfermarkt.com/john-mary/profil/spieler/354214.
Transfer history data appended for: https://www.transfermarkt.com/dyego-sousa/profil/spieler/157036.
Transfer history data appended for: https://www.transfermarkt.com/chao-gan/profil/spieler/269035.
Transfer history data appended for: https://www.transfermarkt.com/shuai-pei/profil/spieler/211424.
Transfer history data appended for: https://www.transfermarkt.com/harold-preciado/profil/spieler/362668.
Transfer history data appended for: https://www.transfermarkt.com/lu-zhang/profil/spieler/143771.
Transfer history data appended for: https://www.transfermarkt.com/xin-zhou/profil/spieler/525909.
Transfer history data appended for: https://www.transfermarkt.com/ju-hun-song/profil/spieler/261408.
Transfer history data appended for: https://www.transfermarkt.com/morteza-pouraliganji/profil/spieler/132563.
Transfer history data appended for: https://www.transfermarkt.com/yuan-zhang/profil/spieler/211066.
Transfer history data appended for: https://www.transfermarkt.com/haofeng-xu/profil/spieler/587423.
Transfer history data appended for: https://www.transfermarkt.com/yajun-zhou/profil/spieler/148193.
Transfer history data appended for: https://www.transfermarkt.com/dalun-zheng/profil/spieler/236686.
Transfer history data appended for: https://www.transfermarkt.com/haolun-mi/profil/spieler/236524.
Transfer history data appended for: https://www.transfermarkt.com/aloisio/profil/spieler/55246.
Transfer history data appended for: https://www.transfermarkt.com/tyias-browning/profil/spieler/156934.
Transfer history data appended for: https://www.transfermarkt.com/jianzhi-zhang/profil/spieler/690671.
Transfer history data appended for: https://www.transfermarkt.com/ji-soo-park/profil/spieler/260197.
Transfer history data appended for: https://www.transfermarkt.com/yiming-liu/profil/spieler/257394.
Transfer history data appended for: https://www.transfermarkt.com/xin-xu/profil/spieler/237852.
Transfer history data appended for: https://www.transfermarkt.com/liyu-yang/profil/spieler/439771.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-goulart/profil/spieler/106076.
Transfer history data appended for: https://www.transfermarkt.com/weiguo-liu/profil/spieler/218209.
Transfer history data appended for: https://www.transfermarkt.com/xuepeng-li/profil/spieler/151473.
Transfer history data appended for: https://www.transfermarkt.com/shilong-wang/profil/spieler/571410.
Transfer history data appended for: https://www.transfermarkt.com/shibo-liu/profil/spieler/363246.
Transfer history data appended for: https://www.transfermarkt.com/elkeson/profil/spieler/103588.
Transfer history data appended for: https://www.transfermarkt.com/talisca/profil/spieler/258626.
Transfer history data appended for: https://www.transfermarkt.com/dianzuo-liu/profil/spieler/211497.
Transfer history data appended for: https://www.transfermarkt.com/linpeng-zhang/profil/spieler/140437.
Transfer history data appended for: https://www.transfermarkt.com/dinghao-yan/profil/spieler/437947.
Transfer history data appended for: https://www.transfermarkt.com/paulinho/profil/spieler/57229.
Transfer history data appended for: https://www.transfermarkt.com/fang-mei/profil/spieler/236652.
Transfer history data appended for: https://www.transfermarkt.com/yihao-zhong/profil/spieler/317154.
Transfer history data appended for: https://www.transfermarkt.com/xiuwei-zhang/profil/spieler/293375.
Transfer history data appended for: https://www.transfermarkt.com/zhi-zheng/profil/spieler/21556.
Transfer history data appended for: https://www.transfermarkt.com/bughrahan-iskandar/profil/spieler/655793.
Transfer history data appended for: https://www.transfermarkt.com/hanwen-deng/profil/spieler/269033.
Transfer history data appended for: https://www.transfermarkt.com/shaocong-wu/profil/spieler/468283.
Transfer history data appended for: https://www.transfermarkt.com/lisheng-liao/profil/spieler/251910.
Transfer history data appended for: https://www.transfermarkt.com/kaiyuan-tan/profil/spieler/570167.
Transfer history data appended for: https://www.transfermarkt.com/fernandinho/profil/spieler/230937.
Transfer history data appended for: https://www.transfermarkt.com/parmanjan-kyum/profil/spieler/774057.
Transfer history data appended for: https://www.transfermarkt.com/bowen-huang/profil/spieler/134427.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-pallesen/profil/spieler/161368.
Transfer history data appended for: https://www.transfermarkt.com/andreas-hansen/profil/spieler/162101.
Transfer history data appended for: https://www.transfermarkt.com/robert-kakeeto/profil/spieler/369673.
Transfer history data appended for: https://www.transfermarkt.com/malthe-hojholt/profil/spieler/543822.
Transfer history data appended for: https://www.transfermarkt.com/jeppe-pedersen/profil/spieler/462831.
Transfer history data appended for: https://www.transfermarkt.com/lucas-andersen/profil/spieler/148344.

Transfer history data appended for: https://www.transfermarkt.com/tim-prica/profil/spieler/527347.
Transfer history data appended for: https://www.transfermarkt.com/iver-fossum/profil/spieler/226450.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-prijovic/profil/spieler/615597.
Transfer history data appended for: https://www.transfermarkt.com/timothe-nkada/profil/spieler/522788.
Transfer history data appended for: https://www.transfermarkt.com/frederik-borsting/profil/spieler/309414.
Transfer history data appended for: https://www.transfermarkt.com/magnus-christensen/profil/spieler/369675.
Transfer history data appended for: https://www.transfermarkt.com/thomas-christiansen/profil/spieler/462829.
Transfer history data appended for: https://www.transfermarkt.com/jacob-rinne/profil/spieler/210528.
Transfer history data appended for: https://www.transfermarkt.com/pedro-ferreira/profil/spieler/337799.
Transfer history data appended for: https://www.transfermarkt.com/kasper-pedersen/profil/spieler/261055.
Transfer history data appended for: https://www.transfermarkt.com/kasper-kusk/profil/spieler/102134.
Transfer history data appended for: https://www.transfermarkt.com/tom-van-weert/profil/spieler/95673.
Transfer history data appended for: https://www.transfermarkt.com/jores-okore/profil/spieler/129085.
Transfer history data appended for: https://www.transfermarkt.com/mathias-ross/profil/spieler/545331.
Transfer history data appended for: https://www.transfermarkt.com/jakob-ahlmann/profil/spieler/48803.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-thelander/profil/spieler/129092.
Transfer history data appended for: https://www.transfermarkt.com/lukas-klitten/profil/spieler/490842.
Transfer history data appended for: https://www.transfermarkt.com/daniel-granli/profil/spieler/266615.
Transfer history data appended for: https://www.transfermarkt.com/evander/profil/spieler/323874.
Transfer history data appended for: https://www.transfermarkt.com/lasse-vibe/profil/spieler/62680.
Transfer history data appended for: https://www.transfermarkt.com/gustav-isaksen/profil/spieler/462823.
Transfer history data appended for: https://www.transfermarkt.com/awer-mabil/profil/spieler/255729.
Transfer history data appended for: https://www.transfermarkt.com/oliver-olsen/profil/spieler/400542.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-andersen/profil/spieler/42694.
Transfer history data appended for: https://www.transfermarkt.com/japhet-sery/profil/spieler/403690.
Transfer history data appended for: https://www.transfermarkt.com/alexander-scholz/profil/spieler/153582.
Transfer history data appended for: https://www.transfermarkt.com/oliver-ottesen/profil/spieler/400708.
Transfer history data appended for: https://www.transfermarkt.com/paulinho/profil/spieler/520492.
Transfer history data appended for: https://www.transfermarkt.com/jens-cajuste/profil/spieler/468066.
Transfer history data appended for: https://www.transfermarkt.com/sory-kaba/profil/spieler/355689.
Transfer history data appended for: https://www.transfermarkt.com/kristian-dirks-riis/profil/spieler/288436.
Transfer history data appended for: https://www.transfermarkt.com/pione-sisto/profil/spieler/252641.
Transfer history data appended for: https://www.transfermarkt.com/chuma-anene/profil/spieler/136167.
Transfer history data appended for: https://www.transfermarkt.com/ronnie-schwartz/profil/spieler/46007.
Transfer history data appended for: https://www.transfermarkt.com/erik-sviatchenko/profil/spieler/48907.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-madsen/profil/spieler/464599.
Transfer history data appended for: https://www.transfermarkt.com/jibril-abubakar/profil/spieler/576967.
Transfer history data appended for: https://www.transfermarkt.com/luca-pfeiffer/profil/spieler/232463.
Transfer history data appended for: https://www.transfermarkt.com/joel-andersson/profil/spieler/255469.
Transfer history data appended for: https://www.transfermarkt.com/frank-onyeka/profil/spieler/421637.
Transfer history data appended for: https://www.transfermarkt.com/anders-dreyer/profil/spieler/342389.
Transfer history data appended for: https://www.transfermarkt.com/jesper-hansen/profil/spieler/22860.
Transfer history data appended for: https://www.transfermarkt.com/bozhidar-kraev/profil/spieler/293607.
Transfer history data appended for: https://www.transfermarkt.com/mikael-anderson/profil/spieler/403673.
Transfer history data appended for: https://www.transfermarkt.com/manjrekar-james/profil/spieler/222686.
Transfer history data appended for: https://www.transfermarkt.com/dion-cools/profil/spieler/316422.
Transfer history data appended for: https://www.transfermarkt.com/nikolas-dyhr/profil/spieler/462837.
Transfer history data appended for: https://www.transfermarkt.com/junior-brumado/profil/spieler/524590.
Transfer history data appended for: https://www.transfermarkt.com/daniel-hoegh/profil/spieler/99100.
Transfer history data appended for: https://www.transfermarkt.com/milan-jevtovic/profil/spieler/236895.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-lassen/profil/spieler/515016.
Transfer history data appended for: https://www.transfermarkt.com/patrick-mortensen/profil/spieler/69511.
Transfer history data appended for: https://www.transfermarkt.com/kamil-grabara/profil/spieler/346551.
Transfer history data appended for: https://www.transfermarkt.com/jon-dagur-thorsteinsson/profil/spieler/331739.
Transfer history data appended for: https://www.transfermarkt.com/gift-links/profil/spieler/445616.
Transfer history data appended for: https://www.transfermarkt.com/daniel-gadegaard-andersen/profil/spieler/492490.
Transfer history data appended for: https://www.transfermarkt.com/kasper-kristensen/profil/spieler/542680.
Transfer history data appended for: https://www.transfermarkt.com/nicolai-poulsen/profil/spieler/253210.
Transfer history data appended for: https://www.transfermarkt.com/alex-gersbach/profil/spieler/331017.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-hausner/profil/spieler/425808.
Transfer history data appended for: https://www.transfermarkt.com/frederik-tingager/profil/spieler/289683.
Transfer history data appended for: https://www.transfermarkt.com/zachary-duncan/profil/spieler/659848.
Transfer history data appended for: https://www.transfermarkt.com/alexander-munksgaard/profil/spieler/283225.
Transfer history data appended for: https://www.transfermarkt.com/albert-gronbaek/profil/spieler/503866.
Transfer history data appended for: https://www.transfermarkt.com/magnus-anbo/profil/spieler/542686.
Transfer history data appended for: https://www.transfermarkt.com/niklas-backman/profil/spieler/75453.
Transfer history data appended for: https://www.transfermarkt.com/kevin-diks/profil/spieler/335209.
Transfer history data appended for: https://www.transfermarkt.com/nicklas-helenius/profil/spieler/102132.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-amini/profil/spieler/138091.
Transfer history data appended for: https://www.transfermarkt.com/soren-tengstedt/profil/spieler/541601.
Transfer history data appended for: https://www.transfermarkt.com/william-eskelinen/profil/spieler/258970.
Transfer history data appended for: https://www.transfermarkt.com/jesper-juelsgaard/profil/spieler/20313.
Transfer history data appended for: https://www.transfermarkt.com/casper-hojer/profil/spieler/222977.
Transfer history data appended for: https://www.transfermarkt.com/bror-blume/profil/spieler/189044.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-hvidt/profil/spieler/400544.
Transfer history data appended for: https://www.transfermarkt.com/patrick-olsen/profil/spieler/135217.
Transfer history data appended for: https://www.transfermarkt.com/mads-albaek/profil/spieler/48805.
Transfer history data appended for: https://www.transfermarkt.com/ogenyi-onazi/profil/spieler/131709.
Transfer history data appended for: https://www.transfermarkt.com/mads-winther/profil/spieler/599677.
Transfer history data appended for: https://www.transfermarkt.com/philipp-schmiedl/profil/spieler/246063.

Transfer history data appended for: https://www.transfermarkt.com/haji-wright/profil/spieler/315291.
Transfer history data appended for: https://www.transfermarkt.com/alexander-bah/profil/spieler/452607.
Transfer history data appended for: https://www.transfermarkt.com/patrick-banggaard/profil/spieler/186557.
Transfer history data appended for: https://www.transfermarkt.com/marc-dal-hende/profil/spieler/126610.
Transfer history data appended for: https://www.transfermarkt.com/roni-arabaci/profil/spieler/584087.
Transfer history data appended for: https://www.transfermarkt.com/jannick-liburd/profil/spieler/610603.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-vinderslev/profil/spieler/495488.
Transfer history data appended for: https://www.transfermarkt.com/nicolai-flo/profil/spieler/242750.
Transfer history data appended for: https://www.transfermarkt.com/julius-eskesen/profil/spieler/345584.
Transfer history data appended for: https://www.transfermarkt.com/stefan-gartenmann/profil/spieler/243770.
Transfer history data appended for: https://www.transfermarkt.com/pierre-kanstrup/profil/spieler/68976.
Transfer history data appended for: https://www.transfermarkt.com/peter-christiansen/profil/spieler/542462.
Transfer history data appended for: https://www.transfermarkt.com/mads-hansen/profil/spieler/503867.
Transfer history data appended for: https://www.transfermarkt.com/jeppe-simonsen/profil/spieler/331975.
Transfer history data appended for: https://www.transfermarkt.com/isak-oli-olafsson/profil/spieler/472866.
Transfer history data appended for: https://www.transfermarkt.com/emil-frederiksen/profil/spieler/422941.
Transfer history data appended for: https://www.transfermarkt.com/johan-absalonsen/profil/spieler/22831.
Transfer history data appended for: https://www.transfermarkt.com/lawrence-thomas/profil/spieler/181337.
Transfer history data appended for: https://www.transfermarkt.com/rilwan-hassan/profil/spieler/140446.
Transfer history data appended for: https://www.transfermarkt.com/anders-jacobsen/profil/spieler/44726.
Transfer history data appended for: https://www.transfermarkt.com/victor-ekani/profil/spieler/489716.
Transfer history data appended for: https://www.transfermarkt.com/mads-steenberg/profil/spieler/599678.
Transfer history data appended for: https://www.transfermarkt.com/anton-skipper/profil/spieler/400538.
Transfer history data appended for: https://www.transfermarkt.com/mikael-uhre/profil/spieler/264423.
Transfer history data appended for: https://www.transfermarkt.com/tobias-borkeeiet/profil/spieler/458537.
Transfer history data appended for: https://www.transfermarkt.com/joel-kabongo/profil/spieler/277236.
Transfer history data appended for: https://www.transfermarkt.com/simon-hedlund/profil/spieler/116900.
Transfer history data appended for: https://www.transfermarkt.com/sigurd-rosted/profil/spieler/230336.
Transfer history data appended for: https://www.transfermarkt.com/andreas-pyndt/profil/spieler/482102.
Transfer history data appended for: https://www.transfermarkt.com/hjortur-hermannsson/profil/spieler/187147.
Transfer history data appended for: https://www.transfermarkt.com/kevin-mensah/profil/spieler/68983.
Transfer history data appended for: https://www.transfermarkt.com/andrija-pavlovic/profil/spieler/188131.
Transfer history data appended for: https://www.transfermarkt.com/andreas-maxso/profil/spieler/253206.
Transfer history data appended for: https://www.transfermarkt.com/anis-slimane/profil/spieler/546712.
Transfer history data appended for: https://www.transfermarkt.com/rezan-corlu/profil/spieler/283193.
Transfer history data appended for: https://www.transfermarkt.com/andreas-bruus/profil/spieler/345748.
Transfer history data appended for: https://www.transfermarkt.com/marvin-schwabe/profil/spieler/160929.
Transfer history data appended for: https://www.transfermarkt.com/lasse-vigen/profil/spieler/148376.
Transfer history data appended for: https://www.transfermarkt.com/mads-hermansen/profil/spieler/400536.
Transfer history data appended for: https://www.transfermarkt.com/morten-frendrup/profil/spieler/503871.
Transfer history data appended for: https://www.transfermarkt.com/peter-bjur/profil/spieler/482110.
Transfer history data appended for: https://www.transfermarkt.com/michael-tornes/profil/spieler/43075.
Transfer history data appended for: https://www.transfermarkt.com/mathias-kvistgaarden/profil/spieler/569663.
Transfer history data appended for: https://www.transfermarkt.com/blas-riveros/profil/spieler/401732.
Transfer history data appended for: https://www.transfermarkt.com/jesper-lindstrom/profil/spieler/513245.
Transfer history data appended for: https://www.transfermarkt.com/anthony-jung/profil/spieler/58995.
Transfer history data appended for: https://www.transfermarkt.com/aron-elis-thrandarson/profil/spieler/178926.
Transfer history data appended for: https://www.transfermarkt.com/ayo-simon-okosun/profil/spieler/173040.
Transfer history data appended for: https://www.transfermarkt.com/kasper-larsen/profil/spieler/95759.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-nissen/profil/spieler/602487.
Transfer history data appended for: https://www.transfermarkt.com/janus-drachmann/profil/spieler/50580.
Transfer history data appended for: https://www.transfermarkt.com/daniel-obbekjaer/profil/spieler/579809.
Transfer history data appended for: https://www.transfermarkt.com/jeppe-tverskov/profil/spieler/257324.
Transfer history data appended for: https://www.transfermarkt.com/mads-frokjaer/profil/spieler/533632.
Transfer history data appended for: https://www.transfermarkt.com/jorgen-skjelvik/profil/spieler/112336.
Transfer history data appended for: https://www.transfermarkt.com/hans-christian-bernat/profil/spieler/400535.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-sabbi/profil/spieler/381187.
Transfer history data appended for: https://www.transfermarkt.com/moses-opondo/profil/spieler/369678.
Transfer history data appended for: https://www.transfermarkt.com/oliver-lund/profil/spieler/71701.
Transfer history data appended for: https://www.transfermarkt.com/sveinn-aron-gudjohnsen/profil/spieler/332527.
Transfer history data appended for: https://www.transfermarkt.com/jens-thomasen/profil/spieler/260848.
Transfer history data appended for: https://www.transfermarkt.com/tarik-ibrahimagic/profil/spieler/602486.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-hyllegaard/profil/spieler/694974.
Transfer history data appended for: https://www.transfermarkt.com/alexander-juel-andersen/profil/spieler/63459.
Transfer history data appended for: https://www.transfermarkt.com/mande-sayouba/profil/spieler/222124.
Transfer history data appended for: https://www.transfermarkt.com/marco-lund/profil/spieler/293324.
Transfer history data appended for: https://www.transfermarkt.com/ryan-laursen/profil/spieler/157626.
Transfer history data appended for: https://www.transfermarkt.com/oliver-christensen/profil/spieler/471936.
Transfer history data appended for: https://www.transfermarkt.com/mart-lieder/profil/spieler/211331.
Transfer history data appended for: https://www.transfermarkt.com/troels-klove/profil/spieler/103434.
Transfer history data appended for: https://www.transfermarkt.com/christian-vestergaard/profil/spieler/492489.
Transfer history data appended for: https://www.transfermarkt.com/max-fenger/profil/spieler/578920.
Transfer history data appended for: https://www.transfermarkt.com/adam-sorensen/profil/spieler/400537.
Transfer history data appended for: https://www.transfermarkt.com/christian-jakobsen/profil/spieler/256186.
Transfer history data appended for: https://www.transfermarkt.com/filip-panjeskovic/profil/spieler/610403.
Transfer history data appended for: https://www.transfermarkt.com/jens-martin-gammelby/profil/spieler/265040.
Transfer history data appended for: https://www.transfermarkt.com/mathias-hebo-rasmussen/profil/spieler/311438.
Transfer history data appended for: https://www.transfermarkt.com/casper-winther/profil/spieler/627936.
Transfer history data appended for: https://www.transfermarkt.com/frederik-gytkjaer/profil/spieler/72402.

Transfer history data appended for: https://www.transfermarkt.com/emil-kornvig/profil/spieler/455068.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-thellufsen/profil/spieler/283231.
Transfer history data appended for: https://www.transfermarkt.com/victor-torp/profil/spieler/403692.
Transfer history data appended for: https://www.transfermarkt.com/ertugrul-teksen/profil/spieler/411646.
Transfer history data appended for: https://www.transfermarkt.com/emil-nielsen/profil/spieler/164647.
Transfer history data appended for: https://www.transfermarkt.com/frederik-winther/profil/spieler/569349.
Transfer history data appended for: https://www.transfermarkt.com/andre-riel/profil/spieler/70567.
Transfer history data appended for: https://www.transfermarkt.com/brian-hamalainen/profil/spieler/61336.
Transfer history data appended for: https://www.transfermarkt.com/marcel-romer/profil/spieler/107266.
Transfer history data appended for: https://www.transfermarkt.com/kevin-tshiembe/profil/spieler/387745.
Transfer history data appended for: https://www.transfermarkt.com/nicolai-geertsen/profil/spieler/157912.
Transfer history data appended for: https://www.transfermarkt.com/thomas-mikkelsen/profil/spieler/23523.
Transfer history data appended for: https://www.transfermarkt.com/magnus-warming/profil/spieler/482107.
Transfer history data appended for: https://www.transfermarkt.com/kasper-enghardt/profil/spieler/201427.
Transfer history data appended for: https://www.transfermarkt.com/lasse-fosgaard/profil/spieler/86310.
Transfer history data appended for: https://www.transfermarkt.com/frederik-schram/profil/spieler/279338.
Transfer history data appended for: https://www.transfermarkt.com/pascal-gregor/profil/spieler/253664.
Transfer history data appended for: https://www.transfermarkt.com/jens-stage/profil/spieler/289835.
Transfer history data appended for: https://www.transfermarkt.com/pierre-bengtsson/profil/spieler/50577.
Transfer history data appended for: https://www.transfermarkt.com/alexander-hjaelmhof/profil/spieler/515015.
Transfer history data appended for: https://www.transfermarkt.com/ragnar-sigurdsson/profil/spieler/46478.
Transfer history data appended for: https://www.transfermarkt.com/viktor-fischer/profil/spieler/95755.
Transfer history data appended for: https://www.transfermarkt.com/victor-nelsson/profil/spieler/422951.
Transfer history data appended for: https://www.transfermarkt.com/karlo-bartolec/profil/spieler/291947.
Transfer history data appended for: https://www.transfermarkt.com/andreas-bjelland/profil/spieler/56354.
Transfer history data appended for: https://www.transfermarkt.com/stephan-andersen/profil/spieler/17880.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-falk/profil/spieler/89200.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-kaufmann/profil/spieler/545332.
Transfer history data appended for: https://www.transfermarkt.com/kamil-wilczek/profil/spieler/78590.
Transfer history data appended for: https://www.transfermarkt.com/peter-ankersen/profil/spieler/146889.
Transfer history data appended for: https://www.transfermarkt.com/karl-johan-johnsson/profil/spieler/112822.
Transfer history data appended for: https://www.transfermarkt.com/sten-grytebust/profil/spieler/73417.
Transfer history data appended for: https://www.transfermarkt.com/zanka/profil/spieler/52059.
Transfer history data appended for: https://www.transfermarkt.com/zeca/profil/spieler/131161.
Transfer history data appended for: https://www.transfermarkt.com/pep-biel/profil/spieler/263804.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-daramy/profil/spieler/574385.
Transfer history data appended for: https://www.transfermarkt.com/bryan-oviedo/profil/spieler/124983.
Transfer history data appended for: https://www.transfermarkt.com/jonas-wind/profil/spieler/391004.
Transfer history data appended for: https://www.transfermarkt.com/nicolai-boilesen/profil/spieler/69642.
Transfer history data appended for: https://www.transfermarkt.com/nicolaj-thomsen/profil/spieler/201497.
Transfer history data appended for: https://www.transfermarkt.com/robert-mudrazija/profil/spieler/339584.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-sadiq/profil/spieler/543501.
Transfer history data appended for: https://www.transfermarkt.com/tochi-chukwuani/profil/spieler/553328.
Transfer history data appended for: https://www.transfermarkt.com/oliver-villadsen/profil/spieler/462838.
Transfer history data appended for: https://www.transfermarkt.com/isaac-atanga/profil/spieler/599686.
Transfer history data appended for: https://www.transfermarkt.com/joachim-rothmann/profil/spieler/455069.
Transfer history data appended for: https://www.transfermarkt.com/martin-frese/profil/spieler/488785.
Transfer history data appended for: https://www.transfermarkt.com/gideon-mensah/profil/spieler/543496.
Transfer history data appended for: https://www.transfermarkt.com/mads-thychosen/profil/spieler/281252.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-rygaard/profil/spieler/51349.
Transfer history data appended for: https://www.transfermarkt.com/ulrik-jenssen/profil/spieler/239044.
Transfer history data appended for: https://www.transfermarkt.com/martin-vantruba/profil/spieler/415529.
Transfer history data appended for: https://www.transfermarkt.com/andreas-gulstorff/profil/spieler/610423.
Transfer history data appended for: https://www.transfermarkt.com/kian-hansen/profil/spieler/91469.
Transfer history data appended for: https://www.transfermarkt.com/maxwell-woledzi/profil/spieler/658529.
Transfer history data appended for: https://www.transfermarkt.com/oliver-antman/profil/spieler/527896.
Transfer history data appended for: https://www.transfermarkt.com/magnus-kofod-andersen/profil/spieler/488784.
Transfer history data appended for: https://www.transfermarkt.com/kamaldeen-sulemana/profil/spieler/746695.
Transfer history data appended for: https://www.transfermarkt.com/emeka-nnamani/profil/spieler/564453.
Transfer history data appended for: https://www.transfermarkt.com/peter-vindahl/profil/spieler/395421.
Transfer history data appended for: https://www.transfermarkt.com/oliver-rimmen/profil/spieler/462839.
Transfer history data appended for: https://www.transfermarkt.com/jacob-christensen/profil/spieler/515017.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-diomande/profil/spieler/658531.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-amon/profil/spieler/542776.
Transfer history data appended for: https://www.transfermarkt.com/ivan-mesik/profil/spieler/482838.
Transfer history data appended for: https://www.transfermarkt.com/abu-francis/profil/spieler/658533.
Transfer history data appended for: https://www.transfermarkt.com/andreas-bredahl/profil/spieler/610427.
Transfer history data appended for: https://www.transfermarkt.com/emmerson/profil/spieler/213429.
Transfer history data appended for: https://www.transfermarkt.com/diego-montiel/profil/spieler/220441.
Transfer history data appended for: https://www.transfermarkt.com/luis-henrique/profil/spieler/379877.
Transfer history data appended for: https://www.transfermarkt.com/malte-amundsen/profil/spieler/363466.
Transfer history data appended for: https://www.transfermarkt.com/saeid-ezatolahi/profil/spieler/249271.
Transfer history data appended for: https://www.transfermarkt.com/mads-greve/profil/spieler/95014.
Transfer history data appended for: https://www.transfermarkt.com/raphael-dwamena/profil/spieler/254290.
Transfer history data appended for: https://www.transfermarkt.com/indy-groothuizen/profil/spieler/241389.
Transfer history data appended for: https://www.transfermarkt.com/lundrim-hetemi/profil/spieler/527467.
Transfer history data appended for: https://www.transfermarkt.com/viljormur-davidsen/profil/spieler/102123.
Transfer history data appended for: https://www.transfermarkt.com/lucas-chang-andersen/profil/spieler/491389.
Transfer history data appended for: https://www.transfermarkt.com/wahid-faghir/profil/spieler/610431.
Transfer history data appended for: https://www.transfermarkt.com/arbnor-mucolli/profil/spieler/467232.

Transfer history data appended for: https://www.transfermarkt.com/allan-sousa/profil/spieler/423197.
Transfer history data appended for: https://www.transfermarkt.com/thomas-gundelund/profil/spieler/482106.
Transfer history data appended for: https://www.transfermarkt.com/ivan-repyakh/profil/spieler/430487.
Transfer history data appended for: https://www.transfermarkt.com/leonel-montano/profil/spieler/491391.
Transfer history data appended for: https://www.transfermarkt.com/lucas-jensen/profil/spieler/213265.
Transfer history data appended for: https://www.transfermarkt.com/jacob-schoop/profil/spieler/70544.
Transfer history data appended for: https://www.transfermarkt.com/matthew-briggs/profil/spieler/51318.
Transfer history data appended for: https://www.transfermarkt.com/ylber-ramadani/profil/spieler/442703.
Transfer history data appended for: https://www.transfermarkt.com/alexander-brunst/profil/spieler/146693.
Transfer history data appended for: https://www.transfermarkt.com/tobias-molgaard/profil/spieler/341466.
Transfer history data appended for: https://www.transfermarkt.com/kevin-yamga/profil/spieler/290768.
Transfer history data appended for: https://www.transfermarkt.com/juhani-ojala/profil/spieler/88257.
Transfer history data appended for: https://www.transfermarkt.com/lirim-qamili/profil/spieler/523965.
Transfer history data appended for: https://www.transfermarkt.com/bjarke-jacobsen/profil/spieler/239987.
Transfer history data appended for: https://www.transfermarkt.com/rune-frantsen/profil/spieler/186486.
Transfer history data appended for: https://www.transfermarkt.com/james-gomez/profil/spieler/689634.
Transfer history data appended for: https://www.transfermarkt.com/agust-hlynsson/profil/spieler/396936.
Transfer history data appended for: https://www.transfermarkt.com/nicolai-brock-madsen/profil/spieler/154051.
Transfer history data appended for: https://www.transfermarkt.com/kjartan-finnbogason/profil/spieler/29392.
Transfer history data appended for: https://www.transfermarkt.com/jacob-buus/profil/spieler/321851.
Transfer history data appended for: https://www.transfermarkt.com/casper-tengstedt/profil/spieler/464598.
Transfer history data appended for: https://www.transfermarkt.com/mathias-madsen/profil/spieler/554198.
Transfer history data appended for: https://www.transfermarkt.com/magnus-jensen/profil/spieler/448471.
Transfer history data appended for: https://www.transfermarkt.com/muamer-brajanac/profil/spieler/462819.
Transfer history data appended for: https://www.transfermarkt.com/matej-delac/profil/spieler/60220.
Transfer history data appended for: https://www.transfermarkt.com/jannik-pohl/profil/spieler/288432.
Transfer history data appended for: https://www.transfermarkt.com/hallur-hansson/profil/spieler/95984.
Transfer history data appended for: https://www.transfermarkt.com/anders-hoff/profil/spieler/673976.
Transfer history data appended for: https://www.transfermarkt.com/thor-lange/profil/spieler/234183.
Transfer history data appended for: https://www.transfermarkt.com/peter-nymann/profil/spieler/23076.
Transfer history data appended for: https://www.transfermarkt.com/malte-kiilerich/profil/spieler/312712.
Transfer history data appended for: https://www.transfermarkt.com/louka-prip/profil/spieler/388465.
Transfer history data appended for: https://www.transfermarkt.com/michael-lansing/profil/spieler/448696.
Transfer history data appended for: https://www.transfermarkt.com/jonas-gemmer/profil/spieler/260838.
Transfer history data appended for: https://www.transfermarkt.com/jonas-thorsen/profil/spieler/94295.
Transfer history data appended for: https://www.transfermarkt.com/andreas-foged/profil/spieler/583585.
Transfer history data appended for: https://www.transfermarkt.com/david-kruse/profil/spieler/569654.
Transfer history data appended for: https://www.transfermarkt.com/jacob-trenskow/profil/spieler/542684.
Transfer history data appended for: https://www.transfermarkt.com/alexander-ludwig/profil/spieler/184534.
Transfer history data appended for: https://www.transfermarkt.com/christoffer-petersen/profil/spieler/462830.
Transfer history data appended for: https://www.transfermarkt.com/tosin-kehinde/profil/spieler/316750.
Transfer history data appended for: https://www.transfermarkt.com/mads-enggaard/profil/spieler/752778.
Transfer history data appended for: https://www.transfermarkt.com/karl-leth/profil/spieler/671847.
Transfer history data appended for: https://www.transfermarkt.com/bjorn-kopplin/profil/spieler/45666.
Transfer history data appended for: https://www.transfermarkt.com/erik-marxen/profil/spieler/94293.
Transfer history data appended for: https://www.transfermarkt.com/marvin-egho/profil/spieler/274984.
Transfer history data appended for: https://www.transfermarkt.com/mathias-nielsen/profil/spieler/147112.
Transfer history data appended for: https://www.transfermarkt.com/frederik-lauenborg/profil/spieler/320272.
Transfer history data appended for: https://www.transfermarkt.com/nikola-mileusnic/profil/spieler/285775.
Transfer history data appended for: https://www.transfermarkt.com/filip-bundgaard/profil/spieler/685145.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-kallesoe/profil/spieler/293134.
Transfer history data appended for: https://www.transfermarkt.com/oliver-bundgaard/profil/spieler/566571.
Transfer history data appended for: https://www.transfermarkt.com/jonas-dakir/profil/spieler/464983.
Transfer history data appended for: https://www.transfermarkt.com/mathias-greve/profil/spieler/237436.
Transfer history data appended for: https://www.transfermarkt.com/simon-graves/profil/spieler/542858.
Transfer history data appended for: https://www.transfermarkt.com/jesper-lauridsen/profil/spieler/48864.
Transfer history data appended for: https://www.transfermarkt.com/issah-salou/profil/spieler/649287.
Transfer history data appended for: https://www.transfermarkt.com/bassala-sambou/profil/spieler/406924.
Transfer history data appended for: https://www.transfermarkt.com/simon-piesinger/profil/spieler/89541.
Transfer history data appended for: https://www.transfermarkt.com/andre-romer/profil/spieler/218085.
Transfer history data appended for: https://www.transfermarkt.com/vito-hammershoy-mistrati/profil/spieler/193724.
Transfer history data appended for: https://www.transfermarkt.com/patrik-carlgren/profil/spieler/190280.
Transfer history data appended for: https://www.transfermarkt.com/tobias-klysner/profil/spieler/525990.
Transfer history data appended for: https://www.transfermarkt.com/edgar-badia/profil/spieler/102146.
Transfer history data appended for: https://www.transfermarkt.com/luismi/profil/spieler/207922.
Transfer history data appended for: https://www.transfermarkt.com/pere-milla/profil/spieler/225593.
Transfer history data appended for: https://www.transfermarkt.com/ivan-marcone/profil/spieler/90451.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-verdu/profil/spieler/184779.
Transfer history data appended for: https://www.transfermarkt.com/omenuke-mfulu/profil/spieler/203516.
Transfer history data appended for: https://www.transfermarkt.com/guido-carrillo/profil/spieler/184672.
Transfer history data appended for: https://www.transfermarkt.com/victor-rodriguez/profil/spieler/129753.
Transfer history data appended for: https://www.transfermarkt.com/diego-rodriguez/profil/spieler/90800.
Transfer history data appended for: https://www.transfermarkt.com/antonio-barragan/profil/spieler/32522.
Transfer history data appended for: https://www.transfermarkt.com/jeison-lucumi/profil/spieler/352567.
Transfer history data appended for: https://www.transfermarkt.com/nino/profil/spieler/29178.
Transfer history data appended for: https://www.transfermarkt.com/josema/profil/spieler/255892.
Transfer history data appended for: https://www.transfermarkt.com/fidel/profil/spieler/149231.
Transfer history data appended for: https://www.transfermarkt.com/youssouf-kone/profil/spieler/274484.
Transfer history data appended for: https://www.transfermarkt.com/raul-guti/profil/spieler/330352.
Transfer history data appended for: https://www.transfermarkt.com/juan-sanchez-mino/profil/spieler/169249.

Transfer history data appended for: https://www.transfermarkt.com/diego-gonzalez/profil/spieler/349836.
Transfer history data appended for: https://www.transfermarkt.com/dani-calvo/profil/spieler/326416.
Transfer history data appended for: https://www.transfermarkt.com/josan/profil/spieler/277533.
Transfer history data appended for: https://www.transfermarkt.com/tete-morente/profil/spieler/339816.
Transfer history data appended for: https://www.transfermarkt.com/ivo-grbic/profil/spieler/226073.
Transfer history data appended for: https://www.transfermarkt.com/mario-hermoso/profil/spieler/281769.
Transfer history data appended for: https://www.transfermarkt.com/marcos-llorente/profil/spieler/282411.
Transfer history data appended for: https://www.transfermarkt.com/diego-costa/profil/spieler/44779.
Transfer history data appended for: https://www.transfermarkt.com/joao-felix/profil/spieler/462250.
Transfer history data appended for: https://www.transfermarkt.com/lucas-torreira/profil/spieler/318077.
Transfer history data appended for: https://www.transfermarkt.com/vitolo/profil/spieler/67082.
Transfer history data appended for: https://www.transfermarkt.com/ricard-sanchez/profil/spieler/388545.
Transfer history data appended for: https://www.transfermarkt.com/hector-herrera/profil/spieler/122043.
Transfer history data appended for: https://www.transfermarkt.com/manu-sanchez/profil/spieler/618809.
Transfer history data appended for: https://www.transfermarkt.com/ivan-saponjic/profil/spieler/274347.
Transfer history data appended for: https://www.transfermarkt.com/miguel-san-roman/profil/spieler/396337.
Transfer history data appended for: https://www.transfermarkt.com/sime-vrsaljko/profil/spieler/76061.
Transfer history data appended for: https://www.transfermarkt.com/geoffrey-kondogbia/profil/spieler/127189.
Transfer history data appended for: https://www.transfermarkt.com/yannick-carrasco/profil/spieler/140776.
Transfer history data appended for: https://www.transfermarkt.com/saul-niguez/profil/spieler/148928.
Transfer history data appended for: https://www.transfermarkt.com/angel-correa/profil/spieler/266807.
Transfer history data appended for: https://www.transfermarkt.com/jan-oblak/profil/spieler/121483.
Transfer history data appended for: https://www.transfermarkt.com/stefan-savic/profil/spieler/107010.
Transfer history data appended for: https://www.transfermarkt.com/koke/profil/spieler/74229.
Transfer history data appended for: https://www.transfermarkt.com/luis-suarez/profil/spieler/44352.
Transfer history data appended for: https://www.transfermarkt.com/renan-lodi/profil/spieler/476352.
Transfer history data appended for: https://www.transfermarkt.com/thomas-lemar/profil/spieler/205562.
Transfer history data appended for: https://www.transfermarkt.com/jose-gimenez/profil/spieler/250845.
Transfer history data appended for: https://www.transfermarkt.com/felipe/profil/spieler/156501.
Transfer history data appended for: https://www.transfermarkt.com/kieran-trippier/profil/spieler/95810.
Transfer history data appended for: https://www.transfermarkt.com/ander-guevara/profil/spieler/465967.
Transfer history data appended for: https://www.transfermarkt.com/adnan-januzaj/profil/spieler/177847.
Transfer history data appended for: https://www.transfermarkt.com/martin-merquelanz/profil/spieler/289272.
Transfer history data appended for: https://www.transfermarkt.com/mikel-oyarzabal/profil/spieler/351478.
Transfer history data appended for: https://www.transfermarkt.com/alex-remiro/profil/spieler/212862.
Transfer history data appended for: https://www.transfermarkt.com/jon-bautista/profil/spieler/289236.
Transfer history data appended for: https://www.transfermarkt.com/aihen-munoz/profil/spieler/517842.
Transfer history data appended for: https://www.transfermarkt.com/jon-guridi/profil/spieler/289257.
Transfer history data appended for: https://www.transfermarkt.com/portu/profil/spieler/99353.
Transfer history data appended for: https://www.transfermarkt.com/mikel-merino/profil/spieler/338424.
Transfer history data appended for: https://www.transfermarkt.com/robin-le-normand/profil/spieler/351809.
Transfer history data appended for: https://www.transfermarkt.com/aritz-elustondo/profil/spieler/229804.
Transfer history data appended for: https://www.transfermarkt.com/joseba-zaldua/profil/spieler/197135.
Transfer history data appended for: https://www.transfermarkt.com/ander-barrenetxea/profil/spieler/616369.
Transfer history data appended for: https://www.transfermarkt.com/willian-jose/profil/spieler/122155.
Transfer history data appended for: https://www.transfermarkt.com/nacho-monreal/profil/spieler/43003.
Transfer history data appended for: https://www.transfermarkt.com/igor-zubeldia/profil/spieler/355628.
Transfer history data appended for: https://www.transfermarkt.com/asier-illarramendi/profil/spieler/59344.
Transfer history data appended for: https://www.transfermarkt.com/luca-sangalli/profil/spieler/289286.
Transfer history data appended for: https://www.transfermarkt.com/andoni-gorosabel/profil/spieler/289255.
Transfer history data appended for: https://www.transfermarkt.com/roberto-lopez/profil/spieler/569866.
Transfer history data appended for: https://www.transfermarkt.com/david-silva/profil/spieler/35518.
Transfer history data appended for: https://www.transfermarkt.com/miguel-angel-moya/profil/spieler/26065.
Transfer history data appended for: https://www.transfermarkt.com/alex-sola/profil/spieler/434990.
Transfer history data appended for: https://www.transfermarkt.com/alexander-isak/profil/spieler/349066.
Transfer history data appended for: https://www.transfermarkt.com/martin-zubimendi/profil/spieler/423440.
Transfer history data appended for: https://www.transfermarkt.com/modibo-sagnan/profil/spieler/524925.
Transfer history data appended for: https://www.transfermarkt.com/kenan-kodro/profil/spieler/197126.
Transfer history data appended for: https://www.transfermarkt.com/oscar-de-marcos/profil/spieler/96718.
Transfer history data appended for: https://www.transfermarkt.com/inigo-cordoba/profil/spieler/251848.
Transfer history data appended for: https://www.transfermarkt.com/unai-simon/profil/spieler/262396.
Transfer history data appended for: https://www.transfermarkt.com/mikel-balenziaga/profil/spieler/85258.
Transfer history data appended for: https://www.transfermarkt.com/iago-herrerin/profil/spieler/71570.
Transfer history data appended for: https://www.transfermarkt.com/inigo-martinez/profil/spieler/158863.
Transfer history data appended for: https://www.transfermarkt.com/inigo-lekue/profil/spieler/255501.
Transfer history data appended for: https://www.transfermarkt.com/asier-villalibre/profil/spieler/251897.
Transfer history data appended for: https://www.transfermarkt.com/ibai-gomez/profil/spieler/127837.
Transfer history data appended for: https://www.transfermarkt.com/yuri-berchiche/profil/spieler/61812.
Transfer history data appended for: https://www.transfermarkt.com/unai-lopez/profil/spieler/192009.
Transfer history data appended for: https://www.transfermarkt.com/yeray-alvarez/profil/spieler/255488.
Transfer history data appended for: https://www.transfermarkt.com/inigo-vicente/profil/spieler/335216.
Transfer history data appended for: https://www.transfermarkt.com/peru-nolaskoain/profil/spieler/447052.
Transfer history data appended for: https://www.transfermarkt.com/mikel-vesga/profil/spieler/300168.
Transfer history data appended for: https://www.transfermarkt.com/inaki-williams/profil/spieler/255508.
Transfer history data appended for: https://www.transfermarkt.com/raul-garcia/profil/spieler/34601.
Transfer history data appended for: https://www.transfermarkt.com/oier-zarraga/profil/spieler/524010.
Transfer history data appended for: https://www.transfermarkt.com/alex-berenguer/profil/spieler/338425.
Transfer history data appended for: https://www.transfermarkt.com/jon-morcillo/profil/spieler/455349.
Transfer history data appended for: https://www.transfermarkt.com/ander-capa/profil/spieler/197545.
Transfer history data appended for: https://www.transfermarkt.com/unai-nunez/profil/spieler/338285.
Transfer history data appended for: https://www.transfermarkt.com/jokin-ezkieta/profil/spieler/379548.

Transfer history data appended for: https://www.transfermarkt.com/oihan-sancet/profil/spieler/571020.
Transfer history data appended for: https://www.transfermarkt.com/iker-muniain/profil/spieler/54235.
Transfer history data appended for: https://www.transfermarkt.com/dani-garcia/profil/spieler/178425.
Transfer history data appended for: https://www.transfermarkt.com/unai-vencedor/profil/spieler/610083.
Transfer history data appended for: https://www.transfermarkt.com/dario-poveda/profil/spieler/399780.
Transfer history data appended for: https://www.transfermarkt.com/ruben-yanez/profil/spieler/246335.
Transfer history data appended for: https://www.transfermarkt.com/angel-rodriguez/profil/spieler/51510.
Transfer history data appended for: https://www.transfermarkt.com/francisco-portillo/profil/spieler/138803.
Transfer history data appended for: https://www.transfermarkt.com/david-timor/profil/spieler/158795.
Transfer history data appended for: https://www.transfermarkt.com/mauro-arambarri/profil/spieler/290249.
Transfer history data appended for: https://www.transfermarkt.com/djene/profil/spieler/221150.
Transfer history data appended for: https://www.transfermarkt.com/abdoulay-diaby/profil/spieler/148396.
Transfer history data appended for: https://www.transfermarkt.com/damian-suarez/profil/spieler/76746.
Transfer history data appended for: https://www.transfermarkt.com/leandro-chichizola/profil/spieler/95736.
Transfer history data appended for: https://www.transfermarkt.com/cucho-hernandez/profil/spieler/459463.
Transfer history data appended for: https://www.transfermarkt.com/jaime-mata/profil/spieler/227961.
Transfer history data appended for: https://www.transfermarkt.com/david-soria/profil/spieler/226012.
Transfer history data appended for: https://www.transfermarkt.com/ante-palaversa/profil/spieler/371003.
Transfer history data appended for: https://www.transfermarkt.com/allan-nyom/profil/spieler/111508.
Transfer history data appended for: https://www.transfermarkt.com/marc-cucurella/profil/spieler/284857.
Transfer history data appended for: https://www.transfermarkt.com/chema/profil/spieler/248330.
Transfer history data appended for: https://www.transfermarkt.com/xabi-etxeita/profil/spieler/71559.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-maksimovic/profil/spieler/273152.
Transfer history data appended for: https://www.transfermarkt.com/victor-mollejo/profil/spieler/505673.
Transfer history data appended for: https://www.transfermarkt.com/enes-unal/profil/spieler/251106.
Transfer history data appended for: https://www.transfermarkt.com/mathi-shy-as-olivera/profil/spieler/376514.
Transfer history data appended for: https://www.transfermarkt.com/alberto-soro/profil/spieler/487688.
Transfer history data appended for: https://www.transfermarkt.com/luis-suarez/profil/spieler/424784.
Transfer history data appended for: https://www.transfermarkt.com/jesus-vallejo/profil/spieler/251896.
Transfer history data appended for: https://www.transfermarkt.com/fede-vico/profil/spieler/162079.
Transfer history data appended for: https://www.transfermarkt.com/victor-diaz/profil/spieler/58330.
Transfer history data appended for: https://www.transfermarkt.com/aaron-escandell/profil/spieler/284430.
Transfer history data appended for: https://www.transfermarkt.com/angel-montoro/profil/spieler/59551.
Transfer history data appended for: https://www.transfermarkt.com/german-sanchez/profil/spieler/95963.
Transfer history data appended for: https://www.transfermarkt.com/carlos-neva/profil/spieler/448844.
Transfer history data appended for: https://www.transfermarkt.com/neyder-lozano/profil/spieler/468700.
Transfer history data appended for: https://www.transfermarkt.com/luis-milla/profil/spieler/281989.
Transfer history data appended for: https://www.transfermarkt.com/jorge-molina/profil/spieler/57825.
Transfer history data appended for: https://www.transfermarkt.com/maxime-gonalons/profil/spieler/60542.
Transfer history data appended for: https://www.transfermarkt.com/rui-silva/profil/spieler/234811.
Transfer history data appended for: https://www.transfermarkt.com/kenedy/profil/spieler/281404.
Transfer history data appended for: https://www.transfermarkt.com/nehuen-perez/profil/spieler/491693.
Transfer history data appended for: https://www.transfermarkt.com/quini/profil/spieler/223053.
Transfer history data appended for: https://www.transfermarkt.com/ramon-azeez/profil/spieler/131667.
Transfer history data appended for: https://www.transfermarkt.com/roberto-soldado/profil/spieler/34870.
Transfer history data appended for: https://www.transfermarkt.com/antonio-puertas/profil/spieler/262365.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-foulquier/profil/spieler/170472.
Transfer history data appended for: https://www.transfermarkt.com/yan-eteki/profil/spieler/297784.
Transfer history data appended for: https://www.transfermarkt.com/yangel-herrera/profil/spieler/378293.
Transfer history data appended for: https://www.transfermarkt.com/andres-guardado/profil/spieler/20506.
Transfer history data appended for: https://www.transfermarkt.com/william-carvalho/profil/spieler/100131.
Transfer history data appended for: https://www.transfermarkt.com/loren-moron/profil/spieler/354741.
Transfer history data appended for: https://www.transfermarkt.com/claudio-bravo/profil/spieler/40423.
Transfer history data appended for: https://www.transfermarkt.com/nabil-fekir/profil/spieler/203496.
Transfer history data appended for: https://www.transfermarkt.com/emerson/profil/spieler/476344.
Transfer history data appended for: https://www.transfermarkt.com/paul-akouokou/profil/spieler/429901.
Transfer history data appended for: https://www.transfermarkt.com/juanmi/profil/spieler/126737.
Transfer history data appended for: https://www.transfermarkt.com/martin-montoya/profil/spieler/68645.
Transfer history data appended for: https://www.transfermarkt.com/aissa-mandi/profil/spieler/80293.
Transfer history data appended for: https://www.transfermarkt.com/sergio-canales/profil/spieler/66106.
Transfer history data appended for: https://www.transfermarkt.com/borja-iglesias/profil/spieler/278359.
Transfer history data appended for: https://www.transfermarkt.com/alex-moreno/profil/spieler/193098.
Transfer history data appended for: https://www.transfermarkt.com/dani-martin/profil/spieler/335221.
Transfer history data appended for: https://www.transfermarkt.com/joaquin/profil/spieler/7663.
Transfer history data appended for: https://www.transfermarkt.com/marc-bartra/profil/spieler/99922.
Transfer history data appended for: https://www.transfermarkt.com/juan-miranda/profil/spieler/341227.
Transfer history data appended for: https://www.transfermarkt.com/guido-rodriguez/profil/spieler/342385.
Transfer history data appended for: https://www.transfermarkt.com/joel-robles/profil/spieler/101118.
Transfer history data appended for: https://www.transfermarkt.com/aitor-ruibal/profil/spieler/378139.
Transfer history data appended for: https://www.transfermarkt.com/victor-ruiz/profil/spieler/62920.
Transfer history data appended for: https://www.transfermarkt.com/takashi-inui/profil/spieler/98249.
Transfer history data appended for: https://www.transfermarkt.com/paulo-oliveira/profil/spieler/139336.
Transfer history data appended for: https://www.transfermarkt.com/recio/profil/spieler/150948.
Transfer history data appended for: https://www.transfermarkt.com/roberto-olabe/profil/spieler/242299.
Transfer history data appended for: https://www.transfermarkt.com/pedro-bigas/profil/spieler/203043.
Transfer history data appended for: https://www.transfermarkt.com/sergio-alvarez/profil/spieler/138935.
Transfer history data appended for: https://www.transfermarkt.com/bryan-gil/profil/spieler/537382.
Transfer history data appended for: https://www.transfermarkt.com/pedro-leon/profil/spieler/51587.
Transfer history data appended for: https://www.transfermarkt.com/edu-exposito/profil/spieler/506248.
Transfer history data appended for: https://www.transfermarkt.com/yoshinori-muto/profil/spieler/230541.
Transfer history data appended for: https://www.transfermarkt.com/marko-dmitrovic/profil/spieler/94308.

Transfer history data appended for: https://www.transfermarkt.com/esteban-burgos/profil/spieler/337922.
Transfer history data appended for: https://www.transfermarkt.com/kevin-rodrigues/profil/spieler/206947.
Transfer history data appended for: https://www.transfermarkt.com/kike-garcia/profil/spieler/93936.
Transfer history data appended for: https://www.transfermarkt.com/anaitz-arbilla/profil/spieler/71548.
Transfer history data appended for: https://www.transfermarkt.com/sergi-enrich/profil/spieler/81988.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-pozo/profil/spieler/341272.
Transfer history data appended for: https://www.transfermarkt.com/jose-antonio-martinez/profil/spieler/311287.
Transfer history data appended for: https://www.transfermarkt.com/quique-gonzalez/profil/spieler/79352.
Transfer history data appended for: https://www.transfermarkt.com/pape-diop/profil/spieler/39907.
Transfer history data appended for: https://www.transfermarkt.com/rafa-soares/profil/spieler/198006.
Transfer history data appended for: https://www.transfermarkt.com/jose-angel/profil/spieler/87469.
Transfer history data appended for: https://www.transfermarkt.com/yoel-rodriguez/profil/spieler/58115.
Transfer history data appended for: https://www.transfermarkt.com/damian-kadzior/profil/spieler/199299.
Transfer history data appended for: https://www.transfermarkt.com/roberto-correa/profil/spieler/223890.
Transfer history data appended for: https://www.transfermarkt.com/jorge-pulido/profil/spieler/67546.
Transfer history data appended for: https://www.transfermarkt.com/pedro-mosquera/profil/spieler/44069.
Transfer history data appended for: https://www.transfermarkt.com/shinji-okazaki/profil/spieler/79642.
Transfer history data appended for: https://www.transfermarkt.com/rafa-mir/profil/spieler/361254.
Transfer history data appended for: https://www.transfermarkt.com/sandro-ramirez/profil/spieler/199369.
Transfer history data appended for: https://www.transfermarkt.com/luisinho/profil/spieler/56777.
Transfer history data appended for: https://www.transfermarkt.com/juan-carlos-real/profil/spieler/201861.
Transfer history data appended for: https://www.transfermarkt.com/javi-galan/profil/spieler/448628.
Transfer history data appended for: https://www.transfermarkt.com/borja-garcia/profil/spieler/67808.
Transfer history data appended for: https://www.transfermarkt.com/dani-escriche/profil/spieler/531829.
Transfer history data appended for: https://www.transfermarkt.com/idrissa-doumbia/profil/spieler/430579.
Transfer history data appended for: https://www.transfermarkt.com/pedro-lopez/profil/spieler/25412.
Transfer history data appended for: https://www.transfermarkt.com/pablo-insua/profil/spieler/171362.
Transfer history data appended for: https://www.transfermarkt.com/antonio-valera/profil/spieler/290275.
Transfer history data appended for: https://www.transfermarkt.com/sergio-gomez/profil/spieler/366930.
Transfer history data appended for: https://www.transfermarkt.com/eugeni-valderrama/profil/spieler/223073.
Transfer history data appended for: https://www.transfermarkt.com/mikel-rico/profil/spieler/51474.
Transfer history data appended for: https://www.transfermarkt.com/jaime-seoane/profil/spieler/340867.
Transfer history data appended for: https://www.transfermarkt.com/kelechi-nwakali/profil/spieler/383153.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-fernandez/profil/spieler/453704.
Transfer history data appended for: https://www.transfermarkt.com/gaston-silva/profil/spieler/189452.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-siovas/profil/spieler/52403.
Transfer history data appended for: https://www.transfermarkt.com/iago-aspas/profil/spieler/72047.
Transfer history data appended for: https://www.transfermarkt.com/okay-yokuslu/profil/spieler/137616.
Transfer history data appended for: https://www.transfermarkt.com/hugo-mallo/profil/spieler/119905.
Transfer history data appended for: https://www.transfermarkt.com/miguel-baeza/profil/spieler/523977.
Transfer history data appended for: https://www.transfermarkt.com/david-junca/profil/spieler/164055.
Transfer history data appended for: https://www.transfermarkt.com/ivan-villar/profil/spieler/297194.
Transfer history data appended for: https://www.transfermarkt.com/nestor-araujo/profil/spieler/64134.
Transfer history data appended for: https://www.transfermarkt.com/renato-tapia/profil/spieler/277137.
Transfer history data appended for: https://www.transfermarkt.com/miguel-rodriguez/profil/spieler/634427.
Transfer history data appended for: https://www.transfermarkt.com/lucas-olaza/profil/spieler/216240.
Transfer history data appended for: https://www.transfermarkt.com/david-costas/profil/spieler/276111.
Transfer history data appended for: https://www.transfermarkt.com/sergio-alvarez/profil/spieler/45912.
Transfer history data appended for: https://www.transfermarkt.com/jeison-murillo/profil/spieler/131102.
Transfer history data appended for: https://www.transfermarkt.com/sergio-carreira/profil/spieler/545647.
Transfer history data appended for: https://www.transfermarkt.com/ruben-blanco/profil/spieler/199321.
Transfer history data appended for: https://www.transfermarkt.com/denis-suarez/profil/spieler/165007.
Transfer history data appended for: https://www.transfermarkt.com/fran-beltran/profil/spieler/423444.
Transfer history data appended for: https://www.transfermarkt.com/joseph-aidoo/profil/spieler/358250.
Transfer history data appended for: https://www.transfermarkt.com/kevin-vazquez/profil/spieler/221315.
Transfer history data appended for: https://www.transfermarkt.com/brais-mendez/profil/spieler/309110.
Transfer history data appended for: https://www.transfermarkt.com/santi-mina/profil/spieler/255653.
Transfer history data appended for: https://www.transfermarkt.com/jorge-saenz/profil/spieler/340339.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-veiga/profil/spieler/699704.
Transfer history data appended for: https://www.transfermarkt.com/miralem-pjanic/profil/spieler/44162.
Transfer history data appended for: https://www.transfermarkt.com/ousmane-dembele/profil/spieler/288230.
Transfer history data appended for: https://www.transfermarkt.com/riqui-puig/profil/spieler/331511.
Transfer history data appended for: https://www.transfermarkt.com/lionel-messi/profil/spieler/28003.
Transfer history data appended for: https://www.transfermarkt.com/marc-andre-ter-stegen/profil/spieler/74857.
Transfer history data appended for: https://www.transfermarkt.com/samuel-umtiti/profil/spieler/126540.
Transfer history data appended for: https://www.transfermarkt.com/trincao/profil/spieler/412669.
Transfer history data appended for: https://www.transfermarkt.com/frenkie-de-jong/profil/spieler/326330.
Transfer history data appended for: https://www.transfermarkt.com/ronald-araujo/profil/spieler/480267.
Transfer history data appended for: https://www.transfermarkt.com/philippe-coutinho/profil/spieler/80444.
Transfer history data appended for: https://www.transfermarkt.com/sergi-roberto/profil/spieler/85370.
Transfer history data appended for: https://www.transfermarkt.com/konrad-de-la-fuente/profil/spieler/466809.
Transfer history data appended for: https://www.transfermarkt.com/arnau-tenas/profil/spieler/466783.
Transfer history data appended for: https://www.transfermarkt.com/jordi-alba/profil/spieler/69751.
Transfer history data appended for: https://www.transfermarkt.com/pedri/profil/spieler/683840.
Transfer history data appended for: https://www.transfermarkt.com/antoine-griezmann/profil/spieler/125781.
Transfer history data appended for: https://www.transfermarkt.com/neto/profil/spieler/111819.
Transfer history data appended for: https://www.transfermarkt.com/junior-firpo/profil/spieler/374139.
Transfer history data appended for: https://www.transfermarkt.com/clement-lenglet/profil/spieler/182904.
Transfer history data appended for: https://www.transfermarkt.com/sergino-dest/profil/spieler/361104.
Transfer history data appended for: https://www.transfermarkt.com/inaki-pena/profil/spieler/283170.
Transfer history data appended for: https://www.transfermarkt.com/gerard-pique/profil/spieler/18944.

Transfer history data appended for: https://www.transfermarkt.com/martin-braithwaite/profil/spieler/95732.
Transfer history data appended for: https://www.transfermarkt.com/oscar-mingueza/profil/spieler/331505.
Transfer history data appended for: https://www.transfermarkt.com/matheus-fernandes/profil/spieler/351892.
Transfer history data appended for: https://www.transfermarkt.com/ansu-fati/profil/spieler/466810.
Transfer history data appended for: https://www.transfermarkt.com/carles-alena/profil/spieler/284854.
Transfer history data appended for: https://www.transfermarkt.com/sergio-busquets/profil/spieler/65230.
Transfer history data appended for: https://www.transfermarkt.com/cheick-doukoure/profil/spieler/129679.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-melero/profil/spieler/162056.
Transfer history data appended for: https://www.transfermarkt.com/roger-marti/profil/spieler/212391.
Transfer history data appended for: https://www.transfermarkt.com/koke-vegas/profil/spieler/299715.
Transfer history data appended for: https://www.transfermarkt.com/coke/profil/spieler/71905.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-radoja/profil/spieler/168959.
Transfer history data appended for: https://www.transfermarkt.com/rober-pier/profil/spieler/387129.
Transfer history data appended for: https://www.transfermarkt.com/nikola-vukcevic/profil/spieler/151470.
Transfer history data appended for: https://www.transfermarkt.com/enis-bardhi/profil/spieler/245014.
Transfer history data appended for: https://www.transfermarkt.com/jose-campana/profil/spieler/120095.
Transfer history data appended for: https://www.transfermarkt.com/mickael-malsa/profil/spieler/205569.
Transfer history data appended for: https://www.transfermarkt.com/sontm/profil/spieler/349856.
Transfer history data appended for: https://www.transfermarkt.com/sergio-postigo/profil/spieler/158791.
Transfer history data appended for: https://www.transfermarkt.com/carlos-clerc/profil/spieler/193784.
Transfer history data appended for: https://www.transfermarkt.com/jorge-miramon/profil/spieler/228917.
Transfer history data appended for: https://www.transfermarkt.com/jorge-de-frutos/profil/spieler/455181.
Transfer history data appended for: https://www.transfermarkt.com/sergio-leon/profil/spieler/145769.
Transfer history data appended for: https://www.transfermarkt.com/dani-gomez/profil/spieler/422460.
Transfer history data appended for: https://www.transfermarkt.com/dani-cardenas/profil/spieler/397676.
Transfer history data appended for: https://www.transfermarkt.com/ruben-rochina/profil/spieler/67548.
Transfer history data appended for: https://www.transfermarkt.com/aitor-fernandez/profil/spieler/118997.
Transfer history data appended for: https://www.transfermarkt.com/oscar-duarte/profil/spieler/175323.
Transfer history data appended for: https://www.transfermarkt.com/ruben-vezo/profil/spieler/257851.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-morales/profil/spieler/252677.
Transfer history data appended for: https://www.transfermarkt.com/tono/profil/spieler/125931.
Transfer history data appended for: https://www.transfermarkt.com/jota/profil/spieler/329812.
Transfer history data appended for: https://www.transfermarkt.com/roque-mesa/profil/spieler/202984.
Transfer history data appended for: https://www.transfermarkt.com/sergi-guardiola/profil/spieler/256429.
Transfer history data appended for: https://www.transfermarkt.com/kike-perez/profil/spieler/527698.
Transfer history data appended for: https://www.transfermarkt.com/roberto/profil/spieler/37403.
Transfer history data appended for: https://www.transfermarkt.com/nacho-martinez/profil/spieler/127554.
Transfer history data appended for: https://www.transfermarkt.com/pablo-hervias/profil/spieler/142027.
Transfer history data appended for: https://www.transfermarkt.com/bruno-gonzalez/profil/spieler/188838.
Transfer history data appended for: https://www.transfermarkt.com/jawad-el-yamiq/profil/spieler/235412.
Transfer history data appended for: https://www.transfermarkt.com/ruben-alcaraz/profil/spieler/247250.
Transfer history data appended for: https://www.transfermarkt.com/michel-herrero/profil/spieler/65331.
Transfer history data appended for: https://www.transfermarkt.com/luis-perez/profil/spieler/358115.
Transfer history data appended for: https://www.transfermarkt.com/oscar-plano/profil/spieler/221309.
Transfer history data appended for: https://www.transfermarkt.com/shon-weissman/profil/spieler/247652.
Transfer history data appended for: https://www.transfermarkt.com/javi-sanchez/profil/spieler/340853.
Transfer history data appended for: https://www.transfermarkt.com/saidy-janko/profil/spieler/196435.
Transfer history data appended for: https://www.transfermarkt.com/toni-villa/profil/spieler/337066.
Transfer history data appended for: https://www.transfermarkt.com/marcos-andre/profil/spieler/481084.
Transfer history data appended for: https://www.transfermarkt.com/jordi-masip/profil/spieler/65263.
Transfer history data appended for: https://www.transfermarkt.com/fede-san-emeterio/profil/spieler/307519.
Transfer history data appended for: https://www.transfermarkt.com/kiko-olivas/profil/spieler/51667.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-fernandez/profil/spieler/221321.
Transfer history data appended for: https://www.transfermarkt.com/waldo-rubio/profil/spieler/404688.
Transfer history data appended for: https://www.transfermarkt.com/vinicius-junior/profil/spieler/371998.
Transfer history data appended for: https://www.transfermarkt.com/ferland-mendy/profil/spieler/291417.
Transfer history data appended for: https://www.transfermarkt.com/luka-modric/profil/spieler/27992.
Transfer history data appended for: https://www.transfermarkt.com/isco/profil/spieler/85288.
Transfer history data appended for: https://www.transfermarkt.com/toni-kroos/profil/spieler/31909.
Transfer history data appended for: https://www.transfermarkt.com/thibaut-courtois/profil/spieler/108390.
Transfer history data appended for: https://www.transfermarkt.com/lucas-vazquez/profil/spieler/221316.
Transfer history data appended for: https://www.transfermarkt.com/eden-hazard/profil/spieler/50202.
Transfer history data appended for: https://www.transfermarkt.com/marcelo/profil/spieler/44501.
Transfer history data appended for: https://www.transfermarkt.com/casemiro/profil/spieler/16306.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-odriozola/profil/spieler/280730.
Transfer history data appended for: https://www.transfermarkt.com/martin-odegaard/profil/spieler/316264.
Transfer history data appended for: https://www.transfermarkt.com/daniel-carvajal/profil/spieler/138927.
Transfer history data appended for: https://www.transfermarkt.com/raphael-varane/profil/spieler/164770.
Transfer history data appended for: https://www.transfermarkt.com/nacho-fernandez/profil/spieler/58884.
Transfer history data appended for: https://www.transfermarkt.com/mariano-diaz/profil/spieler/225020.
Transfer history data appended for: https://www.transfermarkt.com/andriy-lunin/profil/spieler/404839.
Transfer history data appended for: https://www.transfermarkt.com/marco-asensio/profil/spieler/296622.
Transfer history data appended for: https://www.transfermarkt.com/karim-benzema/profil/spieler/18922.
Transfer history data appended for: https://www.transfermarkt.com/sergio-ramos/profil/spieler/25557.
Transfer history data appended for: https://www.transfermarkt.com/eder-militao/profil/spieler/401530.
Transfer history data appended for: https://www.transfermarkt.com/rodrygo/profil/spieler/412363.
Transfer history data appended for: https://www.transfermarkt.com/takefusa-kubo/profil/spieler/405398.
Transfer history data appended for: https://www.transfermarkt.com/manu-trigueros/profil/spieler/188854.
Transfer history data appended for: https://www.transfermarkt.com/mario-gaspar/profil/spieler/73250.
Transfer history data appended for: https://www.transfermarkt.com/pau-torres/profil/spieler/399776.
Transfer history data appended for: https://www.transfermarkt.com/vicente-iborra/profil/spieler/65467.

Transfer history data appended for: https://www.transfermarkt.com/sergio-asenjo/profil/spieler/51710.
Transfer history data appended for: https://www.transfermarkt.com/alex-baena/profil/spieler/548111.
Transfer history data appended for: https://www.transfermarkt.com/dani-parejo/profil/spieler/59561.
Transfer history data appended for: https://www.transfermarkt.com/yeremi-pino/profil/spieler/568157.
Transfer history data appended for: https://www.transfermarkt.com/raul-albiol/profil/spieler/15452.
Transfer history data appended for: https://www.transfermarkt.com/dani-raba/profil/spieler/413262.
Transfer history data appended for: https://www.transfermarkt.com/moi-gomez/profil/spieler/175449.
Transfer history data appended for: https://www.transfermarkt.com/alfonso-pedraza/profil/spieler/356197.
Transfer history data appended for: https://www.transfermarkt.com/paco-alcacer/profil/spieler/126716.
Transfer history data appended for: https://www.transfermarkt.com/jaume-costa/profil/spieler/65318.
Transfer history data appended for: https://www.transfermarkt.com/alberto-moreno/profil/spieler/207917.
Transfer history data appended for: https://www.transfermarkt.com/ramiro-funes-mori/profil/spieler/11111.
Transfer history data appended for: https://www.transfermarkt.com/juan-foyth/profil/spieler/480763.
Transfer history data appended for: https://www.transfermarkt.com/carlos-bacca/profil/spieler/119235.
Transfer history data appended for: https://www.transfermarkt.com/soufiane-chakla/profil/spieler/236956.
Transfer history data appended for: https://www.transfermarkt.com/pervis-estupinan/profil/spieler/349599.
Transfer history data appended for: https://www.transfermarkt.com/gerard-moreno/profil/spieler/177467.
Transfer history data appended for: https://www.transfermarkt.com/fer-nino/profil/spieler/627294.
Transfer history data appended for: https://www.transfermarkt.com/gero-rulli/profil/spieler/229604.
Transfer history data appended for: https://www.transfermarkt.com/samu-chukwueze/profil/spieler/401922.
Transfer history data appended for: https://www.transfermarkt.com/youssef-en-nesyri/profil/spieler/433049.
Transfer history data appended for: https://www.transfermarkt.com/suso/profil/spieler/111961.
Transfer history data appended for: https://www.transfermarkt.com/franco-vazquez/profil/spieler/76163.
Transfer history data appended for: https://www.transfermarkt.com/bono/profil/spieler/207834.
Transfer history data appended for: https://www.transfermarkt.com/sergi-gomez/profil/spieler/92947.
Transfer history data appended for: https://www.transfermarkt.com/jesus-navas/profil/spieler/15956.
Transfer history data appended for: https://www.transfermarkt.com/joan-jordan/profil/spieler/263727.
Transfer history data appended for: https://www.transfermarkt.com/oliver-torres/profil/spieler/214775.
Transfer history data appended for: https://www.transfermarkt.com/munir-el-haddadi/profil/spieler/223725.
Transfer history data appended for: https://www.transfermarkt.com/ivan-rakitic/profil/spieler/32467.
Transfer history data appended for: https://www.transfermarkt.com/fernando-reges/profil/spieler/51174.
Transfer history data appended for: https://www.transfermarkt.com/karim-rekik/profil/spieler/182579.
Transfer history data appended for: https://www.transfermarkt.com/carlos-fernandez/profil/spieler/216464.
Transfer history data appended for: https://www.transfermarkt.com/oussama-idrissi/profil/spieler/241391.
Transfer history data appended for: https://www.transfermarkt.com/jules-kounde/profil/spieler/411975.
Transfer history data appended for: https://www.transfermarkt.com/luuk-de-jong/profil/spieler/72522.
Transfer history data appended for: https://www.transfermarkt.com/joris-gnagnon/profil/spieler/378954.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-gudelj/profil/spieler/74294.
Transfer history data appended for: https://www.transfermarkt.com/diego-carlos/profil/spieler/329145.
Transfer history data appended for: https://www.transfermarkt.com/tomas-vaclik/profil/spieler/64000.
Transfer history data appended for: https://www.transfermarkt.com/marcos-acuna/profil/spieler/60410.
Transfer history data appended for: https://www.transfermarkt.com/aleix-vidal/profil/spieler/88490.
Transfer history data appended for: https://www.transfermarkt.com/javi-diaz/profil/spieler/396107.
Transfer history data appended for: https://www.transfermarkt.com/aridane-hernandez/profil/spieler/82503.
Transfer history data appended for: https://www.transfermarkt.com/ruben-garcia/profil/spieler/213260.
Transfer history data appended for: https://www.transfermarkt.com/juan-cruz/profil/spieler/169497.
Transfer history data appended for: https://www.transfermarkt.com/brandon/profil/spieler/251680.
Transfer history data appended for: https://www.transfermarkt.com/darko-brasanac/profil/spieler/95641.
Transfer history data appended for: https://www.transfermarkt.com/juan-perez/profil/spieler/298613.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-calleri/profil/spieler/284727.
Transfer history data appended for: https://www.transfermarkt.com/jony/profil/spieler/228761.
Transfer history data appended for: https://www.transfermarkt.com/unai-garcia/profil/spieler/197122.
Transfer history data appended for: https://www.transfermarkt.com/chimy-avila/profil/spieler/167721.
Transfer history data appended for: https://www.transfermarkt.com/oier/profil/spieler/63040.
Transfer history data appended for: https://www.transfermarkt.com/inigo-perez/profil/spieler/71579.
Transfer history data appended for: https://www.transfermarkt.com/david-garcia/profil/spieler/298589.
Transfer history data appended for: https://www.transfermarkt.com/ruben-martinez/profil/spieler/8184.
Transfer history data appended for: https://www.transfermarkt.com/nacho-vidal/profil/spieler/216870.
Transfer history data appended for: https://www.transfermarkt.com/sergio-herrera/profil/spieler/248738.
Transfer history data appended for: https://www.transfermarkt.com/lucas-torro/profil/spieler/213670.
Transfer history data appended for: https://www.transfermarkt.com/enric-gallego/profil/spieler/114060.
Transfer history data appended for: https://www.transfermarkt.com/kike-barja/profil/spieler/298575.
Transfer history data appended for: https://www.transfermarkt.com/adrian-lopez/profil/spieler/45383.
Transfer history data appended for: https://www.transfermarkt.com/raul-navas/profil/spieler/142419.
Transfer history data appended for: https://www.transfermarkt.com/roberto-torres/profil/spieler/63056.
Transfer history data appended for: https://www.transfermarkt.com/jon-moncayola/profil/spieler/552425.
Transfer history data appended for: https://www.transfermarkt.com/nano-mesa/profil/spieler/305956.
Transfer history data appended for: https://www.transfermarkt.com/alex-fernandez/profil/spieler/89733.
Transfer history data appended for: https://www.transfermarkt.com/jorge-pombo/profil/spieler/336747.
Transfer history data appended for: https://www.transfermarkt.com/augusto-fernandez/profil/spieler/39151.
Transfer history data appended for: https://www.transfermarkt.com/jens-jonsson/profil/spieler/148355.
Transfer history data appended for: https://www.transfermarkt.com/luismi-quezada/profil/spieler/282428.
Transfer history data appended for: https://www.transfermarkt.com/jose-mari/profil/spieler/225462.
Transfer history data appended for: https://www.transfermarkt.com/david-gil/profil/spieler/162027.
Transfer history data appended for: https://www.transfermarkt.com/alfonso-espino/profil/spieler/311044.
Transfer history data appended for: https://www.transfermarkt.com/bobby-adekanye/profil/spieler/331514.
Transfer history data appended for: https://www.transfermarkt.com/filip-malba-scaron-i%C4%87/profil/spieler/162652.
Transfer history data appended for: https://www.transfermarkt.com/juan-cala/profil/spieler/67089.
Transfer history data appended for: https://www.transfermarkt.com/ivan-alejo/profil/spieler/281755.
Transfer history data appended for: https://www.transfermarkt.com/carlos-akapo/profil/spieler/225015.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-gimenez/profil/spieler/57935.

Transfer history data appended for: https://www.transfermarkt.com/salvi-sanchez/profil/spieler/246204.
Transfer history data appended for: https://www.transfermarkt.com/iza-carcelen/profil/spieler/254037.
Transfer history data appended for: https://www.transfermarkt.com/yann-bodiger/profil/spieler/290533.
Transfer history data appended for: https://www.transfermarkt.com/alberto-perea/profil/spieler/99559.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/fali/profil/spieler/252667.
Transfer history data appended for: https://www.transfermarkt.com/sergio-gonzalez/profil/spieler/435500.
Transfer history data appended for: https://www.transfermarkt.com/marcos-mauro/profil/spieler/247366.
Transfer history data appended for: https://www.transfermarkt.com/pedro-alcala/profil/spieler/51663.
Transfer history data appended for: https://www.transfermarkt.com/jon-ander-garrido/profil/spieler/158704.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-negredo/profil/spieler/18644.
Transfer history data appended for: https://www.transfermarkt.com/abdallahi-mahmoud/profil/spieler/615636.
Transfer history data appended for: https://www.transfermarkt.com/edgar-mendez/profil/spieler/133794.
Transfer history data appended for: https://www.transfermarkt.com/jota-peleteiro/profil/spieler/176591.
Transfer history data appended for: https://www.transfermarkt.com/sergi-garcia/profil/spieler/598608.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-battaglia/profil/spieler/89297.
Transfer history data appended for: https://www.transfermarkt.com/pere-pons/profil/spieler/242497.
Transfer history data appended for: https://www.transfermarkt.com/tomas-pina/profil/spieler/139895.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-ely/profil/spieler/176140.
Transfer history data appended for: https://www.transfermarkt.com/luis-rioja/profil/spieler/278837.
Transfer history data appended for: https://www.transfermarkt.com/adrian-marin/profil/spieler/295414.
Transfer history data appended for: https://www.transfermarkt.com/tomas-tavares/profil/spieler/550549.
Transfer history data appended for: https://www.transfermarkt.com/ximo-navarro/profil/spieler/184767.
Transfer history data appended for: https://www.transfermarkt.com/florian-lejeune/profil/spieler/127108.
Transfer history data appended for: https://www.transfermarkt.com/javi-lopez/profil/spieler/568158.
Transfer history data appended for: https://www.transfermarkt.com/fernando-pacheco/profil/spieler/172015.
Transfer history data appended for: https://www.transfermarkt.com/lucas-perez/profil/spieler/73185.
Transfer history data appended for: https://www.transfermarkt.com/antonio-sivera/profil/spieler/298197.
Transfer history data appended for: https://www.transfermarkt.com/tachi/profil/spieler/354697.
Transfer history data appended for: https://www.transfermarkt.com/victor-laguardia/profil/spieler/67080.
Transfer history data appended for: https://www.transfermarkt.com/borja-sainz/profil/spieler/634461.
Transfer history data appended for: https://www.transfermarkt.com/martin-aguirregabiria/profil/spieler/483573.
Transfer history data appended for: https://www.transfermarkt.com/burgui/profil/spieler/246277.
Transfer history data appended for: https://www.transfermarkt.com/manu-garcia/profil/spieler/76273.
Transfer history data appended for: https://www.transfermarkt.com/ruben-duarte/profil/spieler/177046.
Transfer history data appended for: https://www.transfermarkt.com/carlos-soler/profil/spieler/372246.
Transfer history data appended for: https://www.transfermarkt.com/denis-cheryshev/profil/spieler/98322.
Transfer history data appended for: https://www.transfermarkt.com/manu-vallejo/profil/spieler/527350.
Transfer history data appended for: https://www.transfermarkt.com/jasper-cillessen/profil/spieler/146227.
Transfer history data appended for: https://www.transfermarkt.com/mouctar-diakhaby/profil/spieler/346289.
Transfer history data appended for: https://www.transfermarkt.com/kevin-gameiro/profil/spieler/27389.
Transfer history data appended for: https://www.transfermarkt.com/maxi-gomez/profil/spieler/396894.
Transfer history data appended for: https://www.transfermarkt.com/ruben-sobrino/profil/spieler/85383.
Transfer history data appended for: https://www.transfermarkt.com/yunus-musah/profil/spieler/503991.
Transfer history data appended for: https://www.transfermarkt.com/alex-blanco/profil/spieler/328914.
Transfer history data appended for: https://www.transfermarkt.com/eliaquim-mangala/profil/spieler/90681.
Transfer history data appended for: https://www.transfermarkt.com/vicente-esquerdo/profil/spieler/599263.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-paulista/profil/spieler/149498.
Transfer history data appended for: https://www.transfermarkt.com/toni-lato/profil/spieler/320271.
Transfer history data appended for: https://www.transfermarkt.com/goncalo-guedes/profil/spieler/225122.
Transfer history data appended for: https://www.transfermarkt.com/thierry-correia/profil/spieler/367466.
Transfer history data appended for: https://www.transfermarkt.com/uros-racic/profil/spieler/417575.
Transfer history data appended for: https://www.transfermarkt.com/kang-in-lee/profil/spieler/557149.
Transfer history data appended for: https://www.transfermarkt.com/cristian-rivero/profil/spieler/398131.
Transfer history data appended for: https://www.transfermarkt.com/jose-gaya/profil/spieler/221322.
Transfer history data appended for: https://www.transfermarkt.com/guillem-molina/profil/spieler/602156.
Transfer history data appended for: https://www.transfermarkt.com/hugo-guillamon/profil/spieler/495629.
Transfer history data appended for: https://www.transfermarkt.com/koba-koindredi/profil/spieler/569375.
Transfer history data appended for: https://www.transfermarkt.com/jaume-domenech/profil/spieler/227805.
Transfer history data appended for: https://www.transfermarkt.com/daniel-wass/profil/spieler/63463.
Transfer history data appended for: https://www.transfermarkt.com/matias-nahuel/profil/spieler/263843.
Transfer history data appended for: https://www.transfermarkt.com/carlos-hernandez/profil/spieler/225459.
Transfer history data appended for: https://www.transfermarkt.com/juanjo-nieto/profil/spieler/327207.
Transfer history data appended for: https://www.transfermarkt.com/lucas-ahijado/profil/spieler/349884.
Transfer history data appended for: https://www.transfermarkt.com/simone-grippo/profil/spieler/41767.
Transfer history data appended for: https://www.transfermarkt.com/joan-femenias/profil/spieler/455363.
Transfer history data appended for: https://www.transfermarkt.com/sergio-tejera/profil/spieler/38817.
Transfer history data appended for: https://www.transfermarkt.com/giorgi-aburjania/profil/spieler/186848.
Transfer history data appended for: https://www.transfermarkt.com/rodri-rios/profil/spieler/117549.
Transfer history data appended for: https://www.transfermarkt.com/cedric-teguia/profil/spieler/536831.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-arribas/profil/spieler/137174.
Transfer history data appended for: https://www.transfermarkt.com/viti-rozada/profil/spieler/438971.
Transfer history data appended for: https://www.transfermarkt.com/marco-sangalli/profil/spieler/197131.
Transfer history data appended for: https://www.transfermarkt.com/borja-sanchez/profil/spieler/217155.
Transfer history data appended for: https://www.transfermarkt.com/diegui/profil/spieler/349886.
Transfer history data appended for: https://www.transfermarkt.com/jimmy/profil/spieler/595781.
Transfer history data appended for: https://www.transfermarkt.com/mossa/profil/spieler/96094.
Transfer history data appended for: https://www.transfermarkt.com/bolano/profil/spieler/48294.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-blanco-leschuk/profil/spieler/181006.
Transfer history data appended for: https://www.transfermarkt.com/riki-rodriguez/profil/spieler/596899.
Transfer history data appended for: https://www.transfermarkt.com/edgar-gonzalez/profil/spieler/401624.
Transfer history data appended for: https://www.transfermarkt.com/samuel-obeng/profil/spieler/522719.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-brazao/profil/spieler/371247.
Transfer history data appended for: https://www.transfermarkt.com/rafa-mujica/profil/spieler/361504.
Transfer history data appended for: https://www.transfermarkt.com/oscar-melendo/profil/spieler/448344.
Transfer history data appended for: https://www.transfermarkt.com/diego-lopez/profil/spieler/34370.

Transfer history data appended for: https://www.transfermarkt.com/david-lopez/profil/spieler/129444.
Transfer history data appended for: https://www.transfermarkt.com/matias-vargas/profil/spieler/376211.
Transfer history data appended for: https://www.transfermarkt.com/oscar-gil/profil/spieler/544106.
Transfer history data appended for: https://www.transfermarkt.com/pol-lozano/profil/spieler/412045.
Transfer history data appended for: https://www.transfermarkt.com/keidi-bare/profil/spieler/295622.
Transfer history data appended for: https://www.transfermarkt.com/javi-puado/profil/spieler/408471.
Transfer history data appended for: https://www.transfermarkt.com/adria-pedrosa/profil/spieler/501418.
Transfer history data appended for: https://www.transfermarkt.com/angel-fortuno/profil/spieler/628487.
Transfer history data appended for: https://www.transfermarkt.com/didac-vila/profil/spieler/67090.
Transfer history data appended for: https://www.transfermarkt.com/victor-campuzano/profil/spieler/394285.
Transfer history data appended for: https://www.transfermarkt.com/nico-melamed/profil/spieler/570421.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-vadillo/profil/spieler/162074.
Transfer history data appended for: https://www.transfermarkt.com/leandro-cabrera/profil/spieler/102423.
Transfer history data appended for: https://www.transfermarkt.com/fran-merida/profil/spieler/42920.
Transfer history data appended for: https://www.transfermarkt.com/miguelon/profil/spieler/399775.
Transfer history data appended for: https://www.transfermarkt.com/adrian-embarba/profil/spieler/288318.
Transfer history data appended for: https://www.transfermarkt.com/raul-de-tomas/profil/spieler/162038.
Transfer history data appended for: https://www.transfermarkt.com/fernando-calero/profil/spieler/357884.
Transfer history data appended for: https://www.transfermarkt.com/lei-wu/profil/spieler/140436.
Transfer history data appended for: https://www.transfermarkt.com/jofre-carreras/profil/spieler/628498.
Transfer history data appended for: https://www.transfermarkt.com/alex-lopez/profil/spieler/313113.
Transfer history data appended for: https://www.transfermarkt.com/lluis-lopez/profil/spieler/262391.
Transfer history data appended for: https://www.transfermarkt.com/guillem-jaime/profil/spieler/331508.
Transfer history data appended for: https://www.transfermarkt.com/victor-garcia/profil/spieler/281588.
Transfer history data appended for: https://www.transfermarkt.com/igor-zlatanovic/profil/spieler/343965.
Transfer history data appended for: https://www.transfermarkt.com/josep-sene/profil/spieler/161267.
Transfer history data appended for: https://www.transfermarkt.com/adrian-lapena/profil/spieler/289267.
Transfer history data appended for: https://www.transfermarkt.com/francisco-regalon/profil/spieler/71994.
Transfer history data appended for: https://www.transfermarkt.com/jordi-sanchez/profil/spieler/291693.
Transfer history data appended for: https://www.transfermarkt.com/paolo-fernandes/profil/spieler/284876.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-marcos/profil/spieler/617052.
Transfer history data appended for: https://www.transfermarkt.com/ruben-diez/profil/spieler/311266.
Transfer history data appended for: https://www.transfermarkt.com/jorge-fernandez/profil/spieler/222667.
Transfer history data appended for: https://www.transfermarkt.com/rafa-galvez/profil/spieler/288454.
Transfer history data appended for: https://www.transfermarkt.com/gus-ledes/profil/spieler/139352.
Transfer history data appended for: https://www.transfermarkt.com/inigo-munoz/profil/spieler/442767.
Transfer history data appended for: https://www.transfermarkt.com/arturo-molina/profil/spieler/337781.
Transfer history data appended for: https://www.transfermarkt.com/juanto-ortuno/profil/spieler/213875.
Transfer history data appended for: https://www.transfermarkt.com/oscar-whalley/profil/spieler/260662.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-campos/profil/spieler/73157.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-fidalgo/profil/spieler/261503.
Transfer history data appended for: https://www.transfermarkt.com/eneko-satrustegui/profil/spieler/158792.
Transfer history data appended for: https://www.transfermarkt.com/iago-indias/profil/spieler/356196.
Transfer history data appended for: https://www.transfermarkt.com/jesus-carrillo/profil/spieler/464900.
Transfer history data appended for: https://www.transfermarkt.com/marc-mateu/profil/spieler/96539.
Transfer history data appended for: https://www.transfermarkt.com/joseba-muguruza/profil/spieler/229811.
Transfer history data appended for: https://www.transfermarkt.com/carles-salvador/profil/spieler/217730.
Transfer history data appended for: https://www.transfermarkt.com/marc-castells/profil/spieler/73137.
Transfer history data appended for: https://www.transfermarkt.com/david-cubillas/profil/spieler/128816.
Transfer history data appended for: https://www.transfermarkt.com/cesar-diaz/profil/spieler/51632.
Transfer history data appended for: https://www.transfermarkt.com/carlos-delgado/profil/spieler/175773.
Transfer history data appended for: https://www.transfermarkt.com/andres-mohedano/profil/spieler/289250.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-jackson/profil/spieler/776890.
Transfer history data appended for: https://www.transfermarkt.com/victor-gomez/profil/spieler/495601.
Transfer history data appended for: https://www.transfermarkt.com/dani-vivian/profil/spieler/524000.
Transfer history data appended for: https://www.transfermarkt.com/javi-jimenez/profil/spieler/242287.
Transfer history data appended for: https://www.transfermarkt.com/limones/profil/spieler/57948.
Transfer history data appended for: https://www.transfermarkt.com/genaro-rodriguez/profil/spieler/396109.
Transfer history data appended for: https://www.transfermarkt.com/erik-jirka/profil/spieler/339693.
Transfer history data appended for: https://www.transfermarkt.com/carlos-julio-martinez/profil/spieler/166658.
Transfer history data appended for: https://www.transfermarkt.com/victor-meseguer/profil/spieler/658269.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-schutte/profil/spieler/600836.
Transfer history data appended for: https://www.transfermarkt.com/sergio-moreno/profil/spieler/607779.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-ezzarfani/profil/spieler/449844.
Transfer history data appended for: https://www.transfermarkt.com/pablo-martinez/profil/spieler/568835.
Transfer history data appended for: https://www.transfermarkt.com/raul-lizoain/profil/spieler/167228.
Transfer history data appended for: https://www.transfermarkt.com/nais-djouahra/profil/spieler/594926.
Transfer history data appended for: https://www.transfermarkt.com/juan-berrocal/profil/spieler/461843.
Transfer history data appended for: https://www.transfermarkt.com/javi-munoz/profil/spieler/282421.
Transfer history data appended for: https://www.transfermarkt.com/antonio-caballero/profil/spieler/364890.
Transfer history data appended for: https://www.transfermarkt.com/bojan-letic/profil/spieler/166985.
Transfer history data appended for: https://www.transfermarkt.com/pablo-trigueros/profil/spieler/248337.
Transfer history data appended for: https://www.transfermarkt.com/ivan-martin/profil/spieler/341278.
Transfer history data appended for: https://www.transfermarkt.com/mario-barco/profil/spieler/248021.
Transfer history data appended for: https://www.transfermarkt.com/william-de-camargo/profil/spieler/583607.
Transfer history data appended for: https://www.transfermarkt.com/elady-zorrilla/profil/spieler/240849.
Transfer history data appended for: https://www.transfermarkt.com/jack-harper/profil/spieler/147524.
Transfer history data appended for: https://www.transfermarkt.com/jose-angel-jurado/profil/spieler/187673.
Transfer history data appended for: https://www.transfermarkt.com/alex-martin/profil/spieler/345083.
Transfer history data appended for: https://www.transfermarkt.com/marc-martinez/profil/spieler/129374.

Transfer history data appended for: https://www.transfermarkt.com/sergio-aguza/profil/spieler/246244.
Transfer history data appended for: https://www.transfermarkt.com/alberto-de-la-bella/profil/spieler/73319.
Transfer history data appended for: https://www.transfermarkt.com/david-simon/profil/spieler/228584.
Transfer history data appended for: https://www.transfermarkt.com/berto-cayarga/profil/spieler/510372.
Transfer history data appended for: https://www.transfermarkt.com/verza/profil/spieler/26199.
Transfer history data appended for: https://www.transfermarkt.com/jean-pierre-rhyner/profil/spieler/203981.
Transfer history data appended for: https://www.transfermarkt.com/carlos-david/profil/spieler/65342.
Transfer history data appended for: https://www.transfermarkt.com/ruben-castro/profil/spieler/25316.
Transfer history data appended for: https://www.transfermarkt.com/david-andujar/profil/spieler/531267.
Transfer history data appended for: https://www.transfermarkt.com/david-fornies/profil/spieler/221984.
Transfer history data appended for: https://www.transfermarkt.com/uriel-jove/profil/spieler/724458.
Transfer history data appended for: https://www.transfermarkt.com/miguel-angel-cordero/profil/spieler/58778.
Transfer history data appended for: https://www.transfermarkt.com/sergio-lozano/profil/spieler/341277.
Transfer history data appended for: https://www.transfermarkt.com/julian-delmas/profil/spieler/509484.
Transfer history data appended for: https://www.transfermarkt.com/kleandro-lleshi/profil/spieler/466800.
Transfer history data appended for: https://www.transfermarkt.com/pablo-claveria/profil/spieler/348553.
Transfer history data appended for: https://www.transfermarkt.com/esteve-pena/profil/spieler/398130.
Transfer history data appended for: https://www.transfermarkt.com/alex-gallar/profil/spieler/210143.
Transfer history data appended for: https://www.transfermarkt.com/simon-moreno/profil/spieler/355630.
Transfer history data appended for: https://www.transfermarkt.com/adalberto-carrasquilla/profil/spieler/375300.
Transfer history data appended for: https://www.transfermarkt.com/marcin-bulka/profil/spieler/465955.
Transfer history data appended for: https://www.transfermarkt.com/nacho-gil/profil/spieler/336731.
Transfer history data appended for: https://www.transfermarkt.com/fran-sol/profil/spieler/164292.
Transfer history data appended for: https://www.transfermarkt.com/jorge-padilla/profil/spieler/726030.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-zarfino/profil/spieler/208022.
Transfer history data appended for: https://www.transfermarkt.com/shaq-moore/profil/spieler/336168.
Transfer history data appended for: https://www.transfermarkt.com/otar-kakabadze/profil/spieler/214250.
Transfer history data appended for: https://www.transfermarkt.com/nono/profil/spieler/152776.
Transfer history data appended for: https://www.transfermarkt.com/jacobo-gonzalez/profil/spieler/340870.
Transfer history data appended for: https://www.transfermarkt.com/bruno-wilson/profil/spieler/71830.
Transfer history data appended for: https://www.transfermarkt.com/victor-mendez/profil/spieler/814995.
Transfer history data appended for: https://www.transfermarkt.com/nikola-sipcic/profil/spieler/311146.
Transfer history data appended for: https://www.transfermarkt.com/aitor-sanz/profil/spieler/71834.
Transfer history data appended for: https://www.transfermarkt.com/dylan/profil/spieler/840794.
Transfer history data appended for: https://www.transfermarkt.com/carlos-pomares/profil/spieler/238872.
Transfer history data appended for: https://www.transfermarkt.com/valentin-vada/profil/spieler/225004.
Transfer history data appended for: https://www.transfermarkt.com/borja-lasso/profil/spieler/268949.
Transfer history data appended for: https://www.transfermarkt.com/joselu/profil/spieler/143044.
Transfer history data appended for: https://www.transfermarkt.com/suso-santana/profil/spieler/51522.
Transfer history data appended for: https://www.transfermarkt.com/alex-munoz/profil/spieler/243760.
Transfer history data appended for: https://www.transfermarkt.com/alberto-jimenez/profil/spieler/265289.
Transfer history data appended for: https://www.transfermarkt.com/david-rodriguez/profil/spieler/820375.
Transfer history data appended for: https://www.transfermarkt.com/felix-alonso/profil/spieler/751315.
Transfer history data appended for: https://www.transfermarkt.com/ramon-folch/profil/spieler/286841.
Transfer history data appended for: https://www.transfermarkt.com/carlos-ruiz/profil/spieler/72421.
Transfer history data appended for: https://www.transfermarkt.com/adrian-ortola/profil/spieler/142033.
Transfer history data appended for: https://www.transfermarkt.com/alex-bermejo/profil/spieler/473695.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-apeh/profil/spieler/463332.
Transfer history data appended for: https://www.transfermarkt.com/dani-hernandez/profil/spieler/88528.
Transfer history data appended for: https://www.transfermarkt.com/samuel-shashoua/profil/spieler/387313.
Transfer history data appended for: https://www.transfermarkt.com/alex-lopez/profil/spieler/166674.
Transfer history data appended for: https://www.transfermarkt.com/inigo-ruiz-de-galarreta/profil/spieler/126751.
Transfer history data appended for: https://www.transfermarkt.com/iddrisu-baba/profil/spieler/442805.
Transfer history data appended for: https://www.transfermarkt.com/joan-sastre/profil/spieler/350364.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-sedlar/profil/spieler/237499.
Transfer history data appended for: https://www.transfermarkt.com/lago-junior/profil/spieler/100722.
Transfer history data appended for: https://www.transfermarkt.com/salva-sevilla/profil/spieler/58799.
Transfer history data appended for: https://www.transfermarkt.com/manolo-reina/profil/spieler/29051.
Transfer history data appended for: https://www.transfermarkt.com/luka-romero/profil/spieler/769063.
Transfer history data appended for: https://www.transfermarkt.com/antonio-raillo/profil/spieler/278296.
Transfer history data appended for: https://www.transfermarkt.com/franco-russo/profil/spieler/378463.
Transfer history data appended for: https://www.transfermarkt.com/enzo-lombardo/profil/spieler/443290.
Transfer history data appended for: https://www.transfermarkt.com/fran-gamez/profil/spieler/442816.
Transfer history data appended for: https://www.transfermarkt.com/alex-alegria/profil/spieler/178187.
Transfer history data appended for: https://www.transfermarkt.com/abdon-prats/profil/spieler/177452.
Transfer history data appended for: https://www.transfermarkt.com/braian-cufre/profil/spieler/401521.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-trajkovski/profil/spieler/142920.
Transfer history data appended for: https://www.transfermarkt.com/brian-olivan/profil/spieler/166677.
Transfer history data appended for: https://www.transfermarkt.com/aleix-febas/profil/spieler/217144.
Transfer history data appended for: https://www.transfermarkt.com/murilo-de-souza/profil/spieler/345061.
Transfer history data appended for: https://www.transfermarkt.com/antonio-sanchez/profil/spieler/513031.
Transfer history data appended for: https://www.transfermarkt.com/miquel-parera/profil/spieler/242301.
Transfer history data appended for: https://www.transfermarkt.com/jordi-mboula/profil/spieler/331498.
Transfer history data appended for: https://www.transfermarkt.com/dani-rodriguez/profil/spieler/139435.
Transfer history data appended for: https://www.transfermarkt.com/marc-cardona/profil/spieler/443222.
Transfer history data appended for: https://www.transfermarkt.com/amath-ndiaye/profil/spieler/339820.
Transfer history data appended for: https://www.transfermarkt.com/juan-soriano/profil/spieler/251892.
Transfer history data appended for: https://www.transfermarkt.com/jose-matos/profil/spieler/268957.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-benitez/profil/spieler/610334.
Transfer history data appended for: https://www.transfermarkt.com/ismael-casas/profil/spieler/465316.

Transfer history data appended for: https://www.transfermarkt.com/alberto-escassi/profil/spieler/147232.
Transfer history data appended for: https://www.transfermarkt.com/cristo-romero/profil/spieler/696890.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-crettaz/profil/spieler/631049.
Transfer history data appended for: https://www.transfermarkt.com/caye-quintana/profil/spieler/238471.
Transfer history data appended for: https://www.transfermarkt.com/juande-rivas/profil/spieler/465317.
Transfer history data appended for: https://www.transfermarkt.com/ramon-enriquez/profil/spieler/567222.
Transfer history data appended for: https://www.transfermarkt.com/alberto-quintana/profil/spieler/631055.
Transfer history data appended for: https://www.transfermarkt.com/ivan-calero/profil/spieler/212849.
Transfer history data appended for: https://www.transfermarkt.com/jairo-samperio/profil/spieler/171167.
Transfer history data appended for: https://www.transfermarkt.com/dani-barrio/profil/spieler/89471.
Transfer history data appended for: https://www.transfermarkt.com/luis-munoz/profil/spieler/355624.
Transfer history data appended for: https://www.transfermarkt.com/david-lomban/profil/spieler/63723.
Transfer history data appended for: https://www.transfermarkt.com/juan-cruz/profil/spieler/585700.
Transfer history data appended for: https://www.transfermarkt.com/david-larrubia/profil/spieler/635939.
Transfer history data appended for: https://www.transfermarkt.com/cristian-rodriguez/profil/spieler/442802.
Transfer history data appended for: https://www.transfermarkt.com/yanis-rahmani/profil/spieler/255506.
Transfer history data appended for: https://www.transfermarkt.com/hicham-boussefiane/profil/spieler/465321.
Transfer history data appended for: https://www.transfermarkt.com/julito-martinez/profil/spieler/631067.
Transfer history data appended for: https://www.transfermarkt.com/jozabed-sanchez/profil/spieler/207924.
Transfer history data appended for: https://www.transfermarkt.com/josua-mejias/profil/spieler/427683.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-munoz/profil/spieler/396334.
Transfer history data appended for: https://www.transfermarkt.com/orlando-sa/profil/spieler/64535.
Transfer history data appended for: https://www.transfermarkt.com/pablo-chavarria/profil/spieler/118732.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-benkhemassa/profil/spieler/262220.
Transfer history data appended for: https://www.transfermarkt.com/sergio-akieme/profil/spieler/355627.
Transfer history data appended for: https://www.transfermarkt.com/aitor-bunuel/profil/spieler/374081.
Transfer history data appended for: https://www.transfermarkt.com/fernando-martinez/profil/spieler/81997.
Transfer history data appended for: https://www.transfermarkt.com/cristian-olivera/profil/spieler/657746.
Transfer history data appended for: https://www.transfermarkt.com/chumi/profil/spieler/333361.
Transfer history data appended for: https://www.transfermarkt.com/alex-centelles/profil/spieler/423443.
Transfer history data appended for: https://www.transfermarkt.com/manu-morlanes/profil/spieler/335225.
Transfer history data appended for: https://www.transfermarkt.com/giorgi-makaridze/profil/spieler/55977.
Transfer history data appended for: https://www.transfermarkt.com/samu-costa/profil/spieler/657430.
Transfer history data appended for: https://www.transfermarkt.com/lucas-robertone/profil/spieler/457221.
Transfer history data appended for: https://www.transfermarkt.com/jordi-escobar/profil/spieler/568155.
Transfer history data appended for: https://www.transfermarkt.com/ager-aketxe/profil/spieler/158057.
Transfer history data appended for: https://www.transfermarkt.com/largie-ramazani/profil/spieler/518644.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-peybernes/profil/spieler/111026.
Transfer history data appended for: https://www.transfermarkt.com/pedro-mendes/profil/spieler/498235.
Transfer history data appended for: https://www.transfermarkt.com/radosav-petrovic/profil/spieler/75296.
Transfer history data appended for: https://www.transfermarkt.com/cesar-de-la-hoz/profil/spieler/226261.
Transfer history data appended for: https://www.transfermarkt.com/arvin-appiah/profil/spieler/433257.
Transfer history data appended for: https://www.transfermarkt.com/jorge-cuenca/profil/spieler/494880.
Transfer history data appended for: https://www.transfermarkt.com/nikola-maras/profil/spieler/258475.
Transfer history data appended for: https://www.transfermarkt.com/ivan-balliu/profil/spieler/85295.
Transfer history data appended for: https://www.transfermarkt.com/joao-carvalho/profil/spieler/258005.
Transfer history data appended for: https://www.transfermarkt.com/juan-villar/profil/spieler/85500.
Transfer history data appended for: https://www.transfermarkt.com/jose-corpas/profil/spieler/379534.
Transfer history data appended for: https://www.transfermarkt.com/jose-aurelio-suarez/profil/spieler/223720.
Transfer history data appended for: https://www.transfermarkt.com/aday/profil/spieler/132921.
Transfer history data appended for: https://www.transfermarkt.com/yoel-barcenas/profil/spieler/283473.
Transfer history data appended for: https://www.transfermarkt.com/alex-pachon/profil/spieler/533110.
Transfer history data appended for: https://www.transfermarkt.com/antonio-luna/profil/spieler/126516.
Transfer history data appended for: https://www.transfermarkt.com/enric-franquesa/profil/spieler/282700.
Transfer history data appended for: https://www.transfermarkt.com/bernardo-espinosa/profil/spieler/64598.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-kebe/profil/spieler/785967.
Transfer history data appended for: https://www.transfermarkt.com/valery-fernandez/profil/spieler/331496.
Transfer history data appended for: https://www.transfermarkt.com/pau-victor/profil/spieler/707572.
Transfer history data appended for: https://www.transfermarkt.com/cristhian-stuani/profil/spieler/59323.
Transfer history data appended for: https://www.transfermarkt.com/pablo-moreno/profil/spieler/466811.
Transfer history data appended for: https://www.transfermarkt.com/ramon-terrats/profil/spieler/783396.
Transfer history data appended for: https://www.transfermarkt.com/juanpe/profil/spieler/115333.
Transfer history data appended for: https://www.transfermarkt.com/jordi-calavera/profil/spieler/286849.
Transfer history data appended for: https://www.transfermarkt.com/yan-couto/profil/spieler/627228.
Transfer history data appended for: https://www.transfermarkt.com/jonas-ramalho/profil/spieler/69660.
Transfer history data appended for: https://www.transfermarkt.com/juan-carlos/profil/spieler/120705.
Transfer history data appended for: https://www.transfermarkt.com/arijanet-muric/profil/spieler/371021.
Transfer history data appended for: https://www.transfermarkt.com/gerard-gumbau/profil/spieler/268670.
Transfer history data appended for: https://www.transfermarkt.com/monchu/profil/spieler/282727.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-bustos/profil/spieler/439629.
Transfer history data appended for: https://www.transfermarkt.com/samu-saiz/profil/spieler/131506.
Transfer history data appended for: https://www.transfermarkt.com/michael-santos/profil/spieler/178107.
Transfer history data appended for: https://www.transfermarkt.com/ivan-cuellar/profil/spieler/27493.
Transfer history data appended for: https://www.transfermarkt.com/dani-ojeda/profil/spieler/111621.
Transfer history data appended for: https://www.transfermarkt.com/rober-ibanez/profil/spieler/242532.
Transfer history data appended for: https://www.transfermarkt.com/ignasi-miquel/profil/spieler/70245.
Transfer history data appended for: https://www.transfermarkt.com/ruben-pardo/profil/spieler/99352.
Transfer history data appended for: https://www.transfermarkt.com/rodri-tarin/profil/spieler/203617.
Transfer history data appended for: https://www.transfermarkt.com/unai-bustinza/profil/spieler/156808.
Transfer history data appended for: https://www.transfermarkt.com/sergio-gonzalez/profil/spieler/308989.

Transfer history data appended for: https://www.transfermarkt.com/sabin-merino/profil/spieler/192736.
Transfer history data appended for: https://www.transfermarkt.com/miguel-de-la-fuente/profil/spieler/480883.
Transfer history data appended for: https://www.transfermarkt.com/gaku-shibasaki/profil/spieler/129693.
Transfer history data appended for: https://www.transfermarkt.com/javi-hernandez/profil/spieler/422466.
Transfer history data appended for: https://www.transfermarkt.com/kevin-bua/profil/spieler/252080.
Transfer history data appended for: https://www.transfermarkt.com/borja-baston/profil/spieler/85324.
Transfer history data appended for: https://www.transfermarkt.com/sergi-palencia/profil/spieler/268176.
Transfer history data appended for: https://www.transfermarkt.com/roberto-rosales/profil/spieler/49500.
Transfer history data appended for: https://www.transfermarkt.com/diego-conde/profil/spieler/341713.
Transfer history data appended for: https://www.transfermarkt.com/luis-perea/profil/spieler/396328.
Transfer history data appended for: https://www.transfermarkt.com/daniel-lasure/profil/spieler/336736.
Transfer history data appended for: https://www.transfermarkt.com/javier-aviles/profil/spieler/456938.
Transfer history data appended for: https://www.transfermarkt.com/javi-eraso/profil/spieler/156814.
Transfer history data appended for: https://www.transfermarkt.com/fernando-seoane/profil/spieler/70988.
Transfer history data appended for: https://www.transfermarkt.com/manu-barreiro/profil/spieler/72484.
Transfer history data appended for: https://www.transfermarkt.com/anton-quindimil/profil/spieler/781924.
Transfer history data appended for: https://www.transfermarkt.com/frederico-venancio/profil/spieler/169681.
Transfer history data appended for: https://www.transfermarkt.com/jose-angel-carrillo/profil/spieler/308982.
Transfer history data appended for: https://www.transfermarkt.com/xavi-torres/profil/spieler/65301.
Transfer history data appended for: https://www.transfermarkt.com/pedro-lopez/profil/spieler/365311.
Transfer history data appended for: https://www.transfermarkt.com/fran-vieites/profil/spieler/551182.
Transfer history data appended for: https://www.transfermarkt.com/diego-alende/profil/spieler/373683.
Transfer history data appended for: https://www.transfermarkt.com/gerard-valentin/profil/spieler/278651.
Transfer history data appended for: https://www.transfermarkt.com/edu-campabadal/profil/spieler/126722.
Transfer history data appended for: https://www.transfermarkt.com/cristian-herrera/profil/spieler/237617.
Transfer history data appended for: https://www.transfermarkt.com/luis-ruiz/profil/spieler/286020.
Transfer history data appended for: https://www.transfermarkt.com/hugo-rama/profil/spieler/510329.
Transfer history data appended for: https://www.transfermarkt.com/ander-cantero/profil/spieler/199325.
Transfer history data appended for: https://www.transfermarkt.com/alberto-varo/profil/spieler/280254.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-djalo/profil/spieler/142022.
Transfer history data appended for: https://www.transfermarkt.com/roberto-canella/profil/spieler/57785.
Transfer history data appended for: https://www.transfermarkt.com/iriome-gonzalez/profil/spieler/51519.
Transfer history data appended for: https://www.transfermarkt.com/chris-ramos/profil/spieler/538810.
Transfer history data appended for: https://www.transfermarkt.com/borja-dominguez/profil/spieler/287193.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-rodriguez/profil/spieler/425028.
Transfer history data appended for: https://www.transfermarkt.com/juanpe/profil/spieler/455066.
Transfer history data appended for: https://www.transfermarkt.com/carlos-pita/profil/spieler/34566.
Transfer history data appended for: https://www.transfermarkt.com/el-hacen/profil/spieler/321629.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-catena/profil/spieler/449796.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-velazquez/profil/spieler/189458.
Transfer history data appended for: https://www.transfermarkt.com/joni-montiel/profil/spieler/343273.
Transfer history data appended for: https://www.transfermarkt.com/jose-pozo/profil/spieler/195605.
Transfer history data appended for: https://www.transfermarkt.com/fran-garcia/profil/spieler/341264.
Transfer history data appended for: https://www.transfermarkt.com/andres-martin/profil/spieler/531277.
Transfer history data appended for: https://www.transfermarkt.com/bebe/profil/spieler/153427.
Transfer history data appended for: https://www.transfermarkt.com/esteban-saveljich/profil/spieler/240360.
Transfer history data appended for: https://www.transfermarkt.com/luca-zidane/profil/spieler/283489.
Transfer history data appended for: https://www.transfermarkt.com/yacine-qasmi/profil/spieler/93747.
Transfer history data appended for: https://www.transfermarkt.com/ivan-martos/profil/spieler/406773.
Transfer history data appended for: https://www.transfermarkt.com/stole-dimitrievski/profil/spieler/165467.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-garcia/profil/spieler/257062.
Transfer history data appended for: https://www.transfermarkt.com/mario-suarez/profil/spieler/37337.
Transfer history data appended for: https://www.transfermarkt.com/santi-comesana/profil/spieler/380598.
Transfer history data appended for: https://www.transfermarkt.com/isi-palazon/profil/spieler/362086.
Transfer history data appended for: https://www.transfermarkt.com/miguel-angel-morro/profil/spieler/607780.
Transfer history data appended for: https://www.transfermarkt.com/martin-pascual/profil/spieler/638588.
Transfer history data appended for: https://www.transfermarkt.com/alberto-garcia/profil/spieler/58497.
Transfer history data appended for: https://www.transfermarkt.com/oscar-trejo/profil/spieler/30321.
Transfer history data appended for: https://www.transfermarkt.com/antonin/profil/spieler/610336.
Transfer history data appended for: https://www.transfermarkt.com/mario-hernandez/profil/spieler/608531.
Transfer history data appended for: https://www.transfermarkt.com/oscar-valentin/profil/spieler/517753.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-ulloa/profil/spieler/54890.
Transfer history data appended for: https://www.transfermarkt.com/alberto-zapater/profil/spieler/26153.
Transfer history data appended for: https://www.transfermarkt.com/cristian-alvarez/profil/spieler/55135.
Transfer history data appended for: https://www.transfermarkt.com/inigo-eguaras/profil/spieler/89731.
Transfer history data appended for: https://www.transfermarkt.com/luca-zanimacchia/profil/spieler/407265.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-fernandez/profil/spieler/259930.
Transfer history data appended for: https://www.transfermarkt.com/javi-hernandez/profil/spieler/632893.
Transfer history data appended for: https://www.transfermarkt.com/carlos-vigaray/profil/spieler/263627.
Transfer history data appended for: https://www.transfermarkt.com/rai-nascimento/profil/spieler/483499.
Transfer history data appended for: https://www.transfermarkt.com/jair-amador/profil/spieler/128479.
Transfer history data appended for: https://www.transfermarkt.com/juanjo-narvaez/profil/spieler/213595.
Transfer history data appended for: https://www.transfermarkt.com/giorgi-papunashvili/profil/spieler/214259.
Transfer history data appended for: https://www.transfermarkt.com/pep-chavarria/profil/spieler/596122.
Transfer history data appended for: https://www.transfermarkt.com/adrian-gonzalez/profil/spieler/44073.
Transfer history data appended for: https://www.transfermarkt.com/alberto-guitian/profil/spieler/230895.
Transfer history data appended for: https://www.transfermarkt.com/james-igbekeme/profil/spieler/375849.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/alvaro-raton/profil/spieler/248551.
Transfer history data appended for: https://www.transfermarkt.com/javi-ros/profil/spieler/89330.
Transfer history data appended for: https://www.transfermarkt.com/haris-vuckic/profil/spieler/76560.
Transfer history data appended for: https://www.transfermarkt.com/pichu-atienza/profil/spieler/59337.
Transfer history data appended for: https://www.transfermarkt.com/francho-serrano/profil/spieler/632930.
Transfer history data appended for: https://www.transfermarkt.com/ivan-azon/profil/spieler/633306.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-tejero/profil/spieler/290273.
Transfer history data appended for: https://www.transfermarkt.com/jannick-buyla/profil/spieler/525891.
Transfer history data appended for: https://www.transfermarkt.com/gaizka-larrazabal/profil/spieler/439465.
Transfer history data appended for: https://www.transfermarkt.com/carlos-nieto/profil/spieler/340682.
Transfer history data appended for: https://www.transfermarkt.com/sergio-bermejo/profil/spieler/372051.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-frances/profil/spieler/632896.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-viedma/profil/spieler/331503.
Transfer history data appended for: https://www.transfermarkt.com/moussa-sidibe/profil/spieler/676922.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-pascanu/profil/spieler/421258.
Transfer history data appended for: https://www.transfermarkt.com/erik-moran/profil/spieler/67542.
Transfer history data appended for: https://www.transfermarkt.com/edward-bolanos/profil/spieler/608534.
Transfer history data appended for: https://www.transfermarkt.com/dani-romera/profil/spieler/271451.
Transfer history data appended for: https://www.transfermarkt.com/ivan-rodriguez/profil/spieler/284454.
Transfer history data appended for: https://www.transfermarkt.com/saul-crespo/profil/spieler/387557.
Transfer history data appended for: https://www.transfermarkt.com/paris-adot/profil/spieler/247583.
Transfer history data appended for: https://www.transfermarkt.com/yacouba-magagi/profil/spieler/461511.
Transfer history data appended for: https://www.transfermarkt.com/oscar-sielva/profil/spieler/67550.
Transfer history data appended for: https://www.transfermarkt.com/jose-amo/profil/spieler/311454.
Transfer history data appended for: https://www.transfermarkt.com/jose-antonio-caro/profil/spieler/268946.
Transfer history data appended for: https://www.transfermarkt.com/pablo-larrea/profil/spieler/373353.
Transfer history data appended for: https://www.transfermarkt.com/adrian-castellano/profil/spieler/253826.
Transfer history data appended for: https://www.transfermarkt.com/juergen-elitim/profil/spieler/607057.
Transfer history data appended for: https://www.transfermarkt.com/manu-garcia/profil/spieler/446289.
Transfer history data appended for: https://www.transfermarkt.com/gianfranco-gazzaniga/profil/spieler/270314.
Transfer history data appended for: https://www.transfermarkt.com/yuri/profil/spieler/22452.
Transfer history data appended for: https://www.transfermarkt.com/jose-rios/profil/spieler/81980.
Transfer history data appended for: https://www.transfermarkt.com/gaspar-panadero/profil/spieler/251883.
Transfer history data appended for: https://www.transfermarkt.com/curro-sanchez/profil/spieler/208116.
Transfer history data appended for: https://www.transfermarkt.com/carlos-doncel/profil/spieler/379530.
Transfer history data appended for: https://www.transfermarkt.com/pablo-valcarce/profil/spieler/365313.
Transfer history data appended for: https://www.transfermarkt.com/kaxe/profil/spieler/510999.
Transfer history data appended for: https://www.transfermarkt.com/manu-hernando/profil/spieler/396161.
Transfer history data appended for: https://www.transfermarkt.com/juan-aguilera/profil/spieler/75820.
Transfer history data appended for: https://www.transfermarkt.com/jesus-ruiz/profil/spieler/408288.
Transfer history data appended for: https://www.transfermarkt.com/reko/profil/spieler/290262.
Transfer history data appended for: https://www.transfermarkt.com/dani-jimenez/profil/spieler/126509.
Transfer history data appended for: https://www.transfermarkt.com/aitor-gonzalez/profil/spieler/716157.
Transfer history data appended for: https://www.transfermarkt.com/ernesto-gomez/profil/spieler/288460.
Transfer history data appended for: https://www.transfermarkt.com/oscar-arribas/profil/spieler/476104.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-escardo/profil/spieler/464899.
Transfer history data appended for: https://www.transfermarkt.com/laure/profil/spieler/57876.
Transfer history data appended for: https://www.transfermarkt.com/juanma-bravo/profil/spieler/475833.
Transfer history data appended for: https://www.transfermarkt.com/jose-leon/profil/spieler/281773.
Transfer history data appended for: https://www.transfermarkt.com/javi-castro/profil/spieler/740253.
Transfer history data appended for: https://www.transfermarkt.com/richard-boateng/profil/spieler/198400.
Transfer history data appended for: https://www.transfermarkt.com/jose-carlos-ramirez/profil/spieler/319541.
Transfer history data appended for: https://www.transfermarkt.com/marc-gual/profil/spieler/376486.
Transfer history data appended for: https://www.transfermarkt.com/hugo-fraile/profil/spieler/72201.
Transfer history data appended for: https://www.transfermarkt.com/ander-gorostidi/profil/spieler/450258.
Transfer history data appended for: https://www.transfermarkt.com/fidel-escobar/profil/spieler/345716.
Transfer history data appended for: https://www.transfermarkt.com/samuel-casado/profil/spieler/388888.
Transfer history data appended for: https://www.transfermarkt.com/victor-garcia/profil/spieler/195762.
Transfer history data appended for: https://www.transfermarkt.com/guito/profil/spieler/783879.
Transfer history data appended for: https://www.transfermarkt.com/david-fernandez/profil/spieler/59371.
Transfer history data appended for: https://www.transfermarkt.com/samuel-sosa/profil/spieler/428210.
Transfer history data appended for: https://www.transfermarkt.com/carlos-bellvis/profil/spieler/51550.
Transfer history data appended for: https://www.transfermarkt.com/carlos-carmona/profil/spieler/71394.
Transfer history data appended for: https://www.transfermarkt.com/alex-zalaya/profil/spieler/335226.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-vazquez/profil/spieler/141835.
Transfer history data appended for: https://www.transfermarkt.com/pablo-garcia/profil/spieler/636300.
Transfer history data appended for: https://www.transfermarkt.com/jose-gragera/profil/spieler/557147.
Transfer history data appended for: https://www.transfermarkt.com/pablo-perez/profil/spieler/238717.
Transfer history data appended for: https://www.transfermarkt.com/nacho-mendez/profil/spieler/503837.
Transfer history data appended for: https://www.transfermarkt.com/marc-valiente/profil/spieler/53301.
Transfer history data appended for: https://www.transfermarkt.com/christian-sanchez/profil/spieler/531373.
Transfer history data appended for: https://www.transfermarkt.com/gaspar-campos/profil/spieler/580525.
Transfer history data appended for: https://www.transfermarkt.com/uros-djurdjevic/profil/spieler/190804.
Transfer history data appended for: https://www.transfermarkt.com/saul-garcia/profil/spieler/249471.
Transfer history data appended for: https://www.transfermarkt.com/cristian-salvador/profil/spieler/224774.
Transfer history data appended for: https://www.transfermarkt.com/nikola-cumic/profil/spieler/368982.
Transfer history data appended for: https://www.transfermarkt.com/diego-marino/profil/spieler/59349.
Transfer history data appended for: https://www.transfermarkt.com/manu-garcia/profil/spieler/277118.
Transfer history data appended for: https://www.transfermarkt.com/pelayo-suarez/profil/spieler/311665.
Transfer history data appended for: https://www.transfermarkt.com/aitor-garcia/profil/spieler/214468.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-milovanov/profil/spieler/392655.

Transfer history data appended for: https://www.transfermarkt.com/pedro-diaz/profil/spieler/363057.
Transfer history data appended for: https://www.transfermarkt.com/borja-lopez/profil/spieler/214770.
Transfer history data appended for: https://www.transfermarkt.com/javi-fuego/profil/spieler/56134.
Transfer history data appended for: https://www.transfermarkt.com/neftali-manzambi/profil/spieler/211453.
Transfer history data appended for: https://www.transfermarkt.com/fran-garcia/profil/spieler/152284.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-gomez/profil/spieler/577489.
Transfer history data appended for: https://www.transfermarkt.com/roman-zozulya/profil/spieler/70767.
Transfer history data appended for: https://www.transfermarkt.com/karim-azamoum/profil/spieler/275361.
Transfer history data appended for: https://www.transfermarkt.com/chema-nunez/profil/spieler/434660.
Transfer history data appended for: https://www.transfermarkt.com/flavien-boyomo/profil/spieler/541555.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-gorosito/profil/spieler/125281.
Transfer history data appended for: https://www.transfermarkt.com/alberto-benito/profil/spieler/263748.
Transfer history data appended for: https://www.transfermarkt.com/tomeu-nadal/profil/spieler/88397.
Transfer history data appended for: https://www.transfermarkt.com/david-del-pozo/profil/spieler/372050.
Transfer history data appended for: https://www.transfermarkt.com/javi-jimenez/profil/spieler/251860.
Transfer history data appended for: https://www.transfermarkt.com/ivan-kecojevic/profil/spieler/69005.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-jimenez/profil/spieler/282406.
Transfer history data appended for: https://www.transfermarkt.com/alfredo-ortuno/profil/spieler/96540.
Transfer history data appended for: https://www.transfermarkt.com/carlos-isaac/profil/spieler/396324.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-pena/profil/spieler/156887.
Transfer history data appended for: https://www.transfermarkt.com/bernabe-barragan/profil/spieler/254036.
Transfer history data appended for: https://www.transfermarkt.com/pape-maly-diamanka/profil/spieler/176610.
Transfer history data appended for: https://www.transfermarkt.com/jean-jules/profil/spieler/607377.
Transfer history data appended for: https://www.transfermarkt.com/manu-fuster/profil/spieler/511021.
Transfer history data appended for: https://www.transfermarkt.com/liberto-beltran/profil/spieler/355763.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-arroyo/profil/spieler/681708.
Transfer history data appended for: https://www.transfermarkt.com/javi-navarro/profil/spieler/682500.
Transfer history data appended for: https://www.transfermarkt.com/diego-caballo/profil/spieler/162036.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-arroyo/profil/spieler/138662.
Transfer history data appended for: https://www.transfermarkt.com/damian-petcoff/profil/spieler/185551.
Transfer history data appended for: https://www.transfermarkt.com/jon-errasti/profil/spieler/158849.
Transfer history data appended for: https://www.transfermarkt.com/alex-perez/profil/spieler/167830.
Transfer history data appended for: https://www.transfermarkt.com/rajiv-van-la-parra/profil/spieler/77001.
Transfer history data appended for: https://www.transfermarkt.com/jaime-sierra/profil/spieler/398159.
Transfer history data appended for: https://www.transfermarkt.com/inaki-saenz/profil/spieler/174972.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-bogusz/profil/spieler/431475.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-arnedo/profil/spieler/412927.
Transfer history data appended for: https://www.transfermarkt.com/pablo-bobadilla/profil/spieler/430227.
Transfer history data appended for: https://www.transfermarkt.com/ruben-martinez/profil/spieler/65262.
Transfer history data appended for: https://www.transfermarkt.com/andoni-lopez/profil/spieler/340206.
Transfer history data appended for: https://www.transfermarkt.com/zelu/profil/spieler/231980.
Transfer history data appended for: https://www.transfermarkt.com/ousama-siddiki/profil/spieler/409472.
Transfer history data appended for: https://www.transfermarkt.com/paulino-de-la-fuente/profil/spieler/261502.
Transfer history data appended for: https://www.transfermarkt.com/unai-medina/profil/spieler/104234.
Transfer history data appended for: https://www.transfermarkt.com/enrique-clemente/profil/spieler/487951.
Transfer history data appended for: https://www.transfermarkt.com/roberto-santamaria/profil/spieler/35541.
Transfer history data appended for: https://www.transfermarkt.com/ander-vitoria/profil/spieler/156864.
Transfer history data appended for: https://www.transfermarkt.com/gorka-perez/profil/spieler/383114.
Transfer history data appended for: https://www.transfermarkt.com/iago-lopez/profil/spieler/572299.
Transfer history data appended for: https://www.transfermarkt.com/lander-olaetxea/profil/spieler/377795.
Transfer history data appended for: https://www.transfermarkt.com/andy-rodriguez/profil/spieler/252686.
Transfer history data appended for: https://www.transfermarkt.com/ruben-mino/profil/spieler/65266.
Transfer history data appended for: https://www.transfermarkt.com/yaroslav-meykher/profil/spieler/574213.
Transfer history data appended for: https://www.transfermarkt.com/martin-lapena/profil/spieler/622993.
Transfer history data appended for: https://www.transfermarkt.com/roni/profil/spieler/348552.
Transfer history data appended for: https://www.transfermarkt.com/gorka-guruzeta/profil/spieler/340205.
Transfer history data appended for: https://www.transfermarkt.com/jesus-olmo/profil/spieler/39058.
Transfer history data appended for: https://www.transfermarkt.com/heber-pena/profil/spieler/275020.
Transfer history data appended for: https://www.transfermarkt.com/david-astals/profil/spieler/727578.
Transfer history data appended for: https://www.transfermarkt.com/adri-cuevas/profil/spieler/168773.
Transfer history data appended for: https://www.transfermarkt.com/iker-undabarrena/profil/spieler/181113.
Transfer history data appended for: https://www.transfermarkt.com/froilan-leal/profil/spieler/815002.
Transfer history data appended for: https://www.transfermarkt.com/aleix-coch/profil/spieler/152975.
Transfer history data appended for: https://www.transfermarkt.com/grego-sierra/profil/spieler/253905.
Transfer history data appended for: https://www.transfermarkt.com/pedro-capo/profil/spieler/131357.
Transfer history data appended for: https://www.transfermarkt.com/angel-martinez/profil/spieler/45652.
Transfer history data appended for: https://www.transfermarkt.com/xavi-boniquet/profil/spieler/127552.
Transfer history data appended for: https://www.transfermarkt.com/stoichkov/profil/spieler/271021.
Transfer history data appended for: https://www.transfermarkt.com/diego-fuoli/profil/spieler/531274.
Transfer history data appended for: https://www.transfermarkt.com/juan-ibiza/profil/spieler/411294.
Transfer history data appended for: https://www.transfermarkt.com/edgar-hernandez/profil/spieler/104236.
Transfer history data appended for: https://www.transfermarkt.com/aaron-rey/profil/spieler/430192.
Transfer history data appended for: https://www.transfermarkt.com/pierre-cornud/profil/spieler/536156.
Transfer history data appended for: https://www.transfermarkt.com/antonio-romero/profil/spieler/268963.
Transfer history data appended for: https://www.transfermarkt.com/ian-mackay/profil/spieler/88917.
Transfer history data appended for: https://www.transfermarkt.com/nestor-querol/profil/spieler/441290.
Transfer history data appended for: https://www.transfermarkt.com/juan-hernandez/profil/spieler/349873.
Transfer history data appended for: https://www.transfermarkt.com/oscar-rubio/profil/spieler/57999.
Transfer history data appended for: https://www.transfermarkt.com/victor-garcia/profil/spieler/590690.
Transfer history data appended for: https://www.transfermarkt.com/josu-ozkoidi/profil/spieler/89332.

Transfer history data appended for: https://www.transfermarkt.com/jaime-sanchez/profil/spieler/212863.
Transfer history data appended for: https://www.transfermarkt.com/christian-rivera/profil/spieler/374077.
Transfer history data appended for: https://www.transfermarkt.com/javi-castellano/profil/spieler/65489.
Transfer history data appended for: https://www.transfermarkt.com/cristian-cedres/profil/spieler/261493.
Transfer history data appended for: https://www.transfermarkt.com/eric-curbelo/profil/spieler/390823.
Transfer history data appended for: https://www.transfermarkt.com/claudio-mendes/profil/spieler/699501.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-valles/profil/spieler/417913.
Transfer history data appended for: https://www.transfermarkt.com/dani-castellano/profil/spieler/64363.
Transfer history data appended for: https://www.transfermarkt.com/pietro-iemmello/profil/spieler/62735.
Transfer history data appended for: https://www.transfermarkt.com/ale-diez/profil/spieler/217143.
Transfer history data appended for: https://www.transfermarkt.com/enzo-loiodice/profil/spieler/581781.
Transfer history data appended for: https://www.transfermarkt.com/aythami-artiles/profil/spieler/44735.
Transfer history data appended for: https://www.transfermarkt.com/raul-fernandez/profil/spieler/54217.
Transfer history data appended for: https://www.transfermarkt.com/ismael-athuman/profil/spieler/351204.
Transfer history data appended for: https://www.transfermarkt.com/sergio-ruiz/profil/spieler/394694.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-lemos/profil/spieler/230222.
Transfer history data appended for: https://www.transfermarkt.com/alex-dominguez/profil/spieler/524937.
Transfer history data appended for: https://www.transfermarkt.com/rober-gonzalez/profil/spieler/505675.
Transfer history data appended for: https://www.transfermarkt.com/oscar-clemente/profil/spieler/396340.
Transfer history data appended for: https://www.transfermarkt.com/benito-ramirez/profil/spieler/282672.
Transfer history data appended for: https://www.transfermarkt.com/edu-espiau/profil/spieler/565523.
Transfer history data appended for: https://www.transfermarkt.com/ariday-cabrera/profil/spieler/76032.
Transfer history data appended for: https://www.transfermarkt.com/fabio-gonzalez/profil/spieler/531062.
Transfer history data appended for: https://www.transfermarkt.com/alex-suarez/profil/spieler/510396.
Transfer history data appended for: https://www.transfermarkt.com/jonathan/profil/spieler/579346.
Transfer history data appended for: https://www.transfermarkt.com/kirian-rodriguez/profil/spieler/566574.
Transfer history data appended for: https://www.transfermarkt.com/maikel-mesa/profil/spieler/197576.
Transfer history data appended for: https://www.transfermarkt.com/pejino/profil/spieler/534379.
Transfer history data appended for: https://www.transfermarkt.com/dragan-rosic/profil/spieler/374055.
Transfer history data appended for: https://www.transfermarkt.com/cristobal-marquez/profil/spieler/72281.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-aguado/profil/spieler/449496.
Transfer history data appended for: https://www.transfermarkt.com/alex-mula/profil/spieler/242295.
Transfer history data appended for: https://www.transfermarkt.com/cristian-glauder/profil/spieler/380365.
Transfer history data appended for: https://www.transfermarkt.com/pol-valentin/profil/spieler/380737.
Transfer history data appended for: https://www.transfermarkt.com/franchu/profil/spieler/458466.
Transfer history data appended for: https://www.transfermarkt.com/javier-belman/profil/spieler/422459.
Transfer history data appended for: https://www.transfermarkt.com/aboubakary-kante/profil/spieler/315095.
Transfer history data appended for: https://www.transfermarkt.com/pathe-ciss/profil/spieler/525578.
Transfer history data appended for: https://www.transfermarkt.com/randy-nteka/profil/spieler/560483.
Transfer history data appended for: https://www.transfermarkt.com/jano/profil/spieler/94096.
Transfer history data appended for: https://www.transfermarkt.com/moi-delgado/profil/spieler/260230.
Transfer history data appended for: https://www.transfermarkt.com/aldair-fuentes/profil/spieler/480523.
Transfer history data appended for: https://www.transfermarkt.com/sekou-gassama/profil/spieler/337070.
Transfer history data appended for: https://www.transfermarkt.com/mikel-iribas/profil/spieler/76276.
Transfer history data appended for: https://www.transfermarkt.com/pol-freixanet/profil/spieler/200612.
Transfer history data appended for: https://www.transfermarkt.com/tahiru-awudu/profil/spieler/579649.
Transfer history data appended for: https://www.transfermarkt.com/ruben-pulido/profil/spieler/603969.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-sotillos/profil/spieler/396157.
Transfer history data appended for: https://www.transfermarkt.com/pinchi/profil/spieler/413502.
Transfer history data appended for: https://www.transfermarkt.com/juanma/profil/spieler/45773.
Transfer history data appended for: https://www.transfermarkt.com/adrian-dieguez/profil/spieler/355335.
Transfer history data appended for: https://www.transfermarkt.com/iban-salvador/profil/spieler/250358.
Transfer history data appended for: https://www.transfermarkt.com/artur-pikk/profil/spieler/133593.
Transfer history data appended for: https://www.transfermarkt.com/nana-boateng/profil/spieler/236272.
Transfer history data appended for: https://www.transfermarkt.com/usman-sale/profil/spieler/420081.
Transfer history data appended for: https://www.transfermarkt.com/otso-virtanen/profil/spieler/201623.
Transfer history data appended for: https://www.transfermarkt.com/tabi-manga/profil/spieler/346163.
Transfer history data appended for: https://www.transfermarkt.com/bruno-rodrigues/profil/spieler/397379.
Transfer history data appended for: https://www.transfermarkt.com/rangel/profil/spieler/442784.
Transfer history data appended for: https://www.transfermarkt.com/taneli-heiskanen/profil/spieler/565104.
Transfer history data appended for: https://www.transfermarkt.com/juho-pirttijoki/profil/spieler/322596.
Transfer history data appended for: https://www.transfermarkt.com/saku-savolainen/profil/spieler/274746.
Transfer history data appended for: https://www.transfermarkt.com/ats-purje/profil/spieler/42793.
Transfer history data appended for: https://www.transfermarkt.com/jiri-nissinen/profil/spieler/354483.
Transfer history data appended for: https://www.transfermarkt.com/urho-nissila/profil/spieler/354114.
Transfer history data appended for: https://www.transfermarkt.com/petteri-pennanen/profil/spieler/47703.
Transfer history data appended for: https://www.transfermarkt.com/pedro-vitor/profil/spieler/605326.
Transfer history data appended for: https://www.transfermarkt.com/ville-saxman/profil/spieler/137578.
Transfer history data appended for: https://www.transfermarkt.com/aleksi-honka-hallila/profil/spieler/565106.
Transfer history data appended for: https://www.transfermarkt.com/igors-tarasovs/profil/spieler/84985.
Transfer history data appended for: https://www.transfermarkt.com/arttu-heinonen/profil/spieler/511780.
Transfer history data appended for: https://www.transfermarkt.com/issa-thiaw/profil/spieler/337941.
Transfer history data appended for: https://www.transfermarkt.com/hemmo-riihimaki/profil/spieler/586591.
Transfer history data appended for: https://www.transfermarkt.com/aniekpeno-udoh/profil/spieler/420080.
Transfer history data appended for: https://www.transfermarkt.com/joel-vartiainen/profil/spieler/228287.
Transfer history data appended for: https://www.transfermarkt.com/tommi-jyry/profil/spieler/464308.
Transfer history data appended for: https://www.transfermarkt.com/taneli-hamalainen/profil/spieler/567485.
Transfer history data appended for: https://www.transfermarkt.com/nuno-tomas/profil/spieler/347204.
Transfer history data appended for: https://www.transfermarkt.com/viljami-aittokoski/profil/spieler/581127.
Transfer history data appended for: https://www.transfermarkt.com/albert-vauhkonen/profil/spieler/567457.

Transfer history data appended for: https://www.transfermarkt.com/oskari-sallinen/profil/spieler/487534.
Transfer history data appended for: https://www.transfermarkt.com/jasin-assehnoun/profil/spieler/419828.
Transfer history data appended for: https://www.transfermarkt.com/joona-tiainen/profil/spieler/433847.
Transfer history data appended for: https://www.transfermarkt.com/lassi-forss/profil/spieler/593049.
Transfer history data appended for: https://www.transfermarkt.com/teemu-jantti/profil/spieler/371799.
Transfer history data appended for: https://www.transfermarkt.com/salifu-senghore/profil/spieler/613083.
Transfer history data appended for: https://www.transfermarkt.com/mikko-viitikko/profil/spieler/190453.
Transfer history data appended for: https://www.transfermarkt.com/kari-arkivuo/profil/spieler/25357.
Transfer history data appended for: https://www.transfermarkt.com/altin-zeqiri/profil/spieler/508780.
Transfer history data appended for: https://www.transfermarkt.com/timi-lahti/profil/spieler/88250.
Transfer history data appended for: https://www.transfermarkt.com/patrick-rakovsky/profil/spieler/85201.
Transfer history data appended for: https://www.transfermarkt.com/eemeli-virta/profil/spieler/425392.
Transfer history data appended for: https://www.transfermarkt.com/arlind-sejdiu/profil/spieler/488780.
Transfer history data appended for: https://www.transfermarkt.com/matias-niuta/profil/spieler/563862.
Transfer history data appended for: https://www.transfermarkt.com/mikko-kuningas/profil/spieler/351993.
Transfer history data appended for: https://www.transfermarkt.com/arttu-auranen/profil/spieler/487539.
Transfer history data appended for: https://www.transfermarkt.com/pyry-lampinen/profil/spieler/600047.
Transfer history data appended for: https://www.transfermarkt.com/tim-martinen/profil/spieler/489110.
Transfer history data appended for: https://www.transfermarkt.com/tapio-torpo/profil/spieler/678446.
Transfer history data appended for: https://www.transfermarkt.com/henritse-eninful/profil/spieler/167549.
Transfer history data appended for: https://www.transfermarkt.com/jean-christophe-coubronne/profil/spieler/111042.
Transfer history data appended for: https://www.transfermarkt.com/matti-klinga/profil/spieler/188275.
Transfer history data appended for: https://www.transfermarkt.com/valdrin-rashica/profil/spieler/409109.
Transfer history data appended for: https://www.transfermarkt.com/vahid-hambo/profil/spieler/190427.
Transfer history data appended for: https://www.transfermarkt.com/viljami-isotalo/profil/spieler/419824.
Transfer history data appended for: https://www.transfermarkt.com/dimitry-imbongo/profil/spieler/81533.
Transfer history data appended for: https://www.transfermarkt.com/juuso-hamalainen/profil/spieler/228650.
Transfer history data appended for: https://www.transfermarkt.com/noah-nurmi/profil/spieler/488763.
Transfer history data appended for: https://www.transfermarkt.com/filip-valencic/profil/spieler/101379.
Transfer history data appended for: https://www.transfermarkt.com/kevin-kouassivi-benissan/profil/spieler/363715.
Transfer history data appended for: https://www.transfermarkt.com/liliu/profil/spieler/139006.
Transfer history data appended for: https://www.transfermarkt.com/elias-mastokangas/profil/spieler/422033.
Transfer history data appended for: https://www.transfermarkt.com/timo-furuholm/profil/spieler/49278.
Transfer history data appended for: https://www.transfermarkt.com/henrik-moisander/profil/spieler/5019.
Transfer history data appended for: https://www.transfermarkt.com/taiki-kagayama/profil/spieler/668118.
Transfer history data appended for: https://www.transfermarkt.com/jesper-engstrom/profil/spieler/103388.
Transfer history data appended for: https://www.transfermarkt.com/roope-kantola/profil/spieler/593091.
Transfer history data appended for: https://www.transfermarkt.com/rick-ketting/profil/spieler/309843.
Transfer history data appended for: https://www.transfermarkt.com/aleksi-paananen/profil/spieler/131772.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-kallman/profil/spieler/322990.
Transfer history data appended for: https://www.transfermarkt.com/arttu-hoskonen/profil/spieler/390646.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-muniz/profil/spieler/75888.
Transfer history data appended for: https://www.transfermarkt.com/jan-heinonen/profil/spieler/652403.
Transfer history data appended for: https://www.transfermarkt.com/martti-haukioja/profil/spieler/419584.
Transfer history data appended for: https://www.transfermarkt.com/aati-marttinen/profil/spieler/357128.
Transfer history data appended for: https://www.transfermarkt.com/matias-ojala/profil/spieler/109529.
Transfer history data appended for: https://www.transfermarkt.com/connor-ruane/profil/spieler/291239.
Transfer history data appended for: https://www.transfermarkt.com/juho-makela/profil/spieler/26223.
Transfer history data appended for: https://www.transfermarkt.com/jere-kallinen/profil/spieler/713140.
Transfer history data appended for: https://www.transfermarkt.com/anselmi-nurmela/profil/spieler/228825.
Transfer history data appended for: https://www.transfermarkt.com/juuso-sarkela/profil/spieler/363711.
Transfer history data appended for: https://www.transfermarkt.com/loorents-hertsi/profil/spieler/146273.
Transfer history data appended for: https://www.transfermarkt.com/otso-liimatta/profil/spieler/718152.
Transfer history data appended for: https://www.transfermarkt.com/lassi-nurmos/profil/spieler/188413.
Transfer history data appended for: https://www.transfermarkt.com/alexander-jibrin/profil/spieler/484843.
Transfer history data appended for: https://www.transfermarkt.com/kaapo-kemila/profil/spieler/646409.
Transfer history data appended for: https://www.transfermarkt.com/nestori-kekonen/profil/spieler/679785.
Transfer history data appended for: https://www.transfermarkt.com/daniel-rantanen/profil/spieler/322082.
Transfer history data appended for: https://www.transfermarkt.com/jusif-ali/profil/spieler/433892.
Transfer history data appended for: https://www.transfermarkt.com/samuli-leppala/profil/spieler/363712.
Transfer history data appended for: https://www.transfermarkt.com/christian-bohui/profil/spieler/425389.
Transfer history data appended for: https://www.transfermarkt.com/jere-aallikko/profil/spieler/263897.
Transfer history data appended for: https://www.transfermarkt.com/niklas-jokelainen/profil/spieler/350006.
Transfer history data appended for: https://www.transfermarkt.com/henrik-olander/profil/spieler/356634.
Transfer history data appended for: https://www.transfermarkt.com/aapo-heikkila/profil/spieler/263898.
Transfer history data appended for: https://www.transfermarkt.com/joona-lohela/profil/spieler/707056.
Transfer history data appended for: https://www.transfermarkt.com/rafinha/profil/spieler/47931.
Transfer history data appended for: https://www.transfermarkt.com/miika-koskela/profil/spieler/609402.
Transfer history data appended for: https://www.transfermarkt.com/lasse-ikonen/profil/spieler/647542.
Transfer history data appended for: https://www.transfermarkt.com/kristian-heinolainen/profil/spieler/363704.
Transfer history data appended for: https://www.transfermarkt.com/tommi-lindholm/profil/spieler/225090.
Transfer history data appended for: https://www.transfermarkt.com/fareed-sadat/profil/spieler/354246.
Transfer history data appended for: https://www.transfermarkt.com/juhani-pennanen/profil/spieler/173574.
Transfer history data appended for: https://www.transfermarkt.com/sami-karjalainen/profil/spieler/150958.
Transfer history data appended for: https://www.transfermarkt.com/samuel-kurttila/profil/spieler/425390.
Transfer history data appended for: https://www.transfermarkt.com/otto-ollikainen/profil/spieler/518321.
Transfer history data appended for: https://www.transfermarkt.com/jonas-levanen/profil/spieler/261081.
Transfer history data appended for: https://www.transfermarkt.com/lucas-kaufmann/profil/spieler/241358.
Transfer history data appended for: https://www.transfermarkt.com/dani-hatakka/profil/spieler/172291.
Transfer history data appended for: https://www.transfermarkt.com/jerry-voutilainen/profil/spieler/190456.

Transfer history data appended for: https://www.transfermarkt.com/konsta-rasimus/profil/spieler/97536.
Transfer history data appended for: https://www.transfermarkt.com/duarte-tammilehto/profil/spieler/108584.
Transfer history data appended for: https://www.transfermarkt.com/demba-savage/profil/spieler/49523.
Transfer history data appended for: https://www.transfermarkt.com/nasiru-banahene/profil/spieler/579504.
Transfer history data appended for: https://www.transfermarkt.com/tim-murray/profil/spieler/148169.
Transfer history data appended for: https://www.transfermarkt.com/edmund-arko-mensah/profil/spieler/543492.
Transfer history data appended for: https://www.transfermarkt.com/henri-aalto/profil/spieler/73722.
Transfer history data appended for: https://www.transfermarkt.com/markus-uusitalo/profil/spieler/296271.
Transfer history data appended for: https://www.transfermarkt.com/jean-marie-dongou/profil/spieler/166666.
Transfer history data appended for: https://www.transfermarkt.com/juan-alegria/profil/spieler/662452.
Transfer history data appended for: https://www.transfermarkt.com/tapio-heikkila/profil/spieler/47957.
Transfer history data appended for: https://www.transfermarkt.com/rui-modesto/profil/spieler/671799.
Transfer history data appended for: https://www.transfermarkt.com/borjas-martin/profil/spieler/334850.
Transfer history data appended for: https://www.transfermarkt.com/macoumba-kandji/profil/spieler/59755.
Transfer history data appended for: https://www.transfermarkt.com/javi-hervas/profil/spieler/184218.
Transfer history data appended for: https://www.transfermarkt.com/zakaria-beglarishvili/profil/spieler/139040.
Transfer history data appended for: https://www.transfermarkt.com/kimi-kolsi/profil/spieler/647536.
Transfer history data appended for: https://www.transfermarkt.com/michael-ogungbaro/profil/spieler/369695.
Transfer history data appended for: https://www.transfermarkt.com/david-onyeanula/profil/spieler/683824.
Transfer history data appended for: https://www.transfermarkt.com/juuso-anttila/profil/spieler/593077.
Transfer history data appended for: https://www.transfermarkt.com/miika-kolsi/profil/spieler/564622.
Transfer history data appended for: https://www.transfermarkt.com/hindrek-ojamaa/profil/spieler/149534.
Transfer history data appended for: https://www.transfermarkt.com/david-ramadingaye/profil/spieler/54798.
Transfer history data appended for: https://www.transfermarkt.com/niklas-leinonen/profil/spieler/672460.
Transfer history data appended for: https://www.transfermarkt.com/roger-bonet/profil/spieler/382956.
Transfer history data appended for: https://www.transfermarkt.com/paavo-voutilainen/profil/spieler/348160.
Transfer history data appended for: https://www.transfermarkt.com/thomas-agyiri/profil/spieler/241546.
Transfer history data appended for: https://www.transfermarkt.com/tuomas-ollila/profil/spieler/433887.
Transfer history data appended for: https://www.transfermarkt.com/asier-arranz/profil/spieler/51709.
Transfer history data appended for: https://www.transfermarkt.com/matias-paavola/profil/spieler/492547.
Transfer history data appended for: https://www.transfermarkt.com/antti-makijarvi/profil/spieler/131771.
Transfer history data appended for: https://www.transfermarkt.com/anton-eerola/profil/spieler/484524.
Transfer history data appended for: https://www.transfermarkt.com/pyry-piirainen/profil/spieler/484757.
Transfer history data appended for: https://www.transfermarkt.com/anton-lepola/profil/spieler/239842.
Transfer history data appended for: https://www.transfermarkt.com/matias-lindfors/profil/spieler/296260.
Transfer history data appended for: https://www.transfermarkt.com/mika/profil/spieler/240031.
Transfer history data appended for: https://www.transfermarkt.com/jyri-kiuru/profil/spieler/433895.
Transfer history data appended for: https://www.transfermarkt.com/ville-tikkanen/profil/spieler/482004.
Transfer history data appended for: https://www.transfermarkt.com/robin-sid/profil/spieler/224731.
Transfer history data appended for: https://www.transfermarkt.com/matej-hradecky/profil/spieler/214075.
Transfer history data appended for: https://www.transfermarkt.com/samba-benga/profil/spieler/367645.
Transfer history data appended for: https://www.transfermarkt.com/jeremiah-streng/profil/spieler/488781.
Transfer history data appended for: https://www.transfermarkt.com/aatu-kujanpaa/profil/spieler/407660.
Transfer history data appended for: https://www.transfermarkt.com/denys-oliynyk/profil/spieler/57895.
Transfer history data appended for: https://www.transfermarkt.com/murilo/profil/spieler/716576.
Transfer history data appended for: https://www.transfermarkt.com/daniel-hakans/profil/spieler/448284.
Transfer history data appended for: https://www.transfermarkt.com/jake-jervis/profil/spieler/129074.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-ledesma/profil/spieler/62247.
Transfer history data appended for: https://www.transfermarkt.com/ariel-ngueukam/profil/spieler/224398.
Transfer history data appended for: https://www.transfermarkt.com/anel-rashkaj/profil/spieler/59569.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-el-moutacim/profil/spieler/510714.
Transfer history data appended for: https://www.transfermarkt.com/joonas-sundman/profil/spieler/275203.
Transfer history data appended for: https://www.transfermarkt.com/niko-markkula/profil/spieler/73827.
Transfer history data appended for: https://www.transfermarkt.com/tero-mantyla/profil/spieler/106288.
Transfer history data appended for: https://www.transfermarkt.com/serge-atakayi/profil/spieler/333275.
Transfer history data appended for: https://www.transfermarkt.com/jesse-ost/profil/spieler/93456.
Transfer history data appended for: https://www.transfermarkt.com/darvin-chavez/profil/spieler/91417.
Transfer history data appended for: https://www.transfermarkt.com/joonas-lepisto/profil/spieler/407662.
Transfer history data appended for: https://www.transfermarkt.com/matias-vainionpaa/profil/spieler/520264.
Transfer history data appended for: https://www.transfermarkt.com/keaton-isaksson/profil/spieler/273180.
Transfer history data appended for: https://www.transfermarkt.com/nikko-boxall/profil/spieler/185195.
Transfer history data appended for: https://www.transfermarkt.com/jude-arthur/profil/spieler/539768.
Transfer history data appended for: https://www.transfermarkt.com/walter-viitala/profil/spieler/181061.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-schuller/profil/spieler/72266.
Transfer history data appended for: https://www.transfermarkt.com/ferhan-hasani/profil/spieler/151582.
Transfer history data appended for: https://www.transfermarkt.com/daniel-oshaughnessy/profil/spieler/131967.
Transfer history data appended for: https://www.transfermarkt.com/markus-halsti/profil/spieler/37293.
Transfer history data appended for: https://www.transfermarkt.com/roope-riski/profil/spieler/107577.
Transfer history data appended for: https://www.transfermarkt.com/pyry-hannola/profil/spieler/467289.
Transfer history data appended for: https://www.transfermarkt.com/eetu-vertainen/profil/spieler/433685.
Transfer history data appended for: https://www.transfermarkt.com/ivan-ostojic/profil/spieler/223058.
Transfer history data appended for: https://www.transfermarkt.com/bubacar-djalo/profil/spieler/340529.
Transfer history data appended for: https://www.transfermarkt.com/atomu-tanaka/profil/spieler/79345.
Transfer history data appended for: https://www.transfermarkt.com/nikolai-alho/profil/spieler/131745.
Transfer history data appended for: https://www.transfermarkt.com/lucas-lingman/profil/spieler/322994.
Transfer history data appended for: https://www.transfermarkt.com/tim-vayrynen/profil/spieler/131786.
Transfer history data appended for: https://www.transfermarkt.com/henri-toivomaki/profil/spieler/46993.
Transfer history data appended for: https://www.transfermarkt.com/valtteri-moren/profil/spieler/123595.
Transfer history data appended for: https://www.transfermarkt.com/santeri-vaananen/profil/spieler/564621.
Transfer history data appended for: https://www.transfermarkt.com/luis-carlos-murillo/profil/spieler/173299.

Transfer history data appended for: https://www.transfermarkt.com/miro-tenho/profil/spieler/273064.
Transfer history data appended for: https://www.transfermarkt.com/matti-peltola/profil/spieler/592379.
Transfer history data appended for: https://www.transfermarkt.com/david-browne/profil/spieler/215987.
Transfer history data appended for: https://www.transfermarkt.com/hugo-keto/profil/spieler/320053.
Transfer history data appended for: https://www.transfermarkt.com/antonio-reguero/profil/spieler/71130.
Transfer history data appended for: https://www.transfermarkt.com/gustaf-backaliden/profil/spieler/362893.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-bilonog/profil/spieler/204348.
Transfer history data appended for: https://www.transfermarkt.com/saku-ylatupa/profil/spieler/344836.
Transfer history data appended for: https://www.transfermarkt.com/niilo-maenpaa/profil/spieler/322997.
Transfer history data appended for: https://www.transfermarkt.com/joel-karlstrom/profil/spieler/429158.
Transfer history data appended for: https://www.transfermarkt.com/mikko-sumusalo/profil/spieler/54802.
Transfer history data appended for: https://www.transfermarkt.com/marc-nordqvist/profil/spieler/333273.
Transfer history data appended for: https://www.transfermarkt.com/peter-makrillos/profil/spieler/187364.
Transfer history data appended for: https://www.transfermarkt.com/yanga-baliso/profil/spieler/357354.
Transfer history data appended for: https://www.transfermarkt.com/akseli-pelvas/profil/spieler/47784.
Transfer history data appended for: https://www.transfermarkt.com/johannes-laaksonen/profil/spieler/109671.
Transfer history data appended for: https://www.transfermarkt.com/riku-sjoroos/profil/spieler/190446.
Transfer history data appended for: https://www.transfermarkt.com/lassi-jarvenpaa/profil/spieler/356631.
Transfer history data appended for: https://www.transfermarkt.com/aapo-maenpaa/profil/spieler/322996.
Transfer history data appended for: https://www.transfermarkt.com/oskari-forsman/profil/spieler/49277.
Transfer history data appended for: https://www.transfermarkt.com/frankline-okoye/profil/spieler/580244.
Transfer history data appended for: https://www.transfermarkt.com/maximo-tolonen/profil/spieler/406700.
Transfer history data appended for: https://www.transfermarkt.com/albion-ademi/profil/spieler/348643.
Transfer history data appended for: https://www.transfermarkt.com/robin-buwalda/profil/spieler/220896.
Transfer history data appended for: https://www.transfermarkt.com/tarik-hamza/profil/spieler/343857.
Transfer history data appended for: https://www.transfermarkt.com/kalle-taimi/profil/spieler/224032.
Transfer history data appended for: https://www.transfermarkt.com/tatu-miettunen/profil/spieler/325450.
Transfer history data appended for: https://www.transfermarkt.com/lauri-ala-myllymaki/profil/spieler/270515.
Transfer history data appended for: https://www.transfermarkt.com/doni-arifi/profil/spieler/563841.
Transfer history data appended for: https://www.transfermarkt.com/janne-pekka-laine/profil/spieler/619911.
Transfer history data appended for: https://www.transfermarkt.com/janne-saksela/profil/spieler/130280.
Transfer history data appended for: https://www.transfermarkt.com/eetu-mommo/profil/spieler/592879.
Transfer history data appended for: https://www.transfermarkt.com/mika-hilander/profil/spieler/46911.
Transfer history data appended for: https://www.transfermarkt.com/eero-tamminen/profil/spieler/236742.
Transfer history data appended for: https://www.transfermarkt.com/iiro-jarvinen/profil/spieler/273381.
Transfer history data appended for: https://www.transfermarkt.com/miska-rautiola/profil/spieler/419801.
Transfer history data appended for: https://www.transfermarkt.com/tiemoko-fofana/profil/spieler/569344.
Transfer history data appended for: https://www.transfermarkt.com/jair/profil/spieler/432742.
Transfer history data appended for: https://www.transfermarkt.com/tuure-siira/profil/spieler/188475.
Transfer history data appended for: https://www.transfermarkt.com/naatan-skytta/profil/spieler/567309.
Transfer history data appended for: https://www.transfermarkt.com/maksim-stjopin/profil/spieler/679593.
Transfer history data appended for: https://www.transfermarkt.com/joona-veteli/profil/spieler/226330.
Transfer history data appended for: https://www.transfermarkt.com/eemeli-raittinen/profil/spieler/581453.
Transfer history data appended for: https://www.transfermarkt.com/ilari-mettala/profil/spieler/273266.
Transfer history data appended for: https://www.transfermarkt.com/emile-paul-tendeng/profil/spieler/208563.
Transfer history data appended for: https://www.transfermarkt.com/juho-pietola/profil/spieler/592877.
Transfer history data appended for: https://www.transfermarkt.com/baba-mensah/profil/spieler/302810.
Transfer history data appended for: https://www.transfermarkt.com/felipe-aspegren/profil/spieler/224694.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-missi-mezu/profil/spieler/407014.
Transfer history data appended for: https://www.transfermarkt.com/eetu-huuhtanen/profil/spieler/672789.
Transfer history data appended for: https://www.transfermarkt.com/diogo-tomas/profil/spieler/354476.
Transfer history data appended for: https://www.transfermarkt.com/mikael-almen/profil/spieler/564320.
Transfer history data appended for: https://www.transfermarkt.com/stenio/profil/spieler/497098.
Transfer history data appended for: https://www.transfermarkt.com/tuure-mantynen/profil/spieler/356291.
Transfer history data appended for: https://www.transfermarkt.com/kevin-larsson/profil/spieler/488777.
Transfer history data appended for: https://www.transfermarkt.com/arnold-origi/profil/spieler/62019.
Transfer history data appended for: https://www.transfermarkt.com/macario-hing-glover/profil/spieler/541834.
Transfer history data appended for: https://www.transfermarkt.com/riku-selander/profil/spieler/228717.
Transfer history data appended for: https://www.transfermarkt.com/jani-backman/profil/spieler/47773.
Transfer history data appended for: https://www.transfermarkt.com/sakari-mattila/profil/spieler/47781.
Transfer history data appended for: https://www.transfermarkt.com/matias-hanninen/profil/spieler/188341.
Transfer history data appended for: https://www.transfermarkt.com/eero-matti-auvinen/profil/spieler/322650.
Transfer history data appended for: https://www.transfermarkt.com/sakari-tukiainen/profil/spieler/322567.
Transfer history data appended for: https://www.transfermarkt.com/moshtagh-yaghoubi/profil/spieler/206553.
Transfer history data appended for: https://www.transfermarkt.com/adama-fofana/profil/spieler/648579.
Transfer history data appended for: https://www.transfermarkt.com/otto-huuhtanen/profil/spieler/406695.
Transfer history data appended for: https://www.transfermarkt.com/tino-palmasto/profil/spieler/485089.
Transfer history data appended for: https://www.transfermarkt.com/erikson-carlos/profil/spieler/561385.
Transfer history data appended for: https://www.transfermarkt.com/seung-hyun-lim/profil/spieler/769830.
Transfer history data appended for: https://www.transfermarkt.com/jukka-halme/profil/spieler/109542.
Transfer history data appended for: https://www.transfermarkt.com/joel-mattsson/profil/spieler/355202.
Transfer history data appended for: https://www.transfermarkt.com/sydney-lokale/profil/spieler/658083.
Transfer history data appended for: https://www.transfermarkt.com/hannu-patronen/profil/spieler/47968.
Transfer history data appended for: https://www.transfermarkt.com/jabar-sharza/profil/spieler/289415.
Transfer history data appended for: https://www.transfermarkt.com/foday-manneh/profil/spieler/616764.
Transfer history data appended for: https://www.transfermarkt.com/vitinho/profil/spieler/693251.
Transfer history data appended for: https://www.transfermarkt.com/tuukka-andberg/profil/spieler/418103.
Transfer history data appended for: https://www.transfermarkt.com/nikolas-saira/profil/spieler/379049.
Transfer history data appended for: https://www.transfermarkt.com/john-fagerstrom/profil/spieler/434024.
Transfer history data appended for: https://www.transfermarkt.com/joel-mero/profil/spieler/188277.

Transfer history data appended for: https://www.transfermarkt.com/martti-puolakainen/profil/spieler/176030.
Transfer history data appended for: https://www.transfermarkt.com/luiyi-de-lucas/profil/spieler/597153.
Transfer history data appended for: https://www.transfermarkt.com/ville-valtteri-starck/profil/spieler/190449.
Transfer history data appended for: https://www.transfermarkt.com/antto-hilska/profil/spieler/120252.
Transfer history data appended for: https://www.transfermarkt.com/jacob-bushue/profil/spieler/364648.
Transfer history data appended for: https://www.transfermarkt.com/michael-hartmann/profil/spieler/553585.
Transfer history data appended for: https://www.transfermarkt.com/eero-markkanen/profil/spieler/225078.
Transfer history data appended for: https://www.transfermarkt.com/akseli-lehtojuuri/profil/spieler/648121.
Transfer history data appended for: https://www.transfermarkt.com/maximus-tainio/profil/spieler/482580.
Transfer history data appended for: https://www.transfermarkt.com/jonni-thusberg/profil/spieler/417757.
Transfer history data appended for: https://www.transfermarkt.com/salomo-ojala/profil/spieler/418426.
Transfer history data appended for: https://www.transfermarkt.com/samuel-chidi/profil/spieler/146906.
Transfer history data appended for: https://www.transfermarkt.com/saibou-keita/profil/spieler/481807.
Transfer history data appended for: https://www.transfermarkt.com/jakob-tannander/profil/spieler/369522.
Transfer history data appended for: https://www.transfermarkt.com/topias-listo/profil/spieler/736385.
Transfer history data appended for: https://www.transfermarkt.com/medo/profil/spieler/47777.
Transfer history data appended for: https://www.transfermarkt.com/jonas-hakkinen/profil/spieler/631784.
Transfer history data appended for: https://www.transfermarkt.com/niklas-friberg/profil/spieler/248600.
Transfer history data appended for: https://www.transfermarkt.com/seth-saarinen/profil/spieler/488776.
Transfer history data appended for: https://www.transfermarkt.com/anton-popovitch/profil/spieler/354407.
Transfer history data appended for: https://www.transfermarkt.com/tino-purme/profil/spieler/385587.
Transfer history data appended for: https://www.transfermarkt.com/jami-kyostila/profil/spieler/322666.
Transfer history data appended for: https://www.transfermarkt.com/henri-malundama/profil/spieler/277256.
Transfer history data appended for: https://www.transfermarkt.com/leevi-antinaho/profil/spieler/672459.
Transfer history data appended for: https://www.transfermarkt.com/elhadji-pape-diaw/profil/spieler/410238.
Transfer history data appended for: https://www.transfermarkt.com/mateo-pavlovic/profil/spieler/69436.
Transfer history data appended for: https://www.transfermarkt.com/sada-thioub/profil/spieler/290593.
Transfer history data appended for: https://www.transfermarkt.com/enzo-ebosse/profil/spieler/342877.
Transfer history data appended for: https://www.transfermarkt.com/paul-bernardoni/profil/spieler/318507.
Transfer history data appended for: https://www.transfermarkt.com/stephane-bahoken/profil/spieler/170953.
Transfer history data appended for: https://www.transfermarkt.com/sofiane-boufal/profil/spieler/232271.
Transfer history data appended for: https://www.transfermarkt.com/danijel-petkovic/profil/spieler/188930.
Transfer history data appended for: https://www.transfermarkt.com/noah-fatar/profil/spieler/707225.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-ali-cho/profil/spieler/670847.
Transfer history data appended for: https://www.transfermarkt.com/thomas-toure/profil/spieler/187392.
Transfer history data appended for: https://www.transfermarkt.com/vincent-manceau/profil/spieler/83132.
Transfer history data appended for: https://www.transfermarkt.com/farid-el-melali/profil/spieler/425400.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-cabot/profil/spieler/206912.
Transfer history data appended for: https://www.transfermarkt.com/lois-diony/profil/spieler/126552.
Transfer history data appended for: https://www.transfermarkt.com/angelo-fulgini/profil/spieler/250013.
Transfer history data appended for: https://www.transfermarkt.com/ludovic-butelle/profil/spieler/12029.
Transfer history data appended for: https://www.transfermarkt.com/romain-thomas/profil/spieler/57467.
Transfer history data appended for: https://www.transfermarkt.com/kevin-boma/profil/spieler/709727.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-amadou/profil/spieler/205503.
Transfer history data appended for: https://www.transfermarkt.com/lassana-coulibaly/profil/spieler/386552.
Transfer history data appended for: https://www.transfermarkt.com/waniss-taibi/profil/spieler/680447.
Transfer history data appended for: https://www.transfermarkt.com/ismael-traore/profil/spieler/57216.
Transfer history data appended for: https://www.transfermarkt.com/kevin-bemanga/profil/spieler/746589.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-bamba/profil/spieler/62351.
Transfer history data appended for: https://www.transfermarkt.com/haithem-loucif/profil/spieler/550862.
Transfer history data appended for: https://www.transfermarkt.com/antonin-bobichon/profil/spieler/344575.
Transfer history data appended for: https://www.transfermarkt.com/thomas-mangani/profil/spieler/18934.
Transfer history data appended for: https://www.transfermarkt.com/mathias-pereira-lage/profil/spieler/424072.
Transfer history data appended for: https://www.transfermarkt.com/rachid-alioui/profil/spieler/193130.
Transfer history data appended for: https://www.transfermarkt.com/pierrick-capelle/profil/spieler/214532.
Transfer history data appended for: https://www.transfermarkt.com/zinedine-ould-khaled/profil/spieler/650104.
Transfer history data appended for: https://www.transfermarkt.com/anthony-briancon/profil/spieler/190338.
Transfer history data appended for: https://www.transfermarkt.com/nolan-roux/profil/spieler/81460.
Transfer history data appended for: https://www.transfermarkt.com/loick-landre/profil/spieler/164912.
Transfer history data appended for: https://www.transfermarkt.com/moussa-kone/profil/spieler/364239.
Transfer history data appended for: https://www.transfermarkt.com/niclas-eliasson/profil/spieler/251813.
Transfer history data appended for: https://www.transfermarkt.com/kevin-denkey/profil/spieler/482072.
Transfer history data appended for: https://www.transfermarkt.com/florian-miguel/profil/spieler/347594.
Transfer history data appended for: https://www.transfermarkt.com/baptiste-reynet/profil/spieler/190786.
Transfer history data appended for: https://www.transfermarkt.com/matteo-ahlinvi/profil/spieler/509234.
Transfer history data appended for: https://www.transfermarkt.com/antoine-valerio/profil/spieler/707317.
Transfer history data appended for: https://www.transfermarkt.com/pablo-martinez/profil/spieler/282900.
Transfer history data appended for: https://www.transfermarkt.com/lamine-fomba/profil/spieler/391376.
Transfer history data appended for: https://www.transfermarkt.com/lucas-deaux/profil/spieler/57372.
Transfer history data appended for: https://www.transfermarkt.com/lucas-dias/profil/spieler/476079.
Transfer history data appended for: https://www.transfermarkt.com/clement-depres/profil/spieler/347595.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-paquiez/profil/spieler/412092.
Transfer history data appended for: https://www.transfermarkt.com/kelyan-guessoum/profil/spieler/545520.
Transfer history data appended for: https://www.transfermarkt.com/yassine-benrahou/profil/spieler/344599.
Transfer history data appended for: https://www.transfermarkt.com/sofiane-alakouch/profil/spieler/434358.
Transfer history data appended for: https://www.transfermarkt.com/patrick-burner/profil/spieler/444725.
Transfer history data appended for: https://www.transfermarkt.com/sidy-sarr/profil/spieler/364233.
Transfer history data appended for: https://www.transfermarkt.com/zinedine-ferhat/profil/spieler/232895.
Transfer history data appended for: https://www.transfermarkt.com/lucas-buades/profil/spieler/531960.
Transfer history data appended for: https://www.transfermarkt.com/birger-meling/profil/spieler/282250.

Transfer history data appended for: https://www.transfermarkt.com/sami-ben-amar/profil/spieler/524318.
Transfer history data appended for: https://www.transfermarkt.com/renaud-ripart/profil/spieler/234802.
Transfer history data appended for: https://www.transfermarkt.com/karim-aribi/profil/spieler/456080.
Transfer history data appended for: https://www.transfermarkt.com/haris-duljevic/profil/spieler/184473.
Transfer history data appended for: https://www.transfermarkt.com/burak-yilmaz/profil/spieler/34987.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-pied/profil/spieler/60583.
Transfer history data appended for: https://www.transfermarkt.com/jose-fonte/profil/spieler/33829.
Transfer history data appended for: https://www.transfermarkt.com/eugenio-pizzuto/profil/spieler/704553.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-ikone/profil/spieler/324690.
Transfer history data appended for: https://www.transfermarkt.com/isaac-lihadji/profil/spieler/557610.
Transfer history data appended for: https://www.transfermarkt.com/yusuf-yazici/profil/spieler/386726.
Transfer history data appended for: https://www.transfermarkt.com/boubakary-soumare/profil/spieler/344605.
Transfer history data appended for: https://www.transfermarkt.com/fadiga-ouattara/profil/spieler/513158.
Transfer history data appended for: https://www.transfermarkt.com/reinildo-mandava/profil/spieler/240692.
Transfer history data appended for: https://www.transfermarkt.com/mike-maignan/profil/spieler/182906.
Transfer history data appended for: https://www.transfermarkt.com/orestis-karnezis/profil/spieler/16408.
Transfer history data appended for: https://www.transfermarkt.com/zeki-celik/profil/spieler/251075.
Transfer history data appended for: https://www.transfermarkt.com/sven-botman/profil/spieler/361093.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-bamba/profil/spieler/292818.
Transfer history data appended for: https://www.transfermarkt.com/timothy-weah/profil/spieler/370846.
Transfer history data appended for: https://www.transfermarkt.com/adama-soumaoro/profil/spieler/126673.
Transfer history data appended for: https://www.transfermarkt.com/renato-sanches/profil/spieler/258027.
Transfer history data appended for: https://www.transfermarkt.com/tiago-djalo/profil/spieler/420465.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-david/profil/spieler/533738.
Transfer history data appended for: https://www.transfermarkt.com/domagoj-bradaric/profil/spieler/357796.
Transfer history data appended for: https://www.transfermarkt.com/lucas-chevalier/profil/spieler/463600.
Transfer history data appended for: https://www.transfermarkt.com/cheikh-niasse/profil/spieler/644032.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-andre/profil/spieler/84301.
Transfer history data appended for: https://www.transfermarkt.com/luiz-araujo/profil/spieler/435485.
Transfer history data appended for: https://www.transfermarkt.com/marcelo/profil/spieler/52920.
Transfer history data appended for: https://www.transfermarkt.com/maxwel-cornet/profil/spieler/234781.
Transfer history data appended for: https://www.transfermarkt.com/moussa-dembele/profil/spieler/229004.
Transfer history data appended for: https://www.transfermarkt.com/maxence-caqueret/profil/spieler/395237.
Transfer history data appended for: https://www.transfermarkt.com/tino-kadewere/profil/spieler/384060.
Transfer history data appended for: https://www.transfermarkt.com/melvin-bard/profil/spieler/532775.
Transfer history data appended for: https://www.transfermarkt.com/memphis-depay/profil/spieler/167850.
Transfer history data appended for: https://www.transfermarkt.com/mattia-de-sciglio/profil/spieler/88682.
Transfer history data appended for: https://www.transfermarkt.com/camilo/profil/spieler/672202.
Transfer history data appended for: https://www.transfermarkt.com/yaya-soumare/profil/spieler/591195.
Transfer history data appended for: https://www.transfermarkt.com/djamel-eddine-benlamri/profil/spieler/209990.
Transfer history data appended for: https://www.transfermarkt.com/leo-dubois/profil/spieler/236400.
Transfer history data appended for: https://www.transfermarkt.com/bruno-guimaraes/profil/spieler/520624.
Transfer history data appended for: https://www.transfermarkt.com/cenk-ozkacar/profil/spieler/615350.
Transfer history data appended for: https://www.transfermarkt.com/houssem-aouar/profil/spieler/395693.
Transfer history data appended for: https://www.transfermarkt.com/jean-lucas/profil/spieler/578872.
Transfer history data appended for: https://www.transfermarkt.com/lucas-paqueta/profil/spieler/444523.
Transfer history data appended for: https://www.transfermarkt.com/malcolm-barcola/profil/spieler/461581.
Transfer history data appended for: https://www.transfermarkt.com/karl-toko-ekambi/profil/spieler/315110.
Transfer history data appended for: https://www.transfermarkt.com/rayan-cherki/profil/spieler/607223.
Transfer history data appended for: https://www.transfermarkt.com/julian-pollersbeck/profil/spieler/228975.
Transfer history data appended for: https://www.transfermarkt.com/thiago-mendes/profil/spieler/135617.
Transfer history data appended for: https://www.transfermarkt.com/anthony-lopes/profil/spieler/60561.
Transfer history data appended for: https://www.transfermarkt.com/sinaly-diomande/profil/spieler/702441.
Transfer history data appended for: https://www.transfermarkt.com/loris-benito/profil/spieler/119085.
Transfer history data appended for: https://www.transfermarkt.com/pablo/profil/spieler/149577.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-briand/profil/spieler/18909.
Transfer history data appended for: https://www.transfermarkt.com/youssouf-sabaly/profil/spieler/135492.
Transfer history data appended for: https://www.transfermarkt.com/amadou-traore/profil/spieler/540665.
Transfer history data appended for: https://www.transfermarkt.com/yacine-adli/profil/spieler/395236.
Transfer history data appended for: https://www.transfermarkt.com/vukasin-jovanovic/profil/spieler/264140.
Transfer history data appended for: https://www.transfermarkt.com/maxime-poundje/profil/spieler/126528.
Transfer history data appended for: https://www.transfermarkt.com/toma-basic/profil/spieler/334835.
Transfer history data appended for: https://www.transfermarkt.com/benoit-costil/profil/spieler/22628.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-poussin/profil/spieler/344591.
Transfer history data appended for: https://www.transfermarkt.com/mexer/profil/spieler/127610.
Transfer history data appended for: https://www.transfermarkt.com/over-mandanda/profil/spieler/452803.
Transfer history data appended for: https://www.transfermarkt.com/logan-delaurier-chaubet/profil/spieler/569386.
Transfer history data appended for: https://www.transfermarkt.com/otavio/profil/spieler/312314.
Transfer history data appended for: https://www.transfermarkt.com/laurent-koscielny/profil/spieler/76277.
Transfer history data appended for: https://www.transfermarkt.com/ismael-sow/profil/spieler/540685.
Transfer history data appended for: https://www.transfermarkt.com/remi-oudin/profil/spieler/399543.
Transfer history data appended for: https://www.transfermarkt.com/enock-kwateng/profil/spieler/288241.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-de-preville/profil/spieler/122116.
Transfer history data appended for: https://www.transfermarkt.com/hatem-ben-arfa/profil/spieler/18900.
Transfer history data appended for: https://www.transfermarkt.com/josh-maja/profil/spieler/453824.
Transfer history data appended for: https://www.transfermarkt.com/dilane-bakwa/profil/spieler/540664.
Transfer history data appended for: https://www.transfermarkt.com/david-kong/profil/spieler/236727.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-diarra/profil/spieler/696852.
Transfer history data appended for: https://www.transfermarkt.com/ui-jo-hwang/profil/spieler/260166.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-zerkane/profil/spieler/460654.

Transfer history data appended for: https://www.transfermarkt.com/samuel-kalu/profil/spieler/424051.
Transfer history data appended for: https://www.transfermarkt.com/duje-caleta-car/profil/spieler/238266.
Transfer history data appended for: https://www.transfermarkt.com/jordan-amavi/profil/spieler/241229.
Transfer history data appended for: https://www.transfermarkt.com/luis-henrique/profil/spieler/691316.
Transfer history data appended for: https://www.transfermarkt.com/florian-thauvin/profil/spieler/184892.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-phliponeau/profil/spieler/585951.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-payet/profil/spieler/37647.
Transfer history data appended for: https://www.transfermarkt.com/valere-germain/profil/spieler/60540.
Transfer history data appended for: https://www.transfermarkt.com/yohann-pele/profil/spieler/6270.
Transfer history data appended for: https://www.transfermarkt.com/ugo-bertelli/profil/spieler/708680.
Transfer history data appended for: https://www.transfermarkt.com/lucas-perrin/profil/spieler/352392.
Transfer history data appended for: https://www.transfermarkt.com/valentin-rongier/profil/spieler/332889.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-radonjic/profil/spieler/245078.
Transfer history data appended for: https://www.transfermarkt.com/florian-chabrolle/profil/spieler/418662.
Transfer history data appended for: https://www.transfermarkt.com/boubacar-kamara/profil/spieler/394327.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-balerdi/profil/spieler/575998.
Transfer history data appended for: https://www.transfermarkt.com/jores-rahou/profil/spieler/725577.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-gonzalez/profil/spieler/183647.
Transfer history data appended for: https://www.transfermarkt.com/christopher-rocchia/profil/spieler/352393.
Transfer history data appended for: https://www.transfermarkt.com/cheick-souare/profil/spieler/569367.
Transfer history data appended for: https://www.transfermarkt.com/pape-gueye/profil/spieler/485963.
Transfer history data appended for: https://www.transfermarkt.com/kevin-strootman/profil/spieler/68864.
Transfer history data appended for: https://www.transfermarkt.com/hiroki-sakai/profil/spieler/83002.
Transfer history data appended for: https://www.transfermarkt.com/nassim-ahmed/profil/spieler/611674.
Transfer history data appended for: https://www.transfermarkt.com/simon-ngapandouetnbu/profil/spieler/696600.
Transfer history data appended for: https://www.transfermarkt.com/marley-ake/profil/spieler/682032.
Transfer history data appended for: https://www.transfermarkt.com/saif-eddine-khaoui/profil/spieler/270411.
Transfer history data appended for: https://www.transfermarkt.com/dario-benedetto/profil/spieler/92693.
Transfer history data appended for: https://www.transfermarkt.com/morgan-sanson/profil/spieler/174094.
Transfer history data appended for: https://www.transfermarkt.com/richecard-richard/profil/spieler/639711.
Transfer history data appended for: https://www.transfermarkt.com/michael-cuisance/profil/spieler/344600.
Transfer history data appended for: https://www.transfermarkt.com/aaron-kamardin/profil/spieler/557609.
Transfer history data appended for: https://www.transfermarkt.com/jordan-lotomba/profil/spieler/313094.
Transfer history data appended for: https://www.transfermarkt.com/hicham-boudaoui/profil/spieler/560593.
Transfer history data appended for: https://www.transfermarkt.com/flavius-daniliuc/profil/spieler/322655.
Transfer history data appended for: https://www.transfermarkt.com/alexis-claude-maurice/profil/spieler/384593.
Transfer history data appended for: https://www.transfermarkt.com/racine-coly/profil/spieler/323379.
Transfer history data appended for: https://www.transfermarkt.com/teddy-boulhendi/profil/spieler/789419.
Transfer history data appended for: https://www.transfermarkt.com/youcef-atal/profil/spieler/416108.
Transfer history data appended for: https://www.transfermarkt.com/yoan-cardinale/profil/spieler/241231.
Transfer history data appended for: https://www.transfermarkt.com/jeff-reine-adelaide/profil/spieler/326300.
Transfer history data appended for: https://www.transfermarkt.com/walter-benitez/profil/spieler/296802.
Transfer history data appended for: https://www.transfermarkt.com/andy-pelmard/profil/spieler/494236.
Transfer history data appended for: https://www.transfermarkt.com/rony-lopes/profil/spieler/174694.
Transfer history data appended for: https://www.transfermarkt.com/alexis-trouillet/profil/spieler/482769.
Transfer history data appended for: https://www.transfermarkt.com/dante/profil/spieler/16136.
Transfer history data appended for: https://www.transfermarkt.com/pierre-lees-melou/profil/spieler/377393.
Transfer history data appended for: https://www.transfermarkt.com/kasper-dolberg/profil/spieler/283196.
Transfer history data appended for: https://www.transfermarkt.com/khephren-thuram/profil/spieler/463618.
Transfer history data appended for: https://www.transfermarkt.com/stanley-nsoki/profil/spieler/371141.
Transfer history data appended for: https://www.transfermarkt.com/robson-bambu/profil/spieler/458715.
Transfer history data appended for: https://www.transfermarkt.com/myziane-maolida/profil/spieler/371142.
Transfer history data appended for: https://www.transfermarkt.com/amine-gouiri/profil/spieler/418659.
Transfer history data appended for: https://www.transfermarkt.com/morgan-schneiderlin/profil/spieler/56818.
Transfer history data appended for: https://www.transfermarkt.com/deji-sotona/profil/spieler/586599.
Transfer history data appended for: https://www.transfermarkt.com/dan-ndoye/profil/spieler/365108.
Transfer history data appended for: https://www.transfermarkt.com/dylan-bronn/profil/spieler/450417.
Transfer history data appended for: https://www.transfermarkt.com/fabien-centonze/profil/spieler/384859.
Transfer history data appended for: https://www.transfermarkt.com/lamine-gueye/profil/spieler/568701.
Transfer history data appended for: https://www.transfermarkt.com/matthieu-udol/profil/spieler/344886.
Transfer history data appended for: https://www.transfermarkt.com/lenny-lacroix/profil/spieler/620315.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-niane/profil/spieler/490417.
Transfer history data appended for: https://www.transfermarkt.com/paul-delecroix/profil/spieler/81543.
Transfer history data appended for: https://www.transfermarkt.com/kevin-ndoram/profil/spieler/342209.
Transfer history data appended for: https://www.transfermarkt.com/boubacar-traore/profil/spieler/649020.
Transfer history data appended for: https://www.transfermarkt.com/adama-traore/profil/spieler/364405.
Transfer history data appended for: https://www.transfermarkt.com/farid-boulaya/profil/spieler/202318.
Transfer history data appended for: https://www.transfermarkt.com/warren-tchimbembe/profil/spieler/591914.
Transfer history data appended for: https://www.transfermarkt.com/manuel-cabit/profil/spieler/127075.
Transfer history data appended for: https://www.transfermarkt.com/thierry-ambrose/profil/spieler/265763.
Transfer history data appended for: https://www.transfermarkt.com/victorien-angban/profil/spieler/178314.
Transfer history data appended for: https://www.transfermarkt.com/kiki-kouyate/profil/spieler/211637.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-oukidja/profil/spieler/56809.
Transfer history data appended for: https://www.transfermarkt.com/john-boye/profil/spieler/85585.
Transfer history data appended for: https://www.transfermarkt.com/vagner/profil/spieler/353211.
Transfer history data appended for: https://www.transfermarkt.com/vincent-pajot/profil/spieler/126699.
Transfer history data appended for: https://www.transfermarkt.com/marc-aurele-caillard/profil/spieler/205465.
Transfer history data appended for: https://www.transfermarkt.com/thomas-delaine/profil/spieler/170961.
Transfer history data appended for: https://www.transfermarkt.com/aaron-leya-iseka/profil/spieler/289587.

Transfer history data appended for: https://www.transfermarkt.com/habib-maiga/profil/spieler/293944.
Transfer history data appended for: https://www.transfermarkt.com/youssef-maziz/profil/spieler/481116.
Transfer history data appended for: https://www.transfermarkt.com/opa-nguette/profil/spieler/205587.
Transfer history data appended for: https://www.transfermarkt.com/papa-ndiaga-yade/profil/spieler/568702.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-fofana/profil/spieler/402004.
Transfer history data appended for: https://www.transfermarkt.com/habib-diallo/profil/spieler/344888.
Transfer history data appended for: https://www.transfermarkt.com/eiji-kawashima/profil/spieler/77383.
Transfer history data appended for: https://www.transfermarkt.com/idriss-saadi/profil/spieler/111057.
Transfer history data appended for: https://www.transfermarkt.com/matz-sels/profil/spieler/127202.
Transfer history data appended for: https://www.transfermarkt.com/kevin-zohi/profil/spieler/524929.
Transfer history data appended for: https://www.transfermarkt.com/jean-ricner-bellegarde/profil/spieler/450050.
Transfer history data appended for: https://www.transfermarkt.com/adrien-thomasson/profil/spieler/215977.
Transfer history data appended for: https://www.transfermarkt.com/jean-eudes-aholou/profil/spieler/178313.
Transfer history data appended for: https://www.transfermarkt.com/kenny-lala/profil/spieler/174196.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-lienard/profil/spieler/314940.
Transfer history data appended for: https://www.transfermarkt.com/sanjin-prcic/profil/spieler/125783.
Transfer history data appended for: https://www.transfermarkt.com/alexander-djiku/profil/spieler/250844.
Transfer history data appended for: https://www.transfermarkt.com/bingourou-kamara/profil/spieler/333175.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-sissoko/profil/spieler/372712.
Transfer history data appended for: https://www.transfermarkt.com/ismael-aaneba/profil/spieler/528178.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-chahiri/profil/spieler/358509.
Transfer history data appended for: https://www.transfermarkt.com/mahame-siby/profil/spieler/587646.
Transfer history data appended for: https://www.transfermarkt.com/ludovic-ajorque/profil/spieler/283994.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-simakan/profil/spieler/666234.
Transfer history data appended for: https://www.transfermarkt.com/stefan-mitrovic/profil/spieler/143029.
Transfer history data appended for: https://www.transfermarkt.com/lebo-mothiba/profil/spieler/427161.
Transfer history data appended for: https://www.transfermarkt.com/anthony-caci/profil/spieler/453016.
Transfer history data appended for: https://www.transfermarkt.com/wahbi-khazri/profil/spieler/103565.
Transfer history data appended for: https://www.transfermarkt.com/charles-abi/profil/spieler/418658.
Transfer history data appended for: https://www.transfermarkt.com/jessy-moulin/profil/spieler/33925.
Transfer history data appended for: https://www.transfermarkt.com/maxence-rivera/profil/spieler/735700.
Transfer history data appended for: https://www.transfermarkt.com/yvann-macon/profil/spieler/580747.
Transfer history data appended for: https://www.transfermarkt.com/arnaud-nordin/profil/spieler/324811.
Transfer history data appended for: https://www.transfermarkt.com/saidou-sow/profil/spieler/807128.
Transfer history data appended for: https://www.transfermarkt.com/miguel-trauco/profil/spieler/177690.
Transfer history data appended for: https://www.transfermarkt.com/adil-aouchiche/profil/spieler/569385.
Transfer history data appended for: https://www.transfermarkt.com/alpha-sissoko/profil/spieler/594992.
Transfer history data appended for: https://www.transfermarkt.com/lucas-gourna-douath/profil/spieler/620313.
Transfer history data appended for: https://www.transfermarkt.com/romain-hamouma/profil/spieler/98349.
Transfer history data appended for: https://www.transfermarkt.com/jean-philippe-krasso/profil/spieler/358515.
Transfer history data appended for: https://www.transfermarkt.com/harold-moukoudi/profil/spieler/272636.
Transfer history data appended for: https://www.transfermarkt.com/stefan-bajic/profil/spieler/465836.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-sidibe/profil/spieler/639758.
Transfer history data appended for: https://www.transfermarkt.com/denis-bouanga/profil/spieler/236045.
Transfer history data appended for: https://www.transfermarkt.com/zaydou-youssouf/profil/spieler/471582.
Transfer history data appended for: https://www.transfermarkt.com/kevin-monnet-paquet/profil/spieler/44045.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-retsos/profil/spieler/324351.
Transfer history data appended for: https://www.transfermarkt.com/aimen-moueffek/profil/spieler/484992.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-silva/profil/spieler/114340.
Transfer history data appended for: https://www.transfermarkt.com/yvan-neyou/profil/spieler/469669.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-debuchy/profil/spieler/27306.
Transfer history data appended for: https://www.transfermarkt.com/etienne-green/profil/spieler/696849.
Transfer history data appended for: https://www.transfermarkt.com/ryad-boudebouz/profil/spieler/77826.
Transfer history data appended for: https://www.transfermarkt.com/timothee-kolodziejczak/profil/spieler/84085.
Transfer history data appended for: https://www.transfermarkt.com/mahdi-camara/profil/spieler/324795.
Transfer history data appended for: https://www.transfermarkt.com/stephane-ruffier/profil/spieler/39910.
Transfer history data appended for: https://www.transfermarkt.com/bilal-benkhedim/profil/spieler/609692.
Transfer history data appended for: https://www.transfermarkt.com/yehvann-diouf/profil/spieler/448632.
Transfer history data appended for: https://www.transfermarkt.com/hugo-ekitike/profil/spieler/709726.
Transfer history data appended for: https://www.transfermarkt.com/nathanael-mbuku/profil/spieler/557614.
Transfer history data appended for: https://www.transfermarkt.com/arber-zeneli/profil/spieler/222876.
Transfer history data appended for: https://www.transfermarkt.com/thomas-foket/profil/spieler/215114.
Transfer history data appended for: https://www.transfermarkt.com/fode-doucoure/profil/spieler/798925.
Transfer history data appended for: https://www.transfermarkt.com/kaj-sierhuis/profil/spieler/315283.
Transfer history data appended for: https://www.transfermarkt.com/dialy-ndiaye/profil/spieler/649032.
Transfer history data appended for: https://www.transfermarkt.com/boulaye-dia/profil/spieler/626913.
Transfer history data appended for: https://www.transfermarkt.com/fraser-hornby/profil/spieler/388160.
Transfer history data appended for: https://www.transfermarkt.com/ghislain-konan/profil/spieler/422850.
Transfer history data appended for: https://www.transfermarkt.com/marshall-munetsi/profil/spieler/414908.
Transfer history data appended for: https://www.transfermarkt.com/mouhamadou-drammeh/profil/spieler/399551.
Transfer history data appended for: https://www.transfermarkt.com/yunis-abdelhamid/profil/spieler/199704.
Transfer history data appended for: https://www.transfermarkt.com/moise-sakava/profil/spieler/520054.
Transfer history data appended for: https://www.transfermarkt.com/predrag-rajkovic/profil/spieler/190263.
Transfer history data appended for: https://www.transfermarkt.com/dario-maresic/profil/spieler/307807.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-cafaro/profil/spieler/399383.
Transfer history data appended for: https://www.transfermarkt.com/thibault-de-smet/profil/spieler/340177.
Transfer history data appended for: https://www.transfermarkt.com/wout-faes/profil/spieler/292808.
Transfer history data appended for: https://www.transfermarkt.com/valon-berisha/profil/spieler/145115.
Transfer history data appended for: https://www.transfermarkt.com/dereck-kutesa/profil/spieler/237669.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-donis/profil/spieler/243606.

Transfer history data appended for: https://www.transfermarkt.com/el-bilal-toure/profil/spieler/649016.
Transfer history data appended for: https://www.transfermarkt.com/moreto-cassama/profil/spieler/290746.
Transfer history data appended for: https://www.transfermarkt.com/xavier-chavalerin/profil/spieler/118278.
Transfer history data appended for: https://www.transfermarkt.com/moussa-doumbia/profil/spieler/316137.
Transfer history data appended for: https://www.transfermarkt.com/abdoul-kader-bamba/profil/spieler/560725.
Transfer history data appended for: https://www.transfermarkt.com/dennis-appiah/profil/spieler/111038.
Transfer history data appended for: https://www.transfermarkt.com/bridge-ndilu/profil/spieler/558709.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-pallois/profil/spieler/139279.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-toure/profil/spieler/181382.
Transfer history data appended for: https://www.transfermarkt.com/jean-charles-castelletto/profil/spieler/182875.
Transfer history data appended for: https://www.transfermarkt.com/batista-mendy/profil/spieler/395234.
Transfer history data appended for: https://www.transfermarkt.com/jean-kevin-augustin/profil/spieler/264956.
Transfer history data appended for: https://www.transfermarkt.com/marcus-coco/profil/spieler/353365.
Transfer history data appended for: https://www.transfermarkt.com/imran-louza/profil/spieler/635336.
Transfer history data appended for: https://www.transfermarkt.com/moses-simon/profil/spieler/274862.
Transfer history data appended for: https://www.transfermarkt.com/renaud-emond/profil/spieler/168471.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-abeid/profil/spieler/111036.
Transfer history data appended for: https://www.transfermarkt.com/denis-petric/profil/spieler/28356.
Transfer history data appended for: https://www.transfermarkt.com/kalifa-coulibaly/profil/spieler/184935.
Transfer history data appended for: https://www.transfermarkt.com/charly-jan/profil/spieler/764683.
Transfer history data appended for: https://www.transfermarkt.com/charles-traore/profil/spieler/394906.
Transfer history data appended for: https://www.transfermarkt.com/roli-pereira-de-sa/profil/spieler/243737.
Transfer history data appended for: https://www.transfermarkt.com/ludovic-blas/profil/spieler/288225.
Transfer history data appended for: https://www.transfermarkt.com/anthony-limbombe/profil/spieler/140803.
Transfer history data appended for: https://www.transfermarkt.com/randal-kolo-muani/profil/spieler/487969.
Transfer history data appended for: https://www.transfermarkt.com/thomas-basila/profil/spieler/344592.
Transfer history data appended for: https://www.transfermarkt.com/fabio/profil/spieler/61891.
Transfer history data appended for: https://www.transfermarkt.com/pedro-chirivella/profil/spieler/242273.
Transfer history data appended for: https://www.transfermarkt.com/junior-sambia/profil/spieler/335147.
Transfer history data appended for: https://www.transfermarkt.com/yanis-ammour/profil/spieler/420782.
Transfer history data appended for: https://www.transfermarkt.com/ambroise-oyongo/profil/spieler/184922.
Transfer history data appended for: https://www.transfermarkt.com/joris-chotard/profil/spieler/624037.
Transfer history data appended for: https://www.transfermarkt.com/pedro-mendes/profil/spieler/72857.
Transfer history data appended for: https://www.transfermarkt.com/thibault-tamas/profil/spieler/569374.
Transfer history data appended for: https://www.transfermarkt.com/arnaud-souquet/profil/spieler/111058.
Transfer history data appended for: https://www.transfermarkt.com/daniel-congre/profil/spieler/22386.
Transfer history data appended for: https://www.transfermarkt.com/il-lok-yun/profil/spieler/131480.
Transfer history data appended for: https://www.transfermarkt.com/mihailo-ristic/profil/spieler/271455.
Transfer history data appended for: https://www.transfermarkt.com/petar-skuletic/profil/spieler/58295.
Transfer history data appended for: https://www.transfermarkt.com/samy-benchama/profil/spieler/627464.
Transfer history data appended for: https://www.transfermarkt.com/stephy-mavididi/profil/spieler/340328.
Transfer history data appended for: https://www.transfermarkt.com/beni-makouana/profil/spieler/624920.
Transfer history data appended for: https://www.transfermarkt.com/andy-delort/profil/spieler/122797.
Transfer history data appended for: https://www.transfermarkt.com/keagan-dolly/profil/spieler/234006.
Transfer history data appended for: https://www.transfermarkt.com/dimitry-bertaud/profil/spieler/371816.
Transfer history data appended for: https://www.transfermarkt.com/thibaut-vargas/profil/spieler/627463.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-laborde/profil/spieler/181378.
Transfer history data appended for: https://www.transfermarkt.com/florent-mollet/profil/spieler/222859.
Transfer history data appended for: https://www.transfermarkt.com/jonas-omlin/profil/spieler/247915.
Transfer history data appended for: https://www.transfermarkt.com/jordan-ferri/profil/spieler/118284.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-cozza/profil/spieler/485965.
Transfer history data appended for: https://www.transfermarkt.com/hilton/profil/spieler/4811.
Transfer history data appended for: https://www.transfermarkt.com/clement-vidal/profil/spieler/569388.
Transfer history data appended for: https://www.transfermarkt.com/matis-carvalho/profil/spieler/478346.
Transfer history data appended for: https://www.transfermarkt.com/teji-savanier/profil/spieler/127156.
Transfer history data appended for: https://www.transfermarkt.com/damien-le-tallec/profil/spieler/59950.
Transfer history data appended for: https://www.transfermarkt.com/vincent-le-goff/profil/spieler/120651.
Transfer history data appended for: https://www.transfermarkt.com/andreaw-gravillon/profil/spieler/395083.
Transfer history data appended for: https://www.transfermarkt.com/fabien-lemoine/profil/spieler/56794.
Transfer history data appended for: https://www.transfermarkt.com/armand-lauriente/profil/spieler/579930.
Transfer history data appended for: https://www.transfermarkt.com/trevoh-chalobah/profil/spieler/346314.
Transfer history data appended for: https://www.transfermarkt.com/terem-moffi/profil/spieler/538874.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-delaplace/profil/spieler/149551.
Transfer history data appended for: https://www.transfermarkt.com/matthieu-saunier/profil/spieler/93759.
Transfer history data appended for: https://www.transfermarkt.com/teddy-bartouche/profil/spieler/629587.
Transfer history data appended for: https://www.transfermarkt.com/paul-nardi/profil/spieler/189744.
Transfer history data appended for: https://www.transfermarkt.com/adrian-grbic/profil/spieler/167342.
Transfer history data appended for: https://www.transfermarkt.com/malamine-doumbouya/profil/spieler/790620.
Transfer history data appended for: https://www.transfermarkt.com/franklin-wadja/profil/spieler/524986.
Transfer history data appended for: https://www.transfermarkt.com/thomas-fontaine/profil/spieler/80036.
Transfer history data appended for: https://www.transfermarkt.com/stephane-diarra/profil/spieler/428954.
Transfer history data appended for: https://www.transfermarkt.com/houboulang-mendes/profil/spieler/442552.
Transfer history data appended for: https://www.transfermarkt.com/laurent-abergel/profil/spieler/238626.
Transfer history data appended for: https://www.transfermarkt.com/pierre-yves-hamel/profil/spieler/203504.
Transfer history data appended for: https://www.transfermarkt.com/thomas-callens/profil/spieler/593315.
Transfer history data appended for: https://www.transfermarkt.com/julien-laporte/profil/spieler/386057.
Transfer history data appended for: https://www.transfermarkt.com/matthieu-dreyer/profil/spieler/57134.
Transfer history data appended for: https://www.transfermarkt.com/quentin-boisgard/profil/spieler/412671.
Transfer history data appended for: https://www.transfermarkt.com/jerome-hergault/profil/spieler/314912.

Transfer history data appended for: https://www.transfermarkt.com/thomas-monconduit/profil/spieler/127182.
Transfer history data appended for: https://www.transfermarkt.com/enzo-le-fee/profil/spieler/633992.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-morel/profil/spieler/23960.
Transfer history data appended for: https://www.transfermarkt.com/umut-bozok/profil/spieler/259025.
Transfer history data appended for: https://www.transfermarkt.com/yannick-cahuzac/profil/spieler/44686.
Transfer history data appended for: https://www.transfermarkt.com/massadio-haidara/profil/spieler/170929.
Transfer history data appended for: https://www.transfermarkt.com/cyrille-bayala/profil/spieler/267147.
Transfer history data appended for: https://www.transfermarkt.com/clement-michelin/profil/spieler/318520.
Transfer history data appended for: https://www.transfermarkt.com/didier-desprez/profil/spieler/342876.
Transfer history data appended for: https://www.transfermarkt.com/arnaud-kalimuendo/profil/spieler/585959.
Transfer history data appended for: https://www.transfermarkt.com/florian-sotoca/profil/spieler/354726.
Transfer history data appended for: https://www.transfermarkt.com/corentin-jean/profil/spieler/20463.
Transfer history data appended for: https://www.transfermarkt.com/charles-boli/profil/spieler/695646.
Transfer history data appended for: https://www.transfermarkt.com/zakaria-diallo/profil/spieler/137930.
Transfer history data appended for: https://www.transfermarkt.com/loic-bade/profil/spieler/730581.
Transfer history data appended for: https://www.transfermarkt.com/seko-fofana/profil/spieler/182893.
Transfer history data appended for: https://www.transfermarkt.com/cheick-traore/profil/spieler/378965.
Transfer history data appended for: https://www.transfermarkt.com/wuilker-farinez/profil/spieler/373714.
Transfer history data appended for: https://www.transfermarkt.com/jean-louis-leca/profil/spieler/27490.
Transfer history data appended for: https://www.transfermarkt.com/gael-kakuta/profil/spieler/74297.
Transfer history data appended for: https://www.transfermarkt.com/simon-banza/profil/spieler/344869.
Transfer history data appended for: https://www.transfermarkt.com/adam-oudjani/profil/spieler/676525.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-clauss/profil/spieler/175639.
Transfer history data appended for: https://www.transfermarkt.com/david-costa/profil/spieler/719442.
Transfer history data appended for: https://www.transfermarkt.com/facundo-medina/profil/spieler/474800.
Transfer history data appended for: https://www.transfermarkt.com/ignatius-ganago/profil/spieler/531949.
Transfer history data appended for: https://www.transfermarkt.com/ismael-boura/profil/spieler/770895.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-radovanovic/profil/spieler/339501.
Transfer history data appended for: https://www.transfermarkt.com/cheick-doucoure/profil/spieler/543387.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-gradit/profil/spieler/126557.
Transfer history data appended for: https://www.transfermarkt.com/steven-fortes/profil/spieler/276895.
Transfer history data appended for: https://www.transfermarkt.com/issiaga-sylla/profil/spieler/220878.
Transfer history data appended for: https://www.transfermarkt.com/anibal-chala/profil/spieler/278796.
Transfer history data appended for: https://www.transfermarkt.com/aurelien-scheidler/profil/spieler/497175.
Transfer history data appended for: https://www.transfermarkt.com/didier-ndong/profil/spieler/210081.
Transfer history data appended for: https://www.transfermarkt.com/wesley-lautoa/profil/spieler/154199.
Transfer history data appended for: https://www.transfermarkt.com/mounir-chouiar/profil/spieler/355641.
Transfer history data appended for: https://www.transfermarkt.com/yassine-benzia/profil/spieler/187847.
Transfer history data appended for: https://www.transfermarkt.com/mama-balde/profil/spieler/325223.
Transfer history data appended for: https://www.transfermarkt.com/alex-dobre/profil/spieler/365770.
Transfer history data appended for: https://www.transfermarkt.com/ngonda-muzinga/profil/spieler/426790.
Transfer history data appended for: https://www.transfermarkt.com/wilitty-younoussa/profil/spieler/804934.
Transfer history data appended for: https://www.transfermarkt.com/eric-ebimbe/profil/spieler/536482.
Transfer history data appended for: https://www.transfermarkt.com/jordan-marie/profil/spieler/231025.
Transfer history data appended for: https://www.transfermarkt.com/sacha-boey/profil/spieler/475413.
Transfer history data appended for: https://www.transfermarkt.com/arthur-zagre/profil/spieler/536477.
Transfer history data appended for: https://www.transfermarkt.com/senou-coulibaly/profil/spieler/596240.
Transfer history data appended for: https://www.transfermarkt.com/ahmad-ngouyamsa/profil/spieler/723416.
Transfer history data appended for: https://www.transfermarkt.com/anthony-racioppi/profil/spieler/395671.
Transfer history data appended for: https://www.transfermarkt.com/fouad-chafik/profil/spieler/216499.
Transfer history data appended for: https://www.transfermarkt.com/bersant-celina/profil/spieler/229695.
Transfer history data appended for: https://www.transfermarkt.com/bruno-ecuele-manga/profil/spieler/60990.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-panzo/profil/spieler/392777.
Transfer history data appended for: https://www.transfermarkt.com/frederic-sammaritano/profil/spieler/80173.
Transfer history data appended for: https://www.transfermarkt.com/roger-assale/profil/spieler/263183.
Transfer history data appended for: https://www.transfermarkt.com/saturnin-allagbe/profil/spieler/274958.
Transfer history data appended for: https://www.transfermarkt.com/amir-arli/profil/spieler/662142.
Transfer history data appended for: https://www.transfermarkt.com/levi-ntumba/profil/spieler/509510.
Transfer history data appended for: https://www.transfermarkt.com/moussa-konate/profil/spieler/192774.
Transfer history data appended for: https://www.transfermarkt.com/julian-draxler/profil/spieler/85148.
Transfer history data appended for: https://www.transfermarkt.com/sergio-rico/profil/spieler/207302.
Transfer history data appended for: https://www.transfermarkt.com/pablo-sarabia/profil/spieler/74230.
Transfer history data appended for: https://www.transfermarkt.com/maxen-kapo/profil/spieler/618408.
Transfer history data appended for: https://www.transfermarkt.com/idrissa-gueye/profil/spieler/126665.
Transfer history data appended for: https://www.transfermarkt.com/bandiougou-fadiga/profil/spieler/590914.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-florenzi/profil/spieler/130365.
Transfer history data appended for: https://www.transfermarkt.com/colin-dagba/profil/spieler/460629.
Transfer history data appended for: https://www.transfermarkt.com/danilo-pereira/profil/spieler/141050.
Transfer history data appended for: https://www.transfermarkt.com/ander-herrera/profil/spieler/99343.
Transfer history data appended for: https://www.transfermarkt.com/mitchel-bakker/profil/spieler/361065.
Transfer history data appended for: https://www.transfermarkt.com/kays-ruiz-atil/profil/spieler/538045.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-fressange/profil/spieler/536479.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-letellier/profil/spieler/93730.
Transfer history data appended for: https://www.transfermarkt.com/juan-bernat/profil/spieler/126719.
Transfer history data appended for: https://www.transfermarkt.com/jese/profil/spieler/134936.
Transfer history data appended for: https://www.transfermarkt.com/rafinha/profil/spieler/129473.
Transfer history data appended for: https://www.transfermarkt.com/presnel-kimpembe/profil/spieler/282041.
Transfer history data appended for: https://www.transfermarkt.com/yanis-saidani/profil/spieler/618342.
Transfer history data appended for: https://www.transfermarkt.com/moise-kean/profil/spieler/364135.
Transfer history data appended for: https://www.transfermarkt.com/angel-di-maria/profil/spieler/45320.

Transfer history data appended for: https://www.transfermarkt.com/kylian-mbappe/profil/spieler/342229.
Transfer history data appended for: https://www.transfermarkt.com/timothee-pembele/profil/spieler/538998.
Transfer history data appended for: https://www.transfermarkt.com/marquinhos/profil/spieler/181767.
Transfer history data appended for: https://www.transfermarkt.com/abdou-diallo/profil/spieler/229005.
Transfer history data appended for: https://www.transfermarkt.com/xavi-simons/profil/spieler/566931.
Transfer history data appended for: https://www.transfermarkt.com/neymar/profil/spieler/68290.
Transfer history data appended for: https://www.transfermarkt.com/marco-verratti/profil/spieler/102558.
Transfer history data appended for: https://www.transfermarkt.com/layvin-kurzawa/profil/spieler/126710.
Transfer history data appended for: https://www.transfermarkt.com/fode-ballo-toure/profil/spieler/296422.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-lecomte/profil/spieler/127181.
Transfer history data appended for: https://www.transfermarkt.com/ruben-aguilar/profil/spieler/203746.
Transfer history data appended for: https://www.transfermarkt.com/youssef-ait-bennasser/profil/spieler/265569.
Transfer history data appended for: https://www.transfermarkt.com/radoslaw-majecki/profil/spieler/346546.
Transfer history data appended for: https://www.transfermarkt.com/strahinja-pavlovic/profil/spieler/574671.
Transfer history data appended for: https://www.transfermarkt.com/gelson-martins/profil/spieler/257448.
Transfer history data appended for: https://www.transfermarkt.com/cesc-fabregas/profil/spieler/8806.
Transfer history data appended for: https://www.transfermarkt.com/samuel-grandsir/profil/spieler/432772.
Transfer history data appended for: https://www.transfermarkt.com/kevin-volland/profil/spieler/82009.
Transfer history data appended for: https://www.transfermarkt.com/vito-mannone/profil/spieler/33781.
Transfer history data appended for: https://www.transfermarkt.com/florentino/profil/spieler/357162.
Transfer history data appended for: https://www.transfermarkt.com/eliot-matazo/profil/spieler/535834.
Transfer history data appended for: https://www.transfermarkt.com/benoit-badiashile/profil/spieler/463603.
Transfer history data appended for: https://www.transfermarkt.com/youssouf-fofana/profil/spieler/569598.
Transfer history data appended for: https://www.transfermarkt.com/aurelien-tchouameni/profil/spieler/413112.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-golovin/profil/spieler/263918.
Transfer history data appended for: https://www.transfermarkt.com/enzo-millot/profil/spieler/569366.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-maripan/profil/spieler/249730.
Transfer history data appended for: https://www.transfermarkt.com/chrislain-matsima/profil/spieler/569383.
Transfer history data appended for: https://www.transfermarkt.com/pietro-pellegri/profil/spieler/364133.
Transfer history data appended for: https://www.transfermarkt.com/stevan-jovetic/profil/spieler/46104.
Transfer history data appended for: https://www.transfermarkt.com/djibril-sidibe/profil/spieler/161869.
Transfer history data appended for: https://www.transfermarkt.com/wissam-ben-yedder/profil/spieler/146854.
Transfer history data appended for: https://www.transfermarkt.com/willem-geubbels/profil/spieler/463620.
Transfer history data appended for: https://www.transfermarkt.com/sofiane-diop/profil/spieler/569389.
Transfer history data appended for: https://www.transfermarkt.com/axel-disasi/profil/spieler/386047.
Transfer history data appended for: https://www.transfermarkt.com/julien-faussurier/profil/spieler/78917.
Transfer history data appended for: https://www.transfermarkt.com/franck-honorat/profil/spieler/229006.
Transfer history data appended for: https://www.transfermarkt.com/heriberto-tavares/profil/spieler/445517.
Transfer history data appended for: https://www.transfermarkt.com/gautier-larsonneur/profil/spieler/357047.
Transfer history data appended for: https://www.transfermarkt.com/lilian-brassier/profil/spieler/485960.
Transfer history data appended for: https://www.transfermarkt.com/cristian-battocchio/profil/spieler/129868.
Transfer history data appended for: https://www.transfermarkt.com/haris-belkebla/profil/spieler/138055.
Transfer history data appended for: https://www.transfermarkt.com/romain-perraud/profil/spieler/318523.
Transfer history data appended for: https://www.transfermarkt.com/ferris-ngoma/profil/spieler/127192.
Transfer history data appended for: https://www.transfermarkt.com/idrissa-dioh/profil/spieler/780146.
Transfer history data appended for: https://www.transfermarkt.com/brendan-chardonnet/profil/spieler/250779.
Transfer history data appended for: https://www.transfermarkt.com/jean-kevin-duverne/profil/spieler/344864.
Transfer history data appended for: https://www.transfermarkt.com/hiangaa-mbock/profil/spieler/684062.
Transfer history data appended for: https://www.transfermarkt.com/hugo-magnetti/profil/spieler/474662.
Transfer history data appended for: https://www.transfermarkt.com/mouez-hassen/profil/spieler/215677.
Transfer history data appended for: https://www.transfermarkt.com/steve-mounie/profil/spieler/238639.
Transfer history data appended for: https://www.transfermarkt.com/romain-philippoteaux/profil/spieler/255220.
Transfer history data appended for: https://www.transfermarkt.com/romain-faivre/profil/spieler/555076.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-le-douaron/profil/spieler/737781.
Transfer history data appended for: https://www.transfermarkt.com/sebastien-cibois/profil/spieler/395251.
Transfer history data appended for: https://www.transfermarkt.com/rafiki-said/profil/spieler/780147.
Transfer history data appended for: https://www.transfermarkt.com/ronael-pierre-gabriel/profil/spieler/410185.
Transfer history data appended for: https://www.transfermarkt.com/irvin-cardona/profil/spieler/342226.
Transfer history data appended for: https://www.transfermarkt.com/paul-lasne/profil/spieler/93726.
Transfer history data appended for: https://www.transfermarkt.com/christophe-herelle/profil/spieler/170544.
Transfer history data appended for: https://www.transfermarkt.com/ludovic-baal/profil/spieler/39913.
Transfer history data appended for: https://www.transfermarkt.com/james-lea-siliki/profil/spieler/346291.
Transfer history data appended for: https://www.transfermarkt.com/romain-del-castillo/profil/spieler/353399.
Transfer history data appended for: https://www.transfermarkt.com/adrien-hunou/profil/spieler/203507.
Transfer history data appended for: https://www.transfermarkt.com/georginio-rutter/profil/spieler/538977.
Transfer history data appended for: https://www.transfermarkt.com/eduardo-camavinga/profil/spieler/640428.
Transfer history data appended for: https://www.transfermarkt.com/nayef-aguerd/profil/spieler/361914.
Transfer history data appended for: https://www.transfermarkt.com/romain-salin/profil/spieler/23974.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-doku/profil/spieler/486049.
Transfer history data appended for: https://www.transfermarkt.com/damien-da-silva/profil/spieler/57370.
Transfer history data appended for: https://www.transfermarkt.com/serhou-guirassy/profil/spieler/270541.
Transfer history data appended for: https://www.transfermarkt.com/alfred-gomis/profil/spieler/163568.
Transfer history data appended for: https://www.transfermarkt.com/pepe-bonet/profil/spieler/685086.
Transfer history data appended for: https://www.transfermarkt.com/hamari-traore/profil/spieler/297070.
Transfer history data appended for: https://www.transfermarkt.com/adrien-truffert/profil/spieler/654539.
Transfer history data appended for: https://www.transfermarkt.com/faitout-maouassa/profil/spieler/357072.
Transfer history data appended for: https://www.transfermarkt.com/jonas-martin/profil/spieler/127142.
Transfer history data appended for: https://www.transfermarkt.com/dalbert/profil/spieler/312862.
Transfer history data appended for: https://www.transfermarkt.com/yann-gboho/profil/spieler/463613.

Transfer history data appended for: https://www.transfermarkt.com/daniele-rugani/profil/spieler/162959.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-bourigeaud/profil/spieler/266359.
Transfer history data appended for: https://www.transfermarkt.com/clement-grenier/profil/spieler/72479.
Transfer history data appended for: https://www.transfermarkt.com/gerzino-nyamsi/profil/spieler/378953.
Transfer history data appended for: https://www.transfermarkt.com/martin-terrier/profil/spieler/442891.
Transfer history data appended for: https://www.transfermarkt.com/brandon-soppy/profil/spieler/546880.
Transfer history data appended for: https://www.transfermarkt.com/steven-nzonzi/profil/spieler/73734.
Transfer history data appended for: https://www.transfermarkt.com/jayson-papeau/profil/spieler/665525.
Transfer history data appended for: https://www.transfermarkt.com/nicholas-opoku/profil/spieler/396516.
Transfer history data appended for: https://www.transfermarkt.com/jack-lahne/profil/spieler/493674.
Transfer history data appended for: https://www.transfermarkt.com/prince-gouano/profil/spieler/171410.
Transfer history data appended for: https://www.transfermarkt.com/mickael-alphonse/profil/spieler/172153.
Transfer history data appended for: https://www.transfermarkt.com/gaoussou-traore/profil/spieler/606450.
Transfer history data appended for: https://www.transfermarkt.com/arnaud-lusamba/profil/spieler/272631.
Transfer history data appended for: https://www.transfermarkt.com/amadou-ciss/profil/spieler/526784.
Transfer history data appended for: https://www.transfermarkt.com/molla-wague/profil/spieler/129893.
Transfer history data appended for: https://www.transfermarkt.com/yohann-thuram/profil/spieler/60602.
Transfer history data appended for: https://www.transfermarkt.com/cheick-timite/profil/spieler/424709.
Transfer history data appended for: https://www.transfermarkt.com/valentin-gendrey/profil/spieler/569387.
Transfer history data appended for: https://www.transfermarkt.com/adam-lewis/profil/spieler/347481.
Transfer history data appended for: https://www.transfermarkt.com/juan-ferney-otero/profil/spieler/332305.
Transfer history data appended for: https://www.transfermarkt.com/alexis-blin/profil/spieler/236041.
Transfer history data appended for: https://www.transfermarkt.com/iron-gomis/profil/spieler/693352.
Transfer history data appended for: https://www.transfermarkt.com/stephen-odey/profil/spieler/491890.
Transfer history data appended for: https://www.transfermarkt.com/mustapha-sangare/profil/spieler/832051.
Transfer history data appended for: https://www.transfermarkt.com/florian-bianchini/profil/spieler/715923.
Transfer history data appended for: https://www.transfermarkt.com/sanasi-sy/profil/spieler/606451.
Transfer history data appended for: https://www.transfermarkt.com/nathan-monzango/profil/spieler/804715.
Transfer history data appended for: https://www.transfermarkt.com/regis-gurtner/profil/spieler/39918.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-lomotey/profil/spieler/560465.
Transfer history data appended for: https://www.transfermarkt.com/gregoire-coudert/profil/spieler/525155.
Transfer history data appended for: https://www.transfermarkt.com/rafael-fonseca/profil/spieler/525576.
Transfer history data appended for: https://www.transfermarkt.com/darell-tokpa/profil/spieler/655414.
Transfer history data appended for: https://www.transfermarkt.com/mor-talla-nguer/profil/spieler/422718.
Transfer history data appended for: https://www.transfermarkt.com/steeve-beusnard/profil/spieler/468246.
Transfer history data appended for: https://www.transfermarkt.com/paul-meliande/profil/spieler/804546.
Transfer history data appended for: https://www.transfermarkt.com/quentin-daubin/profil/spieler/407624.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-diatta/profil/spieler/701298.
Transfer history data appended for: https://www.transfermarkt.com/cheikh-sabaly/profil/spieler/568696.
Transfer history data appended for: https://www.transfermarkt.com/romain-bayard/profil/spieler/170535.
Transfer history data appended for: https://www.transfermarkt.com/abdourahmane-ndiaye/profil/spieler/568687.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-bertrand/profil/spieler/195908.
Transfer history data appended for: https://www.transfermarkt.com/antoine-batisse/profil/spieler/335146.
Transfer history data appended for: https://www.transfermarkt.com/patrick-trindade/profil/spieler/789416.
Transfer history data appended for: https://www.transfermarkt.com/idrissa-ba/profil/spieler/315996.
Transfer history data appended for: https://www.transfermarkt.com/younn-zahary/profil/spieler/593279.
Transfer history data appended for: https://www.transfermarkt.com/xavier-kouassi/profil/spieler/132587.
Transfer history data appended for: https://www.transfermarkt.com/thierno-thioub/profil/spieler/612331.
Transfer history data appended for: https://www.transfermarkt.com/anthony-scaramozzino/profil/spieler/17976.
Transfer history data appended for: https://www.transfermarkt.com/yankuba-jarju/profil/spieler/366047.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-iribarnegaray/profil/spieler/469659.
Transfer history data appended for: https://www.transfermarkt.com/romain-armand/profil/spieler/57344.
Transfer history data appended for: https://www.transfermarkt.com/ebenezer-assifuah/profil/spieler/262558.
Transfer history data appended for: https://www.transfermarkt.com/victor-lobry/profil/spieler/592358.
Transfer history data appended for: https://www.transfermarkt.com/scotty-sadzoute/profil/spieler/531338.
Transfer history data appended for: https://www.transfermarkt.com/erwin-koffi/profil/spieler/341942.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-kamissoko/profil/spieler/203759.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-olliero/profil/spieler/395602.
Transfer history data appended for: https://www.transfermarkt.com/louis-bury/profil/spieler/469660.
Transfer history data appended for: https://www.transfermarkt.com/damon-bansais/profil/spieler/469662.
Transfer history data appended for: https://www.transfermarkt.com/hamza-sakhi/profil/spieler/263951.
Transfer history data appended for: https://www.transfermarkt.com/yanis-begraoui/profil/spieler/569376.
Transfer history data appended for: https://www.transfermarkt.com/quentin-bernard/profil/spieler/98262.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-coeff/profil/spieler/89450.
Transfer history data appended for: https://www.transfermarkt.com/kenji-van-boto/profil/spieler/229012.
Transfer history data appended for: https://www.transfermarkt.com/gauthier-hein/profil/spieler/344892.
Transfer history data appended for: https://www.transfermarkt.com/paul-joly/profil/spieler/806168.
Transfer history data appended for: https://www.transfermarkt.com/gautier-lloris/profil/spieler/249636.
Transfer history data appended for: https://www.transfermarkt.com/lassine-sinayoko/profil/spieler/569140.
Transfer history data appended for: https://www.transfermarkt.com/samuel-souprayen/profil/spieler/60599.
Transfer history data appended for: https://www.transfermarkt.com/mickael-le-bihan/profil/spieler/139018.
Transfer history data appended for: https://www.transfermarkt.com/kryss-chapelle/profil/spieler/802894.
Transfer history data appended for: https://www.transfermarkt.com/alec-georgen/profil/spieler/324800.
Transfer history data appended for: https://www.transfermarkt.com/francois-bellugou/profil/spieler/75282.
Transfer history data appended for: https://www.transfermarkt.com/aly-ndom/profil/spieler/396131.
Transfer history data appended for: https://www.transfermarkt.com/ousoumane-camara/profil/spieler/478107.
Transfer history data appended for: https://www.transfermarkt.com/mathias-autret/profil/spieler/138171.
Transfer history data appended for: https://www.transfermarkt.com/birama-toure/profil/spieler/229853.
Transfer history data appended for: https://www.transfermarkt.com/jubal/profil/spieler/149928.

Transfer history data appended for: https://www.transfermarkt.com/xiaoxuan-ji/profil/spieler/251973.
Transfer history data appended for: https://www.transfermarkt.com/axel-ngando/profil/spieler/170478.
Transfer history data appended for: https://www.transfermarkt.com/remy-dugimont/profil/spieler/174304.
Transfer history data appended for: https://www.transfermarkt.com/ryan-ponti/profil/spieler/737481.
Transfer history data appended for: https://www.transfermarkt.com/kevin-fortune/profil/spieler/411439.
Transfer history data appended for: https://www.transfermarkt.com/donovan-leon/profil/spieler/170911.
Transfer history data appended for: https://www.transfermarkt.com/sonny-laiton/profil/spieler/427689.
Transfer history data appended for: https://www.transfermarkt.com/carlens-arcus/profil/spieler/371686.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-sorbon/profil/spieler/56820.
Transfer history data appended for: https://www.transfermarkt.com/felix-eboa-eboa/profil/spieler/296359.
Transfer history data appended for: https://www.transfermarkt.com/logan-ndenbe/profil/spieler/481634.
Transfer history data appended for: https://www.transfermarkt.com/guessouma-fofana/profil/spieler/419999.
Transfer history data appended for: https://www.transfermarkt.com/pierrick-valdivia/profil/spieler/60607.
Transfer history data appended for: https://www.transfermarkt.com/axel-urie/profil/spieler/785579.
Transfer history data appended for: https://www.transfermarkt.com/nicolai-larsen/profil/spieler/92248.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-livolant/profil/spieler/324806.
Transfer history data appended for: https://www.transfermarkt.com/matthias-phaeton/profil/spieler/427693.
Transfer history data appended for: https://www.transfermarkt.com/bryan-pele/profil/spieler/170938.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-robail/profil/spieler/495489.
Transfer history data appended for: https://www.transfermarkt.com/philipe-sampaio/profil/spieler/336697.
Transfer history data appended for: https://www.transfermarkt.com/yannick-gomis/profil/spieler/220848.
Transfer history data appended for: https://www.transfermarkt.com/alaixys-romao/profil/spieler/40014.
Transfer history data appended for: https://www.transfermarkt.com/enzo-basilio/profil/spieler/242716.
Transfer history data appended for: https://www.transfermarkt.com/lloyd-palun/profil/spieler/165400.
Transfer history data appended for: https://www.transfermarkt.com/louis-carnot/profil/spieler/484991.
Transfer history data appended for: https://www.transfermarkt.com/baptiste-roux/profil/spieler/796895.
Transfer history data appended for: https://www.transfermarkt.com/yoann-cathline/profil/spieler/782476.
Transfer history data appended for: https://www.transfermarkt.com/yeni-ngbakoto/profil/spieler/111053.
Transfer history data appended for: https://www.transfermarkt.com/ronny-rodelin/profil/spieler/76055.
Transfer history data appended for: https://www.transfermarkt.com/morgan-poaty/profil/spieler/272640.
Transfer history data appended for: https://www.transfermarkt.com/frantzdy-pierrot/profil/spieler/492955.
Transfer history data appended for: https://www.transfermarkt.com/sikou-niakate/profil/spieler/413118.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-mellot/profil/spieler/525113.
Transfer history data appended for: https://www.transfermarkt.com/paul-georges-ntep/profil/spieler/148955.
Transfer history data appended for: https://www.transfermarkt.com/dominique-youfeigane/profil/spieler/591190.
Transfer history data appended for: https://www.transfermarkt.com/youssouf-mchangama/profil/spieler/167472.
Transfer history data appended for: https://www.transfermarkt.com/lebogang-phiri/profil/spieler/253316.
Transfer history data appended for: https://www.transfermarkt.com/el-hadji-ba/profil/spieler/169090.
Transfer history data appended for: https://www.transfermarkt.com/saliou-ciss/profil/spieler/149444.
Transfer history data appended for: https://www.transfermarkt.com/mickael-biron/profil/spieler/524860.
Transfer history data appended for: https://www.transfermarkt.com/martin-sourzac/profil/spieler/126705.
Transfer history data appended for: https://www.transfermarkt.com/rayan-philippe/profil/spieler/694507.
Transfer history data appended for: https://www.transfermarkt.com/ernest-seka/profil/spieler/283136.
Transfer history data appended for: https://www.transfermarkt.com/christopher-wooh/profil/spieler/572326.
Transfer history data appended for: https://www.transfermarkt.com/kenny-rocha-santos/profil/spieler/476527.
Transfer history data appended for: https://www.transfermarkt.com/yanis-barka/profil/spieler/510258.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-merghem/profil/spieler/452877.
Transfer history data appended for: https://www.transfermarkt.com/ogou-akichi/profil/spieler/192714.
Transfer history data appended for: https://www.transfermarkt.com/souleymane-karamoko/profil/spieler/525119.
Transfer history data appended for: https://www.transfermarkt.com/amine-bassi/profil/spieler/506009.
Transfer history data appended for: https://www.transfermarkt.com/serge-nguessan/profil/spieler/263294.
Transfer history data appended for: https://www.transfermarkt.com/ande-dona-ndoh/profil/spieler/58213.
Transfer history data appended for: https://www.transfermarkt.com/ousmane-cissokho/profil/spieler/39317.
Transfer history data appended for: https://www.transfermarkt.com/mathias-fischer/profil/spieler/345065.
Transfer history data appended for: https://www.transfermarkt.com/dorian-bertrand/profil/spieler/352464.
Transfer history data appended for: https://www.transfermarkt.com/warren-bondo/profil/spieler/659516.
Transfer history data appended for: https://www.transfermarkt.com/gregoire-lefebvre/profil/spieler/302806.
Transfer history data appended for: https://www.transfermarkt.com/mons-bassouamina/profil/spieler/391377.
Transfer history data appended for: https://www.transfermarkt.com/hugo-constant/profil/spieler/556487.
Transfer history data appended for: https://www.transfermarkt.com/vinni-triboulet/profil/spieler/637850.
Transfer history data appended for: https://www.transfermarkt.com/sega-coulibaly/profil/spieler/229003.
Transfer history data appended for: https://www.transfermarkt.com/abdelhamid-el-kaoutari/profil/spieler/74615.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-haag/profil/spieler/635103.
Transfer history data appended for: https://www.transfermarkt.com/rosario-latouchent/profil/spieler/333350.
Transfer history data appended for: https://www.transfermarkt.com/baptiste-valette/profil/spieler/170509.
Transfer history data appended for: https://www.transfermarkt.com/aurelien-nguiamba/profil/spieler/344595.
Transfer history data appended for: https://www.transfermarkt.com/cedric-hountondji/profil/spieler/198709.
Transfer history data appended for: https://www.transfermarkt.com/josue-albert/profil/spieler/170487.
Transfer history data appended for: https://www.transfermarkt.com/david-gomis/profil/spieler/520816.
Transfer history data appended for: https://www.transfermarkt.com/akim-zedadka/profil/spieler/327863.
Transfer history data appended for: https://www.transfermarkt.com/ouparine-djoco/profil/spieler/594993.
Transfer history data appended for: https://www.transfermarkt.com/johan-gastien/profil/spieler/72121.
Transfer history data appended for: https://www.transfermarkt.com/salis-abdul-samed/profil/spieler/688707.
Transfer history data appended for: https://www.transfermarkt.com/jerome-phojo/profil/spieler/170459.
Transfer history data appended for: https://www.transfermarkt.com/muamer-aljic/profil/spieler/787162.
Transfer history data appended for: https://www.transfermarkt.com/driss-trichard/profil/spieler/290595.
Transfer history data appended for: https://www.transfermarkt.com/jordan-tell/profil/spieler/272644.
Transfer history data appended for: https://www.transfermarkt.com/lucas-margueron/profil/spieler/618463.
Transfer history data appended for: https://www.transfermarkt.com/lassana-diako/profil/spieler/674285.
Transfer history data appended for: https://www.transfermarkt.com/vital-nsimba/profil/spieler/203761.

Transfer history data appended for: https://www.transfermarkt.com/yohann-magnin/profil/spieler/594997.
Transfer history data appended for: https://www.transfermarkt.com/sofyan-chader/profil/spieler/748358.
Transfer history data appended for: https://www.transfermarkt.com/florent-ogier/profil/spieler/91473.
Transfer history data appended for: https://www.transfermarkt.com/arthur-desmas/profil/spieler/379869.
Transfer history data appended for: https://www.transfermarkt.com/alidu-seidu/profil/spieler/798404.
Transfer history data appended for: https://www.transfermarkt.com/jim-allevinah/profil/spieler/646733.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-bayo/profil/spieler/594991.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-iglesias/profil/spieler/159907.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-rajot/profil/spieler/509044.
Transfer history data appended for: https://www.transfermarkt.com/jodel-dossou/profil/spieler/221151.
Transfer history data appended for: https://www.transfermarkt.com/jason-berthomier/profil/spieler/306191.
Transfer history data appended for: https://www.transfermarkt.com/fred-gnalega/profil/spieler/837093.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-rivierez/profil/spieler/98274.
Transfer history data appended for: https://www.transfermarkt.com/yoann-court/profil/spieler/60525.
Transfer history data appended for: https://www.transfermarkt.com/santy-ngom/profil/spieler/174089.
Transfer history data appended for: https://www.transfermarkt.com/yoel-armougom/profil/spieler/548716.
Transfer history data appended for: https://www.transfermarkt.com/jason-ngouabi-lougagui/profil/spieler/654411.
Transfer history data appended for: https://www.transfermarkt.com/azzeddine-toufiqui/profil/spieler/460630.
Transfer history data appended for: https://www.transfermarkt.com/vladislav-molchan/profil/spieler/575781.
Transfer history data appended for: https://www.transfermarkt.com/steve-shamal/profil/spieler/345225.
Transfer history data appended for: https://www.transfermarkt.com/godson-kyeremeh/profil/spieler/651973.
Transfer history data appended for: https://www.transfermarkt.com/nicholas-gioacchini/profil/spieler/704156.
Transfer history data appended for: https://www.transfermarkt.com/loup-hervieu/profil/spieler/593281.
Transfer history data appended for: https://www.transfermarkt.com/steeve-yago/profil/spieler/170903.
Transfer history data appended for: https://www.transfermarkt.com/alexis-beka-beka/profil/spieler/539065.
Transfer history data appended for: https://www.transfermarkt.com/yacine-bammou/profil/spieler/276255.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-mendy/profil/spieler/290561.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-jeannot/profil/spieler/111048.
Transfer history data appended for: https://www.transfermarkt.com/anthony-goncalves/profil/spieler/111528.
Transfer history data appended for: https://www.transfermarkt.com/garissone-innocent/profil/spieler/460626.
Transfer history data appended for: https://www.transfermarkt.com/jessy-pi/profil/spieler/170460.
Transfer history data appended for: https://www.transfermarkt.com/aliou-traore/profil/spieler/495668.
Transfer history data appended for: https://www.transfermarkt.com/prince-oniangue/profil/spieler/60578.
Transfer history data appended for: https://www.transfermarkt.com/zeidane-inoussa/profil/spieler/579291.
Transfer history data appended for: https://www.transfermarkt.com/jessy-deminguet/profil/spieler/539232.
Transfer history data appended for: https://www.transfermarkt.com/adama-mbengue/profil/spieler/230066.
Transfer history data appended for: https://www.transfermarkt.com/caleb-zady-sery/profil/spieler/617699.
Transfer history data appended for: https://www.transfermarkt.com/sullivan-pean/profil/spieler/593317.
Transfer history data appended for: https://www.transfermarkt.com/anthony-weber/profil/spieler/56827.
Transfer history data appended for: https://www.transfermarkt.com/kelian-nsona/profil/spieler/569368.
Transfer history data appended for: https://www.transfermarkt.com/remy-riou/profil/spieler/18940.
Transfer history data appended for: https://www.transfermarkt.com/johann-lepenant/profil/spieler/585973.
Transfer history data appended for: https://www.transfermarkt.com/hugo-vandermersch/profil/spieler/693357.
Transfer history data appended for: https://www.transfermarkt.com/woyo-coulibaly/profil/spieler/592975.
Transfer history data appended for: https://www.transfermarkt.com/ylan-gomes/profil/spieler/622056.
Transfer history data appended for: https://www.transfermarkt.com/nolan-mbemba/profil/spieler/276768.
Transfer history data appended for: https://www.transfermarkt.com/pierre-gibaud/profil/spieler/109965.
Transfer history data appended for: https://www.transfermarkt.com/yacouba-coulibaly/profil/spieler/473251.
Transfer history data appended for: https://www.transfermarkt.com/yahia-fofana/profil/spieler/418651.
Transfer history data appended for: https://www.transfermarkt.com/victor-lekhal/profil/spieler/264811.
Transfer history data appended for: https://www.transfermarkt.com/herve-bazile/profil/spieler/95680.
Transfer history data appended for: https://www.transfermarkt.com/godwin-kobby-bentil/profil/spieler/725288.
Transfer history data appended for: https://www.transfermarkt.com/jean-pascal-fontaine/profil/spieler/58826.
Transfer history data appended for: https://www.transfermarkt.com/ayman-ben-mohamed/profil/spieler/249446.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-fofana/profil/spieler/563734.
Transfer history data appended for: https://www.transfermarkt.com/fernand-mayembo/profil/spieler/413245.
Transfer history data appended for: https://www.transfermarkt.com/quentin-cornette/profil/spieler/238630.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-gorgelin/profil/spieler/60543.
Transfer history data appended for: https://www.transfermarkt.com/elies-mahmoud/profil/spieler/804664.
Transfer history data appended for: https://www.transfermarkt.com/romain-basque/profil/spieler/409147.
Transfer history data appended for: https://www.transfermarkt.com/jamal-thiare/profil/spieler/262022.
Transfer history data appended for: https://www.transfermarkt.com/alan-dzabana/profil/spieler/395699.
Transfer history data appended for: https://www.transfermarkt.com/nabil-alioui/profil/spieler/344607.
Transfer history data appended for: https://www.transfermarkt.com/khalid-boutaib/profil/spieler/231941.
Transfer history data appended for: https://www.transfermarkt.com/umut-meras/profil/spieler/341549.
Transfer history data appended for: https://www.transfermarkt.com/souleymane-isaak-toure/profil/spieler/708678.
Transfer history data appended for: https://www.transfermarkt.com/himad-abdelli/profil/spieler/592979.
Transfer history data appended for: https://www.transfermarkt.com/harouna-sy/profil/spieler/524677.
Transfer history data appended for: https://www.transfermarkt.com/alioune-ba/profil/spieler/419997.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-boudaud/profil/spieler/148785.
Transfer history data appended for: https://www.transfermarkt.com/dorian-salhi/profil/spieler/590419.
Transfer history data appended for: https://www.transfermarkt.com/billy-ketkeophomphone/profil/spieler/134712.
Transfer history data appended for: https://www.transfermarkt.com/adon-gomis/profil/spieler/681325.
Transfer history data appended for: https://www.transfermarkt.com/ozkan-cetiner/profil/spieler/802165.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-cisse/profil/spieler/341393.
Transfer history data appended for: https://www.transfermarkt.com/jovanie-tchouatcha/profil/spieler/205629.
Transfer history data appended for: https://www.transfermarkt.com/marc-antoine-guillaume/profil/spieler/468701.
Transfer history data appended for: https://www.transfermarkt.com/axel-maraval/profil/spieler/164967.
Transfer history data appended for: https://www.transfermarkt.com/redouane-kerrouche/profil/spieler/351834.

Transfer history data appended for: https://www.transfermarkt.com/jeremy-vachoux/profil/spieler/203770.
Transfer history data appended for: https://www.transfermarkt.com/emeric-dudouit/profil/spieler/170984.
Transfer history data appended for: https://www.transfermarkt.com/cheick-diarra/profil/spieler/179408.
Transfer history data appended for: https://www.transfermarkt.com/kevin-rocheteau/profil/spieler/281614.
Transfer history data appended for: https://www.transfermarkt.com/malik-tchokounte/profil/spieler/412085.
Transfer history data appended for: https://www.transfermarkt.com/jorris-romil/profil/spieler/470491.
Transfer history data appended for: https://www.transfermarkt.com/demba-thiam/profil/spieler/137970.
Transfer history data appended for: https://www.transfermarkt.com/ilan-kebbal/profil/spieler/739769.
Transfer history data appended for: https://www.transfermarkt.com/loic-kouagba/profil/spieler/410061.
Transfer history data appended for: https://www.transfermarkt.com/randi-goteni/profil/spieler/448633.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-huysman/profil/spieler/102663.
Transfer history data appended for: https://www.transfermarkt.com/thomas-vannoye/profil/spieler/730355.
Transfer history data appended for: https://www.transfermarkt.com/guillaume-bosca/profil/spieler/481721.
Transfer history data appended for: https://www.transfermarkt.com/david-kabamba-kalonji/profil/spieler/694798.
Transfer history data appended for: https://www.transfermarkt.com/leverton-pierre/profil/spieler/552467.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-bruneel/profil/spieler/467637.
Transfer history data appended for: https://www.transfermarkt.com/thibault-vialla/profil/spieler/365881.
Transfer history data appended for: https://www.transfermarkt.com/tom-lebeau/profil/spieler/504349.
Transfer history data appended for: https://www.transfermarkt.com/valentin-jacob/profil/spieler/284526.
Transfer history data appended for: https://www.transfermarkt.com/quentin-bena/profil/spieler/468606.
Transfer history data appended for: https://www.transfermarkt.com/louis-ameka-autchanga/profil/spieler/427948.
Transfer history data appended for: https://www.transfermarkt.com/david-djigla/profil/spieler/228900.
Transfer history data appended for: https://www.transfermarkt.com/joseph-mendes/profil/spieler/169275.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-michel/profil/spieler/193142.
Transfer history data appended for: https://www.transfermarkt.com/pape-ibnou-ba/profil/spieler/565060.
Transfer history data appended for: https://www.transfermarkt.com/lenny-vallier/profil/spieler/371148.
Transfer history data appended for: https://www.transfermarkt.com/joris-moutachy/profil/spieler/558714.
Transfer history data appended for: https://www.transfermarkt.com/yacine-bourhane/profil/spieler/525131.
Transfer history data appended for: https://www.transfermarkt.com/bryan-passi/profil/spieler/411416.
Transfer history data appended for: https://www.transfermarkt.com/issouf-paro/profil/spieler/189483.
Transfer history data appended for: https://www.transfermarkt.com/olivier-kemen/profil/spieler/243725.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-conte/profil/spieler/358512.
Transfer history data appended for: https://www.transfermarkt.com/brahim-konate/profil/spieler/391257.
Transfer history data appended for: https://www.transfermarkt.com/dylan-louiserre/profil/spieler/291415.
Transfer history data appended for: https://www.transfermarkt.com/goduine-koyalipou/profil/spieler/525140.
Transfer history data appended for: https://www.transfermarkt.com/guy-marcelin-kilama/profil/spieler/604777.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-sissoko/profil/spieler/484888.
Transfer history data appended for: https://www.transfermarkt.com/quentin-braat/profil/spieler/390942.
Transfer history data appended for: https://www.transfermarkt.com/bilal-boutobba/profil/spieler/344151.
Transfer history data appended for: https://www.transfermarkt.com/brahima-doukansy/profil/spieler/517378.
Transfer history data appended for: https://www.transfermarkt.com/antoine-baroan/profil/spieler/463666.
Transfer history data appended for: https://www.transfermarkt.com/samuel-renel/profil/spieler/722739.
Transfer history data appended for: https://www.transfermarkt.com/darline-yongwa/profil/spieler/717118.
Transfer history data appended for: https://www.transfermarkt.com/ilyas-chouaref/profil/spieler/639058.
Transfer history data appended for: https://www.transfermarkt.com/romain-grange/profil/spieler/105400.
Transfer history data appended for: https://www.transfermarkt.com/leandro-morante/profil/spieler/691354.
Transfer history data appended for: https://www.transfermarkt.com/yannick-mbone/profil/spieler/198474.
Transfer history data appended for: https://www.transfermarkt.com/remi-pillot/profil/spieler/111027.
Transfer history data appended for: https://www.transfermarkt.com/philippe-paulin-keny/profil/spieler/662208.
Transfer history data appended for: https://www.transfermarkt.com/amir-nouri/profil/spieler/556579.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-cisse/profil/spieler/696598.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-raineau/profil/spieler/56815.
Transfer history data appended for: https://www.transfermarkt.com/tommy-plumain/profil/spieler/716728.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-cordoval/profil/spieler/106225.
Transfer history data appended for: https://www.transfermarkt.com/yanis-merdji/profil/spieler/480454.
Transfer history data appended for: https://www.transfermarkt.com/issa-marega/profil/spieler/593322.
Transfer history data appended for: https://www.transfermarkt.com/leo-leroy/profil/spieler/650350.
Transfer history data appended for: https://www.transfermarkt.com/remi-mulumba/profil/spieler/146099.
Transfer history data appended for: https://www.transfermarkt.com/wilfried-bedfian/profil/spieler/624785.
Transfer history data appended for: https://www.transfermarkt.com/christopher-operi/profil/spieler/469976.
Transfer history data appended for: https://www.transfermarkt.com/opa-sangante/profil/spieler/352448.
Transfer history data appended for: https://www.transfermarkt.com/julien-fabri/profil/spieler/238635.
Transfer history data appended for: https://www.transfermarkt.com/chaker-alhadhur/profil/spieler/178540.
Transfer history data appended for: https://www.transfermarkt.com/baptiste-canelhas-reiffers/profil/spieler/802823.
Transfer history data appended for: https://www.transfermarkt.com/alexis-goncalves-pereira/profil/spieler/691908.
Transfer history data appended for: https://www.transfermarkt.com/nama-fofana/profil/spieler/316748.
Transfer history data appended for: https://www.transfermarkt.com/sirine-doucoure/profil/spieler/802747.
Transfer history data appended for: https://www.transfermarkt.com/guevin-tormin/profil/spieler/318529.
Transfer history data appended for: https://www.transfermarkt.com/alimami-gory/profil/spieler/435492.
Transfer history data appended for: https://www.transfermarkt.com/eden-massouema/profil/spieler/452876.
Transfer history data appended for: https://www.transfermarkt.com/tristan-dingome/profil/spieler/126683.
Transfer history data appended for: https://www.transfermarkt.com/sebastien-renot/profil/spieler/125350.
Transfer history data appended for: https://www.transfermarkt.com/benrandy-abdallah/profil/spieler/485959.
Transfer history data appended for: https://www.transfermarkt.com/yoann-touzghar/profil/spieler/68718.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-mutombo/profil/spieler/341394.
Transfer history data appended for: https://www.transfermarkt.com/rominigue-kouame/profil/spieler/277635.
Transfer history data appended for: https://www.transfermarkt.com/dylan-saint-louis/profil/spieler/355370.
Transfer history data appended for: https://www.transfermarkt.com/mahamadou-dembele/profil/spieler/394326.
Transfer history data appended for: https://www.transfermarkt.com/rui-pires/profil/spieler/398324.

Transfer history data appended for: https://www.transfermarkt.com/rayan-raveloson/profil/spieler/344576.
Transfer history data appended for: https://www.transfermarkt.com/yoann-salmier/profil/spieler/351843.
Transfer history data appended for: https://www.transfermarkt.com/oualid-el-hajjam/profil/spieler/283127.
Transfer history data appended for: https://www.transfermarkt.com/stone-mambo/profil/spieler/591911.
Transfer history data appended for: https://www.transfermarkt.com/lenny-pintor/profil/spieler/418660.
Transfer history data appended for: https://www.transfermarkt.com/maxime-barthelme/profil/spieler/112022.
Transfer history data appended for: https://www.transfermarkt.com/brandon-domingues/profil/spieler/804708.
Transfer history data appended for: https://www.transfermarkt.com/florian-tardieu/profil/spieler/212804.
Transfer history data appended for: https://www.transfermarkt.com/kemehlo-nguena/profil/spieler/820336.
Transfer history data appended for: https://www.transfermarkt.com/terence-baya/profil/spieler/468705.
Transfer history data appended for: https://www.transfermarkt.com/ryan-bouallak/profil/spieler/510262.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-giraudon/profil/spieler/213052.
Transfer history data appended for: https://www.transfermarkt.com/levi-lumeka/profil/spieler/537182.
Transfer history data appended for: https://www.transfermarkt.com/calvin-bombo/profil/spieler/485962.
Transfer history data appended for: https://www.transfermarkt.com/dylan-chambost/profil/spieler/508941.
Transfer history data appended for: https://www.transfermarkt.com/gauthier-gallon/profil/spieler/193256.
Transfer history data appended for: https://www.transfermarkt.com/romain-sans/profil/spieler/641438.
Transfer history data appended for: https://www.transfermarkt.com/younes-kaabouni/profil/spieler/182898.
Transfer history data appended for: https://www.transfermarkt.com/yann-kitala/profil/spieler/395677.
Transfer history data appended for: https://www.transfermarkt.com/abdallah-ndour/profil/spieler/232854.
Transfer history data appended for: https://www.transfermarkt.com/nathan-zohore/profil/spieler/656096.
Transfer history data appended for: https://www.transfermarkt.com/natanael-ntolla/profil/spieler/693358.
Transfer history data appended for: https://www.transfermarkt.com/florentin-pogba/profil/spieler/140497.
Transfer history data appended for: https://www.transfermarkt.com/adama-niane/profil/spieler/253842.
Transfer history data appended for: https://www.transfermarkt.com/fabien-ourega/profil/spieler/216533.
Transfer history data appended for: https://www.transfermarkt.com/maxence-prevot/profil/spieler/394903.
Transfer history data appended for: https://www.transfermarkt.com/christophe-diedhiou/profil/spieler/282031.
Transfer history data appended for: https://www.transfermarkt.com/pape-paye/profil/spieler/93744.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-jeannin/profil/spieler/191882.
Transfer history data appended for: https://www.transfermarkt.com/bryan-lasme/profil/spieler/477109.
Transfer history data appended for: https://www.transfermarkt.com/steve-ambri/profil/spieler/457780.
Transfer history data appended for: https://www.transfermarkt.com/johan-martial/profil/spieler/105388.
Transfer history data appended for: https://www.transfermarkt.com/samy-faraj/profil/spieler/810987.
Transfer history data appended for: https://www.transfermarkt.com/chris-bedia/profil/spieler/294791.
Transfer history data appended for: https://www.transfermarkt.com/bryan-soumare/profil/spieler/644563.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-weissbeck/profil/spieler/347958.
Transfer history data appended for: https://www.transfermarkt.com/rassoul-ndiaye/profil/spieler/662242.
Transfer history data appended for: https://www.transfermarkt.com/joseph-lopy/profil/spieler/204585.
Transfer history data appended for: https://www.transfermarkt.com/walid-jarmouni/profil/spieler/789533.
Transfer history data appended for: https://www.transfermarkt.com/manuel-semedo/profil/spieler/540661.
Transfer history data appended for: https://www.transfermarkt.com/boris-moltenis/profil/spieler/594109.
Transfer history data appended for: https://www.transfermarkt.com/sofiane-daham/profil/spieler/290604.
Transfer history data appended for: https://www.transfermarkt.com/salem-mbakata/profil/spieler/590926.
Transfer history data appended for: https://www.transfermarkt.com/aubin-long/profil/spieler/411434.
Transfer history data appended for: https://www.transfermarkt.com/ousseynou-thioune/profil/spieler/410222.
Transfer history data appended for: https://www.transfermarkt.com/sam-sanna/profil/spieler/694549.
Transfer history data appended for: https://www.transfermarkt.com/ruben-gabrielsen/profil/spieler/107662.
Transfer history data appended for: https://www.transfermarkt.com/branco-van-den-boomen/profil/spieler/203938.
Transfer history data appended for: https://www.transfermarkt.com/rhys-healey/profil/spieler/238185.
Transfer history data appended for: https://www.transfermarkt.com/stephane-zobo/profil/spieler/690797.
Transfer history data appended for: https://www.transfermarkt.com/steven-moreira/profil/spieler/203517.
Transfer history data appended for: https://www.transfermarkt.com/anthony-rouault/profil/spieler/690799.
Transfer history data appended for: https://www.transfermarkt.com/vakoun-issouf-bayo/profil/spieler/375877.
Transfer history data appended for: https://www.transfermarkt.com/nathan-ngoumou/profil/spieler/629588.
Transfer history data appended for: https://www.transfermarkt.com/kelvin-amian/profil/spieler/344072.
Transfer history data appended for: https://www.transfermarkt.com/kalidou-sidibe/profil/spieler/629585.
Transfer history data appended for: https://www.transfermarkt.com/moussa-diarra/profil/spieler/694509.
Transfer history data appended for: https://www.transfermarkt.com/firmin-mubele/profil/spieler/265504.
Transfer history data appended for: https://www.transfermarkt.com/stijn-spierings/profil/spieler/241501.
Transfer history data appended for: https://www.transfermarkt.com/bafode-diakite/profil/spieler/463605.
Transfer history data appended for: https://www.transfermarkt.com/efthymios-koulouris/profil/spieler/242638.
Transfer history data appended for: https://www.transfermarkt.com/kouadio-kone/profil/spieler/624690.
Transfer history data appended for: https://www.transfermarkt.com/florentin-bloch/profil/spieler/582698.
Transfer history data appended for: https://www.transfermarkt.com/wesley-said/profil/spieler/182916.
Transfer history data appended for: https://www.transfermarkt.com/agustin-rogel/profil/spieler/456535.
Transfer history data appended for: https://www.transfermarkt.com/brecht-dejaegere/profil/spieler/159098.
Transfer history data appended for: https://www.transfermarkt.com/adil-taoui/profil/spieler/463617.
Transfer history data appended for: https://www.transfermarkt.com/janis-antiste/profil/spieler/538974.
Transfer history data appended for: https://www.transfermarkt.com/deiver-machado/profil/spieler/332560.
Transfer history data appended for: https://www.transfermarkt.com/maxime-dupe/profil/spieler/127188.
Transfer history data appended for: https://www.transfermarkt.com/amine-adli/profil/spieler/532776.
Transfer history data appended for: https://www.transfermarkt.com/ali-abdi/profil/spieler/211474.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-laura/profil/spieler/291124.
Transfer history data appended for: https://www.transfermarkt.com/cyril-mandouki/profil/spieler/412086.
Transfer history data appended for: https://www.transfermarkt.com/morgan-guilavogui/profil/spieler/691786.
Transfer history data appended for: https://www.transfermarkt.com/julien-lopez/profil/spieler/170506.
Transfer history data appended for: https://www.transfermarkt.com/arnaud-tattevin/profil/spieler/395246.
Transfer history data appended for: https://www.transfermarkt.com/warren-caddy/profil/spieler/369599.
Transfer history data appended for: https://www.transfermarkt.com/lamine-diaby-fadiga/profil/spieler/495669.
Transfer history data appended for: https://www.transfermarkt.com/mario-jason-kikonda/profil/spieler/562452.

Transfer history data appended for: https://www.transfermarkt.com/hugo-gambor/profil/spieler/775403.
Transfer history data appended for: https://www.transfermarkt.com/florian-martin/profil/spieler/150496.
Transfer history data appended for: https://www.transfermarkt.com/moustapha-name/profil/spieler/586262.
Transfer history data appended for: https://www.transfermarkt.com/florent-hanin/profil/spieler/111811.
Transfer history data appended for: https://www.transfermarkt.com/jaouen-hadjam/profil/spieler/750903.
Transfer history data appended for: https://www.transfermarkt.com/ousmane-kante/profil/spieler/528470.
Transfer history data appended for: https://www.transfermarkt.com/patrick-koffi/profil/spieler/748958.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-pitroipa/profil/spieler/19139.
Transfer history data appended for: https://www.transfermarkt.com/anthony-maisonnial/profil/spieler/324829.
Transfer history data appended for: https://www.transfermarkt.com/vincent-demarconnay/profil/spieler/111216.
Transfer history data appended for: https://www.transfermarkt.com/andy-pembele/profil/spieler/798893.
Transfer history data appended for: https://www.transfermarkt.com/lalaina-nomenjanahary/profil/spieler/77745.
Transfer history data appended for: https://www.transfermarkt.com/thibault-campanini/profil/spieler/449223.
Transfer history data appended for: https://www.transfermarkt.com/franck-elle-essouma/profil/spieler/591915.
Transfer history data appended for: https://www.transfermarkt.com/youssoupha-ndiaye/profil/spieler/524658.
Transfer history data appended for: https://www.transfermarkt.com/axel-bamba/profil/spieler/545487.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-belaud/profil/spieler/103060.
Transfer history data appended for: https://www.transfermarkt.com/said-arab/profil/spieler/436170.
Transfer history data appended for: https://www.transfermarkt.com/marvin-gakpa/profil/spieler/170976.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-ntim/profil/spieler/375287.
Transfer history data appended for: https://www.transfermarkt.com/aymen-boutoutaou/profil/spieler/730580.
Transfer history data appended for: https://www.transfermarkt.com/teddy-chevalier/profil/spieler/57514.
Transfer history data appended for: https://www.transfermarkt.com/maxime-spano/profil/spieler/329221.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-moukandjo/profil/spieler/59957.
Transfer history data appended for: https://www.transfermarkt.com/julien-masson/profil/spieler/494315.
Transfer history data appended for: https://www.transfermarkt.com/mathis-picouleau/profil/spieler/395240.
Transfer history data appended for: https://www.transfermarkt.com/noah-diliberto/profil/spieler/730280.
Transfer history data appended for: https://www.transfermarkt.com/moussa-guel/profil/spieler/556371.
Transfer history data appended for: https://www.transfermarkt.com/baptiste-guillaume/profil/spieler/264567.
Transfer history data appended for: https://www.transfermarkt.com/eric-vandenabeele/profil/spieler/213030.
Transfer history data appended for: https://www.transfermarkt.com/theo-pellenard/profil/spieler/238716.
Transfer history data appended for: https://www.transfermarkt.com/kevin-cabral/profil/spieler/460632.
Transfer history data appended for: https://www.transfermarkt.com/laurent-dos-santos/profil/spieler/274571.
Transfer history data appended for: https://www.transfermarkt.com/matteo-fedele/profil/spieler/111438.
Transfer history data appended for: https://www.transfermarkt.com/joffrey-cuffaut/profil/spieler/109720.
Transfer history data appended for: https://www.transfermarkt.com/jerome-prior/profil/spieler/238720.
Transfer history data appended for: https://www.transfermarkt.com/allan-linguet/profil/spieler/635486.
Transfer history data appended for: https://www.transfermarkt.com/metehan-guclu/profil/spieler/395519.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-kocik/profil/spieler/357069.
Transfer history data appended for: https://www.transfermarkt.com/hillel-konate/profil/spieler/170549.
Transfer history data appended for: https://www.transfermarkt.com/elhadj-dabo/profil/spieler/377394.
Transfer history data appended for: https://www.transfermarkt.com/arsene-elogo/profil/spieler/409418.
Transfer history data appended for: https://www.transfermarkt.com/aly-abeid/profil/spieler/393436.
Transfer history data appended for: https://www.transfermarkt.com/malek-chergui/profil/spieler/147009.
Transfer history data appended for: https://www.transfermarkt.com/sessi-dalmeida/profil/spieler/291111.
Transfer history data appended for: https://www.transfermarkt.com/mickael-latour/profil/spieler/203512.
Transfer history data appended for: https://www.transfermarkt.com/sebastien-flochon/profil/spieler/203497.
Transfer history data appended for: https://www.transfermarkt.com/yannick-mamilonne/profil/spieler/440886.
Transfer history data appended for: https://www.transfermarkt.com/bradley-danger/profil/spieler/324798.
Transfer history data appended for: https://www.transfermarkt.com/marvin-martin/profil/spieler/77834.
Transfer history data appended for: https://www.transfermarkt.com/cyril-zabou/profil/spieler/644080.
Transfer history data appended for: https://www.transfermarkt.com/xavier-pinoteau/profil/spieler/111749.
Transfer history data appended for: https://www.transfermarkt.com/bastian-badu/profil/spieler/591197.
Transfer history data appended for: https://www.transfermarkt.com/nikola-petkovic/profil/spieler/552160.
Transfer history data appended for: https://www.transfermarkt.com/vlatko-stojanovski/profil/spieler/345041.
Transfer history data appended for: https://www.transfermarkt.com/john-popelard/profil/spieler/411428.
Transfer history data appended for: https://www.transfermarkt.com/lucas-camelo/profil/spieler/603545.
Transfer history data appended for: https://www.transfermarkt.com/boubacari-doucoure/profil/spieler/507630.
Transfer history data appended for: https://www.transfermarkt.com/oumar-gonzalez/profil/spieler/388795.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-beaulieu/profil/spieler/170982.
Transfer history data appended for: https://www.transfermarkt.com/maxence-derrien/profil/spieler/205525.
Transfer history data appended for: https://www.transfermarkt.com/anthony-soubervie/profil/spieler/110154.
Transfer history data appended for: https://www.transfermarkt.com/luka-susnjara/profil/spieler/334724.
Transfer history data appended for: https://www.transfermarkt.com/guillaume-heinry/profil/spieler/418594.
Transfer history data appended for: https://www.transfermarkt.com/florian-david/profil/spieler/170905.
Transfer history data appended for: https://www.transfermarkt.com/killian-le-roy/profil/spieler/353368.
Transfer history data appended for: https://www.transfermarkt.com/joris-correa/profil/spieler/303406.
Transfer history data appended for: https://www.transfermarkt.com/simon-pontdeme/profil/spieler/45106.
Transfer history data appended for: https://www.transfermarkt.com/guillaume-dequaire/profil/spieler/239255.
Transfer history data appended for: https://www.transfermarkt.com/medhy-guezoui/profil/spieler/127038.
Transfer history data appended for: https://www.transfermarkt.com/aniss-el-hriti/profil/spieler/233858.
Transfer history data appended for: https://www.transfermarkt.com/joachim-eickmayer/profil/spieler/271390.
Transfer history data appended for: https://www.transfermarkt.com/thibault-jaques/profil/spieler/174361.
Transfer history data appended for: https://www.transfermarkt.com/shaquil-delos/profil/spieler/650809.
Transfer history data appended for: https://www.transfermarkt.com/lassana-doucoure/profil/spieler/257345.
Transfer history data appended for: https://www.transfermarkt.com/adrien-monfray/profil/spieler/281611.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-diallo/profil/spieler/290605.
Transfer history data appended for: https://www.transfermarkt.com/loris-nery/profil/spieler/126659.
Transfer history data appended for: https://www.transfermarkt.com/manuel-perez/profil/spieler/166630.

Transfer history data appended for: https://www.transfermarkt.com/david-henen/profil/spieler/202831.
Transfer history data appended for: https://www.transfermarkt.com/brice-maubleu/profil/spieler/78047.
Transfer history data appended for: https://www.transfermarkt.com/abdel-hakim-abdallah/profil/spieler/483460.
Transfer history data appended for: https://www.transfermarkt.com/harouna-abou-demba/profil/spieler/351838.
Transfer history data appended for: https://www.transfermarkt.com/bart-straalman/profil/spieler/336303.
Transfer history data appended for: https://www.transfermarkt.com/jessy-benet/profil/spieler/332047.
Transfer history data appended for: https://www.transfermarkt.com/moussa-djitte/profil/spieler/591796.
Transfer history data appended for: https://www.transfermarkt.com/jules-sylvestre-brac/profil/spieler/693636.
Transfer history data appended for: https://www.transfermarkt.com/willy-semedo/profil/spieler/531450.
Transfer history data appended for: https://www.transfermarkt.com/jerome-mombris/profil/spieler/141102.
Transfer history data appended for: https://www.transfermarkt.com/anthony-belmonte/profil/spieler/231916.
Transfer history data appended for: https://www.transfermarkt.com/yoric-ravet/profil/spieler/82461.
Transfer history data appended for: https://www.transfermarkt.com/achille-anani/profil/spieler/238627.
Transfer history data appended for: https://www.transfermarkt.com/esteban-salles/profil/spieler/323253.
Transfer history data appended for: https://www.transfermarkt.com/jordy-gaspar/profil/spieler/353395.
Transfer history data appended for: https://www.transfermarkt.com/florian-michel/profil/spieler/693356.
Transfer history data appended for: https://www.transfermarkt.com/kevin-tapoko/profil/spieler/192526.
Transfer history data appended for: https://www.transfermarkt.com/paul-bourdelle/profil/spieler/583393.
Transfer history data appended for: https://www.transfermarkt.com/loic-nestor/profil/spieler/66490.
Transfer history data appended for: https://www.transfermarkt.com/charles-pickel/profil/spieler/243879.
Transfer history data appended for: https://www.transfermarkt.com/chris-goteni/profil/spieler/676191.
Transfer history data appended for: https://www.transfermarkt.com/ismael-diallo/profil/spieler/375881.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-coutadeur/profil/spieler/39914.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-courtet/profil/spieler/171408.
Transfer history data appended for: https://www.transfermarkt.com/mickael-barreto/profil/spieler/149518.
Transfer history data appended for: https://www.transfermarkt.com/cedric-avinel/profil/spieler/44421.
Transfer history data appended for: https://www.transfermarkt.com/joris-sainati/profil/spieler/119081.
Transfer history data appended for: https://www.transfermarkt.com/baptiste-dedola/profil/spieler/804660.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-keita/profil/spieler/178019.
Transfer history data appended for: https://www.transfermarkt.com/sidney-obissa/profil/spieler/748362.
Transfer history data appended for: https://www.transfermarkt.com/alassane-ndiaye/profil/spieler/281704.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-youssouf/profil/spieler/57482.
Transfer history data appended for: https://www.transfermarkt.com/lucas-marsella/profil/spieler/624784.
Transfer history data appended for: https://www.transfermarkt.com/riad-nouri/profil/spieler/119104.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-corinus/profil/spieler/621161.
Transfer history data appended for: https://www.transfermarkt.com/vincent-marchetti/profil/spieler/374040.
Transfer history data appended for: https://www.transfermarkt.com/gedeon-kalulu/profil/spieler/395685.
Transfer history data appended for: https://www.transfermarkt.com/mounaim-el-idrissy/profil/spieler/627163.
Transfer history data appended for: https://www.transfermarkt.com/matthieu-huard/profil/spieler/588997.
Transfer history data appended for: https://www.transfermarkt.com/tony-njike/profil/spieler/742226.
Transfer history data appended for: https://www.transfermarkt.com/faiz-mattoir/profil/spieler/730573.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-leroy/profil/spieler/124901.
Transfer history data appended for: https://www.transfermarkt.com/yanis-cimignani/profil/spieler/801754.
Transfer history data appended for: https://www.transfermarkt.com/bevic-moussiti-oko/profil/spieler/364525.
Transfer history data appended for: https://www.transfermarkt.com/qazim-laci/profil/spieler/290552.
Transfer history data appended for: https://www.transfermarkt.com/simon-elisor/profil/spieler/804661.
Transfer history data appended for: https://www.transfermarkt.com/quentin-lecoeuche/profil/spieler/332142.
Transfer history data appended for: https://www.transfermarkt.com/alexis-alegue/profil/spieler/228999.
Transfer history data appended for: https://www.transfermarkt.com/david-douline/profil/spieler/237843.
Transfer history data appended for: https://www.transfermarkt.com/valentin-henry/profil/spieler/353981.
Transfer history data appended for: https://www.transfermarkt.com/loic-poujol/profil/spieler/109039.
Transfer history data appended for: https://www.transfermarkt.com/ugo-bonnet/profil/spieler/525114.
Transfer history data appended for: https://www.transfermarkt.com/ayoub-ouhafsa/profil/spieler/562425.
Transfer history data appended for: https://www.transfermarkt.com/yohan-roche/profil/spieler/524988.
Transfer history data appended for: https://www.transfermarkt.com/aurelien-tertereau/profil/spieler/118300.
Transfer history data appended for: https://www.transfermarkt.com/gregory-coelho/profil/spieler/678660.
Transfer history data appended for: https://www.transfermarkt.com/pierre-bardy/profil/spieler/525108.
Transfer history data appended for: https://www.transfermarkt.com/alan-kerouedan/profil/spieler/395244.
Transfer history data appended for: https://www.transfermarkt.com/johann-obiang/profil/spieler/254358.
Transfer history data appended for: https://www.transfermarkt.com/amiran-sanaia/profil/spieler/107395.
Transfer history data appended for: https://www.transfermarkt.com/theo-guivarch/profil/spieler/358505.
Transfer history data appended for: https://www.transfermarkt.com/pape-sane/profil/spieler/182312.
Transfer history data appended for: https://www.transfermarkt.com/daouda-gueye/profil/spieler/777265.
Transfer history data appended for: https://www.transfermarkt.com/joris-chougrani/profil/spieler/525109.
Transfer history data appended for: https://www.transfermarkt.com/lionel-mpasi-nzau/profil/spieler/164915.
Transfer history data appended for: https://www.transfermarkt.com/alexis-peyrelade/profil/spieler/562174.
Transfer history data appended for: https://www.transfermarkt.com/pierre-ruffaut/profil/spieler/306224.
Transfer history data appended for: https://www.transfermarkt.com/julien-ponceau/profil/spieler/569390.
Transfer history data appended for: https://www.transfermarkt.com/malaly-dembele/profil/spieler/508940.
Transfer history data appended for: https://www.transfermarkt.com/nassim-ouammou/profil/spieler/352125.
Transfer history data appended for: https://www.transfermarkt.com/nathanael-dieng/profil/spieler/491781.
Transfer history data appended for: https://www.transfermarkt.com/jordan-leborgne/profil/spieler/379742.
Transfer history data appended for: https://www.transfermarkt.com/remy-boissier/profil/spieler/525111.
Transfer history data appended for: https://www.transfermarkt.com/boris-mathis/profil/spieler/500087.
Transfer history data appended for: https://www.transfermarkt.com/thomas-secchi/profil/spieler/525107.
Transfer history data appended for: https://www.transfermarkt.com/juan-mata/profil/spieler/44068.
Transfer history data appended for: https://www.transfermarkt.com/fred/profil/spieler/191614.
Transfer history data appended for: https://www.transfermarkt.com/mason-greenwood/profil/spieler/532826.
Transfer history data appended for: https://www.transfermarkt.com/aaron-wan-bissaka/profil/spieler/477758.
Transfer history data appended for: https://www.transfermarkt.com/axel-tuanzebe/profil/spieler/342046.

Transfer history data appended for: https://www.transfermarkt.com/nemanja-matic/profil/spieler/74683.
Transfer history data appended for: https://www.transfermarkt.com/david-de-gea/profil/spieler/59377.
Transfer history data appended for: https://www.transfermarkt.com/bruno-fernandes/profil/spieler/240306.
Transfer history data appended for: https://www.transfermarkt.com/dean-henderson/profil/spieler/258919.
Transfer history data appended for: https://www.transfermarkt.com/brandon-williams/profil/spieler/507700.
Transfer history data appended for: https://www.transfermarkt.com/luke-shaw/profil/spieler/183288.
Transfer history data appended for: https://www.transfermarkt.com/eric-bailly/profil/spieler/286384.
Transfer history data appended for: https://www.transfermarkt.com/alex-telles/profil/spieler/255755.
Transfer history data appended for: https://www.transfermarkt.com/donny-van-de-beek/profil/spieler/288255.
Transfer history data appended for: https://www.transfermarkt.com/timothy-fosu-mensah/profil/spieler/315131.
Transfer history data appended for: https://www.transfermarkt.com/marcus-rashford/profil/spieler/258923.
Transfer history data appended for: https://www.transfermarkt.com/sergio-romero/profil/spieler/30690.
Transfer history data appended for: https://www.transfermarkt.com/marcos-rojo/profil/spieler/93176.
Transfer history data appended for: https://www.transfermarkt.com/phil-jones/profil/spieler/117996.
Transfer history data appended for: https://www.transfermarkt.com/edinson-cavani/profil/spieler/48280.
Transfer history data appended for: https://www.transfermarkt.com/harry-maguire/profil/spieler/177907.
Transfer history data appended for: https://www.transfermarkt.com/lee-grant/profil/spieler/13460.
Transfer history data appended for: https://www.transfermarkt.com/jesse-lingard/profil/spieler/141660.
Transfer history data appended for: https://www.transfermarkt.com/daniel-james/profil/spieler/319301.
Transfer history data appended for: https://www.transfermarkt.com/victor-lindelof/profil/spieler/184573.
Transfer history data appended for: https://www.transfermarkt.com/odion-ighalo/profil/spieler/62121.
Transfer history data appended for: https://www.transfermarkt.com/scott-mctominay/profil/spieler/315969.
Transfer history data appended for: https://www.transfermarkt.com/anthony-martial/profil/spieler/182877.
Transfer history data appended for: https://www.transfermarkt.com/paul-pogba/profil/spieler/122153.
Transfer history data appended for: https://www.transfermarkt.com/bobby-thomas/profil/spieler/788283.
Transfer history data appended for: https://www.transfermarkt.com/jack-cork/profil/spieler/40613.
Transfer history data appended for: https://www.transfermarkt.com/johann-berg-gudmundsson/profil/spieler/89231.
Transfer history data appended for: https://www.transfermarkt.com/jay-rodriguez/profil/spieler/53360.
Transfer history data appended for: https://www.transfermarkt.com/ben-mee/profil/spieler/74810.
Transfer history data appended for: https://www.transfermarkt.com/richard-nartey/profil/spieler/396861.
Transfer history data appended for: https://www.transfermarkt.com/ashley-barnes/profil/spieler/63200.
Transfer history data appended for: https://www.transfermarkt.com/lukas-jensen/profil/spieler/581890.
Transfer history data appended for: https://www.transfermarkt.com/ashley-westwood/profil/spieler/91317.
Transfer history data appended for: https://www.transfermarkt.com/phil-bardsley/profil/spieler/15773.
Transfer history data appended for: https://www.transfermarkt.com/bailey-peacock-farrell/profil/spieler/410436.
Transfer history data appended for: https://www.transfermarkt.com/mace-goodridge/profil/spieler/382552.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-dunne/profil/spieler/396174.
Transfer history data appended for: https://www.transfermarkt.com/robbie-brady/profil/spieler/128229.
Transfer history data appended for: https://www.transfermarkt.com/dwight-mcneil/profil/spieler/584769.
Transfer history data appended for: https://www.transfermarkt.com/chris-wood/profil/spieler/108725.
Transfer history data appended for: https://www.transfermarkt.com/nick-pope/profil/spieler/192080.
Transfer history data appended for: https://www.transfermarkt.com/charlie-taylor/profil/spieler/195633.
Transfer history data appended for: https://www.transfermarkt.com/erik-pieters/profil/spieler/43763.
Transfer history data appended for: https://www.transfermarkt.com/will-norris/profil/spieler/285033.
Transfer history data appended for: https://www.transfermarkt.com/matej-vydra/profil/spieler/101500.
Transfer history data appended for: https://www.transfermarkt.com/josh-brownhill/profil/spieler/293569.
Transfer history data appended for: https://www.transfermarkt.com/dale-stephens/profil/spieler/49755.
Transfer history data appended for: https://www.transfermarkt.com/james-tarkowski/profil/spieler/173504.
Transfer history data appended for: https://www.transfermarkt.com/matthew-lowton/profil/spieler/102258.
Transfer history data appended for: https://www.transfermarkt.com/kevin-long/profil/spieler/111114.
Transfer history data appended for: https://www.transfermarkt.com/jorginho/profil/spieler/102017.
Transfer history data appended for: https://www.transfermarkt.com/danny-drinkwater/profil/spieler/73491.
Transfer history data appended for: https://www.transfermarkt.com/ben-chilwell/profil/spieler/316125.
Transfer history data appended for: https://www.transfermarkt.com/timo-werner/profil/spieler/170527.
Transfer history data appended for: https://www.transfermarkt.com/callum-hudson-odoi/profil/spieler/392768.
Transfer history data appended for: https://www.transfermarkt.com/charly-musonda-jr-/profil/spieler/177862.
Transfer history data appended for: https://www.transfermarkt.com/reece-james/profil/spieler/472423.
Transfer history data appended for: https://www.transfermarkt.com/andreas-christensen/profil/spieler/196948.
Transfer history data appended for: https://www.transfermarkt.com/edouard-mendy/profil/spieler/442531.
Transfer history data appended for: https://www.transfermarkt.com/christian-pulisic/profil/spieler/315779.
Transfer history data appended for: https://www.transfermarkt.com/marcos-alonso/profil/spieler/112515.
Transfer history data appended for: https://www.transfermarkt.com/ngolo-kante/profil/spieler/225083.
Transfer history data appended for: https://www.transfermarkt.com/mateo-kovacic/profil/spieler/51471.
Transfer history data appended for: https://www.transfermarkt.com/kurt-zouma/profil/spieler/157509.
Transfer history data appended for: https://www.transfermarkt.com/olivier-giroud/profil/spieler/82442.
Transfer history data appended for: https://www.transfermarkt.com/kepa/profil/spieler/192279.
Transfer history data appended for: https://www.transfermarkt.com/willy-caballero/profil/spieler/19948.
Transfer history data appended for: https://www.transfermarkt.com/cesar-azpilicueta/profil/spieler/57500.
Transfer history data appended for: https://www.transfermarkt.com/thiago-silva/profil/spieler/29241.
Transfer history data appended for: https://www.transfermarkt.com/billy-gilmour/profil/spieler/423744.
Transfer history data appended for: https://www.transfermarkt.com/emerson/profil/spieler/181778.
Transfer history data appended for: https://www.transfermarkt.com/mason-mount/profil/spieler/346483.
Transfer history data appended for: https://www.transfermarkt.com/tammy-abraham/profil/spieler/331726.
Transfer history data appended for: https://www.transfermarkt.com/hakim-ziyech/profil/spieler/217111.
Transfer history data appended for: https://www.transfermarkt.com/fikayo-tomori/profil/spieler/303254.
Transfer history data appended for: https://www.transfermarkt.com/antonio-rudiger/profil/spieler/86202.
Transfer history data appended for: https://www.transfermarkt.com/kai-havertz/profil/spieler/309400.
Transfer history data appended for: https://www.transfermarkt.com/seamus-coleman/profil/spieler/68390.
Transfer history data appended for: https://www.transfermarkt.com/jonjoe-kenny/profil/spieler/258883.
Transfer history data appended for: https://www.transfermarkt.com/mason-holgate/profil/spieler/348623.

Transfer history data appended for: https://www.transfermarkt.com/joao-virginia/profil/spieler/329813.
Transfer history data appended for: https://www.transfermarkt.com/michael-keane/profil/spieler/118534.
Transfer history data appended for: https://www.transfermarkt.com/ben-godfrey/profil/spieler/343475.
Transfer history data appended for: https://www.transfermarkt.com/cenk-tosun/profil/spieler/45671.
Transfer history data appended for: https://www.transfermarkt.com/niels-nkounkou/profil/spieler/591193.
Transfer history data appended for: https://www.transfermarkt.com/jean-philippe-gbamin/profil/spieler/182894.
Transfer history data appended for: https://www.transfermarkt.com/tom-davies/profil/spieler/314210.
Transfer history data appended for: https://www.transfermarkt.com/fabian-delph/profil/spieler/50362.
Transfer history data appended for: https://www.transfermarkt.com/anthony-gordon/profil/spieler/503733.
Transfer history data appended for: https://www.transfermarkt.com/dominic-calvert-lewin/profil/spieler/306024.
Transfer history data appended for: https://www.transfermarkt.com/beni-baningime/profil/spieler/399369.
Transfer history data appended for: https://www.transfermarkt.com/yerry-mina/profil/spieler/289446.
Transfer history data appended for: https://www.transfermarkt.com/jarrad-branthwaite/profil/spieler/661053.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-doucoure/profil/spieler/127187.
Transfer history data appended for: https://www.transfermarkt.com/james-rodriguez/profil/spieler/88103.
Transfer history data appended for: https://www.transfermarkt.com/richarlison/profil/spieler/378710.
Transfer history data appended for: https://www.transfermarkt.com/allan/profil/spieler/126422.
Transfer history data appended for: https://www.transfermarkt.com/jordan-pickford/profil/spieler/130164.
Transfer history data appended for: https://www.transfermarkt.com/bernard/profil/spieler/175169.
Transfer history data appended for: https://www.transfermarkt.com/jonas-lossl/profil/spieler/48870.
Transfer history data appended for: https://www.transfermarkt.com/alex-iwobi/profil/spieler/242631.
Transfer history data appended for: https://www.transfermarkt.com/lucas-digne/profil/spieler/126664.
Transfer history data appended for: https://www.transfermarkt.com/andre-gomes/profil/spieler/221025.
Transfer history data appended for: https://www.transfermarkt.com/andy-carroll/profil/spieler/48066.
Transfer history data appended for: https://www.transfermarkt.com/dwight-gayle/profil/spieler/196522.
Transfer history data appended for: https://www.transfermarkt.com/sean-longstaff/profil/spieler/346707.
Transfer history data appended for: https://www.transfermarkt.com/allan-saint-maximin/profil/spieler/272642.
Transfer history data appended for: https://www.transfermarkt.com/miguel-almiron/profil/spieler/272999.
Transfer history data appended for: https://www.transfermarkt.com/karl-darlow/profil/spieler/99397.
Transfer history data appended for: https://www.transfermarkt.com/jonjo-shelvey/profil/spieler/71292.
Transfer history data appended for: https://www.transfermarkt.com/mark-gillespie/profil/spieler/142389.
Transfer history data appended for: https://www.transfermarkt.com/jeff-hendrick/profil/spieler/148262.
Transfer history data appended for: https://www.transfermarkt.com/emil-krafth/profil/spieler/184528.
Transfer history data appended for: https://www.transfermarkt.com/paul-dummett/profil/spieler/170321.
Transfer history data appended for: https://www.transfermarkt.com/jamaal-lascelles/profil/spieler/183318.
Transfer history data appended for: https://www.transfermarkt.com/matthew-longstaff/profil/spieler/484387.
Transfer history data appended for: https://www.transfermarkt.com/dan-langley/profil/spieler/532824.
Transfer history data appended for: https://www.transfermarkt.com/jamal-lewis/profil/spieler/346018.
Transfer history data appended for: https://www.transfermarkt.com/ciaran-clark/profil/spieler/98240.
Transfer history data appended for: https://www.transfermarkt.com/matt-ritchie/profil/spieler/92469.
Transfer history data appended for: https://www.transfermarkt.com/javier-manquillo/profil/spieler/162029.
Transfer history data appended for: https://www.transfermarkt.com/callum-wilson/profil/spieler/123682.
Transfer history data appended for: https://www.transfermarkt.com/federico-fernandez/profil/spieler/85475.
Transfer history data appended for: https://www.transfermarkt.com/isaac-hayden/profil/spieler/206225.
Transfer history data appended for: https://www.transfermarkt.com/fabian-schar/profil/spieler/135343.
Transfer history data appended for: https://www.transfermarkt.com/ryan-fraser/profil/spieler/146795.
Transfer history data appended for: https://www.transfermarkt.com/martin-dubravka/profil/spieler/74960.
Transfer history data appended for: https://www.transfermarkt.com/deandre-yedlin/profil/spieler/255916.
Transfer history data appended for: https://www.transfermarkt.com/fabinho/profil/spieler/225693.
Transfer history data appended for: https://www.transfermarkt.com/curtis-jones/profil/spieler/433188.
Transfer history data appended for: https://www.transfermarkt.com/alisson/profil/spieler/105470.
Transfer history data appended for: https://www.transfermarkt.com/sadio-mane/profil/spieler/200512.
Transfer history data appended for: https://www.transfermarkt.com/nathaniel-phillips/profil/spieler/371814.
Transfer history data appended for: https://www.transfermarkt.com/adrian/profil/spieler/71271.
Transfer history data appended for: https://www.transfermarkt.com/xherdan-shaqiri/profil/spieler/86792.
Transfer history data appended for: https://www.transfermarkt.com/georginio-wijnaldum/profil/spieler/49499.
Transfer history data appended for: https://www.transfermarkt.com/neco-williams/profil/spieler/503680.
Transfer history data appended for: https://www.transfermarkt.com/joe-gomez/profil/spieler/256178.
Transfer history data appended for: https://www.transfermarkt.com/andrew-robertson/profil/spieler/234803.
Transfer history data appended for: https://www.transfermarkt.com/joel-matip/profil/spieler/82105.
Transfer history data appended for: https://www.transfermarkt.com/rhys-williams/profil/spieler/503679.
Transfer history data appended for: https://www.transfermarkt.com/virgil-van-dijk/profil/spieler/139208.
Transfer history data appended for: https://www.transfermarkt.com/jordan-henderson/profil/spieler/61651.
Transfer history data appended for: https://www.transfermarkt.com/sepp-van-den-berg/profil/spieler/541231.
Transfer history data appended for: https://www.transfermarkt.com/takumi-minamino/profil/spieler/165793.
Transfer history data appended for: https://www.transfermarkt.com/alex-oxlade-chamberlain/profil/spieler/143424.
Transfer history data appended for: https://www.transfermarkt.com/trent-alexander-arnold/profil/spieler/314353.
Transfer history data appended for: https://www.transfermarkt.com/james-milner/profil/spieler/3333.
Transfer history data appended for: https://www.transfermarkt.com/divock-origi/profil/spieler/148368.
Transfer history data appended for: https://www.transfermarkt.com/naby-keita/profil/spieler/302215.
Transfer history data appended for: https://www.transfermarkt.com/roberto-firmino/profil/spieler/131789.
Transfer history data appended for: https://www.transfermarkt.com/thiago/profil/spieler/60444.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-salah/profil/spieler/148455.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-tsimikas/profil/spieler/338070.
Transfer history data appended for: https://www.transfermarkt.com/caoimhin-kelleher/profil/spieler/340918.
Transfer history data appended for: https://www.transfermarkt.com/liam-cooper/profil/spieler/75067.
Transfer history data appended for: https://www.transfermarkt.com/patrick-bamford/profil/spieler/183334.
Transfer history data appended for: https://www.transfermarkt.com/gaetano-berardi/profil/spieler/43084.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo/profil/spieler/131505.
Transfer history data appended for: https://www.transfermarkt.com/pablo-hernandez/profil/spieler/46220.

Transfer history data appended for: https://www.transfermarkt.com/elia-caprile/profil/spieler/421873.
Transfer history data appended for: https://www.transfermarkt.com/ian-poveda/profil/spieler/392763.
Transfer history data appended for: https://www.transfermarkt.com/conor-shaughnessy/profil/spieler/255626.
Transfer history data appended for: https://www.transfermarkt.com/stuart-dallas/profil/spieler/158764.
Transfer history data appended for: https://www.transfermarkt.com/tyler-roberts/profil/spieler/296986.
Transfer history data appended for: https://www.transfermarkt.com/illan-meslier/profil/spieler/542586.
Transfer history data appended for: https://www.transfermarkt.com/diego-llorente/profil/spieler/246291.
Transfer history data appended for: https://www.transfermarkt.com/kalvin-phillips/profil/spieler/351749.
Transfer history data appended for: https://www.transfermarkt.com/jack-harrison/profil/spieler/417346.
Transfer history data appended for: https://www.transfermarkt.com/robin-koch/profil/spieler/328784.
Transfer history data appended for: https://www.transfermarkt.com/ezgjan-alioski/profil/spieler/129604.
Transfer history data appended for: https://www.transfermarkt.com/raphinha/profil/spieler/411295.
Transfer history data appended for: https://www.transfermarkt.com/jay-roy-grot/profil/spieler/360517.
Transfer history data appended for: https://www.transfermarkt.com/leif-davis/profil/spieler/596446.
Transfer history data appended for: https://www.transfermarkt.com/pascal-struijk/profil/spieler/410708.
Transfer history data appended for: https://www.transfermarkt.com/oliver-casey/profil/spieler/559800.
Transfer history data appended for: https://www.transfermarkt.com/helder-costa/profil/spieler/173900.
Transfer history data appended for: https://www.transfermarkt.com/jamie-shackleton/profil/spieler/534700.
Transfer history data appended for: https://www.transfermarkt.com/kiko-casilla/profil/spieler/27486.
Transfer history data appended for: https://www.transfermarkt.com/joe-gelhardt/profil/spieler/503980.
Transfer history data appended for: https://www.transfermarkt.com/adam-forshaw/profil/spieler/121257.
Transfer history data appended for: https://www.transfermarkt.com/luke-ayling/profil/spieler/67420.
Transfer history data appended for: https://www.transfermarkt.com/tyrick-mitchell/profil/spieler/730893.
Transfer history data appended for: https://www.transfermarkt.com/james-mccarthy/profil/spieler/45333.
Transfer history data appended for: https://www.transfermarkt.com/nathan-ferguson/profil/spieler/507254.
Transfer history data appended for: https://www.transfermarkt.com/gary-cahill/profil/spieler/27511.
Transfer history data appended for: https://www.transfermarkt.com/sam-woods/profil/spieler/611650.
Transfer history data appended for: https://www.transfermarkt.com/nathaniel-clyne/profil/spieler/85177.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-sakho/profil/spieler/47713.
Transfer history data appended for: https://www.transfermarkt.com/andros-townsend/profil/spieler/61842.
Transfer history data appended for: https://www.transfermarkt.com/jairo-riedewald/profil/spieler/241481.
Transfer history data appended for: https://www.transfermarkt.com/michy-batshuayi/profil/spieler/179184.
Transfer history data appended for: https://www.transfermarkt.com/christian-benteke/profil/spieler/50201.
Transfer history data appended for: https://www.transfermarkt.com/joel-ward/profil/spieler/92572.
Transfer history data appended for: https://www.transfermarkt.com/jordan-ayew/profil/spieler/108354.
Transfer history data appended for: https://www.transfermarkt.com/patrick-van-aanholt/profil/spieler/52119.
Transfer history data appended for: https://www.transfermarkt.com/max-meyer/profil/spieler/146164.
Transfer history data appended for: https://www.transfermarkt.com/jeffrey-schlupp/profil/spieler/157506.
Transfer history data appended for: https://www.transfermarkt.com/martin-kelly/profil/spieler/78959.
Transfer history data appended for: https://www.transfermarkt.com/scott-dann/profil/spieler/62688.
Transfer history data appended for: https://www.transfermarkt.com/eberechi-eze/profil/spieler/479999.
Transfer history data appended for: https://www.transfermarkt.com/vicente-guaita/profil/spieler/64399.
Transfer history data appended for: https://www.transfermarkt.com/wayne-hennessey/profil/spieler/45494.
Transfer history data appended for: https://www.transfermarkt.com/wilfried-zaha/profil/spieler/145988.
Transfer history data appended for: https://www.transfermarkt.com/james-mcarthur/profil/spieler/41416.
Transfer history data appended for: https://www.transfermarkt.com/connor-wickham/profil/spieler/95435.
Transfer history data appended for: https://www.transfermarkt.com/jack-butland/profil/spieler/128899.
Transfer history data appended for: https://www.transfermarkt.com/stephen-henderson/profil/spieler/52191.
Transfer history data appended for: https://www.transfermarkt.com/james-tomkins/profil/spieler/61592.
Transfer history data appended for: https://www.transfermarkt.com/conor-hourihane/profil/spieler/61653.
Transfer history data appended for: https://www.transfermarkt.com/matty-cash/profil/spieler/425334.
Transfer history data appended for: https://www.transfermarkt.com/jack-grealish/profil/spieler/203460.
Transfer history data appended for: https://www.transfermarkt.com/tom-heaton/profil/spieler/34130.
Transfer history data appended for: https://www.transfermarkt.com/matt-targett/profil/spieler/250478.
Transfer history data appended for: https://www.transfermarkt.com/kortney-hause/profil/spieler/233124.
Transfer history data appended for: https://www.transfermarkt.com/lovre-kalinic/profil/spieler/46405.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-martinez/profil/spieler/111873.
Transfer history data appended for: https://www.transfermarkt.com/henri-lansbury/profil/spieler/44794.
Transfer history data appended for: https://www.transfermarkt.com/ross-barkley/profil/spieler/131978.
Transfer history data appended for: https://www.transfermarkt.com/wesley/profil/spieler/381362.
Transfer history data appended for: https://www.transfermarkt.com/jed-steer/profil/spieler/110867.
Transfer history data appended for: https://www.transfermarkt.com/douglas-luiz/profil/spieler/447661.
Transfer history data appended for: https://www.transfermarkt.com/marvelous-nakamba/profil/spieler/324882.
Transfer history data appended for: https://www.transfermarkt.com/frederic-guilbert/profil/spieler/354352.
Transfer history data appended for: https://www.transfermarkt.com/anwar-el-ghazi/profil/spieler/183720.
Transfer history data appended for: https://www.transfermarkt.com/ezri-konsa/profil/spieler/413403.
Transfer history data appended for: https://www.transfermarkt.com/ollie-watkins/profil/spieler/324358.
Transfer history data appended for: https://www.transfermarkt.com/neil-taylor/profil/spieler/67416.
Transfer history data appended for: https://www.transfermarkt.com/bertrand-traore/profil/spieler/131996.
Transfer history data appended for: https://www.transfermarkt.com/tyrone-mings/profil/spieler/253677.
Transfer history data appended for: https://www.transfermarkt.com/keinan-davis/profil/spieler/412660.
Transfer history data appended for: https://www.transfermarkt.com/john-mcginn/profil/spieler/193116.
Transfer history data appended for: https://www.transfermarkt.com/bernardo-silva/profil/spieler/241641.
Transfer history data appended for: https://www.transfermarkt.com/phil-foden/profil/spieler/406635.
Transfer history data appended for: https://www.transfermarkt.com/sergio-aguero/profil/spieler/26399.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-zinchenko/profil/spieler/203853.
Transfer history data appended for: https://www.transfermarkt.com/raheem-sterling/profil/spieler/134425.
Transfer history data appended for: https://www.transfermarkt.com/aymeric-laporte/profil/spieler/176553.
Transfer history data appended for: https://www.transfermarkt.com/rodri/profil/spieler/357565.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-mendy/profil/spieler/157495.

Transfer history data appended for: https://www.transfermarkt.com/riyad-mahrez/profil/spieler/171424.
Transfer history data appended for: https://www.transfermarkt.com/joao-cancelo/profil/spieler/182712.
Transfer history data appended for: https://www.transfermarkt.com/ederson/profil/spieler/238223.
Transfer history data appended for: https://www.transfermarkt.com/scott-carson/profil/spieler/14555.
Transfer history data appended for: https://www.transfermarkt.com/eric-garcia/profil/spieler/466794.
Transfer history data appended for: https://www.transfermarkt.com/nathan-ake/profil/spieler/177476.
Transfer history data appended for: https://www.transfermarkt.com/john-stones/profil/spieler/186590.
Transfer history data appended for: https://www.transfermarkt.com/fernandinho/profil/spieler/26267.
Transfer history data appended for: https://www.transfermarkt.com/ferran-torres/profil/spieler/398184.
Transfer history data appended for: https://www.transfermarkt.com/ruben-dias/profil/spieler/258004.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-jesus/profil/spieler/363205.
Transfer history data appended for: https://www.transfermarkt.com/philippe-sandler/profil/spieler/340460.
Transfer history data appended for: https://www.transfermarkt.com/zack-steffen/profil/spieler/221624.
Transfer history data appended for: https://www.transfermarkt.com/yan-valery/profil/spieler/406008.
Transfer history data appended for: https://www.transfermarkt.com/nathan-redmond/profil/spieler/129078.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-diallo/profil/spieler/413032.
Transfer history data appended for: https://www.transfermarkt.com/shane-long/profil/spieler/37304.
Transfer history data appended for: https://www.transfermarkt.com/sam-mcqueen/profil/spieler/226968.
Transfer history data appended for: https://www.transfermarkt.com/james-ward-prowse/profil/spieler/181579.
Transfer history data appended for: https://www.transfermarkt.com/nathan-tella/profil/spieler/340322.
Transfer history data appended for: https://www.transfermarkt.com/che-adams/profil/spieler/346779.
Transfer history data appended for: https://www.transfermarkt.com/stuart-armstrong/profil/spieler/130765.
Transfer history data appended for: https://www.transfermarkt.com/alex-mccarthy/profil/spieler/95976.
Transfer history data appended for: https://www.transfermarkt.com/danny-ings/profil/spieler/134294.
Transfer history data appended for: https://www.transfermarkt.com/moussa-djenepo/profil/spieler/485424.
Transfer history data appended for: https://www.transfermarkt.com/harry-lewis/profil/spieler/341043.
Transfer history data appended for: https://www.transfermarkt.com/jannik-vestergaard/profil/spieler/99331.
Transfer history data appended for: https://www.transfermarkt.com/theo-walcott/profil/spieler/33713.
Transfer history data appended for: https://www.transfermarkt.com/will-smallbone/profil/spieler/444211.
Transfer history data appended for: https://www.transfermarkt.com/ryan-bertrand/profil/spieler/40611.
Transfer history data appended for: https://www.transfermarkt.com/jake-vokins/profil/spieler/421424.
Transfer history data appended for: https://www.transfermarkt.com/kyle-walker-peters/profil/spieler/341051.
Transfer history data appended for: https://www.transfermarkt.com/michael-obafemi/profil/spieler/444208.
Transfer history data appended for: https://www.transfermarkt.com/jack-stephens/profil/spieler/163744.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-salisu/profil/spieler/563963.
Transfer history data appended for: https://www.transfermarkt.com/jarrod-bowen/profil/spieler/314875.
Transfer history data appended for: https://www.transfermarkt.com/ryan-fredericks/profil/spieler/140191.
Transfer history data appended for: https://www.transfermarkt.com/robert-snodgrass/profil/spieler/22614.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-coufal/profil/spieler/157672.
Transfer history data appended for: https://www.transfermarkt.com/issa-diop/profil/spieler/272622.
Transfer history data appended for: https://www.transfermarkt.com/said-benrahma/profil/spieler/290532.
Transfer history data appended for: https://www.transfermarkt.com/fabian-balbuena/profil/spieler/285548.
Transfer history data appended for: https://www.transfermarkt.com/david-martin/profil/spieler/15930.
Transfer history data appended for: https://www.transfermarkt.com/pablo-fornals/profil/spieler/357885.
Transfer history data appended for: https://www.transfermarkt.com/tomas-soucek/profil/spieler/283628.
Transfer history data appended for: https://www.transfermarkt.com/darren-randolph/profil/spieler/51321.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-fabianski/profil/spieler/29692.
Transfer history data appended for: https://www.transfermarkt.com/angelo-ogbonna/profil/spieler/48002.
Transfer history data appended for: https://www.transfermarkt.com/ben-johnson/profil/spieler/468002.
Transfer history data appended for: https://www.transfermarkt.com/arthur-masuaku/profil/spieler/181380.
Transfer history data appended for: https://www.transfermarkt.com/aaron-cresswell/profil/spieler/92571.
Transfer history data appended for: https://www.transfermarkt.com/mark-noble/profil/spieler/31835.
Transfer history data appended for: https://www.transfermarkt.com/michail-antonio/profil/spieler/104124.
Transfer history data appended for: https://www.transfermarkt.com/sebastien-haller/profil/spieler/181375.
Transfer history data appended for: https://www.transfermarkt.com/declan-rice/profil/spieler/357662.
Transfer history data appended for: https://www.transfermarkt.com/andriy-yarmolenko/profil/spieler/69015.
Transfer history data appended for: https://www.transfermarkt.com/craig-dawson/profil/spieler/121477.
Transfer history data appended for: https://www.transfermarkt.com/kevin-mcdonald/profil/spieler/36529.
Transfer history data appended for: https://www.transfermarkt.com/bobby-reid/profil/spieler/186186.
Transfer history data appended for: https://www.transfermarkt.com/tosin-adarabioyo/profil/spieler/258878.
Transfer history data appended for: https://www.transfermarkt.com/joe-bryan/profil/spieler/194460.
Transfer history data appended for: https://www.transfermarkt.com/stefan-johansen/profil/spieler/62008.
Transfer history data appended for: https://www.transfermarkt.com/josh-onomah/profil/spieler/243589.
Transfer history data appended for: https://www.transfermarkt.com/antonee-robinson/profil/spieler/349701.
Transfer history data appended for: https://www.transfermarkt.com/tim-ream/profil/spieler/145466.
Transfer history data appended for: https://www.transfermarkt.com/neeskens-kebano/profil/spieler/111422.
Transfer history data appended for: https://www.transfermarkt.com/ruben-loftus-cheek/profil/spieler/202886.
Transfer history data appended for: https://www.transfermarkt.com/andre-zambo-anguissa/profil/spieler/354361.
Transfer history data appended for: https://www.transfermarkt.com/ivan-cavaleiro/profil/spieler/149716.
Transfer history data appended for: https://www.transfermarkt.com/sylvester-jasper/profil/spieler/502074.
Transfer history data appended for: https://www.transfermarkt.com/terence-kongolo/profil/spieler/152651.
Transfer history data appended for: https://www.transfermarkt.com/aboubakar-kamara/profil/spieler/290951.
Transfer history data appended for: https://www.transfermarkt.com/jean-michael-seri/profil/spieler/178614.
Transfer history data appended for: https://www.transfermarkt.com/jay-stansfield/profil/spieler/696346.
Transfer history data appended for: https://www.transfermarkt.com/marek-rodak/profil/spieler/186901.
Transfer history data appended for: https://www.transfermarkt.com/joachim-andersen/profil/spieler/260827.
Transfer history data appended for: https://www.transfermarkt.com/george-wickens/profil/spieler/502070.
Transfer history data appended for: https://www.transfermarkt.com/michael-hector/profil/spieler/157490.
Transfer history data appended for: https://www.transfermarkt.com/alphonse-areola/profil/spieler/120629.
Transfer history data appended for: https://www.transfermarkt.com/maxime-le-marchand/profil/spieler/60558.

Transfer history data appended for: https://www.transfermarkt.com/denis-odoi/profil/spieler/59641.
Transfer history data appended for: https://www.transfermarkt.com/tom-cairney/profil/spieler/123275.
Transfer history data appended for: https://www.transfermarkt.com/fabri/profil/spieler/45882.
Transfer history data appended for: https://www.transfermarkt.com/harrison-reed/profil/spieler/226973.
Transfer history data appended for: https://www.transfermarkt.com/kenny-tete/profil/spieler/206746.
Transfer history data appended for: https://www.transfermarkt.com/adama-traore/profil/spieler/204103.
Transfer history data appended for: https://www.transfermarkt.com/max-kilman/profil/spieler/525247.
Transfer history data appended for: https://www.transfermarkt.com/ruben-neves/profil/spieler/225161.
Transfer history data appended for: https://www.transfermarkt.com/renat-dadashov/profil/spieler/335461.
Transfer history data appended for: https://www.transfermarkt.com/joao-moutinho/profil/spieler/29364.
Transfer history data appended for: https://www.transfermarkt.com/marcal/profil/spieler/137745.
Transfer history data appended for: https://www.transfermarkt.com/john-ruddy/profil/spieler/29712.
Transfer history data appended for: https://www.transfermarkt.com/vitinha/profil/spieler/487469.
Transfer history data appended for: https://www.transfermarkt.com/willy-boly/profil/spieler/142310.
Transfer history data appended for: https://www.transfermarkt.com/leander-dendoncker/profil/spieler/168157.
Transfer history data appended for: https://www.transfermarkt.com/rayan-ait-nouri/profil/spieler/578391.
Transfer history data appended for: https://www.transfermarkt.com/owen-otasowie/profil/spieler/511815.
Transfer history data appended for: https://www.transfermarkt.com/romain-saiss/profil/spieler/204198.
Transfer history data appended for: https://www.transfermarkt.com/oskar-buur/profil/spieler/293283.
Transfer history data appended for: https://www.transfermarkt.com/ki-jana-hoever/profil/spieler/485583.
Transfer history data appended for: https://www.transfermarkt.com/luke-matheson/profil/spieler/614084.
Transfer history data appended for: https://www.transfermarkt.com/jonny-otto/profil/spieler/175446.
Transfer history data appended for: https://www.transfermarkt.com/pedro-neto/profil/spieler/487465.
Transfer history data appended for: https://www.transfermarkt.com/daniel-podence/profil/spieler/256977.
Transfer history data appended for: https://www.transfermarkt.com/fabio-silva/profil/spieler/505653.
Transfer history data appended for: https://www.transfermarkt.com/nelson-semedo/profil/spieler/231572.
Transfer history data appended for: https://www.transfermarkt.com/rui-patricio/profil/spieler/45026.
Transfer history data appended for: https://www.transfermarkt.com/conor-coady/profil/spieler/128901.
Transfer history data appended for: https://www.transfermarkt.com/john-lundstram/profil/spieler/156941.
Transfer history data appended for: https://www.transfermarkt.com/wes-foderingham/profil/spieler/61697.
Transfer history data appended for: https://www.transfermarkt.com/john-egan/profil/spieler/121324.
Transfer history data appended for: https://www.transfermarkt.com/michael-verrips/profil/spieler/288259.
Transfer history data appended for: https://www.transfermarkt.com/jack-robinson/profil/spieler/128909.
Transfer history data appended for: https://www.transfermarkt.com/jack-oconnell/profil/spieler/212829.
Transfer history data appended for: https://www.transfermarkt.com/lys-mousset/profil/spieler/291422.
Transfer history data appended for: https://www.transfermarkt.com/billy-sharp/profil/spieler/49542.
Transfer history data appended for: https://www.transfermarkt.com/oliver-mcburnie/profil/spieler/298477.
Transfer history data appended for: https://www.transfermarkt.com/phil-jagielka/profil/spieler/13520.
Transfer history data appended for: https://www.transfermarkt.com/simon-moore/profil/spieler/123536.
Transfer history data appended for: https://www.transfermarkt.com/aaron-ramsdale/profil/spieler/427568.
Transfer history data appended for: https://www.transfermarkt.com/kean-bryan/profil/spieler/214928.
Transfer history data appended for: https://www.transfermarkt.com/kyron-gordon/profil/spieler/746734.
Transfer history data appended for: https://www.transfermarkt.com/sander-berge/profil/spieler/333014.
Transfer history data appended for: https://www.transfermarkt.com/oliver-burke/profil/spieler/341317.
Transfer history data appended for: https://www.transfermarkt.com/zak-brunt/profil/spieler/746777.
Transfer history data appended for: https://www.transfermarkt.com/oliver-norwood/profil/spieler/73547.
Transfer history data appended for: https://www.transfermarkt.com/ben-osborn/profil/spieler/218087.
Transfer history data appended for: https://www.transfermarkt.com/john-fleck/profil/spieler/54383.
Transfer history data appended for: https://www.transfermarkt.com/enda-stevens/profil/spieler/85706.
Transfer history data appended for: https://www.transfermarkt.com/rhian-brewster/profil/spieler/406560.
Transfer history data appended for: https://www.transfermarkt.com/george-baldock/profil/spieler/146690.
Transfer history data appended for: https://www.transfermarkt.com/jayden-bogle/profil/spieler/465717.
Transfer history data appended for: https://www.transfermarkt.com/david-mcgoldrick/profil/spieler/35416.
Transfer history data appended for: https://www.transfermarkt.com/chris-basham/profil/spieler/52495.
Transfer history data appended for: https://www.transfermarkt.com/jack-rodwell/profil/spieler/57079.
Transfer history data appended for: https://www.transfermarkt.com/max-lowe/profil/spieler/258885.
Transfer history data appended for: https://www.transfermarkt.com/grady-diangana/profil/spieler/342048.
Transfer history data appended for: https://www.transfermarkt.com/sam-field/profil/spieler/387331.
Transfer history data appended for: https://www.transfermarkt.com/hal-robson-kanu/profil/spieler/65976.
Transfer history data appended for: https://www.transfermarkt.com/dara-oshea/profil/spieler/401320.
Transfer history data appended for: https://www.transfermarkt.com/rekeem-harper/profil/spieler/456877.
Transfer history data appended for: https://www.transfermarkt.com/kyle-bartley/profil/spieler/67421.
Transfer history data appended for: https://www.transfermarkt.com/branislav-ivanovic/profil/spieler/36827.
Transfer history data appended for: https://www.transfermarkt.com/cedric-kipre/profil/spieler/364827.
Transfer history data appended for: https://www.transfermarkt.com/karlan-grant/profil/spieler/314183.
Transfer history data appended for: https://www.transfermarkt.com/charlie-austin/profil/spieler/129627.
Transfer history data appended for: https://www.transfermarkt.com/callum-robinson/profil/spieler/183299.
Transfer history data appended for: https://www.transfermarkt.com/semi-ajayi/profil/spieler/251912.
Transfer history data appended for: https://www.transfermarkt.com/romaine-sawyers/profil/spieler/113036.
Transfer history data appended for: https://www.transfermarkt.com/filip-krovinovic/profil/spieler/261988.
Transfer history data appended for: https://www.transfermarkt.com/david-button/profil/spieler/61814.
Transfer history data appended for: https://www.transfermarkt.com/darnell-furlong/profil/spieler/351755.
Transfer history data appended for: https://www.transfermarkt.com/matt-phillips/profil/spieler/77274.
Transfer history data appended for: https://www.transfermarkt.com/lee-peltier/profil/spieler/38094.
Transfer history data appended for: https://www.transfermarkt.com/kieran-gibbs/profil/spieler/44792.
Transfer history data appended for: https://www.transfermarkt.com/sam-johnstone/profil/spieler/110864.
Transfer history data appended for: https://www.transfermarkt.com/kyle-edwards/profil/spieler/314366.
Transfer history data appended for: https://www.transfermarkt.com/conor-gallagher/profil/spieler/488362.
Transfer history data appended for: https://www.transfermarkt.com/conor-townsend/profil/spieler/146509.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-bond/profil/spieler/130768.
Transfer history data appended for: https://www.transfermarkt.com/cengiz-under/profil/spieler/341647.

Transfer history data appended for: https://www.transfermarkt.com/james-justin/profil/spieler/413220.
Transfer history data appended for: https://www.transfermarkt.com/daniel-amartey/profil/spieler/214056.
Transfer history data appended for: https://www.transfermarkt.com/dennis-praet/profil/spieler/129588.
Transfer history data appended for: https://www.transfermarkt.com/wesley-fofana/profil/spieler/475411.
Transfer history data appended for: https://www.transfermarkt.com/timothy-castagne/profil/spieler/262226.
Transfer history data appended for: https://www.transfermarkt.com/nampalys-mendy/profil/spieler/111051.
Transfer history data appended for: https://www.transfermarkt.com/kelechi-iheanacho/profil/spieler/295330.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-pereira/profil/spieler/215876.
Transfer history data appended for: https://www.transfermarkt.com/youri-tielemans/profil/spieler/249565.
Transfer history data appended for: https://www.transfermarkt.com/ayoze-perez/profil/spieler/246968.
Transfer history data appended for: https://www.transfermarkt.com/james-maddison/profil/spieler/294057.
Transfer history data appended for: https://www.transfermarkt.com/luke-thomas/profil/spieler/505194.
Transfer history data appended for: https://www.transfermarkt.com/eldin-jakupovic/profil/spieler/2857.
Transfer history data appended for: https://www.transfermarkt.com/wilfred-ndidi/profil/spieler/274839.
Transfer history data appended for: https://www.transfermarkt.com/hamza-choudhury/profil/spieler/341501.
Transfer history data appended for: https://www.transfermarkt.com/marc-albrighton/profil/spieler/61560.
Transfer history data appended for: https://www.transfermarkt.com/harvey-barnes/profil/spieler/398065.
Transfer history data appended for: https://www.transfermarkt.com/jonny-evans/profil/spieler/42412.
Transfer history data appended for: https://www.transfermarkt.com/islam-slimani/profil/spieler/174915.
Transfer history data appended for: https://www.transfermarkt.com/jamie-vardy/profil/spieler/197838.
Transfer history data appended for: https://www.transfermarkt.com/caglar-soyuncu/profil/spieler/320141.
Transfer history data appended for: https://www.transfermarkt.com/demarai-gray/profil/spieler/292417.
Transfer history data appended for: https://www.transfermarkt.com/danny-ward/profil/spieler/203026.
Transfer history data appended for: https://www.transfermarkt.com/wes-morgan/profil/spieler/10003.
Transfer history data appended for: https://www.transfermarkt.com/kasper-schmeichel/profil/spieler/16911.
Transfer history data appended for: https://www.transfermarkt.com/toby-alderweireld/profil/spieler/42710.
Transfer history data appended for: https://www.transfermarkt.com/dele-alli/profil/spieler/207929.
Transfer history data appended for: https://www.transfermarkt.com/harry-kane/profil/spieler/132098.
Transfer history data appended for: https://www.transfermarkt.com/paulo-gazzaniga/profil/spieler/195488.
Transfer history data appended for: https://www.transfermarkt.com/joe-hart/profil/spieler/40204.
Transfer history data appended for: https://www.transfermarkt.com/erik-lamela/profil/spieler/111630.
Transfer history data appended for: https://www.transfermarkt.com/eric-dier/profil/spieler/175722.
Transfer history data appended for: https://www.transfermarkt.com/sergio-reguilon/profil/spieler/282429.
Transfer history data appended for: https://www.transfermarkt.com/pierre-emile-hojbjerg/profil/spieler/167799.
Transfer history data appended for: https://www.transfermarkt.com/giovani-lo-celso/profil/spieler/348795.
Transfer history data appended for: https://www.transfermarkt.com/alfie-whiteman/profil/spieler/282823.
Transfer history data appended for: https://www.transfermarkt.com/tanguy-ndombele/profil/spieler/450936.
Transfer history data appended for: https://www.transfermarkt.com/danny-rose/profil/spieler/50174.
Transfer history data appended for: https://www.transfermarkt.com/joe-rodon/profil/spieler/297212.
Transfer history data appended for: https://www.transfermarkt.com/serge-aurier/profil/spieler/127032.
Transfer history data appended for: https://www.transfermarkt.com/heung-min-son/profil/spieler/91845.
Transfer history data appended for: https://www.transfermarkt.com/hugo-lloris/profil/spieler/17965.
Transfer history data appended for: https://www.transfermarkt.com/jack-clarke/profil/spieler/559794.
Transfer history data appended for: https://www.transfermarkt.com/gareth-bale/profil/spieler/39381.
Transfer history data appended for: https://www.transfermarkt.com/japhet-tanganga/profil/spieler/346478.
Transfer history data appended for: https://www.transfermarkt.com/lucas-moura/profil/spieler/77100.
Transfer history data appended for: https://www.transfermarkt.com/carlos-vinicius/profil/spieler/525287.
Transfer history data appended for: https://www.transfermarkt.com/harry-winks/profil/spieler/249126.
Transfer history data appended for: https://www.transfermarkt.com/matt-doherty/profil/spieler/171679.
Transfer history data appended for: https://www.transfermarkt.com/ben-davies/profil/spieler/192765.
Transfer history data appended for: https://www.transfermarkt.com/steven-bergwijn/profil/spieler/284165.
Transfer history data appended for: https://www.transfermarkt.com/gedson-fernandes/profil/spieler/337800.
Transfer history data appended for: https://www.transfermarkt.com/moussa-sissoko/profil/spieler/46001.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-elneny/profil/spieler/160438.
Transfer history data appended for: https://www.transfermarkt.com/runar-alex-runarsson/profil/spieler/205657.
Transfer history data appended for: https://www.transfermarkt.com/matt-macey/profil/spieler/220491.
Transfer history data appended for: https://www.transfermarkt.com/sead-kolasinac/profil/spieler/94005.
Transfer history data appended for: https://www.transfermarkt.com/rob-holding/profil/spieler/253341.
Transfer history data appended for: https://www.transfermarkt.com/willian/profil/spieler/52769.
Transfer history data appended for: https://www.transfermarkt.com/pierre-emerick-aubameyang/profil/spieler/58864.
Transfer history data appended for: https://www.transfermarkt.com/thomas-partey/profil/spieler/230784.
Transfer history data appended for: https://www.transfermarkt.com/kieran-tierney/profil/spieler/300716.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-lacazette/profil/spieler/93720.
Transfer history data appended for: https://www.transfermarkt.com/eddie-nketiah/profil/spieler/340324.
Transfer history data appended for: https://www.transfermarkt.com/gabriel/profil/spieler/435338.
Transfer history data appended for: https://www.transfermarkt.com/pablo-mari/profil/spieler/210178.
Transfer history data appended for: https://www.transfermarkt.com/emile-smith-rowe/profil/spieler/392765.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-pepe/profil/spieler/343052.
Transfer history data appended for: https://www.transfermarkt.com/bukayo-saka/profil/spieler/433177.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-martinelli/profil/spieler/655488.
Transfer history data appended for: https://www.transfermarkt.com/david-luiz/profil/spieler/46741.
Transfer history data appended for: https://www.transfermarkt.com/mesut-ozil/profil/spieler/35664.
Transfer history data appended for: https://www.transfermarkt.com/william-saliba/profil/spieler/495666.
Transfer history data appended for: https://www.transfermarkt.com/hector-bellerin/profil/spieler/191217.
Transfer history data appended for: https://www.transfermarkt.com/shkodran-mustafi/profil/spieler/88590.
Transfer history data appended for: https://www.transfermarkt.com/calum-chambers/profil/spieler/215118.
Transfer history data appended for: https://www.transfermarkt.com/granit-xhaka/profil/spieler/111455.
Transfer history data appended for: https://www.transfermarkt.com/joe-willock/profil/spieler/340329.
Transfer history data appended for: https://www.transfermarkt.com/dani-ceballos/profil/spieler/319745.
Transfer history data appended for: https://www.transfermarkt.com/ainsley-maitland-niles/profil/spieler/285845.

Transfer history data appended for: https://www.transfermarkt.com/pascal-gross/profil/spieler/82873.
Transfer history data appended for: https://www.transfermarkt.com/aaron-connolly/profil/spieler/434207.
Transfer history data appended for: https://www.transfermarkt.com/alireza-jahanbakhsh/profil/spieler/213268.
Transfer history data appended for: https://www.transfermarkt.com/jason-steele/profil/spieler/73564.
Transfer history data appended for: https://www.transfermarkt.com/leandro-trossard/profil/spieler/144028.
Transfer history data appended for: https://www.transfermarkt.com/bernardo/profil/spieler/364258.
Transfer history data appended for: https://www.transfermarkt.com/tariq-lamptey/profil/spieler/504148.
Transfer history data appended for: https://www.transfermarkt.com/yves-bissouma/profil/spieler/410425.
Transfer history data appended for: https://www.transfermarkt.com/steven-alzate/profil/spieler/476237.
Transfer history data appended for: https://www.transfermarkt.com/danny-welbeck/profil/spieler/67063.
Transfer history data appended for: https://www.transfermarkt.com/jose-izquierdo/profil/spieler/147094.
Transfer history data appended for: https://www.transfermarkt.com/ben-white/profil/spieler/335721.
Transfer history data appended for: https://www.transfermarkt.com/solly-march/profil/spieler/209212.
Transfer history data appended for: https://www.transfermarkt.com/joel-veltman/profil/spieler/111195.
Transfer history data appended for: https://www.transfermarkt.com/adam-webster/profil/spieler/212847.
Transfer history data appended for: https://www.transfermarkt.com/alexis-mac-allister/profil/spieler/534033.
Transfer history data appended for: https://www.transfermarkt.com/dan-burn/profil/spieler/134270.
Transfer history data appended for: https://www.transfermarkt.com/mathew-ryan/profil/spieler/128969.
Transfer history data appended for: https://www.transfermarkt.com/robert-sanchez/profil/spieler/403151.
Transfer history data appended for: https://www.transfermarkt.com/neal-maupay/profil/spieler/217115.
Transfer history data appended for: https://www.transfermarkt.com/davy-propper/profil/spieler/79027.
Transfer history data appended for: https://www.transfermarkt.com/andi-zeqiri/profil/spieler/345468.
Transfer history data appended for: https://www.transfermarkt.com/max-sanders/profil/spieler/411495.
Transfer history data appended for: https://www.transfermarkt.com/christian-walton/profil/spieler/208379.
Transfer history data appended for: https://www.transfermarkt.com/adam-lallana/profil/spieler/43530.
Transfer history data appended for: https://www.transfermarkt.com/lewis-dunk/profil/spieler/148153.
Transfer history data appended for: https://www.transfermarkt.com/jayson-molumby/profil/spieler/357656.
Transfer history data appended for: https://www.transfermarkt.com/will-dennis/profil/spieler/582078.
Transfer history data appended for: https://www.transfermarkt.com/chris-mepham/profil/spieler/480987.
Transfer history data appended for: https://www.transfermarkt.com/david-brooks/profil/spieler/277033.
Transfer history data appended for: https://www.transfermarkt.com/dan-gosling/profil/spieler/44983.
Transfer history data appended for: https://www.transfermarkt.com/asmir-begovic/profil/spieler/33873.
Transfer history data appended for: https://www.transfermarkt.com/lloyd-kelly/profil/spieler/480116.
Transfer history data appended for: https://www.transfermarkt.com/arnaut-danjuma/profil/spieler/355861.
Transfer history data appended for: https://www.transfermarkt.com/nnamdi-ofoborh/profil/spieler/611906.
Transfer history data appended for: https://www.transfermarkt.com/adam-smith/profil/spieler/61841.
Transfer history data appended for: https://www.transfermarkt.com/mark-travers/profil/spieler/357658.
Transfer history data appended for: https://www.transfermarkt.com/lewis-cook/profil/spieler/249089.
Transfer history data appended for: https://www.transfermarkt.com/philip-billing/profil/spieler/320411.
Transfer history data appended for: https://www.transfermarkt.com/jack-stacey/profil/spieler/249356.
Transfer history data appended for: https://www.transfermarkt.com/steve-cook/profil/spieler/90836.
Transfer history data appended for: https://www.transfermarkt.com/jack-simpson/profil/spieler/419930.
Transfer history data appended for: https://www.transfermarkt.com/junior-stanislas/profil/spieler/87672.
Transfer history data appended for: https://www.transfermarkt.com/cameron-carter-vickers/profil/spieler/341049.
Transfer history data appended for: https://www.transfermarkt.com/sam-surridge/profil/spieler/398402.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-riquelme/profil/spieler/461617.
Transfer history data appended for: https://www.transfermarkt.com/jaidon-anthony/profil/spieler/684210.
Transfer history data appended for: https://www.transfermarkt.com/diego-rico/profil/spieler/249513.
Transfer history data appended for: https://www.transfermarkt.com/gavin-kilkenny/profil/spieler/469064.
Transfer history data appended for: https://www.transfermarkt.com/jordan-zemura/profil/spieler/633530.
Transfer history data appended for: https://www.transfermarkt.com/dominic-solanke/profil/spieler/258889.
Transfer history data appended for: https://www.transfermarkt.com/isaac-mbenza/profil/spieler/260806.
Transfer history data appended for: https://www.transfermarkt.com/harry-toffolo/profil/spieler/198516.
Transfer history data appended for: https://www.transfermarkt.com/alex-pritchard/profil/spieler/200777.
Transfer history data appended for: https://www.transfermarkt.com/jaden-brown/profil/spieler/346469.
Transfer history data appended for: https://www.transfermarkt.com/naby-sarr/profil/spieler/203532.
Transfer history data appended for: https://www.transfermarkt.com/josh-koroma/profil/spieler/429578.
Transfer history data appended for: https://www.transfermarkt.com/fraizer-campbell/profil/spieler/42411.
Transfer history data appended for: https://www.transfermarkt.com/pipa/profil/spieler/423166.
Transfer history data appended for: https://www.transfermarkt.com/demeaco-duhaney/profil/spieler/380913.
Transfer history data appended for: https://www.transfermarkt.com/tommy-elphick/profil/spieler/37152.
Transfer history data appended for: https://www.transfermarkt.com/joel-pereira/profil/spieler/192611.
Transfer history data appended for: https://www.transfermarkt.com/danny-ward/profil/spieler/124172.
Transfer history data appended for: https://www.transfermarkt.com/carel-eiting/profil/spieler/315128.
Transfer history data appended for: https://www.transfermarkt.com/christopher-schindler/profil/spieler/57842.
Transfer history data appended for: https://www.transfermarkt.com/ryan-schofield/profil/spieler/495441.
Transfer history data appended for: https://www.transfermarkt.com/romoney-crichlow/profil/spieler/689891.
Transfer history data appended for: https://www.transfermarkt.com/rarmani-edmonds-green/profil/spieler/689893.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-hogg/profil/spieler/61573.
Transfer history data appended for: https://www.transfermarkt.com/matty-daly/profil/spieler/566349.
Transfer history data appended for: https://www.transfermarkt.com/richard-stearman/profil/spieler/34349.
Transfer history data appended for: https://www.transfermarkt.com/juninho-bacuna/profil/spieler/348863.
Transfer history data appended for: https://www.transfermarkt.com/lewis-obrien/profil/spieler/560694.
Transfer history data appended for: https://www.transfermarkt.com/ben-hamer/profil/spieler/67283.
Transfer history data appended for: https://www.transfermarkt.com/alex-vallejo/profil/spieler/138934.
Transfer history data appended for: https://www.transfermarkt.com/adama-diakhaby/profil/spieler/453594.
Transfer history data appended for: https://www.transfermarkt.com/felipe-araruna/profil/spieler/435484.
Transfer history data appended for: https://www.transfermarkt.com/ovie-ejaria/profil/spieler/337284.
Transfer history data appended for: https://www.transfermarkt.com/john-swift/profil/spieler/197693.
Transfer history data appended for: https://www.transfermarkt.com/liam-moore/profil/spieler/128906.

Transfer history data appended for: https://www.transfermarkt.com/omar-richards/profil/spieler/424881.
Transfer history data appended for: https://www.transfermarkt.com/lucas-joao/profil/spieler/234787.
Transfer history data appended for: https://www.transfermarkt.com/andy-yiadom/profil/spieler/188256.
Transfer history data appended for: https://www.transfermarkt.com/rafael/profil/spieler/103916.
Transfer history data appended for: https://www.transfermarkt.com/josh-laurent/profil/spieler/314241.
Transfer history data appended for: https://www.transfermarkt.com/andy-rinomhota/profil/spieler/368862.
Transfer history data appended for: https://www.transfermarkt.com/lewis-gibson/profil/spieler/419325.
Transfer history data appended for: https://www.transfermarkt.com/sam-walker/profil/spieler/129558.
Transfer history data appended for: https://www.transfermarkt.com/michael-morrison/profil/spieler/66497.
Transfer history data appended for: https://www.transfermarkt.com/luke-southwood/profil/spieler/398063.
Transfer history data appended for: https://www.transfermarkt.com/sone-aluko/profil/spieler/42198.
Transfer history data appended for: https://www.transfermarkt.com/yakou-meite/profil/spieler/289433.
Transfer history data appended for: https://www.transfermarkt.com/sam-baldock/profil/spieler/67211.
Transfer history data appended for: https://www.transfermarkt.com/michael-olise/profil/spieler/566723.
Transfer history data appended for: https://www.transfermarkt.com/thomas-holmes/profil/spieler/424900.
Transfer history data appended for: https://www.transfermarkt.com/tomas-esteves/profil/spieler/504085.
Transfer history data appended for: https://www.transfermarkt.com/tom-mcintyre/profil/spieler/339235.
Transfer history data appended for: https://www.transfermarkt.com/dejan-tetek/profil/spieler/570312.
Transfer history data appended for: https://www.transfermarkt.com/saman-ghoddos/profil/spieler/204294.
Transfer history data appended for: https://www.transfermarkt.com/luke-daniels/profil/spieler/45921.
Transfer history data appended for: https://www.transfermarkt.com/henrik-dalsgaard/profil/spieler/93315.
Transfer history data appended for: https://www.transfermarkt.com/tariqe-fosu/profil/spieler/249873.
Transfer history data appended for: https://www.transfermarkt.com/sergi-canos/profil/spieler/251845.
Transfer history data appended for: https://www.transfermarkt.com/marcus-forss/profil/spieler/404584.
Transfer history data appended for: https://www.transfermarkt.com/charlie-goode/profil/spieler/376856.
Transfer history data appended for: https://www.transfermarkt.com/ivan-toney/profil/spieler/251664.
Transfer history data appended for: https://www.transfermarkt.com/vitaly-janelt/profil/spieler/270171.
Transfer history data appended for: https://www.transfermarkt.com/shandon-baptiste/profil/spieler/533916.
Transfer history data appended for: https://www.transfermarkt.com/mads-bech-sorensen/profil/spieler/372240.
Transfer history data appended for: https://www.transfermarkt.com/ellery-balcombe/profil/spieler/456292.
Transfer history data appended for: https://www.transfermarkt.com/josh-dasilva/profil/spieler/340321.
Transfer history data appended for: https://www.transfermarkt.com/pontus-jansson/profil/spieler/125314.
Transfer history data appended for: https://www.transfermarkt.com/christian-norgaard/profil/spieler/148367.
Transfer history data appended for: https://www.transfermarkt.com/bryan-mbeumo/profil/spieler/413039.
Transfer history data appended for: https://www.transfermarkt.com/mads-roerslev-rasmussen/profil/spieler/391005.
Transfer history data appended for: https://www.transfermarkt.com/mathias-jensen/profil/spieler/319859.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-marcondes/profil/spieler/232964.
Transfer history data appended for: https://www.transfermarkt.com/rico-henry/profil/spieler/339556.
Transfer history data appended for: https://www.transfermarkt.com/david-raya/profil/spieler/262749.
Transfer history data appended for: https://www.transfermarkt.com/ethan-pinnock/profil/spieler/442248.
Transfer history data appended for: https://www.transfermarkt.com/dominic-thompson/profil/spieler/503688.
Transfer history data appended for: https://www.transfermarkt.com/david-marshall/profil/spieler/9500.
Transfer history data appended for: https://www.transfermarkt.com/jason-knight/profil/spieler/530780.
Transfer history data appended for: https://www.transfermarkt.com/matt-clarke/profil/spieler/307497.
Transfer history data appended for: https://www.transfermarkt.com/krystian-bielik/profil/spieler/287247.
Transfer history data appended for: https://www.transfermarkt.com/max-bird/profil/spieler/486464.
Transfer history data appended for: https://www.transfermarkt.com/kamil-jozwiak/profil/spieler/289167.
Transfer history data appended for: https://www.transfermarkt.com/wayne-rooney/profil/spieler/3332.
Transfer history data appended for: https://www.transfermarkt.com/martyn-waghorn/profil/spieler/61674.
Transfer history data appended for: https://www.transfermarkt.com/curtis-davies/profil/spieler/18227.
Transfer history data appended for: https://www.transfermarkt.com/nathan-byrne/profil/spieler/121276.
Transfer history data appended for: https://www.transfermarkt.com/mike-te-wierik/profil/spieler/155806.
Transfer history data appended for: https://www.transfermarkt.com/george-evans/profil/spieler/181498.
Transfer history data appended for: https://www.transfermarkt.com/andre-wisdom/profil/spieler/128912.
Transfer history data appended for: https://www.transfermarkt.com/morgan-whittaker/profil/spieler/502075.
Transfer history data appended for: https://www.transfermarkt.com/jordon-ibe/profil/spieler/195652.
Transfer history data appended for: https://www.transfermarkt.com/duane-holmes/profil/spieler/257095.
Transfer history data appended for: https://www.transfermarkt.com/kelle-roos/profil/spieler/123503.
Transfer history data appended for: https://www.transfermarkt.com/graeme-shinnie/profil/spieler/95950.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-idem/profil/spieler/412659.
Transfer history data appended for: https://www.transfermarkt.com/louie-sibley/profil/spieler/537270.
Transfer history data appended for: https://www.transfermarkt.com/lee-buchanan/profil/spieler/532539.
Transfer history data appended for: https://www.transfermarkt.com/tom-lawrence/profil/spieler/229970.
Transfer history data appended for: https://www.transfermarkt.com/craig-forsyth/profil/spieler/45492.
Transfer history data appended for: https://www.transfermarkt.com/james-shea/profil/spieler/91340.
Transfer history data appended for: https://www.transfermarkt.com/harry-isted/profil/spieler/284718.
Transfer history data appended for: https://www.transfermarkt.com/tom-lockyer/profil/spieler/207742.
Transfer history data appended for: https://www.transfermarkt.com/george-moncur/profil/spieler/121238.
Transfer history data appended for: https://www.transfermarkt.com/glen-rea/profil/spieler/337640.
Transfer history data appended for: https://www.transfermarkt.com/kiernan-dewsbury-hall/profil/spieler/475188.
Transfer history data appended for: https://www.transfermarkt.com/kazenga-lualua/profil/spieler/52576.
Transfer history data appended for: https://www.transfermarkt.com/elliot-lee/profil/spieler/229826.
Transfer history data appended for: https://www.transfermarkt.com/tq-addy/profil/spieler/703468.
Transfer history data appended for: https://www.transfermarkt.com/jack-chambers/profil/spieler/372772.
Transfer history data appended for: https://www.transfermarkt.com/james-collins/profil/spieler/62640.
Transfer history data appended for: https://www.transfermarkt.com/pelly-ruddock-mpanzu/profil/spieler/244338.
Transfer history data appended for: https://www.transfermarkt.com/eunan-okane/profil/spieler/61583.
Transfer history data appended for: https://www.transfermarkt.com/rhys-norrington-davies/profil/spieler/543164.
Transfer history data appended for: https://www.transfermarkt.com/jordan-clark/profil/spieler/184129.
Transfer history data appended for: https://www.transfermarkt.com/danny-hylton/profil/spieler/92809.

Transfer history data appended for: https://www.transfermarkt.com/ryan-tunnicliffe/profil/spieler/110868.
Transfer history data appended for: https://www.transfermarkt.com/joe-morrell/profil/spieler/293507.
Transfer history data appended for: https://www.transfermarkt.com/sam-nombe/profil/spieler/452380.
Transfer history data appended for: https://www.transfermarkt.com/harry-cornick/profil/spieler/255703.
Transfer history data appended for: https://www.transfermarkt.com/dan-potts/profil/spieler/207037.
Transfer history data appended for: https://www.transfermarkt.com/matty-pearson/profil/spieler/121395.
Transfer history data appended for: https://www.transfermarkt.com/josh-neufville/profil/spieler/543093.
Transfer history data appended for: https://www.transfermarkt.com/dion-pereira/profil/spieler/499604.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-osho/profil/spieler/364409.
Transfer history data appended for: https://www.transfermarkt.com/brendan-galloway/profil/spieler/208244.
Transfer history data appended for: https://www.transfermarkt.com/luke-berry/profil/spieler/125685.
Transfer history data appended for: https://www.transfermarkt.com/martin-cranie/profil/spieler/27659.
Transfer history data appended for: https://www.transfermarkt.com/sonny-bradley/profil/spieler/127794.
Transfer history data appended for: https://www.transfermarkt.com/james-bree/profil/spieler/324223.
Transfer history data appended for: https://www.transfermarkt.com/corey-panter/profil/spieler/666136.
Transfer history data appended for: https://www.transfermarkt.com/tiernan-parker/profil/spieler/471367.
Transfer history data appended for: https://www.transfermarkt.com/jake-peck/profil/spieler/531864.
Transfer history data appended for: https://www.transfermarkt.com/billy-mitchell/profil/spieler/671821.
Transfer history data appended for: https://www.transfermarkt.com/troy-parrott/profil/spieler/552655.
Transfer history data appended for: https://www.transfermarkt.com/murray-wallace/profil/spieler/174099.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-bialkowski/profil/spieler/24496.
Transfer history data appended for: https://www.transfermarkt.com/frank-fielding/profil/spieler/57070.
Transfer history data appended for: https://www.transfermarkt.com/jed-wallace/profil/spieler/198358.
Transfer history data appended for: https://www.transfermarkt.com/mason-bennett/profil/spieler/195637.
Transfer history data appended for: https://www.transfermarkt.com/shaun-hutchinson/profil/spieler/61417.
Transfer history data appended for: https://www.transfermarkt.com/jake-cooper/profil/spieler/243603.
Transfer history data appended for: https://www.transfermarkt.com/ryan-leonard/profil/spieler/145843.
Transfer history data appended for: https://www.transfermarkt.com/ryan-woods/profil/spieler/232897.
Transfer history data appended for: https://www.transfermarkt.com/jiri-skalak/profil/spieler/148734.
Transfer history data appended for: https://www.transfermarkt.com/scott-malone/profil/spieler/101682.
Transfer history data appended for: https://www.transfermarkt.com/kenneth-zohore/profil/spieler/135213.
Transfer history data appended for: https://www.transfermarkt.com/alex-pearce/profil/spieler/47768.
Transfer history data appended for: https://www.transfermarkt.com/mahlon-romeo/profil/spieler/268117.
Transfer history data appended for: https://www.transfermarkt.com/james-brown/profil/spieler/467540.
Transfer history data appended for: https://www.transfermarkt.com/matt-smith/profil/spieler/69786.
Transfer history data appended for: https://www.transfermarkt.com/shaun-williams/profil/spieler/57478.
Transfer history data appended for: https://www.transfermarkt.com/ben-thompson/profil/spieler/337062.
Transfer history data appended for: https://www.transfermarkt.com/connor-mahoney/profil/spieler/287528.
Transfer history data appended for: https://www.transfermarkt.com/shane-ferguson/profil/spieler/62052.
Transfer history data appended for: https://www.transfermarkt.com/tom-bradshaw/profil/spieler/139781.
Transfer history data appended for: https://www.transfermarkt.com/jon-dadi-bodvarsson/profil/spieler/114090.
Transfer history data appended for: https://www.transfermarkt.com/junior-hoilett/profil/spieler/58993.
Transfer history data appended for: https://www.transfermarkt.com/greg-cunningham/profil/spieler/114093.
Transfer history data appended for: https://www.transfermarkt.com/joe-day/profil/spieler/104564.
Transfer history data appended for: https://www.transfermarkt.com/kieffer-moore/profil/spieler/275590.
Transfer history data appended for: https://www.transfermarkt.com/jordi-osei-tutu/profil/spieler/397099.
Transfer history data appended for: https://www.transfermarkt.com/lee-tomlin/profil/spieler/104586.
Transfer history data appended for: https://www.transfermarkt.com/isaac-vassell/profil/spieler/195481.
Transfer history data appended for: https://www.transfermarkt.com/joe-ralls/profil/spieler/195680.
Transfer history data appended for: https://www.transfermarkt.com/sol-bamba/profil/spieler/28984.
Transfer history data appended for: https://www.transfermarkt.com/josh-murphy/profil/spieler/199528.
Transfer history data appended for: https://www.transfermarkt.com/marlon-pack/profil/spieler/118779.
Transfer history data appended for: https://www.transfermarkt.com/filip-benkovic/profil/spieler/293168.
Transfer history data appended for: https://www.transfermarkt.com/leandro-bacuna/profil/spieler/126014.
Transfer history data appended for: https://www.transfermarkt.com/robert-glatzel/profil/spieler/196139.
Transfer history data appended for: https://www.transfermarkt.com/gavin-whyte/profil/spieler/325588.
Transfer history data appended for: https://www.transfermarkt.com/dillon-phillips/profil/spieler/308431.
Transfer history data appended for: https://www.transfermarkt.com/alex-smithies/profil/spieler/33754.
Transfer history data appended for: https://www.transfermarkt.com/harry-wilson/profil/spieler/279455.
Transfer history data appended for: https://www.transfermarkt.com/sean-morrison/profil/spieler/79723.
Transfer history data appended for: https://www.transfermarkt.com/sheyi-ojo/profil/spieler/236510.
Transfer history data appended for: https://www.transfermarkt.com/joe-bennett/profil/spieler/90964.
Transfer history data appended for: https://www.transfermarkt.com/curtis-nelson/profil/spieler/148299.
Transfer history data appended for: https://www.transfermarkt.com/will-vaulks/profil/spieler/238427.
Transfer history data appended for: https://www.transfermarkt.com/aapo-halme/profil/spieler/322984.
Transfer history data appended for: https://www.transfermarkt.com/elliot-simoes/profil/spieler/646900.
Transfer history data appended for: https://www.transfermarkt.com/george-miller/profil/spieler/414892.
Transfer history data appended for: https://www.transfermarkt.com/jordan-williams/profil/spieler/346468.
Transfer history data appended for: https://www.transfermarkt.com/herbie-kane/profil/spieler/314253.
Transfer history data appended for: https://www.transfermarkt.com/conor-chaplin/profil/spieler/349503.
Transfer history data appended for: https://www.transfermarkt.com/matty-james/profil/spieler/73522.
Transfer history data appended for: https://www.transfermarkt.com/mads-juel-andersen/profil/spieler/407021.
Transfer history data appended for: https://www.transfermarkt.com/patrick-schmidt/profil/spieler/297590.
Transfer history data appended for: https://www.transfermarkt.com/clarke-oduor/profil/spieler/529747.
Transfer history data appended for: https://www.transfermarkt.com/mike-bahre/profil/spieler/193006.
Transfer history data appended for: https://www.transfermarkt.com/alex-mowatt/profil/spieler/283514.
Transfer history data appended for: https://www.transfermarkt.com/michael-sollbauer/profil/spieler/74179.
Transfer history data appended for: https://www.transfermarkt.com/dominik-frieser/profil/spieler/273553.
Transfer history data appended for: https://www.transfermarkt.com/isaac-christie-davies/profil/spieler/264660.
Transfer history data appended for: https://www.transfermarkt.com/ben-williams/profil/spieler/427873.

Transfer history data appended for: https://www.transfermarkt.com/jack-walton/profil/spieler/368629.
Transfer history data appended for: https://www.transfermarkt.com/victor-adeboyejo/profil/spieler/344987.
Transfer history data appended for: https://www.transfermarkt.com/callum-styles/profil/spieler/435062.
Transfer history data appended for: https://www.transfermarkt.com/michal-helik/profil/spieler/255383.
Transfer history data appended for: https://www.transfermarkt.com/callum-brittain/profil/spieler/416368.
Transfer history data appended for: https://www.transfermarkt.com/jordan-green/profil/spieler/416622.
Transfer history data appended for: https://www.transfermarkt.com/cauley-woodrow/profil/spieler/169801.
Transfer history data appended for: https://www.transfermarkt.com/brad-collins/profil/spieler/258914.
Transfer history data appended for: https://www.transfermarkt.com/romal-palmer/profil/spieler/737861.
Transfer history data appended for: https://www.transfermarkt.com/luke-thomas/profil/spieler/399473.
Transfer history data appended for: https://www.transfermarkt.com/filip-stuparevic/profil/spieler/442337.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-ngakia/profil/spieler/503795.
Transfer history data appended for: https://www.transfermarkt.com/ismaila-sarr/profil/spieler/410225.
Transfer history data appended for: https://www.transfermarkt.com/james-garner/profil/spieler/505219.
Transfer history data appended for: https://www.transfermarkt.com/craig-cathcart/profil/spieler/59606.
Transfer history data appended for: https://www.transfermarkt.com/stipe-perica/profil/spieler/245072.
Transfer history data appended for: https://www.transfermarkt.com/ken-sema/profil/spieler/252345.
Transfer history data appended for: https://www.transfermarkt.com/troy-deeney/profil/spieler/65477.
Transfer history data appended for: https://www.transfermarkt.com/ben-foster/profil/spieler/13572.
Transfer history data appended for: https://www.transfermarkt.com/joao-pedro/profil/spieler/626724.
Transfer history data appended for: https://www.transfermarkt.com/andre-gray/profil/spieler/120565.
Transfer history data appended for: https://www.transfermarkt.com/tom-cleverley/profil/spieler/73484.
Transfer history data appended for: https://www.transfermarkt.com/kiko-femenia/profil/spieler/76467.
Transfer history data appended for: https://www.transfermarkt.com/etienne-capoue/profil/spieler/63494.
Transfer history data appended for: https://www.transfermarkt.com/william-troost-ekong/profil/spieler/192875.
Transfer history data appended for: https://www.transfermarkt.com/daniel-bachmann/profil/spieler/120186.
Transfer history data appended for: https://www.transfermarkt.com/isaac-success/profil/spieler/295331.
Transfer history data appended for: https://www.transfermarkt.com/adam-parkes/profil/spieler/412596.
Transfer history data appended for: https://www.transfermarkt.com/marc-navarro/profil/spieler/335245.
Transfer history data appended for: https://www.transfermarkt.com/will-hughes/profil/spieler/207014.
Transfer history data appended for: https://www.transfermarkt.com/glenn-murray/profil/spieler/45693.
Transfer history data appended for: https://www.transfermarkt.com/tom-dele-bashiru/profil/spieler/346472.
Transfer history data appended for: https://www.transfermarkt.com/adam-masina/profil/spieler/286949.
Transfer history data appended for: https://www.transfermarkt.com/domingos-quina/profil/spieler/391719.
Transfer history data appended for: https://www.transfermarkt.com/christian-kabasele/profil/spieler/81512.
Transfer history data appended for: https://www.transfermarkt.com/francisco-sierralta/profil/spieler/371436.
Transfer history data appended for: https://www.transfermarkt.com/chuba-akpom/profil/spieler/197642.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-howson/profil/spieler/45395.
Transfer history data appended for: https://www.transfermarkt.com/anfernee-dijksteel/profil/spieler/428302.
Transfer history data appended for: https://www.transfermarkt.com/marc-bola/profil/spieler/340310.
Transfer history data appended for: https://www.transfermarkt.com/lewis-wing/profil/spieler/517286.
Transfer history data appended for: https://www.transfermarkt.com/grant-hall/profil/spieler/124845.
Transfer history data appended for: https://www.transfermarkt.com/duncan-watmore/profil/spieler/248045.
Transfer history data appended for: https://www.transfermarkt.com/ashley-fletcher/profil/spieler/289846.
Transfer history data appended for: https://www.transfermarkt.com/sol-brynn/profil/spieler/465952.
Transfer history data appended for: https://www.transfermarkt.com/dael-fry/profil/spieler/314140.
Transfer history data appended for: https://www.transfermarkt.com/hayden-coulson/profil/spieler/314362.
Transfer history data appended for: https://www.transfermarkt.com/marcus-browne/profil/spieler/391470.
Transfer history data appended for: https://www.transfermarkt.com/marcus-bettinelli/profil/spieler/116648.
Transfer history data appended for: https://www.transfermarkt.com/george-saville/profil/spieler/141573.
Transfer history data appended for: https://www.transfermarkt.com/marcus-tavernier/profil/spieler/399434.
Transfer history data appended for: https://www.transfermarkt.com/nathan-wood/profil/spieler/503990.
Transfer history data appended for: https://www.transfermarkt.com/samy-morsy/profil/spieler/123551.
Transfer history data appended for: https://www.transfermarkt.com/djed-spence/profil/spieler/483348.
Transfer history data appended for: https://www.transfermarkt.com/dejan-stojanovic/profil/spieler/115989.
Transfer history data appended for: https://www.transfermarkt.com/marvin-johnson/profil/spieler/216564.
Transfer history data appended for: https://www.transfermarkt.com/paddy-mcnair/profil/spieler/167268.
Transfer history data appended for: https://www.transfermarkt.com/britt-assombalonga/profil/spieler/186172.
Transfer history data appended for: https://www.transfermarkt.com/patrick-roberts/profil/spieler/225452.
Transfer history data appended for: https://www.transfermarkt.com/lukas-rupp/profil/spieler/82863.
Transfer history data appended for: https://www.transfermarkt.com/emiliano-buendia/profil/spieler/321247.
Transfer history data appended for: https://www.transfermarkt.com/christoph-zimmermann/profil/spieler/77812.
Transfer history data appended for: https://www.transfermarkt.com/oliver-skipp/profil/spieler/406638.
Transfer history data appended for: https://www.transfermarkt.com/xavi-quintilla/profil/spieler/204102.
Transfer history data appended for: https://www.transfermarkt.com/josip-drmic/profil/spieler/140579.
Transfer history data appended for: https://www.transfermarkt.com/jacob-lungi-sorensen/profil/spieler/390664.
Transfer history data appended for: https://www.transfermarkt.com/sam-byram/profil/spieler/236953.
Transfer history data appended for: https://www.transfermarkt.com/jordan-hugill/profil/spieler/291544.
Transfer history data appended for: https://www.transfermarkt.com/max-aarons/profil/spieler/471690.
Transfer history data appended for: https://www.transfermarkt.com/mario-vrancic/profil/spieler/39372.
Transfer history data appended for: https://www.transfermarkt.com/ben-gibson/profil/spieler/128904.
Transfer history data appended for: https://www.transfermarkt.com/teemu-pukki/profil/spieler/46972.
Transfer history data appended for: https://www.transfermarkt.com/bali-mumba/profil/spieler/433186.
Transfer history data appended for: https://www.transfermarkt.com/onel-hernandez/profil/spieler/109751.
Transfer history data appended for: https://www.transfermarkt.com/michael-mcgovern/profil/spieler/29391.
Transfer history data appended for: https://www.transfermarkt.com/grant-hanley/profil/spieler/121385.
Transfer history data appended for: https://www.transfermarkt.com/josh-martin/profil/spieler/547534.
Transfer history data appended for: https://www.transfermarkt.com/tim-krul/profil/spieler/33027.
Transfer history data appended for: https://www.transfermarkt.com/alexander-tettey/profil/spieler/12384.
Transfer history data appended for: https://www.transfermarkt.com/kenny-mclean/profil/spieler/126600.

Transfer history data appended for: https://www.transfermarkt.com/przemyslaw-placheta/profil/spieler/383109.
Transfer history data appended for: https://www.transfermarkt.com/adam-idah/profil/spieler/434223.
Transfer history data appended for: https://www.transfermarkt.com/todd-cantwell/profil/spieler/332341.
Transfer history data appended for: https://www.transfermarkt.com/kieran-dowell/profil/spieler/258916.
Transfer history data appended for: https://www.transfermarkt.com/aston-oxborough/profil/spieler/288948.
Transfer history data appended for: https://www.transfermarkt.com/jack-marriott/profil/spieler/268746.
Transfer history data appended for: https://www.transfermarkt.com/korede-adedoyin/profil/spieler/503727.
Transfer history data appended for: https://www.transfermarkt.com/chey-dunkley/profil/spieler/217094.
Transfer history data appended for: https://www.transfermarkt.com/liam-palmer/profil/spieler/137149.
Transfer history data appended for: https://www.transfermarkt.com/cameron-dawson/profil/spieler/251056.
Transfer history data appended for: https://www.transfermarkt.com/adam-reach/profil/spieler/163530.
Transfer history data appended for: https://www.transfermarkt.com/barry-bannan/profil/spieler/61561.
Transfer history data appended for: https://www.transfermarkt.com/josh-windass/profil/spieler/280813.
Transfer history data appended for: https://www.transfermarkt.com/keiren-westwood/profil/spieler/15164.
Transfer history data appended for: https://www.transfermarkt.com/joey-pelupessy/profil/spieler/187293.
Transfer history data appended for: https://www.transfermarkt.com/dominic-iorfa/profil/spieler/213334.
Transfer history data appended for: https://www.transfermarkt.com/liam-waldock/profil/spieler/794822.
Transfer history data appended for: https://www.transfermarkt.com/izzy-brown/profil/spieler/245805.
Transfer history data appended for: https://www.transfermarkt.com/julian-borner/profil/spieler/45677.
Transfer history data appended for: https://www.transfermarkt.com/osaze-urhoghide/profil/spieler/491738.
Transfer history data appended for: https://www.transfermarkt.com/joshua-render/profil/spieler/729941.
Transfer history data appended for: https://www.transfermarkt.com/ben-hughes/profil/spieler/736836.
Transfer history data appended for: https://www.transfermarkt.com/tom-lees/profil/spieler/121333.
Transfer history data appended for: https://www.transfermarkt.com/conor-grant/profil/spieler/579997.
Transfer history data appended for: https://www.transfermarkt.com/charles-hagan/profil/spieler/733563.
Transfer history data appended for: https://www.transfermarkt.com/callum-paterson/profil/spieler/169555.
Transfer history data appended for: https://www.transfermarkt.com/fisayo-dele-bashiru/profil/spieler/530742.
Transfer history data appended for: https://www.transfermarkt.com/massimo-luongo/profil/spieler/181687.
Transfer history data appended for: https://www.transfermarkt.com/matt-penney/profil/spieler/485546.
Transfer history data appended for: https://www.transfermarkt.com/ciaran-brennan/profil/spieler/550134.
Transfer history data appended for: https://www.transfermarkt.com/jordan-rhodes/profil/spieler/48950.
Transfer history data appended for: https://www.transfermarkt.com/liam-shaw/profil/spieler/623560.
Transfer history data appended for: https://www.transfermarkt.com/aden-flint/profil/spieler/105324.
Transfer history data appended for: https://www.transfermarkt.com/moses-odubajo/profil/spieler/163738.
Transfer history data appended for: https://www.transfermarkt.com/joe-wildsmith/profil/spieler/319851.
Transfer history data appended for: https://www.transfermarkt.com/joost-van-aken/profil/spieler/261546.
Transfer history data appended for: https://www.transfermarkt.com/kadeem-harris/profil/spieler/136501.
Transfer history data appended for: https://www.transfermarkt.com/alex-hunt/profil/spieler/606006.
Transfer history data appended for: https://www.transfermarkt.com/nikolas-ioannou/profil/spieler/265033.
Transfer history data appended for: https://www.transfermarkt.com/luke-freeman/profil/spieler/66923.
Transfer history data appended for: https://www.transfermarkt.com/jordan-smith/profil/spieler/452707.
Transfer history data appended for: https://www.transfermarkt.com/michael-dawson/profil/spieler/9988.
Transfer history data appended for: https://www.transfermarkt.com/jack-colback/profil/spieler/61644.
Transfer history data appended for: https://www.transfermarkt.com/michael-hefele/profil/spieler/102382.
Transfer history data appended for: https://www.transfermarkt.com/carl-jenkinson/profil/spieler/126321.
Transfer history data appended for: https://www.transfermarkt.com/brice-samba/profil/spieler/191056.
Transfer history data appended for: https://www.transfermarkt.com/joe-worrall/profil/spieler/415970.
Transfer history data appended for: https://www.transfermarkt.com/ryan-yates/profil/spieler/425902.
Transfer history data appended for: https://www.transfermarkt.com/joe-lolley/profil/spieler/287167.
Transfer history data appended for: https://www.transfermarkt.com/tyler-blackett/profil/spieler/134414.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-bong/profil/spieler/36291.
Transfer history data appended for: https://www.transfermarkt.com/cafu/profil/spieler/203655.
Transfer history data appended for: https://www.transfermarkt.com/lewis-grabban/profil/spieler/35413.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-diallo/profil/spieler/126681.
Transfer history data appended for: https://www.transfermarkt.com/tendayi-darikwa/profil/spieler/158700.
Transfer history data appended for: https://www.transfermarkt.com/zach-clough/profil/spieler/246351.
Transfer history data appended for: https://www.transfermarkt.com/yuri-ribeiro/profil/spieler/258032.
Transfer history data appended for: https://www.transfermarkt.com/scott-mckenna/profil/spieler/255906.
Transfer history data appended for: https://www.transfermarkt.com/samba-sow/profil/spieler/89461.
Transfer history data appended for: https://www.transfermarkt.com/cyrus-christie/profil/spieler/158623.
Transfer history data appended for: https://www.transfermarkt.com/alex-mighten/profil/spieler/503988.
Transfer history data appended for: https://www.transfermarkt.com/lyle-taylor/profil/spieler/104495.
Transfer history data appended for: https://www.transfermarkt.com/anthony-knockaert/profil/spieler/149237.
Transfer history data appended for: https://www.transfermarkt.com/miguel-angel-guerrero/profil/spieler/137704.
Transfer history data appended for: https://www.transfermarkt.com/sammy-ameobi/profil/spieler/92381.
Transfer history data appended for: https://www.transfermarkt.com/loic-mbe-soh/profil/spieler/463610.
Transfer history data appended for: https://www.transfermarkt.com/fouad-bachirou/profil/spieler/93663.
Transfer history data appended for: https://www.transfermarkt.com/harry-arter/profil/spieler/55742.
Transfer history data appended for: https://www.transfermarkt.com/cameron-evans/profil/spieler/535485.
Transfer history data appended for: https://www.transfermarkt.com/jake-bidwell/profil/spieler/121250.
Transfer history data appended for: https://www.transfermarkt.com/wayne-routledge/profil/spieler/14066.
Transfer history data appended for: https://www.transfermarkt.com/korey-smith/profil/spieler/80435.
Transfer history data appended for: https://www.transfermarkt.com/daniel-williams/profil/spieler/525969.
Transfer history data appended for: https://www.transfermarkt.com/jordan-garrick/profil/spieler/461559.
Transfer history data appended for: https://www.transfermarkt.com/viktor-gyokeres/profil/spieler/325443.
Transfer history data appended for: https://www.transfermarkt.com/liam-cullen/profil/spieler/296978.
Transfer history data appended for: https://www.transfermarkt.com/declan-john/profil/spieler/238585.
Transfer history data appended for: https://www.transfermarkt.com/freddie-woodman/profil/spieler/226049.
Transfer history data appended for: https://www.transfermarkt.com/tivonge-rushesha/profil/spieler/580980.
Transfer history data appended for: https://www.transfermarkt.com/ryan-manning/profil/spieler/262300.

Transfer history data appended for: https://www.transfermarkt.com/steven-benda/profil/spieler/381469.
Transfer history data appended for: https://www.transfermarkt.com/oliver-cooper/profil/spieler/504617.
Transfer history data appended for: https://www.transfermarkt.com/connor-roberts/profil/spieler/214666.
Transfer history data appended for: https://www.transfermarkt.com/ben-cabango/profil/spieler/496659.
Transfer history data appended for: https://www.transfermarkt.com/kasey-palmer/profil/spieler/258216.
Transfer history data appended for: https://www.transfermarkt.com/yan-dhanda/profil/spieler/332340.
Transfer history data appended for: https://www.transfermarkt.com/marc-guehi/profil/spieler/392757.
Transfer history data appended for: https://www.transfermarkt.com/kyle-naughton/profil/spieler/66219.
Transfer history data appended for: https://www.transfermarkt.com/ryan-bennett/profil/spieler/67252.
Transfer history data appended for: https://www.transfermarkt.com/andre-ayew/profil/spieler/45403.
Transfer history data appended for: https://www.transfermarkt.com/george-byers/profil/spieler/240083.
Transfer history data appended for: https://www.transfermarkt.com/lewis-webb/profil/spieler/696749.
Transfer history data appended for: https://www.transfermarkt.com/jamal-lowe/profil/spieler/239949.
Transfer history data appended for: https://www.transfermarkt.com/jay-fulton/profil/spieler/171260.
Transfer history data appended for: https://www.transfermarkt.com/joel-latibeaudiere/profil/spieler/412823.
Transfer history data appended for: https://www.transfermarkt.com/matt-grimes/profil/spieler/265471.
Transfer history data appended for: https://www.transfermarkt.com/morgan-gibbs-white/profil/spieler/429014.
Transfer history data appended for: https://www.transfermarkt.com/matt-bloomfield/profil/spieler/13270.
Transfer history data appended for: https://www.transfermarkt.com/james-clark/profil/spieler/580766.
Transfer history data appended for: https://www.transfermarkt.com/dominic-gape/profil/spieler/226964.
Transfer history data appended for: https://www.transfermarkt.com/adebayo-akinfenwa/profil/spieler/32798.
Transfer history data appended for: https://www.transfermarkt.com/jack-grimmer/profil/spieler/119553.
Transfer history data appended for: https://www.transfermarkt.com/nick-freeman/profil/spieler/448813.
Transfer history data appended for: https://www.transfermarkt.com/scott-kashket/profil/spieler/342690.
Transfer history data appended for: https://www.transfermarkt.com/ryan-tafazolli/profil/spieler/244154.
Transfer history data appended for: https://www.transfermarkt.com/daryl-horgan/profil/spieler/178139.
Transfer history data appended for: https://www.transfermarkt.com/alex-pattison/profil/spieler/399454.
Transfer history data appended for: https://www.transfermarkt.com/cameron-yates/profil/spieler/321412.
Transfer history data appended for: https://www.transfermarkt.com/dennis-adeniran/profil/spieler/353147.
Transfer history data appended for: https://www.transfermarkt.com/joe-jacobson/profil/spieler/39508.
Transfer history data appended for: https://www.transfermarkt.com/jason-mccarthy/profil/spieler/227185.
Transfer history data appended for: https://www.transfermarkt.com/fred-onyedinma/profil/spieler/305274.
Transfer history data appended for: https://www.transfermarkt.com/curtis-thompson/profil/spieler/199530.
Transfer history data appended for: https://www.transfermarkt.com/alex-samuel/profil/spieler/203869.
Transfer history data appended for: https://www.transfermarkt.com/darius-charles/profil/spieler/40445.
Transfer history data appended for: https://www.transfermarkt.com/anis-mehmeti/profil/spieler/530813.
Transfer history data appended for: https://www.transfermarkt.com/josh-parker/profil/spieler/132236.
Transfer history data appended for: https://www.transfermarkt.com/anthony-stewart/profil/spieler/184684.
Transfer history data appended for: https://www.transfermarkt.com/josh-knight/profil/spieler/425026.
Transfer history data appended for: https://www.transfermarkt.com/garath-mccleary/profil/spieler/69653.
Transfer history data appended for: https://www.transfermarkt.com/ryan-allsop/profil/spieler/111073.
Transfer history data appended for: https://www.transfermarkt.com/david-wheeler/profil/spieler/104167.
Transfer history data appended for: https://www.transfermarkt.com/uche-ikpeazu/profil/spieler/245765.
Transfer history data appended for: https://www.transfermarkt.com/curtis-anderson/profil/spieler/406557.
Transfer history data appended for: https://www.transfermarkt.com/emil-riis/profil/spieler/293325.
Transfer history data appended for: https://www.transfermarkt.com/louis-moult/profil/spieler/125561.
Transfer history data appended for: https://www.transfermarkt.com/ben-davies/profil/spieler/257097.
Transfer history data appended for: https://www.transfermarkt.com/jayden-stockley/profil/spieler/134293.
Transfer history data appended for: https://www.transfermarkt.com/billy-bodin/profil/spieler/130229.
Transfer history data appended for: https://www.transfermarkt.com/darnell-fisher/profil/spieler/223263.
Transfer history data appended for: https://www.transfermarkt.com/joe-rafferty/profil/spieler/175740.
Transfer history data appended for: https://www.transfermarkt.com/mathew-hudson/profil/spieler/354303.
Transfer history data appended for: https://www.transfermarkt.com/scott-sinclair/profil/spieler/31552.
Transfer history data appended for: https://www.transfermarkt.com/ryan-ledson/profil/spieler/258884.
Transfer history data appended for: https://www.transfermarkt.com/josh-harrop/profil/spieler/289844.
Transfer history data appended for: https://www.transfermarkt.com/paul-gallagher/profil/spieler/10501.
Transfer history data appended for: https://www.transfermarkt.com/sean-maguire/profil/spieler/191320.
Transfer history data appended for: https://www.transfermarkt.com/connor-ripley/profil/spieler/163531.
Transfer history data appended for: https://www.transfermarkt.com/ben-pearson/profil/spieler/183302.
Transfer history data appended for: https://www.transfermarkt.com/tom-barkhuizen/profil/spieler/160137.
Transfer history data appended for: https://www.transfermarkt.com/joe-rodwell-grant/profil/spieler/745997.
Transfer history data appended for: https://www.transfermarkt.com/paul-huntington/profil/spieler/45516.
Transfer history data appended for: https://www.transfermarkt.com/brad-potts/profil/spieler/237013.
Transfer history data appended for: https://www.transfermarkt.com/josh-earl/profil/spieler/426281.
Transfer history data appended for: https://www.transfermarkt.com/patrick-bauer/profil/spieler/94603.
Transfer history data appended for: https://www.transfermarkt.com/jordan-storey/profil/spieler/435198.
Transfer history data appended for: https://www.transfermarkt.com/david-nugent/profil/spieler/33963.
Transfer history data appended for: https://www.transfermarkt.com/andrew-hughes/profil/spieler/191865.
Transfer history data appended for: https://www.transfermarkt.com/declan-rudd/profil/spieler/74088.
Transfer history data appended for: https://www.transfermarkt.com/daniel-johnson/profil/spieler/169092.
Transfer history data appended for: https://www.transfermarkt.com/tom-bayliss/profil/spieler/425799.
Transfer history data appended for: https://www.transfermarkt.com/alan-browne/profil/spieler/277697.
Transfer history data appended for: https://www.transfermarkt.com/liam-walsh/profil/spieler/314998.
Transfer history data appended for: https://www.transfermarkt.com/famara-diedhiou/profil/spieler/237125.
Transfer history data appended for: https://www.transfermarkt.com/chris-martin/profil/spieler/46154.
Transfer history data appended for: https://www.transfermarkt.com/nathan-baker/profil/spieler/62638.
Transfer history data appended for: https://www.transfermarkt.com/jack-hunt/profil/spieler/135038.
Transfer history data appended for: https://www.transfermarkt.com/max-oleary/profil/spieler/296582.
Transfer history data appended for: https://www.transfermarkt.com/rene-gilmartin/profil/spieler/66518.
Transfer history data appended for: https://www.transfermarkt.com/han-noah-massengo/profil/spieler/536508.
Transfer history data appended for: https://www.transfermarkt.com/antoine-semenyo/profil/spieler/583255.

Transfer history data appended for: https://www.transfermarkt.com/joe-williams/profil/spieler/268185.
Transfer history data appended for: https://www.transfermarkt.com/callum-odowda/profil/spieler/255679.
Transfer history data appended for: https://www.transfermarkt.com/andreas-weimann/profil/spieler/49693.
Transfer history data appended for: https://www.transfermarkt.com/adam-nagy/profil/spieler/368559.
Transfer history data appended for: https://www.transfermarkt.com/zak-vyner/profil/spieler/417955.
Transfer history data appended for: https://www.transfermarkt.com/tyreeq-bakinson/profil/spieler/425716.
Transfer history data appended for: https://www.transfermarkt.com/nahki-wells/profil/spieler/173483.
Transfer history data appended for: https://www.transfermarkt.com/daniel-bentley/profil/spieler/136401.
Transfer history data appended for: https://www.transfermarkt.com/jamie-paterson/profil/spieler/156886.
Transfer history data appended for: https://www.transfermarkt.com/jay-dasilva/profil/spieler/258915.
Transfer history data appended for: https://www.transfermarkt.com/taylor-moore/profil/spieler/314280.
Transfer history data appended for: https://www.transfermarkt.com/chris-brunt/profil/spieler/36814.
Transfer history data appended for: https://www.transfermarkt.com/adrian-mariappa/profil/spieler/38145.
Transfer history data appended for: https://www.transfermarkt.com/tommy-rowe/profil/spieler/67331.
Transfer history data appended for: https://www.transfermarkt.com/joe-wollacott/profil/spieler/418144.
Transfer history data appended for: https://www.transfermarkt.com/alfie-mawson/profil/spieler/287431.
Transfer history data appended for: https://www.transfermarkt.com/steven-sessegnon/profil/spieler/406558.
Transfer history data appended for: https://www.transfermarkt.com/mikel-san-jose/profil/spieler/52469.
Transfer history data appended for: https://www.transfermarkt.com/dan-crowley/profil/spieler/223225.
Transfer history data appended for: https://www.transfermarkt.com/neil-etheridge/profil/spieler/61694.
Transfer history data appended for: https://www.transfermarkt.com/marc-roberts/profil/spieler/284959.
Transfer history data appended for: https://www.transfermarkt.com/ivan-sunjic/profil/spieler/226097.
Transfer history data appended for: https://www.transfermarkt.com/david-davis/profil/spieler/129054.
Transfer history data appended for: https://www.transfermarkt.com/andres-prieto/profil/spieler/238032.
Transfer history data appended for: https://www.transfermarkt.com/maxime-colin/profil/spieler/156618.
Transfer history data appended for: https://www.transfermarkt.com/riley-mcgree/profil/spieler/428061.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-leko/profil/spieler/314266.
Transfer history data appended for: https://www.transfermarkt.com/josh-dacres-cogley/profil/spieler/452683.
Transfer history data appended for: https://www.transfermarkt.com/josh-mceachran/profil/spieler/128905.
Transfer history data appended for: https://www.transfermarkt.com/harlee-dean/profil/spieler/120504.
Transfer history data appended for: https://www.transfermarkt.com/caolan-boyd-munce/profil/spieler/438086.
Transfer history data appended for: https://www.transfermarkt.com/scott-hogan/profil/spieler/138783.
Transfer history data appended for: https://www.transfermarkt.com/jon-toral/profil/spieler/193593.
Transfer history data appended for: https://www.transfermarkt.com/george-friend/profil/spieler/77544.
Transfer history data appended for: https://www.transfermarkt.com/ivan-sanchez/profil/spieler/221311.
Transfer history data appended for: https://www.transfermarkt.com/jeremie-bela/profil/spieler/170966.
Transfer history data appended for: https://www.transfermarkt.com/kristian-pedersen/profil/spieler/331779.
Transfer history data appended for: https://www.transfermarkt.com/maikel-kieftenbeld/profil/spieler/82332.
Transfer history data appended for: https://www.transfermarkt.com/adam-clayton/profil/spieler/73067.
Transfer history data appended for: https://www.transfermarkt.com/jake-clarke-salter/profil/spieler/316551.
Transfer history data appended for: https://www.transfermarkt.com/gary-gardner/profil/spieler/110861.
Transfer history data appended for: https://www.transfermarkt.com/lukas-jutkiewicz/profil/spieler/33507.
Transfer history data appended for: https://www.transfermarkt.com/liam-lindsay/profil/spieler/228912.
Transfer history data appended for: https://www.transfermarkt.com/nathan-collins/profil/spieler/469050.
Transfer history data appended for: https://www.transfermarkt.com/jacob-brown/profil/spieler/469958.
Transfer history data appended for: https://www.transfermarkt.com/jordan-cousins/profil/spieler/128902.
Transfer history data appended for: https://www.transfermarkt.com/tashan-oakley-boothe/profil/spieler/406637.
Transfer history data appended for: https://www.transfermarkt.com/harry-souttar/profil/spieler/298091.
Transfer history data appended for: https://www.transfermarkt.com/angus-gunn/profil/spieler/201574.
Transfer history data appended for: https://www.transfermarkt.com/james-chester/profil/spieler/73482.
Transfer history data appended for: https://www.transfermarkt.com/danny-batth/profil/spieler/129049.
Transfer history data appended for: https://www.transfermarkt.com/jordan-thompson/profil/spieler/321169.
Transfer history data appended for: https://www.transfermarkt.com/joe-allen/profil/spieler/51452.
Transfer history data appended for: https://www.transfermarkt.com/niki-maenpaa/profil/spieler/12359.
Transfer history data appended for: https://www.transfermarkt.com/adam-davies/profil/spieler/121254.
Transfer history data appended for: https://www.transfermarkt.com/nick-powell/profil/spieler/134424.
Transfer history data appended for: https://www.transfermarkt.com/thibaud-verlinden/profil/spieler/338673.
Transfer history data appended for: https://www.transfermarkt.com/blondy-nna-noukeu/profil/spieler/696892.
Transfer history data appended for: https://www.transfermarkt.com/lee-gregory/profil/spieler/208428.
Transfer history data appended for: https://www.transfermarkt.com/andy-lonergan/profil/spieler/14044.
Transfer history data appended for: https://www.transfermarkt.com/moritz-bauer/profil/spieler/159692.
Transfer history data appended for: https://www.transfermarkt.com/josh-tymon/profil/spieler/419929.
Transfer history data appended for: https://www.transfermarkt.com/sam-vokes/profil/spieler/48078.
Transfer history data appended for: https://www.transfermarkt.com/tyrese-campbell/profil/spieler/382554.
Transfer history data appended for: https://www.transfermarkt.com/steven-fletcher/profil/spieler/35099.
Transfer history data appended for: https://www.transfermarkt.com/ryan-shawcross/profil/spieler/45861.
Transfer history data appended for: https://www.transfermarkt.com/tommy-smith/profil/spieler/121398.
Transfer history data appended for: https://www.transfermarkt.com/james-mcclean/profil/spieler/85935.
Transfer history data appended for: https://www.transfermarkt.com/tom-ince/profil/spieler/157368.
Transfer history data appended for: https://www.transfermarkt.com/kevin-wimmer/profil/spieler/122675.
Transfer history data appended for: https://www.transfermarkt.com/sam-clucas/profil/spieler/122223.
Transfer history data appended for: https://www.transfermarkt.com/morgan-fox/profil/spieler/250277.
Transfer history data appended for: https://www.transfermarkt.com/john-mikel-obi/profil/spieler/30739.
Transfer history data appended for: https://www.transfermarkt.com/thomas-kaminski/profil/spieler/77757.
Transfer history data appended for: https://www.transfermarkt.com/tom-trybull/profil/spieler/93831.
Transfer history data appended for: https://www.transfermarkt.com/scott-wharton/profil/spieler/364803.
Transfer history data appended for: https://www.transfermarkt.com/jacob-davenport/profil/spieler/380914.
Transfer history data appended for: https://www.transfermarkt.com/bradley-dack/profil/spieler/238556.
Transfer history data appended for: https://www.transfermarkt.com/jordan-eastham/profil/spieler/531454.
Transfer history data appended for: https://www.transfermarkt.com/lewis-travis/profil/spieler/372802.

Transfer history data appended for: https://www.transfermarkt.com/amarii-bell/profil/spieler/278166.
Transfer history data appended for: https://www.transfermarkt.com/corry-evans/profil/spieler/73501.
Transfer history data appended for: https://www.transfermarkt.com/derrick-williams/profil/spieler/128287.
Transfer history data appended for: https://www.transfermarkt.com/barry-douglas/profil/spieler/91854.
Transfer history data appended for: https://www.transfermarkt.com/joe-rothwell/profil/spieler/183293.
Transfer history data appended for: https://www.transfermarkt.com/joe-rankin-costello/profil/spieler/411229.
Transfer history data appended for: https://www.transfermarkt.com/daniel-ayala/profil/spieler/78966.
Transfer history data appended for: https://www.transfermarkt.com/harry-chapman/profil/spieler/348488.
Transfer history data appended for: https://www.transfermarkt.com/tyrhys-dolan/profil/spieler/647435.
Transfer history data appended for: https://www.transfermarkt.com/darragh-lenihan/profil/spieler/183167.
Transfer history data appended for: https://www.transfermarkt.com/bradley-johnson/profil/spieler/49327.
Transfer history data appended for: https://www.transfermarkt.com/elliott-bennett/profil/spieler/43193.
Transfer history data appended for: https://www.transfermarkt.com/adam-armstrong/profil/spieler/250426.
Transfer history data appended for: https://www.transfermarkt.com/ben-brereton/profil/spieler/426192.
Transfer history data appended for: https://www.transfermarkt.com/sam-gallagher/profil/spieler/227183.
Transfer history data appended for: https://www.transfermarkt.com/ryan-nyambe/profil/spieler/348469.
Transfer history data appended for: https://www.transfermarkt.com/antonis-stergiakis/profil/spieler/366217.
Transfer history data appended for: https://www.transfermarkt.com/stewart-downing/profil/spieler/4063.
Transfer history data appended for: https://www.transfermarkt.com/aynsley-pears/profil/spieler/354456.
Transfer history data appended for: https://www.transfermarkt.com/harvey-elliott/profil/spieler/565822.
Transfer history data appended for: https://www.transfermarkt.com/john-buckley/profil/spieler/503781.
Transfer history data appended for: https://www.transfermarkt.com/ody-alfa/profil/spieler/649748.
Transfer history data appended for: https://www.transfermarkt.com/albert-adomah/profil/spieler/83430.
Transfer history data appended for: https://www.transfermarkt.com/niko-hamalainen/profil/spieler/351546.
Transfer history data appended for: https://www.transfermarkt.com/liam-kelly/profil/spieler/208772.
Transfer history data appended for: https://www.transfermarkt.com/todd-kane/profil/spieler/154287.
Transfer history data appended for: https://www.transfermarkt.com/luke-amos/profil/spieler/258912.
Transfer history data appended for: https://www.transfermarkt.com/geoff-cameron/profil/spieler/31642.
Transfer history data appended for: https://www.transfermarkt.com/joe-lumley/profil/spieler/336367.
Transfer history data appended for: https://www.transfermarkt.com/lee-wallace/profil/spieler/36657.
Transfer history data appended for: https://www.transfermarkt.com/conor-masterson/profil/spieler/293784.
Transfer history data appended for: https://www.transfermarkt.com/bright-osayi-samuel/profil/spieler/358948.
Transfer history data appended for: https://www.transfermarkt.com/yoann-barbet/profil/spieler/159838.
Transfer history data appended for: https://www.transfermarkt.com/charlie-owens/profil/spieler/374263.
Transfer history data appended for: https://www.transfermarkt.com/faysal-bettache/profil/spieler/612163.
Transfer history data appended for: https://www.transfermarkt.com/osman-kakay/profil/spieler/419576.
Transfer history data appended for: https://www.transfermarkt.com/rob-dickie/profil/spieler/257437.
Transfer history data appended for: https://www.transfermarkt.com/george-thomas/profil/spieler/298240.
Transfer history data appended for: https://www.transfermarkt.com/lyndon-dykes/profil/spieler/347138.
Transfer history data appended for: https://www.transfermarkt.com/tom-carroll/profil/spieler/121279.
Transfer history data appended for: https://www.transfermarkt.com/macauley-bonne/profil/spieler/296577.
Transfer history data appended for: https://www.transfermarkt.com/dominic-ball/profil/spieler/167254.
Transfer history data appended for: https://www.transfermarkt.com/seny-dieng/profil/spieler/250870.
Transfer history data appended for: https://www.transfermarkt.com/charlie-kelman/profil/spieler/633492.
Transfer history data appended for: https://www.transfermarkt.com/chris-willock/profil/spieler/314341.
Transfer history data appended for: https://www.transfermarkt.com/ilias-chair/profil/spieler/380473.
Transfer history data appended for: https://www.transfermarkt.com/jordan-shipley/profil/spieler/425800.
Transfer history data appended for: https://www.transfermarkt.com/marko-marosi/profil/spieler/289411.
Transfer history data appended for: https://www.transfermarkt.com/callum-ohare/profil/spieler/371262.
Transfer history data appended for: https://www.transfermarkt.com/marcel-hilssner/profil/spieler/153634.
Transfer history data appended for: https://www.transfermarkt.com/liam-kelly/profil/spieler/106643.
Transfer history data appended for: https://www.transfermarkt.com/matt-godden/profil/spieler/145553.
Transfer history data appended for: https://www.transfermarkt.com/ben-wilson/profil/spieler/121352.
Transfer history data appended for: https://www.transfermarkt.com/wesley-jobello/profil/spieler/181376.
Transfer history data appended for: https://www.transfermarkt.com/sam-mccallum/profil/spieler/618901.
Transfer history data appended for: https://www.transfermarkt.com/tyler-walker/profil/spieler/341295.
Transfer history data appended for: https://www.transfermarkt.com/kyle-mcfadzean/profil/spieler/32526.
Transfer history data appended for: https://www.transfermarkt.com/josh-pask/profil/spieler/339789.
Transfer history data appended for: https://www.transfermarkt.com/dominic-hyam/profil/spieler/263268.
Transfer history data appended for: https://www.transfermarkt.com/jordon-thompson/profil/spieler/425802.
Transfer history data appended for: https://www.transfermarkt.com/ben-sheaf/profil/spieler/314384.
Transfer history data appended for: https://www.transfermarkt.com/gervane-kastaneer/profil/spieler/240752.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-hamer/profil/spieler/322985.
Transfer history data appended for: https://www.transfermarkt.com/jodi-jones/profil/spieler/354695.
Transfer history data appended for: https://www.transfermarkt.com/lee-camp/profil/spieler/13443.
Transfer history data appended for: https://www.transfermarkt.com/julien-da-costa/profil/spieler/289196.
Transfer history data appended for: https://www.transfermarkt.com/michael-rose/profil/spieler/154219.
Transfer history data appended for: https://www.transfermarkt.com/maxime-biamou/profil/spieler/451306.
Transfer history data appended for: https://www.transfermarkt.com/ryan-giles/profil/spieler/504581.
Transfer history data appended for: https://www.transfermarkt.com/amadou-bakayoko/profil/spieler/320408.
Transfer history data appended for: https://www.transfermarkt.com/jamie-allen/profil/spieler/257727.
Transfer history data appended for: https://www.transfermarkt.com/fankaty-dabo/profil/spieler/186926.
Transfer history data appended for: https://www.transfermarkt.com/leo-ostigard/profil/spieler/367284.
Transfer history data appended for: https://www.transfermarkt.com/jamal-blackman/profil/spieler/128898.
Transfer history data appended for: https://www.transfermarkt.com/kyle-vassell/profil/spieler/293002.
Transfer history data appended for: https://www.transfermarkt.com/kieran-sadlier/profil/spieler/222740.
Transfer history data appended for: https://www.transfermarkt.com/viktor-johansson/profil/spieler/273742.
Transfer history data appended for: https://www.transfermarkt.com/freddie-ladapo/profil/spieler/233998.
Transfer history data appended for: https://www.transfermarkt.com/jacob-gratton/profil/spieler/731867.
Transfer history data appended for: https://www.transfermarkt.com/matt-crooks/profil/spieler/169416.

Transfer history data appended for: https://www.transfermarkt.com/dan-barlaser/profil/spieler/256773.
Transfer history data appended for: https://www.transfermarkt.com/matthew-olosunde/profil/spieler/315777.
Transfer history data appended for: https://www.transfermarkt.com/jamie-lindsay/profil/spieler/165341.
Transfer history data appended for: https://www.transfermarkt.com/shaun-macdonald/profil/spieler/10375.
Transfer history data appended for: https://www.transfermarkt.com/wes-harding/profil/spieler/526694.
Transfer history data appended for: https://www.transfermarkt.com/michael-ihiekwe/profil/spieler/145923.
Transfer history data appended for: https://www.transfermarkt.com/adam-thompson/profil/spieler/160163.
Transfer history data appended for: https://www.transfermarkt.com/jake-hull/profil/spieler/805494.
Transfer history data appended for: https://www.transfermarkt.com/michael-smith/profil/spieler/96173.
Transfer history data appended for: https://www.transfermarkt.com/trevor-clarke/profil/spieler/340920.
Transfer history data appended for: https://www.transfermarkt.com/george-hirst/profil/spieler/420808.
Transfer history data appended for: https://www.transfermarkt.com/mickel-miller/profil/spieler/563694.
Transfer history data appended for: https://www.transfermarkt.com/chiedozie-ogbene/profil/spieler/392591.
Transfer history data appended for: https://www.transfermarkt.com/joe-mattock/profil/spieler/49611.
Transfer history data appended for: https://www.transfermarkt.com/florian-jozefzoon/profil/spieler/124873.
Transfer history data appended for: https://www.transfermarkt.com/clark-robertson/profil/spieler/119569.
Transfer history data appended for: https://www.transfermarkt.com/josh-vickers/profil/spieler/242681.
Transfer history data appended for: https://www.transfermarkt.com/billy-jones/profil/spieler/36866.
Transfer history data appended for: https://www.transfermarkt.com/ben-wiles/profil/spieler/542471.
Transfer history data appended for: https://www.transfermarkt.com/angus-macdonald/profil/spieler/192364.
Transfer history data appended for: https://www.transfermarkt.com/richard-wood/profil/spieler/13434.
Transfer history data appended for: https://www.transfermarkt.com/frankie-kent/profil/spieler/307094.
Transfer history data appended for: https://www.transfermarkt.com/idris-kanu/profil/spieler/405982.
Transfer history data appended for: https://www.transfermarkt.com/archie-jones/profil/spieler/677936.
Transfer history data appended for: https://www.transfermarkt.com/nathan-thompson/profil/spieler/79725.
Transfer history data appended for: https://www.transfermarkt.com/frazer-blake-tracy/profil/spieler/675993.
Transfer history data appended for: https://www.transfermarkt.com/ryan-broom/profil/spieler/380029.
Transfer history data appended for: https://www.transfermarkt.com/joe-ward/profil/spieler/370559.
Transfer history data appended for: https://www.transfermarkt.com/ronnie-edwards/profil/spieler/732165.
Transfer history data appended for: https://www.transfermarkt.com/sammie-szmodics/profil/spieler/292139.
Transfer history data appended for: https://www.transfermarkt.com/jack-taylor/profil/spieler/458178.
Transfer history data appended for: https://www.transfermarkt.com/harrison-burrows/profil/spieler/533980.
Transfer history data appended for: https://www.transfermarkt.com/siriki-dembele/profil/spieler/488656.
Transfer history data appended for: https://www.transfermarkt.com/ethan-hamilton/profil/spieler/396286.
Transfer history data appended for: https://www.transfermarkt.com/will-blackmore/profil/spieler/677849.
Transfer history data appended for: https://www.transfermarkt.com/flynn-clarke/profil/spieler/677939.
Transfer history data appended for: https://www.transfermarkt.com/serhat-tasdemir/profil/spieler/526862.
Transfer history data appended for: https://www.transfermarkt.com/ricky-jade-jones/profil/spieler/677935.
Transfer history data appended for: https://www.transfermarkt.com/bradley-rolt/profil/spieler/677895.
Transfer history data appended for: https://www.transfermarkt.com/niall-mason/profil/spieler/319817.
Transfer history data appended for: https://www.transfermarkt.com/bobby-copping/profil/spieler/567662.
Transfer history data appended for: https://www.transfermarkt.com/mark-beevers/profil/spieler/46744.
Transfer history data appended for: https://www.transfermarkt.com/louis-reed/profil/spieler/316312.
Transfer history data appended for: https://www.transfermarkt.com/christy-pym/profil/spieler/260368.
Transfer history data appended for: https://www.transfermarkt.com/jonson-clarke-harris/profil/spieler/158631.
Transfer history data appended for: https://www.transfermarkt.com/reece-brown/profil/spieler/236493.
Transfer history data appended for: https://www.transfermarkt.com/dan-butler/profil/spieler/227944.
Transfer history data appended for: https://www.transfermarkt.com/jason-naismith/profil/spieler/177020.
Transfer history data appended for: https://www.transfermarkt.com/mo-eisa/profil/spieler/255619.
Transfer history data appended for: https://www.transfermarkt.com/daniel-gyollai/profil/spieler/268184.
Transfer history data appended for: https://www.transfermarkt.com/kwadwo-baah/profil/spieler/711247.
Transfer history data appended for: https://www.transfermarkt.com/tolaji-bola/profil/spieler/340307.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-ryan/profil/spieler/58292.
Transfer history data appended for: https://www.transfermarkt.com/alex-newby/profil/spieler/390687.
Transfer history data appended for: https://www.transfermarkt.com/jake-beesley/profil/spieler/321579.
Transfer history data appended for: https://www.transfermarkt.com/yeboah-amankwah/profil/spieler/530740.
Transfer history data appended for: https://www.transfermarkt.com/stephen-humphrys/profil/spieler/354567.
Transfer history data appended for: https://www.transfermarkt.com/bradley-wade/profil/spieler/640027.
Transfer history data appended for: https://www.transfermarkt.com/joe-dunne/profil/spieler/632154.
Transfer history data appended for: https://www.transfermarkt.com/ryan-mclaughlin/profil/spieler/205325.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-keohane/profil/spieler/136179.
Transfer history data appended for: https://www.transfermarkt.com/fabio-tavares/profil/spieler/614086.
Transfer history data appended for: https://www.transfermarkt.com/jay-lynch/profil/spieler/128273.
Transfer history data appended for: https://www.transfermarkt.com/paul-mcshane/profil/spieler/24636.
Transfer history data appended for: https://www.transfermarkt.com/oliver-rathbone/profil/spieler/404553.
Transfer history data appended for: https://www.transfermarkt.com/stephen-dooley/profil/spieler/104077.
Transfer history data appended for: https://www.transfermarkt.com/aaron-morley/profil/spieler/451749.
Transfer history data appended for: https://www.transfermarkt.com/jim-mcnulty/profil/spieler/67310.
Transfer history data appended for: https://www.transfermarkt.com/lewis-bradley/profil/spieler/644743.
Transfer history data appended for: https://www.transfermarkt.com/harrison-hopper/profil/spieler/632152.
Transfer history data appended for: https://www.transfermarkt.com/matthew-lund/profil/spieler/118564.
Transfer history data appended for: https://www.transfermarkt.com/matt-done/profil/spieler/67411.
Transfer history data appended for: https://www.transfermarkt.com/haydon-roberts/profil/spieler/533523.
Transfer history data appended for: https://www.transfermarkt.com/gavin-bazunu/profil/spieler/585550.
Transfer history data appended for: https://www.transfermarkt.com/eoghan-oconnell/profil/spieler/280982.
Transfer history data appended for: https://www.transfermarkt.com/will-aimson/profil/spieler/315619.
Transfer history data appended for: https://www.transfermarkt.com/tyrese-fornah/profil/spieler/503918.
Transfer history data appended for: https://www.transfermarkt.com/danny-mayor/profil/spieler/106708.
Transfer history data appended for: https://www.transfermarkt.com/niall-canavan/profil/spieler/122243.
Transfer history data appended for: https://www.transfermarkt.com/michael-cooper/profil/spieler/533078.

Transfer history data appended for: https://www.transfermarkt.com/ben-reeves/profil/spieler/171234.
Transfer history data appended for: https://www.transfermarkt.com/ryan-hardie/profil/spieler/249063.
Transfer history data appended for: https://www.transfermarkt.com/luke-mccormick/profil/spieler/20978.
Transfer history data appended for: https://www.transfermarkt.com/ryan-law/profil/spieler/565915.
Transfer history data appended for: https://www.transfermarkt.com/gary-sawyer/profil/spieler/42346.
Transfer history data appended for: https://www.transfermarkt.com/panutche-camara/profil/spieler/512916.
Transfer history data appended for: https://www.transfermarkt.com/frank-nouble/profil/spieler/119123.
Transfer history data appended for: https://www.transfermarkt.com/jarvis-cleal/profil/spieler/745164.
Transfer history data appended for: https://www.transfermarkt.com/byron-moore/profil/spieler/66970.
Transfer history data appended for: https://www.transfermarkt.com/george-cooper/profil/spieler/319779.
Transfer history data appended for: https://www.transfermarkt.com/conor-grant/profil/spieler/218355.
Transfer history data appended for: https://www.transfermarkt.com/timmy-abraham/profil/spieler/506199.
Transfer history data appended for: https://www.transfermarkt.com/klajdi-lolos/profil/spieler/565911.
Transfer history data appended for: https://www.transfermarkt.com/dom-telford/profil/spieler/333782.
Transfer history data appended for: https://www.transfermarkt.com/ollie-tomlinson/profil/spieler/784258.
Transfer history data appended for: https://www.transfermarkt.com/kelland-watts/profil/spieler/484389.
Transfer history data appended for: https://www.transfermarkt.com/scott-wootton/profil/spieler/128262.
Transfer history data appended for: https://www.transfermarkt.com/luke-jephcott/profil/spieler/565913.
Transfer history data appended for: https://www.transfermarkt.com/jack-ruddy/profil/spieler/346175.
Transfer history data appended for: https://www.transfermarkt.com/jerome-opoku/profil/spieler/408563.
Transfer history data appended for: https://www.transfermarkt.com/lewis-macleod/profil/spieler/132208.
Transfer history data appended for: https://www.transfermarkt.com/joe-edwards/profil/spieler/121773.
Transfer history data appended for: https://www.transfermarkt.com/daniel-udoh/profil/spieler/428446.
Transfer history data appended for: https://www.transfermarkt.com/brad-walker/profil/spieler/261166.
Transfer history data appended for: https://www.transfermarkt.com/scott-high/profil/spieler/728982.
Transfer history data appended for: https://www.transfermarkt.com/joshua-daniels/profil/spieler/263806.
Transfer history data appended for: https://www.transfermarkt.com/ro-shaun-williams/profil/spieler/314388.
Transfer history data appended for: https://www.transfermarkt.com/charlie-daniels/profil/spieler/61819.
Transfer history data appended for: https://www.transfermarkt.com/ollie-norburn/profil/spieler/177914.
Transfer history data appended for: https://www.transfermarkt.com/marc-pugh/profil/spieler/36939.
Transfer history data appended for: https://www.transfermarkt.com/aaron-pierre/profil/spieler/128292.
Transfer history data appended for: https://www.transfermarkt.com/david-edwards/profil/spieler/54949.
Transfer history data appended for: https://www.transfermarkt.com/josh-vela/profil/spieler/173804.
Transfer history data appended for: https://www.transfermarkt.com/jan-zamburek/profil/spieler/487924.
Transfer history data appended for: https://www.transfermarkt.com/jason-cummings/profil/spieler/209583.
Transfer history data appended for: https://www.transfermarkt.com/matija-sarkic/profil/spieler/293257.
Transfer history data appended for: https://www.transfermarkt.com/dejan-iliev/profil/spieler/205757.
Transfer history data appended for: https://www.transfermarkt.com/leon-clarke/profil/spieler/36859.
Transfer history data appended for: https://www.transfermarkt.com/cameron-gregory/profil/spieler/533840.
Transfer history data appended for: https://www.transfermarkt.com/rekeil-pyke/profil/spieler/476050.
Transfer history data appended for: https://www.transfermarkt.com/donald-love/profil/spieler/179451.
Transfer history data appended for: https://www.transfermarkt.com/ryan-sears/profil/spieler/479202.
Transfer history data appended for: https://www.transfermarkt.com/james-rowland/profil/spieler/633416.
Transfer history data appended for: https://www.transfermarkt.com/sean-goss/profil/spieler/289843.
Transfer history data appended for: https://www.transfermarkt.com/shilow-tracey/profil/spieler/417256.
Transfer history data appended for: https://www.transfermarkt.com/scott-golbourne/profil/spieler/37457.
Transfer history data appended for: https://www.transfermarkt.com/ethan-ebanks-landell/profil/spieler/129067.
Transfer history data appended for: https://www.transfermarkt.com/matthew-millar/profil/spieler/402770.
Transfer history data appended for: https://www.transfermarkt.com/marlon-fossey/profil/spieler/408562.
Transfer history data appended for: https://www.transfermarkt.com/ryan-barnett/profil/spieler/479203.
Transfer history data appended for: https://www.transfermarkt.com/shaun-whalley/profil/spieler/49637.
Transfer history data appended for: https://www.transfermarkt.com/harry-burgoyne/profil/spieler/285583.
Transfer history data appended for: https://www.transfermarkt.com/jordan-williams/profil/spieler/279454.
Transfer history data appended for: https://www.transfermarkt.com/matty-virtue/profil/spieler/279458.
Transfer history data appended for: https://www.transfermarkt.com/daniel-ballard/profil/spieler/503686.
Transfer history data appended for: https://www.transfermarkt.com/ollie-turton/profil/spieler/148660.
Transfer history data appended for: https://www.transfermarkt.com/dan-kemp/profil/spieler/396857.
Transfer history data appended for: https://www.transfermarkt.com/gary-madine/profil/spieler/66994.
Transfer history data appended for: https://www.transfermarkt.com/luke-garbutt/profil/spieler/110860.
Transfer history data appended for: https://www.transfermarkt.com/chris-maxwell/profil/spieler/104686.
Transfer history data appended for: https://www.transfermarkt.com/alex-fojticek/profil/spieler/434072.
Transfer history data appended for: https://www.transfermarkt.com/james-husband/profil/spieler/167393.
Transfer history data appended for: https://www.transfermarkt.com/kenny-dougall/profil/spieler/334804.
Transfer history data appended for: https://www.transfermarkt.com/cj-hamilton/profil/spieler/391788.
Transfer history data appended for: https://www.transfermarkt.com/marvin-ekpiteta/profil/spieler/570768.
Transfer history data appended for: https://www.transfermarkt.com/teddy-howe/profil/spieler/424902.
Transfer history data appended for: https://www.transfermarkt.com/demetri-mitchell/profil/spieler/258886.
Transfer history data appended for: https://www.transfermarkt.com/keshi-anderson/profil/spieler/353674.
Transfer history data appended for: https://www.transfermarkt.com/sullay-kaikai/profil/spieler/244130.
Transfer history data appended for: https://www.transfermarkt.com/jerry-yates/profil/spieler/351261.
Transfer history data appended for: https://www.transfermarkt.com/ethan-robson/profil/spieler/258199.
Transfer history data appended for: https://www.transfermarkt.com/bez-lubala/profil/spieler/577895.
Transfer history data appended for: https://www.transfermarkt.com/oliver-sarkic/profil/spieler/293258.
Transfer history data appended for: https://www.transfermarkt.com/grant-ward/profil/spieler/283655.
Transfer history data appended for: https://www.transfermarkt.com/jordan-thorniley/profil/spieler/411255.
Transfer history data appended for: https://www.transfermarkt.com/jordan-lawrence-gabriel/profil/spieler/425900.
Transfer history data appended for: https://www.transfermarkt.com/daniel-leo-gretarsson/profil/spieler/200747.
Transfer history data appended for: https://www.transfermarkt.com/ben-woodburn/profil/spieler/344015.
Transfer history data appended for: https://www.transfermarkt.com/diallang-jaiyesimi/profil/spieler/415816.
Transfer history data appended for: https://www.transfermarkt.com/rob-hunt/profil/spieler/335591.

Transfer history data appended for: https://www.transfermarkt.com/jonny-smith/profil/spieler/424414.
Transfer history data appended for: https://www.transfermarkt.com/matt-smith/profil/spieler/528894.
Transfer history data appended for: https://www.transfermarkt.com/ellis-iandolo/profil/spieler/386937.
Transfer history data appended for: https://www.transfermarkt.com/akin-odimayo/profil/spieler/473544.
Transfer history data appended for: https://www.transfermarkt.com/joel-grant/profil/spieler/37012.
Transfer history data appended for: https://www.transfermarkt.com/dion-conroy/profil/spieler/255816.
Transfer history data appended for: https://www.transfermarkt.com/archie-matthews/profil/spieler/662240.
Transfer history data appended for: https://www.transfermarkt.com/taylor-curran/profil/spieler/633154.
Transfer history data appended for: https://www.transfermarkt.com/jordan-lyden/profil/spieler/251289.
Transfer history data appended for: https://www.transfermarkt.com/jack-payne/profil/spieler/278092.
Transfer history data appended for: https://www.transfermarkt.com/joe-fryer/profil/spieler/266037.
Transfer history data appended for: https://www.transfermarkt.com/dion-donohue/profil/spieler/393575.
Transfer history data appended for: https://www.transfermarkt.com/tom-broadbent/profil/spieler/526247.
Transfer history data appended for: https://www.transfermarkt.com/paul-caddis/profil/spieler/60908.
Transfer history data appended for: https://www.transfermarkt.com/hallam-hope/profil/spieler/134418.
Transfer history data appended for: https://www.transfermarkt.com/brett-pitman/profil/spieler/48312.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-grounds/profil/spieler/57490.
Transfer history data appended for: https://www.transfermarkt.com/matej-kovar/profil/spieler/550829.
Transfer history data appended for: https://www.transfermarkt.com/zeki-fryers/profil/spieler/141655.
Transfer history data appended for: https://www.transfermarkt.com/jordan-stevens/profil/spieler/533913.
Transfer history data appended for: https://www.transfermarkt.com/tyler-smith/profil/spieler/602978.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-baudry/profil/spieler/77975.
Transfer history data appended for: https://www.transfermarkt.com/anthony-grant/profil/spieler/31698.
Transfer history data appended for: https://www.transfermarkt.com/george-honeyman/profil/spieler/218140.
Transfer history data appended for: https://www.transfermarkt.com/mallik-wilks/profil/spieler/477704.
Transfer history data appended for: https://www.transfermarkt.com/sean-mcloughlin/profil/spieler/524210.
Transfer history data appended for: https://www.transfermarkt.com/martin-samuelsen/profil/spieler/234807.
Transfer history data appended for: https://www.transfermarkt.com/josh-emmanuel/profil/spieler/386263.
Transfer history data appended for: https://www.transfermarkt.com/james-scott/profil/spieler/443726.
Transfer history data appended for: https://www.transfermarkt.com/tom-eaves/profil/spieler/135136.
Transfer history data appended for: https://www.transfermarkt.com/callum-elder/profil/spieler/271997.
Transfer history data appended for: https://www.transfermarkt.com/richard-smallwood/profil/spieler/158713.
Transfer history data appended for: https://www.transfermarkt.com/matt-ingram/profil/spieler/164499.
Transfer history data appended for: https://www.transfermarkt.com/greg-docherty/profil/spieler/227618.
Transfer history data appended for: https://www.transfermarkt.com/festus-arthur/profil/spieler/694830.
Transfer history data appended for: https://www.transfermarkt.com/josh-magennis/profil/spieler/63223.
Transfer history data appended for: https://www.transfermarkt.com/thomas-mayer/profil/spieler/159584.
Transfer history data appended for: https://www.transfermarkt.com/harvey-cartwright/profil/spieler/712592.
Transfer history data appended for: https://www.transfermarkt.com/max-sheaf/profil/spieler/606810.
Transfer history data appended for: https://www.transfermarkt.com/jordy-de-wijs/profil/spieler/215096.
Transfer history data appended for: https://www.transfermarkt.com/lewie-coyle/profil/spieler/413402.
Transfer history data appended for: https://www.transfermarkt.com/alfie-jones/profil/spieler/340990.
Transfer history data appended for: https://www.transfermarkt.com/reece-burke/profil/spieler/264220.
Transfer history data appended for: https://www.transfermarkt.com/hakeeb-adelakun/profil/spieler/255129.
Transfer history data appended for: https://www.transfermarkt.com/george-long/profil/spieler/151334.
Transfer history data appended for: https://www.transfermarkt.com/daniel-batty/profil/spieler/509268.
Transfer history data appended for: https://www.transfermarkt.com/keane-lewis-potter/profil/spieler/644401.
Transfer history data appended for: https://www.transfermarkt.com/jacob-greaves/profil/spieler/693095.
Transfer history data appended for: https://www.transfermarkt.com/regan-slater/profil/spieler/473080.
Transfer history data appended for: https://www.transfermarkt.com/brandon-fleming/profil/spieler/532078.
Transfer history data appended for: https://www.transfermarkt.com/callum-reilly/profil/spieler/212575.
Transfer history data appended for: https://www.transfermarkt.com/adam-roscrow/profil/spieler/456844.
Transfer history data appended for: https://www.transfermarkt.com/alex-woodyard/profil/spieler/148683.
Transfer history data appended for: https://www.transfermarkt.com/steve-seddon/profil/spieler/564049.
Transfer history data appended for: https://www.transfermarkt.com/connal-trueman/profil/spieler/344586.
Transfer history data appended for: https://www.transfermarkt.com/nesta-guinness-walker/profil/spieler/636908.
Transfer history data appended for: https://www.transfermarkt.com/jaakko-oksanen/profil/spieler/433893.
Transfer history data appended for: https://www.transfermarkt.com/anthony-hartigan/profil/spieler/491741.
Transfer history data appended for: https://www.transfermarkt.com/ben-heneghan/profil/spieler/156939.
Transfer history data appended for: https://www.transfermarkt.com/jack-madelin/profil/spieler/551010.
Transfer history data appended for: https://www.transfermarkt.com/ethan-chislett/profil/spieler/636911.
Transfer history data appended for: https://www.transfermarkt.com/ollie-palmer/profil/spieler/282256.
Transfer history data appended for: https://www.transfermarkt.com/ryan-longman/profil/spieler/512175.
Transfer history data appended for: https://www.transfermarkt.com/paul-kalambayi/profil/spieler/426926.
Transfer history data appended for: https://www.transfermarkt.com/terell-thomas/profil/spieler/343022.
Transfer history data appended for: https://www.transfermarkt.com/luke-oneill/profil/spieler/93321.
Transfer history data appended for: https://www.transfermarkt.com/shane-mcloughlin/profil/spieler/376252.
Transfer history data appended for: https://www.transfermarkt.com/zach-robinson/profil/spieler/727132.
Transfer history data appended for: https://www.transfermarkt.com/cheye-alexander/profil/spieler/222732.
Transfer history data appended for: https://www.transfermarkt.com/daniel-csoka/profil/spieler/451273.
Transfer history data appended for: https://www.transfermarkt.com/jack-rudoni/profil/spieler/662476.
Transfer history data appended for: https://www.transfermarkt.com/archie-procter/profil/spieler/727041.
Transfer history data appended for: https://www.transfermarkt.com/joe-pigott/profil/spieler/251831.
Transfer history data appended for: https://www.transfermarkt.com/ayoub-assal/profil/spieler/727129.
Transfer history data appended for: https://www.transfermarkt.com/nikola-tzanev/profil/spieler/363901.
Transfer history data appended for: https://www.transfermarkt.com/jamil-awoyejo/profil/spieler/727130.
Transfer history data appended for: https://www.transfermarkt.com/will-nightingale/profil/spieler/307823.
Transfer history data appended for: https://www.transfermarkt.com/jonah-ayunga/profil/spieler/420777.
Transfer history data appended for: https://www.transfermarkt.com/alex-rodman/profil/spieler/105599.
Transfer history data appended for: https://www.transfermarkt.com/sam-nicholson/profil/spieler/169573.

Transfer history data appended for: https://www.transfermarkt.com/michael-kelly/profil/spieler/193875.
Transfer history data appended for: https://www.transfermarkt.com/david-tutonda/profil/spieler/357333.
Transfer history data appended for: https://www.transfermarkt.com/luke-mccormick/profil/spieler/396858.
Transfer history data appended for: https://www.transfermarkt.com/alfie-kilgour/profil/spieler/396678.
Transfer history data appended for: https://www.transfermarkt.com/ben-liddle/profil/spieler/399436.
Transfer history data appended for: https://www.transfermarkt.com/josh-hare/profil/spieler/250336.
Transfer history data appended for: https://www.transfermarkt.com/erhun-oztumer/profil/spieler/326843.
Transfer history data appended for: https://www.transfermarkt.com/jayden-mitchell-lawson/profil/spieler/475455.
Transfer history data appended for: https://www.transfermarkt.com/josh-grant/profil/spieler/396860.
Transfer history data appended for: https://www.transfermarkt.com/james-daly/profil/spieler/577779.
Transfer history data appended for: https://www.transfermarkt.com/zain-westbrooke/profil/spieler/504904.
Transfer history data appended for: https://www.transfermarkt.com/josh-barrett/profil/spieler/325192.
Transfer history data appended for: https://www.transfermarkt.com/anssi-jaakkola/profil/spieler/18223.
Transfer history data appended for: https://www.transfermarkt.com/cameron-hargreaves/profil/spieler/533903.
Transfer history data appended for: https://www.transfermarkt.com/ed-upson/profil/spieler/54382.
Transfer history data appended for: https://www.transfermarkt.com/jack-baldwin/profil/spieler/195628.
Transfer history data appended for: https://www.transfermarkt.com/zain-walker/profil/spieler/633475.
Transfer history data appended for: https://www.transfermarkt.com/cian-harries/profil/spieler/319300.
Transfer history data appended for: https://www.transfermarkt.com/ali-koiki/profil/spieler/641441.
Transfer history data appended for: https://www.transfermarkt.com/luke-leahy/profil/spieler/227315.
Transfer history data appended for: https://www.transfermarkt.com/mark-little/profil/spieler/41099.
Transfer history data appended for: https://www.transfermarkt.com/brandon-hanlan/profil/spieler/451736.
Transfer history data appended for: https://www.transfermarkt.com/alexis-andre/profil/spieler/468052.
Transfer history data appended for: https://www.transfermarkt.com/max-ehmer/profil/spieler/158718.
Transfer history data appended for: https://www.transfermarkt.com/tom-davies/profil/spieler/316776.
Transfer history data appended for: https://www.transfermarkt.com/jordi-van-stappershoef/profil/spieler/330995.
Transfer history data appended for: https://www.transfermarkt.com/sam-hoskins/profil/spieler/198861.
Transfer history data appended for: https://www.transfermarkt.com/christopher-missilou/profil/spieler/111052.
Transfer history data appended for: https://www.transfermarkt.com/danny-rose/profil/spieler/185702.
Transfer history data appended for: https://www.transfermarkt.com/michael-harriman/profil/spieler/155233.
Transfer history data appended for: https://www.transfermarkt.com/nicky-adams/profil/spieler/63222.
Transfer history data appended for: https://www.transfermarkt.com/joe-nuttall/profil/spieler/277069.
Transfer history data appended for: https://www.transfermarkt.com/fraser-horsfall/profil/spieler/525867.
Transfer history data appended for: https://www.transfermarkt.com/jacob-ballinger/profil/spieler/744496.
Transfer history data appended for: https://www.transfermarkt.com/shaun-mcwilliams/profil/spieler/359204.
Transfer history data appended for: https://www.transfermarkt.com/ricky-korboa/profil/spieler/723350.
Transfer history data appended for: https://www.transfermarkt.com/ricky-holmes/profil/spieler/156899.
Transfer history data appended for: https://www.transfermarkt.com/mark-marshall/profil/spieler/92250.
Transfer history data appended for: https://www.transfermarkt.com/steve-arnold/profil/spieler/22206.
Transfer history data appended for: https://www.transfermarkt.com/scott-pollock/profil/spieler/622792.
Transfer history data appended for: https://www.transfermarkt.com/max-dyche/profil/spieler/816002.
Transfer history data appended for: https://www.transfermarkt.com/morgan-roberts/profil/spieler/579771.
Transfer history data appended for: https://www.transfermarkt.com/ryan-watson/profil/spieler/121269.
Transfer history data appended for: https://www.transfermarkt.com/alan-sheehan/profil/spieler/34347.
Transfer history data appended for: https://www.transfermarkt.com/cian-bolger/profil/spieler/130478.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-mitchell/profil/spieler/205326.
Transfer history data appended for: https://www.transfermarkt.com/caleb-chukwuemeka/profil/spieler/742746.
Transfer history data appended for: https://www.transfermarkt.com/ethan-johnston/profil/spieler/744497.
Transfer history data appended for: https://www.transfermarkt.com/jack-sowerby/profil/spieler/346780.
Transfer history data appended for: https://www.transfermarkt.com/joe-martin/profil/spieler/61833.
Transfer history data appended for: https://www.transfermarkt.com/chris-lines/profil/spieler/49748.
Transfer history data appended for: https://www.transfermarkt.com/harry-smith/profil/spieler/452019.
Transfer history data appended for: https://www.transfermarkt.com/benny-ashley-seal/profil/spieler/322089.
Transfer history data appended for: https://www.transfermarkt.com/luka-racic/profil/spieler/345587.
Transfer history data appended for: https://www.transfermarkt.com/joseph-mills/profil/spieler/81876.
Transfer history data appended for: https://www.transfermarkt.com/ben-blythe/profil/spieler/805915.
Transfer history data appended for: https://www.transfermarkt.com/andy-butler/profil/spieler/49532.
Transfer history data appended for: https://www.transfermarkt.com/branden-horton/profil/spieler/550218.
Transfer history data appended for: https://www.transfermarkt.com/tyreece-john-jules/profil/spieler/503768.
Transfer history data appended for: https://www.transfermarkt.com/fejiri-okenabirhie/profil/spieler/312114.
Transfer history data appended for: https://www.transfermarkt.com/matt-smith/profil/spieler/365877.
Transfer history data appended for: https://www.transfermarkt.com/ben-whiteman/profil/spieler/347389.
Transfer history data appended for: https://www.transfermarkt.com/jason-lokilo/profil/spieler/325200.
Transfer history data appended for: https://www.transfermarkt.com/rayhaan-tulloch/profil/spieler/433184.
Transfer history data appended for: https://www.transfermarkt.com/james-coppinger/profil/spieler/48959.
Transfer history data appended for: https://www.transfermarkt.com/lirak-hasani/profil/spieler/662539.
Transfer history data appended for: https://www.transfermarkt.com/josh-sims/profil/spieler/286919.
Transfer history data appended for: https://www.transfermarkt.com/joe-wright/profil/spieler/356396.
Transfer history data appended for: https://www.transfermarkt.com/taylor-richards/profil/spieler/484551.
Transfer history data appended for: https://www.transfermarkt.com/louis-jones/profil/spieler/428366.
Transfer history data appended for: https://www.transfermarkt.com/cameron-john/profil/spieler/425894.
Transfer history data appended for: https://www.transfermarkt.com/ed-williams/profil/spieler/269453.
Transfer history data appended for: https://www.transfermarkt.com/brad-halliday/profil/spieler/282240.
Transfer history data appended for: https://www.transfermarkt.com/tom-anderson/profil/spieler/128828.
Transfer history data appended for: https://www.transfermarkt.com/anthony-greaves/profil/spieler/624944.
Transfer history data appended for: https://www.transfermarkt.com/danny-amos/profil/spieler/455602.
Transfer history data appended for: https://www.transfermarkt.com/jon-taylor/profil/spieler/137589.
Transfer history data appended for: https://www.transfermarkt.com/reece-james/profil/spieler/245585.
Transfer history data appended for: https://www.transfermarkt.com/madger-gomes/profil/spieler/297661.
Transfer history data appended for: https://www.transfermarkt.com/glenn-whelan/profil/spieler/12124.

Transfer history data appended for: https://www.transfermarkt.com/sam-finley/profil/spieler/217806.
Transfer history data appended for: https://www.transfermarkt.com/jordan-rossiter/profil/spieler/258924.
Transfer history data appended for: https://www.transfermarkt.com/szymon-czajor/profil/spieler/538346.
Transfer history data appended for: https://www.transfermarkt.com/paul-coutts/profil/spieler/93055.
Transfer history data appended for: https://www.transfermarkt.com/danny-andrew/profil/spieler/95245.
Transfer history data appended for: https://www.transfermarkt.com/joel-coleman/profil/spieler/285551.
Transfer history data appended for: https://www.transfermarkt.com/mark-duffy/profil/spieler/105565.
Transfer history data appended for: https://www.transfermarkt.com/ched-evans/profil/spieler/61622.
Transfer history data appended for: https://www.transfermarkt.com/ryan-rydel/profil/spieler/618885.
Transfer history data appended for: https://www.transfermarkt.com/callum-camps/profil/spieler/265577.
Transfer history data appended for: https://www.transfermarkt.com/harvey-saunders/profil/spieler/482999.
Transfer history data appended for: https://www.transfermarkt.com/paddy-madden/profil/spieler/92488.
Transfer history data appended for: https://www.transfermarkt.com/charlie-mulgrew/profil/spieler/37428.
Transfer history data appended for: https://www.transfermarkt.com/alex-cairns/profil/spieler/194386.
Transfer history data appended for: https://www.transfermarkt.com/barrie-mckay/profil/spieler/208934.
Transfer history data appended for: https://www.transfermarkt.com/callum-connolly/profil/spieler/308632.
Transfer history data appended for: https://www.transfermarkt.com/sam-stubbs/profil/spieler/425872.
Transfer history data appended for: https://www.transfermarkt.com/josh-morris/profil/spieler/121391.
Transfer history data appended for: https://www.transfermarkt.com/jayson-leutwiler/profil/spieler/52598.
Transfer history data appended for: https://www.transfermarkt.com/gerard-garner/profil/spieler/618883.
Transfer history data appended for: https://www.transfermarkt.com/tom-edwards/profil/spieler/430788.
Transfer history data appended for: https://www.transfermarkt.com/harrison-holgate/profil/spieler/624894.
Transfer history data appended for: https://www.transfermarkt.com/wes-burns/profil/spieler/255731.
Transfer history data appended for: https://www.transfermarkt.com/james-hill/profil/spieler/611793.
Transfer history data appended for: https://www.transfermarkt.com/morgan-boyes/profil/spieler/554250.
Transfer history data appended for: https://www.transfermarkt.com/joel-cooper/profil/spieler/386936.
Transfer history data appended for: https://www.transfermarkt.com/josh-ruffels/profil/spieler/176632.
Transfer history data appended for: https://www.transfermarkt.com/sam-winnall/profil/spieler/145493.
Transfer history data appended for: https://www.transfermarkt.com/marcus-mcguane/profil/spieler/340320.
Transfer history data appended for: https://www.transfermarkt.com/elliott-moore/profil/spieler/341993.
Transfer history data appended for: https://www.transfermarkt.com/john-mousinho/profil/spieler/48371.
Transfer history data appended for: https://www.transfermarkt.com/simon-eastwood/profil/spieler/49089.
Transfer history data appended for: https://www.transfermarkt.com/matty-taylor/profil/spieler/67237.
Transfer history data appended for: https://www.transfermarkt.com/liam-kelly/profil/spieler/252986.
Transfer history data appended for: https://www.transfermarkt.com/alex-gorrin/profil/spieler/197825.
Transfer history data appended for: https://www.transfermarkt.com/cameron-brannagan/profil/spieler/261357.
Transfer history data appended for: https://www.transfermarkt.com/sam-long/profil/spieler/238591.
Transfer history data appended for: https://www.transfermarkt.com/anthony-forde/profil/spieler/146494.
Transfer history data appended for: https://www.transfermarkt.com/derick-osei-yaw/profil/spieler/471243.
Transfer history data appended for: https://www.transfermarkt.com/sean-clare/profil/spieler/425456.
Transfer history data appended for: https://www.transfermarkt.com/jack-stevens/profil/spieler/337101.
Transfer history data appended for: https://www.transfermarkt.com/olamide-shodipo/profil/spieler/401268.
Transfer history data appended for: https://www.transfermarkt.com/rob-hall/profil/spieler/121236.
Transfer history data appended for: https://www.transfermarkt.com/robert-atkinson/profil/spieler/531783.
Transfer history data appended for: https://www.transfermarkt.com/dan-agyei/profil/spieler/367195.
Transfer history data appended for: https://www.transfermarkt.com/james-henry/profil/spieler/59268.
Transfer history data appended for: https://www.transfermarkt.com/jordan-obita/profil/spieler/158816.
Transfer history data appended for: https://www.transfermarkt.com/mark-sykes/profil/spieler/320403.
Transfer history data appended for: https://www.transfermarkt.com/malachi-napa/profil/spieler/526619.
Transfer history data appended for: https://www.transfermarkt.com/jamie-hanson/profil/spieler/259495.
Transfer history data appended for: https://www.transfermarkt.com/dylan-asonganyi/profil/spieler/543074.
Transfer history data appended for: https://www.transfermarkt.com/gwion-edwards/profil/spieler/192766.
Transfer history data appended for: https://www.transfermarkt.com/myles-kenlock/profil/spieler/387391.
Transfer history data appended for: https://www.transfermarkt.com/freddie-sears/profil/spieler/70714.
Transfer history data appended for: https://www.transfermarkt.com/alan-judge/profil/spieler/42249.
Transfer history data appended for: https://www.transfermarkt.com/flynn-downes/profil/spieler/506189.
Transfer history data appended for: https://www.transfermarkt.com/harry-wright/profil/spieler/659489.
Transfer history data appended for: https://www.transfermarkt.com/david-cornell/profil/spieler/89648.
Transfer history data appended for: https://www.transfermarkt.com/janoi-donacien/profil/spieler/197791.
Transfer history data appended for: https://www.transfermarkt.com/jon-nolan/profil/spieler/121264.
Transfer history data appended for: https://www.transfermarkt.com/toto-nsiala/profil/spieler/121265.
Transfer history data appended for: https://www.transfermarkt.com/james-norwood/profil/spieler/123198.
Transfer history data appended for: https://www.transfermarkt.com/mark-mcguinness/profil/spieler/561454.
Transfer history data appended for: https://www.transfermarkt.com/armando-dobra/profil/spieler/664581.
Transfer history data appended for: https://www.transfermarkt.com/oliver-hawkins/profil/spieler/346181.
Transfer history data appended for: https://www.transfermarkt.com/stephen-ward/profil/spieler/34691.
Transfer history data appended for: https://www.transfermarkt.com/andre-dozzell/profil/spieler/346467.
Transfer history data appended for: https://www.transfermarkt.com/aaron-drinan/profil/spieler/466106.
Transfer history data appended for: https://www.transfermarkt.com/tristan-nydam/profil/spieler/483545.
Transfer history data appended for: https://www.transfermarkt.com/kayden-jackson/profil/spieler/378872.
Transfer history data appended for: https://www.transfermarkt.com/jack-lankester/profil/spieler/602544.
Transfer history data appended for: https://www.transfermarkt.com/luke-woolfenden/profil/spieler/527425.
Transfer history data appended for: https://www.transfermarkt.com/keanan-bennetts/profil/spieler/321096.
Transfer history data appended for: https://www.transfermarkt.com/kane-vincent-young/profil/spieler/350232.
Transfer history data appended for: https://www.transfermarkt.com/corrie-ndaba/profil/spieler/433329.
Transfer history data appended for: https://www.transfermarkt.com/cole-skuse/profil/spieler/48094.
Transfer history data appended for: https://www.transfermarkt.com/teddy-bishop/profil/spieler/276266.
Transfer history data appended for: https://www.transfermarkt.com/luke-chambers/profil/spieler/49380.
Transfer history data appended for: https://www.transfermarkt.com/tomas-holy/profil/spieler/123672.
Transfer history data appended for: https://www.transfermarkt.com/emyr-huws/profil/spieler/121474.
Transfer history data appended for: https://www.transfermarkt.com/james-wilson/profil/spieler/48098.

Transfer history data appended for: https://www.transfermarkt.com/tyreece-onyeka/profil/spieler/673367.
Transfer history data appended for: https://www.transfermarkt.com/will-jaaskelainen/profil/spieler/328651.
Transfer history data appended for: https://www.transfermarkt.com/travis-johnson/profil/spieler/583888.
Transfer history data appended for: https://www.transfermarkt.com/daniel-powell/profil/spieler/92986.
Transfer history data appended for: https://www.transfermarkt.com/charlie-kirk/profil/spieler/421443.
Transfer history data appended for: https://www.transfermarkt.com/dave-richards/profil/spieler/238479.
Transfer history data appended for: https://www.transfermarkt.com/eddie-nolan/profil/spieler/47601.
Transfer history data appended for: https://www.transfermarkt.com/harry-pickering/profil/spieler/426412.
Transfer history data appended for: https://www.transfermarkt.com/nathan-woodthorpe/profil/spieler/673375.
Transfer history data appended for: https://www.transfermarkt.com/josh-lundstram/profil/spieler/505693.
Transfer history data appended for: https://www.transfermarkt.com/luke-offord/profil/spieler/553509.
Transfer history data appended for: https://www.transfermarkt.com/olly-lancashire/profil/spieler/60995.
Transfer history data appended for: https://www.transfermarkt.com/donervon-daniels/profil/spieler/199522.
Transfer history data appended for: https://www.transfermarkt.com/owen-dale/profil/spieler/485252.
Transfer history data appended for: https://www.transfermarkt.com/chris-porter/profil/spieler/49434.
Transfer history data appended for: https://www.transfermarkt.com/sam-booth/profil/spieler/673363.
Transfer history data appended for: https://www.transfermarkt.com/perry-ng/profil/spieler/322677.
Transfer history data appended for: https://www.transfermarkt.com/joe-robbins/profil/spieler/673369.
Transfer history data appended for: https://www.transfermarkt.com/billy-sass-davies/profil/spieler/526874.
Transfer history data appended for: https://www.transfermarkt.com/omar-beckles/profil/spieler/136580.
Transfer history data appended for: https://www.transfermarkt.com/oli-finney/profil/spieler/425590.
Transfer history data appended for: https://www.transfermarkt.com/regan-griffiths/profil/spieler/583863.
Transfer history data appended for: https://www.transfermarkt.com/callum-ainley/profil/spieler/393564.
Transfer history data appended for: https://www.transfermarkt.com/mikael-mandron/profil/spieler/218144.
Transfer history data appended for: https://www.transfermarkt.com/rio-adebisi/profil/spieler/671975.
Transfer history data appended for: https://www.transfermarkt.com/ryan-wintle/profil/spieler/386752.
Transfer history data appended for: https://www.transfermarkt.com/luke-murphy/profil/spieler/91307.
Transfer history data appended for: https://www.transfermarkt.com/tom-lowery/profil/spieler/426414.
Transfer history data appended for: https://www.transfermarkt.com/offrande-zanzala/profil/spieler/337796.
Transfer history data appended for: https://www.transfermarkt.com/ashley-maynard-brewer/profil/spieler/497143.
Transfer history data appended for: https://www.transfermarkt.com/chris-gunter/profil/spieler/43853.
Transfer history data appended for: https://www.transfermarkt.com/akin-famewo/profil/spieler/425713.
Transfer history data appended for: https://www.transfermarkt.com/jake-forster-caskey/profil/spieler/148151.
Transfer history data appended for: https://www.transfermarkt.com/charlie-barker/profil/spieler/747258.
Transfer history data appended for: https://www.transfermarkt.com/jason-pearce/profil/spieler/45823.
Transfer history data appended for: https://www.transfermarkt.com/albie-morgan/profil/spieler/606026.
Transfer history data appended for: https://www.transfermarkt.com/adedeji-oshilaja/profil/spieler/195679.
Transfer history data appended for: https://www.transfermarkt.com/ryan-inniss/profil/spieler/183284.
Transfer history data appended for: https://www.transfermarkt.com/paul-smyth/profil/spieler/408872.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-williams/profil/spieler/170322.
Transfer history data appended for: https://www.transfermarkt.com/dylan-levitt/profil/spieler/496652.
Transfer history data appended for: https://www.transfermarkt.com/ben-purrington/profil/spieler/270988.
Transfer history data appended for: https://www.transfermarkt.com/darren-pratley/profil/spieler/28957.
Transfer history data appended for: https://www.transfermarkt.com/alfie-doughty/profil/spieler/608175.
Transfer history data appended for: https://www.transfermarkt.com/omar-bogle/profil/spieler/134657.
Transfer history data appended for: https://www.transfermarkt.com/chuks-aneke/profil/spieler/122694.
Transfer history data appended for: https://www.transfermarkt.com/ben-amos/profil/spieler/73472.
Transfer history data appended for: https://www.transfermarkt.com/adam-matthews/profil/spieler/108878.
Transfer history data appended for: https://www.transfermarkt.com/ian-maatsen/profil/spieler/485585.
Transfer history data appended for: https://www.transfermarkt.com/conor-washington/profil/spieler/249815.
Transfer history data appended for: https://www.transfermarkt.com/alex-gilbey/profil/spieler/238440.
Transfer history data appended for: https://www.transfermarkt.com/marcus-maddison/profil/spieler/221561.
Transfer history data appended for: https://www.transfermarkt.com/ben-watson/profil/spieler/14081.
Transfer history data appended for: https://www.transfermarkt.com/andrew-shinnie/profil/spieler/51733.
Transfer history data appended for: https://www.transfermarkt.com/colin-daniel/profil/spieler/91291.
Transfer history data appended for: https://www.transfermarkt.com/jevan-anderson/profil/spieler/564484.
Transfer history data appended for: https://www.transfermarkt.com/reece-hutchinson/profil/spieler/578937.
Transfer history data appended for: https://www.transfermarkt.com/luke-varney/profil/spieler/14177.
Transfer history data appended for: https://www.transfermarkt.com/niall-ennis/profil/spieler/369171.
Transfer history data appended for: https://www.transfermarkt.com/kieran-ohara/profil/spieler/289791.
Transfer history data appended for: https://www.transfermarkt.com/ryan-edwards/profil/spieler/192360.
Transfer history data appended for: https://www.transfermarkt.com/lucas-akins/profil/spieler/63199.
Transfer history data appended for: https://www.transfermarkt.com/teddy-sharman-lowe/profil/spieler/731466.
Transfer history data appended for: https://www.transfermarkt.com/ben-hart/profil/spieler/624961.
Transfer history data appended for: https://www.transfermarkt.com/indiana-vassilev/profil/spieler/469860.
Transfer history data appended for: https://www.transfermarkt.com/jake-buxton/profil/spieler/48723.
Transfer history data appended for: https://www.transfermarkt.com/john-brayford/profil/spieler/91286.
Transfer history data appended for: https://www.transfermarkt.com/kane-hemmings/profil/spieler/106641.
Transfer history data appended for: https://www.transfermarkt.com/stephen-quinn/profil/spieler/43266.
Transfer history data appended for: https://www.transfermarkt.com/owen-gallacher/profil/spieler/344587.
Transfer history data appended for: https://www.transfermarkt.com/ben-garratt/profil/spieler/158342.
Transfer history data appended for: https://www.transfermarkt.com/neal-eardley/profil/spieler/49428.
Transfer history data appended for: https://www.transfermarkt.com/michael-bostwick/profil/spieler/69755.
Transfer history data appended for: https://www.transfermarkt.com/joe-powell/profil/spieler/354134.
Transfer history data appended for: https://www.transfermarkt.com/steven-lawless/profil/spieler/106644.
Transfer history data appended for: https://www.transfermarkt.com/kieran-wallace/profil/spieler/183295.
Transfer history data appended for: https://www.transfermarkt.com/callum-hawkins/profil/spieler/602307.
Transfer history data appended for: https://www.transfermarkt.com/charles-vernam/profil/spieler/335181.
Transfer history data appended for: https://www.transfermarkt.com/john-joe-otoole/profil/spieler/57053.
Transfer history data appended for: https://www.transfermarkt.com/sam-hughes/profil/spieler/395797.

Transfer history data appended for: https://www.transfermarkt.com/jack-roles/profil/spieler/431425.
Transfer history data appended for: https://www.transfermarkt.com/ben-fox/profil/spieler/452708.
Transfer history data appended for: https://www.transfermarkt.com/chris-beardsley/profil/spieler/15975.
Transfer history data appended for: https://www.transfermarkt.com/lee-nicholls/profil/spieler/126258.
Transfer history data appended for: https://www.transfermarkt.com/scott-fraser/profil/spieler/193079.
Transfer history data appended for: https://www.transfermarkt.com/baily-cargill/profil/spieler/293450.
Transfer history data appended for: https://www.transfermarkt.com/dean-lewington/profil/spieler/14043.
Transfer history data appended for: https://www.transfermarkt.com/daniel-harvie/profil/spieler/293729.
Transfer history data appended for: https://www.transfermarkt.com/jordan-houghton/profil/spieler/186927.
Transfer history data appended for: https://www.transfermarkt.com/lasse-sorensen/profil/spieler/357967.
Transfer history data appended for: https://www.transfermarkt.com/kieran-agard/profil/spieler/57066.
Transfer history data appended for: https://www.transfermarkt.com/joe-mason/profil/spieler/120706.
Transfer history data appended for: https://www.transfermarkt.com/george-williams/profil/spieler/346244.
Transfer history data appended for: https://www.transfermarkt.com/cameron-jerome/profil/spieler/35855.
Transfer history data appended for: https://www.transfermarkt.com/andy-fisher/profil/spieler/359199.
Transfer history data appended for: https://www.transfermarkt.com/carlton-morris/profil/spieler/246963.
Transfer history data appended for: https://www.transfermarkt.com/ben-gladwin/profil/spieler/210986.
Transfer history data appended for: https://www.transfermarkt.com/laurie-walker/profil/spieler/125689.
Transfer history data appended for: https://www.transfermarkt.com/andrew-surman/profil/spieler/29975.
Transfer history data appended for: https://www.transfermarkt.com/regan-poole/profil/spieler/340194.
Transfer history data appended for: https://www.transfermarkt.com/louis-thompson/profil/spieler/207771.
Transfer history data appended for: https://www.transfermarkt.com/warren-ohora/profil/spieler/449020.
Transfer history data appended for: https://www.transfermarkt.com/david-kasumu/profil/spieler/433837.
Transfer history data appended for: https://www.transfermarkt.com/john-freeman/profil/spieler/727594.
Transfer history data appended for: https://www.transfermarkt.com/richard-keogh/profil/spieler/47983.
Transfer history data appended for: https://www.transfermarkt.com/stephen-walker/profil/spieler/486001.
Transfer history data appended for: https://www.transfermarkt.com/jay-bird/profil/spieler/543075.
Transfer history data appended for: https://www.transfermarkt.com/matthew-sorinola/profil/spieler/690478.
Transfer history data appended for: https://www.transfermarkt.com/will-grigg/profil/spieler/106676.
Transfer history data appended for: https://www.transfermarkt.com/remi-matthews/profil/spieler/196722.
Transfer history data appended for: https://www.transfermarkt.com/lynden-gooch/profil/spieler/307781.
Transfer history data appended for: https://www.transfermarkt.com/arbenit-xhemajli/profil/spieler/354155.
Transfer history data appended for: https://www.transfermarkt.com/dion-sanderson/profil/spieler/495993.
Transfer history data appended for: https://www.transfermarkt.com/jack-diamond/profil/spieler/484385.
Transfer history data appended for: https://www.transfermarkt.com/bailey-wright/profil/spieler/147419.
Transfer history data appended for: https://www.transfermarkt.com/tom-flanagan/profil/spieler/125786.
Transfer history data appended for: https://www.transfermarkt.com/callum-mcfadzean/profil/spieler/134422.
Transfer history data appended for: https://www.transfermarkt.com/grant-leadbitter/profil/spieler/13796.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-mbunga-kimpioka/profil/spieler/433652.
Transfer history data appended for: https://www.transfermarkt.com/josh-scowen/profil/spieler/182842.
Transfer history data appended for: https://www.transfermarkt.com/luke-onien/profil/spieler/282939.
Transfer history data appended for: https://www.transfermarkt.com/morgan-feeney/profil/spieler/399373.
Transfer history data appended for: https://www.transfermarkt.com/conor-mclaughlin/profil/spieler/128419.
Transfer history data appended for: https://www.transfermarkt.com/elliot-embleton/profil/spieler/364828.
Transfer history data appended for: https://www.transfermarkt.com/chris-maguire/profil/spieler/36633.
Transfer history data appended for: https://www.transfermarkt.com/aiden-obrien/profil/spieler/148908.
Transfer history data appended for: https://www.transfermarkt.com/lee-burge/profil/spieler/181007.
Transfer history data appended for: https://www.transfermarkt.com/aiden-mcgeady/profil/spieler/21333.
Transfer history data appended for: https://www.transfermarkt.com/danny-graham/profil/spieler/29152.
Transfer history data appended for: https://www.transfermarkt.com/max-power/profil/spieler/158534.
Transfer history data appended for: https://www.transfermarkt.com/charlie-wyke/profil/spieler/163535.
Transfer history data appended for: https://www.transfermarkt.com/george-dobson/profil/spieler/292734.
Transfer history data appended for: https://www.transfermarkt.com/denver-hume/profil/spieler/423617.
Transfer history data appended for: https://www.transfermarkt.com/jordan-willis/profil/spieler/207056.
Transfer history data appended for: https://www.transfermarkt.com/jordan-graham/profil/spieler/183283.
Transfer history data appended for: https://www.transfermarkt.com/thomas-oconnor/profil/spieler/357661.
Transfer history data appended for: https://www.transfermarkt.com/dominic-samuel/profil/spieler/203784.
Transfer history data appended for: https://www.transfermarkt.com/robbie-mckenzie/profil/spieler/532079.
Transfer history data appended for: https://www.transfermarkt.com/alex-macdonald/profil/spieler/73033.
Transfer history data appended for: https://www.transfermarkt.com/jack-bonham/profil/spieler/209291.
Transfer history data appended for: https://www.transfermarkt.com/joe-walsh/profil/spieler/690548.
Transfer history data appended for: https://www.transfermarkt.com/henry-woods/profil/spieler/614152.
Transfer history data appended for: https://www.transfermarkt.com/kyle-dempsey/profil/spieler/308388.
Transfer history data appended for: https://www.transfermarkt.com/declan-drysdale/profil/spieler/504943.
Transfer history data appended for: https://www.transfermarkt.com/matty-willock/profil/spieler/289845.
Transfer history data appended for: https://www.transfermarkt.com/vadaine-oliver/profil/spieler/141905.
Transfer history data appended for: https://www.transfermarkt.com/zech-medley/profil/spieler/392761.
Transfer history data appended for: https://www.transfermarkt.com/christian-maghoma/profil/spieler/258921.
Transfer history data appended for: https://www.transfermarkt.com/scott-robertson/profil/spieler/536533.
Transfer history data appended for: https://www.transfermarkt.com/josh-eccles/profil/spieler/618903.
Transfer history data appended for: https://www.transfermarkt.com/jack-tucker/profil/spieler/542516.
Transfer history data appended for: https://www.transfermarkt.com/ryan-jackson/profil/spieler/169627.
Transfer history data appended for: https://www.transfermarkt.com/john-akinde/profil/spieler/69749.
Transfer history data appended for: https://www.transfermarkt.com/connor-ogilvie/profil/spieler/236509.
Transfer history data appended for: https://www.transfermarkt.com/jacob-mellis/profil/spieler/50379.
Transfer history data appended for: https://www.transfermarkt.com/trae-coyle/profil/spieler/433254.
Transfer history data appended for: https://www.transfermarkt.com/stuart-okeefe/profil/spieler/93626.
Transfer history data appended for: https://www.transfermarkt.com/thelo-aasgaard/profil/spieler/647384.
Transfer history data appended for: https://www.transfermarkt.com/patrick-webber/profil/spieler/441638.
Transfer history data appended for: https://www.transfermarkt.com/alex-perry/profil/spieler/335722.

Transfer history data appended for: https://www.transfermarkt.com/kyle-joseph/profil/spieler/647395.
Transfer history data appended for: https://www.transfermarkt.com/will-keane/profil/spieler/118535.
Transfer history data appended for: https://www.transfermarkt.com/scott-smith/profil/spieler/647392.
Transfer history data appended for: https://www.transfermarkt.com/luke-robinson/profil/spieler/647376.
Transfer history data appended for: https://www.transfermarkt.com/chris-merrie/profil/spieler/425879.
Transfer history data appended for: https://www.transfermarkt.com/jamie-jones/profil/spieler/57057.
Transfer history data appended for: https://www.transfermarkt.com/joe-piggott/profil/spieler/535054.
Transfer history data appended for: https://www.transfermarkt.com/owen-evans/profil/spieler/300908.
Transfer history data appended for: https://www.transfermarkt.com/emeka-obi/profil/spieler/458728.
Transfer history data appended for: https://www.transfermarkt.com/charlie-jolley/profil/spieler/647393.
Transfer history data appended for: https://www.transfermarkt.com/adam-long/profil/spieler/547936.
Transfer history data appended for: https://www.transfermarkt.com/curtis-tilt/profil/spieler/444571.
Transfer history data appended for: https://www.transfermarkt.com/sam-tickle/profil/spieler/647396.
Transfer history data appended for: https://www.transfermarkt.com/kal-naismith/profil/spieler/61011.
Transfer history data appended for: https://www.transfermarkt.com/viv-solomon-otabor/profil/spieler/391127.
Transfer history data appended for: https://www.transfermarkt.com/oliver-crankshaw/profil/spieler/426285.
Transfer history data appended for: https://www.transfermarkt.com/lee-evans/profil/spieler/221446.
Transfer history data appended for: https://www.transfermarkt.com/bobby-jones/profil/spieler/533476.
Transfer history data appended for: https://www.transfermarkt.com/tom-pearce/profil/spieler/530384.
Transfer history data appended for: https://www.transfermarkt.com/dan-gardner/profil/spieler/142365.
Transfer history data appended for: https://www.transfermarkt.com/matt-palmer/profil/spieler/236870.
Transfer history data appended for: https://www.transfermarkt.com/mackenzie-oneill/profil/spieler/659702.
Transfer history data appended for: https://www.transfermarkt.com/gavin-massey/profil/spieler/148258.
Transfer history data appended for: https://www.transfermarkt.com/darnell-johnson/profil/spieler/314372.
Transfer history data appended for: https://www.transfermarkt.com/sean-mcgurk/profil/spieler/746337.
Transfer history data appended for: https://www.transfermarkt.com/tom-james/profil/spieler/325105.
Transfer history data appended for: https://www.transfermarkt.com/divin-baningime/profil/spieler/547938.
Transfer history data appended for: https://www.transfermarkt.com/joe-garner/profil/spieler/46111.
Transfer history data appended for: https://www.transfermarkt.com/cameron-burgess/profil/spieler/255788.
Transfer history data appended for: https://www.transfermarkt.com/ross-sykes/profil/spieler/450958.
Transfer history data appended for: https://www.transfermarkt.com/ben-barclay/profil/spieler/335593.
Transfer history data appended for: https://www.transfermarkt.com/tariq-uwakwe/profil/spieler/396854.
Transfer history data appended for: https://www.transfermarkt.com/jon-russell/profil/spieler/505561.
Transfer history data appended for: https://www.transfermarkt.com/joe-maguire/profil/spieler/263556.
Transfer history data appended for: https://www.transfermarkt.com/michael-nottingham/profil/spieler/511622.
Transfer history data appended for: https://www.transfermarkt.com/nathan-baxter/profil/spieler/342050.
Transfer history data appended for: https://www.transfermarkt.com/sean-mcconville/profil/spieler/123334.
Transfer history data appended for: https://www.transfermarkt.com/ryan-cassidy/profil/spieler/562396.
Transfer history data appended for: https://www.transfermarkt.com/seamus-conneely/profil/spieler/70019.
Transfer history data appended for: https://www.transfermarkt.com/mark-hughes/profil/spieler/38121.
Transfer history data appended for: https://www.transfermarkt.com/harvey-rodgers/profil/spieler/459873.
Transfer history data appended for: https://www.transfermarkt.com/tom-allan/profil/spieler/484390.
Transfer history data appended for: https://www.transfermarkt.com/lamine-sherif/profil/spieler/399649.
Transfer history data appended for: https://www.transfermarkt.com/joe-pritchard/profil/spieler/314302.
Transfer history data appended for: https://www.transfermarkt.com/matt-butcher/profil/spieler/391132.
Transfer history data appended for: https://www.transfermarkt.com/harry-perritt/profil/spieler/644223.
Transfer history data appended for: https://www.transfermarkt.com/rhys-fenlon/profil/spieler/733423.
Transfer history data appended for: https://www.transfermarkt.com/stephen-sama/profil/spieler/86204.
Transfer history data appended for: https://www.transfermarkt.com/zehn-mohammed/profil/spieler/526643.
Transfer history data appended for: https://www.transfermarkt.com/dion-charles/profil/spieler/284320.
Transfer history data appended for: https://www.transfermarkt.com/toby-savin/profil/spieler/538871.
Transfer history data appended for: https://www.transfermarkt.com/lewis-mansell/profil/spieler/359195.
Transfer history data appended for: https://www.transfermarkt.com/tom-scully/profil/spieler/503728.
Transfer history data appended for: https://www.transfermarkt.com/mo-sangare/profil/spieler/505198.
Transfer history data appended for: https://www.transfermarkt.com/colby-bishop/profil/spieler/307069.
Transfer history data appended for: https://www.transfermarkt.com/ronan-curtis/profil/spieler/363882.
Transfer history data appended for: https://www.transfermarkt.com/marcus-harness/profil/spieler/288323.
Transfer history data appended for: https://www.transfermarkt.com/john-marquis/profil/spieler/130395.
Transfer history data appended for: https://www.transfermarkt.com/duncan-turnbull/profil/spieler/637703.
Transfer history data appended for: https://www.transfermarkt.com/ellis-harrison/profil/spieler/185109.
Transfer history data appended for: https://www.transfermarkt.com/bryn-morris/profil/spieler/236508.
Transfer history data appended for: https://www.transfermarkt.com/tom-naylor/profil/spieler/126225.
Transfer history data appended for: https://www.transfermarkt.com/lee-brown/profil/spieler/120697.
Transfer history data appended for: https://www.transfermarkt.com/suk-jae-lee/profil/spieler/837272.
Transfer history data appended for: https://www.transfermarkt.com/jack-whatmough/profil/spieler/237505.
Transfer history data appended for: https://www.transfermarkt.com/ben-close/profil/spieler/324117.
Transfer history data appended for: https://www.transfermarkt.com/sean-raggett/profil/spieler/226219.
Transfer history data appended for: https://www.transfermarkt.com/craig-macgillivray/profil/spieler/252617.
Transfer history data appended for: https://www.transfermarkt.com/michael-jacobs/profil/spieler/123384.
Transfer history data appended for: https://www.transfermarkt.com/harvey-rew/profil/spieler/633466.
Transfer history data appended for: https://www.transfermarkt.com/callum-johnson/profil/spieler/366834.
Transfer history data appended for: https://www.transfermarkt.com/ryan-williams/profil/spieler/192239.
Transfer history data appended for: https://www.transfermarkt.com/andy-cannon/profil/spieler/341882.
Transfer history data appended for: https://www.transfermarkt.com/cameron-pring/profil/spieler/547382.
Transfer history data appended for: https://www.transfermarkt.com/eoin-teggart/profil/spieler/641075.
Transfer history data appended for: https://www.transfermarkt.com/alex-bass/profil/spieler/334687.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-nicolaisen/profil/spieler/283227.
Transfer history data appended for: https://www.transfermarkt.com/jordy-hiwula/profil/spieler/201576.
Transfer history data appended for: https://www.transfermarkt.com/james-bolton/profil/spieler/208281.
Transfer history data appended for: https://www.transfermarkt.com/paul-downing/profil/spieler/113034.
Transfer history data appended for: https://www.transfermarkt.com/alex-palmer/profil/spieler/245625.

Transfer history data appended for: https://www.transfermarkt.com/lewis-montsma/profil/spieler/410477.
Transfer history data appended for: https://www.transfermarkt.com/adam-jackson/profil/spieler/134419.
Transfer history data appended for: https://www.transfermarkt.com/james-jones/profil/spieler/315968.
Transfer history data appended for: https://www.transfermarkt.com/remy-howarth/profil/spieler/411471.
Transfer history data appended for: https://www.transfermarkt.com/liam-bridcutt/profil/spieler/40612.
Transfer history data appended for: https://www.transfermarkt.com/timothy-eyoma/profil/spieler/406559.
Transfer history data appended for: https://www.transfermarkt.com/jamie-soule/profil/spieler/406636.
Transfer history data appended for: https://www.transfermarkt.com/conor-mcgrandles/profil/spieler/203127.
Transfer history data appended for: https://www.transfermarkt.com/jorge-grant/profil/spieler/334964.
Transfer history data appended for: https://www.transfermarkt.com/tayo-edun/profil/spieler/351502.
Transfer history data appended for: https://www.transfermarkt.com/zak-elbouzedi/profil/spieler/293779.
Transfer history data appended for: https://www.transfermarkt.com/anthony-scully/profil/spieler/325216.
Transfer history data appended for: https://www.transfermarkt.com/ethan-ross/profil/spieler/266030.
Transfer history data appended for: https://www.transfermarkt.com/tom-hopper/profil/spieler/184397.
Transfer history data appended for: https://www.transfermarkt.com/robbie-gotts/profil/spieler/534698.
Transfer history data appended for: https://www.transfermarkt.com/brennan-johnson/profil/spieler/470607.
Transfer history data appended for: https://www.transfermarkt.com/max-melbourne/profil/spieler/460255.
Transfer history data appended for: https://www.transfermarkt.com/theo-archibald/profil/spieler/293709.
Transfer history data appended for: https://www.transfermarkt.com/sean-roughan/profil/spieler/732748.
Transfer history data appended for: https://www.transfermarkt.com/harry-anderson/profil/spieler/335765.
Transfer history data appended for: https://www.transfermarkt.com/joe-walsh/profil/spieler/156559.
Transfer history data appended for: https://www.transfermarkt.com/callum-morton/profil/spieler/492690.
Transfer history data appended for: https://www.transfermarkt.com/mark-ellis/profil/spieler/52497.
Transfer history data appended for: https://www.transfermarkt.com/james-vaughan/profil/spieler/30471.
Transfer history data appended for: https://www.transfermarkt.com/liam-ridehalgh/profil/spieler/135043.
Transfer history data appended for: https://www.transfermarkt.com/jake-burton/profil/spieler/745167.
Transfer history data appended for: https://www.transfermarkt.com/lee-oconnor/profil/spieler/366681.
Transfer history data appended for: https://www.transfermarkt.com/kaiyne-woolery/profil/spieler/277135.
Transfer history data appended for: https://www.transfermarkt.com/joe-murphy/profil/spieler/3655.
Transfer history data appended for: https://www.transfermarkt.com/paul-lewis/profil/spieler/284931.
Transfer history data appended for: https://www.transfermarkt.com/jay-spearing/profil/spieler/52111.
Transfer history data appended for: https://www.transfermarkt.com/sam-smith/profil/spieler/424885.
Transfer history data appended for: https://www.transfermarkt.com/jack-young/profil/spieler/507235.
Transfer history data appended for: https://www.transfermarkt.com/manny-monthe/profil/spieler/319630.
Transfer history data appended for: https://www.transfermarkt.com/morgan-ferrier/profil/spieler/284736.
Transfer history data appended for: https://www.transfermarkt.com/calum-macdonald/profil/spieler/411504.
Transfer history data appended for: https://www.transfermarkt.com/danny-lloyd/profil/spieler/169568.
Transfer history data appended for: https://www.transfermarkt.com/danny-walker-rice/profil/spieler/580712.
Transfer history data appended for: https://www.transfermarkt.com/peter-clarke/profil/spieler/25201.
Transfer history data appended for: https://www.transfermarkt.com/george-ray/profil/spieler/192696.
Transfer history data appended for: https://www.transfermarkt.com/ollie-banks/profil/spieler/158702.
Transfer history data appended for: https://www.transfermarkt.com/liam-feeney/profil/spieler/70273.
Transfer history data appended for: https://www.transfermarkt.com/scott-davies/profil/spieler/67273.
Transfer history data appended for: https://www.transfermarkt.com/sid-nelson/profil/spieler/350401.
Transfer history data appended for: https://www.transfermarkt.com/kieron-morris/profil/spieler/251335.
Transfer history data appended for: https://www.transfermarkt.com/stefan-payne/profil/spieler/126587.
Transfer history data appended for: https://www.transfermarkt.com/kyle-hayde/profil/spieler/734080.
Transfer history data appended for: https://www.transfermarkt.com/otis-khan/profil/spieler/318799.
Transfer history data appended for: https://www.transfermarkt.com/george-nugent/profil/spieler/633411.
Transfer history data appended for: https://www.transfermarkt.com/corey-blackett-taylor/profil/spieler/282821.
Transfer history data appended for: https://www.transfermarkt.com/davis-keillor-dunn/profil/spieler/448672.
Transfer history data appended for: https://www.transfermarkt.com/andrea-badan/profil/spieler/373359.
Transfer history data appended for: https://www.transfermarkt.com/george-blackwood/profil/spieler/343050.
Transfer history data appended for: https://www.transfermarkt.com/jordan-barnett/profil/spieler/596966.
Transfer history data appended for: https://www.transfermarkt.com/dylan-bahamboula/profil/spieler/290928.
Transfer history data appended for: https://www.transfermarkt.com/danny-rowe/profil/spieler/191202.
Transfer history data appended for: https://www.transfermarkt.com/ben-garrity/profil/spieler/741948.
Transfer history data appended for: https://www.transfermarkt.com/tom-hamer/profil/spieler/533833.
Transfer history data appended for: https://www.transfermarkt.com/cameron-borthwick-jackson/profil/spieler/258879.
Transfer history data appended for: https://www.transfermarkt.com/sido-jombati/profil/spieler/191620.
Transfer history data appended for: https://www.transfermarkt.com/alfie-mccalmont/profil/spieler/471368.
Transfer history data appended for: https://www.transfermarkt.com/laurence-bilboe/profil/spieler/461439.
Transfer history data appended for: https://www.transfermarkt.com/carl-piergianni/profil/spieler/147623.
Transfer history data appended for: https://www.transfermarkt.com/zak-dearnley/profil/spieler/396284.
Transfer history data appended for: https://www.transfermarkt.com/conor-mcaleny/profil/spieler/121260.
Transfer history data appended for: https://www.transfermarkt.com/bobby-grant/profil/spieler/67359.
Transfer history data appended for: https://www.transfermarkt.com/kyle-jameson/profil/spieler/494684.
Transfer history data appended for: https://www.transfermarkt.com/brice-ntambwe/profil/spieler/110726.
Transfer history data appended for: https://www.transfermarkt.com/ian-lawlor/profil/spieler/183166.
Transfer history data appended for: https://www.transfermarkt.com/raphael-diarra/profil/spieler/290940.
Transfer history data appended for: https://www.transfermarkt.com/harry-clarke/profil/spieler/528892.
Transfer history data appended for: https://www.transfermarkt.com/callum-whelan/profil/spieler/396165.
Transfer history data appended for: https://www.transfermarkt.com/dylan-fage/profil/spieler/689977.
Transfer history data appended for: https://www.transfermarkt.com/james-perch/profil/spieler/49409.
Transfer history data appended for: https://www.transfermarkt.com/andy-cook/profil/spieler/133397.
Transfer history data appended for: https://www.transfermarkt.com/aaron-odriscoll/profil/spieler/325213.
Transfer history data appended for: https://www.transfermarkt.com/george-maris/profil/spieler/355489.
Transfer history data appended for: https://www.transfermarkt.com/rollin-menayese/profil/spieler/250750.
Transfer history data appended for: https://www.transfermarkt.com/ryan-sweeney/profil/spieler/347666.
Transfer history data appended for: https://www.transfermarkt.com/corey-okeeffe/profil/spieler/325214.
Transfer history data appended for: https://www.transfermarkt.com/ollie-clarke/profil/spieler/146542.

Transfer history data appended for: https://www.transfermarkt.com/farrend-rawson/profil/spieler/335177.
Transfer history data appended for: https://www.transfermarkt.com/kellan-gordon/profil/spieler/370138.
Transfer history data appended for: https://www.transfermarkt.com/harry-charsley/profil/spieler/264191.
Transfer history data appended for: https://www.transfermarkt.com/nicky-maynard/profil/spieler/39705.
Transfer history data appended for: https://www.transfermarkt.com/stephen-mclaughlin/profil/spieler/178067.
Transfer history data appended for: https://www.transfermarkt.com/james-clarke/profil/spieler/625407.
Transfer history data appended for: https://www.transfermarkt.com/joe-riley/profil/spieler/125117.
Transfer history data appended for: https://www.transfermarkt.com/jason-law/profil/spieler/433843.
Transfer history data appended for: https://www.transfermarkt.com/mal-benning/profil/spieler/210545.
Transfer history data appended for: https://www.transfermarkt.com/george-lapslie/profil/spieler/476149.
Transfer history data appended for: https://www.transfermarkt.com/jordan-bowery/profil/spieler/94655.
Transfer history data appended for: https://www.transfermarkt.com/aidan-stone/profil/spieler/681538.
Transfer history data appended for: https://www.transfermarkt.com/jamie-reid/profil/spieler/250840.
Transfer history data appended for: https://www.transfermarkt.com/marek-stech/profil/spieler/61589.
Transfer history data appended for: https://www.transfermarkt.com/alistair-smith/profil/spieler/631258.
Transfer history data appended for: https://www.transfermarkt.com/nathan-ferguson/profil/spieler/449454.
Transfer history data appended for: https://www.transfermarkt.com/jake-hesketh/profil/spieler/315185.
Transfer history data appended for: https://www.transfermarkt.com/tarryn-allarakhia/profil/spieler/602159.
Transfer history data appended for: https://www.transfermarkt.com/reece-grego-cox/profil/spieler/264199.
Transfer history data appended for: https://www.transfermarkt.com/george-francomb/profil/spieler/130755.
Transfer history data appended for: https://www.transfermarkt.com/jake-hessenthaler/profil/spieler/259652.
Transfer history data appended for: https://www.transfermarkt.com/tyler-frost/profil/spieler/424883.
Transfer history data appended for: https://www.transfermarkt.com/dannie-bulman/profil/spieler/104668.
Transfer history data appended for: https://www.transfermarkt.com/tom-dallison/profil/spieler/242607.
Transfer history data appended for: https://www.transfermarkt.com/tony-craig/profil/spieler/13562.
Transfer history data appended for: https://www.transfermarkt.com/brian-galach/profil/spieler/407735.
Transfer history data appended for: https://www.transfermarkt.com/joe-mcnerney/profil/spieler/104345.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-adebowale/profil/spieler/524700.
Transfer history data appended for: https://www.transfermarkt.com/david-sesay/profil/spieler/602158.
Transfer history data appended for: https://www.transfermarkt.com/nick-tsaroulla/profil/spieler/486288.
Transfer history data appended for: https://www.transfermarkt.com/glenn-morris/profil/spieler/48261.
Transfer history data appended for: https://www.transfermarkt.com/tom-nichols/profil/spieler/186597.
Transfer history data appended for: https://www.transfermarkt.com/alfie-jones/profil/spieler/580214.
Transfer history data appended for: https://www.transfermarkt.com/jordan-tunnicliffe/profil/spieler/199531.
Transfer history data appended for: https://www.transfermarkt.com/jack-powell/profil/spieler/204684.
Transfer history data appended for: https://www.transfermarkt.com/tom-mcgill/profil/spieler/406556.
Transfer history data appended for: https://www.transfermarkt.com/lewis-young/profil/spieler/86078.
Transfer history data appended for: https://www.transfermarkt.com/rafiq-khaleel/profil/spieler/809879.
Transfer history data appended for: https://www.transfermarkt.com/sam-ashford/profil/spieler/788703.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-german/profil/spieler/462708.
Transfer history data appended for: https://www.transfermarkt.com/sam-matthews/profil/spieler/282901.
Transfer history data appended for: https://www.transfermarkt.com/ashley-nadesan/profil/spieler/435752.
Transfer history data appended for: https://www.transfermarkt.com/josh-doherty/profil/spieler/167259.
Transfer history data appended for: https://www.transfermarkt.com/max-watters/profil/spieler/586023.
Transfer history data appended for: https://www.transfermarkt.com/archie-davies/profil/spieler/386201.
Transfer history data appended for: https://www.transfermarkt.com/stuart-nelson/profil/spieler/16170.
Transfer history data appended for: https://www.transfermarkt.com/alex-hurst/profil/spieler/690210.
Transfer history data appended for: https://www.transfermarkt.com/luke-joyce/profil/spieler/33786.
Transfer history data appended for: https://www.transfermarkt.com/theo-robinson/profil/spieler/39514.
Transfer history data appended for: https://www.transfermarkt.com/nathan-smith/profil/spieler/321416.
Transfer history data appended for: https://www.transfermarkt.com/leon-legge/profil/spieler/117994.
Transfer history data appended for: https://www.transfermarkt.com/scott-brown/profil/spieler/21703.
Transfer history data appended for: https://www.transfermarkt.com/ryan-campbell-gordon/profil/spieler/690207.
Transfer history data appended for: https://www.transfermarkt.com/devante-rodney/profil/spieler/483383.
Transfer history data appended for: https://www.transfermarkt.com/adam-crookes/profil/spieler/425896.
Transfer history data appended for: https://www.transfermarkt.com/david-worrall/profil/spieler/50742.
Transfer history data appended for: https://www.transfermarkt.com/tom-conlon/profil/spieler/294056.
Transfer history data appended for: https://www.transfermarkt.com/shaun-brisley/profil/spieler/77368.
Transfer history data appended for: https://www.transfermarkt.com/tom-pope/profil/spieler/48970.
Transfer history data appended for: https://www.transfermarkt.com/scott-burgess/profil/spieler/324112.
Transfer history data appended for: https://www.transfermarkt.com/zak-mills/profil/spieler/319381.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-oyeleke/profil/spieler/186598.
Transfer history data appended for: https://www.transfermarkt.com/dan-trickett-smith/profil/spieler/221765.
Transfer history data appended for: https://www.transfermarkt.com/david-amoo/profil/spieler/53302.
Transfer history data appended for: https://www.transfermarkt.com/harry-mckirdy/profil/spieler/291129.
Transfer history data appended for: https://www.transfermarkt.com/david-fitzpatrick/profil/spieler/284950.
Transfer history data appended for: https://www.transfermarkt.com/danny-whitehead/profil/spieler/181168.
Transfer history data appended for: https://www.transfermarkt.com/dino-visser/profil/spieler/139890.
Transfer history data appended for: https://www.transfermarkt.com/james-gibbons/profil/spieler/453678.
Transfer history data appended for: https://www.transfermarkt.com/cristian-montano/profil/spieler/87667.
Transfer history data appended for: https://www.transfermarkt.com/mark-cullen/profil/spieler/127802.
Transfer history data appended for: https://www.transfermarkt.com/mitchell-clark/profil/spieler/390693.
Transfer history data appended for: https://www.transfermarkt.com/miquel-scarlett/profil/spieler/550681.
Transfer history data appended for: https://www.transfermarkt.com/luke-norris/profil/spieler/186277.
Transfer history data appended for: https://www.transfermarkt.com/tom-eastman/profil/spieler/123371.
Transfer history data appended for: https://www.transfermarkt.com/shamal-george/profil/spieler/337290.
Transfer history data appended for: https://www.transfermarkt.com/joshua-bohui/profil/spieler/420812.
Transfer history data appended for: https://www.transfermarkt.com/callum-harriott/profil/spieler/170413.
Transfer history data appended for: https://www.transfermarkt.com/kwame-poku/profil/spieler/701062.
Transfer history data appended for: https://www.transfermarkt.com/ollie-kensdale/profil/spieler/574585.

Transfer history data appended for: https://www.transfermarkt.com/michael-folivi/profil/spieler/479939.
Transfer history data appended for: https://www.transfermarkt.com/omar-sowunmi/profil/spieler/344354.
Transfer history data appended for: https://www.transfermarkt.com/ryan-clampin/profil/spieler/614037.
Transfer history data appended for: https://www.transfermarkt.com/ben-stevenson/profil/spieler/375044.
Transfer history data appended for: https://www.transfermarkt.com/jevani-brown/profil/spieler/189751.
Transfer history data appended for: https://www.transfermarkt.com/luke-gambin/profil/spieler/225121.
Transfer history data appended for: https://www.transfermarkt.com/dean-gerken/profil/spieler/42055.
Transfer history data appended for: https://www.transfermarkt.com/harry-pell/profil/spieler/150759.
Transfer history data appended for: https://www.transfermarkt.com/cohen-bramall/profil/spieler/480191.
Transfer history data appended for: https://www.transfermarkt.com/miles-welch-hayes/profil/spieler/451991.
Transfer history data appended for: https://www.transfermarkt.com/tommy-smith/profil/spieler/54381.
Transfer history data appended for: https://www.transfermarkt.com/courtney-senior/profil/spieler/352633.
Transfer history data appended for: https://www.transfermarkt.com/tom-lapslie/profil/spieler/342556.
Transfer history data appended for: https://www.transfermarkt.com/paris-cowan-hall/profil/spieler/55504.
Transfer history data appended for: https://www.transfermarkt.com/diaz-wright/profil/spieler/458795.
Transfer history data appended for: https://www.transfermarkt.com/noah-chilvers/profil/spieler/574587.
Transfer history data appended for: https://www.transfermarkt.com/jordan-turnbull/profil/spieler/226978.
Transfer history data appended for: https://www.transfermarkt.com/tom-elliott/profil/spieler/46805.
Transfer history data appended for: https://www.transfermarkt.com/tom-clarke/profil/spieler/48124.
Transfer history data appended for: https://www.transfermarkt.com/luke-burgess/profil/spieler/425873.
Transfer history data appended for: https://www.transfermarkt.com/nick-hayes/profil/spieler/391110.
Transfer history data appended for: https://www.transfermarkt.com/bruno-andrade/profil/spieler/169633.
Transfer history data appended for: https://www.transfermarkt.com/george-boyd/profil/spieler/45623.
Transfer history data appended for: https://www.transfermarkt.com/tylor-golden/profil/spieler/543783.
Transfer history data appended for: https://www.transfermarkt.com/jason-lowe/profil/spieler/117997.
Transfer history data appended for: https://www.transfermarkt.com/richie-towell/profil/spieler/114116.
Transfer history data appended for: https://www.transfermarkt.com/martin-smith/profil/spieler/257536.
Transfer history data appended for: https://www.transfermarkt.com/oscar-threlkeld/profil/spieler/173802.
Transfer history data appended for: https://www.transfermarkt.com/dishon-bernard/profil/spieler/531677.
Transfer history data appended for: https://www.transfermarkt.com/vaclav-hladky/profil/spieler/95795.
Transfer history data appended for: https://www.transfermarkt.com/james-wilson/profil/spieler/214104.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-dieseruvwe/profil/spieler/268451.
Transfer history data appended for: https://www.transfermarkt.com/ian-henderson/profil/spieler/11686.
Transfer history data appended for: https://www.transfermarkt.com/brandon-thomas-asante/profil/spieler/451747.
Transfer history data appended for: https://www.transfermarkt.com/ibou-touray/profil/spieler/204960.
Transfer history data appended for: https://www.transfermarkt.com/luke-armstrong/profil/spieler/383046.
Transfer history data appended for: https://www.transfermarkt.com/kevin-berkoe/profil/spieler/509156.
Transfer history data appended for: https://www.transfermarkt.com/alex-denny/profil/spieler/465950.
Transfer history data appended for: https://www.transfermarkt.com/ashley-hunter/profil/spieler/351933.
Transfer history data appended for: https://www.transfermarkt.com/darron-gibson/profil/spieler/42413.
Transfer history data appended for: https://www.transfermarkt.com/ashley-eastham/profil/spieler/118265.
Transfer history data appended for: https://www.transfermarkt.com/aj-leitch-smith/profil/spieler/115608.
Transfer history data appended for: https://www.transfermarkt.com/ben-pringle/profil/spieler/29589.
Transfer history data appended for: https://www.transfermarkt.com/stephen-hendrie/profil/spieler/186269.
Transfer history data appended for: https://www.transfermarkt.com/john-osullivan/profil/spieler/173592.
Transfer history data appended for: https://www.transfermarkt.com/aaron-wildig/profil/spieler/121831.
Transfer history data appended for: https://www.transfermarkt.com/adam-phillips/profil/spieler/314381.
Transfer history data appended for: https://www.transfermarkt.com/mark-halstead/profil/spieler/99972.
Transfer history data appended for: https://www.transfermarkt.com/jordan-slew/profil/spieler/164785.
Transfer history data appended for: https://www.transfermarkt.com/harry-davis/profil/spieler/123675.
Transfer history data appended for: https://www.transfermarkt.com/liam-gibson/profil/spieler/312553.
Transfer history data appended for: https://www.transfermarkt.com/sam-lavelle/profil/spieler/285846.
Transfer history data appended for: https://www.transfermarkt.com/freddie-price/profil/spieler/646939.
Transfer history data appended for: https://www.transfermarkt.com/ryan-cooney/profil/spieler/478014.
Transfer history data appended for: https://www.transfermarkt.com/toumani-diagouraga/profil/spieler/37010.
Transfer history data appended for: https://www.transfermarkt.com/nathaniel-knight-percival/profil/spieler/97886.
Transfer history data appended for: https://www.transfermarkt.com/liam-mcalinden/profil/spieler/166319.
Transfer history data appended for: https://www.transfermarkt.com/yann-songoo/profil/spieler/144341.
Transfer history data appended for: https://www.transfermarkt.com/kelvin-mellor/profil/spieler/143006.
Transfer history data appended for: https://www.transfermarkt.com/cole-stockton/profil/spieler/213398.
Transfer history data appended for: https://www.transfermarkt.com/alex-kenyon/profil/spieler/234824.
Transfer history data appended for: https://www.transfermarkt.com/jake-turner/profil/spieler/457128.
Transfer history data appended for: https://www.transfermarkt.com/carlos-mendes-gomes/profil/spieler/588412.
Transfer history data appended for: https://www.transfermarkt.com/andre-filipe-da-silva-mendes/profil/spieler/744549.
Transfer history data appended for: https://www.transfermarkt.com/mattie-pollock/profil/spieler/624948.
Transfer history data appended for: https://www.transfermarkt.com/luke-waterfall/profil/spieler/90476.
Transfer history data appended for: https://www.transfermarkt.com/virgil-gomis/profil/spieler/628220.
Transfer history data appended for: https://www.transfermarkt.com/max-wright/profil/spieler/444716.
Transfer history data appended for: https://www.transfermarkt.com/james-hanson/profil/spieler/108160.
Transfer history data appended for: https://www.transfermarkt.com/james-mckeown/profil/spieler/62327.
Transfer history data appended for: https://www.transfermarkt.com/joseph-starbuck/profil/spieler/727228.
Transfer history data appended for: https://www.transfermarkt.com/ollie-battersby/profil/spieler/624947.
Transfer history data appended for: https://www.transfermarkt.com/duncan-idehen/profil/spieler/632135.
Transfer history data appended for: https://www.transfermarkt.com/kyle-bennett/profil/spieler/131593.
Transfer history data appended for: https://www.transfermarkt.com/joseph-hope/profil/spieler/696185.
Transfer history data appended for: https://www.transfermarkt.com/james-morton/profil/spieler/682035.
Transfer history data appended for: https://www.transfermarkt.com/terry-taylor/profil/spieler/463758.
Transfer history data appended for: https://www.transfermarkt.com/ludvig-ohman/profil/spieler/77841.
Transfer history data appended for: https://www.transfermarkt.com/elliott-hewitt/profil/spieler/186624.
Transfer history data appended for: https://www.transfermarkt.com/matt-green/profil/spieler/46822.

Transfer history data appended for: https://www.transfermarkt.com/ira-jackson-jr-/profil/spieler/451589.
Transfer history data appended for: https://www.transfermarkt.com/montel-gibson/profil/spieler/431151.
Transfer history data appended for: https://www.transfermarkt.com/james-tilley/profil/spieler/359693.
Transfer history data appended for: https://www.transfermarkt.com/george-williams/profil/spieler/136368.
Transfer history data appended for: https://www.transfermarkt.com/owen-windsor/profil/spieler/680653.
Transfer history data appended for: https://www.transfermarkt.com/danny-rose/profil/spieler/67236.
Transfer history data appended for: https://www.transfermarkt.com/danny-preston/profil/spieler/565676.
Transfer history data appended for: https://www.transfermarkt.com/harry-clifton/profil/spieler/381352.
Transfer history data appended for: https://www.transfermarkt.com/luke-spokes/profil/spieler/809775.
Transfer history data appended for: https://www.transfermarkt.com/sean-scannell/profil/spieler/61549.
Transfer history data appended for: https://www.transfermarkt.com/luke-hendrie/profil/spieler/158786.
Transfer history data appended for: https://www.transfermarkt.com/cameron-painter/profil/spieler/696184.
Transfer history data appended for: https://www.transfermarkt.com/sam-russell/profil/spieler/4043.
Transfer history data appended for: https://www.transfermarkt.com/matty-blair/profil/spieler/105318.
Transfer history data appended for: https://www.transfermarkt.com/reuben-reid/profil/spieler/39693.
Transfer history data appended for: https://www.transfermarkt.com/ben-tozer/profil/spieler/65927.
Transfer history data appended for: https://www.transfermarkt.com/conor-thomas/profil/spieler/131980.
Transfer history data appended for: https://www.transfermarkt.com/grant-horton/profil/spieler/698896.
Transfer history data appended for: https://www.transfermarkt.com/ellis-chapman/profil/spieler/508343.
Transfer history data appended for: https://www.transfermarkt.com/tom-sang/profil/spieler/396176.
Transfer history data appended for: https://www.transfermarkt.com/george-lloyd/profil/spieler/532192.
Transfer history data appended for: https://www.transfermarkt.com/scott-flinders/profil/spieler/42003.
Transfer history data appended for: https://www.transfermarkt.com/tahvon-campbell/profil/spieler/286496.
Transfer history data appended for: https://www.transfermarkt.com/sean-long/profil/spieler/228773.
Transfer history data appended for: https://www.transfermarkt.com/lewis-freestone/profil/spieler/457897.
Transfer history data appended for: https://www.transfermarkt.com/andy-williams/profil/spieler/47909.
Transfer history data appended for: https://www.transfermarkt.com/tom-chamberlain/profil/spieler/698011.
Transfer history data appended for: https://www.transfermarkt.com/alfie-may/profil/spieler/479987.
Transfer history data appended for: https://www.transfermarkt.com/charlie-raglan/profil/spieler/193777.
Transfer history data appended for: https://www.transfermarkt.com/chris-hussey/profil/spieler/125875.
Transfer history data appended for: https://www.transfermarkt.com/liam-sercombe/profil/spieler/77570.
Transfer history data appended for: https://www.transfermarkt.com/finn-azaz/profil/spieler/480723.
Transfer history data appended for: https://www.transfermarkt.com/william-boyle/profil/spieler/247400.
Transfer history data appended for: https://www.transfermarkt.com/dan-bowry/profil/spieler/574779.
Transfer history data appended for: https://www.transfermarkt.com/joshua-griffiths/profil/spieler/565979.
Transfer history data appended for: https://www.transfermarkt.com/alex-addai/profil/spieler/471910.
Transfer history data appended for: https://www.transfermarkt.com/elliot-bonds/profil/spieler/568092.
Transfer history data appended for: https://www.transfermarkt.com/max-harris/profil/spieler/556864.
Transfer history data appended for: https://www.transfermarkt.com/chris-clements/profil/spieler/91289.
Transfer history data appended for: https://www.transfermarkt.com/harrison-mcgahey/profil/spieler/286806.
Transfer history data appended for: https://www.transfermarkt.com/lewis-butroid/profil/spieler/457525.
Transfer history data appended for: https://www.transfermarkt.com/olufela-olomola/profil/spieler/356569.
Transfer history data appended for: https://www.transfermarkt.com/adam-kelsey/profil/spieler/467538.
Transfer history data appended for: https://www.transfermarkt.com/raynner-silva/profil/spieler/774586.
Transfer history data appended for: https://www.transfermarkt.com/tom-pugh/profil/spieler/625078.
Transfer history data appended for: https://www.transfermarkt.com/frank-vincent/profil/spieler/690884.
Transfer history data appended for: https://www.transfermarkt.com/ryan-loft/profil/spieler/364711.
Transfer history data appended for: https://www.transfermarkt.com/kevin-van-veen/profil/spieler/159894.
Transfer history data appended for: https://www.transfermarkt.com/devarn-green/profil/spieler/285844.
Transfer history data appended for: https://www.transfermarkt.com/junior-brown/profil/spieler/66956.
Transfer history data appended for: https://www.transfermarkt.com/kelsey-mooney/profil/spieler/425764.
Transfer history data appended for: https://www.transfermarkt.com/tyler-cordner/profil/spieler/620168.
Transfer history data appended for: https://www.transfermarkt.com/aaron-jarvis/profil/spieler/534559.
Transfer history data appended for: https://www.transfermarkt.com/charlie-barks/profil/spieler/774583.
Transfer history data appended for: https://www.transfermarkt.com/george-hornshaw/profil/spieler/542479.
Transfer history data appended for: https://www.transfermarkt.com/mason-omalley/profil/spieler/696225.
Transfer history data appended for: https://www.transfermarkt.com/alex-gilliead/profil/spieler/221687.
Transfer history data appended for: https://www.transfermarkt.com/jai-rowe/profil/spieler/745161.
Transfer history data appended for: https://www.transfermarkt.com/abo-eisa/profil/spieler/566408.
Transfer history data appended for: https://www.transfermarkt.com/jordan-clarke/profil/spieler/95683.
Transfer history data appended for: https://www.transfermarkt.com/alfie-beestin/profil/spieler/451862.
Transfer history data appended for: https://www.transfermarkt.com/andy-dales/profil/spieler/594092.
Transfer history data appended for: https://www.transfermarkt.com/rory-watson/profil/spieler/344916.
Transfer history data appended for: https://www.transfermarkt.com/lewis-spence/profil/spieler/255340.
Transfer history data appended for: https://www.transfermarkt.com/john-mcatee/profil/spieler/504855.
Transfer history data appended for: https://www.transfermarkt.com/tom-collins/profil/spieler/744552.
Transfer history data appended for: https://www.transfermarkt.com/mark-howard/profil/spieler/25186.
Transfer history data appended for: https://www.transfermarkt.com/myles-hippolyte/profil/spieler/329849.
Transfer history data appended for: https://www.transfermarkt.com/harry-jessop/profil/spieler/774584.
Transfer history data appended for: https://www.transfermarkt.com/jacob-bedeau/profil/spieler/453661.
Transfer history data appended for: https://www.transfermarkt.com/jordan-hallam/profil/spieler/473078.
Transfer history data appended for: https://www.transfermarkt.com/kenan-dunnwald-turan/profil/spieler/238564.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-onariase/profil/spieler/257534.
Transfer history data appended for: https://www.transfermarkt.com/finley-shrimpton/profil/spieler/774585.
Transfer history data appended for: https://www.transfermarkt.com/jake-taylor/profil/spieler/702715.
Transfer history data appended for: https://www.transfermarkt.com/myles-judd/profil/spieler/392302.
Transfer history data appended for: https://www.transfermarkt.com/jordan-thomas/profil/spieler/563306.
Transfer history data appended for: https://www.transfermarkt.com/conor-wilkinson/profil/spieler/228791.
Transfer history data appended for: https://www.transfermarkt.com/craig-clay/profil/spieler/138235.
Transfer history data appended for: https://www.transfermarkt.com/sam-sargeant/profil/spieler/369945.
Transfer history data appended for: https://www.transfermarkt.com/james-dayton/profil/spieler/92548.

Transfer history data appended for: https://www.transfermarkt.com/jordan-maguire-drew/profil/spieler/341028.
Transfer history data appended for: https://www.transfermarkt.com/dan-happe/profil/spieler/491174.
Transfer history data appended for: https://www.transfermarkt.com/sam-ling/profil/spieler/302459.
Transfer history data appended for: https://www.transfermarkt.com/tunji-akinola/profil/spieler/347212.
Transfer history data appended for: https://www.transfermarkt.com/joe-widdowson/profil/spieler/61594.
Transfer history data appended for: https://www.transfermarkt.com/danny-johnson/profil/spieler/344525.
Transfer history data appended for: https://www.transfermarkt.com/jobi-mcanuff/profil/spieler/14047.
Transfer history data appended for: https://www.transfermarkt.com/lawrence-vigouroux/profil/spieler/243591.
Transfer history data appended for: https://www.transfermarkt.com/jamie-turley/profil/spieler/106359.
Transfer history data appended for: https://www.transfermarkt.com/james-brophy/profil/spieler/386505.
Transfer history data appended for: https://www.transfermarkt.com/brendon-shabani/profil/spieler/676167.
Transfer history data appended for: https://www.transfermarkt.com/hector-kyprianou/profil/spieler/661253.
Transfer history data appended for: https://www.transfermarkt.com/jayden-sweeney/profil/spieler/676168.
Transfer history data appended for: https://www.transfermarkt.com/louis-dennis/profil/spieler/233213.
Transfer history data appended for: https://www.transfermarkt.com/shadrach-ogie/profil/spieler/651955.
Transfer history data appended for: https://www.transfermarkt.com/ruel-sotiriou/profil/spieler/547479.
Transfer history data appended for: https://www.transfermarkt.com/josh-coulson/profil/spieler/66493.
Transfer history data appended for: https://www.transfermarkt.com/lee-angol/profil/spieler/233100.
Transfer history data appended for: https://www.transfermarkt.com/ousseynou-cisse/profil/spieler/98827.
Transfer history data appended for: https://www.transfermarkt.com/josh-wright/profil/spieler/55898.
Transfer history data appended for: https://www.transfermarkt.com/liam-kinsella/profil/spieler/334050.
Transfer history data appended for: https://www.transfermarkt.com/danny-guthrie/profil/spieler/16716.
Transfer history data appended for: https://www.transfermarkt.com/rory-holden/profil/spieler/431643.
Transfer history data appended for: https://www.transfermarkt.com/liam-roberts/profil/spieler/249164.
Transfer history data appended for: https://www.transfermarkt.com/dan-scarr/profil/spieler/407363.
Transfer history data appended for: https://www.transfermarkt.com/cameron-norman/profil/spieler/216901.
Transfer history data appended for: https://www.transfermarkt.com/mat-sadler/profil/spieler/3930.
Transfer history data appended for: https://www.transfermarkt.com/stuart-sinclair/profil/spieler/208369.
Transfer history data appended for: https://www.transfermarkt.com/tom-leak/profil/spieler/690227.
Transfer history data appended for: https://www.transfermarkt.com/adan-george/profil/spieler/716109.
Transfer history data appended for: https://www.transfermarkt.com/george-nurse/profil/spieler/633129.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-osadebe/profil/spieler/393284.
Transfer history data appended for: https://www.transfermarkt.com/elijah-adebayo/profil/spieler/319900.
Transfer history data appended for: https://www.transfermarkt.com/wes-mcdonald/profil/spieler/538855.
Transfer history data appended for: https://www.transfermarkt.com/james-clarke/profil/spieler/67215.
Transfer history data appended for: https://www.transfermarkt.com/jack-rose/profil/spieler/186923.
Transfer history data appended for: https://www.transfermarkt.com/sam-perry/profil/spieler/744633.
Transfer history data appended for: https://www.transfermarkt.com/josh-gordon/profil/spieler/426426.
Transfer history data appended for: https://www.transfermarkt.com/hayden-white/profil/spieler/270157.
Transfer history data appended for: https://www.transfermarkt.com/alfie-bates/profil/spieler/624914.
Transfer history data appended for: https://www.transfermarkt.com/caolan-lavery/profil/spieler/127983.
Transfer history data appended for: https://www.transfermarkt.com/jack-nolan/profil/spieler/503760.
Transfer history data appended for: https://www.transfermarkt.com/callum-cockerill-mollett/profil/spieler/454317.
Transfer history data appended for: https://www.transfermarkt.com/zak-jules/profil/spieler/309041.
Transfer history data appended for: https://www.transfermarkt.com/jake-scrimshaw/profil/spieler/655180.
Transfer history data appended for: https://www.transfermarkt.com/tom-walker/profil/spieler/284749.
Transfer history data appended for: https://www.transfermarkt.com/joe-leesley/profil/spieler/354111.
Transfer history data appended for: https://www.transfermarkt.com/jon-stead/profil/spieler/16107.
Transfer history data appended for: https://www.transfermarkt.com/will-smith/profil/spieler/503123.
Transfer history data appended for: https://www.transfermarkt.com/george-thomson/profil/spieler/353800.
Transfer history data appended for: https://www.transfermarkt.com/josh-falkingham/profil/spieler/121326.
Transfer history data appended for: https://www.transfermarkt.com/brendan-kiernan/profil/spieler/192075.
Transfer history data appended for: https://www.transfermarkt.com/kevin-lokko/profil/spieler/264849.
Transfer history data appended for: https://www.transfermarkt.com/calvin-miller/profil/spieler/244261.
Transfer history data appended for: https://www.transfermarkt.com/jake-lawlor/profil/spieler/382816.
Transfer history data appended for: https://www.transfermarkt.com/warren-burrell/profil/spieler/104535.
Transfer history data appended for: https://www.transfermarkt.com/aaron-martin/profil/spieler/796677.
Transfer history data appended for: https://www.transfermarkt.com/lloyd-kerry/profil/spieler/48108.
Transfer history data appended for: https://www.transfermarkt.com/james-belshaw/profil/spieler/107534.
Transfer history data appended for: https://www.transfermarkt.com/joe-cracknell/profil/spieler/195632.
Transfer history data appended for: https://www.transfermarkt.com/mark-beck/profil/spieler/223578.
Transfer history data appended for: https://www.transfermarkt.com/ryan-fallowfield/profil/spieler/450736.
Transfer history data appended for: https://www.transfermarkt.com/connor-hall/profil/spieler/650476.
Transfer history data appended for: https://www.transfermarkt.com/jack-muldoon/profil/spieler/325607.
Transfer history data appended for: https://www.transfermarkt.com/dan-jones/profil/spieler/281891.
Transfer history data appended for: https://www.transfermarkt.com/connor-kirby/profil/spieler/566815.
Transfer history data appended for: https://www.transfermarkt.com/jamie-cumming/profil/spieler/396859.
Transfer history data appended for: https://www.transfermarkt.com/ben-coker/profil/spieler/157075.
Transfer history data appended for: https://www.transfermarkt.com/romain-vincelot/profil/spieler/45110.
Transfer history data appended for: https://www.transfermarkt.com/jack-aitchison/profil/spieler/344589.
Transfer history data appended for: https://www.transfermarkt.com/femi-akinwande/profil/spieler/301129.
Transfer history data appended for: https://www.transfermarkt.com/luke-prosser/profil/spieler/49453.
Transfer history data appended for: https://www.transfermarkt.com/elliot-osborne/profil/spieler/466673.
Transfer history data appended for: https://www.transfermarkt.com/remeao-hutton/profil/spieler/691064.
Transfer history data appended for: https://www.transfermarkt.com/tom-pett/profil/spieler/329205.
Transfer history data appended for: https://www.transfermarkt.com/scott-cuthbert/profil/spieler/21330.
Transfer history data appended for: https://www.transfermarkt.com/luther-wildin/profil/spieler/432181.
Transfer history data appended for: https://www.transfermarkt.com/billy-johnson/profil/spieler/607523.
Transfer history data appended for: https://www.transfermarkt.com/danny-newton/profil/spieler/207881.
Transfer history data appended for: https://www.transfermarkt.com/arthur-read/profil/spieler/458187.
Transfer history data appended for: https://www.transfermarkt.com/marcus-dinanga/profil/spieler/556982.

Transfer history data appended for: https://www.transfermarkt.com/tyrone-marsh/profil/spieler/186029.
Transfer history data appended for: https://www.transfermarkt.com/inih-effiong/profil/spieler/220328.
Transfer history data appended for: https://www.transfermarkt.com/jack-smith/profil/spieler/632378.
Transfer history data appended for: https://www.transfermarkt.com/terence-vancooten/profil/spieler/406935.
Transfer history data appended for: https://www.transfermarkt.com/arthur-iontton/profil/spieler/581870.
Transfer history data appended for: https://www.transfermarkt.com/ross-marshall/profil/spieler/745159.
Transfer history data appended for: https://www.transfermarkt.com/elliott-list/profil/spieler/372714.
Transfer history data appended for: https://www.transfermarkt.com/charlie-carter/profil/spieler/451302.
Transfer history data appended for: https://www.transfermarkt.com/aramide-oteh/profil/spieler/462113.
Transfer history data appended for: https://www.transfermarkt.com/george-tanner/profil/spieler/420811.
Transfer history data appended for: https://www.transfermarkt.com/joe-riley/profil/spieler/387036.
Transfer history data appended for: https://www.transfermarkt.com/jamie-armstrong/profil/spieler/781941.
Transfer history data appended for: https://www.transfermarkt.com/tom-wilson/profil/spieler/781942.
Transfer history data appended for: https://www.transfermarkt.com/gime-toure/profil/spieler/525216.
Transfer history data appended for: https://www.transfermarkt.com/connor-malley/profil/spieler/485998.
Transfer history data appended for: https://www.transfermarkt.com/ethan-walker/profil/spieler/640893.
Transfer history data appended for: https://www.transfermarkt.com/daniel-devine/profil/spieler/451732.
Transfer history data appended for: https://www.transfermarkt.com/nick-anderton/profil/spieler/343328.
Transfer history data appended for: https://www.transfermarkt.com/joshua-kayode/profil/spieler/532195.
Transfer history data appended for: https://www.transfermarkt.com/max-hunt/profil/spieler/554465.
Transfer history data appended for: https://www.transfermarkt.com/rod-mcdonald/profil/spieler/129021.
Transfer history data appended for: https://www.transfermarkt.com/lewis-alessandra/profil/spieler/53601.
Transfer history data appended for: https://www.transfermarkt.com/paul-farman/profil/spieler/97930.
Transfer history data appended for: https://www.transfermarkt.com/rhys-bennett/profil/spieler/128227.
Transfer history data appended for: https://www.transfermarkt.com/jack-armer/profil/spieler/509423.
Transfer history data appended for: https://www.transfermarkt.com/lewis-bell/profil/spieler/808280.
Transfer history data appended for: https://www.transfermarkt.com/jon-mellish/profil/spieler/504939.
Transfer history data appended for: https://www.transfermarkt.com/omari-patrick/profil/spieler/411239.
Transfer history data appended for: https://www.transfermarkt.com/micah-obiero/profil/spieler/795638.
Transfer history data appended for: https://www.transfermarkt.com/dean-furman/profil/spieler/39878.
Transfer history data appended for: https://www.transfermarkt.com/aaron-hayden/profil/spieler/357297.
Transfer history data appended for: https://www.transfermarkt.com/gavin-reilly/profil/spieler/156764.
Transfer history data appended for: https://www.transfermarkt.com/brennan-dickenson/profil/spieler/237552.
Transfer history data appended for: https://www.transfermarkt.com/charlie-birch/profil/spieler/629026.
Transfer history data appended for: https://www.transfermarkt.com/josh-dixon/profil/spieler/671643.
Transfer history data appended for: https://www.transfermarkt.com/marcus-dewhurst/profil/spieler/566348.
Transfer history data appended for: https://www.transfermarkt.com/magnus-norman/profil/spieler/256436.
Transfer history data appended for: https://www.transfermarkt.com/taylor-charters/profil/spieler/702714.
Transfer history data appended for: https://www.transfermarkt.com/callum-guy/profil/spieler/335182.
Transfer history data appended for: https://www.transfermarkt.com/timothee-dieng/profil/spieler/200127.
Transfer history data appended for: https://www.transfermarkt.com/alan-mccormack/profil/spieler/15814.
Transfer history data appended for: https://www.transfermarkt.com/callum-taylor/profil/spieler/741932.
Transfer history data appended for: https://www.transfermarkt.com/james-olayinka/profil/spieler/506965.
Transfer history data appended for: https://www.transfermarkt.com/emile-acquah/profil/spieler/662538.
Transfer history data appended for: https://www.transfermarkt.com/nathan-ralph/profil/spieler/164186.
Transfer history data appended for: https://www.transfermarkt.com/harry-phillips/profil/spieler/560535.
Transfer history data appended for: https://www.transfermarkt.com/simeon-akinola/profil/spieler/337869.
Transfer history data appended for: https://www.transfermarkt.com/tom-clifford/profil/spieler/642538.
Transfer history data appended for: https://www.transfermarkt.com/kazaiah-sterling/profil/spieler/357397.
Transfer history data appended for: https://www.transfermarkt.com/brandon-goodship/profil/spieler/423584.
Transfer history data appended for: https://www.transfermarkt.com/matt-rush/profil/spieler/718546.
Transfer history data appended for: https://www.transfermarkt.com/mark-oxley/profil/spieler/67232.
Transfer history data appended for: https://www.transfermarkt.com/shaun-hobson/profil/spieler/562257.
Transfer history data appended for: https://www.transfermarkt.com/jason-dimitriou/profil/spieler/48250.
Transfer history data appended for: https://www.transfermarkt.com/kyle-taylor/profil/spieler/562254.
Transfer history data appended for: https://www.transfermarkt.com/ashley-nathaniel-george/profil/spieler/590686.
Transfer history data appended for: https://www.transfermarkt.com/miles-mitchell-nelson/profil/spieler/582367.
Transfer history data appended for: https://www.transfermarkt.com/richard-taylor/profil/spieler/696893.
Transfer history data appended for: https://www.transfermarkt.com/harry-lennon/profil/spieler/297476.
Transfer history data appended for: https://www.transfermarkt.com/john-white/profil/spieler/42108.
Transfer history data appended for: https://www.transfermarkt.com/eren-kinali/profil/spieler/727031.
Transfer history data appended for: https://www.transfermarkt.com/harry-seaden/profil/spieler/470605.
Transfer history data appended for: https://www.transfermarkt.com/elvis-bwomono/profil/spieler/531840.
Transfer history data appended for: https://www.transfermarkt.com/lewis-gard/profil/spieler/582366.
Transfer history data appended for: https://www.transfermarkt.com/sam-hart/profil/spieler/279471.
Transfer history data appended for: https://www.transfermarkt.com/clayton-donaldson/profil/spieler/52721.
Transfer history data appended for: https://www.transfermarkt.com/richard-odonnell/profil/spieler/49667.
Transfer history data appended for: https://www.transfermarkt.com/zeli-ismail/profil/spieler/104555.
Transfer history data appended for: https://www.transfermarkt.com/elliot-watt/profil/spieler/403574.
Transfer history data appended for: https://www.transfermarkt.com/callum-cooke/profil/spieler/258882.
Transfer history data appended for: https://www.transfermarkt.com/harry-pritchard/profil/spieler/409692.
Transfer history data appended for: https://www.transfermarkt.com/kurtis-guthrie/profil/spieler/192656.
Transfer history data appended for: https://www.transfermarkt.com/jorge-sikora/profil/spieler/734498.
Transfer history data appended for: https://www.transfermarkt.com/austin-samuels/profil/spieler/392762.
Transfer history data appended for: https://www.transfermarkt.com/jackson-longridge/profil/spieler/225077.
Transfer history data appended for: https://www.transfermarkt.com/connor-wood/profil/spieler/454135.
Transfer history data appended for: https://www.transfermarkt.com/ben-richards-everton/profil/spieler/207891.
Transfer history data appended for: https://www.transfermarkt.com/billy-clarke/profil/spieler/33248.
Transfer history data appended for: https://www.transfermarkt.com/kian-scales/profil/spieler/746385.
Transfer history data appended for: https://www.transfermarkt.com/lee-novak/profil/spieler/105723.

Transfer history data appended for: https://www.transfermarkt.com/tyler-french/profil/spieler/676307.
Transfer history data appended for: https://www.transfermarkt.com/dylan-mottley-henry/profil/spieler/345767.
Transfer history data appended for: https://www.transfermarkt.com/finn-cousin-dawson/profil/spieler/734497.
Transfer history data appended for: https://www.transfermarkt.com/sam-hornby/profil/spieler/372525.
Transfer history data appended for: https://www.transfermarkt.com/reece-staunton/profil/spieler/550641.
Transfer history data appended for: https://www.transfermarkt.com/connor-shanks/profil/spieler/811493.
Transfer history data appended for: https://www.transfermarkt.com/paudie-oconnor/profil/spieler/364024.
Transfer history data appended for: https://www.transfermarkt.com/anthony-oconnor/profil/spieler/121393.
Transfer history data appended for: https://www.transfermarkt.com/gareth-evans/profil/spieler/77369.
Transfer history data appended for: https://www.transfermarkt.com/bryce-hosannah/profil/spieler/529746.
Transfer history data appended for: https://www.transfermarkt.com/levi-sutton/profil/spieler/339734.
Transfer history data appended for: https://www.transfermarkt.com/gethin-jones/profil/spieler/242412.
Transfer history data appended for: https://www.transfermarkt.com/tom-white/profil/spieler/496786.
Transfer history data appended for: https://www.transfermarkt.com/brandon-comley/profil/spieler/362809.
Transfer history data appended for: https://www.transfermarkt.com/jak-hickman/profil/spieler/425798.
Transfer history data appended for: https://www.transfermarkt.com/nathan-delfouneso/profil/spieler/62642.
Transfer history data appended for: https://www.transfermarkt.com/dennis-politic/profil/spieler/470152.
Transfer history data appended for: https://www.transfermarkt.com/ryan-delaney/profil/spieler/316554.
Transfer history data appended for: https://www.transfermarkt.com/matt-gilks/profil/spieler/48254.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-santos/profil/spieler/247666.
Transfer history data appended for: https://www.transfermarkt.com/george-taft/profil/spieler/177613.
Transfer history data appended for: https://www.transfermarkt.com/adam-senior/profil/spieler/672607.
Transfer history data appended for: https://www.transfermarkt.com/harry-brockbank/profil/spieler/527733.
Transfer history data appended for: https://www.transfermarkt.com/antoni-sarcevic/profil/spieler/160525.
Transfer history data appended for: https://www.transfermarkt.com/billy-crellin/profil/spieler/536794.
Transfer history data appended for: https://www.transfermarkt.com/lloyd-isgrove/profil/spieler/226965.
Transfer history data appended for: https://www.transfermarkt.com/eoin-doyle/profil/spieler/68335.
Transfer history data appended for: https://www.transfermarkt.com/jamie-mascoll/profil/spieler/549848.
Transfer history data appended for: https://www.transfermarkt.com/andrew-tutte/profil/spieler/121415.
Transfer history data appended for: https://www.transfermarkt.com/arthur-gnahoua/profil/spieler/255665.
Transfer history data appended for: https://www.transfermarkt.com/reiss-greenidge/profil/spieler/265231.
Transfer history data appended for: https://www.transfermarkt.com/peter-kioso/profil/spieler/595652.
Transfer history data appended for: https://www.transfermarkt.com/ali-crawford/profil/spieler/79620.
Transfer history data appended for: https://www.transfermarkt.com/liam-edwards/profil/spieler/344305.
Transfer history data appended for: https://www.transfermarkt.com/sonny-graham/profil/spieler/680174.
Transfer history data appended for: https://www.transfermarkt.com/ronan-darcy/profil/spieler/671486.
Transfer history data appended for: https://www.transfermarkt.com/shaun-miller/profil/spieler/48965.
Transfer history data appended for: https://www.transfermarkt.com/liam-gordon/profil/spieler/474225.
Transfer history data appended for: https://www.transfermarkt.com/alex-baptiste/profil/spieler/16660.
Transfer history data appended for: https://www.transfermarkt.com/bright-amoateng/profil/spieler/580800.
Transfer history data appended for: https://www.transfermarkt.com/matthew-alexander/profil/spieler/693587.
Transfer history data appended for: https://www.transfermarkt.com/paul-digby/profil/spieler/202883.
Transfer history data appended for: https://www.transfermarkt.com/andy-dallas/profil/spieler/406736.
Transfer history data appended for: https://www.transfermarkt.com/jack-iredale/profil/spieler/524537.
Transfer history data appended for: https://www.transfermarkt.com/harrison-dunk/profil/spieler/196242.
Transfer history data appended for: https://www.transfermarkt.com/kai-mckenzie-lyle/profil/spieler/344534.
Transfer history data appended for: https://www.transfermarkt.com/harry-darling/profil/spieler/475554.
Transfer history data appended for: https://www.transfermarkt.com/joe-neal/profil/spieler/671634.
Transfer history data appended for: https://www.transfermarkt.com/lewis-simper/profil/spieler/727289.
Transfer history data appended for: https://www.transfermarkt.com/ben-worman/profil/spieler/533919.
Transfer history data appended for: https://www.transfermarkt.com/joe-ironside/profil/spieler/177901.
Transfer history data appended for: https://www.transfermarkt.com/hiram-boateng/profil/spieler/244125.
Transfer history data appended for: https://www.transfermarkt.com/paul-mullin/profil/spieler/278501.
Transfer history data appended for: https://www.transfermarkt.com/leon-davies/profil/spieler/409052.
Transfer history data appended for: https://www.transfermarkt.com/luke-hannant/profil/spieler/462068.
Transfer history data appended for: https://www.transfermarkt.com/robbie-cundy/profil/spieler/379711.
Transfer history data appended for: https://www.transfermarkt.com/harvey-knibbs/profil/spieler/484735.
Transfer history data appended for: https://www.transfermarkt.com/greg-taylor/profil/spieler/77042.
Transfer history data appended for: https://www.transfermarkt.com/liam-oneil/profil/spieler/141349.
Transfer history data appended for: https://www.transfermarkt.com/kyle-knoyle/profil/spieler/291171.
Transfer history data appended for: https://www.transfermarkt.com/wes-hoolahan/profil/spieler/24589.
Transfer history data appended for: https://www.transfermarkt.com/dimitar-mitov/profil/spieler/264302.
Transfer history data appended for: https://www.transfermarkt.com/adam-may/profil/spieler/370551.
Transfer history data appended for: https://www.transfermarkt.com/idris-el-mizouni/profil/spieler/633399.
Transfer history data appended for: https://www.transfermarkt.com/callum-burton/profil/spieler/236495.
Transfer history data appended for: https://www.transfermarkt.com/jordan-moore-taylor/profil/spieler/238423.
Transfer history data appended for: https://www.transfermarkt.com/kane-wilson/profil/spieler/392774.
Transfer history data appended for: https://www.transfermarkt.com/udoka-godwin-malife/profil/spieler/636888.
Transfer history data appended for: https://www.transfermarkt.com/elliott-whitehouse/profil/spieler/177933.
Transfer history data appended for: https://www.transfermarkt.com/liam-kitching/profil/spieler/534701.
Transfer history data appended for: https://www.transfermarkt.com/josh-march/profil/spieler/735677.
Transfer history data appended for: https://www.transfermarkt.com/jack-evans/profil/spieler/504494.
Transfer history data appended for: https://www.transfermarkt.com/mathew-stevens/profil/spieler/339023.
Transfer history data appended for: https://www.transfermarkt.com/luke-mcgee/profil/spieler/183301.
Transfer history data appended for: https://www.transfermarkt.com/jamille-matt/profil/spieler/194195.
Transfer history data appended for: https://www.transfermarkt.com/ebou-adams/profil/spieler/323652.
Transfer history data appended for: https://www.transfermarkt.com/taylor-allen/profil/spieler/662956.
Transfer history data appended for: https://www.transfermarkt.com/carl-winchester/profil/spieler/169625.
Transfer history data appended for: https://www.transfermarkt.com/jake-young/profil/spieler/794437.
Transfer history data appended for: https://www.transfermarkt.com/dan-sweeney/profil/spieler/440112.

Transfer history data appended for: https://www.transfermarkt.com/vaughn-covil/profil/spieler/696230.
Transfer history data appended for: https://www.transfermarkt.com/aaron-collins/profil/spieler/341042.
Transfer history data appended for: https://www.transfermarkt.com/jayden-richardson/profil/spieler/565675.
Transfer history data appended for: https://www.transfermarkt.com/scott-wagstaff/profil/spieler/53066.
Transfer history data appended for: https://www.transfermarkt.com/dominic-bernard/profil/spieler/376248.
Transfer history data appended for: https://www.transfermarkt.com/shawn-mccoulsky/profil/spieler/470371.
Transfer history data appended for: https://www.transfermarkt.com/lewis-thomas/profil/spieler/319306.
Transfer history data appended for: https://www.transfermarkt.com/odin-bailey/profil/spieler/346485.
Transfer history data appended for: https://www.transfermarkt.com/nicky-cadden/profil/spieler/291177.
Transfer history data appended for: https://www.transfermarkt.com/chris-stokes/profil/spieler/125119.
Transfer history data appended for: https://www.transfermarkt.com/harvey-bunker/profil/spieler/734509.
Transfer history data appended for: https://www.transfermarkt.com/josh-key/profil/spieler/533912.
Transfer history data appended for: https://www.transfermarkt.com/alex-hartridge/profil/spieler/527788.
Transfer history data appended for: https://www.transfermarkt.com/nicky-law/profil/spieler/43265.
Transfer history data appended for: https://www.transfermarkt.com/matt-jay/profil/spieler/288274.
Transfer history data appended for: https://www.transfermarkt.com/jake-caprice/profil/spieler/194461.
Transfer history data appended for: https://www.transfermarkt.com/rory-mcardle/profil/spieler/43099.
Transfer history data appended for: https://www.transfermarkt.com/nigel-atangana/profil/spieler/327707.
Transfer history data appended for: https://www.transfermarkt.com/harry-kite/profil/spieler/533911.
Transfer history data appended for: https://www.transfermarkt.com/lewis-ward/profil/spieler/258910.
Transfer history data appended for: https://www.transfermarkt.com/archie-collins/profil/spieler/472714.
Transfer history data appended for: https://www.transfermarkt.com/pierce-sweeney/profil/spieler/183172.
Transfer history data appended for: https://www.transfermarkt.com/ryan-bowman/profil/spieler/136536.
Transfer history data appended for: https://www.transfermarkt.com/jake-taylor/profil/spieler/130230.
Transfer history data appended for: https://www.transfermarkt.com/ben-seymour/profil/spieler/527794.
Transfer history data appended for: https://www.transfermarkt.com/joel-randall/profil/spieler/554234.
Transfer history data appended for: https://www.transfermarkt.com/lewis-page/profil/spieler/242652.
Transfer history data appended for: https://www.transfermarkt.com/will-dean/profil/spieler/554235.
Transfer history data appended for: https://www.transfermarkt.com/james-dodd/profil/spieler/589091.
Transfer history data appended for: https://www.transfermarkt.com/jack-sparkes/profil/spieler/527791.
Transfer history data appended for: https://www.transfermarkt.com/jordan-dyer/profil/spieler/589090.
Transfer history data appended for: https://www.transfermarkt.com/jonny-maxted/profil/spieler/186184.
Transfer history data appended for: https://www.transfermarkt.com/noah-smerdon/profil/spieler/684755.
Transfer history data appended for: https://www.transfermarkt.com/jack-arthur/profil/spieler/745188.
Transfer history data appended for: https://www.transfermarkt.com/nelson-iseguan/profil/spieler/811293.
Transfer history data appended for: https://www.transfermarkt.com/alex-fisher/profil/spieler/67221.
Transfer history data appended for: https://www.transfermarkt.com/tom-parkes/profil/spieler/110866.
Transfer history data appended for: https://www.transfermarkt.com/nicky-ajose/profil/spieler/130234.
Transfer history data appended for: https://www.transfermarkt.com/randell-williams/profil/spieler/415170.
Transfer history data appended for: https://www.transfermarkt.com/scott-quigley/profil/spieler/231602.
Transfer history data appended for: https://www.transfermarkt.com/patrick-brough/profil/spieler/283478.
Transfer history data appended for: https://www.transfermarkt.com/callum-gribbin/profil/spieler/314370.
Transfer history data appended for: https://www.transfermarkt.com/matty-platt/profil/spieler/405978.
Transfer history data appended for: https://www.transfermarkt.com/scott-wilson/profil/spieler/298214.
Transfer history data appended for: https://www.transfermarkt.com/connor-brown/profil/spieler/228956.
Transfer history data appended for: https://www.transfermarkt.com/dior-angus/profil/spieler/284922.
Transfer history data appended for: https://www.transfermarkt.com/luke-james/profil/spieler/211144.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-sea/profil/spieler/541461.
Transfer history data appended for: https://www.transfermarkt.com/sam-hird/profil/spieler/47766.
Transfer history data appended for: https://www.transfermarkt.com/lewis-hardcastle/profil/spieler/359194.
Transfer history data appended for: https://www.transfermarkt.com/kgosi-ntlhe/profil/spieler/195654.
Transfer history data appended for: https://www.transfermarkt.com/harrison-biggins/profil/spieler/533958.
Transfer history data appended for: https://www.transfermarkt.com/james-jones/profil/spieler/352729.
Transfer history data appended for: https://www.transfermarkt.com/scott-moloney/profil/spieler/541039.
Transfer history data appended for: https://www.transfermarkt.com/josh-kay/profil/spieler/470839.
Transfer history data appended for: https://www.transfermarkt.com/josh-lillis/profil/spieler/49537.
Transfer history data appended for: https://www.transfermarkt.com/jayden-reid/profil/spieler/559254.
Transfer history data appended for: https://www.transfermarkt.com/bradley-barry/profil/spieler/335588.
Transfer history data appended for: https://www.transfermarkt.com/courtney-baker-richardson/profil/spieler/298231.
Transfer history data appended for: https://www.transfermarkt.com/tom-beadling/profil/spieler/258653.
Transfer history data appended for: https://www.transfermarkt.com/chris-taylor/profil/spieler/49438.
Transfer history data appended for: https://www.transfermarkt.com/yoan-zouma/profil/spieler/690615.
Transfer history data appended for: https://www.transfermarkt.com/joel-dixon/profil/spieler/222014.
Transfer history data appended for: https://www.transfermarkt.com/jason-taylor/profil/spieler/67343.
Transfer history data appended for: https://www.transfermarkt.com/mike-jones/profil/spieler/49558.
Transfer history data appended for: https://www.transfermarkt.com/mickey-demetriou/profil/spieler/194189.
Transfer history data appended for: https://www.transfermarkt.com/lewis-collins/profil/spieler/547037.
Transfer history data appended for: https://www.transfermarkt.com/tom-king/profil/spieler/215810.
Transfer history data appended for: https://www.transfermarkt.com/nick-townsend/profil/spieler/256221.
Transfer history data appended for: https://www.transfermarkt.com/liam-shephard/profil/spieler/197910.
Transfer history data appended for: https://www.transfermarkt.com/ryan-taylor/profil/spieler/49459.
Transfer history data appended for: https://www.transfermarkt.com/joss-labadie/profil/spieler/121807.
Transfer history data appended for: https://www.transfermarkt.com/kevin-ellison/profil/spieler/16881.
Transfer history data appended for: https://www.transfermarkt.com/aaron-lewis/profil/spieler/344014.
Transfer history data appended for: https://www.transfermarkt.com/brandon-cooper/profil/spieler/404381.
Transfer history data appended for: https://www.transfermarkt.com/josh-sheehan/profil/spieler/197830.
Transfer history data appended for: https://www.transfermarkt.com/bradley-webb/profil/spieler/804473.
Transfer history data appended for: https://www.transfermarkt.com/scott-twine/profil/spieler/433818.
Transfer history data appended for: https://www.transfermarkt.com/kyle-howkins/profil/spieler/261297.
Transfer history data appended for: https://www.transfermarkt.com/scot-bennett/profil/spieler/124240.
Transfer history data appended for: https://www.transfermarkt.com/david-longe-king/profil/spieler/678387.

Transfer history data appended for: https://www.transfermarkt.com/robbie-willmott/profil/spieler/66501.
Transfer history data appended for: https://www.transfermarkt.com/ryan-haynes/profil/spieler/265306.
Transfer history data appended for: https://www.transfermarkt.com/matt-dolan/profil/spieler/163523.
Transfer history data appended for: https://www.transfermarkt.com/padraig-amond/profil/spieler/68333.
Transfer history data appended for: https://www.transfermarkt.com/jamie-proctor/profil/spieler/128420.
Transfer history data appended for: https://www.transfermarkt.com/ash-baker/profil/spieler/527493.
Transfer history data appended for: https://www.transfermarkt.com/tristan-abrahams/profil/spieler/492391.
Transfer history data appended for: https://www.transfermarkt.com/saikou-janneh/profil/spieler/607199.
Transfer history data appended for: https://www.transfermarkt.com/jamie-devitt/profil/spieler/85662.
Transfer history data appended for: https://www.transfermarkt.com/enea-mihaj/profil/spieler/448920.
Transfer history data appended for: https://www.transfermarkt.com/theocharis-tsingaras/profil/spieler/464530.
Transfer history data appended for: https://www.transfermarkt.com/diego-biseswar/profil/spieler/35884.
Transfer history data appended for: https://www.transfermarkt.com/andrija-zivkovic/profil/spieler/206843.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo/profil/spieler/388236.
Transfer history data appended for: https://www.transfermarkt.com/giannis-michailidis/profil/spieler/464528.
Transfer history data appended for: https://www.transfermarkt.com/christos-talichmanidis/profil/spieler/540058.
Transfer history data appended for: https://www.transfermarkt.com/leo-jaba/profil/spieler/468260.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-giannoulis/profil/spieler/295630.
Transfer history data appended for: https://www.transfermarkt.com/anderson-esiti/profil/spieler/245027.
Transfer history data appended for: https://www.transfermarkt.com/lefteris-lyratzis/profil/spieler/390125.
Transfer history data appended for: https://www.transfermarkt.com/adrian-nilsen-pereira/profil/spieler/507310.
Transfer history data appended for: https://www.transfermarkt.com/karol-swiderski/profil/spieler/330126.
Transfer history data appended for: https://www.transfermarkt.com/christos-tzolis/profil/spieler/451677.
Transfer history data appended for: https://www.transfermarkt.com/douglas-augusto/profil/spieler/393621.
Transfer history data appended for: https://www.transfermarkt.com/sverrir-ingi-ingason/profil/spieler/137648.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-paschalakis/profil/spieler/88348.
Transfer history data appended for: https://www.transfermarkt.com/fernando-varela/profil/spieler/59084.
Transfer history data appended for: https://www.transfermarkt.com/moussa-wague/profil/spieler/364240.
Transfer history data appended for: https://www.transfermarkt.com/stefan-schwab/profil/spieler/79612.
Transfer history data appended for: https://www.transfermarkt.com/vieirinha/profil/spieler/35247.
Transfer history data appended for: https://www.transfermarkt.com/georgios-vrakas/profil/spieler/481692.
Transfer history data appended for: https://www.transfermarkt.com/zivko-zivkovic/profil/spieler/51161.
Transfer history data appended for: https://www.transfermarkt.com/thomas-murg/profil/spieler/153190.
Transfer history data appended for: https://www.transfermarkt.com/georgios-koutsias/profil/spieler/724039.
Transfer history data appended for: https://www.transfermarkt.com/nikoloz-ninua/profil/spieler/345194.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-rey/profil/spieler/166591.
Transfer history data appended for: https://www.transfermarkt.com/athanasios-michopoulos/profil/spieler/627756.
Transfer history data appended for: https://www.transfermarkt.com/juan-munafo/profil/spieler/127236.
Transfer history data appended for: https://www.transfermarkt.com/ruben-garcia/profil/spieler/361238.
Transfer history data appended for: https://www.transfermarkt.com/luis-fernandez/profil/spieler/230212.
Transfer history data appended for: https://www.transfermarkt.com/sito/profil/spieler/320259.
Transfer history data appended for: https://www.transfermarkt.com/brian-orosco/profil/spieler/495124.
Transfer history data appended for: https://www.transfermarkt.com/adrian-riera/profil/spieler/381206.
Transfer history data appended for: https://www.transfermarkt.com/borja-fernandez/profil/spieler/271988.
Transfer history data appended for: https://www.transfermarkt.com/georgios-kanellopoulos/profil/spieler/534675.
Transfer history data appended for: https://www.transfermarkt.com/leo-tilica/profil/spieler/393839.
Transfer history data appended for: https://www.transfermarkt.com/matias-iglesias/profil/spieler/57013.
Transfer history data appended for: https://www.transfermarkt.com/crespi/profil/spieler/391332.
Transfer history data appended for: https://www.transfermarkt.com/franco-bellocq/profil/spieler/334058.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-kardaris/profil/spieler/584447.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-papadopoulos/profil/spieler/169687.
Transfer history data appended for: https://www.transfermarkt.com/pepe-castano/profil/spieler/354742.
Transfer history data appended for: https://www.transfermarkt.com/triantafyllos-pasalidis/profil/spieler/470422.
Transfer history data appended for: https://www.transfermarkt.com/dani-suarez/profil/spieler/161255.
Transfer history data appended for: https://www.transfermarkt.com/federico-alvarez/profil/spieler/289117.
Transfer history data appended for: https://www.transfermarkt.com/antonis-tsiftsis/profil/spieler/390539.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-tzimas/profil/spieler/540064.
Transfer history data appended for: https://www.transfermarkt.com/eneko-capilla/profil/spieler/289241.
Transfer history data appended for: https://www.transfermarkt.com/ilias-christopoulos/profil/spieler/638196.
Transfer history data appended for: https://www.transfermarkt.com/oluwatobiloba-alagbe/profil/spieler/635803.
Transfer history data appended for: https://www.transfermarkt.com/giannis-kotsiras/profil/spieler/436916.
Transfer history data appended for: https://www.transfermarkt.com/giannis-christopoulos/profil/spieler/534677.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-valiente/profil/spieler/337152.
Transfer history data appended for: https://www.transfermarkt.com/sudais-ali-baba/profil/spieler/635802.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-gomez/profil/spieler/247672.
Transfer history data appended for: https://www.transfermarkt.com/fotis-sgouris/profil/spieler/707103.
Transfer history data appended for: https://www.transfermarkt.com/angelos-zioulis/profil/spieler/343157.
Transfer history data appended for: https://www.transfermarkt.com/adam-tzanetopoulos/profil/spieler/281919.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-stamoulis/profil/spieler/567505.
Transfer history data appended for: https://www.transfermarkt.com/bachana-arabuli/profil/spieler/178838.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-provydakis/profil/spieler/589899.
Transfer history data appended for: https://www.transfermarkt.com/milos-deletic/profil/spieler/203608.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-kostikas/profil/spieler/609646.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-niasse/profil/spieler/79423.
Transfer history data appended for: https://www.transfermarkt.com/giannis-skondras/profil/spieler/67831.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-karamanos/profil/spieler/127826.
Transfer history data appended for: https://www.transfermarkt.com/theodoros-vasilakakis/profil/spieler/69576.
Transfer history data appended for: https://www.transfermarkt.com/miguel-bianconi/profil/spieler/62832.
Transfer history data appended for: https://www.transfermarkt.com/devis-epassy/profil/spieler/170471.

Transfer history data appended for: https://www.transfermarkt.com/daniel-adejo/profil/spieler/88242.
Transfer history data appended for: https://www.transfermarkt.com/athanasios-margaritis/profil/spieler/357191.
Transfer history data appended for: https://www.transfermarkt.com/zisis-chatzistravos/profil/spieler/464535.
Transfer history data appended for: https://www.transfermarkt.com/danny-bejarano/profil/spieler/234761.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-nikolopoulos/profil/spieler/655151.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-villalba/profil/spieler/269817.
Transfer history data appended for: https://www.transfermarkt.com/andreas-vasilogiannis/profil/spieler/63491.
Transfer history data appended for: https://www.transfermarkt.com/patrick-bahanack/profil/spieler/534471.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-bouloulis/profil/spieler/207376.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-theodoropoulos/profil/spieler/139546.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-tsoukalos/profil/spieler/256819.
Transfer history data appended for: https://www.transfermarkt.com/anestis-vlachomitros/profil/spieler/623173.
Transfer history data appended for: https://www.transfermarkt.com/guga-palavandishvili/profil/spieler/204487.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-katsikas/profil/spieler/530131.
Transfer history data appended for: https://www.transfermarkt.com/loukas-vyntra/profil/spieler/16458.
Transfer history data appended for: https://www.transfermarkt.com/lazar-romanic/profil/spieler/478601.
Transfer history data appended for: https://www.transfermarkt.com/georgios-saramantas/profil/spieler/295755.
Transfer history data appended for: https://www.transfermarkt.com/mark-asigba/profil/spieler/286077.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-tsintotas/profil/spieler/164729.
Transfer history data appended for: https://www.transfermarkt.com/giannis-fivos-botos/profil/spieler/486057.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-chygrynskyi/profil/spieler/25732.
Transfer history data appended for: https://www.transfermarkt.com/nassim-hnid/profil/spieler/415679.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-chatziemmanouil/profil/spieler/420921.
Transfer history data appended for: https://www.transfermarkt.com/georgios-theocharis/profil/spieler/618565.
Transfer history data appended for: https://www.transfermarkt.com/anel-sabanadzovic/profil/spieler/376106.
Transfer history data appended for: https://www.transfermarkt.com/efthymios-christopoulos/profil/spieler/416490.
Transfer history data appended for: https://www.transfermarkt.com/helder-lopes/profil/spieler/171068.
Transfer history data appended for: https://www.transfermarkt.com/petar-karaklajic/profil/spieler/697016.
Transfer history data appended for: https://www.transfermarkt.com/stavros-vasilantonopoulos/profil/spieler/233264.
Transfer history data appended for: https://www.transfermarkt.com/ionut-nedelcearu/profil/spieler/274694.
Transfer history data appended for: https://www.transfermarkt.com/karim-ansarifard/profil/spieler/133838.
Transfer history data appended for: https://www.transfermarkt.com/andre-simoes/profil/spieler/131574.
Transfer history data appended for: https://www.transfermarkt.com/theodosis-macheras/profil/spieler/584548.
Transfer history data appended for: https://www.transfermarkt.com/paulinho/profil/spieler/85771.
Transfer history data appended for: https://www.transfermarkt.com/georgios-athanasiadis/profil/spieler/234888.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-insua/profil/spieler/226006.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-galanopoulos/profil/spieler/370885.
Transfer history data appended for: https://www.transfermarkt.com/mario-mitaj/profil/spieler/726114.
Transfer history data appended for: https://www.transfermarkt.com/nenad-krsticic/profil/spieler/56790.
Transfer history data appended for: https://www.transfermarkt.com/christos-albanis/profil/spieler/184885.
Transfer history data appended for: https://www.transfermarkt.com/david-simao/profil/spieler/70359.
Transfer history data appended for: https://www.transfermarkt.com/muamer-tankovic/profil/spieler/198513.
Transfer history data appended for: https://www.transfermarkt.com/michalis-bakakis/profil/spieler/130142.
Transfer history data appended for: https://www.transfermarkt.com/levi-garcia/profil/spieler/354587.
Transfer history data appended for: https://www.transfermarkt.com/ziga-laci/profil/spieler/651842.
Transfer history data appended for: https://www.transfermarkt.com/stratos-svarnas/profil/spieler/318257.
Transfer history data appended for: https://www.transfermarkt.com/petros-mantalos/profil/spieler/128011.
Transfer history data appended for: https://www.transfermarkt.com/giannis-sardelis/profil/spieler/569488.
Transfer history data appended for: https://www.transfermarkt.com/vedad-radonja/profil/spieler/461717.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-shakhov/profil/spieler/58970.
Transfer history data appended for: https://www.transfermarkt.com/abdul-rahman-weiss/profil/spieler/504592.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-vafeas/profil/spieler/333098.
Transfer history data appended for: https://www.transfermarkt.com/adil-nabi/profil/spieler/181554.
Transfer history data appended for: https://www.transfermarkt.com/frixos-grivas/profil/spieler/623640.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-sotiriou/profil/spieler/12880.
Transfer history data appended for: https://www.transfermarkt.com/kosmas-tsilianidis/profil/spieler/243302.
Transfer history data appended for: https://www.transfermarkt.com/felipe-souza-ferreyra/profil/spieler/651417.
Transfer history data appended for: https://www.transfermarkt.com/vahid-selimovic/profil/spieler/351072.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-vaz/profil/spieler/304214.
Transfer history data appended for: https://www.transfermarkt.com/adrian-sardinero/profil/spieler/125870.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-marinakis/profil/spieler/143852.
Transfer history data appended for: https://www.transfermarkt.com/vajebah-sakor/profil/spieler/179838.
Transfer history data appended for: https://www.transfermarkt.com/paschalis-staikos/profil/spieler/242668.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-balogiannis/profil/spieler/460625.
Transfer history data appended for: https://www.transfermarkt.com/apostolos-diamantis/profil/spieler/464529.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-giannoulis/profil/spieler/34289.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-korovesis/profil/spieler/231172.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-sifakis/profil/spieler/623160.
Transfer history data appended for: https://www.transfermarkt.com/juan-neira/profil/spieler/56831.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-gargalatzidis/profil/spieler/390124.
Transfer history data appended for: https://www.transfermarkt.com/praxitelis-vouros/profil/spieler/136645.
Transfer history data appended for: https://www.transfermarkt.com/odysseas-lymperakis/profil/spieler/640686.
Transfer history data appended for: https://www.transfermarkt.com/fabio-sturgeon/profil/spieler/194641.
Transfer history data appended for: https://www.transfermarkt.com/nazareno-solis/profil/spieler/419660.
Transfer history data appended for: https://www.transfermarkt.com/vangelis-nikokyrakis/profil/spieler/582949.
Transfer history data appended for: https://www.transfermarkt.com/georgios-sournakis/profil/spieler/623142.
Transfer history data appended for: https://www.transfermarkt.com/apostolos-giannou/profil/spieler/51166.

Transfer history data appended for: https://www.transfermarkt.com/theodoros-mingos/profil/spieler/342253.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-de-guzman/profil/spieler/31067.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-kotsopoulos/profil/spieler/555519.
Transfer history data appended for: https://www.transfermarkt.com/spyros-risvanis/profil/spieler/279869.
Transfer history data appended for: https://www.transfermarkt.com/clarck-nsikulu/profil/spieler/164937.
Transfer history data appended for: https://www.transfermarkt.com/charilaos-charisis/profil/spieler/257482.
Transfer history data appended for: https://www.transfermarkt.com/georgios-daviotis/profil/spieler/402963.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-galo/profil/spieler/75118.
Transfer history data appended for: https://www.transfermarkt.com/antonis-trimmatis/profil/spieler/533239.
Transfer history data appended for: https://www.transfermarkt.com/spyros-natsos/profil/spieler/324348.
Transfer history data appended for: https://www.transfermarkt.com/giannis-ikonomidis/profil/spieler/446529.
Transfer history data appended for: https://www.transfermarkt.com/petros-giakoumakis/profil/spieler/332802.
Transfer history data appended for: https://www.transfermarkt.com/josip-tomasevic/profil/spieler/160514.
Transfer history data appended for: https://www.transfermarkt.com/kyriakos-kivrakidis/profil/spieler/242760.
Transfer history data appended for: https://www.transfermarkt.com/azer-busuladzic/profil/spieler/106039.
Transfer history data appended for: https://www.transfermarkt.com/patrick-salomon/profil/spieler/51541.
Transfer history data appended for: https://www.transfermarkt.com/juan-muniz/profil/spieler/85357.
Transfer history data appended for: https://www.transfermarkt.com/javier-umbides/profil/spieler/87381.
Transfer history data appended for: https://www.transfermarkt.com/bojan-matic/profil/spieler/439459.
Transfer history data appended for: https://www.transfermarkt.com/georgios-manousos/profil/spieler/79286.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-athanasiou/profil/spieler/623072.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-goutas/profil/spieler/191829.
Transfer history data appended for: https://www.transfermarkt.com/christos-theodorakis/profil/spieler/329899.
Transfer history data appended for: https://www.transfermarkt.com/lucas-galvao/profil/spieler/104540.
Transfer history data appended for: https://www.transfermarkt.com/stefanos-stroungis/profil/spieler/348298.
Transfer history data appended for: https://www.transfermarkt.com/lazaros-christodoulopoulos/profil/spieler/34283.
Transfer history data appended for: https://www.transfermarkt.com/andreas-gianniotis/profil/spieler/226802.
Transfer history data appended for: https://www.transfermarkt.com/christos-mandas/profil/spieler/481675.
Transfer history data appended for: https://www.transfermarkt.com/amir-agayev/profil/spieler/184309.
Transfer history data appended for: https://www.transfermarkt.com/bryan-rabello/profil/spieler/160217.
Transfer history data appended for: https://www.transfermarkt.com/mohammad-reza-azadi/profil/spieler/524923.
Transfer history data appended for: https://www.transfermarkt.com/dalcio/profil/spieler/323589.
Transfer history data appended for: https://www.transfermarkt.com/christos-kalantzis/profil/spieler/586537.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-parras/profil/spieler/529596.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-malis/profil/spieler/448919.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-vergos/profil/spieler/118302.
Transfer history data appended for: https://www.transfermarkt.com/franco-mazurek/profil/spieler/267911.
Transfer history data appended for: https://www.transfermarkt.com/javier-mendoza/profil/spieler/300309.
Transfer history data appended for: https://www.transfermarkt.com/spyros-skondras/profil/spieler/623059.
Transfer history data appended for: https://www.transfermarkt.com/aymen-tahar/profil/spieler/104127.
Transfer history data appended for: https://www.transfermarkt.com/angelos-tsingaras/profil/spieler/609647.
Transfer history data appended for: https://www.transfermarkt.com/jorge-diaz/profil/spieler/240026.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-mazzola/profil/spieler/90797.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-skiadas/profil/spieler/570064.
Transfer history data appended for: https://www.transfermarkt.com/gerasimos-bakadimas/profil/spieler/623048.
Transfer history data appended for: https://www.transfermarkt.com/paolo-medina/profil/spieler/370863.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-melissas/profil/spieler/199179.
Transfer history data appended for: https://www.transfermarkt.com/luis-mosquera/profil/spieler/601321.
Transfer history data appended for: https://www.transfermarkt.com/apostolos-konstantopoulos/profil/spieler/554393.
Transfer history data appended for: https://www.transfermarkt.com/vanderson/profil/spieler/56761.
Transfer history data appended for: https://www.transfermarkt.com/elias-pereyra/profil/spieler/576027.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-arzura/profil/spieler/288005.
Transfer history data appended for: https://www.transfermarkt.com/aristotelis-karasalidis/profil/spieler/207573.
Transfer history data appended for: https://www.transfermarkt.com/georgios-liavas/profil/spieler/481676.
Transfer history data appended for: https://www.transfermarkt.com/juan-alvarez/profil/spieler/457537.
Transfer history data appended for: https://www.transfermarkt.com/gboly-ariyibi/profil/spieler/226958.
Transfer history data appended for: https://www.transfermarkt.com/frederico-duarte/profil/spieler/461936.
Transfer history data appended for: https://www.transfermarkt.com/vangelis-kontogiannis/profil/spieler/655660.
Transfer history data appended for: https://www.transfermarkt.com/manolis-tzanakakis/profil/spieler/187962.
Transfer history data appended for: https://www.transfermarkt.com/christopher-knett/profil/spieler/70164.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-kourbelis/profil/spieler/157543.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-xenopoulos/profil/spieler/450427.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-zagaritis/profil/spieler/613781.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-emmanouilidis/profil/spieler/468036.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-christogeorgos/profil/spieler/567668.
Transfer history data appended for: https://www.transfermarkt.com/ilias-chatzitheodoridis/profil/spieler/340308.
Transfer history data appended for: https://www.transfermarkt.com/sotiris-alexandropoulos/profil/spieler/481688.
Transfer history data appended for: https://www.transfermarkt.com/fran-velez/profil/spieler/147078.
Transfer history data appended for: https://www.transfermarkt.com/spyros-tzavidas/profil/spieler/540060.
Transfer history data appended for: https://www.transfermarkt.com/lucas-villafanez/profil/spieler/125918.
Transfer history data appended for: https://www.transfermarkt.com/yassin-ayoub/profil/spieler/182573.
Transfer history data appended for: https://www.transfermarkt.com/antonito/profil/spieler/62144.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-karagiannis/profil/spieler/481679.
Transfer history data appended for: https://www.transfermarkt.com/andreas-athanasakopoulos/profil/spieler/540059.
Transfer history data appended for: https://www.transfermarkt.com/uffe-bech/profil/spieler/94939.
Transfer history data appended for: https://www.transfermarkt.com/aitor-cantalapiedra/profil/spieler/323740.
Transfer history data appended for: https://www.transfermarkt.com/bart-schenkeveld/profil/spieler/124895.
Transfer history data appended for: https://www.transfermarkt.com/juankar/profil/spieler/126625.

Transfer history data appended for: https://www.transfermarkt.com/dimitrios-serpezis/profil/spieler/481690.
Transfer history data appended for: https://www.transfermarkt.com/argyris-kampetsis/profil/spieler/369103.
Transfer history data appended for: https://www.transfermarkt.com/carlitos/profil/spieler/228885.
Transfer history data appended for: https://www.transfermarkt.com/facundo-sanchez/profil/spieler/107523.
Transfer history data appended for: https://www.transfermarkt.com/christos-chatzigiannakis/profil/spieler/567491.
Transfer history data appended for: https://www.transfermarkt.com/giannis-bouzoukis/profil/spieler/355761.
Transfer history data appended for: https://www.transfermarkt.com/kristo-shehu/profil/spieler/454287.
Transfer history data appended for: https://www.transfermarkt.com/fotis-ioannidis/profil/spieler/532444.
Transfer history data appended for: https://www.transfermarkt.com/sokratis-dioudis/profil/spieler/187798.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-chatzigiovanis/profil/spieler/402887.
Transfer history data appended for: https://www.transfermarkt.com/mauricio/profil/spieler/53286.
Transfer history data appended for: https://www.transfermarkt.com/achilleas-poungouras/profil/spieler/255688.
Transfer history data appended for: https://www.transfermarkt.com/xavier/profil/spieler/243783.
Transfer history data appended for: https://www.transfermarkt.com/theofanis-mavrommatis/profil/spieler/370889.
Transfer history data appended for: https://www.transfermarkt.com/dimosthenis-baxevanidis/profil/spieler/58312.
Transfer history data appended for: https://www.transfermarkt.com/israel-coll/profil/spieler/267732.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-ioannidis/profil/spieler/182685.
Transfer history data appended for: https://www.transfermarkt.com/abiola-dauda/profil/spieler/69651.
Transfer history data appended for: https://www.transfermarkt.com/theodoros-chiritrantas/profil/spieler/707610.
Transfer history data appended for: https://www.transfermarkt.com/davino-verhulst/profil/spieler/33480.
Transfer history data appended for: https://www.transfermarkt.com/christos-lisgaras/profil/spieler/19638.
Transfer history data appended for: https://www.transfermarkt.com/marc-fernandez/profil/spieler/176298.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-lagos/profil/spieler/68418.
Transfer history data appended for: https://www.transfermarkt.com/ritchie-kitoko/profil/spieler/42732.
Transfer history data appended for: https://www.transfermarkt.com/thomas-bedinelli/profil/spieler/184299.
Transfer history data appended for: https://www.transfermarkt.com/sotiris-tsiloulis/profil/spieler/237923.
Transfer history data appended for: https://www.transfermarkt.com/georgios-rodis/profil/spieler/623543.
Transfer history data appended for: https://www.transfermarkt.com/domingues/profil/spieler/393451.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-vitlis/profil/spieler/381913.
Transfer history data appended for: https://www.transfermarkt.com/manolis-kragiopoulos/profil/spieler/428012.
Transfer history data appended for: https://www.transfermarkt.com/manolis-patralis/profil/spieler/292361.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-kotsaris/profil/spieler/242637.
Transfer history data appended for: https://www.transfermarkt.com/athanasios-karagounis/profil/spieler/105811.
Transfer history data appended for: https://www.transfermarkt.com/leonidas-rossi/profil/spieler/597733.
Transfer history data appended for: https://www.transfermarkt.com/adil-rhaili/profil/spieler/262953.
Transfer history data appended for: https://www.transfermarkt.com/fatjon-andoni/profil/spieler/164580.
Transfer history data appended for: https://www.transfermarkt.com/karlo-brucic/profil/spieler/115447.
Transfer history data appended for: https://www.transfermarkt.com/anthony-mounier/profil/spieler/57110.
Transfer history data appended for: https://www.transfermarkt.com/savvas-tsabouris/profil/spieler/96818.
Transfer history data appended for: https://www.transfermarkt.com/diamantis-chouchoumis/profil/spieler/212430.
Transfer history data appended for: https://www.transfermarkt.com/giannis-varkas/profil/spieler/324512.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-giannakopoulos/profil/spieler/114530.
Transfer history data appended for: https://www.transfermarkt.com/juan-dominguez/profil/spieler/72195.
Transfer history data appended for: https://www.transfermarkt.com/jean-baptiste-leo/profil/spieler/290613.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-erramuspe/profil/spieler/112091.
Transfer history data appended for: https://www.transfermarkt.com/pavlos-grosdanis/profil/spieler/655487.
Transfer history data appended for: https://www.transfermarkt.com/georgios-pamlidis/profil/spieler/336104.
Transfer history data appended for: https://www.transfermarkt.com/fabricio-brener/profil/spieler/534617.
Transfer history data appended for: https://www.transfermarkt.com/angelos-liasos/profil/spieler/494679.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-lolis/profil/spieler/655626.
Transfer history data appended for: https://www.transfermarkt.com/christos-eleftheriadis/profil/spieler/210988.
Transfer history data appended for: https://www.transfermarkt.com/giannis-kargas/profil/spieler/242758.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-naumets/profil/spieler/404845.
Transfer history data appended for: https://www.transfermarkt.com/stavros-pilios/profil/spieler/572879.
Transfer history data appended for: https://www.transfermarkt.com/georgios-doumtsis/profil/spieler/586709.
Transfer history data appended for: https://www.transfermarkt.com/sandi-krizman/profil/spieler/47637.
Transfer history data appended for: https://www.transfermarkt.com/pantelis-panourgias/profil/spieler/297013.
Transfer history data appended for: https://www.transfermarkt.com/manolis-saliakas/profil/spieler/242661.
Transfer history data appended for: https://www.transfermarkt.com/antonis-ikonomopoulos/profil/spieler/342252.
Transfer history data appended for: https://www.transfermarkt.com/marvin-peersman/profil/spieler/125769.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-athanasiou/profil/spieler/457620.
Transfer history data appended for: https://www.transfermarkt.com/lefteris-choutesiotis/profil/spieler/182682.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-kartalis/profil/spieler/195704.
Transfer history data appended for: https://www.transfermarkt.com/epaminondas-pantelakis/profil/spieler/286533.
Transfer history data appended for: https://www.transfermarkt.com/makis-giannikoglou/profil/spieler/266203.
Transfer history data appended for: https://www.transfermarkt.com/fabry-castro/profil/spieler/260741.
Transfer history data appended for: https://www.transfermarkt.com/georgios-xydas/profil/spieler/351487.
Transfer history data appended for: https://www.transfermarkt.com/georgios-gogos/profil/spieler/540062.
Transfer history data appended for: https://www.transfermarkt.com/tim-sparv/profil/spieler/13258.
Transfer history data appended for: https://www.transfermarkt.com/georgios-zacharakis/profil/spieler/537474.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-loufakis/profil/spieler/643356.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-torje/profil/spieler/47184.
Transfer history data appended for: https://www.transfermarkt.com/spyros-glynos/profil/spieler/524207.
Transfer history data appended for: https://www.transfermarkt.com/gergely-nagy/profil/spieler/170672.
Transfer history data appended for: https://www.transfermarkt.com/orestis-grigoropoulos/profil/spieler/584562.
Transfer history data appended for: https://www.transfermarkt.com/marko-nunic/profil/spieler/201668.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-pinakas/profil/spieler/586232.
Transfer history data appended for: https://www.transfermarkt.com/manolis-bertos/profil/spieler/72490.

Transfer history data appended for: https://www.transfermarkt.com/steliano-filip/profil/spieler/181501.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-gotzamanidis/profil/spieler/465868.
Transfer history data appended for: https://www.transfermarkt.com/vangelis-platellas/profil/spieler/96464.
Transfer history data appended for: https://www.transfermarkt.com/charilaos-fourkiotis/profil/spieler/596094.
Transfer history data appended for: https://www.transfermarkt.com/nikola-zizic/profil/spieler/174563.
Transfer history data appended for: https://www.transfermarkt.com/ioannis-kosti/profil/spieler/435288.
Transfer history data appended for: https://www.transfermarkt.com/stefanos-souloukos/profil/spieler/580281.
Transfer history data appended for: https://www.transfermarkt.com/radomir-milosavljevic/profil/spieler/145339.
Transfer history data appended for: https://www.transfermarkt.com/alexios-michail/profil/spieler/67071.
Transfer history data appended for: https://www.transfermarkt.com/georgios-maidanos/profil/spieler/668502.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-bajic/profil/spieler/146036.
Transfer history data appended for: https://www.transfermarkt.com/mateo-muzek/profil/spieler/270930.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-chalatsis/profil/spieler/596097.
Transfer history data appended for: https://www.transfermarkt.com/theocharis-iliadis/profil/spieler/484367.
Transfer history data appended for: https://www.transfermarkt.com/nikola-trujic/profil/spieler/94348.
Transfer history data appended for: https://www.transfermarkt.com/fiorin-durmishaj/profil/spieler/331672.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-nikolias/profil/spieler/230968.
Transfer history data appended for: https://www.transfermarkt.com/hamza-younes/profil/spieler/111995.
Transfer history data appended for: https://www.transfermarkt.com/ousseynou-ba/profil/spieler/520815.
Transfer history data appended for: https://www.transfermarkt.com/tiago-silva/profil/spieler/236997.
Transfer history data appended for: https://www.transfermarkt.com/pape-abou-cisse/profil/spieler/364234.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-sourlis/profil/spieler/554398.
Transfer history data appended for: https://www.transfermarkt.com/ilias-karargyris/profil/spieler/537944.
Transfer history data appended for: https://www.transfermarkt.com/apostolos-apostolopoulos/profil/spieler/672314.
Transfer history data appended for: https://www.transfermarkt.com/jose-cholevas/profil/spieler/41112.
Transfer history data appended for: https://www.transfermarkt.com/andreas-bouchalakis/profil/spieler/157535.
Transfer history data appended for: https://www.transfermarkt.com/hugo-cuypers/profil/spieler/420884.
Transfer history data appended for: https://www.transfermarkt.com/yann-mvila/profil/spieler/60573.
Transfer history data appended for: https://www.transfermarkt.com/lazar-randjelovic/profil/spieler/512394.
Transfer history data appended for: https://www.transfermarkt.com/ogmundur-kristinsson/profil/spieler/103444.
Transfer history data appended for: https://www.transfermarkt.com/bruma/profil/spieler/139396.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-valbuena/profil/spieler/40687.
Transfer history data appended for: https://www.transfermarkt.com/avraam-papadopoulos/profil/spieler/12979.
Transfer history data appended for: https://www.transfermarkt.com/rafinha/profil/spieler/33947.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-fortounis/profil/spieler/157539.
Transfer history data appended for: https://www.transfermarkt.com/jose-sa/profil/spieler/249994.
Transfer history data appended for: https://www.transfermarkt.com/bruno/profil/spieler/367255.
Transfer history data appended for: https://www.transfermarkt.com/ruben-vinagre/profil/spieler/357158.
Transfer history data appended for: https://www.transfermarkt.com/mady-camara/profil/spieler/481173.
Transfer history data appended for: https://www.transfermarkt.com/ruben-semedo/profil/spieler/197602.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-tzolakis/profil/spieler/554389.
Transfer history data appended for: https://www.transfermarkt.com/athanasios-androutsos/profil/spieler/341680.
Transfer history data appended for: https://www.transfermarkt.com/georgios-masouras/profil/spieler/329517.
Transfer history data appended for: https://www.transfermarkt.com/el-arbi-hillel-soudani/profil/spieler/174842.
Transfer history data appended for: https://www.transfermarkt.com/pepe/profil/spieler/258018.
Transfer history data appended for: https://www.transfermarkt.com/marios-vrousai/profil/spieler/395632.
Transfer history data appended for: https://www.transfermarkt.com/youssef-el-arabi/profil/spieler/96533.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-lovera/profil/spieler/441422.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-douvikas/profil/spieler/523318.
Transfer history data appended for: https://www.transfermarkt.com/daan-rienstra/profil/spieler/277772.
Transfer history data appended for: https://www.transfermarkt.com/jean-barrientos/profil/spieler/118413.
Transfer history data appended for: https://www.transfermarkt.com/georgios-kanellakis/profil/spieler/540063.
Transfer history data appended for: https://www.transfermarkt.com/boris-klaiman/profil/spieler/177475.
Transfer history data appended for: https://www.transfermarkt.com/amr-warda/profil/spieler/237641.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-kravaritis/profil/spieler/590147.
Transfer history data appended for: https://www.transfermarkt.com/gerasimos-mitoglou/profil/spieler/684519.
Transfer history data appended for: https://www.transfermarkt.com/giannis-kiakos/profil/spieler/451311.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-colombo/profil/spieler/334082.
Transfer history data appended for: https://www.transfermarkt.com/julian-bartolo/profil/spieler/610570.
Transfer history data appended for: https://www.transfermarkt.com/iker-guarrotxena/profil/spieler/82471.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-tsokanis/profil/spieler/5336.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-karagiozis/profil/spieler/399360.
Transfer history data appended for: https://www.transfermarkt.com/salvador-sanchez/profil/spieler/376860.
Transfer history data appended for: https://www.transfermarkt.com/athanasios-garavelis/profil/spieler/286392.
Transfer history data appended for: https://www.transfermarkt.com/juan-jose-perea/profil/spieler/496767.
Transfer history data appended for: https://www.transfermarkt.com/symeon-papadopoulos/profil/spieler/586712.
Transfer history data appended for: https://www.transfermarkt.com/georgios-ballas/profil/spieler/711579.
Transfer history data appended for: https://www.transfermarkt.com/pavlos-logaras/profil/spieler/711575.
Transfer history data appended for: https://www.transfermarkt.com/antonis-dentakis/profil/spieler/280080.
Transfer history data appended for: https://www.transfermarkt.com/stergios-dimopoulos/profil/spieler/139405.
Transfer history data appended for: https://www.transfermarkt.com/sotiris-ninis/profil/spieler/46062.
Transfer history data appended for: https://www.transfermarkt.com/franco-ferrari/profil/spieler/540466.
Transfer history data appended for: https://www.transfermarkt.com/tekio/profil/spieler/198866.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-kritikos/profil/spieler/237893.
Transfer history data appended for: https://www.transfermarkt.com/lerin-duarte/profil/spieler/92842.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-sengergis/profil/spieler/623253.
Transfer history data appended for: https://www.transfermarkt.com/julian-cuesta/profil/spieler/176936.
Transfer history data appended for: https://www.transfermarkt.com/ali-adem/profil/spieler/570788.

Transfer history data appended for: https://www.transfermarkt.com/zacharie-boucher/profil/spieler/111041.
Transfer history data appended for: https://www.transfermarkt.com/georgios-delizisis/profil/spieler/132010.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-sakic/profil/spieler/75413.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-tsagalidis/profil/spieler/537956.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-manos/profil/spieler/206563.
Transfer history data appended for: https://www.transfermarkt.com/xande-silva/profil/spieler/258011.
Transfer history data appended for: https://www.transfermarkt.com/facundo-bertoglio/profil/spieler/107525.
Transfer history data appended for: https://www.transfermarkt.com/james-jeggo/profil/spieler/179467.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-chatzipirpiridis/profil/spieler/623214.
Transfer history data appended for: https://www.transfermarkt.com/ergys-kace/profil/spieler/173405.
Transfer history data appended for: https://www.transfermarkt.com/fabian-ehmann/profil/spieler/290088.
Transfer history data appended for: https://www.transfermarkt.com/mateo-garcia/profil/spieler/441287.
Transfer history data appended for: https://www.transfermarkt.com/petros-bakoutsis/profil/spieler/609649.
Transfer history data appended for: https://www.transfermarkt.com/apostolos-martinis/profil/spieler/481677.
Transfer history data appended for: https://www.transfermarkt.com/javier-matilla/profil/spieler/73269.
Transfer history data appended for: https://www.transfermarkt.com/cristian-lopez/profil/spieler/114282.
Transfer history data appended for: https://www.transfermarkt.com/christos-marmaridis/profil/spieler/672694.
Transfer history data appended for: https://www.transfermarkt.com/daniel-sundgren/profil/spieler/107612.
Transfer history data appended for: https://www.transfermarkt.com/bruno-gama/profil/spieler/15568.
Transfer history data appended for: https://www.transfermarkt.com/marios-siabanis/profil/spieler/324352.
Transfer history data appended for: https://www.transfermarkt.com/daniel-mancini/profil/spieler/381348.
Transfer history data appended for: https://www.transfermarkt.com/cristian-ganea/profil/spieler/262117.
Transfer history data appended for: https://www.transfermarkt.com/petros-bagalianis/profil/spieler/609648.
Transfer history data appended for: https://www.transfermarkt.com/toni-datkovic/profil/spieler/227015.
Transfer history data appended for: https://www.transfermarkt.com/lucas-sasha/profil/spieler/121986.
Transfer history data appended for: https://www.transfermarkt.com/lindsay-rose/profil/spieler/135490.
Transfer history data appended for: https://www.transfermarkt.com/teemu-penninkangas/profil/spieler/224027.
Transfer history data appended for: https://www.transfermarkt.com/darren-collins/profil/spieler/587685.
Transfer history data appended for: https://www.transfermarkt.com/regan-donelon/profil/spieler/326010.
Transfer history data appended for: https://www.transfermarkt.com/ronan-murray/profil/spieler/114107.
Transfer history data appended for: https://www.transfermarkt.com/brendan-ogbu/profil/spieler/260747.
Transfer history data appended for: https://www.transfermarkt.com/john-dunleavy/profil/spieler/134450.
Transfer history data appended for: https://www.transfermarkt.com/john-russell/profil/spieler/56954.
Transfer history data appended for: https://www.transfermarkt.com/brian-morley/profil/spieler/677797.
Transfer history data appended for: https://www.transfermarkt.com/scott-lynch/profil/spieler/654051.
Transfer history data appended for: https://www.transfermarkt.com/junior-ogedi-uzokwe/profil/spieler/411123.
Transfer history data appended for: https://www.transfermarkt.com/edward-mcginty/profil/spieler/478712.
Transfer history data appended for: https://www.transfermarkt.com/ronan-coughlan/profil/spieler/345282.
Transfer history data appended for: https://www.transfermarkt.com/ryan-de-vries/profil/spieler/135824.
Transfer history data appended for: https://www.transfermarkt.com/danny-kane/profil/spieler/224816.
Transfer history data appended for: https://www.transfermarkt.com/jesse-devers/profil/spieler/224804.
Transfer history data appended for: https://www.transfermarkt.com/garry-buckley/profil/spieler/225100.
Transfer history data appended for: https://www.transfermarkt.com/alex-cooper/profil/spieler/65464.
Transfer history data appended for: https://www.transfermarkt.com/john-mahon/profil/spieler/491216.
Transfer history data appended for: https://www.transfermarkt.com/lewis-banks/profil/spieler/345782.
Transfer history data appended for: https://www.transfermarkt.com/david-cawley/profil/spieler/127982.
Transfer history data appended for: https://www.transfermarkt.com/niall-morahan/profil/spieler/585658.
Transfer history data appended for: https://www.transfermarkt.com/sigitas-olberkis/profil/spieler/323611.
Transfer history data appended for: https://www.transfermarkt.com/darragh-noone/profil/spieler/433323.
Transfer history data appended for: https://www.transfermarkt.com/luke-mcnicholas/profil/spieler/653353.
Transfer history data appended for: https://www.transfermarkt.com/will-seymore/profil/spieler/266165.
Transfer history data appended for: https://www.transfermarkt.com/jamie-obrien/profil/spieler/123680.
Transfer history data appended for: https://www.transfermarkt.com/alex-cetiner/profil/spieler/798359.
Transfer history data appended for: https://www.transfermarkt.com/mark-byrne/profil/spieler/94917.
Transfer history data appended for: https://www.transfermarkt.com/jack-brady/profil/spieler/369286.
Transfer history data appended for: https://www.transfermarkt.com/shane-farrell/profil/spieler/567574.
Transfer history data appended for: https://www.transfermarkt.com/denzil-fernandes/profil/spieler/466102.
Transfer history data appended for: https://www.transfermarkt.com/brian-mcmanus/profil/spieler/634365.
Transfer history data appended for: https://www.transfermarkt.com/aaron-dobbs/profil/spieler/419619.
Transfer history data appended for: https://www.transfermarkt.com/aidan-friel/profil/spieler/377170.
Transfer history data appended for: https://www.transfermarkt.com/karl-sheppard/profil/spieler/61587.
Transfer history data appended for: https://www.transfermarkt.com/ally-gilchrist/profil/spieler/193110.
Transfer history data appended for: https://www.transfermarkt.com/lorcan-fitzgerald/profil/spieler/61571.
Transfer history data appended for: https://www.transfermarkt.com/oscar-brennan/profil/spieler/428894.
Transfer history data appended for: https://www.transfermarkt.com/gary-deegan/profil/spieler/68315.
Transfer history data appended for: https://www.transfermarkt.com/dan-byrne/profil/spieler/284987.
Transfer history data appended for: https://www.transfermarkt.com/alex-ohanlon/profil/spieler/279456.
Transfer history data appended for: https://www.transfermarkt.com/colin-mccabe/profil/spieler/224823.
Transfer history data appended for: https://www.transfermarkt.com/karl-moore/profil/spieler/61625.
Transfer history data appended for: https://www.transfermarkt.com/sean-quinn/profil/spieler/491607.
Transfer history data appended for: https://www.transfermarkt.com/ryan-brennan/profil/spieler/137591.
Transfer history data appended for: https://www.transfermarkt.com/luke-byrne/profil/spieler/217735.
Transfer history data appended for: https://www.transfermarkt.com/daniel-oreilly/profil/spieler/192282.
Transfer history data appended for: https://www.transfermarkt.com/jaze-kabia/profil/spieler/572810.
Transfer history data appended for: https://www.transfermarkt.com/georgie-poynton/profil/spieler/284066.
Transfer history data appended for: https://www.transfermarkt.com/dayle-rooney/profil/spieler/491629.
Transfer history data appended for: https://www.transfermarkt.com/ciaran-burns/profil/spieler/596333.
Transfer history data appended for: https://www.transfermarkt.com/ciaran-kilduff/profil/spieler/68337.
Transfer history data appended for: https://www.transfermarkt.com/kian-clarke/profil/spieler/495820.
Transfer history data appended for: https://www.transfermarkt.com/brandon-kavanagh/profil/spieler/469065.

Transfer history data appended for: https://www.transfermarkt.com/joey-obrien/profil/spieler/34672.
Transfer history data appended for: https://www.transfermarkt.com/danny-lafferty/profil/spieler/85928.
Transfer history data appended for: https://www.transfermarkt.com/jack-byrne/profil/spieler/217757.
Transfer history data appended for: https://www.transfermarkt.com/sean-brennan/profil/spieler/469052.
Transfer history data appended for: https://www.transfermarkt.com/roberto-lopes/profil/spieler/166158.
Transfer history data appended for: https://www.transfermarkt.com/aaron-mceneff/profil/spieler/167264.
Transfer history data appended for: https://www.transfermarkt.com/gary-oneil/profil/spieler/307513.
Transfer history data appended for: https://www.transfermarkt.com/alan-mannus/profil/spieler/62855.
Transfer history data appended for: https://www.transfermarkt.com/ronan-finn/profil/spieler/85709.
Transfer history data appended for: https://www.transfermarkt.com/aaron-greene/profil/spieler/122407.
Transfer history data appended for: https://www.transfermarkt.com/greg-bolger/profil/spieler/85713.
Transfer history data appended for: https://www.transfermarkt.com/liam-scales/profil/spieler/439497.
Transfer history data appended for: https://www.transfermarkt.com/lee-grace/profil/spieler/365180.
Transfer history data appended for: https://www.transfermarkt.com/graham-burke/profil/spieler/177892.
Transfer history data appended for: https://www.transfermarkt.com/sean-kavanagh/profil/spieler/183165.
Transfer history data appended for: https://www.transfermarkt.com/sean-callan/profil/spieler/357674.
Transfer history data appended for: https://www.transfermarkt.com/neil-farrugia/profil/spieler/491578.
Transfer history data appended for: https://www.transfermarkt.com/rhys-marshall/profil/spieler/285541.
Transfer history data appended for: https://www.transfermarkt.com/dylan-watts/profil/spieler/365201.
Transfer history data appended for: https://www.transfermarkt.com/thomas-oluwa/profil/spieler/677356.
Transfer history data appended for: https://www.transfermarkt.com/leon-pohls/profil/spieler/249247.
Transfer history data appended for: https://www.transfermarkt.com/dean-williams/profil/spieler/620402.
Transfer history data appended for: https://www.transfermarkt.com/rory-gaffney/profil/spieler/184007.
Transfer history data appended for: https://www.transfermarkt.com/david-harrington/profil/spieler/625838.
Transfer history data appended for: https://www.transfermarkt.com/cian-coleman/profil/spieler/392592.
Transfer history data appended for: https://www.transfermarkt.com/kevin-oconnor/profil/spieler/228778.
Transfer history data appended for: https://www.transfermarkt.com/alec-byrne/profil/spieler/466105.
Transfer history data appended for: https://www.transfermarkt.com/reyon-dillon/profil/spieler/744610.
Transfer history data appended for: https://www.transfermarkt.com/cian-murphy/profil/spieler/434208.
Transfer history data appended for: https://www.transfermarkt.com/joshua-honohan/profil/spieler/718171.
Transfer history data appended for: https://www.transfermarkt.com/cory-galvin/profil/spieler/276283.
Transfer history data appended for: https://www.transfermarkt.com/charlie-fleming/profil/spieler/433520.
Transfer history data appended for: https://www.transfermarkt.com/rob-slevin/profil/spieler/683665.
Transfer history data appended for: https://www.transfermarkt.com/beineon-obrien-whitmarsh/profil/spieler/523679.
Transfer history data appended for: https://www.transfermarkt.com/conor-davis/profil/spieler/245392.
Transfer history data appended for: https://www.transfermarkt.com/ronan-hurley/profil/spieler/466080.
Transfer history data appended for: https://www.transfermarkt.com/cian-bargary/profil/spieler/677812.
Transfer history data appended for: https://www.transfermarkt.com/dylan-mcglade/profil/spieler/228775.
Transfer history data appended for: https://www.transfermarkt.com/dale-holland/profil/spieler/625837.
Transfer history data appended for: https://www.transfermarkt.com/gearoid-morrissey/profil/spieler/114106.
Transfer history data appended for: https://www.transfermarkt.com/liam-bossin/profil/spieler/264176.
Transfer history data appended for: https://www.transfermarkt.com/henry-ochieng/profil/spieler/461756.
Transfer history data appended for: https://www.transfermarkt.com/darragh-crowley/profil/spieler/677799.
Transfer history data appended for: https://www.transfermarkt.com/mark-mcnulty/profil/spieler/34625.
Transfer history data appended for: https://www.transfermarkt.com/jamie-cleary/profil/spieler/585555.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-lunney/profil/spieler/293782.
Transfer history data appended for: https://www.transfermarkt.com/daniel-mandroiu/profil/spieler/293783.
Transfer history data appended for: https://www.transfermarkt.com/andre-wright/profil/spieler/303191.
Transfer history data appended for: https://www.transfermarkt.com/ross-tierney/profil/spieler/623740.
Transfer history data appended for: https://www.transfermarkt.com/dan-casey/profil/spieler/270221.
Transfer history data appended for: https://www.transfermarkt.com/daniel-grant/profil/spieler/577557.
Transfer history data appended for: https://www.transfermarkt.com/james-finnerty/profil/spieler/357673.
Transfer history data appended for: https://www.transfermarkt.com/promise-omochere/profil/spieler/540876.
Transfer history data appended for: https://www.transfermarkt.com/andrew-lyons/profil/spieler/546024.
Transfer history data appended for: https://www.transfermarkt.com/robert-cornwall/profil/spieler/261902.
Transfer history data appended for: https://www.transfermarkt.com/anto-breslin/profil/spieler/224799.
Transfer history data appended for: https://www.transfermarkt.com/keith-buckley/profil/spieler/181349.
Transfer history data appended for: https://www.transfermarkt.com/cristian-magerusan/profil/spieler/567196.
Transfer history data appended for: https://www.transfermarkt.com/keith-ward/profil/spieler/96521.
Transfer history data appended for: https://www.transfermarkt.com/james-talbot/profil/spieler/270225.
Transfer history data appended for: https://www.transfermarkt.com/patrick-kirk/profil/spieler/578337.
Transfer history data appended for: https://www.transfermarkt.com/michael-barker/profil/spieler/148899.
Transfer history data appended for: https://www.transfermarkt.com/dawson-devoy/profil/spieler/683530.
Transfer history data appended for: https://www.transfermarkt.com/dinny-corcoran/profil/spieler/180486.
Transfer history data appended for: https://www.transfermarkt.com/glen-mcauley/profil/spieler/401326.
Transfer history data appended for: https://www.transfermarkt.com/stephen-mcguinness/profil/spieler/264750.
Transfer history data appended for: https://www.transfermarkt.com/conor-levingston/profil/spieler/325207.
Transfer history data appended for: https://www.transfermarkt.com/niall-corbet/profil/spieler/206397.
Transfer history data appended for: https://www.transfermarkt.com/lee-desmond/profil/spieler/252881.
Transfer history data appended for: https://www.transfermarkt.com/shane-griffin/profil/spieler/241905.
Transfer history data appended for: https://www.transfermarkt.com/billy-king/profil/spieler/129973.
Transfer history data appended for: https://www.transfermarkt.com/rory-feely/profil/spieler/344108.
Transfer history data appended for: https://www.transfermarkt.com/chris-forrester/profil/spieler/180497.
Transfer history data appended for: https://www.transfermarkt.com/jason-mcclelland/profil/spieler/385704.
Transfer history data appended for: https://www.transfermarkt.com/ian-bermingham/profil/spieler/85689.
Transfer history data appended for: https://www.transfermarkt.com/neill-byrne/profil/spieler/591629.
Transfer history data appended for: https://www.transfermarkt.com/conor-kearns/profil/spieler/437603.
Transfer history data appended for: https://www.transfermarkt.com/jordan-gibson/profil/spieler/379666.
Transfer history data appended for: https://www.transfermarkt.com/darragh-burns/profil/spieler/634366.
Transfer history data appended for: https://www.transfermarkt.com/jamie-lennon/profil/spieler/567750.

Transfer history data appended for: https://www.transfermarkt.com/dean-clarke/profil/spieler/201802.
Transfer history data appended for: https://www.transfermarkt.com/james-doona/profil/spieler/438746.
Transfer history data appended for: https://www.transfermarkt.com/simon-madden/profil/spieler/66214.
Transfer history data appended for: https://www.transfermarkt.com/jake-walker/profil/spieler/655997.
Transfer history data appended for: https://www.transfermarkt.com/deivids-titovs/profil/spieler/589587.
Transfer history data appended for: https://www.transfermarkt.com/robbie-benson/profil/spieler/181348.
Transfer history data appended for: https://www.transfermarkt.com/darragh-markey/profil/spieler/315385.
Transfer history data appended for: https://www.transfermarkt.com/luke-mcnally/profil/spieler/535927.
Transfer history data appended for: https://www.transfermarkt.com/brendan-clarke/profil/spieler/29874.
Transfer history data appended for: https://www.transfermarkt.com/cian-kelly/profil/spieler/586754.
Transfer history data appended for: https://www.transfermarkt.com/gerardo-bruna/profil/spieler/70772.
Transfer history data appended for: https://www.transfermarkt.com/ciaran-coll/profil/spieler/185571.
Transfer history data appended for: https://www.transfermarkt.com/mark-mcchrystal/profil/spieler/43924.
Transfer history data appended for: https://www.transfermarkt.com/ronan-mckinley/profil/spieler/586681.
Transfer history data appended for: https://www.transfermarkt.com/jake-dunwoody/profil/spieler/420291.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-meite/profil/spieler/475292.
Transfer history data appended for: https://www.transfermarkt.com/colm-horgan/profil/spieler/183162.
Transfer history data appended for: https://www.transfermarkt.com/cameron-mcjannett/profil/spieler/425715.
Transfer history data appended for: https://www.transfermarkt.com/nathan-gartside/profil/spieler/322765.
Transfer history data appended for: https://www.transfermarkt.com/conor-mccormack/profil/spieler/120780.
Transfer history data appended for: https://www.transfermarkt.com/ciaron-harkin/profil/spieler/367153.
Transfer history data appended for: https://www.transfermarkt.com/walter-figueira/profil/spieler/223283.
Transfer history data appended for: https://www.transfermarkt.com/michael-harris/profil/spieler/746571.
Transfer history data appended for: https://www.transfermarkt.com/eoin-toal/profil/spieler/412607.
Transfer history data appended for: https://www.transfermarkt.com/darren-cole/profil/spieler/60983.
Transfer history data appended for: https://www.transfermarkt.com/conor-clifford/profil/spieler/114091.
Transfer history data appended for: https://www.transfermarkt.com/shane-mcnamee/profil/spieler/591631.
Transfer history data appended for: https://www.transfermarkt.com/james-akintunde/profil/spieler/333155.
Transfer history data appended for: https://www.transfermarkt.com/adam-hammill/profil/spieler/38091.
Transfer history data appended for: https://www.transfermarkt.com/joe-thomson/profil/spieler/246066.
Transfer history data appended for: https://www.transfermarkt.com/sean-mcbride/profil/spieler/546027.
Transfer history data appended for: https://www.transfermarkt.com/peter-cherrie/profil/spieler/18197.
Transfer history data appended for: https://www.transfermarkt.com/brendan-barr/profil/spieler/677802.
Transfer history data appended for: https://www.transfermarkt.com/ronan-boyce/profil/spieler/718846.
Transfer history data appended for: https://www.transfermarkt.com/jack-malone/profil/spieler/683468.
Transfer history data appended for: https://www.transfermarkt.com/shane-mceleney/profil/spieler/118071.
Transfer history data appended for: https://www.transfermarkt.com/jamie-browne/profil/spieler/587823.
Transfer history data appended for: https://www.transfermarkt.com/rafael-cretaro/profil/spieler/68534.
Transfer history data appended for: https://www.transfermarkt.com/ruairi-harkin/profil/spieler/98522.
Transfer history data appended for: https://www.transfermarkt.com/mark-russell/profil/spieler/280984.
Transfer history data appended for: https://www.transfermarkt.com/stephen-doherty/profil/spieler/677698.
Transfer history data appended for: https://www.transfermarkt.com/leo-donnellan/profil/spieler/440107.
Transfer history data appended for: https://www.transfermarkt.com/stephen-folan/profil/spieler/198583.
Transfer history data appended for: https://www.transfermarkt.com/ryan-finn/profil/spieler/541057.
Transfer history data appended for: https://www.transfermarkt.com/mark-coyle/profil/spieler/343599.
Transfer history data appended for: https://www.transfermarkt.com/kieran-farren/profil/spieler/719252.
Transfer history data appended for: https://www.transfermarkt.com/ryan-connolly/profil/spieler/141423.
Transfer history data appended for: https://www.transfermarkt.com/kosovar-sadiki/profil/spieler/429245.
Transfer history data appended for: https://www.transfermarkt.com/jack-serrant-green/profil/spieler/184114.
Transfer history data appended for: https://www.transfermarkt.com/mark-mcginley/profil/spieler/143763.
Transfer history data appended for: https://www.transfermarkt.com/alexander-kogler/profil/spieler/307797.
Transfer history data appended for: https://www.transfermarkt.com/tom-mcdermott/profil/spieler/322785.
Transfer history data appended for: https://www.transfermarkt.com/adrian-delap/profil/spieler/503835.
Transfer history data appended for: https://www.transfermarkt.com/shaun-kelly/profil/spieler/59274.
Transfer history data appended for: https://www.transfermarkt.com/david-webster/profil/spieler/92284.
Transfer history data appended for: https://www.transfermarkt.com/tony-mcnamee/profil/spieler/206722.
Transfer history data appended for: https://www.transfermarkt.com/mark-timlin/profil/spieler/308474.
Transfer history data appended for: https://www.transfermarkt.com/corey-mcbride/profil/spieler/721096.
Transfer history data appended for: https://www.transfermarkt.com/gareth-harkin/profil/spieler/104080.
Transfer history data appended for: https://www.transfermarkt.com/cameron-saul/profil/spieler/649448.
Transfer history data appended for: https://www.transfermarkt.com/sam-todd/profil/spieler/451942.
Transfer history data appended for: https://www.transfermarkt.com/adam-foley/profil/spieler/334826.
Transfer history data appended for: https://www.transfermarkt.com/barry-mcnamee/profil/spieler/221523.
Transfer history data appended for: https://www.transfermarkt.com/karl-osullivan/profil/spieler/548940.
Transfer history data appended for: https://www.transfermarkt.com/andy-boyle/profil/spieler/136169.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-corcoran/profil/spieler/579999.
Transfer history data appended for: https://www.transfermarkt.com/nathan-oduwa/profil/spieler/240355.
Transfer history data appended for: https://www.transfermarkt.com/patrick-hoban/profil/spieler/158951.
Transfer history data appended for: https://www.transfermarkt.com/dan-cleary/profil/spieler/264193.
Transfer history data appended for: https://www.transfermarkt.com/dane-massey/profil/spieler/96449.
Transfer history data appended for: https://www.transfermarkt.com/joshua-gatt/profil/spieler/140798.
Transfer history data appended for: https://www.transfermarkt.com/darragh-leahy/profil/spieler/325206.
Transfer history data appended for: https://www.transfermarkt.com/michael-duffy/profil/spieler/232068.
Transfer history data appended for: https://www.transfermarkt.com/jordan-flores/profil/spieler/334703.
Transfer history data appended for: https://www.transfermarkt.com/sean-hoare/profil/spieler/249879.
Transfer history data appended for: https://www.transfermarkt.com/georgie-kelly/profil/spieler/363881.
Transfer history data appended for: https://www.transfermarkt.com/sean-murray/profil/spieler/148907.
Transfer history data appended for: https://www.transfermarkt.com/patrick-mceleney/profil/spieler/121337.
Transfer history data appended for: https://www.transfermarkt.com/will-patching/profil/spieler/314297.
Transfer history data appended for: https://www.transfermarkt.com/stefan-colovic/profil/spieler/366004.

Transfer history data appended for: https://www.transfermarkt.com/aaron-mccarey/profil/spieler/138473.
Transfer history data appended for: https://www.transfermarkt.com/mark-hanratty/profil/spieler/719013.
Transfer history data appended for: https://www.transfermarkt.com/lido-lotefa/profil/spieler/681617.
Transfer history data appended for: https://www.transfermarkt.com/daniel-kelly/profil/spieler/567749.
Transfer history data appended for: https://www.transfermarkt.com/chris-shields/profil/spieler/96297.
Transfer history data appended for: https://www.transfermarkt.com/brian-gartland/profil/spieler/176851.
Transfer history data appended for: https://www.transfermarkt.com/john-mountney/profil/spieler/188539.
Transfer history data appended for: https://www.transfermarkt.com/david-mcmillan/profil/spieler/92545.
Transfer history data appended for: https://www.transfermarkt.com/cameron-dummigan/profil/spieler/248576.
Transfer history data appended for: https://www.transfermarkt.com/gregory-sloggett/profil/spieler/326500.
Transfer history data appended for: https://www.transfermarkt.com/gary-rogers/profil/spieler/56953.
Transfer history data appended for: https://www.transfermarkt.com/sean-gannon/profil/spieler/184670.
Transfer history data appended for: https://www.transfermarkt.com/niall-okeeffe/profil/spieler/706079.
Transfer history data appended for: https://www.transfermarkt.com/dean-walsh/profil/spieler/437441.
Transfer history data appended for: https://www.transfermarkt.com/robert-mccourt/profil/spieler/293786.
Transfer history data appended for: https://www.transfermarkt.com/kurtis-byrne/profil/spieler/62553.
Transfer history data appended for: https://www.transfermarkt.com/shane-griffin/profil/spieler/509666.
Transfer history data appended for: https://www.transfermarkt.com/kevin-lynch/profil/spieler/446144.
Transfer history data appended for: https://www.transfermarkt.com/adham-masood/profil/spieler/599320.
Transfer history data appended for: https://www.transfermarkt.com/tunmise-sobowale/profil/spieler/458633.
Transfer history data appended for: https://www.transfermarkt.com/sam-bone/profil/spieler/495178.
Transfer history data appended for: https://www.transfermarkt.com/tyreke-wilson/profil/spieler/357671.
Transfer history data appended for: https://www.transfermarkt.com/jake-davidson/profil/spieler/518587.
Transfer history data appended for: https://www.transfermarkt.com/robbie-weir/profil/spieler/21804.
Transfer history data appended for: https://www.transfermarkt.com/john-martin/profil/spieler/504115.
Transfer history data appended for: https://www.transfermarkt.com/will-longbottom/profil/spieler/432177.
Transfer history data appended for: https://www.transfermarkt.com/tadgh-ryan/profil/spieler/566820.
Transfer history data appended for: https://www.transfermarkt.com/darragh-power/profil/spieler/683670.
Transfer history data appended for: https://www.transfermarkt.com/ali-coote/profil/spieler/285282.
Transfer history data appended for: https://www.transfermarkt.com/matty-smith/profil/spieler/326587.
Transfer history data appended for: https://www.transfermarkt.com/daryl-murphy/profil/spieler/31312.
Transfer history data appended for: https://www.transfermarkt.com/brian-murphy/profil/spieler/4190.
Transfer history data appended for: https://www.transfermarkt.com/paul-martin/profil/spieler/357669.
Transfer history data appended for: https://www.transfermarkt.com/william-fitzgerald/profil/spieler/546159.
Transfer history data appended for: https://www.transfermarkt.com/elseid-hysaj/profil/spieler/200056.
Transfer history data appended for: https://www.transfermarkt.com/kevin-malcuit/profil/spieler/126711.
Transfer history data appended for: https://www.transfermarkt.com/eljif-elmas/profil/spieler/400489.
Transfer history data appended for: https://www.transfermarkt.com/piotr-zielinski/profil/spieler/181136.
Transfer history data appended for: https://www.transfermarkt.com/alex-meret/profil/spieler/240414.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-insigne/profil/spieler/133964.
Transfer history data appended for: https://www.transfermarkt.com/tiemoue-bakayoko/profil/spieler/182618.
Transfer history data appended for: https://www.transfermarkt.com/hirving-lozano/profil/spieler/316889.
Transfer history data appended for: https://www.transfermarkt.com/dries-mertens/profil/spieler/56416.
Transfer history data appended for: https://www.transfermarkt.com/faouzi-ghoulam/profil/spieler/126656.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-di-lorenzo/profil/spieler/169880.
Transfer history data appended for: https://www.transfermarkt.com/kalidou-koulibaly/profil/spieler/93128.
Transfer history data appended for: https://www.transfermarkt.com/mario-rui/profil/spieler/87884.
Transfer history data appended for: https://www.transfermarkt.com/amir-rrahmani/profil/spieler/257732.
Transfer history data appended for: https://www.transfermarkt.com/diego-demme/profil/spieler/82070.
Transfer history data appended for: https://www.transfermarkt.com/fernando-llorente/profil/spieler/35564.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-lobotka/profil/spieler/192735.
Transfer history data appended for: https://www.transfermarkt.com/fabian-ruiz/profil/spieler/350219.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-manolas/profil/spieler/104752.
Transfer history data appended for: https://www.transfermarkt.com/andrea-petagna/profil/spieler/199258.
Transfer history data appended for: https://www.transfermarkt.com/nikita-contini/profil/spieler/250683.
Transfer history data appended for: https://www.transfermarkt.com/david-ospina/profil/spieler/73396.
Transfer history data appended for: https://www.transfermarkt.com/victor-osimhen/profil/spieler/401923.
Transfer history data appended for: https://www.transfermarkt.com/ciprian-tatarusanu/profil/spieler/55282.
Transfer history data appended for: https://www.transfermarkt.com/andrea-conti/profil/spieler/111227.
Transfer history data appended for: https://www.transfermarkt.com/pierre-kalulu/profil/spieler/585949.
Transfer history data appended for: https://www.transfermarkt.com/brahim-diaz/profil/spieler/314678.
Transfer history data appended for: https://www.transfermarkt.com/mateo-musacchio/profil/spieler/45653.
Transfer history data appended for: https://www.transfermarkt.com/samu-castillejo/profil/spieler/195171.
Transfer history data appended for: https://www.transfermarkt.com/sandro-tonali/profil/spieler/397033.
Transfer history data appended for: https://www.transfermarkt.com/daniel-maldini/profil/spieler/539134.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-colombo/profil/spieler/487843.
Transfer history data appended for: https://www.transfermarkt.com/matteo-gabbia/profil/spieler/323167.
Transfer history data appended for: https://www.transfermarkt.com/theo-hernandez/profil/spieler/339808.
Transfer history data appended for: https://www.transfermarkt.com/simon-kjaer/profil/spieler/48859.
Transfer history data appended for: https://www.transfermarkt.com/zlatan-ibrahimovic/profil/spieler/3455.
Transfer history data appended for: https://www.transfermarkt.com/hakan-calhanoglu/profil/spieler/126414.
Transfer history data appended for: https://www.transfermarkt.com/antonio-donnarumma/profil/spieler/88685.
Transfer history data appended for: https://www.transfermarkt.com/jens-petter-hauge/profil/spieler/422355.
Transfer history data appended for: https://www.transfermarkt.com/ismael-bennacer/profil/spieler/351816.
Transfer history data appended for: https://www.transfermarkt.com/franck-kessie/profil/spieler/294808.
Transfer history data appended for: https://www.transfermarkt.com/leo-duarte/profil/spieler/312678.
Transfer history data appended for: https://www.transfermarkt.com/davide-calabria/profil/spieler/262523.
Transfer history data appended for: https://www.transfermarkt.com/rade-krunic/profil/spieler/259953.
Transfer history data appended for: https://www.transfermarkt.com/alexis-saelemaekers/profil/spieler/381950.
Transfer history data appended for: https://www.transfermarkt.com/diogo-dalot/profil/spieler/357147.

Transfer history data appended for: https://www.transfermarkt.com/rafael-leao/profil/spieler/357164.
Transfer history data appended for: https://www.transfermarkt.com/gianluigi-donnarumma/profil/spieler/315858.
Transfer history data appended for: https://www.transfermarkt.com/sasa-lukic/profil/spieler/245056.
Transfer history data appended for: https://www.transfermarkt.com/samir-ujkani/profil/spieler/42744.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-rodriguez/profil/spieler/86784.
Transfer history data appended for: https://www.transfermarkt.com/nicola-murru/profil/spieler/171399.
Transfer history data appended for: https://www.transfermarkt.com/lyanco/profil/spieler/379807.
Transfer history data appended for: https://www.transfermarkt.com/bremer/profil/spieler/516716.
Transfer history data appended for: https://www.transfermarkt.com/simone-verdi/profil/spieler/130360.
Transfer history data appended for: https://www.transfermarkt.com/antonio-rosati/profil/spieler/6442.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-buongiorno/profil/spieler/386446.
Transfer history data appended for: https://www.transfermarkt.com/armando-izzo/profil/spieler/32113.
Transfer history data appended for: https://www.transfermarkt.com/karol-linetty/profil/spieler/225873.
Transfer history data appended for: https://www.transfermarkt.com/daniele-baselli/profil/spieler/134883.
Transfer history data appended for: https://www.transfermarkt.com/amer-gojak/profil/spieler/293210.
Transfer history data appended for: https://www.transfermarkt.com/simone-edera/profil/spieler/340070.
Transfer history data appended for: https://www.transfermarkt.com/jacopo-segre/profil/spieler/373899.
Transfer history data appended for: https://www.transfermarkt.com/salvatore-sirigu/profil/spieler/25508.
Transfer history data appended for: https://www.transfermarkt.com/erick-ferigra/profil/spieler/331501.
Transfer history data appended for: https://www.transfermarkt.com/mergim-vojvoda/profil/spieler/336125.
Transfer history data appended for: https://www.transfermarkt.com/vanja-milinkovi%C4%87-savi%C4%87/profil/spieler/257474.
Transfer history data appended for: https://www.transfermarkt.com/soualiho-meite/profil/spieler/164913.
Transfer history data appended for: https://www.transfermarkt.com/simone-zaza/profil/spieler/96828.
Transfer history data appended for: https://www.transfermarkt.com/wilfried-singo/profil/spieler/648779.
Transfer history data appended for: https://www.transfermarkt.com/michel-ndary-adopo/profil/spieler/564305.
Transfer history data appended for: https://www.transfermarkt.com/vincenzo-millico/profil/spieler/390159.
Transfer history data appended for: https://www.transfermarkt.com/ilija-nestorovski/profil/spieler/54581.
Transfer history data appended for: https://www.transfermarkt.com/hidde-ter-avest/profil/spieler/258519.
Transfer history data appended for: https://www.transfermarkt.com/jens-stryger-larsen/profil/spieler/69646.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-coulibaly/profil/spieler/472161.
Transfer history data appended for: https://www.transfermarkt.com/kevin-lasagna/profil/spieler/131951.
Transfer history data appended for: https://www.transfermarkt.com/walace/profil/spieler/323954.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-pussetto/profil/spieler/283528.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-de-paul/profil/spieler/255901.
Transfer history data appended for: https://www.transfermarkt.com/sebastien-de-maio/profil/spieler/56830.
Transfer history data appended for: https://www.transfermarkt.com/juan-musso/profil/spieler/242359.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-molina/profil/spieler/424042.
Transfer history data appended for: https://www.transfermarkt.com/manuel-gasparini/profil/spieler/487828.
Transfer history data appended for: https://www.transfermarkt.com/martin-palumbo/profil/spieler/617170.
Transfer history data appended for: https://www.transfermarkt.com/bram-nuytinck/profil/spieler/104597.
Transfer history data appended for: https://www.transfermarkt.com/nicolas/profil/spieler/99523.
Transfer history data appended for: https://www.transfermarkt.com/thomas-ouwejan/profil/spieler/241477.
Transfer history data appended for: https://www.transfermarkt.com/petar-micin/profil/spieler/343963.
Transfer history data appended for: https://www.transfermarkt.com/roberto-pereyra/profil/spieler/112302.
Transfer history data appended for: https://www.transfermarkt.com/simone-scuffet/profil/spieler/238993.
Transfer history data appended for: https://www.transfermarkt.com/cristo/profil/spieler/339707.
Transfer history data appended for: https://www.transfermarkt.com/kevin-bonifazi/profil/spieler/247377.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-prodl/profil/spieler/37981.
Transfer history data appended for: https://www.transfermarkt.com/samir/profil/spieler/255744.
Transfer history data appended for: https://www.transfermarkt.com/jean-victor-makengo/profil/spieler/322305.
Transfer history data appended for: https://www.transfermarkt.com/fernando-forestieri/profil/spieler/44948.
Transfer history data appended for: https://www.transfermarkt.com/koray-gunter/profil/spieler/115763.
Transfer history data appended for: https://www.transfermarkt.com/antonio-di-gaudio/profil/spieler/165722.
Transfer history data appended for: https://www.transfermarkt.com/giangiacomo-magnani/profil/spieler/310458.
Transfer history data appended for: https://www.transfermarkt.com/mert-cetin/profil/spieler/391498.
Transfer history data appended for: https://www.transfermarkt.com/samuel-di-carmine/profil/spieler/45389.
Transfer history data appended for: https://www.transfermarkt.com/miguel-veloso/profil/spieler/43848.
Transfer history data appended for: https://www.transfermarkt.com/andrea-favilli/profil/spieler/340151.
Transfer history data appended for: https://www.transfermarkt.com/bruno-amione/profil/spieler/644676.
Transfer history data appended for: https://www.transfermarkt.com/andrea-danzi/profil/spieler/319171.
Transfer history data appended for: https://www.transfermarkt.com/nicola-borghetto/profil/spieler/415801.
Transfer history data appended for: https://www.transfermarkt.com/ivor-pandur/profil/spieler/371013.
Transfer history data appended for: https://www.transfermarkt.com/nikola-kalinic/profil/spieler/36371.
Transfer history data appended for: https://www.transfermarkt.com/matteo-lovato/profil/spieler/459655.
Transfer history data appended for: https://www.transfermarkt.com/eddie-salcedo/profil/spieler/459661.
Transfer history data appended for: https://www.transfermarkt.com/marco-silvestri/profil/spieler/85528.
Transfer history data appended for: https://www.transfermarkt.com/federico-dimarco/profil/spieler/198116.
Transfer history data appended for: https://www.transfermarkt.com/kevin-ruegg/profil/spieler/290032.
Transfer history data appended for: https://www.transfermarkt.com/darko-lazovic/profil/spieler/70411.
Transfer history data appended for: https://www.transfermarkt.com/ebrima-colley/profil/spieler/567217.
Transfer history data appended for: https://www.transfermarkt.com/marco-benassi/profil/spieler/201040.
Transfer history data appended for: https://www.transfermarkt.com/ivan-ilic/profil/spieler/470794.
Transfer history data appended for: https://www.transfermarkt.com/pawel-dawidowicz/profil/spieler/248732.
Transfer history data appended for: https://www.transfermarkt.com/destiny-udogie/profil/spieler/556385.
Transfer history data appended for: https://www.transfermarkt.com/federico-ceccherini/profil/spieler/163639.
Transfer history data appended for: https://www.transfermarkt.com/mattia-zaccagni/profil/spieler/283735.
Transfer history data appended for: https://www.transfermarkt.com/antonin-barak/profil/spieler/272261.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-berardi/profil/spieler/127217.
Transfer history data appended for: https://www.transfermarkt.com/federico-ricci/profil/spieler/198086.
Transfer history data appended for: https://www.transfermarkt.com/raul-steau/profil/spieler/547818.

Transfer history data appended for: https://www.transfermarkt.com/domenico-berardi/profil/spieler/177843.
Transfer history data appended for: https://www.transfermarkt.com/rogerio/profil/spieler/401527.
Transfer history data appended for: https://www.transfermarkt.com/marlon/profil/spieler/273236.
Transfer history data appended for: https://www.transfermarkt.com/andrea-consigli/profil/spieler/35865.
Transfer history data appended for: https://www.transfermarkt.com/mert-muldur/profil/spieler/353922.
Transfer history data appended for: https://www.transfermarkt.com/vlad-chiriche%C8%99/profil/spieler/123261.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-schiappacasse/profil/spieler/345473.
Transfer history data appended for: https://www.transfermarkt.com/filippo-romagna/profil/spieler/256678.
Transfer history data appended for: https://www.transfermarkt.com/francesco-caputo/profil/spieler/84765.
Transfer history data appended for: https://www.transfermarkt.com/lukas-haraslin/profil/spieler/239941.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-pegolo/profil/spieler/21872.
Transfer history data appended for: https://www.transfermarkt.com/pedro-obiang/profil/spieler/101213.
Transfer history data appended for: https://www.transfermarkt.com/hamed-junior-traore/profil/spieler/391065.
Transfer history data appended for: https://www.transfermarkt.com/gregoire-defrel/profil/spieler/163222.
Transfer history data appended for: https://www.transfermarkt.com/stefano-turati/profil/spieler/543666.
Transfer history data appended for: https://www.transfermarkt.com/maxime-lopez/profil/spieler/290862.
Transfer history data appended for: https://www.transfermarkt.com/manuel-locatelli/profil/spieler/265088.
Transfer history data appended for: https://www.transfermarkt.com/kaan-ayhan/profil/spieler/119031.
Transfer history data appended for: https://www.transfermarkt.com/giacomo-raspadori/profil/spieler/405885.
Transfer history data appended for: https://www.transfermarkt.com/federico-peluso/profil/spieler/21763.
Transfer history data appended for: https://www.transfermarkt.com/francesco-magnanelli/profil/spieler/7093.
Transfer history data appended for: https://www.transfermarkt.com/jeremie-boga/profil/spieler/216569.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-bourabia/profil/spieler/131731.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-gagliolo/profil/spieler/240786.
Transfer history data appended for: https://www.transfermarkt.com/wylan-cyprien/profil/spieler/182889.
Transfer history data appended for: https://www.transfermarkt.com/andrea-dini/profil/spieler/355444.
Transfer history data appended for: https://www.transfermarkt.com/giacomo-ricci/profil/spieler/261056.
Transfer history data appended for: https://www.transfermarkt.com/hernani/profil/spieler/181768.
Transfer history data appended for: https://www.transfermarkt.com/simone-iacoponi/profil/spieler/59699.
Transfer history data appended for: https://www.transfermarkt.com/gervinho/profil/spieler/33481.
Transfer history data appended for: https://www.transfermarkt.com/yordan-osorio/profil/spieler/358165.
Transfer history data appended for: https://www.transfermarkt.com/juraj-kucka/profil/spieler/74943.
Transfer history data appended for: https://www.transfermarkt.com/andreas-cornelius/profil/spieler/203412.
Transfer history data appended for: https://www.transfermarkt.com/yann-karamoh/profil/spieler/324804.
Transfer history data appended for: https://www.transfermarkt.com/simon-sohm/profil/spieler/507486.
Transfer history data appended for: https://www.transfermarkt.com/juan-brunetta/profil/spieler/466268.
Transfer history data appended for: https://www.transfermarkt.com/filippo-rinaldi/profil/spieler/604207.
Transfer history data appended for: https://www.transfermarkt.com/bruno-alves/profil/spieler/13121.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-carriero/profil/spieler/398576.
Transfer history data appended for: https://www.transfermarkt.com/roberto-inglese/profil/spieler/159337.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-valenti/profil/spieler/625202.
Transfer history data appended for: https://www.transfermarkt.com/maxime-busi/profil/spieler/570817.
Transfer history data appended for: https://www.transfermarkt.com/hans-nicolussi-caviglia/profil/spieler/430280.
Transfer history data appended for: https://www.transfermarkt.com/matteo-scozzarella/profil/spieler/85208.
Transfer history data appended for: https://www.transfermarkt.com/simone-colombi/profil/spieler/57285.
Transfer history data appended for: https://www.transfermarkt.com/mattia-sprocati/profil/spieler/199274.
Transfer history data appended for: https://www.transfermarkt.com/andrea-adorante/profil/spieler/364206.
Transfer history data appended for: https://www.transfermarkt.com/valentin-mih%C4%83il%C4%83/profil/spieler/535469.
Transfer history data appended for: https://www.transfermarkt.com/botond-balogh/profil/spieler/543727.
Transfer history data appended for: https://www.transfermarkt.com/hans-hateboer/profil/spieler/275303.
Transfer history data appended for: https://www.transfermarkt.com/mattia-caldara/profil/spieler/197470.
Transfer history data appended for: https://www.transfermarkt.com/cristian-romero/profil/spieler/355915.
Transfer history data appended for: https://www.transfermarkt.com/remo-freuler/profil/spieler/148252.
Transfer history data appended for: https://www.transfermarkt.com/jose-luis-palomino/profil/spieler/125020.
Transfer history data appended for: https://www.transfermarkt.com/ruslan-malinovskyi/profil/spieler/207877.
Transfer history data appended for: https://www.transfermarkt.com/sam-lammers/profil/spieler/386914.
Transfer history data appended for: https://www.transfermarkt.com/francesco-rossi/profil/spieler/126634.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-miranchuk/profil/spieler/255450.
Transfer history data appended for: https://www.transfermarkt.com/marco-carnesecchi/profil/spieler/459763.
Transfer history data appended for: https://www.transfermarkt.com/berat-djimsiti/profil/spieler/165513.
Transfer history data appended for: https://www.transfermarkt.com/marten-de-roon/profil/spieler/133179.
Transfer history data appended for: https://www.transfermarkt.com/cristiano-piccini/profil/spieler/163086.
Transfer history data appended for: https://www.transfermarkt.com/robin-gosens/profil/spieler/273132.
Transfer history data appended for: https://www.transfermarkt.com/amad-diallo/profil/spieler/536835.
Transfer history data appended for: https://www.transfermarkt.com/matteo-ruggeri/profil/spieler/616631.
Transfer history data appended for: https://www.transfermarkt.com/matteo-pessina/profil/spieler/332179.
Transfer history data appended for: https://www.transfermarkt.com/papu-gomez/profil/spieler/20005.
Transfer history data appended for: https://www.transfermarkt.com/boris-radunovi%C4%87/profil/spieler/258482.
Transfer history data appended for: https://www.transfermarkt.com/bosko-sutalo/profil/spieler/431698.
Transfer history data appended for: https://www.transfermarkt.com/josip-ilicic/profil/spieler/80351.
Transfer history data appended for: https://www.transfermarkt.com/luis-muriel/profil/spieler/119228.
Transfer history data appended for: https://www.transfermarkt.com/mario-pasalic/profil/spieler/205938.
Transfer history data appended for: https://www.transfermarkt.com/pierluigi-gollini/profil/spieler/244192.
Transfer history data appended for: https://www.transfermarkt.com/marash-kumbulla/profil/spieler/371371.
Transfer history data appended for: https://www.transfermarkt.com/juan-jesus/profil/spieler/121985.
Transfer history data appended for: https://www.transfermarkt.com/edin-dzeko/profil/spieler/28396.
Transfer history data appended for: https://www.transfermarkt.com/rick-karsdorp/profil/spieler/205006.
Transfer history data appended for: https://www.transfermarkt.com/simone-farelli/profil/spieler/6807.
Transfer history data appended for: https://www.transfermarkt.com/federico-fazio/profil/spieler/45314.

Transfer history data appended for: https://www.transfermarkt.com/chris-smalling/profil/spieler/103427.
Transfer history data appended for: https://www.transfermarkt.com/borja-mayoral/profil/spieler/298976.
Transfer history data appended for: https://www.transfermarkt.com/henrikh-mkhitaryan/profil/spieler/55735.
Transfer history data appended for: https://www.transfermarkt.com/carles-perez/profil/spieler/282810.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-mancini/profil/spieler/256448.
Transfer history data appended for: https://www.transfermarkt.com/javier-pastore/profil/spieler/55215.
Transfer history data appended for: https://www.transfermarkt.com/antonio-mirante/profil/spieler/22141.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-pellegrini/profil/spieler/286297.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-villar/profil/spieler/398163.
Transfer history data appended for: https://www.transfermarkt.com/pau-lopez/profil/spieler/286415.
Transfer history data appended for: https://www.transfermarkt.com/pedro/profil/spieler/65278.
Transfer history data appended for: https://www.transfermarkt.com/bryan-cristante/profil/spieler/199248.
Transfer history data appended for: https://www.transfermarkt.com/bruno-peres/profil/spieler/148751.
Transfer history data appended for: https://www.transfermarkt.com/roger-ibanez/profil/spieler/524481.
Transfer history data appended for: https://www.transfermarkt.com/amadou-diawara/profil/spieler/355501.
Transfer history data appended for: https://www.transfermarkt.com/jordan-veretout/profil/spieler/164771.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-calafiori/profil/spieler/502821.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-zaniolo/profil/spieler/392085.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-spinazzola/profil/spieler/118689.
Transfer history data appended for: https://www.transfermarkt.com/davide-santon/profil/spieler/84344.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-caprari/profil/spieler/146752.
Transfer history data appended for: https://www.transfermarkt.com/gaetano-letizia/profil/spieler/160560.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-del-pinto/profil/spieler/244061.
Transfer history data appended for: https://www.transfermarkt.com/perparim-hetemaj/profil/spieler/37295.
Transfer history data appended for: https://www.transfermarkt.com/davide-masella/profil/spieler/550443.
Transfer history data appended for: https://www.transfermarkt.com/igor-lucatelli/profil/spieler/705094.
Transfer history data appended for: https://www.transfermarkt.com/abdallah-basit/profil/spieler/457773.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-tuia/profil/spieler/73943.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-improta/profil/spieler/163489.
Transfer history data appended for: https://www.transfermarkt.com/christian-pastina/profil/spieler/476624.
Transfer history data appended for: https://www.transfermarkt.com/daam-foulon/profil/spieler/338637.
Transfer history data appended for: https://www.transfermarkt.com/siriki-sanogo/profil/spieler/539612.
Transfer history data appended for: https://www.transfermarkt.com/artur-ionita/profil/spieler/98888.
Transfer history data appended for: https://www.transfermarkt.com/roberto-insigne/profil/spieler/200174.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-manfredini/profil/spieler/139743.
Transfer history data appended for: https://www.transfermarkt.com/pasquale-schiattarella/profil/spieler/56762.
Transfer history data appended for: https://www.transfermarkt.com/federico-barba/profil/spieler/165873.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-viola/profil/spieler/85393.
Transfer history data appended for: https://www.transfermarkt.com/pier-graziano-gori/profil/spieler/85270.
Transfer history data appended for: https://www.transfermarkt.com/massimo-volta/profil/spieler/54921.
Transfer history data appended for: https://www.transfermarkt.com/andres-tello/profil/spieler/331389.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-di-serio/profil/spieler/532040.
Transfer history data appended for: https://www.transfermarkt.com/bryan-dabo/profil/spieler/149446.
Transfer history data appended for: https://www.transfermarkt.com/gabriele-moncini/profil/spieler/238977.
Transfer history data appended for: https://www.transfermarkt.com/marco-sau/profil/spieler/55801.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-montipo/profil/spieler/241923.
Transfer history data appended for: https://www.transfermarkt.com/bartlomiej-dragowski/profil/spieler/208166.
Transfer history data appended for: https://www.transfermarkt.com/erick-pulgar/profil/spieler/215616.
Transfer history data appended for: https://www.transfermarkt.com/dusan-vlahovic/profil/spieler/357498.
Transfer history data appended for: https://www.transfermarkt.com/igor/profil/spieler/380350.
Transfer history data appended for: https://www.transfermarkt.com/lucas-martinez-quarta/profil/spieler/373373.
Transfer history data appended for: https://www.transfermarkt.com/sofyan-amrabat/profil/spieler/287579.
Transfer history data appended for: https://www.transfermarkt.com/borja-valero/profil/spieler/40372.
Transfer history data appended for: https://www.transfermarkt.com/jose-callejon/profil/spieler/61253.
Transfer history data appended for: https://www.transfermarkt.com/valentin-eysseric/profil/spieler/126687.
Transfer history data appended for: https://www.transfermarkt.com/patrick-cutrone/profil/spieler/265078.
Transfer history data appended for: https://www.transfermarkt.com/franck-ribery/profil/spieler/22068.
Transfer history data appended for: https://www.transfermarkt.com/nikola-milenkovic/profil/spieler/413507.
Transfer history data appended for: https://www.transfermarkt.com/giacomo-bonaventura/profil/spieler/57280.
Transfer history data appended for: https://www.transfermarkt.com/federico-brancolini/profil/spieler/451154.
Transfer history data appended for: https://www.transfermarkt.com/christian-dalle-mura/profil/spieler/487829.
Transfer history data appended for: https://www.transfermarkt.com/gaetano-castrovilli/profil/spieler/303116.
Transfer history data appended for: https://www.transfermarkt.com/tofol-montiel/profil/spieler/573979.
Transfer history data appended for: https://www.transfermarkt.com/christian-kouame/profil/spieler/337725.
Transfer history data appended for: https://www.transfermarkt.com/federico-chiesa/profil/spieler/341092.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-frabotta/profil/spieler/386755.
Transfer history data appended for: https://www.transfermarkt.com/wojciech-szczesny/profil/spieler/44058.
Transfer history data appended for: https://www.transfermarkt.com/danilo/profil/spieler/145707.
Transfer history data appended for: https://www.transfermarkt.com/adrien-rabiot/profil/spieler/182913.
Transfer history data appended for: https://www.transfermarkt.com/sami-khedira/profil/spieler/29401.
Transfer history data appended for: https://www.transfermarkt.com/arthur/profil/spieler/362842.
Transfer history data appended for: https://www.transfermarkt.com/dejan-kulusevski/profil/spieler/431755.
Transfer history data appended for: https://www.transfermarkt.com/federico-bernardeschi/profil/spieler/197300.
Transfer history data appended for: https://www.transfermarkt.com/matthijs-de-ligt/profil/spieler/326031.
Transfer history data appended for: https://www.transfermarkt.com/weston-mckennie/profil/spieler/332697.
Transfer history data appended for: https://www.transfermarkt.com/alex-sandro/profil/spieler/79960.
Transfer history data appended for: https://www.transfermarkt.com/stefano-gori/profil/spieler/244491.
Transfer history data appended for: https://www.transfermarkt.com/juan-cuadrado/profil/spieler/91970.
Transfer history data appended for: https://www.transfermarkt.com/carlo-pinsoglio/profil/spieler/75411.

Transfer history data appended for: https://www.transfermarkt.com/gianluigi-buffon/profil/spieler/5023.
Transfer history data appended for: https://www.transfermarkt.com/aaron-ramsey/profil/spieler/50057.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-morata/profil/spieler/128223.
Transfer history data appended for: https://www.transfermarkt.com/cristiano-ronaldo/profil/spieler/8198.
Transfer history data appended for: https://www.transfermarkt.com/manolo-portanova/profil/spieler/394304.
Transfer history data appended for: https://www.transfermarkt.com/giorgio-chiellini/profil/spieler/29260.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-bentancur/profil/spieler/354362.
Transfer history data appended for: https://www.transfermarkt.com/paulo-dybala/profil/spieler/206050.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-bonucci/profil/spieler/39983.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-armini/profil/spieler/421775.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-fares/profil/spieler/287700.
Transfer history data appended for: https://www.transfermarkt.com/sergej-milinkovic-savic/profil/spieler/266302.
Transfer history data appended for: https://www.transfermarkt.com/madiu-bari/profil/spieler/396590.
Transfer history data appended for: https://www.transfermarkt.com/manuel-lazzari/profil/spieler/331401.
Transfer history data appended for: https://www.transfermarkt.com/senad-lulic/profil/spieler/61449.
Transfer history data appended for: https://www.transfermarkt.com/denis-vavro/profil/spieler/239962.
Transfer history data appended for: https://www.transfermarkt.com/pepe-reina/profil/spieler/7825.
Transfer history data appended for: https://www.transfermarkt.com/thomas-strakosha/profil/spieler/222209.
Transfer history data appended for: https://www.transfermarkt.com/jean-daniel-akpa-akpro/profil/spieler/170481.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-escalante/profil/spieler/266795.
Transfer history data appended for: https://www.transfermarkt.com/sofian-kiyine/profil/spieler/393804.
Transfer history data appended for: https://www.transfermarkt.com/riza-durmisi/profil/spieler/135208.
Transfer history data appended for: https://www.transfermarkt.com/andreas-pereira/profil/spieler/203394.
Transfer history data appended for: https://www.transfermarkt.com/marco-alia/profil/spieler/391931.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-correa/profil/spieler/227081.
Transfer history data appended for: https://www.transfermarkt.com/djavan-anderson/profil/spieler/215089.
Transfer history data appended for: https://www.transfermarkt.com/vedat-muriqi/profil/spieler/256267.
Transfer history data appended for: https://www.transfermarkt.com/francesco-acerbi/profil/spieler/131075.
Transfer history data appended for: https://www.transfermarkt.com/silvio-proto/profil/spieler/12518.
Transfer history data appended for: https://www.transfermarkt.com/wesley-hoedt/profil/spieler/253765.
Transfer history data appended for: https://www.transfermarkt.com/luiz-felipe/profil/spieler/457931.
Transfer history data appended for: https://www.transfermarkt.com/lucas-leiva/profil/spieler/41414.
Transfer history data appended for: https://www.transfermarkt.com/adam-marusic/profil/spieler/239802.
Transfer history data appended for: https://www.transfermarkt.com/danilo-cataldi/profil/spieler/199733.
Transfer history data appended for: https://www.transfermarkt.com/marco-parolo/profil/spieler/84545.
Transfer history data appended for: https://www.transfermarkt.com/stefan-radu/profil/spieler/44420.
Transfer history data appended for: https://www.transfermarkt.com/patric/profil/spieler/126729.
Transfer history data appended for: https://www.transfermarkt.com/felipe-caicedo/profil/spieler/37834.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-crociata/profil/spieler/291400.
Transfer history data appended for: https://www.transfermarkt.com/salvatore-molina/profil/spieler/163582.
Transfer history data appended for: https://www.transfermarkt.com/pedro-pereira/profil/spieler/314965.
Transfer history data appended for: https://www.transfermarkt.com/lisandro-magallan/profil/spieler/66736.
Transfer history data appended for: https://www.transfermarkt.com/koffi-djidji/profil/spieler/183031.
Transfer history data appended for: https://www.transfermarkt.com/alex-cordaz/profil/spieler/16633.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-cuomo/profil/spieler/365565.
Transfer history data appended for: https://www.transfermarkt.com/eduardo-henrique/profil/spieler/216118.
Transfer history data appended for: https://www.transfermarkt.com/milos-vulic/profil/spieler/270901.
Transfer history data appended for: https://www.transfermarkt.com/andrea-rispoli/profil/spieler/74448.
Transfer history data appended for: https://www.transfermarkt.com/niccolo-zanellato/profil/spieler/343945.
Transfer history data appended for: https://www.transfermarkt.com/luis-rojas/profil/spieler/662752.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-golemic/profil/spieler/169841.
Transfer history data appended for: https://www.transfermarkt.com/mattia-mustacchio/profil/spieler/56803.
Transfer history data appended for: https://www.transfermarkt.com/gian-marco-crespi/profil/spieler/504825.
Transfer history data appended for: https://www.transfermarkt.com/denis-dragus/profil/spieler/405399.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-riviere/profil/spieler/61637.
Transfer history data appended for: https://www.transfermarkt.com/junior-messias/profil/spieler/449151.
Transfer history data appended for: https://www.transfermarkt.com/marco-festa/profil/spieler/257660.
Transfer history data appended for: https://www.transfermarkt.com/tomislav-gomelt/profil/spieler/210983.
Transfer history data appended for: https://www.transfermarkt.com/simy/profil/spieler/194549.
Transfer history data appended for: https://www.transfermarkt.com/jacopo-petriccione/profil/spieler/218067.
Transfer history data appended for: https://www.transfermarkt.com/aristoteles-romero/profil/spieler/309929.
Transfer history data appended for: https://www.transfermarkt.com/francesco-dalterio/profil/spieler/621223.
Transfer history data appended for: https://www.transfermarkt.com/r%C4%83zvan-marin/profil/spieler/295183.
Transfer history data appended for: https://www.transfermarkt.com/guglielmo-vicario/profil/spieler/286047.
Transfer history data appended for: https://www.transfermarkt.com/simone-aresti/profil/spieler/41912.
Transfer history data appended for: https://www.transfermarkt.com/andrea-carboni/profil/spieler/481834.
Transfer history data appended for: https://www.transfermarkt.com/simone-pinna/profil/spieler/303187.
Transfer history data appended for: https://www.transfermarkt.com/charalampos-lykogiannis/profil/spieler/136514.
Transfer history data appended for: https://www.transfermarkt.com/gaston-pereiro/profil/spieler/264116.
Transfer history data appended for: https://www.transfermarkt.com/gabriele-zappa/profil/spieler/392569.
Transfer history data appended for: https://www.transfermarkt.com/joao-pedro/profil/spieler/129129.
Transfer history data appended for: https://www.transfermarkt.com/matteo-tramoni/profil/spieler/475410.
Transfer history data appended for: https://www.transfermarkt.com/marko-pajac/profil/spieler/190634.
Transfer history data appended for: https://www.transfermarkt.com/luca-ceppitelli/profil/spieler/102745.
Transfer history data appended for: https://www.transfermarkt.com/adam-ounas/profil/spieler/400485.
Transfer history data appended for: https://www.transfermarkt.com/fabrizio-caligara/profil/spieler/386574.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-sottil/profil/spieler/386455.
Transfer history data appended for: https://www.transfermarkt.com/zito-luvumbo/profil/spieler/666547.
Transfer history data appended for: https://www.transfermarkt.com/diego-godin/profil/spieler/54928.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-tripaldelli/profil/spieler/357176.

Transfer history data appended for: https://www.transfermarkt.com/christian-oliva/profil/spieler/563812.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-walukiewicz/profil/spieler/345458.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-simeone/profil/spieler/282388.
Transfer history data appended for: https://www.transfermarkt.com/alberto-cerri/profil/spieler/197751.
Transfer history data appended for: https://www.transfermarkt.com/paolo-farago/profil/spieler/167796.
Transfer history data appended for: https://www.transfermarkt.com/fabio-pisacane/profil/spieler/101922.
Transfer history data appended for: https://www.transfermarkt.com/alessio-cragno/profil/spieler/12907.
Transfer history data appended for: https://www.transfermarkt.com/francesco-cassata/profil/spieler/301236.
Transfer history data appended for: https://www.transfermarkt.com/mattia-bani/profil/spieler/176139.
Transfer history data appended for: https://www.transfermarkt.com/federico-marchetti/profil/spieler/22318.
Transfer history data appended for: https://www.transfermarkt.com/paolo-ghiglione/profil/spieler/313477.
Transfer history data appended for: https://www.transfermarkt.com/miha-zajc/profil/spieler/149829.
Transfer history data appended for: https://www.transfermarkt.com/lasse-schone/profil/spieler/34784.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-rovella/profil/spieler/525704.
Transfer history data appended for: https://www.transfermarkt.com/joel-asoro/profil/spieler/375391.
Transfer history data appended for: https://www.transfermarkt.com/alberto-paleari/profil/spieler/163048.
Transfer history data appended for: https://www.transfermarkt.com/claudiu-micovschi/profil/spieler/319231.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-scamacca/profil/spieler/315867.
Transfer history data appended for: https://www.transfermarkt.com/davide-zappacosta/profil/spieler/173859.
Transfer history data appended for: https://www.transfermarkt.com/lukas-lerager/profil/spieler/167105.
Transfer history data appended for: https://www.transfermarkt.com/davide-biraschi/profil/spieler/199927.
Transfer history data appended for: https://www.transfermarkt.com/valon-behrami/profil/spieler/21905.
Transfer history data appended for: https://www.transfermarkt.com/stefano-sturaro/profil/spieler/167859.
Transfer history data appended for: https://www.transfermarkt.com/eldor-shomurodov/profil/spieler/358166.
Transfer history data appended for: https://www.transfermarkt.com/filippo-melegoni/profil/spieler/315862.
Transfer history data appended for: https://www.transfermarkt.com/petar-brlek/profil/spieler/160471.
Transfer history data appended for: https://www.transfermarkt.com/andrea-masiello/profil/spieler/34198.
Transfer history data appended for: https://www.transfermarkt.com/luca-pellegrini/profil/spieler/346567.
Transfer history data appended for: https://www.transfermarkt.com/lukas-zima/profil/spieler/147558.
Transfer history data appended for: https://www.transfermarkt.com/ivan-lakicevic/profil/spieler/196978.
Transfer history data appended for: https://www.transfermarkt.com/edoardo-goldaniga/profil/spieler/242940.
Transfer history data appended for: https://www.transfermarkt.com/goran-pandev/profil/spieler/12563.
Transfer history data appended for: https://www.transfermarkt.com/lennart-czyborra/profil/spieler/309393.
Transfer history data appended for: https://www.transfermarkt.com/darian-males/profil/spieler/507479.
Transfer history data appended for: https://www.transfermarkt.com/domenico-criscito/profil/spieler/44136.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-caso/profil/spieler/398030.
Transfer history data appended for: https://www.transfermarkt.com/mitchell-dijks/profil/spieler/187245.
Transfer history data appended for: https://www.transfermarkt.com/jerdy-schouten/profil/spieler/347900.
Transfer history data appended for: https://www.transfermarkt.com/arturo-calabresi/profil/spieler/240897.
Transfer history data appended for: https://www.transfermarkt.com/musa-barrow/profil/spieler/486624.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-palacio/profil/spieler/39099.
Transfer history data appended for: https://www.transfermarkt.com/andri-fannar-baldursson/profil/spieler/464446.
Transfer history data appended for: https://www.transfermarkt.com/roberto-soriano/profil/spieler/63186.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-orsolini/profil/spieler/368482.
Transfer history data appended for: https://www.transfermarkt.com/angelo-da-costa/profil/spieler/82693.
Transfer history data appended for: https://www.transfermarkt.com/andreas-skov-olsen/profil/spieler/432982.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-breza/profil/spieler/459842.
Transfer history data appended for: https://www.transfermarkt.com/federico-ravaglia/profil/spieler/390304.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-vignato/profil/spieler/394346.
Transfer history data appended for: https://www.transfermarkt.com/nicola-sansone/profil/spieler/82048.
Transfer history data appended for: https://www.transfermarkt.com/mattias-svanberg/profil/spieler/342405.
Transfer history data appended for: https://www.transfermarkt.com/kingsley-michael/profil/spieler/401920.
Transfer history data appended for: https://www.transfermarkt.com/nehuen-paz/profil/spieler/284724.
Transfer history data appended for: https://www.transfermarkt.com/takehiro-tomiyasu/profil/spieler/331560.
Transfer history data appended for: https://www.transfermarkt.com/stefano-denswil/profil/spieler/182923.
Transfer history data appended for: https://www.transfermarkt.com/aaron-hickey/profil/spieler/591949.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-skorupski/profil/spieler/80894.
Transfer history data appended for: https://www.transfermarkt.com/federico-santander/profil/spieler/99180.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-dominguez/profil/spieler/497291.
Transfer history data appended for: https://www.transfermarkt.com/emil-audero/profil/spieler/256339.
Transfer history data appended for: https://www.transfermarkt.com/maya-yoshida/profil/spieler/81789.
Transfer history data appended for: https://www.transfermarkt.com/kaique-rocha/profil/spieler/633377.
Transfer history data appended for: https://www.transfermarkt.com/keita-balde/profil/spieler/238752.
Transfer history data appended for: https://www.transfermarkt.com/antonino-la-gumina/profil/spieler/287876.
Transfer history data appended for: https://www.transfermarkt.com/tommaso-augello/profil/spieler/284595.
Transfer history data appended for: https://www.transfermarkt.com/adrien-silva/profil/spieler/56810.
Transfer history data appended for: https://www.transfermarkt.com/vasco-regini/profil/spieler/72274.
Transfer history data appended for: https://www.transfermarkt.com/morten-thorsby/profil/spieler/226524.
Transfer history data appended for: https://www.transfermarkt.com/albin-ekdal/profil/spieler/49275.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-askildsen/profil/spieler/574495.
Transfer history data appended for: https://www.transfermarkt.com/fabio-quagliarella/profil/spieler/22328.
Transfer history data appended for: https://www.transfermarkt.com/valerio-verre/profil/spieler/162961.
Transfer history data appended for: https://www.transfermarkt.com/omar-colley/profil/spieler/174733.
Transfer history data appended for: https://www.transfermarkt.com/jakub-jankto/profil/spieler/319160.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-damsgaard/profil/spieler/540941.
Transfer history data appended for: https://www.transfermarkt.com/karlo-letica/profil/spieler/318707.
Transfer history data appended for: https://www.transfermarkt.com/manolo-gabbiadini/profil/spieler/112343.
Transfer history data appended for: https://www.transfermarkt.com/nicola-ravaglia/profil/spieler/42796.
Transfer history data appended for: https://www.transfermarkt.com/tommaso-pobega/profil/spieler/392538.

Transfer history data appended for: https://www.transfermarkt.com/emmanuel-gyasi/profil/spieler/241076.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-mastinu/profil/spieler/397950.
Transfer history data appended for: https://www.transfermarkt.com/rafael/profil/spieler/84467.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-deiola/profil/spieler/235931.
Transfer history data appended for: https://www.transfermarkt.com/simone-bastoni/profil/spieler/257751.
Transfer history data appended for: https://www.transfermarkt.com/jeroen-zoet/profil/spieler/79045.
Transfer history data appended for: https://www.transfermarkt.com/lucien-agoume/profil/spieler/569384.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-marchizza/profil/spieler/297645.
Transfer history data appended for: https://www.transfermarkt.com/jacopo-sala/profil/spieler/96806.
Transfer history data appended for: https://www.transfermarkt.com/luca-vignali/profil/spieler/287367.
Transfer history data appended for: https://www.transfermarkt.com/mbala-nzola/profil/spieler/354814.
Transfer history data appended for: https://www.transfermarkt.com/luca-mora/profil/spieler/110338.
Transfer history data appended for: https://www.transfermarkt.com/salva-ferrer/profil/spieler/624548.
Transfer history data appended for: https://www.transfermarkt.com/andrej-galabinov/profil/spieler/67639.
Transfer history data appended for: https://www.transfermarkt.com/roberto-piccoli/profil/spieler/432092.
Transfer history data appended for: https://www.transfermarkt.com/ardian-ismajli/profil/spieler/435228.
Transfer history data appended for: https://www.transfermarkt.com/ivan-provedel/profil/spieler/197929.
Transfer history data appended for: https://www.transfermarkt.com/elio-capradossi/profil/spieler/238947.
Transfer history data appended for: https://www.transfermarkt.com/paolo-bartolomei/profil/spieler/281900.
Transfer history data appended for: https://www.transfermarkt.com/julian-chabot/profil/spieler/303219.
Transfer history data appended for: https://www.transfermarkt.com/titas-krapikas/profil/spieler/353609.
Transfer history data appended for: https://www.transfermarkt.com/juan-ramos/profil/spieler/288480.
Transfer history data appended for: https://www.transfermarkt.com/giulio-maggiore/profil/spieler/353796.
Transfer history data appended for: https://www.transfermarkt.com/matteo-ricci/profil/spieler/198087.
Transfer history data appended for: https://www.transfermarkt.com/claudio-terzi/profil/spieler/16873.
Transfer history data appended for: https://www.transfermarkt.com/martin-erlic/profil/spieler/357003.
Transfer history data appended for: https://www.transfermarkt.com/radja-nainggolan/profil/spieler/41982.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-brozovic/profil/spieler/156617.
Transfer history data appended for: https://www.transfermarkt.com/ivan-perisic/profil/spieler/42460.
Transfer history data appended for: https://www.transfermarkt.com/arturo-vidal/profil/spieler/37666.
Transfer history data appended for: https://www.transfermarkt.com/milan-skriniar/profil/spieler/204069.
Transfer history data appended for: https://www.transfermarkt.com/achraf-hakimi/profil/spieler/398073.
Transfer history data appended for: https://www.transfermarkt.com/ionu%C8%9B-radu/profil/spieler/303657.
Transfer history data appended for: https://www.transfermarkt.com/stefan-de-vrij/profil/spieler/111196.
Transfer history data appended for: https://www.transfermarkt.com/romelu-lukaku/profil/spieler/96341.
Transfer history data appended for: https://www.transfermarkt.com/axel-bakayoko/profil/spieler/354898.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-barella/profil/spieler/255942.
Transfer history data appended for: https://www.transfermarkt.com/andrea-pinamonti/profil/spieler/315865.
Transfer history data appended for: https://www.transfermarkt.com/ashley-young/profil/spieler/14086.
Transfer history data appended for: https://www.transfermarkt.com/stefano-sensi/profil/spieler/216179.
Transfer history data appended for: https://www.transfermarkt.com/danilo-dambrosio/profil/spieler/55769.
Transfer history data appended for: https://www.transfermarkt.com/filip-stankovic/profil/spieler/552223.
Transfer history data appended for: https://www.transfermarkt.com/daniele-padelli/profil/spieler/27807.
Transfer history data appended for: https://www.transfermarkt.com/samir-handanovic/profil/spieler/28021.
Transfer history data appended for: https://www.transfermarkt.com/roberto-gagliardini/profil/spieler/197471.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-kolarov/profil/spieler/46156.
Transfer history data appended for: https://www.transfermarkt.com/christian-eriksen/profil/spieler/69633.
Transfer history data appended for: https://www.transfermarkt.com/matteo-darmian/profil/spieler/54906.
Transfer history data appended for: https://www.transfermarkt.com/matias-vecino/profil/spieler/143812.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-bastoni/profil/spieler/315853.
Transfer history data appended for: https://www.transfermarkt.com/lautaro-martinez/profil/spieler/406625.
Transfer history data appended for: https://www.transfermarkt.com/andrea-ranocchia/profil/spieler/44327.
Transfer history data appended for: https://www.transfermarkt.com/elhan-kastrati/profil/spieler/258608.
Transfer history data appended for: https://www.transfermarkt.com/karamoko-cisse/profil/spieler/65635.
Transfer history data appended for: https://www.transfermarkt.com/camillo-tavernelli/profil/spieler/410655.
Transfer history data appended for: https://www.transfermarkt.com/davide-adorni/profil/spieler/163212.
Transfer history data appended for: https://www.transfermarkt.com/nicola-pavan/profil/spieler/167480.
Transfer history data appended for: https://www.transfermarkt.com/alessio-vita/profil/spieler/163606.
Transfer history data appended for: https://www.transfermarkt.com/gabriele-plechero/profil/spieler/555189.
Transfer history data appended for: https://www.transfermarkt.com/luca-ghiringhelli/profil/spieler/130352.
Transfer history data appended for: https://www.transfermarkt.com/marco-rosafio/profil/spieler/199722.
Transfer history data appended for: https://www.transfermarkt.com/frank-tsadjout/profil/spieler/392545.
Transfer history data appended for: https://www.transfermarkt.com/roberto-ogunseye/profil/spieler/192105.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-bassano/profil/spieler/455374.
Transfer history data appended for: https://www.transfermarkt.com/daniele-donnarumma/profil/spieler/167900.
Transfer history data appended for: https://www.transfermarkt.com/manuel-iori/profil/spieler/82684.
Transfer history data appended for: https://www.transfermarkt.com/federico-proia/profil/spieler/287651.
Transfer history data appended for: https://www.transfermarkt.com/tommaso-cassandro/profil/spieler/412649.
Transfer history data appended for: https://www.transfermarkt.com/luca-maniero/profil/spieler/176182.
Transfer history data appended for: https://www.transfermarkt.com/domenico-frare/profil/spieler/287639.
Transfer history data appended for: https://www.transfermarkt.com/valerio-mastrantonio/profil/spieler/459725.
Transfer history data appended for: https://www.transfermarkt.com/paolo-grillo/profil/spieler/336963.
Transfer history data appended for: https://www.transfermarkt.com/amedeo-benedetti/profil/spieler/148585.
Transfer history data appended for: https://www.transfermarkt.com/agostino-camigliano/profil/spieler/240400.
Transfer history data appended for: https://www.transfermarkt.com/christian-durso/profil/spieler/340444.
Transfer history data appended for: https://www.transfermarkt.com/mario-gargiulo/profil/spieler/242469.
Transfer history data appended for: https://www.transfermarkt.com/simone-branca/profil/spieler/167793.
Transfer history data appended for: https://www.transfermarkt.com/andrea-marcucci/profil/spieler/319180.
Transfer history data appended for: https://www.transfermarkt.com/gabriele-rolando/profil/spieler/249068.

Transfer history data appended for: https://www.transfermarkt.com/jeremy-menez/profil/spieler/16993.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-stavropoulos/profil/spieler/402970.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-peli/profil/spieler/459149.
Transfer history data appended for: https://www.transfermarkt.com/thiago-cionek/profil/spieler/79510.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-bianchi/profil/spieler/167792.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-loiacono/profil/spieler/331471.
Transfer history data appended for: https://www.transfermarkt.com/daniele-gasparetto/profil/spieler/44628.
Transfer history data appended for: https://www.transfermarkt.com/michael-folorunsho/profil/spieler/377042.
Transfer history data appended for: https://www.transfermarkt.com/enrico-guarna/profil/spieler/22304.
Transfer history data appended for: https://www.transfermarkt.com/kyle-lafferty/profil/spieler/36884.
Transfer history data appended for: https://www.transfermarkt.com/daniele-liotti/profil/spieler/199767.
Transfer history data appended for: https://www.transfermarkt.com/nicola-bellomo/profil/spieler/107958.
Transfer history data appended for: https://www.transfermarkt.com/francesco-de-rose/profil/spieler/124932.
Transfer history data appended for: https://www.transfermarkt.com/hachim-mastour/profil/spieler/253267.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-charpentier/profil/spieler/660342.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-plizzari/profil/spieler/357991.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-farroni/profil/spieler/329669.
Transfer history data appended for: https://www.transfermarkt.com/rigoberto-rivas/profil/spieler/451353.
Transfer history data appended for: https://www.transfermarkt.com/nikola-vasic/profil/spieler/503496.
Transfer history data appended for: https://www.transfermarkt.com/enrico-del-prato/profil/spieler/392956.
Transfer history data appended for: https://www.transfermarkt.com/mouhamadou-sarr/profil/spieler/338101.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-avlonitis/profil/spieler/60164.
Transfer history data appended for: https://www.transfermarkt.com/gabriele-corbo/profil/spieler/423614.
Transfer history data appended for: https://www.transfermarkt.com/khadim-ndiaye/profil/spieler/623851.
Transfer history data appended for: https://www.transfermarkt.com/nikola-ninkovic/profil/spieler/168944.
Transfer history data appended for: https://www.transfermarkt.com/mirko-eramo/profil/spieler/61783.
Transfer history data appended for: https://www.transfermarkt.com/raffaele-pucino/profil/spieler/139307.
Transfer history data appended for: https://www.transfermarkt.com/riad-baji%C4%87/profil/spieler/263267.
Transfer history data appended for: https://www.transfermarkt.com/dario-saric/profil/spieler/293228.
Transfer history data appended for: https://www.transfermarkt.com/danilo-quaranta/profil/spieler/396307.
Transfer history data appended for: https://www.transfermarkt.com/christian-scorza/profil/spieler/460003.
Transfer history data appended for: https://www.transfermarkt.com/christos-donis/profil/spieler/212432.
Transfer history data appended for: https://www.transfermarkt.com/dean-lico/profil/spieler/454292.
Transfer history data appended for: https://www.transfermarkt.com/abdelhamid-sabiri/profil/spieler/340394.
Transfer history data appended for: https://www.transfermarkt.com/cosimo-chirico/profil/spieler/165852.
Transfer history data appended for: https://www.transfermarkt.com/simone-sini/profil/spieler/110934.
Transfer history data appended for: https://www.transfermarkt.com/michele-cavion/profil/spieler/199971.
Transfer history data appended for: https://www.transfermarkt.com/oliver-kragl/profil/spieler/56513.
Transfer history data appended for: https://www.transfermarkt.com/niccolo-tofanari/profil/spieler/340442.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-matos/profil/spieler/535958.
Transfer history data appended for: https://www.transfermarkt.com/luca-bolletta/profil/spieler/704468.
Transfer history data appended for: https://www.transfermarkt.com/daniele-sarzi-puttini/profil/spieler/287344.
Transfer history data appended for: https://www.transfermarkt.com/edoardo-tassi/profil/spieler/347587.
Transfer history data appended for: https://www.transfermarkt.com/emin-ghazoini/profil/spieler/460035.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-brosco/profil/spieler/89034.
Transfer history data appended for: https://www.transfermarkt.com/lukas-spendlhofer/profil/spieler/126114.
Transfer history data appended for: https://www.transfermarkt.com/alberto-gerbo/profil/spieler/88690.
Transfer history data appended for: https://www.transfermarkt.com/lubomir-tupta/profil/spieler/344806.
Transfer history data appended for: https://www.transfermarkt.com/apostolos-vellios/profil/spieler/124495.
Transfer history data appended for: https://www.transfermarkt.com/nicholas-pierini/profil/spieler/372720.
Transfer history data appended for: https://www.transfermarkt.com/gianmarco-cangiano/profil/spieler/496270.
Transfer history data appended for: https://www.transfermarkt.com/filippo-falco/profil/spieler/70689.
Transfer history data appended for: https://www.transfermarkt.com/claud-adjapong/profil/spieler/337716.
Transfer history data appended for: https://www.transfermarkt.com/mariusz-stepinski/profil/spieler/210363.
Transfer history data appended for: https://www.transfermarkt.com/liam-henderson/profil/spieler/193867.
Transfer history data appended for: https://www.transfermarkt.com/gabriel/profil/spieler/79242.
Transfer history data appended for: https://www.transfermarkt.com/fabio-lucioni/profil/spieler/160561.
Transfer history data appended for: https://www.transfermarkt.com/luca-paganini/profil/spieler/167444.
Transfer history data appended for: https://www.transfermarkt.com/massimo-coda/profil/spieler/33763.
Transfer history data appended for: https://www.transfermarkt.com/luca-rossettini/profil/spieler/60128.
Transfer history data appended for: https://www.transfermarkt.com/zan-majer/profil/spieler/180805.
Transfer history data appended for: https://www.transfermarkt.com/ilario-monterisi/profil/spieler/550116.
Transfer history data appended for: https://www.transfermarkt.com/biagio-meccariello/profil/spieler/124002.
Transfer history data appended for: https://www.transfermarkt.com/marco-bleve/profil/spieler/215167.
Transfer history data appended for: https://www.transfermarkt.com/leonard-zuta/profil/spieler/214625.
Transfer history data appended for: https://www.transfermarkt.com/mattia-felici/profil/spieler/600041.
Transfer history data appended for: https://www.transfermarkt.com/pablo-rodriguez/profil/spieler/537765.
Transfer history data appended for: https://www.transfermarkt.com/kastriot-dermaku/profil/spieler/163647.
Transfer history data appended for: https://www.transfermarkt.com/marco-mancosu/profil/spieler/51736.
Transfer history data appended for: https://www.transfermarkt.com/sergio-maselli/profil/spieler/542572.
Transfer history data appended for: https://www.transfermarkt.com/mauro-vigorito/profil/spieler/88595.
Transfer history data appended for: https://www.transfermarkt.com/antonino-gallo/profil/spieler/392516.
Transfer history data appended for: https://www.transfermarkt.com/roberto-pierno/profil/spieler/542570.
Transfer history data appended for: https://www.transfermarkt.com/john-bjorkengren/profil/spieler/413942.
Transfer history data appended for: https://www.transfermarkt.com/edgaras-dubickas/profil/spieler/395295.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-tachtsidis/profil/spieler/62415.
Transfer history data appended for: https://www.transfermarkt.com/marcin-listkowski/profil/spieler/291276.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-borbei/profil/spieler/667640.
Transfer history data appended for: https://www.transfermarkt.com/pierluca-luciani/profil/spieler/672869.

Transfer history data appended for: https://www.transfermarkt.com/alessandro-iacobucci/profil/spieler/104290.
Transfer history data appended for: https://www.transfermarkt.com/andrija-novakovich/profil/spieler/336160.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-baroni/profil/spieler/398025.
Transfer history data appended for: https://www.transfermarkt.com/michele-volpe/profil/spieler/340657.
Transfer history data appended for: https://www.transfermarkt.com/marcos-curado/profil/spieler/334371.
Transfer history data appended for: https://www.transfermarkt.com/mattia-vitale/profil/spieler/291432.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-brighenti/profil/spieler/109110.
Transfer history data appended for: https://www.transfermarkt.com/federico-dionisi/profil/spieler/119369.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-salvi/profil/spieler/150462.
Transfer history data appended for: https://www.transfermarkt.com/daniel-boloca/profil/spieler/441515.
Transfer history data appended for: https://www.transfermarkt.com/marcus-rohden/profil/spieler/205809.
Transfer history data appended for: https://www.transfermarkt.com/camillo-ciano/profil/spieler/61511.
Transfer history data appended for: https://www.transfermarkt.com/piotr-parzyszek/profil/spieler/155202.
Transfer history data appended for: https://www.transfermarkt.com/andrea-beghetto/profil/spieler/199941.
Transfer history data appended for: https://www.transfermarkt.com/salvatore-delia/profil/spieler/62365.
Transfer history data appended for: https://www.transfermarkt.com/alessio-tribuzzi/profil/spieler/395546.
Transfer history data appended for: https://www.transfermarkt.com/przemyslaw-szyminski/profil/spieler/255461.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-marciano/profil/spieler/460034.
Transfer history data appended for: https://www.transfermarkt.com/marco-capuano/profil/spieler/164091.
Transfer history data appended for: https://www.transfermarkt.com/marco-carraro/profil/spieler/297630.
Transfer history data appended for: https://www.transfermarkt.com/nikolas-spalek/profil/spieler/243239.
Transfer history data appended for: https://www.transfermarkt.com/bruno-martella/profil/spieler/164108.
Transfer history data appended for: https://www.transfermarkt.com/andrea-cistana/profil/spieler/337381.
Transfer history data appended for: https://www.transfermarkt.com/ales-mateju/profil/spieler/242078.
Transfer history data appended for: https://www.transfermarkt.com/simon-skrabb/profil/spieler/187047.
Transfer history data appended for: https://www.transfermarkt.com/andrea-papetti/profil/spieler/503619.
Transfer history data appended for: https://www.transfermarkt.com/jakub-labojko/profil/spieler/387529.
Transfer history data appended for: https://www.transfermarkt.com/florian-aye/profil/spieler/372713.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-bisoli/profil/spieler/163216.
Transfer history data appended for: https://www.transfermarkt.com/jhon-chancellor/profil/spieler/213614.
Transfer history data appended for: https://www.transfermarkt.com/alfredo-donnarumma/profil/spieler/130485.
Transfer history data appended for: https://www.transfermarkt.com/massimiliano-mangraviti/profil/spieler/395805.
Transfer history data appended for: https://www.transfermarkt.com/emanuele-ndoj/profil/spieler/287717.
Transfer history data appended for: https://www.transfermarkt.com/filip-jagiello/profil/spieler/242813.
Transfer history data appended for: https://www.transfermarkt.com/tom-van-de-looi/profil/spieler/420189.
Transfer history data appended for: https://www.transfermarkt.com/daniele-dessena/profil/spieler/29962.
Transfer history data appended for: https://www.transfermarkt.com/ernesto-torregrossa/profil/spieler/159883.
Transfer history data appended for: https://www.transfermarkt.com/jesse-joronen/profil/spieler/131758.
Transfer history data appended for: https://www.transfermarkt.com/jaromir-zmrhal/profil/spieler/235413.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-andrenacci/profil/spieler/234880.
Transfer history data appended for: https://www.transfermarkt.com/matic-kotnik/profil/spieler/96189.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-semprini/profil/spieler/315843.
Transfer history data appended for: https://www.transfermarkt.com/holmbert-aron-fridjonsson/profil/spieler/149996.
Transfer history data appended for: https://www.transfermarkt.com/stefano-filigheddu/profil/spieler/616655.
Transfer history data appended for: https://www.transfermarkt.com/andrea-ghezzi/profil/spieler/536460.
Transfer history data appended for: https://www.transfermarkt.com/mattia-valoti/profil/spieler/167741.
Transfer history data appended for: https://www.transfermarkt.com/enrico-brignola/profil/spieler/323147.
Transfer history data appended for: https://www.transfermarkt.com/marko-jankovic/profil/spieler/222223.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-strefezza/profil/spieler/457673.
Transfer history data appended for: https://www.transfermarkt.com/jaume-cuellar/profil/spieler/466808.
Transfer history data appended for: https://www.transfermarkt.com/federico-di-francesco/profil/spieler/38607.
Transfer history data appended for: https://www.transfermarkt.com/caleb-okoli/profil/spieler/461833.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-spaltro/profil/spieler/459180.
Transfer history data appended for: https://www.transfermarkt.com/maurice-gomis/profil/spieler/354381.
Transfer history data appended for: https://www.transfermarkt.com/francesco-vicari/profil/spieler/240158.
Transfer history data appended for: https://www.transfermarkt.com/alberto-paloschi/profil/spieler/68306.
Transfer history data appended for: https://www.transfermarkt.com/demba-thiam/profil/spieler/435406.
Transfer history data appended for: https://www.transfermarkt.com/salvatore-esposito/profil/spieler/390160.
Transfer history data appended for: https://www.transfermarkt.com/cesare-galeotti/profil/spieler/616902.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-dickmann/profil/spieler/283060.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-salamon/profil/spieler/71019.
Transfer history data appended for: https://www.transfermarkt.com/georgi-tunjov/profil/spieler/363610.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-murgia/profil/spieler/289061.
Transfer history data appended for: https://www.transfermarkt.com/sebastiano-esposito/profil/spieler/538918.
Transfer history data appended for: https://www.transfermarkt.com/marco-sala/profil/spieler/392570.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-sernicola/profil/spieler/340707.
Transfer history data appended for: https://www.transfermarkt.com/lucas-castro/profil/spieler/105892.
Transfer history data appended for: https://www.transfermarkt.com/luca-munaretti/profil/spieler/619324.
Transfer history data appended for: https://www.transfermarkt.com/felice-damico/profil/spieler/392500.
Transfer history data appended for: https://www.transfermarkt.com/sauli-vaisanen/profil/spieler/261095.
Transfer history data appended for: https://www.transfermarkt.com/sergej-grubac/profil/spieler/429318.
Transfer history data appended for: https://www.transfermarkt.com/matteo-cotali/profil/spieler/382567.
Transfer history data appended for: https://www.transfermarkt.com/michael-fabbro/profil/spieler/253855.
Transfer history data appended for: https://www.transfermarkt.com/luigi-canotto/profil/spieler/188436.
Transfer history data appended for: https://www.transfermarkt.com/nabil-makni/profil/spieler/710030.
Transfer history data appended for: https://www.transfermarkt.com/joseph-colley/profil/spieler/303455.
Transfer history data appended for: https://www.transfermarkt.com/maxime-leverbe/profil/spieler/451310.
Transfer history data appended for: https://www.transfermarkt.com/marin-cavar/profil/spieler/529612.
Transfer history data appended for: https://www.transfermarkt.com/david-ivan/profil/spieler/168416.

Transfer history data appended for: https://www.transfermarkt.com/jonathan-morsay/profil/spieler/298313.
Transfer history data appended for: https://www.transfermarkt.com/manuel-de-luca/profil/spieler/375816.
Transfer history data appended for: https://www.transfermarkt.com/andrea-seculin/profil/spieler/85380.
Transfer history data appended for: https://www.transfermarkt.com/julian-illanes/profil/spieler/441264.
Transfer history data appended for: https://www.transfermarkt.com/elimelech-enyan/profil/spieler/459961.
Transfer history data appended for: https://www.transfermarkt.com/vasile-mogos/profil/spieler/324214.
Transfer history data appended for: https://www.transfermarkt.com/mattia-viviani/profil/spieler/403845.
Transfer history data appended for: https://www.transfermarkt.com/daniel-pavlev/profil/spieler/437334.
Transfer history data appended for: https://www.transfermarkt.com/guillaume-gigliotti/profil/spieler/60541.
Transfer history data appended for: https://www.transfermarkt.com/adrian-semper/profil/spieler/317057.
Transfer history data appended for: https://www.transfermarkt.com/filippo-tuzzo/profil/spieler/433089.
Transfer history data appended for: https://www.transfermarkt.com/manuel-pucciarelli/profil/spieler/163683.
Transfer history data appended for: https://www.transfermarkt.com/francesco-margiotta/profil/spieler/165891.
Transfer history data appended for: https://www.transfermarkt.com/michele-rigione/profil/spieler/88705.
Transfer history data appended for: https://www.transfermarkt.com/strahinja-tanasijevic/profil/spieler/400001.
Transfer history data appended for: https://www.transfermarkt.com/luca-palmiero/profil/spieler/240357.
Transfer history data appended for: https://www.transfermarkt.com/pietro-rovaglia/profil/spieler/421417.
Transfer history data appended for: https://www.transfermarkt.com/emanuele-zuelli/profil/spieler/477556.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-di-noia/profil/spieler/163264.
Transfer history data appended for: https://www.transfermarkt.com/massimo-bertagnoli/profil/spieler/394352.
Transfer history data appended for: https://www.transfermarkt.com/michele-bragantini/profil/spieler/621554.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-bassoli/profil/spieler/112457.
Transfer history data appended for: https://www.transfermarkt.com/filippo-berra/profil/spieler/213952.
Transfer history data appended for: https://www.transfermarkt.com/luca-zanon/profil/spieler/280044.
Transfer history data appended for: https://www.transfermarkt.com/giacomo-bindi/profil/spieler/45568.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-mallamo/profil/spieler/346560.
Transfer history data appended for: https://www.transfermarkt.com/matteo-rossetti/profil/spieler/440878.
Transfer history data appended for: https://www.transfermarkt.com/roberto-zammarini/profil/spieler/331197.
Transfer history data appended for: https://www.transfermarkt.com/karlo-butic/profil/spieler/388121.
Transfer history data appended for: https://www.transfermarkt.com/davide-gavazzi/profil/spieler/124909.
Transfer history data appended for: https://www.transfermarkt.com/patrick-ciurria/profil/spieler/255838.
Transfer history data appended for: https://www.transfermarkt.com/samuele-perisan/profil/spieler/301240.
Transfer history data appended for: https://www.transfermarkt.com/simone-pasa/profil/spieler/76895.
Transfer history data appended for: https://www.transfermarkt.com/nicola-falasco/profil/spieler/176180.
Transfer history data appended for: https://www.transfermarkt.com/federico-secli/profil/spieler/592513.
Transfer history data appended for: https://www.transfermarkt.com/aldo-banse/profil/spieler/604690.
Transfer history data appended for: https://www.transfermarkt.com/luca-magnino/profil/spieler/297444.
Transfer history data appended for: https://www.transfermarkt.com/pietro-passador/profil/spieler/617164.
Transfer history data appended for: https://www.transfermarkt.com/luca-tremolada/profil/spieler/88713.
Transfer history data appended for: https://www.transfermarkt.com/adam-chrzanowski/profil/spieler/320898.
Transfer history data appended for: https://www.transfermarkt.com/michele-camporese/profil/spieler/62716.
Transfer history data appended for: https://www.transfermarkt.com/gianvito-misuraca/profil/spieler/61753.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-musiolik/profil/spieler/267152.
Transfer history data appended for: https://www.transfermarkt.com/manuel-scavone/profil/spieler/32107.
Transfer history data appended for: https://www.transfermarkt.com/giacomo-calo/profil/spieler/301235.
Transfer history data appended for: https://www.transfermarkt.com/davide-diaw/profil/spieler/404995.
Transfer history data appended for: https://www.transfermarkt.com/alberto-barison/profil/spieler/199940.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-vogliacco/profil/spieler/330208.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-lunetta/profil/spieler/287710.
Transfer history data appended for: https://www.transfermarkt.com/augustus-kargbo/profil/spieler/549791.
Transfer history data appended for: https://www.transfermarkt.com/niko-kirwan/profil/spieler/464561.
Transfer history data appended for: https://www.transfermarkt.com/bright-gyamfi/profil/spieler/339982.
Transfer history data appended for: https://www.transfermarkt.com/luca-zamparo/profil/spieler/102413.
Transfer history data appended for: https://www.transfermarkt.com/simone-mazzocchi/profil/spieler/337809.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-martinelli/profil/spieler/122430.
Transfer history data appended for: https://www.transfermarkt.com/matteo-voltolini/profil/spieler/341389.
Transfer history data appended for: https://www.transfermarkt.com/salvatore-pezzella/profil/spieler/421871.
Transfer history data appended for: https://www.transfermarkt.com/giacomo-venturi/profil/spieler/120236.
Transfer history data appended for: https://www.transfermarkt.com/andrea-galeazzi/profil/spieler/695147.
Transfer history data appended for: https://www.transfermarkt.com/igor-radrezza/profil/spieler/167330.
Transfer history data appended for: https://www.transfermarkt.com/luca-germoni/profil/spieler/339566.
Transfer history data appended for: https://www.transfermarkt.com/arlind-ajeti/profil/spieler/159288.
Transfer history data appended for: https://www.transfermarkt.com/simone-muratore/profil/spieler/297648.
Transfer history data appended for: https://www.transfermarkt.com/ivan-varone/profil/spieler/123258.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-cambiaghi/profil/spieler/459151.
Transfer history data appended for: https://www.transfermarkt.com/paolo-rozzio/profil/spieler/61617.
Transfer history data appended for: https://www.transfermarkt.com/michele-cerofolini/profil/spieler/370701.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-zampano/profil/spieler/199597.
Transfer history data appended for: https://www.transfermarkt.com/mattia-marchi/profil/spieler/99408.
Transfer history data appended for: https://www.transfermarkt.com/marcos-espeche/profil/spieler/331365.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-libutti/profil/spieler/341481.
Transfer history data appended for: https://www.transfermarkt.com/andrea-galeotti/profil/spieler/604201.
Transfer history data appended for: https://www.transfermarkt.com/fausto-rossi/profil/spieler/81743.
Transfer history data appended for: https://www.transfermarkt.com/davide-voltan/profil/spieler/199947.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-gatti/profil/spieler/337385.
Transfer history data appended for: https://www.transfermarkt.com/andrea-colpani/profil/spieler/392959.
Transfer history data appended for: https://www.transfermarkt.com/antonio-marin/profil/spieler/371016.
Transfer history data appended for: https://www.transfermarkt.com/mario-sampirisi/profil/spieler/160357.
Transfer history data appended for: https://www.transfermarkt.com/marco-fossati/profil/spieler/110931.

Transfer history data appended for: https://www.transfermarkt.com/andrea-barberis/profil/spieler/146680.
Transfer history data appended for: https://www.transfermarkt.com/marco-armellino/profil/spieler/144091.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-pirola/profil/spieler/487834.
Transfer history data appended for: https://www.transfermarkt.com/davide-bettella/profil/spieler/357995.
Transfer history data appended for: https://www.transfermarkt.com/eugenio-lamanna/profil/spieler/85240.
Transfer history data appended for: https://www.transfermarkt.com/jose-machin/profil/spieler/355104.
Transfer history data appended for: https://www.transfermarkt.com/michele-di-gregorio/profil/spieler/301238.
Transfer history data appended for: https://www.transfermarkt.com/mirko-maric/profil/spieler/215649.
Transfer history data appended for: https://www.transfermarkt.com/andrea-derrico/profil/spieler/160302.
Transfer history data appended for: https://www.transfermarkt.com/mattia-finotto/profil/spieler/284604.
Transfer history data appended for: https://www.transfermarkt.com/christian-gytkjaer/profil/spieler/76274.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-paletta/profil/spieler/30767.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-bellusci/profil/spieler/57354.
Transfer history data appended for: https://www.transfermarkt.com/nicola-rigoni/profil/spieler/61757.
Transfer history data appended for: https://www.transfermarkt.com/luca-lombardi/profil/spieler/644156.
Transfer history data appended for: https://www.transfermarkt.com/giulio-donati/profil/spieler/88684.
Transfer history data appended for: https://www.transfermarkt.com/carlos-augusto/profil/spieler/585982.
Transfer history data appended for: https://www.transfermarkt.com/davide-frattesi/profil/spieler/394300.
Transfer history data appended for: https://www.transfermarkt.com/daniele-sommariva/profil/spieler/312773.
Transfer history data appended for: https://www.transfermarkt.com/antonino-barilla/profil/spieler/39828.
Transfer history data appended for: https://www.transfermarkt.com/filippo-scaglia/profil/spieler/163597.
Transfer history data appended for: https://www.transfermarkt.com/edgar-elizalde/profil/spieler/465677.
Transfer history data appended for: https://www.transfermarkt.com/milo-scaron-bo%C4%8Di%C4%87/profil/spieler/398945.
Transfer history data appended for: https://www.transfermarkt.com/raul-asencio/profil/spieler/340260.
Transfer history data appended for: https://www.transfermarkt.com/christian-ventola/profil/spieler/336925.
Transfer history data appended for: https://www.transfermarkt.com/fabio-maistro/profil/spieler/398031.
Transfer history data appended for: https://www.transfermarkt.com/stephane-omeonga/profil/spieler/342472.
Transfer history data appended for: https://www.transfermarkt.com/mardochee-nzita/profil/spieler/463738.
Transfer history data appended for: https://www.transfermarkt.com/edoardo-masciangelo/profil/spieler/286293.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-arlotti/profil/spieler/646165.
Transfer history data appended for: https://www.transfermarkt.com/gennaro-scognamiglio/profil/spieler/119082.
Transfer history data appended for: https://www.transfermarkt.com/luca-crecco/profil/spieler/228604.
Transfer history data appended for: https://www.transfermarkt.com/mirko-drudi/profil/spieler/42762.
Transfer history data appended for: https://www.transfermarkt.com/christian-capone/profil/spieler/315856.
Transfer history data appended for: https://www.transfermarkt.com/damir-ceter/profil/spieler/460898.
Transfer history data appended for: https://www.transfermarkt.com/mirko-valdifiori/profil/spieler/84903.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-belloni/profil/spieler/744844.
Transfer history data appended for: https://www.transfermarkt.com/gabriele-quacquarelli/profil/spieler/629577.
Transfer history data appended for: https://www.transfermarkt.com/pawel-jaroszynski/profil/spieler/287600.
Transfer history data appended for: https://www.transfermarkt.com/andrea-di-grazia/profil/spieler/287265.
Transfer history data appended for: https://www.transfermarkt.com/dejan-voki%C4%87/profil/spieler/290698.
Transfer history data appended for: https://www.transfermarkt.com/raoul-bellanova/profil/spieler/357992.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-guth/profil/spieler/492313.
Transfer history data appended for: https://www.transfermarkt.com/leandro-fernandes/profil/spieler/339335.
Transfer history data appended for: https://www.transfermarkt.com/amadou-diambo/profil/spieler/708868.
Transfer history data appended for: https://www.transfermarkt.com/salvatore-bocchetti/profil/spieler/42678.
Transfer history data appended for: https://www.transfermarkt.com/vincenzo-fiorillo/profil/spieler/55000.
Transfer history data appended for: https://www.transfermarkt.com/massimiliano-busellato/profil/spieler/134408.
Transfer history data appended for: https://www.transfermarkt.com/alessio-riccardi/profil/spieler/421765.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-sorrentino/profil/spieler/542588.
Transfer history data appended for: https://www.transfermarkt.com/mattia-del-favero/profil/spieler/265079.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-radaelli/profil/spieler/460114.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-nikolaou/profil/spieler/292772.
Transfer history data appended for: https://www.transfermarkt.com/aleksa-terzic/profil/spieler/404260.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-haas/profil/spieler/192638.
Transfer history data appended for: https://www.transfermarkt.com/leandro-pratelli/profil/spieler/603695.
Transfer history data appended for: https://www.transfermarkt.com/samuele-damiani/profil/spieler/390117.
Transfer history data appended for: https://www.transfermarkt.com/augustinas-klimavicius/profil/spieler/467783.
Transfer history data appended for: https://www.transfermarkt.com/roberto-pirrello/profil/spieler/250781.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-mancuso/profil/spieler/160344.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-fiamozzi/profil/spieler/197745.
Transfer history data appended for: https://www.transfermarkt.com/mattia-viti/profil/spieler/493702.
Transfer history data appended for: https://www.transfermarkt.com/simone-romagnoli/profil/spieler/88706.
Transfer history data appended for: https://www.transfermarkt.com/andrea-la-mantia/profil/spieler/134983.
Transfer history data appended for: https://www.transfermarkt.com/filippo-bandinelli/profil/spieler/240934.
Transfer history data appended for: https://www.transfermarkt.com/davide-zappella/profil/spieler/390120.
Transfer history data appended for: https://www.transfermarkt.com/ryder-matos/profil/spieler/62713.
Transfer history data appended for: https://www.transfermarkt.com/andrea-cambiaso/profil/spieler/459658.
Transfer history data appended for: https://www.transfermarkt.com/jacopo-furlan/profil/spieler/163652.
Transfer history data appended for: https://www.transfermarkt.com/nicolo-casale/profil/spieler/389837.
Transfer history data appended for: https://www.transfermarkt.com/samuele-ricci/profil/spieler/467992.
Transfer history data appended for: https://www.transfermarkt.com/szymon-zurkowski/profil/spieler/387234.
Transfer history data appended for: https://www.transfermarkt.com/leo-stulac/profil/spieler/171159.
Transfer history data appended for: https://www.transfermarkt.com/fabiano-parisi/profil/spieler/547985.
Transfer history data appended for: https://www.transfermarkt.com/angelo-corsi/profil/spieler/102562.
Transfer history data appended for: https://www.transfermarkt.com/gianmarco-ingrosso/profil/spieler/61605.
Transfer history data appended for: https://www.transfermarkt.com/raffaele-schiavi/profil/spieler/28857.
Transfer history data appended for: https://www.transfermarkt.com/ihsan-sacko/profil/spieler/412095.

Transfer history data appended for: https://www.transfermarkt.com/brayan-vera/profil/spieler/642967.
Transfer history data appended for: https://www.transfermarkt.com/gianluigi-sueva/profil/spieler/531973.
Transfer history data appended for: https://www.transfermarkt.com/mirko-bruccini/profil/spieler/42117.
Transfer history data appended for: https://www.transfermarkt.com/daniele-sciaudone/profil/spieler/102368.
Transfer history data appended for: https://www.transfermarkt.com/mirko-carretta/profil/spieler/82648.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-bahlouli/profil/spieler/461600.
Transfer history data appended for: https://www.transfermarkt.com/devid-eugene-bouah/profil/spieler/457235.
Transfer history data appended for: https://www.transfermarkt.com/ben-lhassine-kone/profil/spieler/522681.
Transfer history data appended for: https://www.transfermarkt.com/luca-bittante/profil/spieler/163062.
Transfer history data appended for: https://www.transfermarkt.com/kristjan-matosevic/profil/spieler/340448.
Transfer history data appended for: https://www.transfermarkt.com/gennaro-borrelli/profil/spieler/459988.
Transfer history data appended for: https://www.transfermarkt.com/andrea-tiritiello/profil/spieler/248695.
Transfer history data appended for: https://www.transfermarkt.com/davide-petrucci/profil/spieler/96798.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-idda/profil/spieler/331477.
Transfer history data appended for: https://www.transfermarkt.com/wladimiro-falcone/profil/spieler/238537.
Transfer history data appended for: https://www.transfermarkt.com/umberto-saracco/profil/spieler/199001.
Transfer history data appended for: https://www.transfermarkt.com/abou-ba/profil/spieler/427653.
Transfer history data appended for: https://www.transfermarkt.com/matteo-legittimo/profil/spieler/61606.
Transfer history data appended for: https://www.transfermarkt.com/michele-fornasier/profil/spieler/141654.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-fiordaliso/profil/spieler/386447.
Transfer history data appended for: https://www.transfermarkt.com/filippo-nardi/profil/spieler/404969.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-gaetano/profil/spieler/358008.
Transfer history data appended for: https://www.transfermarkt.com/zan-celar/profil/spieler/340427.
Transfer history data appended for: https://www.transfermarkt.com/daniel-ciofani/profil/spieler/29605.
Transfer history data appended for: https://www.transfermarkt.com/emanuele-valeri/profil/spieler/445126.
Transfer history data appended for: https://www.transfermarkt.com/luca-strizzolo/profil/spieler/155802.
Transfer history data appended for: https://www.transfermarkt.com/giacomo-volpe/profil/spieler/340265.
Transfer history data appended for: https://www.transfermarkt.com/cristian-buonaiuto/profil/spieler/187384.
Transfer history data appended for: https://www.transfermarkt.com/enrico-alfonso/profil/spieler/34334.
Transfer history data appended for: https://www.transfermarkt.com/samuel-gustafson/profil/spieler/255473.
Transfer history data appended for: https://www.transfermarkt.com/emanuele-terranova/profil/spieler/61770.
Transfer history data appended for: https://www.transfermarkt.com/fabio-ceravolo/profil/spieler/35743.
Transfer history data appended for: https://www.transfermarkt.com/matteo-bianchetti/profil/spieler/160986.
Transfer history data appended for: https://www.transfermarkt.com/nadir-zortea/profil/spieler/392966.
Transfer history data appended for: https://www.transfermarkt.com/andrea-zaccagno/profil/spieler/291314.
Transfer history data appended for: https://www.transfermarkt.com/marco-pinato/profil/spieler/164020.
Transfer history data appended for: https://www.transfermarkt.com/luca-ravanelli/profil/spieler/312341.
Transfer history data appended for: https://www.transfermarkt.com/matteo-ghisolfi/profil/spieler/604630.
Transfer history data appended for: https://www.transfermarkt.com/tiago-casasola/profil/spieler/224044.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-micai/profil/spieler/167685.
Transfer history data appended for: https://www.transfermarkt.com/frederic-veseli/profil/spieler/111433.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-barone/profil/spieler/718128.
Transfer history data appended for: https://www.transfermarkt.com/emanuele-cicerelli/profil/spieler/265320.
Transfer history data appended for: https://www.transfermarkt.com/joel-baraye/profil/spieler/325897.
Transfer history data appended for: https://www.transfermarkt.com/marius-adamonis/profil/spieler/300137.
Transfer history data appended for: https://www.transfermarkt.com/vid-belec/profil/spieler/73090.
Transfer history data appended for: https://www.transfermarkt.com/mirko-antonucci/profil/spieler/315852.
Transfer history data appended for: https://www.transfermarkt.com/niccolo-giannetti/profil/spieler/99235.
Transfer history data appended for: https://www.transfermarkt.com/guido-guerrieri/profil/spieler/256996.
Transfer history data appended for: https://www.transfermarkt.com/andrea-schiavone/profil/spieler/136133.
Transfer history data appended for: https://www.transfermarkt.com/andre-anderson/profil/spieler/601577.
Transfer history data appended for: https://www.transfermarkt.com/francesco-di-tacchio/profil/spieler/84766.
Transfer history data appended for: https://www.transfermarkt.com/andreas-karo/profil/spieler/203966.
Transfer history data appended for: https://www.transfermarkt.com/walter-lopez/profil/spieler/58581.
Transfer history data appended for: https://www.transfermarkt.com/luka-bogdan/profil/spieler/226058.
Transfer history data appended for: https://www.transfermarkt.com/valerio-mantovani/profil/spieler/324378.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-capezzi/profil/spieler/84442.
Transfer history data appended for: https://www.transfermarkt.com/cedric-gondo/profil/spieler/213854.
Transfer history data appended for: https://www.transfermarkt.com/edoardo-iannoni/profil/spieler/700053.
Transfer history data appended for: https://www.transfermarkt.com/cristiano-lombardi/profil/spieler/240349.
Transfer history data appended for: https://www.transfermarkt.com/tomasz-kupisz/profil/spieler/45185.
Transfer history data appended for: https://www.transfermarkt.com/pasquale-mazzocchi/profil/spieler/250153.
Transfer history data appended for: https://www.transfermarkt.com/pietro-ceccaroni/profil/spieler/239099.
Transfer history data appended for: https://www.transfermarkt.com/domenico-rossi/profil/spieler/396080.
Transfer history data appended for: https://www.transfermarkt.com/michele-cremonesi/profil/spieler/83409.
Transfer history data appended for: https://www.transfermarkt.com/gian-filippo-felicioli/profil/spieler/290733.
Transfer history data appended for: https://www.transfermarkt.com/youssef-maleh/profil/spieler/324377.
Transfer history data appended for: https://www.transfermarkt.com/filippo-serena/profil/spieler/433881.
Transfer history data appended for: https://www.transfermarkt.com/alberto-pomini/profil/spieler/82743.
Transfer history data appended for: https://www.transfermarkt.com/luca-fiordilino/profil/spieler/287875.
Transfer history data appended for: https://www.transfermarkt.com/domen-crnigoj/profil/spieler/216599.
Transfer history data appended for: https://www.transfermarkt.com/gabriele-ferrarini/profil/spieler/392033.
Transfer history data appended for: https://www.transfermarkt.com/luca-lezzerini/profil/spieler/135747.
Transfer history data appended for: https://www.transfermarkt.com/dennis-johnsen/profil/spieler/406042.
Transfer history data appended for: https://www.transfermarkt.com/bjarki-steinn-bjarkason/profil/spieler/566613.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-capello/profil/spieler/200190.
Transfer history data appended for: https://www.transfermarkt.com/harvey-st-clair/profil/spieler/339238.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-pigozzo/profil/spieler/529833.
Transfer history data appended for: https://www.transfermarkt.com/mattia-aramu/profil/spieler/200188.

Transfer history data appended for: https://www.transfermarkt.com/francesco-di-mariano/profil/spieler/238950.
Transfer history data appended for: https://www.transfermarkt.com/francesco-forte/profil/spieler/164534.
Transfer history data appended for: https://www.transfermarkt.com/ottar-magnus-karlsson/profil/spieler/271622.
Transfer history data appended for: https://www.transfermarkt.com/antonio-junior-vacca/profil/spieler/102984.
Transfer history data appended for: https://www.transfermarkt.com/marco-modolo/profil/spieler/198873.
Transfer history data appended for: https://www.transfermarkt.com/michael-svoboda/profil/spieler/438961.
Transfer history data appended for: https://www.transfermarkt.com/antonio-marino/profil/spieler/102537.
Transfer history data appended for: https://www.transfermarkt.com/anthony-taugourdeau/profil/spieler/91596.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-bocalon/profil/spieler/72491.
Transfer history data appended for: https://www.transfermarkt.com/eros-pisano/profil/spieler/56609.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-quaini/profil/spieler/345742.
Transfer history data appended for: https://www.transfermarkt.com/francesco-lisi/profil/spieler/146937.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-masetti/profil/spieler/525662.
Transfer history data appended for: https://www.transfermarkt.com/marco-varnier/profil/spieler/362981.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-sibilli/profil/spieler/424275.
Transfer history data appended for: https://www.transfermarkt.com/luca-vido/profil/spieler/264514.
Transfer history data appended for: https://www.transfermarkt.com/tommaso-fischer/profil/spieler/671302.
Transfer history data appended for: https://www.transfermarkt.com/nicholas-siega/profil/spieler/97192.
Transfer history data appended for: https://www.transfermarkt.com/francesco-belli/profil/spieler/197299.
Transfer history data appended for: https://www.transfermarkt.com/robert-gucher/profil/spieler/52188.
Transfer history data appended for: https://www.transfermarkt.com/simone-palombi/profil/spieler/289065.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-loria/profil/spieler/386567.
Transfer history data appended for: https://www.transfermarkt.com/simone-perilli/profil/spieler/240675.
Transfer history data appended for: https://www.transfermarkt.com/gaetano-masucci/profil/spieler/82751.
Transfer history data appended for: https://www.transfermarkt.com/andrea-meroni/profil/spieler/337149.
Transfer history data appended for: https://www.transfermarkt.com/luca-mazzitelli/profil/spieler/226025.
Transfer history data appended for: https://www.transfermarkt.com/thomas-alberti/profil/spieler/489819.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-de-vitis/profil/spieler/62725.
Transfer history data appended for: https://www.transfermarkt.com/samuele-birindelli/profil/spieler/461019.
Transfer history data appended for: https://www.transfermarkt.com/marius-marin/profil/spieler/379163.
Transfer history data appended for: https://www.transfermarkt.com/danilo-soddimo/profil/spieler/39690.
Transfer history data appended for: https://www.transfermarkt.com/matteo-kucich/profil/spieler/383778.
Transfer history data appended for: https://www.transfermarkt.com/elia-giani/profil/spieler/465988.
Transfer history data appended for: https://www.transfermarkt.com/antonio-caracciolo/profil/spieler/149525.
Transfer history data appended for: https://www.transfermarkt.com/filippo-costa/profil/spieler/197743.
Transfer history data appended for: https://www.transfermarkt.com/ivan-de-santis/profil/spieler/264485.
Transfer history data appended for: https://www.transfermarkt.com/andrea-paroni/profil/spieler/57272.
Transfer history data appended for: https://www.transfermarkt.com/andrea-settembrini/profil/spieler/273526.
Transfer history data appended for: https://www.transfermarkt.com/daniele-borra/profil/spieler/240799.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-rodriguez/profil/spieler/169533.
Transfer history data appended for: https://www.transfermarkt.com/marco-toscano/profil/spieler/336959.
Transfer history data appended for: https://www.transfermarkt.com/mirko-albertazzi/profil/spieler/323654.
Transfer history data appended for: https://www.transfermarkt.com/mauro-coppolaro/profil/spieler/250921.
Transfer history data appended for: https://www.transfermarkt.com/filippo-de-col/profil/spieler/240803.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-cleur/profil/spieler/425767.
Transfer history data appended for: https://www.transfermarkt.com/andrea-paolucci/profil/spieler/44540.
Transfer history data appended for: https://www.transfermarkt.com/markus-pavic/profil/spieler/274940.
Transfer history data appended for: https://www.transfermarkt.com/matteo-mancosu/profil/spieler/230611.
Transfer history data appended for: https://www.transfermarkt.com/fabrizio-poli/profil/spieler/124173.
Transfer history data appended for: https://www.transfermarkt.com/marco-brescianini/profil/spieler/459128.
Transfer history data appended for: https://www.transfermarkt.com/marco-crimi/profil/spieler/149526.
Transfer history data appended for: https://www.transfermarkt.com/davide-mazzocco/profil/spieler/240254.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-russo/profil/spieler/481344.
Transfer history data appended for: https://www.transfermarkt.com/michele-currarino/profil/spieler/390679.
Transfer history data appended for: https://www.transfermarkt.com/tomi-petrovic/profil/spieler/370110.
Transfer history data appended for: https://www.transfermarkt.com/luca-nizzetto/profil/spieler/83406.
Transfer history data appended for: https://www.transfermarkt.com/marco-chiosa/profil/spieler/163549.
Transfer history data appended for: https://www.transfermarkt.com/michele-pellizzer/profil/spieler/104746.
Transfer history data appended for: https://www.transfermarkt.com/cassio-cardoselli/profil/spieler/391421.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-morosini/profil/spieler/240415.
Transfer history data appended for: https://www.transfermarkt.com/matteo-luigi-brunori/profil/spieler/188889.
Transfer history data appended for: https://www.transfermarkt.com/claudio-morra/profil/spieler/214635.
Transfer history data appended for: https://www.transfermarkt.com/andrea-schenetti/profil/spieler/130357.
Transfer history data appended for: https://www.transfermarkt.com/mario-ierardi/profil/spieler/370704.
Transfer history data appended for: https://www.transfermarkt.com/nicola-pasini/profil/spieler/63254.
Transfer history data appended for: https://www.transfermarkt.com/federico-scoppa/profil/spieler/78621.
Transfer history data appended for: https://www.transfermarkt.com/pietro-perina/profil/spieler/163315.
Transfer history data appended for: https://www.transfermarkt.com/nicola-bizzotto/profil/spieler/156207.
Transfer history data appended for: https://www.transfermarkt.com/matteo-grandi/profil/spieler/155038.
Transfer history data appended for: https://www.transfermarkt.com/simone-guerra/profil/spieler/76110.
Transfer history data appended for: https://www.transfermarkt.com/luca-barlocco/profil/spieler/197741.
Transfer history data appended for: https://www.transfermarkt.com/stefano-giacomelli/profil/spieler/88691.
Transfer history data appended for: https://www.transfermarkt.com/loris-zonta/profil/spieler/377043.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-gerardi/profil/spieler/567458.
Transfer history data appended for: https://www.transfermarkt.com/matteo-bruscagin/profil/spieler/56618.
Transfer history data appended for: https://www.transfermarkt.com/samuele-longo/profil/spieler/124560.
Transfer history data appended for: https://www.transfermarkt.com/alberto-zecchin/profil/spieler/818133.
Transfer history data appended for: https://www.transfermarkt.com/luca-rigoni/profil/spieler/22210.
Transfer history data appended for: https://www.transfermarkt.com/gabriele-gori/profil/spieler/315859.

Transfer history data appended for: https://www.transfermarkt.com/nicola-dalmonte/profil/spieler/301237.
Transfer history data appended for: https://www.transfermarkt.com/pietro-beruatto/profil/spieler/381370.
Transfer history data appended for: https://www.transfermarkt.com/jari-vandeputte/profil/spieler/258827.
Transfer history data appended for: https://www.transfermarkt.com/jacopo-da-riva/profil/spieler/430503.
Transfer history data appended for: https://www.transfermarkt.com/simone-pontisso/profil/spieler/292422.
Transfer history data appended for: https://www.transfermarkt.com/emanuele-padella/profil/spieler/160854.
Transfer history data appended for: https://www.transfermarkt.com/andrea-nalini/profil/spieler/278578.
Transfer history data appended for: https://www.transfermarkt.com/daniel-cappelletti/profil/spieler/130380.
Transfer history data appended for: https://www.transfermarkt.com/hidemasa-morita/profil/spieler/524315.
Transfer history data appended for: https://www.transfermarkt.com/hokuto-shimoda/profil/spieler/308262.
Transfer history data appended for: https://www.transfermarkt.com/taisei-miyashiro/profil/spieler/405395.
Transfer history data appended for: https://www.transfermarkt.com/leandro-damiao/profil/spieler/139449.
Transfer history data appended for: https://www.transfermarkt.com/jesiel/profil/spieler/363156.
Transfer history data appended for: https://www.transfermarkt.com/ao-tanaka/profil/spieler/489359.
Transfer history data appended for: https://www.transfermarkt.com/kyohei-noborizato/profil/spieler/114205.
Transfer history data appended for: https://www.transfermarkt.com/kaito-kamiya/profil/spieler/732986.
Transfer history data appended for: https://www.transfermarkt.com/kengo-nakamura/profil/spieler/61888.
Transfer history data appended for: https://www.transfermarkt.com/yasuto-wakizaka/profil/spieler/512699.
Transfer history data appended for: https://www.transfermarkt.com/shunsuke-ando/profil/spieler/114187.
Transfer history data appended for: https://www.transfermarkt.com/kyeong-tae-lee/profil/spieler/489410.
Transfer history data appended for: https://www.transfermarkt.com/diogo-mateus/profil/spieler/231009.
Transfer history data appended for: https://www.transfermarkt.com/ryota-oshima/profil/spieler/164264.
Transfer history data appended for: https://www.transfermarkt.com/sung-ryong-jung/profil/spieler/81790.
Transfer history data appended for: https://www.transfermarkt.com/miki-yamane/profil/spieler/395589.
Transfer history data appended for: https://www.transfermarkt.com/kaoru-mitoma/profil/spieler/504849.
Transfer history data appended for: https://www.transfermarkt.com/zain-issaka/profil/spieler/681948.
Transfer history data appended for: https://www.transfermarkt.com/kazuya-yamamura/profil/spieler/103314.
Transfer history data appended for: https://www.transfermarkt.com/kento-tachibanada/profil/spieler/681947.
Transfer history data appended for: https://www.transfermarkt.com/yu-kobayashi/profil/spieler/138260.
Transfer history data appended for: https://www.transfermarkt.com/shogo-taniguchi/profil/spieler/307870.
Transfer history data appended for: https://www.transfermarkt.com/koki-harada/profil/spieler/626136.
Transfer history data appended for: https://www.transfermarkt.com/kenta-tanno/profil/spieler/118491.
Transfer history data appended for: https://www.transfermarkt.com/akihiro-ienaga/profil/spieler/86167.
Transfer history data appended for: https://www.transfermarkt.com/manabu-saito/profil/spieler/110877.
Transfer history data appended for: https://www.transfermarkt.com/reo-hatate/profil/spieler/496656.
Transfer history data appended for: https://www.transfermarkt.com/shintaro-kurumaya/profil/spieler/348041.
Transfer history data appended for: https://www.transfermarkt.com/tatsuya-hasegawa/profil/spieler/386090.
Transfer history data appended for: https://www.transfermarkt.com/tomoki-iwata/profil/spieler/356236.
Transfer history data appended for: https://www.transfermarkt.com/yusho-takahashi/profil/spieler/668608.
Transfer history data appended for: https://www.transfermarkt.com/yoshinori-suzuki/profil/spieler/344090.
Transfer history data appended for: https://www.transfermarkt.com/kazuki-fujimoto/profil/spieler/681679.
Transfer history data appended for: https://www.transfermarkt.com/ryosuke-maeda/profil/spieler/255605.
Transfer history data appended for: https://www.transfermarkt.com/yuto-misao/profil/spieler/269384.
Transfer history data appended for: https://www.transfermarkt.com/kento-haneda/profil/spieler/672619.
Transfer history data appended for: https://www.transfermarkt.com/masaki-yumiba/profil/spieler/781906.
Transfer history data appended for: https://www.transfermarkt.com/shun-yoshida/profil/spieler/642561.
Transfer history data appended for: https://www.transfermarkt.com/koki-kotegawa/profil/spieler/86179.
Transfer history data appended for: https://www.transfermarkt.com/daiki-watari/profil/spieler/205961.
Transfer history data appended for: https://www.transfermarkt.com/kohei-isa/profil/spieler/308470.
Transfer history data appended for: https://www.transfermarkt.com/yuji-hoshi/profil/spieler/362814.
Transfer history data appended for: https://www.transfermarkt.com/yamato-machida/profil/spieler/213178.
Transfer history data appended for: https://www.transfermarkt.com/naoki-nomura/profil/spieler/309182.
Transfer history data appended for: https://www.transfermarkt.com/yuta-koide/profil/spieler/489368.
Transfer history data appended for: https://www.transfermarkt.com/kyung-gun-mun/profil/spieler/525940.
Transfer history data appended for: https://www.transfermarkt.com/toshio-shimakawa/profil/spieler/128412.
Transfer history data appended for: https://www.transfermarkt.com/yuki-kobayashi/profil/spieler/164283.
Transfer history data appended for: https://www.transfermarkt.com/kazushi-mitsuhira/profil/spieler/143372.
Transfer history data appended for: https://www.transfermarkt.com/kei-chinen/profil/spieler/354106.
Transfer history data appended for: https://www.transfermarkt.com/yuya-takazawa/profil/spieler/502182.
Transfer history data appended for: https://www.transfermarkt.com/keita-takahata/profil/spieler/624900.
Transfer history data appended for: https://www.transfermarkt.com/yuki-kagawa/profil/spieler/362777.
Transfer history data appended for: https://www.transfermarkt.com/tatsuya-tanaka/profil/spieler/197265.
Transfer history data appended for: https://www.transfermarkt.com/shun-takagi/profil/spieler/213820.
Transfer history data appended for: https://www.transfermarkt.com/ryosuke-tone/profil/spieler/140321.
Transfer history data appended for: https://www.transfermarkt.com/kenta-inoue/profil/spieler/744698.
Transfer history data appended for: https://www.transfermarkt.com/kaoru-takayama/profil/spieler/181574.
Transfer history data appended for: https://www.transfermarkt.com/kazuki-kozuka/profil/spieler/250984.
Transfer history data appended for: https://www.transfermarkt.com/rei-matsumoto/profil/spieler/132235.
Transfer history data appended for: https://www.transfermarkt.com/seigo-kobayashi/profil/spieler/424797.
Transfer history data appended for: https://www.transfermarkt.com/yushi-hasegawa/profil/spieler/593477.
Transfer history data appended for: https://www.transfermarkt.com/joan-oumari/profil/spieler/77875.
Transfer history data appended for: https://www.transfermarkt.com/leandro/profil/spieler/179373.
Transfer history data appended for: https://www.transfermarkt.com/seiji-kimura/profil/spieler/501749.
Transfer history data appended for: https://www.transfermarkt.com/makoto-okazaki/profil/spieler/426659.
Transfer history data appended for: https://www.transfermarkt.com/kiwara-miyazaki/profil/spieler/374982.
Transfer history data appended for: https://www.transfermarkt.com/tsuyoshi-kodama/profil/spieler/132065.
Transfer history data appended for: https://www.transfermarkt.com/rio-omori/profil/spieler/661677.
Transfer history data appended for: https://www.transfermarkt.com/shuto-abe/profil/spieler/678075.
Transfer history data appended for: https://www.transfermarkt.com/kyosuke-tagawa/profil/spieler/469952.
Transfer history data appended for: https://www.transfermarkt.com/takuya-uchida/profil/spieler/432592.

Transfer history data appended for: https://www.transfermarkt.com/taichi-hara/profil/spieler/495752.
Transfer history data appended for: https://www.transfermarkt.com/tsuyoshi-watanabe/profil/spieler/598791.
Transfer history data appended for: https://www.transfermarkt.com/daiki-niwa/profil/spieler/79706.
Transfer history data appended for: https://www.transfermarkt.com/hotaka-nakamura/profil/spieler/683270.
Transfer history data appended for: https://www.transfermarkt.com/rei-hirakawa/profil/spieler/471154.
Transfer history data appended for: https://www.transfermarkt.com/akihiro-hayashi/profil/spieler/121543.
Transfer history data appended for: https://www.transfermarkt.com/taishi-brandon-nozawa/profil/spieler/617377.
Transfer history data appended for: https://www.transfermarkt.com/kazuya-konno/profil/spieler/654348.
Transfer history data appended for: https://www.transfermarkt.com/manato-shinada/profil/spieler/464741.
Transfer history data appended for: https://www.transfermarkt.com/kensuke-nagai/profil/spieler/103305.
Transfer history data appended for: https://www.transfermarkt.com/adailton/profil/spieler/101253.
Transfer history data appended for: https://www.transfermarkt.com/hirotaka-mita/profil/spieler/234425.
Transfer history data appended for: https://www.transfermarkt.com/takumi-nakamura/profil/spieler/590651.
Transfer history data appended for: https://www.transfermarkt.com/masato-morishige/profil/spieler/81786.
Transfer history data appended for: https://www.transfermarkt.com/kashif-bangunagande/profil/spieler/571694.
Transfer history data appended for: https://www.transfermarkt.com/ryoya-ogawa/profil/spieler/353785.
Transfer history data appended for: https://www.transfermarkt.com/yojiro-takahagi/profil/spieler/106275.
Transfer history data appended for: https://www.transfermarkt.com/keigo-higashi/profil/spieler/113657.
Transfer history data appended for: https://www.transfermarkt.com/arthur-silva/profil/spieler/552231.
Transfer history data appended for: https://www.transfermarkt.com/kiichi-yajima/profil/spieler/426661.
Transfer history data appended for: https://www.transfermarkt.com/sodai-hasukawa/profil/spieler/440021.
Transfer history data appended for: https://www.transfermarkt.com/go-hatano/profil/spieler/387502.
Transfer history data appended for: https://www.transfermarkt.com/shunki-higashi/profil/spieler/577216.
Transfer history data appended for: https://www.transfermarkt.com/hiroya-matsumoto/profil/spieler/571330.
Transfer history data appended for: https://www.transfermarkt.com/yuya-asano/profil/spieler/633480.
Transfer history data appended for: https://www.transfermarkt.com/yoshifumi-kashiwa/profil/spieler/141479.
Transfer history data appended for: https://www.transfermarkt.com/yusuke-chajima/profil/spieler/269135.
Transfer history data appended for: https://www.transfermarkt.com/tsukasa-morishima/profil/spieler/351564.
Transfer history data appended for: https://www.transfermarkt.com/yuki-nogami/profil/spieler/222276.
Transfer history data appended for: https://www.transfermarkt.com/ryo-nagai/profil/spieler/131563.
Transfer history data appended for: https://www.transfermarkt.com/gakuto-notsuda/profil/spieler/218277.
Transfer history data appended for: https://www.transfermarkt.com/takuto-hayashi/profil/spieler/126383.
Transfer history data appended for: https://www.transfermarkt.com/hayao-kawabe/profil/spieler/262489.
Transfer history data appended for: https://www.transfermarkt.com/takuya-masuda/profil/spieler/120754.
Transfer history data appended for: https://www.transfermarkt.com/kodai-dohi/profil/spieler/656609.
Transfer history data appended for: https://www.transfermarkt.com/kazuki-kushibiki/profil/spieler/175549.
Transfer history data appended for: https://www.transfermarkt.com/shun-ayukawa/profil/spieler/694949.
Transfer history data appended for: https://www.transfermarkt.com/leandro-pereira/profil/spieler/270414.
Transfer history data appended for: https://www.transfermarkt.com/douglas-vieira/profil/spieler/373289.
Transfer history data appended for: https://www.transfermarkt.com/sho-sasaki/profil/spieler/213249.
Transfer history data appended for: https://www.transfermarkt.com/tomoya-fujii/profil/spieler/680697.
Transfer history data appended for: https://www.transfermarkt.com/kohei-shimizu/profil/spieler/106278.
Transfer history data appended for: https://www.transfermarkt.com/hayato-araki/profil/spieler/602314.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel/profil/spieler/525828.
Transfer history data appended for: https://www.transfermarkt.com/kosei-shibasaki/profil/spieler/83930.
Transfer history data appended for: https://www.transfermarkt.com/rhayner/profil/spieler/99900.
Transfer history data appended for: https://www.transfermarkt.com/ryotaro-hironaga/profil/spieler/113621.
Transfer history data appended for: https://www.transfermarkt.com/keisuke-osako/profil/spieler/415521.
Transfer history data appended for: https://www.transfermarkt.com/akira-ibayashi/profil/spieler/235053.
Transfer history data appended for: https://www.transfermarkt.com/toshihiro-aoyama/profil/spieler/106035.
Transfer history data appended for: https://www.transfermarkt.com/keisuke-saka/profil/spieler/550637.
Transfer history data appended for: https://www.transfermarkt.com/tsukasa-umesaki/profil/spieler/79372.
Transfer history data appended for: https://www.transfermarkt.com/satoshi-tanaka/profil/spieler/665618.
Transfer history data appended for: https://www.transfermarkt.com/naoki-ishihara/profil/spieler/110780.
Transfer history data appended for: https://www.transfermarkt.com/taiga-hata/profil/spieler/570572.
Transfer history data appended for: https://www.transfermarkt.com/kosei-tani/profil/spieler/405382.
Transfer history data appended for: https://www.transfermarkt.com/kazuki-oiwa/profil/spieler/213183.
Transfer history data appended for: https://www.transfermarkt.com/daiki-hotta/profil/spieler/492893.
Transfer history data appended for: https://www.transfermarkt.com/shunya-mori/profil/spieler/528852.
Transfer history data appended for: https://www.transfermarkt.com/temma-matsuda/profil/spieler/524743.
Transfer history data appended for: https://www.transfermarkt.com/naoki-yamada/profil/spieler/79386.
Transfer history data appended for: https://www.transfermarkt.com/tarik-elyounoussi/profil/spieler/37287.
Transfer history data appended for: https://www.transfermarkt.com/daiki-kaneko/profil/spieler/565524.
Transfer history data appended for: https://www.transfermarkt.com/ko-sawada/profil/spieler/382022.
Transfer history data appended for: https://www.transfermarkt.com/shota-kobayashi/profil/spieler/131559.
Transfer history data appended for: https://www.transfermarkt.com/toichi-suzuki/profil/spieler/405388.
Transfer history data appended for: https://www.transfermarkt.com/masaaki-goto/profil/spieler/489409.
Transfer history data appended for: https://www.transfermarkt.com/riuler/profil/spieler/323880.
Transfer history data appended for: https://www.transfermarkt.com/mitsuki-saito/profil/spieler/353878.
Transfer history data appended for: https://www.transfermarkt.com/yuto-iwasaki/profil/spieler/353880.
Transfer history data appended for: https://www.transfermarkt.com/daiki-tomii/profil/spieler/255669.
Transfer history data appended for: https://www.transfermarkt.com/hiroshi-ibusuki/profil/spieler/98074.
Transfer history data appended for: https://www.transfermarkt.com/yuki-ohashi/profil/spieler/592116.
Transfer history data appended for: https://www.transfermarkt.com/ryo-nemoto/profil/spieler/683517.
Transfer history data appended for: https://www.transfermarkt.com/hiroto-nakagawa/profil/spieler/221975.
Transfer history data appended for: https://www.transfermarkt.com/kazunari-ono/profil/spieler/79334.
Transfer history data appended for: https://www.transfermarkt.com/hirokazu-ishihara/profil/spieler/444314.
Transfer history data appended for: https://www.transfermarkt.com/takuya-okamoto/profil/spieler/129692.
Transfer history data appended for: https://www.transfermarkt.com/sho-hiramatsu/profil/spieler/789256.
Transfer history data appended for: https://www.transfermarkt.com/hidetoshi-miyuki/profil/spieler/220335.

Transfer history data appended for: https://www.transfermarkt.com/kazuaki-mawatari/profil/spieler/310343.
Transfer history data appended for: https://www.transfermarkt.com/koki-tachi/profil/spieler/682147.
Transfer history data appended for: https://www.transfermarkt.com/akimi-barada/profil/spieler/121778.
Transfer history data appended for: https://www.transfermarkt.com/sosuke-shibata/profil/spieler/570386.
Transfer history data appended for: https://www.transfermarkt.com/min-tae-kim/profil/spieler/353565.
Transfer history data appended for: https://www.transfermarkt.com/jay-bothroyd/profil/spieler/8188.
Transfer history data appended for: https://www.transfermarkt.com/tomoki-takamine/profil/spieler/504852.
Transfer history data appended for: https://www.transfermarkt.com/hiroki-miyazawa/profil/spieler/79921.
Transfer history data appended for: https://www.transfermarkt.com/ryota-hayasaka/profil/spieler/143352.
Transfer history data appended for: https://www.transfermarkt.com/kosuke-shirai/profil/spieler/260918.
Transfer history data appended for: https://www.transfermarkt.com/kazuki-fukai/profil/spieler/165780.
Transfer history data appended for: https://www.transfermarkt.com/lucas-fernandes/profil/spieler/375821.
Transfer history data appended for: https://www.transfermarkt.com/tsuyoshi-ogashiwa/profil/spieler/679904.
Transfer history data appended for: https://www.transfermarkt.com/douglas/profil/spieler/339482.
Transfer history data appended for: https://www.transfermarkt.com/kojiro-nakano/profil/spieler/610791.
Transfer history data appended for: https://www.transfermarkt.com/yoshiaki-komai/profil/spieler/171936.
Transfer history data appended for: https://www.transfermarkt.com/daiki-suga/profil/spieler/353876.
Transfer history data appended for: https://www.transfermarkt.com/anderson-lopes/profil/spieler/347291.
Transfer history data appended for: https://www.transfermarkt.com/taika-nakashima/profil/spieler/806006.
Transfer history data appended for: https://www.transfermarkt.com/yoshihiro-nakano/profil/spieler/241361.
Transfer history data appended for: https://www.transfermarkt.com/ryosuke-shindo/profil/spieler/288210.
Transfer history data appended for: https://www.transfermarkt.com/hugo-vieira/profil/spieler/124286.
Transfer history data appended for: https://www.transfermarkt.com/taiyo-hama/profil/spieler/489374.
Transfer history data appended for: https://www.transfermarkt.com/ren-fujimura/profil/spieler/500796.
Transfer history data appended for: https://www.transfermarkt.com/shunta-tanaka/profil/spieler/673858.
Transfer history data appended for: https://www.transfermarkt.com/kawin-thamsatchanan/profil/spieler/122383.
Transfer history data appended for: https://www.transfermarkt.com/takuma-arano/profil/spieler/168204.
Transfer history data appended for: https://www.transfermarkt.com/takuro-kaneko/profil/spieler/657625.
Transfer history data appended for: https://www.transfermarkt.com/akito-fukumori/profil/spieler/164259.
Transfer history data appended for: https://www.transfermarkt.com/shunta-awaka/profil/spieler/188906.
Transfer history data appended for: https://www.transfermarkt.com/takanori-sugeno/profil/spieler/83010.
Transfer history data appended for: https://www.transfermarkt.com/naoki-ishikawa/profil/spieler/86171.
Transfer history data appended for: https://www.transfermarkt.com/sho-ito/profil/spieler/45518.
Transfer history data appended for: https://www.transfermarkt.com/yuta-matsumura/profil/spieler/679113.
Transfer history data appended for: https://www.transfermarkt.com/yu-funabashi/profil/spieler/821190.
Transfer history data appended for: https://www.transfermarkt.com/kei-koizumi/profil/spieler/313137.
Transfer history data appended for: https://www.transfermarkt.com/daiki-sugioka/profil/spieler/489408.
Transfer history data appended for: https://www.transfermarkt.com/kento-misao/profil/spieler/295059.
Transfer history data appended for: https://www.transfermarkt.com/everaldo/profil/spieler/205041.
Transfer history data appended for: https://www.transfermarkt.com/juan-alano/profil/spieler/520467.
Transfer history data appended for: https://www.transfermarkt.com/rikuto-hirose/profil/spieler/309473.
Transfer history data appended for: https://www.transfermarkt.com/taiki-yamada/profil/spieler/501742.
Transfer history data appended for: https://www.transfermarkt.com/shintaro-nago/profil/spieler/391547.
Transfer history data appended for: https://www.transfermarkt.com/yukitoshi-ito/profil/spieler/212435.
Transfer history data appended for: https://www.transfermarkt.com/katsuya-nagato/profil/spieler/489364.
Transfer history data appended for: https://www.transfermarkt.com/shuto-yamamoto/profil/spieler/86211.
Transfer history data appended for: https://www.transfermarkt.com/hitoshi-sogahata/profil/spieler/27796.
Transfer history data appended for: https://www.transfermarkt.com/tomoya-inukai/profil/spieler/203908.
Transfer history data appended for: https://www.transfermarkt.com/yasushi-endo/profil/spieler/82967.
Transfer history data appended for: https://www.transfermarkt.com/yuya-oki/profil/spieler/538050.
Transfer history data appended for: https://www.transfermarkt.com/keigo-tsunemoto/profil/spieler/353886.
Transfer history data appended for: https://www.transfermarkt.com/ryota-nagaki/profil/spieler/155373.
Transfer history data appended for: https://www.transfermarkt.com/ryuji-izumi/profil/spieler/396749.
Transfer history data appended for: https://www.transfermarkt.com/tatsuki-nara/profil/spieler/188113.
Transfer history data appended for: https://www.transfermarkt.com/ikuma-sekigawa/profil/spieler/656565.
Transfer history data appended for: https://www.transfermarkt.com/itsuki-someno/profil/spieler/683014.
Transfer history data appended for: https://www.transfermarkt.com/ryotaro-araki/profil/spieler/566011.
Transfer history data appended for: https://www.transfermarkt.com/shoma-doi/profil/spieler/164243.
Transfer history data appended for: https://www.transfermarkt.com/leo-silva/profil/spieler/54172.
Transfer history data appended for: https://www.transfermarkt.com/ryohei-shirasaki/profil/spieler/213488.
Transfer history data appended for: https://www.transfermarkt.com/koki-machida/profil/spieler/415035.
Transfer history data appended for: https://www.transfermarkt.com/ayase-ueda/profil/spieler/589128.
Transfer history data appended for: https://www.transfermarkt.com/sun-tae-kwon/profil/spieler/92496.
Transfer history data appended for: https://www.transfermarkt.com/hikaru-naruoka/profil/spieler/504496.
Transfer history data appended for: https://www.transfermarkt.com/junior-dutra/profil/spieler/99615.
Transfer history data appended for: https://www.transfermarkt.com/kazunori-yoshimoto/profil/spieler/79538.
Transfer history data appended for: https://www.transfermarkt.com/mitsunari-musaka/profil/spieler/131568.
Transfer history data appended for: https://www.transfermarkt.com/shota-kaneko/profil/spieler/270269.
Transfer history data appended for: https://www.transfermarkt.com/yasufumi-nishimura/profil/spieler/524317.
Transfer history data appended for: https://www.transfermarkt.com/kenta-nishizawa/profil/spieler/471216.
Transfer history data appended for: https://www.transfermarkt.com/riyo-kawamoto/profil/spieler/501740.
Transfer history data appended for: https://www.transfermarkt.com/yuito-suzuki/profil/spieler/668606.
Transfer history data appended for: https://www.transfermarkt.com/yugo-tatsuta/profil/spieler/486197.
Transfer history data appended for: https://www.transfermarkt.com/yohei-nishibe/profil/spieler/79641.
Transfer history data appended for: https://www.transfermarkt.com/takuo-okubo/profil/spieler/103308.
Transfer history data appended for: https://www.transfermarkt.com/valdo/profil/spieler/441762.
Transfer history data appended for: https://www.transfermarkt.com/elsinho/profil/spieler/214196.
Transfer history data appended for: https://www.transfermarkt.com/yusuke-goto/profil/spieler/217635.
Transfer history data appended for: https://www.transfermarkt.com/yoshiaki-arai/profil/spieler/519056.
Transfer history data appended for: https://www.transfermarkt.com/teerasil-dangda/profil/spieler/65233.

Transfer history data appended for: https://www.transfermarkt.com/keita-nakamura/profil/spieler/422594.
Transfer history data appended for: https://www.transfermarkt.com/seok-ho-hwang/profil/spieler/210113.
Transfer history data appended for: https://www.transfermarkt.com/yosuke-kawai/profil/spieler/110908.
Transfer history data appended for: https://www.transfermarkt.com/takashi-kanai/profil/spieler/79408.
Transfer history data appended for: https://www.transfermarkt.com/ryo-takeuchi/profil/spieler/110912.
Transfer history data appended for: https://www.transfermarkt.com/naoya-fukumori/profil/spieler/356233.
Transfer history data appended for: https://www.transfermarkt.com/togo-umeda/profil/spieler/509800.
Transfer history data appended for: https://www.transfermarkt.com/kenta-ito/profil/spieler/504169.
Transfer history data appended for: https://www.transfermarkt.com/ryo-okui/profil/spieler/212167.
Transfer history data appended for: https://www.transfermarkt.com/renato-augusto/profil/spieler/232096.
Transfer history data appended for: https://www.transfermarkt.com/neto-volpi/profil/spieler/202959.
Transfer history data appended for: https://www.transfermarkt.com/kota-miyamoto/profil/spieler/307049.
Transfer history data appended for: https://www.transfermarkt.com/hideki-ishige/profil/spieler/165783.
Transfer history data appended for: https://www.transfermarkt.com/haruki-saruta/profil/spieler/486639.
Transfer history data appended for: https://www.transfermarkt.com/yuki-yamamoto/profil/spieler/588478.
Transfer history data appended for: https://www.transfermarkt.com/shuhei-kawasaki/profil/spieler/674088.
Transfer history data appended for: https://www.transfermarkt.com/shoji-toyama/profil/spieler/685526.
Transfer history data appended for: https://www.transfermarkt.com/ryo-shinzato/profil/spieler/256155.
Transfer history data appended for: https://www.transfermarkt.com/gen-shoji/profil/spieler/164277.
Transfer history data appended for: https://www.transfermarkt.com/patric/profil/spieler/174947.
Transfer history data appended for: https://www.transfermarkt.com/kosuke-onose/profil/spieler/195386.
Transfer history data appended for: https://www.transfermarkt.com/young-gwon-kim/profil/spieler/126640.
Transfer history data appended for: https://www.transfermarkt.com/jun-ichimori/profil/spieler/315655.
Transfer history data appended for: https://www.transfermarkt.com/yuya-fukuda/profil/spieler/550581.
Transfer history data appended for: https://www.transfermarkt.com/ryu-takao/profil/spieler/590369.
Transfer history data appended for: https://www.transfermarkt.com/won-ho-shin/profil/spieler/732993.
Transfer history data appended for: https://www.transfermarkt.com/keisuke-kurokawa/profil/spieler/641029.
Transfer history data appended for: https://www.transfermarkt.com/daisuke-takagi/profil/spieler/165797.
Transfer history data appended for: https://www.transfermarkt.com/shunya-suganuma/profil/spieler/111879.
Transfer history data appended for: https://www.transfermarkt.com/hiroki-fujiharu/profil/spieler/179281.
Transfer history data appended for: https://www.transfermarkt.com/dai-tsukamoto/profil/spieler/501746.
Transfer history data appended for: https://www.transfermarkt.com/kohei-okuno/profil/spieler/532055.
Transfer history data appended for: https://www.transfermarkt.com/yota-sato/profil/spieler/683268.
Transfer history data appended for: https://www.transfermarkt.com/shinya-yajima/profil/spieler/196443.
Transfer history data appended for: https://www.transfermarkt.com/shu-kurata/profil/spieler/79415.
Transfer history data appended for: https://www.transfermarkt.com/jefferson-david-tabinas/profil/spieler/489357.
Transfer history data appended for: https://www.transfermarkt.com/kazuma-watanabe/profil/spieler/110874.
Transfer history data appended for: https://www.transfermarkt.com/riku-matsuda/profil/spieler/553818.
Transfer history data appended for: https://www.transfermarkt.com/yun-oh-lee/profil/spieler/540962.
Transfer history data appended for: https://www.transfermarkt.com/masaaki-higashiguchi/profil/spieler/113712.
Transfer history data appended for: https://www.transfermarkt.com/genta-miura/profil/spieler/261931.
Transfer history data appended for: https://www.transfermarkt.com/kei-ishikawa/profil/spieler/164251.
Transfer history data appended for: https://www.transfermarkt.com/yosuke-ideguchi/profil/spieler/318219.
Transfer history data appended for: https://www.transfermarkt.com/ren-shibamoto/profil/spieler/501585.
Transfer history data appended for: https://www.transfermarkt.com/haruto-shirai/profil/spieler/495797.
Transfer history data appended for: https://www.transfermarkt.com/tatsuya-yamaguchi/profil/spieler/550585.
Transfer history data appended for: https://www.transfermarkt.com/yuji-ono/profil/spieler/155761.
Transfer history data appended for: https://www.transfermarkt.com/ayumu-seko/profil/spieler/405389.
Transfer history data appended for: https://www.transfermarkt.com/daichi-akiyama/profil/spieler/248573.
Transfer history data appended for: https://www.transfermarkt.com/shota-fujio/profil/spieler/501741.
Transfer history data appended for: https://www.transfermarkt.com/ryuya-nishio/profil/spieler/432300.
Transfer history data appended for: https://www.transfermarkt.com/tatsuya-tabira/profil/spieler/679110.
Transfer history data appended for: https://www.transfermarkt.com/tatsuhiro-sakamoto/profil/spieler/617408.
Transfer history data appended for: https://www.transfermarkt.com/hiroshi-kiyotake/profil/spieler/86175.
Transfer history data appended for: https://www.transfermarkt.com/riku-matsuda/profil/spieler/279647.
Transfer history data appended for: https://www.transfermarkt.com/nagi-matsumoto/profil/spieler/432402.
Transfer history data appended for: https://www.transfermarkt.com/jun-su-ahn/profil/spieler/402135.
Transfer history data appended for: https://www.transfermarkt.com/hinata-kida/profil/spieler/405391.
Transfer history data appended for: https://www.transfermarkt.com/yasuki-kimoto/profil/spieler/383310.
Transfer history data appended for: https://www.transfermarkt.com/matej-jonjic/profil/spieler/86631.
Transfer history data appended for: https://www.transfermarkt.com/toshiyuki-takagi/profil/spieler/131565.
Transfer history data appended for: https://www.transfermarkt.com/takuya-shimamura/profil/spieler/489416.
Transfer history data appended for: https://www.transfermarkt.com/eiichi-katayama/profil/spieler/310201.
Transfer history data appended for: https://www.transfermarkt.com/koji-suzuki/profil/spieler/213283.
Transfer history data appended for: https://www.transfermarkt.com/leandro-desabato/profil/spieler/181704.
Transfer history data appended for: https://www.transfermarkt.com/hiroaki-okuno/profil/spieler/126396.
Transfer history data appended for: https://www.transfermarkt.com/shu-mogi/profil/spieler/489048.
Transfer history data appended for: https://www.transfermarkt.com/yusuke-maruhashi/profil/spieler/118489.
Transfer history data appended for: https://www.transfermarkt.com/yoichiro-kakitani/profil/spieler/114198.
Transfer history data appended for: https://www.transfermarkt.com/ken-tokura/profil/spieler/79487.
Transfer history data appended for: https://www.transfermarkt.com/bruno-mendes/profil/spieler/216131.
Transfer history data appended for: https://www.transfermarkt.com/masataka-nishimoto/profil/spieler/356229.
Transfer history data appended for: https://www.transfermarkt.com/naoyuki-fujita/profil/spieler/142009.
Transfer history data appended for: https://www.transfermarkt.com/takumi-nagaishi/profil/spieler/508266.
Transfer history data appended for: https://www.transfermarkt.com/jin-hyeon-kim/profil/spieler/118487.
Transfer history data appended for: https://www.transfermarkt.com/pierce-waring/profil/spieler/400000.
Transfer history data appended for: https://www.transfermarkt.com/jun-nishikawa/profil/spieler/432407.
Transfer history data appended for: https://www.transfermarkt.com/tawan-khotrsupho/profil/spieler/656467.
Transfer history data appended for: https://www.transfermarkt.com/takaya-yoshinare/profil/spieler/657620.
Transfer history data appended for: https://www.transfermarkt.com/yuta-koike/profil/spieler/286503.

Transfer history data appended for: https://www.transfermarkt.com/yuta-toyokawa/profil/spieler/241347.
Transfer history data appended for: https://www.transfermarkt.com/daiki-hashioka/profil/spieler/387191.
Transfer history data appended for: https://www.transfermarkt.com/yosuke-kashiwagi/profil/spieler/106056.
Transfer history data appended for: https://www.transfermarkt.com/quenten-martinus/profil/spieler/81288.
Transfer history data appended for: https://www.transfermarkt.com/thomas-deng/profil/spieler/366543.
Transfer history data appended for: https://www.transfermarkt.com/daisuke-suzuki/profil/spieler/79344.
Transfer history data appended for: https://www.transfermarkt.com/yuta-miyamoto/profil/spieler/683328.
Transfer history data appended for: https://www.transfermarkt.com/haruki-fukushima/profil/spieler/358781.
Transfer history data appended for: https://www.transfermarkt.com/katsuya-iwatake/profil/spieler/319800.
Transfer history data appended for: https://www.transfermarkt.com/atsuki-ito/profil/spieler/492715.
Transfer history data appended for: https://www.transfermarkt.com/shusaku-nishikawa/profil/spieler/81787.
Transfer history data appended for: https://www.transfermarkt.com/kosuke-taketomi/profil/spieler/115165.
Transfer history data appended for: https://www.transfermarkt.com/tomoaki-makino/profil/spieler/106064.
Transfer history data appended for: https://www.transfermarkt.com/koya-yuruki/profil/spieler/296471.
Transfer history data appended for: https://www.transfermarkt.com/kenyu-sugimoto/profil/spieler/129694.
Transfer history data appended for: https://www.transfermarkt.com/ryotaro-ito/profil/spieler/415522.
Transfer history data appended for: https://www.transfermarkt.com/kazuki-nagasawa/profil/spieler/263685.
Transfer history data appended for: https://www.transfermarkt.com/yuki-muto/profil/spieler/164165.
Transfer history data appended for: https://www.transfermarkt.com/hidetoshi-takeda/profil/spieler/668674.
Transfer history data appended for: https://www.transfermarkt.com/leonardo/profil/spieler/546292.
Transfer history data appended for: https://www.transfermarkt.com/tomoya-ugajin/profil/spieler/125140.
Transfer history data appended for: https://www.transfermarkt.com/takahiro-sekine/profil/spieler/296787.
Transfer history data appended for: https://www.transfermarkt.com/yuki-abe/profil/spieler/27765.
Transfer history data appended for: https://www.transfermarkt.com/ewerton/profil/spieler/214070.
Transfer history data appended for: https://www.transfermarkt.com/zion-suzuki/profil/spieler/432298.
Transfer history data appended for: https://www.transfermarkt.com/takuya-aoki/profil/spieler/79690.
Transfer history data appended for: https://www.transfermarkt.com/ryosuke-yamanaka/profil/spieler/171418.
Transfer history data appended for: https://www.transfermarkt.com/ryo-ishii/profil/spieler/492744.
Transfer history data appended for: https://www.transfermarkt.com/kai-shibato/profil/spieler/577217.
Transfer history data appended for: https://www.transfermarkt.com/takuya-iwanami/profil/spieler/165784.
Transfer history data appended for: https://www.transfermarkt.com/shinzo-koroki/profil/spieler/82988.
Transfer history data appended for: https://www.transfermarkt.com/yusuke-kobayashi/profil/spieler/221969.
Transfer history data appended for: https://www.transfermarkt.com/ryohei-yamazaki/profil/spieler/86212.
Transfer history data appended for: https://www.transfermarkt.com/hiromu-mitsumaru/profil/spieler/421561.
Transfer history data appended for: https://www.transfermarkt.com/richardson/profil/spieler/145573.
Transfer history data appended for: https://www.transfermarkt.com/taiyo-koga/profil/spieler/489072.
Transfer history data appended for: https://www.transfermarkt.com/tatsuya-yamashita/profil/spieler/118493.
Transfer history data appended for: https://www.transfermarkt.com/michael-olunga/profil/spieler/263482.
Transfer history data appended for: https://www.transfermarkt.com/seung-gyu-kim/profil/spieler/92076.
Transfer history data appended for: https://www.transfermarkt.com/sachiro-toshima/profil/spieler/515925.
Transfer history data appended for: https://www.transfermarkt.com/hiroto-goya/profil/spieler/417609.
Transfer history data appended for: https://www.transfermarkt.com/cristiano/profil/spieler/207600.
Transfer history data appended for: https://www.transfermarkt.com/yuta-kamiya/profil/spieler/275479.
Transfer history data appended for: https://www.transfermarkt.com/kazushige-kirihata/profil/spieler/82983.
Transfer history data appended for: https://www.transfermarkt.com/jiro-kamata/profil/spieler/82979.
Transfer history data appended for: https://www.transfermarkt.com/hayato-nakama/profil/spieler/177131.
Transfer history data appended for: https://www.transfermarkt.com/fumiya-unoki/profil/spieler/665619.
Transfer history data appended for: https://www.transfermarkt.com/haruhiko-takimoto/profil/spieler/376696.
Transfer history data appended for: https://www.transfermarkt.com/yuto-yamada/profil/spieler/605017.
Transfer history data appended for: https://www.transfermarkt.com/ataru-esaka/profil/spieler/356145.
Transfer history data appended for: https://www.transfermarkt.com/masatoshi-mihara/profil/spieler/80860.
Transfer history data appended for: https://www.transfermarkt.com/hidekazu-otani/profil/spieler/82998.
Transfer history data appended for: https://www.transfermarkt.com/kosuke-nakamura/profil/spieler/165794.
Transfer history data appended for: https://www.transfermarkt.com/yuta-someya/profil/spieler/115768.
Transfer history data appended for: https://www.transfermarkt.com/takuma-ominami/profil/spieler/423112.
Transfer history data appended for: https://www.transfermarkt.com/shunki-takahashi/profil/spieler/79384.
Transfer history data appended for: https://www.transfermarkt.com/yusuke-segawa/profil/spieler/422518.
Transfer history data appended for: https://www.transfermarkt.com/mao-hosoya/profil/spieler/663514.
Transfer history data appended for: https://www.transfermarkt.com/naoki-kawaguchi/profil/spieler/165788.
Transfer history data appended for: https://www.transfermarkt.com/kengo-kitazume/profil/spieler/355709.
Transfer history data appended for: https://www.transfermarkt.com/yuji-takahashi/profil/spieler/212120.
Transfer history data appended for: https://www.transfermarkt.com/yusuke-minagawa/profil/spieler/304220.
Transfer history data appended for: https://www.transfermarkt.com/takuya-matsuura/profil/spieler/86187.
Transfer history data appended for: https://www.transfermarkt.com/kakeru-kumagawa/profil/spieler/358501.
Transfer history data appended for: https://www.transfermarkt.com/kensuke-sato/profil/spieler/174549.
Transfer history data appended for: https://www.transfermarkt.com/shunsuke-nakamura/profil/spieler/6069.
Transfer history data appended for: https://www.transfermarkt.com/riku-furuyado/profil/spieler/698128.
Transfer history data appended for: https://www.transfermarkt.com/yuya-takagi/profil/spieler/685003.
Transfer history data appended for: https://www.transfermarkt.com/maguinho/profil/spieler/350766.
Transfer history data appended for: https://www.transfermarkt.com/yuji-senuma/profil/spieler/230483.
Transfer history data appended for: https://www.transfermarkt.com/eijiro-takeda/profil/spieler/150520.
Transfer history data appended for: https://www.transfermarkt.com/calvin-jong-a-pin/profil/spieler/45561.
Transfer history data appended for: https://www.transfermarkt.com/tatsuki-seko/profil/spieler/683269.
Transfer history data appended for: https://www.transfermarkt.com/koki-saito/profil/spieler/501743.
Transfer history data appended for: https://www.transfermarkt.com/ryuji-sugimoto/profil/spieler/186518.
Transfer history data appended for: https://www.transfermarkt.com/kazuyoshi-miura/profil/spieler/112589.
Transfer history data appended for: https://www.transfermarkt.com/masahiko-inoha/profil/spieler/82977.
Transfer history data appended for: https://www.transfermarkt.com/yusuke-matsuo/profil/spieler/675754.
Transfer history data appended for: https://www.transfermarkt.com/yutaro-hakamata/profil/spieler/624896.
Transfer history data appended for: https://www.transfermarkt.com/reo-yasunaga/profil/spieler/576456.

Transfer history data appended for: https://www.transfermarkt.com/yuji-rokutan/profil/spieler/117235.
Transfer history data appended for: https://www.transfermarkt.com/kohei-tezuka/profil/spieler/359238.
Transfer history data appended for: https://www.transfermarkt.com/yuta-minami/profil/spieler/82992.
Transfer history data appended for: https://www.transfermarkt.com/katsuhiro-nakayama/profil/spieler/635021.
Transfer history data appended for: https://www.transfermarkt.com/kazunari-ichimi/profil/spieler/417610.
Transfer history data appended for: https://www.transfermarkt.com/kyowaan-hoshi/profil/spieler/683015.
Transfer history data appended for: https://www.transfermarkt.com/akihiko-takeshige/profil/spieler/138795.
Transfer history data appended for: https://www.transfermarkt.com/akinori-ichikawa/profil/spieler/489419.
Transfer history data appended for: https://www.transfermarkt.com/masakazu-tashiro/profil/spieler/86208.
Transfer history data appended for: https://www.transfermarkt.com/yuki-kobayashi/profil/spieler/405386.
Transfer history data appended for: https://www.transfermarkt.com/yuki-kusano/profil/spieler/635328.
Transfer history data appended for: https://www.transfermarkt.com/kosuke-saito/profil/spieler/421427.
Transfer history data appended for: https://www.transfermarkt.com/takaaki-shichi/profil/spieler/374561.
Transfer history data appended for: https://www.transfermarkt.com/leandro-domingues/profil/spieler/54152.
Transfer history data appended for: https://www.transfermarkt.com/riku-terakado/profil/spieler/821193.
Transfer history data appended for: https://www.transfermarkt.com/ryo-takano/profil/spieler/374560.
Transfer history data appended for: https://www.transfermarkt.com/shinnosuke-hatanaka/profil/spieler/310916.
Transfer history data appended for: https://www.transfermarkt.com/daizen-maeda/profil/spieler/420931.
Transfer history data appended for: https://www.transfermarkt.com/yuki-otsu/profil/spieler/82999.
Transfer history data appended for: https://www.transfermarkt.com/ado-onaiwu/profil/spieler/308133.
Transfer history data appended for: https://www.transfermarkt.com/junior-santos/profil/spieler/592347.
Transfer history data appended for: https://www.transfermarkt.com/ryonosuke-kabayama/profil/spieler/743994.
Transfer history data appended for: https://www.transfermarkt.com/yuki-saneto/profil/spieler/158579.
Transfer history data appended for: https://www.transfermarkt.com/yuji-kajikawa/profil/spieler/308651.
Transfer history data appended for: https://www.transfermarkt.com/jun-amano/profil/spieler/308214.
Transfer history data appended for: https://www.transfermarkt.com/hirotsugu-nakabayashi/profil/spieler/106272.
Transfer history data appended for: https://www.transfermarkt.com/kota-mizunuma/profil/spieler/79419.
Transfer history data appended for: https://www.transfermarkt.com/takahiro-ogihara/profil/spieler/140311.
Transfer history data appended for: https://www.transfermarkt.com/thiago-martins/profil/spieler/277318.
Transfer history data appended for: https://www.transfermarkt.com/theerathon-bunmathan/profil/spieler/159950.
Transfer history data appended for: https://www.transfermarkt.com/ryotaro-tsunoda/profil/spieler/662493.
Transfer history data appended for: https://www.transfermarkt.com/keita-ueda/profil/spieler/821192.
Transfer history data appended for: https://www.transfermarkt.com/takuya-kida/profil/spieler/188907.
Transfer history data appended for: https://www.transfermarkt.com/eitaro-matsuda/profil/spieler/570569.
Transfer history data appended for: https://www.transfermarkt.com/marcos-junior/profil/spieler/218115.
Transfer history data appended for: https://www.transfermarkt.com/erik/profil/spieler/262016.
Transfer history data appended for: https://www.transfermarkt.com/takuya-wada/profil/spieler/131504.
Transfer history data appended for: https://www.transfermarkt.com/kota-watanabe/profil/spieler/353969.
Transfer history data appended for: https://www.transfermarkt.com/makito-ito/profil/spieler/367584.
Transfer history data appended for: https://www.transfermarkt.com/ryuta-koike/profil/spieler/315666.
Transfer history data appended for: https://www.transfermarkt.com/takumi-tsukui/profil/spieler/786986.
Transfer history data appended for: https://www.transfermarkt.com/ken-matsubara/profil/spieler/129686.
Transfer history data appended for: https://www.transfermarkt.com/powell-obinna-obi/profil/spieler/358216.
Transfer history data appended for: https://www.transfermarkt.com/shunsuke-hirai/profil/spieler/743995.
Transfer history data appended for: https://www.transfermarkt.com/yohei-takaoka/profil/spieler/309196.
Transfer history data appended for: https://www.transfermarkt.com/teruhito-nakagawa/profil/spieler/345326.
Transfer history data appended for: https://www.transfermarkt.com/alexandre-guedes/profil/spieler/197613.
Transfer history data appended for: https://www.transfermarkt.com/para/profil/spieler/323618.
Transfer history data appended for: https://www.transfermarkt.com/shogo-nakahara/profil/spieler/257333.
Transfer history data appended for: https://www.transfermarkt.com/shingo-tomita/profil/spieler/126406.
Transfer history data appended for: https://www.transfermarkt.com/takuma-hamasaki/profil/spieler/489437.
Transfer history data appended for: https://www.transfermarkt.com/yoshiki-matsushita/profil/spieler/391525.
Transfer history data appended for: https://www.transfermarkt.com/yasuhiro-hiraoka/profil/spieler/79879.
Transfer history data appended for: https://www.transfermarkt.com/jakub-slowik/profil/spieler/154530.
Transfer history data appended for: https://www.transfermarkt.com/kentaro-seki/profil/spieler/126400.
Transfer history data appended for: https://www.transfermarkt.com/wataru-tanaka/profil/spieler/624916.
Transfer history data appended for: https://www.transfermarkt.com/isaac-cuenca/profil/spieler/176285.
Transfer history data appended for: https://www.transfermarkt.com/goro-kawanami/profil/spieler/121801.
Transfer history data appended for: https://www.transfermarkt.com/shun-nagasawa/profil/spieler/79640.
Transfer history data appended for: https://www.transfermarkt.com/takahiro-yanagi/profil/spieler/407834.
Transfer history data appended for: https://www.transfermarkt.com/takuma-nishimura/profil/spieler/353567.
Transfer history data appended for: https://www.transfermarkt.com/kyohei-yoshino/profil/spieler/165801.
Transfer history data appended for: https://www.transfermarkt.com/takumi-sasaki/profil/spieler/351565.
Transfer history data appended for: https://www.transfermarkt.com/chihiro-kato/profil/spieler/537863.
Transfer history data appended for: https://www.transfermarkt.com/takayoshi-ishihara/profil/spieler/181681.
Transfer history data appended for: https://www.transfermarkt.com/yuma-obata/profil/spieler/653097.
Transfer history data appended for: https://www.transfermarkt.com/ryo-germain/profil/spieler/511448.
Transfer history data appended for: https://www.transfermarkt.com/ryutaro-iio/profil/spieler/257168.
Transfer history data appended for: https://www.transfermarkt.com/shuhei-akasaki/profil/spieler/241351.
Transfer history data appended for: https://www.transfermarkt.com/kunimitsu-sekiguchi/profil/spieler/126401.
Transfer history data appended for: https://www.transfermarkt.com/hisashi-appiah-tawiah/profil/spieler/533680.
Transfer history data appended for: https://www.transfermarkt.com/koji-hachisuka/profil/spieler/234413.
Transfer history data appended for: https://www.transfermarkt.com/jeong-ya-kim/profil/spieler/176909.
Transfer history data appended for: https://www.transfermarkt.com/hayato-teruyama/profil/spieler/624898.
Transfer history data appended for: https://www.transfermarkt.com/takumi-mase/profil/spieler/749070.
Transfer history data appended for: https://www.transfermarkt.com/hiroto-yamada/profil/spieler/405394.
Transfer history data appended for: https://www.transfermarkt.com/simao/profil/spieler/58281.
Transfer history data appended for: https://www.transfermarkt.com/keiya-shiihashi/profil/spieler/417506.
Transfer history data appended for: https://www.transfermarkt.com/shingo-hyodo/profil/spieler/79403.
Transfer history data appended for: https://www.transfermarkt.com/hideto-takahashi/profil/spieler/113629.

Transfer history data appended for: https://www.transfermarkt.com/daisuke-matsumoto/profil/spieler/746411.
Transfer history data appended for: https://www.transfermarkt.com/yosuke-yuzawa/profil/spieler/257329.
Transfer history data appended for: https://www.transfermarkt.com/daichi-hayashi/profil/spieler/690993.
Transfer history data appended for: https://www.transfermarkt.com/yuzo-kobayashi/profil/spieler/82985.
Transfer history data appended for: https://www.transfermarkt.com/yong-gi-ryang/profil/spieler/68381.
Transfer history data appended for: https://www.transfermarkt.com/daiki-matsuoka/profil/spieler/576449.
Transfer history data appended for: https://www.transfermarkt.com/kaisei-ishii/profil/spieler/576448.
Transfer history data appended for: https://www.transfermarkt.com/eduardo/profil/spieler/218138.
Transfer history data appended for: https://www.transfermarkt.com/keisuke-iwashita/profil/spieler/79623.
Transfer history data appended for: https://www.transfermarkt.com/yohei-toyoda/profil/spieler/81788.
Transfer history data appended for: https://www.transfermarkt.com/dong-geon-cho/profil/spieler/134658.
Transfer history data appended for: https://www.transfermarkt.com/jeong-su-park/profil/spieler/421725.
Transfer history data appended for: https://www.transfermarkt.com/tomoya-koyamatsu/profil/spieler/308243.
Transfer history data appended for: https://www.transfermarkt.com/riki-harakawa/profil/spieler/212115.
Transfer history data appended for: https://www.transfermarkt.com/yoshiki-takahashi/profil/spieler/131894.
Transfer history data appended for: https://www.transfermarkt.com/teruki-hara/profil/spieler/470130.
Transfer history data appended for: https://www.transfermarkt.com/daiki-miya/profil/spieler/509575.
Transfer history data appended for: https://www.transfermarkt.com/min-ho-kim/profil/spieler/643146.
Transfer history data appended for: https://www.transfermarkt.com/fuchi-honda/profil/spieler/672620.
Transfer history data appended for: https://www.transfermarkt.com/yuta-higuchi/profil/spieler/633517.
Transfer history data appended for: https://www.transfermarkt.com/yuto-uchida/profil/spieler/280425.
Transfer history data appended for: https://www.transfermarkt.com/yosei-itahashi/profil/spieler/570570.
Transfer history data appended for: https://www.transfermarkt.com/yong-u-ahn/profil/spieler/316240.
Transfer history data appended for: https://www.transfermarkt.com/takeshi-kanamori/profil/spieler/257110.
Transfer history data appended for: https://www.transfermarkt.com/tatsuya-morita/profil/spieler/115765.
Transfer history data appended for: https://www.transfermarkt.com/ryunosuke-sagara/profil/spieler/693038.
Transfer history data appended for: https://www.transfermarkt.com/tiago-alves/profil/spieler/177011.
Transfer history data appended for: https://www.transfermarkt.com/renzo-lopez/profil/spieler/248030.
Transfer history data appended for: https://www.transfermarkt.com/ayumu-ohata/profil/spieler/693037.
Transfer history data appended for: https://www.transfermarkt.com/reoto-kodama/profil/spieler/746412.
Transfer history data appended for: https://www.transfermarkt.com/jianan-wang/profil/spieler/211859.
Transfer history data appended for: https://www.transfermarkt.com/il-kyu-park/profil/spieler/224587.
Transfer history data appended for: https://www.transfermarkt.com/ryoya-morishita/profil/spieler/679903.
Transfer history data appended for: https://www.transfermarkt.com/leo-osaki/profil/spieler/333810.
Transfer history data appended for: https://www.transfermarkt.com/yutaro-oda/profil/spieler/432401.
Transfer history data appended for: https://www.transfermarkt.com/daiju-sasaki/profil/spieler/515653.
Transfer history data appended for: https://www.transfermarkt.com/tatsunori-sakurai/profil/spieler/814466.
Transfer history data appended for: https://www.transfermarkt.com/yuya-nakasaka/profil/spieler/435302.
Transfer history data appended for: https://www.transfermarkt.com/hotaru-yamaguchi/profil/spieler/118492.
Transfer history data appended for: https://www.transfermarkt.com/hiroki-iikura/profil/spieler/79404.
Transfer history data appended for: https://www.transfermarkt.com/andres-iniesta/profil/spieler/7600.
Transfer history data appended for: https://www.transfermarkt.com/daiya-maekawa/profil/spieler/489081.
Transfer history data appended for: https://www.transfermarkt.com/ryuho-kikuchi/profil/spieler/639533.
Transfer history data appended for: https://www.transfermarkt.com/so-fujitani/profil/spieler/351560.
Transfer history data appended for: https://www.transfermarkt.com/dankler/profil/spieler/226896.
Transfer history data appended for: https://www.transfermarkt.com/ryo-hatsuse/profil/spieler/414926.
Transfer history data appended for: https://www.transfermarkt.com/yuta-goke/profil/spieler/486185.
Transfer history data appended for: https://www.transfermarkt.com/douglas/profil/spieler/99548.
Transfer history data appended for: https://www.transfermarkt.com/kyogo-furuhashi/profil/spieler/489463.
Transfer history data appended for: https://www.transfermarkt.com/takuya-yasui/profil/spieler/489084.
Transfer history data appended for: https://www.transfermarkt.com/sergi-samper/profil/spieler/181112.
Transfer history data appended for: https://www.transfermarkt.com/noriaki-fujimoto/profil/spieler/224264.
Transfer history data appended for: https://www.transfermarkt.com/kenshin-yoshimaru/profil/spieler/307065.
Transfer history data appended for: https://www.transfermarkt.com/keijiro-ogawa/profil/spieler/129691.
Transfer history data appended for: https://www.transfermarkt.com/hirofumi-watanabe/profil/spieler/83016.
Transfer history data appended for: https://www.transfermarkt.com/daigo-nishi/profil/spieler/79923.
Transfer history data appended for: https://www.transfermarkt.com/tetsushi-yamakawa/profil/spieler/404379.
Transfer history data appended for: https://www.transfermarkt.com/genta-ito/profil/spieler/640780.
Transfer history data appended for: https://www.transfermarkt.com/thomas-vermaelen/profil/spieler/15904.
Transfer history data appended for: https://www.transfermarkt.com/sho-inagaki/profil/spieler/290660.
Transfer history data appended for: https://www.transfermarkt.com/jae-suk-oh/profil/spieler/126642.
Transfer history data appended for: https://www.transfermarkt.com/haruya-fujii/profil/spieler/570385.
Transfer history data appended for: https://www.transfermarkt.com/shumpei-naruse/profil/spieler/501736.
Transfer history data appended for: https://www.transfermarkt.com/kazuhiko-chiba/profil/spieler/31065.
Transfer history data appended for: https://www.transfermarkt.com/naoki-maeda/profil/spieler/246197.
Transfer history data appended for: https://www.transfermarkt.com/kosuke-ota/profil/spieler/110911.
Transfer history data appended for: https://www.transfermarkt.com/daiki-mitsui/profil/spieler/570568.
Transfer history data appended for: https://www.transfermarkt.com/kazuya-miyahara/profil/spieler/264142.
Transfer history data appended for: https://www.transfermarkt.com/tsubasa-shibuya/profil/spieler/255259.
Transfer history data appended for: https://www.transfermarkt.com/yohei-takeda/profil/spieler/79647.
Transfer history data appended for: https://www.transfermarkt.com/hiroyuki-abe/profil/spieler/211929.
Transfer history data appended for: https://www.transfermarkt.com/yuki-soma/profil/spieler/594069.
Transfer history data appended for: https://www.transfermarkt.com/mu-kanazaki/profil/spieler/86172.
Transfer history data appended for: https://www.transfermarkt.com/yosuke-akiyama/profil/spieler/511447.
Transfer history data appended for: https://www.transfermarkt.com/akira-yoshida/profil/spieler/732989.
Transfer history data appended for: https://www.transfermarkt.com/joao-schmidt/profil/spieler/198859.
Transfer history data appended for: https://www.transfermarkt.com/shinnosuke-nakatani/profil/spieler/275532.
Transfer history data appended for: https://www.transfermarkt.com/yutaka-yoshida/profil/spieler/116223.
Transfer history data appended for: https://www.transfermarkt.com/mitchell-langerak/profil/spieler/49347.
Transfer history data appended for: https://www.transfermarkt.com/mateus/profil/spieler/334828.

Transfer history data appended for: https://www.transfermarkt.com/shuto-watanabe/profil/spieler/556869.
Transfer history data appended for: https://www.transfermarkt.com/ryotaro-ishida/profil/spieler/432304.
Transfer history data appended for: https://www.transfermarkt.com/takuji-yonemoto/profil/spieler/80874.
Transfer history data appended for: https://www.transfermarkt.com/ryogo-yamasaki/profil/spieler/288611.
Transfer history data appended for: https://www.transfermarkt.com/aria-jasuru-hasegawa/profil/spieler/79399.
Transfer history data appended for: https://www.transfermarkt.com/yuichi-maruyama/profil/spieler/212275.
Transfer history data appended for: https://www.transfermarkt.com/guti/profil/spieler/175208.
Transfer history data appended for: https://www.transfermarkt.com/damjan-bohar/profil/spieler/174504.
Transfer history data appended for: https://www.transfermarkt.com/igor-silva/profil/spieler/391720.
Transfer history data appended for: https://www.transfermarkt.com/petar-bockaj/profil/spieler/292666.
Transfer history data appended for: https://www.transfermarkt.com/ante-majstorovic/profil/spieler/207025.
Transfer history data appended for: https://www.transfermarkt.com/mario-jurcevic/profil/spieler/325124.
Transfer history data appended for: https://www.transfermarkt.com/talys/profil/spieler/562671.
Transfer history data appended for: https://www.transfermarkt.com/vedran-jugovic/profil/spieler/49929.
Transfer history data appended for: https://www.transfermarkt.com/merveil-ndockyt/profil/spieler/398886.
Transfer history data appended for: https://www.transfermarkt.com/ante-erceg/profil/spieler/131303.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-lyopa/profil/spieler/54816.
Transfer history data appended for: https://www.transfermarkt.com/marin-pilj/profil/spieler/458052.
Transfer history data appended for: https://www.transfermarkt.com/jose-antonio-caro/profil/spieler/254039.
Transfer history data appended for: https://www.transfermarkt.com/antonijo-jezina/profil/spieler/52524.
Transfer history data appended for: https://www.transfermarkt.com/josip-vukovic/profil/spieler/166230.
Transfer history data appended for: https://www.transfermarkt.com/danijel-loncar/profil/spieler/366287.
Transfer history data appended for: https://www.transfermarkt.com/ivica-ivusic/profil/spieler/160482.
Transfer history data appended for: https://www.transfermarkt.com/eros-grezda/profil/spieler/289814.
Transfer history data appended for: https://www.transfermarkt.com/alen-grgic/profil/spieler/285077.
Transfer history data appended for: https://www.transfermarkt.com/mile-skoric/profil/spieler/71594.
Transfer history data appended for: https://www.transfermarkt.com/mihael-zaper/profil/spieler/434557.
Transfer history data appended for: https://www.transfermarkt.com/mijo-sabic/profil/spieler/315886.
Transfer history data appended for: https://www.transfermarkt.com/domagoj-drozdek/profil/spieler/240247.
Transfer history data appended for: https://www.transfermarkt.com/ivan-posavec/profil/spieler/458540.
Transfer history data appended for: https://www.transfermarkt.com/kerim-memija/profil/spieler/307098.
Transfer history data appended for: https://www.transfermarkt.com/neven-djurasek/profil/spieler/341424.
Transfer history data appended for: https://www.transfermarkt.com/borna-petrovic/profil/spieler/375859.
Transfer history data appended for: https://www.transfermarkt.com/jorgo-pellumbi/profil/spieler/454293.
Transfer history data appended for: https://www.transfermarkt.com/damjan-danicic/profil/spieler/617130.
Transfer history data appended for: https://www.transfermarkt.com/itsuki-urata/profil/spieler/351557.
Transfer history data appended for: https://www.transfermarkt.com/jessie-guera-djou/profil/spieler/547699.
Transfer history data appended for: https://www.transfermarkt.com/nikola-tkalcic/profil/spieler/120874.
Transfer history data appended for: https://www.transfermarkt.com/stefan-milic/profil/spieler/502022.
Transfer history data appended for: https://www.transfermarkt.com/matija-kolaric/profil/spieler/366062.
Transfer history data appended for: https://www.transfermarkt.com/dinko-gavranovic/profil/spieler/319140.
Transfer history data appended for: https://www.transfermarkt.com/jorge-obregon/profil/spieler/414773.
Transfer history data appended for: https://www.transfermarkt.com/dinko-horkas/profil/spieler/357770.
Transfer history data appended for: https://www.transfermarkt.com/marko-stolnik/profil/spieler/226095.
Transfer history data appended for: https://www.transfermarkt.com/leon-benko/profil/spieler/27824.
Transfer history data appended for: https://www.transfermarkt.com/demir-peco/profil/spieler/374248.
Transfer history data appended for: https://www.transfermarkt.com/luka-mezga/profil/spieler/655978.
Transfer history data appended for: https://www.transfermarkt.com/ivan-novoselec/profil/spieler/349015.
Transfer history data appended for: https://www.transfermarkt.com/matej-senic/profil/spieler/263560.
Transfer history data appended for: https://www.transfermarkt.com/dino-skorup/profil/spieler/526565.
Transfer history data appended for: https://www.transfermarkt.com/dejan-glavica/profil/spieler/135118.
Transfer history data appended for: https://www.transfermarkt.com/oliver-zelenika/profil/spieler/131330.
Transfer history data appended for: https://www.transfermarkt.com/vinko-petkovic/profil/spieler/366418.
Transfer history data appended for: https://www.transfermarkt.com/dominik-glavina/profil/spieler/148397.
Transfer history data appended for: https://www.transfermarkt.com/ivan-roca/profil/spieler/454907.
Transfer history data appended for: https://www.transfermarkt.com/jurica-grgec/profil/spieler/187647.
Transfer history data appended for: https://www.transfermarkt.com/ivan-delic/profil/spieler/317023.
Transfer history data appended for: https://www.transfermarkt.com/matija-kovacic/profil/spieler/272391.
Transfer history data appended for: https://www.transfermarkt.com/fran-cerovcec/profil/spieler/584691.
Transfer history data appended for: https://www.transfermarkt.com/agon-elezi/profil/spieler/505324.
Transfer history data appended for: https://www.transfermarkt.com/isnik-alimi/profil/spieler/204659.
Transfer history data appended for: https://www.transfermarkt.com/karlo-bilic/profil/spieler/364579.
Transfer history data appended for: https://www.transfermarkt.com/pjero-lokin/profil/spieler/610191.
Transfer history data appended for: https://www.transfermarkt.com/deni-juric/profil/spieler/407697.
Transfer history data appended for: https://www.transfermarkt.com/juan-nieva/profil/spieler/582545.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/yeferson-contreras/profil/spieler/585351.
Transfer history data appended for: https://www.transfermarkt.com/josip-males/profil/spieler/155566.
Transfer history data appended for: https://www.transfermarkt.com/ivica-batarelo/profil/spieler/531351.
Transfer history data appended for: https://www.transfermarkt.com/emir-sahiti/profil/spieler/403177.
Transfer history data appended for: https://www.transfermarkt.com/todor-todoroski/profil/spieler/344960.
Transfer history data appended for: https://www.transfermarkt.com/luka-celic/profil/spieler/391381.
Transfer history data appended for: https://www.transfermarkt.com/toni-spanja/profil/spieler/195166.
Transfer history data appended for: https://www.transfermarkt.com/arian-mrsulja/profil/spieler/471477.
Transfer history data appended for: https://www.transfermarkt.com/ivan-laca/profil/spieler/663898.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-martin/profil/spieler/622952.
Transfer history data appended for: https://www.transfermarkt.com/mate-barisic/profil/spieler/666140.
Transfer history data appended for: https://www.transfermarkt.com/lovre-rogic/profil/spieler/314616.
Transfer history data appended for: https://www.transfermarkt.com/boris-pandza/profil/spieler/28456.
Transfer history data appended for: https://www.transfermarkt.com/josip-kvesic/profil/spieler/101042.
Transfer history data appended for: https://www.transfermarkt.com/doni-grdic/profil/spieler/706774.
Transfer history data appended for: https://www.transfermarkt.com/prince-ampem/profil/spieler/562734.
Transfer history data appended for: https://www.transfermarkt.com/mario-curic/profil/spieler/531350.
Transfer history data appended for: https://www.transfermarkt.com/martin-vukorepa/profil/spieler/388128.
Transfer history data appended for: https://www.transfermarkt.com/juan-camilo-mesa/profil/spieler/624919.
Transfer history data appended for: https://www.transfermarkt.com/martin-pajic/profil/spieler/470628.
Transfer history data appended for: https://www.transfermarkt.com/nikola-rak/profil/spieler/190636.
Transfer history data appended for: https://www.transfermarkt.com/marko-bulat/profil/spieler/491039.
Transfer history data appended for: https://www.transfermarkt.com/nediljko-labrovic/profil/spieler/610190.
Transfer history data appended for: https://www.transfermarkt.com/stefan-loncar/profil/spieler/352599.
Transfer history data appended for: https://www.transfermarkt.com/ivan-lucic/profil/spieler/164145.
Transfer history data appended for: https://www.transfermarkt.com/rafa-paez/profil/spieler/268258.
Transfer history data appended for: https://www.transfermarkt.com/petar-bosancic/profil/spieler/336577.
Transfer history data appended for: https://www.transfermarkt.com/josip-spoljaric/profil/spieler/293196.
Transfer history data appended for: https://www.transfermarkt.com/luka-hujber/profil/spieler/510256.
Transfer history data appended for: https://www.transfermarkt.com/einar-galilea/profil/spieler/251046.
Transfer history data appended for: https://www.transfermarkt.com/sergi-gonzalez/profil/spieler/281979.
Transfer history data appended for: https://www.transfermarkt.com/dino-halilovic/profil/spieler/333498.
Transfer history data appended for: https://www.transfermarkt.com/slavko-blagojevic/profil/spieler/46021.
Transfer history data appended for: https://www.transfermarkt.com/josip-tomasevic/profil/spieler/177774.
Transfer history data appended for: https://www.transfermarkt.com/antonio-perera/profil/spieler/483742.
Transfer history data appended for: https://www.transfermarkt.com/lovro-majkic/profil/spieler/494847.
Transfer history data appended for: https://www.transfermarkt.com/gedeon-guzina/profil/spieler/447462.
Transfer history data appended for: https://www.transfermarkt.com/matej-vuk/profil/spieler/371004.
Transfer history data appended for: https://www.transfermarkt.com/jan-paus-kunst/profil/spieler/830280.
Transfer history data appended for: https://www.transfermarkt.com/mario-munivrana/profil/spieler/340243.
Transfer history data appended for: https://www.transfermarkt.com/mario-vojkovic/profil/spieler/220727.
Transfer history data appended for: https://www.transfermarkt.com/vice-miljanic/profil/spieler/506292.
Transfer history data appended for: https://www.transfermarkt.com/kyu-hyeong-kim/profil/spieler/558084.
Transfer history data appended for: https://www.transfermarkt.com/rafa-navarro/profil/spieler/351746.
Transfer history data appended for: https://www.transfermarkt.com/lovro-juric/profil/spieler/434247.
Transfer history data appended for: https://www.transfermarkt.com/hyun-woo-kim/profil/spieler/561403.
Transfer history data appended for: https://www.transfermarkt.com/sime-grzan/profil/spieler/186647.
Transfer history data appended for: https://www.transfermarkt.com/marko-bibic/profil/spieler/727414.
Transfer history data appended for: https://www.transfermarkt.com/adrian-fuentes/profil/spieler/597083.
Transfer history data appended for: https://www.transfermarkt.com/mateo-lisica/profil/spieler/665275.
Transfer history data appended for: https://www.transfermarkt.com/antonio-ivancic/profil/spieler/388145.
Transfer history data appended for: https://www.transfermarkt.com/toni-buric/profil/spieler/566526.
Transfer history data appended for: https://www.transfermarkt.com/arona-sane/profil/spieler/282006.
Transfer history data appended for: https://www.transfermarkt.com/franjo-prce/profil/spieler/240260.
Transfer history data appended for: https://www.transfermarkt.com/jeffren/profil/spieler/53309.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-glavcic/profil/spieler/257468.
Transfer history data appended for: https://www.transfermarkt.com/viktor-vrebac/profil/spieler/602936.
Transfer history data appended for: https://www.transfermarkt.com/damian-van-bruggen/profil/spieler/241420.
Transfer history data appended for: https://www.transfermarkt.com/goran-paracki/profil/spieler/39965.
Transfer history data appended for: https://www.transfermarkt.com/miroslav-ilicic/profil/spieler/427370.
Transfer history data appended for: https://www.transfermarkt.com/frane-maglica/profil/spieler/340775.
Transfer history data appended for: https://www.transfermarkt.com/torles-knoll/profil/spieler/284737.
Transfer history data appended for: https://www.transfermarkt.com/ivan-covic/profil/spieler/76254.
Transfer history data appended for: https://www.transfermarkt.com/martin-boakye/profil/spieler/421302.
Transfer history data appended for: https://www.transfermarkt.com/matko-zirdum/profil/spieler/371914.
Transfer history data appended for: https://www.transfermarkt.com/arijan-brkovic/profil/spieler/584091.
Transfer history data appended for: https://www.transfermarkt.com/ivan-krstanovic/profil/spieler/47171.
Transfer history data appended for: https://www.transfermarkt.com/bruno-bogojevic/profil/spieler/464604.
Transfer history data appended for: https://www.transfermarkt.com/matej-jukic/profil/spieler/347851.
Transfer history data appended for: https://www.transfermarkt.com/ivan-filipovic/profil/spieler/234187.
Transfer history data appended for: https://www.transfermarkt.com/bruno-goda/profil/spieler/414956.
Transfer history data appended for: https://www.transfermarkt.com/stipe-bacelic-grgic/profil/spieler/40632.
Transfer history data appended for: https://www.transfermarkt.com/vinko-soldo/profil/spieler/316936.
Transfer history data appended for: https://www.transfermarkt.com/frano-mlinar/profil/spieler/123638.
Transfer history data appended for: https://www.transfermarkt.com/franck-etoundi/profil/spieler/140597.
Transfer history data appended for: https://www.transfermarkt.com/tomislav-bozic/profil/spieler/34577.
Transfer history data appended for: https://www.transfermarkt.com/karlo-lulic/profil/spieler/240252.
Transfer history data appended for: https://www.transfermarkt.com/ivan-dolcek/profil/spieler/554565.
Transfer history data appended for: https://www.transfermarkt.com/jani-atanasov/profil/spieler/392576.
Transfer history data appended for: https://www.transfermarkt.com/mario-cuic/profil/spieler/545226.

Transfer history data appended for: https://www.transfermarkt.com/david-colina/profil/spieler/371000.
Transfer history data appended for: https://www.transfermarkt.com/bassel-jradi/profil/spieler/95737.
Transfer history data appended for: https://www.transfermarkt.com/josip-posavec/profil/spieler/255322.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/adam-gyurcso/profil/spieler/143358.
Transfer history data appended for: https://www.transfermarkt.com/umut-nayir/profil/spieler/248271.
Transfer history data appended for: https://www.transfermarkt.com/leon-krekovic/profil/spieler/425784.
Transfer history data appended for: https://www.transfermarkt.com/darko-nejasmic/profil/spieler/526566.
Transfer history data appended for: https://www.transfermarkt.com/nihad-mujakic/profil/spieler/380919.
Transfer history data appended for: https://www.transfermarkt.com/marin-jakolis/profil/spieler/261963.
Transfer history data appended for: https://www.transfermarkt.com/tonio-teklic/profil/spieler/510241.
Transfer history data appended for: https://www.transfermarkt.com/jairo-da-silva/profil/spieler/315310.
Transfer history data appended for: https://www.transfermarkt.com/kristian-dimitrov/profil/spieler/351800.
Transfer history data appended for: https://www.transfermarkt.com/mario-vuskovic/profil/spieler/432757.
Transfer history data appended for: https://www.transfermarkt.com/stipe-radic/profil/spieler/371002.
Transfer history data appended for: https://www.transfermarkt.com/bozo-mikulic/profil/spieler/334839.
Transfer history data appended for: https://www.transfermarkt.com/darko-todorovic/profil/spieler/293231.
Transfer history data appended for: https://www.transfermarkt.com/marin-ljubic/profil/spieler/532772.
Transfer history data appended for: https://www.transfermarkt.com/mijo-caktas/profil/spieler/197032.
Transfer history data appended for: https://www.transfermarkt.com/ivan-brnic/profil/spieler/432752.
Transfer history data appended for: https://www.transfermarkt.com/stanko-juric/profil/spieler/388125.
Transfer history data appended for: https://www.transfermarkt.com/tibor-halilovic/profil/spieler/324957.
Transfer history data appended for: https://www.transfermarkt.com/tomislav-turcin/profil/spieler/345771.
Transfer history data appended for: https://www.transfermarkt.com/luka-capan/profil/spieler/205902.
Transfer history data appended for: https://www.transfermarkt.com/ennio-travaglia/profil/spieler/393733.
Transfer history data appended for: https://www.transfermarkt.com/sandro-kulenovic/profil/spieler/357778.
Transfer history data appended for: https://www.transfermarkt.com/ivan-lepinjica/profil/spieler/494851.
Transfer history data appended for: https://www.transfermarkt.com/hrvoje-smolcic/profil/spieler/571299.
Transfer history data appended for: https://www.transfermarkt.com/momcilo-raspopovic/profil/spieler/246836.
Transfer history data appended for: https://www.transfermarkt.com/milan-ristovski/profil/spieler/344968.
Transfer history data appended for: https://www.transfermarkt.com/daniel-stefulj/profil/spieler/572917.
Transfer history data appended for: https://www.transfermarkt.com/domagoj-pavicic/profil/spieler/131326.
Transfer history data appended for: https://www.transfermarkt.com/adam-gnezda-cerin/profil/spieler/401394.
Transfer history data appended for: https://www.transfermarkt.com/robert-muric/profil/spieler/226085.
Transfer history data appended for: https://www.transfermarkt.com/nino-galovic/profil/spieler/194005.
Transfer history data appended for: https://www.transfermarkt.com/andrej-prskalo/profil/spieler/38204.
Transfer history data appended for: https://www.transfermarkt.com/niko-galesic/profil/spieler/528835.
Transfer history data appended for: https://www.transfermarkt.com/darko-velkovski/profil/spieler/191822.
Transfer history data appended for: https://www.transfermarkt.com/stjepan-loncar/profil/spieler/341300.
Transfer history data appended for: https://www.transfermarkt.com/dani-iglesias/profil/spieler/199348.
Transfer history data appended for: https://www.transfermarkt.com/joao-escoval/profil/spieler/396428.
Transfer history data appended for: https://www.transfermarkt.com/sterling-yateke/profil/spieler/606332.
Transfer history data appended for: https://www.transfermarkt.com/ivan-tomecak/profil/spieler/49985.
Transfer history data appended for: https://www.transfermarkt.com/ivan-nevistic/profil/spieler/293185.
Transfer history data appended for: https://www.transfermarkt.com/luka-menalo/profil/spieler/316047.
Transfer history data appended for: https://www.transfermarkt.com/david-nwolokor/profil/spieler/358195.
Transfer history data appended for: https://www.transfermarkt.com/marko-putnik/profil/spieler/491043.
Transfer history data appended for: https://www.transfermarkt.com/armando-anastasio/profil/spieler/286275.
Transfer history data appended for: https://www.transfermarkt.com/zoran-arsenic/profil/spieler/280312.
Transfer history data appended for: https://www.transfermarkt.com/filip-braut/profil/spieler/587509.
Transfer history data appended for: https://www.transfermarkt.com/petar-stojanovic/profil/spieler/183841.
Transfer history data appended for: https://www.transfermarkt.com/marko-tolic/profil/spieler/349264.
Transfer history data appended for: https://www.transfermarkt.com/josip-misic/profil/spieler/227035.
Transfer history data appended for: https://www.transfermarkt.com/lovro-majer/profil/spieler/387106.
Transfer history data appended for: https://www.transfermarkt.com/izet-hajrovic/profil/spieler/74996.
Transfer history data appended for: https://www.transfermarkt.com/josip-sutalo/profil/spieler/371001.
Transfer history data appended for: https://www.transfermarkt.com/arijan-ademi/profil/spieler/71542.
Transfer history data appended for: https://www.transfermarkt.com/bruno-petkovic/profil/spieler/256358.
Transfer history data appended for: https://www.transfermarkt.com/josko-gvardiol/profil/spieler/475959.
Transfer history data appended for: https://www.transfermarkt.com/bartol-franjic/profil/spieler/370998.
Transfer history data appended for: https://www.transfermarkt.com/tin-hrvoj/profil/spieler/432746.
Transfer history data appended for: https://www.transfermarkt.com/marko-leskovic/profil/spieler/133834.
Transfer history data appended for: https://www.transfermarkt.com/kristijan-jakic/profil/spieler/374954.
Transfer history data appended for: https://www.transfermarkt.com/marin-leovac/profil/spieler/51604.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-lauritsen/profil/spieler/325994.
Transfer history data appended for: https://www.transfermarkt.com/danijel-zagorac/profil/spieler/131310.
Transfer history data appended for: https://www.transfermarkt.com/kevin-theophile-catherine/profil/spieler/60603.
Transfer history data appended for: https://www.transfermarkt.com/mislav-orsic/profil/spieler/119150.
Transfer history data appended for: https://www.transfermarkt.com/luka-ivanusec/profil/spieler/387105.
Transfer history data appended for: https://www.transfermarkt.com/dino-peric/profil/spieler/240106.
Transfer history data appended for: https://www.transfermarkt.com/lirim-kastrati/profil/spieler/531218.
Transfer history data appended for: https://www.transfermarkt.com/iyayi-atiemwen/profil/spieler/419597.
Transfer history data appended for: https://www.transfermarkt.com/mario-cuze/profil/spieler/376445.
Transfer history data appended for: https://www.transfermarkt.com/sadegh-moharrami/profil/spieler/294778.
Transfer history data appended for: https://www.transfermarkt.com/dominik-livakovic/profil/spieler/205927.
Transfer history data appended for: https://www.transfermarkt.com/robbie-burton/profil/spieler/404386.
Transfer history data appended for: https://www.transfermarkt.com/marko-djira/profil/spieler/357791.
Transfer history data appended for: https://www.transfermarkt.com/sherif-kallaku/profil/spieler/466815.
Transfer history data appended for: https://www.transfermarkt.com/dzemal-ibishi/profil/spieler/542337.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-yahaya/profil/spieler/779309.
Transfer history data appended for: https://www.transfermarkt.com/frane-vojkovic/profil/spieler/226102.
Transfer history data appended for: https://www.transfermarkt.com/luka-ivan-lukic/profil/spieler/781123.
Transfer history data appended for: https://www.transfermarkt.com/hajdin-salihu/profil/spieler/256942.
Transfer history data appended for: https://www.transfermarkt.com/mario-budimir/profil/spieler/41759.

Transfer history data appended for: https://www.transfermarkt.com/reuben-acquah/profil/spieler/254280.
Transfer history data appended for: https://www.transfermarkt.com/kresimir-kovacevic/profil/spieler/270925.
Transfer history data appended for: https://www.transfermarkt.com/petar-gluhakovic/profil/spieler/186361.
Transfer history data appended for: https://www.transfermarkt.com/edis-malikji/profil/spieler/227429.
Transfer history data appended for: https://www.transfermarkt.com/fran-karacic/profil/spieler/367795.
Transfer history data appended for: https://www.transfermarkt.com/roko-simic/profil/spieler/658693.
Transfer history data appended for: https://www.transfermarkt.com/alex-dos-santos/profil/spieler/396341.
Transfer history data appended for: https://www.transfermarkt.com/jon-mersinaj/profil/spieler/540935.
Transfer history data appended for: https://www.transfermarkt.com/moutir-chajia/profil/spieler/448538.
Transfer history data appended for: https://www.transfermarkt.com/oliver-petrak/profil/spieler/46624.
Transfer history data appended for: https://www.transfermarkt.com/josip-majic/profil/spieler/285457.
Transfer history data appended for: https://www.transfermarkt.com/francesco-tahiraj/profil/spieler/287354.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-aliyu/profil/spieler/647958.
Transfer history data appended for: https://www.transfermarkt.com/stipo-markovic/profil/spieler/233136.
Transfer history data appended for: https://www.transfermarkt.com/ivan-celikovic/profil/spieler/47611.
Transfer history data appended for: https://www.transfermarkt.com/kemal-osmankovic/profil/spieler/293223.
Transfer history data appended for: https://www.transfermarkt.com/denis-kolinger/profil/spieler/90725.
Transfer history data appended for: https://www.transfermarkt.com/nikica-jelavic/profil/spieler/25742.
Transfer history data appended for: https://www.transfermarkt.com/enis-cokaj/profil/spieler/644244.
Transfer history data appended for: https://www.transfermarkt.com/indrit-tuci/profil/spieler/675857.
Transfer history data appended for: https://www.transfermarkt.com/filip-jovicevic/profil/spieler/531080.
Transfer history data appended for: https://www.transfermarkt.com/josip-pivaric/profil/spieler/45826.
Transfer history data appended for: https://www.transfermarkt.com/dominik-kovacic/profil/spieler/258898.
Transfer history data appended for: https://www.transfermarkt.com/krunoslav-hendija/profil/spieler/46560.
Transfer history data appended for: https://www.transfermarkt.com/tin-zavalic/profil/spieler/811198.
Transfer history data appended for: https://www.transfermarkt.com/joey-suk/profil/spieler/101657.
Transfer history data appended for: https://www.transfermarkt.com/leon-isek/profil/spieler/687638.
Transfer history data appended for: https://www.transfermarkt.com/nasiru-moro/profil/spieler/548671.
Transfer history data appended for: https://www.transfermarkt.com/younes-delfi/profil/spieler/479233.
Transfer history data appended for: https://www.transfermarkt.com/kristijan-lovric/profil/spieler/294401.
Transfer history data appended for: https://www.transfermarkt.com/albi-doka/profil/spieler/486205.
Transfer history data appended for: https://www.transfermarkt.com/jurica-prsir/profil/spieler/425780.
Transfer history data appended for: https://www.transfermarkt.com/matija-dvornekovic/profil/spieler/98122.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-jovicic/profil/spieler/258268.
Transfer history data appended for: https://www.transfermarkt.com/ivan-severdija/profil/spieler/750022.
Transfer history data appended for: https://www.transfermarkt.com/kristijan-kahlina/profil/spieler/133831.
Transfer history data appended for: https://www.transfermarkt.com/matar-dieye/profil/spieler/427100.
Transfer history data appended for: https://www.transfermarkt.com/marijan-cabraja/profil/spieler/355651.
Transfer history data appended for: https://www.transfermarkt.com/ivan-banic/profil/spieler/160467.
Transfer history data appended for: https://www.transfermarkt.com/hrvoje-babec/profil/spieler/403723.
Transfer history data appended for: https://www.transfermarkt.com/anthony-kalik/profil/spieler/303420.
Transfer history data appended for: https://www.transfermarkt.com/kresimir-krizmanic/profil/spieler/585858.
Transfer history data appended for: https://www.transfermarkt.com/ognjen-mudrinski/profil/spieler/139918.
Transfer history data appended for: https://www.transfermarkt.com/matthew-steenvoorden/profil/spieler/202793.
Transfer history data appended for: https://www.transfermarkt.com/josip-ivan-zorica/profil/spieler/720946.
Transfer history data appended for: https://www.transfermarkt.com/musa-muhammed/profil/spieler/295342.
Transfer history data appended for: https://www.transfermarkt.com/dario-spikic/profil/spieler/403290.
Transfer history data appended for: https://www.transfermarkt.com/josip-mitrovic/profil/spieler/464332.
Transfer history data appended for: https://www.transfermarkt.com/fabrice-hartmann/profil/spieler/405685.
Transfer history data appended for: https://www.transfermarkt.com/marcel-halstenberg/profil/spieler/70243.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-konate/profil/spieler/357119.
Transfer history data appended for: https://www.transfermarkt.com/hee-chan-hwang/profil/spieler/292246.
Transfer history data appended for: https://www.transfermarkt.com/tim-schreiber/profil/spieler/426685.
Transfer history data appended for: https://www.transfermarkt.com/konrad-laimer/profil/spieler/223967.
Transfer history data appended for: https://www.transfermarkt.com/josep-martinez/profil/spieler/388516.
Transfer history data appended for: https://www.transfermarkt.com/kevin-kampl/profil/spieler/53418.
Transfer history data appended for: https://www.transfermarkt.com/willi-orban/profil/spieler/93740.
Transfer history data appended for: https://www.transfermarkt.com/joscha-wosz/profil/spieler/597004.
Transfer history data appended for: https://www.transfermarkt.com/justin-kluivert/profil/spieler/330659.
Transfer history data appended for: https://www.transfermarkt.com/lazar-samardzic/profil/spieler/528833.
Transfer history data appended for: https://www.transfermarkt.com/amadou-haidara/profil/spieler/402008.
Transfer history data appended for: https://www.transfermarkt.com/dani-olmo/profil/spieler/293385.
Transfer history data appended for: https://www.transfermarkt.com/dayot-upamecano/profil/spieler/344695.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-henrichs/profil/spieler/202591.
Transfer history data appended for: https://www.transfermarkt.com/tyler-adams/profil/spieler/332705.
Transfer history data appended for: https://www.transfermarkt.com/hugo-novoa/profil/spieler/668276.
Transfer history data appended for: https://www.transfermarkt.com/emil-forsberg/profil/spieler/111078.
Transfer history data appended for: https://www.transfermarkt.com/marcel-sabitzer/profil/spieler/106987.
Transfer history data appended for: https://www.transfermarkt.com/eric-martel/profil/spieler/597000.
Transfer history data appended for: https://www.transfermarkt.com/yussuf-poulsen/profil/spieler/157635.
Transfer history data appended for: https://www.transfermarkt.com/angelino/profil/spieler/277179.
Transfer history data appended for: https://www.transfermarkt.com/peter-gulacsi/profil/spieler/57071.
Transfer history data appended for: https://www.transfermarkt.com/nordi-mukiele/profil/spieler/348026.
Transfer history data appended for: https://www.transfermarkt.com/dennis-borkowski/profil/spieler/467426.
Transfer history data appended for: https://www.transfermarkt.com/christopher-nkunku/profil/spieler/344381.
Transfer history data appended for: https://www.transfermarkt.com/lukas-klostermann/profil/spieler/215599.
Transfer history data appended for: https://www.transfermarkt.com/thomas-muller/profil/spieler/58358.
Transfer history data appended for: https://www.transfermarkt.com/lucas-hernandez/profil/spieler/281963.
Transfer history data appended for: https://www.transfermarkt.com/kingsley-coman/profil/spieler/243714.
Transfer history data appended for: https://www.transfermarkt.com/douglas-costa/profil/spieler/75615.

Transfer history data appended for: https://www.transfermarkt.com/jamal-musiala/profil/spieler/580195.
Transfer history data appended for: https://www.transfermarkt.com/alexander-nubel/profil/spieler/195778.
Transfer history data appended for: https://www.transfermarkt.com/ron-thorben-hoffmann/profil/spieler/317444.
Transfer history data appended for: https://www.transfermarkt.com/serge-gnabry/profil/spieler/159471.
Transfer history data appended for: https://www.transfermarkt.com/angelo-stiller/profil/spieler/443710.
Transfer history data appended for: https://www.transfermarkt.com/manuel-neuer/profil/spieler/17259.
Transfer history data appended for: https://www.transfermarkt.com/david-alaba/profil/spieler/59016.
Transfer history data appended for: https://www.transfermarkt.com/alphonso-davies/profil/spieler/424204.
Transfer history data appended for: https://www.transfermarkt.com/bouna-sarr/profil/spieler/190685.
Transfer history data appended for: https://www.transfermarkt.com/javi-martinez/profil/spieler/44017.
Transfer history data appended for: https://www.transfermarkt.com/leon-goretzka/profil/spieler/153084.
Transfer history data appended for: https://www.transfermarkt.com/fiete-arp/profil/spieler/343337.
Transfer history data appended for: https://www.transfermarkt.com/chris-richards/profil/spieler/578539.
Transfer history data appended for: https://www.transfermarkt.com/niklas-sule/profil/spieler/166601.
Transfer history data appended for: https://www.transfermarkt.com/joshua-zirkzee/profil/spieler/435648.
Transfer history data appended for: https://www.transfermarkt.com/jerome-boateng/profil/spieler/26485.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-pavard/profil/spieler/353366.
Transfer history data appended for: https://www.transfermarkt.com/robert-lewandowski/profil/spieler/38253.
Transfer history data appended for: https://www.transfermarkt.com/tanguy-nianzou/profil/spieler/538996.
Transfer history data appended for: https://www.transfermarkt.com/bright-arrey-mbi/profil/spieler/580193.
Transfer history data appended for: https://www.transfermarkt.com/leroy-sane/profil/spieler/192565.
Transfer history data appended for: https://www.transfermarkt.com/tiago-dantas/profil/spieler/429987.
Transfer history data appended for: https://www.transfermarkt.com/leon-dajaku/profil/spieler/483974.
Transfer history data appended for: https://www.transfermarkt.com/marc-roca/profil/spieler/336869.
Transfer history data appended for: https://www.transfermarkt.com/corentin-tolisso/profil/spieler/190393.
Transfer history data appended for: https://www.transfermarkt.com/andre-silva/profil/spieler/198008.
Transfer history data appended for: https://www.transfermarkt.com/jabez-makanda/profil/spieler/519226.
Transfer history data appended for: https://www.transfermarkt.com/david-abraham/profil/spieler/58178.
Transfer history data appended for: https://www.transfermarkt.com/makoto-hasebe/profil/spieler/39259.
Transfer history data appended for: https://www.transfermarkt.com/daichi-kamada/profil/spieler/356141.
Transfer history data appended for: https://www.transfermarkt.com/ragnar-ache/profil/spieler/416380.
Transfer history data appended for: https://www.transfermarkt.com/yannick-brugger/profil/spieler/441238.
Transfer history data appended for: https://www.transfermarkt.com/marijan-cavar/profil/spieler/419255.
Transfer history data appended for: https://www.transfermarkt.com/evan-ndicka/profil/spieler/371149.
Transfer history data appended for: https://www.transfermarkt.com/kevin-trapp/profil/spieler/45672.
Transfer history data appended for: https://www.transfermarkt.com/lukas-fahrnberger/profil/spieler/404262.
Transfer history data appended for: https://www.transfermarkt.com/danny-da-costa/profil/spieler/85906.
Transfer history data appended for: https://www.transfermarkt.com/timothy-chandler/profil/spieler/49723.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-rode/profil/spieler/44466.
Transfer history data appended for: https://www.transfermarkt.com/elias-bordner/profil/spieler/569288.
Transfer history data appended for: https://www.transfermarkt.com/tuta/profil/spieler/546213.
Transfer history data appended for: https://www.transfermarkt.com/almamy-toure/profil/spieler/216181.
Transfer history data appended for: https://www.transfermarkt.com/bas-dost/profil/spieler/56331.
Transfer history data appended for: https://www.transfermarkt.com/fynn-otto/profil/spieler/529198.
Transfer history data appended for: https://www.transfermarkt.com/jetro-willems/profil/spieler/146258.
Transfer history data appended for: https://www.transfermarkt.com/felix-irorere/profil/spieler/472224.
Transfer history data appended for: https://www.transfermarkt.com/stefan-ilsanker/profil/spieler/40074.
Transfer history data appended for: https://www.transfermarkt.com/markus-schubert/profil/spieler/296741.
Transfer history data appended for: https://www.transfermarkt.com/djibril-sow/profil/spieler/212723.
Transfer history data appended for: https://www.transfermarkt.com/ajdin-hrustic/profil/spieler/265625.
Transfer history data appended for: https://www.transfermarkt.com/erik-durm/profil/spieler/93922.
Transfer history data appended for: https://www.transfermarkt.com/mark-uth/profil/spieler/112935.
Transfer history data appended for: https://www.transfermarkt.com/vedad-ibisevic/profil/spieler/21175.
Transfer history data appended for: https://www.transfermarkt.com/frederik-ronnow/profil/spieler/107775.
Transfer history data appended for: https://www.transfermarkt.com/suat-serdar/profil/spieler/261905.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-kutucu/profil/spieler/452084.
Transfer history data appended for: https://www.transfermarkt.com/ozan-kabak/profil/spieler/361260.
Transfer history data appended for: https://www.transfermarkt.com/goncalo-paciencia/profil/spieler/181547.
Transfer history data appended for: https://www.transfermarkt.com/nassim-boujellab/profil/spieler/346332.
Transfer history data appended for: https://www.transfermarkt.com/kerim-calhanoglu/profil/spieler/553905.
Transfer history data appended for: https://www.transfermarkt.com/nabil-bentaleb/profil/spieler/245537.
Transfer history data appended for: https://www.transfermarkt.com/amine-harit/profil/spieler/372711.
Transfer history data appended for: https://www.transfermarkt.com/luca-schuler/profil/spieler/388029.
Transfer history data appended for: https://www.transfermarkt.com/omar-mascarell/profil/spieler/142031.
Transfer history data appended for: https://www.transfermarkt.com/kilian-ludewig/profil/spieler/361516.
Transfer history data appended for: https://www.transfermarkt.com/alessandro-schopf/profil/spieler/118397.
Transfer history data appended for: https://www.transfermarkt.com/matthew-hoppe/profil/spieler/678194.
Transfer history data appended for: https://www.transfermarkt.com/timo-becker/profil/spieler/282349.
Transfer history data appended for: https://www.transfermarkt.com/rabbi-matondo/profil/spieler/404384.
Transfer history data appended for: https://www.transfermarkt.com/can-bozdogan/profil/spieler/406609.
Transfer history data appended for: https://www.transfermarkt.com/matija-nastasic/profil/spieler/143559.
Transfer history data appended for: https://www.transfermarkt.com/bastian-oczipka/profil/spieler/53437.
Transfer history data appended for: https://www.transfermarkt.com/michael-langer/profil/spieler/19114.
Transfer history data appended for: https://www.transfermarkt.com/nick-taitague/profil/spieler/354313.
Transfer history data appended for: https://www.transfermarkt.com/benito-raman/profil/spieler/112930.
Transfer history data appended for: https://www.transfermarkt.com/ralf-fahrmann/profil/spieler/39015.
Transfer history data appended for: https://www.transfermarkt.com/malick-thiaw/profil/spieler/521964.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-stambouli/profil/spieler/127160.
Transfer history data appended for: https://www.transfermarkt.com/salif-sane/profil/spieler/126534.
Transfer history data appended for: https://www.transfermarkt.com/levent-mercan/profil/spieler/388820.

Transfer history data appended for: https://www.transfermarkt.com/carlos-gruezo/profil/spieler/189475.
Transfer history data appended for: https://www.transfermarkt.com/raphael-framberger/profil/spieler/146163.
Transfer history data appended for: https://www.transfermarkt.com/andre-hahn/profil/spieler/42783.
Transfer history data appended for: https://www.transfermarkt.com/ruben-vargas/profil/spieler/345886.
Transfer history data appended for: https://www.transfermarkt.com/felix-uduokhai/profil/spieler/278343.
Transfer history data appended for: https://www.transfermarkt.com/rani-khedira/profil/spieler/124410.
Transfer history data appended for: https://www.transfermarkt.com/tomas-koubek/profil/spieler/146714.
Transfer history data appended for: https://www.transfermarkt.com/daniel-caligiuri/profil/spieler/38410.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-leneis/profil/spieler/381250.
Transfer history data appended for: https://www.transfermarkt.com/rafal-gikiewicz/profil/spieler/78339.
Transfer history data appended for: https://www.transfermarkt.com/noah-sarenren-bazee/profil/spieler/283001.
Transfer history data appended for: https://www.transfermarkt.com/jeffrey-gouweleeuw/profil/spieler/106405.
Transfer history data appended for: https://www.transfermarkt.com/alfred-finnbogason/profil/spieler/90024.
Transfer history data appended for: https://www.transfermarkt.com/mads-pedersen/profil/spieler/288429.
Transfer history data appended for: https://www.transfermarkt.com/felix-gotze/profil/spieler/330635.
Transfer history data appended for: https://www.transfermarkt.com/marco-richter/profil/spieler/279009.
Transfer history data appended for: https://www.transfermarkt.com/robert-gumny/profil/spieler/353826.
Transfer history data appended for: https://www.transfermarkt.com/iago/profil/spieler/520468.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-jensen/profil/spieler/249157.
Transfer history data appended for: https://www.transfermarkt.com/reinhold-yabo/profil/spieler/74856.
Transfer history data appended for: https://www.transfermarkt.com/marcel-hartel/profil/spieler/189073.
Transfer history data appended for: https://www.transfermarkt.com/brian-behrendt/profil/spieler/85660.
Transfer history data appended for: https://www.transfermarkt.com/ritsu-doan/profil/spieler/358504.
Transfer history data appended for: https://www.transfermarkt.com/nikolai-rehnen/profil/spieler/264304.
Transfer history data appended for: https://www.transfermarkt.com/amos-pieper/profil/spieler/334221.
Transfer history data appended for: https://www.transfermarkt.com/nils-seufert/profil/spieler/279064.
Transfer history data appended for: https://www.transfermarkt.com/jomaine-consbruch/profil/spieler/511246.
Transfer history data appended for: https://www.transfermarkt.com/manuel-prietl/profil/spieler/152317.
Transfer history data appended for: https://www.transfermarkt.com/joakim-nilsson/profil/spieler/216804.
Transfer history data appended for: https://www.transfermarkt.com/joan-simun-edmundsson/profil/spieler/123683.
Transfer history data appended for: https://www.transfermarkt.com/cedric-brunner/profil/spieler/147038.
Transfer history data appended for: https://www.transfermarkt.com/noel-niemann/profil/spieler/519414.
Transfer history data appended for: https://www.transfermarkt.com/jacob-barrett-laursen/profil/spieler/185164.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-muller/profil/spieler/392139.
Transfer history data appended for: https://www.transfermarkt.com/stefan-ortega-moreno/profil/spieler/85941.
Transfer history data appended for: https://www.transfermarkt.com/anderson-lucoqui/profil/spieler/240274.
Transfer history data appended for: https://www.transfermarkt.com/andreas-voglsammer/profil/spieler/94771.
Transfer history data appended for: https://www.transfermarkt.com/fabian-klos/profil/spieler/78147.
Transfer history data appended for: https://www.transfermarkt.com/sergio-cordova/profil/spieler/377387.
Transfer history data appended for: https://www.transfermarkt.com/oscar-linner/profil/spieler/366974.
Transfer history data appended for: https://www.transfermarkt.com/sven-schipplock/profil/spieler/52530.
Transfer history data appended for: https://www.transfermarkt.com/christian-gebauer/profil/spieler/275423.
Transfer history data appended for: https://www.transfermarkt.com/nathan-de-medina/profil/spieler/285951.
Transfer history data appended for: https://www.transfermarkt.com/mike-van-der-hoorn/profil/spieler/187105.
Transfer history data appended for: https://www.transfermarkt.com/fabian-kunze/profil/spieler/334186.
Transfer history data appended for: https://www.transfermarkt.com/cebio-soukou/profil/spieler/85000.
Transfer history data appended for: https://www.transfermarkt.com/noah-katterbach/profil/spieler/469949.
Transfer history data appended for: https://www.transfermarkt.com/timo-horn/profil/spieler/84938.
Transfer history data appended for: https://www.transfermarkt.com/jonas-hector/profil/spieler/108537.
Transfer history data appended for: https://www.transfermarkt.com/kingsley-ehizibue/profil/spieler/272812.
Transfer history data appended for: https://www.transfermarkt.com/anthony-modeste/profil/spieler/50512.
Transfer history data appended for: https://www.transfermarkt.com/ron-robert-zieler/profil/spieler/21327.
Transfer history data appended for: https://www.transfermarkt.com/florian-kainz/profil/spieler/106270.
Transfer history data appended for: https://www.transfermarkt.com/jan-thielmann/profil/spieler/472249.
Transfer history data appended for: https://www.transfermarkt.com/salih-ozcan/profil/spieler/244940.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-duda/profil/spieler/232418.
Transfer history data appended for: https://www.transfermarkt.com/rafael-czichos/profil/spieler/84150.
Transfer history data appended for: https://www.transfermarkt.com/jorge-mere/profil/spieler/286779.
Transfer history data appended for: https://www.transfermarkt.com/ismail-jakobs/profil/spieler/375137.
Transfer history data appended for: https://www.transfermarkt.com/robert-voloder/profil/spieler/452392.
Transfer history data appended for: https://www.transfermarkt.com/dominick-drexler/profil/spieler/53400.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-limnios/profil/spieler/324344.
Transfer history data appended for: https://www.transfermarkt.com/elvis-rexhbecaj/profil/spieler/280575.
Transfer history data appended for: https://www.transfermarkt.com/julian-krahl/profil/spieler/337082.
Transfer history data appended for: https://www.transfermarkt.com/benno-schmitz/profil/spieler/160968.
Transfer history data appended for: https://www.transfermarkt.com/ellyes-skhiri/profil/spieler/290587.
Transfer history data appended for: https://www.transfermarkt.com/jens-castrop/profil/spieler/613192.
Transfer history data appended for: https://www.transfermarkt.com/sava-arangel-cestic/profil/spieler/464906.
Transfer history data appended for: https://www.transfermarkt.com/sebastiaan-bornauw/profil/spieler/338629.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-andersson/profil/spieler/147573.
Transfer history data appended for: https://www.transfermarkt.com/tim-lemperle/profil/spieler/553285.
Transfer history data appended for: https://www.transfermarkt.com/joao-queiros/profil/spieler/415642.
Transfer history data appended for: https://www.transfermarkt.com/nick-woltemade/profil/spieler/455661.
Transfer history data appended for: https://www.transfermarkt.com/tahith-chong/profil/spieler/344830.
Transfer history data appended for: https://www.transfermarkt.com/jean-manuel-mbom/profil/spieler/335003.
Transfer history data appended for: https://www.transfermarkt.com/milot-rashica/profil/spieler/291739.
Transfer history data appended for: https://www.transfermarkt.com/romano-schmid/profil/spieler/346853.
Transfer history data appended for: https://www.transfermarkt.com/marco-friedl/profil/spieler/156990.
Transfer history data appended for: https://www.transfermarkt.com/yuya-osako/profil/spieler/108650.

Transfer history data appended for: https://www.transfermarkt.com/josh-sargent/profil/spieler/393325.
Transfer history data appended for: https://www.transfermarkt.com/ludwig-augustinsson/profil/spieler/170646.
Transfer history data appended for: https://www.transfermarkt.com/christian-gross/profil/spieler/58396.
Transfer history data appended for: https://www.transfermarkt.com/theodor-gebre-selassie/profil/spieler/60632.
Transfer history data appended for: https://www.transfermarkt.com/felix-agu/profil/spieler/393512.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-eggestein/profil/spieler/190284.
Transfer history data appended for: https://www.transfermarkt.com/eduardo-dos-santos-haesler/profil/spieler/369258.
Transfer history data appended for: https://www.transfermarkt.com/kevin-mohwald/profil/spieler/94137.
Transfer history data appended for: https://www.transfermarkt.com/stefanos-kapino/profil/spieler/68410.
Transfer history data appended for: https://www.transfermarkt.com/milos-veljkovic/profil/spieler/202228.
Transfer history data appended for: https://www.transfermarkt.com/ilia-gruev/profil/spieler/381753.
Transfer history data appended for: https://www.transfermarkt.com/oscar-schonfelder/profil/spieler/455933.
Transfer history data appended for: https://www.transfermarkt.com/patrick-erras/profil/spieler/193859.
Transfer history data appended for: https://www.transfermarkt.com/omer-toprak/profil/spieler/43512.
Transfer history data appended for: https://www.transfermarkt.com/niklas-moisander/profil/spieler/5017.
Transfer history data appended for: https://www.transfermarkt.com/jiri-pavlenka/profil/spieler/260053.
Transfer history data appended for: https://www.transfermarkt.com/davie-selke/profil/spieler/178459.
Transfer history data appended for: https://www.transfermarkt.com/carlo-boukhalfa/profil/spieler/329373.
Transfer history data appended for: https://www.transfermarkt.com/yannik-keitel/profil/spieler/342039.
Transfer history data appended for: https://www.transfermarkt.com/chang-hoon-kwon/profil/spieler/259350.
Transfer history data appended for: https://www.transfermarkt.com/janik-haberer/profil/spieler/177779.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-uphoff/profil/spieler/120296.
Transfer history data appended for: https://www.transfermarkt.com/luca-itter/profil/spieler/296378.
Transfer history data appended for: https://www.transfermarkt.com/lucas-holer/profil/spieler/248999.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-hofler/profil/spieler/55099.
Transfer history data appended for: https://www.transfermarkt.com/keven-schlotterbeck/profil/spieler/413843.
Transfer history data appended for: https://www.transfermarkt.com/amir-abrashi/profil/spieler/66005.
Transfer history data appended for: https://www.transfermarkt.com/mark-flekken/profil/spieler/125714.
Transfer history data appended for: https://www.transfermarkt.com/lino-tempelmann/profil/spieler/378883.
Transfer history data appended for: https://www.transfermarkt.com/manuel-gulde/profil/spieler/45683.
Transfer history data appended for: https://www.transfermarkt.com/baptiste-santamaria/profil/spieler/285323.
Transfer history data appended for: https://www.transfermarkt.com/dominique-heintz/profil/spieler/110036.
Transfer history data appended for: https://www.transfermarkt.com/woo-yeong-jeong/profil/spieler/297583.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-schmid/profil/spieler/70285.
Transfer history data appended for: https://www.transfermarkt.com/christian-gunter/profil/spieler/93707.
Transfer history data appended for: https://www.transfermarkt.com/niclas-thiede/profil/spieler/348778.
Transfer history data appended for: https://www.transfermarkt.com/ermedin-demirovic/profil/spieler/335457.
Transfer history data appended for: https://www.transfermarkt.com/lukas-kubler/profil/spieler/93604.
Transfer history data appended for: https://www.transfermarkt.com/julian-brandt/profil/spieler/187492.
Transfer history data appended for: https://www.transfermarkt.com/youssoufa-moukoko/profil/spieler/467720.
Transfer history data appended for: https://www.transfermarkt.com/mateu-morey-bauza/profil/spieler/388513.
Transfer history data appended for: https://www.transfermarkt.com/jude-bellingham/profil/spieler/581678.
Transfer history data appended for: https://www.transfermarkt.com/tobias-raschl/profil/spieler/384745.
Transfer history data appended for: https://www.transfermarkt.com/raphael-guerreiro/profil/spieler/170986.
Transfer history data appended for: https://www.transfermarkt.com/manuel-akanji/profil/spieler/284730.
Transfer history data appended for: https://www.transfermarkt.com/marco-reus/profil/spieler/35207.
Transfer history data appended for: https://www.transfermarkt.com/thomas-meunier/profil/spieler/100986.
Transfer history data appended for: https://www.transfermarkt.com/nico-schulz/profil/spieler/85867.
Transfer history data appended for: https://www.transfermarkt.com/thomas-delaney/profil/spieler/91849.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-reyna/profil/spieler/504215.
Transfer history data appended for: https://www.transfermarkt.com/erling-haaland/profil/spieler/418560.
Transfer history data appended for: https://www.transfermarkt.com/mats-hummels/profil/spieler/39728.
Transfer history data appended for: https://www.transfermarkt.com/mahmoud-dahoud/profil/spieler/191422.
Transfer history data appended for: https://www.transfermarkt.com/reinier/profil/spieler/627226.
Transfer history data appended for: https://www.transfermarkt.com/axel-witsel/profil/spieler/35047.
Transfer history data appended for: https://www.transfermarkt.com/marcel-schmelzer/profil/spieler/35208.
Transfer history data appended for: https://www.transfermarkt.com/jadon-sancho/profil/spieler/401173.
Transfer history data appended for: https://www.transfermarkt.com/emre-can/profil/spieler/119296.
Transfer history data appended for: https://www.transfermarkt.com/luca-unbehaun/profil/spieler/388815.
Transfer history data appended for: https://www.transfermarkt.com/dan-axel-zagadou/profil/spieler/344598.
Transfer history data appended for: https://www.transfermarkt.com/thorgan-hazard/profil/spieler/102226.
Transfer history data appended for: https://www.transfermarkt.com/roman-burki/profil/spieler/59027.
Transfer history data appended for: https://www.transfermarkt.com/marwin-hitz/profil/spieler/59238.
Transfer history data appended for: https://www.transfermarkt.com/stefan-posch/profil/spieler/223974.
Transfer history data appended for: https://www.transfermarkt.com/philipp-pentke/profil/spieler/8246.
Transfer history data appended for: https://www.transfermarkt.com/mijat-gacinovic/profil/spieler/215864.
Transfer history data appended for: https://www.transfermarkt.com/oliver-baumann/profil/spieler/55089.
Transfer history data appended for: https://www.transfermarkt.com/christoph-baumgartner/profil/spieler/324278.
Transfer history data appended for: https://www.transfermarkt.com/ihlas-bebou/profil/spieler/237164.
Transfer history data appended for: https://www.transfermarkt.com/andrej-kramaric/profil/spieler/46580.
Transfer history data appended for: https://www.transfermarkt.com/munas-dabbur/profil/spieler/145866.
Transfer history data appended for: https://www.transfermarkt.com/ryan-sessegnon/profil/spieler/392775.
Transfer history data appended for: https://www.transfermarkt.com/pavel-kaderabek/profil/spieler/143798.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-beier/profil/spieler/578392.
Transfer history data appended for: https://www.transfermarkt.com/robert-skov/profil/spieler/270393.
Transfer history data appended for: https://www.transfermarkt.com/klauss/profil/spieler/498862.
Transfer history data appended for: https://www.transfermarkt.com/florian-grillitsch/profil/spieler/195736.
Transfer history data appended for: https://www.transfermarkt.com/luca-philipp/profil/spieler/432671.
Transfer history data appended for: https://www.transfermarkt.com/marco-john/profil/spieler/450234.
Transfer history data appended for: https://www.transfermarkt.com/diadie-samassekou/profil/spieler/315604.

Transfer history data appended for: https://www.transfermarkt.com/dennis-geiger/profil/spieler/251309.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-hubner/profil/spieler/52348.
Transfer history data appended for: https://www.transfermarkt.com/sargis-adamyan/profil/spieler/125614.
Transfer history data appended for: https://www.transfermarkt.com/ermin-bicakcic/profil/spieler/51676.
Transfer history data appended for: https://www.transfermarkt.com/kasim-adams/profil/spieler/263801.
Transfer history data appended for: https://www.transfermarkt.com/joshua-brenet/profil/spieler/207006.
Transfer history data appended for: https://www.transfermarkt.com/melayro-bogarde/profil/spieler/476915.
Transfer history data appended for: https://www.transfermarkt.com/niko-giesselmann/profil/spieler/72792.
Transfer history data appended for: https://www.transfermarkt.com/keita-endo/profil/spieler/421726.
Transfer history data appended for: https://www.transfermarkt.com/marvin-friedrich/profil/spieler/196231.
Transfer history data appended for: https://www.transfermarkt.com/sheraldo-becker/profil/spieler/188888.
Transfer history data appended for: https://www.transfermarkt.com/christopher-lenz/profil/spieler/159844.
Transfer history data appended for: https://www.transfermarkt.com/jakob-busk/profil/spieler/203411.
Transfer history data appended for: https://www.transfermarkt.com/christopher-trimmel/profil/spieler/75921.
Transfer history data appended for: https://www.transfermarkt.com/loris-karius/profil/spieler/85864.
Transfer history data appended for: https://www.transfermarkt.com/andreas-luthe/profil/spieler/41323.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-griesbeck/profil/spieler/153555.
Transfer history data appended for: https://www.transfermarkt.com/grischa-promel/profil/spieler/234029.
Transfer history data appended for: https://www.transfermarkt.com/tim-maciejewski/profil/spieler/392156.
Transfer history data appended for: https://www.transfermarkt.com/lennart-moser/profil/spieler/392717.
Transfer history data appended for: https://www.transfermarkt.com/nico-schlotterbeck/profil/spieler/388198.
Transfer history data appended for: https://www.transfermarkt.com/robin-knoche/profil/spieler/94201.
Transfer history data appended for: https://www.transfermarkt.com/max-kruse/profil/spieler/36182.
Transfer history data appended for: https://www.transfermarkt.com/julian-ryerson/profil/spieler/370789.
Transfer history data appended for: https://www.transfermarkt.com/florian-hubner/profil/spieler/85822.
Transfer history data appended for: https://www.transfermarkt.com/marcus-ingvartsen/profil/spieler/269878.
Transfer history data appended for: https://www.transfermarkt.com/robert-andrich/profil/spieler/159088.
Transfer history data appended for: https://www.transfermarkt.com/atakan-karazor/profil/spieler/232320.
Transfer history data appended for: https://www.transfermarkt.com/orel-mangala/profil/spieler/289592.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-castro/profil/spieler/28947.
Transfer history data appended for: https://www.transfermarkt.com/darko-churlinov/profil/spieler/386786.
Transfer history data appended for: https://www.transfermarkt.com/naouirou-ahamada/profil/spieler/538971.
Transfer history data appended for: https://www.transfermarkt.com/holger-badstuber/profil/spieler/54659.
Transfer history data appended for: https://www.transfermarkt.com/maxime-awoudja/profil/spieler/312218.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-gonzalez/profil/spieler/486031.
Transfer history data appended for: https://www.transfermarkt.com/sasa-kalajdzic/profil/spieler/369567.
Transfer history data appended for: https://www.transfermarkt.com/jens-grahl/profil/spieler/40034.
Transfer history data appended for: https://www.transfermarkt.com/lilian-egloff/profil/spieler/472243.
Transfer history data appended for: https://www.transfermarkt.com/tanguy-coulibaly/profil/spieler/618425.
Transfer history data appended for: https://www.transfermarkt.com/fabian-bredlow/profil/spieler/187624.
Transfer history data appended for: https://www.transfermarkt.com/mateo-klimowicz/profil/spieler/540302.
Transfer history data appended for: https://www.transfermarkt.com/luca-mack/profil/spieler/363424.
Transfer history data appended for: https://www.transfermarkt.com/roberto-massimo/profil/spieler/431561.
Transfer history data appended for: https://www.transfermarkt.com/clinton-mola/profil/spieler/470594.
Transfer history data appended for: https://www.transfermarkt.com/borna-sosa/profil/spieler/293194.
Transfer history data appended for: https://www.transfermarkt.com/momo-cisse/profil/spieler/768384.
Transfer history data appended for: https://www.transfermarkt.com/waldemar-anton/profil/spieler/193004.
Transfer history data appended for: https://www.transfermarkt.com/philipp-klement/profil/spieler/60394.
Transfer history data appended for: https://www.transfermarkt.com/philipp-forster/profil/spieler/179635.
Transfer history data appended for: https://www.transfermarkt.com/marcin-kaminski/profil/spieler/129358.
Transfer history data appended for: https://www.transfermarkt.com/marc-oliver-kempf/profil/spieler/160938.
Transfer history data appended for: https://www.transfermarkt.com/antonis-aidonis/profil/spieler/405674.
Transfer history data appended for: https://www.transfermarkt.com/silas-wamangituka/profil/spieler/612826.
Transfer history data appended for: https://www.transfermarkt.com/hamadi-al-ghaddioui/profil/spieler/193534.
Transfer history data appended for: https://www.transfermarkt.com/lars-stindl/profil/spieler/48298.
Transfer history data appended for: https://www.transfermarkt.com/marcus-thuram/profil/spieler/318528.
Transfer history data appended for: https://www.transfermarkt.com/hannes-wolf/profil/spieler/321070.
Transfer history data appended for: https://www.transfermarkt.com/laszlo-benes/profil/spieler/243188.
Transfer history data appended for: https://www.transfermarkt.com/rocco-reitz/profil/spieler/467434.
Transfer history data appended for: https://www.transfermarkt.com/tobias-sippel/profil/spieler/31653.
Transfer history data appended for: https://www.transfermarkt.com/max-grun/profil/spieler/32779.
Transfer history data appended for: https://www.transfermarkt.com/famana-quizera/profil/spieler/504089.
Transfer history data appended for: https://www.transfermarkt.com/kaan-kurt/profil/spieler/392154.
Transfer history data appended for: https://www.transfermarkt.com/yann-sommer/profil/spieler/42205.
Transfer history data appended for: https://www.transfermarkt.com/patrick-herrmann/profil/spieler/32711.
Transfer history data appended for: https://www.transfermarkt.com/jan-olschowsky/profil/spieler/455922.
Transfer history data appended for: https://www.transfermarkt.com/denis-zakaria/profil/spieler/334526.
Transfer history data appended for: https://www.transfermarkt.com/tony-jantschke/profil/spieler/47587.
Transfer history data appended for: https://www.transfermarkt.com/stefan-lainer/profil/spieler/85791.
Transfer history data appended for: https://www.transfermarkt.com/jordan-beyer/profil/spieler/403898.
Transfer history data appended for: https://www.transfermarkt.com/ramy-bensebaini/profil/spieler/284732.
Transfer history data appended for: https://www.transfermarkt.com/julio-villalba/profil/spieler/401717.
Transfer history data appended for: https://www.transfermarkt.com/andreas-poulsen/profil/spieler/345746.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-doucoure/profil/spieler/340480.
Transfer history data appended for: https://www.transfermarkt.com/alassane-plea/profil/spieler/167329.
Transfer history data appended for: https://www.transfermarkt.com/nico-elvedi/profil/spieler/192635.
Transfer history data appended for: https://www.transfermarkt.com/oscar-wendt/profil/spieler/19305.
Transfer history data appended for: https://www.transfermarkt.com/torben-musel/profil/spieler/368860.
Transfer history data appended for: https://www.transfermarkt.com/breel-embolo/profil/spieler/237662.
Transfer history data appended for: https://www.transfermarkt.com/matthias-ginter/profil/spieler/124502.

Transfer history data appended for: https://www.transfermarkt.com/ibrahima-traore/profil/spieler/47285.
Transfer history data appended for: https://www.transfermarkt.com/robin-quaison/profil/spieler/206542.
Transfer history data appended for: https://www.transfermarkt.com/luca-kilian/profil/spieler/384553.
Transfer history data appended for: https://www.transfermarkt.com/aaron-martin/profil/spieler/251878.
Transfer history data appended for: https://www.transfermarkt.com/karim-onisiwo/profil/spieler/119234.
Transfer history data appended for: https://www.transfermarkt.com/jeremiah-st-juste/profil/spieler/288253.
Transfer history data appended for: https://www.transfermarkt.com/leandro-barreiro/profil/spieler/357233.
Transfer history data appended for: https://www.transfermarkt.com/moussa-niakhate/profil/spieler/291200.
Transfer history data appended for: https://www.transfermarkt.com/danny-latza/profil/spieler/39025.
Transfer history data appended for: https://www.transfermarkt.com/robin-zentner/profil/spieler/160963.
Transfer history data appended for: https://www.transfermarkt.com/alexander-hack/profil/spieler/126281.
Transfer history data appended for: https://www.transfermarkt.com/phillipp-mwene/profil/spieler/127573.
Transfer history data appended for: https://www.transfermarkt.com/niklas-tauer/profil/spieler/470815.
Transfer history data appended for: https://www.transfermarkt.com/marius-liesegang/profil/spieler/337090.
Transfer history data appended for: https://www.transfermarkt.com/finn-dahmen/profil/spieler/251299.
Transfer history data appended for: https://www.transfermarkt.com/abass-issah/profil/spieler/482145.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-burkardt/profil/spieler/333647.
Transfer history data appended for: https://www.transfermarkt.com/merveille-papela/profil/spieler/405689.
Transfer history data appended for: https://www.transfermarkt.com/daniel-brosinski/profil/spieler/43984.
Transfer history data appended for: https://www.transfermarkt.com/paul-nebel/profil/spieler/503160.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-lavalee/profil/spieler/420890.
Transfer history data appended for: https://www.transfermarkt.com/omer-hanin/profil/spieler/211530.
Transfer history data appended for: https://www.transfermarkt.com/pierre-kunde-malong/profil/spieler/339829.
Transfer history data appended for: https://www.transfermarkt.com/jean-paul-boetius/profil/spieler/182574.
Transfer history data appended for: https://www.transfermarkt.com/marlon-mustapha/profil/spieler/532495.
Transfer history data appended for: https://www.transfermarkt.com/lucas-alario/profil/spieler/193782.
Transfer history data appended for: https://www.transfermarkt.com/lennart-grill/profil/spieler/309397.
Transfer history data appended for: https://www.transfermarkt.com/charles-aranguiz/profil/spieler/89701.
Transfer history data appended for: https://www.transfermarkt.com/leon-bailey/profil/spieler/387626.
Transfer history data appended for: https://www.transfermarkt.com/patrik-schick/profil/spieler/242086.
Transfer history data appended for: https://www.transfermarkt.com/edmond-tapsoba/profil/spieler/564545.
Transfer history data appended for: https://www.transfermarkt.com/emrehan-gedikli/profil/spieler/580276.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-dragovic/profil/spieler/59032.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-tah/profil/spieler/196357.
Transfer history data appended for: https://www.transfermarkt.com/lars-bender/profil/spieler/30059.
Transfer history data appended for: https://www.transfermarkt.com/lukas-hradecky/profil/spieler/48015.
Transfer history data appended for: https://www.transfermarkt.com/exequiel-palacios/profil/spieler/401578.
Transfer history data appended for: https://www.transfermarkt.com/cem-turkmen/profil/spieler/530157.
Transfer history data appended for: https://www.transfermarkt.com/paulinho/profil/spieler/428791.
Transfer history data appended for: https://www.transfermarkt.com/florian-wirtz/profil/spieler/598577.
Transfer history data appended for: https://www.transfermarkt.com/santiago-arias/profil/spieler/120443.
Transfer history data appended for: https://www.transfermarkt.com/kerem-demirbay/profil/spieler/125858.
Transfer history data appended for: https://www.transfermarkt.com/moussa-diaby/profil/spieler/395516.
Transfer history data appended for: https://www.transfermarkt.com/wendell/profil/spieler/228433.
Transfer history data appended for: https://www.transfermarkt.com/tin-jedvaj/profil/spieler/206386.
Transfer history data appended for: https://www.transfermarkt.com/mitchell-weiser/profil/spieler/119211.
Transfer history data appended for: https://www.transfermarkt.com/julian-baumgartlinger/profil/spieler/34787.
Transfer history data appended for: https://www.transfermarkt.com/niklas-lomb/profil/spieler/85543.
Transfer history data appended for: https://www.transfermarkt.com/daley-sinkgraven/profil/spieler/215099.
Transfer history data appended for: https://www.transfermarkt.com/nadiem-amiri/profil/spieler/232454.
Transfer history data appended for: https://www.transfermarkt.com/sven-bender/profil/spieler/29993.
Transfer history data appended for: https://www.transfermarkt.com/pavao-pervan/profil/spieler/51977.
Transfer history data appended for: https://www.transfermarkt.com/josuha-guilavogui/profil/spieler/93704.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-bialek/profil/spieler/535551.
Transfer history data appended for: https://www.transfermarkt.com/felix-klaus/profil/spieler/89591.
Transfer history data appended for: https://www.transfermarkt.com/yunus-malli/profil/spieler/85352.
Transfer history data appended for: https://www.transfermarkt.com/yannick-gerhardt/profil/spieler/119277.
Transfer history data appended for: https://www.transfermarkt.com/maxence-lacroix/profil/spieler/434224.
Transfer history data appended for: https://www.transfermarkt.com/marin-pongracic/profil/spieler/282144.
Transfer history data appended for: https://www.transfermarkt.com/ridle-baku/profil/spieler/327251.
Transfer history data appended for: https://www.transfermarkt.com/wout-weghorst/profil/spieler/228645.
Transfer history data appended for: https://www.transfermarkt.com/renato-steffen/profil/spieler/194638.
Transfer history data appended for: https://www.transfermarkt.com/xaver-schlager/profil/spieler/223979.
Transfer history data appended for: https://www.transfermarkt.com/paulo-otavio/profil/spieler/221611.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-philipp/profil/spieler/143891.
Transfer history data appended for: https://www.transfermarkt.com/jerome-roussillon/profil/spieler/127076.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-arnold/profil/spieler/117674.
Transfer history data appended for: https://www.transfermarkt.com/niklas-klinger/profil/spieler/192268.
Transfer history data appended for: https://www.transfermarkt.com/omar-marmoush/profil/spieler/445939.
Transfer history data appended for: https://www.transfermarkt.com/john-anthony-brooks/profil/spieler/124732.
Transfer history data appended for: https://www.transfermarkt.com/lino-kasten/profil/spieler/441994.
Transfer history data appended for: https://www.transfermarkt.com/joao-victor/profil/spieler/381724.
Transfer history data appended for: https://www.transfermarkt.com/josip-brekalo/profil/spieler/293169.
Transfer history data appended for: https://www.transfermarkt.com/william/profil/spieler/341710.
Transfer history data appended for: https://www.transfermarkt.com/eduard-lowen/profil/spieler/260655.
Transfer history data appended for: https://www.transfermarkt.com/deyovaisio-zeefuik/profil/spieler/338032.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-darida/profil/spieler/179643.
Transfer history data appended for: https://www.transfermarkt.com/marvin-plattenhardt/profil/spieler/89592.
Transfer history data appended for: https://www.transfermarkt.com/nils-korber/profil/spieler/241974.
Transfer history data appended for: https://www.transfermarkt.com/jordan-torunarigha/profil/spieler/227110.

Transfer history data appended for: https://www.transfermarkt.com/santiago-ascacibar/profil/spieler/423436.
Transfer history data appended for: https://www.transfermarkt.com/lukas-klunter/profil/spieler/282577.
Transfer history data appended for: https://www.transfermarkt.com/dedryck-boyata/profil/spieler/88262.
Transfer history data appended for: https://www.transfermarkt.com/javairo-dilrosun/profil/spieler/315125.
Transfer history data appended for: https://www.transfermarkt.com/niklas-stark/profil/spieler/162434.
Transfer history data appended for: https://www.transfermarkt.com/jessic-ngankam/profil/spieler/448177.
Transfer history data appended for: https://www.transfermarkt.com/lucas-tousart/profil/spieler/353948.
Transfer history data appended for: https://www.transfermarkt.com/marton-dardai/profil/spieler/432281.
Transfer history data appended for: https://www.transfermarkt.com/omar-alderete/profil/spieler/353032.
Transfer history data appended for: https://www.transfermarkt.com/krzysztof-piatek/profil/spieler/327757.
Transfer history data appended for: https://www.transfermarkt.com/daishawn-redan/profil/spieler/361081.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-mittelstadt/profil/spieler/282660.
Transfer history data appended for: https://www.transfermarkt.com/matteo-guendouzi/profil/spieler/465830.
Transfer history data appended for: https://www.transfermarkt.com/rune-jarstein/profil/spieler/24112.
Transfer history data appended for: https://www.transfermarkt.com/matheus-cunha/profil/spieler/517894.
Transfer history data appended for: https://www.transfermarkt.com/alexander-schwolow/profil/spieler/93763.
Transfer history data appended for: https://www.transfermarkt.com/luca-netz/profil/spieler/524285.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-thalhammer/profil/spieler/388316.
Transfer history data appended for: https://www.transfermarkt.com/moritz-schulze/profil/spieler/569681.
Transfer history data appended for: https://www.transfermarkt.com/aristote-nkaka/profil/spieler/383372.
Transfer history data appended for: https://www.transfermarkt.com/jannik-huth/profil/spieler/160954.
Transfer history data appended for: https://www.transfermarkt.com/uwe-hunemeier/profil/spieler/10503.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-vasiliadis/profil/spieler/333516.
Transfer history data appended for: https://www.transfermarkt.com/christian-strohdiek/profil/spieler/48081.
Transfer history data appended for: https://www.transfermarkt.com/svante-ingelsson/profil/spieler/321079.
Transfer history data appended for: https://www.transfermarkt.com/marcel-correia/profil/spieler/55597.
Transfer history data appended for: https://www.transfermarkt.com/frederic-ananou/profil/spieler/240263.
Transfer history data appended for: https://www.transfermarkt.com/adrian-oeynhausen/profil/spieler/598281.
Transfer history data appended for: https://www.transfermarkt.com/kai-proger/profil/spieler/223572.
Transfer history data appended for: https://www.transfermarkt.com/chris-fuhrich/profil/spieler/272278.
Transfer history data appended for: https://www.transfermarkt.com/jayden-bennetts/profil/spieler/646997.
Transfer history data appended for: https://www.transfermarkt.com/johannes-dorfler/profil/spieler/329324.
Transfer history data appended for: https://www.transfermarkt.com/sven-michel/profil/spieler/186988.
Transfer history data appended for: https://www.transfermarkt.com/chima-okoroji/profil/spieler/284035.
Transfer history data appended for: https://www.transfermarkt.com/ron-schallenberg/profil/spieler/332392.
Transfer history data appended for: https://www.transfermarkt.com/julian-justvan/profil/spieler/324861.
Transfer history data appended for: https://www.transfermarkt.com/streli-mamba/profil/spieler/161060.
Transfer history data appended for: https://www.transfermarkt.com/leopold-zingerle/profil/spieler/160971.
Transfer history data appended for: https://www.transfermarkt.com/jamilu-collins/profil/spieler/254934.
Transfer history data appended for: https://www.transfermarkt.com/dennis-jastrzembski/profil/spieler/358870.
Transfer history data appended for: https://www.transfermarkt.com/dennis-srbeny/profil/spieler/159239.
Transfer history data appended for: https://www.transfermarkt.com/prince-osei-owusu/profil/spieler/207593.
Transfer history data appended for: https://www.transfermarkt.com/christopher-antwi-adjei/profil/spieler/289182.
Transfer history data appended for: https://www.transfermarkt.com/jesse-edem-tugbenyo/profil/spieler/565118.
Transfer history data appended for: https://www.transfermarkt.com/antony-evans/profil/spieler/374283.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-schonlau/profil/spieler/213751.
Transfer history data appended for: https://www.transfermarkt.com/sonny-kittel/profil/spieler/78950.
Transfer history data appended for: https://www.transfermarkt.com/amadou-onana/profil/spieler/485706.
Transfer history data appended for: https://www.transfermarkt.com/khaled-narey/profil/spieler/153664.
Transfer history data appended for: https://www.transfermarkt.com/bakery-jatta/profil/spieler/415194.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-dudziak/profil/spieler/147359.
Transfer history data appended for: https://www.transfermarkt.com/daniel-heuer-fernandes/profil/spieler/84993.
Transfer history data appended for: https://www.transfermarkt.com/toni-leistner/profil/spieler/86916.
Transfer history data appended for: https://www.transfermarkt.com/tim-leibold/profil/spieler/185699.
Transfer history data appended for: https://www.transfermarkt.com/rick-van-drongelen/profil/spieler/354340.
Transfer history data appended for: https://www.transfermarkt.com/stephan-ambrosius/profil/spieler/327536.
Transfer history data appended for: https://www.transfermarkt.com/josha-vagnoman/profil/spieler/448258.
Transfer history data appended for: https://www.transfermarkt.com/sven-ulreich/profil/spieler/40680.
Transfer history data appended for: https://www.transfermarkt.com/gideon-jung/profil/spieler/247661.
Transfer history data appended for: https://www.transfermarkt.com/moritz-heyer/profil/spieler/193025.
Transfer history data appended for: https://www.transfermarkt.com/klaus-gjasula/profil/spieler/57598.
Transfer history data appended for: https://www.transfermarkt.com/lukas-hinterseer/profil/spieler/59054.
Transfer history data appended for: https://www.transfermarkt.com/david-kinsombi/profil/spieler/196834.
Transfer history data appended for: https://www.transfermarkt.com/manuel-wintzheimer/profil/spieler/296429.
Transfer history data appended for: https://www.transfermarkt.com/bobby-wood/profil/spieler/72519.
Transfer history data appended for: https://www.transfermarkt.com/jan-gyamerah/profil/spieler/192840.
Transfer history data appended for: https://www.transfermarkt.com/aaron-hunt/profil/spieler/4687.
Transfer history data appended for: https://www.transfermarkt.com/xavier-amaechi/profil/spieler/433185.
Transfer history data appended for: https://www.transfermarkt.com/tom-mickel/profil/spieler/44607.
Transfer history data appended for: https://www.transfermarkt.com/jonas-david/profil/spieler/431848.
Transfer history data appended for: https://www.transfermarkt.com/dominic-baumann/profil/spieler/152431.
Transfer history data appended for: https://www.transfermarkt.com/keanu-staude/profil/spieler/264310.
Transfer history data appended for: https://www.transfermarkt.com/robert-herrmann/profil/spieler/124338.
Transfer history data appended for: https://www.transfermarkt.com/hendrik-bonmann/profil/spieler/104220.
Transfer history data appended for: https://www.transfermarkt.com/fabian-giefer/profil/spieler/53408.
Transfer history data appended for: https://www.transfermarkt.com/arne-feick/profil/spieler/38609.
Transfer history data appended for: https://www.transfermarkt.com/lars-dietz/profil/spieler/224513.
Transfer history data appended for: https://www.transfermarkt.com/eric-verstappen/profil/spieler/187203.
Transfer history data appended for: https://www.transfermarkt.com/nzuzi-toko/profil/spieler/68004.

Transfer history data appended for: https://www.transfermarkt.com/douglas/profil/spieler/64590.
Transfer history data appended for: https://www.transfermarkt.com/ridge-munsy/profil/spieler/51497.
Transfer history data appended for: https://www.transfermarkt.com/saliou-sane/profil/spieler/94256.
Transfer history data appended for: https://www.transfermarkt.com/mitja-lotric/profil/spieler/149820.
Transfer history data appended for: https://www.transfermarkt.com/florian-flecker/profil/spieler/272159.
Transfer history data appended for: https://www.transfermarkt.com/umut-unlu/profil/spieler/795656.
Transfer history data appended for: https://www.transfermarkt.com/luke-hemmerich/profil/spieler/300502.
Transfer history data appended for: https://www.transfermarkt.com/dominik-meisel/profil/spieler/380286.
Transfer history data appended for: https://www.transfermarkt.com/hendrik-hansen/profil/spieler/158049.
Transfer history data appended for: https://www.transfermarkt.com/frank-ronstadt/profil/spieler/270027.
Transfer history data appended for: https://www.transfermarkt.com/chris-david/profil/spieler/187285.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-nikolov/profil/spieler/475431.
Transfer history data appended for: https://www.transfermarkt.com/daniel-hagele/profil/spieler/101168.
Transfer history data appended for: https://www.transfermarkt.com/david-kopacz/profil/spieler/317739.
Transfer history data appended for: https://www.transfermarkt.com/lion-schweers/profil/spieler/333942.
Transfer history data appended for: https://www.transfermarkt.com/leroy-kwadwo/profil/spieler/358903.
Transfer history data appended for: https://www.transfermarkt.com/tobias-kraulich/profil/spieler/405784.
Transfer history data appended for: https://www.transfermarkt.com/patrick-sontheimer/profil/spieler/296897.
Transfer history data appended for: https://www.transfermarkt.com/niklas-hoffmann/profil/spieler/282104.
Transfer history data appended for: https://www.transfermarkt.com/tom-weilandt/profil/spieler/93837.
Transfer history data appended for: https://www.transfermarkt.com/lars-holtkamp/profil/spieler/452224.
Transfer history data appended for: https://www.transfermarkt.com/saulo-decarli/profil/spieler/154578.
Transfer history data appended for: https://www.transfermarkt.com/thomas-eisfeld/profil/spieler/86643.
Transfer history data appended for: https://www.transfermarkt.com/silvere-ganvoula/profil/spieler/312819.
Transfer history data appended for: https://www.transfermarkt.com/cristian-gamboa/profil/spieler/121686.
Transfer history data appended for: https://www.transfermarkt.com/anthony-losilla/profil/spieler/111266.
Transfer history data appended for: https://www.transfermarkt.com/moritz-romling/profil/spieler/452222.
Transfer history data appended for: https://www.transfermarkt.com/armel-bella-kotchap/profil/spieler/467563.
Transfer history data appended for: https://www.transfermarkt.com/stelios-kokovas/profil/spieler/530166.
Transfer history data appended for: https://www.transfermarkt.com/herbert-bockhorn/profil/spieler/186477.
Transfer history data appended for: https://www.transfermarkt.com/manuel-riemann/profil/spieler/40792.
Transfer history data appended for: https://www.transfermarkt.com/milos-pantovic/profil/spieler/232144.
Transfer history data appended for: https://www.transfermarkt.com/robert-tesche/profil/spieler/41458.
Transfer history data appended for: https://www.transfermarkt.com/gerrit-holtmann/profil/spieler/190289.
Transfer history data appended for: https://www.transfermarkt.com/erhan-masovic/profil/spieler/343959.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-maier/profil/spieler/126285.
Transfer history data appended for: https://www.transfermarkt.com/baris-ekincier/profil/spieler/383223.
Transfer history data appended for: https://www.transfermarkt.com/simon-zoller/profil/spieler/79967.
Transfer history data appended for: https://www.transfermarkt.com/paul-grave/profil/spieler/452192.
Transfer history data appended for: https://www.transfermarkt.com/soma-novothny/profil/spieler/148824.
Transfer history data appended for: https://www.transfermarkt.com/tarsis-bonga/profil/spieler/283140.
Transfer history data appended for: https://www.transfermarkt.com/danilo-soares/profil/spieler/154396.
Transfer history data appended for: https://www.transfermarkt.com/vasilios-lampropoulos/profil/spieler/63489.
Transfer history data appended for: https://www.transfermarkt.com/raman-chibsah/profil/spieler/199633.
Transfer history data appended for: https://www.transfermarkt.com/maxim-leitsch/profil/spieler/334207.
Transfer history data appended for: https://www.transfermarkt.com/niko-kijewski/profil/spieler/193032.
Transfer history data appended for: https://www.transfermarkt.com/robin-ziegele/profil/spieler/280589.
Transfer history data appended for: https://www.transfermarkt.com/marcel-engelhardt/profil/spieler/124080.
Transfer history data appended for: https://www.transfermarkt.com/yassin-ben-balla/profil/spieler/391379.
Transfer history data appended for: https://www.transfermarkt.com/dominik-wydra/profil/spieler/120199.
Transfer history data appended for: https://www.transfermarkt.com/jasmin-fejzic/profil/spieler/19471.
Transfer history data appended for: https://www.transfermarkt.com/nick-proschwitz/profil/spieler/31535.
Transfer history data appended for: https://www.transfermarkt.com/njegos-kupusovic/profil/spieler/581048.
Transfer history data appended for: https://www.transfermarkt.com/patrick-kammerbauer/profil/spieler/227087.
Transfer history data appended for: https://www.transfermarkt.com/leandro-putaro/profil/spieler/237732.
Transfer history data appended for: https://www.transfermarkt.com/jannis-nikolaou/profil/spieler/93649.
Transfer history data appended for: https://www.transfermarkt.com/fabio-kaufmann/profil/spieler/160980.
Transfer history data appended for: https://www.transfermarkt.com/danilo-wiebe/profil/spieler/119292.
Transfer history data appended for: https://www.transfermarkt.com/lasse-schluter/profil/spieler/94976.
Transfer history data appended for: https://www.transfermarkt.com/matthias-heiland/profil/spieler/471895.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-kessel/profil/spieler/40116.
Transfer history data appended for: https://www.transfermarkt.com/yari-otto/profil/spieler/316590.
Transfer history data appended for: https://www.transfermarkt.com/marcel-bar/profil/spieler/154853.
Transfer history data appended for: https://www.transfermarkt.com/iba-may/profil/spieler/335954.
Transfer history data appended for: https://www.transfermarkt.com/michael-schultz/profil/spieler/126424.
Transfer history data appended for: https://www.transfermarkt.com/manuel-schwenk/profil/spieler/94641.
Transfer history data appended for: https://www.transfermarkt.com/felix-dornebusch/profil/spieler/119034.
Transfer history data appended for: https://www.transfermarkt.com/leon-burger/profil/spieler/369896.
Transfer history data appended for: https://www.transfermarkt.com/nico-klass/profil/spieler/232936.
Transfer history data appended for: https://www.transfermarkt.com/felix-burmeister/profil/spieler/56112.
Transfer history data appended for: https://www.transfermarkt.com/philipp-riese/profil/spieler/77630.
Transfer history data appended for: https://www.transfermarkt.com/clemens-fandrich/profil/spieler/80007.
Transfer history data appended for: https://www.transfermarkt.com/soren-gonther/profil/spieler/20879.
Transfer history data appended for: https://www.transfermarkt.com/louis-samson/profil/spieler/188931.
Transfer history data appended for: https://www.transfermarkt.com/jan-hochscheidt/profil/spieler/34232.
Transfer history data appended for: https://www.transfermarkt.com/florian-kruger/profil/spieler/317740.
Transfer history data appended for: https://www.transfermarkt.com/malcolm-cacutalua/profil/spieler/123558.
Transfer history data appended for: https://www.transfermarkt.com/ben-zolinski/profil/spieler/93841.
Transfer history data appended for: https://www.transfermarkt.com/steve-breitkreuz/profil/spieler/82735.
Transfer history data appended for: https://www.transfermarkt.com/gaetan-bussmann/profil/spieler/127177.

Transfer history data appended for: https://www.transfermarkt.com/florian-ballas/profil/spieler/110885.
Transfer history data appended for: https://www.transfermarkt.com/kevin-harr/profil/spieler/443853.
Transfer history data appended for: https://www.transfermarkt.com/niklas-jeck/profil/spieler/449150.
Transfer history data appended for: https://www.transfermarkt.com/john-patrick-strauss/profil/spieler/237113.
Transfer history data appended for: https://www.transfermarkt.com/jean-marie-plath/profil/spieler/523206.
Transfer history data appended for: https://www.transfermarkt.com/sascha-hartel/profil/spieler/346701.
Transfer history data appended for: https://www.transfermarkt.com/pascal-testroet/profil/spieler/53521.
Transfer history data appended for: https://www.transfermarkt.com/erik-majetschak/profil/spieler/337083.
Transfer history data appended for: https://www.transfermarkt.com/philipp-klewin/profil/spieler/94120.
Transfer history data appended for: https://www.transfermarkt.com/tom-baumgart/profil/spieler/422052.
Transfer history data appended for: https://www.transfermarkt.com/calogero-rizzuto/profil/spieler/93753.
Transfer history data appended for: https://www.transfermarkt.com/martin-mannel/profil/spieler/39096.
Transfer history data appended for: https://www.transfermarkt.com/fabian-kalig/profil/spieler/153184.
Transfer history data appended for: https://www.transfermarkt.com/antonio-jonjic/profil/spieler/380263.
Transfer history data appended for: https://www.transfermarkt.com/ognjen-gnjatic/profil/spieler/190811.
Transfer history data appended for: https://www.transfermarkt.com/dimitrij-nazarov/profil/spieler/55608.
Transfer history data appended for: https://www.transfermarkt.com/edgar-prib/profil/spieler/60028.
Transfer history data appended for: https://www.transfermarkt.com/brandon-borrello/profil/spieler/293592.
Transfer history data appended for: https://www.transfermarkt.com/dawid-kownacki/profil/spieler/208167.
Transfer history data appended for: https://www.transfermarkt.com/christoph-klarer/profil/spieler/346849.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-iyoha/profil/spieler/314245.
Transfer history data appended for: https://www.transfermarkt.com/florian-kastenmeier/profil/spieler/255294.
Transfer history data appended for: https://www.transfermarkt.com/gokhan-gul/profil/spieler/269171.
Transfer history data appended for: https://www.transfermarkt.com/andre-hoffmann/profil/spieler/85164.
Transfer history data appended for: https://www.transfermarkt.com/jamil-siebert/profil/spieler/604113.
Transfer history data appended for: https://www.transfermarkt.com/shinta-appelkamp/profil/spieler/452121.
Transfer history data appended for: https://www.transfermarkt.com/raphael-wolf/profil/spieler/39306.
Transfer history data appended for: https://www.transfermarkt.com/florian-hartherz/profil/spieler/93571.
Transfer history data appended for: https://www.transfermarkt.com/anton-mitryushkin/profil/spieler/260677.
Transfer history data appended for: https://www.transfermarkt.com/alfredo-morales/profil/spieler/58500.
Transfer history data appended for: https://www.transfermarkt.com/nikell-touglo/profil/spieler/453854.
Transfer history data appended for: https://www.transfermarkt.com/adam-bodzek/profil/spieler/20778.
Transfer history data appended for: https://www.transfermarkt.com/dennis-gorka/profil/spieler/549490.
Transfer history data appended for: https://www.transfermarkt.com/marcel-sobottka/profil/spieler/119044.
Transfer history data appended for: https://www.transfermarkt.com/jakub-piotrowski/profil/spieler/377243.
Transfer history data appended for: https://www.transfermarkt.com/kenan-karaman/profil/spieler/119557.
Transfer history data appended for: https://www.transfermarkt.com/luka-krajnc/profil/spieler/138584.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-peterson/profil/spieler/186704.
Transfer history data appended for: https://www.transfermarkt.com/thomas-pledl/profil/spieler/131561.
Transfer history data appended for: https://www.transfermarkt.com/kelvin-ofori/profil/spieler/687035.
Transfer history data appended for: https://www.transfermarkt.com/linton-maina/profil/spieler/335103.
Transfer history data appended for: https://www.transfermarkt.com/sei-muroya/profil/spieler/188910.
Transfer history data appended for: https://www.transfermarkt.com/mick-gudra/profil/spieler/406610.
Transfer history data appended for: https://www.transfermarkt.com/simon-falette/profil/spieler/170927.
Transfer history data appended for: https://www.transfermarkt.com/franck-evina/profil/spieler/336331.
Transfer history data appended for: https://www.transfermarkt.com/marlon-sundermann/profil/spieler/333901.
Transfer history data appended for: https://www.transfermarkt.com/hendrik-weydandt/profil/spieler/330223.
Transfer history data appended for: https://www.transfermarkt.com/michael-esser/profil/spieler/61989.
Transfer history data appended for: https://www.transfermarkt.com/marc-lamti/profil/spieler/452069.
Transfer history data appended for: https://www.transfermarkt.com/simon-stehle/profil/spieler/557205.
Transfer history data appended for: https://www.transfermarkt.com/timo-hubers/profil/spieler/236981.
Transfer history data appended for: https://www.transfermarkt.com/genki-haraguchi/profil/spieler/79377.
Transfer history data appended for: https://www.transfermarkt.com/jaka-bijol/profil/spieler/371851.
Transfer history data appended for: https://www.transfermarkt.com/philipp-ochs/profil/spieler/207592.
Transfer history data appended for: https://www.transfermarkt.com/mike-frantz/profil/spieler/30942.
Transfer history data appended for: https://www.transfermarkt.com/niklas-hult/profil/spieler/113039.
Transfer history data appended for: https://www.transfermarkt.com/niklas-tarnat/profil/spieler/337025.
Transfer history data appended for: https://www.transfermarkt.com/florent-muslija/profil/spieler/337036.
Transfer history data appended for: https://www.transfermarkt.com/martin-hansen/profil/spieler/45601.
Transfer history data appended for: https://www.transfermarkt.com/kingsley-schindler/profil/spieler/153678.
Transfer history data appended for: https://www.transfermarkt.com/valmir-sulejmani/profil/spieler/193050.
Transfer history data appended for: https://www.transfermarkt.com/michael-ratajczak/profil/spieler/1257.
Transfer history data appended for: https://www.transfermarkt.com/baris-basdas/profil/spieler/55501.
Transfer history data appended for: https://www.transfermarkt.com/dominik-kaiser/profil/spieler/52200.
Transfer history data appended for: https://www.transfermarkt.com/ulrich-bapoh/profil/spieler/331638.
Transfer history data appended for: https://www.transfermarkt.com/konstantin-engel/profil/spieler/42318.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-klaas/profil/spieler/378424.
Transfer history data appended for: https://www.transfermarkt.com/bryan-henning/profil/spieler/202515.
Transfer history data appended for: https://www.transfermarkt.com/philipp-kuhn/profil/spieler/124187.
Transfer history data appended for: https://www.transfermarkt.com/niklas-schmidt/profil/spieler/275249.
Transfer history data appended for: https://www.transfermarkt.com/marc-heider/profil/spieler/31968.
Transfer history data appended for: https://www.transfermarkt.com/moritz-nicolas/profil/spieler/284270.
Transfer history data appended for: https://www.transfermarkt.com/timo-beermann/profil/spieler/88430.
Transfer history data appended for: https://www.transfermarkt.com/ulrich-taffertshofer/profil/spieler/93557.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-kerk/profil/spieler/124517.
Transfer history data appended for: https://www.transfermarkt.com/sven-kohler/profil/spieler/202604.
Transfer history data appended for: https://www.transfermarkt.com/ludovit-reis/profil/spieler/490884.
Transfer history data appended for: https://www.transfermarkt.com/lukas-gugganig/profil/spieler/164142.
Transfer history data appended for: https://www.transfermarkt.com/david-blacha/profil/spieler/38378.
Transfer history data appended for: https://www.transfermarkt.com/marc-auge/profil/spieler/607499.

Transfer history data appended for: https://www.transfermarkt.com/maurice-multhaup/profil/spieler/187496.
Transfer history data appended for: https://www.transfermarkt.com/laurenz-beckemeyer/profil/spieler/400514.
Transfer history data appended for: https://www.transfermarkt.com/nico-granatowski/profil/spieler/45734.
Transfer history data appended for: https://www.transfermarkt.com/etienne-amenyido/profil/spieler/271103.
Transfer history data appended for: https://www.transfermarkt.com/kevin-wolze/profil/spieler/42749.
Transfer history data appended for: https://www.transfermarkt.com/maurice-trapp/profil/spieler/84456.
Transfer history data appended for: https://www.transfermarkt.com/christian-santos/profil/spieler/50487.
Transfer history data appended for: https://www.transfermarkt.com/adam-susac/profil/spieler/69012.
Transfer history data appended for: https://www.transfermarkt.com/ken-reichel/profil/spieler/16831.
Transfer history data appended for: https://www.transfermarkt.com/david-buchholz/profil/spieler/22419.
Transfer history data appended for: https://www.transfermarkt.com/tim-moller/profil/spieler/393519.
Transfer history data appended for: https://www.transfermarkt.com/bashkim-ajdini/profil/spieler/189142.
Transfer history data appended for: https://www.transfermarkt.com/luc-ihorst/profil/spieler/447730.
Transfer history data appended for: https://www.transfermarkt.com/marvin-rittmuller/profil/spieler/307845.
Transfer history data appended for: https://www.transfermarkt.com/florian-pick/profil/spieler/191359.
Transfer history data appended for: https://www.transfermarkt.com/gianni-mollo/profil/spieler/422267.
Transfer history data appended for: https://www.transfermarkt.com/jonas-fohrenbach/profil/spieler/192169.
Transfer history data appended for: https://www.transfermarkt.com/tobias-mohr/profil/spieler/153661.
Transfer history data appended for: https://www.transfermarkt.com/robert-leipertz/profil/spieler/119120.
Transfer history data appended for: https://www.transfermarkt.com/andreas-geipl/profil/spieler/93563.
Transfer history data appended for: https://www.transfermarkt.com/diant-ramaj/profil/spieler/448705.
Transfer history data appended for: https://www.transfermarkt.com/merveille-biankadi/profil/spieler/196843.
Transfer history data appended for: https://www.transfermarkt.com/kevin-ibrahim/profil/spieler/460384.
Transfer history data appended for: https://www.transfermarkt.com/patrick-schmidt/profil/spieler/124416.
Transfer history data appended for: https://www.transfermarkt.com/konstantin-kerschbaumer/profil/spieler/81694.
Transfer history data appended for: https://www.transfermarkt.com/patrick-mainka/profil/spieler/133731.
Transfer history data appended for: https://www.transfermarkt.com/marc-schnatterer/profil/spieler/18684.
Transfer history data appended for: https://www.transfermarkt.com/kevin-muller/profil/spieler/43824.
Transfer history data appended for: https://www.transfermarkt.com/oliver-steurer/profil/spieler/156710.
Transfer history data appended for: https://www.transfermarkt.com/melvin-ramusovic/profil/spieler/478423.
Transfer history data appended for: https://www.transfermarkt.com/vitus-eicher/profil/spieler/57796.
Transfer history data appended for: https://www.transfermarkt.com/kevin-sessa/profil/spieler/448028.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-thiel/profil/spieler/120301.
Transfer history data appended for: https://www.transfermarkt.com/christian-kuhlwetter/profil/spieler/184204.
Transfer history data appended for: https://www.transfermarkt.com/julian-stark/profil/spieler/521174.
Transfer history data appended for: https://www.transfermarkt.com/denis-thomalla/profil/spieler/94030.
Transfer history data appended for: https://www.transfermarkt.com/oliver-husing/profil/spieler/109436.
Transfer history data appended for: https://www.transfermarkt.com/stefan-schimmer/profil/spieler/394033.
Transfer history data appended for: https://www.transfermarkt.com/jan-schoppner/profil/spieler/581357.
Transfer history data appended for: https://www.transfermarkt.com/norman-theuerkauf/profil/spieler/31599.
Transfer history data appended for: https://www.transfermarkt.com/sascha-burchert/profil/spieler/36898.
Transfer history data appended for: https://www.transfermarkt.com/abdourahmane-barry/profil/spieler/536472.
Transfer history data appended for: https://www.transfermarkt.com/havard-nielsen/profil/spieler/136181.
Transfer history data appended for: https://www.transfermarkt.com/emil-berggreen/profil/spieler/234375.
Transfer history data appended for: https://www.transfermarkt.com/simon-asta/profil/spieler/392131.
Transfer history data appended for: https://www.transfermarkt.com/paul-jaeckel/profil/spieler/284248.
Transfer history data appended for: https://www.transfermarkt.com/marius-funk/profil/spieler/170517.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-bauer/profil/spieler/388363.
Transfer history data appended for: https://www.transfermarkt.com/robin-kehr/profil/spieler/334998.
Transfer history data appended for: https://www.transfermarkt.com/marco-meyerhofer/profil/spieler/196084.
Transfer history data appended for: https://www.transfermarkt.com/dickson-abiama/profil/spieler/596813.
Transfer history data appended for: https://www.transfermarkt.com/leon-schaffran/profil/spieler/291383.
Transfer history data appended for: https://www.transfermarkt.com/david-raum/profil/spieler/318204.
Transfer history data appended for: https://www.transfermarkt.com/mergim-mavraj/profil/spieler/38267.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-ernst/profil/spieler/108198.
Transfer history data appended for: https://www.transfermarkt.com/jamie-leweling/profil/spieler/518505.
Transfer history data appended for: https://www.transfermarkt.com/anton-stach/profil/spieler/344069.
Transfer history data appended for: https://www.transfermarkt.com/jae-sung-lee/profil/spieler/314398.
Transfer history data appended for: https://www.transfermarkt.com/johannes-van-den-bergh/profil/spieler/31218.
Transfer history data appended for: https://www.transfermarkt.com/ahmet-arslan/profil/spieler/209686.
Transfer history data appended for: https://www.transfermarkt.com/makana-baku/profil/spieler/336974.
Transfer history data appended for: https://www.transfermarkt.com/joshua-mees/profil/spieler/196815.
Transfer history data appended for: https://www.transfermarkt.com/finn-porath/profil/spieler/241307.
Transfer history data appended for: https://www.transfermarkt.com/jonas-meffert/profil/spieler/107574.
Transfer history data appended for: https://www.transfermarkt.com/fin-bartels/profil/spieler/36207.
Transfer history data appended for: https://www.transfermarkt.com/dominik-reimann/profil/spieler/238722.
Transfer history data appended for: https://www.transfermarkt.com/jonas-sterner/profil/spieler/528619.
Transfer history data appended for: https://www.transfermarkt.com/noah-awuku/profil/spieler/335924.
Transfer history data appended for: https://www.transfermarkt.com/stefan-thesker/profil/spieler/175709.
Transfer history data appended for: https://www.transfermarkt.com/lion-lauberbach/profil/spieler/307800.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-girth/profil/spieler/151111.
Transfer history data appended for: https://www.transfermarkt.com/phil-neumann/profil/spieler/265176.
Transfer history data appended for: https://www.transfermarkt.com/marco-komenda/profil/spieler/335631.
Transfer history data appended for: https://www.transfermarkt.com/thomas-dahne/profil/spieler/115979.
Transfer history data appended for: https://www.transfermarkt.com/alexander-muhling/profil/spieler/85298.
Transfer history data appended for: https://www.transfermarkt.com/simon-lorenz/profil/spieler/278459.
Transfer history data appended for: https://www.transfermarkt.com/niklas-hauptmann/profil/spieler/205544.
Transfer history data appended for: https://www.transfermarkt.com/jannik-dehm/profil/spieler/211671.
Transfer history data appended for: https://www.transfermarkt.com/hauke-wahl/profil/spieler/154147.
Transfer history data appended for: https://www.transfermarkt.com/ioannis-gelios/profil/spieler/156676.

Transfer history data appended for: https://www.transfermarkt.com/janni-serra/profil/spieler/294534.
Transfer history data appended for: https://www.transfermarkt.com/markus-palionis/profil/spieler/32564.
Transfer history data appended for: https://www.transfermarkt.com/tom-baack/profil/spieler/331637.
Transfer history data appended for: https://www.transfermarkt.com/charalampos-makridis/profil/spieler/414318.
Transfer history data appended for: https://www.transfermarkt.com/kaan-caliskaner/profil/spieler/561647.
Transfer history data appended for: https://www.transfermarkt.com/alexander-weidinger/profil/spieler/255633.
Transfer history data appended for: https://www.transfermarkt.com/aaron-opoku/profil/spieler/344063.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-nachreiner/profil/spieler/109987.
Transfer history data appended for: https://www.transfermarkt.com/christoph-moritz/profil/spieler/55519.
Transfer history data appended for: https://www.transfermarkt.com/jann-george/profil/spieler/93532.
Transfer history data appended for: https://www.transfermarkt.com/jan-niklas-beste/profil/spieler/342967.
Transfer history data appended for: https://www.transfermarkt.com/elias-herzig/profil/spieler/591669.
Transfer history data appended for: https://www.transfermarkt.com/andreas-albers/profil/spieler/88647.
Transfer history data appended for: https://www.transfermarkt.com/scott-kennedy/profil/spieler/418300.
Transfer history data appended for: https://www.transfermarkt.com/erik-wekesser/profil/spieler/260657.
Transfer history data appended for: https://www.transfermarkt.com/federico-palacios/profil/spieler/146096.
Transfer history data appended for: https://www.transfermarkt.com/albion-vrenezi/profil/spieler/274355.
Transfer history data appended for: https://www.transfermarkt.com/benedikt-saller/profil/spieler/93552.
Transfer history data appended for: https://www.transfermarkt.com/alexander-meyer/profil/spieler/76158.
Transfer history data appended for: https://www.transfermarkt.com/benedikt-gimber/profil/spieler/227084.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-stolze/profil/spieler/157927.
Transfer history data appended for: https://www.transfermarkt.com/kevin-kunz/profil/spieler/169374.
Transfer history data appended for: https://www.transfermarkt.com/oliver-hein/profil/spieler/60006.
Transfer history data appended for: https://www.transfermarkt.com/andre-becker/profil/spieler/324660.
Transfer history data appended for: https://www.transfermarkt.com/florian-heister/profil/spieler/333661.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-wahling/profil/spieler/282180.
Transfer history data appended for: https://www.transfermarkt.com/jan-marc-schneider/profil/spieler/149354.
Transfer history data appended for: https://www.transfermarkt.com/jan-elvedi/profil/spieler/322506.
Transfer history data appended for: https://www.transfermarkt.com/bjorn-zempelin/profil/spieler/605949.
Transfer history data appended for: https://www.transfermarkt.com/max-besuschkow/profil/spieler/207578.
Transfer history data appended for: https://www.transfermarkt.com/georg-margreitter/profil/spieler/51325.
Transfer history data appended for: https://www.transfermarkt.com/paul-philipp-besong/profil/spieler/453783.
Transfer history data appended for: https://www.transfermarkt.com/enrico-valentini/profil/spieler/40605.
Transfer history data appended for: https://www.transfermarkt.com/noel-knothe/profil/spieler/379960.
Transfer history data appended for: https://www.transfermarkt.com/hanno-behrens/profil/spieler/57091.
Transfer history data appended for: https://www.transfermarkt.com/nikola-dovedan/profil/spieler/120189.
Transfer history data appended for: https://www.transfermarkt.com/manuel-schaffler/profil/spieler/48547.
Transfer history data appended for: https://www.transfermarkt.com/robin-hack/profil/spieler/284010.
Transfer history data appended for: https://www.transfermarkt.com/tom-krauss/profil/spieler/405687.
Transfer history data appended for: https://www.transfermarkt.com/pascal-kopke/profil/spieler/193877.
Transfer history data appended for: https://www.transfermarkt.com/ekin-celebi/profil/spieler/520908.
Transfer history data appended for: https://www.transfermarkt.com/christian-mathenia/profil/spieler/82361.
Transfer history data appended for: https://www.transfermarkt.com/simon-rhein/profil/spieler/284188.
Transfer history data appended for: https://www.transfermarkt.com/fabian-nurnberger/profil/spieler/349433.
Transfer history data appended for: https://www.transfermarkt.com/lukas-muhl/profil/spieler/279079.
Transfer history data appended for: https://www.transfermarkt.com/felix-lohkemper/profil/spieler/164767.
Transfer history data appended for: https://www.transfermarkt.com/patric-klandt/profil/spieler/2154.
Transfer history data appended for: https://www.transfermarkt.com/oliver-sorg/profil/spieler/55114.
Transfer history data appended for: https://www.transfermarkt.com/virgil-misidjan/profil/spieler/214346.
Transfer history data appended for: https://www.transfermarkt.com/asger-sorensen/profil/spieler/260846.
Transfer history data appended for: https://www.transfermarkt.com/adam-zrelak/profil/spieler/261155.
Transfer history data appended for: https://www.transfermarkt.com/andreas-lukse/profil/spieler/29586.
Transfer history data appended for: https://www.transfermarkt.com/christian-fruchtl/profil/spieler/336307.
Transfer history data appended for: https://www.transfermarkt.com/johannes-geis/profil/spieler/89650.
Transfer history data appended for: https://www.transfermarkt.com/fabian-schleusener/profil/spieler/229176.
Transfer history data appended for: https://www.transfermarkt.com/sarpreet-singh/profil/spieler/350357.
Transfer history data appended for: https://www.transfermarkt.com/pius-kratschmer/profil/spieler/222225.
Transfer history data appended for: https://www.transfermarkt.com/kevin-goden/profil/spieler/348214.
Transfer history data appended for: https://www.transfermarkt.com/tim-handwerker/profil/spieler/284177.
Transfer history data appended for: https://www.transfermarkt.com/fabian-schnellhardt/profil/spieler/94148.
Transfer history data appended for: https://www.transfermarkt.com/carl-klaus/profil/spieler/161057.
Transfer history data appended for: https://www.transfermarkt.com/patric-pfeiffer/profil/spieler/391742.
Transfer history data appended for: https://www.transfermarkt.com/erich-berko/profil/spieler/124402.
Transfer history data appended for: https://www.transfermarkt.com/felix-platte/profil/spieler/195782.
Transfer history data appended for: https://www.transfermarkt.com/adrian-stanilewicz/profil/spieler/389078.
Transfer history data appended for: https://www.transfermarkt.com/immanuel-hohn/profil/spieler/77920.
Transfer history data appended for: https://www.transfermarkt.com/tim-skarke/profil/spieler/287920.
Transfer history data appended for: https://www.transfermarkt.com/tobias-kempe/profil/spieler/42072.
Transfer history data appended for: https://www.transfermarkt.com/marvin-mehlem/profil/spieler/237226.
Transfer history data appended for: https://www.transfermarkt.com/ensar-arslan/profil/spieler/718467.
Transfer history data appended for: https://www.transfermarkt.com/serdar-dursun/profil/spieler/80059.
Transfer history data appended for: https://www.transfermarkt.com/nicolai-rapp/profil/spieler/185427.
Transfer history data appended for: https://www.transfermarkt.com/matthias-bader/profil/spieler/237162.
Transfer history data appended for: https://www.transfermarkt.com/mathias-wittek/profil/spieler/48968.
Transfer history data appended for: https://www.transfermarkt.com/aaron-seydel/profil/spieler/187499.
Transfer history data appended for: https://www.transfermarkt.com/lars-lukas-mai/profil/spieler/345780.
Transfer history data appended for: https://www.transfermarkt.com/patrick-herrmann/profil/spieler/57101.
Transfer history data appended for: https://www.transfermarkt.com/silas-zehnder/profil/spieler/317753.
Transfer history data appended for: https://www.transfermarkt.com/henry-jon-crosthwaite/profil/spieler/736973.
Transfer history data appended for: https://www.transfermarkt.com/florian-stritzel/profil/spieler/148096.

Transfer history data appended for: https://www.transfermarkt.com/marcel-schuhen/profil/spieler/93651.
Transfer history data appended for: https://www.transfermarkt.com/seung-ho-paik/profil/spieler/282689.
Transfer history data appended for: https://www.transfermarkt.com/braydon-manu/profil/spieler/231590.
Transfer history data appended for: https://www.transfermarkt.com/victor-palsson/profil/spieler/97241.
Transfer history data appended for: https://www.transfermarkt.com/marco-djuricin/profil/spieler/92989.
Transfer history data appended for: https://www.transfermarkt.com/philip-heise/profil/spieler/112617.
Transfer history data appended for: https://www.transfermarkt.com/dirk-carlson/profil/spieler/341530.
Transfer history data appended for: https://www.transfermarkt.com/janis-hanek/profil/spieler/349535.
Transfer history data appended for: https://www.transfermarkt.com/marc-lorenz/profil/spieler/50600.
Transfer history data appended for: https://www.transfermarkt.com/marco-thiede/profil/spieler/156715.
Transfer history data appended for: https://www.transfermarkt.com/alexander-groiss/profil/spieler/270164.
Transfer history data appended for: https://www.transfermarkt.com/babacar-gueye/profil/spieler/342364.
Transfer history data appended for: https://www.transfermarkt.com/david-trivunic/profil/spieler/471887.
Transfer history data appended for: https://www.transfermarkt.com/paul-lohr/profil/spieler/527630.
Transfer history data appended for: https://www.transfermarkt.com/marvin-wanitzek/profil/spieler/119581.
Transfer history data appended for: https://www.transfermarkt.com/david-pisot/profil/spieler/38348.
Transfer history data appended for: https://www.transfermarkt.com/markus-kuster/profil/spieler/123147.
Transfer history data appended for: https://www.transfermarkt.com/marius-gersbeck/profil/spieler/196382.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-jung/profil/spieler/49730.
Transfer history data appended for: https://www.transfermarkt.com/daniel-gordon/profil/spieler/17733.
Transfer history data appended for: https://www.transfermarkt.com/dominik-kother/profil/spieler/450253.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-goller/profil/spieler/388058.
Transfer history data appended for: https://www.transfermarkt.com/jannis-rabold/profil/spieler/392142.
Transfer history data appended for: https://www.transfermarkt.com/kyoung-rok-choi/profil/spieler/290171.
Transfer history data appended for: https://www.transfermarkt.com/christoph-kobald/profil/spieler/307509.
Transfer history data appended for: https://www.transfermarkt.com/lukas-frode/profil/spieler/153628.
Transfer history data appended for: https://www.transfermarkt.com/tim-breithaupt/profil/spieler/569457.
Transfer history data appended for: https://www.transfermarkt.com/malik-batmaz/profil/spieler/411134.
Transfer history data appended for: https://www.transfermarkt.com/robin-bormuth/profil/spieler/283286.
Transfer history data appended for: https://www.transfermarkt.com/kevin-behrens/profil/spieler/117432.
Transfer history data appended for: https://www.transfermarkt.com/robin-scheu/profil/spieler/322081.
Transfer history data appended for: https://www.transfermarkt.com/ivan-paurevic/profil/spieler/31868.
Transfer history data appended for: https://www.transfermarkt.com/besar-halimi/profil/spieler/152241.
Transfer history data appended for: https://www.transfermarkt.com/diego-contento/profil/spieler/39717.
Transfer history data appended for: https://www.transfermarkt.com/soren-dieckmann/profil/spieler/329508.
Transfer history data appended for: https://www.transfermarkt.com/enrique-pena-zauner/profil/spieler/336325.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-zhirov/profil/spieler/259849.
Transfer history data appended for: https://www.transfermarkt.com/benedikt-grawe/profil/spieler/453303.
Transfer history data appended for: https://www.transfermarkt.com/erik-zenga/profil/spieler/85961.
Transfer history data appended for: https://www.transfermarkt.com/marlon-frey/profil/spieler/182752.
Transfer history data appended for: https://www.transfermarkt.com/anas-ouahim/profil/spieler/240889.
Transfer history data appended for: https://www.transfermarkt.com/nils-roseler/profil/spieler/47740.
Transfer history data appended for: https://www.transfermarkt.com/julius-biada/profil/spieler/93586.
Transfer history data appended for: https://www.transfermarkt.com/dennis-diekmeier/profil/spieler/42044.
Transfer history data appended for: https://www.transfermarkt.com/alexander-rossipal/profil/spieler/296188.
Transfer history data appended for: https://www.transfermarkt.com/nikolas-nartey/profil/spieler/400546.
Transfer history data appended for: https://www.transfermarkt.com/philipp-heerwagen/profil/spieler/2071.
Transfer history data appended for: https://www.transfermarkt.com/rick-wulle/profil/spieler/302388.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-taffertshofer/profil/spieler/196785.
Transfer history data appended for: https://www.transfermarkt.com/martin-fraisl/profil/spieler/277607.
Transfer history data appended for: https://www.transfermarkt.com/daniel-keita-ruel/profil/spieler/42230.
Transfer history data appended for: https://www.transfermarkt.com/philip-turpitz/profil/spieler/122827.
Transfer history data appended for: https://www.transfermarkt.com/philipp-klingmann/profil/spieler/51216.
Transfer history data appended for: https://www.transfermarkt.com/denis-linsmayer/profil/spieler/84653.
Transfer history data appended for: https://www.transfermarkt.com/gerrit-nauber/profil/spieler/85904.
Transfer history data appended for: https://www.transfermarkt.com/tim-kister/profil/spieler/54767.
Transfer history data appended for: https://www.transfermarkt.com/aziz-bouhaddouz/profil/spieler/49821.
Transfer history data appended for: https://www.transfermarkt.com/svend-brodersen/profil/spieler/183292.
Transfer history data appended for: https://www.transfermarkt.com/leon-flach/profil/spieler/391929.
Transfer history data appended for: https://www.transfermarkt.com/christian-viet/profil/spieler/486731.
Transfer history data appended for: https://www.transfermarkt.com/guido-burgstaller/profil/spieler/49239.
Transfer history data appended for: https://www.transfermarkt.com/marvin-knoll/profil/spieler/44299.
Transfer history data appended for: https://www.transfermarkt.com/luca-zander/profil/spieler/139278.
Transfer history data appended for: https://www.transfermarkt.com/robin-himmelmann/profil/spieler/53116.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-ohlsson/profil/spieler/217357.
Transfer history data appended for: https://www.transfermarkt.com/jannes-wieckhoff/profil/spieler/447801.
Transfer history data appended for: https://www.transfermarkt.com/ryo-miyaichi/profil/spieler/129688.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/luis-coordes/profil/spieler/422086.
Transfer history data appended for: https://www.transfermarkt.com/christopher-buchtmann/profil/spieler/72094.
Transfer history data appended for: https://www.transfermarkt.com/boris-tashchy/profil/spieler/138292.
Transfer history data appended for: https://www.transfermarkt.com/marvin-senger/profil/spieler/447797.
Transfer history data appended for: https://www.transfermarkt.com/dennis-smarsch/profil/spieler/342966.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-zalazar/profil/spieler/606752.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-dittgen/profil/spieler/148197.
Transfer history data appended for: https://www.transfermarkt.com/aurel-loubongo/profil/spieler/529101.
Transfer history data appended for: https://www.transfermarkt.com/simon-makienok/profil/spieler/87162.
Transfer history data appended for: https://www.transfermarkt.com/daniel-kofi-kyereh/profil/spieler/272587.
Transfer history data appended for: https://www.transfermarkt.com/lukas-daschner/profil/spieler/334213.
Transfer history data appended for: https://www.transfermarkt.com/leart-paqarada/profil/spieler/107219.
Transfer history data appended for: https://www.transfermarkt.com/finn-ole-becker/profil/spieler/334999.
Transfer history data appended for: https://www.transfermarkt.com/philipp-ziereis/profil/spieler/152627.
Transfer history data appended for: https://www.transfermarkt.com/rico-benatelli/profil/spieler/86156.
Transfer history data appended for: https://www.transfermarkt.com/james-lawrence/profil/spieler/272706.
Transfer history data appended for: https://www.transfermarkt.com/mert-kuyucu/profil/spieler/447802.
Transfer history data appended for: https://www.transfermarkt.com/kevin-lankford/profil/spieler/338879.
Transfer history data appended for: https://www.transfermarkt.com/afeez-aremu/profil/spieler/562409.
Transfer history data appended for: https://www.transfermarkt.com/daniel-buballa/profil/spieler/109763.
Transfer history data appended for: https://www.transfermarkt.com/heinz-morschel/profil/spieler/250945.
Transfer history data appended for: https://www.transfermarkt.com/gino-fechner/profil/spieler/264633.
Transfer history data appended for: https://www.transfermarkt.com/kolja-pusch/profil/spieler/85946.
Transfer history data appended for: https://www.transfermarkt.com/adriano-grimaldi/profil/spieler/69392.
Transfer history data appended for: https://www.transfermarkt.com/rijad-kobiljar/profil/spieler/377793.
Transfer history data appended for: https://www.transfermarkt.com/mike-feigenspan/profil/spieler/315256.
Transfer history data appended for: https://www.transfermarkt.com/gustav-marcussen/profil/spieler/342393.
Transfer history data appended for: https://www.transfermarkt.com/hans-anapak/profil/spieler/453797.
Transfer history data appended for: https://www.transfermarkt.com/peter-van-ooijen/profil/spieler/123521.
Transfer history data appended for: https://www.transfermarkt.com/julius-paris/profil/spieler/695812.
Transfer history data appended for: https://www.transfermarkt.com/dominic-maroh/profil/spieler/41023.
Transfer history data appended for: https://www.transfermarkt.com/christian-kinsombi/profil/spieler/342968.
Transfer history data appended for: https://www.transfermarkt.com/edvinas-girdvainis/profil/spieler/167369.
Transfer history data appended for: https://www.transfermarkt.com/stefan-velkov/profil/spieler/227352.
Transfer history data appended for: https://www.transfermarkt.com/assani-lukimya/profil/spieler/32618.
Transfer history data appended for: https://www.transfermarkt.com/omar-haktab-traore/profil/spieler/388294.
Transfer history data appended for: https://www.transfermarkt.com/dave-gnaase/profil/spieler/286593.
Transfer history data appended for: https://www.transfermarkt.com/christian-dorda/profil/spieler/36189.
Transfer history data appended for: https://www.transfermarkt.com/hidde-jurjus/profil/spieler/215551.
Transfer history data appended for: https://www.transfermarkt.com/tim-albutat/profil/spieler/93658.
Transfer history data appended for: https://www.transfermarkt.com/fridolin-wagner/profil/spieler/238175.
Transfer history data appended for: https://www.transfermarkt.com/lukas-konigshofer/profil/spieler/42483.
Transfer history data appended for: https://www.transfermarkt.com/osayamen-osawe/profil/spieler/173593.
Transfer history data appended for: https://www.transfermarkt.com/patrick-gobel/profil/spieler/94116.
Transfer history data appended for: https://www.transfermarkt.com/ali-ibrahimaj/profil/spieler/240884.
Transfer history data appended for: https://www.transfermarkt.com/leon-schneider/profil/spieler/356325.
Transfer history data appended for: https://www.transfermarkt.com/muhammed-kiprit/profil/spieler/362746.
Transfer history data appended for: https://www.transfermarkt.com/gerrit-wegkamp/profil/spieler/136308.
Transfer history data appended for: https://www.transfermarkt.com/nils-miatke/profil/spieler/59176.
Transfer history data appended for: https://www.transfermarkt.com/bastian-strietzel/profil/spieler/286443.
Transfer history data appended for: https://www.transfermarkt.com/steffen-nkansah/profil/spieler/185423.
Transfer history data appended for: https://www.transfermarkt.com/julius-reinhardt/profil/spieler/48313.
Transfer history data appended for: https://www.transfermarkt.com/matti-kamenz/profil/spieler/312178.
Transfer history data appended for: https://www.transfermarkt.com/marco-schikora/profil/spieler/229792.
Transfer history data appended for: https://www.transfermarkt.com/leon-jensen/profil/spieler/273904.
Transfer history data appended for: https://www.transfermarkt.com/davy-frick/profil/spieler/56554.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-wolfram/profil/spieler/224503.
Transfer history data appended for: https://www.transfermarkt.com/marcus-godinho/profil/spieler/381069.
Transfer history data appended for: https://www.transfermarkt.com/johannes-brinkies/profil/spieler/89649.
Transfer history data appended for: https://www.transfermarkt.com/mike-konnecke/profil/spieler/77869.
Transfer history data appended for: https://www.transfermarkt.com/ali-odabas/profil/spieler/230614.
Transfer history data appended for: https://www.transfermarkt.com/max-sprang/profil/spieler/517085.
Transfer history data appended for: https://www.transfermarkt.com/jozo-stanic/profil/spieler/333450.
Transfer history data appended for: https://www.transfermarkt.com/dustin-willms/profil/spieler/371347.
Transfer history data appended for: https://www.transfermarkt.com/manfred-starke/profil/spieler/83707.
Transfer history data appended for: https://www.transfermarkt.com/yannik-moker/profil/spieler/369882.
Transfer history data appended for: https://www.transfermarkt.com/felix-drinkuth/profil/spieler/154722.
Transfer history data appended for: https://www.transfermarkt.com/ronny-konig/profil/spieler/2175.
Transfer history data appended for: https://www.transfermarkt.com/can-coskun/profil/spieler/237576.
Transfer history data appended for: https://www.transfermarkt.com/marius-hauptmann/profil/spieler/393337.
Transfer history data appended for: https://www.transfermarkt.com/morris-schroter/profil/spieler/171352.
Transfer history data appended for: https://www.transfermarkt.com/maurice-hehne/profil/spieler/215490.
Transfer history data appended for: https://www.transfermarkt.com/marco-schuster/profil/spieler/168186.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-leonce-kouadio/profil/spieler/333243.
Transfer history data appended for: https://www.transfermarkt.com/markus-scholz/profil/spieler/51060.
Transfer history data appended for: https://www.transfermarkt.com/joseph-boyamba/profil/spieler/228386.
Transfer history data appended for: https://www.transfermarkt.com/benedict-dos-santos/profil/spieler/199710.
Transfer history data appended for: https://www.transfermarkt.com/jan-just/profil/spieler/238144.
Transfer history data appended for: https://www.transfermarkt.com/gerrit-gohlke/profil/spieler/480710.

Transfer history data appended for: https://www.transfermarkt.com/gillian-jurcher/profil/spieler/231587.
Transfer history data appended for: https://www.transfermarkt.com/max-christiansen/profil/spieler/192300.
Transfer history data appended for: https://www.transfermarkt.com/dominik-martinovic/profil/spieler/227093.
Transfer history data appended for: https://www.transfermarkt.com/timo-konigsmann/profil/spieler/217718.
Transfer history data appended for: https://www.transfermarkt.com/dorian-diring/profil/spieler/230623.
Transfer history data appended for: https://www.transfermarkt.com/marcel-hofrath/profil/spieler/126310.
Transfer history data appended for: https://www.transfermarkt.com/manfred-osei-kwadwo/profil/spieler/167552.
Transfer history data appended for: https://www.transfermarkt.com/hamza-saghiri/profil/spieler/268757.
Transfer history data appended for: https://www.transfermarkt.com/anton-donkor/profil/spieler/280553.
Transfer history data appended for: https://www.transfermarkt.com/rafael-garcia/profil/spieler/241973.
Transfer history data appended for: https://www.transfermarkt.com/marcel-costly/profil/spieler/274274.
Transfer history data appended for: https://www.transfermarkt.com/jan-hendrik-marx/profil/spieler/169295.
Transfer history data appended for: https://www.transfermarkt.com/jesper-verlaat/profil/spieler/233420.
Transfer history data appended for: https://www.transfermarkt.com/onur-unlucifci/profil/spieler/285161.
Transfer history data appended for: https://www.transfermarkt.com/marcel-seegert/profil/spieler/119572.
Transfer history data appended for: https://www.transfermarkt.com/jan-christoph-bartels/profil/spieler/296346.
Transfer history data appended for: https://www.transfermarkt.com/anthony-roczen/profil/spieler/383032.
Transfer history data appended for: https://www.transfermarkt.com/jannis-turtschan/profil/spieler/452478.
Transfer history data appended for: https://www.transfermarkt.com/lino-volkmer/profil/spieler/699920.
Transfer history data appended for: https://www.transfermarkt.com/leonard-grob/profil/spieler/604544.
Transfer history data appended for: https://www.transfermarkt.com/michael-gurski/profil/spieler/1013.
Transfer history data appended for: https://www.transfermarkt.com/dominik-stahl/profil/spieler/47168.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-krauss/profil/spieler/334554.
Transfer history data appended for: https://www.transfermarkt.com/stephan-mensah/profil/spieler/336323.
Transfer history data appended for: https://www.transfermarkt.com/felix-schroter/profil/spieler/170525.
Transfer history data appended for: https://www.transfermarkt.com/dominik-stroh-engel/profil/spieler/19736.
Transfer history data appended for: https://www.transfermarkt.com/niclas-stierlin/profil/spieler/388026.
Transfer history data appended for: https://www.transfermarkt.com/alexander-fuchs/profil/spieler/278323.
Transfer history data appended for: https://www.transfermarkt.com/moritz-heinrich/profil/spieler/278330.
Transfer history data appended for: https://www.transfermarkt.com/marc-endres/profil/spieler/83184.
Transfer history data appended for: https://www.transfermarkt.com/max-dombrowka/profil/spieler/94754.
Transfer history data appended for: https://www.transfermarkt.com/niclas-anspach/profil/spieler/456222.
Transfer history data appended for: https://www.transfermarkt.com/boipelo-mashigo/profil/spieler/620174.
Transfer history data appended for: https://www.transfermarkt.com/felix-gottlicher/profil/spieler/604547.
Transfer history data appended for: https://www.transfermarkt.com/jim-patrick-muller/profil/spieler/60021.
Transfer history data appended for: https://www.transfermarkt.com/alexander-kaltner/profil/spieler/337244.
Transfer history data appended for: https://www.transfermarkt.com/stephan-hain/profil/spieler/50199.
Transfer history data appended for: https://www.transfermarkt.com/patrick-hasenhuttl/profil/spieler/275454.
Transfer history data appended for: https://www.transfermarkt.com/lucas-hufnagel/profil/spieler/168741.
Transfer history data appended for: https://www.transfermarkt.com/paul-grauschopf/profil/spieler/297054.
Transfer history data appended for: https://www.transfermarkt.com/jannik-bandowski/profil/spieler/189691.
Transfer history data appended for: https://www.transfermarkt.com/felix-muller/profil/spieler/85758.
Transfer history data appended for: https://www.transfermarkt.com/julien-richter/profil/spieler/380280.
Transfer history data appended for: https://www.transfermarkt.com/steve-kroll/profil/spieler/275081.
Transfer history data appended for: https://www.transfermarkt.com/josef-welzmuller/profil/spieler/231549.
Transfer history data appended for: https://www.transfermarkt.com/daniel-hausmann/profil/spieler/605572.
Transfer history data appended for: https://www.transfermarkt.com/robert-muller/profil/spieler/16917.
Transfer history data appended for: https://www.transfermarkt.com/christoph-greger/profil/spieler/278324.
Transfer history data appended for: https://www.transfermarkt.com/christoph-ehlich/profil/spieler/337194.
Transfer history data appended for: https://www.transfermarkt.com/markus-schwabl/profil/spieler/82289.
Transfer history data appended for: https://www.transfermarkt.com/andreas-hirtlreiter/profil/spieler/620494.
Transfer history data appended for: https://www.transfermarkt.com/sascha-bigalke/profil/spieler/44298.
Transfer history data appended for: https://www.transfermarkt.com/luca-marseiler/profil/spieler/339057.
Transfer history data appended for: https://www.transfermarkt.com/nico-mantl/profil/spieler/349536.
Transfer history data appended for: https://www.transfermarkt.com/nicolaj-madsen/profil/spieler/62471.
Transfer history data appended for: https://www.transfermarkt.com/jurgen-gjasula/profil/spieler/5197.
Transfer history data appended for: https://www.transfermarkt.com/korbinian-burger/profil/spieler/196763.
Transfer history data appended for: https://www.transfermarkt.com/tom-schlitter/profil/spieler/695738.
Transfer history data appended for: https://www.transfermarkt.com/dustin-bomheuer/profil/spieler/83241.
Transfer history data appended for: https://www.transfermarkt.com/henry-rorig/profil/spieler/381755.
Transfer history data appended for: https://www.transfermarkt.com/brian-koglin/profil/spieler/251975.
Transfer history data appended for: https://www.transfermarkt.com/leon-bell-bell/profil/spieler/232355.
Transfer history data appended for: https://www.transfermarkt.com/alexander-bittroff/profil/spieler/52354.
Transfer history data appended for: https://www.transfermarkt.com/daniel-steininger/profil/spieler/195720.
Transfer history data appended for: https://www.transfermarkt.com/nico-mai/profil/spieler/429737.
Transfer history data appended for: https://www.transfermarkt.com/florian-kath/profil/spieler/218011.
Transfer history data appended for: https://www.transfermarkt.com/philipp-harant/profil/spieler/333289.
Transfer history data appended for: https://www.transfermarkt.com/sirlord-conteh/profil/spieler/307183.
Transfer history data appended for: https://www.transfermarkt.com/timon-weiner/profil/spieler/296428.
Transfer history data appended for: https://www.transfermarkt.com/morten-behrens/profil/spieler/274039.
Transfer history data appended for: https://www.transfermarkt.com/tobias-muller/profil/spieler/19483.
Transfer history data appended for: https://www.transfermarkt.com/kai-brunker/profil/spieler/284058.
Transfer history data appended for: https://www.transfermarkt.com/dominik-ernst/profil/spieler/115659.
Transfer history data appended for: https://www.transfermarkt.com/thore-jacobsen/profil/spieler/236986.
Transfer history data appended for: https://www.transfermarkt.com/julian-weigel/profil/spieler/628303.
Transfer history data appended for: https://www.transfermarkt.com/andreas-muller/profil/spieler/438315.
Transfer history data appended for: https://www.transfermarkt.com/raphael-obermair/profil/spieler/330699.
Transfer history data appended for: https://www.transfermarkt.com/luka-sliskovic/profil/spieler/262270.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-franzke/profil/spieler/379985.

Transfer history data appended for: https://www.transfermarkt.com/christian-beck/profil/spieler/39396.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-jakubiak/profil/spieler/124084.
Transfer history data appended for: https://www.transfermarkt.com/adrian-malachowski/profil/spieler/342042.
Transfer history data appended for: https://www.transfermarkt.com/julian-schwermann/profil/spieler/296415.
Transfer history data appended for: https://www.transfermarkt.com/robin-bruseke/profil/spieler/232487.
Transfer history data appended for: https://www.transfermarkt.com/philipp-sander/profil/spieler/388409.
Transfer history data appended for: https://www.transfermarkt.com/julian-stockner/profil/spieler/52870.
Transfer history data appended for: https://www.transfermarkt.com/justin-eilers/profil/spieler/50782.
Transfer history data appended for: https://www.transfermarkt.com/sergej-schmik/profil/spieler/66973.
Transfer history data appended for: https://www.transfermarkt.com/matthias-haeder/profil/spieler/45664.
Transfer history data appended for: https://www.transfermarkt.com/lars-ritzka/profil/spieler/333903.
Transfer history data appended for: https://www.transfermarkt.com/frederik-lach/profil/spieler/264641.
Transfer history data appended for: https://www.transfermarkt.com/nico-hecker/profil/spieler/83228.
Transfer history data appended for: https://www.transfermarkt.com/christopher-lannert/profil/spieler/326921.
Transfer history data appended for: https://www.transfermarkt.com/patrick-choroba/profil/spieler/391429.
Transfer history data appended for: https://www.transfermarkt.com/berkan-taz/profil/spieler/451380.
Transfer history data appended for: https://www.transfermarkt.com/steffen-lang/profil/spieler/109728.
Transfer history data appended for: https://www.transfermarkt.com/leander-siemann/profil/spieler/182211.
Transfer history data appended for: https://www.transfermarkt.com/lasse-jurgensen/profil/spieler/296694.
Transfer history data appended for: https://www.transfermarkt.com/sascha-korb/profil/spieler/94952.
Transfer history data appended for: https://www.transfermarkt.com/aygun-yildirim/profil/spieler/300334.
Transfer history data appended for: https://www.transfermarkt.com/yannick-langesberg/profil/spieler/229435.
Transfer history data appended for: https://www.transfermarkt.com/barne-pernot/profil/spieler/423192.
Transfer history data appended for: https://www.transfermarkt.com/patrick-schikowski/profil/spieler/85206.
Transfer history data appended for: https://www.transfermarkt.com/till-brinkmann/profil/spieler/166182.
Transfer history data appended for: https://www.transfermarkt.com/daniel-mikic/profil/spieler/86028.
Transfer history data appended for: https://www.transfermarkt.com/mehmet-kurt/profil/spieler/196226.
Transfer history data appended for: https://www.transfermarkt.com/zlatko-janjic/profil/spieler/27033.
Transfer history data appended for: https://www.transfermarkt.com/kasim-rabihic/profil/spieler/196146.
Transfer history data appended for: https://www.transfermarkt.com/anthony-barylla/profil/spieler/238119.
Transfer history data appended for: https://www.transfermarkt.com/mario-muller/profil/spieler/161697.
Transfer history data appended for: https://www.transfermarkt.com/teo-herr/profil/spieler/514158.
Transfer history data appended for: https://www.transfermarkt.com/markus-mendler/profil/spieler/120834.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-bosel/profil/spieler/233610.
Transfer history data appended for: https://www.transfermarkt.com/lukas-schleimer/profil/spieler/479273.
Transfer history data appended for: https://www.transfermarkt.com/timm-golley/profil/spieler/228966.
Transfer history data appended for: https://www.transfermarkt.com/kianz-froese/profil/spieler/294701.
Transfer history data appended for: https://www.transfermarkt.com/tobias-janicke/profil/spieler/43821.
Transfer history data appended for: https://www.transfermarkt.com/jonas-singer/profil/spieler/378335.
Transfer history data appended for: https://www.transfermarkt.com/minos-gouras/profil/spieler/278569.
Transfer history data appended for: https://www.transfermarkt.com/nicklas-shipnoski/profil/spieler/313178.
Transfer history data appended for: https://www.transfermarkt.com/daniel-batz/profil/spieler/90317.
Transfer history data appended for: https://www.transfermarkt.com/marin-sverko/profil/spieler/282169.
Transfer history data appended for: https://www.transfermarkt.com/fanol-perdedaj/profil/spieler/62934.
Transfer history data appended for: https://www.transfermarkt.com/bone-uaferro/profil/spieler/91280.
Transfer history data appended for: https://www.transfermarkt.com/jose-pierre-vunguidica/profil/spieler/52883.
Transfer history data appended for: https://www.transfermarkt.com/jayson-breitenbach/profil/spieler/279249.
Transfer history data appended for: https://www.transfermarkt.com/manuel-zeitz/profil/spieler/85960.
Transfer history data appended for: https://www.transfermarkt.com/mergim-fejzullahu/profil/spieler/185000.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-jacob/profil/spieler/196876.
Transfer history data appended for: https://www.transfermarkt.com/steven-zellner/profil/spieler/60443.
Transfer history data appended for: https://www.transfermarkt.com/christopher-schorch/profil/spieler/36902.
Transfer history data appended for: https://www.transfermarkt.com/marius-kohl/profil/spieler/718236.
Transfer history data appended for: https://www.transfermarkt.com/maurice-deville/profil/spieler/85538.
Transfer history data appended for: https://www.transfermarkt.com/ramon-castellucci/profil/spieler/279070.
Transfer history data appended for: https://www.transfermarkt.com/rasim-bulic/profil/spieler/679471.
Transfer history data appended for: https://www.transfermarkt.com/patrick-wiegers/profil/spieler/82298.
Transfer history data appended for: https://www.transfermarkt.com/chris-lowe/profil/spieler/55125.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-mai/profil/spieler/152457.
Transfer history data appended for: https://www.transfermarkt.com/kevin-ehlers/profil/spieler/447783.
Transfer history data appended for: https://www.transfermarkt.com/kevin-broll/profil/spieler/161075.
Transfer history data appended for: https://www.transfermarkt.com/patrick-weihrauch/profil/spieler/125105.
Transfer history data appended for: https://www.transfermarkt.com/simon-gollnack/profil/spieler/604738.
Transfer history data appended for: https://www.transfermarkt.com/marvin-stefaniak/profil/spieler/196421.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-meier/profil/spieler/379989.
Transfer history data appended for: https://www.transfermarkt.com/tim-knipping/profil/spieler/185520.
Transfer history data appended for: https://www.transfermarkt.com/justin-lowe/profil/spieler/288668.
Transfer history data appended for: https://www.transfermarkt.com/stefan-kiefer/profil/spieler/438536.
Transfer history data appended for: https://www.transfermarkt.com/paul-will/profil/spieler/356640.
Transfer history data appended for: https://www.transfermarkt.com/pascal-sohm/profil/spieler/158312.
Transfer history data appended for: https://www.transfermarkt.com/ransford-konigsdorffer/profil/spieler/470038.
Transfer history data appended for: https://www.transfermarkt.com/agyemang-diawusie/profil/spieler/317024.
Transfer history data appended for: https://www.transfermarkt.com/philipp-hosiner/profil/spieler/37788.
Transfer history data appended for: https://www.transfermarkt.com/julius-kade/profil/spieler/317735.
Transfer history data appended for: https://www.transfermarkt.com/luka-stor/profil/spieler/340428.
Transfer history data appended for: https://www.transfermarkt.com/marco-hartmann/profil/spieler/23566.
Transfer history data appended for: https://www.transfermarkt.com/yannick-stark/profil/spieler/49737.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-vlachodimos/profil/spieler/83700.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-grosser/profil/spieler/528515.
Transfer history data appended for: https://www.transfermarkt.com/christoph-daferner/profil/spieler/324851.

Transfer history data appended for: https://www.transfermarkt.com/robin-becker/profil/spieler/237444.
Transfer history data appended for: https://www.transfermarkt.com/max-kulke/profil/spieler/394280.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-sauer/profil/spieler/158054.
Transfer history data appended for: https://www.transfermarkt.com/darius-ghindovean/profil/spieler/508762.
Transfer history data appended for: https://www.transfermarkt.com/jonas-brendieck/profil/spieler/361275.
Transfer history data appended for: https://www.transfermarkt.com/connor-krempicki/profil/spieler/107205.
Transfer history data appended for: https://www.transfermarkt.com/vincent-vermeij/profil/spieler/273054.
Transfer history data appended for: https://www.transfermarkt.com/wilson-kamavuaka/profil/spieler/55512.
Transfer history data appended for: https://www.transfermarkt.com/ahmet-engin/profil/spieler/193612.
Transfer history data appended for: https://www.transfermarkt.com/leroy-jacques-mickels/profil/spieler/191426.
Transfer history data appended for: https://www.transfermarkt.com/tobias-fleckstein/profil/spieler/335101.
Transfer history data appended for: https://www.transfermarkt.com/dominic-volkmer/profil/spieler/339596.
Transfer history data appended for: https://www.transfermarkt.com/leo-weinkauf/profil/spieler/196427.
Transfer history data appended for: https://www.transfermarkt.com/joshua-bitter/profil/spieler/265159.
Transfer history data appended for: https://www.transfermarkt.com/sinan-karweina/profil/spieler/337816.
Transfer history data appended for: https://www.transfermarkt.com/lukas-scepanik/profil/spieler/140712.
Transfer history data appended for: https://www.transfermarkt.com/david-tomic/profil/spieler/337682.
Transfer history data appended for: https://www.transfermarkt.com/steven-deana/profil/spieler/61150.
Transfer history data appended for: https://www.transfermarkt.com/orhan-ademi/profil/spieler/92111.
Transfer history data appended for: https://www.transfermarkt.com/dominik-schmidt/profil/spieler/17443.
Transfer history data appended for: https://www.transfermarkt.com/vincent-gembalies/profil/spieler/335999.
Transfer history data appended for: https://www.transfermarkt.com/niko-bretschneider/profil/spieler/397677.
Transfer history data appended for: https://www.transfermarkt.com/arne-sicker/profil/spieler/244997.
Transfer history data appended for: https://www.transfermarkt.com/mirnes-pepic/profil/spieler/195781.
Transfer history data appended for: https://www.transfermarkt.com/cem-sabanci/profil/spieler/452109.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-jansen/profil/spieler/149209.
Transfer history data appended for: https://www.transfermarkt.com/arnold-budimbu/profil/spieler/153897.
Transfer history data appended for: https://www.transfermarkt.com/tom-boere/profil/spieler/124863.
Transfer history data appended for: https://www.transfermarkt.com/kerem-kavuk/profil/spieler/804160.
Transfer history data appended for: https://www.transfermarkt.com/alexander-laukart/profil/spieler/251327.
Transfer history data appended for: https://www.transfermarkt.com/rene-vollath/profil/spieler/40520.
Transfer history data appended for: https://www.transfermarkt.com/marco-holz/profil/spieler/57934.
Transfer history data appended for: https://www.transfermarkt.com/sercan-sararer/profil/spieler/45464.
Transfer history data appended for: https://www.transfermarkt.com/marco-raimondo-metzger/profil/spieler/89539.
Transfer history data appended for: https://www.transfermarkt.com/alexander-sorge/profil/spieler/195612.
Transfer history data appended for: https://www.transfermarkt.com/stefan-stangl/profil/spieler/84537.
Transfer history data appended for: https://www.transfermarkt.com/amani-mbaraka/profil/spieler/794715.
Transfer history data appended for: https://www.transfermarkt.com/filip-kusic/profil/spieler/217285.
Transfer history data appended for: https://www.transfermarkt.com/azur-velagic/profil/spieler/120372.
Transfer history data appended for: https://www.transfermarkt.com/omar-sijaric/profil/spieler/522263.
Transfer history data appended for: https://www.transfermarkt.com/benedikt-kirsch/profil/spieler/237141.
Transfer history data appended for: https://www.transfermarkt.com/mounir-bouziane/profil/spieler/123189.
Transfer history data appended for: https://www.transfermarkt.com/philipp-erhardt/profil/spieler/151216.
Transfer history data appended for: https://www.transfermarkt.com/jordaine-jager/profil/spieler/628440.
Transfer history data appended for: https://www.transfermarkt.com/kilian-fischer/profil/spieler/435796.
Transfer history data appended for: https://www.transfermarkt.com/atakan-akkaynak/profil/spieler/327542.
Transfer history data appended for: https://www.transfermarkt.com/emre-kurt/profil/spieler/237605.
Transfer history data appended for: https://www.transfermarkt.com/nico-gorzel/profil/spieler/307591.
Transfer history data appended for: https://www.transfermarkt.com/unal-tosun/profil/spieler/190699.
Transfer history data appended for: https://www.transfermarkt.com/aaron-berzel/profil/spieler/96098.
Transfer history data appended for: https://www.transfermarkt.com/michael-zant/profil/spieler/198014.
Transfer history data appended for: https://www.transfermarkt.com/furkan-kircicek/profil/spieler/377113.
Transfer history data appended for: https://www.transfermarkt.com/fabijan-podunavac/profil/spieler/792903.
Transfer history data appended for: https://www.transfermarkt.com/furkan-zorba/profil/spieler/315437.
Transfer history data appended for: https://www.transfermarkt.com/boubacar-barry/profil/spieler/242166.
Transfer history data appended for: https://www.transfermarkt.com/daniele-gabriele/profil/spieler/144323.
Transfer history data appended for: https://www.transfermarkt.com/thomas-haas/profil/spieler/325261.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-engl/profil/spieler/278322.
Transfer history data appended for: https://www.transfermarkt.com/franco-fluckiger/profil/spieler/59818.
Transfer history data appended for: https://www.transfermarkt.com/erol-alkan/profil/spieler/307494.
Transfer history data appended for: https://www.transfermarkt.com/jakov-medic/profil/spieler/488755.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-korte/profil/spieler/109792.
Transfer history data appended for: https://www.transfermarkt.com/matthias-hamrol/profil/spieler/104267.
Transfer history data appended for: https://www.transfermarkt.com/marvin-ajani/profil/spieler/216401.
Transfer history data appended for: https://www.transfermarkt.com/michel-niemeyer/profil/spieler/154110.
Transfer history data appended for: https://www.transfermarkt.com/dennis-kempe/profil/spieler/31215.
Transfer history data appended for: https://www.transfermarkt.com/phillip-tietz/profil/spieler/288340.
Transfer history data appended for: https://www.transfermarkt.com/moritz-kuhn/profil/spieler/125331.
Transfer history data appended for: https://www.transfermarkt.com/sascha-mockenhaupt/profil/spieler/147216.
Transfer history data appended for: https://www.transfermarkt.com/marc-lais/profil/spieler/83188.
Transfer history data appended for: https://www.transfermarkt.com/arthur-lyska/profil/spieler/372127.
Transfer history data appended for: https://www.transfermarkt.com/benedikt-rocker/profil/spieler/116272.
Transfer history data appended for: https://www.transfermarkt.com/ben-bischof/profil/spieler/605068.
Transfer history data appended for: https://www.transfermarkt.com/ahmet-gurleyen/profil/spieler/397696.
Transfer history data appended for: https://www.transfermarkt.com/paterson-chato/profil/spieler/149265.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-mrowca/profil/spieler/124568.
Transfer history data appended for: https://www.transfermarkt.com/stefan-aigner/profil/spieler/35183.
Transfer history data appended for: https://www.transfermarkt.com/benedict-hollerbach/profil/spieler/453870.
Transfer history data appended for: https://www.transfermarkt.com/michael-guthorl/profil/spieler/411271.
Transfer history data appended for: https://www.transfermarkt.com/tim-boss/profil/spieler/85534.

Transfer history data appended for: https://www.transfermarkt.com/tobias-schwede/profil/spieler/153680.
Transfer history data appended for: https://www.transfermarkt.com/tim-walbrecht/profil/spieler/529117.
Transfer history data appended for: https://www.transfermarkt.com/torben-rhein/profil/spieler/522253.
Transfer history data appended for: https://www.transfermarkt.com/daniels-ontuzans/profil/spieler/336324.
Transfer history data appended for: https://www.transfermarkt.com/christopher-scott/profil/spieler/503162.
Transfer history data appended for: https://www.transfermarkt.com/jamie-lawrence/profil/spieler/522248.
Transfer history data appended for: https://www.transfermarkt.com/remy-vita/profil/spieler/805835.
Transfer history data appended for: https://www.transfermarkt.com/michael-wagner/profil/spieler/411201.
Transfer history data appended for: https://www.transfermarkt.com/josip-stanisic/profil/spieler/483046.
Transfer history data appended for: https://www.transfermarkt.com/jamal-musiala/profil/spieler/580195.
Transfer history data appended for: https://www.transfermarkt.com/ron-thorben-hoffmann/profil/spieler/317444.
Transfer history data appended for: https://www.transfermarkt.com/dennis-waidner/profil/spieler/453877.
Transfer history data appended for: https://www.transfermarkt.com/angelo-stiller/profil/spieler/443710.
Transfer history data appended for: https://www.transfermarkt.com/lukas-schneller/profil/spieler/453874.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-feldhahn/profil/spieler/31741.
Transfer history data appended for: https://www.transfermarkt.com/timo-kern/profil/spieler/57574.
Transfer history data appended for: https://www.transfermarkt.com/taylor-booth/profil/spieler/513963.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-kuhn/profil/spieler/336012.
Transfer history data appended for: https://www.transfermarkt.com/fiete-arp/profil/spieler/343337.
Transfer history data appended for: https://www.transfermarkt.com/chris-richards/profil/spieler/578539.
Transfer history data appended for: https://www.transfermarkt.com/kilian-senkbeil/profil/spieler/335455.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-welzmuller/profil/spieler/81559.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-zaiser/profil/spieler/380423.
Transfer history data appended for: https://www.transfermarkt.com/jannik-rochelt/profil/spieler/501794.
Transfer history data appended for: https://www.transfermarkt.com/ivan-mihaljevic/profil/spieler/453510.
Transfer history data appended for: https://www.transfermarkt.com/joshua-zirkzee/profil/spieler/435648.
Transfer history data appended for: https://www.transfermarkt.com/alexander-lungwitz/profil/spieler/422211.
Transfer history data appended for: https://www.transfermarkt.com/bright-arrey-mbi/profil/spieler/580193.
Transfer history data appended for: https://www.transfermarkt.com/can-karatas/profil/spieler/424736.
Transfer history data appended for: https://www.transfermarkt.com/tiago-dantas/profil/spieler/429987.
Transfer history data appended for: https://www.transfermarkt.com/leon-dajaku/profil/spieler/483974.
Transfer history data appended for: https://www.transfermarkt.com/malik-tillman/profil/spieler/467437.
Transfer history data appended for: https://www.transfermarkt.com/lenny-borges/profil/spieler/406603.
Transfer history data appended for: https://www.transfermarkt.com/angelo-mayer/profil/spieler/228952.
Transfer history data appended for: https://www.transfermarkt.com/angelo-bruckner/profil/spieler/563617.
Transfer history data appended for: https://www.transfermarkt.com/lenn-jastremski/profil/spieler/524560.
Transfer history data appended for: https://www.transfermarkt.com/tobias-schilk/profil/spieler/93553.
Transfer history data appended for: https://www.transfermarkt.com/michael-eberwein/profil/spieler/195049.
Transfer history data appended for: https://www.transfermarkt.com/sven-muller/profil/spieler/168797.
Transfer history data appended for: https://www.transfermarkt.com/jan-shcherbakovski/profil/spieler/528834.
Transfer history data appended for: https://www.transfermarkt.com/kai-eisele/profil/spieler/192191.
Transfer history data appended for: https://www.transfermarkt.com/terrence-boyd/profil/spieler/103064.
Transfer history data appended for: https://www.transfermarkt.com/lukas-boeder/profil/spieler/227078.
Transfer history data appended for: https://www.transfermarkt.com/jannes-vollert/profil/spieler/267035.
Transfer history data appended for: https://www.transfermarkt.com/laurenz-dehl/profil/spieler/451403.
Transfer history data appended for: https://www.transfermarkt.com/soren-reddemann/profil/spieler/197383.
Transfer history data appended for: https://www.transfermarkt.com/stipe-vucur/profil/spieler/111463.
Transfer history data appended for: https://www.transfermarkt.com/janek-sternberg/profil/spieler/89542.
Transfer history data appended for: https://www.transfermarkt.com/niklas-kastenhofer/profil/spieler/386784.
Transfer history data appended for: https://www.transfermarkt.com/anthony-syhre/profil/spieler/146167.
Transfer history data appended for: https://www.transfermarkt.com/jonas-nietfeld/profil/spieler/155374.
Transfer history data appended for: https://www.transfermarkt.com/toni-lindenhahn/profil/spieler/43822.
Transfer history data appended for: https://www.transfermarkt.com/antonios-papadopoulos/profil/spieler/482573.
Transfer history data appended for: https://www.transfermarkt.com/marcel-titsch-rivero/profil/spieler/49669.
Transfer history data appended for: https://www.transfermarkt.com/fabian-menig/profil/spieler/124507.
Transfer history data appended for: https://www.transfermarkt.com/selim-gunduz/profil/spieler/152781.
Transfer history data appended for: https://www.transfermarkt.com/niklas-landgraf/profil/spieler/196394.
Transfer history data appended for: https://www.transfermarkt.com/dennis-mast/profil/spieler/93854.
Transfer history data appended for: https://www.transfermarkt.com/tom-muller/profil/spieler/341878.
Transfer history data appended for: https://www.transfermarkt.com/julian-guttau/profil/spieler/469814.
Transfer history data appended for: https://www.transfermarkt.com/julian-maurice-derstroff/profil/spieler/87650.
Transfer history data appended for: https://www.transfermarkt.com/jeron-al-hazaimeh/profil/spieler/123395.
Transfer history data appended for: https://www.transfermarkt.com/hassan-amin/profil/spieler/104293.
Transfer history data appended for: https://www.transfermarkt.com/rene-guder/profil/spieler/216348.
Transfer history data appended for: https://www.transfermarkt.com/luka-tankulic/profil/spieler/72989.
Transfer history data appended for: https://www.transfermarkt.com/steffen-puttkammer/profil/spieler/54238.
Transfer history data appended for: https://www.transfermarkt.com/ted-tattermusch/profil/spieler/679013.
Transfer history data appended for: https://www.transfermarkt.com/erik-domaschke/profil/spieler/19072.
Transfer history data appended for: https://www.transfermarkt.com/markus-ballmert/profil/spieler/227799.
Transfer history data appended for: https://www.transfermarkt.com/yannick-osee/profil/spieler/410259.
Transfer history data appended for: https://www.transfermarkt.com/julius-duker/profil/spieler/202957.
Transfer history data appended for: https://www.transfermarkt.com/lukas-kruger/profil/spieler/448092.
Transfer history data appended for: https://www.transfermarkt.com/florian-egerer/profil/spieler/322761.
Transfer history data appended for: https://www.transfermarkt.com/willi-evseev/profil/spieler/80060.
Transfer history data appended for: https://www.transfermarkt.com/hilal-el-helwe/profil/spieler/273551.
Transfer history data appended for: https://www.transfermarkt.com/leonard-bredol/profil/spieler/657962.
Transfer history data appended for: https://www.transfermarkt.com/lars-bunning/profil/spieler/379114.
Transfer history data appended for: https://www.transfermarkt.com/janik-jesgarzewski/profil/spieler/245800.
Transfer history data appended for: https://www.transfermarkt.com/marcus-piossek/profil/spieler/33416.

Transfer history data appended for: https://www.transfermarkt.com/christoph-hemlein/profil/spieler/58030.
Transfer history data appended for: https://www.transfermarkt.com/constantin-frommann/profil/spieler/274989.
Transfer history data appended for: https://www.transfermarkt.com/valdet-rama/profil/spieler/33535.
Transfer history data appended for: https://www.transfermarkt.com/dejan-bozic/profil/spieler/119543.
Transfer history data appended for: https://www.transfermarkt.com/luca-plogmann/profil/spieler/335997.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-andermatt/profil/spieler/196433.
Transfer history data appended for: https://www.transfermarkt.com/matthis-harsman/profil/spieler/443478.
Transfer history data appended for: https://www.transfermarkt.com/thilo-leugers/profil/spieler/47737.
Transfer history data appended for: https://www.transfermarkt.com/elias-huth/profil/spieler/284688.
Transfer history data appended for: https://www.transfermarkt.com/avdo-spahic/profil/spieler/273937.
Transfer history data appended for: https://www.transfermarkt.com/marlon-ritter/profil/spieler/151636.
Transfer history data appended for: https://www.transfermarkt.com/alexander-winkler/profil/spieler/166292.
Transfer history data appended for: https://www.transfermarkt.com/marius-kleinsorge/profil/spieler/256994.
Transfer history data appended for: https://www.transfermarkt.com/anil-gozutok/profil/spieler/443863.
Transfer history data appended for: https://www.transfermarkt.com/andre-hainault/profil/spieler/39335.
Transfer history data appended for: https://www.transfermarkt.com/carlo-sickinger/profil/spieler/282163.
Transfer history data appended for: https://www.transfermarkt.com/jonas-scholz/profil/spieler/380285.
Transfer history data appended for: https://www.transfermarkt.com/tom-fladung/profil/spieler/527665.
Transfer history data appended for: https://www.transfermarkt.com/leon-hotopp/profil/spieler/445599.
Transfer history data appended for: https://www.transfermarkt.com/matheo-raab/profil/spieler/386685.
Transfer history data appended for: https://www.transfermarkt.com/lukas-gottwalt/profil/spieler/435129.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-sessa/profil/spieler/259135.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-morabet/profil/spieler/415879.
Transfer history data appended for: https://www.transfermarkt.com/elija-wohlgemuth/profil/spieler/569286.
Transfer history data appended for: https://www.transfermarkt.com/dominik-schad/profil/spieler/282150.
Transfer history data appended for: https://www.transfermarkt.com/kenny-prince-redondo/profil/spieler/196147.
Transfer history data appended for: https://www.transfermarkt.com/adam-hlousek/profil/spieler/62800.
Transfer history data appended for: https://www.transfermarkt.com/kevin-kraus/profil/spieler/58996.
Transfer history data appended for: https://www.transfermarkt.com/jonas-weyand/profil/spieler/432737.
Transfer history data appended for: https://www.transfermarkt.com/lorenz-otto/profil/spieler/527653.
Transfer history data appended for: https://www.transfermarkt.com/dylan-esmel/profil/spieler/218584.
Transfer history data appended for: https://www.transfermarkt.com/hikmet-ciftci/profil/spieler/244930.
Transfer history data appended for: https://www.transfermarkt.com/lucas-roser/profil/spieler/115210.
Transfer history data appended for: https://www.transfermarkt.com/lukas-spalvis/profil/spieler/155960.
Transfer history data appended for: https://www.transfermarkt.com/hendrick-zuck/profil/spieler/82018.
Transfer history data appended for: https://www.transfermarkt.com/anas-bakhat/profil/spieler/489090.
Transfer history data appended for: https://www.transfermarkt.com/simon-skarlatidis/profil/spieler/139942.
Transfer history data appended for: https://www.transfermarkt.com/janik-bachmann/profil/spieler/327862.
Transfer history data appended for: https://www.transfermarkt.com/philipp-hercher/profil/spieler/216399.
Transfer history data appended for: https://www.transfermarkt.com/constantin-fath/profil/spieler/335929.
Transfer history data appended for: https://www.transfermarkt.com/thorben-deters/profil/spieler/322249.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-hertner/profil/spieler/83694.
Transfer history data appended for: https://www.transfermarkt.com/tommy-grupe/profil/spieler/74841.
Transfer history data appended for: https://www.transfermarkt.com/soren-lippert/profil/spieler/309403.
Transfer history data appended for: https://www.transfermarkt.com/florian-riedel/profil/spieler/54863.
Transfer history data appended for: https://www.transfermarkt.com/elsamed-ramaj/profil/spieler/333944.
Transfer history data appended for: https://www.transfermarkt.com/dren-feka/profil/spieler/224499.
Transfer history data appended for: https://www.transfermarkt.com/jamie-shalom/profil/spieler/599141.
Transfer history data appended for: https://www.transfermarkt.com/nico-rieble/profil/spieler/166281.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-gommert/profil/spieler/19801.
Transfer history data appended for: https://www.transfermarkt.com/martin-roser/profil/spieler/152907.
Transfer history data appended for: https://www.transfermarkt.com/sven-mende/profil/spieler/148123.
Transfer history data appended for: https://www.transfermarkt.com/yannick-deichmann/profil/spieler/158805.
Transfer history data appended for: https://www.transfermarkt.com/patrick-hobsch/profil/spieler/236543.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-hebisch/profil/spieler/57706.
Transfer history data appended for: https://www.transfermarkt.com/ryan-malone/profil/spieler/373178.
Transfer history data appended for: https://www.transfermarkt.com/tim-kircher/profil/spieler/369575.
Transfer history data appended for: https://www.transfermarkt.com/osarenren-okungbowa/profil/spieler/165407.
Transfer history data appended for: https://www.transfermarkt.com/moody-chana/profil/spieler/296350.
Transfer history data appended for: https://www.transfermarkt.com/soufian-benyamina/profil/spieler/77947.
Transfer history data appended for: https://www.transfermarkt.com/marvin-thiel/profil/spieler/237620.
Transfer history data appended for: https://www.transfermarkt.com/michael-luyambula/profil/spieler/384535.
Transfer history data appended for: https://www.transfermarkt.com/ersin-zehir/profil/spieler/275127.
Transfer history data appended for: https://www.transfermarkt.com/lukas-raeder/profil/spieler/125172.
Transfer history data appended for: https://www.transfermarkt.com/tim-weissmann/profil/spieler/279357.
Transfer history data appended for: https://www.transfermarkt.com/morten-rudiger/profil/spieler/190978.
Transfer history data appended for: https://www.transfermarkt.com/mirko-boland/profil/spieler/36255.
Transfer history data appended for: https://www.transfermarkt.com/pascal-steinwender/profil/spieler/279018.
Transfer history data appended for: https://www.transfermarkt.com/rico-preissinger/profil/spieler/206411.
Transfer history data appended for: https://www.transfermarkt.com/jonatan-kotzke/profil/spieler/90330.
Transfer history data appended for: https://www.transfermarkt.com/patrick-sussek/profil/spieler/427291.
Transfer history data appended for: https://www.transfermarkt.com/thomas-keller/profil/spieler/485747.
Transfer history data appended for: https://www.transfermarkt.com/jalen-hawkins/profil/spieler/433091.
Transfer history data appended for: https://www.transfermarkt.com/tobias-schrock/profil/spieler/130437.
Transfer history data appended for: https://www.transfermarkt.com/fabijan-buntic/profil/spieler/248349.
Transfer history data appended for: https://www.transfermarkt.com/robert-jendrusch/profil/spieler/242070.
Transfer history data appended for: https://www.transfermarkt.com/lukas-schellenberg/profil/spieler/336308.
Transfer history data appended for: https://www.transfermarkt.com/justin-butler/profil/spieler/453861.
Transfer history data appended for: https://www.transfermarkt.com/nico-antonitsch/profil/spieler/82526.
Transfer history data appended for: https://www.transfermarkt.com/marc-stendera/profil/spieler/160943.

Transfer history data appended for: https://www.transfermarkt.com/caniggia-elva/profil/spieler/330795.
Transfer history data appended for: https://www.transfermarkt.com/michael-heinloth/profil/spieler/93535.
Transfer history data appended for: https://www.transfermarkt.com/gordon-buch/profil/spieler/196342.
Transfer history data appended for: https://www.transfermarkt.com/filip-bilbija/profil/spieler/602796.
Transfer history data appended for: https://www.transfermarkt.com/dennis-eckert-ayensa/profil/spieler/249303.
Transfer history data appended for: https://www.transfermarkt.com/ilmari-niskanen/profil/spieler/268606.
Transfer history data appended for: https://www.transfermarkt.com/bjorn-paulsen/profil/spieler/103428.
Transfer history data appended for: https://www.transfermarkt.com/marcel-gaus/profil/spieler/56969.
Transfer history data appended for: https://www.transfermarkt.com/dominik-franke/profil/spieler/288348.
Transfer history data appended for: https://www.transfermarkt.com/thorsten-rocher/profil/spieler/174856.
Transfer history data appended for: https://www.transfermarkt.com/robin-krausse/profil/spieler/121454.
Transfer history data appended for: https://www.transfermarkt.com/fatih-kaya/profil/spieler/368825.
Transfer history data appended for: https://www.transfermarkt.com/matthew-durrans/profil/spieler/324757.
Transfer history data appended for: https://www.transfermarkt.com/marius-willsch/profil/spieler/81542.
Transfer history data appended for: https://www.transfermarkt.com/niklas-lang/profil/spieler/590478.
Transfer history data appended for: https://www.transfermarkt.com/quirin-moll/profil/spieler/87190.
Transfer history data appended for: https://www.transfermarkt.com/johann-ngounou-djayo/profil/spieler/458397.
Transfer history data appended for: https://www.transfermarkt.com/dennis-erdmann/profil/spieler/195954.
Transfer history data appended for: https://www.transfermarkt.com/phillipp-steinhart/profil/spieler/82008.
Transfer history data appended for: https://www.transfermarkt.com/stefan-lex/profil/spieler/116792.
Transfer history data appended for: https://www.transfermarkt.com/martin-pusic/profil/spieler/48052.
Transfer history data appended for: https://www.transfermarkt.com/fabian-greilinger/profil/spieler/435798.
Transfer history data appended for: https://www.transfermarkt.com/marco-hiller/profil/spieler/278329.
Transfer history data appended for: https://www.transfermarkt.com/leon-klassen/profil/spieler/441987.
Transfer history data appended for: https://www.transfermarkt.com/sascha-molders/profil/spieler/17689.
Transfer history data appended for: https://www.transfermarkt.com/tim-linsbichler/profil/spieler/346850.
Transfer history data appended for: https://www.transfermarkt.com/erik-tallig/profil/spieler/454034.
Transfer history data appended for: https://www.transfermarkt.com/dennis-dressel/profil/spieler/324856.
Transfer history data appended for: https://www.transfermarkt.com/milos-cocic/profil/spieler/590480.
Transfer history data appended for: https://www.transfermarkt.com/gyorgy-szekely/profil/spieler/197169.
Transfer history data appended for: https://www.transfermarkt.com/stephan-salger/profil/spieler/45707.
Transfer history data appended for: https://www.transfermarkt.com/ahanna-agbowo/profil/spieler/516408.
Transfer history data appended for: https://www.transfermarkt.com/richard-neudecker/profil/spieler/228953.
Transfer history data appended for: https://www.transfermarkt.com/daniel-wein/profil/spieler/124571.
Transfer history data appended for: https://www.transfermarkt.com/tom-kretzschmar/profil/spieler/334127.
Transfer history data appended for: https://www.transfermarkt.com/marco-mannhardt/profil/spieler/522250.
Transfer history data appended for: https://www.transfermarkt.com/semi-belkahia/profil/spieler/315334.
Transfer history data appended for: https://www.transfermarkt.com/maxim-gresler/profil/spieler/620493.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-mielitz/profil/spieler/42079.
Transfer history data appended for: https://www.transfermarkt.com/andre-dej/profil/spieler/85036.
Transfer history data appended for: https://www.transfermarkt.com/dominik-lanius/profil/spieler/333666.
Transfer history data appended for: https://www.transfermarkt.com/michael-seaton/profil/spieler/255933.
Transfer history data appended for: https://www.transfermarkt.com/alexander-hock/profil/spieler/701336.
Transfer history data appended for: https://www.transfermarkt.com/marcel-gottschling/profil/spieler/183755.
Transfer history data appended for: https://www.transfermarkt.com/rene-klingenburg/profil/spieler/120427.
Transfer history data appended for: https://www.transfermarkt.com/yannik-bangsow/profil/spieler/335464.
Transfer history data appended for: https://www.transfermarkt.com/luca-stellwagen/profil/spieler/336975.
Transfer history data appended for: https://www.transfermarkt.com/simon-handle/profil/spieler/106265.
Transfer history data appended for: https://www.transfermarkt.com/ernesto-carratala-jimenez/profil/spieler/578537.
Transfer history data appended for: https://www.transfermarkt.com/patrick-koronkiewicz/profil/spieler/76516.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-rossmann/profil/spieler/158052.
Transfer history data appended for: https://www.transfermarkt.com/timmy-thiele/profil/spieler/95354.
Transfer history data appended for: https://www.transfermarkt.com/fabian-holthaus/profil/spieler/192841.
Transfer history data appended for: https://www.transfermarkt.com/moritz-fritz/profil/spieler/154980.
Transfer history data appended for: https://www.transfermarkt.com/kai-klefisch/profil/spieler/332624.
Transfer history data appended for: https://www.transfermarkt.com/enes-tubluk/profil/spieler/411135.
Transfer history data appended for: https://www.transfermarkt.com/mike-wunderlich/profil/spieler/26171.
Transfer history data appended for: https://www.transfermarkt.com/andre-weis/profil/spieler/58806.
Transfer history data appended for: https://www.transfermarkt.com/steven-lewerenz/profil/spieler/83251.
Transfer history data appended for: https://www.transfermarkt.com/bernard-kyere/profil/spieler/222007.
Transfer history data appended for: https://www.transfermarkt.com/kevin-holzweiler/profil/spieler/148095.
Transfer history data appended for: https://www.transfermarkt.com/sead-hajrovic/profil/spieler/111419.
Transfer history data appended for: https://www.transfermarkt.com/lucas-cueto/profil/spieler/232376.
Transfer history data appended for: https://www.transfermarkt.com/albert-bunjaku/profil/spieler/19194.
Transfer history data appended for: https://www.transfermarkt.com/dario-de-vita/profil/spieler/453756.
Transfer history data appended for: https://www.transfermarkt.com/jeremias-lorch/profil/spieler/196050.
Transfer history data appended for: https://www.transfermarkt.com/nico-neidhart/profil/spieler/158360.
Transfer history data appended for: https://www.transfermarkt.com/damian-rossbach/profil/spieler/153198.
Transfer history data appended for: https://www.transfermarkt.com/markus-kolke/profil/spieler/99451.
Transfer history data appended for: https://www.transfermarkt.com/lukas-scherff/profil/spieler/192309.
Transfer history data appended for: https://www.transfermarkt.com/john-verhoek/profil/spieler/75295.
Transfer history data appended for: https://www.transfermarkt.com/luis-klatte/profil/spieler/335996.
Transfer history data appended for: https://www.transfermarkt.com/julian-riedel/profil/spieler/82112.
Transfer history data appended for: https://www.transfermarkt.com/ben-voll/profil/spieler/453742.
Transfer history data appended for: https://www.transfermarkt.com/sven-sonnenberg/profil/spieler/339151.
Transfer history data appended for: https://www.transfermarkt.com/nils-butzen/profil/spieler/151105.
Transfer history data appended for: https://www.transfermarkt.com/oliver-daedlow/profil/spieler/447772.
Transfer history data appended for: https://www.transfermarkt.com/jan-lohmannsroben/profil/spieler/82452.
Transfer history data appended for: https://www.transfermarkt.com/pascal-breier/profil/spieler/94637.
Transfer history data appended for: https://www.transfermarkt.com/luca-schulz/profil/spieler/397695.

Transfer history data appended for: https://www.transfermarkt.com/nik-omladic/profil/spieler/75665.
Transfer history data appended for: https://www.transfermarkt.com/erik-engelhardt/profil/spieler/291537.
Transfer history data appended for: https://www.transfermarkt.com/aaron-herzog/profil/spieler/276566.
Transfer history data appended for: https://www.transfermarkt.com/bjorn-rother/profil/spieler/233980.
Transfer history data appended for: https://www.transfermarkt.com/manuel-farrona-pulido/profil/spieler/91842.
Transfer history data appended for: https://www.transfermarkt.com/max-reinthaler/profil/spieler/202838.
Transfer history data appended for: https://www.transfermarkt.com/korbinian-vollmann/profil/spieler/126293.
Transfer history data appended for: https://www.transfermarkt.com/luca-horn/profil/spieler/329814.
Transfer history data appended for: https://www.transfermarkt.com/maurice-litka/profil/spieler/188061.
Transfer history data appended for: https://www.transfermarkt.com/bentley-baxter-bahn/profil/spieler/94964.
Transfer history data appended for: https://www.transfermarkt.com/george-bello/profil/spieler/504147.
Transfer history data appended for: https://www.transfermarkt.com/jackson-conway/profil/spieler/469862.
Transfer history data appended for: https://www.transfermarkt.com/jeff-larentowicz/profil/spieler/24902.
Transfer history data appended for: https://www.transfermarkt.com/brendan-moore/profil/spieler/325389.
Transfer history data appended for: https://www.transfermarkt.com/jurgen-damm/profil/spieler/221735.
Transfer history data appended for: https://www.transfermarkt.com/alec-kann/profil/spieler/216686.
Transfer history data appended for: https://www.transfermarkt.com/miles-robinson/profil/spieler/468022.
Transfer history data appended for: https://www.transfermarkt.com/franco-escobar/profil/spieler/338169.
Transfer history data appended for: https://www.transfermarkt.com/edgar-castillo/profil/spieler/53542.
Transfer history data appended for: https://www.transfermarkt.com/josef-martinez/profil/spieler/162569.
Transfer history data appended for: https://www.transfermarkt.com/brad-guzan/profil/spieler/39471.
Transfer history data appended for: https://www.transfermarkt.com/marcelino-moreno/profil/spieler/456617.
Transfer history data appended for: https://www.transfermarkt.com/jake-mulraney/profil/spieler/264206.
Transfer history data appended for: https://www.transfermarkt.com/fernando-meza/profil/spieler/76837.
Transfer history data appended for: https://www.transfermarkt.com/jon-gallagher/profil/spieler/562553.
Transfer history data appended for: https://www.transfermarkt.com/laurence-wyke/profil/spieler/635633.
Transfer history data appended for: https://www.transfermarkt.com/ezequiel-barco/profil/spieler/456623.
Transfer history data appended for: https://www.transfermarkt.com/matheus-rossetto/profil/spieler/445000.
Transfer history data appended for: https://www.transfermarkt.com/eric-remedi/profil/spieler/362364.
Transfer history data appended for: https://www.transfermarkt.com/lagos-kunga/profil/spieler/471591.
Transfer history data appended for: https://www.transfermarkt.com/george-campbell/profil/spieler/585769.
Transfer history data appended for: https://www.transfermarkt.com/jj-williams/profil/spieler/644786.
Transfer history data appended for: https://www.transfermarkt.com/manuel-castro/profil/spieler/335984.
Transfer history data appended for: https://www.transfermarkt.com/erick-torres/profil/spieler/170016.
Transfer history data appended for: https://www.transfermarkt.com/brooks-lennon/profil/spieler/345627.
Transfer history data appended for: https://www.transfermarkt.com/andrew-carleton/profil/spieler/370841.
Transfer history data appended for: https://www.transfermarkt.com/adam-jahn/profil/spieler/260858.
Transfer history data appended for: https://www.transfermarkt.com/emerson-hyndman/profil/spieler/223047.
Transfer history data appended for: https://www.transfermarkt.com/anton-walkes/profil/spieler/307763.
Transfer history data appended for: https://www.transfermarkt.com/mo-adams/profil/spieler/349781.
Transfer history data appended for: https://www.transfermarkt.com/tyler-wolff/profil/spieler/763648.
Transfer history data appended for: https://www.transfermarkt.com/cole-bassett/profil/spieler/605144.
Transfer history data appended for: https://www.transfermarkt.com/abdul-rwatubyaye/profil/spieler/368580.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-anderson/profil/spieler/504146.
Transfer history data appended for: https://www.transfermarkt.com/andre-rawls/profil/spieler/354887.
Transfer history data appended for: https://www.transfermarkt.com/drew-moor/profil/spieler/39503.
Transfer history data appended for: https://www.transfermarkt.com/steven-beitashour/profil/spieler/145114.
Transfer history data appended for: https://www.transfermarkt.com/will-vint/profil/spieler/596219.
Transfer history data appended for: https://www.transfermarkt.com/braian-galvan/profil/spieler/533566.
Transfer history data appended for: https://www.transfermarkt.com/danny-wilson/profil/spieler/103819.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-lewis/profil/spieler/479610.
Transfer history data appended for: https://www.transfermarkt.com/diego-rubio/profil/spieler/179308.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-kelly/profil/spieler/430863.
Transfer history data appended for: https://www.transfermarkt.com/kellyn-acosta/profil/spieler/189895.
Transfer history data appended for: https://www.transfermarkt.com/clint-irwin/profil/spieler/222110.
Transfer history data appended for: https://www.transfermarkt.com/abraham-rodriguez/profil/spieler/659765.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-mezquida/profil/spieler/99993.
Transfer history data appended for: https://www.transfermarkt.com/sam-vines/profil/spieler/535282.
Transfer history data appended for: https://www.transfermarkt.com/collen-warner/profil/spieler/147418.
Transfer history data appended for: https://www.transfermarkt.com/younes-namli/profil/spieler/227039.
Transfer history data appended for: https://www.transfermarkt.com/matt-hundley/profil/spieler/637277.
Transfer history data appended for: https://www.transfermarkt.com/deklan-wynne/profil/spieler/298228.
Transfer history data appended for: https://www.transfermarkt.com/kortne-ford/profil/spieler/480719.
Transfer history data appended for: https://www.transfermarkt.com/andre-shinyashiki/profil/spieler/636331.
Transfer history data appended for: https://www.transfermarkt.com/auston-trusty/profil/spieler/389253.
Transfer history data appended for: https://www.transfermarkt.com/keegan-rosenberry/profil/spieler/268302.
Transfer history data appended for: https://www.transfermarkt.com/jack-price/profil/spieler/129062.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-benezet/profil/spieler/164230.
Transfer history data appended for: https://www.transfermarkt.com/niki-jackson/profil/spieler/544390.
Transfer history data appended for: https://www.transfermarkt.com/derrick-etienne-jr-/profil/spieler/354763.
Transfer history data appended for: https://www.transfermarkt.com/darlington-nagbe/profil/spieler/173489.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-mensah/profil/spieler/110622.
Transfer history data appended for: https://www.transfermarkt.com/fatai-alashe/profil/spieler/268280.
Transfer history data appended for: https://www.transfermarkt.com/josh-williams/profil/spieler/163492.
Transfer history data appended for: https://www.transfermarkt.com/chris-cadden/profil/spieler/277782.
Transfer history data appended for: https://www.transfermarkt.com/luis-diaz/profil/spieler/538984.
Transfer history data appended for: https://www.transfermarkt.com/artur/profil/spieler/435488.
Transfer history data appended for: https://www.transfermarkt.com/aboubacar-keita/profil/spieler/638733.
Transfer history data appended for: https://www.transfermarkt.com/eloy-room/profil/spieler/79294.
Transfer history data appended for: https://www.transfermarkt.com/grant-lillard/profil/spieler/570559.

Transfer history data appended for: https://www.transfermarkt.com/aidan-morris/profil/spieler/513968.
Transfer history data appended for: https://www.transfermarkt.com/andrew-tarbell/profil/spieler/417349.
Transfer history data appended for: https://www.transfermarkt.com/gyasi-zardes/profil/spieler/254230.
Transfer history data appended for: https://www.transfermarkt.com/fanendo-adi/profil/spieler/79654.
Transfer history data appended for: https://www.transfermarkt.com/krisztian-nemeth/profil/spieler/48262.
Transfer history data appended for: https://www.transfermarkt.com/lucas-zelarayan/profil/spieler/230030.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-berhalter/profil/spieler/734761.
Transfer history data appended for: https://www.transfermarkt.com/youness-mokhtar/profil/spieler/83946.
Transfer history data appended for: https://www.transfermarkt.com/miguel-berry/profil/spieler/735115.
Transfer history data appended for: https://www.transfermarkt.com/waylon-francis/profil/spieler/211587.
Transfer history data appended for: https://www.transfermarkt.com/jordan-hamilton/profil/spieler/294707.
Transfer history data appended for: https://www.transfermarkt.com/jon-kempin/profil/spieler/161010.
Transfer history data appended for: https://www.transfermarkt.com/matt-lampson/profil/spieler/210682.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-boateng/profil/spieler/279681.
Transfer history data appended for: https://www.transfermarkt.com/vito-wormgoor/profil/spieler/45543.
Transfer history data appended for: https://www.transfermarkt.com/hector-jimenez/profil/spieler/178226.
Transfer history data appended for: https://www.transfermarkt.com/pedro-santos/profil/spieler/131163.
Transfer history data appended for: https://www.transfermarkt.com/david-jensen/profil/spieler/78819.
Transfer history data appended for: https://www.transfermarkt.com/caden-clark/profil/spieler/742297.
Transfer history data appended for: https://www.transfermarkt.com/jason-pendant/profil/spieler/272639.
Transfer history data appended for: https://www.transfermarkt.com/omir-fernandez/profil/spieler/467271.
Transfer history data appended for: https://www.transfermarkt.com/kyle-duncan/profil/spieler/349699.
Transfer history data appended for: https://www.transfermarkt.com/aaron-long/profil/spieler/271072.
Transfer history data appended for: https://www.transfermarkt.com/marc-rzatkowski/profil/spieler/53681.
Transfer history data appended for: https://www.transfermarkt.com/sean-davis/profil/spieler/271184.
Transfer history data appended for: https://www.transfermarkt.com/jared-stroud/profil/spieler/573442.
Transfer history data appended for: https://www.transfermarkt.com/patrick-seagrist/profil/spieler/735116.
Transfer history data appended for: https://www.transfermarkt.com/florian-valot/profil/spieler/170465.
Transfer history data appended for: https://www.transfermarkt.com/cristhian-casseres-jr-/profil/spieler/467632.
Transfer history data appended for: https://www.transfermarkt.com/mandela-egbo/profil/spieler/258917.
Transfer history data appended for: https://www.transfermarkt.com/brian-white/profil/spieler/562555.
Transfer history data appended for: https://www.transfermarkt.com/tom-barlow/profil/spieler/509916.
Transfer history data appended for: https://www.transfermarkt.com/mathias-jorgensen/profil/spieler/542796.
Transfer history data appended for: https://www.transfermarkt.com/dru-yearwood/profil/spieler/526597.
Transfer history data appended for: https://www.transfermarkt.com/chris-lema/profil/spieler/375563.
Transfer history data appended for: https://www.transfermarkt.com/john-tolkin/profil/spieler/683812.
Transfer history data appended for: https://www.transfermarkt.com/amro-tarek/profil/spieler/158997.
Transfer history data appended for: https://www.transfermarkt.com/samuel-tetteh/profil/spieler/358752.
Transfer history data appended for: https://www.transfermarkt.com/tim-parker/profil/spieler/354737.
Transfer history data appended for: https://www.transfermarkt.com/kendall-mcintosh/profil/spieler/189890.
Transfer history data appended for: https://www.transfermarkt.com/ben-mines/profil/spieler/455564.
Transfer history data appended for: https://www.transfermarkt.com/ryan-meara/profil/spieler/213051.
Transfer history data appended for: https://www.transfermarkt.com/kaku/profil/spieler/355817.
Transfer history data appended for: https://www.transfermarkt.com/sean-nealis/profil/spieler/644798.
Transfer history data appended for: https://www.transfermarkt.com/boniek-garcia/profil/spieler/62241.
Transfer history data appended for: https://www.transfermarkt.com/ronaldo-pena/profil/spieler/309487.
Transfer history data appended for: https://www.transfermarkt.com/nico-lemoine/profil/spieler/393324.
Transfer history data appended for: https://www.transfermarkt.com/aljaz-struna/profil/spieler/108119.
Transfer history data appended for: https://www.transfermarkt.com/victor-cabrera/profil/spieler/353463.
Transfer history data appended for: https://www.transfermarkt.com/christian-ramirez/profil/spieler/236590.
Transfer history data appended for: https://www.transfermarkt.com/erik-mccue/profil/spieler/629362.
Transfer history data appended for: https://www.transfermarkt.com/darwin-ceren/profil/spieler/229330.
Transfer history data appended for: https://www.transfermarkt.com/sam-junqua/profil/spieler/644781.
Transfer history data appended for: https://www.transfermarkt.com/cody-cropper/profil/spieler/170540.
Transfer history data appended for: https://www.transfermarkt.com/adam-lundqvist/profil/spieler/225676.
Transfer history data appended for: https://www.transfermarkt.com/kyle-adams/profil/spieler/562306.
Transfer history data appended for: https://www.transfermarkt.com/matias-vera/profil/spieler/368801.
Transfer history data appended for: https://www.transfermarkt.com/memo-rodriguez/profil/spieler/367063.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-fuenmayor/profil/spieler/309910.
Transfer history data appended for: https://www.transfermarkt.com/mauro-manotas/profil/spieler/325614.
Transfer history data appended for: https://www.transfermarkt.com/michael-nelson/profil/spieler/562558.
Transfer history data appended for: https://www.transfermarkt.com/jose-bizama/profil/spieler/386478.
Transfer history data appended for: https://www.transfermarkt.com/marko-maric/profil/spieler/183793.
Transfer history data appended for: https://www.transfermarkt.com/maynor-figueroa/profil/spieler/62240.
Transfer history data appended for: https://www.transfermarkt.com/ariel-lassiter/profil/spieler/329713.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-palomino/profil/spieler/469859.
Transfer history data appended for: https://www.transfermarkt.com/tomas-martinez/profil/spieler/271438.
Transfer history data appended for: https://www.transfermarkt.com/zarek-valentin/profil/spieler/173492.
Transfer history data appended for: https://www.transfermarkt.com/michael-salazar/profil/spieler/277353.
Transfer history data appended for: https://www.transfermarkt.com/wilfried-zahibo/profil/spieler/198529.
Transfer history data appended for: https://www.transfermarkt.com/niko-hansen/profil/spieler/482613.
Transfer history data appended for: https://www.transfermarkt.com/darwin-quintero/profil/spieler/55666.
Transfer history data appended for: https://www.transfermarkt.com/benji-michel/profil/spieler/627183.
Transfer history data appended for: https://www.transfermarkt.com/alex-de-john/profil/spieler/318222.
Transfer history data appended for: https://www.transfermarkt.com/kyle-smith/profil/spieler/429271.
Transfer history data appended for: https://www.transfermarkt.com/junior-urso/profil/spieler/144789.
Transfer history data appended for: https://www.transfermarkt.com/daryl-dike/profil/spieler/638741.
Transfer history data appended for: https://www.transfermarkt.com/brian-rowe/profil/spieler/213545.
Transfer history data appended for: https://www.transfermarkt.com/dom-dwyer/profil/spieler/105185.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-schlegel/profil/spieler/504258.

Transfer history data appended for: https://www.transfermarkt.com/oriol-rosell/profil/spieler/166628.
Transfer history data appended for: https://www.transfermarkt.com/nani/profil/spieler/33706.
Transfer history data appended for: https://www.transfermarkt.com/pedro-gallese/profil/spieler/95172.
Transfer history data appended for: https://www.transfermarkt.com/kamal-miller/profil/spieler/487504.
Transfer history data appended for: https://www.transfermarkt.com/matheus-aias/profil/spieler/369706.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/david-loera/profil/spieler/402304.
Transfer history data appended for: https://www.transfermarkt.com/tesho-akindele/profil/spieler/307720.
Transfer history data appended for: https://www.transfermarkt.com/antonio-carlos/profil/spieler/207446.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/jordan-bender/profil/spieler/633780.
Transfer history data appended for: https://www.transfermarkt.com/michael-halliday/profil/spieler/750532.
Transfer history data appended for: https://www.transfermarkt.com/andres-perea/profil/spieler/491536.
Transfer history data appended for: https://www.transfermarkt.com/alexander-alvarado/profil/spieler/379838.
Transfer history data appended for: https://www.transfermarkt.com/robinho/profil/spieler/347184.
Transfer history data appended for: https://www.transfermarkt.com/joao-moutinho/profil/spieler/461906.
Transfer history data appended for: https://www.transfermarkt.com/ruan/profil/spieler/520491.
Transfer history data appended for: https://www.transfermarkt.com/joey-dezart/profil/spieler/637450.
Transfer history data appended for: https://www.transfermarkt.com/mason-stajduhar/profil/spieler/401361.
Transfer history data appended for: https://www.transfermarkt.com/jhegson-mendez/profil/spieler/330682.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-pereyra/profil/spieler/102452.
Transfer history data appended for: https://www.transfermarkt.com/chris-mueller/profil/spieler/562387.
Transfer history data appended for: https://www.transfermarkt.com/robin-jansson/profil/spieler/151678.
Transfer history data appended for: https://www.transfermarkt.com/jordan-morris/profil/spieler/337807.
Transfer history data appended for: https://www.transfermarkt.com/will-bruin/profil/spieler/173486.
Transfer history data appended for: https://www.transfermarkt.com/cristian-roldan/profil/spieler/354792.
Transfer history data appended for: https://www.transfermarkt.com/raul-ruidiaz/profil/spieler/129724.
Transfer history data appended for: https://www.transfermarkt.com/kelvin-leerdam/profil/spieler/92936.
Transfer history data appended for: https://www.transfermarkt.com/gustav-svensson/profil/spieler/41362.
Transfer history data appended for: https://www.transfermarkt.com/miguel-ibarra/profil/spieler/220521.
Transfer history data appended for: https://www.transfermarkt.com/jordy-delem/profil/spieler/269944.
Transfer history data appended for: https://www.transfermarkt.com/joevin-jones/profil/spieler/154194.
Transfer history data appended for: https://www.transfermarkt.com/ethan-dobbelaere/profil/spieler/688746.
Transfer history data appended for: https://www.transfermarkt.com/justin-dhillon/profil/spieler/242320.
Transfer history data appended for: https://www.transfermarkt.com/shandon-hopeau/profil/spieler/463777.
Transfer history data appended for: https://www.transfermarkt.com/stefan-cleveland/profil/spieler/482647.
Transfer history data appended for: https://www.transfermarkt.com/shane-oneill/profil/spieler/229912.
Transfer history data appended for: https://www.transfermarkt.com/xavier-arreaga/profil/spieler/323854.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-lodeiro/profil/spieler/72653.
Transfer history data appended for: https://www.transfermarkt.com/roman-torres/profil/spieler/74182.
Transfer history data appended for: https://www.transfermarkt.com/brad-smith/profil/spieler/175745.
Transfer history data appended for: https://www.transfermarkt.com/alfonso-ocampo-chavez/profil/spieler/504214.
Transfer history data appended for: https://www.transfermarkt.com/danny-leyva/profil/spieler/623444.
Transfer history data appended for: https://www.transfermarkt.com/stefan-frei/profil/spieler/99617.
Transfer history data appended for: https://www.transfermarkt.com/nouhou-tolo/profil/spieler/436332.
Transfer history data appended for: https://www.transfermarkt.com/josh-atencio/profil/spieler/504205.
Transfer history data appended for: https://www.transfermarkt.com/trey-muse/profil/spieler/497575.
Transfer history data appended for: https://www.transfermarkt.com/yeimar-gomez-andrade/profil/spieler/343359.
Transfer history data appended for: https://www.transfermarkt.com/alex-roldan/profil/spieler/562560.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-medranda/profil/spieler/283624.
Transfer history data appended for: https://www.transfermarkt.com/joao-paulo/profil/spieler/135984.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-lletget/profil/spieler/175996.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-perez/profil/spieler/694158.
Transfer history data appended for: https://www.transfermarkt.com/julian-araujo/profil/spieler/513970.
Transfer history data appended for: https://www.transfermarkt.com/joe-corona/profil/spieler/162940.
Transfer history data appended for: https://www.transfermarkt.com/eric-lopez/profil/spieler/332707.
Transfer history data appended for: https://www.transfermarkt.com/rolf-feltscher/profil/spieler/52590.
Transfer history data appended for: https://www.transfermarkt.com/cristian-pavon/profil/spieler/373170.
Transfer history data appended for: https://www.transfermarkt.com/ethan-zubak/profil/spieler/375617.
Transfer history data appended for: https://www.transfermarkt.com/carlos-harvey/profil/spieler/628806.
Transfer history data appended for: https://www.transfermarkt.com/chicharito/profil/spieler/50935.
Transfer history data appended for: https://www.transfermarkt.com/cameron-dunbar/profil/spieler/692091.
Transfer history data appended for: https://www.transfermarkt.com/perry-kitchen/profil/spieler/131183.
Transfer history data appended for: https://www.transfermarkt.com/nick-depuy/profil/spieler/482622.
Transfer history data appended for: https://www.transfermarkt.com/kai-koreniuk/profil/spieler/315141.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-dos-santos/profil/spieler/60445.
Transfer history data appended for: https://www.transfermarkt.com/justin-vom-steeg/profil/spieler/455856.
Transfer history data appended for: https://www.transfermarkt.com/david-bingham/profil/spieler/176157.
Transfer history data appended for: https://www.transfermarkt.com/emil-cuello/profil/spieler/636466.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-klinsmann/profil/spieler/334992.
Transfer history data appended for: https://www.transfermarkt.com/gordon-wild/profil/spieler/215765.
Transfer history data appended for: https://www.transfermarkt.com/daniel-steres/profil/spieler/227909.
Transfer history data appended for: https://www.transfermarkt.com/diedie-traore/profil/spieler/494934.
Transfer history data appended for: https://www.transfermarkt.com/efrain-alvarez/profil/spieler/504113.
Transfer history data appended for: https://www.transfermarkt.com/sacha-kljestan/profil/spieler/39475.
Transfer history data appended for: https://www.transfermarkt.com/danilo-acosta/profil/spieler/375074.
Transfer history data appended for: https://www.transfermarkt.com/giancarlo-gonzalez/profil/spieler/111893.
Transfer history data appended for: https://www.transfermarkt.com/ben-sweat/profil/spieler/268310.
Transfer history data appended for: https://www.transfermarkt.com/andres-reyes/profil/spieler/582995.
Transfer history data appended for: https://www.transfermarkt.com/lewis-morgan/profil/spieler/311351.
Transfer history data appended for: https://www.transfermarkt.com/brek-shea/profil/spieler/71107.
Transfer history data appended for: https://www.transfermarkt.com/rodolfo-pizarro/profil/spieler/234918.
Transfer history data appended for: https://www.transfermarkt.com/wil-trapp/profil/spieler/199559.
Transfer history data appended for: https://www.transfermarkt.com/julian-carranza/profil/spieler/491707.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-higuain/profil/spieler/39153.
Transfer history data appended for: https://www.transfermarkt.com/denso-ulysse/profil/spieler/496851.
Transfer history data appended for: https://www.transfermarkt.com/dylan-nealis/profil/spieler/638385.
Transfer history data appended for: https://www.transfermarkt.com/robbie-robinson/profil/spieler/496613.
Transfer history data appended for: https://www.transfermarkt.com/luis-robles/profil/spieler/47289.
Transfer history data appended for: https://www.transfermarkt.com/jorge-figal/profil/spieler/334055.

Transfer history data appended for: https://www.transfermarkt.com/john-mccarthy/profil/spieler/271718.
Transfer history data appended for: https://www.transfermarkt.com/david-norman-jr-/profil/spieler/483310.
Transfer history data appended for: https://www.transfermarkt.com/alvas-powell/profil/spieler/189772.
Transfer history data appended for: https://www.transfermarkt.com/juan-agudelo/profil/spieler/131171.
Transfer history data appended for: https://www.transfermarkt.com/jerome-kiesewetter/profil/spieler/94167.
Transfer history data appended for: https://www.transfermarkt.com/matias-pellegrini/profil/spieler/606267.
Transfer history data appended for: https://www.transfermarkt.com/a-j-delagarza/profil/spieler/105997.
Transfer history data appended for: https://www.transfermarkt.com/victor-ulloa/profil/spieler/158123.
Transfer history data appended for: https://www.transfermarkt.com/jay-chapman/profil/spieler/189032.
Transfer history data appended for: https://www.transfermarkt.com/mikey-ambrose/profil/spieler/255918.
Transfer history data appended for: https://www.transfermarkt.com/george-acosta/profil/spieler/370975.
Transfer history data appended for: https://www.transfermarkt.com/drake-callender/profil/spieler/723561.
Transfer history data appended for: https://www.transfermarkt.com/roberto-puncec/profil/spieler/92120.
Transfer history data appended for: https://www.transfermarkt.com/felipe-hernandez/profil/spieler/464518.
Transfer history data appended for: https://www.transfermarkt.com/alan-pulido/profil/spieler/143045.
Transfer history data appended for: https://www.transfermarkt.com/johnny-russell/profil/spieler/55494.
Transfer history data appended for: https://www.transfermarkt.com/wilson-harris/profil/spieler/576847.
Transfer history data appended for: https://www.transfermarkt.com/amadou-dia/profil/spieler/354912.
Transfer history data appended for: https://www.transfermarkt.com/cameron-duke/profil/spieler/469850.
Transfer history data appended for: https://www.transfermarkt.com/graham-zusi/profil/spieler/108353.
Transfer history data appended for: https://www.transfermarkt.com/matt-besler/profil/spieler/105975.
Transfer history data appended for: https://www.transfermarkt.com/jaylin-lindsey/profil/spieler/370970.
Transfer history data appended for: https://www.transfermarkt.com/richard-sanchez/profil/spieler/178861.
Transfer history data appended for: https://www.transfermarkt.com/tyler-freeman/profil/spieler/623183.
Transfer history data appended for: https://www.transfermarkt.com/wan-kuzain/profil/spieler/464344.
Transfer history data appended for: https://www.transfermarkt.com/gadi-kinda/profil/spieler/200560.
Transfer history data appended for: https://www.transfermarkt.com/eric-dick/profil/spieler/520238.
Transfer history data appended for: https://www.transfermarkt.com/gerso/profil/spieler/197157.
Transfer history data appended for: https://www.transfermarkt.com/daniel-salloi/profil/spieler/321946.
Transfer history data appended for: https://www.transfermarkt.com/roger-espinoza/profil/spieler/71096.
Transfer history data appended for: https://www.transfermarkt.com/felipe-gutierrez/profil/spieler/133089.
Transfer history data appended for: https://www.transfermarkt.com/gianluca-busio/profil/spieler/504209.
Transfer history data appended for: https://www.transfermarkt.com/john-pulskamp/profil/spieler/577858.
Transfer history data appended for: https://www.transfermarkt.com/erik-hurtado/profil/spieler/255922.
Transfer history data appended for: https://www.transfermarkt.com/tim-melia/profil/spieler/119722.
Transfer history data appended for: https://www.transfermarkt.com/luis-martins/profil/spieler/187896.
Transfer history data appended for: https://www.transfermarkt.com/winston-reid/profil/spieler/37526.
Transfer history data appended for: https://www.transfermarkt.com/ilie-sanchez/profil/spieler/65298.
Transfer history data appended for: https://www.transfermarkt.com/andreu-fontas/profil/spieler/65237.
Transfer history data appended for: https://www.transfermarkt.com/khiry-shelton/profil/spieler/354609.
Transfer history data appended for: https://www.transfermarkt.com/graham-smith/profil/spieler/562557.
Transfer history data appended for: https://www.transfermarkt.com/spencer-richey/profil/spieler/131190.
Transfer history data appended for: https://www.transfermarkt.com/tommy-mccabe/profil/spieler/315772.
Transfer history data appended for: https://www.transfermarkt.com/kendall-waston/profil/spieler/195540.
Transfer history data appended for: https://www.transfermarkt.com/greg-garza/profil/spieler/118318.
Transfer history data appended for: https://www.transfermarkt.com/kamohelo-mokotjo/profil/spieler/108601.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-barreal/profil/spieler/613873.
Transfer history data appended for: https://www.transfermarkt.com/brandon-vazquez/profil/spieler/389255.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-deplagne/profil/spieler/127128.
Transfer history data appended for: https://www.transfermarkt.com/caleb-stanko/profil/spieler/190269.
Transfer history data appended for: https://www.transfermarkt.com/frankie-amaya/profil/spieler/575368.
Transfer history data appended for: https://www.transfermarkt.com/siem-de-jong/profil/spieler/45509.
Transfer history data appended for: https://www.transfermarkt.com/ben-lundt/profil/spieler/236792.
Transfer history data appended for: https://www.transfermarkt.com/haris-medunjanin/profil/spieler/30666.
Transfer history data appended for: https://www.transfermarkt.com/rashawn-dally/profil/spieler/652007.
Transfer history data appended for: https://www.transfermarkt.com/nick-hagglund/profil/spieler/307890.
Transfer history data appended for: https://www.transfermarkt.com/hassan-ndam/profil/spieler/485529.
Transfer history data appended for: https://www.transfermarkt.com/jurgen-locadia/profil/spieler/166240.
Transfer history data appended for: https://www.transfermarkt.com/zico-bailey/profil/spieler/370980.
Transfer history data appended for: https://www.transfermarkt.com/allan-cruz/profil/spieler/313234.
Transfer history data appended for: https://www.transfermarkt.com/andrew-gutman/profil/spieler/638408.
Transfer history data appended for: https://www.transfermarkt.com/tom-pettersson/profil/spieler/95377.
Transfer history data appended for: https://www.transfermarkt.com/maikel-van-der-werff/profil/spieler/81778.
Transfer history data appended for: https://www.transfermarkt.com/franko-kovacevic/profil/spieler/425916.
Transfer history data appended for: https://www.transfermarkt.com/saad-abdul-salaam/profil/spieler/270532.
Transfer history data appended for: https://www.transfermarkt.com/rey-ortiz/profil/spieler/404319.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-mclaughlin/profil/spieler/210368.
Transfer history data appended for: https://www.transfermarkt.com/beckham-sunderland/profil/spieler/824176.
Transfer history data appended for: https://www.transfermarkt.com/bobby-edwards/profil/spieler/713500.
Transfer history data appended for: https://www.transfermarkt.com/yimmi-chara/profil/spieler/165361.
Transfer history data appended for: https://www.transfermarkt.com/larrys-mabiala/profil/spieler/55366.
Transfer history data appended for: https://www.transfermarkt.com/aljaz-ivacic/profil/spieler/231923.
Transfer history data appended for: https://www.transfermarkt.com/jorge-villafana/profil/spieler/59531.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-blanco/profil/spieler/54576.
Transfer history data appended for: https://www.transfermarkt.com/marvin-loria/profil/spieler/298207.
Transfer history data appended for: https://www.transfermarkt.com/julio-cascante/profil/spieler/194909.
Transfer history data appended for: https://www.transfermarkt.com/cristhian-paredes/profil/spieler/401728.
Transfer history data appended for: https://www.transfermarkt.com/marco-farfan/profil/spieler/429443.
Transfer history data appended for: https://www.transfermarkt.com/blake-bodily/profil/spieler/381026.
Transfer history data appended for: https://www.transfermarkt.com/diego-valeri/profil/spieler/54588.

Transfer history data appended for: https://www.transfermarkt.com/andy-polo/profil/spieler/189236.
Transfer history data appended for: https://www.transfermarkt.com/felipe-mora/profil/spieler/176927.
Transfer history data appended for: https://www.transfermarkt.com/steve-clark/profil/spieler/141704.
Transfer history data appended for: https://www.transfermarkt.com/bill-tuiloma/profil/spieler/172333.
Transfer history data appended for: https://www.transfermarkt.com/eryk-williamson/profil/spieler/349706.
Transfer history data appended for: https://www.transfermarkt.com/jaroslaw-niezgoda/profil/spieler/269446.
Transfer history data appended for: https://www.transfermarkt.com/diego-chara/profil/spieler/77163.
Transfer history data appended for: https://www.transfermarkt.com/andres-flores/profil/spieler/125387.
Transfer history data appended for: https://www.transfermarkt.com/pablo-bonilla/profil/spieler/486174.
Transfer history data appended for: https://www.transfermarkt.com/renzo-zambrano/profil/spieler/236310.
Transfer history data appended for: https://www.transfermarkt.com/tomas-conechny/profil/spieler/401571.
Transfer history data appended for: https://www.transfermarkt.com/dairon-asprilla/profil/spieler/260381.
Transfer history data appended for: https://www.transfermarkt.com/zac-mcgraw/profil/spieler/788522.
Transfer history data appended for: https://www.transfermarkt.com/chris-duvall/profil/spieler/307887.
Transfer history data appended for: https://www.transfermarkt.com/jeff-attinella/profil/spieler/179323.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-ebobisse/profil/spieler/460529.
Transfer history data appended for: https://www.transfermarkt.com/thomas-hasal/profil/spieler/487505.
Transfer history data appended for: https://www.transfermarkt.com/evan-bush/profil/spieler/148916.
Transfer history data appended for: https://www.transfermarkt.com/russell-teibert/profil/spieler/103627.
Transfer history data appended for: https://www.transfermarkt.com/theo-bair/profil/spieler/501709.
Transfer history data appended for: https://www.transfermarkt.com/damiano-pecile/profil/spieler/718088.
Transfer history data appended for: https://www.transfermarkt.com/cristian-gutierrez/profil/spieler/385104.
Transfer history data appended for: https://www.transfermarkt.com/maxime-crepeau/profil/spieler/189014.
Transfer history data appended for: https://www.transfermarkt.com/ali-adnan/profil/spieler/261611.
Transfer history data appended for: https://www.transfermarkt.com/georges-mukumbilwa/profil/spieler/699184.
Transfer history data appended for: https://www.transfermarkt.com/lucas-cavallini/profil/spieler/221038.
Transfer history data appended for: https://www.transfermarkt.com/ryan-raposo/profil/spieler/638798.
Transfer history data appended for: https://www.transfermarkt.com/patrick-metcalfe/profil/spieler/501710.
Transfer history data appended for: https://www.transfermarkt.com/isaac-boehmer/profil/spieler/802143.
Transfer history data appended for: https://www.transfermarkt.com/jasser-khmiri/profil/spieler/422666.
Transfer history data appended for: https://www.transfermarkt.com/gianfranco-facchineri/profil/spieler/718090.
Transfer history data appended for: https://www.transfermarkt.com/janio-bikel/profil/spieler/288121.
Transfer history data appended for: https://www.transfermarkt.com/tosaint-ricketts/profil/spieler/94579.
Transfer history data appended for: https://www.transfermarkt.com/jake-nerwinski/profil/spieler/482612.
Transfer history data appended for: https://www.transfermarkt.com/derek-cornelius/profil/spieler/328609.
Transfer history data appended for: https://www.transfermarkt.com/erik-godoy/profil/spieler/225479.
Transfer history data appended for: https://www.transfermarkt.com/michael-baldisimo/profil/spieler/493611.
Transfer history data appended for: https://www.transfermarkt.com/andy-rose/profil/spieler/213544.
Transfer history data appended for: https://www.transfermarkt.com/bryan-meredith/profil/spieler/192399.
Transfer history data appended for: https://www.transfermarkt.com/david-milinkovic/profil/spieler/354725.
Transfer history data appended for: https://www.transfermarkt.com/ranko-veselinovic/profil/spieler/336381.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-guido/profil/spieler/189883.
Transfer history data appended for: https://www.transfermarkt.com/tristan-blackmon/profil/spieler/562383.
Transfer history data appended for: https://www.transfermarkt.com/latif-blessing/profil/spieler/398238.
Transfer history data appended for: https://www.transfermarkt.com/carlos-vela/profil/spieler/35773.
Transfer history data appended for: https://www.transfermarkt.com/kenneth-vermeer/profil/spieler/30290.
Transfer history data appended for: https://www.transfermarkt.com/eduard-atuesta/profil/spieler/469135.
Transfer history data appended for: https://www.transfermarkt.com/erik-duenas/profil/spieler/792335.
Transfer history data appended for: https://www.transfermarkt.com/philip-ejimadu/profil/spieler/575370.
Transfer history data appended for: https://www.transfermarkt.com/adrien-perez/profil/spieler/589774.
Transfer history data appended for: https://www.transfermarkt.com/eddie-segura/profil/spieler/459466.
Transfer history data appended for: https://www.transfermarkt.com/bryce-duke/profil/spieler/739675.
Transfer history data appended for: https://www.transfermarkt.com/jose-cifuentes/profil/spieler/450211.
Transfer history data appended for: https://www.transfermarkt.com/christian-torres/profil/spieler/792334.
Transfer history data appended for: https://www.transfermarkt.com/diego-palacios/profil/spieler/425567.
Transfer history data appended for: https://www.transfermarkt.com/pablo-sisniega/profil/spieler/351477.
Transfer history data appended for: https://www.transfermarkt.com/mark-anthony-kaye/profil/spieler/343553.
Transfer history data appended for: https://www.transfermarkt.com/bradley-wright-phillips/profil/spieler/28813.
Transfer history data appended for: https://www.transfermarkt.com/andy-najar/profil/spieler/145838.
Transfer history data appended for: https://www.transfermarkt.com/mark-segbers/profil/spieler/562390.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-el-munir/profil/spieler/202764.
Transfer history data appended for: https://www.transfermarkt.com/antonio-leone/profil/spieler/745454.
Transfer history data appended for: https://www.transfermarkt.com/dejan-jakovic/profil/spieler/77360.
Transfer history data appended for: https://www.transfermarkt.com/kwadwo-opoku/profil/spieler/565774.
Transfer history data appended for: https://www.transfermarkt.com/danny-musovski/profil/spieler/562494.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-traore/profil/spieler/802341.
Transfer history data appended for: https://www.transfermarkt.com/francisco-ginella/profil/spieler/538091.
Transfer history data appended for: https://www.transfermarkt.com/jordan-harvey/profil/spieler/39354.
Transfer history data appended for: https://www.transfermarkt.com/mike-azira/profil/spieler/228498.
Transfer history data appended for: https://www.transfermarkt.com/brian-gutierrez/profil/spieler/724443.
Transfer history data appended for: https://www.transfermarkt.com/kenneth-kronholm/profil/spieler/18971.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-slonina/profil/spieler/656316.
Transfer history data appended for: https://www.transfermarkt.com/ignacio-aliseda/profil/spieler/604616.
Transfer history data appended for: https://www.transfermarkt.com/robert-beric/profil/spieler/91415.
Transfer history data appended for: https://www.transfermarkt.com/francisco-calvo/profil/spieler/188470.
Transfer history data appended for: https://www.transfermarkt.com/wyatt-omsberg/profil/spieler/562554.
Transfer history data appended for: https://www.transfermarkt.com/carlos-teran/profil/spieler/649184.
Transfer history data appended for: https://www.transfermarkt.com/przemyslaw-frankowski/profil/spieler/239743.
Transfer history data appended for: https://www.transfermarkt.com/johan-kappelhof/profil/spieler/124888.
Transfer history data appended for: https://www.transfermarkt.com/fabian-herbers/profil/spieler/196077.

Transfer history data appended for: https://www.transfermarkt.com/miguel-angel-navarro/profil/spieler/509390.
Transfer history data appended for: https://www.transfermarkt.com/nicholas-slonina/profil/spieler/730128.
Transfer history data appended for: https://www.transfermarkt.com/c-j-sapong/profil/spieler/174724.
Transfer history data appended for: https://www.transfermarkt.com/boris-sekulic/profil/spieler/217709.
Transfer history data appended for: https://www.transfermarkt.com/andre-reynolds-ii/profil/spieler/647501.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-medran/profil/spieler/253839.
Transfer history data appended for: https://www.transfermarkt.com/javier-casas/profil/spieler/724411.
Transfer history data appended for: https://www.transfermarkt.com/djordje-mihailovic/profil/spieler/484756.
Transfer history data appended for: https://www.transfermarkt.com/brandt-bronico/profil/spieler/271183.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-bornstein/profil/spieler/39454.
Transfer history data appended for: https://www.transfermarkt.com/chris-brady/profil/spieler/765504.
Transfer history data appended for: https://www.transfermarkt.com/allan-rodriguez/profil/spieler/745457.
Transfer history data appended for: https://www.transfermarkt.com/alex-monis/profil/spieler/724442.
Transfer history data appended for: https://www.transfermarkt.com/elliot-collier/profil/spieler/253861.
Transfer history data appended for: https://www.transfermarkt.com/bobby-shuttleworth/profil/spieler/115887.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-pineda/profil/spieler/345621.
Transfer history data appended for: https://www.transfermarkt.com/connor-sparrow/profil/spieler/430502.
Transfer history data appended for: https://www.transfermarkt.com/gaston-gimenez/profil/spieler/216758.
Transfer history data appended for: https://www.transfermarkt.com/jeremiah-gutjahr/profil/spieler/402838.
Transfer history data appended for: https://www.transfermarkt.com/luka-stojanovic/profil/spieler/186499.
Transfer history data appended for: https://www.transfermarkt.com/james-sands/profil/spieler/393321.
Transfer history data appended for: https://www.transfermarkt.com/tayvon-gray/profil/spieler/627200.
Transfer history data appended for: https://www.transfermarkt.com/alexander-callens/profil/spieler/147462.
Transfer history data appended for: https://www.transfermarkt.com/heber/profil/spieler/150601.
Transfer history data appended for: https://www.transfermarkt.com/andres-jasson/profil/spieler/627208.
Transfer history data appended for: https://www.transfermarkt.com/juan-torres/profil/spieler/368898.
Transfer history data appended for: https://www.transfermarkt.com/luis-barraza/profil/spieler/644782.
Transfer history data appended for: https://www.transfermarkt.com/sebastien-ibeagha/profil/spieler/170854.
Transfer history data appended for: https://www.transfermarkt.com/valentin-castellanos/profil/spieler/522784.
Transfer history data appended for: https://www.transfermarkt.com/gudmundur-thorarinsson/profil/spieler/114113.
Transfer history data appended for: https://www.transfermarkt.com/maxime-chanot/profil/spieler/89030.
Transfer history data appended for: https://www.transfermarkt.com/tony-rocha/profil/spieler/261736.
Transfer history data appended for: https://www.transfermarkt.com/keaton-parks/profil/spieler/451860.
Transfer history data appended for: https://www.transfermarkt.com/gary-mackay-steven/profil/spieler/78961.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-acevedo/profil/spieler/625569.
Transfer history data appended for: https://www.transfermarkt.com/gedion-zelalem/profil/spieler/228370.
Transfer history data appended for: https://www.transfermarkt.com/ronald-matarrita/profil/spieler/268273.
Transfer history data appended for: https://www.transfermarkt.com/anton-tinnerholm/profil/spieler/109196.
Transfer history data appended for: https://www.transfermarkt.com/ismael-tajouri-shradi/profil/spieler/158120.
Transfer history data appended for: https://www.transfermarkt.com/justin-haak/profil/spieler/610628.
Transfer history data appended for: https://www.transfermarkt.com/joe-scally/profil/spieler/504153.
Transfer history data appended for: https://www.transfermarkt.com/brad-stuver/profil/spieler/300600.
Transfer history data appended for: https://www.transfermarkt.com/sean-johnson/profil/spieler/126630.
Transfer history data appended for: https://www.transfermarkt.com/jesus-medina/profil/spieler/353037.
Transfer history data appended for: https://www.transfermarkt.com/bill-hamid/profil/spieler/77714.
Transfer history data appended for: https://www.transfermarkt.com/donovan-pines/profil/spieler/638692.
Transfer history data appended for: https://www.transfermarkt.com/kevin-paredes/profil/spieler/711517.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-abu/profil/spieler/164478.
Transfer history data appended for: https://www.transfermarkt.com/ulises-segura/profil/spieler/306431.
Transfer history data appended for: https://www.transfermarkt.com/steve-birnbaum/profil/spieler/307728.
Transfer history data appended for: https://www.transfermarkt.com/chris-seitz/profil/spieler/51424.
Transfer history data appended for: https://www.transfermarkt.com/julian-gressel/profil/spieler/229640.
Transfer history data appended for: https://www.transfermarkt.com/ola-kamara/profil/spieler/62067.
Transfer history data appended for: https://www.transfermarkt.com/frederic-brillant/profil/spieler/75062.
Transfer history data appended for: https://www.transfermarkt.com/edison-flores/profil/spieler/194998.
Transfer history data appended for: https://www.transfermarkt.com/junior-moreno/profil/spieler/265152.
Transfer history data appended for: https://www.transfermarkt.com/moses-nyeman/profil/spieler/677834.
Transfer history data appended for: https://www.transfermarkt.com/erik-sorga/profil/spieler/322690.
Transfer history data appended for: https://www.transfermarkt.com/earl-edwards-jr-/profil/spieler/354886.
Transfer history data appended for: https://www.transfermarkt.com/axel-sjoberg/profil/spieler/113116.
Transfer history data appended for: https://www.transfermarkt.com/gelmin-rivas/profil/spieler/123500.
Transfer history data appended for: https://www.transfermarkt.com/felipe-martins/profil/spieler/85012.
Transfer history data appended for: https://www.transfermarkt.com/paul-arriola/profil/spieler/189876.
Transfer history data appended for: https://www.transfermarkt.com/oniel-fisher/profil/spieler/357278.
Transfer history data appended for: https://www.transfermarkt.com/joseph-mora/profil/spieler/131255.
Transfer history data appended for: https://www.transfermarkt.com/griffin-yow/profil/spieler/627205.
Transfer history data appended for: https://www.transfermarkt.com/yordy-reyna/profil/spieler/200779.
Transfer history data appended for: https://www.transfermarkt.com/jacob-greene/profil/spieler/684181.
Transfer history data appended for: https://www.transfermarkt.com/russell-canouse/profil/spieler/184133.
Transfer history data appended for: https://www.transfermarkt.com/chris-odoi-atsem/profil/spieler/482616.
Transfer history data appended for: https://www.transfermarkt.com/chase-gasper/profil/spieler/336167.
Transfer history data appended for: https://www.transfermarkt.com/hassani-dotson/profil/spieler/636081.
Transfer history data appended for: https://www.transfermarkt.com/romain-metanire/profil/spieler/154209.
Transfer history data appended for: https://www.transfermarkt.com/aaron-schoenfeld/profil/spieler/218314.
Transfer history data appended for: https://www.transfermarkt.com/tyler-miller/profil/spieler/353479.
Transfer history data appended for: https://www.transfermarkt.com/fred-emmings/profil/spieler/739023.
Transfer history data appended for: https://www.transfermarkt.com/luis-amarilla/profil/spieler/291658.
Transfer history data appended for: https://www.transfermarkt.com/kevin-molino/profil/spieler/123096.
Transfer history data appended for: https://www.transfermarkt.com/kei-kamara/profil/spieler/39049.
Transfer history data appended for: https://www.transfermarkt.com/jose-aja/profil/spieler/336457.

Transfer history data appended for: https://www.transfermarkt.com/adrian-zendejas/profil/spieler/384129.
Transfer history data appended for: https://www.transfermarkt.com/kevin-partida/profil/spieler/572968.
Transfer history data appended for: https://www.transfermarkt.com/sam-gleadle/profil/spieler/568285.
Transfer history data appended for: https://www.transfermarkt.com/brent-kallman/profil/spieler/226643.
Transfer history data appended for: https://www.transfermarkt.com/raheem-edwards/profil/spieler/367429.
Transfer history data appended for: https://www.transfermarkt.com/michael-boxall/profil/spieler/81723.
Transfer history data appended for: https://www.transfermarkt.com/dayne-st-clair/profil/spieler/439750.
Transfer history data appended for: https://www.transfermarkt.com/robin-lod/profil/spieler/173573.
Transfer history data appended for: https://www.transfermarkt.com/greg-ranjitsingh/profil/spieler/367436.
Transfer history data appended for: https://www.transfermarkt.com/thomas-chacon/profil/spieler/465676.
Transfer history data appended for: https://www.transfermarkt.com/foster-langsdorf/profil/spieler/325383.
Transfer history data appended for: https://www.transfermarkt.com/marlon-hairston/profil/spieler/306401.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-reynoso/profil/spieler/439626.
Transfer history data appended for: https://www.transfermarkt.com/ethan-finlay/profil/spieler/212949.
Transfer history data appended for: https://www.transfermarkt.com/noah-billingsley/profil/spieler/353217.
Transfer history data appended for: https://www.transfermarkt.com/james-musa/profil/spieler/135510.
Transfer history data appended for: https://www.transfermarkt.com/jacori-hayes/profil/spieler/482621.
Transfer history data appended for: https://www.transfermarkt.com/ike-opara/profil/spieler/125696.
Transfer history data appended for: https://www.transfermarkt.com/osvaldo-alonso/profil/spieler/62810.
Transfer history data appended for: https://www.transfermarkt.com/steeven-saba/profil/spieler/587902.
Transfer history data appended for: https://www.transfermarkt.com/shamit-shome/profil/spieler/423445.
Transfer history data appended for: https://www.transfermarkt.com/rudy-camacho/profil/spieler/170904.
Transfer history data appended for: https://www.transfermarkt.com/luis-binks/profil/spieler/471004.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-urruti/profil/spieler/193781.
Transfer history data appended for: https://www.transfermarkt.com/jean-aniel-assi/profil/spieler/842419.
Transfer history data appended for: https://www.transfermarkt.com/clement-diop/profil/spieler/190915.
Transfer history data appended for: https://www.transfermarkt.com/rod-fanni/profil/spieler/5477.
Transfer history data appended for: https://www.transfermarkt.com/mason-toye/profil/spieler/562388.
Transfer history data appended for: https://www.transfermarkt.com/nathan-dylan-saliba/profil/spieler/842420.
Transfer history data appended for: https://www.transfermarkt.com/jorge-corrales/profil/spieler/210374.
Transfer history data appended for: https://www.transfermarkt.com/rida-zouhir/profil/spieler/842421.
Transfer history data appended for: https://www.transfermarkt.com/zachary-brault-guillard/profil/spieler/395676.
Transfer history data appended for: https://www.transfermarkt.com/clement-bayiha/profil/spieler/589005.
Transfer history data appended for: https://www.transfermarkt.com/karifa-yao/profil/spieler/677677.
Transfer history data appended for: https://www.transfermarkt.com/ballou-tabla/profil/spieler/408886.
Transfer history data appended for: https://www.transfermarkt.com/joel-waterman/profil/spieler/441738.
Transfer history data appended for: https://www.transfermarkt.com/tomas-giraldo/profil/spieler/718096.
Transfer history data appended for: https://www.transfermarkt.com/victor-wanyama/profil/spieler/77760.
Transfer history data appended for: https://www.transfermarkt.com/sean-rea/profil/spieler/718099.
Transfer history data appended for: https://www.transfermarkt.com/samuel-piette/profil/spieler/189019.
Transfer history data appended for: https://www.transfermarkt.com/keesean-ferdinand/profil/spieler/718095.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-choiniere/profil/spieler/589006.
Transfer history data appended for: https://www.transfermarkt.com/james-pantemis/profil/spieler/429217.
Transfer history data appended for: https://www.transfermarkt.com/anthony-jackson-hamel/profil/spieler/333093.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-sirois/profil/spieler/749407.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-kizza/profil/spieler/568750.
Transfer history data appended for: https://www.transfermarkt.com/amar-sejdic/profil/spieler/424993.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-maciel/profil/spieler/666330.
Transfer history data appended for: https://www.transfermarkt.com/elliot-panicco/profil/spieler/637410.
Transfer history data appended for: https://www.transfermarkt.com/walker-zimmerman/profil/spieler/245337.
Transfer history data appended for: https://www.transfermarkt.com/tanner-dieterich/profil/spieler/351507.
Transfer history data appended for: https://www.transfermarkt.com/taylor-washington/profil/spieler/417394.
Transfer history data appended for: https://www.transfermarkt.com/brian-anunga/profil/spieler/374282.
Transfer history data appended for: https://www.transfermarkt.com/jack-maher/profil/spieler/405189.
Transfer history data appended for: https://www.transfermarkt.com/alistair-johnston/profil/spieler/637446.
Transfer history data appended for: https://www.transfermarkt.com/joe-willis/profil/spieler/175615.
Transfer history data appended for: https://www.transfermarkt.com/dave-romney/profil/spieler/367552.
Transfer history data appended for: https://www.transfermarkt.com/alan-winn/profil/spieler/336173.
Transfer history data appended for: https://www.transfermarkt.com/brady-scott/profil/spieler/370844.
Transfer history data appended for: https://www.transfermarkt.com/c-j-cochran/profil/spieler/367730.
Transfer history data appended for: https://www.transfermarkt.com/derrick-jones/profil/spieler/411554.
Transfer history data appended for: https://www.transfermarkt.com/david-accam/profil/spieler/221855.
Transfer history data appended for: https://www.transfermarkt.com/eric-miller/profil/spieler/245315.
Transfer history data appended for: https://www.transfermarkt.com/daniel-rios/profil/spieler/325603.
Transfer history data appended for: https://www.transfermarkt.com/anibal-godoy/profil/spieler/161671.
Transfer history data appended for: https://www.transfermarkt.com/cameron-lancaster/profil/spieler/182660.
Transfer history data appended for: https://www.transfermarkt.com/ken-tribbett/profil/spieler/271662.
Transfer history data appended for: https://www.transfermarkt.com/daniel-lovitz/profil/spieler/271198.
Transfer history data appended for: https://www.transfermarkt.com/brayan-beckeles/profil/spieler/171043.
Transfer history data appended for: https://www.transfermarkt.com/abu-danladi/profil/spieler/476676.
Transfer history data appended for: https://www.transfermarkt.com/miguel-nazarit/profil/spieler/572039.
Transfer history data appended for: https://www.transfermarkt.com/jalil-anibaba/profil/spieler/174715.
Transfer history data appended for: https://www.transfermarkt.com/randall-leal/profil/spieler/297786.
Transfer history data appended for: https://www.transfermarkt.com/luke-haakenson/profil/spieler/749605.
Transfer history data appended for: https://www.transfermarkt.com/alex-muyl/profil/spieler/413690.
Transfer history data appended for: https://www.transfermarkt.com/dax-mccarty/profil/spieler/39479.
Transfer history data appended for: https://www.transfermarkt.com/matt-lagrassa/profil/spieler/423454.
Transfer history data appended for: https://www.transfermarkt.com/handwalla-bwana/profil/spieler/425824.
Transfer history data appended for: https://www.transfermarkt.com/dominique-badji/profil/spieler/354840.
Transfer history data appended for: https://www.transfermarkt.com/hany-mukhtar/profil/spieler/146155.

Transfer history data appended for: https://www.transfermarkt.com/milan-iloski/profil/spieler/637271.
Transfer history data appended for: https://www.transfermarkt.com/justen-glad/profil/spieler/334597.
Transfer history data appended for: https://www.transfermarkt.com/tate-schmitt/profil/spieler/637658.
Transfer history data appended for: https://www.transfermarkt.com/zac-macmath/profil/spieler/156300.
Transfer history data appended for: https://www.transfermarkt.com/kyle-beckerman/profil/spieler/26995.
Transfer history data appended for: https://www.transfermarkt.com/jeizon-ramirez/profil/spieler/509326.
Transfer history data appended for: https://www.transfermarkt.com/donny-toia/profil/spieler/181662.
Transfer history data appended for: https://www.transfermarkt.com/luke-mulholland/profil/spieler/101399.
Transfer history data appended for: https://www.transfermarkt.com/corey-baird/profil/spieler/336182.
Transfer history data appended for: https://www.transfermarkt.com/erik-holt/profil/spieler/510344.
Transfer history data appended for: https://www.transfermarkt.com/julian-vazquez/profil/spieler/624261.
Transfer history data appended for: https://www.transfermarkt.com/david-ochoa/profil/spieler/580234.
Transfer history data appended for: https://www.transfermarkt.com/ashtone-morgan/profil/spieler/164559.
Transfer history data appended for: https://www.transfermarkt.com/nedum-onuoha/profil/spieler/28810.
Transfer history data appended for: https://www.transfermarkt.com/andrew-putna/profil/spieler/494257.
Transfer history data appended for: https://www.transfermarkt.com/aaron-herrera/profil/spieler/401362.
Transfer history data appended for: https://www.transfermarkt.com/giuseppe-rossi/profil/spieler/19104.
Transfer history data appended for: https://www.transfermarkt.com/alvin-jones/profil/spieler/347597.
Transfer history data appended for: https://www.transfermarkt.com/damir-kreilach/profil/spieler/68884.
Transfer history data appended for: https://www.transfermarkt.com/maikel-chang/profil/spieler/259271.
Transfer history data appended for: https://www.transfermarkt.com/luis-arriaga/profil/spieler/469856.
Transfer history data appended for: https://www.transfermarkt.com/albert-rusnak/profil/spieler/43228.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-silva/profil/spieler/76743.
Transfer history data appended for: https://www.transfermarkt.com/douglas-martinez/profil/spieler/443384.
Transfer history data appended for: https://www.transfermarkt.com/justin-portillo/profil/spieler/318461.
Transfer history data appended for: https://www.transfermarkt.com/christopher-garcia/profil/spieler/743691.
Transfer history data appended for: https://www.transfermarkt.com/pablo-ruiz/profil/spieler/401580.
Transfer history data appended for: https://www.transfermarkt.com/everton-luiz/profil/spieler/75076.
Transfer history data appended for: https://www.transfermarkt.com/justin-meram/profil/spieler/175387.
Transfer history data appended for: https://www.transfermarkt.com/nick-besler/profil/spieler/354597.
Transfer history data appended for: https://www.transfermarkt.com/erickson-gallardo/profil/spieler/331122.
Transfer history data appended for: https://www.transfermarkt.com/jozy-altidore/profil/spieler/39378.
Transfer history data appended for: https://www.transfermarkt.com/jayden-nelson/profil/spieler/635445.
Transfer history data appended for: https://www.transfermarkt.com/ralph-priso/profil/spieler/657271.
Transfer history data appended for: https://www.transfermarkt.com/omar-gonzalez/profil/spieler/99690.
Transfer history data appended for: https://www.transfermarkt.com/griffin-dorsey/profil/spieler/405187.
Transfer history data appended for: https://www.transfermarkt.com/alex-bono/profil/spieler/272881.
Transfer history data appended for: https://www.transfermarkt.com/ifunanyachi-achara/profil/spieler/735809.
Transfer history data appended for: https://www.transfermarkt.com/eriq-zavaleta/profil/spieler/131193.
Transfer history data appended for: https://www.transfermarkt.com/marky-delgado/profil/spieler/222565.
Transfer history data appended for: https://www.transfermarkt.com/laurent-ciman/profil/spieler/22338.
Transfer history data appended for: https://www.transfermarkt.com/quentin-westberg/profil/spieler/33934.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-pozuelo/profil/spieler/188853.
Transfer history data appended for: https://www.transfermarkt.com/chris-mavinga/profil/spieler/93732.
Transfer history data appended for: https://www.transfermarkt.com/kevin-silva/profil/spieler/351503.
Transfer history data appended for: https://www.transfermarkt.com/tony-gallacher/profil/spieler/344579.
Transfer history data appended for: https://www.transfermarkt.com/justin-morrow/profil/spieler/145116.
Transfer history data appended for: https://www.transfermarkt.com/tsubasa-endoh/profil/spieler/417350.
Transfer history data appended for: https://www.transfermarkt.com/michael-bradley/profil/spieler/30593.
Transfer history data appended for: https://www.transfermarkt.com/jahkeele-marshall-rutty/profil/spieler/640852.
Transfer history data appended for: https://www.transfermarkt.com/ayo-akinola/profil/spieler/370979.
Transfer history data appended for: https://www.transfermarkt.com/liam-fraser/profil/spieler/377109.
Transfer history data appended for: https://www.transfermarkt.com/julian-dunn/profil/spieler/494823.
Transfer history data appended for: https://www.transfermarkt.com/nick-deleon/profil/spieler/212979.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-osorio/profil/spieler/260807.
Transfer history data appended for: https://www.transfermarkt.com/richie-laryea/profil/spieler/417348.
Transfer history data appended for: https://www.transfermarkt.com/patrick-mullins/profil/spieler/251421.
Transfer history data appended for: https://www.transfermarkt.com/auro-jr-/profil/spieler/294796.
Transfer history data appended for: https://www.transfermarkt.com/jacob-shaffelburg/profil/spieler/637632.
Transfer history data appended for: https://www.transfermarkt.com/collin-verfurth/profil/spieler/658003.
Transfer history data appended for: https://www.transfermarkt.com/damien-rivera/profil/spieler/722649.
Transfer history data appended for: https://www.transfermarkt.com/antonio-delamea-mlinar/profil/spieler/87214.
Transfer history data appended for: https://www.transfermarkt.com/matt-turner/profil/spieler/425306.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-firmino/profil/spieler/636422.
Transfer history data appended for: https://www.transfermarkt.com/henry-kessler/profil/spieler/638732.
Transfer history data appended for: https://www.transfermarkt.com/brandon-bye/profil/spieler/562389.
Transfer history data appended for: https://www.transfermarkt.com/jeff-caldwell/profil/spieler/336174.
Transfer history data appended for: https://www.transfermarkt.com/kelyn-rowe/profil/spieler/183118.
Transfer history data appended for: https://www.transfermarkt.com/justin-rennicks/profil/spieler/368907.
Transfer history data appended for: https://www.transfermarkt.com/tommy-mcnamara/profil/spieler/307892.
Transfer history data appended for: https://www.transfermarkt.com/andrew-farrell/profil/spieler/253616.
Transfer history data appended for: https://www.transfermarkt.com/kekuta-manneh/profil/spieler/253053.
Transfer history data appended for: https://www.transfermarkt.com/scott-caldwell/profil/spieler/228117.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-bou/profil/spieler/71608.
Transfer history data appended for: https://www.transfermarkt.com/isaac-angking/profil/spieler/559599.
Transfer history data appended for: https://www.transfermarkt.com/matt-polster/profil/spieler/354613.
Transfer history data appended for: https://www.transfermarkt.com/dejuan-jones/profil/spieler/637146.
Transfer history data appended for: https://www.transfermarkt.com/luis-caicedo/profil/spieler/426609.
Transfer history data appended for: https://www.transfermarkt.com/lee-nguyen/profil/spieler/37604.
Transfer history data appended for: https://www.transfermarkt.com/michael-mancienne/profil/spieler/38100.

Transfer history data appended for: https://www.transfermarkt.com/tajon-buchanan/profil/spieler/638793.
Transfer history data appended for: https://www.transfermarkt.com/diego-fagundez/profil/spieler/170100.
Transfer history data appended for: https://www.transfermarkt.com/carles-gil/profil/spieler/127987.
Transfer history data appended for: https://www.transfermarkt.com/brad-knighton/profil/spieler/59470.
Transfer history data appended for: https://www.transfermarkt.com/cristian-penilla/profil/spieler/212309.
Transfer history data appended for: https://www.transfermarkt.com/teal-bunbury/profil/spieler/141217.
Transfer history data appended for: https://www.transfermarkt.com/seth-sinovic/profil/spieler/144959.
Transfer history data appended for: https://www.transfermarkt.com/chris-wondolowski/profil/spieler/39856.
Transfer history data appended for: https://www.transfermarkt.com/carlos-fierro/profil/spieler/185365.
Transfer history data appended for: https://www.transfermarkt.com/eric-calvillo/profil/spieler/315759.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-ochoa/profil/spieler/723386.
Transfer history data appended for: https://www.transfermarkt.com/judson/profil/spieler/349744.
Transfer history data appended for: https://www.transfermarkt.com/oswaldo-alanis/profil/spieler/106282.
Transfer history data appended for: https://www.transfermarkt.com/daniel-vega/profil/spieler/82507.
Transfer history data appended for: https://www.transfermarkt.com/paul-marie/profil/spieler/182907.
Transfer history data appended for: https://www.transfermarkt.com/jack-skahan/profil/spieler/637225.
Transfer history data appended for: https://www.transfermarkt.com/tanner-beason/profil/spieler/635660.
Transfer history data appended for: https://www.transfermarkt.com/valeri-qazaishvili/profil/spieler/156115.
Transfer history data appended for: https://www.transfermarkt.com/jackson-yueill/profil/spieler/349707.
Transfer history data appended for: https://www.transfermarkt.com/tommy-thompson/profil/spieler/308005.
Transfer history data appended for: https://www.transfermarkt.com/siad-haji/profil/spieler/644779.
Transfer history data appended for: https://www.transfermarkt.com/nick-lima/profil/spieler/478802.
Transfer history data appended for: https://www.transfermarkt.com/casey-walls/profil/spieler/724440.
Transfer history data appended for: https://www.transfermarkt.com/gilbert-fuentes/profil/spieler/504206.
Transfer history data appended for: https://www.transfermarkt.com/marcos-lopez/profil/spieler/432175.
Transfer history data appended for: https://www.transfermarkt.com/cristian-espinoza/profil/spieler/278992.
Transfer history data appended for: https://www.transfermarkt.com/guram-kashia/profil/spieler/55972.
Transfer history data appended for: https://www.transfermarkt.com/jacob-akanyirige/profil/spieler/557061.
Transfer history data appended for: https://www.transfermarkt.com/florian-jungwirth/profil/spieler/33078.
Transfer history data appended for: https://www.transfermarkt.com/danny-hoesen/profil/spieler/81163.
Transfer history data appended for: https://www.transfermarkt.com/matt-bersano/profil/spieler/429255.
Transfer history data appended for: https://www.transfermarkt.com/cade-cowell/profil/spieler/647235.
Transfer history data appended for: https://www.transfermarkt.com/shea-salinas/profil/spieler/80670.
Transfer history data appended for: https://www.transfermarkt.com/luis-felipe/profil/spieler/423441.
Transfer history data appended for: https://www.transfermarkt.com/jt-marcinkowski/profil/spieler/336163.
Transfer history data appended for: https://www.transfermarkt.com/thomas-roberts/profil/spieler/513967.
Transfer history data appended for: https://www.transfermarkt.com/bressan/profil/spieler/256453.
Transfer history data appended for: https://www.transfermarkt.com/eddie-munjoma/profil/spieler/636468.
Transfer history data appended for: https://www.transfermarkt.com/thiago-santos/profil/spieler/346922.
Transfer history data appended for: https://www.transfermarkt.com/phelipe/profil/spieler/608218.
Transfer history data appended for: https://www.transfermarkt.com/john-nelson/profil/spieler/351504.
Transfer history data appended for: https://www.transfermarkt.com/brandon-servania/profil/spieler/455979.
Transfer history data appended for: https://www.transfermarkt.com/andres-ricaurte/profil/spieler/253846.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-pepi/profil/spieler/627207.
Transfer history data appended for: https://www.transfermarkt.com/francis-atuahene/profil/spieler/510591.
Transfer history data appended for: https://www.transfermarkt.com/paxton-pomykal/profil/spieler/455978.
Transfer history data appended for: https://www.transfermarkt.com/dante-sealy/profil/spieler/568179.
Transfer history data appended for: https://www.transfermarkt.com/bryan-acosta/profil/spieler/314853.
Transfer history data appended for: https://www.transfermarkt.com/justin-che/profil/spieler/796429.
Transfer history data appended for: https://www.transfermarkt.com/michael-barrios/profil/spieler/313286.
Transfer history data appended for: https://www.transfermarkt.com/bryan-reynolds/profil/spieler/475208.
Transfer history data appended for: https://www.transfermarkt.com/callum-montgomery/profil/spieler/637412.
Transfer history data appended for: https://www.transfermarkt.com/matt-hedges/profil/spieler/212984.
Transfer history data appended for: https://www.transfermarkt.com/jesus-ferreira/profil/spieler/474249.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-maurer/profil/spieler/183337.
Transfer history data appended for: https://www.transfermarkt.com/nkosi-burgess/profil/spieler/501877.
Transfer history data appended for: https://www.transfermarkt.com/fafa-picault/profil/spieler/216683.
Transfer history data appended for: https://www.transfermarkt.com/kyle-zobeck/profil/spieler/261321.
Transfer history data appended for: https://www.transfermarkt.com/carlos-avilez/profil/spieler/354311.
Transfer history data appended for: https://www.transfermarkt.com/edwin-cerrillo/profil/spieler/652470.
Transfer history data appended for: https://www.transfermarkt.com/ryan-hollingshead/profil/spieler/256354.
Transfer history data appended for: https://www.transfermarkt.com/ema-twumasi/profil/spieler/562391.
Transfer history data appended for: https://www.transfermarkt.com/tanner-tessmann/profil/spieler/670096.
Transfer history data appended for: https://www.transfermarkt.com/santiago-mosquera/profil/spieler/490621.
Transfer history data appended for: https://www.transfermarkt.com/matt-freese/profil/spieler/500309.
Transfer history data appended for: https://www.transfermarkt.com/joe-bendik/profil/spieler/168713.
Transfer history data appended for: https://www.transfermarkt.com/olivier-mbaizo/profil/spieler/426944.
Transfer history data appended for: https://www.transfermarkt.com/aurelien-collin/profil/spieler/45155.
Transfer history data appended for: https://www.transfermarkt.com/cole-turner/profil/spieler/659780.
Transfer history data appended for: https://www.transfermarkt.com/matej-oravec/profil/spieler/389619.
Transfer history data appended for: https://www.transfermarkt.com/kacper-przybylko/profil/spieler/86030.
Transfer history data appended for: https://www.transfermarkt.com/anthony-fontana/profil/spieler/447216.
Transfer history data appended for: https://www.transfermarkt.com/michee-ngalina/profil/spieler/580812.
Transfer history data appended for: https://www.transfermarkt.com/jack-elliott/profil/spieler/490362.
Transfer history data appended for: https://www.transfermarkt.com/sergio-santos/profil/spieler/370561.
Transfer history data appended for: https://www.transfermarkt.com/brenden-aaronson/profil/spieler/393323.
Transfer history data appended for: https://www.transfermarkt.com/matthew-real/profil/spieler/368897.
Transfer history data appended for: https://www.transfermarkt.com/mark-mckenzie/profil/spieler/429259.
Transfer history data appended for: https://www.transfermarkt.com/kai-wagner/profil/spieler/357842.
Transfer history data appended for: https://www.transfermarkt.com/jose-andres-martinez/profil/spieler/415666.

Transfer history data appended for: https://www.transfermarkt.com/jamiro-monteiro/profil/spieler/272930.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-bedoya/profil/spieler/111783.
Transfer history data appended for: https://www.transfermarkt.com/cory-burke/profil/spieler/408051.
Transfer history data appended for: https://www.transfermarkt.com/andre-blake/profil/spieler/244149.
Transfer history data appended for: https://www.transfermarkt.com/warren-creavalle/profil/spieler/213005.
Transfer history data appended for: https://www.transfermarkt.com/ilsinho/profil/spieler/52937.
Transfer history data appended for: https://www.transfermarkt.com/jack-de-vries/profil/spieler/659781.
Transfer history data appended for: https://www.transfermarkt.com/raymon-gaddis/profil/spieler/213017.
Transfer history data appended for: https://www.transfermarkt.com/jakob-glesnes/profil/spieler/185636.
Transfer history data appended for: https://www.transfermarkt.com/bryan-smeets/profil/spieler/119066.
Transfer history data appended for: https://www.transfermarkt.com/augustin-drakpe/profil/spieler/593193.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-emegha/profil/spieler/559328.
Transfer history data appended for: https://www.transfermarkt.com/michael-fabrie/profil/spieler/341447.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-van-leer/profil/spieler/123520.
Transfer history data appended for: https://www.transfermarkt.com/maduka-okoye/profil/spieler/340353.
Transfer history data appended for: https://www.transfermarkt.com/tim-coremans/profil/spieler/119061.
Transfer history data appended for: https://www.transfermarkt.com/michael-heylen/profil/spieler/255748.
Transfer history data appended for: https://www.transfermarkt.com/jeffry-fortes/profil/spieler/102660.
Transfer history data appended for: https://www.transfermarkt.com/aaron-meijers/profil/spieler/56836.
Transfer history data appended for: https://www.transfermarkt.com/mica-pinto/profil/spieler/177866.
Transfer history data appended for: https://www.transfermarkt.com/dirk-abels/profil/spieler/333815.
Transfer history data appended for: https://www.transfermarkt.com/lorenzo-soares-fonseca/profil/spieler/416393.
Transfer history data appended for: https://www.transfermarkt.com/bart-vriends/profil/spieler/129991.
Transfer history data appended for: https://www.transfermarkt.com/adil-auassar/profil/spieler/56381.
Transfer history data appended for: https://www.transfermarkt.com/laros-duarte/profil/spieler/258513.
Transfer history data appended for: https://www.transfermarkt.com/sven-mijnans/profil/spieler/578804.
Transfer history data appended for: https://www.transfermarkt.com/danzell-gravenberch/profil/spieler/186282.
Transfer history data appended for: https://www.transfermarkt.com/mario-engels/profil/spieler/93637.
Transfer history data appended for: https://www.transfermarkt.com/wouter-burger/profil/spieler/412953.
Transfer history data appended for: https://www.transfermarkt.com/abdou-harroui/profil/spieler/416386.
Transfer history data appended for: https://www.transfermarkt.com/reda-kharchouch/profil/spieler/482826.
Transfer history data appended for: https://www.transfermarkt.com/lennart-thy/profil/spieler/23553.
Transfer history data appended for: https://www.transfermarkt.com/deroy-duarte/profil/spieler/432852.
Transfer history data appended for: https://www.transfermarkt.com/tom-beugelsdijk/profil/spieler/151494.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-touba/profil/spieler/325924.
Transfer history data appended for: https://www.transfermarkt.com/thierry-lutonda/profil/spieler/416802.
Transfer history data appended for: https://www.transfermarkt.com/said-bakari/profil/spieler/524687.
Transfer history data appended for: https://www.transfermarkt.com/sebbe-augustijns/profil/spieler/674261.
Transfer history data appended for: https://www.transfermarkt.com/cyril-ngonge/profil/spieler/358032.
Transfer history data appended for: https://www.transfermarkt.com/luuk-wouters/profil/spieler/451297.
Transfer history data appended for: https://www.transfermarkt.com/james-efmorfidis/profil/spieler/261071.
Transfer history data appended for: https://www.transfermarkt.com/vitalie-damascan/profil/spieler/354136.
Transfer history data appended for: https://www.transfermarkt.com/nigel-langras/profil/spieler/412944.
Transfer history data appended for: https://www.transfermarkt.com/hans-mulder/profil/spieler/45562.
Transfer history data appended for: https://www.transfermarkt.com/anas-tahiri/profil/spieler/308265.
Transfer history data appended for: https://www.transfermarkt.com/etienne-vaessen/profil/spieler/387197.
Transfer history data appended for: https://www.transfermarkt.com/david-min/profil/spieler/604813.
Transfer history data appended for: https://www.transfermarkt.com/ayman-azhil/profil/spieler/452068.
Transfer history data appended for: https://www.transfermarkt.com/paul-quasten/profil/spieler/18012.
Transfer history data appended for: https://www.transfermarkt.com/richard-van-der-venne/profil/spieler/376675.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-olsak/profil/spieler/422158.
Transfer history data appended for: https://www.transfermarkt.com/jurien-gaari/profil/spieler/328455.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-lamprou/profil/spieler/64352.
Transfer history data appended for: https://www.transfermarkt.com/teun-van-grunsven/profil/spieler/633124.
Transfer history data appended for: https://www.transfermarkt.com/ola-john/profil/spieler/124550.
Transfer history data appended for: https://www.transfermarkt.com/mike-grim/profil/spieler/340453.
Transfer history data appended for: https://www.transfermarkt.com/sylla-sow/profil/spieler/343184.
Transfer history data appended for: https://www.transfermarkt.com/vurnon-anita/profil/spieler/30670.
Transfer history data appended for: https://www.transfermarkt.com/lars-nieuwpoort/profil/spieler/266414.
Transfer history data appended for: https://www.transfermarkt.com/finn-stokkers/profil/spieler/241486.
Transfer history data appended for: https://www.transfermarkt.com/morad-el-haddouti/profil/spieler/410859.
Transfer history data appended for: https://www.transfermarkt.com/melle-meulensteen/profil/spieler/426280.
Transfer history data appended for: https://www.transfermarkt.com/lennerd-daneels/profil/spieler/292805.
Transfer history data appended for: https://www.transfermarkt.com/armando-broja/profil/spieler/571743.
Transfer history data appended for: https://www.transfermarkt.com/oussama-tannane/profil/spieler/235540.
Transfer history data appended for: https://www.transfermarkt.com/lois-openda/profil/spieler/368887.
Transfer history data appended for: https://www.transfermarkt.com/matus-bero/profil/spieler/204047.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-wittek/profil/spieler/196793.
Transfer history data appended for: https://www.transfermarkt.com/max-clark/profil/spieler/183291.
Transfer history data appended for: https://www.transfermarkt.com/enzo-cornelisse/profil/spieler/607164.
Transfer history data appended for: https://www.transfermarkt.com/oussama-darfalou/profil/spieler/321182.
Transfer history data appended for: https://www.transfermarkt.com/jacob-rasmussen/profil/spieler/283233.
Transfer history data appended for: https://www.transfermarkt.com/patrick-vroegh/profil/spieler/433805.
Transfer history data appended for: https://www.transfermarkt.com/filip-moller-delaveris/profil/spieler/502561.
Transfer history data appended for: https://www.transfermarkt.com/danilho-doekhi/profil/spieler/387047.
Transfer history data appended for: https://www.transfermarkt.com/jeroen-houwen/profil/spieler/257980.
Transfer history data appended for: https://www.transfermarkt.com/sondre-tronstad/profil/spieler/210348.
Transfer history data appended for: https://www.transfermarkt.com/tomas-hajek/profil/spieler/181469.
Transfer history data appended for: https://www.transfermarkt.com/eli-dasa/profil/spieler/163847.
Transfer history data appended for: https://www.transfermarkt.com/daan-huisman/profil/spieler/564448.

Transfer history data appended for: https://www.transfermarkt.com/riechedly-bazoer/profil/spieler/216443.
Transfer history data appended for: https://www.transfermarkt.com/hilary-gong/profil/spieler/477306.
Transfer history data appended for: https://www.transfermarkt.com/thomas-bruns/profil/spieler/172202.
Transfer history data appended for: https://www.transfermarkt.com/bilal-bayazit/profil/spieler/361032.
Transfer history data appended for: https://www.transfermarkt.com/idrissa-toure/profil/spieler/335516.
Transfer history data appended for: https://www.transfermarkt.com/remko-pasveer/profil/spieler/25520.
Transfer history data appended for: https://www.transfermarkt.com/thomas-buitink/profil/spieler/357826.
Transfer history data appended for: https://www.transfermarkt.com/million-manhoef/profil/spieler/564449.
Transfer history data appended for: https://www.transfermarkt.com/collin-seedorf/profil/spieler/341678.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-van-rhijn/profil/spieler/124883.
Transfer history data appended for: https://www.transfermarkt.com/nikolai-laursen/profil/spieler/290555.
Transfer history data appended for: https://www.transfermarkt.com/nick-bakker/profil/spieler/210921.
Transfer history data appended for: https://www.transfermarkt.com/glenn-bijl/profil/spieler/203961.
Transfer history data appended for: https://www.transfermarkt.com/hilal-ben-moussa/profil/spieler/223405.
Transfer history data appended for: https://www.transfermarkt.com/behadil-sabani/profil/spieler/415193.
Transfer history data appended for: https://www.transfermarkt.com/marko-kolar/profil/spieler/205924.
Transfer history data appended for: https://www.transfermarkt.com/felix-wiedwald/profil/spieler/44594.
Transfer history data appended for: https://www.transfermarkt.com/sekou-sidibe/profil/spieler/409513.
Transfer history data appended for: https://www.transfermarkt.com/simon-tibbling/profil/spieler/192985.
Transfer history data appended for: https://www.transfermarkt.com/luciano-carty/profil/spieler/556749.
Transfer history data appended for: https://www.transfermarkt.com/dennis-telgenkamp/profil/spieler/84281.
Transfer history data appended for: https://www.transfermarkt.com/stefan-van-der-lei/profil/spieler/187300.
Transfer history data appended for: https://www.transfermarkt.com/robbert-de-vos/profil/spieler/297694.
Transfer history data appended for: https://www.transfermarkt.com/michael-chacon/profil/spieler/158540.
Transfer history data appended for: https://www.transfermarkt.com/lucas-bernadou/profil/spieler/536480.
Transfer history data appended for: https://www.transfermarkt.com/sergio-pena/profil/spieler/224672.
Transfer history data appended for: https://www.transfermarkt.com/ferhat-gorgulu/profil/spieler/120050.
Transfer history data appended for: https://www.transfermarkt.com/robin-jalving/profil/spieler/463526.
Transfer history data appended for: https://www.transfermarkt.com/caner-cavlan/profil/spieler/136550.
Transfer history data appended for: https://www.transfermarkt.com/denis-granecny/profil/spieler/293351.
Transfer history data appended for: https://www.transfermarkt.com/michael-de-leeuw/profil/spieler/110906.
Transfer history data appended for: https://www.transfermarkt.com/desevio-payne/profil/spieler/273570.
Transfer history data appended for: https://www.transfermarkt.com/keziah-veendorp/profil/spieler/258363.
Transfer history data appended for: https://www.transfermarkt.com/donis-avdijaj/profil/spieler/196227.
Transfer history data appended for: https://www.transfermarkt.com/anco-jansen/profil/spieler/56607.
Transfer history data appended for: https://www.transfermarkt.com/janis-blaswich/profil/spieler/81173.
Transfer history data appended for: https://www.transfermarkt.com/sinan-bakis/profil/spieler/134631.
Transfer history data appended for: https://www.transfermarkt.com/tim-breukers/profil/spieler/63356.
Transfer history data appended for: https://www.transfermarkt.com/ismail-azzaoui/profil/spieler/289507.
Transfer history data appended for: https://www.transfermarkt.com/kasper-lunding/profil/spieler/345586.
Transfer history data appended for: https://www.transfermarkt.com/koen-bucker/profil/spieler/335027.
Transfer history data appended for: https://www.transfermarkt.com/lucas-schoofs/profil/spieler/323602.
Transfer history data appended for: https://www.transfermarkt.com/rohat-agca/profil/spieler/591362.
Transfer history data appended for: https://www.transfermarkt.com/teun-bijleveld/profil/spieler/324111.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-amissi/profil/spieler/549954.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-cijntje/profil/spieler/446247.
Transfer history data appended for: https://www.transfermarkt.com/giacomo-quagliata/profil/spieler/458777.
Transfer history data appended for: https://www.transfermarkt.com/mats-knoester/profil/spieler/315138.
Transfer history data appended for: https://www.transfermarkt.com/orestis-kiomourtzoglou/profil/spieler/337243.
Transfer history data appended for: https://www.transfermarkt.com/robin-propper/profil/spieler/202788.
Transfer history data appended for: https://www.transfermarkt.com/luca-de-la-torre/profil/spieler/315762.
Transfer history data appended for: https://www.transfermarkt.com/silvester-van-der-water/profil/spieler/386164.
Transfer history data appended for: https://www.transfermarkt.com/marco-rente/profil/spieler/237244.
Transfer history data appended for: https://www.transfermarkt.com/delano-burgzorg/profil/spieler/436585.
Transfer history data appended for: https://www.transfermarkt.com/michael-brouwer/profil/spieler/231650.
Transfer history data appended for: https://www.transfermarkt.com/daniel-mesenholer/profil/spieler/150080.
Transfer history data appended for: https://www.transfermarkt.com/elias-oubella/profil/spieler/406607.
Transfer history data appended for: https://www.transfermarkt.com/adrian-sz%C5%91ke/profil/spieler/404705.
Transfer history data appended for: https://www.transfermarkt.com/jeff-hardeveld/profil/spieler/263555.
Transfer history data appended for: https://www.transfermarkt.com/noah-fadiga/profil/spieler/379168.
Transfer history data appended for: https://www.transfermarkt.com/navajo-bakboord/profil/spieler/339330.
Transfer history data appended for: https://www.transfermarkt.com/mateo-les/profil/spieler/476755.
Transfer history data appended for: https://www.transfermarkt.com/rai-vloet/profil/spieler/205023.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-holmen/profil/spieler/222320.
Transfer history data appended for: https://www.transfermarkt.com/driess-saddiki/profil/spieler/370042.
Transfer history data appended for: https://www.transfermarkt.com/derrick-kohn/profil/spieler/391780.
Transfer history data appended for: https://www.transfermarkt.com/jasper-dahlhaus/profil/spieler/576682.
Transfer history data appended for: https://www.transfermarkt.com/che-nunnely/profil/spieler/326030.
Transfer history data appended for: https://www.transfermarkt.com/jorn-brondeel/profil/spieler/277242.
Transfer history data appended for: https://www.transfermarkt.com/victor-van-den-bogert/profil/spieler/417827.
Transfer history data appended for: https://www.transfermarkt.com/ole-romeny/profil/spieler/361070.
Transfer history data appended for: https://www.transfermarkt.com/freek-heerkens/profil/spieler/88074.
Transfer history data appended for: https://www.transfermarkt.com/miquel-nelom/profil/spieler/130257.
Transfer history data appended for: https://www.transfermarkt.com/jordens-peters/profil/spieler/31880.
Transfer history data appended for: https://www.transfermarkt.com/connor-van-den-berg/profil/spieler/477476.
Transfer history data appended for: https://www.transfermarkt.com/robbin-ruiter/profil/spieler/81775.
Transfer history data appended for: https://www.transfermarkt.com/wesley-spieringhs/profil/spieler/673344.
Transfer history data appended for: https://www.transfermarkt.com/jan-arie-van-der-heijden/profil/spieler/45538.
Transfer history data appended for: https://www.transfermarkt.com/mats-kohlert/profil/spieler/288067.

Transfer history data appended for: https://www.transfermarkt.com/vangelis-pavlidis/profil/spieler/324503.
Transfer history data appended for: https://www.transfermarkt.com/rick-zuijderwijk/profil/spieler/619736.
Transfer history data appended for: https://www.transfermarkt.com/john-yeboah/profil/spieler/439914.
Transfer history data appended for: https://www.transfermarkt.com/jop-van-der-avert/profil/spieler/497176.
Transfer history data appended for: https://www.transfermarkt.com/leeroy-owusu/profil/spieler/257988.
Transfer history data appended for: https://www.transfermarkt.com/pol-llonch/profil/spieler/205276.
Transfer history data appended for: https://www.transfermarkt.com/elton-kabangu/profil/spieler/396847.
Transfer history data appended for: https://www.transfermarkt.com/paul-gladon/profil/spieler/180843.
Transfer history data appended for: https://www.transfermarkt.com/kwasi-okyere-wriedt/profil/spieler/154819.
Transfer history data appended for: https://www.transfermarkt.com/mike-tresor-ndayishimiye/profil/spieler/381963.
Transfer history data appended for: https://www.transfermarkt.com/gorkem-saglam/profil/spieler/251345.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-kishna/profil/spieler/159026.
Transfer history data appended for: https://www.transfermarkt.com/robert-zwinkels/profil/spieler/33671.
Transfer history data appended for: https://www.transfermarkt.com/pascu/profil/spieler/547354.
Transfer history data appended for: https://www.transfermarkt.com/evan-rottier/profil/spieler/548937.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-karelis/profil/spieler/63487.
Transfer history data appended for: https://www.transfermarkt.com/andrei-ratiu/profil/spieler/527966.
Transfer history data appended for: https://www.transfermarkt.com/david-philipp/profil/spieler/342165.
Transfer history data appended for: https://www.transfermarkt.com/sem-steijn/profil/spieler/593519.
Transfer history data appended for: https://www.transfermarkt.com/maarten-rieder/profil/spieler/435026.
Transfer history data appended for: https://www.transfermarkt.com/lassana-faye/profil/spieler/315129.
Transfer history data appended for: https://www.transfermarkt.com/luuk-koopmans/profil/spieler/235108.
Transfer history data appended for: https://www.transfermarkt.com/gianni-zuiverloon/profil/spieler/27304.
Transfer history data appended for: https://www.transfermarkt.com/dante-rigo/profil/spieler/314974.
Transfer history data appended for: https://www.transfermarkt.com/jamal-amofa/profil/spieler/289651.
Transfer history data appended for: https://www.transfermarkt.com/boy-kemper/profil/spieler/428502.
Transfer history data appended for: https://www.transfermarkt.com/milan-van-ewijk/profil/spieler/587335.
Transfer history data appended for: https://www.transfermarkt.com/michiel-kramer/profil/spieler/56523.
Transfer history data appended for: https://www.transfermarkt.com/ravel-morrison/profil/spieler/128907.
Transfer history data appended for: https://www.transfermarkt.com/jonas-arweiler/profil/spieler/246044.
Transfer history data appended for: https://www.transfermarkt.com/bilal-ould-chikh/profil/spieler/241324.
Transfer history data appended for: https://www.transfermarkt.com/amine-essabri/profil/spieler/578184.
Transfer history data appended for: https://www.transfermarkt.com/shaquille-pinas/profil/spieler/446248.
Transfer history data appended for: https://www.transfermarkt.com/john-goossens/profil/spieler/35527.
Transfer history data appended for: https://www.transfermarkt.com/peet-bijen/profil/spieler/263553.
Transfer history data appended for: https://www.transfermarkt.com/ilay-elmkies/profil/spieler/443752.
Transfer history data appended for: https://www.transfermarkt.com/kees-de-boer/profil/spieler/361121.
Transfer history data appended for: https://www.transfermarkt.com/vicente-besuijen/profil/spieler/412954.
Transfer history data appended for: https://www.transfermarkt.com/samy-bourard/profil/spieler/235230.
Transfer history data appended for: https://www.transfermarkt.com/youri-schoonderwaldt/profil/spieler/531712.
Transfer history data appended for: https://www.transfermarkt.com/yahya-boussakou/profil/spieler/476648.
Transfer history data appended for: https://www.transfermarkt.com/amar-catic/profil/spieler/450195.
Transfer history data appended for: https://www.transfermarkt.com/dario-del-fabro/profil/spieler/110475.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-tagliafico/profil/spieler/131225.
Transfer history data appended for: https://www.transfermarkt.com/lisandro-martinez/profil/spieler/480762.
Transfer history data appended for: https://www.transfermarkt.com/david-neres/profil/spieler/469822.
Transfer history data appended for: https://www.transfermarkt.com/antony/profil/spieler/602105.
Transfer history data appended for: https://www.transfermarkt.com/noussair-mazraoui/profil/spieler/340456.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Transfer history data appended for: https://www.transfermarkt.com/edson-alvarez/profil/spieler/401356.
Transfer history data appended for: https://www.transfermarkt.com/davy-klaassen/profil/spieler/182932.
Transfer history data appended for: https://www.transfermarkt.com/dominik-kotarski/profil/spieler/370997.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-kudus/profil/spieler/543499.
Transfer history data appended for: https://www.transfermarkt.com/kenneth-taylor/profil/spieler/470394.
Transfer history data appended for: https://www.transfermarkt.com/kjell-scherpen/profil/spieler/463527.
Transfer history data appended for: https://www.transfermarkt.com/maarten-stekelenburg/profil/spieler/4311.
Transfer history data appended for: https://www.transfermarkt.com/dusan-tadic/profil/spieler/36139.
Transfer history data appended for: https://www.transfermarkt.com/klaas-jan-huntelaar/profil/spieler/4357.
Transfer history data appended for: https://www.transfermarkt.com/ryan-gravenberch/profil/spieler/478573.
Transfer history data appended for: https://www.transfermarkt.com/quincy-promes/profil/spieler/182381.
Transfer history data appended for: https://www.transfermarkt.com/sean-klaiber/profil/spieler/268113.
Transfer history data appended for: https://www.transfermarkt.com/perr-schuurs/profil/spieler/418543.
Transfer history data appended for: https://www.transfermarkt.com/lassina-traore/profil/spieler/551695.
Transfer history data appended for: https://www.transfermarkt.com/jurrien-timber/profil/spieler/420243.
Transfer history data appended for: https://www.transfermarkt.com/andre-onana/profil/spieler/234509.
Transfer history data appended for: https://www.transfermarkt.com/devyne-rensch/profil/spieler/557407.
Transfer history data appended for: https://www.transfermarkt.com/jurgen-ekkelenkamp/profil/spieler/361068.
Transfer history data appended for: https://www.transfermarkt.com/bart-nieuwkoop/profil/spieler/257987.
Transfer history data appended for: https://www.transfermarkt.com/robert-bozenik/profil/spieler/454576.
Transfer history data appended for: https://www.transfermarkt.com/joao-carlos-teixeira/profil/spieler/132214.
Transfer history data appended for: https://www.transfermarkt.com/sven-van-beek/profil/spieler/256718.
Transfer history data appended for: https://www.transfermarkt.com/mark-diemers/profil/spieler/187507.
Transfer history data appended for: https://www.transfermarkt.com/dylan-vente/profil/spieler/369319.
Transfer history data appended for: https://www.transfermarkt.com/lutsharel-geertruida/profil/spieler/420210.
Transfer history data appended for: https://www.transfermarkt.com/tyrell-malacia/profil/spieler/339340.
Transfer history data appended for: https://www.transfermarkt.com/jordy-wehrmann/profil/spieler/339339.
Transfer history data appended for: https://www.transfermarkt.com/christian-conteh/profil/spieler/530298.
Transfer history data appended for: https://www.transfermarkt.com/eric-botteghin/profil/spieler/56601.
Transfer history data appended for: https://www.transfermarkt.com/marcos-senesi/profil/spieler/469781.
Transfer history data appended for: https://www.transfermarkt.com/luis-sinisterra/profil/spieler/512385.
Transfer history data appended for: https://www.transfermarkt.com/ramon-ten-hove/profil/spieler/387241.
Transfer history data appended for: https://www.transfermarkt.com/bryan-linssen/profil/spieler/82410.
Transfer history data appended for: https://www.transfermarkt.com/luciano-narsingh/profil/spieler/72462.
Transfer history data appended for: https://www.transfermarkt.com/george-johnston/profil/spieler/318549.
Transfer history data appended for: https://www.transfermarkt.com/orkun-kokcu/profil/spieler/454567.
Transfer history data appended for: https://www.transfermarkt.com/leroy-fer/profil/spieler/63342.
Transfer history data appended for: https://www.transfermarkt.com/nick-marsman/profil/spieler/158104.
Transfer history data appended for: https://www.transfermarkt.com/justin-bijlow/profil/spieler/315121.
Transfer history data appended for: https://www.transfermarkt.com/jens-toornstra/profil/spieler/134999.
Transfer history data appended for: https://www.transfermarkt.com/ridgeciano-haps/profil/spieler/228444.
Transfer history data appended for: https://www.transfermarkt.com/steven-berghuis/profil/spieler/129554.
Transfer history data appended for: https://www.transfermarkt.com/naoufal-bannis/profil/spieler/430800.
Transfer history data appended for: https://www.transfermarkt.com/ramon-leeuwin/profil/spieler/60317.
Transfer history data appended for: https://www.transfermarkt.com/albert-gudmundsson/profil/spieler/305947.
Transfer history data appended for: https://www.transfermarkt.com/ron-vlaar/profil/spieler/30697.
Transfer history data appended for: https://www.transfermarkt.com/timo-letschert/profil/spieler/231378.
Transfer history data appended for: https://www.transfermarkt.com/yukinari-sugawara/profil/spieler/405385.
Transfer history data appended for: https://www.transfermarkt.com/hakon-evjen/profil/spieler/394688.
Transfer history data appended for: https://www.transfermarkt.com/myron-boadu/profil/spieler/412932.
Transfer history data appended for: https://www.transfermarkt.com/bruno-martins-indi/profil/spieler/112052.
Transfer history data appended for: https://www.transfermarkt.com/ferdy-druijf/profil/spieler/360519.
Transfer history data appended for: https://www.transfermarkt.com/pantelis-chatzidiakos/profil/spieler/144244.
Transfer history data appended for: https://www.transfermarkt.com/tijjani-reijnders/profil/spieler/460939.
Transfer history data appended for: https://www.transfermarkt.com/jesper-karlsson/profil/spieler/367992.
Transfer history data appended for: https://www.transfermarkt.com/jordy-clasie/profil/spieler/104223.
Transfer history data appended for: https://www.transfermarkt.com/owen-wijndal/profil/spieler/339328.
Transfer history data appended for: https://www.transfermarkt.com/jonas-svensson/profil/spieler/136184.
Transfer history data appended for: https://www.transfermarkt.com/jeremy-helmer/profil/spieler/276135.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-taabouni/profil/spieler/485591.
Transfer history data appended for: https://www.transfermarkt.com/thijs-oosting/profil/spieler/441216.
Transfer history data appended for: https://www.transfermarkt.com/calvin-stengs/profil/spieler/409344.
Transfer history data appended for: https://www.transfermarkt.com/hobie-verhulst/profil/spieler/116471.
Transfer history data appended for: https://www.transfermarkt.com/teun-koopmeiners/profil/spieler/360518.
Transfer history data appended for: https://www.transfermarkt.com/dani-de-wit/profil/spieler/340459.
Transfer history data appended for: https://www.transfermarkt.com/mees-bakker/profil/spieler/436061.
Transfer history data appended for: https://www.transfermarkt.com/juan-familia-castillo/profil/spieler/349567.
Transfer history data appended for: https://www.transfermarkt.com/kenzo-goudmijn/profil/spieler/412943.
Transfer history data appended for: https://www.transfermarkt.com/zakaria-aboukhlal/profil/spieler/393238.
Transfer history data appended for: https://www.transfermarkt.com/marco-bizot/profil/spieler/124884.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-midtsjo/profil/spieler/136180.
Transfer history data appended for: https://www.transfermarkt.com/pelle-clement/profil/spieler/297693.
Transfer history data appended for: https://www.transfermarkt.com/destan-bajselmani/profil/spieler/460611.
Transfer history data appended for: https://www.transfermarkt.com/sai-van-wermeskerken/profil/spieler/172779.
Transfer history data appended for: https://www.transfermarkt.com/dean-huiberts/profil/spieler/530258.
Transfer history data appended for: https://www.transfermarkt.com/immanuel-pherai/profil/spieler/412935.
Transfer history data appended for: https://www.transfermarkt.com/sam-kersten/profil/spieler/430797.
Transfer history data appended for: https://www.transfermarkt.com/marc-olivier-doue/profil/spieler/540654.
Transfer history data appended for: https://www.transfermarkt.com/thomas-lam/profil/spieler/131821.

Transfer history data appended for: https://www.transfermarkt.com/slobodan-tedic/profil/spieler/505652.
Transfer history data appended for: https://www.transfermarkt.com/kenneth-paal/profil/spieler/247596.
Transfer history data appended for: https://www.transfermarkt.com/xavier-mous/profil/spieler/288426.
Transfer history data appended for: https://www.transfermarkt.com/thomas-van-den-belt/profil/spieler/412941.
Transfer history data appended for: https://www.transfermarkt.com/jesper-drost/profil/spieler/143155.
Transfer history data appended for: https://www.transfermarkt.com/eliano-reijnders/profil/spieler/538057.
Transfer history data appended for: https://www.transfermarkt.com/reza-ghoochannejhad/profil/spieler/39522.
Transfer history data appended for: https://www.transfermarkt.com/bram-van-polen/profil/spieler/41583.
Transfer history data appended for: https://www.transfermarkt.com/clint-leemans/profil/spieler/250464.
Transfer history data appended for: https://www.transfermarkt.com/jarno-westerman/profil/spieler/593956.
Transfer history data appended for: https://www.transfermarkt.com/mike-van-duinen/profil/spieler/183397.
Transfer history data appended for: https://www.transfermarkt.com/rico-strieder/profil/spieler/94768.
Transfer history data appended for: https://www.transfermarkt.com/michael-zetterer/profil/spieler/196813.
Transfer history data appended for: https://www.transfermarkt.com/mike-hauptmeijer/profil/spieler/297373.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-saymak/profil/spieler/166959.
Transfer history data appended for: https://www.transfermarkt.com/yuta-nakayama/profil/spieler/346647.
Transfer history data appended for: https://www.transfermarkt.com/sieben-dewaele/profil/spieler/371936.
Transfer history data appended for: https://www.transfermarkt.com/jaimy-kroesen/profil/spieler/600677.
Transfer history data appended for: https://www.transfermarkt.com/jan-bekkema/profil/spieler/312473.
Transfer history data appended for: https://www.transfermarkt.com/couhaib-driouech/profil/spieler/593837.
Transfer history data appended for: https://www.transfermarkt.com/lucas-woudenberg/profil/spieler/221766.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-dresevic/profil/spieler/321135.
Transfer history data appended for: https://www.transfermarkt.com/arjen-van-der-heide/profil/spieler/462087.
Transfer history data appended for: https://www.transfermarkt.com/sherel-floranus/profil/spieler/315211.
Transfer history data appended for: https://www.transfermarkt.com/joey-veerman/profil/spieler/408574.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-shopov/profil/spieler/486813.
Transfer history data appended for: https://www.transfermarkt.com/mitchell-van-bergen/profil/spieler/393239.
Transfer history data appended for: https://www.transfermarkt.com/rein-smit/profil/spieler/477979.
Transfer history data appended for: https://www.transfermarkt.com/henk-veerman/profil/spieler/271743.
Transfer history data appended for: https://www.transfermarkt.com/pawel-bochniewicz/profil/spieler/248395.
Transfer history data appended for: https://www.transfermarkt.com/oliver-batista-meier/profil/spieler/406614.
Transfer history data appended for: https://www.transfermarkt.com/rodney-kongolo/profil/spieler/264748.
Transfer history data appended for: https://www.transfermarkt.com/erwin-mulder/profil/spieler/56631.
Transfer history data appended for: https://www.transfermarkt.com/rami-hajal/profil/spieler/593415.
Transfer history data appended for: https://www.transfermarkt.com/jan-paul-van-hecke/profil/spieler/576314.
Transfer history data appended for: https://www.transfermarkt.com/jan-ras/profil/spieler/440531.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-nygren/profil/spieler/475949.
Transfer history data appended for: https://www.transfermarkt.com/hamdi-akujobi/profil/spieler/590773.
Transfer history data appended for: https://www.transfermarkt.com/ulysses-llanez/profil/spieler/469858.
Transfer history data appended for: https://www.transfermarkt.com/joaquin-fernandez/profil/spieler/580142.
Transfer history data appended for: https://www.transfermarkt.com/lazaros-rota/profil/spieler/483916.
Transfer history data appended for: https://www.transfermarkt.com/lisandro-semedo/profil/spieler/225431.
Transfer history data appended for: https://www.transfermarkt.com/alexei-koselev/profil/spieler/136109.
Transfer history data appended for: https://www.transfermarkt.com/emil-hansson/profil/spieler/276002.
Transfer history data appended for: https://www.transfermarkt.com/zian-flemming/profil/spieler/411537.
Transfer history data appended for: https://www.transfermarkt.com/tesfaldet-tekie/profil/spieler/283185.
Transfer history data appended for: https://www.transfermarkt.com/tom-hendriks/profil/spieler/687560.
Transfer history data appended for: https://www.transfermarkt.com/djibril-dianessy/profil/spieler/355368.
Transfer history data appended for: https://www.transfermarkt.com/yanick-van-osch/profil/spieler/258362.
Transfer history data appended for: https://www.transfermarkt.com/mike-van-beijnen/profil/spieler/540271.
Transfer history data appended for: https://www.transfermarkt.com/martin-angha/profil/spieler/122695.
Transfer history data appended for: https://www.transfermarkt.com/samuel-moutoussamy/profil/spieler/353403.
Transfer history data appended for: https://www.transfermarkt.com/adnan-ugur/profil/spieler/409515.
Transfer history data appended for: https://www.transfermarkt.com/gregoire-amiot/profil/spieler/182879.
Transfer history data appended for: https://www.transfermarkt.com/george-cox/profil/spieler/359692.
Transfer history data appended for: https://www.transfermarkt.com/nassim-el-ablak/profil/spieler/562275.
Transfer history data appended for: https://www.transfermarkt.com/jaroslaw-jach/profil/spieler/327755.
Transfer history data appended for: https://www.transfermarkt.com/jorrit-smeets/profil/spieler/275949.
Transfer history data appended for: https://www.transfermarkt.com/mats-seuntjens/profil/spieler/187809.
Transfer history data appended for: https://www.transfermarkt.com/ben-rienstra/profil/spieler/64506.
Transfer history data appended for: https://www.transfermarkt.com/branislav-ninaj/profil/spieler/260979.
Transfer history data appended for: https://www.transfermarkt.com/roel-janssen/profil/spieler/168787.
Transfer history data appended for: https://www.transfermarkt.com/joshua-wehking/profil/spieler/333641.
Transfer history data appended for: https://www.transfermarkt.com/clint-essers/profil/spieler/387201.
Transfer history data appended for: https://www.transfermarkt.com/armando-obispo/profil/spieler/339337.
Transfer history data appended for: https://www.transfermarkt.com/maxime-delanghe/profil/spieler/409490.
Transfer history data appended for: https://www.transfermarkt.com/yvon-mvogo/profil/spieler/147051.
Transfer history data appended for: https://www.transfermarkt.com/olivier-boscagli/profil/spieler/318508.
Transfer history data appended for: https://www.transfermarkt.com/donyell-malen/profil/spieler/326029.
Transfer history data appended for: https://www.transfermarkt.com/joel-piroe/profil/spieler/369962.
Transfer history data appended for: https://www.transfermarkt.com/philipp-max/profil/spieler/111275.
Transfer history data appended for: https://www.transfermarkt.com/mauro-junior/profil/spieler/323910.
Transfer history data appended for: https://www.transfermarkt.com/ryan-thomas/profil/spieler/203357.
Transfer history data appended for: https://www.transfermarkt.com/timo-baumgartl/profil/spieler/187491.
Transfer history data appended for: https://www.transfermarkt.com/cody-gakpo/profil/spieler/434675.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-ihattaren/profil/spieler/503638.
Transfer history data appended for: https://www.transfermarkt.com/maximiliano-romero/profil/spieler/365758.
Transfer history data appended for: https://www.transfermarkt.com/eran-zahavi/profil/spieler/85093.
Transfer history data appended for: https://www.transfermarkt.com/erick-gutierrez/profil/spieler/298796.

Transfer history data appended for: https://www.transfermarkt.com/jorrit-hendrix/profil/spieler/205004.
Transfer history data appended for: https://www.transfermarkt.com/richard-ledezma/profil/spieler/575367.
Transfer history data appended for: https://www.transfermarkt.com/ismael-saibari/profil/spieler/702869.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-sangare/profil/spieler/375885.
Transfer history data appended for: https://www.transfermarkt.com/vincent-muller/profil/spieler/453807.
Transfer history data appended for: https://www.transfermarkt.com/marco-van-ginkel/profil/spieler/147034.
Transfer history data appended for: https://www.transfermarkt.com/denzel-dumfries/profil/spieler/321528.
Transfer history data appended for: https://www.transfermarkt.com/adrian-fein/profil/spieler/379979.
Transfer history data appended for: https://www.transfermarkt.com/jordan-teze/profil/spieler/364245.
Transfer history data appended for: https://www.transfermarkt.com/noni-madueke/profil/spieler/503987.
Transfer history data appended for: https://www.transfermarkt.com/nick-viergever/profil/spieler/93081.
Transfer history data appended for: https://www.transfermarkt.com/pablo-rosario/profil/spieler/370791.
Transfer history data appended for: https://www.transfermarkt.com/mario-gotze/profil/spieler/74842.
Transfer history data appended for: https://www.transfermarkt.com/danilo/profil/spieler/519731.
Transfer history data appended for: https://www.transfermarkt.com/godfried-roemeratoe/profil/spieler/393241.
Transfer history data appended for: https://www.transfermarkt.com/nathan-markelo/profil/spieler/451576.
Transfer history data appended for: https://www.transfermarkt.com/queensy-menig/profil/spieler/225339.
Transfer history data appended for: https://www.transfermarkt.com/kik-pierie/profil/spieler/361207.
Transfer history data appended for: https://www.transfermarkt.com/lazaros-lamprou/profil/spieler/292356.
Transfer history data appended for: https://www.transfermarkt.com/gijs-smal/profil/spieler/374212.
Transfer history data appended for: https://www.transfermarkt.com/ennio-van-der-gouw/profil/spieler/529425.
Transfer history data appended for: https://www.transfermarkt.com/tyronne-ebuehi/profil/spieler/309944.
Transfer history data appended for: https://www.transfermarkt.com/jeffrey-de-lange/profil/spieler/315253.
Transfer history data appended for: https://www.transfermarkt.com/joel-drommel/profil/spieler/333640.
Transfer history data appended for: https://www.transfermarkt.com/jayden-oosterwolde/profil/spieler/591361.
Transfer history data appended for: https://www.transfermarkt.com/casper-staring/profil/spieler/596158.
Transfer history data appended for: https://www.transfermarkt.com/ramiz-zerrouki/profil/spieler/416660.
Transfer history data appended for: https://www.transfermarkt.com/alexander-jeremejeff/profil/spieler/205760.
Transfer history data appended for: https://www.transfermarkt.com/jesse-bosch/profil/spieler/524043.
Transfer history data appended for: https://www.transfermarkt.com/julio-pleguezuelo/profil/spieler/251885.
Transfer history data appended for: https://www.transfermarkt.com/halil-dervisoglu/profil/spieler/465606.
Transfer history data appended for: https://www.transfermarkt.com/lindon-selahi/profil/spieler/340172.
Transfer history data appended for: https://www.transfermarkt.com/mees-hilgers/profil/spieler/562702.
Transfer history data appended for: https://www.transfermarkt.com/vaclav-cerny/profil/spieler/242063.
Transfer history data appended for: https://www.transfermarkt.com/wout-brama/profil/spieler/30003.
Transfer history data appended for: https://www.transfermarkt.com/thijs-van-leeuwen/profil/spieler/524033.
Transfer history data appended for: https://www.transfermarkt.com/luka-ilic/profil/spieler/429790.
Transfer history data appended for: https://www.transfermarkt.com/aaron-bastiaans/profil/spieler/578459.
Transfer history data appended for: https://www.transfermarkt.com/wassim-essanoussi/profil/spieler/739745.
Transfer history data appended for: https://www.transfermarkt.com/jafar-arias/profil/spieler/326997.
Transfer history data appended for: https://www.transfermarkt.com/stan-van-dijck/profil/spieler/457090.
Transfer history data appended for: https://www.transfermarkt.com/zinedine-machach/profil/spieler/146143.
Transfer history data appended for: https://www.transfermarkt.com/torino-hunte/profil/spieler/267116.
Transfer history data appended for: https://www.transfermarkt.com/nezar-srifi/profil/spieler/499581.
Transfer history data appended for: https://www.transfermarkt.com/georgios-giakoumakis/profil/spieler/234850.
Transfer history data appended for: https://www.transfermarkt.com/yahcuroo-roemer/profil/spieler/539547.
Transfer history data appended for: https://www.transfermarkt.com/simon-janssen/profil/spieler/457092.
Transfer history data appended for: https://www.transfermarkt.com/roy-gelmi/profil/spieler/282520.
Transfer history data appended for: https://www.transfermarkt.com/vito-van-crooij/profil/spieler/312493.
Transfer history data appended for: https://www.transfermarkt.com/danny-post/profil/spieler/90343.
Transfer history data appended for: https://www.transfermarkt.com/evert-linthorst/profil/spieler/361112.
Transfer history data appended for: https://www.transfermarkt.com/lukas-schmitz/profil/spieler/49867.
Transfer history data appended for: https://www.transfermarkt.com/joshua-john/profil/spieler/60312.
Transfer history data appended for: https://www.transfermarkt.com/tristan-dekker/profil/spieler/315124.
Transfer history data appended for: https://www.transfermarkt.com/jens-craenmehr/profil/spieler/554422.
Transfer history data appended for: https://www.transfermarkt.com/thorsten-kirschbaum/profil/spieler/38346.
Transfer history data appended for: https://www.transfermarkt.com/christian-kum/profil/spieler/37850.
Transfer history data appended for: https://www.transfermarkt.com/bram-verbong/profil/spieler/457072.
Transfer history data appended for: https://www.transfermarkt.com/tobias-pachonik/profil/spieler/161549.
Transfer history data appended for: https://www.transfermarkt.com/guus-hupperts/profil/spieler/116636.
Transfer history data appended for: https://www.transfermarkt.com/steffen-schafer/profil/spieler/119291.
Transfer history data appended for: https://www.transfermarkt.com/arjan-swinkels/profil/spieler/34556.
Transfer history data appended for: https://www.transfermarkt.com/delano-van-crooij/profil/spieler/159143.
Transfer history data appended for: https://www.transfermarkt.com/gorkem-can/profil/spieler/361514.
Transfer history data appended for: https://www.transfermarkt.com/leonel-miguel/profil/spieler/497252.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-gudmundsson/profil/spieler/362108.
Transfer history data appended for: https://www.transfermarkt.com/tomas-suslov/profil/spieler/540333.
Transfer history data appended for: https://www.transfermarkt.com/sam-schreck/profil/spieler/335100.
Transfer history data appended for: https://www.transfermarkt.com/kian-slor/profil/spieler/513332.
Transfer history data appended for: https://www.transfermarkt.com/jan-de-boer/profil/spieler/426142.
Transfer history data appended for: https://www.transfermarkt.com/jorgen-strand-larsen/profil/spieler/429983.
Transfer history data appended for: https://www.transfermarkt.com/ko-itakura/profil/spieler/355816.
Transfer history data appended for: https://www.transfermarkt.com/azor-matusiwa/profil/spieler/315145.
Transfer history data appended for: https://www.transfermarkt.com/mo-el-hankouri/profil/spieler/384587.
Transfer history data appended for: https://www.transfermarkt.com/sergio-padt/profil/spieler/79573.
Transfer history data appended for: https://www.transfermarkt.com/damil-dankerlui/profil/spieler/295624.
Transfer history data appended for: https://www.transfermarkt.com/ramon-pascal-lundqvist/profil/spieler/238084.
Transfer history data appended for: https://www.transfermarkt.com/alessio-da-cruz/profil/spieler/337670.
Transfer history data appended for: https://www.transfermarkt.com/wessel-dammers/profil/spieler/250450.
Transfer history data appended for: https://www.transfermarkt.com/thijs-dallinga/profil/spieler/538964.

Transfer history data appended for: https://www.transfermarkt.com/ahmed-el-messaoudi/profil/spieler/303939.
Transfer history data appended for: https://www.transfermarkt.com/thomas-poll/profil/spieler/480457.
Transfer history data appended for: https://www.transfermarkt.com/remco-balk/profil/spieler/412940.
Transfer history data appended for: https://www.transfermarkt.com/bart-van-hintum/profil/spieler/57328.
Transfer history data appended for: https://www.transfermarkt.com/miguel-angel-leal/profil/spieler/527964.
Transfer history data appended for: https://www.transfermarkt.com/arjen-robben/profil/spieler/4360.
Transfer history data appended for: https://www.transfermarkt.com/daniel-van-kaam/profil/spieler/377720.
Transfer history data appended for: https://www.transfermarkt.com/nigel-bertrams/profil/spieler/187594.
Transfer history data appended for: https://www.transfermarkt.com/patrick-joosten/profil/spieler/317593.
Transfer history data appended for: https://www.transfermarkt.com/eric-oelschlagel/profil/spieler/152460.
Transfer history data appended for: https://www.transfermarkt.com/bart-ramselaar/profil/spieler/326701.
Transfer history data appended for: https://www.transfermarkt.com/moussa-sylla/profil/spieler/460655.
Transfer history data appended for: https://www.transfermarkt.com/mark-van-der-maarel/profil/spieler/128042.
Transfer history data appended for: https://www.transfermarkt.com/joris-van-overeem/profil/spieler/182582.
Transfer history data appended for: https://www.transfermarkt.com/emil-bergstrom/profil/spieler/142208.
Transfer history data appended for: https://www.transfermarkt.com/thijmen-nijhuis/profil/spieler/315235.
Transfer history data appended for: https://www.transfermarkt.com/tommy-st-jago/profil/spieler/458734.
Transfer history data appended for: https://www.transfermarkt.com/odysseus-velanas/profil/spieler/360520.
Transfer history data appended for: https://www.transfermarkt.com/django-warmerdam/profil/spieler/288449.
Transfer history data appended for: https://www.transfermarkt.com/maarten-paes/profil/spieler/396077.
Transfer history data appended for: https://www.transfermarkt.com/adam-maher/profil/spieler/122421.
Transfer history data appended for: https://www.transfermarkt.com/urby-emanuelson/profil/spieler/20586.
Transfer history data appended for: https://www.transfermarkt.com/fabian-de-keijzer/profil/spieler/462285.
Transfer history data appended for: https://www.transfermarkt.com/daniel-arzani/profil/spieler/399997.
Transfer history data appended for: https://www.transfermarkt.com/willem-janssen/profil/spieler/19409.
Transfer history data appended for: https://www.transfermarkt.com/adrian-dalmau/profil/spieler/288228.
Transfer history data appended for: https://www.transfermarkt.com/gyrano-kerk/profil/spieler/268112.
Transfer history data appended for: https://www.transfermarkt.com/simon-gustafson/profil/spieler/255474.
Transfer history data appended for: https://www.transfermarkt.com/sander-van-de-streek/profil/spieler/190222.
Transfer history data appended for: https://www.transfermarkt.com/justin-lonwijk/profil/spieler/357917.
Transfer history data appended for: https://www.transfermarkt.com/mimoun-mahi/profil/spieler/216815.
Transfer history data appended for: https://www.transfermarkt.com/giovanni-troupee/profil/spieler/360514.
Transfer history data appended for: https://www.transfermarkt.com/othman-boussaid/profil/spieler/481117.
Transfer history data appended for: https://www.transfermarkt.com/filip-ronningen-jorgensen/profil/spieler/698816.
Transfer history data appended for: https://www.transfermarkt.com/elias-skogvoll/profil/spieler/239062.
Transfer history data appended for: https://www.transfermarkt.com/steffen-hagen/profil/spieler/41187.
Transfer history data appended for: https://www.transfermarkt.com/vebjorn-hoff/profil/spieler/271755.
Transfer history data appended for: https://www.transfermarkt.com/marius-bustgaard-larsen/profil/spieler/418564.
Transfer history data appended for: https://www.transfermarkt.com/espen-ruud/profil/spieler/24113.
Transfer history data appended for: https://www.transfermarkt.com/joshua-kitolano/profil/spieler/432694.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-rodic/profil/spieler/283917.
Transfer history data appended for: https://www.transfermarkt.com/tobias-lauritsen/profil/spieler/272206.
Transfer history data appended for: https://www.transfermarkt.com/thomas-hallstensen/profil/spieler/663751.
Transfer history data appended for: https://www.transfermarkt.com/john-kitolano/profil/spieler/412597.
Transfer history data appended for: https://www.transfermarkt.com/elba-rashani/profil/spieler/149579.
Transfer history data appended for: https://www.transfermarkt.com/egil-selvik/profil/spieler/380744.
Transfer history data appended for: https://www.transfermarkt.com/kachi/profil/spieler/389262.
Transfer history data appended for: https://www.transfermarkt.com/kevin-egell-johnsen/profil/spieler/522167.
Transfer history data appended for: https://www.transfermarkt.com/odin-luras-bjortuft/profil/spieler/502558.
Transfer history data appended for: https://www.transfermarkt.com/sondre-rossbach/profil/spieler/239055.
Transfer history data appended for: https://www.transfermarkt.com/eirik-asante-gayi/profil/spieler/578546.
Transfer history data appended for: https://www.transfermarkt.com/mushaga-bakenga/profil/spieler/121577.
Transfer history data appended for: https://www.transfermarkt.com/bjorn-maeland/profil/spieler/574494.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-berge/profil/spieler/103539.
Transfer history data appended for: https://www.transfermarkt.com/markus-andre-kaasa/profil/spieler/463030.
Transfer history data appended for: https://www.transfermarkt.com/robin-simovic/profil/spieler/213851.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-nordkvelle/profil/spieler/43614.
Transfer history data appended for: https://www.transfermarkt.com/ole-didrik-blomberg/profil/spieler/644607.
Transfer history data appended for: https://www.transfermarkt.com/taijo-teniste/profil/spieler/42808.
Transfer history data appended for: https://www.transfermarkt.com/marcus-johansen-mehnert/profil/spieler/312594.
Transfer history data appended for: https://www.transfermarkt.com/gilli-rolantsson/profil/spieler/95990.
Transfer history data appended for: https://www.transfermarkt.com/thomas-grogaard/profil/spieler/225735.
Transfer history data appended for: https://www.transfermarkt.com/jon-helge-tveita/profil/spieler/128028.
Transfer history data appended for: https://www.transfermarkt.com/markus-pettersen/profil/spieler/367273.
Transfer history data appended for: https://www.transfermarkt.com/robert-taylor/profil/spieler/251836.
Transfer history data appended for: https://www.transfermarkt.com/erlend-hustad/profil/spieler/369099.
Transfer history data appended for: https://www.transfermarkt.com/bismar-acosta/profil/spieler/122679.
Transfer history data appended for: https://www.transfermarkt.com/sander-svendsen/profil/spieler/269503.
Transfer history data appended for: https://www.transfermarkt.com/petter-strand/profil/spieler/319661.
Transfer history data appended for: https://www.transfermarkt.com/vegard-forren/profil/spieler/62054.
Transfer history data appended for: https://www.transfermarkt.com/ali-ahamada/profil/spieler/126767.
Transfer history data appended for: https://www.transfermarkt.com/daniel-pedersen/profil/spieler/187957.
Transfer history data appended for: https://www.transfermarkt.com/hakon-opdal/profil/spieler/15472.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-barmen/profil/spieler/187172.
Transfer history data appended for: https://www.transfermarkt.com/amer-ordagic/profil/spieler/231869.
Transfer history data appended for: https://www.transfermarkt.com/daouda-karamoko-bamba/profil/spieler/285472.
Transfer history data appended for: https://www.transfermarkt.com/mathias-rasmussen/profil/spieler/268327.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-haugen/profil/spieler/73450.
Transfer history data appended for: https://www.transfermarkt.com/ole-martin-kolskogen/profil/spieler/519561.

Transfer history data appended for: https://www.transfermarkt.com/ruben-kristiansen/profil/spieler/150295.
Transfer history data appended for: https://www.transfermarkt.com/jon-gudni-fjoluson/profil/spieler/103732.
Transfer history data appended for: https://www.transfermarkt.com/isak-dybvik-maatta/profil/spieler/664809.
Transfer history data appended for: https://www.transfermarkt.com/gudmund-kongshavn/profil/spieler/122337.
Transfer history data appended for: https://www.transfermarkt.com/daan-klinkenberg/profil/spieler/344895.
Transfer history data appended for: https://www.transfermarkt.com/niklas-castro/profil/spieler/410557.
Transfer history data appended for: https://www.transfermarkt.com/ben-karamoko/profil/spieler/290549.
Transfer history data appended for: https://www.transfermarkt.com/izunna-uzochukwu/profil/spieler/102045.
Transfer history data appended for: https://www.transfermarkt.com/stale-saethre/profil/spieler/234919.
Transfer history data appended for: https://www.transfermarkt.com/jonas-gronner/profil/spieler/153430.
Transfer history data appended for: https://www.transfermarkt.com/jorgen-hatlehol/profil/spieler/368800.
Transfer history data appended for: https://www.transfermarkt.com/vetle-fiskerstrand/profil/spieler/664810.
Transfer history data appended for: https://www.transfermarkt.com/nenass/profil/spieler/461208.
Transfer history data appended for: https://www.transfermarkt.com/torbjorn-agdestein/profil/spieler/151659.
Transfer history data appended for: https://www.transfermarkt.com/markus-karlsbakk/profil/spieler/519882.
Transfer history data appended for: https://www.transfermarkt.com/simen-bolkan-nordli/profil/spieler/418751.
Transfer history data appended for: https://www.transfermarkt.com/sigurd-haugen/profil/spieler/386541.
Transfer history data appended for: https://www.transfermarkt.com/oddbjorn-lie/profil/spieler/27642.
Transfer history data appended for: https://www.transfermarkt.com/david-kristjan-olafsson/profil/spieler/313888.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-carlsen/profil/spieler/73330.
Transfer history data appended for: https://www.transfermarkt.com/sigurd-vidhammer-tafjord/profil/spieler/734649.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-diaw/profil/spieler/830567.
Transfer history data appended for: https://www.transfermarkt.com/shaquill-sno/profil/spieler/290691.
Transfer history data appended for: https://www.transfermarkt.com/parfait-bizoza/profil/spieler/634963.
Transfer history data appended for: https://www.transfermarkt.com/peter-orry-larsen/profil/spieler/62072.
Transfer history data appended for: https://www.transfermarkt.com/andreas-lie/profil/spieler/27641.
Transfer history data appended for: https://www.transfermarkt.com/kasper-jorgensen/profil/spieler/467236.
Transfer history data appended for: https://www.transfermarkt.com/enock-mawete-mwimba/profil/spieler/464592.
Transfer history data appended for: https://www.transfermarkt.com/magnar-odegaard/profil/spieler/106437.
Transfer history data appended for: https://www.transfermarkt.com/joachim-thomassen/profil/spieler/73336.
Transfer history data appended for: https://www.transfermarkt.com/simen-vidtun-nilsen/profil/spieler/736962.
Transfer history data appended for: https://www.transfermarkt.com/isak-heen-berge/profil/spieler/523203.
Transfer history data appended for: https://www.transfermarkt.com/anton-saletros/profil/spieler/249102.
Transfer history data appended for: https://www.transfermarkt.com/jordan-adeoti/profil/spieler/228891.
Transfer history data appended for: https://www.transfermarkt.com/laurent-mendy/profil/spieler/838811.
Transfer history data appended for: https://www.transfermarkt.com/david-mitov-nilsson/profil/spieler/100988.
Transfer history data appended for: https://www.transfermarkt.com/nicolai-naess/profil/spieler/222275.
Transfer history data appended for: https://www.transfermarkt.com/joachim-soltvedt/profil/spieler/326875.
Transfer history data appended for: https://www.transfermarkt.com/bjorn-inge-utvik/profil/spieler/226530.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-ofkir/profil/spieler/369650.
Transfer history data appended for: https://www.transfermarkt.com/anwar-elyounoussi/profil/spieler/551922.
Transfer history data appended for: https://www.transfermarkt.com/alexander-ruud-tveter/profil/spieler/146803.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-lindseth/profil/spieler/234345.
Transfer history data appended for: https://www.transfermarkt.com/ole-jorgen-halvorsen/profil/spieler/42134.
Transfer history data appended for: https://www.transfermarkt.com/mostm/profil/spieler/103558.
Transfer history data appended for: https://www.transfermarkt.com/jorgen-horn/profil/spieler/37333.
Transfer history data appended for: https://www.transfermarkt.com/aboubacar-konte/profil/spieler/649017.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-jarl/profil/spieler/501833.
Transfer history data appended for: https://www.transfermarkt.com/sulayman-bojang/profil/spieler/501819.
Transfer history data appended for: https://www.transfermarkt.com/johan-meldalen-olstad/profil/spieler/528651.
Transfer history data appended for: https://www.transfermarkt.com/mikael-dyrestam/profil/spieler/96043.
Transfer history data appended for: https://www.transfermarkt.com/gaute-hoberg-vetti/profil/spieler/400116.
Transfer history data appended for: https://www.transfermarkt.com/simon-thomas/profil/spieler/103630.
Transfer history data appended for: https://www.transfermarkt.com/tobias-heintz/profil/spieler/329714.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-gunnarshaug/profil/spieler/451683.
Transfer history data appended for: https://www.transfermarkt.com/ulrik-fredriksen/profil/spieler/501989.
Transfer history data appended for: https://www.transfermarkt.com/kevin-martin-krygard/profil/spieler/418563.
Transfer history data appended for: https://www.transfermarkt.com/jonas-valland/profil/spieler/670106.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-kone/profil/spieler/490223.
Transfer history data appended for: https://www.transfermarkt.com/thore-pedersen/profil/spieler/268151.
Transfer history data appended for: https://www.transfermarkt.com/niklas-sandberg/profil/spieler/312771.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima-wadji/profil/spieler/364232.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-velde/profil/spieler/499859.
Transfer history data appended for: https://www.transfermarkt.com/alexander-ammitzboll/profil/spieler/528915.
Transfer history data appended for: https://www.transfermarkt.com/christian-grindheim/profil/spieler/34237.
Transfer history data appended for: https://www.transfermarkt.com/bruno-leite/profil/spieler/476167.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-knudsen/profil/spieler/347849.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-desler/profil/spieler/221873.
Transfer history data appended for: https://www.transfermarkt.com/ludek-vejmola/profil/spieler/265892.
Transfer history data appended for: https://www.transfermarkt.com/alexander-stolas/profil/spieler/107516.
Transfer history data appended for: https://www.transfermarkt.com/joakim-vage-nilsen/profil/spieler/73543.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-hansen/profil/spieler/108468.
Transfer history data appended for: https://www.transfermarkt.com/helge-sandvik/profil/spieler/209467.
Transfer history data appended for: https://www.transfermarkt.com/frank-stople/profil/spieler/605557.
Transfer history data appended for: https://www.transfermarkt.com/oliver-klitten/profil/spieler/525971.
Transfer history data appended for: https://www.transfermarkt.com/peter-therkildsen/profil/spieler/428444.
Transfer history data appended for: https://www.transfermarkt.com/joackim-solberg/profil/spieler/100235.
Transfer history data appended for: https://www.transfermarkt.com/dagur-dan-thorhallsson/profil/spieler/447482.

Transfer history data appended for: https://www.transfermarkt.com/isaac-twum/profil/spieler/287450.
Transfer history data appended for: https://www.transfermarkt.com/sondre-johansen/profil/spieler/258506.
Transfer history data appended for: https://www.transfermarkt.com/ole-amund-sveen/profil/spieler/114556.
Transfer history data appended for: https://www.transfermarkt.com/quint-jansen/profil/spieler/395004.
Transfer history data appended for: https://www.transfermarkt.com/andreas-hellum/profil/spieler/376596.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-brustad/profil/spieler/152481.
Transfer history data appended for: https://www.transfermarkt.com/jorge-vieira/profil/spieler/290106.
Transfer history data appended for: https://www.transfermarkt.com/frank-bamenye-bizoza/profil/spieler/635382.
Transfer history data appended for: https://www.transfermarkt.com/markus-nakkim/profil/spieler/368806.
Transfer history data appended for: https://www.transfermarkt.com/sondre-liseth/profil/spieler/442474.
Transfer history data appended for: https://www.transfermarkt.com/martin-ovenstad/profil/spieler/146797.
Transfer history data appended for: https://www.transfermarkt.com/sosha-makani/profil/spieler/216043.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-stephensen/profil/spieler/258678.
Transfer history data appended for: https://www.transfermarkt.com/vamouti-diomande/profil/spieler/145118.
Transfer history data appended for: https://www.transfermarkt.com/stian-aasmundsen/profil/spieler/265310.
Transfer history data appended for: https://www.transfermarkt.com/william-sell/profil/spieler/376595.
Transfer history data appended for: https://www.transfermarkt.com/vetle-dragsnes/profil/spieler/320046.
Transfer history data appended for: https://www.transfermarkt.com/magnus-baekken/profil/spieler/743311.
Transfer history data appended for: https://www.transfermarkt.com/lars-olden-larsen/profil/spieler/432682.
Transfer history data appended for: https://www.transfermarkt.com/tonny-brochmann/profil/spieler/102048.
Transfer history data appended for: https://www.transfermarkt.com/georges-bokwe/profil/spieler/364823.
Transfer history data appended for: https://www.transfermarkt.com/alexander-hansen/profil/spieler/440780.
Transfer history data appended for: https://www.transfermarkt.com/aristide-mutula-sagbakken/profil/spieler/609009.
Transfer history data appended for: https://www.transfermarkt.com/christian-gauseth/profil/spieler/62056.
Transfer history data appended for: https://www.transfermarkt.com/shuaibu-lalle-ibrahim/profil/spieler/419686.
Transfer history data appended for: https://www.transfermarkt.com/mathias-fredriksen/profil/spieler/225537.
Transfer history data appended for: https://www.transfermarkt.com/ivar-furu/profil/spieler/180752.
Transfer history data appended for: https://www.transfermarkt.com/faris-moumbagna/profil/spieler/599663.
Transfer history data appended for: https://www.transfermarkt.com/kjetil-holand-tosse/profil/spieler/501617.
Transfer history data appended for: https://www.transfermarkt.com/christophe-psyche/profil/spieler/183746.
Transfer history data appended for: https://www.transfermarkt.com/olaus-skarsem/profil/spieler/429287.
Transfer history data appended for: https://www.transfermarkt.com/noah-solskjaer/profil/spieler/810788.
Transfer history data appended for: https://www.transfermarkt.com/dan-peter-ulvestad/profil/spieler/155555.
Transfer history data appended for: https://www.transfermarkt.com/sondre-sorli/profil/spieler/320140.
Transfer history data appended for: https://www.transfermarkt.com/sean-mcdermott/profil/spieler/126194.
Transfer history data appended for: https://www.transfermarkt.com/eirik-johansen/profil/spieler/121387.
Transfer history data appended for: https://www.transfermarkt.com/bendik-bye/profil/spieler/182176.
Transfer history data appended for: https://www.transfermarkt.com/amahl-pellegrino/profil/spieler/218278.
Transfer history data appended for: https://www.transfermarkt.com/pal-erik-ulvestad/profil/spieler/180754.
Transfer history data appended for: https://www.transfermarkt.com/amidou-diop/profil/spieler/336672.
Transfer history data appended for: https://www.transfermarkt.com/horenus-tadesse/profil/spieler/499823.
Transfer history data appended for: https://www.transfermarkt.com/aliou-coly/profil/spieler/220841.
Transfer history data appended for: https://www.transfermarkt.com/max-williamsen/profil/spieler/698969.
Transfer history data appended for: https://www.transfermarkt.com/andreas-hopmark/profil/spieler/230141.
Transfer history data appended for: https://www.transfermarkt.com/bent-sormo/profil/spieler/268713.
Transfer history data appended for: https://www.transfermarkt.com/christoffer-aasbak/profil/spieler/136166.
Transfer history data appended for: https://www.transfermarkt.com/liridon-kalludra/profil/spieler/91230.
Transfer history data appended for: https://www.transfermarkt.com/flamur-kastrati/profil/spieler/100628.
Transfer history data appended for: https://www.transfermarkt.com/oskar-sivertsen/profil/spieler/715510.
Transfer history data appended for: https://www.transfermarkt.com/ousseynou-diagne/profil/spieler/541034.
Transfer history data appended for: https://www.transfermarkt.com/amin-soleiman-askar/profil/spieler/38127.
Transfer history data appended for: https://www.transfermarkt.com/vidar-orn-kjartansson/profil/spieler/115607.
Transfer history data appended for: https://www.transfermarkt.com/odin-thiago-holm/profil/spieler/581109.
Transfer history data appended for: https://www.transfermarkt.com/ousmane-camara/profil/spieler/402134.
Transfer history data appended for: https://www.transfermarkt.com/jonatan-tollas-nation/profil/spieler/73441.
Transfer history data appended for: https://www.transfermarkt.com/henrik-bjordal/profil/spieler/268620.
Transfer history data appended for: https://www.transfermarkt.com/matthias-vilhjalmsson/profil/spieler/53241.
Transfer history data appended for: https://www.transfermarkt.com/ivan-nasberg/profil/spieler/239046.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-klaesson/profil/spieler/418561.
Transfer history data appended for: https://www.transfermarkt.com/felipe-carvalho/profil/spieler/356685.
Transfer history data appended for: https://www.transfermarkt.com/brage-skaret/profil/spieler/539662.
Transfer history data appended for: https://www.transfermarkt.com/magnus-lekven/profil/spieler/41191.
Transfer history data appended for: https://www.transfermarkt.com/magnus-riisnaes/profil/spieler/715508.
Transfer history data appended for: https://www.transfermarkt.com/osame-sahraoui/profil/spieler/580657.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-stokke/profil/spieler/180221.
Transfer history data appended for: https://www.transfermarkt.com/oskar-aron-opsahl/profil/spieler/432705.
Transfer history data appended for: https://www.transfermarkt.com/felix-horn-myhre/profil/spieler/367274.
Transfer history data appended for: https://www.transfermarkt.com/sam-adekugbe/profil/spieler/287578.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-jensen/profil/spieler/218233.
Transfer history data appended for: https://www.transfermarkt.com/johan-bjordal/profil/spieler/26751.
Transfer history data appended for: https://www.transfermarkt.com/bard-finne/profil/spieler/202925.
Transfer history data appended for: https://www.transfermarkt.com/herolind-shala/profil/spieler/125751.
Transfer history data appended for: https://www.transfermarkt.com/christian-dahle-borchgrevink/profil/spieler/367244.
Transfer history data appended for: https://www.transfermarkt.com/kjetil-haug/profil/spieler/328770.
Transfer history data appended for: https://www.transfermarkt.com/aron-donnum/profil/spieler/476836.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-maigaard/profil/spieler/265545.
Transfer history data appended for: https://www.transfermarkt.com/sondre-fosnaess-hanssen/profil/spieler/675904.
Transfer history data appended for: https://www.transfermarkt.com/morten-saetra/profil/spieler/326594.

Transfer history data appended for: https://www.transfermarkt.com/duplexe-tchamba/profil/spieler/490760.
Transfer history data appended for: https://www.transfermarkt.com/viljar-myhra/profil/spieler/291254.
Transfer history data appended for: https://www.transfermarkt.com/marcus-molvadgaard/profil/spieler/345749.
Transfer history data appended for: https://www.transfermarkt.com/daniel-skretteberg/profil/spieler/711280.
Transfer history data appended for: https://www.transfermarkt.com/prosper-mendy/profil/spieler/611956.
Transfer history data appended for: https://www.transfermarkt.com/simen-hammershaug/profil/spieler/660547.
Transfer history data appended for: https://www.transfermarkt.com/halldor-stenevik/profil/spieler/400121.
Transfer history data appended for: https://www.transfermarkt.com/lars-jorgen-salvesen/profil/spieler/336640.
Transfer history data appended for: https://www.transfermarkt.com/lars-christopher-vilsvik/profil/spieler/41997.
Transfer history data appended for: https://www.transfermarkt.com/tobias-fjeld-gulliksen/profil/spieler/619657.
Transfer history data appended for: https://www.transfermarkt.com/nicholas-mickelson/profil/spieler/430034.
Transfer history data appended for: https://www.transfermarkt.com/ari-leifsson/profil/spieler/369633.
Transfer history data appended for: https://www.transfermarkt.com/moses-mawa/profil/spieler/433833.
Transfer history data appended for: https://www.transfermarkt.com/jack-ipalibo/profil/spieler/527967.
Transfer history data appended for: https://www.transfermarkt.com/herman-stengel/profil/spieler/183588.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-tokstad/profil/spieler/113651.
Transfer history data appended for: https://www.transfermarkt.com/johan-hove/profil/spieler/418557.
Transfer history data appended for: https://www.transfermarkt.com/kreshnik-krasniqi/profil/spieler/375419.
Transfer history data appended for: https://www.transfermarkt.com/aleksander-stenseth/profil/spieler/806569.
Transfer history data appended for: https://www.transfermarkt.com/daniel-kubrom-hamde/profil/spieler/581115.
Transfer history data appended for: https://www.transfermarkt.com/valdimar-thor-ingimundarson/profil/spieler/422438.
Transfer history data appended for: https://www.transfermarkt.com/niklas-gunnarsson/profil/spieler/180442.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-parr/profil/spieler/41665.
Transfer history data appended for: https://www.transfermarkt.com/jacob-storevik/profil/spieler/214774.
Transfer history data appended for: https://www.transfermarkt.com/marc-vales/profil/spieler/84241.
Transfer history data appended for: https://www.transfermarkt.com/sander-risan-mork/profil/spieler/622421.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-hansen/profil/spieler/180215.
Transfer history data appended for: https://www.transfermarkt.com/stefan-mladenovic/profil/spieler/413151.
Transfer history data appended for: https://www.transfermarkt.com/emil-palsson/profil/spieler/137650.
Transfer history data appended for: https://www.transfermarkt.com/marcos-celorrio/profil/spieler/309081.
Transfer history data appended for: https://www.transfermarkt.com/sivert-gussias/profil/spieler/538730.
Transfer history data appended for: https://www.transfermarkt.com/anton-kralj/profil/spieler/322071.
Transfer history data appended for: https://www.transfermarkt.com/erik-brenden/profil/spieler/182182.
Transfer history data appended for: https://www.transfermarkt.com/rufo/profil/spieler/247909.
Transfer history data appended for: https://www.transfermarkt.com/george-nuah-gibson/profil/spieler/580441.
Transfer history data appended for: https://www.transfermarkt.com/william-kurtovic/profil/spieler/323296.
Transfer history data appended for: https://www.transfermarkt.com/harmeet-singh/profil/spieler/62125.
Transfer history data appended for: https://www.transfermarkt.com/mats-haakenstad/profil/spieler/260113.
Transfer history data appended for: https://www.transfermarkt.com/lars-markmanrud/profil/spieler/786742.
Transfer history data appended for: https://www.transfermarkt.com/martin-kreuzriegler/profil/spieler/120197.
Transfer history data appended for: https://www.transfermarkt.com/henrik-falchener/profil/spieler/743088.
Transfer history data appended for: https://www.transfermarkt.com/brice-wembangomo/profil/spieler/331214.
Transfer history data appended for: https://www.transfermarkt.com/jesper-granlund/profil/spieler/441880.
Transfer history data appended for: https://www.transfermarkt.com/enric-valles/profil/spieler/65305.
Transfer history data appended for: https://www.transfermarkt.com/lars-grorud/profil/spieler/73507.
Transfer history data appended for: https://www.transfermarkt.com/deyver-vega/profil/spieler/131267.
Transfer history data appended for: https://www.transfermarkt.com/vidar-ari-jonsson/profil/spieler/178918.
Transfer history data appended for: https://www.transfermarkt.com/sander-moen-foss/profil/spieler/440972.
Transfer history data appended for: https://www.transfermarkt.com/ylldren-ibrahimaj/profil/spieler/230845.
Transfer history data appended for: https://www.transfermarkt.com/johnny-furdal/profil/spieler/10249.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-lokberg/profil/spieler/161353.
Transfer history data appended for: https://www.transfermarkt.com/trym-solvberg-ur/profil/spieler/787001.
Transfer history data appended for: https://www.transfermarkt.com/veton-berisha/profil/spieler/181985.
Transfer history data appended for: https://www.transfermarkt.com/tommy-hoiland/profil/spieler/41848.
Transfer history data appended for: https://www.transfermarkt.com/zymer-bytyqi/profil/spieler/213555.
Transfer history data appended for: https://www.transfermarkt.com/viljar-vevatne/profil/spieler/240012.
Transfer history data appended for: https://www.transfermarkt.com/runar-hove/profil/spieler/231032.
Transfer history data appended for: https://www.transfermarkt.com/michael-crowe/profil/spieler/203840.
Transfer history data appended for: https://www.transfermarkt.com/even-ostensen/profil/spieler/231396.
Transfer history data appended for: https://www.transfermarkt.com/samuel-fridjonsson/profil/spieler/240408.
Transfer history data appended for: https://www.transfermarkt.com/joe-bell/profil/spieler/345700.
Transfer history data appended for: https://www.transfermarkt.com/iven-austbo/profil/spieler/26748.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-soraas-sebulonsen/profil/spieler/592387.
Transfer history data appended for: https://www.transfermarkt.com/sondre-bjorshol/profil/spieler/338939.
Transfer history data appended for: https://www.transfermarkt.com/axel-oskar-andresson/profil/spieler/316242.
Transfer history data appended for: https://www.transfermarkt.com/sondre-auklend/profil/spieler/581112.
Transfer history data appended for: https://www.transfermarkt.com/jefferson-de-souza/profil/spieler/640143.
Transfer history data appended for: https://www.transfermarkt.com/arild-ostbo/profil/spieler/73327.
Transfer history data appended for: https://www.transfermarkt.com/henrik-heggheim/profil/spieler/790245.
Transfer history data appended for: https://www.transfermarkt.com/yann-erik-de-lanlay/profil/spieler/163642.
Transfer history data appended for: https://www.transfermarkt.com/rolf-daniel-vikstol/profil/spieler/103485.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-torsteinbo/profil/spieler/180204.
Transfer history data appended for: https://www.transfermarkt.com/morten-konradsen/profil/spieler/224080.
Transfer history data appended for: https://www.transfermarkt.com/joshua-smits/profil/spieler/190687.
Transfer history data appended for: https://www.transfermarkt.com/ola-solbakken/profil/spieler/431811.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-tounekti/profil/spieler/539677.
Transfer history data appended for: https://www.transfermarkt.com/vegard-moberg/profil/spieler/229031.
Transfer history data appended for: https://www.transfermarkt.com/marius-hoibraten/profil/spieler/208587.

Transfer history data appended for: https://www.transfermarkt.com/philip-zinckernagel/profil/spieler/271098.
Transfer history data appended for: https://www.transfermarkt.com/ulrik-saltnes/profil/spieler/201865.
Transfer history data appended for: https://www.transfermarkt.com/runar-hauge/profil/spieler/494180.
Transfer history data appended for: https://www.transfermarkt.com/nikita-haikin/profil/spieler/255440.
Transfer history data appended for: https://www.transfermarkt.com/mads-fagerli-halsoy/profil/spieler/661426.
Transfer history data appended for: https://www.transfermarkt.com/elias-kristoffersen-hagen/profil/spieler/566410.
Transfer history data appended for: https://www.transfermarkt.com/patrick-berg/profil/spieler/308439.
Transfer history data appended for: https://www.transfermarkt.com/hugo-vetlesen/profil/spieler/499758.
Transfer history data appended for: https://www.transfermarkt.com/marius-lode/profil/spieler/223197.
Transfer history data appended for: https://www.transfermarkt.com/marcus-andersen/profil/spieler/432688.
Transfer history data appended for: https://www.transfermarkt.com/sondre-fet/profil/spieler/335298.
Transfer history data appended for: https://www.transfermarkt.com/brede-moe/profil/spieler/182181.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-andre-bjorkan/profil/spieler/364938.
Transfer history data appended for: https://www.transfermarkt.com/alfons-sampsted/profil/spieler/332530.
Transfer history data appended for: https://www.transfermarkt.com/victor-boniface/profil/spieler/656681.
Transfer history data appended for: https://www.transfermarkt.com/kasper-junker/profil/spieler/264576.
Transfer history data appended for: https://www.transfermarkt.com/aleksander-foosnaes/profil/spieler/182179.
Transfer history data appended for: https://www.transfermarkt.com/isak-helstad-amundsen/profil/spieler/746604.
Transfer history data appended for: https://www.transfermarkt.com/younes-amer/profil/spieler/521016.
Transfer history data appended for: https://www.transfermarkt.com/peder-vogt/profil/spieler/578549.
Transfer history data appended for: https://www.transfermarkt.com/mats-solheim/profil/spieler/61895.
Transfer history data appended for: https://www.transfermarkt.com/yaw-amankwah/profil/spieler/73373.
Transfer history data appended for: https://www.transfermarkt.com/kosuke-kinoshita/profil/spieler/221968.
Transfer history data appended for: https://www.transfermarkt.com/oliver-valaker-edvardsen/profil/spieler/374326.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-pignatel-jenssen/profil/spieler/539660.
Transfer history data appended for: https://www.transfermarkt.com/marius-amundsen-ulla/profil/spieler/539658.
Transfer history data appended for: https://www.transfermarkt.com/jonas-vatne-brauti/profil/spieler/523049.
Transfer history data appended for: https://www.transfermarkt.com/magnus-lundal/profil/spieler/476748.
Transfer history data appended for: https://www.transfermarkt.com/kaloyan-kostadinov/profil/spieler/590205.
Transfer history data appended for: https://www.transfermarkt.com/marcus-sandberg/profil/spieler/63443.
Transfer history data appended for: https://www.transfermarkt.com/gustav-valsvik/profil/spieler/136185.
Transfer history data appended for: https://www.transfermarkt.com/jeppe-moe/profil/spieler/312595.
Transfer history data appended for: https://www.transfermarkt.com/tortol-lumanza/profil/spieler/138679.
Transfer history data appended for: https://www.transfermarkt.com/erik-botheim/profil/spieler/418559.
Transfer history data appended for: https://www.transfermarkt.com/sturla-ottesen/profil/spieler/666526.
Transfer history data appended for: https://www.transfermarkt.com/luc-kassi/profil/spieler/238694.
Transfer history data appended for: https://www.transfermarkt.com/kornelius-hansen/profil/spieler/432698.
Transfer history data appended for: https://www.transfermarkt.com/emil-bohinen/profil/spieler/406806.
Transfer history data appended for: https://www.transfermarkt.com/sammy-skytte/profil/spieler/320279.
Transfer history data appended for: https://www.transfermarkt.com/christopher-cheng/profil/spieler/578547.
Transfer history data appended for: https://www.transfermarkt.com/jorgen-overaas/profil/spieler/217646.
Transfer history data appended for: https://www.transfermarkt.com/emil-jonassen/profil/spieler/136178.
Transfer history data appended for: https://www.transfermarkt.com/darren-maatsen/profil/spieler/190874.
Transfer history data appended for: https://www.transfermarkt.com/marcus-antonsson/profil/spieler/171676.
Transfer history data appended for: https://www.transfermarkt.com/oliver-petersen/profil/spieler/592163.
Transfer history data appended for: https://www.transfermarkt.com/erling-knudtzon/profil/spieler/49470.
Transfer history data appended for: https://www.transfermarkt.com/martin-ellingsen/profil/spieler/263718.
Transfer history data appended for: https://www.transfermarkt.com/andreas-linde/profil/spieler/199221.
Transfer history data appended for: https://www.transfermarkt.com/leke-james/profil/spieler/212642.
Transfer history data appended for: https://www.transfermarkt.com/mathis-bolly/profil/spieler/85611.
Transfer history data appended for: https://www.transfermarkt.com/henry-wingo/profil/spieler/378478.
Transfer history data appended for: https://www.transfermarkt.com/alex-craninx/profil/spieler/208512.
Transfer history data appended for: https://www.transfermarkt.com/martin-bjornbak/profil/spieler/184794.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-haugen/profil/spieler/225823.
Transfer history data appended for: https://www.transfermarkt.com/tobias-christensen/profil/spieler/370894.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-sjolstad/profil/spieler/180064.
Transfer history data appended for: https://www.transfermarkt.com/mattias-mostrom/profil/spieler/18099.
Transfer history data appended for: https://www.transfermarkt.com/magnus-wolff-eikrem/profil/spieler/54775.
Transfer history data appended for: https://www.transfermarkt.com/mathias-eriksen-ranmark/profil/spieler/410450.
Transfer history data appended for: https://www.transfermarkt.com/ohi-omoijuanfo/profil/spieler/169368.
Transfer history data appended for: https://www.transfermarkt.com/ola-brynhildsen/profil/spieler/499759.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-aursnes/profil/spieler/223367.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-haraldseid/profil/spieler/183617.
Transfer history data appended for: https://www.transfermarkt.com/marcus-holmgren-pedersen/profil/spieler/583404.
Transfer history data appended for: https://www.transfermarkt.com/eirik-hestad/profil/spieler/228069.
Transfer history data appended for: https://www.transfermarkt.com/birk-risa/profil/spieler/331575.
Transfer history data appended for: https://www.transfermarkt.com/sheriff-sinyan/profil/spieler/394435.
Transfer history data appended for: https://www.transfermarkt.com/eirik-andersen/profil/spieler/184212.
Transfer history data appended for: https://www.transfermarkt.com/etzaz-hussain/profil/spieler/141658.
Transfer history data appended for: https://www.transfermarkt.com/stian-gregersen/profil/spieler/230140.
Transfer history data appended for: https://www.transfermarkt.com/gjermund-asen/profil/spieler/139667.
Transfer history data appended for: https://www.transfermarkt.com/holmar-orn-eyjolfsson/profil/spieler/54871.
Transfer history data appended for: https://www.transfermarkt.com/andre-hansen/profil/spieler/103555.
Transfer history data appended for: https://www.transfermarkt.com/anders-konradsen/profil/spieler/62013.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-zachariassen/profil/spieler/261020.
Transfer history data appended for: https://www.transfermarkt.com/warren-kamanzi/profil/spieler/794758.
Transfer history data appended for: https://www.transfermarkt.com/emil-konradsen-ceide/profil/spieler/508371.
Transfer history data appended for: https://www.transfermarkt.com/robin-bjorkas-skrogstad/profil/spieler/605564.

Transfer history data appended for: https://www.transfermarkt.com/even-hovland/profil/spieler/41875.
Transfer history data appended for: https://www.transfermarkt.com/erlend-dahl-reitan/profil/spieler/369100.
Transfer history data appended for: https://www.transfermarkt.com/pa-konate/profil/spieler/223864.
Transfer history data appended for: https://www.transfermarkt.com/carlo-holse/profil/spieler/345577.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-wiedesheim-paul/profil/spieler/430977.
Transfer history data appended for: https://www.transfermarkt.com/vegar-eggen-hedenstad/profil/spieler/73333.
Transfer history data appended for: https://www.transfermarkt.com/pal-andre-helland/profil/spieler/103567.
Transfer history data appended for: https://www.transfermarkt.com/markus-henriksen/profil/spieler/122011.
Transfer history data appended for: https://www.transfermarkt.com/andreas-helmersen/profil/spieler/333012.
Transfer history data appended for: https://www.transfermarkt.com/per-ciljan-skjelbred/profil/spieler/18918.
Transfer history data appended for: https://www.transfermarkt.com/julian-faye-lund/profil/spieler/358726.
Transfer history data appended for: https://www.transfermarkt.com/samuel-adegbenro/profil/spieler/356119.
Transfer history data appended for: https://www.transfermarkt.com/dino-islamovic/profil/spieler/208095.
Transfer history data appended for: https://www.transfermarkt.com/edvard-tagseth/profil/spieler/432700.
Transfer history data appended for: https://www.transfermarkt.com/kasper-skaanes/profil/spieler/224457.
Transfer history data appended for: https://www.transfermarkt.com/eman-markovic/profil/spieler/374321.
Transfer history data appended for: https://www.transfermarkt.com/amund-wichne/profil/spieler/308459.
Transfer history data appended for: https://www.transfermarkt.com/henrik-gjesdal/profil/spieler/267748.
Transfer history data appended for: https://www.transfermarkt.com/jonas-deumeland/profil/spieler/40573.
Transfer history data appended for: https://www.transfermarkt.com/sander-sjokvist/profil/spieler/663257.
Transfer history data appended for: https://www.transfermarkt.com/mikael-ugland/profil/spieler/418556.
Transfer history data appended for: https://www.transfermarkt.com/jesper-daland/profil/spieler/418553.
Transfer history data appended for: https://www.transfermarkt.com/steffen-skalevik/profil/spieler/268645.
Transfer history data appended for: https://www.transfermarkt.com/joackim-jorgensen/profil/spieler/42141.
Transfer history data appended for: https://www.transfermarkt.com/martin-ramsland/profil/spieler/260135.
Transfer history data appended for: https://www.transfermarkt.com/gudmundur-andri-tryggvason/profil/spieler/358057.
Transfer history data appended for: https://www.transfermarkt.com/henrik-robstad/profil/spieler/267845.
Transfer history data appended for: https://www.transfermarkt.com/adeleke-akinyemi/profil/spieler/153138.
Transfer history data appended for: https://www.transfermarkt.com/espen-borufsen/profil/spieler/50436.
Transfer history data appended for: https://www.transfermarkt.com/mathias-bringaker/profil/spieler/230362.
Transfer history data appended for: https://www.transfermarkt.com/vegard-bergan/profil/spieler/254735.
Transfer history data appended for: https://www.transfermarkt.com/eirik-schulze/profil/spieler/203659.
Transfer history data appended for: https://www.transfermarkt.com/erlend-segberg/profil/spieler/369101.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-el-makrini/profil/spieler/56375.
Transfer history data appended for: https://www.transfermarkt.com/christian-bolanos/profil/spieler/38163.
Transfer history data appended for: https://www.transfermarkt.com/kevin-kabran/profil/spieler/223090.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-tonnessen/profil/spieler/375403.
Transfer history data appended for: https://www.transfermarkt.com/arian-gundersen/profil/spieler/527066.
Transfer history data appended for: https://www.transfermarkt.com/eirik-wichne/profil/spieler/351524.
Transfer history data appended for: https://www.transfermarkt.com/robert-janicki/profil/spieler/366229.
Transfer history data appended for: https://www.transfermarkt.com/kajetan-szmyt/profil/spieler/658730.
Transfer history data appended for: https://www.transfermarkt.com/nikodem-fiedosewicz/profil/spieler/375290.
Transfer history data appended for: https://www.transfermarkt.com/mario-rodriguez/profil/spieler/251888.
Transfer history data appended for: https://www.transfermarkt.com/daniel-bielica/profil/spieler/463233.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-kupczak/profil/spieler/237523.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-spychala/profil/spieler/293057.
Transfer history data appended for: https://www.transfermarkt.com/jan-wojnowski/profil/spieler/390925.
Transfer history data appended for: https://www.transfermarkt.com/michal-kopczynski/profil/spieler/235977.
Transfer history data appended for: https://www.transfermarkt.com/jan-grzesik/profil/spieler/264278.
Transfer history data appended for: https://www.transfermarkt.com/adrian-laskowski/profil/spieler/146317.
Transfer history data appended for: https://www.transfermarkt.com/mariusz-rybicki/profil/spieler/215124.
Transfer history data appended for: https://www.transfermarkt.com/robert-ivanov/profil/spieler/373876.
Transfer history data appended for: https://www.transfermarkt.com/filip-malek/profil/spieler/781661.
Transfer history data appended for: https://www.transfermarkt.com/jakub-kielb/profil/spieler/181119.
Transfer history data appended for: https://www.transfermarkt.com/dominik-smykowski/profil/spieler/781660.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-czyzycki/profil/spieler/385479.
Transfer history data appended for: https://www.transfermarkt.com/aleks-lawniczak/profil/spieler/425739.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-szczepaniak/profil/spieler/77315.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-tralka/profil/spieler/29538.
Transfer history data appended for: https://www.transfermarkt.com/michal-jakobowski/profil/spieler/224176.
Transfer history data appended for: https://www.transfermarkt.com/gracjan-jaroch/profil/spieler/297217.
Transfer history data appended for: https://www.transfermarkt.com/konrad-handzlik/profil/spieler/297216.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-kuzimski/profil/spieler/381891.
Transfer history data appended for: https://www.transfermarkt.com/leo-przybylak/profil/spieler/801237.
Transfer history data appended for: https://www.transfermarkt.com/adrian-chopcia/profil/spieler/387616.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-kieliba/profil/spieler/266234.
Transfer history data appended for: https://www.transfermarkt.com/jakub-kuzdra/profil/spieler/372280.
Transfer history data appended for: https://www.transfermarkt.com/nikodem-niski/profil/spieler/555110.
Transfer history data appended for: https://www.transfermarkt.com/kacper-kostorz/profil/spieler/510459.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-lakomy/profil/spieler/401598.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-holownia/profil/spieler/266379.
Transfer history data appended for: https://www.transfermarkt.com/filip-mladenovic/profil/spieler/168063.
Transfer history data appended for: https://www.transfermarkt.com/vamara-sanogo/profil/spieler/374667.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-slisz/profil/spieler/382429.
Transfer history data appended for: https://www.transfermarkt.com/pawel-stolarski/profil/spieler/235862.
Transfer history data appended for: https://www.transfermarkt.com/michal-karbownik/profil/spieler/401604.
Transfer history data appended for: https://www.transfermarkt.com/valeriane-gvilia/profil/spieler/335191.
Transfer history data appended for: https://www.transfermarkt.com/radoslaw-cielemecki/profil/spieler/554280.
Transfer history data appended for: https://www.transfermarkt.com/jose-kante/profil/spieler/247276.

Transfer history data appended for: https://www.transfermarkt.com/luis-rocha/profil/spieler/235639.
Transfer history data appended for: https://www.transfermarkt.com/andre-martins/profil/spieler/90367.
Transfer history data appended for: https://www.transfermarkt.com/josip-juranovic/profil/spieler/362977.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-wieteska/profil/spieler/208172.
Transfer history data appended for: https://www.transfermarkt.com/ariel-mosor/profil/spieler/554288.
Transfer history data appended for: https://www.transfermarkt.com/marko-vesovic/profil/spieler/98101.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-cholewiak/profil/spieler/255519.
Transfer history data appended for: https://www.transfermarkt.com/pawel-wszolek/profil/spieler/164759.
Transfer history data appended for: https://www.transfermarkt.com/dominik-nagy/profil/spieler/200651.
Transfer history data appended for: https://www.transfermarkt.com/maciej-rosolek/profil/spieler/401609.
Transfer history data appended for: https://www.transfermarkt.com/rafa-lopes/profil/spieler/162819.
Transfer history data appended for: https://www.transfermarkt.com/wojciech-muzyk/profil/spieler/385022.
Transfer history data appended for: https://www.transfermarkt.com/luquinhas/profil/spieler/402825.
Transfer history data appended for: https://www.transfermarkt.com/domagoj-antolic/profil/spieler/48810.
Transfer history data appended for: https://www.transfermarkt.com/william-remy/profil/spieler/89637.
Transfer history data appended for: https://www.transfermarkt.com/radoslaw-cierzniak/profil/spieler/24501.
Transfer history data appended for: https://www.transfermarkt.com/szymon-wlodarczyk/profil/spieler/554282.
Transfer history data appended for: https://www.transfermarkt.com/inaki-astiz/profil/spieler/52161.
Transfer history data appended for: https://www.transfermarkt.com/joel-valencia/profil/spieler/175451.
Transfer history data appended for: https://www.transfermarkt.com/fran-tudor/profil/spieler/343158.
Transfer history data appended for: https://www.transfermarkt.com/ivi-lopez/profil/spieler/282371.
Transfer history data appended for: https://www.transfermarkt.com/oskar-zawada/profil/spieler/232015.
Transfer history data appended for: https://www.transfermarkt.com/piotr-owczarek/profil/spieler/676250.
Transfer history data appended for: https://www.transfermarkt.com/patryk-kun/profil/spieler/252608.
Transfer history data appended for: https://www.transfermarkt.com/david-tijanic/profil/spieler/351792.
Transfer history data appended for: https://www.transfermarkt.com/andrzej-niewulis/profil/spieler/101070.
Transfer history data appended for: https://www.transfermarkt.com/marcel-zurek/profil/spieler/554318.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-kaczmarek/profil/spieler/577595.
Transfer history data appended for: https://www.transfermarkt.com/kacper-trelowski/profil/spieler/720120.
Transfer history data appended for: https://www.transfermarkt.com/marko-poletanovic/profil/spieler/168957.
Transfer history data appended for: https://www.transfermarkt.com/igor-sapala/profil/spieler/380597.
Transfer history data appended for: https://www.transfermarkt.com/daniel-bartl/profil/spieler/109541.
Transfer history data appended for: https://www.transfermarkt.com/petr-schwarz/profil/spieler/208591.
Transfer history data appended for: https://www.transfermarkt.com/tomas-petrasek/profil/spieler/333261.
Transfer history data appended for: https://www.transfermarkt.com/ben-lederman/profil/spieler/366929.
Transfer history data appended for: https://www.transfermarkt.com/petar-mamic/profil/spieler/226082.
Transfer history data appended for: https://www.transfermarkt.com/daniel-mikolajewski/profil/spieler/448567.
Transfer history data appended for: https://www.transfermarkt.com/vladislavs-gutkovskis/profil/spieler/192710.
Transfer history data appended for: https://www.transfermarkt.com/milosz-szczepanski/profil/spieler/321240.
Transfer history data appended for: https://www.transfermarkt.com/przemyslaw-oziebala/profil/spieler/52435.
Transfer history data appended for: https://www.transfermarkt.com/maciej-wilusz/profil/spieler/42109.
Transfer history data appended for: https://www.transfermarkt.com/oskar-krzyzak/profil/spieler/554976.
Transfer history data appended for: https://www.transfermarkt.com/piotr-malinowski/profil/spieler/47280.
Transfer history data appended for: https://www.transfermarkt.com/giannis-papanikolaou/profil/spieler/448058.
Transfer history data appended for: https://www.transfermarkt.com/jakub-szumski/profil/spieler/157848.
Transfer history data appended for: https://www.transfermarkt.com/michal-litwa/profil/spieler/714021.
Transfer history data appended for: https://www.transfermarkt.com/marcin-cebula/profil/spieler/239215.
Transfer history data appended for: https://www.transfermarkt.com/branislav-pindroch/profil/spieler/176966.
Transfer history data appended for: https://www.transfermarkt.com/kamil-piatkowski/profil/spieler/345449.
Transfer history data appended for: https://www.transfermarkt.com/daniel-szelagowski/profil/spieler/566350.
Transfer history data appended for: https://www.transfermarkt.com/kacper-urbanski/profil/spieler/699442.
Transfer history data appended for: https://www.transfermarkt.com/tomasz-makowski/profil/spieler/320961.
Transfer history data appended for: https://www.transfermarkt.com/conrado/profil/spieler/514674.
Transfer history data appended for: https://www.transfermarkt.com/kristers-tobers/profil/spieler/448883.
Transfer history data appended for: https://www.transfermarkt.com/mario-maloca/profil/spieler/48873.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-kopacz/profil/spieler/153306.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-zwolinski/profil/spieler/220740.
Transfer history data appended for: https://www.transfermarkt.com/maciej-gajos/profil/spieler/236891.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-sopocko/profil/spieler/432044.
Transfer history data appended for: https://www.transfermarkt.com/eryk-mirus/profil/spieler/699438.
Transfer history data appended for: https://www.transfermarkt.com/omran-haydary/profil/spieler/415993.
Transfer history data appended for: https://www.transfermarkt.com/zarko-udovicic/profil/spieler/86936.
Transfer history data appended for: https://www.transfermarkt.com/karol-fila/profil/spieler/385817.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-zukowski/profil/spieler/470375.
Transfer history data appended for: https://www.transfermarkt.com/flavio-paixao/profil/spieler/123455.
Transfer history data appended for: https://www.transfermarkt.com/jaroslaw-kubicki/profil/spieler/327756.
Transfer history data appended for: https://www.transfermarkt.com/egzon-kryeziu/profil/spieler/469693.
Transfer history data appended for: https://www.transfermarkt.com/rafal-kobryn/profil/spieler/453900.
Transfer history data appended for: https://www.transfermarkt.com/zlatan-alomerovic/profil/spieler/47594.
Transfer history data appended for: https://www.transfermarkt.com/egy-maulana-vikri/profil/spieler/548371.
Transfer history data appended for: https://www.transfermarkt.com/jakub-arak/profil/spieler/241826.
Transfer history data appended for: https://www.transfermarkt.com/michal-nalepa/profil/spieler/175947.
Transfer history data appended for: https://www.transfermarkt.com/kenny-saief/profil/spieler/209019.
Transfer history data appended for: https://www.transfermarkt.com/jakub-kaluzinski/profil/spieler/699418.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-bartolewski/profil/spieler/425763.
Transfer history data appended for: https://www.transfermarkt.com/sasa-zivec/profil/spieler/128033.
Transfer history data appended for: https://www.transfermarkt.com/lorenco-simic/profil/spieler/226093.
Transfer history data appended for: https://www.transfermarkt.com/daniel-dudzinski/profil/spieler/554945.
Transfer history data appended for: https://www.transfermarkt.com/patryk-szysz/profil/spieler/421710.
Transfer history data appended for: https://www.transfermarkt.com/jakub-sypek/profil/spieler/504601.

Transfer history data appended for: https://www.transfermarkt.com/jakub-bednarczyk/profil/spieler/346328.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-bashkirov/profil/spieler/104200.
Transfer history data appended for: https://www.transfermarkt.com/kamil-bielikow/profil/spieler/401370.
Transfer history data appended for: https://www.transfermarkt.com/filip-starzynski/profil/spieler/199301.
Transfer history data appended for: https://www.transfermarkt.com/soren-reese/profil/spieler/143101.
Transfer history data appended for: https://www.transfermarkt.com/maciej-warpas/profil/spieler/498272.
Transfer history data appended for: https://www.transfermarkt.com/dominik-hladun/profil/spieler/278676.
Transfer history data appended for: https://www.transfermarkt.com/dejan-drazic/profil/spieler/291247.
Transfer history data appended for: https://www.transfermarkt.com/samuel-mraz/profil/spieler/243225.
Transfer history data appended for: https://www.transfermarkt.com/adam-ratajczyk/profil/spieler/628624.
Transfer history data appended for: https://www.transfermarkt.com/sasa-balic/profil/spieler/64104.
Transfer history data appended for: https://www.transfermarkt.com/damian-oko/profil/spieler/385198.
Transfer history data appended for: https://www.transfermarkt.com/dominik-kalinowski/profil/spieler/492352.
Transfer history data appended for: https://www.transfermarkt.com/dominik-jonczy/profil/spieler/385191.
Transfer history data appended for: https://www.transfermarkt.com/dawid-pakulski/profil/spieler/385199.
Transfer history data appended for: https://www.transfermarkt.com/jakub-wojcicki/profil/spieler/160367.
Transfer history data appended for: https://www.transfermarkt.com/jakub-zubrowski/profil/spieler/283012.
Transfer history data appended for: https://www.transfermarkt.com/lubomir-guldan/profil/spieler/50271.
Transfer history data appended for: https://www.transfermarkt.com/kamil-kruk/profil/spieler/372696.
Transfer history data appended for: https://www.transfermarkt.com/konrad-forenc/profil/spieler/121154.
Transfer history data appended for: https://www.transfermarkt.com/kacper-chodyna/profil/spieler/320733.
Transfer history data appended for: https://www.transfermarkt.com/rok-sirk/profil/spieler/308828.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-poreba/profil/spieler/532169.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-lis/profil/spieler/345437.
Transfer history data appended for: https://www.transfermarkt.com/vullnet-basha/profil/spieler/56324.
Transfer history data appended for: https://www.transfermarkt.com/jakub-blaszczykowski/profil/spieler/29835.
Transfer history data appended for: https://www.transfermarkt.com/stefan-savic/profil/spieler/120192.
Transfer history data appended for: https://www.transfermarkt.com/felicio-brown-forbes/profil/spieler/67064.
Transfer history data appended for: https://www.transfermarkt.com/michal-frydrych/profil/spieler/119862.
Transfer history data appended for: https://www.transfermarkt.com/patryk-plewka/profil/spieler/495237.
Transfer history data appended for: https://www.transfermarkt.com/dawid-szot/profil/spieler/545673.
Transfer history data appended for: https://www.transfermarkt.com/daniel-hoyo-kowalski/profil/spieler/553252.
Transfer history data appended for: https://www.transfermarkt.com/georgi-zhukov/profil/spieler/235755.
Transfer history data appended for: https://www.transfermarkt.com/michal-mak/profil/spieler/143976.
Transfer history data appended for: https://www.transfermarkt.com/david-niepsuj/profil/spieler/184849.
Transfer history data appended for: https://www.transfermarkt.com/lukas-klemenz/profil/spieler/237334.
Transfer history data appended for: https://www.transfermarkt.com/adi-mehremic/profil/spieler/192897.
Transfer history data appended for: https://www.transfermarkt.com/chuca/profil/spieler/399779.
Transfer history data appended for: https://www.transfermarkt.com/maciej-sadlok/profil/spieler/50751.
Transfer history data appended for: https://www.transfermarkt.com/kacper-duda/profil/spieler/555067.
Transfer history data appended for: https://www.transfermarkt.com/rafal-janicki/profil/spieler/153638.
Transfer history data appended for: https://www.transfermarkt.com/dawid-abramowicz/profil/spieler/168427.
Transfer history data appended for: https://www.transfermarkt.com/tafara-madembo/profil/spieler/700651.
Transfer history data appended for: https://www.transfermarkt.com/konrad-gruszkowski/profil/spieler/579448.
Transfer history data appended for: https://www.transfermarkt.com/michal-buchalik/profil/spieler/77002.
Transfer history data appended for: https://www.transfermarkt.com/yaw-yeboah/profil/spieler/358985.
Transfer history data appended for: https://www.transfermarkt.com/nikola-kuveljic/profil/spieler/612140.
Transfer history data appended for: https://www.transfermarkt.com/jean-carlos-silva/profil/spieler/282434.
Transfer history data appended for: https://www.transfermarkt.com/aleksander-buksa/profil/spieler/553757.
Transfer history data appended for: https://www.transfermarkt.com/fatos-beqiraj/profil/spieler/66784.
Transfer history data appended for: https://www.transfermarkt.com/kamil-broda/profil/spieler/531010.
Transfer history data appended for: https://www.transfermarkt.com/alan-czerwinski/profil/spieler/240756.
Transfer history data appended for: https://www.transfermarkt.com/tymoteusz-puchacz/profil/spieler/361575.
Transfer history data appended for: https://www.transfermarkt.com/jan-sykora/profil/spieler/187490.
Transfer history data appended for: https://www.transfermarkt.com/vasyl-kravets/profil/spieler/245048.
Transfer history data appended for: https://www.transfermarkt.com/tymoteusz-klups/profil/spieler/358873.
Transfer history data appended for: https://www.transfermarkt.com/mickey-van-der-hart/profil/spieler/207048.
Transfer history data appended for: https://www.transfermarkt.com/jakub-moder/profil/spieler/384461.
Transfer history data appended for: https://www.transfermarkt.com/filip-borowski/profil/spieler/672287.
Transfer history data appended for: https://www.transfermarkt.com/mikael-ishak/profil/spieler/153637.
Transfer history data appended for: https://www.transfermarkt.com/filip-wilak/profil/spieler/625634.
Transfer history data appended for: https://www.transfermarkt.com/djordje-crnomarkovic/profil/spieler/307325.
Transfer history data appended for: https://www.transfermarkt.com/michal-skoras/profil/spieler/393565.
Transfer history data appended for: https://www.transfermarkt.com/jakub-niewiadomski/profil/spieler/554970.
Transfer history data appended for: https://www.transfermarkt.com/nika-kacharava/profil/spieler/251028.
Transfer history data appended for: https://www.transfermarkt.com/krzysztof-bakowski/profil/spieler/554278.
Transfer history data appended for: https://www.transfermarkt.com/marko-malenica/profil/spieler/179894.
Transfer history data appended for: https://www.transfermarkt.com/pedro-tiba/profil/spieler/167165.
Transfer history data appended for: https://www.transfermarkt.com/mohammad-awwad/profil/spieler/460679.
Transfer history data appended for: https://www.transfermarkt.com/dani-ramirez/profil/spieler/246309.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-butko/profil/spieler/94922.
Transfer history data appended for: https://www.transfermarkt.com/thomas-rogne/profil/spieler/62086.
Transfer history data appended for: https://www.transfermarkt.com/filip-szymczak/profil/spieler/554972.
Transfer history data appended for: https://www.transfermarkt.com/tomasz-dejewski/profil/spieler/291343.
Transfer history data appended for: https://www.transfermarkt.com/filip-bednarek/profil/spieler/155158.
Transfer history data appended for: https://www.transfermarkt.com/lubomir-satka/profil/spieler/168408.
Transfer history data appended for: https://www.transfermarkt.com/filip-marchwinski/profil/spieler/555106.
Transfer history data appended for: https://www.transfermarkt.com/jakub-kaminski/profil/spieler/407098.
Transfer history data appended for: https://www.transfermarkt.com/karlo-muhar/profil/spieler/388042.
Transfer history data appended for: https://www.transfermarkt.com/jakub-wrabel/profil/spieler/273533.

Transfer history data appended for: https://www.transfermarkt.com/kacper-kondracki/profil/spieler/747654.
Transfer history data appended for: https://www.transfermarkt.com/cillian-sheridan/profil/spieler/14641.
Transfer history data appended for: https://www.transfermarkt.com/hubert-adamczyk/profil/spieler/287235.
Transfer history data appended for: https://www.transfermarkt.com/angel-garcia/profil/spieler/246278.
Transfer history data appended for: https://www.transfermarkt.com/rafal-wolski/profil/spieler/176514.
Transfer history data appended for: https://www.transfermarkt.com/krzysztof-kaminski/profil/spieler/172874.
Transfer history data appended for: https://www.transfermarkt.com/wojciech-szumilas/profil/spieler/315834.
Transfer history data appended for: https://www.transfermarkt.com/dawid-kocyla/profil/spieler/605780.
Transfer history data appended for: https://www.transfermarkt.com/adrian-szczutowski/profil/spieler/536293.
Transfer history data appended for: https://www.transfermarkt.com/airam-cabrera/profil/spieler/129149.
Transfer history data appended for: https://www.transfermarkt.com/aleksander-pawlak/profil/spieler/725654.
Transfer history data appended for: https://www.transfermarkt.com/patryk-tuszynski/profil/spieler/110856.
Transfer history data appended for: https://www.transfermarkt.com/damian-rasak/profil/spieler/255910.
Transfer history data appended for: https://www.transfermarkt.com/titas-milasius/profil/spieler/422803.
Transfer history data appended for: https://www.transfermarkt.com/dusan-lagator/profil/spieler/246831.
Transfer history data appended for: https://www.transfermarkt.com/bartlomiej-sielewski/profil/spieler/64463.
Transfer history data appended for: https://www.transfermarkt.com/bartlomiej-zynel/profil/spieler/289172.
Transfer history data appended for: https://www.transfermarkt.com/giorgi-merebashvili/profil/spieler/55978.
Transfer history data appended for: https://www.transfermarkt.com/pawel-zuk/profil/spieler/407733.
Transfer history data appended for: https://www.transfermarkt.com/jakub-rzezniczak/profil/spieler/24576.
Transfer history data appended for: https://www.transfermarkt.com/piotr-pyrdol/profil/spieler/385053.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-szwoch/profil/spieler/199302.
Transfer history data appended for: https://www.transfermarkt.com/julio-rodriguez/profil/spieler/238726.
Transfer history data appended for: https://www.transfermarkt.com/torgil-gjertsen/profil/spieler/261115.
Transfer history data appended for: https://www.transfermarkt.com/fryderyk-gerbowski/profil/spieler/554277.
Transfer history data appended for: https://www.transfermarkt.com/bartlomiej-gradecki/profil/spieler/520503.
Transfer history data appended for: https://www.transfermarkt.com/piotr-tomasik/profil/spieler/84918.
Transfer history data appended for: https://www.transfermarkt.com/filip-lesniak/profil/spieler/186383.
Transfer history data appended for: https://www.transfermarkt.com/alan-uryga/profil/spieler/187945.
Transfer history data appended for: https://www.transfermarkt.com/milan-obradovic/profil/spieler/528040.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-lewandowski/profil/spieler/438351.
Transfer history data appended for: https://www.transfermarkt.com/adrian-tokarski/profil/spieler/529539.
Transfer history data appended for: https://www.transfermarkt.com/damian-michalski/profil/spieler/385518.
Transfer history data appended for: https://www.transfermarkt.com/maciej-ambrosiewicz/profil/spieler/452447.
Transfer history data appended for: https://www.transfermarkt.com/patryk-janasik/profil/spieler/397854.
Transfer history data appended for: https://www.transfermarkt.com/bartlomiej-frasik/profil/spieler/528355.
Transfer history data appended for: https://www.transfermarkt.com/grzegorz-kotowicz/profil/spieler/403339.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-bergier/profil/spieler/384337.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-mackowiak/profil/spieler/407564.
Transfer history data appended for: https://www.transfermarkt.com/lubambo-musonda/profil/spieler/333859.
Transfer history data appended for: https://www.transfermarkt.com/waldemar-sobota/profil/spieler/110852.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-scalet/profil/spieler/384844.
Transfer history data appended for: https://www.transfermarkt.com/szymon-lewkot/profil/spieler/384789.
Transfer history data appended for: https://www.transfermarkt.com/erik-exposito/profil/spieler/483461.
Transfer history data appended for: https://www.transfermarkt.com/piotr-samiec-talar/profil/spieler/598448.
Transfer history data appended for: https://www.transfermarkt.com/adrian-lyszczarz/profil/spieler/384791.
Transfer history data appended for: https://www.transfermarkt.com/mariusz-pawelec/profil/spieler/29818.
Transfer history data appended for: https://www.transfermarkt.com/matus-putnocky/profil/spieler/74921.
Transfer history data appended for: https://www.transfermarkt.com/konrad-poprawa/profil/spieler/385052.
Transfer history data appended for: https://www.transfermarkt.com/piotr-celeban/profil/spieler/29509.
Transfer history data appended for: https://www.transfermarkt.com/fabian-piasecki/profil/spieler/255401.
Transfer history data appended for: https://www.transfermarkt.com/guillermo-cotugno/profil/spieler/311739.
Transfer history data appended for: https://www.transfermarkt.com/krzysztof-maczynski/profil/spieler/51337.
Transfer history data appended for: https://www.transfermarkt.com/maciej-palaszewski/profil/spieler/379868.
Transfer history data appended for: https://www.transfermarkt.com/przemyslaw-bargiel/profil/spieler/345460.
Transfer history data appended for: https://www.transfermarkt.com/marcel-zylla/profil/spieler/336330.
Transfer history data appended for: https://www.transfermarkt.com/michal-szromnik/profil/spieler/181135.
Transfer history data appended for: https://www.transfermarkt.com/dariusz-szczerbal/profil/spieler/450355.
Transfer history data appended for: https://www.transfermarkt.com/rafal-makowski/profil/spieler/300425.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-praszelik/profil/spieler/374418.
Transfer history data appended for: https://www.transfermarkt.com/diego-zivulic/profil/spieler/148545.
Transfer history data appended for: https://www.transfermarkt.com/mark-tamas/profil/spieler/260073.
Transfer history data appended for: https://www.transfermarkt.com/dino-stiglec/profil/spieler/100591.
Transfer history data appended for: https://www.transfermarkt.com/wojciech-golla/profil/spieler/161314.
Transfer history data appended for: https://www.transfermarkt.com/marcin-szpakowski/profil/spieler/605748.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-borun/profil/spieler/451198.
Transfer history data appended for: https://www.transfermarkt.com/israel-puerto/profil/spieler/126748.
Transfer history data appended for: https://www.transfermarkt.com/robert-pich/profil/spieler/109742.
Transfer history data appended for: https://www.transfermarkt.com/luis-mata/profil/spieler/258002.
Transfer history data appended for: https://www.transfermarkt.com/alexander-gorgon/profil/spieler/45425.
Transfer history data appended for: https://www.transfermarkt.com/david-stec/profil/spieler/181715.
Transfer history data appended for: https://www.transfermarkt.com/maciej-zurawski/profil/spieler/454388.
Transfer history data appended for: https://www.transfermarkt.com/hubert-matynia/profil/spieler/330686.
Transfer history data appended for: https://www.transfermarkt.com/igor-lasicki/profil/spieler/225874.
Transfer history data appended for: https://www.transfermarkt.com/mariusz-fornalczyk/profil/spieler/697468.
Transfer history data appended for: https://www.transfermarkt.com/konstantinos-triantafyllopoulos/profil/spieler/185691.
Transfer history data appended for: https://www.transfermarkt.com/damian-dabrowski/profil/spieler/143118.
Transfer history data appended for: https://www.transfermarkt.com/tomas-podstawski/profil/spieler/182718.
Transfer history data appended for: https://www.transfermarkt.com/michal-kucharczyk/profil/spieler/116905.

Transfer history data appended for: https://www.transfermarkt.com/mariusz-malec/profil/spieler/331871.
Transfer history data appended for: https://www.transfermarkt.com/marcel-mendes-dudzinski/profil/spieler/717910.
Transfer history data appended for: https://www.transfermarkt.com/kacper-smolinski/profil/spieler/597231.
Transfer history data appended for: https://www.transfermarkt.com/benedikt-zech/profil/spieler/83616.
Transfer history data appended for: https://www.transfermarkt.com/pawel-cibicki/profil/spieler/223849.
Transfer history data appended for: https://www.transfermarkt.com/filip-balcewicz/profil/spieler/554283.
Transfer history data appended for: https://www.transfermarkt.com/santeri-hostikka/profil/spieler/418762.
Transfer history data appended for: https://www.transfermarkt.com/marcel-wedrychowski/profil/spieler/554975.
Transfer history data appended for: https://www.transfermarkt.com/jakub-bartkowski/profil/spieler/130444.
Transfer history data appended for: https://www.transfermarkt.com/adrian-benedyczak/profil/spieler/454386.
Transfer history data appended for: https://www.transfermarkt.com/stanislaw-wawrzynowicz/profil/spieler/409048.
Transfer history data appended for: https://www.transfermarkt.com/dante-stipica/profil/spieler/86635.
Transfer history data appended for: https://www.transfermarkt.com/luka-zahovic/profil/spieler/169362.
Transfer history data appended for: https://www.transfermarkt.com/kacper-kozlowski/profil/spieler/554284.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-kowalczyk/profil/spieler/289168.
Transfer history data appended for: https://www.transfermarkt.com/dariusz-krzysztofek/profil/spieler/534948.
Transfer history data appended for: https://www.transfermarkt.com/hubert-turski/profil/spieler/569593.
Transfer history data appended for: https://www.transfermarkt.com/jakub-bursztyn/profil/spieler/384359.
Transfer history data appended for: https://www.transfermarkt.com/adam-fraczczak/profil/spieler/53721.
Transfer history data appended for: https://www.transfermarkt.com/bartlomiej-mruk/profil/spieler/631866.
Transfer history data appended for: https://www.transfermarkt.com/martin-konczkowski/profil/spieler/258799.
Transfer history data appended for: https://www.transfermarkt.com/kristopher-vida/profil/spieler/164837.
Transfer history data appended for: https://www.transfermarkt.com/tomasz-jodlowiec/profil/spieler/27261.
Transfer history data appended for: https://www.transfermarkt.com/michal-rakowiecki/profil/spieler/535769.
Transfer history data appended for: https://www.transfermarkt.com/tiago-alves/profil/spieler/451857.
Transfer history data appended for: https://www.transfermarkt.com/arkadiusz-pyrka/profil/spieler/599733.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-kirkeskov/profil/spieler/96331.
Transfer history data appended for: https://www.transfermarkt.com/jakub-szmatula/profil/spieler/29537.
Transfer history data appended for: https://www.transfermarkt.com/patryk-krolczyk/profil/spieler/210184.
Transfer history data appended for: https://www.transfermarkt.com/michal-zyro/profil/spieler/67431.
Transfer history data appended for: https://www.transfermarkt.com/jakub-holubek/profil/spieler/192731.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-milewski/profil/spieler/374562.
Transfer history data appended for: https://www.transfermarkt.com/javier-hyjek/profil/spieler/536846.
Transfer history data appended for: https://www.transfermarkt.com/tomas-huk/profil/spieler/181612.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-rymaniak/profil/spieler/81257.
Transfer history data appended for: https://www.transfermarkt.com/jakub-czerwinski/profil/spieler/143282.
Transfer history data appended for: https://www.transfermarkt.com/patryk-lipski/profil/spieler/255392.
Transfer history data appended for: https://www.transfermarkt.com/jakub-swierczok/profil/spieler/193554.
Transfer history data appended for: https://www.transfermarkt.com/dominik-steczyk/profil/spieler/344415.
Transfer history data appended for: https://www.transfermarkt.com/tomasz-mokwa/profil/spieler/266250.
Transfer history data appended for: https://www.transfermarkt.com/frantisek-plach/profil/spieler/404345.
Transfer history data appended for: https://www.transfermarkt.com/remigiusz-borkala/profil/spieler/470054.
Transfer history data appended for: https://www.transfermarkt.com/piotr-malarczyk/profil/spieler/120892.
Transfer history data appended for: https://www.transfermarkt.com/karol-szymanski/profil/spieler/266269.
Transfer history data appended for: https://www.transfermarkt.com/gerard-badia/profil/spieler/95430.
Transfer history data appended for: https://www.transfermarkt.com/patryk-sokolowski/profil/spieler/284871.
Transfer history data appended for: https://www.transfermarkt.com/karol-stanek/profil/spieler/452672.
Transfer history data appended for: https://www.transfermarkt.com/michal-chrapek/profil/spieler/117683.
Transfer history data appended for: https://www.transfermarkt.com/martin-chudy/profil/spieler/80732.
Transfer history data appended for: https://www.transfermarkt.com/roman-prochazka/profil/spieler/80690.
Transfer history data appended for: https://www.transfermarkt.com/kamil-surowiec/profil/spieler/505728.
Transfer history data appended for: https://www.transfermarkt.com/adam-ryczkowski/profil/spieler/264297.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-nowak/profil/spieler/261085.
Transfer history data appended for: https://www.transfermarkt.com/przemyslaw-wisniewski/profil/spieler/386967.
Transfer history data appended for: https://www.transfermarkt.com/alasana-manneh/profil/spieler/435807.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-neugebauer/profil/spieler/585073.
Transfer history data appended for: https://www.transfermarkt.com/michal-rostkowski/profil/spieler/560940.
Transfer history data appended for: https://www.transfermarkt.com/wojciech-hajda/profil/spieler/372695.
Transfer history data appended for: https://www.transfermarkt.com/karol-jaksik/profil/spieler/454273.
Transfer history data appended for: https://www.transfermarkt.com/daniel-scislak/profil/spieler/479708.
Transfer history data appended for: https://www.transfermarkt.com/krzysztof-kubica/profil/spieler/573968.
Transfer history data appended for: https://www.transfermarkt.com/stefanos-evangelou/profil/spieler/342255.
Transfer history data appended for: https://www.transfermarkt.com/michal-koj/profil/spieler/185679.
Transfer history data appended for: https://www.transfermarkt.com/erik-janza/profil/spieler/174522.
Transfer history data appended for: https://www.transfermarkt.com/adrian-gryszkiewicz/profil/spieler/388944.
Transfer history data appended for: https://www.transfermarkt.com/jesus-jimenez/profil/spieler/510545.
Transfer history data appended for: https://www.transfermarkt.com/aleksander-paluszek/profil/spieler/605746.
Transfer history data appended for: https://www.transfermarkt.com/dawid-kudla/profil/spieler/266239.
Transfer history data appended for: https://www.transfermarkt.com/piotr-krawczyk/profil/spieler/294191.
Transfer history data appended for: https://www.transfermarkt.com/kacper-michalski/profil/spieler/466224.
Transfer history data appended for: https://www.transfermarkt.com/filip-bainovic/profil/spieler/358909.
Transfer history data appended for: https://www.transfermarkt.com/giannis-masouras/profil/spieler/295780.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-wolsztynski/profil/spieler/356515.
Transfer history data appended for: https://www.transfermarkt.com/alex-sobczyk/profil/spieler/287191.
Transfer history data appended for: https://www.transfermarkt.com/norbert-wojtuszek/profil/spieler/607435.
Transfer history data appended for: https://www.transfermarkt.com/dariusz-pawlowski/profil/spieler/386956.
Transfer history data appended for: https://www.transfermarkt.com/martin-polacek/profil/spieler/90954.
Transfer history data appended for: https://www.transfermarkt.com/patryk-drabik/profil/spieler/527418.
Transfer history data appended for: https://www.transfermarkt.com/filip-modelski/profil/spieler/79190.

Transfer history data appended for: https://www.transfermarkt.com/kacper-gach/profil/spieler/514939.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-bashlay/profil/spieler/92030.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-sierpina/profil/spieler/119941.
Transfer history data appended for: https://www.transfermarkt.com/marko-roginic/profil/spieler/317504.
Transfer history data appended for: https://www.transfermarkt.com/dominik-frelek/profil/spieler/608932.
Transfer history data appended for: https://www.transfermarkt.com/rafal-leszczynski/profil/spieler/120970.
Transfer history data appended for: https://www.transfermarkt.com/arkadiusz-leszczynski/profil/spieler/401898.
Transfer history data appended for: https://www.transfermarkt.com/jakub-bieronski/profil/spieler/617431.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-myakushko/profil/spieler/193158.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-jaroch/profil/spieler/261874.
Transfer history data appended for: https://www.transfermarkt.com/szymon-mroczko/profil/spieler/614406.
Transfer history data appended for: https://www.transfermarkt.com/maksymilian-sitek/profil/spieler/532428.
Transfer history data appended for: https://www.transfermarkt.com/michal-rzuchowski/profil/spieler/237356.
Transfer history data appended for: https://www.transfermarkt.com/konrad-gutowski/profil/spieler/450044.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-marzec/profil/spieler/331278.
Transfer history data appended for: https://www.transfermarkt.com/tomasz-nowak/profil/spieler/46840.
Transfer history data appended for: https://www.transfermarkt.com/desley-ubbink/profil/spieler/272718.
Transfer history data appended for: https://www.transfermarkt.com/michal-batelt/profil/spieler/782962.
Transfer history data appended for: https://www.transfermarkt.com/konrad-sieracki/profil/spieler/527423.
Transfer history data appended for: https://www.transfermarkt.com/gerg%C5%91-kocsis/profil/spieler/179641.
Transfer history data appended for: https://www.transfermarkt.com/michal-peskovic/profil/spieler/57581.
Transfer history data appended for: https://www.transfermarkt.com/rafal-figiel/profil/spieler/118594.
Transfer history data appended for: https://www.transfermarkt.com/kamil-bilinski/profil/spieler/95197.
Transfer history data appended for: https://www.transfermarkt.com/ivan-martin/profil/spieler/339752.
Transfer history data appended for: https://www.transfermarkt.com/michal-studnicki/profil/spieler/709675.
Transfer history data appended for: https://www.transfermarkt.com/kornel-osyra/profil/spieler/148266.
Transfer history data appended for: https://www.transfermarkt.com/milan-rundic/profil/spieler/182185.
Transfer history data appended for: https://www.transfermarkt.com/karol-danielak/profil/spieler/178222.
Transfer history data appended for: https://www.transfermarkt.com/filip-laskowski/profil/spieler/597621.
Transfer history data appended for: https://www.transfermarkt.com/pawel-tomczyk/profil/spieler/388953.
Transfer history data appended for: https://www.transfermarkt.com/adam-kramarz/profil/spieler/600169.
Transfer history data appended for: https://www.transfermarkt.com/rafal-straczek/profil/spieler/447343.
Transfer history data appended for: https://www.transfermarkt.com/andreja-proki%C4%87/profil/spieler/188993.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-dudek/profil/spieler/687439.
Transfer history data appended for: https://www.transfermarkt.com/wojciech-lisowski/profil/spieler/182953.
Transfer history data appended for: https://www.transfermarkt.com/kamil-koscielny/profil/spieler/281332.
Transfer history data appended for: https://www.transfermarkt.com/michal-gliwa/profil/spieler/42056.
Transfer history data appended for: https://www.transfermarkt.com/robert-dadok/profil/spieler/351796.
Transfer history data appended for: https://www.transfermarkt.com/jakub-wrobel/profil/spieler/253154.
Transfer history data appended for: https://www.transfermarkt.com/adrian-skrzyniak/profil/spieler/748292.
Transfer history data appended for: https://www.transfermarkt.com/petteri-forsell/profil/spieler/73908.
Transfer history data appended for: https://www.transfermarkt.com/damian-pawlowski/profil/spieler/320741.
Transfer history data appended for: https://www.transfermarkt.com/martin-sus/profil/spieler/81981.
Transfer history data appended for: https://www.transfermarkt.com/grzegorz-tomasiewicz/profil/spieler/240458.
Transfer history data appended for: https://www.transfermarkt.com/krystian-getinger/profil/spieler/69516.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-zyro/profil/spieler/297234.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-seweryn/profil/spieler/555573.
Transfer history data appended for: https://www.transfermarkt.com/kacper-sadlocha/profil/spieler/554977.
Transfer history data appended for: https://www.transfermarkt.com/damian-primel/profil/spieler/133124.
Transfer history data appended for: https://www.transfermarkt.com/wojciech-blyszko/profil/spieler/454377.
Transfer history data appended for: https://www.transfermarkt.com/lukasz-zjawinski/profil/spieler/401608.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-bajorek/profil/spieler/655590.
Transfer history data appended for: https://www.transfermarkt.com/maciej-urbanczyk/profil/spieler/255423.
Transfer history data appended for: https://www.transfermarkt.com/maciej-domanski/profil/spieler/281376.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-mak/profil/spieler/143975.
Transfer history data appended for: https://www.transfermarkt.com/szymon-stasik/profil/spieler/385485.
Transfer history data appended for: https://www.transfermarkt.com/marcin-flis/profil/spieler/187973.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-wdowiak/profil/spieler/295495.
Transfer history data appended for: https://www.transfermarkt.com/sylwester-lusiusz/profil/spieler/426297.
Transfer history data appended for: https://www.transfermarkt.com/vinicius-ferreira/profil/spieler/612490.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-supryn/profil/spieler/453410.
Transfer history data appended for: https://www.transfermarkt.com/michal-siplak/profil/spieler/239957.
Transfer history data appended for: https://www.transfermarkt.com/oleksiy-dytyatyev/profil/spieler/242279.
Transfer history data appended for: https://www.transfermarkt.com/florian-loshaj/profil/spieler/242040.
Transfer history data appended for: https://www.transfermarkt.com/bojan-cecaric/profil/spieler/239069.
Transfer history data appended for: https://www.transfermarkt.com/dorian-pitula/profil/spieler/496699.
Transfer history data appended for: https://www.transfermarkt.com/daniel-pik/profil/spieler/528410.
Transfer history data appended for: https://www.transfermarkt.com/adam-wilk/profil/spieler/356755.
Transfer history data appended for: https://www.transfermarkt.com/filip-majchrowicz/profil/spieler/528402.
Transfer history data appended for: https://www.transfermarkt.com/michal-wisniewski/profil/spieler/528325.
Transfer history data appended for: https://www.transfermarkt.com/david-jablonsky/profil/spieler/113575.
Transfer history data appended for: https://www.transfermarkt.com/dawid-szymonowicz/profil/spieler/242846.
Transfer history data appended for: https://www.transfermarkt.com/ivan-fiolic/profil/spieler/226070.
Transfer history data appended for: https://www.transfermarkt.com/karol-niemczycki/profil/spieler/521634.
Transfer history data appended for: https://www.transfermarkt.com/ivan-marquez/profil/spieler/296227.
Transfer history data appended for: https://www.transfermarkt.com/matej-rodin/profil/spieler/316445.
Transfer history data appended for: https://www.transfermarkt.com/diego-ferraresso/profil/spieler/120104.
Transfer history data appended for: https://www.transfermarkt.com/damir-sadikovic/profil/spieler/255972.
Transfer history data appended for: https://www.transfermarkt.com/marcos-alvarez/profil/spieler/47944.

Transfer history data appended for: https://www.transfermarkt.com/sebastian-strozik/profil/spieler/384438.
Transfer history data appended for: https://www.transfermarkt.com/matheus-santos/profil/spieler/612491.
Transfer history data appended for: https://www.transfermarkt.com/thiago/profil/spieler/687844.
Transfer history data appended for: https://www.transfermarkt.com/kamil-pestka/profil/spieler/384482.
Transfer history data appended for: https://www.transfermarkt.com/cornel-rapa/profil/spieler/96290.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-pienczak/profil/spieler/650292.
Transfer history data appended for: https://www.transfermarkt.com/filip-piszczek/profil/spieler/325215.
Transfer history data appended for: https://www.transfermarkt.com/jakub-gut/profil/spieler/727114.
Transfer history data appended for: https://www.transfermarkt.com/pelle-van-amersfoort/profil/spieler/262613.
Transfer history data appended for: https://www.transfermarkt.com/sergiu-hanca/profil/spieler/212806.
Transfer history data appended for: https://www.transfermarkt.com/milan-dimun/profil/spieler/291232.
Transfer history data appended for: https://www.transfermarkt.com/rivaldinho/profil/spieler/313968.
Transfer history data appended for: https://www.transfermarkt.com/przemyslaw-kapek/profil/spieler/697556.
Transfer history data appended for: https://www.transfermarkt.com/tomasz-bala/profil/spieler/579770.
Transfer history data appended for: https://www.transfermarkt.com/patryk-zaucha/profil/spieler/393568.
Transfer history data appended for: https://www.transfermarkt.com/lukas-hrosso/profil/spieler/74941.
Transfer history data appended for: https://www.transfermarkt.com/michael-gardawski/profil/spieler/52791.
Transfer history data appended for: https://www.transfermarkt.com/radoslaw-kanach/profil/spieler/396690.
Transfer history data appended for: https://www.transfermarkt.com/pawel-olszewski/profil/spieler/342659.
Transfer history data appended for: https://www.transfermarkt.com/mateusz-wyjadlowski/profil/spieler/453141.
Transfer history data appended for: https://www.transfermarkt.com/fernan-lopez/profil/spieler/287194.
Transfer history data appended for: https://www.transfermarkt.com/oliwier-wojciechowski/profil/spieler/618392.
Transfer history data appended for: https://www.transfermarkt.com/maciej-bortniczuk/profil/spieler/587156.
Transfer history data appended for: https://www.transfermarkt.com/taras-romanczuk/profil/spieler/280939.
Transfer history data appended for: https://www.transfermarkt.com/ivan-runje/profil/spieler/109012.
Transfer history data appended for: https://www.transfermarkt.com/fedor-chernykh/profil/spieler/140540.
Transfer history data appended for: https://www.transfermarkt.com/jakov-puljic/profil/spieler/217751.
Transfer history data appended for: https://www.transfermarkt.com/tomas-prikryl/profil/spieler/152693.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-tiru/profil/spieler/186744.
Transfer history data appended for: https://www.transfermarkt.com/xavier-dziekonski/profil/spieler/699400.
Transfer history data appended for: https://www.transfermarkt.com/krzysztof-toporkiewicz/profil/spieler/628556.
Transfer history data appended for: https://www.transfermarkt.com/bodvar-bodvarsson/profil/spieler/273173.
Transfer history data appended for: https://www.transfermarkt.com/hubert-gostomski/profil/spieler/364049.
Transfer history data appended for: https://www.transfermarkt.com/damian-weglarz/profil/spieler/281791.
Transfer history data appended for: https://www.transfermarkt.com/jan-majsterek/profil/spieler/597614.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-bida/profil/spieler/475802.
Transfer history data appended for: https://www.transfermarkt.com/kris-twardek/profil/spieler/293372.
Transfer history data appended for: https://www.transfermarkt.com/szymon-sobczak/profil/spieler/164489.
Transfer history data appended for: https://www.transfermarkt.com/pavels-steinbors/profil/spieler/42891.
Transfer history data appended for: https://www.transfermarkt.com/maciej-makuszewski/profil/spieler/153033.
Transfer history data appended for: https://www.transfermarkt.com/martin-pospisil/profil/spieler/180538.
Transfer history data appended for: https://www.transfermarkt.com/przemyslaw-mystkowski/profil/spieler/287319.
Transfer history data appended for: https://www.transfermarkt.com/jesus-imaz/profil/spieler/176423.
Transfer history data appended for: https://www.transfermarkt.com/bartlomiej-wdowik/profil/spieler/589013.
Transfer history data appended for: https://www.transfermarkt.com/kamil-wojtkowski/profil/spieler/293063.
Transfer history data appended for: https://www.transfermarkt.com/andrej-kadlec/profil/spieler/260842.
Transfer history data appended for: https://www.transfermarkt.com/rafik-guitane/profil/spieler/394328.
Transfer history data appended for: https://www.transfermarkt.com/rene/profil/spieler/154990.
Transfer history data appended for: https://www.transfermarkt.com/claudio-winck/profil/spieler/181783.
Transfer history data appended for: https://www.transfermarkt.com/franck-bambock/profil/spieler/182882.
Transfer history data appended for: https://www.transfermarkt.com/faiq-bolkiah/profil/spieler/331725.
Transfer history data appended for: https://www.transfermarkt.com/caio-secco/profil/spieler/175188.
Transfer history data appended for: https://www.transfermarkt.com/dejan-kerkez/profil/spieler/393846.
Transfer history data appended for: https://www.transfermarkt.com/charles/profil/spieler/181773.
Transfer history data appended for: https://www.transfermarkt.com/fabio-china/profil/spieler/435497.
Transfer history data appended for: https://www.transfermarkt.com/lucas-africo/profil/spieler/597087.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-pinho/profil/spieler/366278.
Transfer history data appended for: https://www.transfermarkt.com/joel-tagueu/profil/spieler/184928.
Transfer history data appended for: https://www.transfermarkt.com/francois-xavier-fumu-tamuzo/profil/spieler/324891.
Transfer history data appended for: https://www.transfermarkt.com/amir-abedzadeh/profil/spieler/218431.
Transfer history data appended for: https://www.transfermarkt.com/jorge-correa/profil/spieler/96140.
Transfer history data appended for: https://www.transfermarkt.com/edgar-costa/profil/spieler/126956.
Transfer history data appended for: https://www.transfermarkt.com/ruben-macedo/profil/spieler/225119.
Transfer history data appended for: https://www.transfermarkt.com/jefferson/profil/spieler/696655.
Transfer history data appended for: https://www.transfermarkt.com/diego-moreno/profil/spieler/312731.
Transfer history data appended for: https://www.transfermarkt.com/zainadine-junior/profil/spieler/137192.
Transfer history data appended for: https://www.transfermarkt.com/pedro-pelagio/profil/spieler/606050.
Transfer history data appended for: https://www.transfermarkt.com/marcelinho/profil/spieler/439782.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-hermes/profil/spieler/348769.
Transfer history data appended for: https://www.transfermarkt.com/ali-alipour/profil/spieler/249360.
Transfer history data appended for: https://www.transfermarkt.com/jean-cleber/profil/spieler/187697.
Transfer history data appended for: https://www.transfermarkt.com/caue/profil/spieler/76090.
Transfer history data appended for: https://www.transfermarkt.com/goncalo-silva/profil/spieler/194214.
Transfer history data appended for: https://www.transfermarkt.com/francisco-varela/profil/spieler/212867.
Transfer history data appended for: https://www.transfermarkt.com/silvestre-varela/profil/spieler/31316.
Transfer history data appended for: https://www.transfermarkt.com/ruben-lima/profil/spieler/58965.
Transfer history data appended for: https://www.transfermarkt.com/diogo-calila/profil/spieler/396429.
Transfer history data appended for: https://www.transfermarkt.com/joao-monteiro/profil/spieler/426212.
Transfer history data appended for: https://www.transfermarkt.com/richard-alexandre/profil/spieler/574949.
Transfer history data appended for: https://www.transfermarkt.com/andre-moreira/profil/spieler/326363.

Transfer history data appended for: https://www.transfermarkt.com/tomas-ribeiro/profil/spieler/433358.
Transfer history data appended for: https://www.transfermarkt.com/eduardo-kau/profil/spieler/683557.
Transfer history data appended for: https://www.transfermarkt.com/tiago-esgaio/profil/spieler/581121.
Transfer history data appended for: https://www.transfermarkt.com/thibang-phete/profil/spieler/388581.
Transfer history data appended for: https://www.transfermarkt.com/alhassane-keita/profil/spieler/197734.
Transfer history data appended for: https://www.transfermarkt.com/edi-semedo/profil/spieler/504107.
Transfer history data appended for: https://www.transfermarkt.com/miguel-cardoso/profil/spieler/348425.
Transfer history data appended for: https://www.transfermarkt.com/mateo-cassierra/profil/spieler/362667.
Transfer history data appended for: https://www.transfermarkt.com/afonso-sousa/profil/spieler/375378.
Transfer history data appended for: https://www.transfermarkt.com/robinho/profil/spieler/591353.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-kritsyuk/profil/spieler/98547.
Transfer history data appended for: https://www.transfermarkt.com/chima-akas/profil/spieler/407577.
Transfer history data appended for: https://www.transfermarkt.com/tomas-castro/profil/spieler/681831.
Transfer history data appended for: https://www.transfermarkt.com/dieguinho/profil/spieler/179043.
Transfer history data appended for: https://www.transfermarkt.com/bruno-ramires/profil/spieler/348267.
Transfer history data appended for: https://www.transfermarkt.com/pedro-alvaro/profil/spieler/375376.
Transfer history data appended for: https://www.transfermarkt.com/nilton-varela/profil/spieler/681829.
Transfer history data appended for: https://www.transfermarkt.com/danny-henriques/profil/spieler/411502.
Transfer history data appended for: https://www.transfermarkt.com/afonso-taira/profil/spieler/118317.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-viera/profil/spieler/492316.
Transfer history data appended for: https://www.transfermarkt.com/joao-afonso/profil/spieler/211107.
Transfer history data appended for: https://www.transfermarkt.com/mikel-villanueva/profil/spieler/308371.
Transfer history data appended for: https://www.transfermarkt.com/thiago/profil/spieler/376175.
Transfer history data appended for: https://www.transfermarkt.com/lucas-marques/profil/spieler/375025.
Transfer history data appended for: https://www.transfermarkt.com/julio-romao/profil/spieler/645423.
Transfer history data appended for: https://www.transfermarkt.com/andre-mesquita/profil/spieler/303599.
Transfer history data appended for: https://www.transfermarkt.com/carlos-jr-/profil/spieler/284000.
Transfer history data appended for: https://www.transfermarkt.com/costinha/profil/spieler/236886.
Transfer history data appended for: https://www.transfermarkt.com/pierre-sagna/profil/spieler/127031.
Transfer history data appended for: https://www.transfermarkt.com/rodolfo-cardoso/profil/spieler/427107.
Transfer history data appended for: https://www.transfermarkt.com/shahriar-moghanlou/profil/spieler/357125.
Transfer history data appended for: https://www.transfermarkt.com/nene/profil/spieler/301824.
Transfer history data appended for: https://www.transfermarkt.com/mansur/profil/spieler/211345.
Transfer history data appended for: https://www.transfermarkt.com/andre-ferreira/profil/spieler/290346.
Transfer history data appended for: https://www.transfermarkt.com/ukra/profil/spieler/55994.
Transfer history data appended for: https://www.transfermarkt.com/osama-rashid/profil/spieler/95429.
Transfer history data appended for: https://www.transfermarkt.com/fabio-cardoso/profil/spieler/155025.
Transfer history data appended for: https://www.transfermarkt.com/cryzan/profil/spieler/373300.
Transfer history data appended for: https://www.transfermarkt.com/jean-patric/profil/spieler/537296.
Transfer history data appended for: https://www.transfermarkt.com/cristian-gonzalez/profil/spieler/358738.
Transfer history data appended for: https://www.transfermarkt.com/rafael-ramos/profil/spieler/290388.
Transfer history data appended for: https://www.transfermarkt.com/joao-lucas/profil/spieler/347905.
Transfer history data appended for: https://www.transfermarkt.com/marco-pereira/profil/spieler/74689.
Transfer history data appended for: https://www.transfermarkt.com/jaume-grau/profil/spieler/340864.
Transfer history data appended for: https://www.transfermarkt.com/ruben-fonseca/profil/spieler/648027.
Transfer history data appended for: https://www.transfermarkt.com/pedro-augusto/profil/spieler/594105.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-alves/profil/spieler/118323.
Transfer history data appended for: https://www.transfermarkt.com/jota-goncalves/profil/spieler/690924.
Transfer history data appended for: https://www.transfermarkt.com/bebeto/profil/spieler/124548.
Transfer history data appended for: https://www.transfermarkt.com/pedro-trigueira/profil/spieler/91949.
Transfer history data appended for: https://www.transfermarkt.com/enzo-martinez/profil/spieler/578737.
Transfer history data appended for: https://www.transfermarkt.com/joel-sousa/profil/spieler/514218.
Transfer history data appended for: https://www.transfermarkt.com/filipe-ferreira/profil/spieler/182936.
Transfer history data appended for: https://www.transfermarkt.com/joao-jaquite/profil/spieler/380409.
Transfer history data appended for: https://www.transfermarkt.com/joao-mendes/profil/spieler/504503.
Transfer history data appended for: https://www.transfermarkt.com/salvador-agra/profil/spieler/155395.
Transfer history data appended for: https://www.transfermarkt.com/tomislav-strkalj/profil/spieler/240262.
Transfer history data appended for: https://www.transfermarkt.com/rafael-barbosa/profil/spieler/225151.
Transfer history data appended for: https://www.transfermarkt.com/mario-gonzalez/profil/spieler/255995.
Transfer history data appended for: https://www.transfermarkt.com/tiago-almeida/profil/spieler/782612.
Transfer history data appended for: https://www.transfermarkt.com/abdel-medioub/profil/spieler/596901.
Transfer history data appended for: https://www.transfermarkt.com/babacar-niasse/profil/spieler/176573.
Transfer history data appended for: https://www.transfermarkt.com/naoufel-khacef/profil/spieler/462738.
Transfer history data appended for: https://www.transfermarkt.com/souleymane-anne/profil/spieler/562601.
Transfer history data appended for: https://www.transfermarkt.com/telmo-arcanjo/profil/spieler/791528.
Transfer history data appended for: https://www.transfermarkt.com/yohan-tavares/profil/spieler/85953.
Transfer history data appended for: https://www.transfermarkt.com/joao-pedro/profil/spieler/235568.
Transfer history data appended for: https://www.transfermarkt.com/cesar-martins/profil/spieler/269467.
Transfer history data appended for: https://www.transfermarkt.com/pedro-henrique/profil/spieler/531916.
Transfer history data appended for: https://www.transfermarkt.com/miguel-bandarra/profil/spieler/647129.
Transfer history data appended for: https://www.transfermarkt.com/abner/profil/spieler/273455.
Transfer history data appended for: https://www.transfermarkt.com/ryan-gauld/profil/spieler/193081.
Transfer history data appended for: https://www.transfermarkt.com/fabricio-isidoro/profil/spieler/512127.
Transfer history data appended for: https://www.transfermarkt.com/hugo-seco/profil/spieler/295169.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-ferreira/profil/spieler/151205.
Transfer history data appended for: https://www.transfermarkt.com/claudio-falcao/profil/spieler/437566.
Transfer history data appended for: https://www.transfermarkt.com/alex-pinto/profil/spieler/415645.
Transfer history data appended for: https://www.transfermarkt.com/filipe-melo/profil/spieler/134580.
Transfer history data appended for: https://www.transfermarkt.com/fabio-nunes/profil/spieler/138350.
Transfer history data appended for: https://www.transfermarkt.com/madi-queta/profil/spieler/314970.
Transfer history data appended for: https://www.transfermarkt.com/jonatan-lucca/profil/spieler/232577.

Transfer history data appended for: https://www.transfermarkt.com/brian-mansilla/profil/spieler/373374.
Transfer history data appended for: https://www.transfermarkt.com/hugo-marques/profil/spieler/72776.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-velho/profil/spieler/527026.
Transfer history data appended for: https://www.transfermarkt.com/rafael-defendi/profil/spieler/59823.
Transfer history data appended for: https://www.transfermarkt.com/lica/profil/spieler/51058.
Transfer history data appended for: https://www.transfermarkt.com/bilel-aouacheria/profil/spieler/290530.
Transfer history data appended for: https://www.transfermarkt.com/cassio-scheid/profil/spieler/510635.
Transfer history data appended for: https://www.transfermarkt.com/patrick/profil/spieler/552534.
Transfer history data appended for: https://www.transfermarkt.com/alvarinho/profil/spieler/176906.
Transfer history data appended for: https://www.transfermarkt.com/bura/profil/spieler/595008.
Transfer history data appended for: https://www.transfermarkt.com/amine-oudrhiri/profil/spieler/306668.
Transfer history data appended for: https://www.transfermarkt.com/jorge-fellipe/profil/spieler/132060.
Transfer history data appended for: https://www.transfermarkt.com/eduardo-mancha/profil/spieler/578685.
Transfer history data appended for: https://www.transfermarkt.com/ivo-pinto/profil/spieler/82281.
Transfer history data appended for: https://www.transfermarkt.com/nikola-jambor/profil/spieler/335062.
Transfer history data appended for: https://www.transfermarkt.com/bruno-moreira/profil/spieler/56183.
Transfer history data appended for: https://www.transfermarkt.com/gelson-dala/profil/spieler/407907.
Transfer history data appended for: https://www.transfermarkt.com/diego-lopes/profil/spieler/131933.
Transfer history data appended for: https://www.transfermarkt.com/fabio-coentrao/profil/spieler/33648.
Transfer history data appended for: https://www.transfermarkt.com/nando-pijnaker/profil/spieler/455425.
Transfer history data appended for: https://www.transfermarkt.com/matheus-reis/profil/spieler/379249.
Transfer history data appended for: https://www.transfermarkt.com/nelson-monte/profil/spieler/332615.
Transfer history data appended for: https://www.transfermarkt.com/pedro-amaral/profil/spieler/319623.
Transfer history data appended for: https://www.transfermarkt.com/pele/profil/spieler/99189.
Transfer history data appended for: https://www.transfermarkt.com/said-ahmed-said/profil/spieler/45529.
Transfer history data appended for: https://www.transfermarkt.com/andre-pereira/profil/spieler/358177.
Transfer history data appended for: https://www.transfermarkt.com/filipe-augusto/profil/spieler/212899.
Transfer history data appended for: https://www.transfermarkt.com/tarantini/profil/spieler/34077.
Transfer history data appended for: https://www.transfermarkt.com/toni-borevkovic/profil/spieler/396342.
Transfer history data appended for: https://www.transfermarkt.com/junio/profil/spieler/520469.
Transfer history data appended for: https://www.transfermarkt.com/leo-vieira/profil/spieler/67144.
Transfer history data appended for: https://www.transfermarkt.com/ryotaro-meshino/profil/spieler/426666.
Transfer history data appended for: https://www.transfermarkt.com/ronan/profil/spieler/333166.
Transfer history data appended for: https://www.transfermarkt.com/gabrielzinho/profil/spieler/523850.
Transfer history data appended for: https://www.transfermarkt.com/safawi-rasid/profil/spieler/474220.
Transfer history data appended for: https://www.transfermarkt.com/romulo/profil/spieler/520462.
Transfer history data appended for: https://www.transfermarkt.com/lucas-tagliapietra/profil/spieler/189047.
Transfer history data appended for: https://www.transfermarkt.com/fernando-medeiros/profil/spieler/411661.
Transfer history data appended for: https://www.transfermarkt.com/lucas-possignolo/profil/spieler/312123.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-vaz-te/profil/spieler/9413.
Transfer history data appended for: https://www.transfermarkt.com/fali-cande/profil/spieler/520530.
Transfer history data appended for: https://www.transfermarkt.com/willyan-rocha/profil/spieler/518472.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-ferreira/profil/spieler/59508.
Transfer history data appended for: https://www.transfermarkt.com/anderson-oliveira/profil/spieler/594550.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-antonio/profil/spieler/340557.
Transfer history data appended for: https://www.transfermarkt.com/welinton-junior/profil/spieler/262002.
Transfer history data appended for: https://www.transfermarkt.com/fabricio/profil/spieler/173617.
Transfer history data appended for: https://www.transfermarkt.com/anatole-abang/profil/spieler/363264.
Transfer history data appended for: https://www.transfermarkt.com/luquinhas/profil/spieler/651205.
Transfer history data appended for: https://www.transfermarkt.com/koki-anzai/profil/spieler/310822.
Transfer history data appended for: https://www.transfermarkt.com/pedro-sa/profil/spieler/299400.
Transfer history data appended for: https://www.transfermarkt.com/dener/profil/spieler/190543.
Transfer history data appended for: https://www.transfermarkt.com/samuel/profil/spieler/284701.
Transfer history data appended for: https://www.transfermarkt.com/henrique/profil/spieler/375820.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-hackman/profil/spieler/375039.
Transfer history data appended for: https://www.transfermarkt.com/lucas-fernandes/profil/spieler/430761.
Transfer history data appended for: https://www.transfermarkt.com/aylton-boa-morte/profil/spieler/352811.
Transfer history data appended for: https://www.transfermarkt.com/julio-cesar/profil/spieler/249062.
Transfer history data appended for: https://www.transfermarkt.com/fahd-moufi/profil/spieler/265589.
Transfer history data appended for: https://www.transfermarkt.com/jafar-salmani/profil/spieler/564700.
Transfer history data appended for: https://www.transfermarkt.com/beto/profil/spieler/595809.
Transfer history data appended for: https://www.transfermarkt.com/shuichi-gonda/profil/spieler/79517.
Transfer history data appended for: https://www.transfermarkt.com/jorginho/profil/spieler/462248.
Transfer history data appended for: https://www.transfermarkt.com/ruben-del-campo/profil/spieler/457778.
Transfer history data appended for: https://www.transfermarkt.com/ivan-jaime/profil/spieler/610335.
Transfer history data appended for: https://www.transfermarkt.com/patrick-william/profil/spieler/560903.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-assuncao/profil/spieler/461629.
Transfer history data appended for: https://www.transfermarkt.com/andrija-lukovic/profil/spieler/258135.
Transfer history data appended for: https://www.transfermarkt.com/carlos-valenzuela/profil/spieler/441477.
Transfer history data appended for: https://www.transfermarkt.com/matheus-clemente/profil/spieler/631589.
Transfer history data appended for: https://www.transfermarkt.com/ivan-zlobin/profil/spieler/282654.
Transfer history data appended for: https://www.transfermarkt.com/srdjan-babic/profil/spieler/222805.
Transfer history data appended for: https://www.transfermarkt.com/henrique-trevisan/profil/spieler/374090.
Transfer history data appended for: https://www.transfermarkt.com/dani-morer/profil/spieler/282726.
Transfer history data appended for: https://www.transfermarkt.com/guga/profil/spieler/258034.
Transfer history data appended for: https://www.transfermarkt.com/bruno-jordao/profil/spieler/415646.
Transfer history data appended for: https://www.transfermarkt.com/ruben-lameiras/profil/spieler/264848.
Transfer history data appended for: https://www.transfermarkt.com/riccieli/profil/spieler/646677.
Transfer history data appended for: https://www.transfermarkt.com/abdul-ibrahim/profil/spieler/640837.
Transfer history data appended for: https://www.transfermarkt.com/luiz-junior/profil/spieler/712107.
Transfer history data appended for: https://www.transfermarkt.com/vana-alves/profil/spieler/212198.

Transfer history data appended for: https://www.transfermarkt.com/edwin-herrera/profil/spieler/602036.
Transfer history data appended for: https://www.transfermarkt.com/jorge-pereira/profil/spieler/337805.
Transfer history data appended for: https://www.transfermarkt.com/jhonata-robert/profil/spieler/711338.
Transfer history data appended for: https://www.transfermarkt.com/gil-dias/profil/spieler/329723.
Transfer history data appended for: https://www.transfermarkt.com/anderson-silva/profil/spieler/522714.
Transfer history data appended for: https://www.transfermarkt.com/calvin-verdonk/profil/spieler/258364.
Transfer history data appended for: https://www.transfermarkt.com/joao-neto/profil/spieler/564919.
Transfer history data appended for: https://www.transfermarkt.com/diogo-queiros/profil/spieler/357148.
Transfer history data appended for: https://www.transfermarkt.com/marcello-trotta/profil/spieler/129505.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-campana/profil/spieler/606872.
Transfer history data appended for: https://www.transfermarkt.com/facundo-ferreyra/profil/spieler/93795.
Transfer history data appended for: https://www.transfermarkt.com/andre-almeida/profil/spieler/83466.
Transfer history data appended for: https://www.transfermarkt.com/everton/profil/spieler/321239.
Transfer history data appended for: https://www.transfermarkt.com/nuno-tavares/profil/spieler/535955.
Transfer history data appended for: https://www.transfermarkt.com/jean-clair-todibo/profil/spieler/605184.
Transfer history data appended for: https://www.transfermarkt.com/franco-cervi/profil/spieler/341110.
Transfer history data appended for: https://www.transfermarkt.com/mile-svilar/profil/spieler/338670.
Transfer history data appended for: https://www.transfermarkt.com/gabriel/profil/spieler/167291.
Transfer history data appended for: https://www.transfermarkt.com/pizzi/profil/spieler/64339.
Transfer history data appended for: https://www.transfermarkt.com/jan-vertonghen/profil/spieler/43250.
Transfer history data appended for: https://www.transfermarkt.com/goncalo-ramos/profil/spieler/550550.
Transfer history data appended for: https://www.transfermarkt.com/odysseas-vlachodimos/profil/spieler/124419.
Transfer history data appended for: https://www.transfermarkt.com/luca-waldschmidt/profil/spieler/196095.
Transfer history data appended for: https://www.transfermarkt.com/chiquinho/profil/spieler/334557.
Transfer history data appended for: https://www.transfermarkt.com/andreas-samaris/profil/spieler/140032.
Transfer history data appended for: https://www.transfermarkt.com/diogo-goncalves/profil/spieler/258015.
Transfer history data appended for: https://www.transfermarkt.com/ferro/profil/spieler/294321.
Transfer history data appended for: https://www.transfermarkt.com/morato/profil/spieler/673492.
Transfer history data appended for: https://www.transfermarkt.com/jardel/profil/spieler/122946.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-otamendi/profil/spieler/54781.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-grimaldo/profil/spieler/193082.
Transfer history data appended for: https://www.transfermarkt.com/rafa-silva/profil/spieler/238055.
Transfer history data appended for: https://www.transfermarkt.com/helton-leite/profil/spieler/175383.
Transfer history data appended for: https://www.transfermarkt.com/adel-taarabt/profil/spieler/45287.
Transfer history data appended for: https://www.transfermarkt.com/julian-weigl/profil/spieler/196792.
Transfer history data appended for: https://www.transfermarkt.com/pedrinho/profil/spieler/515208.
Transfer history data appended for: https://www.transfermarkt.com/filipe-soares/profil/spieler/357163.
Transfer history data appended for: https://www.transfermarkt.com/fabio-pacheco/profil/spieler/111200.
Transfer history data appended for: https://www.transfermarkt.com/galego/profil/spieler/654236.
Transfer history data appended for: https://www.transfermarkt.com/reynaldo/profil/spieler/514297.
Transfer history data appended for: https://www.transfermarkt.com/pedro-nuno/profil/spieler/335380.
Transfer history data appended for: https://www.transfermarkt.com/sori-mane/profil/spieler/410212.
Transfer history data appended for: https://www.transfermarkt.com/anthony-dalberto/profil/spieler/157387.
Transfer history data appended for: https://www.transfermarkt.com/ibrahima/profil/spieler/595012.
Transfer history data appended for: https://www.transfermarkt.com/andre-luis/profil/spieler/539203.
Transfer history data appended for: https://www.transfermarkt.com/derik-lacerda/profil/spieler/700933.
Transfer history data appended for: https://www.transfermarkt.com/matheus-silva/profil/spieler/593208.
Transfer history data appended for: https://www.transfermarkt.com/lazar-rosic/profil/spieler/198053.
Transfer history data appended for: https://www.transfermarkt.com/mateus-pasinato/profil/spieler/349418.
Transfer history data appended for: https://www.transfermarkt.com/nahuel-ferraresi/profil/spieler/466336.
Transfer history data appended for: https://www.transfermarkt.com/abdu-conte/profil/spieler/337798.
Transfer history data appended for: https://www.transfermarkt.com/miguel-oliveira/profil/spieler/237297.
Transfer history data appended for: https://www.transfermarkt.com/yantm/profil/spieler/323945.
Transfer history data appended for: https://www.transfermarkt.com/david-tavares/profil/spieler/416089.
Transfer history data appended for: https://www.transfermarkt.com/walterson-silva/profil/spieler/516127.
Transfer history data appended for: https://www.transfermarkt.com/goncalo-franco/profil/spieler/674798.
Transfer history data appended for: https://www.transfermarkt.com/steven-vitoria/profil/spieler/54716.
Transfer history data appended for: https://www.transfermarkt.com/lucas-rodrigues/profil/spieler/608943.
Transfer history data appended for: https://www.transfermarkt.com/afonso-figueiredo/profil/spieler/237000.
Transfer history data appended for: https://www.transfermarkt.com/pedro-amador/profil/spieler/564544.
Transfer history data appended for: https://www.transfermarkt.com/alex-soares/profil/spieler/207571.
Transfer history data appended for: https://www.transfermarkt.com/kewin/profil/spieler/669219.
Transfer history data appended for: https://www.transfermarkt.com/vladan-danilovic/profil/spieler/456898.
Transfer history data appended for: https://www.transfermarkt.com/julio-cesar/profil/spieler/347019.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-freitas/profil/spieler/340113.
Transfer history data appended for: https://www.transfermarkt.com/ruben-micael/profil/spieler/84491.
Transfer history data appended for: https://www.transfermarkt.com/kalindi/profil/spieler/379377.
Transfer history data appended for: https://www.transfermarkt.com/joao-victor/profil/spieler/743769.
Transfer history data appended for: https://www.transfermarkt.com/chico-ramos/profil/spieler/198007.
Transfer history data appended for: https://www.transfermarkt.com/bryan-rochez/profil/spieler/333199.
Transfer history data appended for: https://www.transfermarkt.com/ruben-freitas/profil/spieler/371503.
Transfer history data appended for: https://www.transfermarkt.com/rui-encarnacao/profil/spieler/671203.
Transfer history data appended for: https://www.transfermarkt.com/joao-vigario/profil/spieler/336735.
Transfer history data appended for: https://www.transfermarkt.com/giorgi-arabidze/profil/spieler/292717.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-abdullahi-alhassan/profil/spieler/364295.
Transfer history data appended for: https://www.transfermarkt.com/brayan-riascos/profil/spieler/313691.
Transfer history data appended for: https://www.transfermarkt.com/kenji-gorre/profil/spieler/374889.
Transfer history data appended for: https://www.transfermarkt.com/gergely-bobal/profil/spieler/164817.
Transfer history data appended for: https://www.transfermarkt.com/nuno-borges/profil/spieler/583520.
Transfer history data appended for: https://www.transfermarkt.com/rui-correia/profil/spieler/258745.
Transfer history data appended for: https://www.transfermarkt.com/mabrouk-rouai/profil/spieler/690608.

Transfer history data appended for: https://www.transfermarkt.com/lucas-kal/profil/spieler/435489.
Transfer history data appended for: https://www.transfermarkt.com/vincent-koziello/profil/spieler/290551.
Transfer history data appended for: https://www.transfermarkt.com/vincent-thill/profil/spieler/316760.
Transfer history data appended for: https://www.transfermarkt.com/pedrao/profil/spieler/585264.
Transfer history data appended for: https://www.transfermarkt.com/joao-camacho/profil/spieler/268732.
Transfer history data appended for: https://www.transfermarkt.com/riccardo-piscitelli/profil/spieler/163051.
Transfer history data appended for: https://www.transfermarkt.com/larry-azouni/profil/spieler/204347.
Transfer history data appended for: https://www.transfermarkt.com/witi/profil/spieler/352425.
Transfer history data appended for: https://www.transfermarkt.com/daniel-guimaraes/profil/spieler/269864.
Transfer history data appended for: https://www.transfermarkt.com/denis-will-poha/profil/spieler/288248.
Transfer history data appended for: https://www.transfermarkt.com/jorge-fernandes/profil/spieler/344395.
Transfer history data appended for: https://www.transfermarkt.com/miguel-luis/profil/spieler/357161.
Transfer history data appended for: https://www.transfermarkt.com/andre-andre/profil/spieler/63837.
Transfer history data appended for: https://www.transfermarkt.com/falaye-sacko/profil/spieler/364857.
Transfer history data appended for: https://www.transfermarkt.com/matous-trmal/profil/spieler/549039.
Transfer history data appended for: https://www.transfermarkt.com/elias-abouchabaka/profil/spieler/335002.
Transfer history data appended for: https://www.transfermarkt.com/jacob-maddox/profil/spieler/314268.
Transfer history data appended for: https://www.transfermarkt.com/yann-aurel-bisseck/profil/spieler/441986.
Transfer history data appended for: https://www.transfermarkt.com/zie-ouattara/profil/spieler/613437.
Transfer history data appended for: https://www.transfermarkt.com/bruno-varela/profil/spieler/182722.
Transfer history data appended for: https://www.transfermarkt.com/joseph-amoah/profil/spieler/358719.
Transfer history data appended for: https://www.transfermarkt.com/marcus-edwards/profil/spieler/314367.
Transfer history data appended for: https://www.transfermarkt.com/rochinha/profil/spieler/290336.
Transfer history data appended for: https://www.transfermarkt.com/bruno-duarte/profil/spieler/598629.
Transfer history data appended for: https://www.transfermarkt.com/pepelu/profil/spieler/328480.
Transfer history data appended for: https://www.transfermarkt.com/gideon-mensah/profil/spieler/397171.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-janvier/profil/spieler/324803.
Transfer history data appended for: https://www.transfermarkt.com/andre-almeida/profil/spieler/375382.
Transfer history data appended for: https://www.transfermarkt.com/abdul-mumin/profil/spieler/451801.
Transfer history data appended for: https://www.transfermarkt.com/jonas-carls/profil/spieler/239972.
Transfer history data appended for: https://www.transfermarkt.com/silvio/profil/spieler/84511.
Transfer history data appended for: https://www.transfermarkt.com/jung-min-kim/profil/spieler/297705.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-tie/profil/spieler/525962.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-quaresma/profil/spieler/4188.
Transfer history data appended for: https://www.transfermarkt.com/abou-ouattara/profil/spieler/443263.
Transfer history data appended for: https://www.transfermarkt.com/lyle-foster/profil/spieler/467623.
Transfer history data appended for: https://www.transfermarkt.com/matheus-mascarenhas/profil/spieler/503766.
Transfer history data appended for: https://www.transfermarkt.com/alhassan-wakaso/profil/spieler/168536.
Transfer history data appended for: https://www.transfermarkt.com/noah-jean-holm/profil/spieler/494177.
Transfer history data appended for: https://www.transfermarkt.com/easah-suliman/profil/spieler/282820.
Transfer history data appended for: https://www.transfermarkt.com/celton-biai/profil/spieler/461963.
Transfer history data appended for: https://www.transfermarkt.com/juan-villa/profil/spieler/641131.
Transfer history data appended for: https://www.transfermarkt.com/ruben-fernandes/profil/spieler/27178.
Transfer history data appended for: https://www.transfermarkt.com/ygor-nogueira/profil/spieler/187211.
Transfer history data appended for: https://www.transfermarkt.com/souleymane-aw/profil/spieler/490415.
Transfer history data appended for: https://www.transfermarkt.com/claude-goncalves/profil/spieler/280178.
Transfer history data appended for: https://www.transfermarkt.com/yves-baraye/profil/spieler/193994.
Transfer history data appended for: https://www.transfermarkt.com/lourency/profil/spieler/432960.
Transfer history data appended for: https://www.transfermarkt.com/alaa-abbas/profil/spieler/560958.
Transfer history data appended for: https://www.transfermarkt.com/henrique-gomes/profil/spieler/352918.
Transfer history data appended for: https://www.transfermarkt.com/leandrinho/profil/spieler/425939.
Transfer history data appended for: https://www.transfermarkt.com/daniel-fuzato/profil/spieler/438682.
Transfer history data appended for: https://www.transfermarkt.com/brian-araujo/profil/spieler/695141.
Transfer history data appended for: https://www.transfermarkt.com/boubacar-hanne/profil/spieler/522412.
Transfer history data appended for: https://www.transfermarkt.com/samuel-lino/profil/spieler/694928.
Transfer history data appended for: https://www.transfermarkt.com/diogo-silva/profil/spieler/671882.
Transfer history data appended for: https://www.transfermarkt.com/rodrigao/profil/spieler/510782.
Transfer history data appended for: https://www.transfermarkt.com/guilherme-mantuan/profil/spieler/477461.
Transfer history data appended for: https://www.transfermarkt.com/denis/profil/spieler/75102.
Transfer history data appended for: https://www.transfermarkt.com/tim-hall/profil/spieler/299973.
Transfer history data appended for: https://www.transfermarkt.com/renan-oliveira/profil/spieler/522091.
Transfer history data appended for: https://www.transfermarkt.com/vitor-carvalho/profil/spieler/553062.
Transfer history data appended for: https://www.transfermarkt.com/joao-talocha/profil/spieler/205116.
Transfer history data appended for: https://www.transfermarkt.com/kanya-fujimoto/profil/spieler/415525.
Transfer history data appended for: https://www.transfermarkt.com/lucas-mineiro/profil/spieler/432958.
Transfer history data appended for: https://www.transfermarkt.com/joel-pereira/profil/spieler/225165.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-isaiah/profil/spieler/352840.
Transfer history data appended for: https://www.transfermarkt.com/joao-afonso/profil/spieler/224878.
Transfer history data appended for: https://www.transfermarkt.com/miullen/profil/spieler/617445.
Transfer history data appended for: https://www.transfermarkt.com/antoine-leautey/profil/spieler/467486.
Transfer history data appended for: https://www.transfermarkt.com/eduardo/profil/spieler/220722.
Transfer history data appended for: https://www.transfermarkt.com/nuno-sequeira/profil/spieler/193303.
Transfer history data appended for: https://www.transfermarkt.com/vitor-tormena/profil/spieler/517300.
Transfer history data appended for: https://www.transfermarkt.com/joao-novais/profil/spieler/228940.
Transfer history data appended for: https://www.transfermarkt.com/bruno-viana/profil/spieler/411838.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-esgaio/profil/spieler/139395.
Transfer history data appended for: https://www.transfermarkt.com/ze-carlos/profil/spieler/617679.
Transfer history data appended for: https://www.transfermarkt.com/nico-gaitan/profil/spieler/75442.
Transfer history data appended for: https://www.transfermarkt.com/lukas-hornicek/profil/spieler/629773.
Transfer history data appended for: https://www.transfermarkt.com/andre-horta/profil/spieler/329722.
Transfer history data appended for: https://www.transfermarkt.com/fransergio/profil/spieler/111828.

Transfer history data appended for: https://www.transfermarkt.com/matheus/profil/spieler/177547.
Transfer history data appended for: https://www.transfermarkt.com/galeno/profil/spieler/454121.
Transfer history data appended for: https://www.transfermarkt.com/abel-ruiz/profil/spieler/340376.
Transfer history data appended for: https://www.transfermarkt.com/tiago-sa/profil/spieler/286908.
Transfer history data appended for: https://www.transfermarkt.com/andre-castro/profil/spieler/58267.
Transfer history data appended for: https://www.transfermarkt.com/david-carmo/profil/spieler/498237.
Transfer history data appended for: https://www.transfermarkt.com/francisco-moura/profil/spieler/478365.
Transfer history data appended for: https://www.transfermarkt.com/al-musrati/profil/spieler/377641.
Transfer history data appended for: https://www.transfermarkt.com/diogo-figueiras/profil/spieler/172181.
Transfer history data appended for: https://www.transfermarkt.com/paulinho/profil/spieler/211072.
Transfer history data appended for: https://www.transfermarkt.com/raul-silva/profil/spieler/164705.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-horta/profil/spieler/261927.
Transfer history data appended for: https://www.transfermarkt.com/reggie-cannon/profil/spieler/478940.
Transfer history data appended for: https://www.transfermarkt.com/matheus-kayser/profil/spieler/187212.
Transfer history data appended for: https://www.transfermarkt.com/yanis-hamache/profil/spieler/629567.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-perez/profil/spieler/182108.
Transfer history data appended for: https://www.transfermarkt.com/leo-jardim/profil/spieler/288415.
Transfer history data appended for: https://www.transfermarkt.com/show/profil/spieler/568216.
Transfer history data appended for: https://www.transfermarkt.com/angel-gomes/profil/spieler/392770.
Transfer history data appended for: https://www.transfermarkt.com/cristian-castro/profil/spieler/726697.
Transfer history data appended for: https://www.transfermarkt.com/nathan/profil/spieler/740273.
Transfer history data appended for: https://www.transfermarkt.com/chidozie-awaziem/profil/spieler/358143.
Transfer history data appended for: https://www.transfermarkt.com/paulinho/profil/spieler/534473.
Transfer history data appended for: https://www.transfermarkt.com/jorge-benguche/profil/spieler/454321.
Transfer history data appended for: https://www.transfermarkt.com/musa-juwara/profil/spieler/562030.
Transfer history data appended for: https://www.transfermarkt.com/miguel-reisinho/profil/spieler/478366.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-sauer/profil/spieler/336158.
Transfer history data appended for: https://www.transfermarkt.com/rafael-bracali/profil/spieler/44177.
Transfer history data appended for: https://www.transfermarkt.com/jackson-porozo/profil/spieler/491616.
Transfer history data appended for: https://www.transfermarkt.com/alberth-elis/profil/spieler/281319.
Transfer history data appended for: https://www.transfermarkt.com/joao-goncalves/profil/spieler/685805.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-mangas/profil/spieler/314944.
Transfer history data appended for: https://www.transfermarkt.com/yusupha-njie/profil/spieler/177964.
Transfer history data appended for: https://www.transfermarkt.com/javi-garcia/profil/spieler/36350.
Transfer history data appended for: https://www.transfermarkt.com/alejandro-gomez/profil/spieler/504104.
Transfer history data appended for: https://www.transfermarkt.com/nuno-santos/profil/spieler/367468.
Transfer history data appended for: https://www.transfermarkt.com/zouhair-feddal/profil/spieler/129386.
Transfer history data appended for: https://www.transfermarkt.com/eduardo-quaresma/profil/spieler/504073.
Transfer history data appended for: https://www.transfermarkt.com/pedro-goncalves/profil/spieler/426620.
Transfer history data appended for: https://www.transfermarkt.com/nuno-santos/profil/spieler/290391.
Transfer history data appended for: https://www.transfermarkt.com/joao-mario/profil/spieler/149729.
Transfer history data appended for: https://www.transfermarkt.com/joao-palhinha/profil/spieler/257455.
Transfer history data appended for: https://www.transfermarkt.com/tiago-tomas/profil/spieler/616344.
Transfer history data appended for: https://www.transfermarkt.com/lumor/profil/spieler/344393.
Transfer history data appended for: https://www.transfermarkt.com/luis-neto/profil/spieler/56036.
Transfer history data appended for: https://www.transfermarkt.com/bruno-gaspar/profil/spieler/230457.
Transfer history data appended for: https://www.transfermarkt.com/rodrigo-fernandes/profil/spieler/489212.
Transfer history data appended for: https://www.transfermarkt.com/cristian-borja/profil/spieler/356099.
Transfer history data appended for: https://www.transfermarkt.com/jovane-cabral/profil/spieler/448466.
Transfer history data appended for: https://www.transfermarkt.com/gonzalo-plata/profil/spieler/592735.
Transfer history data appended for: https://www.transfermarkt.com/andraz-sporar/profil/spieler/179860.
Transfer history data appended for: https://www.transfermarkt.com/nuno-mendes/profil/spieler/616341.
Transfer history data appended for: https://www.transfermarkt.com/pedro-porro/profil/spieler/553875.
Transfer history data appended for: https://www.transfermarkt.com/daniel-braganca/profil/spieler/461943.
Transfer history data appended for: https://www.transfermarkt.com/luis-maximiano/profil/spieler/367464.
Transfer history data appended for: https://www.transfermarkt.com/luiz-phellype/profil/spieler/240578.
Transfer history data appended for: https://www.transfermarkt.com/goncalo-inacio/profil/spieler/549006.
Transfer history data appended for: https://www.transfermarkt.com/tabata/profil/spieler/438202.
Transfer history data appended for: https://www.transfermarkt.com/matheus-nunes/profil/spieler/601883.
Transfer history data appended for: https://www.transfermarkt.com/joelson-fernandes/profil/spieler/581140.
Transfer history data appended for: https://www.transfermarkt.com/antonio-adan/profil/spieler/44062.
Transfer history data appended for: https://www.transfermarkt.com/rafael-camacho/profil/spieler/400831.
Transfer history data appended for: https://www.transfermarkt.com/stefan-ristovski/profil/spieler/104466.
Transfer history data appended for: https://www.transfermarkt.com/marco-baixinho/profil/spieler/131015.
Transfer history data appended for: https://www.transfermarkt.com/lucas-silva/profil/spieler/644158.
Transfer history data appended for: https://www.transfermarkt.com/maracas/profil/spieler/373187.
Transfer history data appended for: https://www.transfermarkt.com/michael/profil/spieler/579207.
Transfer history data appended for: https://www.transfermarkt.com/luther-singh/profil/spieler/387378.
Transfer history data appended for: https://www.transfermarkt.com/jorge-silva/profil/spieler/329721.
Transfer history data appended for: https://www.transfermarkt.com/fernando-fonseca/profil/spieler/344392.
Transfer history data appended for: https://www.transfermarkt.com/pedro-martelo/profil/spieler/410322.
Transfer history data appended for: https://www.transfermarkt.com/simao-rocha/profil/spieler/682719.
Transfer history data appended for: https://www.transfermarkt.com/martin-calderon/profil/spieler/278404.
Transfer history data appended for: https://www.transfermarkt.com/helder-ferreira/profil/spieler/350311.
Transfer history data appended for: https://www.transfermarkt.com/oleg-reabciuk/profil/spieler/461512.
Transfer history data appended for: https://www.transfermarkt.com/marcelo/profil/spieler/190185.
Transfer history data appended for: https://www.transfermarkt.com/pedro-marques/profil/spieler/425371.
Transfer history data appended for: https://www.transfermarkt.com/bruno-costa/profil/spieler/344519.
Transfer history data appended for: https://www.transfermarkt.com/joao-amaral/profil/spieler/352898.
Transfer history data appended for: https://www.transfermarkt.com/dor-jan/profil/spieler/226230.
Transfer history data appended for: https://www.transfermarkt.com/abbas-ibrahim/profil/spieler/631278.

Transfer history data appended for: https://www.transfermarkt.com/adriano-castanheira/profil/spieler/243779.
Transfer history data appended for: https://www.transfermarkt.com/douglas-tanque/profil/spieler/168530.
Transfer history data appended for: https://www.transfermarkt.com/jordi/profil/spieler/255928.
Transfer history data appended for: https://www.transfermarkt.com/joao-pedro/profil/spieler/298410.
Transfer history data appended for: https://www.transfermarkt.com/stephen-eustaquio/profil/spieler/512913.
Transfer history data appended for: https://www.transfermarkt.com/david-sualehe/profil/spieler/344540.
Transfer history data appended for: https://www.transfermarkt.com/matchoi-djalo/profil/spieler/685887.
Transfer history data appended for: https://www.transfermarkt.com/luiz-carlos/profil/spieler/129670.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-diaby/profil/spieler/611430.
Transfer history data appended for: https://www.transfermarkt.com/evanilson/profil/spieler/711337.
Transfer history data appended for: https://www.transfermarkt.com/luis-diaz/profil/spieler/480692.
Transfer history data appended for: https://www.transfermarkt.com/diogo-costa/profil/spieler/357153.
Transfer history data appended for: https://www.transfermarkt.com/agustin-marchesin/profil/spieler/54534.
Transfer history data appended for: https://www.transfermarkt.com/carraca/profil/spieler/291941.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-loum/profil/spieler/364237.
Transfer history data appended for: https://www.transfermarkt.com/otavio/profil/spieler/231289.
Transfer history data appended for: https://www.transfermarkt.com/diogo-leite/profil/spieler/357156.
Transfer history data appended for: https://www.transfermarkt.com/jesus-corona/profil/spieler/125165.
Transfer history data appended for: https://www.transfermarkt.com/romario-baro/profil/spieler/375383.
Transfer history data appended for: https://www.transfermarkt.com/claudio-ramos/profil/spieler/155396.
Transfer history data appended for: https://www.transfermarkt.com/mouhamed-mbaye/profil/spieler/410226.
Transfer history data appended for: https://www.transfermarkt.com/fabio-vieira/profil/spieler/537598.
Transfer history data appended for: https://www.transfermarkt.com/mateus-uribe/profil/spieler/214538.
Transfer history data appended for: https://www.transfermarkt.com/moussa-marega/profil/spieler/283130.
Transfer history data appended for: https://www.transfermarkt.com/nanu/profil/spieler/291399.
Transfer history data appended for: https://www.transfermarkt.com/wilson-manafa/profil/spieler/257388.
Transfer history data appended for: https://www.transfermarkt.com/ivan-marcano/profil/spieler/57723.
Transfer history data appended for: https://www.transfermarkt.com/marko-grujic/profil/spieler/222813.
Transfer history data appended for: https://www.transfermarkt.com/shoya-nakajima/profil/spieler/188911.
Transfer history data appended for: https://www.transfermarkt.com/sergio-oliveira/profil/spieler/112465.
Transfer history data appended for: https://www.transfermarkt.com/felipe-anderson/profil/spieler/159372.
Transfer history data appended for: https://www.transfermarkt.com/joao-mario/profil/spieler/537602.
Transfer history data appended for: https://www.transfermarkt.com/chancel-mbemba/profil/spieler/203348.
Transfer history data appended for: https://www.transfermarkt.com/malang-sarr/profil/spieler/344596.
Transfer history data appended for: https://www.transfermarkt.com/toni-martinez/profil/spieler/302371.
Transfer history data appended for: https://www.transfermarkt.com/pepe/profil/spieler/14132.
Transfer history data appended for: https://www.transfermarkt.com/zaidu-sanusi/profil/spieler/544784.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-taremi/profil/spieler/307058.
Transfer history data appended for: https://www.transfermarkt.com/mihai-popa/profil/spieler/623412.
Transfer history data appended for: https://www.transfermarkt.com/mihai-radut/profil/spieler/96850.
Transfer history data appended for: https://www.transfermarkt.com/andrei-trusescu/profil/spieler/466718.
Transfer history data appended for: https://www.transfermarkt.com/romario-moise/profil/spieler/390844.
Transfer history data appended for: https://www.transfermarkt.com/albert-stahl/profil/spieler/478022.
Transfer history data appended for: https://www.transfermarkt.com/paulian-banu/profil/spieler/700767.
Transfer history data appended for: https://www.transfermarkt.com/sebastien-wuthrich/profil/spieler/52744.
Transfer history data appended for: https://www.transfermarkt.com/hugo-sousa/profil/spieler/187908.
Transfer history data appended for: https://www.transfermarkt.com/george-merloi/profil/spieler/530697.
Transfer history data appended for: https://www.transfermarkt.com/shlomi-azulay/profil/spieler/136997.
Transfer history data appended for: https://www.transfermarkt.com/valerica-gaman/profil/spieler/47576.
Transfer history data appended for: https://www.transfermarkt.com/daniel-graovac/profil/spieler/131728.
Transfer history data appended for: https://www.transfermarkt.com/ionut-andrei-zaharia/profil/spieler/814974.
Transfer history data appended for: https://www.transfermarkt.com/dinu-graur/profil/spieler/309570.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-serban/profil/spieler/623422.
Transfer history data appended for: https://www.transfermarkt.com/mirel-bolboasa/profil/spieler/64114.
Transfer history data appended for: https://www.transfermarkt.com/david-lazar/profil/spieler/168278.
Transfer history data appended for: https://www.transfermarkt.com/silviu-balaure/profil/spieler/296585.
Transfer history data appended for: https://www.transfermarkt.com/valentin-gheorghe/profil/spieler/453810.
Transfer history data appended for: https://www.transfermarkt.com/constantin-dima/profil/spieler/335820.
Transfer history data appended for: https://www.transfermarkt.com/ljuban-crepulja/profil/spieler/238474.
Transfer history data appended for: https://www.transfermarkt.com/raoul-baicu/profil/spieler/605947.
Transfer history data appended for: https://www.transfermarkt.com/takayuki-seto/profil/spieler/97562.
Transfer history data appended for: https://www.transfermarkt.com/robert-riza/profil/spieler/623411.
Transfer history data appended for: https://www.transfermarkt.com/risto-radunovic/profil/spieler/144339.
Transfer history data appended for: https://www.transfermarkt.com/david-bruno/profil/spieler/126964.
Transfer history data appended for: https://www.transfermarkt.com/mattia-montini/profil/spieler/130368.
Transfer history data appended for: https://www.transfermarkt.com/dario-canadjija/profil/spieler/193998.
Transfer history data appended for: https://www.transfermarkt.com/constantin-budescu/profil/spieler/164233.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-baxevanos/profil/spieler/465616.
Transfer history data appended for: https://www.transfermarkt.com/andreias-calcan/profil/spieler/244548.
Transfer history data appended for: https://www.transfermarkt.com/razvan-popa/profil/spieler/220851.
Transfer history data appended for: https://www.transfermarkt.com/vlad-olteanu/profil/spieler/339960.
Transfer history data appended for: https://www.transfermarkt.com/juan-pablo-passaglia/profil/spieler/128339.
Transfer history data appended for: https://www.transfermarkt.com/antonio-stan/profil/spieler/831083.
Transfer history data appended for: https://www.transfermarkt.com/platini/profil/spieler/130930.
Transfer history data appended for: https://www.transfermarkt.com/dan-talmaciu/profil/spieler/830935.
Transfer history data appended for: https://www.transfermarkt.com/gai-assulin/profil/spieler/38412.
Transfer history data appended for: https://www.transfermarkt.com/razvan-onea/profil/spieler/536130.
Transfer history data appended for: https://www.transfermarkt.com/manuel-de-iriondo/profil/spieler/296805.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-balint/profil/spieler/813629.
Transfer history data appended for: https://www.transfermarkt.com/joseph-mensah/profil/spieler/286000.

Transfer history data appended for: https://www.transfermarkt.com/donaldo-acka/profil/spieler/547052.
Transfer history data appended for: https://www.transfermarkt.com/floriano-vanzo/profil/spieler/201696.
Transfer history data appended for: https://www.transfermarkt.com/dzenan-zajmovic/profil/spieler/278769.
Transfer history data appended for: https://www.transfermarkt.com/sorin-busu/profil/spieler/57679.
Transfer history data appended for: https://www.transfermarkt.com/lucas-chacana/profil/spieler/420408.
Transfer history data appended for: https://www.transfermarkt.com/levente-b%C5%91sz/profil/spieler/368548.
Transfer history data appended for: https://www.transfermarkt.com/manuel-angiulli/profil/spieler/263711.
Transfer history data appended for: https://www.transfermarkt.com/ianos-brinza/profil/spieler/556245.
Transfer history data appended for: https://www.transfermarkt.com/nicandro-breeveld/profil/spieler/53222.
Transfer history data appended for: https://www.transfermarkt.com/doru-popadiuc/profil/spieler/279927.
Transfer history data appended for: https://www.transfermarkt.com/andrei-agape/profil/spieler/793471.
Transfer history data appended for: https://www.transfermarkt.com/cosmin-frasinescu/profil/spieler/46546.
Transfer history data appended for: https://www.transfermarkt.com/teodor-axinte/profil/spieler/470143.
Transfer history data appended for: https://www.transfermarkt.com/marius-mihalache/profil/spieler/97556.
Transfer history data appended for: https://www.transfermarkt.com/andrei-cristea/profil/spieler/26491.
Transfer history data appended for: https://www.transfermarkt.com/stefan-rusu/profil/spieler/582926.
Transfer history data appended for: https://www.transfermarkt.com/rodny-lopes-cabral/profil/spieler/245902.
Transfer history data appended for: https://www.transfermarkt.com/catalin-aeroaiei/profil/spieler/394886.
Transfer history data appended for: https://www.transfermarkt.com/hidajet-hankic/profil/spieler/156680.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-melinte/profil/spieler/830290.
Transfer history data appended for: https://www.transfermarkt.com/andrei-patache/profil/spieler/64216.
Transfer history data appended for: https://www.transfermarkt.com/adrian-moescu/profil/spieler/706943.
Transfer history data appended for: https://www.transfermarkt.com/eduard-florescu/profil/spieler/379194.
Transfer history data appended for: https://www.transfermarkt.com/alin-seroni/profil/spieler/243846.
Transfer history data appended for: https://www.transfermarkt.com/bautista-pavlovsky/profil/spieler/633726.
Transfer history data appended for: https://www.transfermarkt.com/mihai-roman/profil/spieler/64229.
Transfer history data appended for: https://www.transfermarkt.com/marian-tarsa/profil/spieler/412738.
Transfer history data appended for: https://www.transfermarkt.com/mario-contra/profil/spieler/331578.
Transfer history data appended for: https://www.transfermarkt.com/mahmoud-al-mawas/profil/spieler/380348.
Transfer history data appended for: https://www.transfermarkt.com/sekou-camara/profil/spieler/486537.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-tiganasu/profil/spieler/177661.
Transfer history data appended for: https://www.transfermarkt.com/christopher-braun/profil/spieler/82657.
Transfer history data appended for: https://www.transfermarkt.com/david-babunski/profil/spieler/133628.
Transfer history data appended for: https://www.transfermarkt.com/david-croitoru/profil/spieler/791176.
Transfer history data appended for: https://www.transfermarkt.com/enriko-papa/profil/spieler/241221.
Transfer history data appended for: https://www.transfermarkt.com/hamidou-keyta/profil/spieler/419293.
Transfer history data appended for: https://www.transfermarkt.com/youssef-toutouh/profil/spieler/164658.
Transfer history data appended for: https://www.transfermarkt.com/hervin-ongenda/profil/spieler/182910.
Transfer history data appended for: https://www.transfermarkt.com/florin-plamada/profil/spieler/241574.
Transfer history data appended for: https://www.transfermarkt.com/baba-toure/profil/spieler/315111.
Transfer history data appended for: https://www.transfermarkt.com/stefan-ashkovski/profil/spieler/134458.
Transfer history data appended for: https://www.transfermarkt.com/marcel-holzmann/profil/spieler/54847.
Transfer history data appended for: https://www.transfermarkt.com/minas-chalkiadakis/profil/spieler/460332.
Transfer history data appended for: https://www.transfermarkt.com/realdo-fili/profil/spieler/270019.
Transfer history data appended for: https://www.transfermarkt.com/denis-harut/profil/spieler/412641.
Transfer history data appended for: https://www.transfermarkt.com/andrei-chindris/profil/spieler/435731.
Transfer history data appended for: https://www.transfermarkt.com/eduard-pap/profil/spieler/249080.
Transfer history data appended for: https://www.transfermarkt.com/andrei-tircoveanu/profil/spieler/271293.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-rodriguez/profil/spieler/537768.
Transfer history data appended for: https://www.transfermarkt.com/billel-omrani/profil/spieler/131589.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-chipciu/profil/spieler/64126.
Transfer history data appended for: https://www.transfermarkt.com/andrei-joca/profil/spieler/675540.
Transfer history data appended for: https://www.transfermarkt.com/jakub-vojtus/profil/spieler/104990.
Transfer history data appended for: https://www.transfermarkt.com/mario-rondon/profil/spieler/119272.
Transfer history data appended for: https://www.transfermarkt.com/ovidiu-hoban/profil/spieler/81484.
Transfer history data appended for: https://www.transfermarkt.com/paulo-vinicius/profil/spieler/45025.
Transfer history data appended for: https://www.transfermarkt.com/michael-pereira/profil/spieler/147483.
Transfer history data appended for: https://www.transfermarkt.com/camora/profil/spieler/44698.
Transfer history data appended for: https://www.transfermarkt.com/rares-murariu/profil/spieler/319238.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-paun/profil/spieler/291656.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-debeljuh/profil/spieler/340073.
Transfer history data appended for: https://www.transfermarkt.com/iasmin-latovlevici/profil/spieler/47172.
Transfer history data appended for: https://www.transfermarkt.com/syam-ben-youssef/profil/spieler/133078.
Transfer history data appended for: https://www.transfermarkt.com/william-soares/profil/spieler/80151.
Transfer history data appended for: https://www.transfermarkt.com/luis-aurelio/profil/spieler/236748.
Transfer history data appended for: https://www.transfermarkt.com/mike-cestor/profil/spieler/136744.
Transfer history data appended for: https://www.transfermarkt.com/nicolae-carnat/profil/spieler/341140.
Transfer history data appended for: https://www.transfermarkt.com/ionut-rus/profil/spieler/418208.
Transfer history data appended for: https://www.transfermarkt.com/ivica-zunic/profil/spieler/139943.
Transfer history data appended for: https://www.transfermarkt.com/mateo-susic/profil/spieler/83287.
Transfer history data appended for: https://www.transfermarkt.com/cristian-balgradean/profil/spieler/158839.
Transfer history data appended for: https://www.transfermarkt.com/cristian-manea/profil/spieler/271284.
Transfer history data appended for: https://www.transfermarkt.com/catalin-itu/profil/spieler/464306.
Transfer history data appended for: https://www.transfermarkt.com/andrei-burca/profil/spieler/289308.
Transfer history data appended for: https://www.transfermarkt.com/valentin-costache/profil/spieler/341391.
Transfer history data appended for: https://www.transfermarkt.com/damjan-djokovic/profil/spieler/143039.
Transfer history data appended for: https://www.transfermarkt.com/denis-ciobotariu/profil/spieler/428593.
Transfer history data appended for: https://www.transfermarkt.com/razvan-ivan/profil/spieler/654067.
Transfer history data appended for: https://www.transfermarkt.com/erico/profil/spieler/233917.
Transfer history data appended for: https://www.transfermarkt.com/simo-rumbullaku/profil/spieler/234237.

Transfer history data appended for: https://www.transfermarkt.com/ciprian-rus/profil/spieler/397474.
Transfer history data appended for: https://www.transfermarkt.com/calin-popescu/profil/spieler/509936.
Transfer history data appended for: https://www.transfermarkt.com/sorin-bustea/profil/spieler/213101.
Transfer history data appended for: https://www.transfermarkt.com/mihovil-klapan/profil/spieler/252874.
Transfer history data appended for: https://www.transfermarkt.com/marius-tomozei/profil/spieler/213243.
Transfer history data appended for: https://www.transfermarkt.com/dragos-tescan/profil/spieler/700772.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-oroian/profil/spieler/614623.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-ionita/profil/spieler/113865.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-benga/profil/spieler/202800.
Transfer history data appended for: https://www.transfermarkt.com/dragos-balauru/profil/spieler/175972.
Transfer history data appended for: https://www.transfermarkt.com/nelut-rosu/profil/spieler/241310.
Transfer history data appended for: https://www.transfermarkt.com/cristian-melinte/profil/spieler/63461.
Transfer history data appended for: https://www.transfermarkt.com/horatiu-moldovan/profil/spieler/525438.
Transfer history data appended for: https://www.transfermarkt.com/denis-rusu/profil/spieler/805072.
Transfer history data appended for: https://www.transfermarkt.com/valentin-buhacianu/profil/spieler/394464.
Transfer history data appended for: https://www.transfermarkt.com/ioan-hora/profil/spieler/54528.
Transfer history data appended for: https://www.transfermarkt.com/octavian-ursu/profil/spieler/286549.
Transfer history data appended for: https://www.transfermarkt.com/marian-pleasca/profil/spieler/148206.
Transfer history data appended for: https://www.transfermarkt.com/david-miculescu/profil/spieler/614800.
Transfer history data appended for: https://www.transfermarkt.com/vlad-morar/profil/spieler/186031.
Transfer history data appended for: https://www.transfermarkt.com/florin-iacob/profil/spieler/186028.
Transfer history data appended for: https://www.transfermarkt.com/florin-ilie/profil/spieler/192866.
Transfer history data appended for: https://www.transfermarkt.com/arpad-tordai/profil/spieler/271294.
Transfer history data appended for: https://www.transfermarkt.com/andrei-artean/profil/spieler/241254.
Transfer history data appended for: https://www.transfermarkt.com/virgil-ghita/profil/spieler/340977.
Transfer history data appended for: https://www.transfermarkt.com/carlo-casap/profil/spieler/340981.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-buta/profil/spieler/724115.
Transfer history data appended for: https://www.transfermarkt.com/alex-georgescu/profil/spieler/547855.
Transfer history data appended for: https://www.transfermarkt.com/roberto-malaele/profil/spieler/556209.
Transfer history data appended for: https://www.transfermarkt.com/ion-gaztanaga/profil/spieler/66110.
Transfer history data appended for: https://www.transfermarkt.com/kevin-luckassen/profil/spieler/187290.
Transfer history data appended for: https://www.transfermarkt.com/robert-hodorogea/profil/spieler/289403.
Transfer history data appended for: https://www.transfermarkt.com/bradley-de-nooijer/profil/spieler/313741.
Transfer history data appended for: https://www.transfermarkt.com/darius-grosu/profil/spieler/568557.
Transfer history data appended for: https://www.transfermarkt.com/ely-fernandes/profil/spieler/292488.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-matan/profil/spieler/368942.
Transfer history data appended for: https://www.transfermarkt.com/radu-boboc/profil/spieler/319202.
Transfer history data appended for: https://www.transfermarkt.com/cosmin-matei/profil/spieler/81421.
Transfer history data appended for: https://www.transfermarkt.com/aurelian-chitu/profil/spieler/164236.
Transfer history data appended for: https://www.transfermarkt.com/alexi-pitu/profil/spieler/547822.
Transfer history data appended for: https://www.transfermarkt.com/stefan-bodisteanu/profil/spieler/608448.
Transfer history data appended for: https://www.transfermarkt.com/josemi-castaneda/profil/spieler/455080.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-mladen/profil/spieler/96790.
Transfer history data appended for: https://www.transfermarkt.com/catalin-cabuz/profil/spieler/315442.
Transfer history data appended for: https://www.transfermarkt.com/victor-fernandez/profil/spieler/415205.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-iancu/profil/spieler/164254.
Transfer history data appended for: https://www.transfermarkt.com/angel-martinez/profil/spieler/66117.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-popescu/profil/spieler/608447.
Transfer history data appended for: https://www.transfermarkt.com/adrian-stoian/profil/spieler/96853.
Transfer history data appended for: https://www.transfermarkt.com/damien-dussaut/profil/spieler/205533.
Transfer history data appended for: https://www.transfermarkt.com/george-ganea/profil/spieler/335821.
Transfer history data appended for: https://www.transfermarkt.com/romario-benzar/profil/spieler/164231.
Transfer history data appended for: https://www.transfermarkt.com/andrei-ciobanu/profil/spieler/340980.
Transfer history data appended for: https://www.transfermarkt.com/doru-dumitrescu/profil/spieler/415890.
Transfer history data appended for: https://www.transfermarkt.com/razvan-tincu/profil/spieler/48685.
Transfer history data appended for: https://www.transfermarkt.com/marius-stefanescu/profil/spieler/685795.
Transfer history data appended for: https://www.transfermarkt.com/peter-gal-andrezly/profil/spieler/90872.
Transfer history data appended for: https://www.transfermarkt.com/rachid-bouhenna/profil/spieler/194790.
Transfer history data appended for: https://www.transfermarkt.com/aleksa-markovic/profil/spieler/636241.
Transfer history data appended for: https://www.transfermarkt.com/bryan-nouvier/profil/spieler/344889.
Transfer history data appended for: https://www.transfermarkt.com/boubacar-fofana/profil/spieler/130964.
Transfer history data appended for: https://www.transfermarkt.com/zsombor-veress/profil/spieler/451326.
Transfer history data appended for: https://www.transfermarkt.com/florin-stefan/profil/spieler/320637.
Transfer history data appended for: https://www.transfermarkt.com/andres-dumitrescu/profil/spieler/547812.
Transfer history data appended for: https://www.transfermarkt.com/florin-purece/profil/spieler/203059.
Transfer history data appended for: https://www.transfermarkt.com/claudiu-veres/profil/spieler/746702.
Transfer history data appended for: https://www.transfermarkt.com/lorant-kovacs/profil/spieler/272527.
Transfer history data appended for: https://www.transfermarkt.com/ioan-dumiter/profil/spieler/466722.
Transfer history data appended for: https://www.transfermarkt.com/radoslav-dimitrov/profil/spieler/134163.
Transfer history data appended for: https://www.transfermarkt.com/george-dragomir/profil/spieler/749036.
Transfer history data appended for: https://www.transfermarkt.com/vlad-mitrea/profil/spieler/484029.
Transfer history data appended for: https://www.transfermarkt.com/istvan-fulop/profil/spieler/242113.
Transfer history data appended for: https://www.transfermarkt.com/admir-bajrovic/profil/spieler/222556.
Transfer history data appended for: https://www.transfermarkt.com/panagiotis-deligiannidis/profil/spieler/234733.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-mitrea/profil/spieler/208866.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-vasvari/profil/spieler/177660.
Transfer history data appended for: https://www.transfermarkt.com/pavol-safranko/profil/spieler/366937.
Transfer history data appended for: https://www.transfermarkt.com/claudiu-petrila/profil/spieler/623424.
Transfer history data appended for: https://www.transfermarkt.com/roland-niczuly/profil/spieler/337619.

Transfer history data appended for: https://www.transfermarkt.com/adnan-aganovic/profil/spieler/50806.
Transfer history data appended for: https://www.transfermarkt.com/balazs-csiszer/profil/spieler/639141.
Transfer history data appended for: https://www.transfermarkt.com/anass-achahbar/profil/spieler/182554.
Transfer history data appended for: https://www.transfermarkt.com/lorand-fulop/profil/spieler/448674.
Transfer history data appended for: https://www.transfermarkt.com/jesus-fernandez/profil/spieler/91885.
Transfer history data appended for: https://www.transfermarkt.com/catalin-golofca/profil/spieler/241234.
Transfer history data appended for: https://www.transfermarkt.com/george-cimpanu/profil/spieler/687846.
Transfer history data appended for: https://www.transfermarkt.com/stephane-acka/profil/spieler/287203.
Transfer history data appended for: https://www.transfermarkt.com/reagy-ofosu/profil/spieler/83253.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-screciu/profil/spieler/418219.
Transfer history data appended for: https://www.transfermarkt.com/andrei-burlacu/profil/spieler/415457.
Transfer history data appended for: https://www.transfermarkt.com/paul-papp/profil/spieler/112552.
Transfer history data appended for: https://www.transfermarkt.com/mihai-capatina/profil/spieler/292201.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-mateiu/profil/spieler/64193.
Transfer history data appended for: https://www.transfermarkt.com/mihai-balasa/profil/spieler/236940.
Transfer history data appended for: https://www.transfermarkt.com/andrei-marinescu/profil/spieler/45052.
Transfer history data appended for: https://www.transfermarkt.com/ionut-mitran/profil/spieler/724575.
Transfer history data appended for: https://www.transfermarkt.com/laurentiu-popescu/profil/spieler/271289.
Transfer history data appended for: https://www.transfermarkt.com/dan-nistor/profil/spieler/156639.
Transfer history data appended for: https://www.transfermarkt.com/stefan-baiaram/profil/spieler/686232.
Transfer history data appended for: https://www.transfermarkt.com/vasile-constantin/profil/spieler/685203.
Transfer history data appended for: https://www.transfermarkt.com/cristi-barbut/profil/spieler/262108.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-cicald%C4%83u/profil/spieler/295810.
Transfer history data appended for: https://www.transfermarkt.com/stefan-vladoiu/profil/spieler/451603.
Transfer history data appended for: https://www.transfermarkt.com/antoni-ivanov/profil/spieler/283287.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-vatajelu/profil/spieler/213246.
Transfer history data appended for: https://www.transfermarkt.com/mirko-pigliacelli/profil/spieler/165893.
Transfer history data appended for: https://www.transfermarkt.com/ovidiu-bic/profil/spieler/220816.
Transfer history data appended for: https://www.transfermarkt.com/andrei-ivan/profil/spieler/271282.
Transfer history data appended for: https://www.transfermarkt.com/elvir-koljic/profil/spieler/296695.
Transfer history data appended for: https://www.transfermarkt.com/nicusor-bancu/profil/spieler/213195.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-tudorie/profil/spieler/260139.
Transfer history data appended for: https://www.transfermarkt.com/adrian-popa/profil/spieler/104062.
Transfer history data appended for: https://www.transfermarkt.com/ion-gheorghe/profil/spieler/436075.
Transfer history data appended for: https://www.transfermarkt.com/vasile-mihai/profil/spieler/349089.
Transfer history data appended for: https://www.transfermarkt.com/cosmin-achim/profil/spieler/312471.
Transfer history data appended for: https://www.transfermarkt.com/victor-rimniceanu/profil/spieler/213699.
Transfer history data appended for: https://www.transfermarkt.com/adelin-voinescu/profil/spieler/805627.
Transfer history data appended for: https://www.transfermarkt.com/marcos-lavin/profil/spieler/282409.
Transfer history data appended for: https://www.transfermarkt.com/george-buliga/profil/spieler/649787.
Transfer history data appended for: https://www.transfermarkt.com/razvan-gradinaru/profil/spieler/289256.
Transfer history data appended for: https://www.transfermarkt.com/mihai-cotolan/profil/spieler/436073.
Transfer history data appended for: https://www.transfermarkt.com/ricardinho/profil/spieler/337537.
Transfer history data appended for: https://www.transfermarkt.com/ionut-balaur/profil/spieler/64103.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-ionut-stoica/profil/spieler/568537.
Transfer history data appended for: https://www.transfermarkt.com/eric/profil/spieler/81509.
Transfer history data appended for: https://www.transfermarkt.com/cristian-costin/profil/spieler/397485.
Transfer history data appended for: https://www.transfermarkt.com/jefte-betancor/profil/spieler/198015.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-lopes/profil/spieler/279355.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-chilili/profil/spieler/575217.
Transfer history data appended for: https://www.transfermarkt.com/milan-kocic/profil/spieler/274828.
Transfer history data appended for: https://www.transfermarkt.com/gregoire-puel/profil/spieler/156487.
Transfer history data appended for: https://www.transfermarkt.com/pablo-de-lucas/profil/spieler/57851.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-ilie/profil/spieler/588433.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-mailat/profil/spieler/364697.
Transfer history data appended for: https://www.transfermarkt.com/anderson/profil/spieler/700073.
Transfer history data appended for: https://www.transfermarkt.com/cezar-trandafirescu/profil/spieler/436083.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-vlad/profil/spieler/204040.
Transfer history data appended for: https://www.transfermarkt.com/claudiu-bortoneanu/profil/spieler/474520.
Transfer history data appended for: https://www.transfermarkt.com/igor-armas/profil/spieler/64667.
Transfer history data appended for: https://www.transfermarkt.com/paul-pirvulescu/profil/spieler/81494.
Transfer history data appended for: https://www.transfermarkt.com/amir-bilali/profil/spieler/226181.
Transfer history data appended for: https://www.transfermarkt.com/lucian-dumitriu/profil/spieler/287418.
Transfer history data appended for: https://www.transfermarkt.com/andrei-cordea/profil/spieler/435712.
Transfer history data appended for: https://www.transfermarkt.com/petri%C8%99or-petrescu/profil/spieler/241343.
Transfer history data appended for: https://www.transfermarkt.com/andrei-ureche/profil/spieler/394535.
Transfer history data appended for: https://www.transfermarkt.com/bautista-cascini/profil/spieler/423439.
Transfer history data appended for: https://www.transfermarkt.com/razvan-dogaru/profil/spieler/511636.
Transfer history data appended for: https://www.transfermarkt.com/florin-gardos/profil/spieler/57423.
Transfer history data appended for: https://www.transfermarkt.com/asen-chandarov/profil/spieler/335740.
Transfer history data appended for: https://www.transfermarkt.com/jovan-markovi%C4%87/profil/spieler/418235.
Transfer history data appended for: https://www.transfermarkt.com/marian-serban/profil/spieler/535465.
Transfer history data appended for: https://www.transfermarkt.com/aleksandru-longher/profil/spieler/540921.
Transfer history data appended for: https://www.transfermarkt.com/ivan-marian/profil/spieler/655481.
Transfer history data appended for: https://www.transfermarkt.com/razvan-andronic/profil/spieler/568539.
Transfer history data appended for: https://www.transfermarkt.com/florinel-sandu/profil/spieler/804240.
Transfer history data appended for: https://www.transfermarkt.com/cristian-tanase/profil/spieler/46662.
Transfer history data appended for: https://www.transfermarkt.com/florin-achim/profil/spieler/212679.
Transfer history data appended for: https://www.transfermarkt.com/razvan-patriche/profil/spieler/64218.

Transfer history data appended for: https://www.transfermarkt.com/tsvetelin-chunchukov/profil/spieler/274666.
Transfer history data appended for: https://www.transfermarkt.com/ciprian-gliga/profil/spieler/534441.
Transfer history data appended for: https://www.transfermarkt.com/denis-ventura/profil/spieler/231722.
Transfer history data appended for: https://www.transfermarkt.com/eugeniu-cebotaru/profil/spieler/48820.
Transfer history data appended for: https://www.transfermarkt.com/marius-vanghele/profil/spieler/791473.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-boiciuc/profil/spieler/358734.
Transfer history data appended for: https://www.transfermarkt.com/octavian-valceanu/profil/spieler/252192.
Transfer history data appended for: https://www.transfermarkt.com/mihai-dobrescu/profil/spieler/236127.
Transfer history data appended for: https://www.transfermarkt.com/georgi-pashov/profil/spieler/87297.
Transfer history data appended for: https://www.transfermarkt.com/andrei-susu/profil/spieler/777431.
Transfer history data appended for: https://www.transfermarkt.com/mladen-jutric/profil/spieler/197052.
Transfer history data appended for: https://www.transfermarkt.com/david-meza-colli/profil/spieler/54328.
Transfer history data appended for: https://www.transfermarkt.com/george-micle/profil/spieler/723749.
Transfer history data appended for: https://www.transfermarkt.com/costinel-tofan/profil/spieler/394481.
Transfer history data appended for: https://www.transfermarkt.com/grigore-turda/profil/spieler/451328.
Transfer history data appended for: https://www.transfermarkt.com/andrei-panait/profil/spieler/81426.
Transfer history data appended for: https://www.transfermarkt.com/andrei-prepelita/profil/spieler/37933.
Transfer history data appended for: https://www.transfermarkt.com/flavius-croitoru/profil/spieler/209066.
Transfer history data appended for: https://www.transfermarkt.com/daniel-serbanica/profil/spieler/529149.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-greab/profil/spieler/186027.
Transfer history data appended for: https://www.transfermarkt.com/antun-palic/profil/spieler/68205.
Transfer history data appended for: https://www.transfermarkt.com/ionut-nastasie/profil/spieler/148000.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-matei/profil/spieler/131882.
Transfer history data appended for: https://www.transfermarkt.com/angelo-cocian/profil/spieler/478052.
Transfer history data appended for: https://www.transfermarkt.com/alexander-maes/profil/spieler/110796.
Transfer history data appended for: https://www.transfermarkt.com/sylvain-deslandes/profil/spieler/272621.
Transfer history data appended for: https://www.transfermarkt.com/ionut-serban/profil/spieler/212764.
Transfer history data appended for: https://www.transfermarkt.com/andrei-mirica/profil/spieler/710095.
Transfer history data appended for: https://www.transfermarkt.com/stephan-draghici/profil/spieler/435706.
Transfer history data appended for: https://www.transfermarkt.com/luka-maric/profil/spieler/190722.
Transfer history data appended for: https://www.transfermarkt.com/andrei-blejdea/profil/spieler/313631.
Transfer history data appended for: https://www.transfermarkt.com/mihai-leca/profil/spieler/234286.
Transfer history data appended for: https://www.transfermarkt.com/georgian-honciu/profil/spieler/212754.
Transfer history data appended for: https://www.transfermarkt.com/catalin-barbu/profil/spieler/476049.
Transfer history data appended for: https://www.transfermarkt.com/alin-popa/profil/spieler/209115.
Transfer history data appended for: https://www.transfermarkt.com/mediop-ndiaye/profil/spieler/515941.
Transfer history data appended for: https://www.transfermarkt.com/cephas-malele/profil/spieler/22686.
Transfer history data appended for: https://www.transfermarkt.com/sergio-marakis/profil/spieler/188669.
Transfer history data appended for: https://www.transfermarkt.com/clement-couturier/profil/spieler/467304.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-deac/profil/spieler/337737.
Transfer history data appended for: https://www.transfermarkt.com/paul-iacob/profil/spieler/303359.
Transfer history data appended for: https://www.transfermarkt.com/andrei-serban/profil/spieler/289290.
Transfer history data appended for: https://www.transfermarkt.com/tiberiu-capusa/profil/spieler/340978.
Transfer history data appended for: https://www.transfermarkt.com/marco-dulca/profil/spieler/391445.
Transfer history data appended for: https://www.transfermarkt.com/blaise-yameogo/profil/spieler/576738.
Transfer history data appended for: https://www.transfermarkt.com/denis-dumitrascu/profil/spieler/274671.
Transfer history data appended for: https://www.transfermarkt.com/valmir-berisha/profil/spieler/226146.
Transfer history data appended for: https://www.transfermarkt.com/cornel-dinu/profil/spieler/212749.
Transfer history data appended for: https://www.transfermarkt.com/vadim-rata/profil/spieler/136128.
Transfer history data appended for: https://www.transfermarkt.com/alex-negrea/profil/spieler/303318.
Transfer history data appended for: https://www.transfermarkt.com/daniel-popa/profil/spieler/341364.
Transfer history data appended for: https://www.transfermarkt.com/bourama-fomba/profil/spieler/780352.
Transfer history data appended for: https://www.transfermarkt.com/rares-pop/profil/spieler/435730.
Transfer history data appended for: https://www.transfermarkt.com/tomas-diaz/profil/spieler/741999.
Transfer history data appended for: https://www.transfermarkt.com/laurentiu-corbu/profil/spieler/378746.
Transfer history data appended for: https://www.transfermarkt.com/cristian-negut/profil/spieler/430836.
Transfer history data appended for: https://www.transfermarkt.com/dinu-moldovan/profil/spieler/129501.
Transfer history data appended for: https://www.transfermarkt.com/cristian-cherchez/profil/spieler/212748.
Transfer history data appended for: https://www.transfermarkt.com/mihai-neicutescu/profil/spieler/436079.
Transfer history data appended for: https://www.transfermarkt.com/mihai-aioani/profil/spieler/426724.
Transfer history data appended for: https://www.transfermarkt.com/marius-martac/profil/spieler/241296.
Transfer history data appended for: https://www.transfermarkt.com/mihai-costea/profil/spieler/47572.
Transfer history data appended for: https://www.transfermarkt.com/daniel-florea/profil/spieler/46543.
Transfer history data appended for: https://www.transfermarkt.com/andrei-pitian/profil/spieler/301258.
Transfer history data appended for: https://www.transfermarkt.com/ante-puljic/profil/spieler/47459.
Transfer history data appended for: https://www.transfermarkt.com/aleix-garcia/profil/spieler/261504.
Transfer history data appended for: https://www.transfermarkt.com/radu-zamfir/profil/spieler/540849.
Transfer history data appended for: https://www.transfermarkt.com/alin-lazar/profil/spieler/540893.
Transfer history data appended for: https://www.transfermarkt.com/andrei-radu/profil/spieler/243293.
Transfer history data appended for: https://www.transfermarkt.com/ionut-serban/profil/spieler/217891.
Transfer history data appended for: https://www.transfermarkt.com/tomas-mejias/profil/spieler/62947.
Transfer history data appended for: https://www.transfermarkt.com/adam-nemec/profil/spieler/55210.
Transfer history data appended for: https://www.transfermarkt.com/isma-lopez/profil/spieler/54231.
Transfer history data appended for: https://www.transfermarkt.com/marco-ehmann/profil/spieler/336310.
Transfer history data appended for: https://www.transfermarkt.com/robert-moldoveanu/profil/spieler/319235.
Transfer history data appended for: https://www.transfermarkt.com/magaye-gueye/profil/spieler/91956.
Transfer history data appended for: https://www.transfermarkt.com/borja-valle/profil/spieler/176067.
Transfer history data appended for: https://www.transfermarkt.com/alexander-gonzalez/profil/spieler/147562.
Transfer history data appended for: https://www.transfermarkt.com/deian-sorescu/profil/spieler/379209.
Transfer history data appended for: https://www.transfermarkt.com/andrei-sin/profil/spieler/213777.

Transfer history data appended for: https://www.transfermarkt.com/rene-hinojo/profil/spieler/64350.
Transfer history data appended for: https://www.transfermarkt.com/juan-camara/profil/spieler/162039.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-ba/profil/spieler/106837.
Transfer history data appended for: https://www.transfermarkt.com/mihai-esanu/profil/spieler/436072.
Transfer history data appended for: https://www.transfermarkt.com/catalin-magureanu/profil/spieler/491962.
Transfer history data appended for: https://www.transfermarkt.com/ionut-amzar/profil/spieler/672896.
Transfer history data appended for: https://www.transfermarkt.com/janusz-gol/profil/spieler/80941.
Transfer history data appended for: https://www.transfermarkt.com/geani-cretu/profil/spieler/540920.
Transfer history data appended for: https://www.transfermarkt.com/andreas-mihaiu/profil/spieler/436080.
Transfer history data appended for: https://www.transfermarkt.com/andrei-bani/profil/spieler/491956.
Transfer history data appended for: https://www.transfermarkt.com/ioan-borcea/profil/spieler/608464.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-rauta/profil/spieler/209117.
Transfer history data appended for: https://www.transfermarkt.com/levent-oltay/profil/spieler/540843.
Transfer history data appended for: https://www.transfermarkt.com/vlad-achim/profil/spieler/69402.
Transfer history data appended for: https://www.transfermarkt.com/florin-bejan/profil/spieler/147993.
Transfer history data appended for: https://www.transfermarkt.com/claudiu-stan/profil/spieler/540892.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-grigore/profil/spieler/436078.
Transfer history data appended for: https://www.transfermarkt.com/aleksander-mitrovic/profil/spieler/608470.
Transfer history data appended for: https://www.transfermarkt.com/francisco-junior/profil/spieler/215840.
Transfer history data appended for: https://www.transfermarkt.com/idrisa-sambu/profil/spieler/290761.
Transfer history data appended for: https://www.transfermarkt.com/razvan-horj/profil/spieler/422587.
Transfer history data appended for: https://www.transfermarkt.com/ionut-larie/profil/spieler/46582.
Transfer history data appended for: https://www.transfermarkt.com/nicolao-dumitru/profil/spieler/87052.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-jica/profil/spieler/675045.
Transfer history data appended for: https://www.transfermarkt.com/nasser-chamed/profil/spieler/234766.
Transfer history data appended for: https://www.transfermarkt.com/razvan-trif/profil/spieler/395799.
Transfer history data appended for: https://www.transfermarkt.com/luis-nitu/profil/spieler/575181.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-plumbuitu/profil/spieler/666433.
Transfer history data appended for: https://www.transfermarkt.com/paul-costea/profil/spieler/599465.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-birsan/profil/spieler/805628.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-baco/profil/spieler/431058.
Transfer history data appended for: https://www.transfermarkt.com/yuri-matias/profil/spieler/443612.
Transfer history data appended for: https://www.transfermarkt.com/mihai-velisar/profil/spieler/610483.
Transfer history data appended for: https://www.transfermarkt.com/daniel-nicula/profil/spieler/787715.
Transfer history data appended for: https://www.transfermarkt.com/ovidiu-horsia/profil/spieler/418223.
Transfer history data appended for: https://www.transfermarkt.com/mihai-butean/profil/spieler/375712.
Transfer history data appended for: https://www.transfermarkt.com/albert-popa/profil/spieler/494593.
Transfer history data appended for: https://www.transfermarkt.com/andrei-cristea/profil/spieler/464239.
Transfer history data appended for: https://www.transfermarkt.com/sergiu-ciocan/profil/spieler/687721.
Transfer history data appended for: https://www.transfermarkt.com/ze-manuel/profil/spieler/113025.
Transfer history data appended for: https://www.transfermarkt.com/moussa-sanoh/profil/spieler/203928.
Transfer history data appended for: https://www.transfermarkt.com/tomas-smola/profil/spieler/255413.
Transfer history data appended for: https://www.transfermarkt.com/bryan-alceus/profil/spieler/354686.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-buzbuchi/profil/spieler/216660.
Transfer history data appended for: https://www.transfermarkt.com/andrei-capra/profil/spieler/805629.
Transfer history data appended for: https://www.transfermarkt.com/yves-simon-pambou/profil/spieler/291746.
Transfer history data appended for: https://www.transfermarkt.com/rares-dogaru/profil/spieler/790986.
Transfer history data appended for: https://www.transfermarkt.com/roberto-romeo/profil/spieler/153206.
Transfer history data appended for: https://www.transfermarkt.com/eduard-avram/profil/spieler/666464.
Transfer history data appended for: https://www.transfermarkt.com/lukas-droppa/profil/spieler/81959.
Transfer history data appended for: https://www.transfermarkt.com/razvan-plesca/profil/spieler/25940.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-valente/profil/spieler/292775.
Transfer history data appended for: https://www.transfermarkt.com/gabriel/profil/spieler/210088.
Transfer history data appended for: https://www.transfermarkt.com/ronaldo-deaconu/profil/spieler/271281.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-voda/profil/spieler/528694.
Transfer history data appended for: https://www.transfermarkt.com/david-mayoral/profil/spieler/355629.
Transfer history data appended for: https://www.transfermarkt.com/kevin-rimane/profil/spieler/93751.
Transfer history data appended for: https://www.transfermarkt.com/stanley-elbers/profil/spieler/188905.
Transfer history data appended for: https://www.transfermarkt.com/soni-mustivar/profil/spieler/85195.
Transfer history data appended for: https://www.transfermarkt.com/lucian-buzan/profil/spieler/540113.
Transfer history data appended for: https://www.transfermarkt.com/baba-alhassan/profil/spieler/626899.
Transfer history data appended for: https://www.transfermarkt.com/adrian-scarlatache/profil/spieler/46644.
Transfer history data appended for: https://www.transfermarkt.com/goran-karanovic/profil/spieler/33337.
Transfer history data appended for: https://www.transfermarkt.com/andrei-campean/profil/spieler/524156.
Transfer history data appended for: https://www.transfermarkt.com/raul-oprut/profil/spieler/393806.
Transfer history data appended for: https://www.transfermarkt.com/cristiano-figueiredo/profil/spieler/100127.
Transfer history data appended for: https://www.transfermarkt.com/jo-santos/profil/spieler/237058.
Transfer history data appended for: https://www.transfermarkt.com/fabio-fortes/profil/spieler/190920.
Transfer history data appended for: https://www.transfermarkt.com/angel-bastos/profil/spieler/337758.
Transfer history data appended for: https://www.transfermarkt.com/bright-addae/profil/spieler/128036.
Transfer history data appended for: https://www.transfermarkt.com/claudiu-belu-iordache/profil/spieler/208716.
Transfer history data appended for: https://www.transfermarkt.com/david-caiado/profil/spieler/37414.
Transfer history data appended for: https://www.transfermarkt.com/ionut-pop/profil/spieler/21517.
Transfer history data appended for: https://www.transfermarkt.com/romario-pires/profil/spieler/148601.
Transfer history data appended for: https://www.transfermarkt.com/adrian-ster/profil/spieler/395817.
Transfer history data appended for: https://www.transfermarkt.com/edson-pires/profil/spieler/626337.
Transfer history data appended for: https://www.transfermarkt.com/andrei-sintean/profil/spieler/319229.
Transfer history data appended for: https://www.transfermarkt.com/ousmane-viera/profil/spieler/69014.
Transfer history data appended for: https://www.transfermarkt.com/razvan-dalbea/profil/spieler/123263.
Transfer history data appended for: https://www.transfermarkt.com/ionut-stoica/profil/spieler/241584.

Transfer history data appended for: https://www.transfermarkt.com/luca-florica/profil/spieler/568573.
Transfer history data appended for: https://www.transfermarkt.com/catalin-straton/profil/spieler/123251.
Transfer history data appended for: https://www.transfermarkt.com/darius-olaru/profil/spieler/395800.
Transfer history data appended for: https://www.transfermarkt.com/stefan-cana/profil/spieler/568543.
Transfer history data appended for: https://www.transfermarkt.com/adrian-sut/profil/spieler/433979.
Transfer history data appended for: https://www.transfermarkt.com/ionut-vina/profil/spieler/208828.
Transfer history data appended for: https://www.transfermarkt.com/ionut-pantiru/profil/spieler/481484.
Transfer history data appended for: https://www.transfermarkt.com/lucian-filip/profil/spieler/60880.
Transfer history data appended for: https://www.transfermarkt.com/aristidis-soiledis/profil/spieler/63490.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-simion/profil/spieler/447557.
Transfer history data appended for: https://www.transfermarkt.com/ovidiu-popescu/profil/spieler/289017.
Transfer history data appended for: https://www.transfermarkt.com/florin-tanase/profil/spieler/314329.
Transfer history data appended for: https://www.transfermarkt.com/sergiu-bus/profil/spieler/123671.
Transfer history data appended for: https://www.transfermarkt.com/olimpiu-morutan/profil/spieler/429551.
Transfer history data appended for: https://www.transfermarkt.com/razvan-oaida/profil/spieler/341141.
Transfer history data appended for: https://www.transfermarkt.com/cristian-dumitru/profil/spieler/599600.
Transfer history data appended for: https://www.transfermarkt.com/christian-tand/profil/spieler/614798.
Transfer history data appended for: https://www.transfermarkt.com/dennis-man/profil/spieler/397486.
Transfer history data appended for: https://www.transfermarkt.com/mihai-udrea/profil/spieler/786187.
Transfer history data appended for: https://www.transfermarkt.com/ovidiu-perianu/profil/spieler/623425.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-buziuc/profil/spieler/269786.
Transfer history data appended for: https://www.transfermarkt.com/marius-briceag/profil/spieler/209063.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-enache/profil/spieler/197652.
Transfer history data appended for: https://www.transfermarkt.com/valentin-cretu/profil/spieler/79507.
Transfer history data appended for: https://www.transfermarkt.com/florinel-coman/profil/spieler/340982.
Transfer history data appended for: https://www.transfermarkt.com/dragos-nedelcu/profil/spieler/295868.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-stan/profil/spieler/97517.
Transfer history data appended for: https://www.transfermarkt.com/octavian-popescu/profil/spieler/797100.
Transfer history data appended for: https://www.transfermarkt.com/george-miron/profil/spieler/332205.
Transfer history data appended for: https://www.transfermarkt.com/robert-ion/profil/spieler/608511.
Transfer history data appended for: https://www.transfermarkt.com/andrei-vlad/profil/spieler/424302.
Transfer history data appended for: https://www.transfermarkt.com/iulian-cristea/profil/spieler/331971.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-pantea/profil/spieler/670828.
Transfer history data appended for: https://www.transfermarkt.com/pil-su-choi/profil/spieler/319922.
Transfer history data appended for: https://www.transfermarkt.com/dong-woo-kim/profil/spieler/156007.
Transfer history data appended for: https://www.transfermarkt.com/myeong-jun-kim/profil/spieler/574285.
Transfer history data appended for: https://www.transfermarkt.com/seung-jun-kim/profil/spieler/261397.
Transfer history data appended for: https://www.transfermarkt.com/jeong-ho-kim/profil/spieler/523917.
Transfer history data appended for: https://www.transfermarkt.com/ho-yeong-seong/profil/spieler/676358.
Transfer history data appended for: https://www.transfermarkt.com/seok-yeong-yun/profil/spieler/126643.
Transfer history data appended for: https://www.transfermarkt.com/dong-jun-lee/profil/spieler/269601.
Transfer history data appended for: https://www.transfermarkt.com/ho-jeong-jeong/profil/spieler/151792.
Transfer history data appended for: https://www.transfermarkt.com/hyun-kim/profil/spieler/217564.
Transfer history data appended for: https://www.transfermarkt.com/hyeok-kyu-kwon/profil/spieler/550957.
Transfer history data appended for: https://www.transfermarkt.com/jeong-hyeop-lee/profil/spieler/260193.
Transfer history data appended for: https://www.transfermarkt.com/ho-yeong-park/profil/spieler/558533.
Transfer history data appended for: https://www.transfermarkt.com/romulo/profil/spieler/345544.
Transfer history data appended for: https://www.transfermarkt.com/kyu-seong-lee/profil/spieler/389181.
Transfer history data appended for: https://www.transfermarkt.com/guan-woo-park/profil/spieler/576363.
Transfer history data appended for: https://www.transfermarkt.com/jun-kang-park/profil/spieler/263529.
Transfer history data appended for: https://www.transfermarkt.com/jin-gi-hong/profil/spieler/217636.
Transfer history data appended for: https://www.transfermarkt.com/jun-ho-hwang/profil/spieler/652536.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-vintecinco/profil/spieler/552731.
Transfer history data appended for: https://www.transfermarkt.com/jin-kyu-kim/profil/spieler/365377.
Transfer history data appended for: https://www.transfermarkt.com/ji-seung-lee/profil/spieler/657035.
Transfer history data appended for: https://www.transfermarkt.com/jung-hyun-kim/profil/spieler/216701.
Transfer history data appended for: https://www.transfermarkt.com/ho-jun-kim/profil/spieler/90719.
Transfer history data appended for: https://www.transfermarkt.com/kyeong-min-park/profil/spieler/550926.
Transfer history data appended for: https://www.transfermarkt.com/mun-hwan-kim/profil/spieler/524592.
Transfer history data appended for: https://www.transfermarkt.com/ji-min-lee/profil/spieler/379437.
Transfer history data appended for: https://www.transfermarkt.com/seong-min-jeong/profil/spieler/189061.
Transfer history data appended for: https://www.transfermarkt.com/min-soo-kang/profil/spieler/81791.
Transfer history data appended for: https://www.transfermarkt.com/sang-jun-lee/profil/spieler/550988.
Transfer history data appended for: https://www.transfermarkt.com/rae-jun-lee/profil/spieler/420644.
Transfer history data appended for: https://www.transfermarkt.com/byong-oh-kim/profil/spieler/263825.
Transfer history data appended for: https://www.transfermarkt.com/jong-woo-park/profil/spieler/180776.
Transfer history data appended for: https://www.transfermarkt.com/dostonbek-tursunov/profil/spieler/375959.
Transfer history data appended for: https://www.transfermarkt.com/sung-yun-kwon/profil/spieler/568661.
Transfer history data appended for: https://www.transfermarkt.com/jin-sung-kim/profil/spieler/732697.
Transfer history data appended for: https://www.transfermarkt.com/hyeon-cheol-jeong/profil/spieler/261393.
Transfer history data appended for: https://www.transfermarkt.com/sung-yueng-ki/profil/spieler/81796.
Transfer history data appended for: https://www.transfermarkt.com/han-been-yang/profil/spieler/156442.
Transfer history data appended for: https://www.transfermarkt.com/in-gyu-lee/profil/spieler/568657.
Transfer history data appended for: https://www.transfermarkt.com/yo-han-go/profil/spieler/135850.
Transfer history data appended for: https://www.transfermarkt.com/hyun-soo-hwang/profil/spieler/314242.
Transfer history data appended for: https://www.transfermarkt.com/min-gyu-oh/profil/spieler/740765.
Transfer history data appended for: https://www.transfermarkt.com/seok-yeong-cho/profil/spieler/732698.
Transfer history data appended for: https://www.transfermarkt.com/sang-hee-kang/profil/spieler/676391.
Transfer history data appended for: https://www.transfermarkt.com/se-jong-ju/profil/spieler/217345.
Transfer history data appended for: https://www.transfermarkt.com/young-wook-cho/profil/spieler/297720.

Transfer history data appended for: https://www.transfermarkt.com/won-kyun-kim/profil/spieler/379064.
Transfer history data appended for: https://www.transfermarkt.com/adriano/profil/spieler/147841.
Transfer history data appended for: https://www.transfermarkt.com/won-sik-kim/profil/spieler/217612.
Transfer history data appended for: https://www.transfermarkt.com/han-min-jung/profil/spieler/568659.
Transfer history data appended for: https://www.transfermarkt.com/jin-wook-jeong/profil/spieler/573824.
Transfer history data appended for: https://www.transfermarkt.com/jong-gyu-yoon/profil/spieler/402163.
Transfer history data appended for: https://www.transfermarkt.com/yu-min-yang/profil/spieler/568632.
Transfer history data appended for: https://www.transfermarkt.com/jong-beom-baek/profil/spieler/568644.
Transfer history data appended for: https://www.transfermarkt.com/osmar/profil/spieler/89370.
Transfer history data appended for: https://www.transfermarkt.com/kwang-min-ko/profil/spieler/201381.
Transfer history data appended for: https://www.transfermarkt.com/chan-hee-han/profil/spieler/427550.
Transfer history data appended for: https://www.transfermarkt.com/jin-ya-kim/profil/spieler/402160.
Transfer history data appended for: https://www.transfermarkt.com/jin-hyung-song/profil/spieler/69961.
Transfer history data appended for: https://www.transfermarkt.com/min-su-kim/profil/spieler/732699.
Transfer history data appended for: https://www.transfermarkt.com/sang-hun-yu/profil/spieler/189042.
Transfer history data appended for: https://www.transfermarkt.com/ju-sung-kim/profil/spieler/568633.
Transfer history data appended for: https://www.transfermarkt.com/seung-jae-lee/profil/spieler/641352.
Transfer history data appended for: https://www.transfermarkt.com/seung-gyu-han/profil/spieler/486598.
Transfer history data appended for: https://www.transfermarkt.com/young-sun-yun/profil/spieler/151807.
Transfer history data appended for: https://www.transfermarkt.com/ikromzhon-alibaev/profil/spieler/311898.
Transfer history data appended for: https://www.transfermarkt.com/ju-tae-yun/profil/spieler/179047.
Transfer history data appended for: https://www.transfermarkt.com/oh-yeon-cha/profil/spieler/402156.
Transfer history data appended for: https://www.transfermarkt.com/kyung-won-kwon/profil/spieler/260189.
Transfer history data appended for: https://www.transfermarkt.com/dong-min-kim/profil/spieler/510242.
Transfer history data appended for: https://www.transfermarkt.com/myung-jae-lee/profil/spieler/314773.
Transfer history data appended for: https://www.transfermarkt.com/hyeon-gyu-oh/profil/spieler/639246.
Transfer history data appended for: https://www.transfermarkt.com/won-jin-jung/profil/spieler/420640.
Transfer history data appended for: https://www.transfermarkt.com/byung-hyun-park/profil/spieler/552540.
Transfer history data appended for: https://www.transfermarkt.com/jeong-bin-lee/profil/spieler/342146.
Transfer history data appended for: https://www.transfermarkt.com/dong-su-lee/profil/spieler/497374.
Transfer history data appended for: https://www.transfermarkt.com/dong-jin-park/profil/spieler/428649.
Transfer history data appended for: https://www.transfermarkt.com/tae-hyun-an/profil/spieler/530447.
Transfer history data appended for: https://www.transfermarkt.com/jae-hee-jeong/profil/spieler/530750.
Transfer history data appended for: https://www.transfermarkt.com/chang-geun-lee/profil/spieler/132532.
Transfer history data appended for: https://www.transfermarkt.com/myeong-seok-ko/profil/spieler/342134.
Transfer history data appended for: https://www.transfermarkt.com/sang-ki-lee/profil/spieler/507608.
Transfer history data appended for: https://www.transfermarkt.com/keun-ho-lee/profil/spieler/292261.
Transfer history data appended for: https://www.transfermarkt.com/se-hun-oh/profil/spieler/402167.
Transfer history data appended for: https://www.transfermarkt.com/chang-jin-moon/profil/spieler/217571.
Transfer history data appended for: https://www.transfermarkt.com/bo-seob-kim/profil/spieler/520818.
Transfer history data appended for: https://www.transfermarkt.com/ju-seong-woo/profil/spieler/261413.
Transfer history data appended for: https://www.transfermarkt.com/yong-hwan-kim/profil/spieler/274826.
Transfer history data appended for: https://www.transfermarkt.com/seon-min-moon/profil/spieler/225342.
Transfer history data appended for: https://www.transfermarkt.com/ji-min-park/profil/spieler/581990.
Transfer history data appended for: https://www.transfermarkt.com/sang-min-sim/profil/spieler/261407.
Transfer history data appended for: https://www.transfermarkt.com/yong-woo-park/profil/spieler/374076.
Transfer history data appended for: https://www.transfermarkt.com/yong-jun-heo/profil/spieler/261392.
Transfer history data appended for: https://www.transfermarkt.com/se-jin-jeon/profil/spieler/560797.
Transfer history data appended for: https://www.transfermarkt.com/ji-hun-kang/profil/spieler/558683.
Transfer history data appended for: https://www.transfermarkt.com/cheol-won-choi/profil/spieler/530057.
Transfer history data appended for: https://www.transfermarkt.com/bjorn-johnsen/profil/spieler/250686.
Transfer history data appended for: https://www.transfermarkt.com/jason-davidson/profil/spieler/137669.
Transfer history data appended for: https://www.transfermarkt.com/du-jae-won/profil/spieler/429696.
Transfer history data appended for: https://www.transfermarkt.com/sang-heon-lee/profil/spieler/402151.
Transfer history data appended for: https://www.transfermarkt.com/min-duk-kim/profil/spieler/652527.
Transfer history data appended for: https://www.transfermarkt.com/ha-bean-park/profil/spieler/652526.
Transfer history data appended for: https://www.transfermarkt.com/jae-won-jang/profil/spieler/402147.
Transfer history data appended for: https://www.transfermarkt.com/jeung-in-park/profil/spieler/645850.
Transfer history data appended for: https://www.transfermarkt.com/hoon-sung-jeong/profil/spieler/284105.
Transfer history data appended for: https://www.transfermarkt.com/su-hyeok-jo/profil/spieler/155998.
Transfer history data appended for: https://www.transfermarkt.com/keun-ho-lee/profil/spieler/81802.
Transfer history data appended for: https://www.transfermarkt.com/hyeong-kyeong-lee/profil/spieler/676396.
Transfer history data appended for: https://www.transfermarkt.com/dong-hwan-min/profil/spieler/639119.
Transfer history data appended for: https://www.transfermarkt.com/sung-joon-kim/profil/spieler/174572.
Transfer history data appended for: https://www.transfermarkt.com/dong-ho-jeong/profil/spieler/110871.
Transfer history data appended for: https://www.transfermarkt.com/jin-ho-shin/profil/spieler/180560.
Transfer history data appended for: https://www.transfermarkt.com/dave-bulthuis/profil/spieler/187098.
Transfer history data appended for: https://www.transfermarkt.com/hyun-taek-cho/profil/spieler/677469.
Transfer history data appended for: https://www.transfermarkt.com/hyeon-seung-lee/profil/spieler/695128.
Transfer history data appended for: https://www.transfermarkt.com/seung-hyun-jung/profil/spieler/379438.
Transfer history data appended for: https://www.transfermarkt.com/kee-hee-kim/profil/spieler/180579.
Transfer history data appended for: https://www.transfermarkt.com/ju-hwan-seo/profil/spieler/715720.
Transfer history data appended for: https://www.transfermarkt.com/hyun-woo-jo/profil/spieler/260171.
Transfer history data appended for: https://www.transfermarkt.com/tae-hwan-kim/profil/spieler/156009.
Transfer history data appended for: https://www.transfermarkt.com/jae-uh-bae/profil/spieler/427057.
Transfer history data appended for: https://www.transfermarkt.com/myong-jin-ko/profil/spieler/90720.
Transfer history data appended for: https://www.transfermarkt.com/junior-negrao/profil/spieler/52790.
Transfer history data appended for: https://www.transfermarkt.com/ju-ho-park/profil/spieler/111900.
Transfer history data appended for: https://www.transfermarkt.com/gi-un-lee/profil/spieler/721726.
Transfer history data appended for: https://www.transfermarkt.com/dong-kyeong-lee/profil/spieler/558086.
Transfer history data appended for: https://www.transfermarkt.com/chul-hong/profil/spieler/151791.

Transfer history data appended for: https://www.transfermarkt.com/min-jun-kim/profil/spieler/676363.
Transfer history data appended for: https://www.transfermarkt.com/chung-yong-lee/profil/spieler/81801.
Transfer history data appended for: https://www.transfermarkt.com/bit-garam-yoon/profil/spieler/163990.
Transfer history data appended for: https://www.transfermarkt.com/in-seong-kim/profil/spieler/214534.
Transfer history data appended for: https://www.transfermarkt.com/young-woo-seol/profil/spieler/639414.
Transfer history data appended for: https://www.transfermarkt.com/jung-soo-park/profil/spieler/156997.
Transfer history data appended for: https://www.transfermarkt.com/jun-hyeok-choi/profil/spieler/558353.
Transfer history data appended for: https://www.transfermarkt.com/jun-hui-park/profil/spieler/312439.
Transfer history data appended for: https://www.transfermarkt.com/min-ki-lee/profil/spieler/428652.
Transfer history data appended for: https://www.transfermarkt.com/felipe-silva/profil/spieler/592377.
Transfer history data appended for: https://www.transfermarkt.com/reum-yeo/profil/spieler/379410.
Transfer history data appended for: https://www.transfermarkt.com/jun-yeon-jeong/profil/spieler/91158.
Transfer history data appended for: https://www.transfermarkt.com/willyan/profil/spieler/198974.
Transfer history data appended for: https://www.transfermarkt.com/jun-ho-hong/profil/spieler/428658.
Transfer history data appended for: https://www.transfermarkt.com/do-won-baek/profil/spieler/742197.
Transfer history data appended for: https://www.transfermarkt.com/rustamzhon-ashurmatov/profil/spieler/288883.
Transfer history data appended for: https://www.transfermarkt.com/yool-heo/profil/spieler/677470.
Transfer history data appended for: https://www.transfermarkt.com/tae-gon-kim/profil/spieler/642003.
Transfer history data appended for: https://www.transfermarkt.com/min-hyeok-im/profil/spieler/426923.
Transfer history data appended for: https://www.transfermarkt.com/jeong-hwan-kim/profil/spieler/426922.
Transfer history data appended for: https://www.transfermarkt.com/yong-su-han/profil/spieler/217550.
Transfer history data appended for: https://www.transfermarkt.com/bong-hun-yeo/profil/spieler/386501.
Transfer history data appended for: https://www.transfermarkt.com/jin-hyeong-lee/profil/spieler/173262.
Transfer history data appended for: https://www.transfermarkt.com/hyo-gi-kim/profil/spieler/217454.
Transfer history data appended for: https://www.transfermarkt.com/ju-kong-kim/profil/spieler/655770.
Transfer history data appended for: https://www.transfermarkt.com/hyeon-seok-doo/profil/spieler/574188.
Transfer history data appended for: https://www.transfermarkt.com/won-sang-eom/profil/spieler/630269.
Transfer history data appended for: https://www.transfermarkt.com/han-do-lee/profil/spieler/426124.
Transfer history data appended for: https://www.transfermarkt.com/heui-kyun-lee/profil/spieler/642004.
Transfer history data appended for: https://www.transfermarkt.com/hyeon-uh-jeong/profil/spieler/642005.
Transfer history data appended for: https://www.transfermarkt.com/chang-soo-kim/profil/spieler/81792.
Transfer history data appended for: https://www.transfermarkt.com/pyeong-guk-yun/profil/spieler/260207.
Transfer history data appended for: https://www.transfermarkt.com/marcos-urena/profil/spieler/118074.
Transfer history data appended for: https://www.transfermarkt.com/eu-ddeum-lee/profil/spieler/263837.
Transfer history data appended for: https://www.transfermarkt.com/hee-hoon-han/profil/spieler/288561.
Transfer history data appended for: https://www.transfermarkt.com/jin-hyun-kim/profil/spieler/678642.
Transfer history data appended for: https://www.transfermarkt.com/soon-min-lee/profil/spieler/508376.
Transfer history data appended for: https://www.transfermarkt.com/tae-yun-kim/profil/spieler/134670.
Transfer history data appended for: https://www.transfermarkt.com/jin-hyun-lee/profil/spieler/132748.
Transfer history data appended for: https://www.transfermarkt.com/dae-won-kim/profil/spieler/497439.
Transfer history data appended for: https://www.transfermarkt.com/han-bin-park/profil/spieler/200650.
Transfer history data appended for: https://www.transfermarkt.com/jin-hyuk-kim/profil/spieler/497422.
Transfer history data appended for: https://www.transfermarkt.com/min-seo-park/profil/spieler/654693.
Transfer history data appended for: https://www.transfermarkt.com/tsubasa-nishi/profil/spieler/299492.
Transfer history data appended for: https://www.transfermarkt.com/jin-yong-lee/profil/spieler/639120.
Transfer history data appended for: https://www.transfermarkt.com/jae-kyeong-park/profil/spieler/654647.
Transfer history data appended for: https://www.transfermarkt.com/yeong-eun-choi/profil/spieler/570659.
Transfer history data appended for: https://www.transfermarkt.com/jong-tae-yoon/profil/spieler/688794.
Transfer history data appended for: https://www.transfermarkt.com/tae-uk-jeong/profil/spieler/429677.
Transfer history data appended for: https://www.transfermarkt.com/tae-kyu-ko/profil/spieler/654683.
Transfer history data appended for: https://www.transfermarkt.com/dong-jin-kim/profil/spieler/132527.
Transfer history data appended for: https://www.transfermarkt.com/seong-won-jang/profil/spieler/606411.
Transfer history data appended for: https://www.transfermarkt.com/woo-seok-kim/profil/spieler/497421.
Transfer history data appended for: https://www.transfermarkt.com/jin-woo-jo/profil/spieler/558437.
Transfer history data appended for: https://www.transfermarkt.com/edgar-silva/profil/spieler/45673.
Transfer history data appended for: https://www.transfermarkt.com/chan-woong-lee/profil/spieler/734400.
Transfer history data appended for: https://www.transfermarkt.com/hak-yun-lee/profil/spieler/645157.
Transfer history data appended for: https://www.transfermarkt.com/chang-mu-shin/profil/spieler/319282.
Transfer history data appended for: https://www.transfermarkt.com/chang-min-ahn/profil/spieler/734397.
Transfer history data appended for: https://www.transfermarkt.com/tae-hyeon-hwang/profil/spieler/297701.
Transfer history data appended for: https://www.transfermarkt.com/jun-heui-lee/profil/spieler/521416.
Transfer history data appended for: https://www.transfermarkt.com/seung-won-jeong/profil/spieler/497440.
Transfer history data appended for: https://www.transfermarkt.com/jae-mun-ryu/profil/spieler/261405.
Transfer history data appended for: https://www.transfermarkt.com/cesinha/profil/spieler/226382.
Transfer history data appended for: https://www.transfermarkt.com/dong-geon-lee/profil/spieler/578399.
Transfer history data appended for: https://www.transfermarkt.com/seon-min-kim/profil/spieler/176985.
Transfer history data appended for: https://www.transfermarkt.com/chi-in-jeong/profil/spieler/429695.
Transfer history data appended for: https://www.transfermarkt.com/jae-hyeok-im/profil/spieler/572170.
Transfer history data appended for: https://www.transfermarkt.com/jae-woo-kim/profil/spieler/458065.
Transfer history data appended for: https://www.transfermarkt.com/myeong-rae-ha/profil/spieler/671819.
Transfer history data appended for: https://www.transfermarkt.com/jeong-un-hong/profil/spieler/497413.
Transfer history data appended for: https://www.transfermarkt.com/hu-sung-oh/profil/spieler/637744.
Transfer history data appended for: https://www.transfermarkt.com/sung-yun-gu/profil/spieler/238030.
Transfer history data appended for: https://www.transfermarkt.com/soon-min-hwang/profil/spieler/198136.
Transfer history data appended for: https://www.transfermarkt.com/jung-shin/profil/spieler/734398.
Transfer history data appended for: https://www.transfermarkt.com/dejan-damjanovi%C4%87/profil/spieler/42434.
Transfer history data appended for: https://www.transfermarkt.com/tae-han-kim/profil/spieler/570660.
Transfer history data appended for: https://www.transfermarkt.com/keun-seob-lee/profil/spieler/734399.
Transfer history data appended for: https://www.transfermarkt.com/yeong-ung-jeong/profil/spieler/654687.
Transfer history data appended for: https://www.transfermarkt.com/jae-sung-lee/profil/spieler/114871.
Transfer history data appended for: https://www.transfermarkt.com/won-chang-choi/profil/spieler/544502.

Transfer history data appended for: https://www.transfermarkt.com/jun-ah-yang/profil/spieler/150174.
Transfer history data appended for: https://www.transfermarkt.com/jun-yub-kim/profil/spieler/173269.
Transfer history data appended for: https://www.transfermarkt.com/rashid-mahazi/profil/spieler/292764.
Transfer history data appended for: https://www.transfermarkt.com/ji-hwan-mun/profil/spieler/531038.
Transfer history data appended for: https://www.transfermarkt.com/ho-seok-lee/profil/spieler/316468.
Transfer history data appended for: https://www.transfermarkt.com/chang-yong-jung/profil/spieler/734639.
Transfer history data appended for: https://www.transfermarkt.com/ban-suk-oh/profil/spieler/221889.
Transfer history data appended for: https://www.transfermarkt.com/stefan-mugosa/profil/spieler/149738.
Transfer history data appended for: https://www.transfermarkt.com/san-jeong/profil/spieler/113541.
Transfer history data appended for: https://www.transfermarkt.com/jong-jin-kim/profil/spieler/644013.
Transfer history data appended for: https://www.transfermarkt.com/hwi-jin-ham/profil/spieler/525062.
Transfer history data appended for: https://www.transfermarkt.com/min-seok-kim/profil/spieler/721596.
Transfer history data appended for: https://www.transfermarkt.com/joon-suk-lee/profil/spieler/545492.
Transfer history data appended for: https://www.transfermarkt.com/yun-gu-gang/profil/spieler/555215.
Transfer history data appended for: https://www.transfermarkt.com/eun-su-im/profil/spieler/578779.
Transfer history data appended for: https://www.transfermarkt.com/beom-kyeong-choi/profil/spieler/588270.
Transfer history data appended for: https://www.transfermarkt.com/yeon-su-kim/profil/spieler/529694.
Transfer history data appended for: https://www.transfermarkt.com/sung-hyung-yoo/profil/spieler/740885.
Transfer history data appended for: https://www.transfermarkt.com/sang-hyeob-lee/profil/spieler/265277.
Transfer history data appended for: https://www.transfermarkt.com/geon-heui-pyo/profil/spieler/716470.
Transfer history data appended for: https://www.transfermarkt.com/jong-wook-lee/profil/spieler/701456.
Transfer history data appended for: https://www.transfermarkt.com/jun-beom-kim/profil/spieler/558542.
Transfer history data appended for: https://www.transfermarkt.com/je-ho-lee/profil/spieler/667295.
Transfer history data appended for: https://www.transfermarkt.com/do-hyeok-kim/profil/spieler/319363.
Transfer history data appended for: https://www.transfermarkt.com/uh-hyeok-lee/profil/spieler/190362.
Transfer history data appended for: https://www.transfermarkt.com/ho-nam-kim/profil/spieler/158040.
Transfer history data appended for: https://www.transfermarkt.com/elias-aguilar/profil/spieler/211491.
Transfer history data appended for: https://www.transfermarkt.com/shi-uh-song/profil/spieler/465808.
Transfer history data appended for: https://www.transfermarkt.com/dong-yun-jeong/profil/spieler/428654.
Transfer history data appended for: https://www.transfermarkt.com/dong-heon-kim/profil/spieler/652530.
Transfer history data appended for: https://www.transfermarkt.com/eon-hak-ji/profil/spieler/343735.
Transfer history data appended for: https://www.transfermarkt.com/dae-jung-kim/profil/spieler/379073.
Transfer history data appended for: https://www.transfermarkt.com/jeung-ho-kim/profil/spieler/585710.
Transfer history data appended for: https://www.transfermarkt.com/chae-un-kim/profil/spieler/545493.
Transfer history data appended for: https://www.transfermarkt.com/dae-han-park/profil/spieler/318740.
Transfer history data appended for: https://www.transfermarkt.com/seong-ju-kim/profil/spieler/211879.
Transfer history data appended for: https://www.transfermarkt.com/yu-seong-kim/profil/spieler/712232.
Transfer history data appended for: https://www.transfermarkt.com/jin-beom-an/profil/spieler/314854.
Transfer history data appended for: https://www.transfermarkt.com/tae-heui-lee/profil/spieler/292264.
Transfer history data appended for: https://www.transfermarkt.com/min-hyuk-kim/profil/spieler/357951.
Transfer history data appended for: https://www.transfermarkt.com/hee-won-choi/profil/spieler/630166.
Transfer history data appended for: https://www.transfermarkt.com/jong-hyeok-jeon/profil/spieler/574704.
Transfer history data appended for: https://www.transfermarkt.com/jamshid-iskandarov/profil/spieler/260857.
Transfer history data appended for: https://www.transfermarkt.com/chang-yong-lee/profil/spieler/282843.
Transfer history data appended for: https://www.transfermarkt.com/seung-min-jeon/profil/spieler/677330.
Transfer history data appended for: https://www.transfermarkt.com/igor-jovanovic/profil/spieler/50366.
Transfer history data appended for: https://www.transfermarkt.com/sun-young-lim/profil/spieler/180590.
Transfer history data appended for: https://www.transfermarkt.com/seung-kyeom-im/profil/spieler/292265.
Transfer history data appended for: https://www.transfermarkt.com/bo-min-seo/profil/spieler/318760.
Transfer history data appended for: https://www.transfermarkt.com/soon-hyung-kwon/profil/spieler/113552.
Transfer history data appended for: https://www.transfermarkt.com/so-ung-kim/profil/spieler/574708.
Transfer history data appended for: https://www.transfermarkt.com/yong-ho-yoon/profil/spieler/501993.
Transfer history data appended for: https://www.transfermarkt.com/hyeon-seong-kim/profil/spieler/154743.
Transfer history data appended for: https://www.transfermarkt.com/dong-hyeon-kim/profil/spieler/564915.
Transfer history data appended for: https://www.transfermarkt.com/jung-min-lee/profil/spieler/782786.
Transfer history data appended for: https://www.transfermarkt.com/young-kwang-kim/profil/spieler/27408.
Transfer history data appended for: https://www.transfermarkt.com/tomislav-kis/profil/spieler/179899.
Transfer history data appended for: https://www.transfermarkt.com/ji-moog-choi/profil/spieler/763338.
Transfer history data appended for: https://www.transfermarkt.com/tae-min-park/profil/spieler/91338.
Transfer history data appended for: https://www.transfermarkt.com/ki-yeol-kim/profil/spieler/652531.
Transfer history data appended for: https://www.transfermarkt.com/oh-baek-choi/profil/spieler/529721.
Transfer history data appended for: https://www.transfermarkt.com/su-il-park/profil/spieler/552541.
Transfer history data appended for: https://www.transfermarkt.com/sang-ho-na/profil/spieler/508381.
Transfer history data appended for: https://www.transfermarkt.com/yeong-kyu-ahn/profil/spieler/217474.
Transfer history data appended for: https://www.transfermarkt.com/sang-hoon-ma/profil/spieler/241606.
Transfer history data appended for: https://www.transfermarkt.com/je-un-yeon/profil/spieler/426763.
Transfer history data appended for: https://www.transfermarkt.com/si-hoo-hong/profil/spieler/765944.
Transfer history data appended for: https://www.transfermarkt.com/tae-heui-lee/profil/spieler/379444.
Transfer history data appended for: https://www.transfermarkt.com/in-su-yu/profil/spieler/412696.
Transfer history data appended for: https://www.transfermarkt.com/dong-hyen-yang/profil/spieler/92103.
Transfer history data appended for: https://www.transfermarkt.com/jae-won-lee/profil/spieler/634362.
Transfer history data appended for: https://www.transfermarkt.com/ja-ung-heo/profil/spieler/645841.
Transfer history data appended for: https://www.transfermarkt.com/tae-jun-park/profil/spieler/586944.
Transfer history data appended for: https://www.transfermarkt.com/soo-bin-lee/profil/spieler/641646.
Transfer history data appended for: https://www.transfermarkt.com/sung-yoon-lee/profil/spieler/643930.
Transfer history data appended for: https://www.transfermarkt.com/jeong-hoon-kim/profil/spieler/639090.
Transfer history data appended for: https://www.transfermarkt.com/jeong-ho-hong/profil/spieler/126638.
Transfer history data appended for: https://www.transfermarkt.com/sung-eun-na/profil/spieler/557243.
Transfer history data appended for: https://www.transfermarkt.com/yong-lee/profil/spieler/92078.
Transfer history data appended for: https://www.transfermarkt.com/bum-keun-song/profil/spieler/508237.
Transfer history data appended for: https://www.transfermarkt.com/kyo-won-han/profil/spieler/178106.

Transfer history data appended for: https://www.transfermarkt.com/ja-ryong-koo/profil/spieler/263835.
Transfer history data appended for: https://www.transfermarkt.com/byeong-keun-hwang/profil/spieler/426129.
Transfer history data appended for: https://www.transfermarkt.com/jung-nam-hong/profil/spieler/92479.
Transfer history data appended for: https://www.transfermarkt.com/se-jin-myeong/profil/spieler/742931.
Transfer history data appended for: https://www.transfermarkt.com/min-hyeok-kim/profil/spieler/94970.
Transfer history data appended for: https://www.transfermarkt.com/chul-soon-choi/profil/spieler/92473.
Transfer history data appended for: https://www.transfermarkt.com/takahiro-kunimoto/profil/spieler/296782.
Transfer history data appended for: https://www.transfermarkt.com/bo-kyung-kim/profil/spieler/128375.
Transfer history data appended for: https://www.transfermarkt.com/jun-ho-son/profil/spieler/312446.
Transfer history data appended for: https://www.transfermarkt.com/hyung-min-shin/profil/spieler/90802.
Transfer history data appended for: https://www.transfermarkt.com/modou-barrow/profil/spieler/189070.
Transfer history data appended for: https://www.transfermarkt.com/si-heon-lee/profil/spieler/645848.
Transfer history data appended for: https://www.transfermarkt.com/won-jae-park/profil/spieler/90799.
Transfer history data appended for: https://www.transfermarkt.com/bo-kyeong-choi/profil/spieler/92080.
Transfer history data appended for: https://www.transfermarkt.com/murilo-henrique/profil/spieler/333857.
Transfer history data appended for: https://www.transfermarkt.com/gue-sung-jo/profil/spieler/652537.
Transfer history data appended for: https://www.transfermarkt.com/ji-hyeok-yun/profil/spieler/557241.
Transfer history data appended for: https://www.transfermarkt.com/seung-ki-lee/profil/spieler/184874.
Transfer history data appended for: https://www.transfermarkt.com/bum-young-lee/profil/spieler/115199.
Transfer history data appended for: https://www.transfermarkt.com/ju-yong-lee/profil/spieler/314399.
Transfer history data appended for: https://www.transfermarkt.com/seung-jun-song/profil/spieler/735035.
Transfer history data appended for: https://www.transfermarkt.com/kwang-yeon-lee/profil/spieler/630165.
Transfer history data appended for: https://www.transfermarkt.com/se-gye-sin/profil/spieler/184431.
Transfer history data appended for: https://www.transfermarkt.com/won-jin-hong/profil/spieler/735036.
Transfer history data appended for: https://www.transfermarkt.com/yeon-gyu-lee/profil/spieler/676395.
Transfer history data appended for: https://www.transfermarkt.com/min-woo-seo/profil/spieler/730142.
Transfer history data appended for: https://www.transfermarkt.com/chae-min-lim/profil/spieler/260196.
Transfer history data appended for: https://www.transfermarkt.com/ji-hyun-kim/profil/spieler/562360.
Transfer history data appended for: https://www.transfermarkt.com/su-hyeok-kim/profil/spieler/562358.
Transfer history data appended for: https://www.transfermarkt.com/jae-wan-jo/profil/spieler/561211.
Transfer history data appended for: https://www.transfermarkt.com/young-bin-kim/profil/spieler/379409.
Transfer history data appended for: https://www.transfermarkt.com/gwang-hoon-chae/profil/spieler/530745.
Transfer history data appended for: https://www.transfermarkt.com/jae-uk-shin/profil/spieler/752460.
Transfer history data appended for: https://www.transfermarkt.com/seung-dae-kim/profil/spieler/260183.
Transfer history data appended for: https://www.transfermarkt.com/gang-han-lee/profil/spieler/735037.
Transfer history data appended for: https://www.transfermarkt.com/ji-hun-jo/profil/spieler/62630.
Transfer history data appended for: https://www.transfermarkt.com/yeong-jae-lee/profil/spieler/486601.
Transfer history data appended for: https://www.transfermarkt.com/hyeon-sik-lee/profil/spieler/562357.
Transfer history data appended for: https://www.transfermarkt.com/jae-beom-kwon/profil/spieler/743253.
Transfer history data appended for: https://www.transfermarkt.com/ji-yong-jeong/profil/spieler/673471.
Transfer history data appended for: https://www.transfermarkt.com/bum-soo-lee/profil/spieler/96139.
Transfer history data appended for: https://www.transfermarkt.com/soo-beom-kim/profil/spieler/180587.
Transfer history data appended for: https://www.transfermarkt.com/kwang-seok-mun/profil/spieler/573770.
Transfer history data appended for: https://www.transfermarkt.com/kyeong-jung-kim/profil/spieler/194388.
Transfer history data appended for: https://www.transfermarkt.com/yun-seong-jo/profil/spieler/649603.
Transfer history data appended for: https://www.transfermarkt.com/min-uh-jeong/profil/spieler/677134.
Transfer history data appended for: https://www.transfermarkt.com/seok-hwa-jung/profil/spieler/260172.
Transfer history data appended for: https://www.transfermarkt.com/moo-yol-go/profil/spieler/181669.
Transfer history data appended for: https://www.transfermarkt.com/takahiro-nakazato/profil/spieler/103306.
Transfer history data appended for: https://www.transfermarkt.com/guk-yeong-han/profil/spieler/139670.
Transfer history data appended for: https://www.transfermarkt.com/kyong-bae-park/profil/spieler/741592.
Transfer history data appended for: https://www.transfermarkt.com/byeong-wook-lee/profil/spieler/556382.
Transfer history data appended for: https://www.transfermarkt.com/ho-in-lee/profil/spieler/558354.
Transfer history data appended for: https://www.transfermarkt.com/kwang-hun-shin/profil/spieler/81794.
Transfer history data appended for: https://www.transfermarkt.com/eui-su-ji/profil/spieler/667334.
Transfer history data appended for: https://www.transfermarkt.com/sol-hyun-ka/profil/spieler/263824.
Transfer history data appended for: https://www.transfermarkt.com/jae-kwon-lee/profil/spieler/178076.
Transfer history data appended for: https://www.transfermarkt.com/sang-min-lee/profil/spieler/501992.
Transfer history data appended for: https://www.transfermarkt.com/yong-eon-lee/profil/spieler/676393.
Transfer history data appended for: https://www.transfermarkt.com/i-gi-lee/profil/spieler/735200.
Transfer history data appended for: https://www.transfermarkt.com/adam-taggart/profil/spieler/171721.
Transfer history data appended for: https://www.transfermarkt.com/tae-hwan-kim/profil/spieler/646357.
Transfer history data appended for: https://www.transfermarkt.com/eui-kwon-han/profil/spieler/321222.
Transfer history data appended for: https://www.transfermarkt.com/kang-hee-lee/profil/spieler/734395.
Transfer history data appended for: https://www.transfermarkt.com/ki-je-lee/profil/spieler/194389.
Transfer history data appended for: https://www.transfermarkt.com/seo-ho-yun/profil/spieler/639413.
Transfer history data appended for: https://www.transfermarkt.com/sang-hwi-shin/profil/spieler/646356.
Transfer history data appended for: https://www.transfermarkt.com/sang-hyeob-im/profil/spieler/151067.
Transfer history data appended for: https://www.transfermarkt.com/chan-gi-an/profil/spieler/645842.
Transfer history data appended for: https://www.transfermarkt.com/dong-geon-no/profil/spieler/194418.
Transfer history data appended for: https://www.transfermarkt.com/yong-hyeok-lee/profil/spieler/667294.
Transfer history data appended for: https://www.transfermarkt.com/pung-yeon-lee/profil/spieler/730363.
Transfer history data appended for: https://www.transfermarkt.com/sang-bin-jung/profil/spieler/638571.
Transfer history data appended for: https://www.transfermarkt.com/seong-jin-jo/profil/spieler/140478.
Transfer history data appended for: https://www.transfermarkt.com/min-woo-kim/profil/spieler/128376.
Transfer history data appended for: https://www.transfermarkt.com/seok-hee-han/profil/spieler/653005.
Transfer history data appended for: https://www.transfermarkt.com/sang-ki-min/profil/spieler/152253.
Transfer history data appended for: https://www.transfermarkt.com/terry-antonis/profil/spieler/153880.
Transfer history data appended for: https://www.transfermarkt.com/ho-jun-son/profil/spieler/638540.
Transfer history data appended for: https://www.transfermarkt.com/jun-jae-myeong/profil/spieler/426123.
Transfer history data appended for: https://www.transfermarkt.com/da-sol-kim/profil/spieler/126639.

Transfer history data appended for: https://www.transfermarkt.com/hyun-muk-kang/profil/spieler/735201.
Transfer history data appended for: https://www.transfermarkt.com/seong-keun-choi/profil/spieler/128447.
Transfer history data appended for: https://www.transfermarkt.com/doneil-henry/profil/spieler/157907.
Transfer history data appended for: https://www.transfermarkt.com/jong-uh-kim/profil/spieler/426199.
Transfer history data appended for: https://www.transfermarkt.com/ki-hun-yeom/profil/spieler/92093.
Transfer history data appended for: https://www.transfermarkt.com/geon-heui-kim/profil/spieler/426198.
Transfer history data appended for: https://www.transfermarkt.com/sang-min-yang/profil/spieler/50141.
Transfer history data appended for: https://www.transfermarkt.com/seung-beom-ko/profil/spieler/426201.
Transfer history data appended for: https://www.transfermarkt.com/dae-won-park/profil/spieler/402141.
Transfer history data appended for: https://www.transfermarkt.com/hyung-mo-yang/profil/spieler/316269.
Transfer history data appended for: https://www.transfermarkt.com/dae-yeong-ku/profil/spieler/319368.
Transfer history data appended for: https://www.transfermarkt.com/sang-hyeok-park/profil/spieler/402150.
Transfer history data appended for: https://www.transfermarkt.com/jong-seong-lee/profil/spieler/172152.
Transfer history data appended for: https://www.transfermarkt.com/seok-jong-han/profil/spieler/318747.
Transfer history data appended for: https://www.transfermarkt.com/jun-hyeong-kim/profil/spieler/501994.
Transfer history data appended for: https://www.transfermarkt.com/sang-jun-kim/profil/spieler/639242.
Transfer history data appended for: https://www.transfermarkt.com/ho-ik-jang/profil/spieler/426209.
Transfer history data appended for: https://www.transfermarkt.com/sang-woo-kang/profil/spieler/261394.
Transfer history data appended for: https://www.transfermarkt.com/samuel-pungi/profil/spieler/817090.
Transfer history data appended for: https://www.transfermarkt.com/beom-seok-oh/profil/spieler/67672.
Transfer history data appended for: https://www.transfermarkt.com/young-jun-choi/profil/spieler/184582.
Transfer history data appended for: https://www.transfermarkt.com/kyung-min-mun/profil/spieler/671817.
Transfer history data appended for: https://www.transfermarkt.com/wan-kyu-kwon/profil/spieler/317775.
Transfer history data appended for: https://www.transfermarkt.com/do-hyeon-lee/profil/spieler/671816.
Transfer history data appended for: https://www.transfermarkt.com/dong-un-shim/profil/spieler/217649.
Transfer history data appended for: https://www.transfermarkt.com/brandon-oneill/profil/spieler/218371.
Transfer history data appended for: https://www.transfermarkt.com/tae-ryoul-yang/profil/spieler/570657.
Transfer history data appended for: https://www.transfermarkt.com/sung-hoon-cho/profil/spieler/641642.
Transfer history data appended for: https://www.transfermarkt.com/jae-hun-park/profil/spieler/743789.
Transfer history data appended for: https://www.transfermarkt.com/joon-jae-nam/profil/spieler/131391.
Transfer history data appended for: https://www.transfermarkt.com/min-kyu-kim/profil/spieler/715731.
Transfer history data appended for: https://www.transfermarkt.com/ryun-sung-kim/profil/spieler/638535.
Transfer history data appended for: https://www.transfermarkt.com/seung-mo-lee/profil/spieler/402166.
Transfer history data appended for: https://www.transfermarkt.com/kwang-suk-kim/profil/spieler/90788.
Transfer history data appended for: https://www.transfermarkt.com/kwang-hyeok-lee/profil/spieler/292258.
Transfer history data appended for: https://www.transfermarkt.com/min-kyu-song/profil/spieler/581977.
Transfer history data appended for: https://www.transfermarkt.com/hyun-moo-kang/profil/spieler/312424.
Transfer history data appended for: https://www.transfermarkt.com/min-gul-uh/profil/spieler/743788.
Transfer history data appended for: https://www.transfermarkt.com/min-kwang-jeon/profil/spieler/529712.
Transfer history data appended for: https://www.transfermarkt.com/chang-rae-ha/profil/spieler/510244.
Transfer history data appended for: https://www.transfermarkt.com/jae-woo-park/profil/spieler/641644.
Transfer history data appended for: https://www.transfermarkt.com/ji-hun-noh/profil/spieler/742810.
Transfer history data appended for: https://www.transfermarkt.com/ji-yong-lee/profil/spieler/730372.
Transfer history data appended for: https://www.transfermarkt.com/dong-bum-kim/profil/spieler/641645.
Transfer history data appended for: https://www.transfermarkt.com/kyung-hyun-min/profil/spieler/654288.
Transfer history data appended for: https://www.transfermarkt.com/seung-min-song/profil/spieler/319835.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-iljutcenko/profil/spieler/191292.
Transfer history data appended for: https://www.transfermarkt.com/jun-lee/profil/spieler/429694.
Transfer history data appended for: https://www.transfermarkt.com/manuel-palacios/profil/spieler/242552.
Transfer history data appended for: https://www.transfermarkt.com/ju-hwan-kim/profil/spieler/639241.
Transfer history data appended for: https://www.transfermarkt.com/ho-jae-lee/profil/spieler/545501.
Transfer history data appended for: https://www.transfermarkt.com/jae-young-choi/profil/spieler/641641.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-palocevic/profil/spieler/192740.
Transfer history data appended for: https://www.transfermarkt.com/seok-kyu-lee/profil/spieler/754829.
Transfer history data appended for: https://www.transfermarkt.com/yoon-sang-hong/profil/spieler/639040.
Transfer history data appended for: https://www.transfermarkt.com/in-jae-hwang/profil/spieler/428671.
Transfer history data appended for: https://www.transfermarkt.com/young-jun-goh/profil/spieler/639245.
Transfer history data appended for: https://www.transfermarkt.com/sang-won-kim/profil/spieler/316369.
Transfer history data appended for: https://www.transfermarkt.com/roman-zobnin/profil/spieler/166277.
Transfer history data appended for: https://www.transfermarkt.com/jordan-larsson/profil/spieler/308552.
Transfer history data appended for: https://www.transfermarkt.com/pavel-maslov/profil/spieler/424121.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-kokorin/profil/spieler/89086.
Transfer history data appended for: https://www.transfermarkt.com/maksim-glushenkov/profil/spieler/448981.
Transfer history data appended for: https://www.transfermarkt.com/nail-umyarov/profil/spieler/381833.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-maksimenko/profil/spieler/351419.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-tashaev/profil/spieler/260301.
Transfer history data appended for: https://www.transfermarkt.com/oston-urunov/profil/spieler/492556.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-selikhov/profil/spieler/265153.
Transfer history data appended for: https://www.transfermarkt.com/ayaz-guliev/profil/spieler/260672.
Transfer history data appended for: https://www.transfermarkt.com/zelimkhan-bakaev/profil/spieler/279242.
Transfer history data appended for: https://www.transfermarkt.com/samuel-gigot/profil/spieler/276896.
Transfer history data appended for: https://www.transfermarkt.com/ilya-kutepov/profil/spieler/129096.
Transfer history data appended for: https://www.transfermarkt.com/georgiy-dzhikiya/profil/spieler/185024.
Transfer history data appended for: https://www.transfermarkt.com/andrey-eshchenko/profil/spieler/48987.
Transfer history data appended for: https://www.transfermarkt.com/artem-rebrov/profil/spieler/15680.
Transfer history data appended for: https://www.transfermarkt.com/alex-kral/profil/spieler/337333.
Transfer history data appended for: https://www.transfermarkt.com/ilya-gaponov/profil/spieler/395654.
Transfer history data appended for: https://www.transfermarkt.com/mikhail-ignatov/profil/spieler/419672.
Transfer history data appended for: https://www.transfermarkt.com/ayrton-lucas/profil/spieler/349585.
Transfer history data appended for: https://www.transfermarkt.com/cedric-gogoua/profil/spieler/221119.

Transfer history data appended for: https://www.transfermarkt.com/flamarion-junior/profil/spieler/465858.
Transfer history data appended for: https://www.transfermarkt.com/kirill-kolesnichenko/profil/spieler/366751.
Transfer history data appended for: https://www.transfermarkt.com/danil-stepanov/profil/spieler/456182.
Transfer history data appended for: https://www.transfermarkt.com/nikolay-kipiani/profil/spieler/282625.
Transfer history data appended for: https://www.transfermarkt.com/ilya-zhigulev/profil/spieler/443778.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-pesegov/profil/spieler/98556.
Transfer history data appended for: https://www.transfermarkt.com/oleg-kozhemyakin/profil/spieler/343773.
Transfer history data appended for: https://www.transfermarkt.com/armen-manucharyan/profil/spieler/244133.
Transfer history data appended for: https://www.transfermarkt.com/nikita-repin/profil/spieler/515074.
Transfer history data appended for: https://www.transfermarkt.com/sergey-makarov/profil/spieler/267356.
Transfer history data appended for: https://www.transfermarkt.com/oleg-nikolaev/profil/spieler/449581.
Transfer history data appended for: https://www.transfermarkt.com/patricio-matricardi/profil/spieler/283585.
Transfer history data appended for: https://www.transfermarkt.com/zurab-davitashvili/profil/spieler/427572.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-dovbnya/profil/spieler/47004.
Transfer history data appended for: https://www.transfermarkt.com/andres-ponce/profil/spieler/308256.
Transfer history data appended for: https://www.transfermarkt.com/solomon-kvirkvelia/profil/spieler/157391.
Transfer history data appended for: https://www.transfermarkt.com/kamil-mullin/profil/spieler/234868.
Transfer history data appended for: https://www.transfermarkt.com/josip-condric/profil/spieler/240941.
Transfer history data appended for: https://www.transfermarkt.com/nikita-muromskiy/profil/spieler/685937.
Transfer history data appended for: https://www.transfermarkt.com/azat-bairyev/profil/spieler/55295.
Transfer history data appended for: https://www.transfermarkt.com/sergey-serchenkov/profil/spieler/282644.
Transfer history data appended for: https://www.transfermarkt.com/beka-mikeltadze/profil/spieler/319452.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-saplinov/profil/spieler/449575.
Transfer history data appended for: https://www.transfermarkt.com/oleg-aleynik/profil/spieler/78716.
Transfer history data appended for: https://www.transfermarkt.com/maksim-belyaev/profil/spieler/98533.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-kadiri/profil/spieler/442942.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-dovbnya/profil/spieler/263911.
Transfer history data appended for: https://www.transfermarkt.com/valeri-gromyko/profil/spieler/351729.
Transfer history data appended for: https://www.transfermarkt.com/nikolay-rasskazov/profil/spieler/285868.
Transfer history data appended for: https://www.transfermarkt.com/goran-causic/profil/spieler/94304.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-lutsenko/profil/spieler/38801.
Transfer history data appended for: https://www.transfermarkt.com/gia-grigalava/profil/spieler/52089.
Transfer history data appended for: https://www.transfermarkt.com/vladislav-panteleev/profil/spieler/260681.
Transfer history data appended for: https://www.transfermarkt.com/egor-shamov/profil/spieler/449377.
Transfer history data appended for: https://www.transfermarkt.com/yuri-kovalev/profil/spieler/203510.
Transfer history data appended for: https://www.transfermarkt.com/igor-gorbatenko/profil/spieler/62834.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-lomovitskiy/profil/spieler/292837.
Transfer history data appended for: https://www.transfermarkt.com/kings-kangwa/profil/spieler/684998.
Transfer history data appended for: https://www.transfermarkt.com/kirill-kombarov/profil/spieler/26591.
Transfer history data appended for: https://www.transfermarkt.com/roman-minaev/profil/spieler/449385.
Transfer history data appended for: https://www.transfermarkt.com/sergey-tkachev/profil/spieler/132091.
Transfer history data appended for: https://www.transfermarkt.com/guram-adzhoev/profil/spieler/290649.
Transfer history data appended for: https://www.transfermarkt.com/taras-burlak/profil/spieler/70212.
Transfer history data appended for: https://www.transfermarkt.com/artem-sokol/profil/spieler/330780.
Transfer history data appended for: https://www.transfermarkt.com/artur-nigmatullin/profil/spieler/70074.
Transfer history data appended for: https://www.transfermarkt.com/georgi-kostadinov/profil/spieler/198816.
Transfer history data appended for: https://www.transfermarkt.com/anri-khagush/profil/spieler/53228.
Transfer history data appended for: https://www.transfermarkt.com/luka-djordjevic/profil/spieler/188338.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-denisov/profil/spieler/82597.
Transfer history data appended for: https://www.transfermarkt.com/kirill-panchenko/profil/spieler/106675.
Transfer history data appended for: https://www.transfermarkt.com/daniil-khlusevich/profil/spieler/621436.
Transfer history data appended for: https://www.transfermarkt.com/mikhail-levashov/profil/spieler/148028.
Transfer history data appended for: https://www.transfermarkt.com/oleg-baklov/profil/spieler/338908.
Transfer history data appended for: https://www.transfermarkt.com/yuri-bavin/profil/spieler/212258.
Transfer history data appended for: https://www.transfermarkt.com/yaroslav-godzyur/profil/spieler/48514.
Transfer history data appended for: https://www.transfermarkt.com/stefan-strandberg/profil/spieler/50617.
Transfer history data appended for: https://www.transfermarkt.com/roman-emeljanov/profil/spieler/103950.
Transfer history data appended for: https://www.transfermarkt.com/chingiz-magomadov/profil/spieler/455014.
Transfer history data appended for: https://www.transfermarkt.com/othman-el-kabir/profil/spieler/260370.
Transfer history data appended for: https://www.transfermarkt.com/vyacheslav-podberezkin/profil/spieler/207528.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-evseev/profil/spieler/194947.
Transfer history data appended for: https://www.transfermarkt.com/nikolai-zolotov/profil/spieler/297752.
Transfer history data appended for: https://www.transfermarkt.com/eric-bicfalvi/profil/spieler/46504.
Transfer history data appended for: https://www.transfermarkt.com/andrey-panyukov/profil/spieler/181177.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-rykov/profil/spieler/117802.
Transfer history data appended for: https://www.transfermarkt.com/artem-shabolin/profil/spieler/605923.
Transfer history data appended for: https://www.transfermarkt.com/danijel-miskic/profil/spieler/131323.
Transfer history data appended for: https://www.transfermarkt.com/andrey-egorychev/profil/spieler/447257.
Transfer history data appended for: https://www.transfermarkt.com/shamsiddin-shanbiev/profil/spieler/330783.
Transfer history data appended for: https://www.transfermarkt.com/rafal-augustyniak/profil/spieler/264796.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-efremov/profil/spieler/214243.
Transfer history data appended for: https://www.transfermarkt.com/david-karaev/profil/spieler/256488.
Transfer history data appended for: https://www.transfermarkt.com/igor-kalinin/profil/spieler/267396.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-gerasimov/profil/spieler/300447.
Transfer history data appended for: https://www.transfermarkt.com/branko-jovicic/profil/spieler/214715.
Transfer history data appended for: https://www.transfermarkt.com/ilya-pomazun/profil/spieler/217686.
Transfer history data appended for: https://www.transfermarkt.com/denys-kulakov/profil/spieler/25734.
Transfer history data appended for: https://www.transfermarkt.com/arseni-logashov/profil/spieler/88615.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-troshechkin/profil/spieler/308541.

Transfer history data appended for: https://www.transfermarkt.com/andrey-murnin/profil/spieler/61959.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-konate/profil/spieler/457743.
Transfer history data appended for: https://www.transfermarkt.com/kamran-aliev/profil/spieler/489815.
Transfer history data appended for: https://www.transfermarkt.com/mikhail-tikhonov/profil/spieler/445784.
Transfer history data appended for: https://www.transfermarkt.com/arshak-koryan/profil/spieler/214252.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-dolgov/profil/spieler/515506.
Transfer history data appended for: https://www.transfermarkt.com/egor-danilkin/profil/spieler/260229.
Transfer history data appended for: https://www.transfermarkt.com/kirill-bozhenov/profil/spieler/605534.
Transfer history data appended for: https://www.transfermarkt.com/bryan-idowu/profil/spieler/178957.
Transfer history data appended for: https://www.transfermarkt.com/danil-kazantsev/profil/spieler/687059.
Transfer history data appended for: https://www.transfermarkt.com/danil-lipovoy/profil/spieler/462988.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-tikhiy/profil/spieler/188650.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-filin/profil/spieler/301037.
Transfer history data appended for: https://www.transfermarkt.com/ilya-kamyshev/profil/spieler/282364.
Transfer history data appended for: https://www.transfermarkt.com/ilya-kukharchuk/profil/spieler/104700.
Transfer history data appended for: https://www.transfermarkt.com/ilya-lantratov/profil/spieler/230946.
Transfer history data appended for: https://www.transfermarkt.com/egor-generalov/profil/spieler/104503.
Transfer history data appended for: https://www.transfermarkt.com/reziuan-mirzov/profil/spieler/232093.
Transfer history data appended for: https://www.transfermarkt.com/denis-glushakov/profil/spieler/55336.
Transfer history data appended for: https://www.transfermarkt.com/pavel-mogilevets/profil/spieler/176618.
Transfer history data appended for: https://www.transfermarkt.com/islambek-kuat/profil/spieler/213846.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-gapon/profil/spieler/88610.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-khomich/profil/spieler/27017.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-dyadyun/profil/spieler/56637.
Transfer history data appended for: https://www.transfermarkt.com/maksim-nenakhov/profil/spieler/382535.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-kharin/profil/spieler/193464.
Transfer history data appended for: https://www.transfermarkt.com/amir-aduev/profil/spieler/485961.
Transfer history data appended for: https://www.transfermarkt.com/vitali-gudiev/profil/spieler/190188.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-iljin/profil/spieler/220650.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-putsko/profil/spieler/126337.
Transfer history data appended for: https://www.transfermarkt.com/lechii-sadulaev/profil/spieler/623553.
Transfer history data appended for: https://www.transfermarkt.com/odise-roshi/profil/spieler/99003.
Transfer history data appended for: https://www.transfermarkt.com/artem-polyarus/profil/spieler/131444.
Transfer history data appended for: https://www.transfermarkt.com/georgi-melkadze/profil/spieler/281552.
Transfer history data appended for: https://www.transfermarkt.com/oleg-ivanov/profil/spieler/16756.
Transfer history data appended for: https://www.transfermarkt.com/miroslav-bogosavac/profil/spieler/273945.
Transfer history data appended for: https://www.transfermarkt.com/abubakar-kadyrov/profil/spieler/488849.
Transfer history data appended for: https://www.transfermarkt.com/arsen-adamov/profil/spieler/455016.
Transfer history data appended for: https://www.transfermarkt.com/bernard-berisha/profil/spieler/240226.
Transfer history data appended for: https://www.transfermarkt.com/wilker-angel/profil/spieler/178400.
Transfer history data appended for: https://www.transfermarkt.com/andrey-semenov/profil/spieler/105478.
Transfer history data appended for: https://www.transfermarkt.com/pavel-kaloshin/profil/spieler/605627.
Transfer history data appended for: https://www.transfermarkt.com/giorgi-shelia/profil/spieler/58971.
Transfer history data appended for: https://www.transfermarkt.com/ablaye-mbengue/profil/spieler/354040.
Transfer history data appended for: https://www.transfermarkt.com/artem-timofeev/profil/spieler/211727.
Transfer history data appended for: https://www.transfermarkt.com/islam-alsultanov/profil/spieler/623557.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-melikhov/profil/spieler/476274.
Transfer history data appended for: https://www.transfermarkt.com/anton-shvets/profil/spieler/221992.
Transfer history data appended for: https://www.transfermarkt.com/rizvan-utsiev/profil/spieler/51274.
Transfer history data appended for: https://www.transfermarkt.com/khalid-kadyrov/profil/spieler/155304.
Transfer history data appended for: https://www.transfermarkt.com/marat-bystrov/profil/spieler/394980.
Transfer history data appended for: https://www.transfermarkt.com/zoran-nizic/profil/spieler/120710.
Transfer history data appended for: https://www.transfermarkt.com/marko-dugandzic/profil/spieler/225961.
Transfer history data appended for: https://www.transfermarkt.com/christian-noboa/profil/spieler/45858.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-pomerko/profil/spieler/72164.
Transfer history data appended for: https://www.transfermarkt.com/artur-yusupov/profil/spieler/97541.
Transfer history data appended for: https://www.transfermarkt.com/miha-mevlja/profil/spieler/100160.
Transfer history data appended for: https://www.transfermarkt.com/maksim-barsov/profil/spieler/126341.
Transfer history data appended for: https://www.transfermarkt.com/andrey-bokovoy/profil/spieler/596523.
Transfer history data appended for: https://www.transfermarkt.com/emanuel-mammana/profil/spieler/275512.
Transfer history data appended for: https://www.transfermarkt.com/nikita-burmistrov/profil/spieler/49676.
Transfer history data appended for: https://www.transfermarkt.com/nikita-koldunov/profil/spieler/458389.
Transfer history data appended for: https://www.transfermarkt.com/joaozinho/profil/spieler/73783.
Transfer history data appended for: https://www.transfermarkt.com/ivan-novoseltsev/profil/spieler/231873.
Transfer history data appended for: https://www.transfermarkt.com/elmir-nabiullin/profil/spieler/214257.
Transfer history data appended for: https://www.transfermarkt.com/danil-prutsev/profil/spieler/381714.
Transfer history data appended for: https://www.transfermarkt.com/ivelin-popov/profil/spieler/38340.
Transfer history data appended for: https://www.transfermarkt.com/erik-vardanyan/profil/spieler/403080.
Transfer history data appended for: https://www.transfermarkt.com/anton-zabolotnyi/profil/spieler/70114.
Transfer history data appended for: https://www.transfermarkt.com/ivan-miladinovic/profil/spieler/296963.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-rudenko/profil/spieler/318468.
Transfer history data appended for: https://www.transfermarkt.com/nikita-kalugin/profil/spieler/285862.
Transfer history data appended for: https://www.transfermarkt.com/nikolay-zabolotnyi/profil/spieler/55439.
Transfer history data appended for: https://www.transfermarkt.com/sergey-terekhov/profil/spieler/74081.
Transfer history data appended for: https://www.transfermarkt.com/kirill-zaika/profil/spieler/379181.
Transfer history data appended for: https://www.transfermarkt.com/timofey-margasov/profil/spieler/148485.
Transfer history data appended for: https://www.transfermarkt.com/ibragim-tsallagov/profil/spieler/138399.
Transfer history data appended for: https://www.transfermarkt.com/soslan-dzhanaev/profil/spieler/59209.
Transfer history data appended for: https://www.transfermarkt.com/akmal-bakhtiyarov/profil/spieler/413688.

Transfer history data appended for: https://www.transfermarkt.com/shapi-suleymanov/profil/spieler/335725.
Transfer history data appended for: https://www.transfermarkt.com/aleks-matsukatov/profil/spieler/312895.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-chernov/profil/spieler/187024.
Transfer history data appended for: https://www.transfermarkt.com/daniil-utkin/profil/spieler/375667.
Transfer history data appended for: https://www.transfermarkt.com/leon-sabua/profil/spieler/476142.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-olsson/profil/spieler/193592.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-gorodov/profil/spieler/38681.
Transfer history data appended for: https://www.transfermarkt.com/matvey-safonov/profil/spieler/318470.
Transfer history data appended for: https://www.transfermarkt.com/viktor-claesson/profil/spieler/116598.
Transfer history data appended for: https://www.transfermarkt.com/maksim-kutovoy/profil/spieler/430485.
Transfer history data appended for: https://www.transfermarkt.com/egor-sorokin/profil/spieler/288721.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-stotskiy/profil/spieler/124700.
Transfer history data appended for: https://www.transfermarkt.com/denis-adamov/profil/spieler/334477.
Transfer history data appended for: https://www.transfermarkt.com/igor-smolnikov/profil/spieler/46635.
Transfer history data appended for: https://www.transfermarkt.com/tonny-vilhena/profil/spieler/182581.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-martynovich/profil/spieler/59352.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-ionov/profil/spieler/55356.
Transfer history data appended for: https://www.transfermarkt.com/ruslan-kambolov/profil/spieler/58568.
Transfer history data appended for: https://www.transfermarkt.com/wanderson/profil/spieler/236202.
Transfer history data appended for: https://www.transfermarkt.com/kaio/profil/spieler/523363.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-markov/profil/spieler/166737.
Transfer history data appended for: https://www.transfermarkt.com/sergey-petrov/profil/spieler/102581.
Transfer history data appended for: https://www.transfermarkt.com/yuri-gazinskiy/profil/spieler/159957.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-chernikov/profil/spieler/432112.
Transfer history data appended for: https://www.transfermarkt.com/eduard-spertsyan/profil/spieler/515744.
Transfer history data appended for: https://www.transfermarkt.com/andrey-sinitsyn/profil/spieler/106196.
Transfer history data appended for: https://www.transfermarkt.com/marcus-berg/profil/spieler/30418.
Transfer history data appended for: https://www.transfermarkt.com/cristian-ramirez/profil/spieler/189485.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-kozlov/profil/spieler/24912.
Transfer history data appended for: https://www.transfermarkt.com/kento-hashimoto/profil/spieler/183436.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-pavlovets/profil/spieler/249747.
Transfer history data appended for: https://www.transfermarkt.com/armin-gigovic/profil/spieler/651269.
Transfer history data appended for: https://www.transfermarkt.com/david-tosevski/profil/spieler/542338.
Transfer history data appended for: https://www.transfermarkt.com/danil-glebov/profil/spieler/570423.
Transfer history data appended for: https://www.transfermarkt.com/nikolay-poyarkov/profil/spieler/449721.
Transfer history data appended for: https://www.transfermarkt.com/khoren-bayramyan/profil/spieler/189715.
Transfer history data appended for: https://www.transfermarkt.com/maksim-rudakov/profil/spieler/235347.
Transfer history data appended for: https://www.transfermarkt.com/mathias-normann/profil/spieler/257805.
Transfer history data appended for: https://www.transfermarkt.com/haitam-aleesami/profil/spieler/230166.
Transfer history data appended for: https://www.transfermarkt.com/sergey-pesjakov/profil/spieler/61397.
Transfer history data appended for: https://www.transfermarkt.com/maksim-osipenko/profil/spieler/293829.
Transfer history data appended for: https://www.transfermarkt.com/egor-baburin/profil/spieler/146918.
Transfer history data appended for: https://www.transfermarkt.com/denis-terentjev/profil/spieler/144583.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-poloz/profil/spieler/98539.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-obukhov/profil/spieler/105506.
Transfer history data appended for: https://www.transfermarkt.com/dennis-hadzikadunic/profil/spieler/322065.
Transfer history data appended for: https://www.transfermarkt.com/roman-tugarev/profil/spieler/289643.
Transfer history data appended for: https://www.transfermarkt.com/pavel-mamaev/profil/spieler/38802.
Transfer history data appended for: https://www.transfermarkt.com/pontus-almqvist/profil/spieler/300532.
Transfer history data appended for: https://www.transfermarkt.com/gamid-agalarov/profil/spieler/567023.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-chernov/profil/spieler/393883.
Transfer history data appended for: https://www.transfermarkt.com/sergey-borodin/profil/spieler/318403.
Transfer history data appended for: https://www.transfermarkt.com/yuri-shafinskiy/profil/spieler/212251.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-nikitin/profil/spieler/106536.
Transfer history data appended for: https://www.transfermarkt.com/artem-golubev/profil/spieler/375663.
Transfer history data appended for: https://www.transfermarkt.com/grigori-morozov/profil/spieler/166275.
Transfer history data appended for: https://www.transfermarkt.com/lovro-bizjak/profil/spieler/220315.
Transfer history data appended for: https://www.transfermarkt.com/nikita-belousov/profil/spieler/623315.
Transfer history data appended for: https://www.transfermarkt.com/filip-mrzljak/profil/spieler/131324.
Transfer history data appended for: https://www.transfermarkt.com/oleg-danchenko/profil/spieler/257937.
Transfer history data appended for: https://www.transfermarkt.com/catalin-carp/profil/spieler/213016.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-sysuev/profil/spieler/72171.
Transfer history data appended for: https://www.transfermarkt.com/komnen-andric/profil/spieler/260316.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-belenov/profil/spieler/62514.
Transfer history data appended for: https://www.transfermarkt.com/vyacheslav-krotov/profil/spieler/187460.
Transfer history data appended for: https://www.transfermarkt.com/pavel-alikin/profil/spieler/25879.
Transfer history data appended for: https://www.transfermarkt.com/timur-zhamaletdinov/profil/spieler/315557.
Transfer history data appended for: https://www.transfermarkt.com/kirill-folmer/profil/spieler/485658.
Transfer history data appended for: https://www.transfermarkt.com/bojan-jokic/profil/spieler/44317.
Transfer history data appended for: https://www.transfermarkt.com/konstantin-pliev/profil/spieler/394400.
Transfer history data appended for: https://www.transfermarkt.com/azer-aliev/profil/spieler/230929.
Transfer history data appended for: https://www.transfermarkt.com/jimmy-tabidze/profil/spieler/250907.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-sukhov/profil/spieler/48557.
Transfer history data appended for: https://www.transfermarkt.com/akhmed-alibekov/profil/spieler/343175.
Transfer history data appended for: https://www.transfermarkt.com/vladislav-kamilov/profil/spieler/152962.
Transfer history data appended for: https://www.transfermarkt.com/sardar-azmoun/profil/spieler/180337.
Transfer history data appended for: https://www.transfermarkt.com/danila-prokhin/profil/spieler/486083.
Transfer history data appended for: https://www.transfermarkt.com/danil-krugovoy/profil/spieler/372535.
Transfer history data appended for: https://www.transfermarkt.com/wendel/profil/spieler/499721.

Transfer history data appended for: https://www.transfermarkt.com/mikhail-kerzhakov/profil/spieler/27706.
Transfer history data appended for: https://www.transfermarkt.com/yaroslav-rakitskiy/profil/spieler/89222.
Transfer history data appended for: https://www.transfermarkt.com/andrey-lunev/profil/spieler/112541.
Transfer history data appended for: https://www.transfermarkt.com/daler-kuzyaev/profil/spieler/279570.
Transfer history data appended for: https://www.transfermarkt.com/vyacheslav-karavaev/profil/spieler/170620.
Transfer history data appended for: https://www.transfermarkt.com/andrey-mostovoy/profil/spieler/362570.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-erokhin/profil/spieler/84483.
Transfer history data appended for: https://www.transfermarkt.com/magomed-ozdoev/profil/spieler/137206.
Transfer history data appended for: https://www.transfermarkt.com/daniil-shamkin/profil/spieler/601445.
Transfer history data appended for: https://www.transfermarkt.com/wilmar-barrios/profil/spieler/257668.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-vasyutin/profil/spieler/215213.
Transfer history data appended for: https://www.transfermarkt.com/dejan-lovren/profil/spieler/37838.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-driussi/profil/spieler/294853.
Transfer history data appended for: https://www.transfermarkt.com/leon-musaev/profil/spieler/375668.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-sutormin/profil/spieler/217033.
Transfer history data appended for: https://www.transfermarkt.com/yuri-zhirkov/profil/spieler/16760.
Transfer history data appended for: https://www.transfermarkt.com/malcom/profil/spieler/323704.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-gritsaenko/profil/spieler/379634.
Transfer history data appended for: https://www.transfermarkt.com/vitali-shakhov/profil/spieler/125760.
Transfer history data appended for: https://www.transfermarkt.com/guram-tetrashvili/profil/spieler/275256.
Transfer history data appended for: https://www.transfermarkt.com/maksim-volodjko/profil/spieler/140576.
Transfer history data appended for: https://www.transfermarkt.com/pavel-karasev/profil/spieler/185028.
Transfer history data appended for: https://www.transfermarkt.com/varazdat-haroyan/profil/spieler/155423.
Transfer history data appended for: https://www.transfermarkt.com/sebastien-thill/profil/spieler/158594.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-kapliyenko/profil/spieler/248931.
Transfer history data appended for: https://www.transfermarkt.com/nikita-chicherin/profil/spieler/82201.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-kabakhidze/profil/spieler/461704.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-karapetyan/profil/spieler/49788.
Transfer history data appended for: https://www.transfermarkt.com/adessoye-oyewole/profil/spieler/59180.
Transfer history data appended for: https://www.transfermarkt.com/valeri-chuperka/profil/spieler/98968.
Transfer history data appended for: https://www.transfermarkt.com/jasurbek-jaloliddinov/profil/spieler/603416.
Transfer history data appended for: https://www.transfermarkt.com/mikhail-kostyukov/profil/spieler/275159.
Transfer history data appended for: https://www.transfermarkt.com/anton-kilin/profil/spieler/98558.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-rabiu/profil/spieler/67721.
Transfer history data appended for: https://www.transfermarkt.com/nikita-chagrov/profil/spieler/217652.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-rybin/profil/spieler/106210.
Transfer history data appended for: https://www.transfermarkt.com/soslan-takazov/profil/spieler/181179.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-shlyakov/profil/spieler/145981.
Transfer history data appended for: https://www.transfermarkt.com/german-onugkha/profil/spieler/568318.
Transfer history data appended for: https://www.transfermarkt.com/francois-kamano/profil/spieler/333802.
Transfer history data appended for: https://www.transfermarkt.com/vitali-lystsov/profil/spieler/207519.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-zhivoglyadov/profil/spieler/178335.
Transfer history data appended for: https://www.transfermarkt.com/grzegorz-krychowiak/profil/spieler/45184.
Transfer history data appended for: https://www.transfermarkt.com/ze-luis/profil/spieler/134602.
Transfer history data appended for: https://www.transfermarkt.com/boris-rotenberg/profil/spieler/54310.
Transfer history data appended for: https://www.transfermarkt.com/anton-miranchuk/profil/spieler/255451.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-magkeev/profil/spieler/462329.
Transfer history data appended for: https://www.transfermarkt.com/maksim-mukhin/profil/spieler/623274.
Transfer history data appended for: https://www.transfermarkt.com/mikhail-lysov/profil/spieler/289590.
Transfer history data appended for: https://www.transfermarkt.com/daniil-kulikov/profil/spieler/425756.
Transfer history data appended for: https://www.transfermarkt.com/rifat-zhemaletdinov/profil/spieler/267383.
Transfer history data appended for: https://www.transfermarkt.com/vladislav-ignatjev/profil/spieler/51897.
Transfer history data appended for: https://www.transfermarkt.com/maciej-rybus/profil/spieler/59597.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-barinov/profil/spieler/263905.
Transfer history data appended for: https://www.transfermarkt.com/anton-kochenkov/profil/spieler/70220.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-rybchinskiy/profil/spieler/362572.
Transfer history data appended for: https://www.transfermarkt.com/eder/profil/spieler/84481.
Transfer history data appended for: https://www.transfermarkt.com/vitali-lisakovich/profil/spieler/344565.
Transfer history data appended for: https://www.transfermarkt.com/murilo-cerqueira/profil/spieler/458710.
Transfer history data appended for: https://www.transfermarkt.com/guilherme/profil/spieler/55369.
Transfer history data appended for: https://www.transfermarkt.com/anton-shunin/profil/spieler/37549.
Transfer history data appended for: https://www.transfermarkt.com/ivan-ordets/profil/spieler/118850.
Transfer history data appended for: https://www.transfermarkt.com/charles-kabore/profil/spieler/57402.
Transfer history data appended for: https://www.transfermarkt.com/nikola-moro/profil/spieler/316934.
Transfer history data appended for: https://www.transfermarkt.com/roman-neustadter/profil/spieler/40478.
Transfer history data appended for: https://www.transfermarkt.com/roman-evgenjev/profil/spieler/422838.
Transfer history data appended for: https://www.transfermarkt.com/konstantin-tyukavin/profil/spieler/532676.
Transfer history data appended for: https://www.transfermarkt.com/sergey-parshivlyuk/profil/spieler/52477.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-szymanski/profil/spieler/320748.
Transfer history data appended for: https://www.transfermarkt.com/ivan-budachev/profil/spieler/638365.
Transfer history data appended for: https://www.transfermarkt.com/daniil-lesovoy/profil/spieler/315252.
Transfer history data appended for: https://www.transfermarkt.com/vladislav-karapuzov/profil/spieler/404912.
Transfer history data appended for: https://www.transfermarkt.com/arsen-zakharyan/profil/spieler/555143.
Transfer history data appended for: https://www.transfermarkt.com/konstantin-rausch/profil/spieler/45668.
Transfer history data appended for: https://www.transfermarkt.com/nikolay-komlichenko/profil/spieler/300538.
Transfer history data appended for: https://www.transfermarkt.com/anton-terekhov/profil/spieler/284847.
Transfer history data appended for: https://www.transfermarkt.com/vyacheslav-grulev/profil/spieler/365261.
Transfer history data appended for: https://www.transfermarkt.com/slytm/profil/spieler/102043.
Transfer history data appended for: https://www.transfermarkt.com/sergey-slepov/profil/spieler/396273.

Transfer history data appended for: https://www.transfermarkt.com/vladimir-moskvichev/profil/spieler/402604.
Transfer history data appended for: https://www.transfermarkt.com/igor-shkolik/profil/spieler/451252.
Transfer history data appended for: https://www.transfermarkt.com/clinton-njie/profil/spieler/241119.
Transfer history data appended for: https://www.transfermarkt.com/igor-leshchuk/profil/spieler/168527.
Transfer history data appended for: https://www.transfermarkt.com/zaurbek-pliev/profil/spieler/121958.
Transfer history data appended for: https://www.transfermarkt.com/daniil-fomin/profil/spieler/400713.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-skopintsev/profil/spieler/281917.
Transfer history data appended for: https://www.transfermarkt.com/silvije-begic/profil/spieler/290774.
Transfer history data appended for: https://www.transfermarkt.com/georgi-zotov/profil/spieler/113235.
Transfer history data appended for: https://www.transfermarkt.com/igor-konovalov/profil/spieler/288240.
Transfer history data appended for: https://www.transfermarkt.com/filip-uremovic/profil/spieler/325887.
Transfer history data appended for: https://www.transfermarkt.com/kirill-klimov/profil/spieler/431724.
Transfer history data appended for: https://www.transfermarkt.com/djordje-despotovic/profil/spieler/167316.
Transfer history data appended for: https://www.transfermarkt.com/oliver-abildgaard/profil/spieler/325993.
Transfer history data appended for: https://www.transfermarkt.com/ivan-konovalov/profil/spieler/278190.
Transfer history data appended for: https://www.transfermarkt.com/nikita-medvedev/profil/spieler/296513.
Transfer history data appended for: https://www.transfermarkt.com/in-beom-hwang/profil/spieler/365394.
Transfer history data appended for: https://www.transfermarkt.com/dmitri-tarasov/profil/spieler/48560.
Transfer history data appended for: https://www.transfermarkt.com/oleg-shatov/profil/spieler/59187.
Transfer history data appended for: https://www.transfermarkt.com/yuri-dyupin/profil/spieler/228660.
Transfer history data appended for: https://www.transfermarkt.com/ilya-samoshnikov/profil/spieler/522030.
Transfer history data appended for: https://www.transfermarkt.com/ivan-ignatjev/profil/spieler/318426.
Transfer history data appended for: https://www.transfermarkt.com/aleksandr-zuev/profil/spieler/263963.
Transfer history data appended for: https://www.transfermarkt.com/soltmurad-bakaev/profil/spieler/416704.
Transfer history data appended for: https://www.transfermarkt.com/mikhail-merkulov/profil/spieler/231387.
Transfer history data appended for: https://www.transfermarkt.com/carl-starfelt/profil/spieler/258987.
Transfer history data appended for: https://www.transfermarkt.com/chidera-ejuke/profil/spieler/500067.
Transfer history data appended for: https://www.transfermarkt.com/viktor-vasin/profil/spieler/60134.
Transfer history data appended for: https://www.transfermarkt.com/nikita-kotin/profil/spieler/566046.
Transfer history data appended for: https://www.transfermarkt.com/kirill-nababkin/profil/spieler/38805.
Transfer history data appended for: https://www.transfermarkt.com/arnor-sigurdsson/profil/spieler/377665.
Transfer history data appended for: https://www.transfermarkt.com/fedor-chalov/profil/spieler/287183.
Transfer history data appended for: https://www.transfermarkt.com/adolfo-gaich/profil/spieler/608469.
Transfer history data appended for: https://www.transfermarkt.com/igor-diveev/profil/spieler/532732.
Transfer history data appended for: https://www.transfermarkt.com/konstantin-kuchaev/profil/spieler/381834.
Transfer history data appended for: https://www.transfermarkt.com/vladislav-torop/profil/spieler/555146.
Transfer history data appended for: https://www.transfermarkt.com/konstantin-maradishvili/profil/spieler/535974.
Transfer history data appended for: https://www.transfermarkt.com/ilya-shkurin/profil/spieler/523315.
Transfer history data appended for: https://www.transfermarkt.com/nayair-tiknizyan/profil/spieler/461701.
Transfer history data appended for: https://www.transfermarkt.com/bruno-fuchs/profil/spieler/563692.
Transfer history data appended for: https://www.transfermarkt.com/mario-fernandes/profil/spieler/102740.
Transfer history data appended for: https://www.transfermarkt.com/nikola-vlasic/profil/spieler/293200.
Transfer history data appended for: https://www.transfermarkt.com/igor-akinfeev/profil/spieler/15570.
Transfer history data appended for: https://www.transfermarkt.com/baktiyar-zaynutdinov/profil/spieler/344299.
Transfer history data appended for: https://www.transfermarkt.com/alan-dzagoev/profil/spieler/69683.
Transfer history data appended for: https://www.transfermarkt.com/vadim-karpov/profil/spieler/518261.
Transfer history data appended for: https://www.transfermarkt.com/ilzat-akhmetov/profil/spieler/334440.
Transfer history data appended for: https://www.transfermarkt.com/kristijan-bistrovic/profil/spieler/375857.
Transfer history data appended for: https://www.transfermarkt.com/ivan-oblyakov/profil/spieler/419845.
Transfer history data appended for: https://www.transfermarkt.com/hordur-magnusson/profil/spieler/130353.
Transfer history data appended for: https://www.transfermarkt.com/georgi-schennikov/profil/spieler/70097.
Transfer history data appended for: https://www.transfermarkt.com/lucas-lima/profil/spieler/182323.
Transfer history data appended for: https://www.transfermarkt.com/marko-marin/profil/spieler/35251.
Transfer history data appended for: https://www.transfermarkt.com/yazeed-al-bakr/profil/spieler/164590.
Transfer history data appended for: https://www.transfermarkt.com/hassan-al-qead/profil/spieler/487480.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-owais/profil/spieler/262845.
Transfer history data appended for: https://www.transfermarkt.com/ljubomir-fejsa/profil/spieler/46110.
Transfer history data appended for: https://www.transfermarkt.com/sultan-mandash/profil/spieler/210349.
Transfer history data appended for: https://www.transfermarkt.com/hussain-al-moqahwi/profil/spieler/159675.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-hassoun-tarmin/profil/spieler/509900.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-asmari/profil/spieler/509898.
Transfer history data appended for: https://www.transfermarkt.com/yasser-al-mosailem/profil/spieler/147865.
Transfer history data appended for: https://www.transfermarkt.com/yousef-saad-al-harbi/profil/spieler/478533.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-mjehd/profil/spieler/554034.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-mitri%C8%9B%C4%83/profil/spieler/209649.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-khabrani/profil/spieler/264826.
Transfer history data appended for: https://www.transfermarkt.com/salman-al-muwashar/profil/spieler/178033.
Transfer history data appended for: https://www.transfermarkt.com/muhannad-asiri/profil/spieler/153347.
Transfer history data appended for: https://www.transfermarkt.com/talal-al-absi/profil/spieler/265069.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-rubaie-al-yami/profil/spieler/509914.
Transfer history data appended for: https://www.transfermarkt.com/omar-al-somah/profil/spieler/220688.
Transfer history data appended for: https://www.transfermarkt.com/motaz-hawsawi/profil/spieler/193169.
Transfer history data appended for: https://www.transfermarkt.com/saeed-al-mowalad/profil/spieler/250826.
Transfer history data appended for: https://www.transfermarkt.com/abdulbaset-al-hindi/profil/spieler/478528.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-fatil/profil/spieler/193150.
Transfer history data appended for: https://www.transfermarkt.com/nooh-al-mousa/profil/spieler/267975.
Transfer history data appended for: https://www.transfermarkt.com/samuel-owusu/profil/spieler/340994.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-gharib/profil/spieler/164593.
Transfer history data appended for: https://www.transfermarkt.com/driss-fettouhi/profil/spieler/78956.

Transfer history data appended for: https://www.transfermarkt.com/fawaz-al-tarees/profil/spieler/153435.
Transfer history data appended for: https://www.transfermarkt.com/madallah-al-olayan/profil/spieler/264729.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-boleahi/profil/spieler/229877.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-kanno/profil/spieler/308120.
Transfer history data appended for: https://www.transfermarkt.com/omar-khribin/profil/spieler/299161.
Transfer history data appended for: https://www.transfermarkt.com/hattan-bahebri/profil/spieler/201379.
Transfer history data appended for: https://www.transfermarkt.com/habib-al-wutaian/profil/spieler/469595.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-burayk/profil/spieler/379058.
Transfer history data appended for: https://www.transfermarkt.com/salman-al-faraj/profil/spieler/155487.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-cuellar/profil/spieler/119333.
Transfer history data appended for: https://www.transfermarkt.com/andre-carrillo/profil/spieler/135057.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-jadani/profil/spieler/250825.
Transfer history data appended for: https://www.transfermarkt.com/muteb-al-mufarrij/profil/spieler/631917.
Transfer history data appended for: https://www.transfermarkt.com/nasser-al-dawsari/profil/spieler/509911.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-otayf/profil/spieler/193159.
Transfer history data appended for: https://www.transfermarkt.com/yasir-al-shahrani/profil/spieler/171915.
Transfer history data appended for: https://www.transfermarkt.com/salem-al-dawsari/profil/spieler/195332.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-jahfali/profil/spieler/159561.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-muaiouf/profil/spieler/147866.
Transfer history data appended for: https://www.transfermarkt.com/hyeon-su-jang/profil/spieler/194387.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-giovinco/profil/spieler/52312.
Transfer history data appended for: https://www.transfermarkt.com/luciano-vietto/profil/spieler/214316.
Transfer history data appended for: https://www.transfermarkt.com/bafetimbi-gomis/profil/spieler/22388.
Transfer history data appended for: https://www.transfermarkt.com/amiri-kurdi/profil/spieler/136749.
Transfer history data appended for: https://www.transfermarkt.com/mansoor-al-bishi/profil/spieler/672382.
Transfer history data appended for: https://www.transfermarkt.com/nawaf-al-ghamdi/profil/spieler/631924.
Transfer history data appended for: https://www.transfermarkt.com/muhannad-fallatah/profil/spieler/445705.
Transfer history data appended for: https://www.transfermarkt.com/ayman-yusef-al-hujaili/profil/spieler/209749.
Transfer history data appended for: https://www.transfermarkt.com/moustapha-zeghba/profil/spieler/233069.
Transfer history data appended for: https://www.transfermarkt.com/omar-al-mzeal/profil/spieler/159926.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-khtab/profil/spieler/470836.
Transfer history data appended for: https://www.transfermarkt.com/sami-kassar/profil/spieler/476368.
Transfer history data appended for: https://www.transfermarkt.com/ramzi-solan/profil/spieler/680170.
Transfer history data appended for: https://www.transfermarkt.com/mazen-abusharara/profil/spieler/264825.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-al-baraka/profil/spieler/364956.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-samtai/profil/spieler/153842.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-al-sarhani/profil/spieler/646762.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-rio/profil/spieler/435663.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-al-aryani/profil/spieler/461126.
Transfer history data appended for: https://www.transfermarkt.com/tareq-abdullah/profil/spieler/500078.
Transfer history data appended for: https://www.transfermarkt.com/emilio-zelaya/profil/spieler/30832.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-jaseem/profil/spieler/686068.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-qaisy/profil/spieler/364393.
Transfer history data appended for: https://www.transfermarkt.com/sultan-msrahi/profil/spieler/153189.
Transfer history data appended for: https://www.transfermarkt.com/bilel-saidani/profil/spieler/292223.
Transfer history data appended for: https://www.transfermarkt.com/khaled-shrahili/profil/spieler/164589.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-chenihi/profil/spieler/232873.
Transfer history data appended for: https://www.transfermarkt.com/cristian-lema/profil/spieler/147128.
Transfer history data appended for: https://www.transfermarkt.com/abdulwahab-jaafar/profil/spieler/153514.
Transfer history data appended for: https://www.transfermarkt.com/mansour-hamzi/profil/spieler/315050.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-zubaidi/profil/spieler/487473.
Transfer history data appended for: https://www.transfermarkt.com/sami-al-najei/profil/spieler/434672.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-ammar/profil/spieler/369090.
Transfer history data appended for: https://www.transfermarkt.com/abbas-shengeeti/profil/spieler/262840.
Transfer history data appended for: https://www.transfermarkt.com/farouk-chafai/profil/spieler/175170.
Transfer history data appended for: https://www.transfermarkt.com/murad-al-rashidi/profil/spieler/264730.
Transfer history data appended for: https://www.transfermarkt.com/mansour-al-muwallad/profil/spieler/509913.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-atiah/profil/spieler/262739.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-mohsen-harzzan/profil/spieler/506072.
Transfer history data appended for: https://www.transfermarkt.com/hussein-al-jassim/profil/spieler/490813.
Transfer history data appended for: https://www.transfermarkt.com/sa-scaron-a-jovanovic/profil/spieler/129392.
Transfer history data appended for: https://www.transfermarkt.com/marwane-saadane/profil/spieler/210009.
Transfer history data appended for: https://www.transfermarkt.com/mohammad-al-bariah/profil/spieler/214926.
Transfer history data appended for: https://www.transfermarkt.com/hasan-al-habib/profil/spieler/452402.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-saeed/profil/spieler/504124.
Transfer history data appended for: https://www.transfermarkt.com/saeed-al-dosari/profil/spieler/209578.
Transfer history data appended for: https://www.transfermarkt.com/sager-otayf/profil/spieler/324636.
Transfer history data appended for: https://www.transfermarkt.com/nawaf-al-boushail/profil/spieler/821377.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-majrashi/profil/spieler/193170.
Transfer history data appended for: https://www.transfermarkt.com/mitchell-te-vrede/profil/spieler/79127.
Transfer history data appended for: https://www.transfermarkt.com/bashkim-kadrii/profil/spieler/91851.
Transfer history data appended for: https://www.transfermarkt.com/majed-omar-kanabah/profil/spieler/209515.
Transfer history data appended for: https://www.transfermarkt.com/qasim-al-oujami/profil/spieler/362905.
Transfer history data appended for: https://www.transfermarkt.com/sadiq-dnh/profil/spieler/353310.
Transfer history data appended for: https://www.transfermarkt.com/maksym-koval/profil/spieler/120211.
Transfer history data appended for: https://www.transfermarkt.com/tawfiq-buhumaid/profil/spieler/185540.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-zaqan/profil/spieler/229866.
Transfer history data appended for: https://www.transfermarkt.com/fahad-m-al-harbi/profil/spieler/433919.

Transfer history data appended for: https://www.transfermarkt.com/sofiane-bendebka/profil/spieler/248250.
Transfer history data appended for: https://www.transfermarkt.com/amaar-al-dohaim/profil/spieler/314859.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-yousef/profil/spieler/180926.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-dhaw/profil/spieler/536974.
Transfer history data appended for: https://www.transfermarkt.com/gustav-wikheim/profil/spieler/180767.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-al-shereid/profil/spieler/435043.
Transfer history data appended for: https://www.transfermarkt.com/hussien-hawsawi/profil/spieler/263699.
Transfer history data appended for: https://www.transfermarkt.com/khalid-al-kabi/profil/spieler/326012.
Transfer history data appended for: https://www.transfermarkt.com/julio-tavares/profil/spieler/216426.
Transfer history data appended for: https://www.transfermarkt.com/alexander-merkel/profil/spieler/86926.
Transfer history data appended for: https://www.transfermarkt.com/shaye-sharahili/profil/spieler/153232.
Transfer history data appended for: https://www.transfermarkt.com/meshal-khayrallah/profil/spieler/264720.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-ghaleb/profil/spieler/153225.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-mahdi-al-bassas/profil/spieler/193164.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-ashraf/profil/spieler/572667.
Transfer history data appended for: https://www.transfermarkt.com/awadh-khrees/profil/spieler/166307.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-saiari/profil/spieler/321046.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-qahtani/profil/spieler/315632.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-malayekah/profil/spieler/172678.
Transfer history data appended for: https://www.transfermarkt.com/tariq-al-kabe/profil/spieler/364475.
Transfer history data appended for: https://www.transfermarkt.com/khaled-hussein-daghriri/profil/spieler/455983.
Transfer history data appended for: https://www.transfermarkt.com/guilherme-augusto/profil/spieler/444920.
Transfer history data appended for: https://www.transfermarkt.com/hicham-faik/profil/spieler/228572.
Transfer history data appended for: https://www.transfermarkt.com/mishari-al-thmali/profil/spieler/359355.
Transfer history data appended for: https://www.transfermarkt.com/doaihy-al-sahli/profil/spieler/461127.
Transfer history data appended for: https://www.transfermarkt.com/igor-rossi/profil/spieler/130616.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-qasem/profil/spieler/288390.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-kassar/profil/spieler/177956.
Transfer history data appended for: https://www.transfermarkt.com/raphael-silva/profil/spieler/280283.
Transfer history data appended for: https://www.transfermarkt.com/hussain-salem/profil/spieler/282720.
Transfer history data appended for: https://www.transfermarkt.com/saleh-al-qumayzi/profil/spieler/184152.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-bahri/profil/spieler/441177.
Transfer history data appended for: https://www.transfermarkt.com/saad-al-salouli/profil/spieler/206060.
Transfer history data appended for: https://www.transfermarkt.com/saeed-al-rubaie/profil/spieler/213257.
Transfer history data appended for: https://www.transfermarkt.com/majed-al-najrani/profil/spieler/264827.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-salem/profil/spieler/270377.
Transfer history data appended for: https://www.transfermarkt.com/naim-sliti/profil/spieler/184491.
Transfer history data appended for: https://www.transfermarkt.com/hazzaa-ibrahim-al-hazzaa/profil/spieler/270375.
Transfer history data appended for: https://www.transfermarkt.com/hussein-halawani/profil/spieler/522644.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-khatib/profil/spieler/462162.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-majrashi/profil/spieler/500321.
Transfer history data appended for: https://www.transfermarkt.com/souza/profil/spieler/107259.
Transfer history data appended for: https://www.transfermarkt.com/karol-mets/profil/spieler/139304.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-alghamdi/profil/spieler/671043.
Transfer history data appended for: https://www.transfermarkt.com/fahd-ghazi/profil/spieler/451929.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-mohannashi/profil/spieler/593334.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-saleh/profil/spieler/260850.
Transfer history data appended for: https://www.transfermarkt.com/mahar-sharoumah/profil/spieler/543780.
Transfer history data appended for: https://www.transfermarkt.com/hamed-al-ghamdi/profil/spieler/593337.
Transfer history data appended for: https://www.transfermarkt.com/walid-azarou/profil/spieler/471776.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-khaybari/profil/spieler/324634.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-kuwaykibi/profil/spieler/264888.
Transfer history data appended for: https://www.transfermarkt.com/ali-abdullah-hazazi/profil/spieler/153172.
Transfer history data appended for: https://www.transfermarkt.com/ali-fouad-masrahi/profil/spieler/153353.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-al-wasli/profil/spieler/500195.
Transfer history data appended for: https://www.transfermarkt.com/waleed-abdullah/profil/spieler/86282.
Transfer history data appended for: https://www.transfermarkt.com/ayman-yahya/profil/spieler/735815.
Transfer history data appended for: https://www.transfermarkt.com/abdulelah-al-amri/profil/spieler/509894.
Transfer history data appended for: https://www.transfermarkt.com/mukhtar-ali/profil/spieler/258911.
Transfer history data appended for: https://www.transfermarkt.com/abderazak-hamdallah/profil/spieler/235052.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-al-alawi/profil/spieler/817684.
Transfer history data appended for: https://www.transfermarkt.com/abdulmajeed-al-sulaiheem/profil/spieler/324633.
Transfer history data appended for: https://www.transfermarkt.com/khalid-al-ghannam/profil/spieler/631923.
Transfer history data appended for: https://www.transfermarkt.com/maicon/profil/spieler/84695.
Transfer history data appended for: https://www.transfermarkt.com/brad-jones/profil/spieler/4042.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-khaibari/profil/spieler/437903.
Transfer history data appended for: https://www.transfermarkt.com/raed-al-ghamdi/profil/spieler/177998.
Transfer history data appended for: https://www.transfermarkt.com/osama-al-khalaf/profil/spieler/364392.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-al-dosari/profil/spieler/474967.
Transfer history data appended for: https://www.transfermarkt.com/jin-su-kim/profil/spieler/132529.
Transfer history data appended for: https://www.transfermarkt.com/khalid-al-ghuwainem/profil/spieler/707717.
Transfer history data appended for: https://www.transfermarkt.com/petros/profil/spieler/200558.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-al-obaid/profil/spieler/264828.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-hassan/profil/spieler/141805.
Transfer history data appended for: https://www.transfermarkt.com/firas-al-buraikan/profil/spieler/631922.
Transfer history data appended for: https://www.transfermarkt.com/yahia-al-shehri/profil/spieler/150788.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-oujami/profil/spieler/264909.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-al-dawsari/profil/spieler/153351.

Transfer history data appended for: https://www.transfermarkt.com/gonzalo-martinez/profil/spieler/281405.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-madu/profil/spieler/265940.
Transfer history data appended for: https://www.transfermarkt.com/abdulfattah-asiri/profil/spieler/264236.
Transfer history data appended for: https://www.transfermarkt.com/sultan-al-ghannam/profil/spieler/435045.
Transfer history data appended for: https://www.transfermarkt.com/waleed-bakshween/profil/spieler/147869.
Transfer history data appended for: https://www.transfermarkt.com/jaber-issa/profil/spieler/590630.
Transfer history data appended for: https://www.transfermarkt.com/radhi-al-otaibe/profil/spieler/672388.
Transfer history data appended for: https://www.transfermarkt.com/alberto-botia/profil/spieler/53077.
Transfer history data appended for: https://www.transfermarkt.com/alaa-al-hajji/profil/spieler/443937.
Transfer history data appended for: https://www.transfermarkt.com/youssoufou-niakate/profil/spieler/351990.
Transfer history data appended for: https://www.transfermarkt.com/pedro-henrique/profil/spieler/164015.
Transfer history data appended for: https://www.transfermarkt.com/dimitri-petratos/profil/spieler/153882.
Transfer history data appended for: https://www.transfermarkt.com/hernani/profil/spieler/172142.
Transfer history data appended for: https://www.transfermarkt.com/hatem-bilal/profil/spieler/164485.
Transfer history data appended for: https://www.transfermarkt.com/ayman-al-khalif/profil/spieler/470933.
Transfer history data appended for: https://www.transfermarkt.com/faris-abdi/profil/spieler/578992.
Transfer history data appended for: https://www.transfermarkt.com/jaber-nasser-asiri/profil/spieler/561472.
Transfer history data appended for: https://www.transfermarkt.com/hamad-al-jayzani/profil/spieler/364445.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-zubaidi/profil/spieler/193155.
Transfer history data appended for: https://www.transfermarkt.com/anselmo/profil/spieler/114341.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-hafith/profil/spieler/193151.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-araf/profil/spieler/153363.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-jaber/profil/spieler/490819.
Transfer history data appended for: https://www.transfermarkt.com/yassen-hamza/profil/spieler/213909.
Transfer history data appended for: https://www.transfermarkt.com/meshary-al-qahtani/profil/spieler/686453.
Transfer history data appended for: https://www.transfermarkt.com/raghed-najjar/profil/spieler/447495.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-amri/profil/spieler/364470.
Transfer history data appended for: https://www.transfermarkt.com/abdulkarim-al-qahtani/profil/spieler/434685.
Transfer history data appended for: https://www.transfermarkt.com/basem-atallah/profil/spieler/211656.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-oaisher/profil/spieler/187950.
Transfer history data appended for: https://www.transfermarkt.com/sultan-al-sawadi/profil/spieler/224234.
Transfer history data appended for: https://www.transfermarkt.com/hussain-ahmed-al-eissa/profil/spieler/498115.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-qarni/profil/spieler/164592.
Transfer history data appended for: https://www.transfermarkt.com/iago-santos/profil/spieler/332220.
Transfer history data appended for: https://www.transfermarkt.com/faisal-darwish/profil/spieler/165394.
Transfer history data appended for: https://www.transfermarkt.com/cedric-amissi/profil/spieler/166359.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-namer/profil/spieler/572683.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-al-zubaidi/profil/spieler/153841.
Transfer history data appended for: https://www.transfermarkt.com/yaseen-barnawi/profil/spieler/359354.
Transfer history data appended for: https://www.transfermarkt.com/mitchell-duke/profil/spieler/177775.
Transfer history data appended for: https://www.transfermarkt.com/leandre-tawamba/profil/spieler/242564.
Transfer history data appended for: https://www.transfermarkt.com/fahad-al-rashidi/profil/spieler/509912.
Transfer history data appended for: https://www.transfermarkt.com/rayan-al-mousa/profil/spieler/153212.
Transfer history data appended for: https://www.transfermarkt.com/hasan-kadesh/profil/spieler/260859.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-jawaey/profil/spieler/177477.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-abusabaan/profil/spieler/183512.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-reshoudi/profil/spieler/159441.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-asiri/profil/spieler/209499.
Transfer history data appended for: https://www.transfermarkt.com/sandro-manoel/profil/spieler/70119.
Transfer history data appended for: https://www.transfermarkt.com/malik-al-abdulmonem/profil/spieler/741039.
Transfer history data appended for: https://www.transfermarkt.com/sumaihan-al-nabit/profil/spieler/478531.
Transfer history data appended for: https://www.transfermarkt.com/cassio/profil/spieler/53841.
Transfer history data appended for: https://www.transfermarkt.com/nawaf-al-sabhi/profil/spieler/177957.
Transfer history data appended for: https://www.transfermarkt.com/hamdan-al-ruwaili/profil/spieler/364115.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-sahlawi/profil/spieler/150787.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-shanqiti/profil/spieler/631931.
Transfer history data appended for: https://www.transfermarkt.com/hussein-shaian/profil/spieler/153585.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-sane/profil/spieler/193584.
Transfer history data appended for: https://www.transfermarkt.com/nawaf-al-abed/profil/spieler/149643.
Transfer history data appended for: https://www.transfermarkt.com/igor-lichnovsky/profil/spieler/209513.
Transfer history data appended for: https://www.transfermarkt.com/khalid-al-ghamdi/profil/spieler/153148.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-salem/profil/spieler/142408.
Transfer history data appended for: https://www.transfermarkt.com/fawaz-al-sagour/profil/spieler/364450.
Transfer history data appended for: https://www.transfermarkt.com/giedrius-arlauskis/profil/spieler/69001.
Transfer history data appended for: https://www.transfermarkt.com/cristian-guanca/profil/spieler/167423.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-hamdan/profil/spieler/68626.
Transfer history data appended for: https://www.transfermarkt.com/kahlid-al-dubaysh/profil/spieler/735816.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-zoari/profil/spieler/126330.
Transfer history data appended for: https://www.transfermarkt.com/hassan-m-tambakti/profil/spieler/509897.
Transfer history data appended for: https://www.transfermarkt.com/jamal-bajandooh/profil/spieler/314865.
Transfer history data appended for: https://www.transfermarkt.com/abdulilah-al-shaheen/profil/spieler/438742.
Transfer history data appended for: https://www.transfermarkt.com/nasser-al-omran/profil/spieler/606820.
Transfer history data appended for: https://www.transfermarkt.com/makhete-diop/profil/spieler/124757.
Transfer history data appended for: https://www.transfermarkt.com/ever-banega/profil/spieler/12249.
Transfer history data appended for: https://www.transfermarkt.com/abdulmalek-al-khaibri/profil/spieler/153526.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-shamekh/profil/spieler/359347.
Transfer history data appended for: https://www.transfermarkt.com/waleed-hizam-al-oneazi/profil/spieler/451135.
Transfer history data appended for: https://www.transfermarkt.com/marwan-al-haidari/profil/spieler/821378.

Transfer history data appended for: https://www.transfermarkt.com/zaid-al-bawardi/profil/spieler/509896.
Transfer history data appended for: https://www.transfermarkt.com/alfred-ndiaye/profil/spieler/77737.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-sharahili/profil/spieler/319552.
Transfer history data appended for: https://www.transfermarkt.com/turki-al-ammar/profil/spieler/31671.
Transfer history data appended for: https://www.transfermarkt.com/fabio-martins/profil/spieler/223029.
Transfer history data appended for: https://www.transfermarkt.com/abdulmalik-al-shammari/profil/spieler/452889.
Transfer history data appended for: https://www.transfermarkt.com/xandro-schenk/profil/spieler/226026.
Transfer history data appended for: https://www.transfermarkt.com/youssef-el-jebli/profil/spieler/324921.
Transfer history data appended for: https://www.transfermarkt.com/zakaria-sami/profil/spieler/265021.
Transfer history data appended for: https://www.transfermarkt.com/hassan-al-zafawi/profil/spieler/267967.
Transfer history data appended for: https://www.transfermarkt.com/saleh-dallabah-al-abbas/profil/spieler/675868.
Transfer history data appended for: https://www.transfermarkt.com/hassan-raghfawi/profil/spieler/153417.
Transfer history data appended for: https://www.transfermarkt.com/renato-chaves/profil/spieler/64870.
Transfer history data appended for: https://www.transfermarkt.com/khaleem-hyland/profil/spieler/77663.
Transfer history data appended for: https://www.transfermarkt.com/rakan-al-shamlan-alanaze/profil/spieler/560974.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-damdam/profil/spieler/436500.
Transfer history data appended for: https://www.transfermarkt.com/daifallah-al-qarni/profil/spieler/436731.
Transfer history data appended for: https://www.transfermarkt.com/mashari-gdiaa-al-anazi/profil/spieler/264882.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-rayhi/profil/spieler/273432.
Transfer history data appended for: https://www.transfermarkt.com/muteab-mansour-al-mutairi/profil/spieler/31411.
Transfer history data appended for: https://www.transfermarkt.com/ismael-al-maghrabi/profil/spieler/363258.
Transfer history data appended for: https://www.transfermarkt.com/maher-othman/profil/spieler/262835.
Transfer history data appended for: https://www.transfermarkt.com/saad-al-khairy/profil/spieler/487475.
Transfer history data appended for: https://www.transfermarkt.com/hassan-sharaheli/profil/spieler/462156.
Transfer history data appended for: https://www.transfermarkt.com/naif-al-mas/profil/spieler/631929.
Transfer history data appended for: https://www.transfermarkt.com/fabio-abreu/profil/spieler/292398.
Transfer history data appended for: https://www.transfermarkt.com/hani-al-nahedh/profil/spieler/314860.
Transfer history data appended for: https://www.transfermarkt.com/soltan-ghneman-al-mutairi/profil/spieler/451197.
Transfer history data appended for: https://www.transfermarkt.com/mansour-al-najjar/profil/spieler/453583.
Transfer history data appended for: https://www.transfermarkt.com/edson/profil/spieler/103146.
Transfer history data appended for: https://www.transfermarkt.com/fahad-al-johani/profil/spieler/209741.
Transfer history data appended for: https://www.transfermarkt.com/majed-al-khaibari/profil/spieler/269540.
Transfer history data appended for: https://www.transfermarkt.com/nayef-abdullah-hazazi/profil/spieler/264831.
Transfer history data appended for: https://www.transfermarkt.com/jack-duncan/profil/spieler/171382.
Transfer history data appended for: https://www.transfermarkt.com/faisal-al-masrahi/profil/spieler/209532.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-al-sefre/profil/spieler/686019.
Transfer history data appended for: https://www.transfermarkt.com/faraj-al-ghashayan/profil/spieler/631918.
Transfer history data appended for: https://www.transfermarkt.com/sultan-mofareh-al-dosari/profil/spieler/209657.
Transfer history data appended for: https://www.transfermarkt.com/turki-sufyani/profil/spieler/362097.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-fraidi/profil/spieler/86769.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-hadhereti/profil/spieler/364479.
Transfer history data appended for: https://www.transfermarkt.com/fawaz-fallatah/profil/spieler/222435.
Transfer history data appended for: https://www.transfermarkt.com/uros-vitas/profil/spieler/138512.
Transfer history data appended for: https://www.transfermarkt.com/mihai-bordeianu/profil/spieler/210059.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-waked/profil/spieler/308096.
Transfer history data appended for: https://www.transfermarkt.com/omar-al-zayni/profil/spieler/164598.
Transfer history data appended for: https://www.transfermarkt.com/andria/profil/spieler/171194.
Transfer history data appended for: https://www.transfermarkt.com/wesam-waheab/profil/spieler/342451.
Transfer history data appended for: https://www.transfermarkt.com/walead-al-shangeati/profil/spieler/514766.
Transfer history data appended for: https://www.transfermarkt.com/riad-sharahili/profil/spieler/187951.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-al-barakah/profil/spieler/212637.
Transfer history data appended for: https://www.transfermarkt.com/abdelali-mhamdi/profil/spieler/353476.
Transfer history data appended for: https://www.transfermarkt.com/moaath-afana/profil/spieler/527056.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-shammari/profil/spieler/211394.
Transfer history data appended for: https://www.transfermarkt.com/carlos-strandberg/profil/spieler/252689.
Transfer history data appended for: https://www.transfermarkt.com/ahmad-al-hbeab/profil/spieler/343299.
Transfer history data appended for: https://www.transfermarkt.com/amine-attouchi/profil/spieler/234993.
Transfer history data appended for: https://www.transfermarkt.com/saad-bguir/profil/spieler/253752.
Transfer history data appended for: https://www.transfermarkt.com/craig-goodwin/profil/spieler/214798.
Transfer history data appended for: https://www.transfermarkt.com/thaar-al-otaibi/profil/spieler/816378.
Transfer history data appended for: https://www.transfermarkt.com/khalid-awaji/profil/spieler/209580.
Transfer history data appended for: https://www.transfermarkt.com/ammar-al-najjar/profil/spieler/487472.
Transfer history data appended for: https://www.transfermarkt.com/saleh-jamaan-al-amri/profil/spieler/229940.
Transfer history data appended for: https://www.transfermarkt.com/saeed-al-hamsl/profil/spieler/141976.
Transfer history data appended for: https://www.transfermarkt.com/osama-ashoor/profil/spieler/153218.
Transfer history data appended for: https://www.transfermarkt.com/mehdi-tahrat/profil/spieler/238584.
Transfer history data appended for: https://www.transfermarkt.com/fahd-mohammed-al-jumaiya/profil/spieler/537565.
Transfer history data appended for: https://www.transfermarkt.com/sari-amro/profil/spieler/267968.
Transfer history data appended for: https://www.transfermarkt.com/karam-barnawi/profil/spieler/160599.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-mazidi/profil/spieler/185669.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-al-juman/profil/spieler/536976.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-subaie/profil/spieler/441185.
Transfer history data appended for: https://www.transfermarkt.com/khaled-al-khathalan/profil/spieler/153568.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-ghamdi/profil/spieler/466416.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-miletic/profil/spieler/153657.
Transfer history data appended for: https://www.transfermarkt.com/azzedine-doukha/profil/spieler/175462.
Transfer history data appended for: https://www.transfermarkt.com/ahmad-al-rehaili/profil/spieler/352715.
Transfer history data appended for: https://www.transfermarkt.com/aqel-al-sahbi/profil/spieler/159567.

Transfer history data appended for: https://www.transfermarkt.com/hussain-al-nakhli/profil/spieler/364358.
Transfer history data appended for: https://www.transfermarkt.com/husein-al-shuwaish/profil/spieler/185538.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-reman/profil/spieler/549599.
Transfer history data appended for: https://www.transfermarkt.com/abdulfattah-adam/profil/spieler/265966.
Transfer history data appended for: https://www.transfermarkt.com/karim-el-berkaoui/profil/spieler/362278.
Transfer history data appended for: https://www.transfermarkt.com/ahmad-al-zaein/profil/spieler/159436.
Transfer history data appended for: https://www.transfermarkt.com/awad-khamis/profil/spieler/265939.
Transfer history data appended for: https://www.transfermarkt.com/muteb-al-mutlaq/profil/spieler/434671.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-al-ghamdi/profil/spieler/288389.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-sahli/profil/spieler/331316.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-fahad/profil/spieler/359350.
Transfer history data appended for: https://www.transfermarkt.com/sultan-al-farhan/profil/spieler/268095.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-dawsari/profil/spieler/672389.
Transfer history data appended for: https://www.transfermarkt.com/jalal-daoudi/profil/spieler/236322.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-yahya-maghrahi/profil/spieler/530973.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-nikolic/profil/spieler/260543.
Transfer history data appended for: https://www.transfermarkt.com/rashed-al-rahab/profil/spieler/93466.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-shoraimi/profil/spieler/646003.
Transfer history data appended for: https://www.transfermarkt.com/mutaz-tmbacti/profil/spieler/267978.
Transfer history data appended for: https://www.transfermarkt.com/hamed-al-maghati/profil/spieler/364452.
Transfer history data appended for: https://www.transfermarkt.com/saif-hussein-al-qeshta/profil/spieler/614213.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-nahiri/profil/spieler/236340.
Transfer history data appended for: https://www.transfermarkt.com/saad-al-harbi/profil/spieler/210192.
Transfer history data appended for: https://www.transfermarkt.com/saeed-al-qarni/profil/spieler/153245.
Transfer history data appended for: https://www.transfermarkt.com/bastos/profil/spieler/195810.
Transfer history data appended for: https://www.transfermarkt.com/amer-haroon/profil/spieler/359768.
Transfer history data appended for: https://www.transfermarkt.com/hassan-al-harbi/profil/spieler/364593.
Transfer history data appended for: https://www.transfermarkt.com/getterson/profil/spieler/446043.
Transfer history data appended for: https://www.transfermarkt.com/khaled-al-zaylai/profil/spieler/153217.
Transfer history data appended for: https://www.transfermarkt.com/ali-khorrami/profil/spieler/262847.
Transfer history data appended for: https://www.transfermarkt.com/saleh-al-omrani/profil/spieler/153155.
Transfer history data appended for: https://www.transfermarkt.com/amin-bukhari/profil/spieler/509875.
Transfer history data appended for: https://www.transfermarkt.com/faisal-al-jamaan/profil/spieler/153525.
Transfer history data appended for: https://www.transfermarkt.com/ismeal-musalmi/profil/spieler/31672.
Transfer history data appended for: https://www.transfermarkt.com/fareed-al-harbi/profil/spieler/441018.
Transfer history data appended for: https://www.transfermarkt.com/filip-bradaric/profil/spieler/238486.
Transfer history data appended for: https://www.transfermarkt.com/juanpi-anor/profil/spieler/256680.
Transfer history data appended for: https://www.transfermarkt.com/omar-al-suhaimi/profil/spieler/435044.
Transfer history data appended for: https://www.transfermarkt.com/amadou-moutari/profil/spieler/213035.
Transfer history data appended for: https://www.transfermarkt.com/saad-al-saleh/profil/spieler/364464.
Transfer history data appended for: https://www.transfermarkt.com/yahia-al-kabie/profil/spieler/164597.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-katheri/profil/spieler/364592.
Transfer history data appended for: https://www.transfermarkt.com/nawaf-al-farshan/profil/spieler/707775.
Transfer history data appended for: https://www.transfermarkt.com/rabea-al-sofiani/profil/spieler/153584.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-fouad/profil/spieler/469222.
Transfer history data appended for: https://www.transfermarkt.com/saphir-taider/profil/spieler/144779.
Transfer history data appended for: https://www.transfermarkt.com/saud-abdulhamid/profil/spieler/631927.
Transfer history data appended for: https://www.transfermarkt.com/fahad-al-muwallad/profil/spieler/193153.
Transfer history data appended for: https://www.transfermarkt.com/romarinho/profil/spieler/193925.
Transfer history data appended for: https://www.transfermarkt.com/hamdan-al-shammrani/profil/spieler/505496.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-al-jebreen/profil/spieler/209493.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-hegazy/profil/spieler/111524.
Transfer history data appended for: https://www.transfermarkt.com/abdulelah-al-malki/profil/spieler/390855.
Transfer history data appended for: https://www.transfermarkt.com/ziyad-al-sahafi/profil/spieler/421391.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-grohe/profil/spieler/52313.
Transfer history data appended for: https://www.transfermarkt.com/fawaz-al-qarni/profil/spieler/193167.
Transfer history data appended for: https://www.transfermarkt.com/abdulmajid-al-sawat/profil/spieler/434684.
Transfer history data appended for: https://www.transfermarkt.com/abdulmohsin-fallatah/profil/spieler/271842.
Transfer history data appended for: https://www.transfermarkt.com/essam-al-muwallad/profil/spieler/692496.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-ali-al-bishi/profil/spieler/153350.
Transfer history data appended for: https://www.transfermarkt.com/garry-rodrigues/profil/spieler/170895.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-al-obood/profil/spieler/441191.
Transfer history data appended for: https://www.transfermarkt.com/khaled-al-sumairi/profil/spieler/470011.
Transfer history data appended for: https://www.transfermarkt.com/bruno-henrique/profil/spieler/277335.
Transfer history data appended for: https://www.transfermarkt.com/omar-hawsawi/profil/spieler/180216.
Transfer history data appended for: https://www.transfermarkt.com/hamad-al-mansour/profil/spieler/364454.
Transfer history data appended for: https://www.transfermarkt.com/aleksandar-prijovic/profil/spieler/61505.
Transfer history data appended for: https://www.transfermarkt.com/haroune-camara/profil/spieler/31406.
Transfer history data appended for: https://www.transfermarkt.com/rakan-al-najar/profil/spieler/112813.
Transfer history data appended for: https://www.transfermarkt.com/muhannad-shanqeeti/profil/spieler/229879.
Transfer history data appended for: https://www.transfermarkt.com/karim-el-ahmadi/profil/spieler/25523.
Transfer history data appended for: https://www.transfermarkt.com/scott-allan/profil/spieler/60904.
Transfer history data appended for: https://www.transfermarkt.com/lewis-stevenson/profil/spieler/42547.
Transfer history data appended for: https://www.transfermarkt.com/martin-boyle/profil/spieler/140554.
Transfer history data appended for: https://www.transfermarkt.com/paul-hanlon/profil/spieler/60792.
Transfer history data appended for: https://www.transfermarkt.com/paul-mcginn/profil/spieler/120070.
Transfer history data appended for: https://www.transfermarkt.com/craig-samson/profil/spieler/12752.
Transfer history data appended for: https://www.transfermarkt.com/stephen-mcginn/profil/spieler/51430.
Transfer history data appended for: https://www.transfermarkt.com/jamie-gullan/profil/spieler/346643.

Transfer history data appended for: https://www.transfermarkt.com/david-gray/profil/spieler/37678.
Transfer history data appended for: https://www.transfermarkt.com/joe-newell/profil/spieler/185342.
Transfer history data appended for: https://www.transfermarkt.com/josh-doig/profil/spieler/567129.
Transfer history data appended for: https://www.transfermarkt.com/melker-hallberg/profil/spieler/203773.
Transfer history data appended for: https://www.transfermarkt.com/kyle-magennis/profil/spieler/399258.
Transfer history data appended for: https://www.transfermarkt.com/christian-doidge/profil/spieler/255353.
Transfer history data appended for: https://www.transfermarkt.com/dillon-barnes/profil/spieler/259151.
Transfer history data appended for: https://www.transfermarkt.com/ofir-marciano/profil/spieler/112008.
Transfer history data appended for: https://www.transfermarkt.com/stevie-mallan/profil/spieler/331089.
Transfer history data appended for: https://www.transfermarkt.com/kevin-nisbet/profil/spieler/360661.
Transfer history data appended for: https://www.transfermarkt.com/jamie-murphy/profil/spieler/51730.
Transfer history data appended for: https://www.transfermarkt.com/sean-mackie/profil/spieler/374984.
Transfer history data appended for: https://www.transfermarkt.com/ryan-porteous/profil/spieler/446093.
Transfer history data appended for: https://www.transfermarkt.com/drey-wright/profil/spieler/238468.
Transfer history data appended for: https://www.transfermarkt.com/alex-gogic/profil/spieler/225393.
Transfer history data appended for: https://www.transfermarkt.com/darren-mcgregor/profil/spieler/43753.
Transfer history data appended for: https://www.transfermarkt.com/allan-campbell/profil/spieler/347619.
Transfer history data appended for: https://www.transfermarkt.com/chris-long/profil/spieler/183298.
Transfer history data appended for: https://www.transfermarkt.com/jordan-white/profil/spieler/124577.
Transfer history data appended for: https://www.transfermarkt.com/barry-maguire/profil/spieler/443541.
Transfer history data appended for: https://www.transfermarkt.com/robbie-crawford/profil/spieler/171374.
Transfer history data appended for: https://www.transfermarkt.com/callum-lang/profil/spieler/425865.
Transfer history data appended for: https://www.transfermarkt.com/declan-gallagher/profil/spieler/107544.
Transfer history data appended for: https://www.transfermarkt.com/dean-cornelius/profil/spieler/592473.
Transfer history data appended for: https://www.transfermarkt.com/tony-watt/profil/spieler/132764.
Transfer history data appended for: https://www.transfermarkt.com/liam-polworth/profil/spieler/132209.
Transfer history data appended for: https://www.transfermarkt.com/jordan-archer/profil/spieler/177952.
Transfer history data appended for: https://www.transfermarkt.com/mark-ohara/profil/spieler/235780.
Transfer history data appended for: https://www.transfermarkt.com/stephen-odonnell/profil/spieler/186337.
Transfer history data appended for: https://www.transfermarkt.com/david-devine/profil/spieler/674692.
Transfer history data appended for: https://www.transfermarkt.com/nathan-mcginley/profil/spieler/387355.
Transfer history data appended for: https://www.transfermarkt.com/sherwin-seedorf/profil/spieler/411544.
Transfer history data appended for: https://www.transfermarkt.com/aaron-chapman/profil/spieler/270571.
Transfer history data appended for: https://www.transfermarkt.com/bevis-mugabi/profil/spieler/226971.
Transfer history data appended for: https://www.transfermarkt.com/ricki-lamie/profil/spieler/216270.
Transfer history data appended for: https://www.transfermarkt.com/liam-grimshaw/profil/spieler/247263.
Transfer history data appended for: https://www.transfermarkt.com/jake-hastie/profil/spieler/392375.
Transfer history data appended for: https://www.transfermarkt.com/yusuf-hussain/profil/spieler/592472.
Transfer history data appended for: https://www.transfermarkt.com/scott-fox/profil/spieler/60923.
Transfer history data appended for: https://www.transfermarkt.com/charles-dunne/profil/spieler/220496.
Transfer history data appended for: https://www.transfermarkt.com/trevor-carson/profil/spieler/41131.
Transfer history data appended for: https://www.transfermarkt.com/liam-donnelly/profil/spieler/211121.
Transfer history data appended for: https://www.transfermarkt.com/devante-cole/profil/spieler/186924.
Transfer history data appended for: https://www.transfermarkt.com/max-johnston/profil/spieler/652632.
Transfer history data appended for: https://www.transfermarkt.com/jake-carroll/profil/spieler/182242.
Transfer history data appended for: https://www.transfermarkt.com/tom-rogic/profil/spieler/213672.
Transfer history data appended for: https://www.transfermarkt.com/odsonne-edouard/profil/spieler/344152.
Transfer history data appended for: https://www.transfermarkt.com/luca-connell/profil/spieler/580027.
Transfer history data appended for: https://www.transfermarkt.com/ismaila-soro/profil/spieler/466765.
Transfer history data appended for: https://www.transfermarkt.com/callum-mcgregor/profil/spieler/120977.
Transfer history data appended for: https://www.transfermarkt.com/mikey-johnston/profil/spieler/297257.
Transfer history data appended for: https://www.transfermarkt.com/hatem-abd-elhamed/profil/spieler/176990.
Transfer history data appended for: https://www.transfermarkt.com/shane-duffy/profil/spieler/119269.
Transfer history data appended for: https://www.transfermarkt.com/manny-perez/profil/spieler/502442.
Transfer history data appended for: https://www.transfermarkt.com/scott-bain/profil/spieler/85627.
Transfer history data appended for: https://www.transfermarkt.com/ryan-christie/profil/spieler/188077.
Transfer history data appended for: https://www.transfermarkt.com/greg-taylor/profil/spieler/362562.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-elyounoussi/profil/spieler/186644.
Transfer history data appended for: https://www.transfermarkt.com/jeremie-frimpong/profil/spieler/484547.
Transfer history data appended for: https://www.transfermarkt.com/olivier-ntcham/profil/spieler/224088.
Transfer history data appended for: https://www.transfermarkt.com/patryk-klimala/profil/spieler/387153.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-ajer/profil/spieler/328658.
Transfer history data appended for: https://www.transfermarkt.com/david-turnbull/profil/spieler/345760.
Transfer history data appended for: https://www.transfermarkt.com/christopher-jullien/profil/spieler/201737.
Transfer history data appended for: https://www.transfermarkt.com/anthony-ralston/profil/spieler/388171.
Transfer history data appended for: https://www.transfermarkt.com/albian-ajeti/profil/spieler/195906.
Transfer history data appended for: https://www.transfermarkt.com/james-forrest/profil/spieler/84992.
Transfer history data appended for: https://www.transfermarkt.com/leigh-griffiths/profil/spieler/45611.
Transfer history data appended for: https://www.transfermarkt.com/nir-bitton/profil/spieler/129788.
Transfer history data appended for: https://www.transfermarkt.com/scott-brown/profil/spieler/12688.
Transfer history data appended for: https://www.transfermarkt.com/vasilis-barkas/profil/spieler/248658.
Transfer history data appended for: https://www.transfermarkt.com/jak-alnwick/profil/spieler/128895.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-obika/profil/spieler/61838.
Transfer history data appended for: https://www.transfermarkt.com/marcus-fraser/profil/spieler/132203.
Transfer history data appended for: https://www.transfermarkt.com/dean-lyness/profil/spieler/103616.
Transfer history data appended for: https://www.transfermarkt.com/kristian-dennis/profil/spieler/67375.
Transfer history data appended for: https://www.transfermarkt.com/conor-mccarthy/profil/spieler/382686.
Transfer history data appended for: https://www.transfermarkt.com/kyle-mcallister/profil/spieler/399260.
Transfer history data appended for: https://www.transfermarkt.com/cameron-macpherson/profil/spieler/399257.
Transfer history data appended for: https://www.transfermarkt.com/lewis-jamieson/profil/spieler/694355.

Transfer history data appended for: https://www.transfermarkt.com/danny-finlayson/profil/spieler/424019.
Transfer history data appended for: https://www.transfermarkt.com/ryan-flynn/profil/spieler/45228.
Transfer history data appended for: https://www.transfermarkt.com/brandon-mason/profil/spieler/479942.
Transfer history data appended for: https://www.transfermarkt.com/jake-doyle-hayes/profil/spieler/340921.
Transfer history data appended for: https://www.transfermarkt.com/nathan-sheron/profil/spieler/475441.
Transfer history data appended for: https://www.transfermarkt.com/peter-urminsky/profil/spieler/454574.
Transfer history data appended for: https://www.transfermarkt.com/jamie-mcgrath/profil/spieler/344107.
Transfer history data appended for: https://www.transfermarkt.com/sam-foley/profil/spieler/48226.
Transfer history data appended for: https://www.transfermarkt.com/lee-erwin/profil/spieler/161484.
Transfer history data appended for: https://www.transfermarkt.com/junior-morias/profil/spieler/233141.
Transfer history data appended for: https://www.transfermarkt.com/dylan-connolly/profil/spieler/251838.
Transfer history data appended for: https://www.transfermarkt.com/richard-tait/profil/spieler/125746.
Transfer history data appended for: https://www.transfermarkt.com/ethan-erhahon/profil/spieler/463760.
Transfer history data appended for: https://www.transfermarkt.com/joe-shaughnessy/profil/spieler/119574.
Transfer history data appended for: https://www.transfermarkt.com/ilkay-durmus/profil/spieler/119549.
Transfer history data appended for: https://www.transfermarkt.com/kyle-munro/profil/spieler/456355.
Transfer history data appended for: https://www.transfermarkt.com/andy-winter/profil/spieler/567115.
Transfer history data appended for: https://www.transfermarkt.com/shaun-want/profil/spieler/332866.
Transfer history data appended for: https://www.transfermarkt.com/tunde-owolabi/profil/spieler/797358.
Transfer history data appended for: https://www.transfermarkt.com/aaron-martin/profil/spieler/136581.
Transfer history data appended for: https://www.transfermarkt.com/nathan-thomas/profil/spieler/222024.
Transfer history data appended for: https://www.transfermarkt.com/david-templeton/profil/spieler/54268.
Transfer history data appended for: https://www.transfermarkt.com/ross-callachan/profil/spieler/151213.
Transfer history data appended for: https://www.transfermarkt.com/lewis-smith/profil/spieler/446712.
Transfer history data appended for: https://www.transfermarkt.com/ryan-scully/profil/spieler/94686.
Transfer history data appended for: https://www.transfermarkt.com/ronan-hughes/profil/spieler/351624.
Transfer history data appended for: https://www.transfermarkt.com/hakeem-odoffin/profil/spieler/399340.
Transfer history data appended for: https://www.transfermarkt.com/reegan-mimnaugh/profil/spieler/606603.
Transfer history data appended for: https://www.transfermarkt.com/brian-easton/profil/spieler/45331.
Transfer history data appended for: https://www.transfermarkt.com/ben-stirling/profil/spieler/293761.
Transfer history data appended for: https://www.transfermarkt.com/lee-hodson/profil/spieler/110356.
Transfer history data appended for: https://www.transfermarkt.com/ryan-fulton/profil/spieler/193861.
Transfer history data appended for: https://www.transfermarkt.com/kyle-gourlay/profil/spieler/344905.
Transfer history data appended for: https://www.transfermarkt.com/jamie-hamilton/profil/spieler/567118.
Transfer history data appended for: https://www.transfermarkt.com/david-moyo/profil/spieler/249161.
Transfer history data appended for: https://www.transfermarkt.com/scott-mcmann/profil/spieler/192077.
Transfer history data appended for: https://www.transfermarkt.com/jamie-smith/profil/spieler/622179.
Transfer history data appended for: https://www.transfermarkt.com/charlie-trafford/profil/spieler/272955.
Transfer history data appended for: https://www.transfermarkt.com/will-collar/profil/spieler/335598.
Transfer history data appended for: https://www.transfermarkt.com/george-stanger/profil/spieler/509709.
Transfer history data appended for: https://www.transfermarkt.com/callum-smith/profil/spieler/422425.
Transfer history data appended for: https://www.transfermarkt.com/scott-martin/profil/spieler/330174.
Transfer history data appended for: https://www.transfermarkt.com/justin-johnson/profil/spieler/374016.
Transfer history data appended for: https://www.transfermarkt.com/marios-ogboe/profil/spieler/446302.
Transfer history data appended for: https://www.transfermarkt.com/ross-laidlaw/profil/spieler/150212.
Transfer history data appended for: https://www.transfermarkt.com/regan-charles-cook/profil/spieler/385635.
Transfer history data appended for: https://www.transfermarkt.com/oli-shaw/profil/spieler/369424.
Transfer history data appended for: https://www.transfermarkt.com/ross-munro/profil/spieler/425496.
Transfer history data appended for: https://www.transfermarkt.com/josh-reid/profil/spieler/554365.
Transfer history data appended for: https://www.transfermarkt.com/ross-doohan/profil/spieler/285283.
Transfer history data appended for: https://www.transfermarkt.com/tom-grivosti/profil/spieler/524131.
Transfer history data appended for: https://www.transfermarkt.com/matthew-wright/profil/spieler/530965.
Transfer history data appended for: https://www.transfermarkt.com/iain-vigurs/profil/spieler/59328.
Transfer history data appended for: https://www.transfermarkt.com/ross-stewart/profil/spieler/447995.
Transfer history data appended for: https://www.transfermarkt.com/harry-paton/profil/spieler/395833.
Transfer history data appended for: https://www.transfermarkt.com/jordan-tillson/profil/spieler/251485.
Transfer history data appended for: https://www.transfermarkt.com/jermaine-hylton/profil/spieler/352126.
Transfer history data appended for: https://www.transfermarkt.com/ross-draper/profil/spieler/119332.
Transfer history data appended for: https://www.transfermarkt.com/carl-tremarco/profil/spieler/49560.
Transfer history data appended for: https://www.transfermarkt.com/stephen-kelly/profil/spieler/403572.
Transfer history data appended for: https://www.transfermarkt.com/callum-morris/profil/spieler/62080.
Transfer history data appended for: https://www.transfermarkt.com/michael-gardyne/profil/spieler/43259.
Transfer history data appended for: https://www.transfermarkt.com/ben-williamson/profil/spieler/692381.
Transfer history data appended for: https://www.transfermarkt.com/coll-donaldson/profil/spieler/196229.
Transfer history data appended for: https://www.transfermarkt.com/charlie-lakin/profil/spieler/564048.
Transfer history data appended for: https://www.transfermarkt.com/alex-iacovitti/profil/spieler/287051.
Transfer history data appended for: https://www.transfermarkt.com/keith-watson/profil/spieler/27700.
Transfer history data appended for: https://www.transfermarkt.com/connor-randall/profil/spieler/262545.
Transfer history data appended for: https://www.transfermarkt.com/billy-mckay/profil/spieler/123294.
Transfer history data appended for: https://www.transfermarkt.com/zander-clark/profil/spieler/98067.
Transfer history data appended for: https://www.transfermarkt.com/chris-kane/profil/spieler/161496.
Transfer history data appended for: https://www.transfermarkt.com/stevie-may/profil/spieler/111432.
Transfer history data appended for: https://www.transfermarkt.com/shaun-rooney/profil/spieler/280409.
Transfer history data appended for: https://www.transfermarkt.com/liam-craig/profil/spieler/35531.
Transfer history data appended for: https://www.transfermarkt.com/murray-davidson/profil/spieler/45555.
Transfer history data appended for: https://www.transfermarkt.com/scott-tanser/profil/spieler/268119.
Transfer history data appended for: https://www.transfermarkt.com/michael-ohalloran/profil/spieler/125158.
Transfer history data appended for: https://www.transfermarkt.com/guy-melamed/profil/spieler/142532.
Transfer history data appended for: https://www.transfermarkt.com/callum-hendry/profil/spieler/390156.
Transfer history data appended for: https://www.transfermarkt.com/jamie-mccart/profil/spieler/290801.
Transfer history data appended for: https://www.transfermarkt.com/ali-mccann/profil/spieler/450714.

Transfer history data appended for: https://www.transfermarkt.com/callum-booth/profil/spieler/84979.
Transfer history data appended for: https://www.transfermarkt.com/danny-mcnamara/profil/spieler/647138.
Transfer history data appended for: https://www.transfermarkt.com/craig-conway/profil/spieler/14574.
Transfer history data appended for: https://www.transfermarkt.com/david-wotherspoon/profil/spieler/74861.
Transfer history data appended for: https://www.transfermarkt.com/liam-gordon/profil/spieler/238029.
Transfer history data appended for: https://www.transfermarkt.com/elliot-parish/profil/spieler/62645.
Transfer history data appended for: https://www.transfermarkt.com/craig-bryson/profil/spieler/22728.
Transfer history data appended for: https://www.transfermarkt.com/jason-kerr/profil/spieler/340728.
Transfer history data appended for: https://www.transfermarkt.com/aaron-tshibola/profil/spieler/243633.
Transfer history data appended for: https://www.transfermarkt.com/gary-dicker/profil/spieler/67274.
Transfer history data appended for: https://www.transfermarkt.com/colin-doyle/profil/spieler/28728.
Transfer history data appended for: https://www.transfermarkt.com/danny-rogers/profil/spieler/200956.
Transfer history data appended for: https://www.transfermarkt.com/alan-power/profil/spieler/60781.
Transfer history data appended for: https://www.transfermarkt.com/ally-taylor/profil/spieler/606530.
Transfer history data appended for: https://www.transfermarkt.com/aaron-mcgowan/profil/spieler/257729.
Transfer history data appended for: https://www.transfermarkt.com/rory-mckenzie/profil/spieler/177550.
Transfer history data appended for: https://www.transfermarkt.com/chris-burke/profil/spieler/9618.
Transfer history data appended for: https://www.transfermarkt.com/stuart-findlay/profil/spieler/165334.
Transfer history data appended for: https://www.transfermarkt.com/greg-kiltie/profil/spieler/244256.
Transfer history data appended for: https://www.transfermarkt.com/jake-eastwood/profil/spieler/526873.
Transfer history data appended for: https://www.transfermarkt.com/kirk-broadfoot/profil/spieler/14768.
Transfer history data appended for: https://www.transfermarkt.com/curtis-lyle/profil/spieler/450853.
Transfer history data appended for: https://www.transfermarkt.com/nicke-kabamba/profil/spieler/483385.
Transfer history data appended for: https://www.transfermarkt.com/mitch-pinnock/profil/spieler/265592.
Transfer history data appended for: https://www.transfermarkt.com/clevid-dikamona/profil/spieler/114935.
Transfer history data appended for: https://www.transfermarkt.com/eamonn-brophy/profil/spieler/265513.
Transfer history data appended for: https://www.transfermarkt.com/danny-whitehall/profil/spieler/333545.
Transfer history data appended for: https://www.transfermarkt.com/zeno-ibsen-rossi/profil/spieler/655177.
Transfer history data appended for: https://www.transfermarkt.com/ross-millen/profil/spieler/191707.
Transfer history data appended for: https://www.transfermarkt.com/tomas-brindley/profil/spieler/606531.
Transfer history data appended for: https://www.transfermarkt.com/brandon-haunstrup/profil/spieler/379603.
Transfer history data appended for: https://www.transfermarkt.com/calum-waters/profil/spieler/193898.
Transfer history data appended for: https://www.transfermarkt.com/curtis-main/profil/spieler/77715.
Transfer history data appended for: https://www.transfermarkt.com/ronald-hernandez/profil/spieler/428745.
Transfer history data appended for: https://www.transfermarkt.com/funso-ojo/profil/spieler/60951.
Transfer history data appended for: https://www.transfermarkt.com/gary-woods/profil/spieler/73582.
Transfer history data appended for: https://www.transfermarkt.com/marley-watkins/profil/spieler/91315.
Transfer history data appended for: https://www.transfermarkt.com/jonny-hayes/profil/spieler/52380.
Transfer history data appended for: https://www.transfermarkt.com/lewis-ferguson/profil/spieler/428563.
Transfer history data appended for: https://www.transfermarkt.com/ross-mccrorie/profil/spieler/293746.
Transfer history data appended for: https://www.transfermarkt.com/joe-lewis/profil/spieler/25834.
Transfer history data appended for: https://www.transfermarkt.com/dylan-mcgeouch/profil/spieler/120976.
Transfer history data appended for: https://www.transfermarkt.com/matty-kennedy/profil/spieler/132207.
Transfer history data appended for: https://www.transfermarkt.com/scott-wright/profil/spieler/276914.
Transfer history data appended for: https://www.transfermarkt.com/michael-devlin/profil/spieler/173192.
Transfer history data appended for: https://www.transfermarkt.com/tommie-hoban/profil/spieler/183161.
Transfer history data appended for: https://www.transfermarkt.com/shay-logan/profil/spieler/58579.
Transfer history data appended for: https://www.transfermarkt.com/andy-considine/profil/spieler/21306.
Transfer history data appended for: https://www.transfermarkt.com/ash-taylor/profil/spieler/106721.
Transfer history data appended for: https://www.transfermarkt.com/ryan-hedges/profil/spieler/326230.
Transfer history data appended for: https://www.transfermarkt.com/sam-cosgrove/profil/spieler/351691.
Transfer history data appended for: https://www.transfermarkt.com/tomas-cerny/profil/spieler/35641.
Transfer history data appended for: https://www.transfermarkt.com/greg-leigh/profil/spieler/201586.
Transfer history data appended for: https://www.transfermarkt.com/connor-mclennan/profil/spieler/344584.
Transfer history data appended for: https://www.transfermarkt.com/niall-mcginn/profil/spieler/68321.
Transfer history data appended for: https://www.transfermarkt.com/dean-campbell/profil/spieler/463755.
Transfer history data appended for: https://www.transfermarkt.com/ryan-edmondson/profil/spieler/559806.
Transfer history data appended for: https://www.transfermarkt.com/adrian-sporle/profil/spieler/440371.
Transfer history data appended for: https://www.transfermarkt.com/nicky-clark/profil/spieler/62163.
Transfer history data appended for: https://www.transfermarkt.com/jack-newman/profil/spieler/532536.
Transfer history data appended for: https://www.transfermarkt.com/kai-fotheringham/profil/spieler/652672.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-siegrist/profil/spieler/111426.
Transfer history data appended for: https://www.transfermarkt.com/paul-mcmullan/profil/spieler/193883.
Transfer history data appended for: https://www.transfermarkt.com/jeando-fuchs/profil/spieler/375710.
Transfer history data appended for: https://www.transfermarkt.com/marc-mcnulty/profil/spieler/125850.
Transfer history data appended for: https://www.transfermarkt.com/liam-smith/profil/spieler/281807.
Transfer history data appended for: https://www.transfermarkt.com/louis-appere/profil/spieler/449019.
Transfer history data appended for: https://www.transfermarkt.com/lawrence-shankland/profil/spieler/225744.
Transfer history data appended for: https://www.transfermarkt.com/mark-connolly/profil/spieler/128285.
Transfer history data appended for: https://www.transfermarkt.com/adam-king/profil/spieler/169566.
Transfer history data appended for: https://www.transfermarkt.com/declan-glass/profil/spieler/509713.
Transfer history data appended for: https://www.transfermarkt.com/logan-chalmers/profil/spieler/396548.
Transfer history data appended for: https://www.transfermarkt.com/peter-pawlett/profil/spieler/62170.
Transfer history data appended for: https://www.transfermarkt.com/jamie-robson/profil/spieler/326585.
Transfer history data appended for: https://www.transfermarkt.com/luke-bolton/profil/spieler/382553.
Transfer history data appended for: https://www.transfermarkt.com/mark-reynolds/profil/spieler/21419.
Transfer history data appended for: https://www.transfermarkt.com/dillon-powers/profil/spieler/125698.
Transfer history data appended for: https://www.transfermarkt.com/deniz-mehmet/profil/spieler/110689.
Transfer history data appended for: https://www.transfermarkt.com/ryan-edwards/profil/spieler/173580.
Transfer history data appended for: https://www.transfermarkt.com/ian-harkes/profil/spieler/482493.
Transfer history data appended for: https://www.transfermarkt.com/calum-butcher/profil/spieler/61813.

Transfer history data appended for: https://www.transfermarkt.com/calvin-bassey/profil/spieler/461883.
Transfer history data appended for: https://www.transfermarkt.com/borna-barisic/profil/spieler/39125.
Transfer history data appended for: https://www.transfermarkt.com/jordan-jones/profil/spieler/249256.
Transfer history data appended for: https://www.transfermarkt.com/glenn-middleton/profil/spieler/344588.
Transfer history data appended for: https://www.transfermarkt.com/leon-balogun/profil/spieler/56100.
Transfer history data appended for: https://www.transfermarkt.com/greg-stewart/profil/spieler/156775.
Transfer history data appended for: https://www.transfermarkt.com/george-edmundson/profil/spieler/385848.
Transfer history data appended for: https://www.transfermarkt.com/nathan-patterson/profil/spieler/424015.
Transfer history data appended for: https://www.transfermarkt.com/james-tavernier/profil/spieler/62094.
Transfer history data appended for: https://www.transfermarkt.com/cedric-itten/profil/spieler/243856.
Transfer history data appended for: https://www.transfermarkt.com/filip-helander/profil/spieler/198067.
Transfer history data appended for: https://www.transfermarkt.com/nikola-katic/profil/spieler/422051.
Transfer history data appended for: https://www.transfermarkt.com/glen-kamara/profil/spieler/242632.
Transfer history data appended for: https://www.transfermarkt.com/ianis-hagi/profil/spieler/282076.
Transfer history data appended for: https://www.transfermarkt.com/kemar-roofe/profil/spieler/141350.
Transfer history data appended for: https://www.transfermarkt.com/brandon-barker/profil/spieler/214927.
Transfer history data appended for: https://www.transfermarkt.com/jon-mclaughlin/profil/spieler/92983.
Transfer history data appended for: https://www.transfermarkt.com/alfredo-morelos/profil/spieler/338962.
Transfer history data appended for: https://www.transfermarkt.com/andy-firth/profil/spieler/279133.
Transfer history data appended for: https://www.transfermarkt.com/allan-mcgregor/profil/spieler/9422.
Transfer history data appended for: https://www.transfermarkt.com/scott-arfield/profil/spieler/55291.
Transfer history data appended for: https://www.transfermarkt.com/joe-aribo/profil/spieler/468198.
Transfer history data appended for: https://www.transfermarkt.com/steven-davis/profil/spieler/28973.
Transfer history data appended for: https://www.transfermarkt.com/bongani-zungu/profil/spieler/240892.
Transfer history data appended for: https://www.transfermarkt.com/connor-goldson/profil/spieler/163656.
Transfer history data appended for: https://www.transfermarkt.com/jermain-defoe/profil/spieler/3875.
Transfer history data appended for: https://www.transfermarkt.com/ryan-jack/profil/spieler/60793.
Transfer history data appended for: https://www.transfermarkt.com/ciaron-brown/profil/spieler/611845.
Transfer history data appended for: https://www.transfermarkt.com/julien-serrano/profil/spieler/342216.
Transfer history data appended for: https://www.transfermarkt.com/scott-robinson/profil/spieler/60960.
Transfer history data appended for: https://www.transfermarkt.com/jay-emmanuel-thomas/profil/spieler/27969.
Transfer history data appended for: https://www.transfermarkt.com/alan-lithgow/profil/spieler/45299.
Transfer history data appended for: https://www.transfermarkt.com/matej-poplatnik/profil/spieler/235360.
Transfer history data appended for: https://www.transfermarkt.com/jack-mcmillan/profil/spieler/347617.
Transfer history data appended for: https://www.transfermarkt.com/scott-pittman/profil/spieler/182614.
Transfer history data appended for: https://www.transfermarkt.com/aaron-taylor-sinclair/profil/spieler/121032.
Transfer history data appended for: https://www.transfermarkt.com/steve-lawson/profil/spieler/446767.
Transfer history data appended for: https://www.transfermarkt.com/jack-fitzwater/profil/spieler/342047.
Transfer history data appended for: https://www.transfermarkt.com/max-stryjek/profil/spieler/240457.
Transfer history data appended for: https://www.transfermarkt.com/carlo-pignatiello/profil/spieler/406734.
Transfer history data appended for: https://www.transfermarkt.com/jason-holt/profil/spieler/105695.
Transfer history data appended for: https://www.transfermarkt.com/robby-mccrorie/profil/spieler/244260.
Transfer history data appended for: https://www.transfermarkt.com/nicky-devlin/profil/spieler/148215.
Transfer history data appended for: https://www.transfermarkt.com/scott-tiffoney/profil/spieler/387579.
Transfer history data appended for: https://www.transfermarkt.com/craig-sibbald/profil/spieler/165345.
Transfer history data appended for: https://www.transfermarkt.com/gary-maley/profil/spieler/200855.
Transfer history data appended for: https://www.transfermarkt.com/keaghan-jacobs/profil/spieler/59830.
Transfer history data appended for: https://www.transfermarkt.com/efe-eric-ambrose/profil/spieler/81831.
Transfer history data appended for: https://www.transfermarkt.com/jon-guthrie/profil/spieler/222108.
Transfer history data appended for: https://www.transfermarkt.com/marvin-bartley/profil/spieler/66980.
Transfer history data appended for: https://www.transfermarkt.com/alan-forrest/profil/spieler/276764.
Transfer history data appended for: https://www.transfermarkt.com/josh-mullin/profil/spieler/144863.
Transfer history data appended for: https://www.transfermarkt.com/hampus-zackrisson/profil/spieler/217376.
Transfer history data appended for: https://www.transfermarkt.com/albin-svensson/profil/spieler/561255.
Transfer history data appended for: https://www.transfermarkt.com/keanin-ayer-boya/profil/spieler/605051.
Transfer history data appended for: https://www.transfermarkt.com/monday-samuel/profil/spieler/239546.
Transfer history data appended for: https://www.transfermarkt.com/stojan-lukic/profil/spieler/38024.
Transfer history data appended for: https://www.transfermarkt.com/andre-boman/profil/spieler/663093.
Transfer history data appended for: https://www.transfermarkt.com/anton-liljenback/profil/spieler/318671.
Transfer history data appended for: https://www.transfermarkt.com/gustaf-norlin/profil/spieler/540120.
Transfer history data appended for: https://www.transfermarkt.com/alibek-aliev/profil/spieler/271763.
Transfer history data appended for: https://www.transfermarkt.com/astrit-selmani/profil/spieler/423879.
Transfer history data appended for: https://www.transfermarkt.com/hampus-danielsson/profil/spieler/570254.
Transfer history data appended for: https://www.transfermarkt.com/tashreeq-matthews/profil/spieler/512980.
Transfer history data appended for: https://www.transfermarkt.com/adama-fofana/profil/spieler/570534.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-nanasi/profil/spieler/579928.
Transfer history data appended for: https://www.transfermarkt.com/nils-bertilsson/profil/spieler/585327.
Transfer history data appended for: https://www.transfermarkt.com/philip-ljung/profil/spieler/300708.
Transfer history data appended for: https://www.transfermarkt.com/robin-book/profil/spieler/158804.
Transfer history data appended for: https://www.transfermarkt.com/jesper-modig/profil/spieler/205788.
Transfer history data appended for: https://www.transfermarkt.com/luke-le-roux/profil/spieler/467616.
Transfer history data appended for: https://www.transfermarkt.com/august-stromberg/profil/spieler/93201.
Transfer history data appended for: https://www.transfermarkt.com/joakim-lindner/profil/spieler/184674.
Transfer history data appended for: https://www.transfermarkt.com/jon-birkfeldt/profil/spieler/333513.
Transfer history data appended for: https://www.transfermarkt.com/robin-tranberg/profil/spieler/138426.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-cronvall/profil/spieler/726967.
Transfer history data appended for: https://www.transfermarkt.com/albert-ejupi/profil/spieler/204291.
Transfer history data appended for: https://www.transfermarkt.com/daniel-krezic/profil/spieler/304335.
Transfer history data appended for: https://www.transfermarkt.com/junes-barny/profil/spieler/255161.
Transfer history data appended for: https://www.transfermarkt.com/erion-sadiku/profil/spieler/570253.

Transfer history data appended for: https://www.transfermarkt.com/albin-winbo/profil/spieler/546968.
Transfer history data appended for: https://www.transfermarkt.com/liam-munther/profil/spieler/570255.
Transfer history data appended for: https://www.transfermarkt.com/emin-nouri/profil/spieler/35727.
Transfer history data appended for: https://www.transfermarkt.com/isak-jansson/profil/spieler/535820.
Transfer history data appended for: https://www.transfermarkt.com/mayron-george/profil/spieler/195162.
Transfer history data appended for: https://www.transfermarkt.com/adrian-edqvist/profil/spieler/396305.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-sjostedt/profil/spieler/170243.
Transfer history data appended for: https://www.transfermarkt.com/henrik-lofkvist/profil/spieler/286482.
Transfer history data appended for: https://www.transfermarkt.com/viktor-elm/profil/spieler/36391.
Transfer history data appended for: https://www.transfermarkt.com/isak-magnusson/profil/spieler/392257.
Transfer history data appended for: https://www.transfermarkt.com/olle-lindqvist/profil/spieler/398774.
Transfer history data appended for: https://www.transfermarkt.com/filip-sachpekidis/profil/spieler/228253.
Transfer history data appended for: https://www.transfermarkt.com/carl-gustafsson/profil/spieler/430823.
Transfer history data appended for: https://www.transfermarkt.com/tobias-andersson/profil/spieler/180123.
Transfer history data appended for: https://www.transfermarkt.com/johan-stenmark/profil/spieler/377466.
Transfer history data appended for: https://www.transfermarkt.com/malte-persson/profil/spieler/428703.
Transfer history data appended for: https://www.transfermarkt.com/alexander-ahl-holmstrom/profil/spieler/498171.
Transfer history data appended for: https://www.transfermarkt.com/johan-arvidsson/profil/spieler/430815.
Transfer history data appended for: https://www.transfermarkt.com/edvin-crona/profil/spieler/428605.
Transfer history data appended for: https://www.transfermarkt.com/viktor-kruger/profil/spieler/431754.
Transfer history data appended for: https://www.transfermarkt.com/ole-soderberg/profil/spieler/62145.
Transfer history data appended for: https://www.transfermarkt.com/douglas-bergqvist/profil/spieler/186044.
Transfer history data appended for: https://www.transfermarkt.com/york-rafael/profil/spieler/377480.
Transfer history data appended for: https://www.transfermarkt.com/rafinha/profil/spieler/217254.
Transfer history data appended for: https://www.transfermarkt.com/geir-andre-herrem/profil/spieler/61917.
Transfer history data appended for: https://www.transfermarkt.com/gbenga-arokoyo/profil/spieler/184932.
Transfer history data appended for: https://www.transfermarkt.com/nils-froling/profil/spieler/532784.
Transfer history data appended for: https://www.transfermarkt.com/piotr-johansson/profil/spieler/223861.
Transfer history data appended for: https://www.transfermarkt.com/jaja/profil/spieler/364883.
Transfer history data appended for: https://www.transfermarkt.com/lucas-hagg-johansson/profil/spieler/205307.
Transfer history data appended for: https://www.transfermarkt.com/erik-israelsson/profil/spieler/76085.
Transfer history data appended for: https://www.transfermarkt.com/romario-pereira-sipiao/profil/spieler/118714.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-ring/profil/spieler/262709.
Transfer history data appended for: https://www.transfermarkt.com/johan-dahlin/profil/spieler/41653.
Transfer history data appended for: https://www.transfermarkt.com/dusan-melicharek/profil/spieler/37061.
Transfer history data appended for: https://www.transfermarkt.com/franz-brorsson/profil/spieler/271773.
Transfer history data appended for: https://www.transfermarkt.com/jonas-knudsen/profil/spieler/144904.
Transfer history data appended for: https://www.transfermarkt.com/arnor-ingvi-traustason/profil/spieler/153237.
Transfer history data appended for: https://www.transfermarkt.com/amin-sarr/profil/spieler/748382.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-bengtsson/profil/spieler/37080.
Transfer history data appended for: https://www.transfermarkt.com/bonke-innocent/profil/spieler/333383.
Transfer history data appended for: https://www.transfermarkt.com/felix-beijmo/profil/spieler/322293.
Transfer history data appended for: https://www.transfermarkt.com/oscar-lewicki/profil/spieler/76051.
Transfer history data appended for: https://www.transfermarkt.com/anders-christiansen/profil/spieler/77259.
Transfer history data appended for: https://www.transfermarkt.com/erdal-rakip/profil/spieler/230746.
Transfer history data appended for: https://www.transfermarkt.com/behrang-safari/profil/spieler/18807.
Transfer history data appended for: https://www.transfermarkt.com/adi-nalic/profil/spieler/332875.
Transfer history data appended for: https://www.transfermarkt.com/ola-toivonen/profil/spieler/36500.
Transfer history data appended for: https://www.transfermarkt.com/eric-larsson/profil/spieler/146774.
Transfer history data appended for: https://www.transfermarkt.com/soren-rieks/profil/spieler/44471.
Transfer history data appended for: https://www.transfermarkt.com/anel-ahmedhodzic/profil/spieler/377468.
Transfer history data appended for: https://www.transfermarkt.com/marko-johansson/profil/spieler/316983.
Transfer history data appended for: https://www.transfermarkt.com/lasse-nielsen/profil/spieler/42913.
Transfer history data appended for: https://www.transfermarkt.com/jo-inge-berget/profil/spieler/73323.
Transfer history data appended for: https://www.transfermarkt.com/mathias-nilsson/profil/spieler/396298.
Transfer history data appended for: https://www.transfermarkt.com/samuel-adrian/profil/spieler/396295.
Transfer history data appended for: https://www.transfermarkt.com/noel-mbo/profil/spieler/403338.
Transfer history data appended for: https://www.transfermarkt.com/assad-al-hamlawi/profil/spieler/518451.
Transfer history data appended for: https://www.transfermarkt.com/mix-diskerud/profil/spieler/103559.
Transfer history data appended for: https://www.transfermarkt.com/kalle-joelsson/profil/spieler/366458.
Transfer history data appended for: https://www.transfermarkt.com/alexander-nilsson/profil/spieler/599958.
Transfer history data appended for: https://www.transfermarkt.com/martin-olsson/profil/spieler/38073.
Transfer history data appended for: https://www.transfermarkt.com/carl-thulin/profil/spieler/320781.
Transfer history data appended for: https://www.transfermarkt.com/jakob-voelkerling-persson/profil/spieler/587923.
Transfer history data appended for: https://www.transfermarkt.com/marcus-olsson/profil/spieler/72264.
Transfer history data appended for: https://www.transfermarkt.com/erik-figueroa/profil/spieler/125308.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-abubakari/profil/spieler/44413.
Transfer history data appended for: https://www.transfermarkt.com/kebba-ceesay/profil/spieler/45879.
Transfer history data appended for: https://www.transfermarkt.com/max-svensson/profil/spieler/367981.
Transfer history data appended for: https://www.transfermarkt.com/adam-eriksson/profil/spieler/205404.
Transfer history data appended for: https://www.transfermarkt.com/anthony-van-den-hurk/profil/spieler/226100.
Transfer history data appended for: https://www.transfermarkt.com/brandur-hendriksson-olsen/profil/spieler/289855.
Transfer history data appended for: https://www.transfermarkt.com/alex-timossi-andersson/profil/spieler/454628.
Transfer history data appended for: https://www.transfermarkt.com/shkodran-maholli/profil/spieler/183499.
Transfer history data appended for: https://www.transfermarkt.com/ravy-tsouka/profil/spieler/353418.
Transfer history data appended for: https://www.transfermarkt.com/daniel-hafsteinsson/profil/spieler/489000.
Transfer history data appended for: https://www.transfermarkt.com/anders-lindegaard/profil/spieler/22491.
Transfer history data appended for: https://www.transfermarkt.com/andreas-landgren/profil/spieler/45887.
Transfer history data appended for: https://www.transfermarkt.com/alhaji-gero/profil/spieler/257558.

Transfer history data appended for: https://www.transfermarkt.com/joseph-ceesay/profil/spieler/364278.
Transfer history data appended for: https://www.transfermarkt.com/romain-gall/profil/spieler/242325.
Transfer history data appended for: https://www.transfermarkt.com/oscar-jansson/profil/spieler/45628.
Transfer history data appended for: https://www.transfermarkt.com/helmer-andersson/profil/spieler/493660.
Transfer history data appended for: https://www.transfermarkt.com/niclas-bergmark/profil/spieler/585326.
Transfer history data appended for: https://www.transfermarkt.com/hussein-ali/profil/spieler/585325.
Transfer history data appended for: https://www.transfermarkt.com/simon-gustafsson/profil/spieler/530021.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-karjalainen/profil/spieler/273383.
Transfer history data appended for: https://www.transfermarkt.com/johan-martensson/profil/spieler/76047.
Transfer history data appended for: https://www.transfermarkt.com/alfred-ajdarevic/profil/spieler/369324.
Transfer history data appended for: https://www.transfermarkt.com/daniel-bjorkman/profil/spieler/221939.
Transfer history data appended for: https://www.transfermarkt.com/martin-broberg/profil/spieler/114665.
Transfer history data appended for: https://www.transfermarkt.com/jake-larsson/profil/spieler/553472.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-hjertstrand/profil/spieler/312177.
Transfer history data appended for: https://www.transfermarkt.com/daniel-bjornkvist/profil/spieler/229386.
Transfer history data appended for: https://www.transfermarkt.com/michael-almeback/profil/spieler/51529.
Transfer history data appended for: https://www.transfermarkt.com/andreas-skovgaard/profil/spieler/355512.
Transfer history data appended for: https://www.transfermarkt.com/jake-mcguire/profil/spieler/482650.
Transfer history data appended for: https://www.transfermarkt.com/nordin-gerzic/profil/spieler/50544.
Transfer history data appended for: https://www.transfermarkt.com/agon-mehmeti/profil/spieler/72687.
Transfer history data appended for: https://www.transfermarkt.com/isaac-boye/profil/spieler/526449.
Transfer history data appended for: https://www.transfermarkt.com/kevin-wright/profil/spieler/255822.
Transfer history data appended for: https://www.transfermarkt.com/simon-amin/profil/spieler/554822.
Transfer history data appended for: https://www.transfermarkt.com/albin-granlund/profil/spieler/146907.
Transfer history data appended for: https://www.transfermarkt.com/dennis-collander/profil/spieler/527336.
Transfer history data appended for: https://www.transfermarkt.com/erik-bjorndahl/profil/spieler/114776.
Transfer history data appended for: https://www.transfermarkt.com/deniz-hummet/profil/spieler/271787.
Transfer history data appended for: https://www.transfermarkt.com/nahir-besara/profil/spieler/81755.
Transfer history data appended for: https://www.transfermarkt.com/fabio-de-sousa-silva/profil/spieler/605301.
Transfer history data appended for: https://www.transfermarkt.com/david-seger/profil/spieler/665582.
Transfer history data appended for: https://www.transfermarkt.com/robin-tihi/profil/spieler/579288.
Transfer history data appended for: https://www.transfermarkt.com/paulos-abraham/profil/spieler/579289.
Transfer history data appended for: https://www.transfermarkt.com/erik-ring/profil/spieler/677298.
Transfer history data appended for: https://www.transfermarkt.com/tom-strannegard/profil/spieler/527343.
Transfer history data appended for: https://www.transfermarkt.com/felix-michel-melki/profil/spieler/258477.
Transfer history data appended for: https://www.transfermarkt.com/sotirios-papagiannopoulos/profil/spieler/97616.
Transfer history data appended for: https://www.transfermarkt.com/bojan-radulovic/profil/spieler/516407.
Transfer history data appended for: https://www.transfermarkt.com/jakob-haugaard/profil/spieler/138335.
Transfer history data appended for: https://www.transfermarkt.com/daniel-mushitu/profil/spieler/464134.
Transfer history data appended for: https://www.transfermarkt.com/adam-ben-lamin/profil/spieler/464135.
Transfer history data appended for: https://www.transfermarkt.com/robert-lundstrom/profil/spieler/100984.
Transfer history data appended for: https://www.transfermarkt.com/panajotis-dimitriadis/profil/spieler/95364.
Transfer history data appended for: https://www.transfermarkt.com/heradi-rashidi/profil/spieler/258972.
Transfer history data appended for: https://www.transfermarkt.com/bilal-hussein/profil/spieler/448266.
Transfer history data appended for: https://www.transfermarkt.com/eric-kahl/profil/spieler/675278.
Transfer history data appended for: https://www.transfermarkt.com/budimir-janosevic/profil/spieler/46693.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-larsson/profil/spieler/31720.
Transfer history data appended for: https://www.transfermarkt.com/erick-otieno/profil/spieler/442118.
Transfer history data appended for: https://www.transfermarkt.com/henok-goitom/profil/spieler/6838.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-lindkvist/profil/spieler/114691.
Transfer history data appended for: https://www.transfermarkt.com/nabil-bahoui/profil/spieler/93184.
Transfer history data appended for: https://www.transfermarkt.com/filip-rogic/profil/spieler/217069.
Transfer history data appended for: https://www.transfermarkt.com/per-karlsson/profil/spieler/18096.
Transfer history data appended for: https://www.transfermarkt.com/stefan-silva/profil/spieler/208905.
Transfer history data appended for: https://www.transfermarkt.com/mikael-lustig/profil/spieler/36025.
Transfer history data appended for: https://www.transfermarkt.com/ebenezer-ofori/profil/spieler/262597.
Transfer history data appended for: https://www.transfermarkt.com/kyriakos-stamatopoulos/profil/spieler/26436.
Transfer history data appended for: https://www.transfermarkt.com/enoch-kofi-adu/profil/spieler/88239.
Transfer history data appended for: https://www.transfermarkt.com/isac-haggman/profil/spieler/628572.
Transfer history data appended for: https://www.transfermarkt.com/noah-sonko-sundberg/profil/spieler/249121.
Transfer history data appended for: https://www.transfermarkt.com/pontus-kindberg/profil/spieler/628574.
Transfer history data appended for: https://www.transfermarkt.com/isak-ssewankambo/profil/spieler/249118.
Transfer history data appended for: https://www.transfermarkt.com/andrew-mills/profil/spieler/198123.
Transfer history data appended for: https://www.transfermarkt.com/blair-turgott/profil/spieler/134426.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-karlsson-grach/profil/spieler/669450.
Transfer history data appended for: https://www.transfermarkt.com/thomas-isherwood/profil/spieler/322075.
Transfer history data appended for: https://www.transfermarkt.com/ludvig-fritzson/profil/spieler/334810.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-awad/profil/spieler/205861.
Transfer history data appended for: https://www.transfermarkt.com/gustav-wikstrand/profil/spieler/628575.
Transfer history data appended for: https://www.transfermarkt.com/jerell-sellars/profil/spieler/243690.
Transfer history data appended for: https://www.transfermarkt.com/sam-mensah/profil/spieler/124937.
Transfer history data appended for: https://www.transfermarkt.com/nikolaos-dosis/profil/spieler/481689.
Transfer history data appended for: https://www.transfermarkt.com/malcolm-stolt/profil/spieler/549405.
Transfer history data appended for: https://www.transfermarkt.com/sixten-mohlin/profil/spieler/249106.
Transfer history data appended for: https://www.transfermarkt.com/felix-horberg/profil/spieler/501455.
Transfer history data appended for: https://www.transfermarkt.com/kalpi-ouattara/profil/spieler/640737.
Transfer history data appended for: https://www.transfermarkt.com/charlie-colkett/profil/spieler/236496.
Transfer history data appended for: https://www.transfermarkt.com/frank-arhin/profil/spieler/527599.
Transfer history data appended for: https://www.transfermarkt.com/ronald-mukiibi/profil/spieler/183607.

Transfer history data appended for: https://www.transfermarkt.com/eirik-haugan/profil/spieler/308444.
Transfer history data appended for: https://www.transfermarkt.com/alex-purver/profil/spieler/455512.
Transfer history data appended for: https://www.transfermarkt.com/aly-keita/profil/spieler/114803.
Transfer history data appended for: https://www.transfermarkt.com/marco-weymans/profil/spieler/286044.
Transfer history data appended for: https://www.transfermarkt.com/patrick-kpozo/profil/spieler/355633.
Transfer history data appended for: https://www.transfermarkt.com/henrik-bellman/profil/spieler/367980.
Transfer history data appended for: https://www.transfermarkt.com/robin-wikberg/profil/spieler/628573.
Transfer history data appended for: https://www.transfermarkt.com/nebiyou-perry/profil/spieler/398972.
Transfer history data appended for: https://www.transfermarkt.com/rewan-amin/profil/spieler/241402.
Transfer history data appended for: https://www.transfermarkt.com/simon-kroon/profil/spieler/189989.
Transfer history data appended for: https://www.transfermarkt.com/francis-jno-baptiste/profil/spieler/573867.
Transfer history data appended for: https://www.transfermarkt.com/jacob-ondrejka/profil/spieler/663237.
Transfer history data appended for: https://www.transfermarkt.com/prince-isaac-kouame/profil/spieler/593392.
Transfer history data appended for: https://www.transfermarkt.com/rami-kaib/profil/spieler/274373.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-alm/profil/spieler/290085.
Transfer history data appended for: https://www.transfermarkt.com/per-frick/profil/spieler/216148.
Transfer history data appended for: https://www.transfermarkt.com/leo-vaisanen/profil/spieler/309439.
Transfer history data appended for: https://www.transfermarkt.com/marokhy-ndione/profil/spieler/479019.
Transfer history data appended for: https://www.transfermarkt.com/simon-strand/profil/spieler/103405.
Transfer history data appended for: https://www.transfermarkt.com/jeppe-okkels/profil/spieler/345591.
Transfer history data appended for: https://www.transfermarkt.com/johan-larsson/profil/spieler/140678.
Transfer history data appended for: https://www.transfermarkt.com/alexander-bernhardsson/profil/spieler/633454.
Transfer history data appended for: https://www.transfermarkt.com/mathias-dyngeland/profil/spieler/228006.
Transfer history data appended for: https://www.transfermarkt.com/tim-ronning/profil/spieler/377465.
Transfer history data appended for: https://www.transfermarkt.com/samuel-holmen/profil/spieler/24379.
Transfer history data appended for: https://www.transfermarkt.com/sivert-heltne-nilsen/profil/spieler/180167.
Transfer history data appended for: https://www.transfermarkt.com/joseph-okumu/profil/spieler/453376.
Transfer history data appended for: https://www.transfermarkt.com/frederik-holst/profil/spieler/135209.
Transfer history data appended for: https://www.transfermarkt.com/christopher-mcvey/profil/spieler/321155.
Transfer history data appended for: https://www.transfermarkt.com/robert-gojani/profil/spieler/187103.
Transfer history data appended for: https://www.transfermarkt.com/simon-olsson/profil/spieler/321158.
Transfer history data appended for: https://www.transfermarkt.com/gustav-henriksson/profil/spieler/368565.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-rosenqvist/profil/spieler/285153.
Transfer history data appended for: https://www.transfermarkt.com/kalle-bjorklund/profil/spieler/549228.
Transfer history data appended for: https://www.transfermarkt.com/oliver-dovin/profil/spieler/527329.
Transfer history data appended for: https://www.transfermarkt.com/alexander-kacaniklic/profil/spieler/51040.
Transfer history data appended for: https://www.transfermarkt.com/mads-fenger/profil/spieler/100980.
Transfer history data appended for: https://www.transfermarkt.com/david-ousted/profil/spieler/22913.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-machini/profil/spieler/277125.
Transfer history data appended for: https://www.transfermarkt.com/leon-hien/profil/spieler/664349.
Transfer history data appended for: https://www.transfermarkt.com/serge-junior-martinsson-ngouali/profil/spieler/148219.
Transfer history data appended for: https://www.transfermarkt.com/darijan-bojanic/profil/spieler/184526.
Transfer history data appended for: https://www.transfermarkt.com/richard-magyar/profil/spieler/148727.
Transfer history data appended for: https://www.transfermarkt.com/jean-carlos-de-brito/profil/spieler/520380.
Transfer history data appended for: https://www.transfermarkt.com/paulinho/profil/spieler/58475.
Transfer history data appended for: https://www.transfermarkt.com/filston-mawana/profil/spieler/396304.
Transfer history data appended for: https://www.transfermarkt.com/mohanad-jeahze/profil/spieler/296384.
Transfer history data appended for: https://www.transfermarkt.com/imad-khalili/profil/spieler/32910.
Transfer history data appended for: https://www.transfermarkt.com/loue-bayere-junior/profil/spieler/678101.
Transfer history data appended for: https://www.transfermarkt.com/dennis-widgren/profil/spieler/217197.
Transfer history data appended for: https://www.transfermarkt.com/akinkunmi-amoo/profil/spieler/666580.
Transfer history data appended for: https://www.transfermarkt.com/aimar-sher/profil/spieler/579294.
Transfer history data appended for: https://www.transfermarkt.com/oscar-krusnell/profil/spieler/344693.
Transfer history data appended for: https://www.transfermarkt.com/simon-sandberg/profil/spieler/214621.
Transfer history data appended for: https://www.transfermarkt.com/aron-johannsson/profil/spieler/119169.
Transfer history data appended for: https://www.transfermarkt.com/davor-blazevic/profil/spieler/138408.
Transfer history data appended for: https://www.transfermarkt.com/tim-soderstrom/profil/spieler/217274.
Transfer history data appended for: https://www.transfermarkt.com/jeppe-andersen/profil/spieler/148345.
Transfer history data appended for: https://www.transfermarkt.com/aziz-ouattara-mohammed/profil/spieler/678100.
Transfer history data appended for: https://www.transfermarkt.com/andre-alsanati/profil/spieler/431748.
Transfer history data appended for: https://www.transfermarkt.com/abdul-khalili/profil/spieler/154414.
Transfer history data appended for: https://www.transfermarkt.com/david-fallman/profil/spieler/100999.
Transfer history data appended for: https://www.transfermarkt.com/axel-sjoberg/profil/spieler/594630.
Transfer history data appended for: https://www.transfermarkt.com/gustav-ludwigson/profil/spieler/558269.
Transfer history data appended for: https://www.transfermarkt.com/stefano-holmquist-vecchia/profil/spieler/295572.
Transfer history data appended for: https://www.transfermarkt.com/simon-gefvert/profil/spieler/380936.
Transfer history data appended for: https://www.transfermarkt.com/karl-larson/profil/spieler/180354.
Transfer history data appended for: https://www.transfermarkt.com/adam-stahl/profil/spieler/223920.
Transfer history data appended for: https://www.transfermarkt.com/jonas-lindberg/profil/spieler/116944.
Transfer history data appended for: https://www.transfermarkt.com/joakim-persson/profil/spieler/675657.
Transfer history data appended for: https://www.transfermarkt.com/elias-andersson/profil/spieler/229616.
Transfer history data appended for: https://www.transfermarkt.com/kennedy-igboananike/profil/spieler/51828.
Transfer history data appended for: https://www.transfermarkt.com/laorent-shabani/profil/spieler/381979.
Transfer history data appended for: https://www.transfermarkt.com/andre-osterholm/profil/spieler/322725.
Transfer history data appended for: https://www.transfermarkt.com/axel-bjornstrom/profil/spieler/299902.
Transfer history data appended for: https://www.transfermarkt.com/lukas-jonsson/profil/spieler/136601.
Transfer history data appended for: https://www.transfermarkt.com/isak-braholm/profil/spieler/430829.
Transfer history data appended for: https://www.transfermarkt.com/yukiya-sugita/profil/spieler/290914.
Transfer history data appended for: https://www.transfermarkt.com/hannes-sveijer/profil/spieler/665542.

Transfer history data appended for: https://www.transfermarkt.com/adam-hellborg/profil/spieler/322066.
Transfer history data appended for: https://www.transfermarkt.com/tim-bjorkstrom/profil/spieler/131051.
Transfer history data appended for: https://www.transfermarkt.com/sam-lundholm/profil/spieler/220432.
Transfer history data appended for: https://www.transfermarkt.com/daniel-jarl/profil/spieler/97037.
Transfer history data appended for: https://www.transfermarkt.com/jon-viscosi/profil/spieler/353414.
Transfer history data appended for: https://www.transfermarkt.com/nahom-girmai-netabay/profil/spieler/255768.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-saeid/profil/spieler/211085.
Transfer history data appended for: https://www.transfermarkt.com/niklas-busch-thor/profil/spieler/209026.
Transfer history data appended for: https://www.transfermarkt.com/johan-karlsson/profil/spieler/667869.
Transfer history data appended for: https://www.transfermarkt.com/hjalmar-ekdal/profil/spieler/392179.
Transfer history data appended for: https://www.transfermarkt.com/jamie-roche/profil/spieler/667870.
Transfer history data appended for: https://www.transfermarkt.com/maic-sema/profil/spieler/41581.
Transfer history data appended for: https://www.transfermarkt.com/isak-pettersson/profil/spieler/296458.
Transfer history data appended for: https://www.transfermarkt.com/ishaq-abdulrazak/profil/spieler/775535.
Transfer history data appended for: https://www.transfermarkt.com/eric-smith/profil/spieler/292534.
Transfer history data appended for: https://www.transfermarkt.com/filip-dagerstal/profil/spieler/270905.
Transfer history data appended for: https://www.transfermarkt.com/christopher-telo/profil/spieler/49158.
Transfer history data appended for: https://www.transfermarkt.com/linus-wahlqvist/profil/spieler/249125.
Transfer history data appended for: https://www.transfermarkt.com/christoffer-nyman/profil/spieler/167149.
Transfer history data appended for: https://www.transfermarkt.com/egzon-binaku/profil/spieler/318645.
Transfer history data appended for: https://www.transfermarkt.com/andreas-blomqvist/profil/spieler/223032.
Transfer history data appended for: https://www.transfermarkt.com/manasse-kusu/profil/spieler/504240.
Transfer history data appended for: https://www.transfermarkt.com/julius-lindgren/profil/spieler/427729.
Transfer history data appended for: https://www.transfermarkt.com/oliver-stefansson/profil/spieler/579583.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-levi/profil/spieler/383880.
Transfer history data appended for: https://www.transfermarkt.com/sead-haksabanovic/profil/spieler/349300.
Transfer history data appended for: https://www.transfermarkt.com/simon-thern/profil/spieler/116614.
Transfer history data appended for: https://www.transfermarkt.com/theodore-rask/profil/spieler/502129.
Transfer history data appended for: https://www.transfermarkt.com/alexander-fransson/profil/spieler/238056.
Transfer history data appended for: https://www.transfermarkt.com/henrik-castegren/profil/spieler/253159.
Transfer history data appended for: https://www.transfermarkt.com/kevin-alvarez/profil/spieler/281305.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-khazeni/profil/spieler/541525.
Transfer history data appended for: https://www.transfermarkt.com/isak-bergmann-johannesson/profil/spieler/579565.
Transfer history data appended for: https://www.transfermarkt.com/linus-hallenius/profil/spieler/50587.
Transfer history data appended for: https://www.transfermarkt.com/felix-jakobsson/profil/spieler/390038.
Transfer history data appended for: https://www.transfermarkt.com/lars-gerson/profil/spieler/73524.
Transfer history data appended for: https://www.transfermarkt.com/max-rundqvist/profil/spieler/402790.
Transfer history data appended for: https://www.transfermarkt.com/carljohan-eriksson/profil/spieler/214073.
Transfer history data appended for: https://www.transfermarkt.com/jacob-bergstrom/profil/spieler/554726.
Transfer history data appended for: https://www.transfermarkt.com/jesper-lofgren/profil/spieler/392743.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-tamimi/profil/spieler/220475.
Transfer history data appended for: https://www.transfermarkt.com/david-lofquist/profil/spieler/75884.
Transfer history data appended for: https://www.transfermarkt.com/pontus-jonsson/profil/spieler/557647.
Transfer history data appended for: https://www.transfermarkt.com/jesper-gustavsson/profil/spieler/223896.
Transfer history data appended for: https://www.transfermarkt.com/max-watson/profil/spieler/257102.
Transfer history data appended for: https://www.transfermarkt.com/joel-nilsson/profil/spieler/223912.
Transfer history data appended for: https://www.transfermarkt.com/hampus-holgersson/profil/spieler/518479.
Transfer history data appended for: https://www.transfermarkt.com/taylor-silverholt/profil/spieler/552981.
Transfer history data appended for: https://www.transfermarkt.com/eric-bjorkander/profil/spieler/291816.
Transfer history data appended for: https://www.transfermarkt.com/viktor-agardius/profil/spieler/115733.
Transfer history data appended for: https://www.transfermarkt.com/martin-spelmann/profil/spieler/43010.
Transfer history data appended for: https://www.transfermarkt.com/mamudo-moro/profil/spieler/429605.
Transfer history data appended for: https://www.transfermarkt.com/jasin-khayat/profil/spieler/240728.
Transfer history data appended for: https://www.transfermarkt.com/erik-parsson/profil/spieler/223870.
Transfer history data appended for: https://www.transfermarkt.com/viktor-gustafson/profil/spieler/501555.
Transfer history data appended for: https://www.transfermarkt.com/adam-petersson/profil/spieler/557946.
Transfer history data appended for: https://www.transfermarkt.com/amer-eriksson-ibragic/profil/spieler/265973.
Transfer history data appended for: https://www.transfermarkt.com/noel-tornqvist/profil/spieler/730531.
Transfer history data appended for: https://www.transfermarkt.com/moses-ogbu/profil/spieler/186702.
Transfer history data appended for: https://www.transfermarkt.com/besard-sabovic/profil/spieler/322077.
Transfer history data appended for: https://www.transfermarkt.com/omar-dampha/profil/spieler/90479.
Transfer history data appended for: https://www.transfermarkt.com/david-batanero/profil/spieler/379365.
Transfer history data appended for: https://www.transfermarkt.com/kadir-hodzic/profil/spieler/225618.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-lindgren/profil/spieler/29456.
Transfer history data appended for: https://www.transfermarkt.com/leo-bengtsson/profil/spieler/323325.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-yasin/profil/spieler/114791.
Transfer history data appended for: https://www.transfermarkt.com/johan-hammar/profil/spieler/156937.
Transfer history data appended for: https://www.transfermarkt.com/tobias-carlsson/profil/spieler/553825.
Transfer history data appended for: https://www.transfermarkt.com/pontus-dahlberg/profil/spieler/365544.
Transfer history data appended for: https://www.transfermarkt.com/viktor-lundberg/profil/spieler/75568.
Transfer history data appended for: https://www.transfermarkt.com/daleho-irandust/profil/spieler/369653.
Transfer history data appended for: https://www.transfermarkt.com/kevin-yakob/profil/spieler/413268.
Transfer history data appended for: https://www.transfermarkt.com/gustav-berggren/profil/spieler/258007.
Transfer history data appended for: https://www.transfermarkt.com/nikola-gulan/profil/spieler/46553.
Transfer history data appended for: https://www.transfermarkt.com/jasse-tuominen/profil/spieler/274749.
Transfer history data appended for: https://www.transfermarkt.com/alexander-soderlund/profil/spieler/87479.
Transfer history data appended for: https://www.transfermarkt.com/aiham-ousou/profil/spieler/585068.
Transfer history data appended for: https://www.transfermarkt.com/adam-andersson/profil/spieler/255468.
Transfer history data appended for: https://www.transfermarkt.com/joona-toivio/profil/spieler/37339.

Transfer history data appended for: https://www.transfermarkt.com/godswill-ekpolo/profil/spieler/223727.
Transfer history data appended for: https://www.transfermarkt.com/erik-friberg/profil/spieler/49144.
Transfer history data appended for: https://www.transfermarkt.com/patrik-walemark/profil/spieler/721470.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-rasheed/profil/spieler/204409.
Transfer history data appended for: https://www.transfermarkt.com/ali-youssef/profil/spieler/501131.
Transfer history data appended for: https://www.transfermarkt.com/oskar-sverrisson/profil/spieler/222234.
Transfer history data appended for: https://www.transfermarkt.com/alexander-nadj/profil/spieler/36678.
Transfer history data appended for: https://www.transfermarkt.com/alexander-faltsetas/profil/spieler/107541.
Transfer history data appended for: https://www.transfermarkt.com/peter-abrahamsson/profil/spieler/62147.
Transfer history data appended for: https://www.transfermarkt.com/august-erlingmark/profil/spieler/428050.
Transfer history data appended for: https://www.transfermarkt.com/yahya-kalley/profil/spieler/593410.
Transfer history data appended for: https://www.transfermarkt.com/alexander-farnerud/profil/spieler/10255.
Transfer history data appended for: https://www.transfermarkt.com/alhassan-yusuf-abdullahi/profil/spieler/600481.
Transfer history data appended for: https://www.transfermarkt.com/patrik-karlsson-lagemyr/profil/spieler/265333.
Transfer history data appended for: https://www.transfermarkt.com/hosam-aiesh/profil/spieler/220550.
Transfer history data appended for: https://www.transfermarkt.com/jakob-johansson/profil/spieler/46473.
Transfer history data appended for: https://www.transfermarkt.com/giorgi-kharaishvili/profil/spieler/250897.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-wikstrom/profil/spieler/504243.
Transfer history data appended for: https://www.transfermarkt.com/tobias-sana/profil/spieler/75901.
Transfer history data appended for: https://www.transfermarkt.com/sargon-abraham/profil/spieler/116930.
Transfer history data appended for: https://www.transfermarkt.com/jesper-tolinsson/profil/spieler/605394.
Transfer history data appended for: https://www.transfermarkt.com/emil-holm/profil/spieler/496745.
Transfer history data appended for: https://www.transfermarkt.com/isak-dahlqvist/profil/spieler/501054.
Transfer history data appended for: https://www.transfermarkt.com/alexander-jallow/profil/spieler/357622.
Transfer history data appended for: https://www.transfermarkt.com/robin-soder/profil/spieler/77314.
Transfer history data appended for: https://www.transfermarkt.com/tom-amos/profil/spieler/349335.
Transfer history data appended for: https://www.transfermarkt.com/amin-affane/profil/spieler/154274.
Transfer history data appended for: https://www.transfermarkt.com/giannis-anestis/profil/spieler/191853.
Transfer history data appended for: https://www.transfermarkt.com/pontus-wernbloom/profil/spieler/36688.
Transfer history data appended for: https://www.transfermarkt.com/andre-calisir/profil/spieler/114680.
Transfer history data appended for: https://www.transfermarkt.com/kristopher-da-graca/profil/spieler/322061.
Transfer history data appended for: https://www.transfermarkt.com/noah-alexandersson/profil/spieler/504244.
Transfer history data appended for: https://www.transfermarkt.com/christian-kouakou/profil/spieler/183143.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-ring/profil/spieler/180137.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-ulvestad/profil/spieler/158022.
Transfer history data appended for: https://www.transfermarkt.com/erik-berg/profil/spieler/49147.
Transfer history data appended for: https://www.transfermarkt.com/emir-kujovic/profil/spieler/47199.
Transfer history data appended for: https://www.transfermarkt.com/jesper-nyholm/profil/spieler/211148.
Transfer history data appended for: https://www.transfermarkt.com/aslak-fonn-witry/profil/spieler/313944.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-augustinsson/profil/spieler/297482.
Transfer history data appended for: https://www.transfermarkt.com/nicklas-barkroth/profil/spieler/59205.
Transfer history data appended for: https://www.transfermarkt.com/jacob-une-larsson/profil/spieler/197221.
Transfer history data appended for: https://www.transfermarkt.com/oscar-pettersson/profil/spieler/577816.
Transfer history data appended for: https://www.transfermarkt.com/curtis-edwards/profil/spieler/244223.
Transfer history data appended for: https://www.transfermarkt.com/karl-holmberg/profil/spieler/184744.
Transfer history data appended for: https://www.transfermarkt.com/haris-radetinac/profil/spieler/47729.
Transfer history data appended for: https://www.transfermarkt.com/magnus-eriksson/profil/spieler/75554.
Transfer history data appended for: https://www.transfermarkt.com/per-kristian-bratveit/profil/spieler/226410.
Transfer history data appended for: https://www.transfermarkt.com/tommi-vaiho/profil/spieler/41521.
Transfer history data appended for: https://www.transfermarkt.com/edward-chilufya/profil/spieler/490309.
Transfer history data appended for: https://www.transfermarkt.com/alexander-abrahamsson/profil/spieler/405774.
Transfer history data appended for: https://www.transfermarkt.com/erland-tangvik/profil/spieler/522352.
Transfer history data appended for: https://www.transfermarkt.com/elliot-kack/profil/spieler/151682.
Transfer history data appended for: https://www.transfermarkt.com/jesper-karlstrom/profil/spieler/222855.
Transfer history data appended for: https://www.transfermarkt.com/kevin-walker/profil/spieler/45194.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-banda/profil/spieler/490308.
Transfer history data appended for: https://www.transfermarkt.com/edi-sylisufaj/profil/spieler/442823.
Transfer history data appended for: https://www.transfermarkt.com/matthew-garbett/profil/spieler/617019.
Transfer history data appended for: https://www.transfermarkt.com/tim-erlandsson/profil/spieler/258561.
Transfer history data appended for: https://www.transfermarkt.com/sander-van-looy/profil/spieler/320842.
Transfer history data appended for: https://www.transfermarkt.com/anton-wede/profil/spieler/113044.
Transfer history data appended for: https://www.transfermarkt.com/john-chibuike/profil/spieler/112578.
Transfer history data appended for: https://www.transfermarkt.com/viktor-noring/profil/spieler/74091.
Transfer history data appended for: https://www.transfermarkt.com/gustaf-nilsson/profil/spieler/320440.
Transfer history data appended for: https://www.transfermarkt.com/lorik-ademi/profil/spieler/558685.
Transfer history data appended for: https://www.transfermarkt.com/tibor-joza/profil/spieler/33182.
Transfer history data appended for: https://www.transfermarkt.com/marcus-mathisen/profil/spieler/268216.
Transfer history data appended for: https://www.transfermarkt.com/tobias-englund/profil/spieler/116599.
Transfer history data appended for: https://www.transfermarkt.com/tobias-karlsson/profil/spieler/116530.
Transfer history data appended for: https://www.transfermarkt.com/johan-brattberg/profil/spieler/261998.
Transfer history data appended for: https://www.transfermarkt.com/carl-martinsson/profil/spieler/430819.
Transfer history data appended for: https://www.transfermarkt.com/christoffer-carlsson/profil/spieler/53244.
Transfer history data appended for: https://www.transfermarkt.com/melker-nilsson/profil/spieler/430828.
Transfer history data appended for: https://www.transfermarkt.com/carl-johansson/profil/spieler/225043.
Transfer history data appended for: https://www.transfermarkt.com/mahmut-ozen/profil/spieler/204404.
Transfer history data appended for: https://www.transfermarkt.com/axel-noren/profil/spieler/416104.
Transfer history data appended for: https://www.transfermarkt.com/rasmus-fridolf/profil/spieler/553832.
Transfer history data appended for: https://www.transfermarkt.com/kwame-kizito/profil/spieler/357127.
Transfer history data appended for: https://www.transfermarkt.com/jacob-ericsson/profil/spieler/138411.

Transfer history data appended for: https://www.transfermarkt.com/gabriel-johansson/profil/spieler/518474.
Transfer history data appended for: https://www.transfermarkt.com/nsima-peter/profil/spieler/204320.
Transfer history data appended for: https://www.transfermarkt.com/karl-soderstrom/profil/spieler/204417.
Transfer history data appended for: https://www.transfermarkt.com/mohammad-ahmadi/profil/spieler/593418.
Transfer history data appended for: https://www.transfermarkt.com/mumuni-abubakar/profil/spieler/213149.
Transfer history data appended for: https://www.transfermarkt.com/donald-makgetlwa/profil/spieler/550516.
Transfer history data appended for: https://www.transfermarkt.com/thabiso-mokoena/profil/spieler/437906.
Transfer history data appended for: https://www.transfermarkt.com/khomotso-masia/profil/spieler/437654.
Transfer history data appended for: https://www.transfermarkt.com/tsheamo-mashoene/profil/spieler/417549.
Transfer history data appended for: https://www.transfermarkt.com/tumelo-khutlang/profil/spieler/429966.
Transfer history data appended for: https://www.transfermarkt.com/rendani-maduwa/profil/spieler/437650.
Transfer history data appended for: https://www.transfermarkt.com/pentjie-zulu/profil/spieler/234114.
Transfer history data appended for: https://www.transfermarkt.com/rodrick-kabwe/profil/spieler/263088.
Transfer history data appended for: https://www.transfermarkt.com/tebogo-makobela/profil/spieler/371381.
Transfer history data appended for: https://www.transfermarkt.com/ethen-sampson/profil/spieler/316194.
Transfer history data appended for: https://www.transfermarkt.com/themba-ndlovu/profil/spieler/420561.
Transfer history data appended for: https://www.transfermarkt.com/xolani-ndlovu/profil/spieler/531278.
Transfer history data appended for: https://www.transfermarkt.com/tiklas-thutlwa/profil/spieler/801853.
Transfer history data appended for: https://www.transfermarkt.com/jonas-mendes/profil/spieler/191284.
Transfer history data appended for: https://www.transfermarkt.com/wiseman-maluleke/profil/spieler/308046.
Transfer history data appended for: https://www.transfermarkt.com/thivhavhudzi-ndou/profil/spieler/370615.
Transfer history data appended for: https://www.transfermarkt.com/king-ndlovu/profil/spieler/539336.
Transfer history data appended for: https://www.transfermarkt.com/tebogo-sodi/profil/spieler/567763.
Transfer history data appended for: https://www.transfermarkt.com/kenneth-nthatheni/profil/spieler/556422.
Transfer history data appended for: https://www.transfermarkt.com/donashano-malama/profil/spieler/315817.
Transfer history data appended for: https://www.transfermarkt.com/thuso-phala/profil/spieler/56233.
Transfer history data appended for: https://www.transfermarkt.com/rotshidzwa-muleka/profil/spieler/417538.
Transfer history data appended for: https://www.transfermarkt.com/sibusiso-khumalo/profil/spieler/126631.
Transfer history data appended for: https://www.transfermarkt.com/andiswa-ndawonde/profil/spieler/511794.
Transfer history data appended for: https://www.transfermarkt.com/joseph-douhadji/profil/spieler/425971.
Transfer history data appended for: https://www.transfermarkt.com/robert-ngambi/profil/spieler/63305.
Transfer history data appended for: https://www.transfermarkt.com/lefa-hlongwane/profil/spieler/416004.
Transfer history data appended for: https://www.transfermarkt.com/andriamirado-andrianarimanana/profil/spieler/512537.
Transfer history data appended for: https://www.transfermarkt.com/onyedikachi-ononogbu/profil/spieler/613121.
Transfer history data appended for: https://www.transfermarkt.com/rodney-ramagalela/profil/spieler/190264.
Transfer history data appended for: https://www.transfermarkt.com/ovidy-karuru/profil/spieler/86876.
Transfer history data appended for: https://www.transfermarkt.com/edwin-gyimah/profil/spieler/215196.
Transfer history data appended for: https://www.transfermarkt.com/lehlogonolo-masalesa/profil/spieler/139881.
Transfer history data appended for: https://www.transfermarkt.com/travis-graham/profil/spieler/234009.
Transfer history data appended for: https://www.transfermarkt.com/lindokuhle-sithole/profil/spieler/563482.
Transfer history data appended for: https://www.transfermarkt.com/daylon-claasen/profil/spieler/51224.
Transfer history data appended for: https://www.transfermarkt.com/bongani-mpandle/profil/spieler/282420.
Transfer history data appended for: https://www.transfermarkt.com/fares-hachi/profil/spieler/380466.
Transfer history data appended for: https://www.transfermarkt.com/jose-ali-meza/profil/spieler/235718.
Transfer history data appended for: https://www.transfermarkt.com/deolin-mekoa/profil/spieler/330715.
Transfer history data appended for: https://www.transfermarkt.com/malebogo-modise/profil/spieler/341967.
Transfer history data appended for: https://www.transfermarkt.com/tebogo-tlolane/profil/spieler/466249.
Transfer history data appended for: https://www.transfermarkt.com/sibusiso-hlubi/profil/spieler/484857.
Transfer history data appended for: https://www.transfermarkt.com/clive-augusto/profil/spieler/699441.
Transfer history data appended for: https://www.transfermarkt.com/ujaun-mcdonald/profil/spieler/563481.
Transfer history data appended for: https://www.transfermarkt.com/phumlani-ntshangase/profil/spieler/253314.
Transfer history data appended for: https://www.transfermarkt.com/keagan-buchanan/profil/spieler/184877.
Transfer history data appended for: https://www.transfermarkt.com/bongokuhle-hlongwane/profil/spieler/669202.
Transfer history data appended for: https://www.transfermarkt.com/nazeer-allie/profil/spieler/39801.
Transfer history data appended for: https://www.transfermarkt.com/mxolisi-kunene/profil/spieler/388256.
Transfer history data appended for: https://www.transfermarkt.com/rushine-de-reuck/profil/spieler/511793.
Transfer history data appended for: https://www.transfermarkt.com/pogiso-sanoka/profil/spieler/386054.
Transfer history data appended for: https://www.transfermarkt.com/riyaaz-ismail/profil/spieler/390596.
Transfer history data appended for: https://www.transfermarkt.com/tyroane-sandows/profil/spieler/364401.
Transfer history data appended for: https://www.transfermarkt.com/daniel-morgan/profil/spieler/133250.
Transfer history data appended for: https://www.transfermarkt.com/bandile-shandu/profil/spieler/253848.
Transfer history data appended for: https://www.transfermarkt.com/sizwe-muthwa/profil/spieler/598510.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-mwange/profil/spieler/708950.
Transfer history data appended for: https://www.transfermarkt.com/kwanda-mngonyama/profil/spieler/234019.
Transfer history data appended for: https://www.transfermarkt.com/nathanael-mbourou/profil/spieler/496561.
Transfer history data appended for: https://www.transfermarkt.com/yusuf-jappie/profil/spieler/357370.
Transfer history data appended for: https://www.transfermarkt.com/jethren-barr/profil/spieler/240881.
Transfer history data appended for: https://www.transfermarkt.com/judas-moseamedi/profil/spieler/386343.
Transfer history data appended for: https://www.transfermarkt.com/thabiso-kutumela/profil/spieler/417536.
Transfer history data appended for: https://www.transfermarkt.com/keegan-ritchie/profil/spieler/110314.
Transfer history data appended for: https://www.transfermarkt.com/vincent-sithole/profil/spieler/567250.
Transfer history data appended for: https://www.transfermarkt.com/simphiwe-tshabalala/profil/spieler/370598.
Transfer history data appended for: https://www.transfermarkt.com/zaphaniah-mbokoma/profil/spieler/242539.
Transfer history data appended for: https://www.transfermarkt.com/given-thibedi/profil/spieler/529921.
Transfer history data appended for: https://www.transfermarkt.com/deveraux-springbok/profil/spieler/370601.
Transfer history data appended for: https://www.transfermarkt.com/njabulo-ngcobo/profil/spieler/457014.
Transfer history data appended for: https://www.transfermarkt.com/sidney-motshweni/profil/spieler/312279.
Transfer history data appended for: https://www.transfermarkt.com/thela-ngobeni/profil/spieler/106031.
Transfer history data appended for: https://www.transfermarkt.com/tlakusani-mthethwa/profil/spieler/397495.

Transfer history data appended for: https://www.transfermarkt.com/ruzaigh-gamildien/profil/spieler/192460.
Transfer history data appended for: https://www.transfermarkt.com/mokeri-senwamadi/profil/spieler/609256.
Transfer history data appended for: https://www.transfermarkt.com/daniel-gozar/profil/spieler/283561.
Transfer history data appended for: https://www.transfermarkt.com/sifiso-hlanti/profil/spieler/162484.
Transfer history data appended for: https://www.transfermarkt.com/lebohang-mokoena/profil/spieler/37730.
Transfer history data appended for: https://www.transfermarkt.com/kamohelo-mahlatsi/profil/spieler/563689.
Transfer history data appended for: https://www.transfermarkt.com/musa-nyatama/profil/spieler/107421.
Transfer history data appended for: https://www.transfermarkt.com/virgil-vries/profil/spieler/160204.
Transfer history data appended for: https://www.transfermarkt.com/thabo-matlaba/profil/spieler/160649.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-ndiki/profil/spieler/357349.
Transfer history data appended for: https://www.transfermarkt.com/mthokozisi-shwabule/profil/spieler/609259.
Transfer history data appended for: https://www.transfermarkt.com/sanele-tshabalala/profil/spieler/341953.
Transfer history data appended for: https://www.transfermarkt.com/thapelo-tshilo/profil/spieler/118959.
Transfer history data appended for: https://www.transfermarkt.com/junaid-sait/profil/spieler/320184.
Transfer history data appended for: https://www.transfermarkt.com/phetso-maphanga/profil/spieler/417764.
Transfer history data appended for: https://www.transfermarkt.com/patrick-meso/profil/spieler/370593.
Transfer history data appended for: https://www.transfermarkt.com/givemore-khupe/profil/spieler/471292.
Transfer history data appended for: https://www.transfermarkt.com/slindokuhle-mponzo/profil/spieler/699382.
Transfer history data appended for: https://www.transfermarkt.com/nathaniel-tladi/profil/spieler/370608.
Transfer history data appended for: https://www.transfermarkt.com/sibusiso-masina/profil/spieler/386344.
Transfer history data appended for: https://www.transfermarkt.com/sizwe-nkosi/profil/spieler/636475.
Transfer history data appended for: https://www.transfermarkt.com/joseph-mhlongo/profil/spieler/383452.
Transfer history data appended for: https://www.transfermarkt.com/joshua-sauls/profil/spieler/233621.
Transfer history data appended for: https://www.transfermarkt.com/zanempi-methula/profil/spieler/609258.
Transfer history data appended for: https://www.transfermarkt.com/wandisile-letlabika/profil/spieler/26618.
Transfer history data appended for: https://www.transfermarkt.com/siphelele-ndlovu/profil/spieler/637865.
Transfer history data appended for: https://www.transfermarkt.com/lutho-mbanjwa/profil/spieler/550515.
Transfer history data appended for: https://www.transfermarkt.com/vuyo-mere/profil/spieler/37729.
Transfer history data appended for: https://www.transfermarkt.com/fawaaz-basadien/profil/spieler/478520.
Transfer history data appended for: https://www.transfermarkt.com/kagiso-malinga/profil/spieler/437720.
Transfer history data appended for: https://www.transfermarkt.com/sizwe-twala/profil/spieler/711070.
Transfer history data appended for: https://www.transfermarkt.com/sammy-seabi/profil/spieler/386494.
Transfer history data appended for: https://www.transfermarkt.com/moeketsi-makhanya/profil/spieler/699359.
Transfer history data appended for: https://www.transfermarkt.com/ayanda-rorwana/profil/spieler/554213.
Transfer history data appended for: https://www.transfermarkt.com/sipho-sibiya/profil/spieler/609257.
Transfer history data appended for: https://www.transfermarkt.com/itumeleng-shopane/profil/spieler/471289.
Transfer history data appended for: https://www.transfermarkt.com/broderick-burds/profil/spieler/196100.
Transfer history data appended for: https://www.transfermarkt.com/bafana-kali/profil/spieler/333180.
Transfer history data appended for: https://www.transfermarkt.com/thabo-mosadi/profil/spieler/237056.
Transfer history data appended for: https://www.transfermarkt.com/mfanafuthi-shozi/profil/spieler/437642.
Transfer history data appended for: https://www.transfermarkt.com/rodwell-chinyengetere/profil/spieler/237435.
Transfer history data appended for: https://www.transfermarkt.com/sikhumbuzo-ncube/profil/spieler/643813.
Transfer history data appended for: https://www.transfermarkt.com/evidence-makgopa/profil/spieler/746781.
Transfer history data appended for: https://www.transfermarkt.com/vusi-sibiya/profil/spieler/626895.
Transfer history data appended for: https://www.transfermarkt.com/denwin-farmer/profil/spieler/312258.
Transfer history data appended for: https://www.transfermarkt.com/richard-mbulu/profil/spieler/513319.
Transfer history data appended for: https://www.transfermarkt.com/thabo-nemukondeni/profil/spieler/420530.
Transfer history data appended for: https://www.transfermarkt.com/elvis-chipezeze/profil/spieler/429972.
Transfer history data appended for: https://www.transfermarkt.com/matome-kgoetyane/profil/spieler/503708.
Transfer history data appended for: https://www.transfermarkt.com/kagiso-selemela/profil/spieler/531280.
Transfer history data appended for: https://www.transfermarkt.com/elliot-seema/profil/spieler/537740.
Transfer history data appended for: https://www.transfermarkt.com/oscarine-masuluke/profil/spieler/417537.
Transfer history data appended for: https://www.transfermarkt.com/bonginkosi-makume/profil/spieler/592698.
Transfer history data appended for: https://www.transfermarkt.com/gerald-phiri-junior/profil/spieler/376901.
Transfer history data appended for: https://www.transfermarkt.com/jemondre-dickens/profil/spieler/621774.
Transfer history data appended for: https://www.transfermarkt.com/naeem-amoojee/profil/spieler/809642.
Transfer history data appended for: https://www.transfermarkt.com/mogau-bowali/profil/spieler/840558.
Transfer history data appended for: https://www.transfermarkt.com/goodman-mosele/profil/spieler/531279.
Transfer history data appended for: https://www.transfermarkt.com/cheslyn-jampies/profil/spieler/145177.
Transfer history data appended for: https://www.transfermarkt.com/sello-molewa/profil/spieler/741406.
Transfer history data appended for: https://www.transfermarkt.com/kgodiso-monama/profil/spieler/636473.
Transfer history data appended for: https://www.transfermarkt.com/manuel-kambala/profil/spieler/514196.
Transfer history data appended for: https://www.transfermarkt.com/tshidiso-patjie/profil/spieler/330729.
Transfer history data appended for: https://www.transfermarkt.com/ananias-gebhardt/profil/spieler/199219.
Transfer history data appended for: https://www.transfermarkt.com/nhlanhla-mgaga/profil/spieler/637876.
Transfer history data appended for: https://www.transfermarkt.com/kgosto-maloka/profil/spieler/735310.
Transfer history data appended for: https://www.transfermarkt.com/thamsanqa-masiya/profil/spieler/353057.
Transfer history data appended for: https://www.transfermarkt.com/lawrence-ntswane/profil/spieler/647567.
Transfer history data appended for: https://www.transfermarkt.com/tshego-molapo/profil/spieler/806795.
Transfer history data appended for: https://www.transfermarkt.com/martin-nsimba/profil/spieler/566498.
Transfer history data appended for: https://www.transfermarkt.com/augustine-mahlonoko/profil/spieler/596912.
Transfer history data appended for: https://www.transfermarkt.com/siseko-manona/profil/spieler/244759.
Transfer history data appended for: https://www.transfermarkt.com/wonderboy-makhubu/profil/spieler/437660.
Transfer history data appended for: https://www.transfermarkt.com/mbulelo-wambi/profil/spieler/193672.
Transfer history data appended for: https://www.transfermarkt.com/shaune-mogaila/profil/spieler/468686.
Transfer history data appended for: https://www.transfermarkt.com/wensten-van-der-linde/profil/spieler/320189.
Transfer history data appended for: https://www.transfermarkt.com/gaona-modisane/profil/spieler/417731.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-williams/profil/spieler/421969.
Transfer history data appended for: https://www.transfermarkt.com/marks-munyai/profil/spieler/370623.

Transfer history data appended for: https://www.transfermarkt.com/mlungisi-mbunjana/profil/spieler/417767.
Transfer history data appended for: https://www.transfermarkt.com/karabo-tshepe/profil/spieler/236810.
Transfer history data appended for: https://www.transfermarkt.com/chitiya-mususu/profil/spieler/568421.
Transfer history data appended for: https://www.transfermarkt.com/ntshuxeko-ndlovu/profil/spieler/556811.
Transfer history data appended for: https://www.transfermarkt.com/marlon-heugh/profil/spieler/370572.
Transfer history data appended for: https://www.transfermarkt.com/reneilwe-letsholonyane/profil/spieler/109903.
Transfer history data appended for: https://www.transfermarkt.com/bevan-fransman/profil/spieler/38451.
Transfer history data appended for: https://www.transfermarkt.com/tumelo-bodibe/profil/spieler/417728.
Transfer history data appended for: https://www.transfermarkt.com/felix-badenhorst/profil/spieler/82040.
Transfer history data appended for: https://www.transfermarkt.com/sihle-nduli/profil/spieler/304978.
Transfer history data appended for: https://www.transfermarkt.com/melusi-buthelezi/profil/spieler/605905.
Transfer history data appended for: https://www.transfermarkt.com/luckyboy-mokoena/profil/spieler/253312.
Transfer history data appended for: https://www.transfermarkt.com/lindokuhle-mbatha/profil/spieler/118977.
Transfer history data appended for: https://www.transfermarkt.com/khayelihle-shozi/profil/spieler/365597.
Transfer history data appended for: https://www.transfermarkt.com/wayde-lekay/profil/spieler/556429.
Transfer history data appended for: https://www.transfermarkt.com/spiwe-msimango/profil/spieler/556784.
Transfer history data appended for: https://www.transfermarkt.com/ebrahim-seedat/profil/spieler/187745.
Transfer history data appended for: https://www.transfermarkt.com/myer-bevan/profil/spieler/419571.
Transfer history data appended for: https://www.transfermarkt.com/mxolisi-macuphu/profil/spieler/162488.
Transfer history data appended for: https://www.transfermarkt.com/sphiwe-mahlangu/profil/spieler/547130.
Transfer history data appended for: https://www.transfermarkt.com/justice-figuareido/profil/spieler/604952.
Transfer history data appended for: https://www.transfermarkt.com/masilake-phohlongo/profil/spieler/357352.
Transfer history data appended for: https://www.transfermarkt.com/kurt-lentjies/profil/spieler/109977.
Transfer history data appended for: https://www.transfermarkt.com/andile-mbenyane/profil/spieler/144224.
Transfer history data appended for: https://www.transfermarkt.com/thokozani-sekotlong/profil/spieler/231605.
Transfer history data appended for: https://www.transfermarkt.com/masixole-nkewana/profil/spieler/419641.
Transfer history data appended for: https://www.transfermarkt.com/mduduzi-sibeko/profil/spieler/420562.
Transfer history data appended for: https://www.transfermarkt.com/vuyolwethu-dinge/profil/spieler/827564.
Transfer history data appended for: https://www.transfermarkt.com/nyiko-mobbie/profil/spieler/435086.
Transfer history data appended for: https://www.transfermarkt.com/bienvenu-eva-nga/profil/spieler/564547.
Transfer history data appended for: https://www.transfermarkt.com/ryan-rae/profil/spieler/258355.
Transfer history data appended for: https://www.transfermarkt.com/tumiso-mogakwe/profil/spieler/689123.
Transfer history data appended for: https://www.transfermarkt.com/frederic-nsabiyumva/profil/spieler/340031.
Transfer history data appended for: https://www.transfermarkt.com/silas-maziya/profil/spieler/450798.
Transfer history data appended for: https://www.transfermarkt.com/mlungisi-mazibuko/profil/spieler/179690.
Transfer history data appended for: https://www.transfermarkt.com/augustine-chidi-kwem/profil/spieler/708891.
Transfer history data appended for: https://www.transfermarkt.com/xolani-maholo/profil/spieler/528913.
Transfer history data appended for: https://www.transfermarkt.com/sandile-mthethwa/profil/spieler/420526.
Transfer history data appended for: https://www.transfermarkt.com/tsietsi-khooa/profil/spieler/639132.
Transfer history data appended for: https://www.transfermarkt.com/luvuyo-phewa/profil/spieler/647577.
Transfer history data appended for: https://www.transfermarkt.com/riaan-hanamub/profil/spieler/514203.
Transfer history data appended for: https://www.transfermarkt.com/sithembiso-ngobe/profil/spieler/532669.
Transfer history data appended for: https://www.transfermarkt.com/zusakhe-sali/profil/spieler/596910.
Transfer history data appended for: https://www.transfermarkt.com/ramasimong-maloisane/profil/spieler/601971.
Transfer history data appended for: https://www.transfermarkt.com/ayanda-mtshali/profil/spieler/160637.
Transfer history data appended for: https://www.transfermarkt.com/isaac-nhlapo/profil/spieler/329541.
Transfer history data appended for: https://www.transfermarkt.com/gregory-damons/profil/spieler/690790.
Transfer history data appended for: https://www.transfermarkt.com/avela-cezu/profil/spieler/391733.
Transfer history data appended for: https://www.transfermarkt.com/sizwe-mdlinzo/profil/spieler/346094.
Transfer history data appended for: https://www.transfermarkt.com/keenan-phillips/profil/spieler/647578.
Transfer history data appended for: https://www.transfermarkt.com/sipho-mbule/profil/spieler/436374.
Transfer history data appended for: https://www.transfermarkt.com/grant-kekana/profil/spieler/43030.
Transfer history data appended for: https://www.transfermarkt.com/ronwen-williams/profil/spieler/175577.
Transfer history data appended for: https://www.transfermarkt.com/thatayaone-ditlhokwe/profil/spieler/594128.
Transfer history data appended for: https://www.transfermarkt.com/moses-waiswa/profil/spieler/615607.
Transfer history data appended for: https://www.transfermarkt.com/guily-manziba/profil/spieler/568423.
Transfer history data appended for: https://www.transfermarkt.com/luke-fleurs/profil/spieler/467606.
Transfer history data appended for: https://www.transfermarkt.com/siyabonga-nhlapo/profil/spieler/196110.
Transfer history data appended for: https://www.transfermarkt.com/ghampani-lungu/profil/spieler/604391.
Transfer history data appended for: https://www.transfermarkt.com/teboho-mokoena/profil/spieler/436372.
Transfer history data appended for: https://www.transfermarkt.com/oswin-appollis/profil/spieler/673381.
Transfer history data appended for: https://www.transfermarkt.com/kudakwashe-mahachi/profil/spieler/288981.
Transfer history data appended for: https://www.transfermarkt.com/zama-rambuwane/profil/spieler/312246.
Transfer history data appended for: https://www.transfermarkt.com/jamie-webber/profil/spieler/471290.
Transfer history data appended for: https://www.transfermarkt.com/iqraam-rayners/profil/spieler/337884.
Transfer history data appended for: https://www.transfermarkt.com/khanyisile-mayo/profil/spieler/720440.
Transfer history data appended for: https://www.transfermarkt.com/onismor-bhasera/profil/spieler/48255.
Transfer history data appended for: https://www.transfermarkt.com/thamsanqa-gabuza/profil/spieler/138106.
Transfer history data appended for: https://www.transfermarkt.com/bongani-khumalo/profil/spieler/82215.
Transfer history data appended for: https://www.transfermarkt.com/jesse-donn/profil/spieler/530635.
Transfer history data appended for: https://www.transfermarkt.com/gape-moralo/profil/spieler/801759.
Transfer history data appended for: https://www.transfermarkt.com/evans-rusike/profil/spieler/382166.
Transfer history data appended for: https://www.transfermarkt.com/selaelo-rasebotja/profil/spieler/803083.
Transfer history data appended for: https://www.transfermarkt.com/george-chigova/profil/spieler/221386.
Transfer history data appended for: https://www.transfermarkt.com/lucky-mohomi/profil/spieler/383440.
Transfer history data appended for: https://www.transfermarkt.com/thalente-mbatha/profil/spieler/735697.
Transfer history data appended for: https://www.transfermarkt.com/bradley-grobler/profil/spieler/113282.
Transfer history data appended for: https://www.transfermarkt.com/boalefa-pule/profil/spieler/195824.
Transfer history data appended for: https://www.transfermarkt.com/mpho-mathebula/profil/spieler/799621.

Transfer history data appended for: https://www.transfermarkt.com/zitha-macheke/profil/spieler/332245.
Transfer history data appended for: https://www.transfermarkt.com/junior-mendieta/profil/spieler/486132.
Transfer history data appended for: https://www.transfermarkt.com/bongane-mathabela/profil/spieler/353052.
Transfer history data appended for: https://www.transfermarkt.com/robyn-johannes/profil/spieler/109970.
Transfer history data appended for: https://www.transfermarkt.com/ally-msengi/profil/spieler/733024.
Transfer history data appended for: https://www.transfermarkt.com/tristan-hanslo/profil/spieler/672798.
Transfer history data appended for: https://www.transfermarkt.com/ashley-du-preez/profil/spieler/478498.
Transfer history data appended for: https://www.transfermarkt.com/inga-nyeleka/profil/spieler/685629.
Transfer history data appended for: https://www.transfermarkt.com/stanley-dimgba/profil/spieler/353667.
Transfer history data appended for: https://www.transfermarkt.com/mark-van-heerden/profil/spieler/109888.
Transfer history data appended for: https://www.transfermarkt.com/keegan-pool/profil/spieler/551701.
Transfer history data appended for: https://www.transfermarkt.com/sibusiso-mthethwa/profil/spieler/236067.
Transfer history data appended for: https://www.transfermarkt.com/leletu-skelem/profil/spieler/632198.
Transfer history data appended for: https://www.transfermarkt.com/nathan-sinkala/profil/spieler/212420.
Transfer history data appended for: https://www.transfermarkt.com/diego-franco/profil/spieler/259736.
Transfer history data appended for: https://www.transfermarkt.com/mswati-mavuso/profil/spieler/467605.
Transfer history data appended for: https://www.transfermarkt.com/asavela-mbekile/profil/spieler/242720.
Transfer history data appended for: https://www.transfermarkt.com/waseem-isaacs/profil/spieler/176979.
Transfer history data appended for: https://www.transfermarkt.com/lee-langeveldt/profil/spieler/42826.
Transfer history data appended for: https://www.transfermarkt.com/alan-robertson/profil/spieler/286149.
Transfer history data appended for: https://www.transfermarkt.com/jayden-adams/profil/spieler/804472.
Transfer history data appended for: https://www.transfermarkt.com/sage-stephens-lottering-/profil/spieler/160289.
Transfer history data appended for: https://www.transfermarkt.com/phathutshedzo-nange/profil/spieler/370614.
Transfer history data appended for: https://www.transfermarkt.com/dean-david-van-rooyen/profil/spieler/514175.
Transfer history data appended for: https://www.transfermarkt.com/zwelethu-ndlovu/profil/spieler/370596.
Transfer history data appended for: https://www.transfermarkt.com/granwald-scott/profil/spieler/39822.
Transfer history data appended for: https://www.transfermarkt.com/kristopher-bergman/profil/spieler/160470.
Transfer history data appended for: https://www.transfermarkt.com/daylan-hawes/profil/spieler/386390.
Transfer history data appended for: https://www.transfermarkt.com/tshireletso-motsogi/profil/spieler/685636.
Transfer history data appended for: https://www.transfermarkt.com/mogamad-de-goede/profil/spieler/370568.
Transfer history data appended for: https://www.transfermarkt.com/ryan-moon/profil/spieler/312245.
Transfer history data appended for: https://www.transfermarkt.com/azeemud-deen-brenner/profil/spieler/633511.
Transfer history data appended for: https://www.transfermarkt.com/molahlehi-khunyedi/profil/spieler/651930.
Transfer history data appended for: https://www.transfermarkt.com/gift-motupa/profil/spieler/357400.
Transfer history data appended for: https://www.transfermarkt.com/haashim-domingo/profil/spieler/353056.
Transfer history data appended for: https://www.transfermarkt.com/thapelo-morena/profil/spieler/297509.
Transfer history data appended for: https://www.transfermarkt.com/tebogo-langerman/profil/spieler/110094.
Transfer history data appended for: https://www.transfermarkt.com/themba-zwane/profil/spieler/176578.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-nascimento/profil/spieler/126203.
Transfer history data appended for: https://www.transfermarkt.com/lebohang-maboe/profil/spieler/420543.
Transfer history data appended for: https://www.transfermarkt.com/sibusiso-vilakazi/profil/spieler/129335.
Transfer history data appended for: https://www.transfermarkt.com/tiyani-mabunda/profil/spieler/173935.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-goss/profil/spieler/258304.
Transfer history data appended for: https://www.transfermarkt.com/aubrey-modiba/profil/spieler/353432.
Transfer history data appended for: https://www.transfermarkt.com/mothobi-mvala/profil/spieler/370606.
Transfer history data appended for: https://www.transfermarkt.com/keletso-makgalwa/profil/spieler/436370.
Transfer history data appended for: https://www.transfermarkt.com/peter-shalulile/profil/spieler/397937.
Transfer history data appended for: https://www.transfermarkt.com/grant-margeman/profil/spieler/370566.
Transfer history data appended for: https://www.transfermarkt.com/jody-february/profil/spieler/304951.
Transfer history data appended for: https://www.transfermarkt.com/denis-onyango/profil/spieler/68096.
Transfer history data appended for: https://www.transfermarkt.com/mosa-lebusa/profil/spieler/236788.
Transfer history data appended for: https://www.transfermarkt.com/lesedi-kapinga/profil/spieler/547832.
Transfer history data appended for: https://www.transfermarkt.com/rivaldo-coetzee/profil/spieler/304020.
Transfer history data appended for: https://www.transfermarkt.com/george-maluleka/profil/spieler/108600.
Transfer history data appended for: https://www.transfermarkt.com/kennedy-mweene/profil/spieler/66399.
Transfer history data appended for: https://www.transfermarkt.com/khuliso-mudau/profil/spieler/450806.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-affonso/profil/spieler/251688.
Transfer history data appended for: https://www.transfermarkt.com/sphelele-mkhulise/profil/spieler/492135.
Transfer history data appended for: https://www.transfermarkt.com/lyle-lakay/profil/spieler/152501.
Transfer history data appended for: https://www.transfermarkt.com/gaston-sirino/profil/spieler/401811.
Transfer history data appended for: https://www.transfermarkt.com/bangaly-soumahoro/profil/spieler/221100.
Transfer history data appended for: https://www.transfermarkt.com/motjeka-madisha/profil/spieler/304970.
Transfer history data appended for: https://www.transfermarkt.com/andile-jali/profil/spieler/118538.
Transfer history data appended for: https://www.transfermarkt.com/brian-onyango/profil/spieler/208076.
Transfer history data appended for: https://www.transfermarkt.com/reyaad-pieterse/profil/spieler/160572.
Transfer history data appended for: https://www.transfermarkt.com/hlompho-kekana/profil/spieler/108595.
Transfer history data appended for: https://www.transfermarkt.com/kermit-erasmus/profil/spieler/65992.
Transfer history data appended for: https://www.transfermarkt.com/promise-mkhuma/profil/spieler/584217.
Transfer history data appended for: https://www.transfermarkt.com/daniel-cardoso/profil/spieler/236047.
Transfer history data appended for: https://www.transfermarkt.com/philani-zulu/profil/spieler/226250.
Transfer history data appended for: https://www.transfermarkt.com/dumisani-zuma/profil/spieler/334833.
Transfer history data appended for: https://www.transfermarkt.com/lebohang-lesako/profil/spieler/529926.
Transfer history data appended for: https://www.transfermarkt.com/teddy-akumu/profil/spieler/175104.
Transfer history data appended for: https://www.transfermarkt.com/brylon-petersen/profil/spieler/498986.
Transfer history data appended for: https://www.transfermarkt.com/keletso-sifama/profil/spieler/801655.
Transfer history data appended for: https://www.transfermarkt.com/karabo-molefe/profil/spieler/655033.
Transfer history data appended for: https://www.transfermarkt.com/khama-billiat/profil/spieler/135849.
Transfer history data appended for: https://www.transfermarkt.com/kgotso-moleko/profil/spieler/160500.
Transfer history data appended for: https://www.transfermarkt.com/happy-mashiane/profil/spieler/554214.

Transfer history data appended for: https://www.transfermarkt.com/nkosingiphile-ngcobo/profil/spieler/471293.
Transfer history data appended for: https://www.transfermarkt.com/lazarous-kambole/profil/spieler/365314.
Transfer history data appended for: https://www.transfermarkt.com/eric-mathoho/profil/spieler/140208.
Transfer history data appended for: https://www.transfermarkt.com/yagan-sasman/profil/spieler/324952.
Transfer history data appended for: https://www.transfermarkt.com/samir-nurkovic/profil/spieler/192791.
Transfer history data appended for: https://www.transfermarkt.com/ramahlwe-mphahlele/profil/spieler/110303.
Transfer history data appended for: https://www.transfermarkt.com/daniel-akpeyi/profil/spieler/28725.
Transfer history data appended for: https://www.transfermarkt.com/siphosakhe-ntiya-ntiya/profil/spieler/312288.
Transfer history data appended for: https://www.transfermarkt.com/reeve-frosler/profil/spieler/341955.
Transfer history data appended for: https://www.transfermarkt.com/lebogang-manyama/profil/spieler/160434.
Transfer history data appended for: https://www.transfermarkt.com/siphelele-ntshangase/profil/spieler/365611.
Transfer history data appended for: https://www.transfermarkt.com/bruce-bvuma/profil/spieler/498985.
Transfer history data appended for: https://www.transfermarkt.com/kearyn-baccus/profil/spieler/171419.
Transfer history data appended for: https://www.transfermarkt.com/njabulo-blom/profil/spieler/554197.
Transfer history data appended for: https://www.transfermarkt.com/willard-katsande/profil/spieler/160050.
Transfer history data appended for: https://www.transfermarkt.com/itumeleng-khune/profil/spieler/39616.
Transfer history data appended for: https://www.transfermarkt.com/leonardo-castro/profil/spieler/92055.
Transfer history data appended for: https://www.transfermarkt.com/siyabonga-ngezana/profil/spieler/445610.
Transfer history data appended for: https://www.transfermarkt.com/kgotso-mofokeng/profil/spieler/640890.
Transfer history data appended for: https://www.transfermarkt.com/mbhazima-rikhotso/profil/spieler/356170.
Transfer history data appended for: https://www.transfermarkt.com/tumelo-njoti/profil/spieler/689121.
Transfer history data appended for: https://www.transfermarkt.com/given-mashikinya/profil/spieler/333171.
Transfer history data appended for: https://www.transfermarkt.com/neo-maema/profil/spieler/560463.
Transfer history data appended for: https://www.transfermarkt.com/sera-motebang/profil/spieler/429971.
Transfer history data appended for: https://www.transfermarkt.com/mpusana-tani/profil/spieler/551700.
Transfer history data appended for: https://www.transfermarkt.com/vusi-shikweni/profil/spieler/385149.
Transfer history data appended for: https://www.transfermarkt.com/mzwanele-mahashe/profil/spieler/173827.
Transfer history data appended for: https://www.transfermarkt.com/matshego-nyapoli/profil/spieler/453371.
Transfer history data appended for: https://www.transfermarkt.com/ndumiso-mabena/profil/spieler/118939.
Transfer history data appended for: https://www.transfermarkt.com/shadrack-kobedi/profil/spieler/453373.
Transfer history data appended for: https://www.transfermarkt.com/menzi-ndwandwe/profil/spieler/391732.
Transfer history data appended for: https://www.transfermarkt.com/sello-matjila/profil/spieler/386492.
Transfer history data appended for: https://www.transfermarkt.com/jabulani-ncobeni/profil/spieler/112851.
Transfer history data appended for: https://www.transfermarkt.com/justice-chabalala/profil/spieler/407913.
Transfer history data appended for: https://www.transfermarkt.com/andile-fikizolo/profil/spieler/329521.
Transfer history data appended for: https://www.transfermarkt.com/teboho-khasipe/profil/spieler/340081.
Transfer history data appended for: https://www.transfermarkt.com/ronald-pfumbidzai/profil/spieler/383400.
Transfer history data appended for: https://www.transfermarkt.com/mondli-mpoto/profil/spieler/312280.
Transfer history data appended for: https://www.transfermarkt.com/gerhard-phafoli/profil/spieler/554216.
Transfer history data appended for: https://www.transfermarkt.com/keabetswe-mabe/profil/spieler/453372.
Transfer history data appended for: https://www.transfermarkt.com/siphelele-luthuli/profil/spieler/277483.
Transfer history data appended for: https://www.transfermarkt.com/jackson-mabokgwane/profil/spieler/109978.
Transfer history data appended for: https://www.transfermarkt.com/sifiso-ngobeni/profil/spieler/699755.
Transfer history data appended for: https://www.transfermarkt.com/ryan-de-jongh/profil/spieler/206334.
Transfer history data appended for: https://www.transfermarkt.com/thato-lingwati/profil/spieler/371382.
Transfer history data appended for: https://www.transfermarkt.com/aviwe-nyamende/profil/spieler/448651.
Transfer history data appended for: https://www.transfermarkt.com/tebogo-potsane/profil/spieler/455771.
Transfer history data appended for: https://www.transfermarkt.com/tumelo-mangweni/profil/spieler/628355.
Transfer history data appended for: https://www.transfermarkt.com/victor-letsoalo/profil/spieler/417540.
Transfer history data appended for: https://www.transfermarkt.com/lantshene-phalane/profil/spieler/190876.
Transfer history data appended for: https://www.transfermarkt.com/langa-mvana/profil/spieler/601973.
Transfer history data appended for: https://www.transfermarkt.com/menzi-masuku/profil/spieler/217498.
Transfer history data appended for: https://www.transfermarkt.com/harris-tchilimbou/profil/spieler/80436.
Transfer history data appended for: https://www.transfermarkt.com/lucky-baloyi/profil/spieler/157925.
Transfer history data appended for: https://www.transfermarkt.com/rendani-ndou/profil/spieler/330730.
Transfer history data appended for: https://www.transfermarkt.com/sipho-chaine/profil/spieler/453370.
Transfer history data appended for: https://www.transfermarkt.com/linda-mntambo/profil/spieler/371388.
Transfer history data appended for: https://www.transfermarkt.com/terrence-dzvukamanja/profil/spieler/599002.
Transfer history data appended for: https://www.transfermarkt.com/fortune-makaringe/profil/spieler/370663.
Transfer history data appended for: https://www.transfermarkt.com/ben-motshwari/profil/spieler/334120.
Transfer history data appended for: https://www.transfermarkt.com/happy-jele/profil/spieler/75393.
Transfer history data appended for: https://www.transfermarkt.com/zakhele-lepasa/profil/spieler/596913.
Transfer history data appended for: https://www.transfermarkt.com/gabadinho-mhango/profil/spieler/242021.
Transfer history data appended for: https://www.transfermarkt.com/austin-muwowo/profil/spieler/684730.
Transfer history data appended for: https://www.transfermarkt.com/abel-mabaso/profil/spieler/236862.
Transfer history data appended for: https://www.transfermarkt.com/azola-tshobeni/profil/spieler/840556.
Transfer history data appended for: https://www.transfermarkt.com/innocent-maela/profil/spieler/308045.
Transfer history data appended for: https://www.transfermarkt.com/wayne-sandilands/profil/spieler/113297.
Transfer history data appended for: https://www.transfermarkt.com/thabiso-monyane/profil/spieler/579037.
Transfer history data appended for: https://www.transfermarkt.com/siyabonga-mpontshane/profil/spieler/160650.
Transfer history data appended for: https://www.transfermarkt.com/siphesihle-ndlovu/profil/spieler/446715.
Transfer history data appended for: https://www.transfermarkt.com/thulani-hlatshwayo/profil/spieler/124391.
Transfer history data appended for: https://www.transfermarkt.com/richard-ofori/profil/spieler/274756.
Transfer history data appended for: https://www.transfermarkt.com/tshegofatso-mabasa/profil/spieler/342489.
Transfer history data appended for: https://www.transfermarkt.com/kabelo-dlamini/profil/spieler/537741.
Transfer history data appended for: https://www.transfermarkt.com/nkanyiso-zungu/profil/spieler/385132.
Transfer history data appended for: https://www.transfermarkt.com/ntsikelelo-nyauza/profil/spieler/177338.
Transfer history data appended for: https://www.transfermarkt.com/thabang-monare/profil/spieler/255398.
Transfer history data appended for: https://www.transfermarkt.com/wayde-jooste/profil/spieler/282407.

Transfer history data appended for: https://www.transfermarkt.com/deon-hotto/profil/spieler/273903.
Transfer history data appended for: https://www.transfermarkt.com/collins-makgaka/profil/spieler/438861.
Transfer history data appended for: https://www.transfermarkt.com/maliele-vincent-pule/profil/spieler/329523.
Transfer history data appended for: https://www.transfermarkt.com/thembinkosi-lorch/profil/spieler/330726.
Transfer history data appended for: https://www.transfermarkt.com/bongani-sam/profil/spieler/556783.
Transfer history data appended for: https://www.transfermarkt.com/paseka-mako/profil/spieler/409574.
Transfer history data appended for: https://www.transfermarkt.com/jean-marc-makusu/profil/spieler/310759.
Transfer history data appended for: https://www.transfermarkt.com/mpho-makola/profil/spieler/110634.
Transfer history data appended for: https://www.transfermarkt.com/taahir-goedeman/profil/spieler/801355.
Transfer history data appended for: https://www.transfermarkt.com/shane-roberts/profil/spieler/530183.
Transfer history data appended for: https://www.transfermarkt.com/peter-leeuwenburgh/profil/spieler/166326.
Transfer history data appended for: https://www.transfermarkt.com/jermaine-george/profil/spieler/626279.
Transfer history data appended for: https://www.transfermarkt.com/taariq-fielies/profil/spieler/243750.
Transfer history data appended for: https://www.transfermarkt.com/sanele-gaxa/profil/spieler/829256.
Transfer history data appended for: https://www.transfermarkt.com/aubrey-ngoma/profil/spieler/230924.
Transfer history data appended for: https://www.transfermarkt.com/marc-anderson/profil/spieler/711071.
Transfer history data appended for: https://www.transfermarkt.com/bradley-ralani/profil/spieler/146329.
Transfer history data appended for: https://www.transfermarkt.com/shaquille-abrahams/profil/spieler/447197.
Transfer history data appended for: https://www.transfermarkt.com/thato-mokeke/profil/spieler/160312.
Transfer history data appended for: https://www.transfermarkt.com/prince-opoku-agyemang/profil/spieler/734816.
Transfer history data appended for: https://www.transfermarkt.com/mpho-matsi/profil/spieler/231598.
Transfer history data appended for: https://www.transfermarkt.com/thamsanqa-mkhize/profil/spieler/138107.
Transfer history data appended for: https://www.transfermarkt.com/nana-akosah-bempah/profil/spieler/431338.
Transfer history data appended for: https://www.transfermarkt.com/duncan-adonis/profil/spieler/447198.
Transfer history data appended for: https://www.transfermarkt.com/abbubaker-mobara/profil/spieler/233964.
Transfer history data appended for: https://www.transfermarkt.com/thabo-nodada/profil/spieler/386340.
Transfer history data appended for: https://www.transfermarkt.com/mduduzi-mdantsane/profil/spieler/510067.
Transfer history data appended for: https://www.transfermarkt.com/fagrie-lakay/profil/spieler/246832.
Transfer history data appended for: https://www.transfermarkt.com/terrence-mashego/profil/spieler/538416.
Transfer history data appended for: https://www.transfermarkt.com/reid-bombay/profil/spieler/566481.
Transfer history data appended for: https://www.transfermarkt.com/zukile-kewuti/profil/spieler/555981.
Transfer history data appended for: https://www.transfermarkt.com/diego-appollis/profil/spieler/802119.
Transfer history data appended for: https://www.transfermarkt.com/tashreeq-morris/profil/spieler/282252.
Transfer history data appended for: https://www.transfermarkt.com/craig-martin/profil/spieler/524681.
Transfer history data appended for: https://www.transfermarkt.com/keanu-cupido/profil/spieler/390595.
Transfer history data appended for: https://www.transfermarkt.com/olwethu-nyembe/profil/spieler/726746.
Transfer history data appended for: https://www.transfermarkt.com/edmilson-dove/profil/spieler/426964.
Transfer history data appended for: https://www.transfermarkt.com/charles-zulu/profil/spieler/343274.
Transfer history data appended for: https://www.transfermarkt.com/zaakir-allie/profil/spieler/573834.
Transfer history data appended for: https://www.transfermarkt.com/giannis-potouridis/profil/spieler/129200.
Transfer history data appended for: https://www.transfermarkt.com/thabo-molefe/profil/spieler/291077.
Transfer history data appended for: https://www.transfermarkt.com/siyabonga-dube/profil/spieler/291073.
Transfer history data appended for: https://www.transfermarkt.com/lindokuhle-mtshali/profil/spieler/448657.
Transfer history data appended for: https://www.transfermarkt.com/kaleb-parusnath/profil/spieler/291080.
Transfer history data appended for: https://www.transfermarkt.com/bongani-kama/profil/spieler/437916.
Transfer history data appended for: https://www.transfermarkt.com/danny-phiri/profil/spieler/345705.
Transfer history data appended for: https://www.transfermarkt.com/richard-matloga/profil/spieler/370580.
Transfer history data appended for: https://www.transfermarkt.com/sanele-mathenjwa/profil/spieler/553297.
Transfer history data appended for: https://www.transfermarkt.com/siboniso-conco/profil/spieler/426388.
Transfer history data appended for: https://www.transfermarkt.com/gladwin-shitolo/profil/spieler/126635.
Transfer history data appended for: https://www.transfermarkt.com/michael-gumede/profil/spieler/342581.
Transfer history data appended for: https://www.transfermarkt.com/siyavuya-ndlovu/profil/spieler/556785.
Transfer history data appended for: https://www.transfermarkt.com/seth-parusnath/profil/spieler/291079.
Transfer history data appended for: https://www.transfermarkt.com/edmore-sibanda/profil/spieler/151318.
Transfer history data appended for: https://www.transfermarkt.com/maximilian-mbaeva/profil/spieler/65886.
Transfer history data appended for: https://www.transfermarkt.com/lungelo-dube/profil/spieler/291072.
Transfer history data appended for: https://www.transfermarkt.com/kyle-davies/profil/spieler/551702.
Transfer history data appended for: https://www.transfermarkt.com/nkosingiphile-gumede/profil/spieler/207617.
Transfer history data appended for: https://www.transfermarkt.com/boikanyo-komane/profil/spieler/419697.
Transfer history data appended for: https://www.transfermarkt.com/sifiso-mlungwana/profil/spieler/692803.
Transfer history data appended for: https://www.transfermarkt.com/nduduzo-sibiya/profil/spieler/291082.
Transfer history data appended for: https://www.transfermarkt.com/zolani-nkombelo/profil/spieler/420533.
Transfer history data appended for: https://www.transfermarkt.com/thabani-zuke/profil/spieler/478467.
Transfer history data appended for: https://www.transfermarkt.com/pule-mmodi/profil/spieler/613120.
Transfer history data appended for: https://www.transfermarkt.com/knox-mutizwa/profil/spieler/412123.
Transfer history data appended for: https://www.transfermarkt.com/mzwandile-buthelezi/profil/spieler/495499.
Transfer history data appended for: https://www.transfermarkt.com/trevor-mathiane/profil/spieler/258306.
Transfer history data appended for: https://www.transfermarkt.com/mthokozisi-dube/profil/spieler/330728.
Transfer history data appended for: https://www.transfermarkt.com/ntsako-makhubela/profil/spieler/478661.
Transfer history data appended for: https://www.transfermarkt.com/romario-dlamini/profil/spieler/417781.
Transfer history data appended for: https://www.transfermarkt.com/nkosinathi-sibisi/profil/spieler/399068.
Transfer history data appended for: https://www.transfermarkt.com/sello-motsepe/profil/spieler/370584.
Transfer history data appended for: https://www.transfermarkt.com/divine-lunga/profil/spieler/573039.
Transfer history data appended for: https://www.transfermarkt.com/thando-khwela/profil/spieler/692805.
Transfer history data appended for: https://www.transfermarkt.com/siphamandla-sabelo/profil/spieler/484842.
Transfer history data appended for: https://www.transfermarkt.com/nkosikhona-dube/profil/spieler/557325.
Transfer history data appended for: https://www.transfermarkt.com/velemseni-ndwandwe/profil/spieler/478466.
Transfer history data appended for: https://www.transfermarkt.com/sphamandla-nene/profil/spieler/840850.
Transfer history data appended for: https://www.transfermarkt.com/augustine-ramphele/profil/spieler/417715.

Transfer history data appended for: https://www.transfermarkt.com/thembela-sikhakhane/profil/spieler/260981.
Transfer history data appended for: https://www.transfermarkt.com/lehlohonolo-majoro/profil/spieler/160647.
Transfer history data appended for: https://www.transfermarkt.com/siyethemba-sithebe-mnguni-/profil/spieler/420546.
Transfer history data appended for: https://www.transfermarkt.com/bayanda-shangase/profil/spieler/647579.
Transfer history data appended for: https://www.transfermarkt.com/phakamani-mahlambi/profil/spieler/386510.
Transfer history data appended for: https://www.transfermarkt.com/singabakho-ngema/profil/spieler/693415.
Transfer history data appended for: https://www.transfermarkt.com/bongi-ntuli/profil/spieler/216352.
Transfer history data appended for: https://www.transfermarkt.com/sandile-khumalo/profil/spieler/691495.
Transfer history data appended for: https://www.transfermarkt.com/siphiwe-tshabalala/profil/spieler/37735.
Transfer history data appended for: https://www.transfermarkt.com/amigo-memela/profil/spieler/135078.
Transfer history data appended for: https://www.transfermarkt.com/talent-chawapiwa/profil/spieler/520837.
Transfer history data appended for: https://www.transfermarkt.com/somila-ntsundwana/profil/spieler/386030.
Transfer history data appended for: https://www.transfermarkt.com/veli-mothwa/profil/spieler/286562.
Transfer history data appended for: https://www.transfermarkt.com/makhehlene-makhaula/profil/spieler/333179.
Transfer history data appended for: https://www.transfermarkt.com/butholezwe-ncube/profil/spieler/457016.
Transfer history data appended for: https://www.transfermarkt.com/siyabonga-mbatha/profil/spieler/112741.
Transfer history data appended for: https://www.transfermarkt.com/siphelele-magubane/profil/spieler/414909.
Transfer history data appended for: https://www.transfermarkt.com/augustine-mulenga/profil/spieler/496326.
Transfer history data appended for: https://www.transfermarkt.com/sibongiseni-mthembu/profil/spieler/457015.
Transfer history data appended for: https://www.transfermarkt.com/mfanafikile-dlamini/profil/spieler/592559.
Transfer history data appended for: https://www.transfermarkt.com/xolani-mlambo/profil/spieler/330727.
Transfer history data appended for: https://www.transfermarkt.com/mhlengi-cele/profil/spieler/273783.
Transfer history data appended for: https://www.transfermarkt.com/sbusiso-magaqa/profil/spieler/457018.
Transfer history data appended for: https://www.transfermarkt.com/mario-booysen/profil/spieler/109957.
Transfer history data appended for: https://www.transfermarkt.com/andre-de-jong/profil/spieler/264903.
Transfer history data appended for: https://www.transfermarkt.com/sibusiso-mabiliso/profil/spieler/555600.
Transfer history data appended for: https://www.transfermarkt.com/neil-boshoff/profil/spieler/458885.
Transfer history data appended for: https://www.transfermarkt.com/samuel-darpoh/profil/spieler/457017.
Transfer history data appended for: https://www.transfermarkt.com/sicelo-mkhize/profil/spieler/478654.
Transfer history data appended for: https://www.transfermarkt.com/sphesihle-maduna/profil/spieler/565900.
Transfer history data appended for: https://www.transfermarkt.com/siphelele-mthembu/profil/spieler/108177.
Transfer history data appended for: https://www.transfermarkt.com/sbusiso-maluleke/profil/spieler/693393.
Transfer history data appended for: https://www.transfermarkt.com/jean-noel-amonome/profil/spieler/633888.
Transfer history data appended for: https://www.transfermarkt.com/siyanda-khumalo/profil/spieler/273811.
Transfer history data appended for: https://www.transfermarkt.com/tapelo-xoki-nyongo-/profil/spieler/329542.
Transfer history data appended for: https://www.transfermarkt.com/ntuthuko-madela/profil/spieler/672579.
Transfer history data appended for: https://www.transfermarkt.com/olwethu-mzimela/profil/spieler/801685.
Transfer history data appended for: https://www.transfermarkt.com/boiki-modikaseng/profil/spieler/597913.
Transfer history data appended for: https://www.transfermarkt.com/tyrese-de-bruin/profil/spieler/741409.
Transfer history data appended for: https://www.transfermarkt.com/charlie-hlalele/profil/spieler/594573.
Transfer history data appended for: https://www.transfermarkt.com/samkelo-mgwazela/profil/spieler/811935.
Transfer history data appended for: https://www.transfermarkt.com/limbikani-mzava/profil/spieler/161583.
Transfer history data appended for: https://www.transfermarkt.com/mbongeni-gumede/profil/spieler/234010.
Transfer history data appended for: https://www.transfermarkt.com/tommy-mandlazi/profil/spieler/233962.
Transfer history data appended for: https://www.transfermarkt.com/thabo-mnyamane/profil/spieler/286548.
Transfer history data appended for: https://www.transfermarkt.com/justin-shonga/profil/spieler/513874.
Transfer history data appended for: https://www.transfermarkt.com/lebogang-mabotja/profil/spieler/370612.
Transfer history data appended for: https://www.transfermarkt.com/tshepo-ramaele/profil/spieler/547842.
Transfer history data appended for: https://www.transfermarkt.com/tefo-mokoena/profil/spieler/547807.
Transfer history data appended for: https://www.transfermarkt.com/modibedi-mokoena/profil/spieler/547854.
Transfer history data appended for: https://www.transfermarkt.com/meshack-maphangule/profil/spieler/370613.
Transfer history data appended for: https://www.transfermarkt.com/thabo-rakhale/profil/spieler/231565.
Transfer history data appended for: https://www.transfermarkt.com/mogakolodi-ngele/profil/spieler/154213.
Transfer history data appended for: https://www.transfermarkt.com/brandon-theron/profil/spieler/320187.
Transfer history data appended for: https://www.transfermarkt.com/masibusane-zongo/profil/spieler/108608.
Transfer history data appended for: https://www.transfermarkt.com/tholang-masegela/profil/spieler/534437.
Transfer history data appended for: https://www.transfermarkt.com/brighton-mhlongo/profil/spieler/206537.
Transfer history data appended for: https://www.transfermarkt.com/alfred-ndengane/profil/spieler/242547.
Transfer history data appended for: https://www.transfermarkt.com/carlington-nyadombo/profil/spieler/158440.
Transfer history data appended for: https://www.transfermarkt.com/simon-mamudzidi/profil/spieler/567621.
Transfer history data appended for: https://www.transfermarkt.com/epnot-dzaga/profil/spieler/195640.
Transfer history data appended for: https://www.transfermarkt.com/gift-nemutandani/profil/spieler/636476.
Transfer history data appended for: https://www.transfermarkt.com/jabulani-ndebele/profil/spieler/370617.
Transfer history data appended for: https://www.transfermarkt.com/bogosi-morojele/profil/spieler/468682.
Transfer history data appended for: https://www.transfermarkt.com/jean-djunga-munganga/profil/spieler/233965.
Transfer history data appended for: https://www.transfermarkt.com/thembisani-nevhulamba/profil/spieler/437881.
Transfer history data appended for: https://www.transfermarkt.com/monde-mpambaniso/profil/spieler/495505.
Transfer history data appended for: https://www.transfermarkt.com/ndivhuwo-ravhuhali/profil/spieler/417572.
Transfer history data appended for: https://www.transfermarkt.com/lerato-lamola/profil/spieler/280607.
Transfer history data appended for: https://www.transfermarkt.com/siphenathi-laqwela/profil/spieler/420528.
Transfer history data appended for: https://www.transfermarkt.com/ndabayithethwa-ndlondlo/profil/spieler/636981.
Transfer history data appended for: https://www.transfermarkt.com/miguel-timm/profil/spieler/184884.
Transfer history data appended for: https://www.transfermarkt.com/diamond-thopola/profil/spieler/273850.
Transfer history data appended for: https://www.transfermarkt.com/nicholus-lukhubeni/profil/spieler/723094.
Transfer history data appended for: https://www.transfermarkt.com/lehlohonolo-nonyane/profil/spieler/196112.
Transfer history data appended for: https://www.transfermarkt.com/rhulani-manzini/profil/spieler/196128.
Transfer history data appended for: https://www.transfermarkt.com/edgar-manaka/profil/spieler/173964.
Transfer history data appended for: https://www.transfermarkt.com/ayanda-nkili/profil/spieler/258802.

Transfer history data appended for: https://www.transfermarkt.com/celimpilo-ngema/profil/spieler/547790.
Transfer history data appended for: https://www.transfermarkt.com/aluwani-nedzamba/profil/spieler/547840.
Transfer history data appended for: https://www.transfermarkt.com/washington-arubi/profil/spieler/80411.
Transfer history data appended for: https://www.transfermarkt.com/farai-madhanaga/profil/spieler/430067.
Transfer history data appended for: https://www.transfermarkt.com/ace-bhengu/profil/spieler/110284.
Transfer history data appended for: https://www.transfermarkt.com/gokhan-kardes/profil/spieler/256777.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-obertan/profil/spieler/43261.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-akdag/profil/spieler/182079.
Transfer history data appended for: https://www.transfermarkt.com/oltan-karakullukcu/profil/spieler/171261.
Transfer history data appended for: https://www.transfermarkt.com/jugurtha-hamroun/profil/spieler/81563.
Transfer history data appended for: https://www.transfermarkt.com/petrus-boumal/profil/spieler/127074.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-gomes/profil/spieler/258835.
Transfer history data appended for: https://www.transfermarkt.com/kayacan-erdogan/profil/spieler/58825.
Transfer history data appended for: https://www.transfermarkt.com/adolphe-teikeu/profil/spieler/105362.
Transfer history data appended for: https://www.transfermarkt.com/armando-sadiku/profil/spieler/140082.
Transfer history data appended for: https://www.transfermarkt.com/fabien-farnolle/profil/spieler/34937.
Transfer history data appended for: https://www.transfermarkt.com/murat-ucar/profil/spieler/292545.
Transfer history data appended for: https://www.transfermarkt.com/osman-celik/profil/spieler/293661.
Transfer history data appended for: https://www.transfermarkt.com/leo-schwechlen/profil/spieler/60594.
Transfer history data appended for: https://www.transfermarkt.com/rashad-muhammed/profil/spieler/351388.
Transfer history data appended for: https://www.transfermarkt.com/batuhan-unsal/profil/spieler/457522.
Transfer history data appended for: https://www.transfermarkt.com/mitchell-donald/profil/spieler/45511.
Transfer history data appended for: https://www.transfermarkt.com/arturo-mina/profil/spieler/263628.
Transfer history data appended for: https://www.transfermarkt.com/cenk-ahmet-alkilic/profil/spieler/68211.
Transfer history data appended for: https://www.transfermarkt.com/hasan-hatipoglu/profil/spieler/196900.
Transfer history data appended for: https://www.transfermarkt.com/emrah-bassan/profil/spieler/177031.
Transfer history data appended for: https://www.transfermarkt.com/mucahid-albayrak/profil/spieler/292496.
Transfer history data appended for: https://www.transfermarkt.com/arvydas-novikovas/profil/spieler/87444.
Transfer history data appended for: https://www.transfermarkt.com/kaan-kanak/profil/spieler/123527.
Transfer history data appended for: https://www.transfermarkt.com/adama-traore/profil/spieler/262608.
Transfer history data appended for: https://www.transfermarkt.com/rayane-aabid/profil/spieler/468244.
Transfer history data appended for: https://www.transfermarkt.com/ruben-ribeiro/profil/spieler/52480.
Transfer history data appended for: https://www.transfermarkt.com/mesut-caytemel/profil/spieler/53543.
Transfer history data appended for: https://www.transfermarkt.com/dame-diop/profil/spieler/209971.
Transfer history data appended for: https://www.transfermarkt.com/soner-ornek/profil/spieler/74643.
Transfer history data appended for: https://www.transfermarkt.com/mirkan-aydin/profil/spieler/46897.
Transfer history data appended for: https://www.transfermarkt.com/mame-diouf/profil/spieler/62049.
Transfer history data appended for: https://www.transfermarkt.com/david-akintola/profil/spieler/353775.
Transfer history data appended for: https://www.transfermarkt.com/yusuf-abdioglu/profil/spieler/199938.
Transfer history data appended for: https://www.transfermarkt.com/akin-alkan/profil/spieler/252056.
Transfer history data appended for: https://www.transfermarkt.com/abdurrahman-canli/profil/spieler/319679.
Transfer history data appended for: https://www.transfermarkt.com/burak-camoglu/profil/spieler/197402.
Transfer history data appended for: https://www.transfermarkt.com/helder-barbosa/profil/spieler/39784.
Transfer history data appended for: https://www.transfermarkt.com/alexandros-katranis/profil/spieler/324341.
Transfer history data appended for: https://www.transfermarkt.com/munir/profil/spieler/97925.
Transfer history data appended for: https://www.transfermarkt.com/isaac-sackey/profil/spieler/259943.
Transfer history data appended for: https://www.transfermarkt.com/idir-ouali/profil/spieler/46716.
Transfer history data appended for: https://www.transfermarkt.com/yavuz-bugra-boyar/profil/spieler/616489.
Transfer history data appended for: https://www.transfermarkt.com/joseph-akomadi/profil/spieler/619468.
Transfer history data appended for: https://www.transfermarkt.com/selim-ilgaz/profil/spieler/205551.
Transfer history data appended for: https://www.transfermarkt.com/strahil-popov/profil/spieler/87299.
Transfer history data appended for: https://www.transfermarkt.com/aaron-boupendza/profil/spieler/427605.
Transfer history data appended for: https://www.transfermarkt.com/silviu-lung-jr-/profil/spieler/73731.
Transfer history data appended for: https://www.transfermarkt.com/cristian-sapunaru/profil/spieler/25942.
Transfer history data appended for: https://www.transfermarkt.com/emre-demir/profil/spieler/637669.
Transfer history data appended for: https://www.transfermarkt.com/wilfried-kanga/profil/spieler/395523.
Transfer history data appended for: https://www.transfermarkt.com/daniel-avramovski/profil/spieler/193289.
Transfer history data appended for: https://www.transfermarkt.com/oguzhan-capar/profil/spieler/351718.
Transfer history data appended for: https://www.transfermarkt.com/hasan-huseyin-acar/profil/spieler/285634.
Transfer history data appended for: https://www.transfermarkt.com/aaron-lennon/profil/spieler/14221.
Transfer history data appended for: https://www.transfermarkt.com/omer-uzun/profil/spieler/451880.
Transfer history data appended for: https://www.transfermarkt.com/abdulkadir-tasdan/profil/spieler/812658.
Transfer history data appended for: https://www.transfermarkt.com/adem-dogan/profil/spieler/576035.
Transfer history data appended for: https://www.transfermarkt.com/harrison-manzala/profil/spieler/268555.
Transfer history data appended for: https://www.transfermarkt.com/mugdat-celik/profil/spieler/67570.
Transfer history data appended for: https://www.transfermarkt.com/aziz-behich/profil/spieler/136834.
Transfer history data appended for: https://www.transfermarkt.com/nurettin-korkmaz/profil/spieler/654374.
Transfer history data appended for: https://www.transfermarkt.com/zoran-kvrzic/profil/spieler/159839.
Transfer history data appended for: https://www.transfermarkt.com/denis-alibec/profil/spieler/81396.
Transfer history data appended for: https://www.transfermarkt.com/yaw-ackah/profil/spieler/672933.
Transfer history data appended for: https://www.transfermarkt.com/miguel-lopes/profil/spieler/59248.
Transfer history data appended for: https://www.transfermarkt.com/gustavo-campanharo/profil/spieler/103674.
Transfer history data appended for: https://www.transfermarkt.com/ilhan-depe/profil/spieler/166725.
Transfer history data appended for: https://www.transfermarkt.com/ilhan-parlak/profil/spieler/37091.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-kolovetsios/profil/spieler/112648.
Transfer history data appended for: https://www.transfermarkt.com/joseph-attamah/profil/spieler/263546.
Transfer history data appended for: https://www.transfermarkt.com/dogan-alemdar/profil/spieler/576033.
Transfer history data appended for: https://www.transfermarkt.com/yasir-subasi/profil/spieler/375719.
Transfer history data appended for: https://www.transfermarkt.com/douglas/profil/spieler/58426.
Transfer history data appended for: https://www.transfermarkt.com/fabrice-nsakala/profil/spieler/86930.

Transfer history data appended for: https://www.transfermarkt.com/dorukhan-tokoz/profil/spieler/275935.
Transfer history data appended for: https://www.transfermarkt.com/domagoj-vida/profil/spieler/46083.
Transfer history data appended for: https://www.transfermarkt.com/erdogan-kaya/profil/spieler/558720.
Transfer history data appended for: https://www.transfermarkt.com/vincent-aboubakar/profil/spieler/147487.
Transfer history data appended for: https://www.transfermarkt.com/georges-kevin-nkoudou/profil/spieler/215679.
Transfer history data appended for: https://www.transfermarkt.com/atakan-uner/profil/spieler/370834.
Transfer history data appended for: https://www.transfermarkt.com/oguzhan-ozyakup/profil/spieler/77966.
Transfer history data appended for: https://www.transfermarkt.com/muhayer-oktay/profil/spieler/330236.
Transfer history data appended for: https://www.transfermarkt.com/utku-yuvakuran/profil/spieler/342995.
Transfer history data appended for: https://www.transfermarkt.com/francisco-montero/profil/spieler/396333.
Transfer history data appended for: https://www.transfermarkt.com/tyler-boyd/profil/spieler/203330.
Transfer history data appended for: https://www.transfermarkt.com/guven-yalcin/profil/spieler/341019.
Transfer history data appended for: https://www.transfermarkt.com/atiba-hutchinson/profil/spieler/16101.
Transfer history data appended for: https://www.transfermarkt.com/jeremain-lens/profil/spieler/38497.
Transfer history data appended for: https://www.transfermarkt.com/cyle-larin/profil/spieler/343463.
Transfer history data appended for: https://www.transfermarkt.com/necip-uysal/profil/spieler/77710.
Transfer history data appended for: https://www.transfermarkt.com/kartal-yilmaz/profil/spieler/461951.
Transfer history data appended for: https://www.transfermarkt.com/adem-ljajic/profil/spieler/69374.
Transfer history data appended for: https://www.transfermarkt.com/ersin-destanoglu/profil/spieler/500091.
Transfer history data appended for: https://www.transfermarkt.com/josef/profil/spieler/73741.
Transfer history data appended for: https://www.transfermarkt.com/rachid-ghezzal/profil/spieler/118287.
Transfer history data appended for: https://www.transfermarkt.com/emre-bilgin/profil/spieler/727147.
Transfer history data appended for: https://www.transfermarkt.com/ajdin-hasic/profil/spieler/522851.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-isimat-mirin/profil/spieler/147846.
Transfer history data appended for: https://www.transfermarkt.com/ridvan-yilmaz/profil/spieler/477930.
Transfer history data appended for: https://www.transfermarkt.com/ertugrul-taskiran/profil/spieler/91945.
Transfer history data appended for: https://www.transfermarkt.com/gilbert-koomson/profil/spieler/282473.
Transfer history data appended for: https://www.transfermarkt.com/erdem-canpolat/profil/spieler/521956.
Transfer history data appended for: https://www.transfermarkt.com/alan/profil/spieler/515639.
Transfer history data appended for: https://www.transfermarkt.com/cagtay-kurukalip/profil/spieler/616886.
Transfer history data appended for: https://www.transfermarkt.com/tarkan-serbest/profil/spieler/158118.
Transfer history data appended for: https://www.transfermarkt.com/dogucan-haspolat/profil/spieler/387143.
Transfer history data appended for: https://www.transfermarkt.com/ahmet-oguz/profil/spieler/291758.
Transfer history data appended for: https://www.transfermarkt.com/florent-hadergjonaj/profil/spieler/238809.
Transfer history data appended for: https://www.transfermarkt.com/eren-elmali/profil/spieler/616894.
Transfer history data appended for: https://www.transfermarkt.com/armin-hodzic/profil/spieler/166753.
Transfer history data appended for: https://www.transfermarkt.com/azad-toptik/profil/spieler/332061.
Transfer history data appended for: https://www.transfermarkt.com/yasin-dulger/profil/spieler/296919.
Transfer history data appended for: https://www.transfermarkt.com/tomas-brecka/profil/spieler/265879.
Transfer history data appended for: https://www.transfermarkt.com/oussama-haddadi/profil/spieler/191407.
Transfer history data appended for: https://www.transfermarkt.com/aytac-kara/profil/spieler/159908.
Transfer history data appended for: https://www.transfermarkt.com/loret-sadiku/profil/spieler/116611.
Transfer history data appended for: https://www.transfermarkt.com/kevin-varga/profil/spieler/385906.
Transfer history data appended for: https://www.transfermarkt.com/yusuf-erdogan/profil/spieler/191391.
Transfer history data appended for: https://www.transfermarkt.com/ramazan-kose/profil/spieler/73627.
Transfer history data appended for: https://www.transfermarkt.com/feyzi-yildirim/profil/spieler/338422.
Transfer history data appended for: https://www.transfermarkt.com/anil-koc/profil/spieler/168161.
Transfer history data appended for: https://www.transfermarkt.com/enes-sari/profil/spieler/602899.
Transfer history data appended for: https://www.transfermarkt.com/bengali-fode-koita/profil/spieler/79110.
Transfer history data appended for: https://www.transfermarkt.com/julian-jeanvier/profil/spieler/134277.
Transfer history data appended for: https://www.transfermarkt.com/haris-hajradinovic/profil/spieler/215592.
Transfer history data appended for: https://www.transfermarkt.com/mickael-tirpan/profil/spieler/201248.
Transfer history data appended for: https://www.transfermarkt.com/gerard-gohou/profil/spieler/141796.
Transfer history data appended for: https://www.transfermarkt.com/guido-herrera/profil/spieler/230014.
Transfer history data appended for: https://www.transfermarkt.com/christian-cueva/profil/spieler/95280.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-eskihellac/profil/spieler/390379.
Transfer history data appended for: https://www.transfermarkt.com/issam-chebake/profil/spieler/332049.
Transfer history data appended for: https://www.transfermarkt.com/eray-iscan/profil/spieler/88371.
Transfer history data appended for: https://www.transfermarkt.com/bulent-cevahir/profil/spieler/147518.
Transfer history data appended for: https://www.transfermarkt.com/kubilay-kanatsizkus/profil/spieler/330876.
Transfer history data appended for: https://www.transfermarkt.com/semih-kaya/profil/spieler/60709.
Transfer history data appended for: https://www.transfermarkt.com/dogukan-emeksiz/profil/spieler/540067.
Transfer history data appended for: https://www.transfermarkt.com/ertac-ozbir/profil/spieler/159079.
Transfer history data appended for: https://www.transfermarkt.com/teenage-hadebe/profil/spieler/429975.
Transfer history data appended for: https://www.transfermarkt.com/abdulsamed-damlu/profil/spieler/341649.
Transfer history data appended for: https://www.transfermarkt.com/berk-yildiz/profil/spieler/212325.
Transfer history data appended for: https://www.transfermarkt.com/youssouf-ndayishimiye/profil/spieler/674612.
Transfer history data appended for: https://www.transfermarkt.com/wallace/profil/spieler/225335.
Transfer history data appended for: https://www.transfermarkt.com/olcay-sahan/profil/spieler/36200.
Transfer history data appended for: https://www.transfermarkt.com/jetmir-topalli/profil/spieler/600222.
Transfer history data appended for: https://www.transfermarkt.com/adem-buyuk/profil/spieler/54148.
Transfer history data appended for: https://www.transfermarkt.com/murat-akca/profil/spieler/66953.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-ildiz/profil/spieler/226169.
Transfer history data appended for: https://www.transfermarkt.com/moryke-fofana/profil/spieler/240497.
Transfer history data appended for: https://www.transfermarkt.com/fernando-zuqui/profil/spieler/248763.
Transfer history data appended for: https://www.transfermarkt.com/karim-hafez/profil/spieler/333004.
Transfer history data appended for: https://www.transfermarkt.com/murat-aksit/profil/spieler/621391.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-akbas/profil/spieler/98113.
Transfer history data appended for: https://www.transfermarkt.com/zeki-yavru/profil/spieler/98131.
Transfer history data appended for: https://www.transfermarkt.com/jody-lukoki/profil/spieler/165975.

Transfer history data appended for: https://www.transfermarkt.com/egemen-pehlivan/profil/spieler/697067.
Transfer history data appended for: https://www.transfermarkt.com/alassane-ndao/profil/spieler/569777.
Transfer history data appended for: https://www.transfermarkt.com/lucas-biglia/profil/spieler/26721.
Transfer history data appended for: https://www.transfermarkt.com/artur-sobiech/profil/spieler/75640.
Transfer history data appended for: https://www.transfermarkt.com/ramazan-civelek/profil/spieler/282560.
Transfer history data appended for: https://www.transfermarkt.com/zeki-yildirim/profil/spieler/141737.
Transfer history data appended for: https://www.transfermarkt.com/aatif-chahechouhe/profil/spieler/73480.
Transfer history data appended for: https://www.transfermarkt.com/yavuz-ulas-genc/profil/spieler/667915.
Transfer history data appended for: https://www.transfermarkt.com/fatih-kurucuk/profil/spieler/337516.
Transfer history data appended for: https://www.transfermarkt.com/jure-balkovec/profil/spieler/181410.
Transfer history data appended for: https://www.transfermarkt.com/furkan-kara/profil/spieler/708775.
Transfer history data appended for: https://www.transfermarkt.com/yannis-salibur/profil/spieler/79893.
Transfer history data appended for: https://www.transfermarkt.com/efe-tatli/profil/spieler/696876.
Transfer history data appended for: https://www.transfermarkt.com/murat-sarigul/profil/spieler/641264.
Transfer history data appended for: https://www.transfermarkt.com/cristobal-jorquera/profil/spieler/66280.
Transfer history data appended for: https://www.transfermarkt.com/vato-arveladze/profil/spieler/345195.
Transfer history data appended for: https://www.transfermarkt.com/ervin-zukanovic/profil/spieler/44059.
Transfer history data appended for: https://www.transfermarkt.com/mevlut-erdinc/profil/spieler/38360.
Transfer history data appended for: https://www.transfermarkt.com/eric-lichaj/profil/spieler/61575.
Transfer history data appended for: https://www.transfermarkt.com/muzaffer-kablan/profil/spieler/321714.
Transfer history data appended for: https://www.transfermarkt.com/aksel-aktas/profil/spieler/371147.
Transfer history data appended for: https://www.transfermarkt.com/erik-sabo/profil/spieler/155597.
Transfer history data appended for: https://www.transfermarkt.com/koray-altinay/profil/spieler/148550.
Transfer history data appended for: https://www.transfermarkt.com/aykut-ozer/profil/spieler/117518.
Transfer history data appended for: https://www.transfermarkt.com/alparslan-erdem/profil/spieler/42050.
Transfer history data appended for: https://www.transfermarkt.com/martin-skrtel/profil/spieler/24180.
Transfer history data appended for: https://www.transfermarkt.com/muhammed-sarikaya/profil/spieler/572132.
Transfer history data appended for: https://www.transfermarkt.com/volkan-babacan/profil/spieler/52261.
Transfer history data appended for: https://www.transfermarkt.com/ravil-tagir/profil/spieler/655893.
Transfer history data appended for: https://www.transfermarkt.com/ugur-ucar/profil/spieler/21370.
Transfer history data appended for: https://www.transfermarkt.com/mehmet-topal/profil/spieler/44402.
Transfer history data appended for: https://www.transfermarkt.com/fredrik-gulbrandsen/profil/spieler/110708.
Transfer history data appended for: https://www.transfermarkt.com/enes-karakus/profil/spieler/622067.
Transfer history data appended for: https://www.transfermarkt.com/cemali-sertel/profil/spieler/573981.
Transfer history data appended for: https://www.transfermarkt.com/irfan-can-kahveci/profil/spieler/216603.
Transfer history data appended for: https://www.transfermarkt.com/deniz-turuc/profil/spieler/216662.
Transfer history data appended for: https://www.transfermarkt.com/enzo-crivelli/profil/spieler/291110.
Transfer history data appended for: https://www.transfermarkt.com/emre-kaplan/profil/spieler/645932.
Transfer history data appended for: https://www.transfermarkt.com/mert-gunok/profil/spieler/51894.
Transfer history data appended for: https://www.transfermarkt.com/rafael/profil/spieler/61892.
Transfer history data appended for: https://www.transfermarkt.com/edin-visca/profil/spieler/109217.
Transfer history data appended for: https://www.transfermarkt.com/ahmet-kivanc/profil/spieler/340880.
Transfer history data appended for: https://www.transfermarkt.com/nacer-chadli/profil/spieler/59631.
Transfer history data appended for: https://www.transfermarkt.com/hasan-ali-kaldirim/profil/spieler/55605.
Transfer history data appended for: https://www.transfermarkt.com/mete-kaan-demir/profil/spieler/282615.
Transfer history data appended for: https://www.transfermarkt.com/danijel-aleksic/profil/spieler/48119.
Transfer history data appended for: https://www.transfermarkt.com/boli-bolingoli/profil/spieler/168156.
Transfer history data appended for: https://www.transfermarkt.com/mahmut-tekdemir/profil/spieler/54177.
Transfer history data appended for: https://www.transfermarkt.com/junior-caicara/profil/spieler/112062.
Transfer history data appended for: https://www.transfermarkt.com/ponck/profil/spieler/341516.
Transfer history data appended for: https://www.transfermarkt.com/kerim-frei/profil/spieler/146844.
Transfer history data appended for: https://www.transfermarkt.com/demba-ba/profil/spieler/40205.
Transfer history data appended for: https://www.transfermarkt.com/berkay-ozcan/profil/spieler/249952.
Transfer history data appended for: https://www.transfermarkt.com/okechukwu-azubuike/profil/spieler/386126.
Transfer history data appended for: https://www.transfermarkt.com/muhammed-sengezer/profil/spieler/330871.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-epureanu/profil/spieler/45340.
Transfer history data appended for: https://www.transfermarkt.com/brown-ideye/profil/spieler/64308.
Transfer history data appended for: https://www.transfermarkt.com/stefano-napoleoni/profil/spieler/43518.
Transfer history data appended for: https://www.transfermarkt.com/balazs-megyeri/profil/spieler/98428.
Transfer history data appended for: https://www.transfermarkt.com/burak-suleyman/profil/spieler/246241.
Transfer history data appended for: https://www.transfermarkt.com/marcio-mossoro/profil/spieler/45596.
Transfer history data appended for: https://www.transfermarkt.com/batuhan-kirdaroglu/profil/spieler/620188.
Transfer history data appended for: https://www.transfermarkt.com/berkan-emir/profil/spieler/241902.
Transfer history data appended for: https://www.transfermarkt.com/zlatko-tripic/profil/spieler/195274.
Transfer history data appended for: https://www.transfermarkt.com/kubilay-sonmez/profil/spieler/160512.
Transfer history data appended for: https://www.transfermarkt.com/obinna-nwobodo/profil/spieler/364299.
Transfer history data appended for: https://www.transfermarkt.com/irfan-can-egribayat/profil/spieler/322873.
Transfer history data appended for: https://www.transfermarkt.com/titi/profil/spieler/55250.
Transfer history data appended for: https://www.transfermarkt.com/marko-mihojevic/profil/spieler/235646.
Transfer history data appended for: https://www.transfermarkt.com/dzenan-burekovic/profil/spieler/227639.
Transfer history data appended for: https://www.transfermarkt.com/lamine-gassama/profil/spieler/60539.
Transfer history data appended for: https://www.transfermarkt.com/efe-binici/profil/spieler/667563.
Transfer history data appended for: https://www.transfermarkt.com/alpaslan-ozturk/profil/spieler/138736.
Transfer history data appended for: https://www.transfermarkt.com/soner-aydogdu/profil/spieler/85291.
Transfer history data appended for: https://www.transfermarkt.com/metin-yildirim/profil/spieler/660139.
Transfer history data appended for: https://www.transfermarkt.com/yalcin-kayan/profil/spieler/605266.
Transfer history data appended for: https://www.transfermarkt.com/murat-paluli/profil/spieler/288858.
Transfer history data appended for: https://www.transfermarkt.com/arda-ozcimen/profil/spieler/615430.
Transfer history data appended for: https://www.transfermarkt.com/halil-akbunar/profil/spieler/212229.
Transfer history data appended for: https://www.transfermarkt.com/oguz-yilmaz/profil/spieler/199958.

Transfer history data appended for: https://www.transfermarkt.com/recep-niyaz/profil/spieler/105653.
Transfer history data appended for: https://www.transfermarkt.com/zakarya-bergdich/profil/spieler/149540.
Transfer history data appended for: https://www.transfermarkt.com/ozer-ozdemir/profil/spieler/289898.
Transfer history data appended for: https://www.transfermarkt.com/sakib-aytac/profil/spieler/114491.
Transfer history data appended for: https://www.transfermarkt.com/abdulkadir-sunger/profil/spieler/796259.
Transfer history data appended for: https://www.transfermarkt.com/muhammet-ozkal/profil/spieler/339432.
Transfer history data appended for: https://www.transfermarkt.com/fabiano/profil/spieler/271335.
Transfer history data appended for: https://www.transfermarkt.com/eren-kiryolcu/profil/spieler/811332.
Transfer history data appended for: https://www.transfermarkt.com/radoslaw-murawski/profil/spieler/220969.
Transfer history data appended for: https://www.transfermarkt.com/fede-varela/profil/spieler/309980.
Transfer history data appended for: https://www.transfermarkt.com/muris-mesanovic/profil/spieler/70176.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-yumlu/profil/spieler/76176.
Transfer history data appended for: https://www.transfermarkt.com/mathieu-dossevi/profil/spieler/77828.
Transfer history data appended for: https://www.transfermarkt.com/hugo-rodallega/profil/spieler/37934.
Transfer history data appended for: https://www.transfermarkt.com/ismail-aissati/profil/spieler/30710.
Transfer history data appended for: https://www.transfermarkt.com/angelo-sagal/profil/spieler/190941.
Transfer history data appended for: https://www.transfermarkt.com/huseyin-altintas/profil/spieler/293956.
Transfer history data appended for: https://www.transfermarkt.com/ozgur-cek/profil/spieler/52262.
Transfer history data appended for: https://www.transfermarkt.com/cenk-gonen/profil/spieler/45214.
Transfer history data appended for: https://www.transfermarkt.com/alihan-kalkan/profil/spieler/677186.
Transfer history data appended for: https://www.transfermarkt.com/tiago-lopes/profil/spieler/171069.
Transfer history data appended for: https://www.transfermarkt.com/fernando-muslera/profil/spieler/58088.
Transfer history data appended for: https://www.transfermarkt.com/younes-belhanda/profil/spieler/118022.
Transfer history data appended for: https://www.transfermarkt.com/ryan-donk/profil/spieler/38414.
Transfer history data appended for: https://www.transfermarkt.com/emin-bayram/profil/spieler/655902.
Transfer history data appended for: https://www.transfermarkt.com/falcao/profil/spieler/39152.
Transfer history data appended for: https://www.transfermarkt.com/fatih-ozturk/profil/spieler/209574.
Transfer history data appended for: https://www.transfermarkt.com/sofiane-feghouli/profil/spieler/57162.
Transfer history data appended for: https://www.transfermarkt.com/taylan-antalyali/profil/spieler/204176.
Transfer history data appended for: https://www.transfermarkt.com/christian-luyindama/profil/spieler/262793.
Transfer history data appended for: https://www.transfermarkt.com/marcao/profil/spieler/439022.
Transfer history data appended for: https://www.transfermarkt.com/martin-linnes/profil/spieler/137582.
Transfer history data appended for: https://www.transfermarkt.com/kerem-yusuf-ersunar/profil/spieler/655896.
Transfer history data appended for: https://www.transfermarkt.com/ryan-babel/profil/spieler/16135.
Transfer history data appended for: https://www.transfermarkt.com/ogulcan-caglayan/profil/spieler/248219.
Transfer history data appended for: https://www.transfermarkt.com/emre-akbaba/profil/spieler/278654.
Transfer history data appended for: https://www.transfermarkt.com/emre-kilinc/profil/spieler/208848.
Transfer history data appended for: https://www.transfermarkt.com/omer-bayram/profil/spieler/117586.
Transfer history data appended for: https://www.transfermarkt.com/omar-elabdellaoui/profil/spieler/121404.
Transfer history data appended for: https://www.transfermarkt.com/jesse-sekidika/profil/spieler/437392.
Transfer history data appended for: https://www.transfermarkt.com/ali-yavuz-kol/profil/spieler/477938.
Transfer history data appended for: https://www.transfermarkt.com/okan-kocuk/profil/spieler/204189.
Transfer history data appended for: https://www.transfermarkt.com/kerem-akturkoglu/profil/spieler/382528.
Transfer history data appended for: https://www.transfermarkt.com/sener-ozbayrakli/profil/spieler/169873.
Transfer history data appended for: https://www.transfermarkt.com/sinan-gumus/profil/spieler/196524.
Transfer history data appended for: https://www.transfermarkt.com/filip-novak/profil/spieler/107665.
Transfer history data appended for: https://www.transfermarkt.com/ferdi-kadioglu/profil/spieler/369316.
Transfer history data appended for: https://www.transfermarkt.com/enner-valencia/profil/spieler/139503.
Transfer history data appended for: https://www.transfermarkt.com/mame-thiam/profil/spieler/163053.
Transfer history data appended for: https://www.transfermarkt.com/jose-sosa/profil/spieler/20137.
Transfer history data appended for: https://www.transfermarkt.com/mbwana-samatta/profil/spieler/182201.
Transfer history data appended for: https://www.transfermarkt.com/oytun-ozdogan/profil/spieler/353860.
Transfer history data appended for: https://www.transfermarkt.com/nazim-sangare/profil/spieler/157113.
Transfer history data appended for: https://www.transfermarkt.com/sadik-ciftpinar/profil/spieler/176354.
Transfer history data appended for: https://www.transfermarkt.com/marcel-tisserand/profil/spieler/170463.
Transfer history data appended for: https://www.transfermarkt.com/kemal-ademi/profil/spieler/333161.
Transfer history data appended for: https://www.transfermarkt.com/omer-beyaz/profil/spieler/588020.
Transfer history data appended for: https://www.transfermarkt.com/mauricio-lemos/profil/spieler/303140.
Transfer history data appended for: https://www.transfermarkt.com/ozan-tufan/profil/spieler/236471.
Transfer history data appended for: https://www.transfermarkt.com/altay-bayindir/profil/spieler/336077.
Transfer history data appended for: https://www.transfermarkt.com/nabil-dirar/profil/spieler/42267.
Transfer history data appended for: https://www.transfermarkt.com/mert-hakan-yandas/profil/spieler/306462.
Transfer history data appended for: https://www.transfermarkt.com/diego-perotti/profil/spieler/54984.
Transfer history data appended for: https://www.transfermarkt.com/luiz-gustavo/profil/spieler/10471.
Transfer history data appended for: https://www.transfermarkt.com/serdar-aziz/profil/spieler/44996.
Transfer history data appended for: https://www.transfermarkt.com/papiss-demba-cisse/profil/spieler/33952.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-pelkas/profil/spieler/212832.
Transfer history data appended for: https://www.transfermarkt.com/gokhan-gonul/profil/spieler/33793.
Transfer history data appended for: https://www.transfermarkt.com/manolis-siopis/profil/spieler/182688.
Transfer history data appended for: https://www.transfermarkt.com/anastasios-bakasetas/profil/spieler/162571.
Transfer history data appended for: https://www.transfermarkt.com/georgios-tzavellas/profil/spieler/42942.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-pektemek/profil/spieler/58602.
Transfer history data appended for: https://www.transfermarkt.com/alpay-celebi/profil/spieler/388188.
Transfer history data appended for: https://www.transfermarkt.com/umut-gunes/profil/spieler/422203.
Transfer history data appended for: https://www.transfermarkt.com/marafona/profil/spieler/56005.
Transfer history data appended for: https://www.transfermarkt.com/francois-moubandje/profil/spieler/123021.
Transfer history data appended for: https://www.transfermarkt.com/adam-bareiro/profil/spieler/514120.
Transfer history data appended for: https://www.transfermarkt.com/ufuk-ceylan/profil/spieler/29631.
Transfer history data appended for: https://www.transfermarkt.com/salih-ucan/profil/spieler/170838.
Transfer history data appended for: https://www.transfermarkt.com/steven-caulker/profil/spieler/121280.

Transfer history data appended for: https://www.transfermarkt.com/ahmet-cagri-guney/profil/spieler/655903.
Transfer history data appended for: https://www.transfermarkt.com/hasan-ayaroglu/profil/spieler/222608.
Transfer history data appended for: https://www.transfermarkt.com/efkan-bekiroglu/profil/spieler/327402.
Transfer history data appended for: https://www.transfermarkt.com/davidson/profil/spieler/397090.
Transfer history data appended for: https://www.transfermarkt.com/tayfur-bingol/profil/spieler/184440.
Transfer history data appended for: https://www.transfermarkt.com/ahmet-gulay/profil/spieler/655898.
Transfer history data appended for: https://www.transfermarkt.com/berkan-kutlu/profil/spieler/469787.
Transfer history data appended for: https://www.transfermarkt.com/efecan-karaca/profil/spieler/50655.
Transfer history data appended for: https://www.transfermarkt.com/fatih-aksoy/profil/spieler/338794.
Transfer history data appended for: https://www.transfermarkt.com/atakan-gunduz/profil/spieler/477927.
Transfer history data appended for: https://www.transfermarkt.com/serkan-asan/profil/spieler/491966.
Transfer history data appended for: https://www.transfermarkt.com/majid-hosseini/profil/spieler/294767.
Transfer history data appended for: https://www.transfermarkt.com/fousseni-diabate/profil/spieler/364861.
Transfer history data appended for: https://www.transfermarkt.com/vitor-hugo/profil/spieler/149752.
Transfer history data appended for: https://www.transfermarkt.com/edgar-ie/profil/spieler/191987.
Transfer history data appended for: https://www.transfermarkt.com/muhammet-taha-tepe/profil/spieler/477924.
Transfer history data appended for: https://www.transfermarkt.com/abdulkadir-omur/profil/spieler/271495.
Transfer history data appended for: https://www.transfermarkt.com/abdulkadir-parmak/profil/spieler/276337.
Transfer history data appended for: https://www.transfermarkt.com/flavio/profil/spieler/373191.
Transfer history data appended for: https://www.transfermarkt.com/arda-akbulut/profil/spieler/347383.
Transfer history data appended for: https://www.transfermarkt.com/lewis-baker/profil/spieler/198589.
Transfer history data appended for: https://www.transfermarkt.com/yusuf-sari/profil/spieler/517376.
Transfer history data appended for: https://www.transfermarkt.com/salih-kavrazli/profil/spieler/633434.
Transfer history data appended for: https://www.transfermarkt.com/bilal-basacikoglu/profil/spieler/224256.
Transfer history data appended for: https://www.transfermarkt.com/anthony-nwakaeme/profil/spieler/175988.
Transfer history data appended for: https://www.transfermarkt.com/anders-trondsen/profil/spieler/228042.
Transfer history data appended for: https://www.transfermarkt.com/ahmet-canbaz/profil/spieler/288313.
Transfer history data appended for: https://www.transfermarkt.com/joao-pereira/profil/spieler/13217.
Transfer history data appended for: https://www.transfermarkt.com/ugurcan-cakir/profil/spieler/292199.
Transfer history data appended for: https://www.transfermarkt.com/gaston-campi/profil/spieler/292174.
Transfer history data appended for: https://www.transfermarkt.com/erce-kardesler/profil/spieler/291548.
Transfer history data appended for: https://www.transfermarkt.com/djaniny/profil/spieler/197170.
Transfer history data appended for: https://www.transfermarkt.com/kamil-ahmet-corekci/profil/spieler/110686.
Transfer history data appended for: https://www.transfermarkt.com/safa-kinali/profil/spieler/592360.
Transfer history data appended for: https://www.transfermarkt.com/huseyin-turkmen/profil/spieler/395862.
Transfer history data appended for: https://www.transfermarkt.com/bogachan-kazmaz/profil/spieler/665404.
Transfer history data appended for: https://www.transfermarkt.com/zafer-gorgen/profil/spieler/576566.
Transfer history data appended for: https://www.transfermarkt.com/mithat-pala/profil/spieler/703720.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-durak/profil/spieler/82713.
Transfer history data appended for: https://www.transfermarkt.com/dogan-erdogan/profil/spieler/239733.
Transfer history data appended for: https://www.transfermarkt.com/fernando-boldrin/profil/spieler/144752.
Transfer history data appended for: https://www.transfermarkt.com/ismail-koybasi/profil/spieler/74641.
Transfer history data appended for: https://www.transfermarkt.com/braian-samudio/profil/spieler/520405.
Transfer history data appended for: https://www.transfermarkt.com/murat-saglam/profil/spieler/339051.
Transfer history data appended for: https://www.transfermarkt.com/dimitrios-chatziisaias/profil/spieler/284856.
Transfer history data appended for: https://www.transfermarkt.com/konrad-michalak/profil/spieler/387160.
Transfer history data appended for: https://www.transfermarkt.com/selim-ay/profil/spieler/157175.
Transfer history data appended for: https://www.transfermarkt.com/dario-melnjak/profil/spieler/238500.
Transfer history data appended for: https://www.transfermarkt.com/ismael-diomande/profil/spieler/170495.
Transfer history data appended for: https://www.transfermarkt.com/emir-dilaver/profil/spieler/80161.
Transfer history data appended for: https://www.transfermarkt.com/montassar-talbi/profil/spieler/496706.
Transfer history data appended for: https://www.transfermarkt.com/kemal-ruzgar/profil/spieler/196655.
Transfer history data appended for: https://www.transfermarkt.com/loic-remy/profil/spieler/45121.
Transfer history data appended for: https://www.transfermarkt.com/godfred-donsah/profil/spieler/291266.
Transfer history data appended for: https://www.transfermarkt.com/mykola-morozyuk/profil/spieler/59389.
Transfer history data appended for: https://www.transfermarkt.com/dusan-jovancic/profil/spieler/231354.
Transfer history data appended for: https://www.transfermarkt.com/fabricio-baiano/profil/spieler/282513.
Transfer history data appended for: https://www.transfermarkt.com/milan-skoda/profil/spieler/63047.
Transfer history data appended for: https://www.transfermarkt.com/tunay-torun/profil/spieler/39247.
Transfer history data appended for: https://www.transfermarkt.com/alberk-koc/profil/spieler/374882.
Transfer history data appended for: https://www.transfermarkt.com/onur-bulut/profil/spieler/152733.
Transfer history data appended for: https://www.transfermarkt.com/gokhan-akkan/profil/spieler/223025.
Transfer history data appended for: https://www.transfermarkt.com/yassine-meriah/profil/spieler/306330.
Transfer history data appended for: https://www.transfermarkt.com/emirhan-topcu/profil/spieler/531332.
Transfer history data appended for: https://www.transfermarkt.com/fernando-andrade/profil/spieler/236537.
Transfer history data appended for: https://www.transfermarkt.com/tarik-cetin/profil/spieler/286170.
Transfer history data appended for: https://www.transfermarkt.com/yasin-pehlivan/profil/spieler/64016.
Transfer history data appended for: https://www.transfermarkt.com/izzet-karaboga/profil/spieler/662144.
Transfer history data appended for: https://www.transfermarkt.com/farouk-miya/profil/spieler/339005.
Transfer history data appended for: https://www.transfermarkt.com/paolo-hurtado/profil/spieler/84318.
Transfer history data appended for: https://www.transfermarkt.com/levan-shengelia/profil/spieler/329630.
Transfer history data appended for: https://www.transfermarkt.com/samuel-eduok/profil/spieler/274802.
Transfer history data appended for: https://www.transfermarkt.com/marko-jevtovic/profil/spieler/256000.
Transfer history data appended for: https://www.transfermarkt.com/erten-ersu/profil/spieler/203986.
Transfer history data appended for: https://www.transfermarkt.com/volkan-findikli/profil/spieler/126417.
Transfer history data appended for: https://www.transfermarkt.com/marin-anicic/profil/spieler/60784.
Transfer history data appended for: https://www.transfermarkt.com/nejc-skubic/profil/spieler/91434.
Transfer history data appended for: https://www.transfermarkt.com/sokol-cikalleshi/profil/spieler/99047.
Transfer history data appended for: https://www.transfermarkt.com/eray-birnican/profil/spieler/45212.
Transfer history data appended for: https://www.transfermarkt.com/alper-uludag/profil/spieler/55524.

Transfer history data appended for: https://www.transfermarkt.com/guilherme/profil/spieler/217863.
Transfer history data appended for: https://www.transfermarkt.com/erdon-daci/profil/spieler/410285.
Transfer history data appended for: https://www.transfermarkt.com/ugur-demirok/profil/spieler/44977.
Transfer history data appended for: https://www.transfermarkt.com/ali-karakaya/profil/spieler/658837.
Transfer history data appended for: https://www.transfermarkt.com/deni-milosevic/profil/spieler/168163.
Transfer history data appended for: https://www.transfermarkt.com/oguz-kagan-guctekin/profil/spieler/352718.
Transfer history data appended for: https://www.transfermarkt.com/adil-demirbag/profil/spieler/354173.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-sehic/profil/spieler/46252.
Transfer history data appended for: https://www.transfermarkt.com/sener-kaya/profil/spieler/738867.
Transfer history data appended for: https://www.transfermarkt.com/ahmet-calik/profil/spieler/182395.
Transfer history data appended for: https://www.transfermarkt.com/omer-ali-sahiner/profil/spieler/110695.
Transfer history data appended for: https://www.transfermarkt.com/serkan-kirintili/profil/spieler/16058.
Transfer history data appended for: https://www.transfermarkt.com/amir-hadziahmetovic/profil/spieler/293213.
Transfer history data appended for: https://www.transfermarkt.com/ozan-can-oruc/profil/spieler/361272.
Transfer history data appended for: https://www.transfermarkt.com/abdulkerim-bardakci/profil/spieler/199316.
Transfer history data appended for: https://www.transfermarkt.com/muhammet-demir/profil/spieler/83560.
Transfer history data appended for: https://www.transfermarkt.com/jefferson/profil/spieler/252922.
Transfer history data appended for: https://www.transfermarkt.com/jean-armel-kana-biyik/profil/spieler/57404.
Transfer history data appended for: https://www.transfermarkt.com/zvonimir-kozulj/profil/spieler/194205.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-burak-bozan/profil/spieler/587726.
Transfer history data appended for: https://www.transfermarkt.com/junior-morais/profil/spieler/125069.
Transfer history data appended for: https://www.transfermarkt.com/kenan-ozer/profil/spieler/38195.
Transfer history data appended for: https://www.transfermarkt.com/alexandru-maxim/profil/spieler/129513.
Transfer history data appended for: https://www.transfermarkt.com/furkan-soyalp/profil/spieler/221285.
Transfer history data appended for: https://www.transfermarkt.com/nouha-dicko/profil/spieler/173750.
Transfer history data appended for: https://www.transfermarkt.com/mirza-cihan/profil/spieler/583970.
Transfer history data appended for: https://www.transfermarkt.com/pawel-olkowski/profil/spieler/117469.
Transfer history data appended for: https://www.transfermarkt.com/guray-vural/profil/spieler/52281.
Transfer history data appended for: https://www.transfermarkt.com/oguz-ceylan/profil/spieler/139316.
Transfer history data appended for: https://www.transfermarkt.com/ali-ates/profil/spieler/601029.
Transfer history data appended for: https://www.transfermarkt.com/andre-sousa/profil/spieler/187860.
Transfer history data appended for: https://www.transfermarkt.com/mehmet-erdem-ugurlu/profil/spieler/185883.
Transfer history data appended for: https://www.transfermarkt.com/ulas-zengin/profil/spieler/354259.
Transfer history data appended for: https://www.transfermarkt.com/amedej-vetrih/profil/spieler/121481.
Transfer history data appended for: https://www.transfermarkt.com/kubilay-aktas/profil/spieler/274466.
Transfer history data appended for: https://www.transfermarkt.com/murat-sipahioglu/profil/spieler/700264.
Transfer history data appended for: https://www.transfermarkt.com/joseph-paintsil/profil/spieler/534435.
Transfer history data appended for: https://www.transfermarkt.com/erdi-dikmen/profil/spieler/251078.
Transfer history data appended for: https://www.transfermarkt.com/alper-potuk/profil/spieler/99186.
Transfer history data appended for: https://www.transfermarkt.com/korcan-celikay/profil/spieler/50483.
Transfer history data appended for: https://www.transfermarkt.com/endri-cekici/profil/spieler/204049.
Transfer history data appended for: https://www.transfermarkt.com/cebrail-karayel/profil/spieler/260330.
Transfer history data appended for: https://www.transfermarkt.com/stelios-kitsiou/profil/spieler/189151.
Transfer history data appended for: https://www.transfermarkt.com/ricardo-friedrich/profil/spieler/372201.
Transfer history data appended for: https://www.transfermarkt.com/assane-diousse/profil/spieler/287635.
Transfer history data appended for: https://www.transfermarkt.com/tiago-pinto/profil/spieler/63293.
Transfer history data appended for: https://www.transfermarkt.com/ender-aygoren/profil/spieler/576990.
Transfer history data appended for: https://www.transfermarkt.com/emre-gural/profil/spieler/60004.
Transfer history data appended for: https://www.transfermarkt.com/orkan-cinar/profil/spieler/233113.
Transfer history data appended for: https://www.transfermarkt.com/atakan-cankaya/profil/spieler/315208.
Transfer history data appended for: https://www.transfermarkt.com/torgeir-borven/profil/spieler/129236.
Transfer history data appended for: https://www.transfermarkt.com/luka-adzic/profil/spieler/423609.
Transfer history data appended for: https://www.transfermarkt.com/jonathan-bolingi/profil/spieler/315337.
Transfer history data appended for: https://www.transfermarkt.com/mert-topuz/profil/spieler/635993.
Transfer history data appended for: https://www.transfermarkt.com/saba-lobjanidze/profil/spieler/251029.
Transfer history data appended for: https://www.transfermarkt.com/sahverdi-cetin/profil/spieler/342100.
Transfer history data appended for: https://www.transfermarkt.com/daniel-lukasik/profil/spieler/67655.
Transfer history data appended for: https://www.transfermarkt.com/michal-pazdan/profil/spieler/54512.
Transfer history data appended for: https://www.transfermarkt.com/mucahit-can-akcay/profil/spieler/315202.
Transfer history data appended for: https://www.transfermarkt.com/berke-gurbuz/profil/spieler/655907.
Transfer history data appended for: https://www.transfermarkt.com/ante-kulusic/profil/spieler/46056.
Transfer history data appended for: https://www.transfermarkt.com/idriz-voca/profil/spieler/342098.
Transfer history data appended for: https://www.transfermarkt.com/atila-turan/profil/spieler/111063.
Transfer history data appended for: https://www.transfermarkt.com/furkan-beklevic/profil/spieler/460218.
Transfer history data appended for: https://www.transfermarkt.com/sidney-sam/profil/spieler/39102.
Transfer history data appended for: https://www.transfermarkt.com/fredy/profil/spieler/87854.
Transfer history data appended for: https://www.transfermarkt.com/mert-yilmaz/profil/spieler/393217.
Transfer history data appended for: https://www.transfermarkt.com/dogukan-ozkan/profil/spieler/537611.
Transfer history data appended for: https://www.transfermarkt.com/ali-eren-iyican/profil/spieler/554066.
Transfer history data appended for: https://www.transfermarkt.com/eren-albayrak/profil/spieler/59931.
Transfer history data appended for: https://www.transfermarkt.com/ufuk-akyol/profil/spieler/241251.
Transfer history data appended for: https://www.transfermarkt.com/dogukan-sinik/profil/spieler/370833.
Transfer history data appended for: https://www.transfermarkt.com/adis-jahovic/profil/spieler/98536.
Transfer history data appended for: https://www.transfermarkt.com/ferhat-kaplan/profil/spieler/93104.
Transfer history data appended for: https://www.transfermarkt.com/fedor-kudryashov/profil/spieler/48634.
Transfer history data appended for: https://www.transfermarkt.com/amilton/profil/spieler/227676.
Transfer history data appended for: https://www.transfermarkt.com/gokdeniz-bayrakdar/profil/spieler/345105.
Transfer history data appended for: https://www.transfermarkt.com/naldo/profil/spieler/148666.
Transfer history data appended for: https://www.transfermarkt.com/dever-orgill/profil/spieler/103621.
Transfer history data appended for: https://www.transfermarkt.com/hakan-ozmert/profil/spieler/17465.

Transfer history data appended for: https://www.transfermarkt.com/mevluthan-ekelik/profil/spieler/727082.
Transfer history data appended for: https://www.transfermarkt.com/enes-sancar-sahin/profil/spieler/617875.
Transfer history data appended for: https://www.transfermarkt.com/bahadir-ozturk/profil/spieler/353970.
Transfer history data appended for: https://www.transfermarkt.com/ruud-boffin/profil/spieler/31336.
Transfer history data appended for: https://www.transfermarkt.com/omar-imeri/profil/spieler/535537.
Transfer history data appended for: https://www.transfermarkt.com/veysel-sari/profil/spieler/88374.
Transfer history data appended for: https://www.transfermarkt.com/adem-metin-turk/profil/spieler/727101.
Transfer history data appended for: https://www.transfermarkt.com/bunyamin-balci/profil/spieler/620072.
Transfer history data appended for: https://www.transfermarkt.com/diego-angelo/profil/spieler/59333.
Transfer history data appended for: https://www.transfermarkt.com/pierre-yves-polomat/profil/spieler/203764.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-sahindere/profil/spieler/655901.
Transfer history data appended for: https://www.transfermarkt.com/murat-yildirim/profil/spieler/35530.
Transfer history data appended for: https://www.transfermarkt.com/daniel-candeias/profil/spieler/56046.
Transfer history data appended for: https://www.transfermarkt.com/halil-ibrahim-pehlivan/profil/spieler/291760.
Transfer history data appended for: https://www.transfermarkt.com/soner-dikmen/profil/spieler/291750.
Transfer history data appended for: https://www.transfermarkt.com/zargo-toure/profil/spieler/81663.
Transfer history data appended for: https://www.transfermarkt.com/salih-dursun/profil/spieler/176961.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-cecenoglu/profil/spieler/299232.
Transfer history data appended for: https://www.transfermarkt.com/piris-da-motta/profil/spieler/273033.
Transfer history data appended for: https://www.transfermarkt.com/berat-ozdemir/profil/spieler/483063.
Transfer history data appended for: https://www.transfermarkt.com/dominik-furman/profil/spieler/74687.
Transfer history data appended for: https://www.transfermarkt.com/mustafa-huseyin-seyhan/profil/spieler/391496.
Transfer history data appended for: https://www.transfermarkt.com/baran-basyigit/profil/spieler/740514.
Transfer history data appended for: https://www.transfermarkt.com/kristoffer-nordfeldt/profil/spieler/75890.
Transfer history data appended for: https://www.transfermarkt.com/rahmetullah-berisbek/profil/spieler/534706.
Transfer history data appended for: https://www.transfermarkt.com/sefa-yilmaz/profil/spieler/56518.
Transfer history data appended for: https://www.transfermarkt.com/omurcan-artan/profil/spieler/702988.
Transfer history data appended for: https://www.transfermarkt.com/ubeyd-adiyaman/profil/spieler/251070.
Transfer history data appended for: https://www.transfermarkt.com/arda-kizildag/profil/spieler/532905.
Transfer history data appended for: https://www.transfermarkt.com/ilker-karakas/profil/spieler/352721.
Transfer history data appended for: https://www.transfermarkt.com/gokhan-altiparmak/profil/spieler/740515.
Transfer history data appended for: https://www.transfermarkt.com/mattias-johansson/profil/spieler/132014.
Transfer history data appended for: https://www.transfermarkt.com/floyd-ayite/profil/spieler/77974.
Transfer history data appended for: https://www.transfermarkt.com/kadir-enes-kira/profil/spieler/702559.
Transfer history data appended for: https://www.transfermarkt.com/atalay-gokce/profil/spieler/656206.
Transfer history data appended for: https://www.transfermarkt.com/max-gradel/profil/spieler/28140.
Transfer history data appended for: https://www.transfermarkt.com/casimir-ninga/profil/spieler/392810.
Transfer history data appended for: https://www.transfermarkt.com/kerem-atakan-kesgin/profil/spieler/361264.
Transfer history data appended for: https://www.transfermarkt.com/erdogan-yesilyurt/profil/spieler/158946.
Transfer history data appended for: https://www.transfermarkt.com/olarenwaju-kayode/profil/spieler/131694.
Transfer history data appended for: https://www.transfermarkt.com/aaron-appindangoye/profil/spieler/254249.
Transfer history data appended for: https://www.transfermarkt.com/isaac-cofie/profil/spieler/99327.
Transfer history data appended for: https://www.transfermarkt.com/claudemir/profil/spieler/68275.
Transfer history data appended for: https://www.transfermarkt.com/yasin-oztekin/profil/spieler/31867.
Transfer history data appended for: https://www.transfermarkt.com/robin-yalcin/profil/spieler/124422.
Transfer history data appended for: https://www.transfermarkt.com/baris-yardimci/profil/spieler/91948.
Transfer history data appended for: https://www.transfermarkt.com/muammer-yildirim/profil/spieler/169927.
Transfer history data appended for: https://www.transfermarkt.com/eren-sahin/profil/spieler/668069.
Transfer history data appended for: https://www.transfermarkt.com/ziya-erdal/profil/spieler/170644.
Transfer history data appended for: https://www.transfermarkt.com/samba-camara/profil/spieler/291397.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-samassa/profil/spieler/72422.
Transfer history data appended for: https://www.transfermarkt.com/armin-djerlek/profil/spieler/429787.
Transfer history data appended for: https://www.transfermarkt.com/ali-sasal-vural/profil/spieler/157178.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-rybalka/profil/spieler/81649.
Transfer history data appended for: https://www.transfermarkt.com/marcelo-goiano/profil/spieler/248903.
Transfer history data appended for: https://www.transfermarkt.com/faycal-fajr/profil/spieler/174344.
Transfer history data appended for: https://www.transfermarkt.com/ugur-ciftci/profil/spieler/172163.
Transfer history data appended for: https://www.transfermarkt.com/jorge-felix/profil/spieler/251930.
Transfer history data appended for: https://www.transfermarkt.com/lukas-sadilek/profil/spieler/242084.
Transfer history data appended for: https://www.transfermarkt.com/radek-porcal/profil/spieler/82153.
Transfer history data appended for: https://www.transfermarkt.com/timur-melekestsev/profil/spieler/520070.
Transfer history data appended for: https://www.transfermarkt.com/vlastimil-danicek/profil/spieler/141099.
Transfer history data appended for: https://www.transfermarkt.com/michal-kohut/profil/spieler/427829.
Transfer history data appended for: https://www.transfermarkt.com/vaclav-jurecka/profil/spieler/248355.
Transfer history data appended for: https://www.transfermarkt.com/michal-kadlec/profil/spieler/21042.
Transfer history data appended for: https://www.transfermarkt.com/daniel-marecek/profil/spieler/293359.
Transfer history data appended for: https://www.transfermarkt.com/marek-havlik/profil/spieler/233656.
Transfer history data appended for: https://www.transfermarkt.com/filip-kubala/profil/spieler/339077.
Transfer history data appended for: https://www.transfermarkt.com/petr-reinberk/profil/spieler/70639.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-hofmann/profil/spieler/81991.
Transfer history data appended for: https://www.transfermarkt.com/rigino-cicilia/profil/spieler/275939.
Transfer history data appended for: https://www.transfermarkt.com/patrik-simko/profil/spieler/132375.
Transfer history data appended for: https://www.transfermarkt.com/milan-petrzela/profil/spieler/21101.
Transfer history data appended for: https://www.transfermarkt.com/jan-kalabiska/profil/spieler/70699.
Transfer history data appended for: https://www.transfermarkt.com/josef-divisek/profil/spieler/95794.
Transfer history data appended for: https://www.transfermarkt.com/pavol-bajza/profil/spieler/120175.
Transfer history data appended for: https://www.transfermarkt.com/jakub-rezek/profil/spieler/321202.
Transfer history data appended for: https://www.transfermarkt.com/vit-nemrava/profil/spieler/221280.
Transfer history data appended for: https://www.transfermarkt.com/jan-navratil/profil/spieler/95802.
Transfer history data appended for: https://www.transfermarkt.com/patrik-hellebrand/profil/spieler/339070.

Transfer history data appended for: https://www.transfermarkt.com/milan-havel/profil/spieler/261913.
Transfer history data appended for: https://www.transfermarkt.com/radim-reznik/profil/spieler/62794.
Transfer history data appended for: https://www.transfermarkt.com/pavel-bucha/profil/spieler/563033.
Transfer history data appended for: https://www.transfermarkt.com/filip-kasa/profil/spieler/186527.
Transfer history data appended for: https://www.transfermarkt.com/lukas-kalvach/profil/spieler/283621.
Transfer history data appended for: https://www.transfermarkt.com/marko-alvir/profil/spieler/179898.
Transfer history data appended for: https://www.transfermarkt.com/lukas-hejda/profil/spieler/96047.
Transfer history data appended for: https://www.transfermarkt.com/zdenek-ondrasek/profil/spieler/72947.
Transfer history data appended for: https://www.transfermarkt.com/matej-hybs/profil/spieler/137621.
Transfer history data appended for: https://www.transfermarkt.com/jean-david-beauguel/profil/spieler/198395.
Transfer history data appended for: https://www.transfermarkt.com/david-limbersky/profil/spieler/16090.
Transfer history data appended for: https://www.transfermarkt.com/ales-cermak/profil/spieler/147540.
Transfer history data appended for: https://www.transfermarkt.com/jan-kopic/profil/spieler/119103.
Transfer history data appended for: https://www.transfermarkt.com/jan-kovarik/profil/spieler/81800.
Transfer history data appended for: https://www.transfermarkt.com/joel-kayamba/profil/spieler/384856.
Transfer history data appended for: https://www.transfermarkt.com/miroslav-kacer/profil/spieler/186382.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-mihalik/profil/spieler/265051.
Transfer history data appended for: https://www.transfermarkt.com/adriel-ba-loua/profil/spieler/364314.
Transfer history data appended for: https://www.transfermarkt.com/ales-hruska/profil/spieler/63897.
Transfer history data appended for: https://www.transfermarkt.com/ludek-pernica/profil/spieler/147099.
Transfer history data appended for: https://www.transfermarkt.com/tomas-horava/profil/spieler/70153.
Transfer history data appended for: https://www.transfermarkt.com/jakub-brabec/profil/spieler/112948.
Transfer history data appended for: https://www.transfermarkt.com/dominik-svacek/profil/spieler/269167.
Transfer history data appended for: https://www.transfermarkt.com/jindrich-stanek/profil/spieler/242089.
Transfer history data appended for: https://www.transfermarkt.com/jean-mangabeira/profil/spieler/551904.
Transfer history data appended for: https://www.transfermarkt.com/gigli-ndefe/profil/spieler/223035.
Transfer history data appended for: https://www.transfermarkt.com/lukas-bartosak/profil/spieler/145821.
Transfer history data appended for: https://www.transfermarkt.com/tomas-jursa/profil/spieler/82165.
Transfer history data appended for: https://www.transfermarkt.com/tomas-ostrak/profil/spieler/428189.
Transfer history data appended for: https://www.transfermarkt.com/roman-hasa/profil/spieler/265919.
Transfer history data appended for: https://www.transfermarkt.com/christian-herc/profil/spieler/365765.
Transfer history data appended for: https://www.transfermarkt.com/kristi-qose/profil/spieler/267497.
Transfer history data appended for: https://www.transfermarkt.com/martin-sindelar/profil/spieler/152695.
Transfer history data appended for: https://www.transfermarkt.com/daniel-stropek/profil/spieler/598508.
Transfer history data appended for: https://www.transfermarkt.com/david-guba/profil/spieler/112459.
Transfer history data appended for: https://www.transfermarkt.com/eduardo-santos/profil/spieler/564546.
Transfer history data appended for: https://www.transfermarkt.com/petr-bolek/profil/spieler/21239.
Transfer history data appended for: https://www.transfermarkt.com/libor-hrdlicka/profil/spieler/82508.
Transfer history data appended for: https://www.transfermarkt.com/lukas-cmelik/profil/spieler/186379.
Transfer history data appended for: https://www.transfermarkt.com/rafael-tavares/profil/spieler/644994.
Transfer history data appended for: https://www.transfermarkt.com/martin-vlachovsky/profil/spieler/649566.
Transfer history data appended for: https://www.transfermarkt.com/filip-twardzik/profil/spieler/93873.
Transfer history data appended for: https://www.transfermarkt.com/rajmund-mikus/profil/spieler/329401.
Transfer history data appended for: https://www.transfermarkt.com/vojtech-smrz/profil/spieler/474779.
Transfer history data appended for: https://www.transfermarkt.com/marek-janecka/profil/spieler/90328.
Transfer history data appended for: https://www.transfermarkt.com/marek-hanousek/profil/spieler/76655.
Transfer history data appended for: https://www.transfermarkt.com/oliver-putyera/profil/spieler/371121.
Transfer history data appended for: https://www.transfermarkt.com/soufiane-drame/profil/spieler/471614.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-neuman/profil/spieler/668311.
Transfer history data appended for: https://www.transfermarkt.com/roman-holis/profil/spieler/474804.
Transfer history data appended for: https://www.transfermarkt.com/milan-jirasek/profil/spieler/124556.
Transfer history data appended for: https://www.transfermarkt.com/jaroslav-svozil/profil/spieler/267503.
Transfer history data appended for: https://www.transfermarkt.com/muhamed-tijani/profil/spieler/665546.
Transfer history data appended for: https://www.transfermarkt.com/jakub-pokorny/profil/spieler/333494.
Transfer history data appended for: https://www.transfermarkt.com/patrizio-stronati/profil/spieler/264559.
Transfer history data appended for: https://www.transfermarkt.com/dominik-martisiak/profil/spieler/434093.
Transfer history data appended for: https://www.transfermarkt.com/jakub-drozd/profil/spieler/652058.
Transfer history data appended for: https://www.transfermarkt.com/david-buchta/profil/spieler/405856.
Transfer history data appended for: https://www.transfermarkt.com/milan-lalkovic/profil/spieler/91887.
Transfer history data appended for: https://www.transfermarkt.com/jiri-fleisman/profil/spieler/70690.
Transfer history data appended for: https://www.transfermarkt.com/radovan-murin/profil/spieler/469791.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-azatskyi/profil/spieler/211313.
Transfer history data appended for: https://www.transfermarkt.com/viktor-budinsky/profil/spieler/226980.
Transfer history data appended for: https://www.transfermarkt.com/roman-potocny/profil/spieler/179240.
Transfer history data appended for: https://www.transfermarkt.com/pepe-mena/profil/spieler/396145.
Transfer history data appended for: https://www.transfermarkt.com/dan-ozvolda/profil/spieler/408889.
Transfer history data appended for: https://www.transfermarkt.com/martin-fillo/profil/spieler/35753.
Transfer history data appended for: https://www.transfermarkt.com/jan-juroska/profil/spieler/324023.
Transfer history data appended for: https://www.transfermarkt.com/daniel-tetour/profil/spieler/366883.
Transfer history data appended for: https://www.transfermarkt.com/tomas-zajic/profil/spieler/324041.
Transfer history data appended for: https://www.transfermarkt.com/azevedo/profil/spieler/154335.
Transfer history data appended for: https://www.transfermarkt.com/daniel-holzer/profil/spieler/198603.
Transfer history data appended for: https://www.transfermarkt.com/nemanja-kuzmanovic/profil/spieler/60472.
Transfer history data appended for: https://www.transfermarkt.com/filip-kaloc/profil/spieler/396230.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-sasinka/profil/spieler/293366.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-chveja/profil/spieler/321179.
Transfer history data appended for: https://www.transfermarkt.com/adam-janos/profil/spieler/133733.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-keita/profil/spieler/220902.
Transfer history data appended for: https://www.transfermarkt.com/jiri-bederka/profil/spieler/326042.
Transfer history data appended for: https://www.transfermarkt.com/jan-vondra/profil/spieler/198617.

Transfer history data appended for: https://www.transfermarkt.com/daniel-krch/profil/spieler/146719.
Transfer history data appended for: https://www.transfermarkt.com/roman-kvet/profil/spieler/400649.
Transfer history data appended for: https://www.transfermarkt.com/patrik-le-giang/profil/spieler/166239.
Transfer history data appended for: https://www.transfermarkt.com/david-bartek/profil/spieler/62971.
Transfer history data appended for: https://www.transfermarkt.com/matej-pulkrab/profil/spieler/256097.
Transfer history data appended for: https://www.transfermarkt.com/vojtech-novak/profil/spieler/714148.
Transfer history data appended for: https://www.transfermarkt.com/antonin-vanicek/profil/spieler/321215.
Transfer history data appended for: https://www.transfermarkt.com/lukas-hulka/profil/spieler/198607.
Transfer history data appended for: https://www.transfermarkt.com/marek-kouba/profil/spieler/514836.
Transfer history data appended for: https://www.transfermarkt.com/josef-jindrisek/profil/spieler/21040.
Transfer history data appended for: https://www.transfermarkt.com/filip-hasek/profil/spieler/260031.
Transfer history data appended for: https://www.transfermarkt.com/martin-dostal/profil/spieler/178466.
Transfer history data appended for: https://www.transfermarkt.com/vladislav-levin/profil/spieler/260265.
Transfer history data appended for: https://www.transfermarkt.com/jakub-necas/profil/spieler/301019.
Transfer history data appended for: https://www.transfermarkt.com/roman-vales/profil/spieler/95805.
Transfer history data appended for: https://www.transfermarkt.com/till-schumacher/profil/spieler/236467.
Transfer history data appended for: https://www.transfermarkt.com/lukas-pokorny/profil/spieler/279529.
Transfer history data appended for: https://www.transfermarkt.com/david-puskac/profil/spieler/194562.
Transfer history data appended for: https://www.transfermarkt.com/petr-hronek/profil/spieler/280856.
Transfer history data appended for: https://www.transfermarkt.com/daniel-kostl/profil/spieler/293358.
Transfer history data appended for: https://www.transfermarkt.com/jan-vodhanel/profil/spieler/430250.
Transfer history data appended for: https://www.transfermarkt.com/hugo-jan-backovsky/profil/spieler/339041.
Transfer history data appended for: https://www.transfermarkt.com/borek-dockal/profil/spieler/62983.
Transfer history data appended for: https://www.transfermarkt.com/dominik-holec/profil/spieler/181611.
Transfer history data appended for: https://www.transfermarkt.com/filip-panak/profil/spieler/331963.
Transfer history data appended for: https://www.transfermarkt.com/florin-nita/profil/spieler/200475.
Transfer history data appended for: https://www.transfermarkt.com/adam-hlozek/profil/spieler/552057.
Transfer history data appended for: https://www.transfermarkt.com/david-moberg-karlsson/profil/spieler/63422.
Transfer history data appended for: https://www.transfermarkt.com/libor-kozak/profil/spieler/63824.
Transfer history data appended for: https://www.transfermarkt.com/martin-minchev/profil/spieler/481128.
Transfer history data appended for: https://www.transfermarkt.com/tomas-wiesner/profil/spieler/334807.
Transfer history data appended for: https://www.transfermarkt.com/matej-polidar/profil/spieler/639928.
Transfer history data appended for: https://www.transfermarkt.com/filip-soucek/profil/spieler/672840.
Transfer history data appended for: https://www.transfermarkt.com/dominik-plechaty/profil/spieler/456146.
Transfer history data appended for: https://www.transfermarkt.com/david-lischka/profil/spieler/334822.
Transfer history data appended for: https://www.transfermarkt.com/david-hancko/profil/spieler/404418.
Transfer history data appended for: https://www.transfermarkt.com/ladislav-krejci/profil/spieler/140206.
Transfer history data appended for: https://www.transfermarkt.com/michal-sacek/profil/spieler/430054.
Transfer history data appended for: https://www.transfermarkt.com/srdjan-plavsic/profil/spieler/322800.
Transfer history data appended for: https://www.transfermarkt.com/matej-hanousek/profil/spieler/267473.
Transfer history data appended for: https://www.transfermarkt.com/andreas-vindheim/profil/spieler/254472.
Transfer history data appended for: https://www.transfermarkt.com/michal-travnik/profil/spieler/189640.
Transfer history data appended for: https://www.transfermarkt.com/lukas-stetina/profil/spieler/119110.
Transfer history data appended for: https://www.transfermarkt.com/david-pavelka/profil/spieler/133734.
Transfer history data appended for: https://www.transfermarkt.com/milan-heca/profil/spieler/119472.
Transfer history data appended for: https://www.transfermarkt.com/adam-karabec/profil/spieler/652061.
Transfer history data appended for: https://www.transfermarkt.com/ladislav-krejci/profil/spieler/345911.
Transfer history data appended for: https://www.transfermarkt.com/lukas-julis/profil/spieler/147550.
Transfer history data appended for: https://www.transfermarkt.com/tomas-solil/profil/spieler/488870.
Transfer history data appended for: https://www.transfermarkt.com/emil-tischler/profil/spieler/263359.
Transfer history data appended for: https://www.transfermarkt.com/vojtech-sychra/profil/spieler/580129.
Transfer history data appended for: https://www.transfermarkt.com/michal-petran/profil/spieler/187585.
Transfer history data appended for: https://www.transfermarkt.com/matej-vit/profil/spieler/486667.
Transfer history data appended for: https://www.transfermarkt.com/stepan-hrncir/profil/spieler/469116.
Transfer history data appended for: https://www.transfermarkt.com/tomas-celustka/profil/spieler/194579.
Transfer history data appended for: https://www.transfermarkt.com/cadu/profil/spieler/748908.
Transfer history data appended for: https://www.transfermarkt.com/sang-hyuk-lee/profil/spieler/646071.
Transfer history data appended for: https://www.transfermarkt.com/michal-surzyn/profil/spieler/523509.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-smid/profil/spieler/464935.
Transfer history data appended for: https://www.transfermarkt.com/jiri-slama/profil/spieler/503963.
Transfer history data appended for: https://www.transfermarkt.com/samuel-simek/profil/spieler/580150.
Transfer history data appended for: https://www.transfermarkt.com/tomas-kubart/profil/spieler/487926.
Transfer history data appended for: https://www.transfermarkt.com/martin-sejvl/profil/spieler/235210.
Transfer history data appended for: https://www.transfermarkt.com/ewerton/profil/spieler/456893.
Transfer history data appended for: https://www.transfermarkt.com/lukas-husek/profil/spieler/490895.
Transfer history data appended for: https://www.transfermarkt.com/david-huf/profil/spieler/339072.
Transfer history data appended for: https://www.transfermarkt.com/petr-kurka/profil/spieler/629774.
Transfer history data appended for: https://www.transfermarkt.com/jan-prosek/profil/spieler/198605.
Transfer history data appended for: https://www.transfermarkt.com/pieter-langedijk/profil/spieler/248617.
Transfer history data appended for: https://www.transfermarkt.com/jiri-letacek/profil/spieler/339079.
Transfer history data appended for: https://www.transfermarkt.com/michal-hlavaty/profil/spieler/293355.
Transfer history data appended for: https://www.transfermarkt.com/lukas-pfeifer/profil/spieler/503962.
Transfer history data appended for: https://www.transfermarkt.com/marek-bohac/profil/spieler/123604.
Transfer history data appended for: https://www.transfermarkt.com/jan-jerabek/profil/spieler/235171.
Transfer history data appended for: https://www.transfermarkt.com/filip-cihak/profil/spieler/456143.
Transfer history data appended for: https://www.transfermarkt.com/pavel-cerny/profil/spieler/63859.
Transfer history data appended for: https://www.transfermarkt.com/martin-toml/profil/spieler/221287.
Transfer history data appended for: https://www.transfermarkt.com/tomas-grigar/profil/spieler/18913.
Transfer history data appended for: https://www.transfermarkt.com/vukadin-vukadinovic/profil/spieler/84813.
Transfer history data appended for: https://www.transfermarkt.com/jakub-divis/profil/spieler/44710.
Transfer history data appended for: https://www.transfermarkt.com/david-heidenreich/profil/spieler/473887.

Transfer history data appended for: https://www.transfermarkt.com/jan-shejbal/profil/spieler/280875.
Transfer history data appended for: https://www.transfermarkt.com/jan-fortelny/profil/spieler/233235.
Transfer history data appended for: https://www.transfermarkt.com/jan-plachy/profil/spieler/422608.
Transfer history data appended for: https://www.transfermarkt.com/evgeniy-nazarov/profil/spieler/371628.
Transfer history data appended for: https://www.transfermarkt.com/jakub-reznicek/profil/spieler/59772.
Transfer history data appended for: https://www.transfermarkt.com/jakub-mares/profil/spieler/35577.
Transfer history data appended for: https://www.transfermarkt.com/alois-hycka/profil/spieler/123765.
Transfer history data appended for: https://www.transfermarkt.com/jan-knapik/profil/spieler/591843.
Transfer history data appended for: https://www.transfermarkt.com/daniel-trubac/profil/spieler/265056.
Transfer history data appended for: https://www.transfermarkt.com/david-cerny/profil/spieler/651651.
Transfer history data appended for: https://www.transfermarkt.com/robert-jukl/profil/spieler/523507.
Transfer history data appended for: https://www.transfermarkt.com/matyas-kozak/profil/spieler/486748.
Transfer history data appended for: https://www.transfermarkt.com/matej-radosta/profil/spieler/486618.
Transfer history data appended for: https://www.transfermarkt.com/ludek-nemecek/profil/spieler/599580.
Transfer history data appended for: https://www.transfermarkt.com/patrik-zitny/profil/spieler/192809.
Transfer history data appended for: https://www.transfermarkt.com/pavel-moulis/profil/spieler/195503.
Transfer history data appended for: https://www.transfermarkt.com/admir-ljevakovic/profil/spieler/39957.
Transfer history data appended for: https://www.transfermarkt.com/tomas-vondrasek/profil/spieler/63751.
Transfer history data appended for: https://www.transfermarkt.com/lukas-marecek/profil/spieler/70170.
Transfer history data appended for: https://www.transfermarkt.com/tomas-kucera/profil/spieler/194492.
Transfer history data appended for: https://www.transfermarkt.com/dominik-sup/profil/spieler/509139.
Transfer history data appended for: https://www.transfermarkt.com/ales-nesicky/profil/spieler/146722.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-tijani/profil/spieler/534375.
Transfer history data appended for: https://www.transfermarkt.com/michal-fukala/profil/spieler/500308.
Transfer history data appended for: https://www.transfermarkt.com/milan-knobloch/profil/spieler/368406.
Transfer history data appended for: https://www.transfermarkt.com/imad-rondic/profil/spieler/464154.
Transfer history data appended for: https://www.transfermarkt.com/martin-koscelnik/profil/spieler/382204.
Transfer history data appended for: https://www.transfermarkt.com/michael-rabusic/profil/spieler/63965.
Transfer history data appended for: https://www.transfermarkt.com/filip-nguyen/profil/spieler/202914.
Transfer history data appended for: https://www.transfermarkt.com/lukas-csano/profil/spieler/550700.
Transfer history data appended for: https://www.transfermarkt.com/jan-mikula/profil/spieler/178467.
Transfer history data appended for: https://www.transfermarkt.com/jakub-hromada/profil/spieler/186380.
Transfer history data appended for: https://www.transfermarkt.com/karel-knejzlik/profil/spieler/260502.
Transfer history data appended for: https://www.transfermarkt.com/matej-chalus/profil/spieler/321178.
Transfer history data appended for: https://www.transfermarkt.com/david-cancola/profil/spieler/228879.
Transfer history data appended for: https://www.transfermarkt.com/marios-pourzitidis/profil/spieler/598148.
Transfer history data appended for: https://www.transfermarkt.com/jakub-barac/profil/spieler/503432.
Transfer history data appended for: https://www.transfermarkt.com/jan-matousek/profil/spieler/400653.
Transfer history data appended for: https://www.transfermarkt.com/jhon-mosquera/profil/spieler/239126.
Transfer history data appended for: https://www.transfermarkt.com/radim-cernicky/profil/spieler/708310.
Transfer history data appended for: https://www.transfermarkt.com/kamso-mara/profil/spieler/525085.
Transfer history data appended for: https://www.transfermarkt.com/daniel-kosek/profil/spieler/486626.
Transfer history data appended for: https://www.transfermarkt.com/jan-sulc/profil/spieler/447930.
Transfer history data appended for: https://www.transfermarkt.com/jakub-jugas/profil/spieler/146712.
Transfer history data appended for: https://www.transfermarkt.com/michal-sadilek/profil/spieler/321204.
Transfer history data appended for: https://www.transfermarkt.com/taras-kacharaba/profil/spieler/213975.
Transfer history data appended for: https://www.transfermarkt.com/jakub-pesek/profil/spieler/346840.
Transfer history data appended for: https://www.transfermarkt.com/michal-beran/profil/spieler/664456.
Transfer history data appended for: https://www.transfermarkt.com/yusuf/profil/spieler/351181.
Transfer history data appended for: https://www.transfermarkt.com/kristian-michal/profil/spieler/561229.
Transfer history data appended for: https://www.transfermarkt.com/jakub-martinec/profil/spieler/293360.
Transfer history data appended for: https://www.transfermarkt.com/michal-cernak/profil/spieler/652059.
Transfer history data appended for: https://www.transfermarkt.com/david-stepanek/profil/spieler/256103.
Transfer history data appended for: https://www.transfermarkt.com/tomas-cvancara/profil/spieler/544148.
Transfer history data appended for: https://www.transfermarkt.com/vladimir-jovovic/profil/spieler/246827.
Transfer history data appended for: https://www.transfermarkt.com/rafael-acosta/profil/spieler/248246.
Transfer history data appended for: https://www.transfermarkt.com/patrik-haitl/profil/spieler/390502.
Transfer history data appended for: https://www.transfermarkt.com/milos-kratochvil/profil/spieler/289464.
Transfer history data appended for: https://www.transfermarkt.com/jakub-povazanec/profil/spieler/113003.
Transfer history data appended for: https://www.transfermarkt.com/tomas-hubschman/profil/spieler/9688.
Transfer history data appended for: https://www.transfermarkt.com/jakub-podany/profil/spieler/81978.
Transfer history data appended for: https://www.transfermarkt.com/jan-hanus/profil/spieler/120030.
Transfer history data appended for: https://www.transfermarkt.com/jan-chramosta/profil/spieler/95792.
Transfer history data appended for: https://www.transfermarkt.com/david-machacek/profil/spieler/424233.
Transfer history data appended for: https://www.transfermarkt.com/jaroslav-zeleny/profil/spieler/142219.
Transfer history data appended for: https://www.transfermarkt.com/vlastimil-hruby/profil/spieler/157578.
Transfer history data appended for: https://www.transfermarkt.com/robert-hruby/profil/spieler/147548.
Transfer history data appended for: https://www.transfermarkt.com/jan-krob/profil/spieler/62511.
Transfer history data appended for: https://www.transfermarkt.com/oliver-velich/profil/spieler/685302.
Transfer history data appended for: https://www.transfermarkt.com/tomas-ladra/profil/spieler/334803.
Transfer history data appended for: https://www.transfermarkt.com/vojtech-kubista/profil/spieler/220776.
Transfer history data appended for: https://www.transfermarkt.com/libor-holik/profil/spieler/323903.
Transfer history data appended for: https://www.transfermarkt.com/dominik-plestil/profil/spieler/504809.
Transfer history data appended for: https://www.transfermarkt.com/ivan-schranz/profil/spieler/108416.
Transfer history data appended for: https://www.transfermarkt.com/martin-dolezal/profil/spieler/82026.
Transfer history data appended for: https://www.transfermarkt.com/michal-jerabek/profil/spieler/261897.
Transfer history data appended for: https://www.transfermarkt.com/kasper-hamalainen/profil/spieler/48016.
Transfer history data appended for: https://www.transfermarkt.com/matej-mrsic/profil/spieler/191823.
Transfer history data appended for: https://www.transfermarkt.com/maksym-taloverov/profil/spieler/668557.
Transfer history data appended for: https://www.transfermarkt.com/martin-janacek/profil/spieler/488869.

Transfer history data appended for: https://www.transfermarkt.com/petr-javorek/profil/spieler/35177.
Transfer history data appended for: https://www.transfermarkt.com/filip-havelka/profil/spieler/318099.
Transfer history data appended for: https://www.transfermarkt.com/lukas-havel/profil/spieler/383869.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-colic/profil/spieler/122227.
Transfer history data appended for: https://www.transfermarkt.com/ubong-ekpai/profil/spieler/365861.
Transfer history data appended for: https://www.transfermarkt.com/lukas-matejka/profil/spieler/480189.
Transfer history data appended for: https://www.transfermarkt.com/lukas-janosik/profil/spieler/403298.
Transfer history data appended for: https://www.transfermarkt.com/jaroslav-drobny/profil/spieler/12864.
Transfer history data appended for: https://www.transfermarkt.com/patrik-brandner/profil/spieler/279374.
Transfer history data appended for: https://www.transfermarkt.com/matej-valenta/profil/spieler/572240.
Transfer history data appended for: https://www.transfermarkt.com/fortune-bassey/profil/spieler/585985.
Transfer history data appended for: https://www.transfermarkt.com/vojtech-vorel/profil/spieler/221289.
Transfer history data appended for: https://www.transfermarkt.com/mick-van-buren/profil/spieler/189053.
Transfer history data appended for: https://www.transfermarkt.com/jiri-kladrubsky/profil/spieler/57415.
Transfer history data appended for: https://www.transfermarkt.com/pavel-sulc/profil/spieler/500053.
Transfer history data appended for: https://www.transfermarkt.com/david-ledecky/profil/spieler/333654.
Transfer history data appended for: https://www.transfermarkt.com/martin-kralik/profil/spieler/168417.
Transfer history data appended for: https://www.transfermarkt.com/pavel-novak/profil/spieler/148705.
Transfer history data appended for: https://www.transfermarkt.com/lukas-skovajsa/profil/spieler/232390.
Transfer history data appended for: https://www.transfermarkt.com/patrik-cavos/profil/spieler/283614.
Transfer history data appended for: https://www.transfermarkt.com/karol-meszaros/profil/spieler/217707.
Transfer history data appended for: https://www.transfermarkt.com/simon-sumbera/profil/spieler/204279.
Transfer history data appended for: https://www.transfermarkt.com/peter-stepanovsky/profil/spieler/91804.
Transfer history data appended for: https://www.transfermarkt.com/jan-sedlak/profil/spieler/333652.
Transfer history data appended for: https://www.transfermarkt.com/antonin-rusek/profil/spieler/318112.
Transfer history data appended for: https://www.transfermarkt.com/jan-moravec/profil/spieler/63021.
Transfer history data appended for: https://www.transfermarkt.com/jan-koudelka/profil/spieler/483640.
Transfer history data appended for: https://www.transfermarkt.com/jan-hladik/profil/spieler/384882.
Transfer history data appended for: https://www.transfermarkt.com/juraj-kotula/profil/spieler/299587.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-pachlopnik/profil/spieler/424374.
Transfer history data appended for: https://www.transfermarkt.com/damian-baris/profil/spieler/278861.
Transfer history data appended for: https://www.transfermarkt.com/marek-vintr/profil/spieler/584550.
Transfer history data appended for: https://www.transfermarkt.com/jakub-cernin/profil/spieler/572792.
Transfer history data appended for: https://www.transfermarkt.com/pavel-dreksa/profil/spieler/119832.
Transfer history data appended for: https://www.transfermarkt.com/adam-fousek/profil/spieler/273101.
Transfer history data appended for: https://www.transfermarkt.com/marek-mach/profil/spieler/427827.
Transfer history data appended for: https://www.transfermarkt.com/rudolf-reiter/profil/spieler/316279.
Transfer history data appended for: https://www.transfermarkt.com/jakub-sural/profil/spieler/292536.
Transfer history data appended for: https://www.transfermarkt.com/vojtech-marek/profil/spieler/666262.
Transfer history data appended for: https://www.transfermarkt.com/jan-hlavica/profil/spieler/147545.
Transfer history data appended for: https://www.transfermarkt.com/adrian-cermak/profil/spieler/202481.
Transfer history data appended for: https://www.transfermarkt.com/zoran-gajic/profil/spieler/70328.
Transfer history data appended for: https://www.transfermarkt.com/jiri-floder/profil/spieler/265038.
Transfer history data appended for: https://www.transfermarkt.com/jakub-prichystal/profil/spieler/342491.
Transfer history data appended for: https://www.transfermarkt.com/martin-sustr/profil/spieler/112466.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-vanek/profil/spieler/134578.
Transfer history data appended for: https://www.transfermarkt.com/lukas-endl/profil/spieler/652055.
Transfer history data appended for: https://www.transfermarkt.com/lukas-krystufek/profil/spieler/236156.
Transfer history data appended for: https://www.transfermarkt.com/laco-takacs/profil/spieler/303440.
Transfer history data appended for: https://www.transfermarkt.com/jan-stejskal/profil/spieler/260071.
Transfer history data appended for: https://www.transfermarkt.com/nicolae-stanciu/profil/spieler/148372.
Transfer history data appended for: https://www.transfermarkt.com/jan-sirotnik/profil/spieler/565471.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-kudela/profil/spieler/35699.
Transfer history data appended for: https://www.transfermarkt.com/petar-musa/profil/spieler/387110.
Transfer history data appended for: https://www.transfermarkt.com/abdallah-sima/profil/spieler/776798.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-kolar/profil/spieler/189630.
Transfer history data appended for: https://www.transfermarkt.com/david-hovorka/profil/spieler/263431.
Transfer history data appended for: https://www.transfermarkt.com/jan-boril/profil/spieler/129655.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-traore/profil/spieler/179236.
Transfer history data appended for: https://www.transfermarkt.com/lukas-masopust/profil/spieler/234153.
Transfer history data appended for: https://www.transfermarkt.com/jan-kuchta/profil/spieler/334802.
Transfer history data appended for: https://www.transfermarkt.com/tomas-malinsky/profil/spieler/193590.
Transfer history data appended for: https://www.transfermarkt.com/premysl-kovar/profil/spieler/70625.
Transfer history data appended for: https://www.transfermarkt.com/david-zima/profil/spieler/544149.
Transfer history data appended for: https://www.transfermarkt.com/tomas-holes/profil/spieler/216278.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-karafiat/profil/spieler/181614.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-lingr/profil/spieler/321195.
Transfer history data appended for: https://www.transfermarkt.com/peter-olayinka/profil/spieler/248393.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-tecl/profil/spieler/81390.
Transfer history data appended for: https://www.transfermarkt.com/oscar-dorley/profil/spieler/401475.
Transfer history data appended for: https://www.transfermarkt.com/petr-sevcik/profil/spieler/147555.
Transfer history data appended for: https://www.transfermarkt.com/lukas-provod/profil/spieler/292779.
Transfer history data appended for: https://www.transfermarkt.com/jan-seda/profil/spieler/44422.
Transfer history data appended for: https://www.transfermarkt.com/michael-honig/profil/spieler/488871.
Transfer history data appended for: https://www.transfermarkt.com/davis-ikaunieks/profil/spieler/153820.
Transfer history data appended for: https://www.transfermarkt.com/robert-mazan/profil/spieler/181619.
Transfer history data appended for: https://www.transfermarkt.com/petr-mares/profil/spieler/134874.
Transfer history data appended for: https://www.transfermarkt.com/david-pech/profil/spieler/552055.
Transfer history data appended for: https://www.transfermarkt.com/daniel-langhamer/profil/spieler/710409.
Transfer history data appended for: https://www.transfermarkt.com/antonin-krapka/profil/spieler/367653.
Transfer history data appended for: https://www.transfermarkt.com/dominik-janosek/profil/spieler/522993.

Transfer history data appended for: https://www.transfermarkt.com/jakub-fulnek/profil/spieler/212872.
Transfer history data appended for: https://www.transfermarkt.com/jakub-klima/profil/spieler/539698.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-mazuch/profil/spieler/23443.
Transfer history data appended for: https://www.transfermarkt.com/simon-gabriel/profil/spieler/486608.
Transfer history data appended for: https://www.transfermarkt.com/aleksey-tataev/profil/spieler/312502.
Transfer history data appended for: https://www.transfermarkt.com/david-simek/profil/spieler/493763.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-zahustel/profil/spieler/143148.
Transfer history data appended for: https://www.transfermarkt.com/michal-skoda/profil/spieler/199855.
Transfer history data appended for: https://www.transfermarkt.com/petr-mikulec/profil/spieler/499574.
Transfer history data appended for: https://www.transfermarkt.com/david-doudera/profil/spieler/493758.
Transfer history data appended for: https://www.transfermarkt.com/dominik-masek/profil/spieler/126770.
Transfer history data appended for: https://www.transfermarkt.com/jakub-markovic/profil/spieler/486605.
Transfer history data appended for: https://www.transfermarkt.com/vaclav-drchal/profil/spieler/421984.
Transfer history data appended for: https://www.transfermarkt.com/jiri-kulhanek/profil/spieler/292522.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-rudzan/profil/spieler/438566.
Transfer history data appended for: https://www.transfermarkt.com/vojtech-stransky/profil/spieler/728609.
Transfer history data appended for: https://www.transfermarkt.com/lukas-budinsky/profil/spieler/187591.
Transfer history data appended for: https://www.transfermarkt.com/jiri-klima/profil/spieler/260038.
Transfer history data appended for: https://www.transfermarkt.com/marco-tulio/profil/spieler/525086.
Transfer history data appended for: https://www.transfermarkt.com/marek-matejovsky/profil/spieler/26906.
Transfer history data appended for: https://www.transfermarkt.com/petr-buchta/profil/spieler/194333.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-dostal/profil/spieler/82477.
Transfer history data appended for: https://www.transfermarkt.com/tomas-poznar/profil/spieler/81979.
Transfer history data appended for: https://www.transfermarkt.com/lamin-jawo/profil/spieler/444387.
Transfer history data appended for: https://www.transfermarkt.com/pedro-martinez/profil/spieler/404632.
Transfer history data appended for: https://www.transfermarkt.com/petr-jiracek/profil/spieler/63737.
Transfer history data appended for: https://www.transfermarkt.com/martins-toutou/profil/spieler/651080.
Transfer history data appended for: https://www.transfermarkt.com/matej-rakovan/profil/spieler/141353.
Transfer history data appended for: https://www.transfermarkt.com/youba-drame/profil/spieler/560274.
Transfer history data appended for: https://www.transfermarkt.com/cheick-conde/profil/spieler/698560.
Transfer history data appended for: https://www.transfermarkt.com/lukas-vrastil/profil/spieler/147557.
Transfer history data appended for: https://www.transfermarkt.com/patrik-slamena/profil/spieler/396231.
Transfer history data appended for: https://www.transfermarkt.com/jan-siska/profil/spieler/583145.
Transfer history data appended for: https://www.transfermarkt.com/jakub-kolar/profil/spieler/668323.
Transfer history data appended for: https://www.transfermarkt.com/marek-hlinka/profil/spieler/147111.
Transfer history data appended for: https://www.transfermarkt.com/vakhtang-chanturishvili/profil/spieler/187115.
Transfer history data appended for: https://www.transfermarkt.com/simon-chwaszcz/profil/spieler/300181.
Transfer history data appended for: https://www.transfermarkt.com/martin-cedidla/profil/spieler/633447.
Transfer history data appended for: https://www.transfermarkt.com/vaclav-prochazka/profil/spieler/35763.
Transfer history data appended for: https://www.transfermarkt.com/jakub-janetzky/profil/spieler/260036.
Transfer history data appended for: https://www.transfermarkt.com/antonin-fantis/profil/spieler/81811.
Transfer history data appended for: https://www.transfermarkt.com/dominik-simersky/profil/spieler/167175.
Transfer history data appended for: https://www.transfermarkt.com/robert-matejov/profil/spieler/113009.
Transfer history data appended for: https://www.transfermarkt.com/pavel-vyhnal/profil/spieler/164082.
Transfer history data appended for: https://www.transfermarkt.com/pavel-hajek/profil/spieler/633571.
Transfer history data appended for: https://www.transfermarkt.com/emmanuel-antwi/profil/spieler/360712.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-vavra/profil/spieler/227624.
Transfer history data appended for: https://www.transfermarkt.com/chris-cortez/profil/spieler/187149.
Transfer history data appended for: https://www.transfermarkt.com/adam-petrak/profil/spieler/709285.
Transfer history data appended for: https://www.transfermarkt.com/martin-novy/profil/spieler/331570.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-koci/profil/spieler/366951.
Transfer history data appended for: https://www.transfermarkt.com/mihailo-cmiljanovic/profil/spieler/222214.
Transfer history data appended for: https://www.transfermarkt.com/jonas-vais/profil/spieler/503965.
Transfer history data appended for: https://www.transfermarkt.com/filip-zorvan/profil/spieler/297680.
Transfer history data appended for: https://www.transfermarkt.com/karel-soldat/profil/spieler/306230.
Transfer history data appended for: https://www.transfermarkt.com/jan-rezek/profil/spieler/15890.
Transfer history data appended for: https://www.transfermarkt.com/jan-kvida/profil/spieler/180547.
Transfer history data appended for: https://www.transfermarkt.com/jaroslav-tregler/profil/spieler/289160.
Transfer history data appended for: https://www.transfermarkt.com/olivier-kingue/profil/spieler/398807.
Transfer history data appended for: https://www.transfermarkt.com/peter-klescik/profil/spieler/74712.
Transfer history data appended for: https://www.transfermarkt.com/idrissa-diarra/profil/spieler/603660.
Transfer history data appended for: https://www.transfermarkt.com/vaclav-svoboda/profil/spieler/358136.
Transfer history data appended for: https://www.transfermarkt.com/dusan-pinc/profil/spieler/615266.
Transfer history data appended for: https://www.transfermarkt.com/martin-jindracek/profil/spieler/88752.
Transfer history data appended for: https://www.transfermarkt.com/jan-dil/profil/spieler/450426.
Transfer history data appended for: https://www.transfermarkt.com/jakub-siman/profil/spieler/198612.
Transfer history data appended for: https://www.transfermarkt.com/tomas-pilik/profil/spieler/35179.
Transfer history data appended for: https://www.transfermarkt.com/martin-melichar/profil/spieler/665431.
Transfer history data appended for: https://www.transfermarkt.com/isaac-boakye/profil/spieler/443559.
Transfer history data appended for: https://www.transfermarkt.com/radek-voltr/profil/spieler/113159.
Transfer history data appended for: https://www.transfermarkt.com/ales-mandous/profil/spieler/240536.
Transfer history data appended for: https://www.transfermarkt.com/florent-poulolo/profil/spieler/600151.
Transfer history data appended for: https://www.transfermarkt.com/pablo-gonzalez/profil/spieler/215457.
Transfer history data appended for: https://www.transfermarkt.com/michal-veprek/profil/spieler/64004.
Transfer history data appended for: https://www.transfermarkt.com/ondrej-zmrzly/profil/spieler/343558.
Transfer history data appended for: https://www.transfermarkt.com/jan-kotouc/profil/spieler/516557.
Transfer history data appended for: https://www.transfermarkt.com/jakub-trefil/profil/spieler/580157.
Transfer history data appended for: https://www.transfermarkt.com/radim-breite/profil/spieler/94172.
Transfer history data appended for: https://www.transfermarkt.com/radek-latal/profil/spieler/433834.
Transfer history data appended for: https://www.transfermarkt.com/simon-falta/profil/spieler/206919.

Transfer history data appended for: https://www.transfermarkt.com/dominik-radic/profil/spieler/287043.
Transfer history data appended for: https://www.transfermarkt.com/tomas-zahradnicek/profil/spieler/314836.
Transfer history data appended for: https://www.transfermarkt.com/martin-nespor/profil/spieler/116183.
Transfer history data appended for: https://www.transfermarkt.com/pavel-zifcak/profil/spieler/503966.
Transfer history data appended for: https://www.transfermarkt.com/michal-reichl/profil/spieler/262704.
Transfer history data appended for: https://www.transfermarkt.com/milan-kerbr/profil/spieler/82143.
Transfer history data appended for: https://www.transfermarkt.com/vit-benes/profil/spieler/62973.
Transfer history data appended for: https://www.transfermarkt.com/lukas-gressak/profil/spieler/80903.
Transfer history data appended for: https://www.transfermarkt.com/martin-sladky/profil/spieler/163319.
Transfer history data appended for: https://www.transfermarkt.com/krystof-danek/profil/spieler/652047.
Transfer history data appended for: https://www.transfermarkt.com/jan-sterba/profil/spieler/147556.
Transfer history data appended for: https://www.transfermarkt.com/jachym-sip/profil/spieler/622254.
Transfer history data appended for: https://www.transfermarkt.com/jakub-yunis/profil/spieler/283636.
Transfer history data appended for: https://www.transfermarkt.com/martin-hala/profil/spieler/146711.
Transfer history data appended for: https://www.transfermarkt.com/mojmir-chytil/profil/spieler/405855.
Transfer history data appended for: https://www.transfermarkt.com/david-houska/profil/spieler/206926.
Transfer history data appended for: https://www.transfermarkt.com/jan-schaffartzik/profil/spieler/120083.
Transfer history data appended for: https://www.transfermarkt.com/vojtech-srom/profil/spieler/70647.
Transfer history data appended for: https://www.transfermarkt.com/bartosz-pikul/profil/spieler/337520.
Transfer history data appended for: https://www.transfermarkt.com/rene-dedic/profil/spieler/316289.
Transfer history data appended for: https://www.transfermarkt.com/pavel-zavadil/profil/spieler/22060.
Transfer history data appended for: https://www.transfermarkt.com/jan-reznicek/profil/spieler/235202.
Transfer history data appended for: https://www.transfermarkt.com/bojan-djordjic/profil/spieler/202745.
Transfer history data appended for: https://www.transfermarkt.com/krystof-lasak/profil/spieler/384369.
Transfer history data appended for: https://www.transfermarkt.com/christ-tiehi/profil/spieler/571821.
Transfer history data appended for: https://www.transfermarkt.com/jan-zidek/profil/spieler/280146.
Transfer history data appended for: https://www.transfermarkt.com/lukas-zeleznik/profil/spieler/70202.
Transfer history data appended for: https://www.transfermarkt.com/bidje-manzia/profil/spieler/256086.
Transfer history data appended for: https://www.transfermarkt.com/karol-mondek/profil/spieler/192738.
Transfer history data appended for: https://www.transfermarkt.com/josef-hnanicek/profil/spieler/180558.
Transfer history data appended for: https://www.transfermarkt.com/jiri-texl/profil/spieler/331694.
Transfer history data appended for: https://www.transfermarkt.com/vaclav-jurena/profil/spieler/225171.
Transfer history data appended for: https://www.transfermarkt.com/lukas-holik/profil/spieler/204280.
Transfer history data appended for: https://www.transfermarkt.com/joss-didiba/profil/spieler/395107.
Transfer history data appended for: https://www.transfermarkt.com/matej-hrabina/profil/spieler/195552.
Transfer history data appended for: https://www.transfermarkt.com/adam-rychly/profil/spieler/537098.
Transfer history data appended for: https://www.transfermarkt.com/dalibor-vecerka/profil/spieler/728626.
Transfer history data appended for: https://www.transfermarkt.com/matej-helesic/profil/spieler/292514.
Transfer history data appended for: https://www.transfermarkt.com/stepan-harazim/profil/spieler/730415.
Transfer history data appended for: https://www.transfermarkt.com/denis-darmovzal/profil/spieler/706793.
Transfer history data appended for: https://www.transfermarkt.com/vilem-fendrich/profil/spieler/163353.
Transfer history data appended for: https://www.transfermarkt.com/dominik-smekal/profil/spieler/293368.
Transfer history data appended for: https://www.transfermarkt.com/hamdan-al-kamali/profil/spieler/107397.
Transfer history data appended for: https://www.transfermarkt.com/saoud-abdulrazaq/profil/spieler/482995.
Transfer history data appended for: https://www.transfermarkt.com/aziz-ganiev/profil/spieler/431911.
Transfer history data appended for: https://www.transfermarkt.com/saeed-ahmad/profil/spieler/322981.
Transfer history data appended for: https://www.transfermarkt.com/majed-naser/profil/spieler/68738.
Transfer history data appended for: https://www.transfermarkt.com/saif-yousuf/profil/spieler/114066.
Transfer history data appended for: https://www.transfermarkt.com/walid-abbas/profil/spieler/90161.
Transfer history data appended for: https://www.transfermarkt.com/waled-husain/profil/spieler/131944.
Transfer history data appended for: https://www.transfermarkt.com/mohammad-juma-al-balooshi/profil/spieler/421313.
Transfer history data appended for: https://www.transfermarkt.com/eid-khamis-alnuaimi/profil/spieler/575700.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-hussain/profil/spieler/114154.
Transfer history data appended for: https://www.transfermarkt.com/majed-hassan/profil/spieler/131945.
Transfer history data appended for: https://www.transfermarkt.com/hassan-hamza/profil/spieler/225801.
Transfer history data appended for: https://www.transfermarkt.com/carlos-eduardo/profil/spieler/110078.
Transfer history data appended for: https://www.transfermarkt.com/igor-jesus/profil/spieler/432164.
Transfer history data appended for: https://www.transfermarkt.com/yousef-jaber/profil/spieler/90164.
Transfer history data appended for: https://www.transfermarkt.com/abdalla-al-naqbi/profil/spieler/323135.
Transfer history data appended for: https://www.transfermarkt.com/ismail-al-hammadi/profil/spieler/86285.
Transfer history data appended for: https://www.transfermarkt.com/fede-cartabia/profil/spieler/242548.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-abdulla-jamil/profil/spieler/630140.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-khalil/profil/spieler/68754.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-jaber/profil/spieler/222821.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-attas/profil/spieler/320261.
Transfer history data appended for: https://www.transfermarkt.com/leonardo/profil/spieler/241163.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-marzooq/profil/spieler/128334.
Transfer history data appended for: https://www.transfermarkt.com/pedro-conde/profil/spieler/96089.
Transfer history data appended for: https://www.transfermarkt.com/adeel-alchadli/profil/spieler/523000.
Transfer history data appended for: https://www.transfermarkt.com/abdelaziz-sanqour/profil/spieler/114157.
Transfer history data appended for: https://www.transfermarkt.com/harib-suhail/profil/spieler/706533.
Transfer history data appended for: https://www.transfermarkt.com/salmin-khamis/profil/spieler/172690.
Transfer history data appended for: https://www.transfermarkt.com/leandro-spadacio/profil/spieler/826278.
Transfer history data appended for: https://www.transfermarkt.com/heldon/profil/spieler/90660.
Transfer history data appended for: https://www.transfermarkt.com/diogo-amado/profil/spieler/72835.
Transfer history data appended for: https://www.transfermarkt.com/saoud-saeed/profil/spieler/128335.
Transfer history data appended for: https://www.transfermarkt.com/ismaeil-ahmed/profil/spieler/272387.
Transfer history data appended for: https://www.transfermarkt.com/yousuf-ahmed/profil/spieler/272372.
Transfer history data appended for: https://www.transfermarkt.com/gustavo/profil/spieler/268223.
Transfer history data appended for: https://www.transfermarkt.com/guilherme-barbosa/profil/spieler/606432.

Transfer history data appended for: https://www.transfermarkt.com/rashed-malallah/profil/spieler/261038.
Transfer history data appended for: https://www.transfermarkt.com/saad-surour/profil/spieler/114070.
Transfer history data appended for: https://www.transfermarkt.com/bubacarr-trawally/profil/spieler/353112.
Transfer history data appended for: https://www.transfermarkt.com/sulaiman-nasser-alameri/profil/spieler/501549.
Transfer history data appended for: https://www.transfermarkt.com/hussain-abdulrahman/profil/spieler/539360.
Transfer history data appended for: https://www.transfermarkt.com/hassan-zahran/profil/spieler/268890.
Transfer history data appended for: https://www.transfermarkt.com/hamad-khalid-ali/profil/spieler/539364.
Transfer history data appended for: https://www.transfermarkt.com/yousif-mohamed-yousif/profil/spieler/269917.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-mohammed/profil/spieler/374112.
Transfer history data appended for: https://www.transfermarkt.com/darlington-emmanuel-igwekali/profil/spieler/638313.
Transfer history data appended for: https://www.transfermarkt.com/humaid-abdalla-saleh/profil/spieler/428371.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-antaly/profil/spieler/268461.
Transfer history data appended for: https://www.transfermarkt.com/waleid-al-yammahi/profil/spieler/427846.
Transfer history data appended for: https://www.transfermarkt.com/rashed-hassan/profil/spieler/224213.
Transfer history data appended for: https://www.transfermarkt.com/hasan-abdulrahman/profil/spieler/269898.
Transfer history data appended for: https://www.transfermarkt.com/william-owusu-acheampong/profil/spieler/45347.
Transfer history data appended for: https://www.transfermarkt.com/mohammad-yaqoob/profil/spieler/269612.
Transfer history data appended for: https://www.transfermarkt.com/waheed-ismail/profil/spieler/269181.
Transfer history data appended for: https://www.transfermarkt.com/abdalla-saleh/profil/spieler/269648.
Transfer history data appended for: https://www.transfermarkt.com/abdulla-al-jamhi/profil/spieler/268972.
Transfer history data appended for: https://www.transfermarkt.com/abdulla-malallah/profil/spieler/68760.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-ibrahim/profil/spieler/272374.
Transfer history data appended for: https://www.transfermarkt.com/khaled-khalfan-zayed/profil/spieler/433812.
Transfer history data appended for: https://www.transfermarkt.com/rashid-al-hajri/profil/spieler/269618.
Transfer history data appended for: https://www.transfermarkt.com/mohammad-sarwashi/profil/spieler/562098.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-salem/profil/spieler/322968.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-hosani/profil/spieler/185495.
Transfer history data appended for: https://www.transfermarkt.com/khaled-nasser-al-rezzi/profil/spieler/614939.
Transfer history data appended for: https://www.transfermarkt.com/khaled-khalfan/profil/spieler/295281.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-ismail/profil/spieler/269907.
Transfer history data appended for: https://www.transfermarkt.com/anouar-el-mhassani/profil/spieler/533465.
Transfer history data appended for: https://www.transfermarkt.com/walid-khalid/profil/spieler/272389.
Transfer history data appended for: https://www.transfermarkt.com/oumar-traore/profil/spieler/639431.
Transfer history data appended for: https://www.transfermarkt.com/ali-mabkhout/profil/spieler/114150.
Transfer history data appended for: https://www.transfermarkt.com/saif-khalfan/profil/spieler/261465.
Transfer history data appended for: https://www.transfermarkt.com/bruno/profil/spieler/718649.
Transfer history data appended for: https://www.transfermarkt.com/ali-khaseif/profil/spieler/107426.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-obaid-alabdoli/profil/spieler/423961.
Transfer history data appended for: https://www.transfermarkt.com/rakaan-almenhali/profil/spieler/799405.
Transfer history data appended for: https://www.transfermarkt.com/omar-abdulrahman/profil/spieler/114149.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-rabii/profil/spieler/729938.
Transfer history data appended for: https://www.transfermarkt.com/bader-al-shabibi/profil/spieler/511641.
Transfer history data appended for: https://www.transfermarkt.com/abdullrahman-al-ameri/profil/spieler/539358.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-omar-al-attas/profil/spieler/485863.
Transfer history data appended for: https://www.transfermarkt.com/khalfan-mubarak/profil/spieler/353259.
Transfer history data appended for: https://www.transfermarkt.com/adel-abu-baker-hussain-mohamed-fadaq/profil/spieler/429879.
Transfer history data appended for: https://www.transfermarkt.com/amer-abdulrahman/profil/spieler/128336.
Transfer history data appended for: https://www.transfermarkt.com/zayed-al-ameri/profil/spieler/295541.
Transfer history data appended for: https://www.transfermarkt.com/khalifa-alhammadi/profil/spieler/555541.
Transfer history data appended for: https://www.transfermarkt.com/salem-abdulla/profil/spieler/113751.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-ghilani/profil/spieler/314839.
Transfer history data appended for: https://www.transfermarkt.com/faisal-al-martoushi/profil/spieler/706530.
Transfer history data appended for: https://www.transfermarkt.com/thulani-serero/profil/spieler/109881.
Transfer history data appended for: https://www.transfermarkt.com/milos-kosanovic/profil/spieler/65521.
Transfer history data appended for: https://www.transfermarkt.com/renner/profil/spieler/687589.
Transfer history data appended for: https://www.transfermarkt.com/fawaz-awana/profil/spieler/222803.
Transfer history data appended for: https://www.transfermarkt.com/majed-abdulla/profil/spieler/664061.
Transfer history data appended for: https://www.transfermarkt.com/suhail-al-noobi/profil/spieler/295544.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-alhammadi/profil/spieler/485778.
Transfer history data appended for: https://www.transfermarkt.com/saile/profil/spieler/717661.
Transfer history data appended for: https://www.transfermarkt.com/gaston-alvarez-suarez/profil/spieler/213191.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-helal-rashed/profil/spieler/582231.
Transfer history data appended for: https://www.transfermarkt.com/george-tibar/profil/spieler/660242.
Transfer history data appended for: https://www.transfermarkt.com/hussain-abbas-juma/profil/spieler/423779.
Transfer history data appended for: https://www.transfermarkt.com/sultan-al-shamsi/profil/spieler/295545.
Transfer history data appended for: https://www.transfermarkt.com/omran-hassan-beero-mohammed-alraeesi/profil/spieler/687226.
Transfer history data appended for: https://www.transfermarkt.com/shahin-surour-al-dermaki/profil/spieler/423962.
Transfer history data appended for: https://www.transfermarkt.com/sasa-ivkovic/profil/spieler/189100.
Transfer history data appended for: https://www.transfermarkt.com/ali-awana-almessabi/profil/spieler/656315.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-zaabi/profil/spieler/709438.
Transfer history data appended for: https://www.transfermarkt.com/nicolas-gimenez/profil/spieler/364946.
Transfer history data appended for: https://www.transfermarkt.com/eisa-ali-abass/profil/spieler/547171.
Transfer history data appended for: https://www.transfermarkt.com/sultan-husain-alehremi/profil/spieler/438989.
Transfer history data appended for: https://www.transfermarkt.com/salim-al-mamari/profil/spieler/673442.
Transfer history data appended for: https://www.transfermarkt.com/luis-cerejo/profil/spieler/686473.
Transfer history data appended for: https://www.transfermarkt.com/nahyan-saleh-saeed-salem-almenhali/profil/spieler/687224.
Transfer history data appended for: https://www.transfermarkt.com/salem-abdulla-rashed-abdullah-al-baloushi/profil/spieler/687220.

Transfer history data appended for: https://www.transfermarkt.com/eissa-al-otaiba/profil/spieler/501548.
Transfer history data appended for: https://www.transfermarkt.com/hamad-al-ahbabi/profil/spieler/268889.
Transfer history data appended for: https://www.transfermarkt.com/ahmad-malalla/profil/spieler/268826.
Transfer history data appended for: https://www.transfermarkt.com/joao-pedro/profil/spieler/293471.
Transfer history data appended for: https://www.transfermarkt.com/khamis-saleh-ismaiel-khalil-alhammadi/profil/spieler/687221.
Transfer history data appended for: https://www.transfermarkt.com/fahad-mohamed/profil/spieler/358758.
Transfer history data appended for: https://www.transfermarkt.com/khamis-saleh-ismaiel/profil/spieler/438980.
Transfer history data appended for: https://www.transfermarkt.com/saif-hussein-mohammed-said-al-balushi/profil/spieler/687223.
Transfer history data appended for: https://www.transfermarkt.com/joao-victor/profil/spieler/687218.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-saif-mohamed-hamad-alzar-al-shamsi/profil/spieler/432325.
Transfer history data appended for: https://www.transfermarkt.com/mohammad-abdulbasit/profil/spieler/322699.
Transfer history data appended for: https://www.transfermarkt.com/caio/profil/spieler/308441.
Transfer history data appended for: https://www.transfermarkt.com/ali-aldhanhani/profil/spieler/428216.
Transfer history data appended for: https://www.transfermarkt.com/igor-coronado/profil/spieler/215915.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-bin-habib/profil/spieler/712022.
Transfer history data appended for: https://www.transfermarkt.com/khaled-ebraheim/profil/spieler/485782.
Transfer history data appended for: https://www.transfermarkt.com/abdoulaye-traore/profil/spieler/398275.
Transfer history data appended for: https://www.transfermarkt.com/gustavo/profil/spieler/735574.
Transfer history data appended for: https://www.transfermarkt.com/mayed-muhsin/profil/spieler/482993.
Transfer history data appended for: https://www.transfermarkt.com/khalid-abdulraheem-mohamed-bawazir/profil/spieler/428220.
Transfer history data appended for: https://www.transfermarkt.com/otabek-shukurov/profil/spieler/294525.
Transfer history data appended for: https://www.transfermarkt.com/salem-saleh/profil/spieler/148178.
Transfer history data appended for: https://www.transfermarkt.com/adel-al-hosani/profil/spieler/171887.
Transfer history data appended for: https://www.transfermarkt.com/alhusain-saleh/profil/spieler/323545.
Transfer history data appended for: https://www.transfermarkt.com/tareq-ahmed/profil/spieler/268812.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-khalfan-ali/profil/spieler/427863.
Transfer history data appended for: https://www.transfermarkt.com/caio-rosa/profil/spieler/739437.
Transfer history data appended for: https://www.transfermarkt.com/abdelaziz-salim-ali/profil/spieler/562085.
Transfer history data appended for: https://www.transfermarkt.com/hamad-jasim/profil/spieler/508105.
Transfer history data appended for: https://www.transfermarkt.com/yousif-saeed/profil/spieler/261423.
Transfer history data appended for: https://www.transfermarkt.com/luan-pereira/profil/spieler/527394.
Transfer history data appended for: https://www.transfermarkt.com/majed-suroor/profil/spieler/430277.
Transfer history data appended for: https://www.transfermarkt.com/abdalla-yousif-abdalla/profil/spieler/428405.
Transfer history data appended for: https://www.transfermarkt.com/marcus-meloni/profil/spieler/709443.
Transfer history data appended for: https://www.transfermarkt.com/salem-sultan/profil/spieler/428222.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-al-karbi/profil/spieler/485779.
Transfer history data appended for: https://www.transfermarkt.com/manei-mohamed/profil/spieler/260855.
Transfer history data appended for: https://www.transfermarkt.com/rashed-ali/profil/spieler/269175.
Transfer history data appended for: https://www.transfermarkt.com/khalil-ibrahim-al-hammadi/profil/spieler/431780.
Transfer history data appended for: https://www.transfermarkt.com/tahnoon-alzaabi/profil/spieler/630160.
Transfer history data appended for: https://www.transfermarkt.com/khamis-esmaeel/profil/spieler/185014.
Transfer history data appended for: https://www.transfermarkt.com/gian/profil/spieler/824729.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-menhali/profil/spieler/185016.
Transfer history data appended for: https://www.transfermarkt.com/luvannor/profil/spieler/192701.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-shamsi/profil/spieler/295277.
Transfer history data appended for: https://www.transfermarkt.com/rashed-muhayer/profil/spieler/378702.
Transfer history data appended for: https://www.transfermarkt.com/yahya-alghassani/profil/spieler/614840.
Transfer history data appended for: https://www.transfermarkt.com/lucas-pimenta/profil/spieler/681120.
Transfer history data appended for: https://www.transfermarkt.com/ismaeil-matar/profil/spieler/37927.
Transfer history data appended for: https://www.transfermarkt.com/ruben-amaral/profil/spieler/624826.
Transfer history data appended for: https://www.transfermarkt.com/myung-joo-lee/profil/spieler/217569.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-rashid/profil/spieler/295283.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-ali-alebri/profil/spieler/128374.
Transfer history data appended for: https://www.transfermarkt.com/alaeddine-zouhir/profil/spieler/634697.
Transfer history data appended for: https://www.transfermarkt.com/mansor-al-harbi/profil/spieler/630159.
Transfer history data appended for: https://www.transfermarkt.com/fares-juma/profil/spieler/57588.
Transfer history data appended for: https://www.transfermarkt.com/ismail-ahmed/profil/spieler/148017.
Transfer history data appended for: https://www.transfermarkt.com/omar-yaisien/profil/spieler/536481.
Transfer history data appended for: https://www.transfermarkt.com/erik/profil/spieler/680551.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-hilal-khalifa/profil/spieler/513825.
Transfer history data appended for: https://www.transfermarkt.com/andrija-radovanovic/profil/spieler/699200.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-khalfan-zayed-barout-al-harasi/profil/spieler/651487.
Transfer history data appended for: https://www.transfermarkt.com/kodjo-fo-doh-laba/profil/spieler/425973.
Transfer history data appended for: https://www.transfermarkt.com/jamal-ibrahim-hassain/profil/spieler/223418.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-abdulrahman/profil/spieler/148016.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-ahmad/profil/spieler/114164.
Transfer history data appended for: https://www.transfermarkt.com/ali-saeed-al-blooshi/profil/spieler/817683.
Transfer history data appended for: https://www.transfermarkt.com/rayan-yaslam/profil/spieler/372590.
Transfer history data appended for: https://www.transfermarkt.com/bandar-mohamed/profil/spieler/185650.
Transfer history data appended for: https://www.transfermarkt.com/mohsen-abdullah/profil/spieler/433811.
Transfer history data appended for: https://www.transfermarkt.com/hamad-abdulla-nasser/profil/spieler/584542.
Transfer history data appended for: https://www.transfermarkt.com/saeed-juma-hassan/profil/spieler/505211.
Transfer history data appended for: https://www.transfermarkt.com/caio-canedo/profil/spieler/140952.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-diaky/profil/spieler/147873.
Transfer history data appended for: https://www.transfermarkt.com/saad-khamis-saad-mubarak-al-abadla/profil/spieler/431785.
Transfer history data appended for: https://www.transfermarkt.com/khalid-eisa/profil/spieler/147871.
Transfer history data appended for: https://www.transfermarkt.com/tsukasa-shiotani/profil/spieler/177521.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-jamal/profil/spieler/430465.

Transfer history data appended for: https://www.transfermarkt.com/yahia-nader/profil/spieler/614835.
Transfer history data appended for: https://www.transfermarkt.com/rafael-pereira/profil/spieler/742834.
Transfer history data appended for: https://www.transfermarkt.com/fahad-hadeed/profil/spieler/131952.
Transfer history data appended for: https://www.transfermarkt.com/bauyrzhan-islamkhan/profil/spieler/198780.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-ali-shakir/profil/spieler/539362.
Transfer history data appended for: https://www.transfermarkt.com/ibraheem-al-kaabi/profil/spieler/431615.
Transfer history data appended for: https://www.transfermarkt.com/dawoud-sulaiman/profil/spieler/185641.
Transfer history data appended for: https://www.transfermarkt.com/khaled-abdulla-mobarak-ali-al-blooshi/profil/spieler/614902.
Transfer history data appended for: https://www.transfermarkt.com/samuel-armenteros/profil/spieler/55751.
Transfer history data appended for: https://www.transfermarkt.com/ali-eid-ghumail/profil/spieler/489761.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-moosa-saqer-murad/profil/spieler/482994.
Transfer history data appended for: https://www.transfermarkt.com/rashid-jalal/profil/spieler/261418.
Transfer history data appended for: https://www.transfermarkt.com/helal-saeed/profil/spieler/148032.
Transfer history data appended for: https://www.transfermarkt.com/alvaro-de-oliveira/profil/spieler/832072.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-aqeel/profil/spieler/614941.
Transfer history data appended for: https://www.transfermarkt.com/salem-obaid/profil/spieler/268137.
Transfer history data appended for: https://www.transfermarkt.com/ismail-al-tamim/profil/spieler/619612.
Transfer history data appended for: https://www.transfermarkt.com/abdallah-saeed-salem/profil/spieler/471652.
Transfer history data appended for: https://www.transfermarkt.com/roly-bonevacia/profil/spieler/124885.
Transfer history data appended for: https://www.transfermarkt.com/abdulazeez-muftau-owolabi/profil/spieler/494626.
Transfer history data appended for: https://www.transfermarkt.com/hamdan-naser-masoud/profil/spieler/430551.
Transfer history data appended for: https://www.transfermarkt.com/aymen-assou/profil/spieler/536509.
Transfer history data appended for: https://www.transfermarkt.com/faisal-yousef-saqer/profil/spieler/569855.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-bairaq/profil/spieler/619619.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-salem/profil/spieler/185640.
Transfer history data appended for: https://www.transfermarkt.com/abdulla-hassan-khalfan-alnoubi/profil/spieler/487351.
Transfer history data appended for: https://www.transfermarkt.com/aboubacar-kone/profil/spieler/409500.
Transfer history data appended for: https://www.transfermarkt.com/yaser-salem/profil/spieler/269177.
Transfer history data appended for: https://www.transfermarkt.com/humaid-ahmed/profil/spieler/261035.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-mustafa/profil/spieler/826049.
Transfer history data appended for: https://www.transfermarkt.com/abdulla-wahdani/profil/spieler/672645.
Transfer history data appended for: https://www.transfermarkt.com/farley-rosa/profil/spieler/197622.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-mallah/profil/spieler/269908.
Transfer history data appended for: https://www.transfermarkt.com/khaleil-khameis-salem/profil/spieler/427856.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-saeed-mohamed/profil/spieler/268941.
Transfer history data appended for: https://www.transfermarkt.com/hussein-abdullah/profil/spieler/606465.
Transfer history data appended for: https://www.transfermarkt.com/ryan-mendes/profil/spieler/111627.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-fawzi/profil/spieler/114065.
Transfer history data appended for: https://www.transfermarkt.com/tariq-ahmed/profil/spieler/147883.
Transfer history data appended for: https://www.transfermarkt.com/hussain-mahdi-mohammed/profil/spieler/562099.
Transfer history data appended for: https://www.transfermarkt.com/habib-al-fardan/profil/spieler/114155.
Transfer history data appended for: https://www.transfermarkt.com/khalifa-mubarak/profil/spieler/261036.
Transfer history data appended for: https://www.transfermarkt.com/caique/profil/spieler/669535.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-ibrahim-saleh/profil/spieler/508108.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-ali-ayed/profil/spieler/150785.
Transfer history data appended for: https://www.transfermarkt.com/toze/profil/spieler/203654.
Transfer history data appended for: https://www.transfermarkt.com/sebastian-tagliabue/profil/spieler/89771.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-essa-ali/profil/spieler/430929.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-yousuf/profil/spieler/131956.
Transfer history data appended for: https://www.transfermarkt.com/mahmoud-al-hammadi/profil/spieler/107425.
Transfer history data appended for: https://www.transfermarkt.com/yacob-hassan-mohamed/profil/spieler/430553.
Transfer history data appended for: https://www.transfermarkt.com/mohanad-khamis-obaid/profil/spieler/711809.
Transfer history data appended for: https://www.transfermarkt.com/brandley-kuwas/profil/spieler/232219.
Transfer history data appended for: https://www.transfermarkt.com/esteban-pavez/profil/spieler/131233.
Transfer history data appended for: https://www.transfermarkt.com/glauber/profil/spieler/658602.
Transfer history data appended for: https://www.transfermarkt.com/juninho/profil/spieler/709448.
Transfer history data appended for: https://www.transfermarkt.com/omar-juma-rabiah/profil/spieler/428406.
Transfer history data appended for: https://www.transfermarkt.com/hazza-salem/profil/spieler/148035.
Transfer history data appended for: https://www.transfermarkt.com/saif-mohamed/profil/spieler/68736.
Transfer history data appended for: https://www.transfermarkt.com/salem-aleedi/profil/spieler/539356.
Transfer history data appended for: https://www.transfermarkt.com/ali-hussain/profil/spieler/134872.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-yassi/profil/spieler/268124.
Transfer history data appended for: https://www.transfermarkt.com/darwish-mohamed/profil/spieler/319527.
Transfer history data appended for: https://www.transfermarkt.com/falah-waleed/profil/spieler/671795.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-haboush/profil/spieler/311725.
Transfer history data appended for: https://www.transfermarkt.com/abdulla-malalla/profil/spieler/185564.
Transfer history data appended for: https://www.transfermarkt.com/khalfan-hassan-khalfan-al-noobi-al-hammadi/profil/spieler/575701.
Transfer history data appended for: https://www.transfermarkt.com/adel-sabil-moosa/profil/spieler/485858.
Transfer history data appended for: https://www.transfermarkt.com/pascal-chidi-bolu/profil/spieler/794808.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-mahri/profil/spieler/68737.
Transfer history data appended for: https://www.transfermarkt.com/ahmad-essa-juma/profil/spieler/503669.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-yousef/profil/spieler/324197.
Transfer history data appended for: https://www.transfermarkt.com/kouame-autonne-kouadio/profil/spieler/718648.
Transfer history data appended for: https://www.transfermarkt.com/obeid-thani-bilal-raihan/profil/spieler/463859.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-hefeiti-al-hefeiti/profil/spieler/614904.
Transfer history data appended for: https://www.transfermarkt.com/rashed-essa/profil/spieler/251257.
Transfer history data appended for: https://www.transfermarkt.com/ramon-lopes/profil/spieler/104351.
Transfer history data appended for: https://www.transfermarkt.com/salim-ali-ibrahim/profil/spieler/260856.

Transfer history data appended for: https://www.transfermarkt.com/abdelqader-ali-qambar-hassan-abdalla/profil/spieler/431779.
Transfer history data appended for: https://www.transfermarkt.com/khalid-jalal/profil/spieler/172187.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-eisa/profil/spieler/269616.
Transfer history data appended for: https://www.transfermarkt.com/adel/profil/spieler/485520.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-malallah/profil/spieler/268981.
Transfer history data appended for: https://www.transfermarkt.com/fawzi-fayez/profil/spieler/148024.
Transfer history data appended for: https://www.transfermarkt.com/amir-mubarak-al-hammadi/profil/spieler/90163.
Transfer history data appended for: https://www.transfermarkt.com/waleed-sirag/profil/spieler/619621.
Transfer history data appended for: https://www.transfermarkt.com/hassan-ameen/profil/spieler/148145.
Transfer history data appended for: https://www.transfermarkt.com/khalid-ghuloom/profil/spieler/829871.
Transfer history data appended for: https://www.transfermarkt.com/abdulaziz-ismail/profil/spieler/268931.
Transfer history data appended for: https://www.transfermarkt.com/dodo/profil/spieler/281837.
Transfer history data appended for: https://www.transfermarkt.com/bader-al-attas/profil/spieler/449709.
Transfer history data appended for: https://www.transfermarkt.com/faysal-yousif-murad/profil/spieler/482992.
Transfer history data appended for: https://www.transfermarkt.com/khalid-ali-khamis/profil/spieler/268933.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-al-hammadi/profil/spieler/423964.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-ali-mubarak/profil/spieler/485783.
Transfer history data appended for: https://www.transfermarkt.com/saeed-ali-rawahi/profil/spieler/511640.
Transfer history data appended for: https://www.transfermarkt.com/denilson/profil/spieler/271498.
Transfer history data appended for: https://www.transfermarkt.com/amran-al-jassasi/profil/spieler/567508.
Transfer history data appended for: https://www.transfermarkt.com/masoud-sulaiman/profil/spieler/423778.
Transfer history data appended for: https://www.transfermarkt.com/ismael-al-harbi/profil/spieler/735070.
Transfer history data appended for: https://www.transfermarkt.com/khaled-saif-al-senani/profil/spieler/153835.
Transfer history data appended for: https://www.transfermarkt.com/saeed-al-kathiri/profil/spieler/148142.
Transfer history data appended for: https://www.transfermarkt.com/musallem-fayez/profil/spieler/148018.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-yslam/profil/spieler/470523.
Transfer history data appended for: https://www.transfermarkt.com/sultan-al-ghafri/profil/spieler/151692.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-saif/profil/spieler/323759.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-ayim/profil/spieler/450820.
Transfer history data appended for: https://www.transfermarkt.com/mikhail-rosheuvel/profil/spieler/64507.
Transfer history data appended for: https://www.transfermarkt.com/ali-al-amir/profil/spieler/220838.
Transfer history data appended for: https://www.transfermarkt.com/daouda-toure/profil/spieler/656955.
Transfer history data appended for: https://www.transfermarkt.com/khalid-butti/profil/spieler/185018.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-mahmoud-hasan-ahmed-alhammadi/profil/spieler/706855.
Transfer history data appended for: https://www.transfermarkt.com/idriss-mzaouiyani/profil/spieler/536483.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-aljneibi/profil/spieler/670750.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-mohamed-yaslam-aboud-balfaqaih/profil/spieler/687222.
Transfer history data appended for: https://www.transfermarkt.com/abdulla-sultan/profil/spieler/148037.
Transfer history data appended for: https://www.transfermarkt.com/badr-al-harthi/profil/spieler/428221.
Transfer history data appended for: https://www.transfermarkt.com/suhail-salem/profil/spieler/358756.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-saeed-masoud/profil/spieler/222835.
Transfer history data appended for: https://www.transfermarkt.com/sultan-al-suwaidi/profil/spieler/268998.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-mahmoud/profil/spieler/824733.
Transfer history data appended for: https://www.transfermarkt.com/yaseen-al-bakhit/profil/spieler/229864.
Transfer history data appended for: https://www.transfermarkt.com/issam-el-adoua/profil/spieler/64992.
Transfer history data appended for: https://www.transfermarkt.com/suhail-abdulla/profil/spieler/541479.
Transfer history data appended for: https://www.transfermarkt.com/nasser-mahmoud-noor/profil/spieler/619628.
Transfer history data appended for: https://www.transfermarkt.com/hassan-mohammed/profil/spieler/261039.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-surour/profil/spieler/324180.
Transfer history data appended for: https://www.transfermarkt.com/ali-saleh/profil/spieler/430855.
Transfer history data appended for: https://www.transfermarkt.com/khalid-tariq/profil/spieler/261490.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-saleh-radi-rida-khamis/profil/spieler/575706.
Transfer history data appended for: https://www.transfermarkt.com/abdulrahman-ali/profil/spieler/428381.
Transfer history data appended for: https://www.transfermarkt.com/neris/profil/spieler/349513.
Transfer history data appended for: https://www.transfermarkt.com/haboosh-saleh/profil/spieler/222814.
Transfer history data appended for: https://www.transfermarkt.com/yousif-ali-almheiri/profil/spieler/630142.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-sebil/profil/spieler/131953.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-al-shamisi/profil/spieler/148014.
Transfer history data appended for: https://www.transfermarkt.com/khalid-al-shaibani/profil/spieler/427866.
Transfer history data appended for: https://www.transfermarkt.com/yousef-ahmed/profil/spieler/261448.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-ali-suwaidan/profil/spieler/582255.
Transfer history data appended for: https://www.transfermarkt.com/fabio-lima/profil/spieler/179054.
Transfer history data appended for: https://www.transfermarkt.com/faris-khalil/profil/spieler/574406.
Transfer history data appended for: https://www.transfermarkt.com/ghanem-ahmed/profil/spieler/753628.
Transfer history data appended for: https://www.transfermarkt.com/george-dwubeng/profil/spieler/579635.
Transfer history data appended for: https://www.transfermarkt.com/natan-felipe/profil/spieler/709859.
Transfer history data appended for: https://www.transfermarkt.com/matheus/profil/spieler/656524.
Transfer history data appended for: https://www.transfermarkt.com/joao-figueiredo/profil/spieler/439343.
Transfer history data appended for: https://www.transfermarkt.com/ali-salmin/profil/spieler/269649.
Transfer history data appended for: https://www.transfermarkt.com/ali-abdulla-ali-alabdulla-al-ansari/profil/spieler/574405.
Transfer history data appended for: https://www.transfermarkt.com/hassan-ibrahim/profil/spieler/223640.
Transfer history data appended for: https://www.transfermarkt.com/ronaldo-mendes/profil/spieler/236952.
Transfer history data appended for: https://www.transfermarkt.com/humaid-abdulla/profil/spieler/268857.
Transfer history data appended for: https://www.transfermarkt.com/ahmad-nasser-bahrooz-saqer/profil/spieler/427870.
Transfer history data appended for: https://www.transfermarkt.com/salem-juma-awad/profil/spieler/359763.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-akberi/profil/spieler/295540.
Transfer history data appended for: https://www.transfermarkt.com/waleed-al-hamadi/profil/spieler/626145.
Transfer history data appended for: https://www.transfermarkt.com/khalid-sebil/profil/spieler/149842.

Transfer history data appended for: https://www.transfermarkt.com/abdalla-mohammed/profil/spieler/429812.
Transfer history data appended for: https://www.transfermarkt.com/omar-ahmed-rashed/profil/spieler/428218.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-abdulla-jshak/profil/spieler/620527.
Transfer history data appended for: https://www.transfermarkt.com/mana-saeed-khudoum/profil/spieler/428403.
Transfer history data appended for: https://www.transfermarkt.com/dawood-ali/profil/spieler/223632.
Transfer history data appended for: https://www.transfermarkt.com/davide-mariani/profil/spieler/107790.
Transfer history data appended for: https://www.transfermarkt.com/yousif-abdulla/profil/spieler/134868.
Transfer history data appended for: https://www.transfermarkt.com/yaqoub-yousif/profil/spieler/148241.
Transfer history data appended for: https://www.transfermarkt.com/saeed-musabbeh/profil/spieler/322441.
Transfer history data appended for: https://www.transfermarkt.com/saeed-almarashda/profil/spieler/651482.
Transfer history data appended for: https://www.transfermarkt.com/hassan-yousuf/profil/spieler/131955.
Transfer history data appended for: https://www.transfermarkt.com/khalid-abdulrahman-ali-alblooshi/profil/spieler/687851.
Transfer history data appended for: https://www.transfermarkt.com/ebraheim-khameis/profil/spieler/429809.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-sabeel/profil/spieler/539359.
Transfer history data appended for: https://www.transfermarkt.com/gabriel-santini/profil/spieler/392112.
Transfer history data appended for: https://www.transfermarkt.com/khaled-shamareikh/profil/spieler/430402.
Transfer history data appended for: https://www.transfermarkt.com/wanderson/profil/spieler/214144.
Transfer history data appended for: https://www.transfermarkt.com/fahad-sebil/profil/spieler/114162.
Transfer history data appended for: https://www.transfermarkt.com/rashid-mohamed/profil/spieler/131948.
Transfer history data appended for: https://www.transfermarkt.com/waleed-ambar/profil/spieler/261386.
Transfer history data appended for: https://www.transfermarkt.com/peniel-mlapa/profil/spieler/70280.
Transfer history data appended for: https://www.transfermarkt.com/mohamed-al-shehhi/profil/spieler/68732.
Transfer history data appended for: https://www.transfermarkt.com/mubarak-saeed/profil/spieler/185348.
Transfer history data appended for: https://www.transfermarkt.com/jamal-abdulla-ali/profil/spieler/269899.
Transfer history data appended for: https://www.transfermarkt.com/matheus-barbosa/profil/spieler/724524.
Transfer history data appended for: https://www.transfermarkt.com/willian-forte/profil/spieler/547947.
Transfer history data appended for: https://www.transfermarkt.com/osama-elshaal/profil/spieler/742336.
Transfer history data appended for: https://www.transfermarkt.com/mansour-mohamed/profil/spieler/268921.
Transfer history data appended for: https://www.transfermarkt.com/abdul-salam-mohammed/profil/spieler/320178.
Transfer history data appended for: https://www.transfermarkt.com/nasser-abdulhadi/profil/spieler/374113.
Transfer history data appended for: https://www.transfermarkt.com/yaqoob-yousef/profil/spieler/706525.
Transfer history data appended for: https://www.transfermarkt.com/saqer-mohd-rabie/profil/spieler/470529.
Transfer history data appended for: https://www.transfermarkt.com/ahmed-mahmoud/profil/spieler/128337.
Transfer history data appended for: https://www.transfermarkt.com/zayed-ahmed/profil/spieler/295274.
Transfer history data appended for: https://www.transfermarkt.com/mwape-musonda/profil/spieler/263179.
Transfer history data appended for: https://www.transfermarkt.com/eisa-ahmed/profil/spieler/171886.
Transfer history data appended for: https://www.transfermarkt.com/junior-hochou/profil/spieler/824728.
Transfer history data appended for: https://www.transfermarkt.com/yaser-al-junaibi/profil/spieler/148136.
Transfer history data appended for: https://www.transfermarkt.com/abdulla-kazim/profil/spieler/295576.
Transfer history data appended for: https://www.transfermarkt.com/saeed-khameis-saeed-ali-al-mesmari/profil/spieler/840445.
Transfer history data appended for: https://www.transfermarkt.com/khalaf-mohammed-al-hosani/profil/spieler/428740.
Transfer history data appended for: https://www.transfermarkt.com/mohammad-jamal-atiq/profil/spieler/128373.
Transfer history data appended for: https://www.transfermarkt.com/abdulla-malalla-juma/profil/spieler/430519.
Transfer history data appended for: https://www.transfermarkt.com/walid-ahmed-hassan-ahmed-al-mazam/profil/spieler/539401.
Transfer history data appended for: https://www.transfermarkt.com/waleed-ahmed/profil/spieler/134871.
Transfer history data appended for: https://www.transfermarkt.com/mohammed-talib/profil/spieler/548481.
Transfer history data appended for: https://www.transfermarkt.com/hamad-al-hammadi/profil/spieler/260854.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-khamis-juma/profil/spieler/614897.
Transfer history data appended for: https://www.transfermarkt.com/hamad-ibrahim/profil/spieler/261463.
Transfer history data appended for: https://www.transfermarkt.com/kevin-londono/profil/spieler/421007.
Transfer history data appended for: https://www.transfermarkt.com/humaid-salmein/profil/spieler/295594.
Transfer history data appended for: https://www.transfermarkt.com/khalid-ali-matar/profil/spieler/224198.
Transfer history data appended for: https://www.transfermarkt.com/adnan-hussain/profil/spieler/185494.
Transfer history data appended for: https://www.transfermarkt.com/saeed-suleiman-salem/profil/spieler/829302.
Transfer history data appended for: https://www.transfermarkt.com/abdullah-abdulqader/profil/spieler/268141.
Transfer history data appended for: https://www.transfermarkt.com/alhusain-saleh-easa-ali/profil/spieler/431614.
Transfer history data appended for: https://www.transfermarkt.com/hamad-al-marzoqi/profil/spieler/485784.
Transfer history data appended for: https://www.transfermarkt.com/mohamad-ibrahim-alhamadi/profil/spieler/631815.
Transfer history data appended for: https://www.transfermarkt.com/brian-ramirez/profil/spieler/804793.
Transfer history data appended for: https://www.transfermarkt.com/willian-farias/profil/spieler/71080.
Transfer history data appended for: https://www.transfermarkt.com/mahmood-qassim/profil/spieler/223639.
Transfer history data appended for: https://www.transfermarkt.com/saeed-jassim/profil/spieler/322988.
Transfer history data appended for: https://www.transfermarkt.com/humaid-abdulla/profil/spieler/223395.
Transfer history data appended for: https://www.transfermarkt.com/artem-dovbyk/profil/spieler/343537.
Transfer history data appended for: https://www.transfermarkt.com/arseniy-batagov/profil/spieler/665048.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-belyaev/profil/spieler/524031.
Transfer history data appended for: https://www.transfermarkt.com/yuriy-vakulko/profil/spieler/369155.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-safronov/profil/spieler/467241.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-nazarenko/profil/spieler/495920.
Transfer history data appended for: https://www.transfermarkt.com/andriy-tsurikov/profil/spieler/155964.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-dubinchak/profil/spieler/366723.
Transfer history data appended for: https://www.transfermarkt.com/igor-kogut/profil/spieler/448868.
Transfer history data appended for: https://www.transfermarkt.com/danylo-ignatenko/profil/spieler/376082.
Transfer history data appended for: https://www.transfermarkt.com/volodymyr-adamyuk/profil/spieler/273663.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-buletsa/profil/spieler/404846.
Transfer history data appended for: https://www.transfermarkt.com/francisco-di-franco/profil/spieler/274058.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-kravchenko/profil/spieler/59076.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-loginov/profil/spieler/110688.

Transfer history data appended for: https://www.transfermarkt.com/valeriy-yurchuk/profil/spieler/292396.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-pikhalyonok/profil/spieler/294780.
Transfer history data appended for: https://www.transfermarkt.com/oleksiy-chychykov/profil/spieler/43404.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-svatok/profil/spieler/244271.
Transfer history data appended for: https://www.transfermarkt.com/lucas-taylor/profil/spieler/387928.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-sarnavskyi/profil/spieler/177276.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-korkishko/profil/spieler/91380.
Transfer history data appended for: https://www.transfermarkt.com/douglas/profil/spieler/101304.
Transfer history data appended for: https://www.transfermarkt.com/yegor-yarmolyuk/profil/spieler/717411.
Transfer history data appended for: https://www.transfermarkt.com/oleksiy-bykov/profil/spieler/396395.
Transfer history data appended for: https://www.transfermarkt.com/maksym-chekh/profil/spieler/396401.
Transfer history data appended for: https://www.transfermarkt.com/eldar-kuliev/profil/spieler/819493.
Transfer history data appended for: https://www.transfermarkt.com/petro-stasyuk/profil/spieler/343622.
Transfer history data appended for: https://www.transfermarkt.com/artem-bondarenko/profil/spieler/537854.
Transfer history data appended for: https://www.transfermarkt.com/igor-kyryukhantsev/profil/spieler/203855.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-topalov/profil/spieler/365692.
Transfer history data appended for: https://www.transfermarkt.com/igor-tyshchenko/profil/spieler/97727.
Transfer history data appended for: https://www.transfermarkt.com/vyacheslav-tankovskyi/profil/spieler/213980.
Transfer history data appended for: https://www.transfermarkt.com/oleg-kudryk/profil/spieler/341485.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-gorbunov/profil/spieler/288853.
Transfer history data appended for: https://www.transfermarkt.com/vyacheslav-velev/profil/spieler/672802.
Transfer history data appended for: https://www.transfermarkt.com/danylo-sikan/profil/spieler/417228.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-galchuk/profil/spieler/59022.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-biblyk/profil/spieler/537851.
Transfer history data appended for: https://www.transfermarkt.com/artem-pospelov/profil/spieler/628580.
Transfer history data appended for: https://www.transfermarkt.com/danylo-sagutkin/profil/spieler/341486.
Transfer history data appended for: https://www.transfermarkt.com/oleksiy-kashchuk/profil/spieler/404849.
Transfer history data appended for: https://www.transfermarkt.com/andriy-kulakov/profil/spieler/404848.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-chobotenko/profil/spieler/245021.
Transfer history data appended for: https://www.transfermarkt.com/anton-baydal/profil/spieler/699842.
Transfer history data appended for: https://www.transfermarkt.com/mykyta-peterman/profil/spieler/461663.
Transfer history data appended for: https://www.transfermarkt.com/nazariy-muravskyi/profil/spieler/533318.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-myshnyov/profil/spieler/212243.
Transfer history data appended for: https://www.transfermarkt.com/oleg-ocheretko/profil/spieler/708241.
Transfer history data appended for: https://www.transfermarkt.com/alan-patrick/profil/spieler/104505.
Transfer history data appended for: https://www.transfermarkt.com/marcos-antonio/profil/spieler/468301.
Transfer history data appended for: https://www.transfermarkt.com/viktor-kovalenko/profil/spieler/203842.
Transfer history data appended for: https://www.transfermarkt.com/valeriy-bondar/profil/spieler/396394.
Transfer history data appended for: https://www.transfermarkt.com/manor-solomon/profil/spieler/396638.
Transfer history data appended for: https://www.transfermarkt.com/dodo/profil/spieler/401529.
Transfer history data appended for: https://www.transfermarkt.com/marlos/profil/spieler/68778.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-vyunnyk/profil/spieler/623331.
Transfer history data appended for: https://www.transfermarkt.com/andriy-pyatov/profil/spieler/39996.
Transfer history data appended for: https://www.transfermarkt.com/davit-khocholava/profil/spieler/165825.
Transfer history data appended for: https://www.transfermarkt.com/mykola-matvienko/profil/spieler/289059.
Transfer history data appended for: https://www.transfermarkt.com/oleksiy-shevchenko/profil/spieler/136537.
Transfer history data appended for: https://www.transfermarkt.com/maksym-malyshev/profil/spieler/256213.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-konoplyanka/profil/spieler/58949.
Transfer history data appended for: https://www.transfermarkt.com/ismaily/profil/spieler/124028.
Transfer history data appended for: https://www.transfermarkt.com/viktor-kornienko/profil/spieler/467243.
Transfer history data appended for: https://www.transfermarkt.com/dentinho/profil/spieler/52787.
Transfer history data appended for: https://www.transfermarkt.com/vitao/profil/spieler/428783.
Transfer history data appended for: https://www.transfermarkt.com/taras-stepanenko/profil/spieler/59970.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-vakula/profil/spieler/526578.
Transfer history data appended for: https://www.transfermarkt.com/maycon/profil/spieler/421935.
Transfer history data appended for: https://www.transfermarkt.com/fernando/profil/spieler/550495.
Transfer history data appended for: https://www.transfermarkt.com/junior-moraes/profil/spieler/52915.
Transfer history data appended for: https://www.transfermarkt.com/anatoliy-trubin/profil/spieler/537844.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-kryvtsov/profil/spieler/74089.
Transfer history data appended for: https://www.transfermarkt.com/tete/profil/spieler/371256.
Transfer history data appended for: https://www.transfermarkt.com/taison/profil/spieler/76028.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-bolbat/profil/spieler/264063.
Transfer history data appended for: https://www.transfermarkt.com/vyacheslav-churko/profil/spieler/131553.
Transfer history data appended for: https://www.transfermarkt.com/marquinhos-cipriano/profil/spieler/569805.
Transfer history data appended for: https://www.transfermarkt.com/georgiy-sudakov/profil/spieler/623325.
Transfer history data appended for: https://www.transfermarkt.com/yuriy-kravchuk/profil/spieler/320953.
Transfer history data appended for: https://www.transfermarkt.com/donatas-kazlauskas/profil/spieler/167863.
Transfer history data appended for: https://www.transfermarkt.com/andriy-busko/profil/spieler/524965.
Transfer history data appended for: https://www.transfermarkt.com/igor-koshman/profil/spieler/297008.
Transfer history data appended for: https://www.transfermarkt.com/maksym-grysyo/profil/spieler/448783.
Transfer history data appended for: https://www.transfermarkt.com/ostap-malashevskyi/profil/spieler/570267.
Transfer history data appended for: https://www.transfermarkt.com/german-penkov/profil/spieler/375659.
Transfer history data appended for: https://www.transfermarkt.com/maksym-komarets/profil/spieler/771917.
Transfer history data appended for: https://www.transfermarkt.com/yuriy-zakharkiv/profil/spieler/372138.
Transfer history data appended for: https://www.transfermarkt.com/enes-mahmutovic/profil/spieler/329055.
Transfer history data appended for: https://www.transfermarkt.com/andriy-vychizhanin/profil/spieler/752040.
Transfer history data appended for: https://www.transfermarkt.com/nazariy-nych/profil/spieler/523903.
Transfer history data appended for: https://www.transfermarkt.com/frane-cirjak/profil/spieler/250416.
Transfer history data appended for: https://www.transfermarkt.com/maroine-mihoubi/profil/spieler/460644.
Transfer history data appended for: https://www.transfermarkt.com/orest-kostyk/profil/spieler/747315.

Transfer history data appended for: https://www.transfermarkt.com/volodymyr-yakimets/profil/spieler/396402.
Transfer history data appended for: https://www.transfermarkt.com/mihkel-ainsalu/profil/spieler/198967.
Transfer history data appended for: https://www.transfermarkt.com/ernest/profil/spieler/359678.
Transfer history data appended for: https://www.transfermarkt.com/maks-juraj-celic/profil/spieler/348768.
Transfer history data appended for: https://www.transfermarkt.com/yegor-klymenchuk/profil/spieler/375955.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-savoshko/profil/spieler/775824.
Transfer history data appended for: https://www.transfermarkt.com/china/profil/spieler/497719.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-romanchuk/profil/spieler/553772.
Transfer history data appended for: https://www.transfermarkt.com/welves/profil/spieler/654311.
Transfer history data appended for: https://www.transfermarkt.com/rafael-sabino/profil/spieler/598992.
Transfer history data appended for: https://www.transfermarkt.com/filipe-pachtmann/profil/spieler/708172.
Transfer history data appended for: https://www.transfermarkt.com/yevgeniy-kucherenko/profil/spieler/537841.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-yemets/profil/spieler/576022.
Transfer history data appended for: https://www.transfermarkt.com/mykyta-kravchenko/profil/spieler/370399.
Transfer history data appended for: https://www.transfermarkt.com/vitaliy-gavrysh/profil/spieler/59038.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-volynets/profil/spieler/166581.
Transfer history data appended for: https://www.transfermarkt.com/vadym-milko/profil/spieler/58418.
Transfer history data appended for: https://www.transfermarkt.com/yevgeniy-morozko/profil/spieler/380376.
Transfer history data appended for: https://www.transfermarkt.com/denys-antyukh/profil/spieler/383325.
Transfer history data appended for: https://www.transfermarkt.com/volodymyr-lysenko/profil/spieler/58413.
Transfer history data appended for: https://www.transfermarkt.com/maksym-maksymenko/profil/spieler/114398.
Transfer history data appended for: https://www.transfermarkt.com/oleksiy-zozulya/profil/spieler/269365.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-zadoya/profil/spieler/59978.
Transfer history data appended for: https://www.transfermarkt.com/mamadou-danfa/profil/spieler/649029.
Transfer history data appended for: https://www.transfermarkt.com/matija-rom/profil/spieler/320861.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-seleznyov/profil/spieler/59908.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-kucheruk/profil/spieler/404838.
Transfer history data appended for: https://www.transfermarkt.com/yevgeniy-isaenko/profil/spieler/539441.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-novak/profil/spieler/91358.
Transfer history data appended for: https://www.transfermarkt.com/kyrylo-petrov/profil/spieler/58427.
Transfer history data appended for: https://www.transfermarkt.com/denys-kostyshyn/profil/spieler/366446.
Transfer history data appended for: https://www.transfermarkt.com/oleg-ilyin/profil/spieler/495923.
Transfer history data appended for: https://www.transfermarkt.com/yevgeniy-smyrnyi/profil/spieler/396532.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-chornomorets/profil/spieler/167555.
Transfer history data appended for: https://www.transfermarkt.com/pavlo-orikhovskyi/profil/spieler/248936.
Transfer history data appended for: https://www.transfermarkt.com/andriy-bogdanov/profil/spieler/92567.
Transfer history data appended for: https://www.transfermarkt.com/andriy-mostovyi/profil/spieler/92640.
Transfer history data appended for: https://www.transfermarkt.com/joonas-tamm/profil/spieler/111556.
Transfer history data appended for: https://www.transfermarkt.com/levan-arveladze/profil/spieler/168292.
Transfer history data appended for: https://www.transfermarkt.com/yegor-kartushov/profil/spieler/94925.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-khlyobas/profil/spieler/62610.
Transfer history data appended for: https://www.transfermarkt.com/maksym-imerekov/profil/spieler/94924.
Transfer history data appended for: https://www.transfermarkt.com/andriy-dombrovskyi/profil/spieler/381273.
Transfer history data appended for: https://www.transfermarkt.com/maksym-degtyarov/profil/spieler/193323.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-kalitvintsev/profil/spieler/108710.
Transfer history data appended for: https://www.transfermarkt.com/yukhym-konoplya/profil/spieler/467250.
Transfer history data appended for: https://www.transfermarkt.com/igor-lytovka/profil/spieler/93105.
Transfer history data appended for: https://www.transfermarkt.com/andriy-gitchenko/profil/spieler/91727.
Transfer history data appended for: https://www.transfermarkt.com/artur-zapadnya/profil/spieler/111074.
Transfer history data appended for: https://www.transfermarkt.com/pylyp-budkivskyi/profil/spieler/99863.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-starenkyi/profil/spieler/93077.
Transfer history data appended for: https://www.transfermarkt.com/pavlo-polegenko/profil/spieler/216579.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-ogirya/profil/spieler/111072.
Transfer history data appended for: https://www.transfermarkt.com/vitaliy-yermakov/profil/spieler/169260.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-past/profil/spieler/49016.
Transfer history data appended for: https://www.transfermarkt.com/andriy-totovytskyi/profil/spieler/277777.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-volkov/profil/spieler/134761.
Transfer history data appended for: https://www.transfermarkt.com/ilya-shevtsov/profil/spieler/383198.
Transfer history data appended for: https://www.transfermarkt.com/mykhaylo-mudryk/profil/spieler/537860.
Transfer history data appended for: https://www.transfermarkt.com/mykhaylo-shyshka/profil/spieler/168041.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-shust/profil/spieler/38297.
Transfer history data appended for: https://www.transfermarkt.com/denis-yanakov/profil/spieler/404851.
Transfer history data appended for: https://www.transfermarkt.com/mykhaylo-plokhotnyuk/profil/spieler/515669.
Transfer history data appended for: https://www.transfermarkt.com/volodymyr-krynskyi/profil/spieler/332144.
Transfer history data appended for: https://www.transfermarkt.com/denys-balan/profil/spieler/166563.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-kozak/profil/spieler/375180.
Transfer history data appended for: https://www.transfermarkt.com/rudolf-blagogee/profil/spieler/579586.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-zaporozhets/profil/spieler/380554.
Transfer history data appended for: https://www.transfermarkt.com/mykola-kvasnyi/profil/spieler/398675.
Transfer history data appended for: https://www.transfermarkt.com/yohana-oscar-mkomola/profil/spieler/568915.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-ignatyev/profil/spieler/411027.
Transfer history data appended for: https://www.transfermarkt.com/nika-sichinava/profil/spieler/241700.
Transfer history data appended for: https://www.transfermarkt.com/volodymyr-bilotserkovets/profil/spieler/755175.
Transfer history data appended for: https://www.transfermarkt.com/mladen-bartulovic/profil/spieler/28179.
Transfer history data appended for: https://www.transfermarkt.com/maksym-kovalyov/profil/spieler/58402.
Transfer history data appended for: https://www.transfermarkt.com/vitaliy-pavlov/profil/spieler/59115.
Transfer history data appended for: https://www.transfermarkt.com/ilya-kovalenko/profil/spieler/177267.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-lupashko/profil/spieler/53258.
Transfer history data appended for: https://www.transfermarkt.com/oleg-synyogub/profil/spieler/319165.

Transfer history data appended for: https://www.transfermarkt.com/oleksandr-kucherenko/profil/spieler/358956.
Transfer history data appended for: https://www.transfermarkt.com/artem-shchedryi/profil/spieler/123279.
Transfer history data appended for: https://www.transfermarkt.com/andriy-semenko/profil/spieler/379977.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-fateev/profil/spieler/271635.
Transfer history data appended for: https://www.transfermarkt.com/artem-malysh/profil/spieler/461653.
Transfer history data appended for: https://www.transfermarkt.com/orest-lebedenko/profil/spieler/524964.
Transfer history data appended for: https://www.transfermarkt.com/yevgeniy-pasich/profil/spieler/315237.
Transfer history data appended for: https://www.transfermarkt.com/ivan-zotko/profil/spieler/305423.
Transfer history data appended for: https://www.transfermarkt.com/igor-snurnitsyn/profil/spieler/419119.
Transfer history data appended for: https://www.transfermarkt.com/artem-kychak/profil/spieler/88879.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-kargbo-jr-/profil/spieler/550696.
Transfer history data appended for: https://www.transfermarkt.com/betim-halimi/profil/spieler/497190.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-gryshko/profil/spieler/48989.
Transfer history data appended for: https://www.transfermarkt.com/shahab-zahedi/profil/spieler/350828.
Transfer history data appended for: https://www.transfermarkt.com/pavlo-ksyonz/profil/spieler/57888.
Transfer history data appended for: https://www.transfermarkt.com/rizvan-ablitarov/profil/spieler/58922.
Transfer history data appended for: https://www.transfermarkt.com/kirill-kirilenko/profil/spieler/470265.
Transfer history data appended for: https://www.transfermarkt.com/fabricio-alvarenga/profil/spieler/381430.
Transfer history data appended for: https://www.transfermarkt.com/ruslan-babenko/profil/spieler/94928.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-politylo/profil/spieler/58606.
Transfer history data appended for: https://www.transfermarkt.com/taras-zaviyskyi/profil/spieler/213984.
Transfer history data appended for: https://www.transfermarkt.com/temur-chogadze/profil/spieler/400719.
Transfer history data appended for: https://www.transfermarkt.com/issiar-drame/profil/spieler/461582.
Transfer history data appended for: https://www.transfermarkt.com/benito/profil/spieler/491960.
Transfer history data appended for: https://www.transfermarkt.com/andriy-chekotun/profil/spieler/728379.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-tsymbalyuk/profil/spieler/376226.
Transfer history data appended for: https://www.transfermarkt.com/daniel-romanovskij/profil/spieler/229320.
Transfer history data appended for: https://www.transfermarkt.com/andriy-kravchuk/profil/spieler/537859.
Transfer history data appended for: https://www.transfermarkt.com/maxime-do-couto/profil/spieler/315930.
Transfer history data appended for: https://www.transfermarkt.com/shemmy-mayembe/profil/spieler/432094.
Transfer history data appended for: https://www.transfermarkt.com/andriy-tkachuk/profil/spieler/58150.
Transfer history data appended for: https://www.transfermarkt.com/danylo-knysh/profil/spieler/268697.
Transfer history data appended for: https://www.transfermarkt.com/tercious-malepe/profil/spieler/388313.
Transfer history data appended for: https://www.transfermarkt.com/anatoliy-nuriev/profil/spieler/570743.
Transfer history data appended for: https://www.transfermarkt.com/anton-shynder/profil/spieler/39253.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-glagola/profil/spieler/341490.
Transfer history data appended for: https://www.transfermarkt.com/oleksiy-khakhlyov/profil/spieler/404847.
Transfer history data appended for: https://www.transfermarkt.com/rustam-akhmedzade/profil/spieler/792844.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-matkobozhyk/profil/spieler/468735.
Transfer history data appended for: https://www.transfermarkt.com/andriy-popovych/profil/spieler/186769.
Transfer history data appended for: https://www.transfermarkt.com/vasyl-pynyashko/profil/spieler/632674.
Transfer history data appended for: https://www.transfermarkt.com/oleg-golodyuk/profil/spieler/58016.
Transfer history data appended for: https://www.transfermarkt.com/oleg-dopilka/profil/spieler/58389.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-snizhko/profil/spieler/381815.
Transfer history data appended for: https://www.transfermarkt.com/artur-karnoza/profil/spieler/58946.
Transfer history data appended for: https://www.transfermarkt.com/maksym-lopyryonok/profil/spieler/448867.
Transfer history data appended for: https://www.transfermarkt.com/mislav-matic/profil/spieler/651388.
Transfer history data appended for: https://www.transfermarkt.com/taras-sakiv/profil/spieler/498899.
Transfer history data appended for: https://www.transfermarkt.com/edgar-caparros/profil/spieler/384299.
Transfer history data appended for: https://www.transfermarkt.com/oleksiy-shpak/profil/spieler/632675.
Transfer history data appended for: https://www.transfermarkt.com/anton-kanibolotskyi/profil/spieler/58945.
Transfer history data appended for: https://www.transfermarkt.com/kyrylo-melichenko/profil/spieler/467244.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-pavlish/profil/spieler/537847.
Transfer history data appended for: https://www.transfermarkt.com/denys-kozhanov/profil/spieler/58403.
Transfer history data appended for: https://www.transfermarkt.com/georgiy-tsitaishvili/profil/spieler/419067.
Transfer history data appended for: https://www.transfermarkt.com/tomasz-kedziora/profil/spieler/181118.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-andriyevskyi/profil/spieler/207074.
Transfer history data appended for: https://www.transfermarkt.com/mykola-shaparenko/profil/spieler/368611.
Transfer history data appended for: https://www.transfermarkt.com/carlos-de-pena/profil/spieler/257740.
Transfer history data appended for: https://www.transfermarkt.com/georgiy-bushchan/profil/spieler/206888.
Transfer history data appended for: https://www.transfermarkt.com/artem-besedin/profil/spieler/305415.
Transfer history data appended for: https://www.transfermarkt.com/viktor-tsygankov/profil/spieler/264372.
Transfer history data appended for: https://www.transfermarkt.com/tudor-baluta/profil/spieler/433976.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-tymchyk/profil/spieler/287792.
Transfer history data appended for: https://www.transfermarkt.com/mykyta-burda/profil/spieler/213865.
Transfer history data appended for: https://www.transfermarkt.com/clayton/profil/spieler/250007.
Transfer history data appended for: https://www.transfermarkt.com/vitaliy-mykolenko/profil/spieler/404842.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-sydorchuk/profil/spieler/124182.
Transfer history data appended for: https://www.transfermarkt.com/ruslan-neshcheret/profil/spieler/417242.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-syrota/profil/spieler/505463.
Transfer history data appended for: https://www.transfermarkt.com/ilya-zabarnyi/profil/spieler/659089.
Transfer history data appended for: https://www.transfermarkt.com/volodymyr-shepelev/profil/spieler/294746.
Transfer history data appended for: https://www.transfermarkt.com/benjamin-verbic/profil/spieler/188180.
Transfer history data appended for: https://www.transfermarkt.com/mikkel-duelund/profil/spieler/320265.
Transfer history data appended for: https://www.transfermarkt.com/denys-garmash/profil/spieler/70754.
Transfer history data appended for: https://www.transfermarkt.com/vitaliy-buyalskyi/profil/spieler/167722.
Transfer history data appended for: https://www.transfermarkt.com/denys-popov/profil/spieler/404841.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-supryaga/profil/spieler/419061.
Transfer history data appended for: https://www.transfermarkt.com/artem-shabanov/profil/spieler/236468.

Transfer history data appended for: https://www.transfermarkt.com/nazariy-rusyn/profil/spieler/366729.
Transfer history data appended for: https://www.transfermarkt.com/volodymyr-kostevych/profil/spieler/208469.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-lednev/profil/spieler/423606.
Transfer history data appended for: https://www.transfermarkt.com/maksim-grechkin/profil/spieler/347270.
Transfer history data appended for: https://www.transfermarkt.com/lovro-cvek/profil/spieler/317467.
Transfer history data appended for: https://www.transfermarkt.com/tymofiy-sukhar/profil/spieler/404844.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-gladkyi/profil/spieler/53270.
Transfer history data appended for: https://www.transfermarkt.com/vitaliy-vernydub/profil/spieler/59973.
Transfer history data appended for: https://www.transfermarkt.com/joel-abu-hanna/profil/spieler/267330.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-kabaev/profil/spieler/210689.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-gryn/profil/spieler/269374.
Transfer history data appended for: https://www.transfermarkt.com/maksym-kazakov/profil/spieler/373044.
Transfer history data appended for: https://www.transfermarkt.com/mihailo-perovic/profil/spieler/293253.
Transfer history data appended for: https://www.transfermarkt.com/juninho/profil/spieler/606952.
Transfer history data appended for: https://www.transfermarkt.com/nikola-vasilj/profil/spieler/248454.
Transfer history data appended for: https://www.transfermarkt.com/igor-chaykovskyi/profil/spieler/94923.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-kochergin/profil/spieler/248932.
Transfer history data appended for: https://www.transfermarkt.com/vladlen-yurchenko/profil/spieler/157373.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-ivanisenya/profil/spieler/376228.
Transfer history data appended for: https://www.transfermarkt.com/denys-favorov/profil/spieler/289095.
Transfer history data appended for: https://www.transfermarkt.com/andrejs-ciganiks/profil/spieler/202659.
Transfer history data appended for: https://www.transfermarkt.com/yegor-nazaryna/profil/spieler/430190.
Transfer history data appended for: https://www.transfermarkt.com/mykyta-shevchenko/profil/spieler/80312.
Transfer history data appended for: https://www.transfermarkt.com/artem-gromov/profil/spieler/122088.
Transfer history data appended for: https://www.transfermarkt.com/maksym-lunyov/profil/spieler/401822.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-khomchenovskyi/profil/spieler/59896.
Transfer history data appended for: https://www.transfermarkt.com/agron-rufati/profil/spieler/460591.
Transfer history data appended for: https://www.transfermarkt.com/allahyar-sayyadmanesh/profil/spieler/480975.
Transfer history data appended for: https://www.transfermarkt.com/zauri-makharadze/profil/spieler/166575.
Transfer history data appended for: https://www.transfermarkt.com/joao-teixeira/profil/spieler/344893.
Transfer history data appended for: https://www.transfermarkt.com/valeriy-bondarenko/profil/spieler/365540.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-grechyshkin/profil/spieler/130041.
Transfer history data appended for: https://www.transfermarkt.com/oleg-bilyk/profil/spieler/449084.
Transfer history data appended for: https://www.transfermarkt.com/tymur-stetskov/profil/spieler/549960.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-shastal/profil/spieler/359796.
Transfer history data appended for: https://www.transfermarkt.com/denys-miroshnichenko/profil/spieler/244262.
Transfer history data appended for: https://www.transfermarkt.com/vasyl-grytsuk/profil/spieler/59047.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-rudyk/profil/spieler/296659.
Transfer history data appended for: https://www.transfermarkt.com/kyrylo-kovalets/profil/spieler/140676.
Transfer history data appended for: https://www.transfermarkt.com/denys-ustymenko/profil/spieler/622410.
Transfer history data appended for: https://www.transfermarkt.com/oleksiy-dovgyi/profil/spieler/91419.
Transfer history data appended for: https://www.transfermarkt.com/denys-bezborodko/profil/spieler/269371.
Transfer history data appended for: https://www.transfermarkt.com/maksym-tretyakov/profil/spieler/248938.
Transfer history data appended for: https://www.transfermarkt.com/artem-gordienko/profil/spieler/271482.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-baboglo/profil/spieler/567873.
Transfer history data appended for: https://www.transfermarkt.com/roman-vantukh/profil/spieler/396536.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-myshenko/profil/spieler/325420.
Transfer history data appended for: https://www.transfermarkt.com/yuriy-pankiv/profil/spieler/102572.
Transfer history data appended for: https://www.transfermarkt.com/pavlo-pashaev/profil/spieler/58961.
Transfer history data appended for: https://www.transfermarkt.com/maksym-zaderaka/profil/spieler/325429.
Transfer history data appended for: https://www.transfermarkt.com/artem-sitalo/profil/spieler/320247.
Transfer history data appended for: https://www.transfermarkt.com/vadym-yanchak/profil/spieler/553056.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-banada/profil/spieler/242272.
Transfer history data appended for: https://www.transfermarkt.com/valeriy-luchkevych/profil/spieler/248934.
Transfer history data appended for: https://www.transfermarkt.com/kaspars-dubra/profil/spieler/85506.
Transfer history data appended for: https://www.transfermarkt.com/glib-bukhal/profil/spieler/381268.
Transfer history data appended for: https://www.transfermarkt.com/vadym-sapay/profil/spieler/59129.
Transfer history data appended for: https://www.transfermarkt.com/vladyslav-kulach/profil/spieler/167556.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-riznyk/profil/spieler/597880.
Transfer history data appended for: https://www.transfermarkt.com/volodymyr-chesnakov/profil/spieler/58930.
Transfer history data appended for: https://www.transfermarkt.com/volodymyr-bayenko/profil/spieler/314571.
Transfer history data appended for: https://www.transfermarkt.com/sergiy-yavorskyi/profil/spieler/91479.
Transfer history data appended for: https://www.transfermarkt.com/najeeb-yakubu/profil/spieler/543493.
Transfer history data appended for: https://www.transfermarkt.com/david-puclin/profil/spieler/197078.
Transfer history data appended for: https://www.transfermarkt.com/denys-vasin/profil/spieler/49030.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-sklyar/profil/spieler/91801.
Transfer history data appended for: https://www.transfermarkt.com/ruslan-stepanyuk/profil/spieler/222079.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-tkachenko/profil/spieler/174213.
Transfer history data appended for: https://www.transfermarkt.com/igor-perduta/profil/spieler/201671.
Transfer history data appended for: https://www.transfermarkt.com/artem-chelyadin/profil/spieler/511909.
Transfer history data appended for: https://www.transfermarkt.com/ibrahim-kane/profil/spieler/543380.
Transfer history data appended for: https://www.transfermarkt.com/danylo-kravchuk/profil/spieler/751363.
Transfer history data appended for: https://www.transfermarkt.com/mykyta-tatarkov/profil/spieler/321417.
Transfer history data appended for: https://www.transfermarkt.com/pape-alioune-ndiaye/profil/spieler/433219.
Transfer history data appended for: https://www.transfermarkt.com/pavlo-rebenok/profil/spieler/43359.
Transfer history data appended for: https://www.transfermarkt.com/pavlo-isenko/profil/spieler/726033.
Transfer history data appended for: https://www.transfermarkt.com/ivan-pesic/profil/spieler/115133.
Transfer history data appended for: https://www.transfermarkt.com/yevgen-opanasenko/profil/spieler/86931.
Transfer history data appended for: https://www.transfermarkt.com/dmytro-shcherbak/profil/spieler/436379.

Transfer history data appended for: https://www.transfermarkt.com/erik-gliha/profil/spieler/284608.
Transfer history data appended for: https://www.transfermarkt.com/rostyslav-rusyn/profil/spieler/289487.
Transfer history data appended for: https://www.transfermarkt.com/bogdan-boychuk/profil/spieler/337198.
Transfer history data appended for: https://www.transfermarkt.com/oleg-veremiyenko/profil/spieler/497222.
Transfer history data appended for: https://www.transfermarkt.com/maryan-mysyk/profil/spieler/316945.
Transfer history data appended for: https://www.transfermarkt.com/ostap-prytula/profil/spieler/620368.
Transfer history data appended for: https://www.transfermarkt.com/yuriy-kopyna/profil/spieler/432658.
Transfer history data appended for: https://www.transfermarkt.com/maksym-bilyi/profil/spieler/107803.
Transfer history data appended for: https://www.transfermarkt.com/mykola-kukharevych/profil/spieler/730126.
Transfer history data appended for: https://www.transfermarkt.com/ivan-kalyuzhnyi/profil/spieler/343151.
Transfer history data appended for: https://www.transfermarkt.com/david-zec/profil/spieler/469709.
Transfer history data appended for: https://www.transfermarkt.com/yuriy-klymchuk/profil/spieler/501612.
Transfer history data appended for: https://www.transfermarkt.com/roman-gagun/profil/spieler/522327.
Transfer history data appended for: https://www.transfermarkt.com/roman-mysak/profil/spieler/117481.
Transfer history data appended for: https://www.transfermarkt.com/igor-duts/profil/spieler/176409.
Transfer history data appended for: https://www.transfermarkt.com/danylo-kondrakov/profil/spieler/540186.
Transfer history data appended for: https://www.transfermarkt.com/valeriy-fedorchuk/profil/spieler/82599.
Transfer history data appended for: https://www.transfermarkt.com/stanislav-bilenkyi/profil/spieler/511669.
Transfer history data appended for: https://www.transfermarkt.com/vadym-paramonov/profil/spieler/312799.
Transfer history data appended for: https://www.transfermarkt.com/volodymyr-zastavnyi/profil/spieler/162783.
Transfer history data appended for: https://www.transfermarkt.com/yaroslav-martynyuk/profil/spieler/58072.
Transfer history data appended for: https://www.transfermarkt.com/milos-stamenkovic/profil/spieler/146725.
Transfer history data appended for: https://www.transfermarkt.com/svyatoslav-kozlovskyi/profil/spieler/206889.
Transfer history data appended for: https://www.transfermarkt.com/andriy-kukharuk/profil/spieler/365195.
Transfer history data appended for: https://www.transfermarkt.com/hisham-layous/profil/spieler/694512.
Transfer history data appended for: https://www.transfermarkt.com/ivan-brikner/profil/spieler/295613.
Transfer history data appended for: https://www.transfermarkt.com/oleksandr-bandura/profil/spieler/85969.
Transfer history data appended for: https://www.transfermarkt.com/igor-boychuk/profil/spieler/427668.
Scraping ended at: 2020-12-05 16:16:29.021880
Time taken to scrape the transfer history data of the 21,969 players for the 2020/2021 season is: 378.25 minutes.

In [33]:
# Display DataFrame
df_th.head()

,transfered_from,transferred_to,market_values,transfer_fees,transfer_dates,transfer_season,country_to,country_from,transfer_types,internal_external_transfer,age_at_transfer,player_id,all_youth_clubs,season
0,apejes fc de mfou,sc rheindorf altach,0,0,2017-08-31,17/18,austria,cameroon,transfer,external,19,452238,apejes fc de mfou,2020/2021
0,sv ried,sc rheindorf altach,0,0,2013-07-01,13/14,austria,austria,transfer,external,24,59132,"aka linz,fussballakademie linz,usv st. ulrich,...",2020/2021
1,lask linz,sv ried,0,0,2011-07-01,11/12,austria,austria,transfer,external,22,59132,"aka linz,fussballakademie linz,usv st. ulrich,...",2020/2021
2,sc austria lustenau,lask linz,0,0,2010-06-30,09/10,austria,austria,loan,external,21,59132,"aka linz,fussballakademie linz,usv st. ulrich,...",2020/2021
3,lask linz,sc austria lustenau,0,0,2009-01-08,08/09,austria,austria,loan,external,19,59132,"aka linz,fussballakademie linz,usv st. ulrich,...",2020/2021

In [31]:
df_th.shape

(129837, 14)

##### Export DataFrame

In [21]:
# Export DataFrame as a CSV file

## Export a copy to the 'archive' subfolder of the TM folder, including the date
df_th.to_csv(data_dir_tm + f'/raw/{short_season_string}/transfer-history/archive/' + f'tm_player_th_all_{short_season_string}_last_updated_{today}.csv', index=None, header=True)

## Export another copy to the TM folder called 'latest' (can be overwritten)
df_th.to_csv(data_dir_tm + f'/raw/{short_season_string}/transfer-history/' + f'tm_player_th_all_{short_season_string}_latest.csv', index=None, header=True)

NameError: name 'df_th' is not defined

#### <a id='#section3.3.6.'>3.3.6. Performance Data</a>

In [12]:
# Run this script to scrape latest version of performance data from TransferMarkt

## Start timer
tic = datetime.datetime.now()

## Create empty list
lst_df_performance = []

## Print time scraping started
print(f'Scraping started at: {tic}')

## Scrape bio information for each player
for player_page in lst_player_urls:
    try:
        dict_output = tm_pull(player_page, performance_data=True, output='pandas')
        df = dict_output['performance_data']
        lst_df_performance.append(df)
        print(f'Performance history data appended for: {player_page}.')
    except:
        pass

## Concatenate DataFrames
df_performance = pd.concat(lst_df_performance)

## Print time scraping ended
print(f'Scraping ended at: {toc}')

## Create attribute for the season    
df_performance['season'] = full_season_string

## End timer
toc = datetime.datetime.now()

## Calculate time take
total_time = (toc-tic).total_seconds()
print(f'Time taken to scrape the performance data of the {len_player_urls:,} players for the {full_season_string} season is: {total_time/60:0.2f} minutes.')

Scraping started at: 2020-12-07 15:54:46.780808
Performance history data appended for: https://www.transfermarkt.com/erik-palmer-brown/profil/spieler/282199.
Performance history data appended for: https://www.transfermarkt.com/manprit-sarkaria/profil/spieler/288690.
Performance history data appended for: https://www.transfermarkt.com/alon-turgeman/profil/spieler/177249.
Performance history data appended for: https://www.transfermarkt.com/bright-edomwonyi/profil/spieler/229857.
Performance history data appended for: https://www.transfermarkt.com/christoph-martschinko/profil/spieler/120191.
Performance history data appended for: https://www.transfermarkt.com/alexander-grunwald/profil/spieler/34763.
Performance history data appended for: https://www.transfermarkt.com/niels-hahn/profil/spieler/404936.
Performance history data appended for: https://www.transfermarkt.com/maudo-jarjue/profil/spieler/450462.
Performance history data appended for: https://www.transfermarkt.com/georg-teigl/profil/spieler/81698.
Performance history data appended for: https://www.transfermarkt.com/maximilian-sax/profil/spieler/115072.
Performance history data appended for: https://www.transfermarkt.com/christian-schoissengeyr/profil/spieler/157242.
Performance history data appended for: https://www.transfermarkt.com/benedikt-pichler/profil/spieler/331362.
Performance history data appended for: https://www.transfermarkt.com/vesel-demaku/profil/spieler/346846.
Performance history data appended for: https://www.transfermarkt.com/patrick-pentz/profil/spieler/223972.
Performance history data appended for: https://www.transfermarkt.com/christoph-monschein/profil/spieler/300095.
Performance history data appended for: https://www.transfermarkt.com/matthias-braunoder/profil/spieler/488052.
Performance history data appended for: https://www.transfermarkt.com/thomas-ebner/profil/spieler/122781.
Performance history data appended for: https://www.transfermarkt.com/aleksandar-jukic/profil/spieler/393699.
Performance history data appended for: https://www.transfermarkt.com/ammar-helac/profil/spieler/307598.
Performance history data appended for: https://www.transfermarkt.com/dominik-fitz/profil/spieler/354022.
Performance history data appended for: https://www.transfermarkt.com/stephan-zwierschitz/profil/spieler/81701.
Performance history data appended for: https://www.transfermarkt.com/mirko-kos/profil/spieler/307511.
Performance history data appended for: https://www.transfermarkt.com/patrick-wimmer/profil/spieler/533295.
Performance history data appended for: https://www.transfermarkt.com/stefan-radulovic/profil/spieler/527529.
Performance history data appended for: https://www.transfermarkt.com/anouar-el-moukhantir/profil/spieler/261495.
Performance history data appended for: https://www.transfermarkt.com/christoph-schosswendter/profil/spieler/68379.
Performance history data appended for: https://www.transfermarkt.com/johannes-handl/profil/spieler/293084.
Performance history data appended for: https://www.transfermarkt.com/csaba-mester/profil/spieler/497340.
Performance history data appended for: https://www.transfermarkt.com/michael-madl/profil/spieler/20381.
Performance history data appended for: https://www.transfermarkt.com/markus-suttner/profil/spieler/31514.
Performance history data appended for: https://www.transfermarkt.com/lukas-rath/profil/spieler/67442.
Performance history data appended for: https://www.transfermarkt.com/lukas-malicsek/profil/spieler/354061.
Performance history data appended for: https://www.transfermarkt.com/roman-kerschbaum/profil/spieler/120202.
Performance history data appended for: https://www.transfermarkt.com/morten-hjulmand/profil/spieler/461496.
Performance history data appended for: https://www.transfermarkt.com/marco-hausjell/profil/spieler/354054.
Performance history data appended for: https://www.transfermarkt.com/julian-buchta/profil/spieler/346844.
Performance history data appended for: https://www.transfermarkt.com/osman-hadzikic/profil/spieler/188881.
Performance history data appended for: https://www.transfermarkt.com/felix-kekoh/profil/spieler/806200.
Performance history data appended for: https://www.transfermarkt.com/emanuel-aiwu/profil/spieler/394152.
Performance history data appended for: https://www.transfermarkt.com/tomislav-tomic/profil/spieler/190272.
Performance history data appended for: https://www.transfermarkt.com/andreas-leitner/profil/spieler/106851.
Performance history data appended for: https://www.transfermarkt.com/christoph-haas/profil/spieler/157390.
Performance history data appended for: https://www.transfermarkt.com/leonardo-lukacevic/profil/spieler/321870.
Performance history data appended for: https://www.transfermarkt.com/wilhelm-vorsager/profil/spieler/293015.
Performance history data appended for: https://www.transfermarkt.com/stefan-maierhofer/profil/spieler/32660.
Performance history data appended for: https://www.transfermarkt.com/aleksandar-cirkovic/profil/spieler/452218.
Performance history data appended for: https://www.transfermarkt.com/onurhan-babuscu/profil/spieler/538481.
Performance history data appended for: https://www.transfermarkt.com/nikola-pejovic/profil/spieler/343954.
Performance history data appended for: https://www.transfermarkt.com/josef-ganda/profil/spieler/456929.
Performance history data appended for: https://www.transfermarkt.com/paul-koller/profil/spieler/523895.
Performance history data appended for: https://www.transfermarkt.com/filip-ristanic/profil/spieler/601113.
Performance history data appended for: https://www.transfermarkt.com/luca-kronberger/profil/spieler/519011.
Performance history data appended for: https://www.transfermarkt.com/stephan-auer/profil/spieler/82527.
Performance history data appended for: https://www.transfermarkt.com/sebastian-bauer/profil/spieler/151739.
Performance history data appended for: https://www.transfermarkt.com/pascal-petlach/profil/spieler/354063.
Performance history data appended for: https://www.transfermarkt.com/maximilian-breunig/profil/spieler/584254.
Performance history data appended for: https://www.transfermarkt.com/dominik-starkl/profil/spieler/158214.
Performance history data appended for: https://www.transfermarkt.com/milos-spasic/profil/spieler/307689.
Performance history data appended for: https://www.transfermarkt.com/phoenix-missi/profil/spieler/806199.
Performance history data appended for: https://www.transfermarkt.com/marco-kadlec/profil/spieler/394150.
Performance history data appended for: https://www.transfermarkt.com/erwin-hoffer/profil/spieler/25785.
Performance history data appended for: https://www.transfermarkt.com/marcus-maier/profil/spieler/195577.
Performance history data appended for: https://www.transfermarkt.com/patson-daka/profil/spieler/365172.
Performance history data appended for: https://www.transfermarkt.com/amar-dedic/profil/spieler/519184.
Performance history data appended for: https://www.transfermarkt.com/masaya-okugawa/profil/spieler/307052.
Performance history data appended for: https://www.transfermarkt.com/albert-vallci/profil/spieler/261935.
Performance history data appended for: https://www.transfermarkt.com/nicolas-seiwald/profil/spieler/404950.
Performance history data appended for: https://www.transfermarkt.com/majeed-ashimeru/profil/spieler/360140.
Performance history data appended for: https://www.transfermarkt.com/antoine-bernede/profil/spieler/395512.
Performance history data appended for: https://www.transfermarkt.com/jerome-onguene/profil/spieler/272638.
Performance history data appended for: https://www.transfermarkt.com/andreas-ulmer/profil/spieler/31196.
Performance history data appended for: https://www.transfermarkt.com/karim-adeyemi/profil/spieler/496094.
Performance history data appended for: https://www.transfermarkt.com/ousmane-diakite/profil/spieler/402007.
Performance history data appended for: https://www.transfermarkt.com/dominik-szoboszlai/profil/spieler/451276.
Performance history data appended for: https://www.transfermarkt.com/carlos-miguel-coronel/profil/spieler/378871.
Performance history data appended for: https://www.transfermarkt.com/andre-ramalho/profil/spieler/175792.

Performance history data appended for: https://www.transfermarkt.com/chukwubuike-adamu/profil/spieler/452477.
Performance history data appended for: https://www.transfermarkt.com/luka-sucic/profil/spieler/502722.
Performance history data appended for: https://www.transfermarkt.com/alexander-walke/profil/spieler/1271.
Performance history data appended for: https://www.transfermarkt.com/sekou-koita/profil/spieler/402010.
Performance history data appended for: https://www.transfermarkt.com/youba-diarra/profil/spieler/564451.
Performance history data appended for: https://www.transfermarkt.com/rasmus-kristensen/profil/spieler/369684.
Performance history data appended for: https://www.transfermarkt.com/mohamed-camara/profil/spieler/543382.
Performance history data appended for: https://www.transfermarkt.com/noah-okafor/profil/spieler/346890.
Performance history data appended for: https://www.transfermarkt.com/maximilian-wober/profil/spieler/263361.
Performance history data appended for: https://www.transfermarkt.com/cican-stankovic/profil/spieler/127679.
Performance history data appended for: https://www.transfermarkt.com/enock-mwepu/profil/spieler/490307.
Performance history data appended for: https://www.transfermarkt.com/oumar-solet/profil/spieler/463665.
Performance history data appended for: https://www.transfermarkt.com/mergim-berisha/profil/spieler/307924.
Performance history data appended for: https://www.transfermarkt.com/zlatko-junuzovic/profil/spieler/31007.
Performance history data appended for: https://www.transfermarkt.com/patrick-farkas/profil/spieler/81675.
Performance history data appended for: https://www.transfermarkt.com/manuel-kuttin/profil/spieler/91410.
Performance history data appended for: https://www.transfermarkt.com/nemanja-rnic/profil/spieler/27236.
Performance history data appended for: https://www.transfermarkt.com/christopher-wernitznig/profil/spieler/77117.
Performance history data appended for: https://www.transfermarkt.com/luka-lochoshvili/profil/spieler/345189.
Performance history data appended for: https://www.transfermarkt.com/mario-leitgeb/profil/spieler/52821.
Performance history data appended for: https://www.transfermarkt.com/alexander-kofler/profil/spieler/55569.
Performance history data appended for: https://www.transfermarkt.com/dominik-baumgartner/profil/spieler/206906.
Performance history data appended for: https://www.transfermarkt.com/eliel-peretz/profil/spieler/444018.
Performance history data appended for: https://www.transfermarkt.com/jonathan-scherzer/profil/spieler/196782.
Performance history data appended for: https://www.transfermarkt.com/lukas-schofl/profil/spieler/514440.
Performance history data appended for: https://www.transfermarkt.com/guram-giorbelidze/profil/spieler/330277.
Performance history data appended for: https://www.transfermarkt.com/michael-novak/profil/spieler/77487.
Performance history data appended for: https://www.transfermarkt.com/mario-pavelic/profil/spieler/106866.
Performance history data appended for: https://www.transfermarkt.com/michael-liendl/profil/spieler/17057.
Performance history data appended for: https://www.transfermarkt.com/stefan-peric/profil/spieler/223973.
Performance history data appended for: https://www.transfermarkt.com/dejan-joveljic/profil/spieler/336382.
Performance history data appended for: https://www.transfermarkt.com/matthaus-taferner/profil/spieler/434104.
Performance history data appended for: https://www.transfermarkt.com/fabian-tauchhammer/profil/spieler/428462.
Performance history data appended for: https://www.transfermarkt.com/dario-vizinger/profil/spieler/391340.
Performance history data appended for: https://www.transfermarkt.com/cheikhou-dieng/profil/spieler/225536.
Performance history data appended for: https://www.transfermarkt.com/marc-andre-schmerbock/profil/spieler/145010.
Performance history data appended for: https://www.transfermarkt.com/kai-stratznig/profil/spieler/531217.
Performance history data appended for: https://www.transfermarkt.com/sven-sprangler/profil/spieler/181714.
Performance history data appended for: https://www.transfermarkt.com/marko-soldo/profil/spieler/270598.
Performance history data appended for: https://www.transfermarkt.com/nicolas-meister/profil/spieler/321057.
Performance history data appended for: https://www.transfermarkt.com/marcel-tanzmayr/profil/spieler/524541.
Performance history data appended for: https://www.transfermarkt.com/george-davies/profil/spieler/273065.
Performance history data appended for: https://www.transfermarkt.com/christoph-halper/profil/spieler/308086.
Performance history data appended for: https://www.transfermarkt.com/christoph-riegler/profil/spieler/122899.
Performance history data appended for: https://www.transfermarkt.com/emilian-metu/profil/spieler/580622.
Performance history data appended for: https://www.transfermarkt.com/robert-ljubicic/profil/spieler/353634.
Performance history data appended for: https://www.transfermarkt.com/ahmet-muhamedbegovic/profil/spieler/271323.
Performance history data appended for: https://www.transfermarkt.com/peter-pokorny/profil/spieler/490595.
Performance history data appended for: https://www.transfermarkt.com/reza-asadi/profil/spieler/408805.
Performance history data appended for: https://www.transfermarkt.com/martin-majnovics/profil/spieler/394609.
Performance history data appended for: https://www.transfermarkt.com/michael-blauensteiner/profil/spieler/195854.
Performance history data appended for: https://www.transfermarkt.com/manuel-maranda/profil/spieler/287995.
Performance history data appended for: https://www.transfermarkt.com/michael-steinwender/profil/spieler/375434.
Performance history data appended for: https://www.transfermarkt.com/armin-gremsl/profil/spieler/159758.
Performance history data appended for: https://www.transfermarkt.com/alexander-schmidt/profil/spieler/307939.
Performance history data appended for: https://www.transfermarkt.com/dor-hugi/profil/spieler/293602.
Performance history data appended for: https://www.transfermarkt.com/kofi-schulz/profil/spieler/192539.
Performance history data appended for: https://www.transfermarkt.com/daniel-luxbacher/profil/spieler/81710.
Performance history data appended for: https://www.transfermarkt.com/lukas-grozurek/profil/spieler/75829.
Performance history data appended for: https://www.transfermarkt.com/luan/profil/spieler/349820.
Performance history data appended for: https://www.transfermarkt.com/daniel-drescher/profil/spieler/49510.
Performance history data appended for: https://www.transfermarkt.com/daniel-schutz/profil/spieler/52245.
Performance history data appended for: https://www.transfermarkt.com/christoph-messerer/profil/spieler/646845.
Performance history data appended for: https://www.transfermarkt.com/thorsten-schick/profil/spieler/55574.
Performance history data appended for: https://www.transfermarkt.com/dejan-ljubicic/profil/spieler/287188.
Performance history data appended for: https://www.transfermarkt.com/dejan-petrovic/profil/spieler/320859.
Performance history data appended for: https://www.transfermarkt.com/philipp-schobesberger/profil/spieler/190848.
Performance history data appended for: https://www.transfermarkt.com/leo-greiml/profil/spieler/434110.
Performance history data appended for: https://www.transfermarkt.com/filip-stojkovic/profil/spieler/139751.
Performance history data appended for: https://www.transfermarkt.com/melih-ibrahimoglu/profil/spieler/391555.
Performance history data appended for: https://www.transfermarkt.com/christopher-dibon/profil/spieler/54607.
Performance history data appended for: https://www.transfermarkt.com/christoph-knasmullner/profil/spieler/59068.
Performance history data appended for: https://www.transfermarkt.com/adrian-hajdari/profil/spieler/388304.
Performance history data appended for: https://www.transfermarkt.com/paul-gartler/profil/spieler/223957.
Performance history data appended for: https://www.transfermarkt.com/marcel-ritzmaier/profil/spieler/84162.
Performance history data appended for: https://www.transfermarkt.com/srdjan-grahovac/profil/spieler/123158.
Performance history data appended for: https://www.transfermarkt.com/yusuf-demir/profil/spieler/548031.

Performance history data appended for: https://www.transfermarkt.com/kelvin-arase/profil/spieler/321048.
Performance history data appended for: https://www.transfermarkt.com/lion-schuster/profil/spieler/391560.
Performance history data appended for: https://www.transfermarkt.com/dalibor-velimirovic/profil/spieler/437891.
Performance history data appended for: https://www.transfermarkt.com/deni-alar/profil/spieler/42004.
Performance history data appended for: https://www.transfermarkt.com/lukas-sulzbacher/profil/spieler/375355.
Performance history data appended for: https://www.transfermarkt.com/paul-gobara/profil/spieler/353915.
Performance history data appended for: https://www.transfermarkt.com/dragoljub-savic/profil/spieler/574656.
Performance history data appended for: https://www.transfermarkt.com/taxiarchis-fountas/profil/spieler/192409.
Performance history data appended for: https://www.transfermarkt.com/bernhard-unger/profil/spieler/341761.
Performance history data appended for: https://www.transfermarkt.com/mateo-barac/profil/spieler/329629.
Performance history data appended for: https://www.transfermarkt.com/maximilian-ullmann/profil/spieler/239934.
Performance history data appended for: https://www.transfermarkt.com/richard-strebinger/profil/spieler/93768.
Performance history data appended for: https://www.transfermarkt.com/koya-kitagawa/profil/spieler/290705.
Performance history data appended for: https://www.transfermarkt.com/maximilian-hofmann/profil/spieler/131231.
Performance history data appended for: https://www.transfermarkt.com/ercan-kara/profil/spieler/320701.
Performance history data appended for: https://www.transfermarkt.com/tamas-szanto/profil/spieler/235529.
Performance history data appended for: https://www.transfermarkt.com/mario-sonnleitner/profil/spieler/18297.
Performance history data appended for: https://www.transfermarkt.com/dardan-shabanhaxhaj/profil/spieler/452464.
Performance history data appended for: https://www.transfermarkt.com/jon-gorenc-stankovic/profil/spieler/245034.
Performance history data appended for: https://www.transfermarkt.com/amadou-dante/profil/spieler/649087.
Performance history data appended for: https://www.transfermarkt.com/andreas-kuen/profil/spieler/186798.
Performance history data appended for: https://www.transfermarkt.com/sandro-ingolitsch/profil/spieler/286627.
Performance history data appended for: https://www.transfermarkt.com/paul-komposch/profil/spieler/452461.
Performance history data appended for: https://www.transfermarkt.com/otar-kiteishvili/profil/spieler/352596.
Performance history data appended for: https://www.transfermarkt.com/francisco-mwepu/profil/spieler/632872.
Performance history data appended for: https://www.transfermarkt.com/jusuf-gazibegovic/profil/spieler/393745.
Performance history data appended for: https://www.transfermarkt.com/lukas-jager/profil/spieler/120206.
Performance history data appended for: https://www.transfermarkt.com/sandro-schendl/profil/spieler/527596.
Performance history data appended for: https://www.transfermarkt.com/vincent-trummer/profil/spieler/365589.
Performance history data appended for: https://www.transfermarkt.com/tobias-schutzenauer/profil/spieler/243237.
Performance history data appended for: https://www.transfermarkt.com/luka-maric/profil/spieler/432859.
Performance history data appended for: https://www.transfermarkt.com/niklas-geyrhofer/profil/spieler/394008.
Performance history data appended for: https://www.transfermarkt.com/tobias-koch/profil/spieler/434103.
Performance history data appended for: https://www.transfermarkt.com/stefan-hierlander/profil/spieler/59053.
Performance history data appended for: https://www.transfermarkt.com/bekim-balaj/profil/spieler/99137.
Performance history data appended for: https://www.transfermarkt.com/emeka-eze/profil/spieler/498517.
Performance history data appended for: https://www.transfermarkt.com/kevin-friesenbichler/profil/spieler/106848.
Performance history data appended for: https://www.transfermarkt.com/gregory-wuthrich/profil/spieler/203125.
Performance history data appended for: https://www.transfermarkt.com/ivan-ljubic/profil/spieler/250028.
Performance history data appended for: https://www.transfermarkt.com/philipp-huspek/profil/spieler/59057.
Performance history data appended for: https://www.transfermarkt.com/david-nemeth/profil/spieler/451906.
Performance history data appended for: https://www.transfermarkt.com/jakob-jantscher/profil/spieler/52269.
Performance history data appended for: https://www.transfermarkt.com/sebastian-zettl/profil/spieler/434106.
Performance history data appended for: https://www.transfermarkt.com/jorg-siebenhandl/profil/spieler/59009.
Performance history data appended for: https://www.transfermarkt.com/alain-wiss/profil/spieler/58165.
Performance history data appended for: https://www.transfermarkt.com/jakob-odehnal/profil/spieler/526353.
Performance history data appended for: https://www.transfermarkt.com/aljaz-casar/profil/spieler/682519.
Performance history data appended for: https://www.transfermarkt.com/manuel-thurnwald/profil/spieler/307485.
Performance history data appended for: https://www.transfermarkt.com/lars-nussbaumer/profil/spieler/407503.
Performance history data appended for: https://www.transfermarkt.com/daniel-maderner/profil/spieler/195741.
Performance history data appended for: https://www.transfermarkt.com/nana-kofi-babil/profil/spieler/734819.
Performance history data appended for: https://www.transfermarkt.com/marco-meilinger/profil/spieler/79607.
Performance history data appended for: https://www.transfermarkt.com/berkay-dabanli/profil/spieler/121528.
Performance history data appended for: https://www.transfermarkt.com/manfred-fischer/profil/spieler/269093.
Performance history data appended for: https://www.transfermarkt.com/ogulcan-bekar/profil/spieler/375358.
Performance history data appended for: https://www.transfermarkt.com/nosa-iyobosa-edokpolor/profil/spieler/276841.
Performance history data appended for: https://www.transfermarkt.com/tino-casali/profil/spieler/169271.
Performance history data appended for: https://www.transfermarkt.com/mario-stefel/profil/spieler/356558.
Performance history data appended for: https://www.transfermarkt.com/chinedu-obasi/profil/spieler/41663.
Performance history data appended for: https://www.transfermarkt.com/jan-zwischenbrugger/profil/spieler/83617.
Performance history data appended for: https://www.transfermarkt.com/emir-karic/profil/spieler/286596.
Performance history data appended for: https://www.transfermarkt.com/anderson/profil/spieler/494830.
Performance history data appended for: https://www.transfermarkt.com/philipp-netzer/profil/spieler/17084.
Performance history data appended for: https://www.transfermarkt.com/david-bumberger/profil/spieler/321850.
Performance history data appended for: https://www.transfermarkt.com/johannes-tartarotti/profil/spieler/307871.
Performance history data appended for: https://www.transfermarkt.com/samuel-oum-gouet/profil/spieler/452238.
Performance history data appended for: https://www.transfermarkt.com/frantz-pangop/profil/spieler/266954.
Performance history data appended for: https://www.transfermarkt.com/daniel-nussbaumer/profil/spieler/307824.
Performance history data appended for: https://www.transfermarkt.com/emanuel-schreiner/profil/spieler/59132.
Performance history data appended for: https://www.transfermarkt.com/martin-kobras/profil/spieler/51719.
Performance history data appended for: https://www.transfermarkt.com/renny-smith/profil/spieler/291895.
Performance history data appended for: https://www.transfermarkt.com/florian-toplitsch/profil/spieler/83584.
Performance history data appended for: https://www.transfermarkt.com/felix-kerber/profil/spieler/524490.
Performance history data appended for: https://www.transfermarkt.com/zlatko-dedic/profil/spieler/28835.
Performance history data appended for: https://www.transfermarkt.com/tobias-anselm/profil/spieler/321847.
Performance history data appended for: https://www.transfermarkt.com/stefan-lauf/profil/spieler/604548.
Performance history data appended for: https://www.transfermarkt.com/david-gugganig/profil/spieler/223960.

Performance history data appended for: https://www.transfermarkt.com/kelvin-yeboah/profil/spieler/589737.
Performance history data appended for: https://www.transfermarkt.com/fabian-koch/profil/spieler/59069.
Performance history data appended for: https://www.transfermarkt.com/ferdinand-oswald/profil/spieler/58360.
Performance history data appended for: https://www.transfermarkt.com/johannes-naschberger/profil/spieler/321874.
Performance history data appended for: https://www.transfermarkt.com/zan-rogelj/profil/spieler/371861.
Performance history data appended for: https://www.transfermarkt.com/nikolai-baden-frederiksen/profil/spieler/400550.
Performance history data appended for: https://www.transfermarkt.com/thanos-petsos/profil/spieler/82110.
Performance history data appended for: https://www.transfermarkt.com/stefan-hager/profil/spieler/158179.
Performance history data appended for: https://www.transfermarkt.com/nemanja-celic/profil/spieler/353899.
Performance history data appended for: https://www.transfermarkt.com/raffael-behounek/profil/spieler/321095.
Performance history data appended for: https://www.transfermarkt.com/ignacio-jauregui/profil/spieler/282469.
Performance history data appended for: https://www.transfermarkt.com/bruno-soares/profil/spieler/104545.
Performance history data appended for: https://www.transfermarkt.com/simon-beccari/profil/spieler/364558.
Performance history data appended for: https://www.transfermarkt.com/david-schnegg/profil/spieler/378260.
Performance history data appended for: https://www.transfermarkt.com/benjamin-pranter/profil/spieler/58963.
Performance history data appended for: https://www.transfermarkt.com/julian-golles/profil/spieler/339826.
Performance history data appended for: https://www.transfermarkt.com/florian-rieder/profil/spieler/317847.
Performance history data appended for: https://www.transfermarkt.com/kilian-bauernfeind/profil/spieler/524475.
Performance history data appended for: https://www.transfermarkt.com/benjamin-ozegovic/profil/spieler/319825.
Performance history data appended for: https://www.transfermarkt.com/florian-buchacher/profil/spieler/52773.
Performance history data appended for: https://www.transfermarkt.com/husein-balic/profil/spieler/241803.
Performance history data appended for: https://www.transfermarkt.com/valentino-muller/profil/spieler/307817.
Performance history data appended for: https://www.transfermarkt.com/christian-ramsebner/profil/spieler/37820.
Performance history data appended for: https://www.transfermarkt.com/thomas-sabitzer/profil/spieler/394032.
Performance history data appended for: https://www.transfermarkt.com/stefan-haudum/profil/spieler/156681.
Performance history data appended for: https://www.transfermarkt.com/mamoudou-karamoko/profil/spieler/646782.
Performance history data appended for: https://www.transfermarkt.com/thomas-goiginger/profil/spieler/189912.
Performance history data appended for: https://www.transfermarkt.com/thomas-turner/profil/spieler/316729.
Performance history data appended for: https://www.transfermarkt.com/philipp-wiesinger/profil/spieler/159139.
Performance history data appended for: https://www.transfermarkt.com/tobias-lawal/profil/spieler/393686.
Performance history data appended for: https://www.transfermarkt.com/dominik-reiter/profil/spieler/307667.
Performance history data appended for: https://www.transfermarkt.com/petar-filipovic/profil/spieler/85922.
Performance history data appended for: https://www.transfermarkt.com/yevgen-cheberko/profil/spieler/343153.
Performance history data appended for: https://www.transfermarkt.com/andreas-gruber/profil/spieler/194477.
Performance history data appended for: https://www.transfermarkt.com/johannes-eggestein/profil/spieler/251303.
Performance history data appended for: https://www.transfermarkt.com/gernot-trauner/profil/spieler/59145.
Performance history data appended for: https://www.transfermarkt.com/reinhold-ranftl/profil/spieler/83119.
Performance history data appended for: https://www.transfermarkt.com/james-holland/profil/spieler/43158.
Performance history data appended for: https://www.transfermarkt.com/andres-andrade/profil/spieler/403808.
Performance history data appended for: https://www.transfermarkt.com/ibrahima-drame/profil/spieler/649028.
Performance history data appended for: https://www.transfermarkt.com/peter-michorl/profil/spieler/158106.
Performance history data appended for: https://www.transfermarkt.com/marvin-potzmann/profil/spieler/106869.
Performance history data appended for: https://www.transfermarkt.com/marko-raguz/profil/spieler/307664.
Performance history data appended for: https://www.transfermarkt.com/rene-renner/profil/spieler/212333.
Performance history data appended for: https://www.transfermarkt.com/patrick-plojer/profil/spieler/434111.
Performance history data appended for: https://www.transfermarkt.com/alexander-schlager/profil/spieler/186374.
Performance history data appended for: https://www.transfermarkt.com/mads-emil-madsen/profil/spieler/422950.
Performance history data appended for: https://www.transfermarkt.com/thomas-gebauer/profil/spieler/12137.
Performance history data appended for: https://www.transfermarkt.com/lukas-grgic/profil/spieler/224871.
Performance history data appended for: https://www.transfermarkt.com/stefan-rakowitz/profil/spieler/76422.
Performance history data appended for: https://www.transfermarkt.com/julius-ertlthaler/profil/spieler/286622.
Performance history data appended for: https://www.transfermarkt.com/lukas-ried/profil/spieler/194770.
Performance history data appended for: https://www.transfermarkt.com/raphael-sallinger/profil/spieler/225360.
Performance history data appended for: https://www.transfermarkt.com/sascha-horvath/profil/spieler/186365.
Performance history data appended for: https://www.transfermarkt.com/jurgen-heil/profil/spieler/271223.
Performance history data appended for: https://www.transfermarkt.com/alexander-burgstaller/profil/spieler/307554.
Performance history data appended for: https://www.transfermarkt.com/seifedin-chabbi/profil/spieler/106862.
Performance history data appended for: https://www.transfermarkt.com/abdoul-yoda/profil/spieler/811856.
Performance history data appended for: https://www.transfermarkt.com/felix-luckeneder/profil/spieler/156691.
Performance history data appended for: https://www.transfermarkt.com/samson-tijani/profil/spieler/666613.
Performance history data appended for: https://www.transfermarkt.com/rajko-rep/profil/spieler/80525.
Performance history data appended for: https://www.transfermarkt.com/philipp-sturm/profil/spieler/307696.
Performance history data appended for: https://www.transfermarkt.com/rene-swete/profil/spieler/181454.
Performance history data appended for: https://www.transfermarkt.com/florian-faist/profil/spieler/255287.
Performance history data appended for: https://www.transfermarkt.com/manfred-gollner/profil/spieler/89055.
Performance history data appended for: https://www.transfermarkt.com/hamidou-maiga/profil/spieler/364851.
Performance history data appended for: https://www.transfermarkt.com/lukas-fadinger/profil/spieler/394018.
Performance history data appended for: https://www.transfermarkt.com/lukas-gabbichler/profil/spieler/341762.
Performance history data appended for: https://www.transfermarkt.com/christian-klem/profil/spieler/58948.
Performance history data appended for: https://www.transfermarkt.com/andreas-lienhart/profil/spieler/32394.
Performance history data appended for: https://www.transfermarkt.com/stefan-golles/profil/spieler/307381.
Performance history data appended for: https://www.transfermarkt.com/dario-tadic/profil/spieler/50860.
Performance history data appended for: https://www.transfermarkt.com/bakary-nimaga/profil/spieler/257730.
Performance history data appended for: https://www.transfermarkt.com/michael-huber/profil/spieler/72146.
Performance history data appended for: https://www.transfermarkt.com/michael-john-lema/profil/spieler/317450.
Performance history data appended for: https://www.transfermarkt.com/thomas-rotter/profil/spieler/119231.
Performance history data appended for: https://www.transfermarkt.com/tobias-kainz/profil/spieler/69741.

Performance history data appended for: https://www.transfermarkt.com/thomas-reifeltshammer/profil/spieler/77612.
Performance history data appended for: https://www.transfermarkt.com/kennedy-boateng/profil/spieler/451317.
Performance history data appended for: https://www.transfermarkt.com/samuel-sahin-radlinger/profil/spieler/77563.
Performance history data appended for: https://www.transfermarkt.com/constantin-reiner/profil/spieler/286643.
Performance history data appended for: https://www.transfermarkt.com/felix-seiwald/profil/spieler/394070.
Performance history data appended for: https://www.transfermarkt.com/ante-bajic/profil/spieler/282918.
Performance history data appended for: https://www.transfermarkt.com/lukas-gutlbauer/profil/spieler/371430.
Performance history data appended for: https://www.transfermarkt.com/markus-lackner/profil/spieler/82536.
Performance history data appended for: https://www.transfermarkt.com/seth-paintsil/profil/spieler/372813.
Performance history data appended for: https://www.transfermarkt.com/sadam-sulley/profil/spieler/437600.
Performance history data appended for: https://www.transfermarkt.com/murat-satin/profil/spieler/225687.
Performance history data appended for: https://www.transfermarkt.com/valentin-grubeck/profil/spieler/159581.
Performance history data appended for: https://www.transfermarkt.com/daniel-edward-daniliuc/profil/spieler/354052.
Performance history data appended for: https://www.transfermarkt.com/marcel-ziegl/profil/spieler/59152.
Performance history data appended for: https://www.transfermarkt.com/stefan-nutz/profil/spieler/106171.
Performance history data appended for: https://www.transfermarkt.com/canillas/profil/spieler/383246.
Performance history data appended for: https://www.transfermarkt.com/michael-lercher/profil/spieler/186369.
Performance history data appended for: https://www.transfermarkt.com/marcel-canadi/profil/spieler/223953.
Performance history data appended for: https://www.transfermarkt.com/luca-meisl/profil/spieler/307641.
Performance history data appended for: https://www.transfermarkt.com/bernd-gschweidl/profil/spieler/167350.
Performance history data appended for: https://www.transfermarkt.com/manuel-haas/profil/spieler/186363.
Performance history data appended for: https://www.transfermarkt.com/arne-ammerer/profil/spieler/240653.
Performance history data appended for: https://www.transfermarkt.com/daniel-offenbacher/profil/spieler/83505.
Performance history data appended for: https://www.transfermarkt.com/balakiyem-takougnadi/profil/spieler/122132.
Performance history data appended for: https://www.transfermarkt.com/julian-wiessmeier/profil/spieler/93559.
Performance history data appended for: https://www.transfermarkt.com/manuel-kerhe/profil/spieler/52369.
Performance history data appended for: https://www.transfermarkt.com/filip-borsos/profil/spieler/445038.
Performance history data appended for: https://www.transfermarkt.com/marco-grull/profil/spieler/391766.
Performance history data appended for: https://www.transfermarkt.com/elias-pereyra/profil/spieler/576027.
Performance history data appended for: https://www.transfermarkt.com/marcelo-herrera/profil/spieler/621369.
Performance history data appended for: https://www.transfermarkt.com/adolfo-gaich/profil/spieler/608469.
Performance history data appended for: https://www.transfermarkt.com/geronimo-poblete/profil/spieler/216714.
Performance history data appended for: https://www.transfermarkt.com/adam-bareiro/profil/spieler/514120.
Performance history data appended for: https://www.transfermarkt.com/marcos-senesi/profil/spieler/469781.
Performance history data appended for: https://www.transfermarkt.com/ruben-botta/profil/spieler/88542.
Performance history data appended for: https://www.transfermarkt.com/sergio-vittor/profil/spieler/91597.
Performance history data appended for: https://www.transfermarkt.com/daniel-osvaldo/profil/spieler/37389.
Performance history data appended for: https://www.transfermarkt.com/sebastian-dubarbier/profil/spieler/55866.
Performance history data appended for: https://www.transfermarkt.com/juan-manuel-cruz/profil/spieler/748316.
Performance history data appended for: https://www.transfermarkt.com/sebastian-benega/profil/spieler/606271.
Performance history data appended for: https://www.transfermarkt.com/franco-quinteros/profil/spieler/567241.
Performance history data appended for: https://www.transfermarkt.com/israel-damonte/profil/spieler/20129.
Performance history data appended for: https://www.transfermarkt.com/matias-moya/profil/spieler/476616.
Performance history data appended for: https://www.transfermarkt.com/federico-torres/profil/spieler/728264.
Performance history data appended for: https://www.transfermarkt.com/santiago-gallucci/profil/spieler/113129.
Performance history data appended for: https://www.transfermarkt.com/gervasio-nunez/profil/spieler/55211.
Performance history data appended for: https://www.transfermarkt.com/marcelo-meli/profil/spieler/263557.
Performance history data appended for: https://www.transfermarkt.com/mauro-barraza/profil/spieler/612632.
Performance history data appended for: https://www.transfermarkt.com/diego-rodriguez/profil/spieler/90800.
Performance history data appended for: https://www.transfermarkt.com/francisco-manenti/profil/spieler/653690.
Performance history data appended for: https://www.transfermarkt.com/dany-cure/profil/spieler/258740.
Performance history data appended for: https://www.transfermarkt.com/cristian-chavez/profil/spieler/70132.
Performance history data appended for: https://www.transfermarkt.com/emanuel-romero/profil/spieler/612633.
Performance history data appended for: https://www.transfermarkt.com/leonardo-villalba/profil/spieler/269817.
Performance history data appended for: https://www.transfermarkt.com/joao-rodriguez/profil/spieler/253125.
Performance history data appended for: https://www.transfermarkt.com/leonel-ferroni/profil/spieler/548903.
Performance history data appended for: https://www.transfermarkt.com/nicolas-femia/profil/spieler/691601.
Performance history data appended for: https://www.transfermarkt.com/facundo-melivilo/profil/spieler/134564.
Performance history data appended for: https://www.transfermarkt.com/marcos-rouzies/profil/spieler/649997.
Performance history data appended for: https://www.transfermarkt.com/facundo-barboza/profil/spieler/422395.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/marcelo-freites/profil/spieler/702886.
Performance history data appended for: https://www.transfermarkt.com/joaquin-mateo/profil/spieler/544164.
Performance history data appended for: https://www.transfermarkt.com/christian-almeida/profil/spieler/195936.
Performance history data appended for: https://www.transfermarkt.com/enzo-ybanez/profil/spieler/534034.
Performance history data appended for: https://www.transfermarkt.com/nahuel-arena/profil/spieler/552629.
Performance history data appended for: https://www.transfermarkt.com/tomas-cardona/profil/spieler/422700.
Performance history data appended for: https://www.transfermarkt.com/andres-mehring/profil/spieler/240903.
Performance history data appended for: https://www.transfermarkt.com/joaquin-varela/profil/spieler/553421.
Performance history data appended for: https://www.transfermarkt.com/juan-brunetta/profil/spieler/466268.
Performance history data appended for: https://www.transfermarkt.com/juan-sanchez-mino/profil/spieler/169249.
Performance history data appended for: https://www.transfermarkt.com/gaston-silva/profil/spieler/189452.
Performance history data appended for: https://www.transfermarkt.com/martin-campana/profil/spieler/91755.
Performance history data appended for: https://www.transfermarkt.com/cristian-chavez/profil/spieler/70132.
Performance history data appended for: https://www.transfermarkt.com/sebastian-sosa/profil/spieler/76592.
Performance history data appended for: https://www.transfermarkt.com/facundo-bertoglio/profil/spieler/107525.
Performance history data appended for: https://www.transfermarkt.com/roman-martinez/profil/spieler/53134.
Performance history data appended for: https://www.transfermarkt.com/sebastian-rincon/profil/spieler/223917.
Performance history data appended for: https://www.transfermarkt.com/fernando-evangelista/profil/spieler/240058.
Performance history data appended for: https://www.transfermarkt.com/yoel-juarez/profil/spieler/660286.
Performance history data appended for: https://www.transfermarkt.com/nazareno-solis/profil/spieler/419660.
Performance history data appended for: https://www.transfermarkt.com/matias-fritzler/profil/spieler/54557.
Performance history data appended for: https://www.transfermarkt.com/marcelo-estigarribia/profil/spieler/76329.
Performance history data appended for: https://www.transfermarkt.com/joaquin-hass/profil/spieler/649786.
Performance history data appended for: https://www.transfermarkt.com/juan-cruz-zurbriggen/profil/spieler/728222.
Performance history data appended for: https://www.transfermarkt.com/tomas-moschion/profil/spieler/631887.
Performance history data appended for: https://www.transfermarkt.com/gaston-diaz/profil/spieler/68748.
Performance history data appended for: https://www.transfermarkt.com/fernando-zuqui/profil/spieler/248763.
Performance history data appended for: https://www.transfermarkt.com/agustin-doffo/profil/spieler/374858.
Performance history data appended for: https://www.transfermarkt.com/jose-luis-sinisterra/profil/spieler/463055.
Performance history data appended for: https://www.transfermarkt.com/guillermo-sara/profil/spieler/87409.
Performance history data appended for: https://www.transfermarkt.com/matias-vera/profil/spieler/745786.
Performance history data appended for: https://www.transfermarkt.com/lautaro-valenti/profil/spieler/625202.
Performance history data appended for: https://www.transfermarkt.com/joaquin-arzura/profil/spieler/288005.
Performance history data appended for: https://www.transfermarkt.com/nicolas-cordero/profil/spieler/371840.
Performance history data appended for: https://www.transfermarkt.com/javier-mendoza/profil/spieler/300309.
Performance history data appended for: https://www.transfermarkt.com/esteban-rolon/profil/spieler/399887.
Performance history data appended for: https://www.transfermarkt.com/mauro-bogado/profil/spieler/54822.
Performance history data appended for: https://www.transfermarkt.com/mariano-bareiro/profil/spieler/352326.
Performance history data appended for: https://www.transfermarkt.com/rodrigo-gomez/profil/spieler/247672.
Performance history data appended for: https://www.transfermarkt.com/nicolas-romat/profil/spieler/67827.
Performance history data appended for: https://www.transfermarkt.com/adrian-calello/profil/spieler/55911.
Performance history data appended for: https://www.transfermarkt.com/fernando-pellegrino/profil/spieler/125843.
Performance history data appended for: https://www.transfermarkt.com/fernando-cosciuc/profil/spieler/503368.
Performance history data appended for: https://www.transfermarkt.com/gonzalo-jara/profil/spieler/40429.
Performance history data appended for: https://www.transfermarkt.com/gaston-fernandez/profil/spieler/23882.
Performance history data appended for: https://www.transfermarkt.com/enzo-kalinski/profil/spieler/67818.
Performance history data appended for: https://www.transfermarkt.com/mauricio-rosales/profil/spieler/251619.
Performance history data appended for: https://www.transfermarkt.com/facundo-sanchez/profil/spieler/107523.
Performance history data appended for: https://www.transfermarkt.com/nahuel-estevez/profil/spieler/552472.
Performance history data appended for: https://www.transfermarkt.com/marcos-rojo/profil/spieler/93176.
Performance history data appended for: https://www.transfermarkt.com/alexis-mac-allister/profil/spieler/534033.
Performance history data appended for: https://www.transfermarkt.com/agustin-almendra/profil/spieler/491698.
Performance history data appended for: https://www.transfermarkt.com/sebastian-perez/profil/spieler/182108.
Performance history data appended for: https://www.transfermarkt.com/edwin-cardona/profil/spieler/119342.
Performance history data appended for: https://www.transfermarkt.com/daniele-de-rossi/profil/spieler/5947.
Performance history data appended for: https://www.transfermarkt.com/ivan-marcone/profil/spieler/90451.
Performance history data appended for: https://www.transfermarkt.com/federico-bravo/profil/spieler/266775.
Performance history data appended for: https://www.transfermarkt.com/franco-pizzicanella/profil/spieler/424046.
Performance history data appended for: https://www.transfermarkt.com/lucas-martinez-quarta/profil/spieler/373373.
Performance history data appended for: https://www.transfermarkt.com/exequiel-palacios/profil/spieler/401578.
Performance history data appended for: https://www.transfermarkt.com/luis-leal/profil/spieler/158419.
Performance history data appended for: https://www.transfermarkt.com/cristian-lema/profil/spieler/147128.
Performance history data appended for: https://www.transfermarkt.com/stefano-callegari/profil/spieler/556300.
Performance history data appended for: https://www.transfermarkt.com/juan-manuel-requena/profil/spieler/637902.
Performance history data appended for: https://www.transfermarkt.com/cristian-insaurralde/profil/spieler/238140.
Performance history data appended for: https://www.transfermarkt.com/leonel-ferroni/profil/spieler/548903.
Performance history data appended for: https://www.transfermarkt.com/ivan-maggi/profil/spieler/708874.
Performance history data appended for: https://www.transfermarkt.com/jose-luis-rodriguez/profil/spieler/430339.
Performance history data appended for: https://www.transfermarkt.com/mateo-cassierra/profil/spieler/362667.
Performance history data appended for: https://www.transfermarkt.com/david-barbona/profil/spieler/356089.
Performance history data appended for: https://www.transfermarkt.com/neri-cardozo/profil/spieler/19955.
Performance history data appended for: https://www.transfermarkt.com/julio-gonzalez/profil/spieler/417196.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/alexis-castro/profil/spieler/364602.
Performance history data appended for: https://www.transfermarkt.com/lucio-chiappero/profil/spieler/361719.
Performance history data appended for: https://www.transfermarkt.com/diego-rodriguez/profil/spieler/90800.
Performance history data appended for: https://www.transfermarkt.com/nicolas-avellaneda/profil/spieler/270968.
Performance history data appended for: https://www.transfermarkt.com/matias-barrios/profil/spieler/748212.
Performance history data appended for: https://www.transfermarkt.com/ruben-botta/profil/spieler/88542.
Performance history data appended for: https://www.transfermarkt.com/juan-miritello/profil/spieler/728200.
Performance history data appended for: https://www.transfermarkt.com/neri-cardozo/profil/spieler/19955.
Performance history data appended for: https://www.transfermarkt.com/maximiliano-romero/profil/spieler/365758.
Performance history data appended for: https://www.transfermarkt.com/fabian-cubero/profil/spieler/26438.
Performance history data appended for: https://www.transfermarkt.com/cristian-nunez/profil/spieler/563815.
Performance history data appended for: https://www.transfermarkt.com/tobias-zarate/profil/spieler/742603.
Performance history data appended for: https://www.transfermarkt.com/braian-cufre/profil/spieler/401521.
Performance history data appended for: https://www.transfermarkt.com/lucas-robertone/profil/spieler/457221.
Performance history data appended for: https://www.transfermarkt.com/nicolas-dominguez/profil/spieler/497291.
Performance history data appended for: https://www.transfermarkt.com/isaias-barroza/profil/spieler/728265.
Performance history data appended for: https://www.transfermarkt.com/lautaro-parisi/profil/spieler/610569.
Performance history data appended for: https://www.transfermarkt.com/juan-cruz-kaprof/profil/spieler/282365.
Performance history data appended for: https://www.transfermarkt.com/gaston-alvarez-suarez/profil/spieler/213191.
Performance history data appended for: https://www.transfermarkt.com/diego-nunez/profil/spieler/498133.
Performance history data appended for: https://www.transfermarkt.com/ezequiel-cerica/profil/spieler/440181.
Performance history data appended for: https://www.transfermarkt.com/pablo-alvarez/profil/spieler/55993.
Performance history data appended for: https://www.transfermarkt.com/ruben-zamponi/profil/spieler/11924.
Performance history data appended for: https://www.transfermarkt.com/ezequiel-rescaldani/profil/spieler/164477.
Performance history data appended for: https://www.transfermarkt.com/nicolas-gimenez/profil/spieler/364946.
Performance history data appended for: https://www.transfermarkt.com/javier-mendez/profil/spieler/285772.
Performance history data appended for: https://www.transfermarkt.com/alfredo-pussetto/profil/spieler/323834.
Performance history data appended for: https://www.transfermarkt.com/braian-alvarez/profil/spieler/545618.
Performance history data appended for: https://www.transfermarkt.com/nicolas-mazzola/profil/spieler/90797.
Performance history data appended for: https://www.transfermarkt.com/juan-cavallaro/profil/spieler/221037.
Performance history data appended for: https://www.transfermarkt.com/maximiliano-cuadra/profil/spieler/493001.
Performance history data appended for: https://www.transfermarkt.com/alan-sosa/profil/spieler/545408.
Performance history data appended for: https://www.transfermarkt.com/leonel-rivas/profil/spieler/471655.
Performance history data appended for: https://www.transfermarkt.com/miguel-barbieri/profil/spieler/431703.
Performance history data appended for: https://www.transfermarkt.com/rodrigo-gonzalez/profil/spieler/659589.
Performance history data appended for: https://www.transfermarkt.com/maximiliano-lovera/profil/spieler/441422.
Performance history data appended for: https://www.transfermarkt.com/joaquin-pereyra/profil/spieler/424043.
Performance history data appended for: https://www.transfermarkt.com/nahuel-molina/profil/spieler/424042.
Performance history data appended for: https://www.transfermarkt.com/jeremias-ledesma/profil/spieler/284342.
Performance history data appended for: https://www.transfermarkt.com/nicolas-colazo/profil/spieler/116277.
Performance history data appended for: https://www.transfermarkt.com/cristian-gonzalez/profil/spieler/358738.
Performance history data appended for: https://www.transfermarkt.com/nestor-ortigoza/profil/spieler/26726.
Performance history data appended for: https://www.transfermarkt.com/jonas-aguirre/profil/spieler/149436.
Performance history data appended for: https://www.transfermarkt.com/facundo-medina/profil/spieler/474800.
Performance history data appended for: https://www.transfermarkt.com/leonel-rivas/profil/spieler/471655.
Performance history data appended for: https://www.transfermarkt.com/guido-herrera/profil/spieler/230014.
Performance history data appended for: https://www.transfermarkt.com/nahuel-bustos/profil/spieler/439629.
Performance history data appended for: https://www.transfermarkt.com/mauro-valiente/profil/spieler/621403.
Performance history data appended for: https://www.transfermarkt.com/andres-cubas/profil/spieler/323872.
Performance history data appended for: https://www.transfermarkt.com/carlos-villalba/profil/spieler/652968.
Performance history data appended for: https://www.transfermarkt.com/matias-escudero/profil/spieler/267893.
Performance history data appended for: https://www.transfermarkt.com/federico-mancinelli/profil/spieler/54356.
Performance history data appended for: https://www.transfermarkt.com/agustin-sufi/profil/spieler/441263.
Performance history data appended for: https://www.transfermarkt.com/pablo-cortizo/profil/spieler/66317.
Performance history data appended for: https://www.transfermarkt.com/federico-vietto/profil/spieler/401579.
Performance history data appended for: https://www.transfermarkt.com/hugo-silveira/profil/spieler/263052.
Performance history data appended for: https://www.transfermarkt.com/juan-cruz-franzoni/profil/spieler/576806.
Performance history data appended for: https://www.transfermarkt.com/mathias-abero/profil/spieler/142370.
Performance history data appended for: https://www.transfermarkt.com/gabriel-diaz/profil/spieler/345004.
Performance history data appended for: https://www.transfermarkt.com/gabriel-compagnucci/profil/spieler/538608.
Performance history data appended for: https://www.transfermarkt.com/martin-aruga/profil/spieler/634811.
Performance history data appended for: https://www.transfermarkt.com/gaston-veron/profil/spieler/564001.
Performance history data appended for: https://www.transfermarkt.com/francisco-ilarregui/profil/spieler/339463.
Performance history data appended for: https://www.transfermarkt.com/enzo-ybanez/profil/spieler/534034.
Performance history data appended for: https://www.transfermarkt.com/lucas-ambrogio/profil/spieler/697584.
Performance history data appended for: https://www.transfermarkt.com/maximiliano-centurion/profil/spieler/665933.
Performance history data appended for: https://www.transfermarkt.com/agustin-bolivar/profil/spieler/534623.
Performance history data appended for: https://www.transfermarkt.com/khalil-caraballo/profil/spieler/702885.
Performance history data appended for: https://www.transfermarkt.com/tomas-durso/profil/spieler/534625.
Performance history data appended for: https://www.transfermarkt.com/jhonatan-agudelo/profil/spieler/313426.
Performance history data appended for: https://www.transfermarkt.com/maximiliano-comba/profil/spieler/615182.
Performance history data appended for: https://www.transfermarkt.com/maximiliano-cuadra/profil/spieler/493001.
Performance history data appended for: https://www.transfermarkt.com/brian-mansilla/profil/spieler/373374.
Performance history data appended for: https://www.transfermarkt.com/claudio-spinelli/profil/spieler/504882.
Performance history data appended for: https://www.transfermarkt.com/liam-rose/profil/spieler/329834.
Performance history data appended for: https://www.transfermarkt.com/antonis-martis/profil/spieler/527957.
Performance history data appended for: https://www.transfermarkt.com/mark-milligan/profil/spieler/37372.

Performance history data appended for: https://www.transfermarkt.com/milislav-popovic/profil/spieler/388303.
Performance history data appended for: https://www.transfermarkt.com/matt-derbyshire/profil/spieler/15175.
Performance history data appended for: https://www.transfermarkt.com/tommy-oar/profil/spieler/80708.
Performance history data appended for: https://www.transfermarkt.com/yianni-nicolaou/profil/spieler/607274.
Performance history data appended for: https://www.transfermarkt.com/denis-genreau/profil/spieler/470618.
Performance history data appended for: https://www.transfermarkt.com/walter-scott/profil/spieler/560827.
Performance history data appended for: https://www.transfermarkt.com/ivan-franjic/profil/spieler/48424.
Performance history data appended for: https://www.transfermarkt.com/loic-puyo/profil/spieler/170916.
Performance history data appended for: https://www.transfermarkt.com/benat-etxebarria/profil/spieler/40888.
Performance history data appended for: https://www.transfermarkt.com/charles-mbombwa/profil/spieler/603866.
Performance history data appended for: https://www.transfermarkt.com/aleksandar-jovanovic/profil/spieler/50377.
Performance history data appended for: https://www.transfermarkt.com/moudi-najjar/profil/spieler/566941.
Performance history data appended for: https://www.transfermarkt.com/nick-suman/profil/spieler/477136.
Performance history data appended for: https://www.transfermarkt.com/jake-mcging/profil/spieler/355721.
Performance history data appended for: https://www.transfermarkt.com/adam-federici/profil/spieler/4233.
Performance history data appended for: https://www.transfermarkt.com/markel-susaeta/profil/spieler/54245.
Performance history data appended for: https://www.transfermarkt.com/stefan-mauk/profil/spieler/189231.
Performance history data appended for: https://www.transfermarkt.com/yaya-dukuly/profil/spieler/652487.
Performance history data appended for: https://www.transfermarkt.com/noah-smith/profil/spieler/722984.
Performance history data appended for: https://www.transfermarkt.com/ben-halloran/profil/spieler/160740.
Performance history data appended for: https://www.transfermarkt.com/nathan-konstandopoulos/profil/spieler/306518.
Performance history data appended for: https://www.transfermarkt.com/joe-gauci/profil/spieler/591844.
Performance history data appended for: https://www.transfermarkt.com/pacifique-niyongabire/profil/spieler/561646.
Performance history data appended for: https://www.transfermarkt.com/james-delianov/profil/spieler/399981.
Performance history data appended for: https://www.transfermarkt.com/dakota-ochsenham/profil/spieler/734488.
Performance history data appended for: https://www.transfermarkt.com/mohamed-toure/profil/spieler/742770.
Performance history data appended for: https://www.transfermarkt.com/george-timotheou/profil/spieler/344677.
Performance history data appended for: https://www.transfermarkt.com/yared-abetew/profil/spieler/652837.
Performance history data appended for: https://www.transfermarkt.com/louis-darrigo/profil/spieler/561650.
Performance history data appended for: https://www.transfermarkt.com/ryan-kitto/profil/spieler/296454.
Performance history data appended for: https://www.transfermarkt.com/tomi-juric/profil/spieler/171820.
Performance history data appended for: https://www.transfermarkt.com/james-troisi/profil/spieler/52585.
Performance history data appended for: https://www.transfermarkt.com/michael-marrone/profil/spieler/111896.
Performance history data appended for: https://www.transfermarkt.com/michael-jakobsen/profil/spieler/8421.
Performance history data appended for: https://www.transfermarkt.com/javi-lopez/profil/spieler/72310.
Performance history data appended for: https://www.transfermarkt.com/alhassan-toure/profil/spieler/692440.
Performance history data appended for: https://www.transfermarkt.com/jordan-elsey/profil/spieler/187355.
Performance history data appended for: https://www.transfermarkt.com/ryan-strain/profil/spieler/549354.
Performance history data appended for: https://www.transfermarkt.com/kusini-yengi/profil/spieler/708099.
Performance history data appended for: https://www.transfermarkt.com/andrew-redmayne/profil/spieler/51975.
Performance history data appended for: https://www.transfermarkt.com/ryan-mcgowan/profil/spieler/54265.
Performance history data appended for: https://www.transfermarkt.com/george-mells/profil/spieler/337278.
Performance history data appended for: https://www.transfermarkt.com/dylan-wenzel-halls/profil/spieler/582754.
Performance history data appended for: https://www.transfermarkt.com/macauley-gillesphey/profil/spieler/267113.
Performance history data appended for: https://www.transfermarkt.com/joe-champness/profil/spieler/539321.
Performance history data appended for: https://www.transfermarkt.com/kai-trewin/profil/spieler/691326.
Performance history data appended for: https://www.transfermarkt.com/josh-brindell-south/profil/spieler/290697.
Performance history data appended for: https://www.transfermarkt.com/jai-ingham/profil/spieler/307784.
Performance history data appended for: https://www.transfermarkt.com/izaack-powell/profil/spieler/650572.
Performance history data appended for: https://www.transfermarkt.com/rahmat-akbari/profil/spieler/543320.
Performance history data appended for: https://www.transfermarkt.com/tom-aldred/profil/spieler/95076.
Performance history data appended for: https://www.transfermarkt.com/jack-hingert/profil/spieler/121903.
Performance history data appended for: https://www.transfermarkt.com/macklin-freke/profil/spieler/631103.
Performance history data appended for: https://www.transfermarkt.com/jordan-courtney-perkins/profil/spieler/691325.
Performance history data appended for: https://www.transfermarkt.com/corey-brown/profil/spieler/187345.
Performance history data appended for: https://www.transfermarkt.com/jamie-young/profil/spieler/13435.
Performance history data appended for: https://www.transfermarkt.com/scott-mcdonald/profil/spieler/13799.
Performance history data appended for: https://www.transfermarkt.com/jay-oshea/profil/spieler/68327.
Performance history data appended for: https://www.transfermarkt.com/danny-kim/profil/spieler/607430.
Performance history data appended for: https://www.transfermarkt.com/kwame-yeboah/profil/spieler/187383.
Performance history data appended for: https://www.transfermarkt.com/jordan-odoherty/profil/spieler/453838.
Performance history data appended for: https://www.transfermarkt.com/daniel-wilmering/profil/spieler/660145.
Performance history data appended for: https://www.transfermarkt.com/mohamed-al-taay/profil/spieler/732828.
Performance history data appended for: https://www.transfermarkt.com/daniel-margush/profil/spieler/414085.
Performance history data appended for: https://www.transfermarkt.com/tate-russell/profil/spieler/589458.
Performance history data appended for: https://www.transfermarkt.com/dylan-mcgowan/profil/spieler/72504.
Performance history data appended for: https://www.transfermarkt.com/nicolai-muller/profil/spieler/39426.
Performance history data appended for: https://www.transfermarkt.com/graham-dorrans/profil/spieler/36608.
Performance history data appended for: https://www.transfermarkt.com/keanu-baccus/profil/spieler/479037.
Performance history data appended for: https://www.transfermarkt.com/kosta-grozos/profil/spieler/500924.
Performance history data appended for: https://www.transfermarkt.com/simon-cox/profil/spieler/37150.
Performance history data appended for: https://www.transfermarkt.com/fabian-monge/profil/spieler/650865.
Performance history data appended for: https://www.transfermarkt.com/jake-trew/profil/spieler/714260.
Performance history data appended for: https://www.transfermarkt.com/jarrod-carluccio/profil/spieler/749273.
Performance history data appended for: https://www.transfermarkt.com/daniel-lopar/profil/spieler/4769.
Performance history data appended for: https://www.transfermarkt.com/phillip-cancar/profil/spieler/716810.
Performance history data appended for: https://www.transfermarkt.com/anthony-lesiotis/profil/spieler/565890.
Performance history data appended for: https://www.transfermarkt.com/vedran-janjetovic/profil/spieler/47194.

Performance history data appended for: https://www.transfermarkt.com/mohamed-adam/profil/spieler/692322.
Performance history data appended for: https://www.transfermarkt.com/patrick-ziegler/profil/spieler/54964.
Performance history data appended for: https://www.transfermarkt.com/noah-pagden/profil/spieler/716586.
Performance history data appended for: https://www.transfermarkt.com/daniel-georgievski/profil/spieler/47615.
Performance history data appended for: https://www.transfermarkt.com/tass-mourdoukoutas/profil/spieler/561049.
Performance history data appended for: https://www.transfermarkt.com/bruce-kamau/profil/spieler/334157.
Performance history data appended for: https://www.transfermarkt.com/matt-simon/profil/spieler/43372.
Performance history data appended for: https://www.transfermarkt.com/kye-rowles/profil/spieler/399990.
Performance history data appended for: https://www.transfermarkt.com/ziggy-gordon/profil/spieler/175841.
Performance history data appended for: https://www.transfermarkt.com/ruon-tongyik/profil/spieler/410067.
Performance history data appended for: https://www.transfermarkt.com/joshua-nisbet/profil/spieler/603863.
Performance history data appended for: https://www.transfermarkt.com/lewis-miller/profil/spieler/603864.
Performance history data appended for: https://www.transfermarkt.com/oliver-bozanic/profil/spieler/43117.
Performance history data appended for: https://www.transfermarkt.com/jack-clisby/profil/spieler/256915.
Performance history data appended for: https://www.transfermarkt.com/louis-khoury/profil/spieler/506211.
Performance history data appended for: https://www.transfermarkt.com/mark-birighitti/profil/spieler/80702.
Performance history data appended for: https://www.transfermarkt.com/daniel-bouman/profil/spieler/411483.
Performance history data appended for: https://www.transfermarkt.com/mark-moric/profil/spieler/496653.
Performance history data appended for: https://www.transfermarkt.com/jair/profil/spieler/148664.
Performance history data appended for: https://www.transfermarkt.com/daniel-de-silva/profil/spieler/259721.
Performance history data appended for: https://www.transfermarkt.com/gianni-stensness/profil/spieler/627472.
Performance history data appended for: https://www.transfermarkt.com/alou-kuol/profil/spieler/748070.
Performance history data appended for: https://www.transfermarkt.com/aidan-munford/profil/spieler/692327.
Performance history data appended for: https://www.transfermarkt.com/adam-pearce/profil/spieler/345701.
Performance history data appended for: https://www.transfermarkt.com/jacob-melling/profil/spieler/181924.
Performance history data appended for: https://www.transfermarkt.com/dylan-ruiz-diaz/profil/spieler/668120.
Performance history data appended for: https://www.transfermarkt.com/ben-folami/profil/spieler/532107.
Performance history data appended for: https://www.transfermarkt.com/robbie-kruse/profil/spieler/51972.
Performance history data appended for: https://www.transfermarkt.com/lleyton-brooks/profil/spieler/742831.
Performance history data appended for: https://www.transfermarkt.com/rudy-gestede/profil/spieler/39908.
Performance history data appended for: https://www.transfermarkt.com/dylan-ryan/profil/spieler/480022.
Performance history data appended for: https://www.transfermarkt.com/jack-palazzolo/profil/spieler/668845.
Performance history data appended for: https://www.transfermarkt.com/liam-mcging/profil/spieler/675114.
Performance history data appended for: https://www.transfermarkt.com/clayton-lewis/profil/spieler/292982.
Performance history data appended for: https://www.transfermarkt.com/stefan-marinovic/profil/spieler/120619.
Performance history data appended for: https://www.transfermarkt.com/jaushua-sotirio/profil/spieler/302818.
Performance history data appended for: https://www.transfermarkt.com/ulises-davila/profil/spieler/108820.
Performance history data appended for: https://www.transfermarkt.com/alex-rufer/profil/spieler/256019.
Performance history data appended for: https://www.transfermarkt.com/te-atawhai-hudson-wihongi/profil/spieler/204766.
Performance history data appended for: https://www.transfermarkt.com/oliver-sail/profil/spieler/290838.
Performance history data appended for: https://www.transfermarkt.com/mirza-muratovic/profil/spieler/613651.
Performance history data appended for: https://www.transfermarkt.com/louis-fenton/profil/spieler/203552.
Performance history data appended for: https://www.transfermarkt.com/joshua-laws/profil/spieler/293742.
Performance history data appended for: https://www.transfermarkt.com/tomer-hemed/profil/spieler/112668.
Performance history data appended for: https://www.transfermarkt.com/david-ball/profil/spieler/121401.
Performance history data appended for: https://www.transfermarkt.com/zac-jones/profil/spieler/485667.
Performance history data appended for: https://www.transfermarkt.com/tim-payne/profil/spieler/149901.
Performance history data appended for: https://www.transfermarkt.com/oskar-van-hattum/profil/spieler/617025.
Performance history data appended for: https://www.transfermarkt.com/cameron-devlin/profil/spieler/399162.
Performance history data appended for: https://www.transfermarkt.com/luke-devere/profil/spieler/80716.
Performance history data appended for: https://www.transfermarkt.com/ben-waine/profil/spieler/539502.
Performance history data appended for: https://www.transfermarkt.com/reno-piscopo/profil/spieler/265093.
Performance history data appended for: https://www.transfermarkt.com/matthew-ridenton/profil/spieler/264457.
Performance history data appended for: https://www.transfermarkt.com/james-mcgarry/profil/spieler/345343.
Performance history data appended for: https://www.transfermarkt.com/sam-sutton/profil/spieler/470986.
Performance history data appended for: https://www.transfermarkt.com/christopher-oikonomidis/profil/spieler/248483.
Performance history data appended for: https://www.transfermarkt.com/james-meredith/profil/spieler/48111.
Performance history data appended for: https://www.transfermarkt.com/andy-keogh/profil/spieler/29419.
Performance history data appended for: https://www.transfermarkt.com/trent-ostler/profil/spieler/692320.
Performance history data appended for: https://www.transfermarkt.com/dino-djulbic/profil/spieler/48295.
Performance history data appended for: https://www.transfermarkt.com/tarek-elrich/profil/spieler/43151.
Performance history data appended for: https://www.transfermarkt.com/vince-lia/profil/spieler/43165.
Performance history data appended for: https://www.transfermarkt.com/gabriel-popovic/profil/spieler/692321.
Performance history data appended for: https://www.transfermarkt.com/daniel-walsh/profil/spieler/692319.
Performance history data appended for: https://www.transfermarkt.com/alex-grant/profil/spieler/225068.
Performance history data appended for: https://www.transfermarkt.com/jackson-lee/profil/spieler/570590.
Performance history data appended for: https://www.transfermarkt.com/riley-warland/profil/spieler/552746.
Performance history data appended for: https://www.transfermarkt.com/rostyn-griffiths/profil/spieler/67715.
Performance history data appended for: https://www.transfermarkt.com/jamie-maclaren/profil/spieler/173591.
Performance history data appended for: https://www.transfermarkt.com/richard-windbichler/profil/spieler/74770.
Performance history data appended for: https://www.transfermarkt.com/mitchell-graham/profil/spieler/613513.
Performance history data appended for: https://www.transfermarkt.com/conor-metcalfe/profil/spieler/522223.
Performance history data appended for: https://www.transfermarkt.com/idrus-abdulahi/profil/spieler/626709.
Performance history data appended for: https://www.transfermarkt.com/benjamin-garuccio/profil/spieler/187359.
Performance history data appended for: https://www.transfermarkt.com/nathaniel-atkinson/profil/spieler/556038.
Performance history data appended for: https://www.transfermarkt.com/craig-noone/profil/spieler/81202.
Performance history data appended for: https://www.transfermarkt.com/tom-glover/profil/spieler/335615.
Performance history data appended for: https://www.transfermarkt.com/scott-galloway/profil/spieler/257415.

Performance history data appended for: https://www.transfermarkt.com/andrew-nabbout/profil/spieler/247289.
Performance history data appended for: https://www.transfermarkt.com/aiden-oneill/profil/spieler/385918.
Performance history data appended for: https://www.transfermarkt.com/adrian-luna/profil/spieler/131113.
Performance history data appended for: https://www.transfermarkt.com/scott-jamieson/profil/spieler/52498.
Performance history data appended for: https://www.transfermarkt.com/kerrin-stokes/profil/spieler/704397.
Performance history data appended for: https://www.transfermarkt.com/taras-gomulka/profil/spieler/794888.
Performance history data appended for: https://www.transfermarkt.com/stefan-colakovski/profil/spieler/714272.
Performance history data appended for: https://www.transfermarkt.com/harrison-delbridge/profil/spieler/318541.
Performance history data appended for: https://www.transfermarkt.com/florin-berenguer/profil/spieler/111040.
Performance history data appended for: https://www.transfermarkt.com/matthew-sutton/profil/spieler/561484.
Performance history data appended for: https://www.transfermarkt.com/curtis-good/profil/spieler/179471.
Performance history data appended for: https://www.transfermarkt.com/raphael-borges-rodrigues/profil/spieler/704398.
Performance history data appended for: https://www.transfermarkt.com/marco-tilio/profil/spieler/565531.
Performance history data appended for: https://www.transfermarkt.com/ryan-scott/profil/spieler/604264.
Performance history data appended for: https://www.transfermarkt.com/lachlan-wales/profil/spieler/499735.
Performance history data appended for: https://www.transfermarkt.com/luke-duzel/profil/spieler/703660.
Performance history data appended for: https://www.transfermarkt.com/tomoki-imai/profil/spieler/255095.
Performance history data appended for: https://www.transfermarkt.com/dylan-pierias/profil/spieler/486972.
Performance history data appended for: https://www.transfermarkt.com/joshua-risdon/profil/spieler/160614.
Performance history data appended for: https://www.transfermarkt.com/joshua-cavallo/profil/spieler/613515.
Performance history data appended for: https://www.transfermarkt.com/brendan-hamill/profil/spieler/147600.
Performance history data appended for: https://www.transfermarkt.com/andrew-durante/profil/spieler/43148.
Performance history data appended for: https://www.transfermarkt.com/apostolos-stamatelopoulos/profil/spieler/547924.
Performance history data appended for: https://www.transfermarkt.com/sebastian-pasquali/profil/spieler/448680.
Performance history data appended for: https://www.transfermarkt.com/tomislav-uskok/profil/spieler/409114.
Performance history data appended for: https://www.transfermarkt.com/filip-kurto/profil/spieler/104376.
Performance history data appended for: https://www.transfermarkt.com/valentino-yuel/profil/spieler/662257.
Performance history data appended for: https://www.transfermarkt.com/ivan-vujica/profil/spieler/240436.
Performance history data appended for: https://www.transfermarkt.com/connor-pain/profil/spieler/257682.
Performance history data appended for: https://www.transfermarkt.com/alessandro-diamanti/profil/spieler/23197.
Performance history data appended for: https://www.transfermarkt.com/besart-berisha/profil/spieler/17257.
Performance history data appended for: https://www.transfermarkt.com/jerry-skotadis/profil/spieler/613653.
Performance history data appended for: https://www.transfermarkt.com/aaron-calver/profil/spieler/255162.
Performance history data appended for: https://www.transfermarkt.com/thiel-iradukunda/profil/spieler/603861.
Performance history data appended for: https://www.transfermarkt.com/victor-sanchez/profil/spieler/63290.
Performance history data appended for: https://www.transfermarkt.com/max-burgess/profil/spieler/343049.
Performance history data appended for: https://www.transfermarkt.com/oskar-dillon/profil/spieler/606651.
Performance history data appended for: https://www.transfermarkt.com/kwabena-appiah-kubi/profil/spieler/230478.
Performance history data appended for: https://www.transfermarkt.com/steven-lustica/profil/spieler/127910.
Performance history data appended for: https://www.transfermarkt.com/lucas-mauragis/profil/spieler/795253.
Performance history data appended for: https://www.transfermarkt.com/noah-james/profil/spieler/471494.
Performance history data appended for: https://www.transfermarkt.com/michael-neill/profil/spieler/265715.
Performance history data appended for: https://www.transfermarkt.com/kaine-sheppard/profil/spieler/237533.
Performance history data appended for: https://www.transfermarkt.com/roy-odonovan/profil/spieler/34629.
Performance history data appended for: https://www.transfermarkt.com/nigel-boogaard/profil/spieler/43116.
Performance history data appended for: https://www.transfermarkt.com/connor-otoole/profil/spieler/434225.
Performance history data appended for: https://www.transfermarkt.com/joe-ledley/profil/spieler/34409.
Performance history data appended for: https://www.transfermarkt.com/ramy-najjarine/profil/spieler/448337.
Performance history data appended for: https://www.transfermarkt.com/angus-thurgate/profil/spieler/559464.
Performance history data appended for: https://www.transfermarkt.com/jason-hoffman/profil/spieler/62839.
Performance history data appended for: https://www.transfermarkt.com/kosta-petratos/profil/spieler/418026.
Performance history data appended for: https://www.transfermarkt.com/jack-simmons/profil/spieler/596086.
Performance history data appended for: https://www.transfermarkt.com/lachlan-jackson/profil/spieler/298883.
Performance history data appended for: https://www.transfermarkt.com/bernie-ibini-isei/profil/spieler/140205.
Performance history data appended for: https://www.transfermarkt.com/steven-ugarkovic/profil/spieler/262971.
Performance history data appended for: https://www.transfermarkt.com/john-koutroumbis/profil/spieler/456583.
Performance history data appended for: https://www.transfermarkt.com/patrick-langlois/profil/spieler/601976.
Performance history data appended for: https://www.transfermarkt.com/lewis-italiano/profil/spieler/204381.
Performance history data appended for: https://www.transfermarkt.com/makis-petratos/profil/spieler/614402.
Performance history data appended for: https://www.transfermarkt.com/ben-kantarovski/profil/spieler/66394.
Performance history data appended for: https://www.transfermarkt.com/nikolai-topor-stanley/profil/spieler/37870.
Performance history data appended for: https://www.transfermarkt.com/obbi-oulare/profil/spieler/314959.
Performance history data appended for: https://www.transfermarkt.com/nicolas-gavory/profil/spieler/182816.
Performance history data appended for: https://www.transfermarkt.com/collins-fai/profil/spieler/250638.
Performance history data appended for: https://www.transfermarkt.com/zinho-vanheusden/profil/spieler/338672.
Performance history data appended for: https://www.transfermarkt.com/laurent-henkinet/profil/spieler/157125.
Performance history data appended for: https://www.transfermarkt.com/mehdi-carcela-gonzalez/profil/spieler/42714.
Performance history data appended for: https://www.transfermarkt.com/merveille-bokadi/profil/spieler/368612.
Performance history data appended for: https://www.transfermarkt.com/jackson-muleka/profil/spieler/549966.
Performance history data appended for: https://www.transfermarkt.com/damjan-pavlovic/profil/spieler/409511.
Performance history data appended for: https://www.transfermarkt.com/arnaud-bodart/profil/spieler/417278.
Performance history data appended for: https://www.transfermarkt.com/samuel-bastien/profil/spieler/289510.
Performance history data appended for: https://www.transfermarkt.com/jean-francois-gillet/profil/spieler/22149.
Performance history data appended for: https://www.transfermarkt.com/felipe-avenatti/profil/spieler/216375.
Performance history data appended for: https://www.transfermarkt.com/moussa-sissako/profil/spieler/536475.
Performance history data appended for: https://www.transfermarkt.com/abdoul-tapsoba/profil/spieler/640735.
Performance history data appended for: https://www.transfermarkt.com/konstantinos-laifis/profil/spieler/121570.

Performance history data appended for: https://www.transfermarkt.com/nicolas-raskin/profil/spieler/422763.
Performance history data appended for: https://www.transfermarkt.com/aleksandar-boljevic/profil/spieler/227532.
Performance history data appended for: https://www.transfermarkt.com/selim-amallah/profil/spieler/377219.
Performance history data appended for: https://www.transfermarkt.com/duje-cop/profil/spieler/46415.
Performance history data appended for: https://www.transfermarkt.com/gojko-cimirot/profil/spieler/150482.
Performance history data appended for: https://www.transfermarkt.com/joachim-carcela-gonzalez/profil/spieler/381965.
Performance history data appended for: https://www.transfermarkt.com/noe-dussenne/profil/spieler/160736.
Performance history data appended for: https://www.transfermarkt.com/laurent-jans/profil/spieler/163724.
Performance history data appended for: https://www.transfermarkt.com/mitchy-ntelo/profil/spieler/706860.
Performance history data appended for: https://www.transfermarkt.com/eddy-sylvestre/profil/spieler/629566.
Performance history data appended for: https://www.transfermarkt.com/michel-ange-balikwisha/profil/spieler/502239.
Performance history data appended for: https://www.transfermarkt.com/eden-shamir/profil/spieler/204111.
Performance history data appended for: https://www.transfermarkt.com/maxime-lestienne/profil/spieler/96454.
Performance history data appended for: https://www.transfermarkt.com/william-balikwisha/profil/spieler/381968.
Performance history data appended for: https://www.transfermarkt.com/sofiane-bouzian/profil/spieler/593378.
Performance history data appended for: https://www.transfermarkt.com/steven-defour/profil/spieler/33866.
Performance history data appended for: https://www.transfermarkt.com/siemen-voet/profil/spieler/460845.
Performance history data appended for: https://www.transfermarkt.com/niklo-dailly/profil/spieler/695769.
Performance history data appended for: https://www.transfermarkt.com/maryan-shved/profil/spieler/359247.
Performance history data appended for: https://www.transfermarkt.com/kerim-mrabti/profil/spieler/225569.
Performance history data appended for: https://www.transfermarkt.com/sheldon-bateau/profil/spieler/113378.
Performance history data appended for: https://www.transfermarkt.com/rocky-bushiri/profil/spieler/511802.
Performance history data appended for: https://www.transfermarkt.com/aster-vranckx/profil/spieler/503881.
Performance history data appended for: https://www.transfermarkt.com/gaetan-coucke/profil/spieler/338651.
Performance history data appended for: https://www.transfermarkt.com/lucas-bijker/profil/spieler/187283.
Performance history data appended for: https://www.transfermarkt.com/geoffry-hairemans/profil/spieler/110292.
Performance history data appended for: https://www.transfermarkt.com/sandy-walsh/profil/spieler/187329.
Performance history data appended for: https://www.transfermarkt.com/lars-coveliers/profil/spieler/429911.
Performance history data appended for: https://www.transfermarkt.com/joachim-van-damme/profil/spieler/74544.
Performance history data appended for: https://www.transfermarkt.com/maxime-wenssens/profil/spieler/570819.
Performance history data appended for: https://www.transfermarkt.com/gustav-engvall/profil/spieler/248024.
Performance history data appended for: https://www.transfermarkt.com/igor-de-camargo/profil/spieler/13023.
Performance history data appended for: https://www.transfermarkt.com/victor-wernersson/profil/spieler/271816.
Performance history data appended for: https://www.transfermarkt.com/trova-boni/profil/spieler/557012.
Performance history data appended for: https://www.transfermarkt.com/rob-schoofs/profil/spieler/157396.
Performance history data appended for: https://www.transfermarkt.com/issa-kabore/profil/spieler/649452.
Performance history data appended for: https://www.transfermarkt.com/yannick-thoelen/profil/spieler/64246.
Performance history data appended for: https://www.transfermarkt.com/thibault-peyre/profil/spieler/170914.
Performance history data appended for: https://www.transfermarkt.com/jordi-vanlerberghe/profil/spieler/235275.
Performance history data appended for: https://www.transfermarkt.com/william-togui/profil/spieler/362291.
Performance history data appended for: https://www.transfermarkt.com/nikola-storm/profil/spieler/183120.
Performance history data appended for: https://www.transfermarkt.com/onur-kaya/profil/spieler/33709.
Performance history data appended for: https://www.transfermarkt.com/jordan-lukaku/profil/spieler/140804.
Performance history data appended for: https://www.transfermarkt.com/didier-lamkel-ze/profil/spieler/442320.
Performance history data appended for: https://www.transfermarkt.com/matheus/profil/spieler/412688.
Performance history data appended for: https://www.transfermarkt.com/faris-haroun/profil/spieler/16617.
Performance history data appended for: https://www.transfermarkt.com/benson-manuel/profil/spieler/322702.
Performance history data appended for: https://www.transfermarkt.com/cristian-benavente/profil/spieler/232859.
Performance history data appended for: https://www.transfermarkt.com/bruny-nsimba/profil/spieler/452584.
Performance history data appended for: https://www.transfermarkt.com/jae-ik-lee/profil/spieler/297709.
Performance history data appended for: https://www.transfermarkt.com/dieumerci-mbokani/profil/spieler/44624.
Performance history data appended for: https://www.transfermarkt.com/nill-de-pauw/profil/spieler/52746.
Performance history data appended for: https://www.transfermarkt.com/alireza-beiranvand/profil/spieler/229081.
Performance history data appended for: https://www.transfermarkt.com/koji-miyoshi/profil/spieler/295060.
Performance history data appended for: https://www.transfermarkt.com/frank-boya/profil/spieler/473201.
Performance history data appended for: https://www.transfermarkt.com/lior-refaelov/profil/spieler/24484.
Performance history data appended for: https://www.transfermarkt.com/martin-hongla/profil/spieler/398808.
Performance history data appended for: https://www.transfermarkt.com/abdoulaye-seck/profil/spieler/265383.
Performance history data appended for: https://www.transfermarkt.com/jean-butez/profil/spieler/290537.
Performance history data appended for: https://www.transfermarkt.com/aurelio-buta/profil/spieler/258039.
Performance history data appended for: https://www.transfermarkt.com/alexis-de-sart/profil/spieler/323713.
Performance history data appended for: https://www.transfermarkt.com/pieter-gerkens/profil/spieler/183383.
Performance history data appended for: https://www.transfermarkt.com/ritchie-de-laet/profil/spieler/55687.
Performance history data appended for: https://www.transfermarkt.com/moustafa-ava-dongo/profil/spieler/708876.
Performance history data appended for: https://www.transfermarkt.com/birger-verstraete/profil/spieler/234193.
Performance history data appended for: https://www.transfermarkt.com/sander-coopman/profil/spieler/279254.
Performance history data appended for: https://www.transfermarkt.com/louis-verstraete/profil/spieler/396841.
Performance history data appended for: https://www.transfermarkt.com/simen-juklerod/profil/spieler/230985.
Performance history data appended for: https://www.transfermarkt.com/ivo-rodrigues/profil/spieler/215122.
Performance history data appended for: https://www.transfermarkt.com/davor-matijas/profil/spieler/357780.
Performance history data appended for: https://www.transfermarkt.com/nana-ampomah/profil/spieler/429086.
Performance history data appended for: https://www.transfermarkt.com/dylan-batubinsika/profil/spieler/289432.
Performance history data appended for: https://www.transfermarkt.com/junior-pius/profil/spieler/314969.
Performance history data appended for: https://www.transfermarkt.com/dragan-lausberg/profil/spieler/435775.
Performance history data appended for: https://www.transfermarkt.com/guy-mbenza/profil/spieler/506948.
Performance history data appended for: https://www.transfermarkt.com/jeremy-gelin/profil/spieler/288237.
Performance history data appended for: https://www.transfermarkt.com/aboubakar-keita/profil/spieler/294807.

Performance history data appended for: https://www.transfermarkt.com/daniel-iversen/profil/spieler/260841.
Performance history data appended for: https://www.transfermarkt.com/samy-kehli/profil/spieler/176026.
Performance history data appended for: https://www.transfermarkt.com/yannick-aguemon/profil/spieler/170485.
Performance history data appended for: https://www.transfermarkt.com/musa-al-tamari/profil/spieler/551505.
Performance history data appended for: https://www.transfermarkt.com/casper-de-norre/profil/spieler/292806.
Performance history data appended for: https://www.transfermarkt.com/pierre-yves-ngawa/profil/spieler/140786.
Performance history data appended for: https://www.transfermarkt.com/oregan-ravet/profil/spieler/547889.
Performance history data appended for: https://www.transfermarkt.com/arthur-allemeersch/profil/spieler/565019.
Performance history data appended for: https://www.transfermarkt.com/derrick-tshimanga/profil/spieler/78507.
Performance history data appended for: https://www.transfermarkt.com/kristiyan-malinov/profil/spieler/282897.
Performance history data appended for: https://www.transfermarkt.com/xavier-mercier/profil/spieler/190146.
Performance history data appended for: https://www.transfermarkt.com/milan-tucic/profil/spieler/513646.
Performance history data appended for: https://www.transfermarkt.com/tom-van-hyfte/profil/spieler/22372.
Performance history data appended for: https://www.transfermarkt.com/stallone-limbombe/profil/spieler/292615.
Performance history data appended for: https://www.transfermarkt.com/jeremy-perbet/profil/spieler/23966.
Performance history data appended for: https://www.transfermarkt.com/jonah-osabutey/profil/spieler/269766.
Performance history data appended for: https://www.transfermarkt.com/toon-raemaekers/profil/spieler/712086.
Performance history data appended for: https://www.transfermarkt.com/vaclav-jemelka/profil/spieler/384879.
Performance history data appended for: https://www.transfermarkt.com/david-hubert/profil/spieler/52811.
Performance history data appended for: https://www.transfermarkt.com/josh-eppiah/profil/spieler/455917.
Performance history data appended for: https://www.transfermarkt.com/jordy-gillekens/profil/spieler/465307.
Performance history data appended for: https://www.transfermarkt.com/yohan-croizet/profil/spieler/195910.
Performance history data appended for: https://www.transfermarkt.com/kamal-sowah/profil/spieler/564489.
Performance history data appended for: https://www.transfermarkt.com/olivier-myny/profil/spieler/316406.
Performance history data appended for: https://www.transfermarkt.com/mathieu-maertens/profil/spieler/310131.
Performance history data appended for: https://www.transfermarkt.com/thibault-vlietinck/profil/spieler/249568.
Performance history data appended for: https://www.transfermarkt.com/isaac-asante/profil/spieler/719654.
Performance history data appended for: https://www.transfermarkt.com/thomas-henry/profil/spieler/412513.
Performance history data appended for: https://www.transfermarkt.com/daan-vekemans/profil/spieler/481640.
Performance history data appended for: https://www.transfermarkt.com/kenneth-schuermans/profil/spieler/217776.
Performance history data appended for: https://www.transfermarkt.com/tristan-borges/profil/spieler/402531.
Performance history data appended for: https://www.transfermarkt.com/frederic-duplus/profil/spieler/77829.
Performance history data appended for: https://www.transfermarkt.com/barnabas-bese/profil/spieler/148809.
Performance history data appended for: https://www.transfermarkt.com/rafael-romo/profil/spieler/101031.
Performance history data appended for: https://www.transfermarkt.com/dylan-ouedraogo/profil/spieler/460648.
Performance history data appended for: https://www.transfermarkt.com/sascha-kotysch/profil/spieler/41125.
Performance history data appended for: https://www.transfermarkt.com/zakaria-bakkali/profil/spieler/203378.
Performance history data appended for: https://www.transfermarkt.com/francis-amuzu/profil/spieler/423604.
Performance history data appended for: https://www.transfermarkt.com/michel-vlap/profil/spieler/342702.
Performance history data appended for: https://www.transfermarkt.com/kemar-lawrence/profil/spieler/288710.
Performance history data appended for: https://www.transfermarkt.com/peter-zulj/profil/spieler/128105.
Performance history data appended for: https://www.transfermarkt.com/matt-miazga/profil/spieler/245893.
Performance history data appended for: https://www.transfermarkt.com/bubacarr-sanneh/profil/spieler/292366.
Performance history data appended for: https://www.transfermarkt.com/michael-murillo/profil/spieler/354482.
Performance history data appended for: https://www.transfermarkt.com/anouar-ait-el-hadj/profil/spieler/486039.
Performance history data appended for: https://www.transfermarkt.com/hannes-delcroix/profil/spieler/338635.
Performance history data appended for: https://www.transfermarkt.com/antonio-milic/profil/spieler/179896.
Performance history data appended for: https://www.transfermarkt.com/paul-mukairu/profil/spieler/667914.
Performance history data appended for: https://www.transfermarkt.com/mohammed-dauda/profil/spieler/360711.
Performance history data appended for: https://www.transfermarkt.com/adrien-trebel/profil/spieler/159622.
Performance history data appended for: https://www.transfermarkt.com/ognjen-vranjes/profil/spieler/94807.
Performance history data appended for: https://www.transfermarkt.com/yari-verschaeren/profil/spieler/502302.
Performance history data appended for: https://www.transfermarkt.com/rik-vercauteren/profil/spieler/463737.
Performance history data appended for: https://www.transfermarkt.com/bogdan-mykhaylichenko/profil/spieler/294730.
Performance history data appended for: https://www.transfermarkt.com/timon-wellenreuther/profil/spieler/196829.
Performance history data appended for: https://www.transfermarkt.com/marco-kana/profil/spieler/486051.
Performance history data appended for: https://www.transfermarkt.com/antoine-colassin/profil/spieler/440953.
Performance history data appended for: https://www.transfermarkt.com/bart-verbruggen/profil/spieler/565093.
Performance history data appended for: https://www.transfermarkt.com/elias-cobbaut/profil/spieler/419723.
Performance history data appended for: https://www.transfermarkt.com/josh-cullen/profil/spieler/242606.
Performance history data appended for: https://www.transfermarkt.com/killian-sardella/profil/spieler/454336.
Performance history data appended for: https://www.transfermarkt.com/hendrik-van-crombrugge/profil/spieler/137326.
Performance history data appended for: https://www.transfermarkt.com/lukas-nmecha/profil/spieler/314288.
Performance history data appended for: https://www.transfermarkt.com/ilias-takidine/profil/spieler/488768.
Performance history data appended for: https://www.transfermarkt.com/percy-tau/profil/spieler/312239.
Performance history data appended for: https://www.transfermarkt.com/derrick-luckassen/profil/spieler/241457.
Performance history data appended for: https://www.transfermarkt.com/mustapha-bundu/profil/spieler/457728.
Performance history data appended for: https://www.transfermarkt.com/albert-sambi-lokonga/profil/spieler/381967.
Performance history data appended for: https://www.transfermarkt.com/landry-dimata/profil/spieler/311489.
Performance history data appended for: https://www.transfermarkt.com/kristian-arnstad/profil/spieler/581106.
Performance history data appended for: https://www.transfermarkt.com/andreas-beck/profil/spieler/31182.
Performance history data appended for: https://www.transfermarkt.com/gary-magnee/profil/spieler/679050.
Performance history data appended for: https://www.transfermarkt.com/knowledge-musona/profil/spieler/120785.
Performance history data appended for: https://www.transfermarkt.com/emmanuel-agbadou/profil/spieler/683895.
Performance history data appended for: https://www.transfermarkt.com/benoit-poulain/profil/spieler/80188.
Performance history data appended for: https://www.transfermarkt.com/ortwin-de-wolf/profil/spieler/450218.
Performance history data appended for: https://www.transfermarkt.com/smail-prevljak/profil/spieler/328264.

Performance history data appended for: https://www.transfermarkt.com/nils-schouterden/profil/spieler/62700.
Performance history data appended for: https://www.transfermarkt.com/julien-ngoy/profil/spieler/286005.
Performance history data appended for: https://www.transfermarkt.com/mamadou-kone/profil/spieler/171165.
Performance history data appended for: https://www.transfermarkt.com/isaac-nuhu/profil/spieler/740615.
Performance history data appended for: https://www.transfermarkt.com/edo-kayembe/profil/spieler/486477.
Performance history data appended for: https://www.transfermarkt.com/jens-cools/profil/spieler/142929.
Performance history data appended for: https://www.transfermarkt.com/jordi-amat/profil/spieler/85289.
Performance history data appended for: https://www.transfermarkt.com/abdul-nurudeen/profil/spieler/511168.
Performance history data appended for: https://www.transfermarkt.com/theo-defourny/profil/spieler/104543.
Performance history data appended for: https://www.transfermarkt.com/konan-n-rsquo-dri/profil/spieler/649490.
Performance history data appended for: https://www.transfermarkt.com/amara-baby/profil/spieler/108587.
Performance history data appended for: https://www.transfermarkt.com/emmanuel-sowah-adjei/profil/spieler/408839.
Performance history data appended for: https://www.transfermarkt.com/stef-peeters/profil/spieler/208542.
Performance history data appended for: https://www.transfermarkt.com/silas-gnaka/profil/spieler/481091.
Performance history data appended for: https://www.transfermarkt.com/menno-koch/profil/spieler/182578.
Performance history data appended for: https://www.transfermarkt.com/carlos-embalo/profil/spieler/275682.
Performance history data appended for: https://www.transfermarkt.com/senna-miangue/profil/spieler/249552.
Performance history data appended for: https://www.transfermarkt.com/jonathan-heris/profil/spieler/101531.
Performance history data appended for: https://www.transfermarkt.com/adriano/profil/spieler/34495.
Performance history data appended for: https://www.transfermarkt.com/boris-lambert/profil/spieler/585711.
Performance history data appended for: https://www.transfermarkt.com/sibiry-keita/profil/spieler/565778.
Performance history data appended for: https://www.transfermarkt.com/miguel-vieira/profil/spieler/214300.
Performance history data appended for: https://www.transfermarkt.com/andreas-wiegel/profil/spieler/45698.
Performance history data appended for: https://www.transfermarkt.com/leonardo-bertone/profil/spieler/194975.
Performance history data appended for: https://www.transfermarkt.com/lucas-pirard/profil/spieler/168166.
Performance history data appended for: https://www.transfermarkt.com/nordin-jackers/profil/spieler/250543.
Performance history data appended for: https://www.transfermarkt.com/denzel-jubitana/profil/spieler/502893.
Performance history data appended for: https://www.transfermarkt.com/brendan-schoonbaert/profil/spieler/369159.
Performance history data appended for: https://www.transfermarkt.com/alessandro-albanese/profil/spieler/407347.
Performance history data appended for: https://www.transfermarkt.com/danel-sinani/profil/spieler/346499.
Performance history data appended for: https://www.transfermarkt.com/serge-leuko/profil/spieler/184917.
Performance history data appended for: https://www.transfermarkt.com/jur-schryvers/profil/spieler/250574.
Performance history data appended for: https://www.transfermarkt.com/michael-frey/profil/spieler/147043.
Performance history data appended for: https://www.transfermarkt.com/brent-gabriel/profil/spieler/338665.
Performance history data appended for: https://www.transfermarkt.com/jordan-faucher/profil/spieler/169757.
Performance history data appended for: https://www.transfermarkt.com/amine-khammas/profil/spieler/401938.
Performance history data appended for: https://www.transfermarkt.com/jenthe-mertens/profil/spieler/526469.
Performance history data appended for: https://www.transfermarkt.com/aboubakary-koita/profil/spieler/422377.
Performance history data appended for: https://www.transfermarkt.com/matthias-verreth/profil/spieler/292817.
Performance history data appended for: https://www.transfermarkt.com/aleksandar-vukotic/profil/spieler/398851.
Performance history data appended for: https://www.transfermarkt.com/daan-heymans/profil/spieler/446491.
Performance history data appended for: https://www.transfermarkt.com/paul-keita/profil/spieler/164735.
Performance history data appended for: https://www.transfermarkt.com/djihad-bizimana/profil/spieler/418173.
Performance history data appended for: https://www.transfermarkt.com/milan-de-mey/profil/spieler/558553.
Performance history data appended for: https://www.transfermarkt.com/dries-wuytens/profil/spieler/83951.
Performance history data appended for: https://www.transfermarkt.com/alexis-gamboa/profil/spieler/452714.
Performance history data appended for: https://www.transfermarkt.com/georges-mandjeck/profil/spieler/52112.
Performance history data appended for: https://www.transfermarkt.com/joseph-efford/profil/spieler/537467.
Performance history data appended for: https://www.transfermarkt.com/tom-reyners/profil/spieler/358042.
Performance history data appended for: https://www.transfermarkt.com/din-sula/profil/spieler/358907.
Performance history data appended for: https://www.transfermarkt.com/andrija-vukcevic/profil/spieler/294987.
Performance history data appended for: https://www.transfermarkt.com/melvin-sitti/profil/spieler/689089.
Performance history data appended for: https://www.transfermarkt.com/elisha-owusu/profil/spieler/395695.
Performance history data appended for: https://www.transfermarkt.com/sulayman-marreh/profil/spieler/264046.
Performance history data appended for: https://www.transfermarkt.com/nurio-fortuna/profil/spieler/290261.
Performance history data appended for: https://www.transfermarkt.com/dino-arslanagic/profil/spieler/110660.
Performance history data appended for: https://www.transfermarkt.com/alexandre-de-bruyn/profil/spieler/224691.
Performance history data appended for: https://www.transfermarkt.com/laurent-depoitre/profil/spieler/90583.
Performance history data appended for: https://www.transfermarkt.com/michael-ngadeu-ngadjui/profil/spieler/227239.
Performance history data appended for: https://www.transfermarkt.com/jordan-botaka/profil/spieler/196860.
Performance history data appended for: https://www.transfermarkt.com/dylan-mbayo/profil/spieler/502289.
Performance history data appended for: https://www.transfermarkt.com/bruno-godeau/profil/spieler/142924.
Performance history data appended for: https://www.transfermarkt.com/giorgi-chakvetadze/profil/spieler/412616.
Performance history data appended for: https://www.transfermarkt.com/roman-yaremchuk/profil/spieler/221958.
Performance history data appended for: https://www.transfermarkt.com/anderson-niangbo/profil/spieler/294814.
Performance history data appended for: https://www.transfermarkt.com/tim-kleindienst/profil/spieler/193033.
Performance history data appended for: https://www.transfermarkt.com/sven-kums/profil/spieler/42735.
Performance history data appended for: https://www.transfermarkt.com/ibrahima-cisse/profil/spieler/684340.
Performance history data appended for: https://www.transfermarkt.com/roman-bezus/profil/spieler/97567.
Performance history data appended for: https://www.transfermarkt.com/andreas-hanche-olsen/profil/spieler/370683.
Performance history data appended for: https://www.transfermarkt.com/niklas-dorsch/profil/spieler/251302.
Performance history data appended for: https://www.transfermarkt.com/sinan-bolat/profil/spieler/33862.
Performance history data appended for: https://www.transfermarkt.com/igor-plastun/profil/spieler/97335.
Performance history data appended for: https://www.transfermarkt.com/matheo-parmentier/profil/spieler/737533.
Performance history data appended for: https://www.transfermarkt.com/milad-mohammadi/profil/spieler/333355.
Performance history data appended for: https://www.transfermarkt.com/osman-bukari/profil/spieler/548650.
Performance history data appended for: https://www.transfermarkt.com/colin-coosemans/profil/spieler/154351.

Performance history data appended for: https://www.transfermarkt.com/alessio-castro-montes/profil/spieler/340166.
Performance history data appended for: https://www.transfermarkt.com/davy-roef/profil/spieler/140808.
Performance history data appended for: https://www.transfermarkt.com/vadis-odjidja-ofoe/profil/spieler/38388.
Performance history data appended for: https://www.transfermarkt.com/kylian-hazard/profil/spieler/275457.
Performance history data appended for: https://www.transfermarkt.com/dino-hotic/profil/spieler/183836.
Performance history data appended for: https://www.transfermarkt.com/robbe-decostere/profil/spieler/601407.
Performance history data appended for: https://www.transfermarkt.com/thibo-somers/profil/spieler/719456.
Performance history data appended for: https://www.transfermarkt.com/andi-koshi/profil/spieler/502268.
Performance history data appended for: https://www.transfermarkt.com/merveille-goblet/profil/spieler/193470.
Performance history data appended for: https://www.transfermarkt.com/arne-cassaert/profil/spieler/725003.
Performance history data appended for: https://www.transfermarkt.com/jeremy-taravel/profil/spieler/56821.
Performance history data appended for: https://www.transfermarkt.com/dimitar-velkovski/profil/spieler/323403.
Performance history data appended for: https://www.transfermarkt.com/vitinho/profil/spieler/468249.
Performance history data appended for: https://www.transfermarkt.com/kevin-hoggas/profil/spieler/379737.
Performance history data appended for: https://www.transfermarkt.com/jean-marcelin/profil/spieler/475412.
Performance history data appended for: https://www.transfermarkt.com/david-bates/profil/spieler/272539.
Performance history data appended for: https://www.transfermarkt.com/naomichi-ueda/profil/spieler/188915.
Performance history data appended for: https://www.transfermarkt.com/olivier-deman/profil/spieler/621802.
Performance history data appended for: https://www.transfermarkt.com/thomas-didillon/profil/spieler/182891.
Performance history data appended for: https://www.transfermarkt.com/alexander-corryn/profil/spieler/129580.
Performance history data appended for: https://www.transfermarkt.com/leonardo-da-silva-lopes/profil/spieler/348756.
Performance history data appended for: https://www.transfermarkt.com/charles-vanhoutte/profil/spieler/569845.
Performance history data appended for: https://www.transfermarkt.com/anthony-musaba/profil/spieler/511401.
Performance history data appended for: https://www.transfermarkt.com/serge-philippe-raux-yao/profil/spieler/683891.
Performance history data appended for: https://www.transfermarkt.com/johanna-omolo/profil/spieler/85834.
Performance history data appended for: https://www.transfermarkt.com/miguel-van-damme/profil/spieler/321571.
Performance history data appended for: https://www.transfermarkt.com/franck-kanoute/profil/spieler/478198.
Performance history data appended for: https://www.transfermarkt.com/giulian-biancone/profil/spieler/536507.
Performance history data appended for: https://www.transfermarkt.com/warleson/profil/spieler/477460.
Performance history data appended for: https://www.transfermarkt.com/calvin-dekuyper/profil/spieler/719455.
Performance history data appended for: https://www.transfermarkt.com/ike-ugbo/profil/spieler/339943.
Performance history data appended for: https://www.transfermarkt.com/aldom-deuro/profil/spieler/648971.
Performance history data appended for: https://www.transfermarkt.com/erdin-demir/profil/spieler/151567.
Performance history data appended for: https://www.transfermarkt.com/damien-marcq/profil/spieler/57534.
Performance history data appended for: https://www.transfermarkt.com/abdallah-ali-mohamed/profil/spieler/517372.
Performance history data appended for: https://www.transfermarkt.com/william-bianda/profil/spieler/427197.
Performance history data appended for: https://www.transfermarkt.com/daniel-opare/profil/spieler/65781.
Performance history data appended for: https://www.transfermarkt.com/cameron-humphreys/profil/spieler/277723.
Performance history data appended for: https://www.transfermarkt.com/panagiotis-armenakas/profil/spieler/336679.
Performance history data appended for: https://www.transfermarkt.com/laurens-de-bock/profil/spieler/110668.
Performance history data appended for: https://www.transfermarkt.com/ewoud-pletinckx/profil/spieler/491298.
Performance history data appended for: https://www.transfermarkt.com/gianni-bruno/profil/spieler/95604.
Performance history data appended for: https://www.transfermarkt.com/jean-luc-dompe/profil/spieler/291222.
Performance history data appended for: https://www.transfermarkt.com/jannes-van-hecke/profil/spieler/620566.
Performance history data appended for: https://www.transfermarkt.com/jelle-vossen/profil/spieler/42748.
Performance history data appended for: https://www.transfermarkt.com/olivier-deschacht/profil/spieler/9593.
Performance history data appended for: https://www.transfermarkt.com/eike-bansen/profil/spieler/287025.
Performance history data appended for: https://www.transfermarkt.com/mikael-soisalo/profil/spieler/323010.
Performance history data appended for: https://www.transfermarkt.com/ibrahima-seck/profil/spieler/209933.
Performance history data appended for: https://www.transfermarkt.com/maxime-thiel/profil/spieler/464068.
Performance history data appended for: https://www.transfermarkt.com/bassem-srarfi/profil/spieler/401836.
Performance history data appended for: https://www.transfermarkt.com/abdoulaye-sissako/profil/spieler/418661.
Performance history data appended for: https://www.transfermarkt.com/sammy-bossut/profil/spieler/48064.
Performance history data appended for: https://www.transfermarkt.com/louis-bostyn/profil/spieler/159382.
Performance history data appended for: https://www.transfermarkt.com/nikolaos-kainourgios/profil/spieler/493332.
Performance history data appended for: https://www.transfermarkt.com/mathieu-de-smet/profil/spieler/499956.
Performance history data appended for: https://www.transfermarkt.com/omar-govea/profil/spieler/282927.
Performance history data appended for: https://www.transfermarkt.com/tomas-chory/profil/spieler/198614.
Performance history data appended for: https://www.transfermarkt.com/petar-golubovic/profil/spieler/239783.
Performance history data appended for: https://www.transfermarkt.com/marko-ilic/profil/spieler/343953.
Performance history data appended for: https://www.transfermarkt.com/maxim-deman/profil/spieler/688246.
Performance history data appended for: https://www.transfermarkt.com/trent-sainsbury/profil/spieler/145840.
Performance history data appended for: https://www.transfermarkt.com/sambou-sissoko/profil/spieler/649019.
Performance history data appended for: https://www.transfermarkt.com/faiz-selemani/profil/spieler/352017.
Performance history data appended for: https://www.transfermarkt.com/lucas-rougeaux/profil/spieler/226288.
Performance history data appended for: https://www.transfermarkt.com/yevgen-makarenko/profil/spieler/96455.
Performance history data appended for: https://www.transfermarkt.com/michiel-jonckheere/profil/spieler/150711.
Performance history data appended for: https://www.transfermarkt.com/ilombe-mboyo/profil/spieler/96227.
Performance history data appended for: https://www.transfermarkt.com/christophe-lepoint/profil/spieler/4742.
Performance history data appended for: https://www.transfermarkt.com/kristof-dhaene/profil/spieler/156496.
Performance history data appended for: https://www.transfermarkt.com/eric-ocansey/profil/spieler/380416.
Performance history data appended for: https://www.transfermarkt.com/luqman-hakim/profil/spieler/541749.
Performance history data appended for: https://www.transfermarkt.com/julien-de-sart/profil/spieler/129592.
Performance history data appended for: https://www.transfermarkt.com/jovan-stojanovic/profil/spieler/175440.
Performance history data appended for: https://www.transfermarkt.com/adam-jakubech/profil/spieler/258267.
Performance history data appended for: https://www.transfermarkt.com/brendan-hines-ike/profil/spieler/411302.
Performance history data appended for: https://www.transfermarkt.com/gilles-dewaele/profil/spieler/250138.

Performance history data appended for: https://www.transfermarkt.com/timothy-derijck/profil/spieler/31131.
Performance history data appended for: https://www.transfermarkt.com/mohamed-badamosi/profil/spieler/369384.
Performance history data appended for: https://www.transfermarkt.com/hannes-van-der-bruggen/profil/spieler/110822.
Performance history data appended for: https://www.transfermarkt.com/pape-habib-gueye/profil/spieler/585339.
Performance history data appended for: https://www.transfermarkt.com/odilon-kossounou/profil/spieler/644771.
Performance history data appended for: https://www.transfermarkt.com/michael-krmencik/profil/spieler/178469.
Performance history data appended for: https://www.transfermarkt.com/brandon-mechele/profil/spieler/236168.
Performance history data appended for: https://www.transfermarkt.com/nick-shinton/profil/spieler/409533.
Performance history data appended for: https://www.transfermarkt.com/charles-de-ketelaere/profil/spieler/435772.
Performance history data appended for: https://www.transfermarkt.com/siebe-schrijvers/profil/spieler/208552.
Performance history data appended for: https://www.transfermarkt.com/youssouph-badji/profil/spieler/649035.
Performance history data appended for: https://www.transfermarkt.com/ethan-horvath/profil/spieler/242284.
Performance history data appended for: https://www.transfermarkt.com/simon-deli/profil/spieler/234124.
Performance history data appended for: https://www.transfermarkt.com/hans-vanaken/profil/spieler/137576.
Performance history data appended for: https://www.transfermarkt.com/senne-lammens/profil/spieler/503883.
Performance history data appended for: https://www.transfermarkt.com/federico-ricca/profil/spieler/285322.
Performance history data appended for: https://www.transfermarkt.com/maxim-de-cuyper/profil/spieler/429915.
Performance history data appended for: https://www.transfermarkt.com/clinton-mata/profil/spieler/187718.
Performance history data appended for: https://www.transfermarkt.com/david-okereke/profil/spieler/413605.
Performance history data appended for: https://www.transfermarkt.com/noa-lang/profil/spieler/339332.
Performance history data appended for: https://www.transfermarkt.com/krepin-diatta/profil/spieler/490426.
Performance history data appended for: https://www.transfermarkt.com/mats-rits/profil/spieler/92164.
Performance history data appended for: https://www.transfermarkt.com/thomas-van-den-keybus/profil/spieler/502298.
Performance history data appended for: https://www.transfermarkt.com/matej-mitrovic/profil/spieler/206734.
Performance history data appended for: https://www.transfermarkt.com/emmanuel-dennis/profil/spieler/448854.
Performance history data appended for: https://www.transfermarkt.com/eder-balanta/profil/spieler/265127.
Performance history data appended for: https://www.transfermarkt.com/ruud-vormer/profil/spieler/45864.
Performance history data appended for: https://www.transfermarkt.com/simon-mignolet/profil/spieler/50219.
Performance history data appended for: https://www.transfermarkt.com/ignace-van-der-brempt/profil/spieler/490423.
Performance history data appended for: https://www.transfermarkt.com/amadou-sagna/profil/spieler/649025.
Performance history data appended for: https://www.transfermarkt.com/eduard-sobol/profil/spieler/206717.
Performance history data appended for: https://www.transfermarkt.com/denis-prychynenko/profil/spieler/93862.
Performance history data appended for: https://www.transfermarkt.com/antoine-lejoly/profil/spieler/289583.
Performance history data appended for: https://www.transfermarkt.com/joren-dom/profil/spieler/80442.
Performance history data appended for: https://www.transfermarkt.com/musashi-suzuki/profil/spieler/188914.
Performance history data appended for: https://www.transfermarkt.com/keres-masangu/profil/spieler/393018.
Performance history data appended for: https://www.transfermarkt.com/blessing-eleke/profil/spieler/348229.
Performance history data appended for: https://www.transfermarkt.com/yan-vorogovskiy/profil/spieler/357608.
Performance history data appended for: https://www.transfermarkt.com/ismaila-coulibaly/profil/spieler/490224.
Performance history data appended for: https://www.transfermarkt.com/jan-van-den-bergh/profil/spieler/334495.
Performance history data appended for: https://www.transfermarkt.com/raphael-holzhauser/profil/spieler/104414.
Performance history data appended for: https://www.transfermarkt.com/ayrton-mboko/profil/spieler/285998.
Performance history data appended for: https://www.transfermarkt.com/pierre-bourdin/profil/spieler/164902.
Performance history data appended for: https://www.transfermarkt.com/tom-pietermaat/profil/spieler/110797.
Performance history data appended for: https://www.transfermarkt.com/marius-noubissi/profil/spieler/357701.
Performance history data appended for: https://www.transfermarkt.com/ryan-sanusi/profil/spieler/202380.
Performance history data appended for: https://www.transfermarkt.com/dario-van-den-buijs/profil/spieler/235274.
Performance history data appended for: https://www.transfermarkt.com/wouter-biebauw/profil/spieler/19896.
Performance history data appended for: https://www.transfermarkt.com/gregory-grisez/profil/spieler/89628.
Performance history data appended for: https://www.transfermarkt.com/abdoulie-sanyang/profil/spieler/693906.
Performance history data appended for: https://www.transfermarkt.com/loris-brogno/profil/spieler/182420.
Performance history data appended for: https://www.transfermarkt.com/frederic-frans/profil/spieler/46715.
Performance history data appended for: https://www.transfermarkt.com/mohamed-reda-halaimia/profil/spieler/387944.
Performance history data appended for: https://www.transfermarkt.com/mike-vanhamel/profil/spieler/42178.
Performance history data appended for: https://www.transfermarkt.com/tarik-tissoudali/profil/spieler/245228.
Performance history data appended for: https://www.transfermarkt.com/georgios-vagiannidis/profil/spieler/546186.
Performance history data appended for: https://www.transfermarkt.com/chris-durkin/profil/spieler/367423.
Performance history data appended for: https://www.transfermarkt.com/santiago-colombatto/profil/spieler/395122.
Performance history data appended for: https://www.transfermarkt.com/ibrahima-sory-sankhon/profil/spieler/426648.
Performance history data appended for: https://www.transfermarkt.com/mory-konate/profil/spieler/364370.
Performance history data appended for: https://www.transfermarkt.com/yuma-suzuki/profil/spieler/345323.
Performance history data appended for: https://www.transfermarkt.com/wim-vanmarsenille/profil/spieler/706037.
Performance history data appended for: https://www.transfermarkt.com/wolke-janssens/profil/spieler/235247.
Performance history data appended for: https://www.transfermarkt.com/duckens-nazon/profil/spieler/345763.
Performance history data appended for: https://www.transfermarkt.com/hamza-masoudi/profil/spieler/597095.
Performance history data appended for: https://www.transfermarkt.com/samuel-asamoah/profil/spieler/232848.
Performance history data appended for: https://www.transfermarkt.com/stan-van-dessel/profil/spieler/480265.
Performance history data appended for: https://www.transfermarkt.com/daniel-schmidt/profil/spieler/158799.
Performance history data appended for: https://www.transfermarkt.com/samy-mmaee/profil/spieler/331840.
Performance history data appended for: https://www.transfermarkt.com/seung-woo-lee/profil/spieler/280239.
Performance history data appended for: https://www.transfermarkt.com/nelson-balongo/profil/spieler/583756.
Performance history data appended for: https://www.transfermarkt.com/jorge-teixeira/profil/spieler/59791.
Performance history data appended for: https://www.transfermarkt.com/jonathan-buatu/profil/spieler/137313.
Performance history data appended for: https://www.transfermarkt.com/liberato-cacace/profil/spieler/469211.
Performance history data appended for: https://www.transfermarkt.com/siebren-lathouwers/profil/spieler/452580.
Performance history data appended for: https://www.transfermarkt.com/facundo-colidio/profil/spieler/491705.
Performance history data appended for: https://www.transfermarkt.com/tatsuya-ito/profil/spieler/381248.

Performance history data appended for: https://www.transfermarkt.com/kenny-steppe/profil/spieler/42531.
Performance history data appended for: https://www.transfermarkt.com/steve-de-ridder/profil/spieler/41818.
Performance history data appended for: https://www.transfermarkt.com/maximiliano-caufriez/profil/spieler/369267.
Performance history data appended for: https://www.transfermarkt.com/oleksandr-filippov/profil/spieler/237623.
Performance history data appended for: https://www.transfermarkt.com/jhonny-lucas/profil/spieler/540990.
Performance history data appended for: https://www.transfermarkt.com/keito-nakamura/profil/spieler/405397.
Performance history data appended for: https://www.transfermarkt.com/ko-matsubara/profil/spieler/307300.
Performance history data appended for: https://www.transfermarkt.com/pol-garcia/profil/spieler/178217.
Performance history data appended for: https://www.transfermarkt.com/matheo-vroman/profil/spieler/593939.
Performance history data appended for: https://www.transfermarkt.com/matias-silvestre/profil/spieler/20003.
Performance history data appended for: https://www.transfermarkt.com/kouadio-yves-dabila/profil/spieler/503740.
Performance history data appended for: https://www.transfermarkt.com/alessandro-ciranni/profil/spieler/338680.
Performance history data appended for: https://www.transfermarkt.com/harlem-gnohere/profil/spieler/70778.
Performance history data appended for: https://www.transfermarkt.com/serge-tabekou/profil/spieler/370522.
Performance history data appended for: https://www.transfermarkt.com/babacar-dione/profil/spieler/509116.
Performance history data appended for: https://www.transfermarkt.com/charles-andreas-brym/profil/spieler/595028.
Performance history data appended for: https://www.transfermarkt.com/robbe-quirynen/profil/spieler/660319.
Performance history data appended for: https://www.transfermarkt.com/xadas/profil/spieler/345345.
Performance history data appended for: https://www.transfermarkt.com/marko-bakic/profil/spieler/188335.
Performance history data appended for: https://www.transfermarkt.com/william-simba/profil/spieler/798717.
Performance history data appended for: https://www.transfermarkt.com/vaso-vasic/profil/spieler/68030.
Performance history data appended for: https://www.transfermarkt.com/herve-koffi/profil/spieler/415383.
Performance history data appended for: https://www.transfermarkt.com/eric-junior-bocat/profil/spieler/740529.
Performance history data appended for: https://www.transfermarkt.com/nuno-da-costa/profil/spieler/306166.
Performance history data appended for: https://www.transfermarkt.com/el-hadji-gueye/profil/spieler/795055.
Performance history data appended for: https://www.transfermarkt.com/dimitri-mohamed/profil/spieler/190917.
Performance history data appended for: https://www.transfermarkt.com/agim-zeka/profil/spieler/342824.
Performance history data appended for: https://www.transfermarkt.com/lillo-guarneri/profil/spieler/490387.
Performance history data appended for: https://www.transfermarkt.com/jean-onana/profil/spieler/656441.
Performance history data appended for: https://www.transfermarkt.com/saad-agouzoul/profil/spieler/556865.
Performance history data appended for: https://www.transfermarkt.com/alexandre-ippolito/profil/spieler/664128.
Performance history data appended for: https://www.transfermarkt.com/beni-badibanga/profil/spieler/347625.
Performance history data appended for: https://www.transfermarkt.com/fabrice-olinga/profil/spieler/238291.
Performance history data appended for: https://www.transfermarkt.com/enes-saglik/profil/spieler/120306.
Performance history data appended for: https://www.transfermarkt.com/nick-gillekens/profil/spieler/283580.
Performance history data appended for: https://www.transfermarkt.com/deni-ho%C4%8Dko/profil/spieler/227534.
Performance history data appended for: https://www.transfermarkt.com/darly-nlandu/profil/spieler/434226.
Performance history data appended for: https://www.transfermarkt.com/capita/profil/spieler/666545.
Performance history data appended for: https://www.transfermarkt.com/imad-faraj/profil/spieler/371145.
Performance history data appended for: https://www.transfermarkt.com/benjamin-van-durmen/profil/spieler/434514.
Performance history data appended for: https://www.transfermarkt.com/virgiliu-postolachi/profil/spieler/536519.
Performance history data appended for: https://www.transfermarkt.com/kaveh-rezaei/profil/spieler/132553.
Performance history data appended for: https://www.transfermarkt.com/amine-benchaib/profil/spieler/503855.
Performance history data appended for: https://www.transfermarkt.com/dorian-dessoleil/profil/spieler/182424.
Performance history data appended for: https://www.transfermarkt.com/ali-gholizadeh/profil/spieler/294772.
Performance history data appended for: https://www.transfermarkt.com/lukasz-teodorczyk/profil/spieler/157849.
Performance history data appended for: https://www.transfermarkt.com/gaetan-hendrickx/profil/spieler/161658.
Performance history data appended for: https://www.transfermarkt.com/christophe-diandy/profil/spieler/105352.
Performance history data appended for: https://www.transfermarkt.com/massimo-bruno/profil/spieler/111376.
Performance history data appended for: https://www.transfermarkt.com/guillaume-gillet/profil/spieler/31952.
Performance history data appended for: https://www.transfermarkt.com/steeven-willems/profil/spieler/203539.
Performance history data appended for: https://www.transfermarkt.com/nicolas-penneteau/profil/spieler/5578.
Performance history data appended for: https://www.transfermarkt.com/ken-nkuba/profil/spieler/627939.
Performance history data appended for: https://www.transfermarkt.com/ryota-morioka/profil/spieler/140310.
Performance history data appended for: https://www.transfermarkt.com/gjoko-zajkov/profil/spieler/205849.
Performance history data appended for: https://www.transfermarkt.com/joachim-imbrechts/profil/spieler/502261.
Performance history data appended for: https://www.transfermarkt.com/lucas-ribeiro-costa/profil/spieler/612880.
Performance history data appended for: https://www.transfermarkt.com/jules-van-cleemput/profil/spieler/384280.
Performance history data appended for: https://www.transfermarkt.com/modou-diagne/profil/spieler/256902.
Performance history data appended for: https://www.transfermarkt.com/jon-flanagan/profil/spieler/145922.
Performance history data appended for: https://www.transfermarkt.com/shamar-nicholson/profil/spieler/354666.
Performance history data appended for: https://www.transfermarkt.com/mamadou-fall/profil/spieler/289713.
Performance history data appended for: https://www.transfermarkt.com/saido-berahino/profil/spieler/128897.
Performance history data appended for: https://www.transfermarkt.com/joris-kayembe/profil/spieler/129586.
Performance history data appended for: https://www.transfermarkt.com/marco-ilaimaharitra/profil/spieler/205550.
Performance history data appended for: https://www.transfermarkt.com/remy-descamps/profil/spieler/282028.
Performance history data appended for: https://www.transfermarkt.com/ivan-goranov/profil/spieler/183538.
Performance history data appended for: https://www.transfermarkt.com/marko-kvasina/profil/spieler/240778.
Performance history data appended for: https://www.transfermarkt.com/fabrice-ondoa/profil/spieler/220999.
Performance history data appended for: https://www.transfermarkt.com/ari-freyr-skulason/profil/spieler/42948.
Performance history data appended for: https://www.transfermarkt.com/brecht-capon/profil/spieler/42703.
Performance history data appended for: https://www.transfermarkt.com/frederik-jakel/profil/spieler/405679.
Performance history data appended for: https://www.transfermarkt.com/mamadou-thiam/profil/spieler/368624.
Performance history data appended for: https://www.transfermarkt.com/jelle-bataille/profil/spieler/460378.
Performance history data appended for: https://www.transfermarkt.com/guillaume-hubert/profil/spieler/129585.
Performance history data appended for: https://www.transfermarkt.com/bram-castro/profil/spieler/13283.
Performance history data appended for: https://www.transfermarkt.com/makhtar-gueye/profil/spieler/606849.

Performance history data appended for: https://www.transfermarkt.com/maxime-darpino/profil/spieler/346290.
Performance history data appended for: https://www.transfermarkt.com/anton-tanghe/profil/spieler/460848.
Performance history data appended for: https://www.transfermarkt.com/arthur-theate/profil/spieler/368891.
Performance history data appended for: https://www.transfermarkt.com/francois-marquet/profil/spieler/194438.
Performance history data appended for: https://www.transfermarkt.com/jordy-schelfhout/profil/spieler/688245.
Performance history data appended for: https://www.transfermarkt.com/andrew-hjulsager/profil/spieler/167798.
Performance history data appended for: https://www.transfermarkt.com/nick-batzner/profil/spieler/443855.
Performance history data appended for: https://www.transfermarkt.com/sindrit-guri/profil/spieler/189604.
Performance history data appended for: https://www.transfermarkt.com/toby-sibbick/profil/spieler/484215.
Performance history data appended for: https://www.transfermarkt.com/jack-hendry/profil/spieler/363223.
Performance history data appended for: https://www.transfermarkt.com/indy-boonen/profil/spieler/338817.
Performance history data appended for: https://www.transfermarkt.com/robbie-dhaese/profil/spieler/460379.
Performance history data appended for: https://www.transfermarkt.com/theo-ndicka-matam/profil/spieler/461595.
Performance history data appended for: https://www.transfermarkt.com/evangelos-patoulidis/profil/spieler/375718.
Performance history data appended for: https://www.transfermarkt.com/kevin-vandendriessche/profil/spieler/174285.
Performance history data appended for: https://www.transfermarkt.com/cameron-mcgeehan/profil/spieler/167265.
Performance history data appended for: https://www.transfermarkt.com/fashion-sakala/profil/spieler/485729.
Performance history data appended for: https://www.transfermarkt.com/patrik-hrosovsky/profil/spieler/217879.
Performance history data appended for: https://www.transfermarkt.com/jhon-lucumi/profil/spieler/413565.
Performance history data appended for: https://www.transfermarkt.com/rubin-seigers/profil/spieler/314980.
Performance history data appended for: https://www.transfermarkt.com/shawn-adewoye/profil/spieler/358021.
Performance history data appended for: https://www.transfermarkt.com/eboue-kouassi/profil/spieler/314137.
Performance history data appended for: https://www.transfermarkt.com/daniel-munoz/profil/spieler/493003.
Performance history data appended for: https://www.transfermarkt.com/bryan-heynen/profil/spieler/356081.
Performance history data appended for: https://www.transfermarkt.com/junya-ito/profil/spieler/348791.
Performance history data appended for: https://www.transfermarkt.com/danny-vukovic/profil/spieler/43113.
Performance history data appended for: https://www.transfermarkt.com/dries-wouters/profil/spieler/249570.
Performance history data appended for: https://www.transfermarkt.com/zinho-gano/profil/spieler/182446.
Performance history data appended for: https://www.transfermarkt.com/tobe-leysen/profil/spieler/580434.
Performance history data appended for: https://www.transfermarkt.com/luca-oyen/profil/spieler/551085.
Performance history data appended for: https://www.transfermarkt.com/joakim-maehle/profil/spieler/369674.
Performance history data appended for: https://www.transfermarkt.com/bastien-toma/profil/spieler/390179.
Performance history data appended for: https://www.transfermarkt.com/theo-bongonda/profil/spieler/280701.
Performance history data appended for: https://www.transfermarkt.com/pierre-dwomoh/profil/spieler/652803.
Performance history data appended for: https://www.transfermarkt.com/jere-uronen/profil/spieler/131827.
Performance history data appended for: https://www.transfermarkt.com/gerardo-arteaga/profil/spieler/469718.
Performance history data appended for: https://www.transfermarkt.com/maarten-vandevoordt/profil/spieler/486046.
Performance history data appended for: https://www.transfermarkt.com/paul-onuachu/profil/spieler/272855.
Performance history data appended for: https://www.transfermarkt.com/kristian-thorstvedt/profil/spieler/564785.
Performance history data appended for: https://www.transfermarkt.com/elias-sierra/profil/spieler/409514.
Performance history data appended for: https://www.transfermarkt.com/mats-moller-daehli/profil/spieler/190831.
Performance history data appended for: https://www.transfermarkt.com/carlos-cuesta/profil/spieler/474589.
Performance history data appended for: https://www.transfermarkt.com/cyriel-dessers/profil/spieler/317806.
Performance history data appended for: https://www.transfermarkt.com/sebastien-dewaest/profil/spieler/125754.
Performance history data appended for: https://www.transfermarkt.com/stefan-knezevic/profil/spieler/293247.
Performance history data appended for: https://www.transfermarkt.com/ashvin-balaruban/profil/spieler/507454.
Performance history data appended for: https://www.transfermarkt.com/tyron-owusu/profil/spieler/583055.
Performance history data appended for: https://www.transfermarkt.com/tsiy-william-ndenge/profil/spieler/253574.
Performance history data appended for: https://www.transfermarkt.com/alex-carbonell/profil/spieler/262389.
Performance history data appended for: https://www.transfermarkt.com/david-zibung/profil/spieler/4914.
Performance history data appended for: https://www.transfermarkt.com/lino-lang/profil/spieler/445326.
Performance history data appended for: https://www.transfermarkt.com/marvin-schulz/profil/spieler/168678.
Performance history data appended for: https://www.transfermarkt.com/lucas/profil/spieler/190314.
Performance history data appended for: https://www.transfermarkt.com/martin-frydek/profil/spieler/146710.
Performance history data appended for: https://www.transfermarkt.com/yvan-alounga/profil/spieler/534493.
Performance history data appended for: https://www.transfermarkt.com/salah-aziz-binous/profil/spieler/511143.
Performance history data appended for: https://www.transfermarkt.com/marco-burch/profil/spieler/479268.
Performance history data appended for: https://www.transfermarkt.com/dejan-sorgic/profil/spieler/65442.
Performance history data appended for: https://www.transfermarkt.com/filip-ugrinic/profil/spieler/394236.
Performance history data appended for: https://www.transfermarkt.com/christian-schwegler/profil/spieler/4931.
Performance history data appended for: https://www.transfermarkt.com/pascal-schurpf/profil/spieler/65290.
Performance history data appended for: https://www.transfermarkt.com/julian-hermann/profil/spieler/310113.
Performance history data appended for: https://www.transfermarkt.com/marco-burki/profil/spieler/172192.
Performance history data appended for: https://www.transfermarkt.com/louis-schaub/profil/spieler/147485.
Performance history data appended for: https://www.transfermarkt.com/mark-marleku/profil/spieler/310066.
Performance history data appended for: https://www.transfermarkt.com/nenad-zivkovic/profil/spieler/507419.
Performance history data appended for: https://www.transfermarkt.com/marius-muller/profil/spieler/118161.
Performance history data appended for: https://www.transfermarkt.com/simon-grether/profil/spieler/159299.
Performance history data appended for: https://www.transfermarkt.com/lorik-emini/profil/spieler/410871.
Performance history data appended for: https://www.transfermarkt.com/ibrahima-ndiaye/profil/spieler/457031.
Performance history data appended for: https://www.transfermarkt.com/samuel-alabi/profil/spieler/582019.
Performance history data appended for: https://www.transfermarkt.com/varol-tasar/profil/spieler/310361.
Performance history data appended for: https://www.transfermarkt.com/silvan-sidler/profil/spieler/342063.
Performance history data appended for: https://www.transfermarkt.com/adria-guerrero/profil/spieler/282724.
Performance history data appended for: https://www.transfermarkt.com/alessandro-pietrogiovanna/profil/spieler/608004.
Performance history data appended for: https://www.transfermarkt.com/david-jovanovic/profil/spieler/510893.
Performance history data appended for: https://www.transfermarkt.com/mattia-bottani/profil/spieler/86484.

Performance history data appended for: https://www.transfermarkt.com/mijat-maric/profil/spieler/6666.
Performance history data appended for: https://www.transfermarkt.com/roman-macek/profil/spieler/256085.
Performance history data appended for: https://www.transfermarkt.com/stefano-guidotti/profil/spieler/396405.
Performance history data appended for: https://www.transfermarkt.com/joaquin-ardaiz/profil/spieler/415550.
Performance history data appended for: https://www.transfermarkt.com/alexander-gerndt/profil/spieler/45881.
Performance history data appended for: https://www.transfermarkt.com/kevin-monzialo/profil/spieler/591199.
Performance history data appended for: https://www.transfermarkt.com/jonathan-sabbatini/profil/spieler/102409.
Performance history data appended for: https://www.transfermarkt.com/marcis-oss/profil/spieler/159124.
Performance history data appended for: https://www.transfermarkt.com/noam-baumann/profil/spieler/192605.
Performance history data appended for: https://www.transfermarkt.com/noah-de-queiroz/profil/spieler/357860.
Performance history data appended for: https://www.transfermarkt.com/lucio-soldini/profil/spieler/507450.
Performance history data appended for: https://www.transfermarkt.com/mickael-facchinetti/profil/spieler/79392.
Performance history data appended for: https://www.transfermarkt.com/sandi-lovric/profil/spieler/268429.
Performance history data appended for: https://www.transfermarkt.com/ransford-selasi/profil/spieler/292333.
Performance history data appended for: https://www.transfermarkt.com/sebastian-osigwe/profil/spieler/199453.
Performance history data appended for: https://www.transfermarkt.com/akos-kecskes/profil/spieler/204155.
Performance history data appended for: https://www.transfermarkt.com/cendrim-kameraj/profil/spieler/390173.
Performance history data appended for: https://www.transfermarkt.com/christopher-lungoyi/profil/spieler/346903.
Performance history data appended for: https://www.transfermarkt.com/jens-odgaard/profil/spieler/345590.
Performance history data appended for: https://www.transfermarkt.com/fabio-daprela/profil/spieler/66109.
Performance history data appended for: https://www.transfermarkt.com/florjan-seferaj/profil/spieler/529316.
Performance history data appended for: https://www.transfermarkt.com/miroslav-covilo/profil/spieler/60452.
Performance history data appended for: https://www.transfermarkt.com/olivier-custodio/profil/spieler/183312.
Performance history data appended for: https://www.transfermarkt.com/numa-lavanchy/profil/spieler/147501.
Performance history data appended for: https://www.transfermarkt.com/fidan-aliti/profil/spieler/182870.
Performance history data appended for: https://www.transfermarkt.com/mirlind-kryeziu/profil/spieler/265208.
Performance history data appended for: https://www.transfermarkt.com/becir-omeragic/profil/spieler/507344.
Performance history data appended for: https://www.transfermarkt.com/benjamin-kololli/profil/spieler/191486.
Performance history data appended for: https://www.transfermarkt.com/zivko-kostadinovic/profil/spieler/178277.
Performance history data appended for: https://www.transfermarkt.com/willie-britto/profil/spieler/364307.
Performance history data appended for: https://www.transfermarkt.com/vasilije-janjicic/profil/spieler/265254.
Performance history data appended for: https://www.transfermarkt.com/kedus-haile-selassie/profil/spieler/357871.
Performance history data appended for: https://www.transfermarkt.com/fabian-rohner/profil/spieler/451483.
Performance history data appended for: https://www.transfermarkt.com/antonio-marchesano/profil/spieler/150963.
Performance history data appended for: https://www.transfermarkt.com/assan-ceesay/profil/spieler/388382.
Performance history data appended for: https://www.transfermarkt.com/silvan-wallner/profil/spieler/602443.
Performance history data appended for: https://www.transfermarkt.com/blaz-kramer/profil/spieler/322288.
Performance history data appended for: https://www.transfermarkt.com/ousmane-doumbia/profil/spieler/286292.
Performance history data appended for: https://www.transfermarkt.com/umaru-bangura/profil/spieler/38304.
Performance history data appended for: https://www.transfermarkt.com/novem-baumann/profil/spieler/183308.
Performance history data appended for: https://www.transfermarkt.com/adrian-winter/profil/spieler/59681.
Performance history data appended for: https://www.transfermarkt.com/wilfried-gnonto/profil/spieler/627626.
Performance history data appended for: https://www.transfermarkt.com/yanick-brecher/profil/spieler/165532.
Performance history data appended for: https://www.transfermarkt.com/nils-reichmuth/profil/spieler/507412.
Performance history data appended for: https://www.transfermarkt.com/salim-khelifi/profil/spieler/147049.
Performance history data appended for: https://www.transfermarkt.com/toni-domgjoni/profil/spieler/344649.
Performance history data appended for: https://www.transfermarkt.com/filip-frei/profil/spieler/507468.
Performance history data appended for: https://www.transfermarkt.com/nathan/profil/spieler/339711.
Performance history data appended for: https://www.transfermarkt.com/henri-koide/profil/spieler/507495.
Performance history data appended for: https://www.transfermarkt.com/stephan-seiler/profil/spieler/421819.
Performance history data appended for: https://www.transfermarkt.com/hekuran-kryeziu/profil/spieler/168979.
Performance history data appended for: https://www.transfermarkt.com/marco-schonbachler/profil/spieler/47528.
Performance history data appended for: https://www.transfermarkt.com/aiyegun-tosin/profil/spieler/239647.
Performance history data appended for: https://www.transfermarkt.com/lasse-sobiech/profil/spieler/79503.
Performance history data appended for: https://www.transfermarkt.com/tobias-schattin/profil/spieler/237679.
Performance history data appended for: https://www.transfermarkt.com/raphael-rossi/profil/spieler/290271.
Performance history data appended for: https://www.transfermarkt.com/jean-ruiz/profil/spieler/345067.
Performance history data appended for: https://www.transfermarkt.com/andre-edgar/profil/spieler/525924.
Performance history data appended for: https://www.transfermarkt.com/mauro-rodrigues/profil/spieler/514623.
Performance history data appended for: https://www.transfermarkt.com/geoffroy-serey-die/profil/spieler/77708.
Performance history data appended for: https://www.transfermarkt.com/yamato-wakatsuki/profil/spieler/657624.
Performance history data appended for: https://www.transfermarkt.com/itaitinga/profil/spieler/610123.
Performance history data appended for: https://www.transfermarkt.com/nathanael-saintini/profil/spieler/585950.
Performance history data appended for: https://www.transfermarkt.com/aimery-pinga/profil/spieler/347097.
Performance history data appended for: https://www.transfermarkt.com/gaetan-karlen/profil/spieler/166400.
Performance history data appended for: https://www.transfermarkt.com/damien-buchard/profil/spieler/346887.
Performance history data appended for: https://www.transfermarkt.com/ayoub-abdellaoui/profil/spieler/262208.
Performance history data appended for: https://www.transfermarkt.com/baltazar/profil/spieler/585346.
Performance history data appended for: https://www.transfermarkt.com/roberts-uldrikis/profil/spieler/342152.
Performance history data appended for: https://www.transfermarkt.com/timothy-fayulu/profil/spieler/541420.
Performance history data appended for: https://www.transfermarkt.com/nasser-daoudou-msa/profil/spieler/531356.
Performance history data appended for: https://www.transfermarkt.com/siyar-doldur/profil/spieler/346888.
Performance history data appended for: https://www.transfermarkt.com/artan-asani/profil/spieler/355772.
Performance history data appended for: https://www.transfermarkt.com/nikita-vlasenko/profil/spieler/510898.
Performance history data appended for: https://www.transfermarkt.com/sandro-theler/profil/spieler/421820.
Performance history data appended for: https://www.transfermarkt.com/birama-ndoye/profil/spieler/237903.
Performance history data appended for: https://www.transfermarkt.com/matteo-tosetti/profil/spieler/111453.

Performance history data appended for: https://www.transfermarkt.com/alexandre-nsakala/profil/spieler/418656.
Performance history data appended for: https://www.transfermarkt.com/christian-zock/profil/spieler/337017.
Performance history data appended for: https://www.transfermarkt.com/jan-bamert/profil/spieler/289875.
Performance history data appended for: https://www.transfermarkt.com/guillaume-hoarau/profil/spieler/23934.
Performance history data appended for: https://www.transfermarkt.com/dennis-iapichino/profil/spieler/123711.
Performance history data appended for: https://www.transfermarkt.com/jared-khasa/profil/spieler/425460.
Performance history data appended for: https://www.transfermarkt.com/musa-araz/profil/spieler/147037.
Performance history data appended for: https://www.transfermarkt.com/patrick-luan/profil/spieler/518676.
Performance history data appended for: https://www.transfermarkt.com/mattias-andersson/profil/spieler/342407.
Performance history data appended for: https://www.transfermarkt.com/kevin-fickentscher/profil/spieler/33651.
Performance history data appended for: https://www.transfermarkt.com/anto-grgic/profil/spieler/192637.
Performance history data appended for: https://www.transfermarkt.com/luca-clemenza/profil/spieler/291520.
Performance history data appended for: https://www.transfermarkt.com/dimitri-cavare/profil/spieler/278553.
Performance history data appended for: https://www.transfermarkt.com/arian-kabashi/profil/spieler/335548.
Performance history data appended for: https://www.transfermarkt.com/ivan-martic/profil/spieler/73048.
Performance history data appended for: https://www.transfermarkt.com/yassin-fortune/profil/spieler/342878.
Performance history data appended for: https://www.transfermarkt.com/nathan-senerine/profil/spieler/488171.
Performance history data appended for: https://www.transfermarkt.com/nico-maier/profil/spieler/346904.
Performance history data appended for: https://www.transfermarkt.com/fabian-rieder/profil/spieler/507341.
Performance history data appended for: https://www.transfermarkt.com/nicolas-burgy/profil/spieler/203895.
Performance history data appended for: https://www.transfermarkt.com/nicolas-moumi-ngamaleu/profil/spieler/266768.
Performance history data appended for: https://www.transfermarkt.com/marvin-spielmann/profil/spieler/192653.
Performance history data appended for: https://www.transfermarkt.com/fabian-lustenberger/profil/spieler/42203.
Performance history data appended for: https://www.transfermarkt.com/felix-mambimbi/profil/spieler/507496.
Performance history data appended for: https://www.transfermarkt.com/miralem-sulejmani/profil/spieler/36080.
Performance history data appended for: https://www.transfermarkt.com/sandro-lauper/profil/spieler/254965.
Performance history data appended for: https://www.transfermarkt.com/esteban-petignat/profil/spieler/479480.
Performance history data appended for: https://www.transfermarkt.com/jean-pierre-nsame/profil/spieler/225055.
Performance history data appended for: https://www.transfermarkt.com/jordan-lefort/profil/spieler/192492.
Performance history data appended for: https://www.transfermarkt.com/guillaume-faivre/profil/spieler/32750.
Performance history data appended for: https://www.transfermarkt.com/vincent-sierro/profil/spieler/280387.
Performance history data appended for: https://www.transfermarkt.com/taulant-seferi/profil/spieler/254985.
Performance history data appended for: https://www.transfermarkt.com/joschua-neuenschwander/profil/spieler/346905.
Performance history data appended for: https://www.transfermarkt.com/jordan-siebatcheu/profil/spieler/355369.
Performance history data appended for: https://www.transfermarkt.com/christopher-martins-pereira/profil/spieler/248054.
Performance history data appended for: https://www.transfermarkt.com/mohamed-camara/profil/spieler/426723.
Performance history data appended for: https://www.transfermarkt.com/christian-fassnacht/profil/spieler/250490.
Performance history data appended for: https://www.transfermarkt.com/leo-seydoux/profil/spieler/313097.
Performance history data appended for: https://www.transfermarkt.com/gianluca-gaudino/profil/spieler/195051.
Performance history data appended for: https://www.transfermarkt.com/cedric-zesiger/profil/spieler/382478.
Performance history data appended for: https://www.transfermarkt.com/michel-aebischer/profil/spieler/237658.
Performance history data appended for: https://www.transfermarkt.com/david-von-ballmoos/profil/spieler/203124.
Performance history data appended for: https://www.transfermarkt.com/silvan-hefti/profil/spieler/237666.
Performance history data appended for: https://www.transfermarkt.com/ulisses-garcia/profil/spieler/192616.
Performance history data appended for: https://www.transfermarkt.com/quentin-maceiras/profil/spieler/274498.
Performance history data appended for: https://www.transfermarkt.com/meschack-elia/profil/spieler/423678.
Performance history data appended for: https://www.transfermarkt.com/miroslav-stevanovic/profil/spieler/75816.
Performance history data appended for: https://www.transfermarkt.com/boubacar-fofana/profil/spieler/563098.
Performance history data appended for: https://www.transfermarkt.com/alexis-antunes/profil/spieler/346898.
Performance history data appended for: https://www.transfermarkt.com/gael-ondoua/profil/spieler/322309.
Performance history data appended for: https://www.transfermarkt.com/alexis-guerin/profil/spieler/695055.
Performance history data appended for: https://www.transfermarkt.com/boris-cespedes/profil/spieler/183311.
Performance history data appended for: https://www.transfermarkt.com/yoan-severin/profil/spieler/340065.
Performance history data appended for: https://www.transfermarkt.com/nicolas-vouilloz/profil/spieler/507488.
Performance history data appended for: https://www.transfermarkt.com/theo-valls/profil/spieler/341396.
Performance history data appended for: https://www.transfermarkt.com/alban-ajdini/profil/spieler/511801.
Performance history data appended for: https://www.transfermarkt.com/steve-rouiller/profil/spieler/88404.
Performance history data appended for: https://www.transfermarkt.com/edin-omeragic/profil/spieler/507391.
Performance history data appended for: https://www.transfermarkt.com/vincent-sasso/profil/spieler/122115.
Performance history data appended for: https://www.transfermarkt.com/alex-schalk/profil/spieler/186228.
Performance history data appended for: https://www.transfermarkt.com/timothe-cognat/profil/spieler/324796.
Performance history data appended for: https://www.transfermarkt.com/gael-clichy/profil/spieler/7449.
Performance history data appended for: https://www.transfermarkt.com/koro-kone/profil/spieler/61005.
Performance history data appended for: https://www.transfermarkt.com/ricardo-azevedo/profil/spieler/507466.
Performance history data appended for: https://www.transfermarkt.com/mathis-holcbecher/profil/spieler/507469.
Performance history data appended for: https://www.transfermarkt.com/kastriot-imeri/profil/spieler/469957.
Performance history data appended for: https://www.transfermarkt.com/joel-kiassumbua/profil/spieler/111423.
Performance history data appended for: https://www.transfermarkt.com/anthony-sauthier/profil/spieler/69899.
Performance history data appended for: https://www.transfermarkt.com/jeremy-frick/profil/spieler/170344.
Performance history data appended for: https://www.transfermarkt.com/matteo-regillo/profil/spieler/509829.
Performance history data appended for: https://www.transfermarkt.com/moussa-diallo/profil/spieler/450390.
Performance history data appended for: https://www.transfermarkt.com/grejohn-kyei/profil/spieler/321647.
Performance history data appended for: https://www.transfermarkt.com/noah-henchoz/profil/spieler/507340.
Performance history data appended for: https://www.transfermarkt.com/theophilious-opoku-mensah/profil/spieler/507411.
Performance history data appended for: https://www.transfermarkt.com/arial-mendy/profil/spieler/422715.
Performance history data appended for: https://www.transfermarkt.com/alexis-martial/profil/spieler/613767.
Performance history data appended for: https://www.transfermarkt.com/arthur-cabral/profil/spieler/390638.

Performance history data appended for: https://www.transfermarkt.com/aldo-kalulu/profil/spieler/292822.
Performance history data appended for: https://www.transfermarkt.com/eray-comert/profil/spieler/298583.
Performance history data appended for: https://www.transfermarkt.com/yannick-marchand/profil/spieler/346882.
Performance history data appended for: https://www.transfermarkt.com/taulant-xhaka/profil/spieler/113125.
Performance history data appended for: https://www.transfermarkt.com/mihailo-stevanovic/profil/spieler/499330.
Performance history data appended for: https://www.transfermarkt.com/afimico-pululu/profil/spieler/410649.
Performance history data appended for: https://www.transfermarkt.com/jasper-van-der-werff/profil/spieler/322519.
Performance history data appended for: https://www.transfermarkt.com/jorge/profil/spieler/345084.
Performance history data appended for: https://www.transfermarkt.com/djordje-nikolic/profil/spieler/274344.
Performance history data appended for: https://www.transfermarkt.com/edon-zhegrova/profil/spieler/496857.
Performance history data appended for: https://www.transfermarkt.com/julian-von-moos/profil/spieler/500762.
Performance history data appended for: https://www.transfermarkt.com/jozef-pukaj/profil/spieler/421809.
Performance history data appended for: https://www.transfermarkt.com/albian-hajdari/profil/spieler/579459.
Performance history data appended for: https://www.transfermarkt.com/lirik-vishi/profil/spieler/499213.
Performance history data appended for: https://www.transfermarkt.com/andrea-padula/profil/spieler/334665.
Performance history data appended for: https://www.transfermarkt.com/valentin-stocker/profil/spieler/45178.
Performance history data appended for: https://www.transfermarkt.com/liam-chipperfield/profil/spieler/604780.
Performance history data appended for: https://www.transfermarkt.com/timm-klose/profil/spieler/65255.
Performance history data appended for: https://www.transfermarkt.com/silvan-widmer/profil/spieler/168989.
Performance history data appended for: https://www.transfermarkt.com/luca-zuffi/profil/spieler/59246.
Performance history data appended for: https://www.transfermarkt.com/felix-gebhardt/profil/spieler/499317.
Performance history data appended for: https://www.transfermarkt.com/pajtim-kasami/profil/spieler/130108.
Performance history data appended for: https://www.transfermarkt.com/orges-bunjaku/profil/spieler/499214.
Performance history data appended for: https://www.transfermarkt.com/elis-isufi/profil/spieler/346889.
Performance history data appended for: https://www.transfermarkt.com/ricky-van-wolfswinkel/profil/spieler/41355.
Performance history data appended for: https://www.transfermarkt.com/samuele-campo/profil/spieler/183446.
Performance history data appended for: https://www.transfermarkt.com/raoul-petretta/profil/spieler/243878.
Performance history data appended for: https://www.transfermarkt.com/tician-tushi/profil/spieler/507499.
Performance history data appended for: https://www.transfermarkt.com/heinz-lindner/profil/spieler/59082.
Performance history data appended for: https://www.transfermarkt.com/konstantinos-dimitriou/profil/spieler/348522.
Performance history data appended for: https://www.transfermarkt.com/fabian-frei/profil/spieler/52595.
Performance history data appended for: https://www.transfermarkt.com/dimitri-oberlin/profil/spieler/212718.
Performance history data appended for: https://www.transfermarkt.com/benjamin-buchel/profil/spieler/66708.
Performance history data appended for: https://www.transfermarkt.com/mohamed-coulibaly/profil/spieler/74607.
Performance history data appended for: https://www.transfermarkt.com/yannick-schmid/profil/spieler/291896.
Performance history data appended for: https://www.transfermarkt.com/gion-chande/profil/spieler/290013.
Performance history data appended for: https://www.transfermarkt.com/sandro-wieser/profil/spieler/130227.
Performance history data appended for: https://www.transfermarkt.com/justin-ospelt/profil/spieler/405831.
Performance history data appended for: https://www.transfermarkt.com/ferhat-saglam/profil/spieler/508069.
Performance history data appended for: https://www.transfermarkt.com/joel-schmied/profil/spieler/322517.
Performance history data appended for: https://www.transfermarkt.com/tunahan-cicek/profil/spieler/154573.
Performance history data appended for: https://www.transfermarkt.com/matteo-di-giusto/profil/spieler/421823.
Performance history data appended for: https://www.transfermarkt.com/cedric-gasser/profil/spieler/384104.
Performance history data appended for: https://www.transfermarkt.com/nicolae-milinceanu/profil/spieler/256669.
Performance history data appended for: https://www.transfermarkt.com/fuad-rahimi/profil/spieler/410601.
Performance history data appended for: https://www.transfermarkt.com/pius-dorn/profil/spieler/192166.
Performance history data appended for: https://www.transfermarkt.com/dejan-djokic/profil/spieler/524710.
Performance history data appended for: https://www.transfermarkt.com/yago-gomes-do-nascimento/profil/spieler/603773.
Performance history data appended for: https://www.transfermarkt.com/boris-prokopic/profil/spieler/48076.
Performance history data appended for: https://www.transfermarkt.com/milan-gajic/profil/spieler/46928.
Performance history data appended for: https://www.transfermarkt.com/denis-simani/profil/spieler/135344.
Performance history data appended for: https://www.transfermarkt.com/linus-obexer/profil/spieler/254972.
Performance history data appended for: https://www.transfermarkt.com/maximilian-goppel/profil/spieler/294704.
Performance history data appended for: https://www.transfermarkt.com/sebastian-santin/profil/spieler/192082.
Performance history data appended for: https://www.transfermarkt.com/gianni-antoniazzi/profil/spieler/322504.
Performance history data appended for: https://www.transfermarkt.com/gabriel-luchinger/profil/spieler/159714.
Performance history data appended for: https://www.transfermarkt.com/nico-hug/profil/spieler/274681.
Performance history data appended for: https://www.transfermarkt.com/manuel-sutter/profil/spieler/59140.
Performance history data appended for: https://www.transfermarkt.com/fabio-solimando/profil/spieler/507463.
Performance history data appended for: https://www.transfermarkt.com/vincent-rufli/profil/spieler/23874.
Performance history data appended for: https://www.transfermarkt.com/miro-muheim/profil/spieler/298603.
Performance history data appended for: https://www.transfermarkt.com/basil-stillhart/profil/spieler/269526.
Performance history data appended for: https://www.transfermarkt.com/florian-kamberi/profil/spieler/284020.
Performance history data appended for: https://www.transfermarkt.com/nicolas-luchinger/profil/spieler/183260.
Performance history data appended for: https://www.transfermarkt.com/alessandro-krauchi/profil/spieler/289892.
Performance history data appended for: https://www.transfermarkt.com/betim-fazliji/profil/spieler/410636.
Performance history data appended for: https://www.transfermarkt.com/kwadwo-duah/profil/spieler/254955.
Performance history data appended for: https://www.transfermarkt.com/jeremy-guillemenot/profil/spieler/290016.
Performance history data appended for: https://www.transfermarkt.com/fabiano-alves/profil/spieler/347398.
Performance history data appended for: https://www.transfermarkt.com/lukas-gortler/profil/spieler/179638.
Performance history data appended for: https://www.transfermarkt.com/lawrence-ati-zigi/profil/spieler/254285.
Performance history data appended for: https://www.transfermarkt.com/andre-ribeiro/profil/spieler/342482.
Performance history data appended for: https://www.transfermarkt.com/lorenzo-gonzalez/profil/spieler/346901.
Performance history data appended for: https://www.transfermarkt.com/adonis-ajeti/profil/spieler/223380.
Performance history data appended for: https://www.transfermarkt.com/lukas-watkowiak/profil/spieler/196791.
Performance history data appended for: https://www.transfermarkt.com/salifou-diarrassouba/profil/spieler/649459.
Performance history data appended for: https://www.transfermarkt.com/boubacar-traore/profil/spieler/410083.

Performance history data appended for: https://www.transfermarkt.com/angelo-campos/profil/spieler/421821.
Performance history data appended for: https://www.transfermarkt.com/thody-elie-youan/profil/spieler/465715.
Performance history data appended for: https://www.transfermarkt.com/armin-abaz/profil/spieler/357862.
Performance history data appended for: https://www.transfermarkt.com/nico-strubi/profil/spieler/346896.
Performance history data appended for: https://www.transfermarkt.com/victor-ruiz/profil/spieler/336857.
Performance history data appended for: https://www.transfermarkt.com/jordi-quintilla/profil/spieler/166679.
Performance history data appended for: https://www.transfermarkt.com/musah-nuhu/profil/spieler/477681.
Performance history data appended for: https://www.transfermarkt.com/boris-babic/profil/spieler/237660.
Performance history data appended for: https://www.transfermarkt.com/leonidas-stergiou/profil/spieler/507345.
Performance history data appended for: https://www.transfermarkt.com/tim-staubli/profil/spieler/346894.
Performance history data appended for: https://www.transfermarkt.com/yannis-letard/profil/spieler/590280.
Performance history data appended for: https://www.transfermarkt.com/trazie-thomas/profil/spieler/819420.
Performance history data appended for: https://www.transfermarkt.com/marc-tsoungui/profil/spieler/357858.
Performance history data appended for: https://www.transfermarkt.com/mickael-nanizayamo/profil/spieler/463744.
Performance history data appended for: https://www.transfermarkt.com/simone-rapp/profil/spieler/154635.
Performance history data appended for: https://www.transfermarkt.com/gabriel-bares/profil/spieler/484743.
Performance history data appended for: https://www.transfermarkt.com/cameron-puertas/profil/spieler/449592.
Performance history data appended for: https://www.transfermarkt.com/lucas-da-cunha/profil/spieler/495667.
Performance history data appended for: https://www.transfermarkt.com/elton-monteiro/profil/spieler/122722.
Performance history data appended for: https://www.transfermarkt.com/mory-diaw/profil/spieler/164904.
Performance history data appended for: https://www.transfermarkt.com/anthony-koura/profil/spieler/127098.
Performance history data appended for: https://www.transfermarkt.com/rafik-zekhnini/profil/spieler/354278.
Performance history data appended for: https://www.transfermarkt.com/alvyn-sanches/profil/spieler/583058.
Performance history data appended for: https://www.transfermarkt.com/aldin-turkes/profil/spieler/192655.
Performance history data appended for: https://www.transfermarkt.com/noah-falk/profil/spieler/365096.
Performance history data appended for: https://www.transfermarkt.com/per-egil-flo/profil/spieler/41869.
Performance history data appended for: https://www.transfermarkt.com/noah-loosli/profil/spieler/265209.
Performance history data appended for: https://www.transfermarkt.com/armel-zohouri/profil/spieler/819419.
Performance history data appended for: https://www.transfermarkt.com/evann-guessand/profil/spieler/500689.
Performance history data appended for: https://www.transfermarkt.com/nicolas-getaz/profil/spieler/129642.
Performance history data appended for: https://www.transfermarkt.com/nikola-boranijasevic/profil/spieler/180090.
Performance history data appended for: https://www.transfermarkt.com/christian-schneuwly/profil/spieler/52556.
Performance history data appended for: https://www.transfermarkt.com/stjepan-kukuruzovic/profil/spieler/68655.
Performance history data appended for: https://www.transfermarkt.com/pedro-brazao/profil/spieler/577590.
Performance history data appended for: https://www.transfermarkt.com/thomas-castella/profil/spieler/165435.
Performance history data appended for: https://www.transfermarkt.com/theo-rochat/profil/spieler/525923.
Performance history data appended for: https://www.transfermarkt.com/joel-geissmann/profil/spieler/167188.
Performance history data appended for: https://www.transfermarkt.com/moritz-jenz/profil/spieler/460245.
Performance history data appended for: https://www.transfermarkt.com/josias-lukembila/profil/spieler/449590.
Performance history data appended for: https://www.transfermarkt.com/isaac-schmidt/profil/spieler/449597.
Performance history data appended for: https://www.transfermarkt.com/sebastian-cuerdo/profil/spieler/73072.
Performance history data appended for: https://www.transfermarkt.com/jorge-valdivia/profil/spieler/20758.
Performance history data appended for: https://www.transfermarkt.com/gonzalo-cordoba/profil/spieler/660736.
Performance history data appended for: https://www.transfermarkt.com/geronimo-poblete/profil/spieler/216714.
Performance history data appended for: https://www.transfermarkt.com/chriss-gutierrez/profil/spieler/460880.
Performance history data appended for: https://www.transfermarkt.com/denil-maldonado/profil/spieler/401769.
Performance history data appended for: https://www.transfermarkt.com/felix-charrupi/profil/spieler/651657.
Performance history data appended for: https://www.transfermarkt.com/jeison-lucumi/profil/spieler/352567.
Performance history data appended for: https://www.transfermarkt.com/daniel-munoz/profil/spieler/493003.
Performance history data appended for: https://www.transfermarkt.com/deiver-machado/profil/spieler/332560.
Performance history data appended for: https://www.transfermarkt.com/tino-costa/profil/spieler/77003.
Performance history data appended for: https://www.transfermarkt.com/pablo-ceppelini/profil/spieler/159773.
Performance history data appended for: https://www.transfermarkt.com/carlos-cuesta/profil/spieler/474589.
Performance history data appended for: https://www.transfermarkt.com/fabio-burbano/profil/spieler/119889.
Performance history data appended for: https://www.transfermarkt.com/brayan-perea/profil/spieler/188498.
Performance history data appended for: https://www.transfermarkt.com/jose-luis-caicedo/profil/spieler/662451.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/edwin-herrera/profil/spieler/602036.
Performance history data appended for: https://www.transfermarkt.com/luis-diaz/profil/spieler/480692.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/horacio-ramirez/profil/spieler/103117.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/luciano-guaycochea/profil/spieler/265082.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/wilson-cuero/profil/spieler/118520.
Performance history data appended for: https://www.transfermarkt.com/brayan-angulo/profil/spieler/312835.
Performance history data appended for: https://www.transfermarkt.com/jhon-quinones/profil/spieler/585350.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/fernando-aristeguieta/profil/spieler/140126.
Performance history data appended for: https://www.transfermarkt.com/jean-sinisterra/profil/spieler/648377.
Performance history data appended for: https://www.transfermarkt.com/juan-camilo-mesa/profil/spieler/624919.
Performance history data appended for: https://www.transfermarkt.com/gustavo-carvajal/profil/spieler/543466.
Performance history data appended for: https://www.transfermarkt.com/yeferson-contreras/profil/spieler/585351.
Performance history data appended for: https://www.transfermarkt.com/juan-nieva/profil/spieler/582545.
Performance history data appended for: https://www.transfermarkt.com/luis-hurtado/profil/spieler/428935.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/maximiliano-nunez/profil/spieler/83531.
Performance history data appended for: https://www.transfermarkt.com/jeison-quinones/profil/spieler/119344.
Performance history data appended for: https://www.transfermarkt.com/carlos-ibarguen/profil/spieler/362582.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/alvaro-villete/profil/spieler/227112.
Performance history data appended for: https://www.transfermarkt.com/herlbert-soto/profil/spieler/356662.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/kevin-londono/profil/spieler/421007.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/dario-andres-rodriguez/profil/spieler/312526.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/luis-mosquera/profil/spieler/601321.
Performance history data appended for: https://www.transfermarkt.com/diego-moreno/profil/spieler/312731.
Performance history data appended for: https://www.transfermarkt.com/yilton-diaz/profil/spieler/417778.
Performance history data appended for: https://www.transfermarkt.com/kevin-agudelo/profil/spieler/587458.
Performance history data appended for: https://www.transfermarkt.com/joaquin-gottesman/profil/spieler/498555.
Performance history data appended for: https://www.transfermarkt.com/wuilker-farinez/profil/spieler/373714.
Performance history data appended for: https://www.transfermarkt.com/jader-valencia/profil/spieler/570165.
Performance history data appended for: https://www.transfermarkt.com/marco-perez/profil/spieler/76648.
Performance history data appended for: https://www.transfermarkt.com/alex-castro/profil/spieler/304870.
Performance history data appended for: https://www.transfermarkt.com/jhonatan-agudelo/profil/spieler/313426.
Performance history data appended for: https://www.transfermarkt.com/lisandro-cabrera/profil/spieler/617776.
Performance history data appended for: https://www.transfermarkt.com/robert-carvajal/profil/spieler/636666.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/luis-ortiz/profil/spieler/748354.
Performance history data appended for: https://www.transfermarkt.com/jorge-obregon/profil/spieler/414773.
Performance history data appended for: https://www.transfermarkt.com/jhon-renteria/profil/spieler/573347.
Performance history data appended for: https://www.transfermarkt.com/yohn-mosquera/profil/spieler/92000.
Performance history data appended for: https://www.transfermarkt.com/juan-mosquera/profil/spieler/312732.
Performance history data appended for: https://www.transfermarkt.com/brayan-angulo/profil/spieler/312835.
Performance history data appended for: https://www.transfermarkt.com/william-palacios/profil/spieler/265982.
Performance history data appended for: https://www.transfermarkt.com/william-parra/profil/spieler/331066.
Performance history data appended for: https://www.transfermarkt.com/carlos-ibarguen/profil/spieler/362582.
Performance history data appended for: https://www.transfermarkt.com/nicolas-benedetti/profil/spieler/382836.
Performance history data appended for: https://www.transfermarkt.com/camilo-vargas/profil/spieler/74113.
Performance history data appended for: https://www.transfermarkt.com/juan-dinenno/profil/spieler/288786.
Performance history data appended for: https://www.transfermarkt.com/christian-rivera/profil/spieler/426324.
Performance history data appended for: https://www.transfermarkt.com/jhon-mosquera/profil/spieler/239126.
Performance history data appended for: https://www.transfermarkt.com/francisco-delorenzi/profil/spieler/648439.
Performance history data appended for: https://www.transfermarkt.com/carlos-carbonero/profil/spieler/136605.
Performance history data appended for: https://www.transfermarkt.com/kevin-balanta/profil/spieler/339758.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/maximiliano-freitas/profil/spieler/203367.
Performance history data appended for: https://www.transfermarkt.com/daniel-munoz/profil/spieler/493003.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/yilton-diaz/profil/spieler/417778.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/jose-ortiz/profil/spieler/572044.
Performance history data appended for: https://www.transfermarkt.com/felipe-ponce/profil/spieler/70083.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/jailson/profil/spieler/366948.
Performance history data appended for: https://www.transfermarkt.com/dyego-sousa/profil/spieler/157036.
Performance history data appended for: https://www.transfermarkt.com/tiquinho-soares/profil/spieler/103381.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/toni-sunjic/profil/spieler/60790.
Performance history data appended for: https://www.transfermarkt.com/miler-bolanos/profil/spieler/103246.
Performance history data appended for: https://www.transfermarkt.com/ibrahim-sadiq/profil/spieler/543501.
Performance history data appended for: https://www.transfermarkt.com/martin-vantruba/profil/spieler/415529.
Performance history data appended for: https://www.transfermarkt.com/maxwell-woledzi/profil/spieler/658529.
Performance history data appended for: https://www.transfermarkt.com/abu-francis/profil/spieler/658533.
Performance history data appended for: https://www.transfermarkt.com/ivan-mesik/profil/spieler/482838.
Performance history data appended for: https://www.transfermarkt.com/emeka-nnamani/profil/spieler/564453.
Performance history data appended for: https://www.transfermarkt.com/tochi-chukwuani/profil/spieler/553328.
Performance history data appended for: https://www.transfermarkt.com/magnus-kofod-andersen/profil/spieler/488784.
Performance history data appended for: https://www.transfermarkt.com/mohammed-diomande/profil/spieler/658531.
Performance history data appended for: https://www.transfermarkt.com/isaac-atanga/profil/spieler/599686.
Performance history data appended for: https://www.transfermarkt.com/mads-thychosen/profil/spieler/281252.
Performance history data appended for: https://www.transfermarkt.com/jacob-christensen/profil/spieler/515017.
Performance history data appended for: https://www.transfermarkt.com/joachim-rothmann/profil/spieler/455069.
Performance history data appended for: https://www.transfermarkt.com/kamaldeen-sulemana/profil/spieler/746695.
Performance history data appended for: https://www.transfermarkt.com/peter-vindahl/profil/spieler/395421.
Performance history data appended for: https://www.transfermarkt.com/oliver-rimmen/profil/spieler/462839.
Performance history data appended for: https://www.transfermarkt.com/andreas-gulstorff/profil/spieler/610423.
Performance history data appended for: https://www.transfermarkt.com/kian-hansen/profil/spieler/91469.
Performance history data appended for: https://www.transfermarkt.com/mikkel-rygaard/profil/spieler/51349.
Performance history data appended for: https://www.transfermarkt.com/oliver-villadsen/profil/spieler/462838.
Performance history data appended for: https://www.transfermarkt.com/johan-djourou/profil/spieler/34561.
Performance history data appended for: https://www.transfermarkt.com/ulrik-jenssen/profil/spieler/239044.
Performance history data appended for: https://www.transfermarkt.com/oliver-antman/profil/spieler/527896.
Performance history data appended for: https://www.transfermarkt.com/martin-frese/profil/spieler/488785.
Performance history data appended for: https://www.transfermarkt.com/andreas-bredahl/profil/spieler/610427.
Performance history data appended for: https://www.transfermarkt.com/jonathan-amon/profil/spieler/542776.
Performance history data appended for: https://www.transfermarkt.com/nicolaj-thomsen/profil/spieler/201497.
Performance history data appended for: https://www.transfermarkt.com/jens-stage/profil/spieler/289835.
Performance history data appended for: https://www.transfermarkt.com/peter-ankersen/profil/spieler/146889.
Performance history data appended for: https://www.transfermarkt.com/victor-nelsson/profil/spieler/422951.
Performance history data appended for: https://www.transfermarkt.com/marios-ikonomou/profil/spieler/174488.
Performance history data appended for: https://www.transfermarkt.com/sten-grytebust/profil/spieler/73417.
Performance history data appended for: https://www.transfermarkt.com/karl-johan-johnsson/profil/spieler/112822.
Performance history data appended for: https://www.transfermarkt.com/jonas-wind/profil/spieler/391004.
Performance history data appended for: https://www.transfermarkt.com/ragnar-sigurdsson/profil/spieler/46478.
Performance history data appended for: https://www.transfermarkt.com/rasmus-falk/profil/spieler/89200.
Performance history data appended for: https://www.transfermarkt.com/zanka/profil/spieler/52059.
Performance history data appended for: https://www.transfermarkt.com/mohammed-daramy/profil/spieler/574385.
Performance history data appended for: https://www.transfermarkt.com/bryan-oviedo/profil/spieler/124983.
Performance history data appended for: https://www.transfermarkt.com/karlo-bartolec/profil/spieler/291947.
Performance history data appended for: https://www.transfermarkt.com/stephan-andersen/profil/spieler/17880.
Performance history data appended for: https://www.transfermarkt.com/pep-biel/profil/spieler/263804.
Performance history data appended for: https://www.transfermarkt.com/andreas-bjelland/profil/spieler/56354.
Performance history data appended for: https://www.transfermarkt.com/kamil-wilczek/profil/spieler/78590.
Performance history data appended for: https://www.transfermarkt.com/robert-mudrazija/profil/spieler/339584.
Performance history data appended for: https://www.transfermarkt.com/viktor-fischer/profil/spieler/95755.
Performance history data appended for: https://www.transfermarkt.com/alexander-hjaelmhof/profil/spieler/515015.
Performance history data appended for: https://www.transfermarkt.com/nicolai-boilesen/profil/spieler/69642.
Performance history data appended for: https://www.transfermarkt.com/mikkel-kaufmann/profil/spieler/545332.
Performance history data appended for: https://www.transfermarkt.com/zeca/profil/spieler/131161.
Performance history data appended for: https://www.transfermarkt.com/pierre-bengtsson/profil/spieler/50577.
Performance history data appended for: https://www.transfermarkt.com/patrick-olsen/profil/spieler/135217.
Performance history data appended for: https://www.transfermarkt.com/alex-gersbach/profil/spieler/331017.
Performance history data appended for: https://www.transfermarkt.com/albert-gronbaek/profil/spieler/503866.
Performance history data appended for: https://www.transfermarkt.com/bror-blume/profil/spieler/189044.
Performance history data appended for: https://www.transfermarkt.com/magnus-anbo/profil/spieler/542686.
Performance history data appended for: https://www.transfermarkt.com/casper-hojer/profil/spieler/222977.
Performance history data appended for: https://www.transfermarkt.com/niklas-backman/profil/spieler/75453.
Performance history data appended for: https://www.transfermarkt.com/kamil-grabara/profil/spieler/346551.
Performance history data appended for: https://www.transfermarkt.com/soren-tengstedt/profil/spieler/541601.
Performance history data appended for: https://www.transfermarkt.com/patrick-mortensen/profil/spieler/69511.
Performance history data appended for: https://www.transfermarkt.com/mikkel-lassen/profil/spieler/515016.
Performance history data appended for: https://www.transfermarkt.com/kevin-diks/profil/spieler/335209.
Performance history data appended for: https://www.transfermarkt.com/gift-links/profil/spieler/445616.
Performance history data appended for: https://www.transfermarkt.com/benjamin-hvidt/profil/spieler/400544.
Performance history data appended for: https://www.transfermarkt.com/nicolai-poulsen/profil/spieler/253210.
Performance history data appended for: https://www.transfermarkt.com/sebastian-hausner/profil/spieler/425808.
Performance history data appended for: https://www.transfermarkt.com/mustafa-amini/profil/spieler/138091.
Performance history data appended for: https://www.transfermarkt.com/zachary-duncan/profil/spieler/659848.
Performance history data appended for: https://www.transfermarkt.com/milan-jevtovic/profil/spieler/236895.
Performance history data appended for: https://www.transfermarkt.com/nicklas-helenius/profil/spieler/102132.
Performance history data appended for: https://www.transfermarkt.com/jesper-juelsgaard/profil/spieler/20313.
Performance history data appended for: https://www.transfermarkt.com/kasper-kristensen/profil/spieler/542680.
Performance history data appended for: https://www.transfermarkt.com/daniel-gadegaard-andersen/profil/spieler/492490.
Performance history data appended for: https://www.transfermarkt.com/frederik-tingager/profil/spieler/289683.

Performance history data appended for: https://www.transfermarkt.com/william-eskelinen/profil/spieler/258970.
Performance history data appended for: https://www.transfermarkt.com/jon-dagur-thorsteinsson/profil/spieler/331739.
Performance history data appended for: https://www.transfermarkt.com/alexander-munksgaard/profil/spieler/283225.
Performance history data appended for: https://www.transfermarkt.com/mathias-ross/profil/spieler/545331.
Performance history data appended for: https://www.transfermarkt.com/tim-prica/profil/spieler/527347.
Performance history data appended for: https://www.transfermarkt.com/jores-okore/profil/spieler/129085.
Performance history data appended for: https://www.transfermarkt.com/daniel-granli/profil/spieler/266615.
Performance history data appended for: https://www.transfermarkt.com/andreas-hansen/profil/spieler/162101.
Performance history data appended for: https://www.transfermarkt.com/robert-kakeeto/profil/spieler/369673.
Performance history data appended for: https://www.transfermarkt.com/jakob-ahlmann/profil/spieler/48803.
Performance history data appended for: https://www.transfermarkt.com/kasper-pedersen/profil/spieler/261055.
Performance history data appended for: https://www.transfermarkt.com/timothe-nkada/profil/spieler/522788.
Performance history data appended for: https://www.transfermarkt.com/iver-fossum/profil/spieler/226450.
Performance history data appended for: https://www.transfermarkt.com/tom-van-weert/profil/spieler/95673.
Performance history data appended for: https://www.transfermarkt.com/vladimir-prijovic/profil/spieler/615597.
Performance history data appended for: https://www.transfermarkt.com/jacob-rinne/profil/spieler/210528.
Performance history data appended for: https://www.transfermarkt.com/malthe-hojholt/profil/spieler/543822.
Performance history data appended for: https://www.transfermarkt.com/rasmus-thelander/profil/spieler/129092.
Performance history data appended for: https://www.transfermarkt.com/magnus-christensen/profil/spieler/369675.
Performance history data appended for: https://www.transfermarkt.com/lucas-andersen/profil/spieler/148344.
Performance history data appended for: https://www.transfermarkt.com/kristoffer-pallesen/profil/spieler/161368.
Performance history data appended for: https://www.transfermarkt.com/kasper-kusk/profil/spieler/102134.
Performance history data appended for: https://www.transfermarkt.com/pedro-ferreira/profil/spieler/337799.
Performance history data appended for: https://www.transfermarkt.com/lukas-klitten/profil/spieler/490842.
Performance history data appended for: https://www.transfermarkt.com/oscar-hiljemark/profil/spieler/158810.
Performance history data appended for: https://www.transfermarkt.com/frederik-borsting/profil/spieler/309414.
Performance history data appended for: https://www.transfermarkt.com/jeppe-pedersen/profil/spieler/462831.
Performance history data appended for: https://www.transfermarkt.com/thomas-christiansen/profil/spieler/462829.
Performance history data appended for: https://www.transfermarkt.com/emmanuel-sabbi/profil/spieler/381187.
Performance history data appended for: https://www.transfermarkt.com/tarik-ibrahimagic/profil/spieler/602486.
Performance history data appended for: https://www.transfermarkt.com/troels-klove/profil/spieler/103434.
Performance history data appended for: https://www.transfermarkt.com/rasmus-nissen/profil/spieler/602487.
Performance history data appended for: https://www.transfermarkt.com/mart-lieder/profil/spieler/211331.
Performance history data appended for: https://www.transfermarkt.com/mads-frokjaer/profil/spieler/533632.
Performance history data appended for: https://www.transfermarkt.com/hans-christian-bernat/profil/spieler/400535.
Performance history data appended for: https://www.transfermarkt.com/oliver-christensen/profil/spieler/471936.
Performance history data appended for: https://www.transfermarkt.com/alexander-juel-andersen/profil/spieler/63459.
Performance history data appended for: https://www.transfermarkt.com/marco-lund/profil/spieler/293324.
Performance history data appended for: https://www.transfermarkt.com/sveinn-aron-gudjohnsen/profil/spieler/332527.
Performance history data appended for: https://www.transfermarkt.com/janus-drachmann/profil/spieler/50580.
Performance history data appended for: https://www.transfermarkt.com/aron-elis-thrandarson/profil/spieler/178926.
Performance history data appended for: https://www.transfermarkt.com/jeppe-tverskov/profil/spieler/257324.
Performance history data appended for: https://www.transfermarkt.com/moses-opondo/profil/spieler/369678.
Performance history data appended for: https://www.transfermarkt.com/max-fenger/profil/spieler/578920.
Performance history data appended for: https://www.transfermarkt.com/christian-vestergaard/profil/spieler/492489.
Performance history data appended for: https://www.transfermarkt.com/ryan-laursen/profil/spieler/157626.
Performance history data appended for: https://www.transfermarkt.com/mande-sayouba/profil/spieler/222124.
Performance history data appended for: https://www.transfermarkt.com/jorgen-skjelvik/profil/spieler/112336.
Performance history data appended for: https://www.transfermarkt.com/oliver-lund/profil/spieler/71701.
Performance history data appended for: https://www.transfermarkt.com/daniel-obbekjaer/profil/spieler/579809.
Performance history data appended for: https://www.transfermarkt.com/jens-thomasen/profil/spieler/260848.
Performance history data appended for: https://www.transfermarkt.com/mikkel-hyllegaard/profil/spieler/694974.
Performance history data appended for: https://www.transfermarkt.com/kasper-larsen/profil/spieler/95759.
Performance history data appended for: https://www.transfermarkt.com/ayo-simon-okosun/profil/spieler/173040.
Performance history data appended for: https://www.transfermarkt.com/issam-jebali/profil/spieler/122635.
Performance history data appended for: https://www.transfermarkt.com/simon-piesinger/profil/spieler/89541.
Performance history data appended for: https://www.transfermarkt.com/mikkel-kallesoe/profil/spieler/293134.
Performance history data appended for: https://www.transfermarkt.com/mathias-nielsen/profil/spieler/147112.
Performance history data appended for: https://www.transfermarkt.com/filip-bundgaard/profil/spieler/685145.
Performance history data appended for: https://www.transfermarkt.com/simon-graves/profil/spieler/542858.
Performance history data appended for: https://www.transfermarkt.com/andre-romer/profil/spieler/218085.
Performance history data appended for: https://www.transfermarkt.com/erik-marxen/profil/spieler/94293.
Performance history data appended for: https://www.transfermarkt.com/frederik-lauenborg/profil/spieler/320272.
Performance history data appended for: https://www.transfermarkt.com/mathias-greve/profil/spieler/237436.
Performance history data appended for: https://www.transfermarkt.com/tobias-klysner/profil/spieler/525990.
Performance history data appended for: https://www.transfermarkt.com/christoffer-petersen/profil/spieler/462830.
Performance history data appended for: https://www.transfermarkt.com/oliver-bundgaard/profil/spieler/566571.
Performance history data appended for: https://www.transfermarkt.com/issah-salou/profil/spieler/649287.
Performance history data appended for: https://www.transfermarkt.com/jonas-dakir/profil/spieler/464983.
Performance history data appended for: https://www.transfermarkt.com/marvin-egho/profil/spieler/274984.
Performance history data appended for: https://www.transfermarkt.com/alhaji-kamara/profil/spieler/235355.
Performance history data appended for: https://www.transfermarkt.com/karl-leth/profil/spieler/671847.
Performance history data appended for: https://www.transfermarkt.com/bjorn-kopplin/profil/spieler/45666.
Performance history data appended for: https://www.transfermarkt.com/nikola-mileusnic/profil/spieler/285775.
Performance history data appended for: https://www.transfermarkt.com/patrik-carlgren/profil/spieler/190280.
Performance history data appended for: https://www.transfermarkt.com/bassala-sambou/profil/spieler/406924.
Performance history data appended for: https://www.transfermarkt.com/vito-hammershoy-mistrati/profil/spieler/193724.

Performance history data appended for: https://www.transfermarkt.com/mads-enggaard/profil/spieler/752778.
Performance history data appended for: https://www.transfermarkt.com/jesper-lauridsen/profil/spieler/48864.
Performance history data appended for: https://www.transfermarkt.com/tosin-kehinde/profil/spieler/316750.
Performance history data appended for: https://www.transfermarkt.com/andreas-maxso/profil/spieler/253206.
Performance history data appended for: https://www.transfermarkt.com/sigurd-rosted/profil/spieler/230336.
Performance history data appended for: https://www.transfermarkt.com/michael-tornes/profil/spieler/43075.
Performance history data appended for: https://www.transfermarkt.com/mathias-kvistgaarden/profil/spieler/569663.
Performance history data appended for: https://www.transfermarkt.com/simon-hedlund/profil/spieler/116900.
Performance history data appended for: https://www.transfermarkt.com/anis-slimane/profil/spieler/546712.
Performance history data appended for: https://www.transfermarkt.com/rezan-corlu/profil/spieler/283193.
Performance history data appended for: https://www.transfermarkt.com/josip-radosevic/profil/spieler/160506.
Performance history data appended for: https://www.transfermarkt.com/tobias-borkeeiet/profil/spieler/458537.
Performance history data appended for: https://www.transfermarkt.com/kevin-mensah/profil/spieler/68983.
Performance history data appended for: https://www.transfermarkt.com/andreas-bruus/profil/spieler/345748.
Performance history data appended for: https://www.transfermarkt.com/andreas-pyndt/profil/spieler/482102.
Performance history data appended for: https://www.transfermarkt.com/anthony-jung/profil/spieler/58995.
Performance history data appended for: https://www.transfermarkt.com/peter-bjur/profil/spieler/482110.
Performance history data appended for: https://www.transfermarkt.com/joel-kabongo/profil/spieler/277236.
Performance history data appended for: https://www.transfermarkt.com/blas-riveros/profil/spieler/401732.
Performance history data appended for: https://www.transfermarkt.com/mads-hermansen/profil/spieler/400536.
Performance history data appended for: https://www.transfermarkt.com/marvin-schwabe/profil/spieler/160929.
Performance history data appended for: https://www.transfermarkt.com/morten-frendrup/profil/spieler/503871.
Performance history data appended for: https://www.transfermarkt.com/anton-skipper/profil/spieler/400538.
Performance history data appended for: https://www.transfermarkt.com/hjortur-hermannsson/profil/spieler/187147.
Performance history data appended for: https://www.transfermarkt.com/andrija-pavlovic/profil/spieler/188131.
Performance history data appended for: https://www.transfermarkt.com/jesper-lindstrom/profil/spieler/513245.
Performance history data appended for: https://www.transfermarkt.com/mikael-uhre/profil/spieler/264423.
Performance history data appended for: https://www.transfermarkt.com/lasse-vigen/profil/spieler/148376.
Performance history data appended for: https://www.transfermarkt.com/oliver-olsen/profil/spieler/400542.
Performance history data appended for: https://www.transfermarkt.com/alexander-scholz/profil/spieler/153582.
Performance history data appended for: https://www.transfermarkt.com/junior-brumado/profil/spieler/524590.
Performance history data appended for: https://www.transfermarkt.com/bozhidar-kraev/profil/spieler/293607.
Performance history data appended for: https://www.transfermarkt.com/daniel-hoegh/profil/spieler/99100.
Performance history data appended for: https://www.transfermarkt.com/jesper-hansen/profil/spieler/22860.
Performance history data appended for: https://www.transfermarkt.com/oliver-ottesen/profil/spieler/400708.
Performance history data appended for: https://www.transfermarkt.com/awer-mabil/profil/spieler/255729.
Performance history data appended for: https://www.transfermarkt.com/manjrekar-james/profil/spieler/222686.
Performance history data appended for: https://www.transfermarkt.com/paulinho/profil/spieler/520492.
Performance history data appended for: https://www.transfermarkt.com/nikolas-dyhr/profil/spieler/462837.
Performance history data appended for: https://www.transfermarkt.com/evander/profil/spieler/323874.
Performance history data appended for: https://www.transfermarkt.com/kristian-dirks-riis/profil/spieler/288436.
Performance history data appended for: https://www.transfermarkt.com/gustav-isaksen/profil/spieler/462823.
Performance history data appended for: https://www.transfermarkt.com/chuma-anene/profil/spieler/136167.
Performance history data appended for: https://www.transfermarkt.com/mikael-anderson/profil/spieler/403673.
Performance history data appended for: https://www.transfermarkt.com/sory-kaba/profil/spieler/355689.
Performance history data appended for: https://www.transfermarkt.com/dion-cools/profil/spieler/316422.
Performance history data appended for: https://www.transfermarkt.com/jens-cajuste/profil/spieler/468066.
Performance history data appended for: https://www.transfermarkt.com/mikkel-andersen/profil/spieler/42694.
Performance history data appended for: https://www.transfermarkt.com/ronnie-schwartz/profil/spieler/46007.
Performance history data appended for: https://www.transfermarkt.com/pione-sisto/profil/spieler/252641.
Performance history data appended for: https://www.transfermarkt.com/nicolas-madsen/profil/spieler/464599.
Performance history data appended for: https://www.transfermarkt.com/frank-onyeka/profil/spieler/421637.
Performance history data appended for: https://www.transfermarkt.com/luca-pfeiffer/profil/spieler/232463.
Performance history data appended for: https://www.transfermarkt.com/erik-sviatchenko/profil/spieler/48907.
Performance history data appended for: https://www.transfermarkt.com/anders-dreyer/profil/spieler/342389.
Performance history data appended for: https://www.transfermarkt.com/lasse-vibe/profil/spieler/62680.
Performance history data appended for: https://www.transfermarkt.com/joel-andersson/profil/spieler/255469.
Performance history data appended for: https://www.transfermarkt.com/japhet-sery/profil/spieler/403690.
Performance history data appended for: https://www.transfermarkt.com/casper-winther/profil/spieler/627936.
Performance history data appended for: https://www.transfermarkt.com/christian-jakobsen/profil/spieler/256186.
Performance history data appended for: https://www.transfermarkt.com/filip-panjeskovic/profil/spieler/610403.
Performance history data appended for: https://www.transfermarkt.com/thomas-mikkelsen/profil/spieler/23523.
Performance history data appended for: https://www.transfermarkt.com/adam-sorensen/profil/spieler/400537.
Performance history data appended for: https://www.transfermarkt.com/mathias-hebo-rasmussen/profil/spieler/311438.
Performance history data appended for: https://www.transfermarkt.com/kevin-tshiembe/profil/spieler/387745.
Performance history data appended for: https://www.transfermarkt.com/brian-hamalainen/profil/spieler/61336.
Performance history data appended for: https://www.transfermarkt.com/pascal-gregor/profil/spieler/253664.
Performance history data appended for: https://www.transfermarkt.com/rasmus-thellufsen/profil/spieler/283231.
Performance history data appended for: https://www.transfermarkt.com/frederik-gytkjaer/profil/spieler/72402.
Performance history data appended for: https://www.transfermarkt.com/ertugrul-teksen/profil/spieler/411646.
Performance history data appended for: https://www.transfermarkt.com/emil-kornvig/profil/spieler/455068.
Performance history data appended for: https://www.transfermarkt.com/magnus-warming/profil/spieler/482107.
Performance history data appended for: https://www.transfermarkt.com/frederik-winther/profil/spieler/569349.
Performance history data appended for: https://www.transfermarkt.com/marcel-romer/profil/spieler/107266.
Performance history data appended for: https://www.transfermarkt.com/emil-nielsen/profil/spieler/164647.
Performance history data appended for: https://www.transfermarkt.com/victor-torp/profil/spieler/403692.
Performance history data appended for: https://www.transfermarkt.com/jens-martin-gammelby/profil/spieler/265040.

Performance history data appended for: https://www.transfermarkt.com/kasper-enghardt/profil/spieler/201427.
Performance history data appended for: https://www.transfermarkt.com/frederik-schram/profil/spieler/279338.
Performance history data appended for: https://www.transfermarkt.com/lasse-fosgaard/profil/spieler/86310.
Performance history data appended for: https://www.transfermarkt.com/nicolai-geertsen/profil/spieler/157912.
Performance history data appended for: https://www.transfermarkt.com/andre-riel/profil/spieler/70567.
Performance history data appended for: https://www.transfermarkt.com/mads-greve/profil/spieler/95014.
Performance history data appended for: https://www.transfermarkt.com/malte-amundsen/profil/spieler/363466.
Performance history data appended for: https://www.transfermarkt.com/wahid-faghir/profil/spieler/610431.
Performance history data appended for: https://www.transfermarkt.com/jacob-schoop/profil/spieler/70544.
Performance history data appended for: https://www.transfermarkt.com/saeid-ezatolahi/profil/spieler/249271.
Performance history data appended for: https://www.transfermarkt.com/alexander-milosevic/profil/spieler/171376.
Performance history data appended for: https://www.transfermarkt.com/allan-sousa/profil/spieler/423197.
Performance history data appended for: https://www.transfermarkt.com/kevin-yamga/profil/spieler/290768.
Performance history data appended for: https://www.transfermarkt.com/viljormur-davidsen/profil/spieler/102123.
Performance history data appended for: https://www.transfermarkt.com/diego-montiel/profil/spieler/220441.
Performance history data appended for: https://www.transfermarkt.com/raphael-dwamena/profil/spieler/254290.
Performance history data appended for: https://www.transfermarkt.com/ylber-ramadani/profil/spieler/442703.
Performance history data appended for: https://www.transfermarkt.com/lucas-chang-andersen/profil/spieler/491389.
Performance history data appended for: https://www.transfermarkt.com/leonel-montano/profil/spieler/491391.
Performance history data appended for: https://www.transfermarkt.com/lundrim-hetemi/profil/spieler/527467.
Performance history data appended for: https://www.transfermarkt.com/matthew-briggs/profil/spieler/51318.
Performance history data appended for: https://www.transfermarkt.com/luis-henrique/profil/spieler/379877.
Performance history data appended for: https://www.transfermarkt.com/indy-groothuizen/profil/spieler/241389.
Performance history data appended for: https://www.transfermarkt.com/thomas-gundelund/profil/spieler/482106.
Performance history data appended for: https://www.transfermarkt.com/lucas-jensen/profil/spieler/213265.
Performance history data appended for: https://www.transfermarkt.com/emmerson/profil/spieler/213429.
Performance history data appended for: https://www.transfermarkt.com/tobias-molgaard/profil/spieler/341466.
Performance history data appended for: https://www.transfermarkt.com/juhani-ojala/profil/spieler/88257.
Performance history data appended for: https://www.transfermarkt.com/ivan-repyakh/profil/spieler/430487.
Performance history data appended for: https://www.transfermarkt.com/arbnor-mucolli/profil/spieler/467232.
Performance history data appended for: https://www.transfermarkt.com/alexander-brunst/profil/spieler/146693.
Performance history data appended for: https://www.transfermarkt.com/julius-eskesen/profil/spieler/345584.
Performance history data appended for: https://www.transfermarkt.com/stefan-gartenmann/profil/spieler/243770.
Performance history data appended for: https://www.transfermarkt.com/mads-hansen/profil/spieler/503867.
Performance history data appended for: https://www.transfermarkt.com/lawrence-thomas/profil/spieler/181337.
Performance history data appended for: https://www.transfermarkt.com/alexander-bah/profil/spieler/452607.
Performance history data appended for: https://www.transfermarkt.com/roni-arabaci/profil/spieler/584087.
Performance history data appended for: https://www.transfermarkt.com/patrick-banggaard/profil/spieler/186557.
Performance history data appended for: https://www.transfermarkt.com/rasmus-vinderslev/profil/spieler/495488.
Performance history data appended for: https://www.transfermarkt.com/mads-albaek/profil/spieler/48805.
Performance history data appended for: https://www.transfermarkt.com/philipp-schmiedl/profil/spieler/246063.
Performance history data appended for: https://www.transfermarkt.com/johan-absalonsen/profil/spieler/22831.
Performance history data appended for: https://www.transfermarkt.com/jannick-liburd/profil/spieler/610603.
Performance history data appended for: https://www.transfermarkt.com/pierre-kanstrup/profil/spieler/68976.
Performance history data appended for: https://www.transfermarkt.com/marc-dal-hende/profil/spieler/126610.
Performance history data appended for: https://www.transfermarkt.com/ogenyi-onazi/profil/spieler/131709.
Performance history data appended for: https://www.transfermarkt.com/rilwan-hassan/profil/spieler/140446.
Performance history data appended for: https://www.transfermarkt.com/mads-winther/profil/spieler/599677.
Performance history data appended for: https://www.transfermarkt.com/haji-wright/profil/spieler/315291.
Performance history data appended for: https://www.transfermarkt.com/jeppe-simonsen/profil/spieler/331975.
Performance history data appended for: https://www.transfermarkt.com/anders-jacobsen/profil/spieler/44726.
Performance history data appended for: https://www.transfermarkt.com/peter-christiansen/profil/spieler/542462.
Performance history data appended for: https://www.transfermarkt.com/nicolai-flo/profil/spieler/242750.
Performance history data appended for: https://www.transfermarkt.com/isak-oli-olafsson/profil/spieler/472866.
Performance history data appended for: https://www.transfermarkt.com/mads-steenberg/profil/spieler/599678.
Performance history data appended for: https://www.transfermarkt.com/emil-frederiksen/profil/spieler/422941.
Performance history data appended for: https://www.transfermarkt.com/victor-ekani/profil/spieler/489716.
Performance history data appended for: https://www.transfermarkt.com/bjarke-jacobsen/profil/spieler/239987.
Performance history data appended for: https://www.transfermarkt.com/alexander-ludwig/profil/spieler/184534.
Performance history data appended for: https://www.transfermarkt.com/kjartan-finnbogason/profil/spieler/29392.
Performance history data appended for: https://www.transfermarkt.com/james-gomez/profil/spieler/689634.
Performance history data appended for: https://www.transfermarkt.com/jacob-buus/profil/spieler/321851.
Performance history data appended for: https://www.transfermarkt.com/thor-lange/profil/spieler/234183.
Performance history data appended for: https://www.transfermarkt.com/michael-lansing/profil/spieler/448696.
Performance history data appended for: https://www.transfermarkt.com/jacob-trenskow/profil/spieler/542684.
Performance history data appended for: https://www.transfermarkt.com/jannik-pohl/profil/spieler/288432.
Performance history data appended for: https://www.transfermarkt.com/casper-tengstedt/profil/spieler/464598.
Performance history data appended for: https://www.transfermarkt.com/michael-lumb/profil/spieler/48867.
Performance history data appended for: https://www.transfermarkt.com/matej-delac/profil/spieler/60220.
Performance history data appended for: https://www.transfermarkt.com/agust-hlynsson/profil/spieler/396936.
Performance history data appended for: https://www.transfermarkt.com/rune-frantsen/profil/spieler/186486.
Performance history data appended for: https://www.transfermarkt.com/louka-prip/profil/spieler/388465.
Performance history data appended for: https://www.transfermarkt.com/peter-nymann/profil/spieler/23076.
Performance history data appended for: https://www.transfermarkt.com/hallur-hansson/profil/spieler/95984.
Performance history data appended for: https://www.transfermarkt.com/mathias-madsen/profil/spieler/554198.
Performance history data appended for: https://www.transfermarkt.com/nicolai-brock-madsen/profil/spieler/154051.
Performance history data appended for: https://www.transfermarkt.com/jonas-gemmer/profil/spieler/260838.

Performance history data appended for: https://www.transfermarkt.com/anders-hoff/profil/spieler/673976.
Performance history data appended for: https://www.transfermarkt.com/lirim-qamili/profil/spieler/523965.
Performance history data appended for: https://www.transfermarkt.com/david-kruse/profil/spieler/569654.
Performance history data appended for: https://www.transfermarkt.com/jonas-thorsen/profil/spieler/94295.
Performance history data appended for: https://www.transfermarkt.com/malte-kiilerich/profil/spieler/312712.
Performance history data appended for: https://www.transfermarkt.com/muamer-brajanac/profil/spieler/462819.
Performance history data appended for: https://www.transfermarkt.com/magnus-jensen/profil/spieler/448471.
Performance history data appended for: https://www.transfermarkt.com/andreas-foged/profil/spieler/583585.
Performance history data appended for: https://www.transfermarkt.com/rui-silva/profil/spieler/234811.
Performance history data appended for: https://www.transfermarkt.com/dimitri-foulquier/profil/spieler/170472.
Performance history data appended for: https://www.transfermarkt.com/domingos-duarte/profil/spieler/257376.
Performance history data appended for: https://www.transfermarkt.com/german-sanchez/profil/spieler/95963.
Performance history data appended for: https://www.transfermarkt.com/angel-montoro/profil/spieler/59551.
Performance history data appended for: https://www.transfermarkt.com/yangel-herrera/profil/spieler/378293.
Performance history data appended for: https://www.transfermarkt.com/neyder-lozano/profil/spieler/468700.
Performance history data appended for: https://www.transfermarkt.com/jesus-vallejo/profil/spieler/251896.
Performance history data appended for: https://www.transfermarkt.com/fede-vico/profil/spieler/162079.
Performance history data appended for: https://www.transfermarkt.com/jorge-molina/profil/spieler/57825.
Performance history data appended for: https://www.transfermarkt.com/carlos-neva/profil/spieler/448844.
Performance history data appended for: https://www.transfermarkt.com/quini/profil/spieler/223053.
Performance history data appended for: https://www.transfermarkt.com/luis-suarez/profil/spieler/424784.
Performance history data appended for: https://www.transfermarkt.com/alberto-soro/profil/spieler/487688.
Performance history data appended for: https://www.transfermarkt.com/luis-milla/profil/spieler/281989.
Performance history data appended for: https://www.transfermarkt.com/yan-eteki/profil/spieler/297784.
Performance history data appended for: https://www.transfermarkt.com/nehuen-perez/profil/spieler/491693.
Performance history data appended for: https://www.transfermarkt.com/ramon-azeez/profil/spieler/131667.
Performance history data appended for: https://www.transfermarkt.com/kenedy/profil/spieler/281404.
Performance history data appended for: https://www.transfermarkt.com/antonio-puertas/profil/spieler/262365.
Performance history data appended for: https://www.transfermarkt.com/maxime-gonalons/profil/spieler/60542.
Performance history data appended for: https://www.transfermarkt.com/roberto-soldado/profil/spieler/34870.
Performance history data appended for: https://www.transfermarkt.com/victor-diaz/profil/spieler/58330.
Performance history data appended for: https://www.transfermarkt.com/aaron-escandell/profil/spieler/284430.
Performance history data appended for: https://www.transfermarkt.com/darwin-machis/profil/spieler/211251.
Performance history data appended for: https://www.transfermarkt.com/pablo-hervias/profil/spieler/142027.
Performance history data appended for: https://www.transfermarkt.com/roberto/profil/spieler/37403.
Performance history data appended for: https://www.transfermarkt.com/nacho-martinez/profil/spieler/127554.
Performance history data appended for: https://www.transfermarkt.com/kike-perez/profil/spieler/527698.
Performance history data appended for: https://www.transfermarkt.com/luis-perez/profil/spieler/358115.
Performance history data appended for: https://www.transfermarkt.com/shon-weissman/profil/spieler/247652.
Performance history data appended for: https://www.transfermarkt.com/oscar-plano/profil/spieler/221309.
Performance history data appended for: https://www.transfermarkt.com/bruno-gonzalez/profil/spieler/188838.
Performance history data appended for: https://www.transfermarkt.com/roque-mesa/profil/spieler/202984.
Performance history data appended for: https://www.transfermarkt.com/ruben-alcaraz/profil/spieler/247250.
Performance history data appended for: https://www.transfermarkt.com/michel-herrero/profil/spieler/65331.
Performance history data appended for: https://www.transfermarkt.com/javi-sanchez/profil/spieler/340853.
Performance history data appended for: https://www.transfermarkt.com/saidy-janko/profil/spieler/196435.
Performance history data appended for: https://www.transfermarkt.com/waldo-rubio/profil/spieler/404688.
Performance history data appended for: https://www.transfermarkt.com/fabian-orellana/profil/spieler/60890.
Performance history data appended for: https://www.transfermarkt.com/joaquin-fernandez/profil/spieler/221321.
Performance history data appended for: https://www.transfermarkt.com/jordi-masip/profil/spieler/65263.
Performance history data appended for: https://www.transfermarkt.com/marcos-andre/profil/spieler/481084.
Performance history data appended for: https://www.transfermarkt.com/jota/profil/spieler/329812.
Performance history data appended for: https://www.transfermarkt.com/jawad-el-yamiq/profil/spieler/235412.
Performance history data appended for: https://www.transfermarkt.com/toni-villa/profil/spieler/337066.
Performance history data appended for: https://www.transfermarkt.com/kiko-olivas/profil/spieler/51667.
Performance history data appended for: https://www.transfermarkt.com/raul-carnero/profil/spieler/139434.
Performance history data appended for: https://www.transfermarkt.com/sergi-guardiola/profil/spieler/256429.
Performance history data appended for: https://www.transfermarkt.com/fede-san-emeterio/profil/spieler/307519.
Performance history data appended for: https://www.transfermarkt.com/raul-albiol/profil/spieler/15452.
Performance history data appended for: https://www.transfermarkt.com/moi-gomez/profil/spieler/175449.
Performance history data appended for: https://www.transfermarkt.com/juan-foyth/profil/spieler/480763.
Performance history data appended for: https://www.transfermarkt.com/alex-baena/profil/spieler/548111.
Performance history data appended for: https://www.transfermarkt.com/vicente-iborra/profil/spieler/65467.
Performance history data appended for: https://www.transfermarkt.com/yeremi-pino/profil/spieler/568157.
Performance history data appended for: https://www.transfermarkt.com/ruben-pena/profil/spieler/238868.
Performance history data appended for: https://www.transfermarkt.com/dani-parejo/profil/spieler/59561.
Performance history data appended for: https://www.transfermarkt.com/francis-coquelin/profil/spieler/74869.
Performance history data appended for: https://www.transfermarkt.com/dani-raba/profil/spieler/413262.
Performance history data appended for: https://www.transfermarkt.com/fer-nino/profil/spieler/627294.
Performance history data appended for: https://www.transfermarkt.com/gerard-moreno/profil/spieler/177467.
Performance history data appended for: https://www.transfermarkt.com/gero-rulli/profil/spieler/229604.
Performance history data appended for: https://www.transfermarkt.com/paco-alcacer/profil/spieler/126716.
Performance history data appended for: https://www.transfermarkt.com/ramiro-funes-mori/profil/spieler/11111.
Performance history data appended for: https://www.transfermarkt.com/alberto-moreno/profil/spieler/207917.
Performance history data appended for: https://www.transfermarkt.com/sergio-asenjo/profil/spieler/51710.
Performance history data appended for: https://www.transfermarkt.com/pau-torres/profil/spieler/399776.
Performance history data appended for: https://www.transfermarkt.com/filip-jorgensen/profil/spieler/585323.
Performance history data appended for: https://www.transfermarkt.com/samu-chukwueze/profil/spieler/401922.
Performance history data appended for: https://www.transfermarkt.com/takefusa-kubo/profil/spieler/405398.

Performance history data appended for: https://www.transfermarkt.com/pervis-estupinan/profil/spieler/349599.
Performance history data appended for: https://www.transfermarkt.com/jaume-costa/profil/spieler/65318.
Performance history data appended for: https://www.transfermarkt.com/manu-trigueros/profil/spieler/188854.
Performance history data appended for: https://www.transfermarkt.com/carlos-bacca/profil/spieler/119235.
Performance history data appended for: https://www.transfermarkt.com/alfonso-pedraza/profil/spieler/356197.
Performance history data appended for: https://www.transfermarkt.com/soufiane-chakla/profil/spieler/236956.
Performance history data appended for: https://www.transfermarkt.com/mario-gaspar/profil/spieler/73250.
Performance history data appended for: https://www.transfermarkt.com/victor-rodriguez/profil/spieler/129753.
Performance history data appended for: https://www.transfermarkt.com/antonio-barragan/profil/spieler/32522.
Performance history data appended for: https://www.transfermarkt.com/nino/profil/spieler/29178.
Performance history data appended for: https://www.transfermarkt.com/lucas-boye/profil/spieler/334222.
Performance history data appended for: https://www.transfermarkt.com/guido-carrillo/profil/spieler/184672.
Performance history data appended for: https://www.transfermarkt.com/emiliano-rigoni/profil/spieler/282544.
Performance history data appended for: https://www.transfermarkt.com/jeison-lucumi/profil/spieler/352567.
Performance history data appended for: https://www.transfermarkt.com/juan-sanchez-mino/profil/spieler/169249.
Performance history data appended for: https://www.transfermarkt.com/pere-milla/profil/spieler/225593.
Performance history data appended for: https://www.transfermarkt.com/miguel-cifuentes/profil/spieler/175836.
Performance history data appended for: https://www.transfermarkt.com/diego-rodriguez/profil/spieler/90800.
Performance history data appended for: https://www.transfermarkt.com/youssouf-kone/profil/spieler/274484.
Performance history data appended for: https://www.transfermarkt.com/dani-calvo/profil/spieler/326416.
Performance history data appended for: https://www.transfermarkt.com/edgar-badia/profil/spieler/102146.
Performance history data appended for: https://www.transfermarkt.com/diego-gonzalez/profil/spieler/349836.
Performance history data appended for: https://www.transfermarkt.com/gonzalo-verdu/profil/spieler/184779.
Performance history data appended for: https://www.transfermarkt.com/josan/profil/spieler/277533.
Performance history data appended for: https://www.transfermarkt.com/josema/profil/spieler/255892.
Performance history data appended for: https://www.transfermarkt.com/raul-guti/profil/spieler/330352.
Performance history data appended for: https://www.transfermarkt.com/fidel/profil/spieler/149231.
Performance history data appended for: https://www.transfermarkt.com/ivan-marcone/profil/spieler/90451.
Performance history data appended for: https://www.transfermarkt.com/luismi/profil/spieler/207922.
Performance history data appended for: https://www.transfermarkt.com/tete-morente/profil/spieler/339816.
Performance history data appended for: https://www.transfermarkt.com/omenuke-mfulu/profil/spieler/203516.
Performance history data appended for: https://www.transfermarkt.com/jan-oblak/profil/spieler/121483.
Performance history data appended for: https://www.transfermarkt.com/diego-costa/profil/spieler/44779.
Performance history data appended for: https://www.transfermarkt.com/vitolo/profil/spieler/67082.
Performance history data appended for: https://www.transfermarkt.com/stefan-savic/profil/spieler/107010.
Performance history data appended for: https://www.transfermarkt.com/sime-vrsaljko/profil/spieler/76061.
Performance history data appended for: https://www.transfermarkt.com/luis-suarez/profil/spieler/44352.
Performance history data appended for: https://www.transfermarkt.com/kieran-trippier/profil/spieler/95810.
Performance history data appended for: https://www.transfermarkt.com/ivo-grbic/profil/spieler/226073.
Performance history data appended for: https://www.transfermarkt.com/geoffrey-kondogbia/profil/spieler/127189.
Performance history data appended for: https://www.transfermarkt.com/marcos-llorente/profil/spieler/282411.
Performance history data appended for: https://www.transfermarkt.com/ivan-saponjic/profil/spieler/274347.
Performance history data appended for: https://www.transfermarkt.com/hector-herrera/profil/spieler/122043.
Performance history data appended for: https://www.transfermarkt.com/jose-gimenez/profil/spieler/250845.
Performance history data appended for: https://www.transfermarkt.com/angel-correa/profil/spieler/266807.
Performance history data appended for: https://www.transfermarkt.com/ricard-sanchez/profil/spieler/388545.
Performance history data appended for: https://www.transfermarkt.com/joao-felix/profil/spieler/462250.
Performance history data appended for: https://www.transfermarkt.com/manu-sanchez/profil/spieler/618809.
Performance history data appended for: https://www.transfermarkt.com/renan-lodi/profil/spieler/476352.
Performance history data appended for: https://www.transfermarkt.com/felipe/profil/spieler/156501.
Performance history data appended for: https://www.transfermarkt.com/lucas-torreira/profil/spieler/318077.
Performance history data appended for: https://www.transfermarkt.com/miguel-san-roman/profil/spieler/396337.
Performance history data appended for: https://www.transfermarkt.com/koke/profil/spieler/74229.
Performance history data appended for: https://www.transfermarkt.com/yannick-carrasco/profil/spieler/140776.
Performance history data appended for: https://www.transfermarkt.com/thomas-lemar/profil/spieler/205562.
Performance history data appended for: https://www.transfermarkt.com/saul-niguez/profil/spieler/148928.
Performance history data appended for: https://www.transfermarkt.com/mario-hermoso/profil/spieler/281769.
Performance history data appended for: https://www.transfermarkt.com/vinicius-junior/profil/spieler/371998.
Performance history data appended for: https://www.transfermarkt.com/mariano-diaz/profil/spieler/225020.
Performance history data appended for: https://www.transfermarkt.com/alvaro-odriozola/profil/spieler/280730.
Performance history data appended for: https://www.transfermarkt.com/federico-valverde/profil/spieler/369081.
Performance history data appended for: https://www.transfermarkt.com/martin-odegaard/profil/spieler/316264.
Performance history data appended for: https://www.transfermarkt.com/rodrygo/profil/spieler/412363.
Performance history data appended for: https://www.transfermarkt.com/ferland-mendy/profil/spieler/291417.
Performance history data appended for: https://www.transfermarkt.com/casemiro/profil/spieler/16306.
Performance history data appended for: https://www.transfermarkt.com/luka-modric/profil/spieler/27992.
Performance history data appended for: https://www.transfermarkt.com/sergio-ramos/profil/spieler/25557.
Performance history data appended for: https://www.transfermarkt.com/thibaut-courtois/profil/spieler/108390.
Performance history data appended for: https://www.transfermarkt.com/marcelo/profil/spieler/44501.
Performance history data appended for: https://www.transfermarkt.com/toni-kroos/profil/spieler/31909.
Performance history data appended for: https://www.transfermarkt.com/luka-jovic/profil/spieler/257462.
Performance history data appended for: https://www.transfermarkt.com/raphael-varane/profil/spieler/164770.
Performance history data appended for: https://www.transfermarkt.com/daniel-carvajal/profil/spieler/138927.
Performance history data appended for: https://www.transfermarkt.com/eder-militao/profil/spieler/401530.
Performance history data appended for: https://www.transfermarkt.com/karim-benzema/profil/spieler/18922.
Performance history data appended for: https://www.transfermarkt.com/isco/profil/spieler/85288.
Performance history data appended for: https://www.transfermarkt.com/nacho-fernandez/profil/spieler/58884.
Performance history data appended for: https://www.transfermarkt.com/lucas-vazquez/profil/spieler/221316.
Performance history data appended for: https://www.transfermarkt.com/andriy-lunin/profil/spieler/404839.

Performance history data appended for: https://www.transfermarkt.com/marco-asensio/profil/spieler/296622.
Performance history data appended for: https://www.transfermarkt.com/eden-hazard/profil/spieler/50202.
Performance history data appended for: https://www.transfermarkt.com/oscar-rodriguez/profil/spieler/284884.
Performance history data appended for: https://www.transfermarkt.com/tomas-vaclik/profil/spieler/64000.
Performance history data appended for: https://www.transfermarkt.com/oliver-torres/profil/spieler/214775.
Performance history data appended for: https://www.transfermarkt.com/joris-gnagnon/profil/spieler/378954.
Performance history data appended for: https://www.transfermarkt.com/bono/profil/spieler/207834.
Performance history data appended for: https://www.transfermarkt.com/luuk-de-jong/profil/spieler/72522.
Performance history data appended for: https://www.transfermarkt.com/suso/profil/spieler/111961.
Performance history data appended for: https://www.transfermarkt.com/diego-carlos/profil/spieler/329145.
Performance history data appended for: https://www.transfermarkt.com/lucas-ocampos/profil/spieler/189441.
Performance history data appended for: https://www.transfermarkt.com/karim-rekik/profil/spieler/182579.
Performance history data appended for: https://www.transfermarkt.com/sergi-gomez/profil/spieler/92947.
Performance history data appended for: https://www.transfermarkt.com/fernando-reges/profil/spieler/51174.
Performance history data appended for: https://www.transfermarkt.com/jesus-navas/profil/spieler/15956.
Performance history data appended for: https://www.transfermarkt.com/jules-kounde/profil/spieler/411975.
Performance history data appended for: https://www.transfermarkt.com/carlos-fernandez/profil/spieler/216464.
Performance history data appended for: https://www.transfermarkt.com/youssef-en-nesyri/profil/spieler/433049.
Performance history data appended for: https://www.transfermarkt.com/sergio-escudero/profil/spieler/93935.
Performance history data appended for: https://www.transfermarkt.com/marcos-acuna/profil/spieler/60410.
Performance history data appended for: https://www.transfermarkt.com/oussama-idrissi/profil/spieler/241391.
Performance history data appended for: https://www.transfermarkt.com/munir-el-haddadi/profil/spieler/223725.
Performance history data appended for: https://www.transfermarkt.com/javi-diaz/profil/spieler/396107.
Performance history data appended for: https://www.transfermarkt.com/joan-jordan/profil/spieler/263727.
Performance history data appended for: https://www.transfermarkt.com/ivan-rakitic/profil/spieler/32467.
Performance history data appended for: https://www.transfermarkt.com/aleix-vidal/profil/spieler/88490.
Performance history data appended for: https://www.transfermarkt.com/nemanja-gudelj/profil/spieler/74294.
Performance history data appended for: https://www.transfermarkt.com/franco-vazquez/profil/spieler/76163.
Performance history data appended for: https://www.transfermarkt.com/martin-zubimendi/profil/spieler/423440.
Performance history data appended for: https://www.transfermarkt.com/aritz-elustondo/profil/spieler/229804.
Performance history data appended for: https://www.transfermarkt.com/alex-remiro/profil/spieler/212862.
Performance history data appended for: https://www.transfermarkt.com/mikel-oyarzabal/profil/spieler/351478.
Performance history data appended for: https://www.transfermarkt.com/mikel-merino/profil/spieler/338424.
Performance history data appended for: https://www.transfermarkt.com/ander-barrenetxea/profil/spieler/616369.
Performance history data appended for: https://www.transfermarkt.com/asier-illarramendi/profil/spieler/59344.
Performance history data appended for: https://www.transfermarkt.com/alexander-isak/profil/spieler/349066.
Performance history data appended for: https://www.transfermarkt.com/nacho-monreal/profil/spieler/43003.
Performance history data appended for: https://www.transfermarkt.com/adnan-januzaj/profil/spieler/177847.
Performance history data appended for: https://www.transfermarkt.com/jon-guridi/profil/spieler/289257.
Performance history data appended for: https://www.transfermarkt.com/luca-sangalli/profil/spieler/289286.
Performance history data appended for: https://www.transfermarkt.com/igor-zubeldia/profil/spieler/355628.
Performance history data appended for: https://www.transfermarkt.com/portu/profil/spieler/99353.
Performance history data appended for: https://www.transfermarkt.com/martin-merquelanz/profil/spieler/289272.
Performance history data appended for: https://www.transfermarkt.com/ander-guevara/profil/spieler/465967.
Performance history data appended for: https://www.transfermarkt.com/david-silva/profil/spieler/35518.
Performance history data appended for: https://www.transfermarkt.com/joseba-zaldua/profil/spieler/197135.
Performance history data appended for: https://www.transfermarkt.com/alex-sola/profil/spieler/434990.
Performance history data appended for: https://www.transfermarkt.com/modibo-sagnan/profil/spieler/524925.
Performance history data appended for: https://www.transfermarkt.com/aihen-munoz/profil/spieler/517842.
Performance history data appended for: https://www.transfermarkt.com/miguel-angel-moya/profil/spieler/26065.
Performance history data appended for: https://www.transfermarkt.com/andoni-gorosabel/profil/spieler/289255.
Performance history data appended for: https://www.transfermarkt.com/willian-jose/profil/spieler/122155.
Performance history data appended for: https://www.transfermarkt.com/robin-le-normand/profil/spieler/351809.
Performance history data appended for: https://www.transfermarkt.com/jon-bautista/profil/spieler/289236.
Performance history data appended for: https://www.transfermarkt.com/roberto-lopez/profil/spieler/569866.
Performance history data appended for: https://www.transfermarkt.com/marcos-mauro/profil/spieler/247366.
Performance history data appended for: https://www.transfermarkt.com/yann-bodiger/profil/spieler/290533.
Performance history data appended for: https://www.transfermarkt.com/alfonso-espino/profil/spieler/311044.
Performance history data appended for: https://www.transfermarkt.com/ivan-alejo/profil/spieler/281755.
Performance history data appended for: https://www.transfermarkt.com/jorge-pombo/profil/spieler/336747.
Performance history data appended for: https://www.transfermarkt.com/jose-mari/profil/spieler/225462.
Performance history data appended for: https://www.transfermarkt.com/pedro-alcala/profil/spieler/51663.
Performance history data appended for: https://www.transfermarkt.com/filip-malba-scaron-i%C4%87/profil/spieler/162652.
Performance history data appended for: https://www.transfermarkt.com/iza-carcelen/profil/spieler/254037.
Performance history data appended for: https://www.transfermarkt.com/alvaro-gimenez/profil/spieler/57935.
Performance history data appended for: https://www.transfermarkt.com/alex-fernandez/profil/spieler/89733.
Performance history data appended for: https://www.transfermarkt.com/salvi-sanchez/profil/spieler/246204.
Performance history data appended for: https://www.transfermarkt.com/luismi-quezada/profil/spieler/282428.
Performance history data appended for: https://www.transfermarkt.com/bobby-adekanye/profil/spieler/331514.
Performance history data appended for: https://www.transfermarkt.com/jeremias-ledesma/profil/spieler/284342.
Performance history data appended for: https://www.transfermarkt.com/alvaro-negredo/profil/spieler/18644.
Performance history data appended for: https://www.transfermarkt.com/choco-lozano/profil/spieler/131275.
Performance history data appended for: https://www.transfermarkt.com/nano-mesa/profil/spieler/305956.
Performance history data appended for: https://www.transfermarkt.com/david-gil/profil/spieler/162027.
Performance history data appended for: https://www.transfermarkt.com/augusto-fernandez/profil/spieler/39151.
Performance history data appended for: https://www.transfermarkt.com/carlos-akapo/profil/spieler/225015.
Performance history data appended for: https://www.transfermarkt.com/jairo-izquierdo/profil/spieler/337946.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/fali/profil/spieler/252667.
Performance history data appended for: https://www.transfermarkt.com/juan-cala/profil/spieler/67089.
Performance history data appended for: https://www.transfermarkt.com/jon-ander-garrido/profil/spieler/158704.
Performance history data appended for: https://www.transfermarkt.com/sergio-gonzalez/profil/spieler/435500.
Performance history data appended for: https://www.transfermarkt.com/alberto-perea/profil/spieler/99559.
Performance history data appended for: https://www.transfermarkt.com/jens-jonsson/profil/spieler/148355.
Performance history data appended for: https://www.transfermarkt.com/lucas-torro/profil/spieler/213670.
Performance history data appended for: https://www.transfermarkt.com/jon-moncayola/profil/spieler/552425.
Performance history data appended for: https://www.transfermarkt.com/ruben-garcia/profil/spieler/213260.
Performance history data appended for: https://www.transfermarkt.com/aridane-hernandez/profil/spieler/82503.
Performance history data appended for: https://www.transfermarkt.com/david-garcia/profil/spieler/298589.
Performance history data appended for: https://www.transfermarkt.com/jonathan-calleri/profil/spieler/284727.
Performance history data appended for: https://www.transfermarkt.com/oier/profil/spieler/63040.
Performance history data appended for: https://www.transfermarkt.com/darko-brasanac/profil/spieler/95641.
Performance history data appended for: https://www.transfermarkt.com/brandon/profil/spieler/251680.
Performance history data appended for: https://www.transfermarkt.com/ruben-martinez/profil/spieler/8184.
Performance history data appended for: https://www.transfermarkt.com/enric-gallego/profil/spieler/114060.
Performance history data appended for: https://www.transfermarkt.com/kike-barja/profil/spieler/298575.
Performance history data appended for: https://www.transfermarkt.com/inigo-perez/profil/spieler/71579.
Performance history data appended for: https://www.transfermarkt.com/unai-garcia/profil/spieler/197122.
Performance history data appended for: https://www.transfermarkt.com/facundo-roncaglia/profil/spieler/61546.
Performance history data appended for: https://www.transfermarkt.com/juan-cruz/profil/spieler/169497.
Performance history data appended for: https://www.transfermarkt.com/raul-navas/profil/spieler/142419.
Performance history data appended for: https://www.transfermarkt.com/juan-perez/profil/spieler/298613.
Performance history data appended for: https://www.transfermarkt.com/adrian-lopez/profil/spieler/45383.
Performance history data appended for: https://www.transfermarkt.com/chimy-avila/profil/spieler/167721.
Performance history data appended for: https://www.transfermarkt.com/sergio-herrera/profil/spieler/248738.
Performance history data appended for: https://www.transfermarkt.com/jony/profil/spieler/228761.
Performance history data appended for: https://www.transfermarkt.com/nacho-vidal/profil/spieler/216870.
Performance history data appended for: https://www.transfermarkt.com/roberto-torres/profil/spieler/63056.
Performance history data appended for: https://www.transfermarkt.com/ante-budimir/profil/spieler/46413.
Performance history data appended for: https://www.transfermarkt.com/joel-robles/profil/spieler/101118.
Performance history data appended for: https://www.transfermarkt.com/alex-moreno/profil/spieler/193098.
Performance history data appended for: https://www.transfermarkt.com/william-carvalho/profil/spieler/100131.
Performance history data appended for: https://www.transfermarkt.com/victor-camarasa/profil/spieler/263856.
Performance history data appended for: https://www.transfermarkt.com/sergio-canales/profil/spieler/66106.
Performance history data appended for: https://www.transfermarkt.com/juanmi/profil/spieler/126737.
Performance history data appended for: https://www.transfermarkt.com/diego-lainez/profil/spieler/371174.
Performance history data appended for: https://www.transfermarkt.com/cristian-tello/profil/spieler/141834.
Performance history data appended for: https://www.transfermarkt.com/juan-miranda/profil/spieler/341227.
Performance history data appended for: https://www.transfermarkt.com/guido-rodriguez/profil/spieler/342385.
Performance history data appended for: https://www.transfermarkt.com/andres-guardado/profil/spieler/20506.
Performance history data appended for: https://www.transfermarkt.com/martin-montoya/profil/spieler/68645.
Performance history data appended for: https://www.transfermarkt.com/emerson/profil/spieler/476344.
Performance history data appended for: https://www.transfermarkt.com/loren-moron/profil/spieler/354741.
Performance history data appended for: https://www.transfermarkt.com/borja-iglesias/profil/spieler/278359.
Performance history data appended for: https://www.transfermarkt.com/aitor-ruibal/profil/spieler/378139.
Performance history data appended for: https://www.transfermarkt.com/marc-bartra/profil/spieler/99922.
Performance history data appended for: https://www.transfermarkt.com/aissa-mandi/profil/spieler/80293.
Performance history data appended for: https://www.transfermarkt.com/joaquin/profil/spieler/7663.
Performance history data appended for: https://www.transfermarkt.com/antonio-sanabria/profil/spieler/234523.
Performance history data appended for: https://www.transfermarkt.com/sidnei/profil/spieler/27374.
Performance history data appended for: https://www.transfermarkt.com/victor-ruiz/profil/spieler/62920.
Performance history data appended for: https://www.transfermarkt.com/nabil-fekir/profil/spieler/203496.
Performance history data appended for: https://www.transfermarkt.com/paul-akouokou/profil/spieler/429901.
Performance history data appended for: https://www.transfermarkt.com/claudio-bravo/profil/spieler/40423.
Performance history data appended for: https://www.transfermarkt.com/dani-martin/profil/spieler/335221.
Performance history data appended for: https://www.transfermarkt.com/florian-lejeune/profil/spieler/127108.
Performance history data appended for: https://www.transfermarkt.com/adrian-marin/profil/spieler/295414.
Performance history data appended for: https://www.transfermarkt.com/ruben-duarte/profil/spieler/177046.
Performance history data appended for: https://www.transfermarkt.com/pere-pons/profil/spieler/242497.
Performance history data appended for: https://www.transfermarkt.com/antonio-sivera/profil/spieler/298197.
Performance history data appended for: https://www.transfermarkt.com/rodrigo-battaglia/profil/spieler/89297.
Performance history data appended for: https://www.transfermarkt.com/manu-garcia/profil/spieler/76273.
Performance history data appended for: https://www.transfermarkt.com/ximo-navarro/profil/spieler/184767.
Performance history data appended for: https://www.transfermarkt.com/burgui/profil/spieler/246277.
Performance history data appended for: https://www.transfermarkt.com/victor-laguardia/profil/spieler/67080.
Performance history data appended for: https://www.transfermarkt.com/jota-peleteiro/profil/spieler/176591.
Performance history data appended for: https://www.transfermarkt.com/tachi/profil/spieler/354697.
Performance history data appended for: https://www.transfermarkt.com/sergi-garcia/profil/spieler/598608.
Performance history data appended for: https://www.transfermarkt.com/joselu/profil/spieler/81999.
Performance history data appended for: https://www.transfermarkt.com/martin-aguirregabiria/profil/spieler/483573.
Performance history data appended for: https://www.transfermarkt.com/borja-sainz/profil/spieler/634461.
Performance history data appended for: https://www.transfermarkt.com/javi-lopez/profil/spieler/568158.
Performance history data appended for: https://www.transfermarkt.com/deyverson/profil/spieler/243541.
Performance history data appended for: https://www.transfermarkt.com/john-guidetti/profil/spieler/98596.
Performance history data appended for: https://www.transfermarkt.com/tomas-pina/profil/spieler/139895.
Performance history data appended for: https://www.transfermarkt.com/lucas-perez/profil/spieler/73185.
Performance history data appended for: https://www.transfermarkt.com/edgar-mendez/profil/spieler/133794.

Performance history data appended for: https://www.transfermarkt.com/fernando-pacheco/profil/spieler/172015.
Performance history data appended for: https://www.transfermarkt.com/abdallahi-mahmoud/profil/spieler/615636.
Performance history data appended for: https://www.transfermarkt.com/rodrigo-ely/profil/spieler/176140.
Performance history data appended for: https://www.transfermarkt.com/luis-rioja/profil/spieler/278837.
Performance history data appended for: https://www.transfermarkt.com/tomas-tavares/profil/spieler/550549.
Performance history data appended for: https://www.transfermarkt.com/guillem-molina/profil/spieler/602156.
Performance history data appended for: https://www.transfermarkt.com/eliaquim-mangala/profil/spieler/90681.
Performance history data appended for: https://www.transfermarkt.com/uros-racic/profil/spieler/417575.
Performance history data appended for: https://www.transfermarkt.com/alex-blanco/profil/spieler/328914.
Performance history data appended for: https://www.transfermarkt.com/jason/profil/spieler/263860.
Performance history data appended for: https://www.transfermarkt.com/jasper-cillessen/profil/spieler/146227.
Performance history data appended for: https://www.transfermarkt.com/toni-lato/profil/spieler/320271.
Performance history data appended for: https://www.transfermarkt.com/denis-cheryshev/profil/spieler/98322.
Performance history data appended for: https://www.transfermarkt.com/hugo-guillamon/profil/spieler/495629.
Performance history data appended for: https://www.transfermarkt.com/goncalo-guedes/profil/spieler/225122.
Performance history data appended for: https://www.transfermarkt.com/manu-vallejo/profil/spieler/527350.
Performance history data appended for: https://www.transfermarkt.com/cristian-rivero/profil/spieler/398131.
Performance history data appended for: https://www.transfermarkt.com/ruben-sobrino/profil/spieler/85383.
Performance history data appended for: https://www.transfermarkt.com/kang-in-lee/profil/spieler/557149.
Performance history data appended for: https://www.transfermarkt.com/koba-koindredi/profil/spieler/569375.
Performance history data appended for: https://www.transfermarkt.com/jaume-domenech/profil/spieler/227805.
Performance history data appended for: https://www.transfermarkt.com/jose-gaya/profil/spieler/221322.
Performance history data appended for: https://www.transfermarkt.com/carlos-soler/profil/spieler/372246.
Performance history data appended for: https://www.transfermarkt.com/thierry-correia/profil/spieler/367466.
Performance history data appended for: https://www.transfermarkt.com/vicente-esquerdo/profil/spieler/599263.
Performance history data appended for: https://www.transfermarkt.com/daniel-wass/profil/spieler/63463.
Performance history data appended for: https://www.transfermarkt.com/yunus-musah/profil/spieler/503991.
Performance history data appended for: https://www.transfermarkt.com/gabriel-paulista/profil/spieler/149498.
Performance history data appended for: https://www.transfermarkt.com/maxi-gomez/profil/spieler/396894.
Performance history data appended for: https://www.transfermarkt.com/kevin-gameiro/profil/spieler/27389.
Performance history data appended for: https://www.transfermarkt.com/mouctar-diakhaby/profil/spieler/346289.
Performance history data appended for: https://www.transfermarkt.com/dani-cardenas/profil/spieler/397676.
Performance history data appended for: https://www.transfermarkt.com/aitor-fernandez/profil/spieler/118997.
Performance history data appended for: https://www.transfermarkt.com/jose-luis-morales/profil/spieler/252677.
Performance history data appended for: https://www.transfermarkt.com/gonzalo-melero/profil/spieler/162056.
Performance history data appended for: https://www.transfermarkt.com/cheick-doukoure/profil/spieler/129679.
Performance history data appended for: https://www.transfermarkt.com/carlos-clerc/profil/spieler/193784.
Performance history data appended for: https://www.transfermarkt.com/rober-pier/profil/spieler/387129.
Performance history data appended for: https://www.transfermarkt.com/oscar-duarte/profil/spieler/175323.
Performance history data appended for: https://www.transfermarkt.com/dani-gomez/profil/spieler/422460.
Performance history data appended for: https://www.transfermarkt.com/edgar-sevikyan/profil/spieler/430488.
Performance history data appended for: https://www.transfermarkt.com/sergio-postigo/profil/spieler/158791.
Performance history data appended for: https://www.transfermarkt.com/sontm/profil/spieler/349856.
Performance history data appended for: https://www.transfermarkt.com/nemanja-radoja/profil/spieler/168959.
Performance history data appended for: https://www.transfermarkt.com/ruben-vezo/profil/spieler/257851.
Performance history data appended for: https://www.transfermarkt.com/jose-campana/profil/spieler/120095.
Performance history data appended for: https://www.transfermarkt.com/roger-marti/profil/spieler/212391.
Performance history data appended for: https://www.transfermarkt.com/mickael-malsa/profil/spieler/205569.
Performance history data appended for: https://www.transfermarkt.com/coke/profil/spieler/71905.
Performance history data appended for: https://www.transfermarkt.com/enis-bardhi/profil/spieler/245014.
Performance history data appended for: https://www.transfermarkt.com/sergio-leon/profil/spieler/145769.
Performance history data appended for: https://www.transfermarkt.com/nikola-vukcevic/profil/spieler/151470.
Performance history data appended for: https://www.transfermarkt.com/tono/profil/spieler/125931.
Performance history data appended for: https://www.transfermarkt.com/jorge-de-frutos/profil/spieler/455181.
Performance history data appended for: https://www.transfermarkt.com/jorge-miramon/profil/spieler/228917.
Performance history data appended for: https://www.transfermarkt.com/ruben-rochina/profil/spieler/67548.
Performance history data appended for: https://www.transfermarkt.com/koke-vegas/profil/spieler/299715.
Performance history data appended for: https://www.transfermarkt.com/pape-diop/profil/spieler/39907.
Performance history data appended for: https://www.transfermarkt.com/edu-exposito/profil/spieler/506248.
Performance history data appended for: https://www.transfermarkt.com/bryan-gil/profil/spieler/537382.
Performance history data appended for: https://www.transfermarkt.com/kike-garcia/profil/spieler/93936.
Performance history data appended for: https://www.transfermarkt.com/sergi-enrich/profil/spieler/81988.
Performance history data appended for: https://www.transfermarkt.com/pedro-bigas/profil/spieler/203043.
Performance history data appended for: https://www.transfermarkt.com/paulo-oliveira/profil/spieler/139336.
Performance history data appended for: https://www.transfermarkt.com/yoel-rodriguez/profil/spieler/58115.
Performance history data appended for: https://www.transfermarkt.com/esteban-burgos/profil/spieler/337922.
Performance history data appended for: https://www.transfermarkt.com/rafa-soares/profil/spieler/198006.
Performance history data appended for: https://www.transfermarkt.com/alejandro-pozo/profil/spieler/341272.
Performance history data appended for: https://www.transfermarkt.com/marko-dmitrovic/profil/spieler/94308.
Performance history data appended for: https://www.transfermarkt.com/quique-gonzalez/profil/spieler/79352.
Performance history data appended for: https://www.transfermarkt.com/pedro-leon/profil/spieler/51587.
Performance history data appended for: https://www.transfermarkt.com/yoshinori-muto/profil/spieler/230541.
Performance history data appended for: https://www.transfermarkt.com/kevin-rodrigues/profil/spieler/206947.
Performance history data appended for: https://www.transfermarkt.com/takashi-inui/profil/spieler/98249.
Performance history data appended for: https://www.transfermarkt.com/jose-antonio-martinez/profil/spieler/311287.
Performance history data appended for: https://www.transfermarkt.com/jose-angel/profil/spieler/87469.
Performance history data appended for: https://www.transfermarkt.com/sergio-alvarez/profil/spieler/138935.
Performance history data appended for: https://www.transfermarkt.com/damian-kadzior/profil/spieler/199299.

Performance history data appended for: https://www.transfermarkt.com/roberto-correa/profil/spieler/223890.
Performance history data appended for: https://www.transfermarkt.com/anaitz-arbilla/profil/spieler/71548.
Performance history data appended for: https://www.transfermarkt.com/roberto-olabe/profil/spieler/242299.
Performance history data appended for: https://www.transfermarkt.com/recio/profil/spieler/150948.
Performance history data appended for: https://www.transfermarkt.com/jorge-pulido/profil/spieler/67546.
Performance history data appended for: https://www.transfermarkt.com/javi-ontiveros/profil/spieler/298983.
Performance history data appended for: https://www.transfermarkt.com/rafa-mir/profil/spieler/361254.
Performance history data appended for: https://www.transfermarkt.com/luisinho/profil/spieler/56777.
Performance history data appended for: https://www.transfermarkt.com/antonio-valera/profil/spieler/290275.
Performance history data appended for: https://www.transfermarkt.com/javi-galan/profil/spieler/448628.
Performance history data appended for: https://www.transfermarkt.com/kelechi-nwakali/profil/spieler/383153.
Performance history data appended for: https://www.transfermarkt.com/pedro-mosquera/profil/spieler/44069.
Performance history data appended for: https://www.transfermarkt.com/jaime-seoane/profil/spieler/340867.
Performance history data appended for: https://www.transfermarkt.com/dani-escriche/profil/spieler/531829.
Performance history data appended for: https://www.transfermarkt.com/david-ferreiro/profil/spieler/71918.
Performance history data appended for: https://www.transfermarkt.com/gaston-silva/profil/spieler/189452.
Performance history data appended for: https://www.transfermarkt.com/borja-garcia/profil/spieler/67808.
Performance history data appended for: https://www.transfermarkt.com/alvaro-fernandez/profil/spieler/453704.
Performance history data appended for: https://www.transfermarkt.com/eugeni-valderrama/profil/spieler/223073.
Performance history data appended for: https://www.transfermarkt.com/andres-fernandez/profil/spieler/57522.
Performance history data appended for: https://www.transfermarkt.com/idrissa-doumbia/profil/spieler/430579.
Performance history data appended for: https://www.transfermarkt.com/sandro-ramirez/profil/spieler/199369.
Performance history data appended for: https://www.transfermarkt.com/dimitrios-siovas/profil/spieler/52403.
Performance history data appended for: https://www.transfermarkt.com/pablo-maffeo/profil/spieler/251876.
Performance history data appended for: https://www.transfermarkt.com/pablo-insua/profil/spieler/171362.
Performance history data appended for: https://www.transfermarkt.com/shinji-okazaki/profil/spieler/79642.
Performance history data appended for: https://www.transfermarkt.com/sergio-gomez/profil/spieler/366930.
Performance history data appended for: https://www.transfermarkt.com/juan-carlos-real/profil/spieler/201861.
Performance history data appended for: https://www.transfermarkt.com/mikel-rico/profil/spieler/51474.
Performance history data appended for: https://www.transfermarkt.com/pedro-lopez/profil/spieler/25412.
Performance history data appended for: https://www.transfermarkt.com/jorge-saenz/profil/spieler/340339.
Performance history data appended for: https://www.transfermarkt.com/miguel-rodriguez/profil/spieler/634427.
Performance history data appended for: https://www.transfermarkt.com/david-costas/profil/spieler/276111.
Performance history data appended for: https://www.transfermarkt.com/lucas-olaza/profil/spieler/216240.
Performance history data appended for: https://www.transfermarkt.com/okay-yokuslu/profil/spieler/137616.
Performance history data appended for: https://www.transfermarkt.com/iago-aspas/profil/spieler/72047.
Performance history data appended for: https://www.transfermarkt.com/jeison-murillo/profil/spieler/131102.
Performance history data appended for: https://www.transfermarkt.com/ruben-blanco/profil/spieler/199321.
Performance history data appended for: https://www.transfermarkt.com/ivan-villar/profil/spieler/297194.
Performance history data appended for: https://www.transfermarkt.com/miguel-baeza/profil/spieler/523977.
Performance history data appended for: https://www.transfermarkt.com/fran-beltran/profil/spieler/423444.
Performance history data appended for: https://www.transfermarkt.com/denis-suarez/profil/spieler/165007.
Performance history data appended for: https://www.transfermarkt.com/emre-mor/profil/spieler/283223.
Performance history data appended for: https://www.transfermarkt.com/sergio-carreira/profil/spieler/545647.
Performance history data appended for: https://www.transfermarkt.com/nestor-araujo/profil/spieler/64134.
Performance history data appended for: https://www.transfermarkt.com/santi-mina/profil/spieler/255653.
Performance history data appended for: https://www.transfermarkt.com/david-junca/profil/spieler/164055.
Performance history data appended for: https://www.transfermarkt.com/nolito/profil/spieler/70934.
Performance history data appended for: https://www.transfermarkt.com/hugo-mallo/profil/spieler/119905.
Performance history data appended for: https://www.transfermarkt.com/gabriel-veiga/profil/spieler/699704.
Performance history data appended for: https://www.transfermarkt.com/renato-tapia/profil/spieler/277137.
Performance history data appended for: https://www.transfermarkt.com/joseph-aidoo/profil/spieler/358250.
Performance history data appended for: https://www.transfermarkt.com/sergio-alvarez/profil/spieler/45912.
Performance history data appended for: https://www.transfermarkt.com/kevin-vazquez/profil/spieler/221315.
Performance history data appended for: https://www.transfermarkt.com/brais-mendez/profil/spieler/309110.
Performance history data appended for: https://www.transfermarkt.com/antoine-griezmann/profil/spieler/125781.
Performance history data appended for: https://www.transfermarkt.com/marc-andre-ter-stegen/profil/spieler/74857.
Performance history data appended for: https://www.transfermarkt.com/clement-lenglet/profil/spieler/182904.
Performance history data appended for: https://www.transfermarkt.com/carles-alena/profil/spieler/284854.
Performance history data appended for: https://www.transfermarkt.com/ansu-fati/profil/spieler/466810.
Performance history data appended for: https://www.transfermarkt.com/frenkie-de-jong/profil/spieler/326330.
Performance history data appended for: https://www.transfermarkt.com/miralem-pjanic/profil/spieler/44162.
Performance history data appended for: https://www.transfermarkt.com/ousmane-dembele/profil/spieler/288230.
Performance history data appended for: https://www.transfermarkt.com/inaki-pena/profil/spieler/283170.
Performance history data appended for: https://www.transfermarkt.com/sergino-dest/profil/spieler/361104.
Performance history data appended for: https://www.transfermarkt.com/oscar-mingueza/profil/spieler/331505.
Performance history data appended for: https://www.transfermarkt.com/sergio-busquets/profil/spieler/65230.
Performance history data appended for: https://www.transfermarkt.com/ronald-araujo/profil/spieler/480267.
Performance history data appended for: https://www.transfermarkt.com/gerard-pique/profil/spieler/18944.
Performance history data appended for: https://www.transfermarkt.com/lionel-messi/profil/spieler/28003.
Performance history data appended for: https://www.transfermarkt.com/pedri/profil/spieler/683840.
Performance history data appended for: https://www.transfermarkt.com/junior-firpo/profil/spieler/374139.
Performance history data appended for: https://www.transfermarkt.com/neto/profil/spieler/111819.
Performance history data appended for: https://www.transfermarkt.com/trincao/profil/spieler/412669.
Performance history data appended for: https://www.transfermarkt.com/konrad-de-la-fuente/profil/spieler/466809.
Performance history data appended for: https://www.transfermarkt.com/sergi-roberto/profil/spieler/85370.
Performance history data appended for: https://www.transfermarkt.com/jordi-alba/profil/spieler/69751.
Performance history data appended for: https://www.transfermarkt.com/riqui-puig/profil/spieler/331511.

Performance history data appended for: https://www.transfermarkt.com/martin-braithwaite/profil/spieler/95732.
Performance history data appended for: https://www.transfermarkt.com/matheus-fernandes/profil/spieler/351892.
Performance history data appended for: https://www.transfermarkt.com/samuel-umtiti/profil/spieler/126540.
Performance history data appended for: https://www.transfermarkt.com/arnau-tenas/profil/spieler/466783.
Performance history data appended for: https://www.transfermarkt.com/philippe-coutinho/profil/spieler/80444.
Performance history data appended for: https://www.transfermarkt.com/dario-poveda/profil/spieler/399780.
Performance history data appended for: https://www.transfermarkt.com/mauro-arambarri/profil/spieler/290249.
Performance history data appended for: https://www.transfermarkt.com/ante-palaversa/profil/spieler/371003.
Performance history data appended for: https://www.transfermarkt.com/chema/profil/spieler/248330.
Performance history data appended for: https://www.transfermarkt.com/david-timor/profil/spieler/158795.
Performance history data appended for: https://www.transfermarkt.com/francisco-portillo/profil/spieler/138803.
Performance history data appended for: https://www.transfermarkt.com/damian-suarez/profil/spieler/76746.
Performance history data appended for: https://www.transfermarkt.com/marc-cucurella/profil/spieler/284857.
Performance history data appended for: https://www.transfermarkt.com/jaime-mata/profil/spieler/227961.
Performance history data appended for: https://www.transfermarkt.com/djene/profil/spieler/221150.
Performance history data appended for: https://www.transfermarkt.com/abdoulay-diaby/profil/spieler/148396.
Performance history data appended for: https://www.transfermarkt.com/leandro-chichizola/profil/spieler/95736.
Performance history data appended for: https://www.transfermarkt.com/enes-unal/profil/spieler/251106.
Performance history data appended for: https://www.transfermarkt.com/nemanja-maksimovic/profil/spieler/273152.
Performance history data appended for: https://www.transfermarkt.com/mathi-shy-as-olivera/profil/spieler/376514.
Performance history data appended for: https://www.transfermarkt.com/david-soria/profil/spieler/226012.
Performance history data appended for: https://www.transfermarkt.com/erick-cabaco/profil/spieler/302991.
Performance history data appended for: https://www.transfermarkt.com/ruben-yanez/profil/spieler/246335.
Performance history data appended for: https://www.transfermarkt.com/allan-nyom/profil/spieler/111508.
Performance history data appended for: https://www.transfermarkt.com/angel-rodriguez/profil/spieler/51510.
Performance history data appended for: https://www.transfermarkt.com/xabi-etxeita/profil/spieler/71559.
Performance history data appended for: https://www.transfermarkt.com/cucho-hernandez/profil/spieler/459463.
Performance history data appended for: https://www.transfermarkt.com/victor-mollejo/profil/spieler/505673.
Performance history data appended for: https://www.transfermarkt.com/unai-nunez/profil/spieler/338285.
Performance history data appended for: https://www.transfermarkt.com/inigo-cordoba/profil/spieler/251848.
Performance history data appended for: https://www.transfermarkt.com/peru-nolaskoain/profil/spieler/447052.
Performance history data appended for: https://www.transfermarkt.com/dani-garcia/profil/spieler/178425.
Performance history data appended for: https://www.transfermarkt.com/ander-capa/profil/spieler/197545.
Performance history data appended for: https://www.transfermarkt.com/ibai-gomez/profil/spieler/127837.
Performance history data appended for: https://www.transfermarkt.com/jokin-ezkieta/profil/spieler/379548.
Performance history data appended for: https://www.transfermarkt.com/mikel-vesga/profil/spieler/300168.
Performance history data appended for: https://www.transfermarkt.com/oier-zarraga/profil/spieler/524010.
Performance history data appended for: https://www.transfermarkt.com/oihan-sancet/profil/spieler/571020.
Performance history data appended for: https://www.transfermarkt.com/iker-muniain/profil/spieler/54235.
Performance history data appended for: https://www.transfermarkt.com/raul-garcia/profil/spieler/34601.
Performance history data appended for: https://www.transfermarkt.com/oscar-de-marcos/profil/spieler/96718.
Performance history data appended for: https://www.transfermarkt.com/inaki-williams/profil/spieler/255508.
Performance history data appended for: https://www.transfermarkt.com/iago-herrerin/profil/spieler/71570.
Performance history data appended for: https://www.transfermarkt.com/alex-berenguer/profil/spieler/338425.
Performance history data appended for: https://www.transfermarkt.com/inigo-vicente/profil/spieler/335216.
Performance history data appended for: https://www.transfermarkt.com/yuri-berchiche/profil/spieler/61812.
Performance history data appended for: https://www.transfermarkt.com/unai-vencedor/profil/spieler/610083.
Performance history data appended for: https://www.transfermarkt.com/inigo-lekue/profil/spieler/255501.
Performance history data appended for: https://www.transfermarkt.com/asier-villalibre/profil/spieler/251897.
Performance history data appended for: https://www.transfermarkt.com/unai-lopez/profil/spieler/192009.
Performance history data appended for: https://www.transfermarkt.com/yeray-alvarez/profil/spieler/255488.
Performance history data appended for: https://www.transfermarkt.com/jon-morcillo/profil/spieler/455349.
Performance history data appended for: https://www.transfermarkt.com/unai-simon/profil/spieler/262396.
Performance history data appended for: https://www.transfermarkt.com/mikel-balenziaga/profil/spieler/85258.
Performance history data appended for: https://www.transfermarkt.com/kenan-kodro/profil/spieler/197126.
Performance history data appended for: https://www.transfermarkt.com/inigo-martinez/profil/spieler/158863.
Performance history data appended for: https://www.transfermarkt.com/julito-martinez/profil/spieler/631067.
Performance history data appended for: https://www.transfermarkt.com/jose-matos/profil/spieler/268957.
Performance history data appended for: https://www.transfermarkt.com/david-lomban/profil/spieler/63723.
Performance history data appended for: https://www.transfermarkt.com/dani-barrio/profil/spieler/89471.
Performance history data appended for: https://www.transfermarkt.com/jairo-samperio/profil/spieler/171167.
Performance history data appended for: https://www.transfermarkt.com/alberto-escassi/profil/spieler/147232.
Performance history data appended for: https://www.transfermarkt.com/david-larrubia/profil/spieler/635939.
Performance history data appended for: https://www.transfermarkt.com/juan-cruz/profil/spieler/585700.
Performance history data appended for: https://www.transfermarkt.com/yanis-rahmani/profil/spieler/255506.
Performance history data appended for: https://www.transfermarkt.com/joaquin-munoz/profil/spieler/396334.
Performance history data appended for: https://www.transfermarkt.com/pablo-chavarria/profil/spieler/118732.
Performance history data appended for: https://www.transfermarkt.com/alberto-quintana/profil/spieler/631055.
Performance history data appended for: https://www.transfermarkt.com/caye-quintana/profil/spieler/238471.
Performance history data appended for: https://www.transfermarkt.com/gonzalo-crettaz/profil/spieler/631049.
Performance history data appended for: https://www.transfermarkt.com/ismael-casas/profil/spieler/465316.
Performance history data appended for: https://www.transfermarkt.com/luis-munoz/profil/spieler/355624.
Performance history data appended for: https://www.transfermarkt.com/juande-rivas/profil/spieler/465317.
Performance history data appended for: https://www.transfermarkt.com/ramon-enriquez/profil/spieler/567222.
Performance history data appended for: https://www.transfermarkt.com/juan-soriano/profil/spieler/251892.
Performance history data appended for: https://www.transfermarkt.com/orlando-sa/profil/spieler/64535.
Performance history data appended for: https://www.transfermarkt.com/alejandro-benitez/profil/spieler/610334.
Performance history data appended for: https://www.transfermarkt.com/cristo-romero/profil/spieler/696890.

Performance history data appended for: https://www.transfermarkt.com/mohamed-benkhemassa/profil/spieler/262220.
Performance history data appended for: https://www.transfermarkt.com/hicham-boussefiane/profil/spieler/465321.
Performance history data appended for: https://www.transfermarkt.com/cristian-rodriguez/profil/spieler/442802.
Performance history data appended for: https://www.transfermarkt.com/ivan-calero/profil/spieler/212849.
Performance history data appended for: https://www.transfermarkt.com/josua-mejias/profil/spieler/427683.
Performance history data appended for: https://www.transfermarkt.com/jozabed-sanchez/profil/spieler/207924.
Performance history data appended for: https://www.transfermarkt.com/uriel-jove/profil/spieler/724458.
Performance history data appended for: https://www.transfermarkt.com/nacho-gil/profil/spieler/336731.
Performance history data appended for: https://www.transfermarkt.com/david-fornies/profil/spieler/221984.
Performance history data appended for: https://www.transfermarkt.com/esteve-pena/profil/spieler/398130.
Performance history data appended for: https://www.transfermarkt.com/sergio-lozano/profil/spieler/341277.
Performance history data appended for: https://www.transfermarkt.com/elady-zorrilla/profil/spieler/240849.
Performance history data appended for: https://www.transfermarkt.com/verza/profil/spieler/26199.
Performance history data appended for: https://www.transfermarkt.com/alberto-de-la-bella/profil/spieler/73319.
Performance history data appended for: https://www.transfermarkt.com/julian-delmas/profil/spieler/509484.
Performance history data appended for: https://www.transfermarkt.com/marc-martinez/profil/spieler/129374.
Performance history data appended for: https://www.transfermarkt.com/kleandro-lleshi/profil/spieler/466800.
Performance history data appended for: https://www.transfermarkt.com/pablo-claveria/profil/spieler/348553.
Performance history data appended for: https://www.transfermarkt.com/jack-harper/profil/spieler/147524.
Performance history data appended for: https://www.transfermarkt.com/berto-cayarga/profil/spieler/510372.
Performance history data appended for: https://www.transfermarkt.com/alex-gallar/profil/spieler/210143.
Performance history data appended for: https://www.transfermarkt.com/david-andujar/profil/spieler/531267.
Performance history data appended for: https://www.transfermarkt.com/carlos-david/profil/spieler/65342.
Performance history data appended for: https://www.transfermarkt.com/william-de-camargo/profil/spieler/583607.
Performance history data appended for: https://www.transfermarkt.com/alex-martin/profil/spieler/345083.
Performance history data appended for: https://www.transfermarkt.com/jean-pierre-rhyner/profil/spieler/203981.
Performance history data appended for: https://www.transfermarkt.com/marcin-bulka/profil/spieler/465955.
Performance history data appended for: https://www.transfermarkt.com/simon-moreno/profil/spieler/355630.
Performance history data appended for: https://www.transfermarkt.com/sergio-aguza/profil/spieler/246244.
Performance history data appended for: https://www.transfermarkt.com/jose-angel-jurado/profil/spieler/187673.
Performance history data appended for: https://www.transfermarkt.com/david-simon/profil/spieler/228584.
Performance history data appended for: https://www.transfermarkt.com/ruben-castro/profil/spieler/25316.
Performance history data appended for: https://www.transfermarkt.com/adalberto-carrasquilla/profil/spieler/375300.
Performance history data appended for: https://www.transfermarkt.com/miguel-angel-cordero/profil/spieler/58778.
Performance history data appended for: https://www.transfermarkt.com/kenneth-omeruo/profil/spieler/131708.
Performance history data appended for: https://www.transfermarkt.com/sabin-merino/profil/spieler/192736.
Performance history data appended for: https://www.transfermarkt.com/javi-eraso/profil/spieler/156814.
Performance history data appended for: https://www.transfermarkt.com/sergio-gonzalez/profil/spieler/308989.
Performance history data appended for: https://www.transfermarkt.com/luis-perea/profil/spieler/396328.
Performance history data appended for: https://www.transfermarkt.com/rober-ibanez/profil/spieler/242532.
Performance history data appended for: https://www.transfermarkt.com/daniel-lasure/profil/spieler/336736.
Performance history data appended for: https://www.transfermarkt.com/javi-hernandez/profil/spieler/422466.
Performance history data appended for: https://www.transfermarkt.com/diego-conde/profil/spieler/341713.
Performance history data appended for: https://www.transfermarkt.com/juan-munoz/profil/spieler/268958.
Performance history data appended for: https://www.transfermarkt.com/ruben-perez/profil/spieler/113045.
Performance history data appended for: https://www.transfermarkt.com/borja-baston/profil/spieler/85324.
Performance history data appended for: https://www.transfermarkt.com/unai-bustinza/profil/spieler/156808.
Performance history data appended for: https://www.transfermarkt.com/sergi-palencia/profil/spieler/268176.
Performance history data appended for: https://www.transfermarkt.com/ivan-cuellar/profil/spieler/27493.
Performance history data appended for: https://www.transfermarkt.com/michael-santos/profil/spieler/178107.
Performance history data appended for: https://www.transfermarkt.com/asier-riesgo/profil/spieler/23338.
Performance history data appended for: https://www.transfermarkt.com/jonathan-silva/profil/spieler/189453.
Performance history data appended for: https://www.transfermarkt.com/miguel-de-la-fuente/profil/spieler/480883.
Performance history data appended for: https://www.transfermarkt.com/ruben-pardo/profil/spieler/99352.
Performance history data appended for: https://www.transfermarkt.com/rodri-tarin/profil/spieler/203617.
Performance history data appended for: https://www.transfermarkt.com/ignasi-miquel/profil/spieler/70245.
Performance history data appended for: https://www.transfermarkt.com/gaku-shibasaki/profil/spieler/129693.
Performance history data appended for: https://www.transfermarkt.com/dani-ojeda/profil/spieler/111621.
Performance history data appended for: https://www.transfermarkt.com/kevin-bua/profil/spieler/252080.
Performance history data appended for: https://www.transfermarkt.com/javier-aviles/profil/spieler/456938.
Performance history data appended for: https://www.transfermarkt.com/roberto-rosales/profil/spieler/49500.
Performance history data appended for: https://www.transfermarkt.com/jose-manuel-arnaiz/profil/spieler/364603.
Performance history data appended for: https://www.transfermarkt.com/giorgi-aburjania/profil/spieler/186848.
Performance history data appended for: https://www.transfermarkt.com/matias-nahuel/profil/spieler/263843.
Performance history data appended for: https://www.transfermarkt.com/sergio-tejera/profil/spieler/38817.
Performance history data appended for: https://www.transfermarkt.com/samuel-obeng/profil/spieler/522719.
Performance history data appended for: https://www.transfermarkt.com/bolano/profil/spieler/48294.
Performance history data appended for: https://www.transfermarkt.com/riki-rodriguez/profil/spieler/596899.
Performance history data appended for: https://www.transfermarkt.com/juanjo-nieto/profil/spieler/327207.
Performance history data appended for: https://www.transfermarkt.com/lucas-ahijado/profil/spieler/349884.
Performance history data appended for: https://www.transfermarkt.com/joan-femenias/profil/spieler/455363.
Performance history data appended for: https://www.transfermarkt.com/rodri-rios/profil/spieler/117549.
Performance history data appended for: https://www.transfermarkt.com/alejandro-arribas/profil/spieler/137174.
Performance history data appended for: https://www.transfermarkt.com/mossa/profil/spieler/96094.
Performance history data appended for: https://www.transfermarkt.com/cedric-teguia/profil/spieler/536831.
Performance history data appended for: https://www.transfermarkt.com/viti-rozada/profil/spieler/438971.
Performance history data appended for: https://www.transfermarkt.com/edgar-gonzalez/profil/spieler/401624.
Performance history data appended for: https://www.transfermarkt.com/jimmy/profil/spieler/595781.

Performance history data appended for: https://www.transfermarkt.com/simone-grippo/profil/spieler/41767.
Performance history data appended for: https://www.transfermarkt.com/rafa-mujica/profil/spieler/361504.
Performance history data appended for: https://www.transfermarkt.com/marco-sangalli/profil/spieler/197131.
Performance history data appended for: https://www.transfermarkt.com/gustavo-blanco-leschuk/profil/spieler/181006.
Performance history data appended for: https://www.transfermarkt.com/diegui/profil/spieler/349886.
Performance history data appended for: https://www.transfermarkt.com/carlos-hernandez/profil/spieler/225459.
Performance history data appended for: https://www.transfermarkt.com/borja-sanchez/profil/spieler/217155.
Performance history data appended for: https://www.transfermarkt.com/gabriel-brazao/profil/spieler/371247.
Performance history data appended for: https://www.transfermarkt.com/raul-lizoain/profil/spieler/167228.
Performance history data appended for: https://www.transfermarkt.com/erik-jirka/profil/spieler/339693.
Performance history data appended for: https://www.transfermarkt.com/mohamed-ezzarfani/profil/spieler/449844.
Performance history data appended for: https://www.transfermarkt.com/carlos-julio-martinez/profil/spieler/166658.
Performance history data appended for: https://www.transfermarkt.com/sergio-moreno/profil/spieler/607779.
Performance history data appended for: https://www.transfermarkt.com/ivan-martin/profil/spieler/341278.
Performance history data appended for: https://www.transfermarkt.com/juan-berrocal/profil/spieler/461843.
Performance history data appended for: https://www.transfermarkt.com/andres-mohedano/profil/spieler/289250.
Performance history data appended for: https://www.transfermarkt.com/javi-jimenez/profil/spieler/242287.
Performance history data appended for: https://www.transfermarkt.com/javi-munoz/profil/spieler/282421.
Performance history data appended for: https://www.transfermarkt.com/dani-vivian/profil/spieler/524000.
Performance history data appended for: https://www.transfermarkt.com/genaro-rodriguez/profil/spieler/396109.
Performance history data appended for: https://www.transfermarkt.com/antonio-caballero/profil/spieler/364890.
Performance history data appended for: https://www.transfermarkt.com/nicolas-jackson/profil/spieler/776890.
Performance history data appended for: https://www.transfermarkt.com/mario-barco/profil/spieler/248021.
Performance history data appended for: https://www.transfermarkt.com/pablo-trigueros/profil/spieler/248337.
Performance history data appended for: https://www.transfermarkt.com/nais-djouahra/profil/spieler/594926.
Performance history data appended for: https://www.transfermarkt.com/bojan-letic/profil/spieler/166985.
Performance history data appended for: https://www.transfermarkt.com/victor-meseguer/profil/spieler/658269.
Performance history data appended for: https://www.transfermarkt.com/limones/profil/spieler/57948.
Performance history data appended for: https://www.transfermarkt.com/victor-gomez/profil/spieler/495601.
Performance history data appended for: https://www.transfermarkt.com/ricardo-schutte/profil/spieler/600836.
Performance history data appended for: https://www.transfermarkt.com/pablo-martinez/profil/spieler/568835.
Performance history data appended for: https://www.transfermarkt.com/ismael-athuman/profil/spieler/351204.
Performance history data appended for: https://www.transfermarkt.com/aythami-artiles/profil/spieler/44735.
Performance history data appended for: https://www.transfermarkt.com/christian-rivera/profil/spieler/374077.
Performance history data appended for: https://www.transfermarkt.com/edu-espiau/profil/spieler/565523.
Performance history data appended for: https://www.transfermarkt.com/alex-suarez/profil/spieler/510396.
Performance history data appended for: https://www.transfermarkt.com/jonathan/profil/spieler/579346.
Performance history data appended for: https://www.transfermarkt.com/claudio-mendes/profil/spieler/699501.
Performance history data appended for: https://www.transfermarkt.com/enzo-loiodice/profil/spieler/581781.
Performance history data appended for: https://www.transfermarkt.com/alvaro-valles/profil/spieler/417913.
Performance history data appended for: https://www.transfermarkt.com/fabio-gonzalez/profil/spieler/531062.
Performance history data appended for: https://www.transfermarkt.com/ale-diez/profil/spieler/217143.
Performance history data appended for: https://www.transfermarkt.com/raul-fernandez/profil/spieler/54217.
Performance history data appended for: https://www.transfermarkt.com/sergio-araujo/profil/spieler/110366.
Performance history data appended for: https://www.transfermarkt.com/alvaro-lemos/profil/spieler/230222.
Performance history data appended for: https://www.transfermarkt.com/javi-castellano/profil/spieler/65489.
Performance history data appended for: https://www.transfermarkt.com/sergio-ruiz/profil/spieler/394694.
Performance history data appended for: https://www.transfermarkt.com/eric-curbelo/profil/spieler/390823.
Performance history data appended for: https://www.transfermarkt.com/alex-dominguez/profil/spieler/524937.
Performance history data appended for: https://www.transfermarkt.com/oscar-clemente/profil/spieler/396340.
Performance history data appended for: https://www.transfermarkt.com/pejino/profil/spieler/534379.
Performance history data appended for: https://www.transfermarkt.com/cristian-cedres/profil/spieler/261493.
Performance history data appended for: https://www.transfermarkt.com/tomas-cardona/profil/spieler/422700.
Performance history data appended for: https://www.transfermarkt.com/pietro-iemmello/profil/spieler/62735.
Performance history data appended for: https://www.transfermarkt.com/dani-castellano/profil/spieler/64363.
Performance history data appended for: https://www.transfermarkt.com/ariday-cabrera/profil/spieler/76032.
Performance history data appended for: https://www.transfermarkt.com/kirian-rodriguez/profil/spieler/566574.
Performance history data appended for: https://www.transfermarkt.com/rober-gonzalez/profil/spieler/505675.
Performance history data appended for: https://www.transfermarkt.com/benito-ramirez/profil/spieler/282672.
Performance history data appended for: https://www.transfermarkt.com/maikel-mesa/profil/spieler/197576.
Performance history data appended for: https://www.transfermarkt.com/arvin-appiah/profil/spieler/433257.
Performance history data appended for: https://www.transfermarkt.com/cesar-de-la-hoz/profil/spieler/226261.
Performance history data appended for: https://www.transfermarkt.com/jose-corpas/profil/spieler/379534.
Performance history data appended for: https://www.transfermarkt.com/jose-carlos-lazo/profil/spieler/282410.
Performance history data appended for: https://www.transfermarkt.com/pedro-mendes/profil/spieler/498235.
Performance history data appended for: https://www.transfermarkt.com/giorgi-makaridze/profil/spieler/55977.
Performance history data appended for: https://www.transfermarkt.com/chumi/profil/spieler/333361.
Performance history data appended for: https://www.transfermarkt.com/ager-aketxe/profil/spieler/158057.
Performance history data appended for: https://www.transfermarkt.com/mathieu-peybernes/profil/spieler/111026.
Performance history data appended for: https://www.transfermarkt.com/nikola-maras/profil/spieler/258475.
Performance history data appended for: https://www.transfermarkt.com/jordi-escobar/profil/spieler/568155.
Performance history data appended for: https://www.transfermarkt.com/joao-carvalho/profil/spieler/258005.
Performance history data appended for: https://www.transfermarkt.com/juan-villar/profil/spieler/85500.
Performance history data appended for: https://www.transfermarkt.com/manu-morlanes/profil/spieler/335225.
Performance history data appended for: https://www.transfermarkt.com/alex-centelles/profil/spieler/423443.
Performance history data appended for: https://www.transfermarkt.com/umar-sadiq/profil/spieler/337715.
Performance history data appended for: https://www.transfermarkt.com/aitor-bunuel/profil/spieler/374081.
Performance history data appended for: https://www.transfermarkt.com/ivan-balliu/profil/spieler/85295.

Performance history data appended for: https://www.transfermarkt.com/lucas-robertone/profil/spieler/457221.
Performance history data appended for: https://www.transfermarkt.com/largie-ramazani/profil/spieler/518644.
Performance history data appended for: https://www.transfermarkt.com/fran-villalba/profil/spieler/311680.
Performance history data appended for: https://www.transfermarkt.com/sergio-akieme/profil/spieler/355627.
Performance history data appended for: https://www.transfermarkt.com/radosav-petrovic/profil/spieler/75296.
Performance history data appended for: https://www.transfermarkt.com/jorge-cuenca/profil/spieler/494880.
Performance history data appended for: https://www.transfermarkt.com/cristian-olivera/profil/spieler/657746.
Performance history data appended for: https://www.transfermarkt.com/samu-costa/profil/spieler/657430.
Performance history data appended for: https://www.transfermarkt.com/fernando-martinez/profil/spieler/81997.
Performance history data appended for: https://www.transfermarkt.com/yuri/profil/spieler/22452.
Performance history data appended for: https://www.transfermarkt.com/jose-antonio-caro/profil/spieler/268946.
Performance history data appended for: https://www.transfermarkt.com/juergen-elitim/profil/spieler/607057.
Performance history data appended for: https://www.transfermarkt.com/jose-rios/profil/spieler/81980.
Performance history data appended for: https://www.transfermarkt.com/alexandru-pascanu/profil/spieler/421258.
Performance history data appended for: https://www.transfermarkt.com/dani-romera/profil/spieler/271451.
Performance history data appended for: https://www.transfermarkt.com/oscar-sielva/profil/spieler/67550.
Performance history data appended for: https://www.transfermarkt.com/gaspar-panadero/profil/spieler/251883.
Performance history data appended for: https://www.transfermarkt.com/paris-adot/profil/spieler/247583.
Performance history data appended for: https://www.transfermarkt.com/pablo-larrea/profil/spieler/373353.
Performance history data appended for: https://www.transfermarkt.com/yacouba-magagi/profil/spieler/461511.
Performance history data appended for: https://www.transfermarkt.com/manu-garcia/profil/spieler/446289.
Performance history data appended for: https://www.transfermarkt.com/adrian-castellano/profil/spieler/253826.
Performance history data appended for: https://www.transfermarkt.com/moussa-sidibe/profil/spieler/676922.
Performance history data appended for: https://www.transfermarkt.com/pablo-valcarce/profil/spieler/365313.
Performance history data appended for: https://www.transfermarkt.com/carlos-doncel/profil/spieler/379530.
Performance history data appended for: https://www.transfermarkt.com/jose-amo/profil/spieler/311454.
Performance history data appended for: https://www.transfermarkt.com/curro-sanchez/profil/spieler/208116.
Performance history data appended for: https://www.transfermarkt.com/alejandro-viedma/profil/spieler/331503.
Performance history data appended for: https://www.transfermarkt.com/gianfranco-gazzaniga/profil/spieler/270314.
Performance history data appended for: https://www.transfermarkt.com/saul-crespo/profil/spieler/387557.
Performance history data appended for: https://www.transfermarkt.com/erik-moran/profil/spieler/67542.
Performance history data appended for: https://www.transfermarkt.com/kaxe/profil/spieler/510999.
Performance history data appended for: https://www.transfermarkt.com/edward-bolanos/profil/spieler/608534.
Performance history data appended for: https://www.transfermarkt.com/ivan-rodriguez/profil/spieler/284454.
Performance history data appended for: https://www.transfermarkt.com/manu-hernando/profil/spieler/396161.
Performance history data appended for: https://www.transfermarkt.com/jesus-olmo/profil/spieler/39058.
Performance history data appended for: https://www.transfermarkt.com/xavi-boniquet/profil/spieler/127552.
Performance history data appended for: https://www.transfermarkt.com/victor-garcia/profil/spieler/590690.
Performance history data appended for: https://www.transfermarkt.com/pedro-capo/profil/spieler/131357.
Performance history data appended for: https://www.transfermarkt.com/juan-ibiza/profil/spieler/411294.
Performance history data appended for: https://www.transfermarkt.com/gorka-guruzeta/profil/spieler/340205.
Performance history data appended for: https://www.transfermarkt.com/oscar-rubio/profil/spieler/57999.
Performance history data appended for: https://www.transfermarkt.com/adri-cuevas/profil/spieler/168773.
Performance history data appended for: https://www.transfermarkt.com/stoichkov/profil/spieler/271021.
Performance history data appended for: https://www.transfermarkt.com/edgar-hernandez/profil/spieler/104236.
Performance history data appended for: https://www.transfermarkt.com/josu-ozkoidi/profil/spieler/89332.
Performance history data appended for: https://www.transfermarkt.com/aaron-rey/profil/spieler/430192.
Performance history data appended for: https://www.transfermarkt.com/aleix-coch/profil/spieler/152975.
Performance history data appended for: https://www.transfermarkt.com/froilan-leal/profil/spieler/815002.
Performance history data appended for: https://www.transfermarkt.com/ian-mackay/profil/spieler/88917.
Performance history data appended for: https://www.transfermarkt.com/antonio-romero/profil/spieler/268963.
Performance history data appended for: https://www.transfermarkt.com/juan-hernandez/profil/spieler/349873.
Performance history data appended for: https://www.transfermarkt.com/grego-sierra/profil/spieler/253905.
Performance history data appended for: https://www.transfermarkt.com/heber-pena/profil/spieler/275020.
Performance history data appended for: https://www.transfermarkt.com/iker-undabarrena/profil/spieler/181113.
Performance history data appended for: https://www.transfermarkt.com/pierre-cornud/profil/spieler/536156.
Performance history data appended for: https://www.transfermarkt.com/diego-fuoli/profil/spieler/531274.
Performance history data appended for: https://www.transfermarkt.com/angel-martinez/profil/spieler/45652.
Performance history data appended for: https://www.transfermarkt.com/nestor-querol/profil/spieler/441290.
Performance history data appended for: https://www.transfermarkt.com/jaime-sanchez/profil/spieler/212863.
Performance history data appended for: https://www.transfermarkt.com/david-astals/profil/spieler/727578.
Performance history data appended for: https://www.transfermarkt.com/alex-perez/profil/spieler/167830.
Performance history data appended for: https://www.transfermarkt.com/leonardo-ruiz/profil/spieler/344399.
Performance history data appended for: https://www.transfermarkt.com/enrique-clemente/profil/spieler/487951.
Performance history data appended for: https://www.transfermarkt.com/damian-petcoff/profil/spieler/185551.
Performance history data appended for: https://www.transfermarkt.com/gorka-perez/profil/spieler/383114.
Performance history data appended for: https://www.transfermarkt.com/unai-medina/profil/spieler/104234.
Performance history data appended for: https://www.transfermarkt.com/zelu/profil/spieler/231980.
Performance history data appended for: https://www.transfermarkt.com/ruben-mino/profil/spieler/65266.
Performance history data appended for: https://www.transfermarkt.com/roni/profil/spieler/348552.
Performance history data appended for: https://www.transfermarkt.com/ousama-siddiki/profil/spieler/409472.
Performance history data appended for: https://www.transfermarkt.com/iago-lopez/profil/spieler/572299.
Performance history data appended for: https://www.transfermarkt.com/mateusz-bogusz/profil/spieler/431475.
Performance history data appended for: https://www.transfermarkt.com/roberto-santamaria/profil/spieler/35541.
Performance history data appended for: https://www.transfermarkt.com/ruben-martinez/profil/spieler/65262.
Performance history data appended for: https://www.transfermarkt.com/andy-rodriguez/profil/spieler/252686.
Performance history data appended for: https://www.transfermarkt.com/jon-errasti/profil/spieler/158849.
Performance history data appended for: https://www.transfermarkt.com/martin-lapena/profil/spieler/622993.

Performance history data appended for: https://www.transfermarkt.com/rajiv-van-la-parra/profil/spieler/77001.
Performance history data appended for: https://www.transfermarkt.com/pablo-bobadilla/profil/spieler/430227.
Performance history data appended for: https://www.transfermarkt.com/ander-vitoria/profil/spieler/156864.
Performance history data appended for: https://www.transfermarkt.com/yaroslav-meykher/profil/spieler/574213.
Performance history data appended for: https://www.transfermarkt.com/andoni-lopez/profil/spieler/340206.
Performance history data appended for: https://www.transfermarkt.com/jaime-sierra/profil/spieler/398159.
Performance history data appended for: https://www.transfermarkt.com/inaki-saenz/profil/spieler/174972.
Performance history data appended for: https://www.transfermarkt.com/alvaro-arnedo/profil/spieler/412927.
Performance history data appended for: https://www.transfermarkt.com/lander-olaetxea/profil/spieler/377795.
Performance history data appended for: https://www.transfermarkt.com/paulino-de-la-fuente/profil/spieler/261502.
Performance history data appended for: https://www.transfermarkt.com/aldair-fuentes/profil/spieler/480523.
Performance history data appended for: https://www.transfermarkt.com/pol-valentin/profil/spieler/380737.
Performance history data appended for: https://www.transfermarkt.com/randy-nteka/profil/spieler/560483.
Performance history data appended for: https://www.transfermarkt.com/tahiru-awudu/profil/spieler/579649.
Performance history data appended for: https://www.transfermarkt.com/pol-freixanet/profil/spieler/200612.
Performance history data appended for: https://www.transfermarkt.com/adrian-dieguez/profil/spieler/355335.
Performance history data appended for: https://www.transfermarkt.com/dragan-rosic/profil/spieler/374055.
Performance history data appended for: https://www.transfermarkt.com/cristobal-marquez/profil/spieler/72281.
Performance history data appended for: https://www.transfermarkt.com/iban-salvador/profil/spieler/250358.
Performance history data appended for: https://www.transfermarkt.com/cristian-glauder/profil/spieler/380365.
Performance history data appended for: https://www.transfermarkt.com/alex-mula/profil/spieler/242295.
Performance history data appended for: https://www.transfermarkt.com/juanma/profil/spieler/45773.
Performance history data appended for: https://www.transfermarkt.com/ruben-pulido/profil/spieler/603969.
Performance history data appended for: https://www.transfermarkt.com/javier-belman/profil/spieler/422459.
Performance history data appended for: https://www.transfermarkt.com/moi-delgado/profil/spieler/260230.
Performance history data appended for: https://www.transfermarkt.com/alejandro-sotillos/profil/spieler/396157.
Performance history data appended for: https://www.transfermarkt.com/franchu/profil/spieler/458466.
Performance history data appended for: https://www.transfermarkt.com/sekou-gassama/profil/spieler/337070.
Performance history data appended for: https://www.transfermarkt.com/jano/profil/spieler/94096.
Performance history data appended for: https://www.transfermarkt.com/pathe-ciss/profil/spieler/525578.
Performance history data appended for: https://www.transfermarkt.com/alvaro-aguado/profil/spieler/449496.
Performance history data appended for: https://www.transfermarkt.com/aboubakary-kante/profil/spieler/315095.
Performance history data appended for: https://www.transfermarkt.com/pinchi/profil/spieler/413502.
Performance history data appended for: https://www.transfermarkt.com/mikel-iribas/profil/spieler/76276.
Performance history data appended for: https://www.transfermarkt.com/leonardo-ulloa/profil/spieler/54890.
Performance history data appended for: https://www.transfermarkt.com/emiliano-velazquez/profil/spieler/189458.
Performance history data appended for: https://www.transfermarkt.com/mario-suarez/profil/spieler/37337.
Performance history data appended for: https://www.transfermarkt.com/isi-palazon/profil/spieler/362086.
Performance history data appended for: https://www.transfermarkt.com/alvaro-garcia/profil/spieler/257062.
Performance history data appended for: https://www.transfermarkt.com/martin-pascual/profil/spieler/638588.
Performance history data appended for: https://www.transfermarkt.com/fran-garcia/profil/spieler/341264.
Performance history data appended for: https://www.transfermarkt.com/alejandro-catena/profil/spieler/449796.
Performance history data appended for: https://www.transfermarkt.com/stole-dimitrievski/profil/spieler/165467.
Performance history data appended for: https://www.transfermarkt.com/yacine-qasmi/profil/spieler/93747.
Performance history data appended for: https://www.transfermarkt.com/ivan-martos/profil/spieler/406773.
Performance history data appended for: https://www.transfermarkt.com/luis-advincula/profil/spieler/103890.
Performance history data appended for: https://www.transfermarkt.com/mario-hernandez/profil/spieler/608531.
Performance history data appended for: https://www.transfermarkt.com/alberto-garcia/profil/spieler/58497.
Performance history data appended for: https://www.transfermarkt.com/santi-comesana/profil/spieler/380598.
Performance history data appended for: https://www.transfermarkt.com/miguel-angel-morro/profil/spieler/607780.
Performance history data appended for: https://www.transfermarkt.com/esteban-saveljich/profil/spieler/240360.
Performance history data appended for: https://www.transfermarkt.com/oscar-trejo/profil/spieler/30321.
Performance history data appended for: https://www.transfermarkt.com/luca-zidane/profil/spieler/283489.
Performance history data appended for: https://www.transfermarkt.com/bebe/profil/spieler/153427.
Performance history data appended for: https://www.transfermarkt.com/andres-martin/profil/spieler/531277.
Performance history data appended for: https://www.transfermarkt.com/jose-pozo/profil/spieler/195605.
Performance history data appended for: https://www.transfermarkt.com/oscar-valentin/profil/spieler/517753.
Performance history data appended for: https://www.transfermarkt.com/antonin/profil/spieler/610336.
Performance history data appended for: https://www.transfermarkt.com/joni-montiel/profil/spieler/343273.
Performance history data appended for: https://www.transfermarkt.com/richard-boateng/profil/spieler/198400.
Performance history data appended for: https://www.transfermarkt.com/fidel-escobar/profil/spieler/345716.
Performance history data appended for: https://www.transfermarkt.com/javi-castro/profil/spieler/740253.
Performance history data appended for: https://www.transfermarkt.com/david-fernandez/profil/spieler/59371.
Performance history data appended for: https://www.transfermarkt.com/guito/profil/spieler/783879.
Performance history data appended for: https://www.transfermarkt.com/samuel-casado/profil/spieler/388888.
Performance history data appended for: https://www.transfermarkt.com/dani-jimenez/profil/spieler/126509.
Performance history data appended for: https://www.transfermarkt.com/juan-aguilera/profil/spieler/75820.
Performance history data appended for: https://www.transfermarkt.com/laure/profil/spieler/57876.
Performance history data appended for: https://www.transfermarkt.com/carlos-bellvis/profil/spieler/51550.
Performance history data appended for: https://www.transfermarkt.com/reko/profil/spieler/290262.
Performance history data appended for: https://www.transfermarkt.com/alejandro-escardo/profil/spieler/464899.
Performance history data appended for: https://www.transfermarkt.com/hugo-fraile/profil/spieler/72201.
Performance history data appended for: https://www.transfermarkt.com/jose-carlos-ramirez/profil/spieler/319541.
Performance history data appended for: https://www.transfermarkt.com/victor-garcia/profil/spieler/195762.
Performance history data appended for: https://www.transfermarkt.com/ander-gorostidi/profil/spieler/450258.
Performance history data appended for: https://www.transfermarkt.com/marc-gual/profil/spieler/376486.
Performance history data appended for: https://www.transfermarkt.com/jose-leon/profil/spieler/281773.
Performance history data appended for: https://www.transfermarkt.com/jesus-ruiz/profil/spieler/408288.

Performance history data appended for: https://www.transfermarkt.com/barbero/profil/spieler/514514.
Performance history data appended for: https://www.transfermarkt.com/oscar-arribas/profil/spieler/476104.
Performance history data appended for: https://www.transfermarkt.com/juanma-bravo/profil/spieler/475833.
Performance history data appended for: https://www.transfermarkt.com/samuel-sosa/profil/spieler/428210.
Performance history data appended for: https://www.transfermarkt.com/ernesto-gomez/profil/spieler/288460.
Performance history data appended for: https://www.transfermarkt.com/aitor-gonzalez/profil/spieler/716157.
Performance history data appended for: https://www.transfermarkt.com/dani-rodriguez/profil/spieler/139435.
Performance history data appended for: https://www.transfermarkt.com/martin-valjent/profil/spieler/277384.
Performance history data appended for: https://www.transfermarkt.com/murilo-de-souza/profil/spieler/345061.
Performance history data appended for: https://www.transfermarkt.com/jordi-mboula/profil/spieler/331498.
Performance history data appended for: https://www.transfermarkt.com/luka-romero/profil/spieler/769063.
Performance history data appended for: https://www.transfermarkt.com/miquel-parera/profil/spieler/242301.
Performance history data appended for: https://www.transfermarkt.com/fran-gamez/profil/spieler/442816.
Performance history data appended for: https://www.transfermarkt.com/aleksandar-sedlar/profil/spieler/237499.
Performance history data appended for: https://www.transfermarkt.com/alex-lopez/profil/spieler/166674.
Performance history data appended for: https://www.transfermarkt.com/iddrisu-baba/profil/spieler/442805.
Performance history data appended for: https://www.transfermarkt.com/marc-cardona/profil/spieler/443222.
Performance history data appended for: https://www.transfermarkt.com/brian-olivan/profil/spieler/166677.
Performance history data appended for: https://www.transfermarkt.com/salva-sevilla/profil/spieler/58799.
Performance history data appended for: https://www.transfermarkt.com/antonio-raillo/profil/spieler/278296.
Performance history data appended for: https://www.transfermarkt.com/braian-cufre/profil/spieler/401521.
Performance history data appended for: https://www.transfermarkt.com/aleksandar-trajkovski/profil/spieler/142920.
Performance history data appended for: https://www.transfermarkt.com/aleix-febas/profil/spieler/217144.
Performance history data appended for: https://www.transfermarkt.com/franco-russo/profil/spieler/378463.
Performance history data appended for: https://www.transfermarkt.com/antonio-sanchez/profil/spieler/513031.
Performance history data appended for: https://www.transfermarkt.com/lago-junior/profil/spieler/100722.
Performance history data appended for: https://www.transfermarkt.com/joan-sastre/profil/spieler/350364.
Performance history data appended for: https://www.transfermarkt.com/alex-alegria/profil/spieler/178187.
Performance history data appended for: https://www.transfermarkt.com/inigo-ruiz-de-galarreta/profil/spieler/126751.
Performance history data appended for: https://www.transfermarkt.com/manolo-reina/profil/spieler/29051.
Performance history data appended for: https://www.transfermarkt.com/abdon-prats/profil/spieler/177452.
Performance history data appended for: https://www.transfermarkt.com/enzo-lombardo/profil/spieler/443290.
Performance history data appended for: https://www.transfermarkt.com/amath-ndiaye/profil/spieler/339820.
Performance history data appended for: https://www.transfermarkt.com/felix-alonso/profil/spieler/751315.
Performance history data appended for: https://www.transfermarkt.com/shaq-moore/profil/spieler/336168.
Performance history data appended for: https://www.transfermarkt.com/david-rodriguez/profil/spieler/820375.
Performance history data appended for: https://www.transfermarkt.com/dani-hernandez/profil/spieler/88528.
Performance history data appended for: https://www.transfermarkt.com/nono/profil/spieler/152776.
Performance history data appended for: https://www.transfermarkt.com/fran-sol/profil/spieler/164292.
Performance history data appended for: https://www.transfermarkt.com/otar-kakabadze/profil/spieler/214250.
Performance history data appended for: https://www.transfermarkt.com/giovanni-zarfino/profil/spieler/208022.
Performance history data appended for: https://www.transfermarkt.com/nikola-sipcic/profil/spieler/311146.
Performance history data appended for: https://www.transfermarkt.com/jacobo-gonzalez/profil/spieler/340870.
Performance history data appended for: https://www.transfermarkt.com/emmanuel-apeh/profil/spieler/463332.
Performance history data appended for: https://www.transfermarkt.com/ramon-folch/profil/spieler/286841.
Performance history data appended for: https://www.transfermarkt.com/borja-lasso/profil/spieler/268949.
Performance history data appended for: https://www.transfermarkt.com/joselu/profil/spieler/143044.
Performance history data appended for: https://www.transfermarkt.com/carlos-ruiz/profil/spieler/72421.
Performance history data appended for: https://www.transfermarkt.com/suso-santana/profil/spieler/51522.
Performance history data appended for: https://www.transfermarkt.com/bruno-wilson/profil/spieler/71830.
Performance history data appended for: https://www.transfermarkt.com/adrian-ortola/profil/spieler/142033.
Performance history data appended for: https://www.transfermarkt.com/jorge-padilla/profil/spieler/726030.
Performance history data appended for: https://www.transfermarkt.com/alex-bermejo/profil/spieler/473695.
Performance history data appended for: https://www.transfermarkt.com/alex-munoz/profil/spieler/243760.
Performance history data appended for: https://www.transfermarkt.com/victor-mendez/profil/spieler/814995.
Performance history data appended for: https://www.transfermarkt.com/alberto-jimenez/profil/spieler/265289.
Performance history data appended for: https://www.transfermarkt.com/samuel-shashoua/profil/spieler/387313.
Performance history data appended for: https://www.transfermarkt.com/aitor-sanz/profil/spieler/71834.
Performance history data appended for: https://www.transfermarkt.com/dylan/profil/spieler/840794.
Performance history data appended for: https://www.transfermarkt.com/valentin-vada/profil/spieler/225004.
Performance history data appended for: https://www.transfermarkt.com/carlos-pomares/profil/spieler/238872.
Performance history data appended for: https://www.transfermarkt.com/samu-saiz/profil/spieler/131506.
Performance history data appended for: https://www.transfermarkt.com/juan-carlos/profil/spieler/120705.
Performance history data appended for: https://www.transfermarkt.com/pau-victor/profil/spieler/707572.
Performance history data appended for: https://www.transfermarkt.com/aday/profil/spieler/132921.
Performance history data appended for: https://www.transfermarkt.com/arijanet-muric/profil/spieler/371021.
Performance history data appended for: https://www.transfermarkt.com/yan-couto/profil/spieler/627228.
Performance history data appended for: https://www.transfermarkt.com/pablo-moreno/profil/spieler/466811.
Performance history data appended for: https://www.transfermarkt.com/antonio-luna/profil/spieler/126516.
Performance history data appended for: https://www.transfermarkt.com/valery-fernandez/profil/spieler/331496.
Performance history data appended for: https://www.transfermarkt.com/ramon-terrats/profil/spieler/783396.
Performance history data appended for: https://www.transfermarkt.com/jordi-calavera/profil/spieler/286849.
Performance history data appended for: https://www.transfermarkt.com/cristhian-stuani/profil/spieler/59323.
Performance history data appended for: https://www.transfermarkt.com/mamadou-sylla/profil/spieler/166683.
Performance history data appended for: https://www.transfermarkt.com/jose-aurelio-suarez/profil/spieler/223720.
Performance history data appended for: https://www.transfermarkt.com/gerard-gumbau/profil/spieler/268670.
Performance history data appended for: https://www.transfermarkt.com/nahuel-bustos/profil/spieler/439629.
Performance history data appended for: https://www.transfermarkt.com/alex-pachon/profil/spieler/533110.

Performance history data appended for: https://www.transfermarkt.com/santiago-bueno/profil/spieler/438001.
Performance history data appended for: https://www.transfermarkt.com/enric-franquesa/profil/spieler/282700.
Performance history data appended for: https://www.transfermarkt.com/yoel-barcenas/profil/spieler/283473.
Performance history data appended for: https://www.transfermarkt.com/ibrahima-kebe/profil/spieler/785967.
Performance history data appended for: https://www.transfermarkt.com/jonas-ramalho/profil/spieler/69660.
Performance history data appended for: https://www.transfermarkt.com/sebastian-cristoforo/profil/spieler/188157.
Performance history data appended for: https://www.transfermarkt.com/bernardo-espinosa/profil/spieler/64598.
Performance history data appended for: https://www.transfermarkt.com/monchu/profil/spieler/282727.
Performance history data appended for: https://www.transfermarkt.com/juanpe/profil/spieler/115333.
Performance history data appended for: https://www.transfermarkt.com/bernabe-barragan/profil/spieler/254036.
Performance history data appended for: https://www.transfermarkt.com/ivan-kecojevic/profil/spieler/69005.
Performance history data appended for: https://www.transfermarkt.com/javi-navarro/profil/spieler/682500.
Performance history data appended for: https://www.transfermarkt.com/pape-maly-diamanka/profil/spieler/176610.
Performance history data appended for: https://www.transfermarkt.com/alberto-benito/profil/spieler/263748.
Performance history data appended for: https://www.transfermarkt.com/karim-azamoum/profil/spieler/275361.
Performance history data appended for: https://www.transfermarkt.com/fran-garcia/profil/spieler/152284.
Performance history data appended for: https://www.transfermarkt.com/david-del-pozo/profil/spieler/372050.
Performance history data appended for: https://www.transfermarkt.com/flavien-boyomo/profil/spieler/541555.
Performance history data appended for: https://www.transfermarkt.com/eddy-silvestre/profil/spieler/238865.
Performance history data appended for: https://www.transfermarkt.com/javi-jimenez/profil/spieler/251860.
Performance history data appended for: https://www.transfermarkt.com/carlos-isaac/profil/spieler/396324.
Performance history data appended for: https://www.transfermarkt.com/nicolas-gorosito/profil/spieler/125281.
Performance history data appended for: https://www.transfermarkt.com/diego-caballo/profil/spieler/162036.
Performance history data appended for: https://www.transfermarkt.com/alvaro-pena/profil/spieler/156887.
Performance history data appended for: https://www.transfermarkt.com/manu-fuster/profil/spieler/511021.
Performance history data appended for: https://www.transfermarkt.com/roman-zozulya/profil/spieler/70767.
Performance history data appended for: https://www.transfermarkt.com/alvaro-arroyo/profil/spieler/138662.
Performance history data appended for: https://www.transfermarkt.com/chema-nunez/profil/spieler/434660.
Performance history data appended for: https://www.transfermarkt.com/alvaro-jimenez/profil/spieler/282406.
Performance history data appended for: https://www.transfermarkt.com/emiliano-gomez/profil/spieler/577489.
Performance history data appended for: https://www.transfermarkt.com/tomeu-nadal/profil/spieler/88397.
Performance history data appended for: https://www.transfermarkt.com/alfredo-ortuno/profil/spieler/96540.
Performance history data appended for: https://www.transfermarkt.com/jean-jules/profil/spieler/607377.
Performance history data appended for: https://www.transfermarkt.com/nahuel-arroyo/profil/spieler/681708.
Performance history data appended for: https://www.transfermarkt.com/liberto-beltran/profil/spieler/355763.
Performance history data appended for: https://www.transfermarkt.com/angel-fortuno/profil/spieler/628487.
Performance history data appended for: https://www.transfermarkt.com/adrian-embarba/profil/spieler/288318.
Performance history data appended for: https://www.transfermarkt.com/lluis-lopez/profil/spieler/262391.
Performance history data appended for: https://www.transfermarkt.com/pol-lozano/profil/spieler/412045.
Performance history data appended for: https://www.transfermarkt.com/leandro-cabrera/profil/spieler/102423.
Performance history data appended for: https://www.transfermarkt.com/alex-lopez/profil/spieler/313113.
Performance history data appended for: https://www.transfermarkt.com/adria-pedrosa/profil/spieler/501418.
Performance history data appended for: https://www.transfermarkt.com/david-lopez/profil/spieler/129444.
Performance history data appended for: https://www.transfermarkt.com/lei-wu/profil/spieler/140436.
Performance history data appended for: https://www.transfermarkt.com/nico-melamed/profil/spieler/570421.
Performance history data appended for: https://www.transfermarkt.com/fernando-calero/profil/spieler/357884.
Performance history data appended for: https://www.transfermarkt.com/didac-vila/profil/spieler/67090.
Performance history data appended for: https://www.transfermarkt.com/oier-olazabal/profil/spieler/8176.
Performance history data appended for: https://www.transfermarkt.com/diego-lopez/profil/spieler/34370.
Performance history data appended for: https://www.transfermarkt.com/oscar-melendo/profil/spieler/448344.
Performance history data appended for: https://www.transfermarkt.com/victor-campuzano/profil/spieler/394285.
Performance history data appended for: https://www.transfermarkt.com/javi-puado/profil/spieler/408471.
Performance history data appended for: https://www.transfermarkt.com/keidi-bare/profil/spieler/295622.
Performance history data appended for: https://www.transfermarkt.com/matias-vargas/profil/spieler/376211.
Performance history data appended for: https://www.transfermarkt.com/fran-merida/profil/spieler/42920.
Performance history data appended for: https://www.transfermarkt.com/raul-de-tomas/profil/spieler/162038.
Performance history data appended for: https://www.transfermarkt.com/alvaro-vadillo/profil/spieler/162074.
Performance history data appended for: https://www.transfermarkt.com/sergi-darder/profil/spieler/142021.
Performance history data appended for: https://www.transfermarkt.com/jofre-carreras/profil/spieler/628498.
Performance history data appended for: https://www.transfermarkt.com/oscar-gil/profil/spieler/544106.
Performance history data appended for: https://www.transfermarkt.com/miguelon/profil/spieler/399775.
Performance history data appended for: https://www.transfermarkt.com/borja-dominguez/profil/spieler/287193.
Performance history data appended for: https://www.transfermarkt.com/juanpe/profil/spieler/455066.
Performance history data appended for: https://www.transfermarkt.com/frederico-venancio/profil/spieler/169681.
Performance history data appended for: https://www.transfermarkt.com/diego-alende/profil/spieler/373683.
Performance history data appended for: https://www.transfermarkt.com/fran-vieites/profil/spieler/551182.
Performance history data appended for: https://www.transfermarkt.com/luis-ruiz/profil/spieler/286020.
Performance history data appended for: https://www.transfermarkt.com/fernando-seoane/profil/spieler/70988.
Performance history data appended for: https://www.transfermarkt.com/ander-cantero/profil/spieler/199325.
Performance history data appended for: https://www.transfermarkt.com/pedro-lopez/profil/spieler/365311.
Performance history data appended for: https://www.transfermarkt.com/iriome-gonzalez/profil/spieler/51519.
Performance history data appended for: https://www.transfermarkt.com/gerard-valentin/profil/spieler/278651.
Performance history data appended for: https://www.transfermarkt.com/el-hacen/profil/spieler/321629.
Performance history data appended for: https://www.transfermarkt.com/anton-quindimil/profil/spieler/781924.
Performance history data appended for: https://www.transfermarkt.com/hugo-rama/profil/spieler/510329.
Performance history data appended for: https://www.transfermarkt.com/alberto-varo/profil/spieler/280254.
Performance history data appended for: https://www.transfermarkt.com/marcelo-djalo/profil/spieler/142022.
Performance history data appended for: https://www.transfermarkt.com/jose-angel-carrillo/profil/spieler/308982.

Performance history data appended for: https://www.transfermarkt.com/manu-barreiro/profil/spieler/72484.
Performance history data appended for: https://www.transfermarkt.com/chris-ramos/profil/spieler/538810.
Performance history data appended for: https://www.transfermarkt.com/carlos-pita/profil/spieler/34566.
Performance history data appended for: https://www.transfermarkt.com/jose-luis-rodriguez/profil/spieler/425028.
Performance history data appended for: https://www.transfermarkt.com/xavi-torres/profil/spieler/65301.
Performance history data appended for: https://www.transfermarkt.com/edu-campabadal/profil/spieler/126722.
Performance history data appended for: https://www.transfermarkt.com/cristian-herrera/profil/spieler/237617.
Performance history data appended for: https://www.transfermarkt.com/roberto-canella/profil/spieler/57785.
Performance history data appended for: https://www.transfermarkt.com/manu-garcia/profil/spieler/277118.
Performance history data appended for: https://www.transfermarkt.com/nikola-cumic/profil/spieler/368982.
Performance history data appended for: https://www.transfermarkt.com/alvaro-vazquez/profil/spieler/141835.
Performance history data appended for: https://www.transfermarkt.com/alex-zalaya/profil/spieler/335226.
Performance history data appended for: https://www.transfermarkt.com/pedro-diaz/profil/spieler/363057.
Performance history data appended for: https://www.transfermarkt.com/marc-valiente/profil/spieler/53301.
Performance history data appended for: https://www.transfermarkt.com/jose-gragera/profil/spieler/557147.
Performance history data appended for: https://www.transfermarkt.com/aitor-garcia/profil/spieler/214468.
Performance history data appended for: https://www.transfermarkt.com/christian-sanchez/profil/spieler/531373.
Performance history data appended for: https://www.transfermarkt.com/cristian-salvador/profil/spieler/224774.
Performance history data appended for: https://www.transfermarkt.com/gaspar-campos/profil/spieler/580525.
Performance history data appended for: https://www.transfermarkt.com/uros-djurdjevic/profil/spieler/190804.
Performance history data appended for: https://www.transfermarkt.com/bogdan-milovanov/profil/spieler/392655.
Performance history data appended for: https://www.transfermarkt.com/diego-marino/profil/spieler/59349.
Performance history data appended for: https://www.transfermarkt.com/borja-lopez/profil/spieler/214770.
Performance history data appended for: https://www.transfermarkt.com/pablo-perez/profil/spieler/238717.
Performance history data appended for: https://www.transfermarkt.com/saul-garcia/profil/spieler/249471.
Performance history data appended for: https://www.transfermarkt.com/jean-sylvain-babin/profil/spieler/45256.
Performance history data appended for: https://www.transfermarkt.com/nacho-mendez/profil/spieler/503837.
Performance history data appended for: https://www.transfermarkt.com/neftali-manzambi/profil/spieler/211453.
Performance history data appended for: https://www.transfermarkt.com/pelayo-suarez/profil/spieler/311665.
Performance history data appended for: https://www.transfermarkt.com/javi-fuego/profil/spieler/56134.
Performance history data appended for: https://www.transfermarkt.com/pablo-garcia/profil/spieler/636300.
Performance history data appended for: https://www.transfermarkt.com/carlos-carmona/profil/spieler/71394.
Performance history data appended for: https://www.transfermarkt.com/gus-ledes/profil/spieler/139352.
Performance history data appended for: https://www.transfermarkt.com/victor-garcia/profil/spieler/281588.
Performance history data appended for: https://www.transfermarkt.com/ruben-diez/profil/spieler/311266.
Performance history data appended for: https://www.transfermarkt.com/jorge-fernandez/profil/spieler/222667.
Performance history data appended for: https://www.transfermarkt.com/josep-sene/profil/spieler/161267.
Performance history data appended for: https://www.transfermarkt.com/alvaro-campos/profil/spieler/73157.
Performance history data appended for: https://www.transfermarkt.com/marc-mateu/profil/spieler/96539.
Performance history data appended for: https://www.transfermarkt.com/alvaro-fidalgo/profil/spieler/261503.
Performance history data appended for: https://www.transfermarkt.com/eneko-satrustegui/profil/spieler/158792.
Performance history data appended for: https://www.transfermarkt.com/inigo-munoz/profil/spieler/442767.
Performance history data appended for: https://www.transfermarkt.com/francisco-regalon/profil/spieler/71994.
Performance history data appended for: https://www.transfermarkt.com/joseba-muguruza/profil/spieler/229811.
Performance history data appended for: https://www.transfermarkt.com/jesus-carrillo/profil/spieler/464900.
Performance history data appended for: https://www.transfermarkt.com/alejandro-marcos/profil/spieler/617052.
Performance history data appended for: https://www.transfermarkt.com/arturo-molina/profil/spieler/337781.
Performance history data appended for: https://www.transfermarkt.com/cesar-diaz/profil/spieler/51632.
Performance history data appended for: https://www.transfermarkt.com/rafa-galvez/profil/spieler/288454.
Performance history data appended for: https://www.transfermarkt.com/igor-zlatanovic/profil/spieler/343965.
Performance history data appended for: https://www.transfermarkt.com/iago-indias/profil/spieler/356196.
Performance history data appended for: https://www.transfermarkt.com/marc-castells/profil/spieler/73137.
Performance history data appended for: https://www.transfermarkt.com/guillem-jaime/profil/spieler/331508.
Performance history data appended for: https://www.transfermarkt.com/juanto-ortuno/profil/spieler/213875.
Performance history data appended for: https://www.transfermarkt.com/paolo-fernandes/profil/spieler/284876.
Performance history data appended for: https://www.transfermarkt.com/oscar-whalley/profil/spieler/260662.
Performance history data appended for: https://www.transfermarkt.com/david-cubillas/profil/spieler/128816.
Performance history data appended for: https://www.transfermarkt.com/adrian-lapena/profil/spieler/289267.
Performance history data appended for: https://www.transfermarkt.com/jordi-sanchez/profil/spieler/291693.
Performance history data appended for: https://www.transfermarkt.com/carles-salvador/profil/spieler/217730.
Performance history data appended for: https://www.transfermarkt.com/carlos-delgado/profil/spieler/175773.
Performance history data appended for: https://www.transfermarkt.com/alvaro-tejero/profil/spieler/290273.
Performance history data appended for: https://www.transfermarkt.com/francho-serrano/profil/spieler/632930.
Performance history data appended for: https://www.transfermarkt.com/haris-vuckic/profil/spieler/76560.
Performance history data appended for: https://www.transfermarkt.com/carlos-vigaray/profil/spieler/263627.
Performance history data appended for: https://www.transfermarkt.com/jannick-buyla/profil/spieler/525891.
Performance history data appended for: https://www.transfermarkt.com/rai-nascimento/profil/spieler/483499.
Performance history data appended for: https://www.transfermarkt.com/giorgi-papunashvili/profil/spieler/214259.
Performance history data appended for: https://www.transfermarkt.com/juanjo-narvaez/profil/spieler/213595.
Performance history data appended for: https://www.transfermarkt.com/james-igbekeme/profil/spieler/375849.
Performance history data appended for: https://www.transfermarkt.com/gaizka-larrazabal/profil/spieler/439465.
Performance history data appended for: https://www.transfermarkt.com/javi-ros/profil/spieler/89330.
Performance history data appended for: https://www.transfermarkt.com/inigo-eguaras/profil/spieler/89731.
Performance history data appended for: https://www.transfermarkt.com/sergio-bermejo/profil/spieler/372051.

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Performance history data appended for: https://www.transfermarkt.com/alvaro-raton/profil/spieler/248551.
Performance history data appended for: https://www.transfermarkt.com/jair-amador/profil/spieler/128479.
Performance history data appended for: https://www.transfermarkt.com/ivan-azon/profil/spieler/633306.
Performance history data appended for: https://www.transfermarkt.com/pichu-atienza/profil/spieler/59337.
Performance history data appended for: https://www.transfermarkt.com/alberto-zapater/profil/spieler/26153.
Performance history data appended for: https://www.transfermarkt.com/javi-hernandez/profil/spieler/632893.
Performance history data appended for: https://www.transfermarkt.com/carlos-nieto/profil/spieler/340682.
Performance history data appended for: https://www.transfermarkt.com/cristian-alvarez/profil/spieler/55135.
Performance history data appended for: https://www.transfermarkt.com/gabriel-fernandez/profil/spieler/259930.
Performance history data appended for: https://www.transfermarkt.com/pep-chavarria/profil/spieler/596122.
Performance history data appended for: https://www.transfermarkt.com/adrian-gonzalez/profil/spieler/44073.
Performance history data appended for: https://www.transfermarkt.com/alejandro-frances/profil/spieler/632896.
Performance history data appended for: https://www.transfermarkt.com/luca-zanimacchia/profil/spieler/407265.
Performance history data appended for: https://www.transfermarkt.com/alberto-guitian/profil/spieler/230895.
Performance history data appended for: https://www.transfermarkt.com/borjas-martin/profil/spieler/334850.
Performance history data appended for: https://www.transfermarkt.com/lucas-kaufmann/profil/spieler/241358.
Performance history data appended for: https://www.transfermarkt.com/macoumba-kandji/profil/spieler/59755.
Performance history data appended for: https://www.transfermarkt.com/konsta-rasimus/profil/spieler/97536.
Performance history data appended for: https://www.transfermarkt.com/edmund-arko-mensah/profil/spieler/543492.
Performance history data appended for: https://www.transfermarkt.com/dani-hatakka/profil/spieler/172291.
Performance history data appended for: https://www.transfermarkt.com/tapio-heikkila/profil/spieler/47957.
Performance history data appended for: https://www.transfermarkt.com/jerry-voutilainen/profil/spieler/190456.
Performance history data appended for: https://www.transfermarkt.com/javi-hervas/profil/spieler/184218.
Performance history data appended for: https://www.transfermarkt.com/duarte-tammilehto/profil/spieler/108584.
Performance history data appended for: https://www.transfermarkt.com/henri-aalto/profil/spieler/73722.
Performance history data appended for: https://www.transfermarkt.com/markus-uusitalo/profil/spieler/296271.
Performance history data appended for: https://www.transfermarkt.com/jonas-levanen/profil/spieler/261081.
Performance history data appended for: https://www.transfermarkt.com/jean-marie-dongou/profil/spieler/166666.
Performance history data appended for: https://www.transfermarkt.com/tim-murray/profil/spieler/148169.
Performance history data appended for: https://www.transfermarkt.com/eero-tamminen/profil/spieler/236742.
Performance history data appended for: https://www.transfermarkt.com/diogo-tomas/profil/spieler/354476.
Performance history data appended for: https://www.transfermarkt.com/naatan-skytta/profil/spieler/567309.
Performance history data appended for: https://www.transfermarkt.com/tuure-mantynen/profil/spieler/356291.
Performance history data appended for: https://www.transfermarkt.com/jair/profil/spieler/432742.
Performance history data appended for: https://www.transfermarkt.com/joona-veteli/profil/spieler/226330.
Performance history data appended for: https://www.transfermarkt.com/juho-pietola/profil/spieler/592877.
Performance history data appended for: https://www.transfermarkt.com/doni-arifi/profil/spieler/563841.
Performance history data appended for: https://www.transfermarkt.com/lauri-ala-myllymaki/profil/spieler/270515.
Performance history data appended for: https://www.transfermarkt.com/tatu-miettunen/profil/spieler/325450.
Performance history data appended for: https://www.transfermarkt.com/felipe-aspegren/profil/spieler/224694.
Performance history data appended for: https://www.transfermarkt.com/mika-hilander/profil/spieler/46911.
Performance history data appended for: https://www.transfermarkt.com/mikael-almen/profil/spieler/564320.
Performance history data appended for: https://www.transfermarkt.com/eemeli-raittinen/profil/spieler/581453.
Performance history data appended for: https://www.transfermarkt.com/eetu-mommo/profil/spieler/592879.
Performance history data appended for: https://www.transfermarkt.com/ilari-mettala/profil/spieler/273266.
Performance history data appended for: https://www.transfermarkt.com/tuure-siira/profil/spieler/188475.
Performance history data appended for: https://www.transfermarkt.com/arlind-sejdiu/profil/spieler/488780.
Scraping ended at: 2020-12-07 15:54:46.649223
Time taken to scrape the performance data of the 21,940 players for the 2020/2021 season is: 225.37 minutes.

In [13]:
# Display DataFrame
df_performance.head()

,season,competition,competition_code,club,in_squad,appearances,ppg,goals,assists,subbed_on,subbed_off,yellow_card,second_yellow_card,red_card,penalties,mins_played,clean_sheets,goals_conceded,player_id,age
0,2020/2021,Bundesliga,A1,Austria Vienna,10,9,1.11,0,0,0,0,1,0,0,0,810,0,0,282199,23
1,2020/2021,ÖFB-Cup,ofb,Austria Vienna,1,1,3.00,0,0,0,0,1,0,0,0,90,0,0,282199,23
2,2020/2021,Bundesliga EL-Play-off,A1EL,Austria Vienna,3,3,1.33,0,0,0,0,0,0,0,0,270,0,0,282199,22
3,2020/2021,Bundesliga,A1,Austria Vienna,23,22,1.59,2,1,3,2,2,0,1,0,1773,0,0,282199,22
4,2020/2021,ÖFB-Cup,ofb,Austria Vienna,1,1,0.00,0,0,0,1,0,0,0,0,68,0,0,282199,22

In [14]:
df_performance.shape

(58581, 20)

##### Export DataFrame

In [15]:
# Export DataFrame as a CSV file

## Export a copy to the 'archive' subfolder of the TM folder, including the date
df_performance.to_csv(data_dir_tm + f'/raw/{short_season_string}/performance/' + f'tm_player_th_all_{short_season_string}_last_updated_{today}.csv', index=None, header=True)

## Export another copy to the TM folder called 'latest' (can be overwritten)
df_performance.to_csv(data_dir_tm + f'/raw/{short_season_string}/performance/archive/' + f'tm_player_th_all_{short_season_string}_latest.csv', index=None, header=True)

#### <a id='#section3.3.7.'>3.3.7. Market Value History</a>

In [16]:
# Run this script to scrape latest version of market value history data from TransferMarkt

## Start timer
tic = datetime.datetime.now()

## Create empty list
lst_df_value_history = []

## Print time scraping started
print(f'Scraping started at: {tic}')

## Scrape bio information for each player
for player_page in lst_player_urls:
    try:
        dict_output = tm_pull(player_page, market_value_history=True, output='pandas')
        df = dict_output['market_value_history']
        lst_df_value_history.append(df)
        print(f'Market value history data appended for: {player_page}.')
    except:
        pass

## Concatenate DataFrames
df_value_history = pd.concat(lst_df_value_history)

## Print time scraping ended
print(f'Scraping ended at: {toc}')

## Create attribute for the season    
df_value_history['season'] = full_season_string

## End timer
toc = datetime.datetime.now()

## Calculate time take
total_time = (toc-tic).total_seconds()
print(f'Time taken to scrape the market value history data of the {len_player_urls:,} players for the {full_season_string} season is: {total_time/60:0.2f} minutes.')

Scraping started at: 2020-12-07 19:40:09.839975
Scraping ended at: 2020-12-07 19:40:08.960476
Time taken to scrape the market value history data of the 21,940 players for the 2020/2021 season is: 0.90 minutes.

In [17]:
# Display DataFrame
df_value_history.head()

,season,competition,competition_code,club,in_squad,appearances,ppg,goals,assists,subbed_on,subbed_off,yellow_card,second_yellow_card,red_card,penalties,mins_played,clean_sheets,goals_conceded,player_id,age
0,2020/2021,Bundesliga,A1,Austria Vienna,10,9,1.11,0,0,0,0,1,0,0,0,810,0,0,282199,23
1,2020/2021,ÖFB-Cup,ofb,Austria Vienna,1,1,3.00,0,0,0,0,1,0,0,0,90,0,0,282199,23
2,2020/2021,Bundesliga EL-Play-off,A1EL,Austria Vienna,3,3,1.33,0,0,0,0,0,0,0,0,270,0,0,282199,22
3,2020/2021,Bundesliga,A1,Austria Vienna,23,22,1.59,2,1,3,2,2,0,1,0,1773,0,0,282199,22
4,2020/2021,ÖFB-Cup,ofb,Austria Vienna,1,1,0.00,0,0,0,1,0,0,0,0,68,0,0,282199,22

In [18]:
df_value_history.shape

(58581, 20)

##### Export DataFrame

In [20]:
# Export DataFrame as a CSV file

## Export a copy to the 'archive' subfolder of the TM folder, including the date
df_value_history.to_csv(data_dir_tm + f'/raw/{short_season_string}/market-value-history/archive/' + f'tm_player_th_all_{short_season_string}_last_updated_{today}.csv', index=None, header=True)

## Export another copy to the TM folder called 'latest' (can be overwritten)
df_value_history.to_csv(data_dir_tm + f'/raw/{short_season_string}/market-value-history/' + f'tm_player_th_all_{short_season_string}_latest.csv', index=None, header=True)

#### <a id='#section3.3.8.'>3.3.8. Join Individual DataFrames</a>

##### Bio and Status data

In [ ]:
# Join the Bio and Status DataFrames to form one, unified DataFrame
df_tm_bio_status = pd.merge(df_bio, df_status, left_on='player_id', right_on='player_id', how='left')

In [ ]:
# Display DataFrame
df_tm_bio_status

In [ ]:
df_tm_bio_status.shape

In [ ]:
# Export DataFrame as a CSV file

## Export a copy to the 'archive' subfolder of the TM folder, including the date
df_tm_bio_status.to_csv(data_dir_tm + f'/raw/{short_season_string}/joined/' + f'tm_bio_status_{short_season_string}_last_updated_{today}.csv', index=None, header=True)

## Export another copy to the TM folder called 'latest' (can be overwritten)
df_tm_bio_status.to_csv(data_dir_tm + f'/raw/{short_season_string}/joined/archive/' + f'tm_bio_status_{short_season_string}_latest.csv', index=None, header=True)

##### Bio, Status, and Transfer History data

In [ ]:
# Join the Bio and Status DataFrames to form one, unified DataFrame
df_tm_bio_status_th = pd.merge(df_tm_bio_status, df_th, left_on='player_id', right_on='player_id', how='left')

In [ ]:
# Display DataFrame
df_tm_bio_status_th

In [ ]:
df_tm_bio_status_th.shape

In [ ]:
# Export DataFrame as a CSV file

## Export a copy to the 'archive' subfolder of the TM folder, including the date
df_tm_bio_status_th.to_csv(data_dir_tm + f'/raw/{short_season_string}/joined/' + f'tm_bio_status_th_{short_season_string}_last_updated_{today}.csv', index=None, header=True)

## Export another copy to the TM folder called 'latest' (can be overwritten)
df_tm_bio_status_th.to_csv(data_dir_tm + f'/raw/{short_season_string}/joined/archive/' + f'tm_bio_status_th_{short_season_string}_latest.csv', index=None, header=True)

##### Bio, Status, and Performance History data

In [ ]:
# Join the Bio and Status DataFrames to form one, unified DataFrame
df_tm_bio_status_performance = pd.merge(df_tm_bio_status, df_performance, left_on='player_id', right_on='player_id', how='left')

In [ ]:
# Display DataFrame
df_tm_bio_status_performance

In [ ]:
df_tm_bio_status_performance.shape

In [ ]:
# Export DataFrame as a CSV file

## Export a copy to the 'archive' subfolder of the TM folder, including the date
df_tm_bio_status_performance.to_csv(data_dir_tm + f'/raw/{short_season_string}/joined/' + f'tm_bio_status_performance_{short_season_string}_last_updated_{today}.csv', index=None, header=True)

## Export another copy to the TM folder called 'latest' (can be overwritten)
df_tm_bio_status_performance.to_csv(data_dir_tm + f'/raw/{short_season_string}/joined/archive/' + f'tm_bio_status_performance_{short_season_string}_latest.csv', index=None, header=True)

##### Bio, Status, and Market Value History data

In [ ]:
# Join the Bio and Status DataFrames to form one, unified DataFrame
df_tm_bio_status_value_history = pd.merge(df_tm_bio_status, df_value_history, left_on='player_id', right_on='player_id', how='left')

In [ ]:
# Display DataFrame
df_tm_bio_status_value_history

In [ ]:
df_tm_bio_status_value_history.shape

In [ ]:
# Export DataFrame as a CSV file

## Export a copy to the 'archive' subfolder of the TM folder, including the date
df_tm_bio_status_value_history.to_csv(data_dir_tm + f'/raw/{short_season_string}/joined/' + f'tm_bio_status_value_history_{short_season_string}_last_updated_{today}.csv', index=None, header=True)

## Export another copy to the TM folder called 'latest' (can be overwritten)
df_tm_bio_status_value_history.to_csv(data_dir_tm + f'/raw/{short_season_string}/joined/archive/' + f'tm_bio_status_value_history_{short_season_string}_latest.csv', index=None, header=True)

## <a id='#section4'>4. Summary</a>
This notebook scrapes data from [TransferMarkt](https://www.transfermarkt.co.uk/) using [Beautifulsoup](https://pypi.org/project/beautifulsoup4/) and the [Tyrone Mings web scraper](https://github.com/FCrSTATS/tyrone_mings) by [FCrSTATS](https://twitter.com/FC_rstats). This landed data is then manipulated as DataFrames using [pandas](http://pandas.pydata.org/).

This data includes Bio and Status data, as well as Transfer History, Performance History and Market Value History data.

## <a id='#section5'>5. Next Steps</a>
The next step is to take this data and engineer it so that it's ready for analysis and to be matched against other data source.

## <a id='#section6'>6. References</a>

#### Data and Web Scraping
*    [tyrone_mings GitHub repository](https://github.com/FCrSTATS/tyrone_mings) by [FCrSTATS](https://github.com/FCrSTATS)
*    [Python Package Index (PyPI) tyrone-mings library](https://pypi.org/project/tyrone-mings/)
*    [Beyond crowd judgments: Data-driven estimation of market value in association football](https://www.sciencedirect.com/science/article/pii/S0377221717304332) by Oliver Müllera, Alexander Simons, and Markus Weinmann.
*    [06/04/2020: BBC - Premier League squads 'drop £1.6bn in value'](https://www.bbc.co.uk/sport/football/52221463).

---

***Visit my website [EddWebster.com](https://www.eddwebster.com) or my [GitHub Repository](https://github.com/eddwebster) for more projects. If you'd like to get in contact, my Twitter handle is [@eddwebster](http://www.twitter.com/eddwebster) and my email is: edd.j.webster@gmail.com.***

[Back to the top](#top)